- src/dtx/dtx_common.c
- src/dtx/dtx_rpc.c
- src/include/daos_srv/vos.h
- src/object/srv_obj.c
- src/vos/vos_dtx.c
It is possible that some DTX on non-leader is blocked by long time bulk data transfer or DTX refresh, as to related RPC from DTX leader to non-leader for current operation get timeout, and then the DTX may be aborted by the DTX leader before current DTX complete on the non-leader locally. Under such case, the non-leader should break the operation for current DTX.
> DAOS-11685 dtx: handle DTX abort by race

- docs/testing/ior.md
fix hrefs to DAOS 2.0 docs
Doc-only: true
> DAOS-11633 doc: fix hrefs to DAOS 2.0 docs (#10584)

- docs/admin/pool_operations.md
- docs/user/container.md
document that ec_cell_sz changed from 1MiB to 64kiB in DAOS 2.2
provide better guidance how to select the optimal EC cell size
Doc-only: true
>  DAOS-11674 doc: document default EC cell size change in DAOS 2.2 (#10583) 

- docs/admin/hardware.md
fix ucx link typo
Doc-only: true
> DAOS-11462 doc: fix typo (#10608)

- docs/overview/fault.md
- docs/overview/use_cases.md
- src/client/kv/README.md
- src/control/cmd/daos_server/README.md
- src/include/daos_obj_class.h
- src/object/README.md
DAOS-11696 doc: clarify wording of pool map version exchange
Clients detect pool map changes by passing their version to servers with
every RPC.
Signed-off-by: Ted Anderson <nonzero@google.com>
> DAOS-11696 doc: clarify wording of pool map version exchange

- src/control/server/server.go
- src/control/server/server_utils.go
- src/control/server/server_utils_test.go
In environments where access_points hostnames can resolve
to multiple IP addresses in a nondeterministic manner, we
can run into problems due to MS peers not recognizing each
other. This patch works around the problem by pinning each
replica to the lowest IP address in the set of addresses
associated with each replica's hostname.
> DAOS-11796 control: Consistently resolve MS replica addresses

- src/tests/ftest/cart/test_multisend_client.c
- src/tests/ftest/cart/test_multisend_common.h
Cleanup and coverity fixes for a multi-send client/server.
Added an option to force RPCs to be forced to a fixed target.
> DAOS-11901 test: Cleanup and coverity fixes for multi-send

- src/control/fault/code/codes.go
- src/control/server/faults.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
If the pool create request has specified more ranks than are
available in the system, reject it.
> DAOS-11740 control: Reject invalid number of pool create ranks (#10444)

- src/control/cmd/daos_server/command_test.go
- src/control/cmd/daos_server/main.go
Move the privileged helper check to a pre-exec list that is run in
the command processor. Allows certain commands (e.g. version) to
bypass installation sanity checks with minimal code and unit
test changes.
> DAOS-11755 control: Allow daos_server to show version/help without helper (#10528)

- src/control/cmd/daos_agent/config.go
- src/control/cmd/daos_agent/config_test.go
- src/control/cmd/daos_agent/fabric.go
- src/control/cmd/daos_agent/fabric_test.go
- src/control/cmd/daos_agent/infocache.go
- src/control/cmd/daos_agent/infocache_test.go
- src/control/cmd/daos_agent/start.go
- src/control/common/collection_utils.go
- src/control/common/collection_utils_test.go
- src/tests/ftest/harness/config.py
- src/tests/ftest/harness/config.yaml
- src/tests/ftest/util/agent_utils_params.py
- utils/config/daos_agent.yml
Note that this backport PR includes both the initial implementation and a functional test added by @daltonbohning.
The cherry-pick of #10445 wasn't clean due to differences between master and release/2.2.
> DAOS-11664 agent: Add config option to ignore interfaces (#10445)

- src/control/lib/hardware/sysfs/provider.go
- src/control/lib/hardware/sysfs/provider_test.go
Infiniband pkey devices link to their parent device differently than other virtual net devices do. This patch updates both the IB status detection and topology detection to associate the pkey device to its Infiniband interface.
> DAOS-11514 control: Detect IB pkey parent devices (#10328)

- src/rebuild/rebuild_iv.c
- src/rebuild/scan.c
Ignore the EXIST error for scan object insertion for now, since it is harmless for rebuild process.
Once there are errors, let's abort the rebuild immediately and retry.
Conflicts:
src/rebuild/scan.c
> DAOS-11447 rebuild: ignore exist ERROR for object insert (#10097)

- docs/admin/pool_operations.md
Add documentation indicating that dmg is not supporting concurent creation of pools with size given as a percentage of the overall available storage size.
> DAOS-10038 doc: Add concurrent pool creation warning

- src/client/dfs/dfs.c
- src/client/dfs/duns.c
- src/include/daos/object.h
- src/object/cli_obj.c
- also include fix for DAOS-11914
> DAOS-11913 dfs: coverity fixes CID 452244 & 452245

- Jenkinsfile
- src/tests/ftest/harness/advanced.py
- src/tests/ftest/harness/basic.py
- src/tests/ftest/process_core_files.py
- utils/githooks/pre-commit.d/20-flake.sh
- utils/githooks/pre-commit.d/40-pylint.sh
- utils/rpms/daos.spec
> DAOS-11764 build: Enable debuginfo sub-packages

- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
- src/control/server/mgmt_pool.go
In some test scenarios, the current MS leader's only engine rank is
killed as part of the test, but the leadership transfer doesn't occur
until a dRPC request fails. The PoolCreate logic handled this, but other
Pool operations didn't. This commit just adds the retry logic to all
Pool operations.
> DAOS-11953 control: Add DataPlaneNotStarted to retryable pool errors

- src/object/cli_obj.c
- src/placement/pl_map_common.c
- src/pool/srv_cli.c
- src/tests/ftest/osa/online_extend.py
1. Only checking non-extending shards in obj_grp_valid_shard_get().
2. Recreate the bulk during retry, in case the bulk needs to be created and re-binded, once refreshing the layout.
> DAOS-11936 object: fix online extending bugs

- src/control/lib/hardware/hwprov/defaults.go
- src/control/lib/hardware/libfabric/bindings.go
- src/control/lib/hardware/ucx/bindings.go
The use case where libfabric is present but UCX libs aren't installed is normal.
- Log missing dynamically loaded libs at debug level only.
- Improve error messages so it's easier to tell which library failed to load.
> DAOS-11554 control: Don't log missing lib as error (#10327)

- src/vea/tests/vea_stress.c
Fix spelling in vea_stress.c
Change spelling of enumerations as well.
> DAOS-623 vea: fix spelling in vea test (#10605, #10607)

- src/rebuild/srv.c
Missing riv_sync setting for rebuild status sync
> DAOS-11655 rebuild: missing riv_sync (#10519)

- src/vos/evtree.c
- src/vos/tests/evt_stress.py
- utils/run_test.sh
Modify default sort to use even split if the tree is too deep.  Otherwise, some I/O patterns can cause a segfault
due to the depth exceeding the EVT_TRACE_MAX
Rename ssof to soff for consistency
> DAOS-11894 vos: Avoid segfault due to default evtree sort policy

- src/pool/srv_iv.c
- src/tests/ftest/rebuild/with_io.yaml
rf check ult might set sc_rw_disabled true if RF is 0 and rebuild has not finished yet:
src/object/srv_obj.c:1719 obj_capa_check() cont hdl 9cea8bf9 exceeds rf
Test-tag: test_rebuild_with_io
Signed-off-by: Wang Shilong <shilong.wang@intel.com
> DAOS-11163 test: set redun fac property for container

- src/object/cli_ec.c
- src/object/cli_obj.c
For some fail cases it calls tse_task_complete(task, rc) for err handing. In tse_task_complete only over-write task->dt_result if it is zero, but for some cases need to overwrite task->dt_result's retry-able result if get new different failure to avoid possible dead loop of retry or assertion.
> DAOS-11666 object: refine task err handling

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
- src/tests/ftest/erasurecode/mdtest_smoke.yaml
The proposed patch return an error when the --tier-ratio option is used to create a pool with a ratio of the available storage.
With this patch, if the user gives the default value '6,94' to the --tier-ratio option, then the error will not be raised, and the given tier-ratio will be silently ignored as if the --tier-ratio option was not given.  From my investigation, it will not be so easy to deal with this limitation as the goflag package only define the value of the options and not if they were used.
> DAOS-10884 control: not mix dmg pool create --tier-ratio and --size=percentage

- src/client/pydaos/raw/daos_cref.py
pydaos AsyncWorker1() method uses an extraneous/unnecessary DaosEvent() instance than the one already created/passed by callers.
This patch enables usage of original/caller's DaosEvent() instance, like in AsyncWorker2().
> DAOS-11882 pydaos: AsyncWorker1() should use passed DaosEvent() (#10530)

- src/client/pydaos/raw/daos_api.py
Commit c5c4b26989 (DAOS-3927/PR-1617) had introduced a regression (one parameter in excess to be passed to daos_cont_create() api, when properties specified) which has only been unveilled when commit 44c7676212 (DAOS-11375/PR-10203) has landed due to causing redundancy factor property to be passed by default !!...
This patch removes the extra/erroneous parameter.
> DAOS-11643 tests: fix parameters passing to API (#10529)

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_resync.c
- src/dtx/dtx_rpc.c
- src/include/daos_srv/dtx_srv.h
- src/include/daos_srv/vos.h
- src/object/obj_tx.c
- src/object/srv_obj_remote.c
- src/vos/tests/vts_dtx.c
- src/vos/vos_dtx.c
- src/vos/vos_tls.h
The patch fixes the following DTX related issues:
1. Use the address of tree handle for dtx_rpc_post.
If we directly use the value of tree handle as dtx_rpc_post()'s
input parameter, then it may be DAOS_HDL_INVAL before DTX helper
ULT being scheduled. That will cause memory leak.
2. Abort remote DTX entry before local one.
The DTX abort maybe triggered by dtx_leader_end for RPC timeout
on some remote DTX participant(s). Under such case, client side
RPC sponsor may also hit the RPC timeout and resends related RPC
to the leader. To avoid DTX abort and resend RPC forwarding being
executed in parallel, we will abort local DTX after remote done,
before that the logic of handling resent RPC on server will find
the local pinned DTX entry then notify related client to resend
RPC sometime later. …
> DAOS-11679 dtx: misc patch for dtx related issues

- src/object/srv_obj_migrate.c
In ds_migrate_stop(), migrate_fini_one_ult only wait non-0 xstream ULTs to stop, so it should also wait for 0 xstream migrate ULT to stop before destroying migrate tls.
> DAOS-11750 object: wait for 0 xstream tls stop (#10487)

- src/chk/chk.pb-c.c
- src/chk/chk.pb-c.h
- src/proto/chk/chk.proto
Introduce new flags for check start to overwrite former set flags when resume the check from former paused/stop phase without reset all the process.
CF_NO_FAILOUT:  Overwrite former set CF_FAILOUT flag.
CF_NO_AUTO:     Overwrite former set CF_AUTO flag.
> DAOS-11538 chk: new flags to overwrite former start options

- src/control/server/engine/exec_test.go
Fixes two intermittent issues seen while running this
unit test suite:
* Ensure that the context is not canceled before the
child test process starts
* Don't regenerate the fake daos_engine binary if
it already exists
> DAOS-11959 control: Improve server/engine unit tests

- .github/workflows/ci2.yml
- .github/workflows/landing-builds.yml
- src/client/dfs/duns.c
Move rocky8 to Landings only, and add rocky9 to PRs and landings.
> DAOS-11972 cq: Change GitHub Actions distros matrix.

- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
- src/control/server/mgmt_pool.go
In some test scenarios, the current MS leader's only engine rank is
killed as part of the test, but the leadership transfer doesn't occur
until a dRPC request fails. The PoolCreate logic handled this, but other
Pool operations didn't. This commit just adds the retry logic to all
Pool operations.
> DAOS-11953 control: Add DataPlaneNotStarted to retryable pool errors (#10653)

- src/control/cmd/daos_server/storage_nvme.go
- src/control/cmd/daos_server/storage_nvme_test.go
- src/control/server/storage/bdev/mocks.go
To improve consistency, nvme scan command should only report bdevs
specified in provided configuration file (if none specified then report all).
> DAOS-11961 control: Add config awareness for daos_server nvme scan cmd

- src/cart/crt_context.c
- src/cart/crt_init.c
- The check for not overflowing 256 contexts was only set for SEP mode, causing crash if client tried to allocate more.
> DAOS-11970 cart: Fix limit checks on contexts

- src/client/api/object.c
- src/client/dfs/dfs.c
- src/include/daos/task.h
- src/include/daos_obj.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_task.c
- src/tests/suite/dfs_unit_test.c
- add a new API to allow querying the max update epoch from an object without needing to query the keys.
- use the new API to return correct mtime and ctime for directory objects in DFS.
> DAOS-11422 dfs: add support for mtime and ctime on directory objects

- src/rebuild/scan.c
- src/rebuild/srv.c
Increase ult stack size to 64KB for checking tgt/leader ULT.
> DAOS-11952 rebuild: increase stack size for rebuild ULT

- src/chk/chk.pb-c.c
- src/chk/chk.pb-c.h
- src/proto/chk/chk.proto
From control plane's perspective, it always can know the pool UUID from MS database if it exists on MS. So if the user wants to check whether some pool is dangling pool or not, he/she can specify such UUID via DAOS check start option. But for orphan pool, since there is no record in MS database, the user cannot know its UUID as then cannot be aware of its existence. So unless all pools are checked from the scratch or the user records the pool UUID via other way, otherwise, he/she has no chance to detect some orphan pools.
So we need the start option "-o | --orphan" for such purpose. It is more meaningful than the option "-d | --dangling".
> DAOS-11538 proto: replace dangling pool option with orphan pool

- src/common/ad_mem.c
- src/common/tests/ad_mem_tests.c
group header is stored in the first 32k of arena, the first bit of bitmap is reserved for this, group address should not add header size, otherwise, last group will be out of boundary.
extend adt_no_space_1 which help reproduce this, also it is a test for free memory management testing which will be pushed later.
> DAOS-11605 common: fix to calculate group address

- src/dtx/dtx_common.c
- src/include/daos_srv/dtx_srv.h
- src/object/srv_obj.c
- src/vos/tests/vts_dtx.c
- src/vos/vos_dtx.c
When modify single replicated object, if it is not conditional, then it is unnecessary to keep related committed DTX entry, because:
1. We do not have DTX resync for such DTX.
2. We do not have DTX refresh for such DTX.
3. For relative rare case, the client may resend related modification RPC, then it is harmless to re-execute related modifiation since it does not break related semantics. The redundant (old) modification will be clean via VOS aggregation some time later.
> DAOS-11896 dtx: drop committed DTX for non-conditional solo modification

- src/container/cli.c
- src/container/cli_internal.h
- src/include/daos/container.h
- src/include/daos/pool.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_internal.h
- src/object/obj_tx.c
- src/object/obj_verify.c
- src/pool/cli.c
- src/pool/cli_internal.h
Whenever we want to access pool and container pointer in daos client stack,
looking a per-proccess handle hash table by daos handle is required.
Performance could not scale well for multiple threads because of pthread read lock scability.
To avoid above issue, It is possible to store container and pool pointers in dc_object directly,
extra reference will be held for pool/cont if object is opened. during IO, accessing these
pointers are safe, even pool/cont are closed, server will return errors.
Benchmarking showed fio 4k random write(32 threads) improved from 381k iops to
1500k iops on Rocky8.
> DAOS-11146 object: cache dc_pool and dc_cont

- src/tests/suite/daos_rebuild.c
Do not kill all replicas of the object, otherwise
it may cause EIO for inflight I/O for the moment.
Test-tag: daos_core_test_rebuild
> DAOS-11949 tests: Do not kill all replicas

- src/control/cmd/daos/property.go
Return an error if setting the property string fails.
> DAOS-11981 tools: Check rc in label prop handler

- src/bio/bio_wal.c
- src/include/daos_srv/bio.h
I'm not sure we should be passing umm to bio_yield. Perhaps it's better handled with a macro for use in places we may be in a transaction.
Anyway, rather than pass a umm to the vio_replay routine, just pass and handle NULL parameter to bio_yield.
> DAOS-623 bio: Workaround compilation failure

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/tests/ad_mem_tests.c
- A blob is pinned in memory because arenas in LRU keeps refcount on it, so there is no way to actually free it on close/destroy. With this patch, all groups & arenas in LRU can release refcounts on close, so close & destroy are able to free memory.
- Blob incarnation was overwritten on open(), it is fixed by this patch.
- Change allocation size of the performance test from 64 to 256 bytes, because arena will overflow when the size is 64 (too many groups), this requires a seprate fix in follow-on patch.
> DAOS-11605 common: free blob on destroy

- src/tests/ftest/nvme/pool_exclude.py
- src/tests/ftest/nvme/pool_exclude.yaml
- src/tests/ftest/pool/rf.py
The pool and container rf property is depdrecated in favor of the name rd_fac property.
This PR also fix a regression, on the indentation of the nvme/pool_exclude.yaml configuration file, introduced with DAOS-11624.
Finally, this PR fix some minor codespell
The two targeted ftest have been run sucessfully 20 times with the CI https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-10625/6/tests/
> DAOS-11927 test: fix deprecated json output rf property

- ci/provisioning/post_provision_config_common_functions.sh
- ftest.sh
- src/tests/ftest/launch.py
- src/tests/ftest/scripts/main.sh
- src/tests/ftest/slurm_setup.py
- src/tests/ftest/soak/faults.py
- src/tests/ftest/soak/harassers.py
- src/tests/ftest/soak/smoke.py
- src/tests/ftest/soak/smoke.yaml
- src/tests/ftest/soak/stress_2h.py
- src/tests/ftest/soak/stress_2h.yaml
- src/tests/ftest/soak/stress_48h.py
- src/tests/ftest/soak/stress_48h.yaml
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/soak_test_base.py
- src/tests/ftest/util/soak_utils.py
Test-tag: pr soak_smoke
Updated test code to run soak via a Jenkins build in CI Updates include:
- Allow ftest/main to include up to 24 nodes
- Update post provisioning to easily add *-testing branch
- Create DAOS_APP_DIR env within the testing framework
- Changed vpic default mpi to mpich
- Fixed an issue in soak cleanup where it was removing the shared tmp dir
> DAOS-11269 test:  Update pipeline-lib to enable soak-branch (#9911)

- src/bio/bio_buffer.c
- src/bio/bio_context.c
- src/bio/bio_internal.h
- src/bio/bio_wal.c
- src/bio/bio_xstream.c
- src/include/daos_srv/bio.h
- src/include/daos_srv/vea.h
- src/vea/vea_api.c
- src/vos/vos_aggregate.c
- src/vos/vos_internal.h
- src/vos/vos_io.c
- src/vos/vos_obj.c
- src/vos/vos_pool.c
- src/vos/vos_pool_scrub.c
When md on SSD introduced, umem_instance will require bio_io_context for underlying meta SSD I/O, to get rid of this awkward circular referencing between umem_instance and bio_io_context, this patch moved the umem_instance (bic_umem) from bio_io_context into bio_desc.
This will make the umem_instance setup procedure more straightforward, prepare BIO meta/IO contexts first, then setup umem_instance.
> DAOS-11885 bio: remove umem from bio_io_context

- src/chk/chk_engine.c
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/vos/vos_obj.c
- src/vos/vos_obj.h
- src/vos/vos_obj_cache.c
It contains the following:
1. Introduce new flags VOS_OBJ_KILL_DKEY for vos_obj_del_key() to
avoid failing inside vos_obj_hold().
2. Check start RPC transfers wrong flags to check engine, that may
causes the check engine on non-leader to run under dryrun mode.
Fix it.
3. Set repair action more accurately.
> DAOS-11538 chk: misc fixes for chk related issues - part II

- src/dtx/dtx_rpc.c
- src/vos/vos_dtx.c
There is race among DTX commit, DTX aggregation and DTX refresh: DTX refresh is triggered before some DTX entry committed on the non-leader. But such DTX entry has already been committed on the leader and removed by DTX aggregation locally very soon. Then the DTX refresh for such DTX entry will get -DER_TX_UNCERTAIN from the leader. That will cause non-leader to mark such DTX as DTE_ORPHAN via vos_dtx_set_flags(). But just during the DTX refresh, the DTX is committed on current non-leader (after some long time of delay), then the vos_dtx_set_flags() will get failure.
Under such race case, the DTX refresh needs to handle related DTX as committed one instead of report failure.
> DAOS-11924 dtx: handle race among DTX commit and DTX refresh

- src/common/pool_map.c
- src/include/daos/pool_map.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/srv_obj_remote.c
- src/placement/jump_map.c
- src/placement/pl_map.h
- src/placement/pl_map_common.c
- src/placement/tests/jump_map_place_obj.c
- src/pool/srv_pool.c
- src/pool/srv_pool_map.c
- src/pool/srv_target.c
- src/rebuild/srv.c
- src/tests/suite/daos_extend_simple.c
1. Cleanup extend handler to use pool_svc_update_map(), similar as other pool update handler.
2. Change extend pool map status to NEW->UP->UPIN, to match with reintegrated process. NEW: just added the rank. UP: extending targets. UPIN: extended/healthy targets.
3. A few fixes for punch over online extending, so for extending/reintegrating/excluding shards, it should use DELAY forward flag. And add tests to verify it.
> DAOS-11943 objects: online extending fixes

- src/control/cmd/daos/property.go
Return an error if setting the property string fails.
> DAOS-11981 tools: Check rc in label prop handler (#10705)

- src/client/dfs/dfs.c
- src/include/daos/object.h
- src/object/cli_obj.c
- src/object/obj_class.c
when creating a container, the file object class is not checked since we only create the root directory and SB object. Add a check to see if the file oclass is passed, it satisfies the RF.
Test-tag: pr oc_selection
> DAOS-11907 dfs: check passed in object classes if they satisfy the RF

- src/control/cmd/dmg/check.go
- src/control/lib/control/check.go
- src/control/lib/ui/bool_flags.go
- src/control/lib/ui/bool_flags_test.go
Provides two new set-policy flags:
* dmg check set-policy --all-interactive
* dmg check set-policy --reset-defaults
These flags can be used instead of setting each policy's action
individually.
Additionally, adds UI support for the new checker flags added
in a previous commit.
* dmg check start --auto=[on|off] --failout=[on|off]
> DAOS-9799 chk: Allow checker policies to be set all-interactive

- src/tests/ftest/launch.py
- src/tests/ftest/scripts/setup_nodes.sh
Setup both fuse.conf and fuse3.conf to account for OS differences.
Test-tag: test_dfuse_mu_mount pr,vm
> DAOS-12011 test: setup fuse3.conf

- src/chk/chk_engine.c
- src/include/daos_srv/pool.h
- src/pool/srv_pool.c
- src/rsvc/srv.c
Prevent automatic PS reconfigurations in the CR "check" mode, in order
to avoid racing with the chk module's actions. Schedule PS
reconfigurations when the chk module is ready before moving a pool to
the DONE phase.
Fix a segfault due to the use of an invalid svc variable when destroying
a stopped rsvc replica:
pool_svc_locate_cb (id=0x18, path=0x7fa947c6d2e0) at
src/pool/srv_pool.c:953
ds_rsvc_stop (class=DS_RSVC_CLASS_POOL, id=0x7fa96c5f0860,
caller_term=18446744073709551615, destroy=<optimized out>) at
src/rsvc/srv.c:1009
ds_rsvc_stop_handler (rpc=0x7fa96c5f0660) at src/rsvc/srv.c:1437
crt_handle_rpc (arg=0x7fa96c5f0660) at src/cart/crt_rpc.c:1654
> DAOS-10138 chk: Schedule PS reconf before DONE

- src/bio/bio_device.c
- src/mgmt/srv_query.c
When VMD is not enabled, retrieving LED state for a SSD fails. This
failure should be captured and logged but not cause fatal errors when
listing SMD device details.
Test-tag: daily_regression pr
> DAOS-12036 bio: Fix LED state error in list smd devs on non-VMD

- src/vos/vos_common.c
For a distributed transaction with multiple update/punch against the same akey, some reserved nvme area may be released internally. These area is recorded via dth->dth_deferred_nvme. In spite of whether the transaction is committed or aborted finally, we both need to cancel these area to avoid space leak.
> DAOS-12020 vos: cancel deferred nvme list unconditionally

- src/pool/srv_target.c
Looks like both GC/Flush ULT stacks can overflow upon certain situations, and this may be due to some PMDK/SPDK/DPDK recent changes ...
So bump their stack size from default/16K to DSS_DEEP_STACK_SZ.
> DAOS-11149 pool: bump GC ULT stack size (#9924)

- src/client/dfs/README.md
- src/client/dfs/dfs.c
- src/client/dfs/duns.c
- src/control/cmd/daos/container.go
- src/include/daos_fs.h
- src/include/daos_uns.h
- src/utils/daos_hdlr.c
- src/utils/daos_hdlr.h
- utils/node_local_test.py
Change oclass to be the default for all objects, and add a new option for file_oclass (dir_oclass is already there).
Features: dfs
> DAOS-12038 dfs: add file_oclass option for DFS container creation

- src/control/cmd/dmg/main.go
- src/control/lib/control/rpc.go
This error can occur in certain circumstances and should be
retryable. Also fixes the JSON output handler to ensure that
the response field is null if there was an error.
> DAOS-12025 control: Add os.ErrDeadlineExceeded to retryable errors

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/tests/ad_mem_tests.c
- If caller always allocates 64-byte space, arena can have more than 500 groups and overflow group sorters of arena. This patch increases reserved metadata space of arena so an arena can have up to 480 groups in the extreme case.
- Add comments to explain the future usage of some reserved bytes.
- Fix a refcount leak in unit test.
> DAOS-11605 common: arena overflow

- src/tests/ftest/launch.py
- src/tests/ftest/util/run_utils.py
Now that the interface speed check performed by launch.py is performed via a clushed cat command the error handling for a virtio network interface needs to be updated to handle the error coming from the cat command.  Also fixed the error handling for detecting the core file pattern.
> DAOS-12049 test: Fix speed check for virtio network interface

- src/tests/ftest/pool/create_capacity.yaml
Increasing the pool/create_capacity.py test timeout by 100 seconds to allow for enough time to tear down the test if the pool creation takes longer than norrmal.
Test-tag: create_performance
Test-repeat: 5
> DAOS-11945 test: Increase pool/create_capacity.py timeout

- src/common/drpc.c
- src/common/tests/common-mock-ld-opts
- src/common/tests/test_mocks.c
- src/control/cmd/daos_agent/start.go
- src/control/cmd/drpc_test/main.go
- src/control/drpc/README.md
- src/control/drpc/drpc_server.go
- src/control/drpc/drpc_server_test.go
- src/control/server/drpc.go
- src/engine/tests/drpc_client_tests.c
- src/include/daos/test_mocks.h
/var/daos/daos_server/daos_server.sock has permissions 777, should be 600
/var/daos/daos_server/daos_engine_^pid^.sock has permission 755, should be 600
/var/daos/daos_agent/daos_agent.sock has permissions 777, should be 666
> DAOS-11811 control: Tighten up permissions of dRPC socket files (#10470)

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_resync.c
- src/dtx/dtx_rpc.c
- src/include/daos_srv/dtx_srv.h
- src/include/daos_srv/vos.h
- src/object/srv_obj_remote.c
- src/vos/tests/vts_dtx.c
- src/vos/vos_dtx.c
- src/vos/vos_tls.h
master-commit: 839d77ead4471eb3a759573453a8ad23fcca1c1c
The patch fixes the following DTX related issues:
1. Use the address of tree handle for dtx_rpc_post. If we directly use the value of tree handle as dtx_rpc_post()'s input parameter, then it may be DAOS_HDL_INVAL before DTX helper ULT being scheduled. That will cause memory leak.
2. Abort remote DTX entry before local one. The DTX abort maybe triggered by dtx_leader_end for RPC timeout on some remote DTX participant(s). Under such case, client side RPC sponsor may also hit the RPC timeout and resends related RPC to the leader. To avoid DTX abort and resend RPC forwarding being executed in parallel, we will abort local DTX after remote done, before that the logic of handling resent RPC on server will find the local pinned DTX entry …
> DAOS-11679 dtx: misc patch for dtx related issues - b22

- src/common/ad_mem.c
- src/vea/vea_init.c
Arena binheap ops has same name declared as vea binheap ops, and they are both not declared as static which cause strange memory corruptions.
> DAOS-11605 common: rename heap_ops to avoid conflict

- src/vos/vos_obj.c
- src/vos/vos_obj.h
- src/vos/vos_obj_cache.c
During traverse some table under the sysdb, the caller holds reference
on related object, it will cause vos_obj_hold() to return -DER_BUSY if
use DAOS_INTENT_KILL when call vos_obj_del_key(), that is triggered by
the iteration callback. In fact, such restriction is only meaningful
when delete the object instead of the dkey under the object. The patch
introduces new flags VOS_OBJ_KILL_DKEY for vos_obj_del_key() to bypass
related check inside vos_obj_hold().
> DAOS-11993 vos: new flags VOS_OBJ_KILL_DKEY for  vos_obj_del_key

- src/control/common/test/mocks.go
- src/control/common/test/utils.go
- src/control/fault/code/codes.go
- src/control/lib/control/pool.go
- src/control/lib/control/system.go
- src/control/server/mgmt_cont_test.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
- src/control/system/faults.go
- src/control/system/raft/database.go
- src/control/system/raft/database_test.go
- src/control/system/raft/pool_lock.go
- src/control/system/raft/pool_lock_test.go
- src/control/system/raft/raft.go
- src/control/system/raft/raft_recovery.go
- src/control/system/raft/raft_recovery_test.go
In certain circumstances, a PoolCreate and PoolDestroy may
race, leading to unexpected behavior. This commit adds a
new locking mechanism at the pool database level to prevent
concurrent write operations by more than one parent gRPC
handler.
Additionally, we now call raft.Barrier() as part of the
leadership check in order to ensure that the leader has caught
up with any outstanding logs before proceeding on to any logic
that depends on having leadership.
> DAOS-11919 control: Add concurrent pool ops protection

- src/object/cli_obj.c
- src/tests/suite/dfs_unit_test.c
During EC object enumeration, kds and recxs over each sub anchor may need reallocate, if the number is changed.
set rd_lvl to rank, in the case the test runs with more ranks and fewer nodes.
> DAOS-12063 object: reset kds and recxs for each shard

- src/cart/crt_group.c
- src/cart/crt_init.c
- src/cart/crt_internal_types.h
- src/cart/crt_rpc.c
- daos tool crashed when running over a secondary provider 
- This issue was caused by wrong structure being used on the client end.
> DAOS-12108 cart: Fix segfault over secondary provider

- src/common/fault_domain.c
- src/common/fault_domain.h
- src/common/pool_map.c
- src/common/tests/fault_domain_tests.c
- src/control/server/config/faults.go
- src/control/server/faultdomain.go
- src/control/server/faultdomain_test.go
- Add support for a second layer in fault_path in config yaml.
- Update pool map parsing to understand the second layer, if it exists, as PO_COMP_TP_GRP.
- Remove previous hacks to add group components.
> DAOS-12104 control: Allow an optional second layer in domain path

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/tests/ad_mem_tests.c
- src/include/daos_srv/ad_mem.h
DAOS engine may allocate large chunk for DTX, ad_mem should support it as well. umem layer should use AD_ARENA_LARGE flag to reserve space if size > 4K.
- Fix a bug in bits number calculation for reserving group
- Removed registered arena specification counter
- Add unit test for large allocation
- Decrease the mimimum unit count per group to 2 (2MB is huge page size)
- Add more error messages
> DAOS_11605 common: register arena type for large allocation

- ci/unit/test_nlt_node.sh
Recent changes to NLT have resulted in larger engine log file sizes, closely approaching the current limit 650MiB.
With this change, increase the limit to leave some room for future engine code logging additions, and future NLT changes that could have a corresponding impact on volume of logging done.
> DAOS-12120 test: increase NLT log file size limit

- src/common/ad_mem.c
- src/common/dav/dav_clogs.c
- src/common/dav/dav_iface.c
D_ALIGNED_ALLOC does memset and D_ALIGNED_ALLOC_NZ doesn't so
fixup some allocations that landed previously.
Fix calculation of bmap size so it's based on uint64 instead
of bytes.
Fix allocation of reserve bit map so it allocates the right size
> DAOS-623 common: Address some valgrind issues in ad_mem

- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
- src/control/lib/control/response.go
- src/control/lib/control/rpc.go
In the event that a PoolDestroy RPC is retried and the pool is
destroyed while the client is waiting to retry, the server will
return a -DER_NONEXIST in response to the final retry. As this
is not really an error, just catch it and signal success.
Test-repeat-vm: 10
> DAOS-12119 control: Handle -DER_NONEXIST on retried PoolDestroy

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_iv.c
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/chk/chk_srv.c
- src/container/srv_container.c
- src/container/srv_target.c
- src/dtx/dtx_common.c
- src/dtx/dtx_srv.c
- src/engine/sched.c
- src/engine/server_iv.c
- src/include/daos_srv/container.h
- src/include/daos_srv/pool.h
- src/pool/srv_pool.c
- src/pool/srv_target.c
It contains the following:
1. Fix NULL pointer in chk_pools_dump().
2. Handle non-exist pool shard when start the pool.
3. More accurate log message.
4. Introduce seq# for check IV for trace related notification.
5. Ignore -DER_GRPVER for CHK IV because the pool (shard) on remote rank may does not exist, that is normal for DAOS check.
6. Stop pool service before ds_pool_clues_init() when check restart.
7. Check leader miss to set generation in pool bookmark for reset case.
8. Post handle pool start after checking the pool successfully, incluiding:
8.1 Start GC ULT.
8.2 Start flush ULT.
8.3 Start scrubbing ULT.
8.4 Start VOS aggregation ULT.
8.5 Start EC aggregation ULT if enabled.
8.6 Register container(s) to DTX batched commit ULT.
9. Allow trust the label in container property to fix …
> DAOS-11538 chk: misc fixes for chk related issues - IV

- src/control/common/test/mocks.go
- src/control/common/test/utils.go
- src/control/fault/code/codes.go
- src/control/lib/control/pool.go
- src/control/lib/control/system.go
- src/control/server/mgmt_cont_test.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
- src/control/system/database.go
- src/control/system/database_test.go
- src/control/system/faults.go
- src/control/system/pool_lock.go
- src/control/system/pool_lock_test.go
- src/control/system/raft.go
In certain circumstances, a PoolCreate and PoolDestroy may
race, leading to unexpected behavior. This commit adds a
new locking mechanism at the pool database level to prevent
concurrent write operations by more than one parent gRPC
handler.
Additionally, we now call raft.Barrier() as part of the
leadership check in order to ensure that the leader has caught
up with any outstanding logs before proceeding on to any logic
that depends on having leadership.
> DAOS-11919 control: Add concurrent pool ops protection (#10668)

- src/cart/crt_swim.c
CID 451763: Data race condition (MISSING_LOCK)
> DAOS-11813 swim: fix race access in crt_swim_cli_cb() (#10524)

- src/object/obj_class.c
dc_set_oclass set the obj class possibly cause grp size exceed domain_nr, this patch is to fix it.
> DAOS-12041 object: dc_set_oclass should consider small domain_nr

- docs/release/release_notes.md
mention in relnotes that dmg is now in new daos-admin RPM
Doc-only: true
> DAOS-9355 doc: mention new daos-admin RPM in relnotes

- src/bio/bio_internal.h
- src/bio/bio_monitor.c
- src/bio/bio_xstream.c
Currently only data SSDs monitoring is supported, this patch tries
enable health collection for WAL and Meta SSDs as well.
Auto fault detection and state transit for WAL/Meta SSDs are not
supported yet.
> DAOS-11048 bio: monitor WAL and Meta SSDs

- src/mgmt/srv_drpc.c
After "D_ALLOC_PTR(resp->device);", resp->device (instead of resp) should be checked 
coverity 474372
> DAOS-12116 mgmt: resp->device should be checked 

- src/tests/ftest/fault_injection/pool.py
The rpc error message that is reported when a fault is injected during the pool fault injection test has changed and the test is no longer detecting the failure.  The test needs to be updated to detect the correct error message.
Test-tag: test_pool_services pr
> DAOS-12040 test: Error message has changed

- .github/workflows/landing-builds.yml
- utils/docker/Dockerfile.el.9
- utils/scripts/install-el9.sh
Update package list on el9 and enable server build.  Initially
el9 didn't include enough packages to allow the server to build
however they have now all been ported upstream so update the
package list and enable the build.
> DAOS-12147 build: Include server build on el9.

- Jenkinsfile
- src/common/tests_dmg_helpers.c
It seems possible that the buffer where dmg command line is being constructed, to be passed to system() call, can be in a page that had been registered for RDMA, which can cause a SEGV in fork()'ed child upon access for parsing.
So, to ensure allocating buffer in a brand new page, using mmap() to avoid this.
> DAOS-10301 test: pass dmg command line with mmap() (#10394)

- ci/provisioning/post_provision_config_common_functions.sh
- ci/provisioning/post_provision_config_nodes_EL_8.sh
Install ucx-{cma,ib,knem,rdmacm,xpmem} from the MOFED repo.
Move the modulefile module creation from being EL8 specific to being
done in post_provision_config_nodes() on all distros.
> SRE-549 test: Install MOFED ucx-* packages

- src/client/dfuse/dfuse_main.c
man getopt_long() says it returns int, but dfuse uses char. This causes portability issues on little endian arm64 platforms. Change type from char to int to resolve this.
> DAOS-12165 dfuse: fix getopt_long type for arm64 compatibility

- src/control/common/proto/error.go
- src/control/common/proto/error_test.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
- src/control/server/mgmt_pool.go
- src/control/system/errors.go
The previous commit checked for the wrong error in determining
whether or not a PoolDestroy failure is fatal.
> DAOS-12119 control: Handle correct error on retried PoolDestroy

- src/pool/srv_pool.c
To avoid memory leak when failing to get pool version. Coverity issues 706096 in master.
> DAOS-12164 pool: free prop when failing to get pool version

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removes the now unused Functional Hardware Small stage.
> DAOS-12086 test: Removing HW Small stage.

- src/common/dav/dav.h
- src/common/dav/dav_iface.c
- src/common/dav/dav_internal.h
- src/common/dav/memblock.c
- src/common/dav/mo_wal.h
- src/common/dav/tx.c
- src/common/dav/wal_tx.c
- src/common/dav/wal_tx.h
- src/common/mem.c
- utils/run_test.sh
The changes include:
- umem_store integration with BMEM.
- dav_tx_end() now accepts data_iod and passes it to wal_commit.
- redo log entry associated with dav_reserve() will not use ACT_COPY_PTR.
Signed-off-by: sherintg <sherin-t.george@hpe.com>
> DAOS-12058 common: Integrating BMEM with WAL

- src/control/cmd/daos/fi.go
- src/control/cmd/daos/fi_disabled.go
- src/control/cmd/daos/main.go
Add support for the following faults:
* daos faults DAOS_CHK_CONT_ORPHAN
Fail to remove container during destroy
* daos faults DAOS_CHK_CONT_BAD_LABEL
Fail to persist set-prop --properties label:$newval
> DAOS-11663 chk: Add daos faults command for CR FI

- src/control/system/raft/database.go
The loop should just be restarted in order to act on future
leadership changes.
> DAOS-11986 control: Don't break out of leadership monitoring loop

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removed the now unused Functional Hardware Small stage.
> DAOS-12087 test: Removing HW Small stage

- src/control/common/proto/error.go
- src/control/common/proto/error_test.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
- src/control/lib/control/response.go
- src/control/lib/control/rpc.go
- src/control/server/mgmt_pool.go
- src/control/system/database.go
- src/control/system/errors.go
In the event that a PoolDestroy RPC is retried and the pool is
destroyed while the client is waiting to retry, the server will
return an ErrPoolNotFound error in response to the final retry. As
this is not really an error, just catch it and signal success.
> DAOS-12119 control: Handle ErrPoolNotFound on retried PoolDestroy (#10873)

- src/control/cmd/daos/fi.go
Add a "container" subcommand to set fault location
and then inject the fault in a single command.
Currently supported:
* daos faults container $pool $cont --location DAOS_CHK_CONT_BAD_LABEL
* daos faults container $pool $cont --location DAOS_CHK_CONT_ORPHAN
> DAOS-11663 chk: Improve daos faults commands

- src/control/system/database.go
The loop should just be restarted in order to act on future
leadership changes.
> DAOS-11986 control: Don't break out of leadership monitoring loop (#10937)

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_iv.c
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/chk/chk_srv.c
- src/chk/chk_upcall.c
- src/container/srv_container.c
- src/container/srv_target.c
- src/dtx/dtx_resync.c
- src/engine/server_iv.c
- src/include/daos_srv/daos_chk.h
- src/include/daos_srv/pool.h
- src/include/daos_srv/rsvc.h
- src/object/srv_obj_migrate.c
- src/pool/srv_pool.c
- src/pool/srv_target.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/rsvc/srv.c
1. Wait pool map refresh before next step check.
If the check engine refreshes the pool map, then it needs to wait
for a while until the pool map has been dispatched to all related
pool shards, that will avoid group versioning related trouble for
subsequent container based check.
2. Auto re-start check from the beginning if former check done.
That will avoid explicitly specifying '-r' option when start check
every time after the first check completed.
3. Allow to start pool service with lost some pool shards.
That is useful when the storage for some pool shards are broken
(such as related vos-x file under the pool directory is lost).
4. Use the same sequence# if report an inconsistency multiple times
For an inconsistency, its sequence# is assigned when it …
> DAOS-12145 chk: misc fixes for chk related issues - I

- src/engine/init.c
- src/include/gurt/telemetry_common.h
Previously the metrics shared memory region was created with a static size. However many metrics are now created on a per-target basis. The size needs to scale with the number of targets.
The estimates of the number of standard metrics and number of target metrics are higher than the actual number, to allow some buffer space for future additions.
> DAOS-11880 engine: Scale size of metrics shmem region

- src/tests/ftest/cart/iv/iv_one_node.py
- src/tests/ftest/cart/iv/iv_two_node.py
- src/tests/ftest/cart/util/cart_utils.py
* Wrong number of servers were calculated during the cleanup stage of the test. This resulted in non-existent ranks being pinged for the shutdown leading to asserts and core files being generated.
> DAOS-12155 cart:  Fix iv test cleanup stage (#10932)

- .github/workflows/doxygen.yml
- .github/workflows/pylint.yml
- src/client/ds3/SConscript
- src/include/daos_s3.h
Fix typo in Doxygen file that was casuing errors.
Enable Doxygen checks for all PRs so it can be marked as required
Re-indent public header file with clang-format.
Fix flake issues and remove extra libs from SConscript.
> DAOS-12175 ds3: Fix Doxygen and re-indent header file.

- src/client/java/daos-java/src/main/java/io/daos/Constants.java
- src/client/java/daos-java/src/main/java/io/daos/DaosEventQueue.java
- src/client/java/daos-java/src/main/java/io/daos/DaosIOException.java
- src/client/java/daos-java/src/main/java/io/daos/DaosUtils.java
- src/client/java/daos-java/src/main/java/io/daos/obj/DaosObjClient.java
- src/client/java/daos-java/src/main/java/io/daos/obj/DaosObject.java
- src/client/java/daos-java/src/main/java/io/daos/obj/IODataDescSync.java
- src/client/java/daos-java/src/main/java/io/daos/obj/IODescUpdAsync.java
- src/client/java/daos-java/src/main/java/io/daos/obj/IODescUpdBase.java
- src/client/java/daos-java/src/main/java/io/daos/obj/IODescUpdSync.java
- src/client/java/daos-java/src/main/java/io/daos/obj/IOKeyDesc.java
- src/client/java/daos-java/src/main/native/include/daos_jni_common.h
- src/client/java/daos-java/src/main/native/io_daos_obj_DaosObjClient.c
- src/client/java/daos-java/src/test/java/io/daos/obj/DaosObjectIT.java
- src/client/java/daos-java/src/test/java/io/daos/obj/IODataDescSyncTest.java
1. pad zero when dkey length is less than 8
2. fix some UT and IT
3. add new IO Desc to write only one akey entry for remote shuffle
Signed-off-by: Jifu Zhang <jiafu.zhang@intel.com>
> DAOS-12068  Support dkey/akey length less than 8 bytes in Java synchronous object API

- utils/githooks/pre-commit.d/40-gofmt.sh
Avoid running the hook if the commit didn't change any .go files.
If the commit did change .go files, and gofmt is not in the $PATH
for some reason, the hook will fail.
> DAOS-7821 build: Update gofmt githook to skip if no .go files changed

- src/container/srv_container.c
Previous PR 2446 added D_ERROR to help find where an intermittent container create failure occurred. A failed call to cont_svc_lookup_leader() (e.g., a simple -DER_NOTLEADER) is better surfaced in logging with D_DEBUG, to prevent too much logging noise.
> DAOS-4451 container: ds_cont_op_handler() error log to debug

- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/chk/chk_upcall.c
When leader report inconsistency to control plane for interaction with the user, it may offer some const strings for describing the inconsistency. The upcall logic should not modify such strings to avoid DRAM corruption, instead, we will duplicate the strings and modify the duplicated ones.
On the other hand, the pool ULT that is driven by check main logic to handle related pool inconsistency should not remove related cpr from the pool tree to avoid leaking itself in ABT stack.
> DAOS-12220 chk: avoid modify const string when upcall

- src/control/server/ctl_smd_rpc_test.go
Add unit test coverage for SMD manage set-faulty and replace cases with
a dual engine configuration to prevent any regressions.
> DAOS-12043 control: Add unit tests for smd manage with dual-engine

- src/control/server/storage/bdev/backend_test.go
- src/control/server/storage/bdev/backend_vmd.go
- src/control/server/storage/bdev/backend_vmd_test.go
The prepare step during server start-up should prepare the entire VMD
domain of any VMD backing device to be used by an engine. This should
happen if the backing device PCI address is included in server config 
file bdev_lists or provided explicitly in a daos_server nvme prepare
cmdline option. Without this change server start-up will fail if VMD
backing device addresses are included in the server config file. To
implement, the allow list parameter passed when calling into NVMe/SPDK
prepare should be processed to replace backing device addresses with the
endpoint addresses
> DAOS-12223 control: Allow VMD backing device addresses in NVMe prepare

- src/control/server/mgmt_check.go
Non-leader servers will correctly reply with ErrNotLeader or
ErrNotReplica instead of trying to handle the RPCs.
> DAOS-12238 chk: Add leadership check to checker RPC handlers

- src/tests/ftest/osa/online_reintegration.py
Test-tag: test_osa_online_reintegration test_osa_online_reintegration_without_csum
Summary: Enable the online reintegration tests related to DAOS-7420 ticket.
> DAOS-7420 test: Enable two online reintegration test.

- utils/setup_daos_server_helper.sh
Use $SL_SPDK_PREFIX to link SPDK include directory when populating user share paths
for developer build setup (utils/setup_daos_server_helper.sh).
> DAOS-12265 control: Fix SPDK include path symlink for dev setup

- src/container/srv_container.c
- src/container/srv_layout.h
- src/mgmt/srv_pool.c
- src/mgmt/srv_target.c
- src/pool/srv_pool.c
- src/tests/ftest/pool/label.py
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/dmg_utils.py
- src/tests/ftest/util/dmg_utils_base.py
- src/tests/ftest/util/fio_utils.py
- src/tests/ftest/util/test_utils_pool.py
Change pool destroy code so some essential log entries are
D_INFO (rather than D_DEBUG). This is done so when pool destroy fails
(or hangs), a course-grained understanding of progress is visible
before running a reproducer with log_mask: DEBUG. Additionally,
some D_ERROR entries are added so slightly more information is
reported about the location of a failed destroy.
Also with this change, the functional test code uses the
dmg server set-logmasks command to elevate the engine log_mask
to "DEBUG" immediately preceding any pool create or pool destroy.
Correspondingly, immediately following, it executes
dmg server set-logmasks (no argument) to restore the original
log_mask. This is done to lessen the need for test reproducer
runs when a test failed in pool create/destroy (fairly common)
but …
> DAOS-12222 pool: more INFO logs; test: DEBUG in create/destroy

- src/control/fault/code/codes.go
- src/control/server/faults.go
- src/control/server/server_utils.go
- src/control/server/server_utils_test.go
When multiple engines coexist on the same NUMA node (and there is an
equal number of engines per NUMA node), divide the total number of
hugepages proportionally across NUMA nodes when allocating.
> DAOS-12255 control: Correct hugepage affinity with multi-engine-per-NUMA

- src/bio/bio_wal.c
- src/vos/tests/SConscript
- src/vos/tests/vos_tests.c
- src/vos/tests/vts_common.h
- src/vos/tests/vts_wal.c
Added VOS unit tests to test meta blob loading, WAL replay and checkpoint. This PR only added test infrastructure and single basic pool test as an example, more tests will be added when WAL replay and checkpoint is implemented.
> DAOS-12214 tests: VOS unit tests for WAL

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_resync.c
- src/dtx/dtx_rpc.c
- src/dtx/dtx_srv.c
- src/include/daos/dtx.h
- src/include/daos_srv/vos.h
- src/include/daos_srv/vos_types.h
- src/object/cli_obj.c
- src/object/obj_tx.c
- src/object/srv_obj.c
- src/vos/vos_dtx.c
Before committing the DTX on remote participants, we cannot remove the active DTX locally; otherwise, the local committed DTX entry may be removed via DTX aggregation before remote participants commit done. Under such case, if some remote DTX participant triggere DTX_REFRESH for such DTX during the interval, then it will get -DER_TX_UNCERTAIN, that may cause related application to be failed. So we let remote participants to commit firstly, if failed, we will ask the leader to retry the commit until all participants got committed.
> DAOS-12091 dtx: commit DTX on remote participants before local

- src/bio/bio_buffer.c
- src/bio/bio_internal.h
- src/bio/bio_wal.c
- src/bio/bio_wal.h
- src/bio/bio_xstream.c
- src/common/debug.c
- src/include/daos/debug.h
- src/include/daos_srv/bio.h
- src/tests/ftest/util/telemetry_utils.py
- Added WAL metrics:
1. wal_sz: WAL TX bytes;
2. wal_qd: WAL TX queue depth;
3. wal_waiters: Number of waiters waiting for WAL space;
- Don't do async bio_iod_post() when the value is too large (default maximum value size is 1MB, could be tuned by env var DAOS_MAX_ASYNC_SZ) to avoid calculating csum on too large values.
- Inroduced bio_wal_query() to get WAL space, committed, checkpointed information, it could be used by checkpoint ULT in the future.
- Introduced "No WAL csum tail" mode, when a WAL is formatted with "No csum tail", TX csum won't be generated, and the WAL tx integrity check will fully rely on WAL tx headers. This mode is disabled for now.
> DAOS-11412 bio: WAL metrics

- src/control/common/proto/logging.go
- src/control/common/proto/mgmt/addons.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_acl.go
- src/control/lib/control/response.go
- src/control/lib/control/system.go
- src/control/logging/logger.go
- src/control/server/ctl_firmware.go
- src/control/server/ctl_network_rpc.go
- src/control/server/ctl_ranks_rpc.go
- src/control/server/ctl_smd_rpc.go
- src/control/server/ctl_storage_rpc.go
- src/control/server/interceptors.go
- src/control/server/mgmt_cont.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_system.go
- src/control/server/server.go
- src/control/server/server_utils.go
- src/control/system/raft/database.go
- src/control/system/raft/raft.go
Remove boilerplate from gRPC handlers by logging
request and result automatically via an interceptor.
> DAOS-12250 control: Improve debug logging

- src/mgmt/srv_pool.c
- src/mgmt/srv_target.c
With this change, add some INFO level log messages in the engine
pool create code execution flow, so coarse-grained progress
on stuck pool creates can be more easily seen. Additionally,
add more D_DEBUG statements so progress is more explicitly
visible when engines are configured with the more verbose
log_mask: DEBUG setting.
> DAOS-12257 pool: create logging with log_mask: INFO and DEBUG

- src/tests/ftest/ior/crash.py
- src/tests/ftest/util/ior_test_base.py
avocado's SubProcess output is buffered, so searching stdout in realtime is not
reliable. Instead of checking for "Commencing...", just create the pool
and container upfront, slepp for half of stonewall time, and stop IOR.
Test-tag: test_ior_crash
Test-repeat: 3
> DAOS-11192 test: simplify ior/crash subprocess checking

- src/vos/tests/vts_pm.c
- src/vos/vos_ilog.c
If a key is punched and there is a subsequent, not-yet-committed update, aggregation will remove the key.  Fix the check so that it also checks for uncommitted entries to avoid this.
> DAOS-12260 vos: Fix bug where uncommitted update can be removed

- src/tests/ftest/dfuse/caching_check.py
- src/tests/ftest/dfuse/root_container.py
- src/tests/ftest/util/dfuse_utils.py
- src/tests/ftest/util/run_utils.py
- src/tests/ftest/util/soak_utils.py
Test-tag: dfuse,-manual,-dm_posix_meta_entry soak_smoke Skip-func-test-leap15: false
- dfuse_utils
- replace all pcmd() with run_remote().
- cleanup setting pool and cont params
- run_utils
- add RemoteCommandResult.passed_hosts
- add RemoteCommandResult.failed_hosts
> DAOS-11975 test: replace dfuse_utils pcmd with run_remote (#10696)

- src/chk/chk.pb-c.c
- src/chk/chk.pb-c.h
- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/chk/chk_srv.c
- src/control/common/proto/chk/chk.pb.go
- src/control/common/proto/mgmt/check.pb.go
- src/control/lib/control/check.go
- src/control/system/checker/finding.go
- src/control/system/checker/finding_test.go
- src/mgmt/check.pb-c.h
- src/proto/chk/chk.proto
- src/proto/mgmt/check.proto
- src/vos/vos_layout.h
1. Use the same sequence for delay repair inconsistent pool label
When the user choose to trust MS to repair inconsistent pool label,
then the real repair will not be done on the check leader, instead,
it will be postponed until the pool service started and related PS
leader will repair the pool label. After that related check engine
will report the repair result. It should reuse the same sequence#
to allow control plane to locate the original interaction report.
2. Typo fix for CheckScanPhase
Rename OSP_AGGREGATION to CSP_AGGREGATION.
Rename DSP_DONE to CSP_DONE.
3. Fix confused query output with scan phase DONE but RUNNING status.
4. Repair multiple dangling pools via dedicated ULTs concurrently.
Then check and repair for different pools will be totally …
> DAOS-12145 chk: misc fixes for chk related issues - IV

- src/vos/vos_dtx.c
master-commit: eedb765cd3748df0db98f7f8dbfcdc0ec6b18cfc
Mainly include the followings:
1. If the DTX entry is not committable, then do NOT return -DER_INPROGRESS when DTX refresh on it.
2. For stand-alone read, ignore non-prepared DTX in spite of it is on the leader or not.
> DAOS-11602 vos: fix some DTX visibility issues

- src/common/btree.c
- src/tests/suite/daos_iotest.h
- src/tests/suite/daos_test.h
- src/vos/evt_priv.h
- src/vos/vos_aggregate.c
- src/vos/vos_internal.h
Signed bit fields cause a compiler warning with new Intel compiler.  I suspect this may be a bug but there is also no reason a bit field should be signed.
> DAOS-12296 common: Fix Intel compiler warnings

- src/common/btree.c
- src/tests/suite/daos_iotest.h
- src/tests/suite/daos_test.h
- src/vos/evt_priv.h
- src/vos/vos_aggregate.c
- src/vos/vos_internal.h
Signed bit fields cause a compiler warning with new Intel compiler.  I suspect this may be a bug but there is also no reason a bit field should be signed.
> DAOS-12296 common: Fix Intel compiler warnings (#11095)

- src/vos/tests/vts_pm.c
- src/vos/vos_ilog.c
If a key is punched and there is a subsequent, not-yet-committed update, aggregation will remove the key.  Fix the check so that it also checks for uncommitted entries to avoid this.
> DAOS-12260 vos: Fix bug where uncommitted update can be removed (#11038)

- src/tests/ftest/launch.py
An unescaped . in an RE makes a huge difference if was supposed to be
escaped.
> SRE-416 test: Fix Launchable xunit1 de-mangle

- src/rebuild/srv.c
If the rank is being added to the pool map after
rebuild starts, then it will not be tracked by rebuild process anyway, so let's remove the invalid rank check in rebuild_leader_set_status().
> DAOS-12198 rebuild: remove invalid assertion.

- src/chk/chk_engine.c
- src/chk/chk_leader.c
1. Correctly set the repair action after interaction with user.
Fix a bug for handling dangling pool map entry.
2. Resolve merge conflict in ds_iv_ns_update() when merge master.
> DAOS-12145 chk: misc fixes for chk related issues - V

- src/common/tests_dmg_helpers.c
- src/include/daos/tests_lib.h
- src/tests/suite/daos_checksum.c
- src/tests/suite/daos_container.c
- src/tests/suite/daos_epoch_io.c
- src/tests/suite/daos_obj.c
- src/tests/suite/daos_pool.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_simple.c
- src/tests/suite/daos_test.h
- src/tests/suite/daos_test_common.c
Use the new-style dmg helper to perform all pool operations.
Avoids malloc/RDMA problems as described in DAOS-10301.
> DAOS-12277 test: Convert suite to use new-style dmg helpers

- src/chk/chk_engine.c
- src/chk/chk_leader.c
1. Keep leader scheduler until handled dangling pools
Otherwise, if there are only dangling pools, then leader scheduler may exist too early as to the pool tree (that is attached to check instance) is destroyed before dangling pool ULTs accessing it.
2. Use dss_thread_collective_reduce when query pool on check engine
> DAOS-12145: chk: misc fixes for chk related issues - VI

- src/control/cmd/dmg/pretty/check.go
- src/control/lib/control/check.go
If the checker is running, show the number of pools being checked.
If the checker has completed, show the number of unique pools
found in the results.
> DAOS-12270 chk: Adjust check query output based on status

- src/control/server/config/server_test.go
- src/control/server/ctl_smd_rpc_test.go
- src/control/server/ctl_storage_test.go
- src/control/server/ctl_svc_test.go
- src/control/server/engine/config.go
- src/control/server/engine/config_test.go
- src/control/server/engine/testdata/full.golden
- src/control/server/instance_superblock.go
- src/control/server/instance_superblock_test.go
- utils/config/daos_server.yml
The ranks assigned to engines will be determined by the DAOS
Management Service. The old rank parameter in the engine
configuration section was a legacy remnant of pre-Control Plane
days and is a source of confusion and errors for new users.
> DAOS-12279 control: Remove support for config-specified ranks

- Jenkinsfile
Add support for the Functional Hardware Medium TCP Provider stage in order to run any 'provider' tagged tests in the tcp provider branches.
Test-tag: test_always_passes_hw test_daos_pool
> DAOS-12021 tests: Add HW Medium TCP Provider stage

- src/tests/ftest/util/ior_test_base.py
- src/tests/ftest/util/ior_utils.py
- src/tests/ftest/util/test_utils_pool.py
Test-tag: ior,pr ior,daily_regression
- Move IorTestBase.display_pool_space to TestPool.display_space
- Don't call both display_pool_daos_space and set_query_data since set_query_data already displays the space in a more readable format. display_pool_daos_space should be phased-out anyway.
> DAOS-623 test: remove duplicate ior pool space functions

- src/tests/ftest/dfuse/caching_check.py
- src/tests/ftest/dfuse/caching_check.yaml
Test-tag: test_dfuse_caching_check
- Reduce threshold from 450% to 300%
- Misc cleanup
> DAOS-12259 test: reduce dfuse caching perf threshold

- src/tests/ftest/datamover/posix_subsets.py
- src/tests/ftest/datamover/posix_subsets.yaml
Test-tag: dm_posix_subsets
- Enable root -> new dir variant with dcp
> DAOS-11873 test: datamover dcp test with root->new dir

- debian/control
- site_scons/components/__init__.py
- src/bio/bio_context.c
- src/bio/bio_wal.c
- src/bio/bio_wal.h
- src/bio/bio_xstream.c
- src/bio/smd/smd_internal.h
- src/bio/smd/tests/smd_ut.c
- src/common/SConscript
- src/common/sys_lmdb.c
- src/engine/srv.c
- src/include/daos/sys_db.h
- src/include/daos_srv/bio.h
- src/include/daos_srv/daos_engine.h
- src/include/daos_srv/vos_types.h
- src/vos/sys_db.c
- src/vos/vos_common.c
- src/vos/vos_internal.h
- src/vos/vos_pool.c
- utils/rpms/daos.spec
- utils/run_test.sh
- utils/scripts/install-el8.sh
- utils/scripts/install-el9.sh
- utils/scripts/install-leap15.sh
- utils/scripts/install-ubuntu.sh
LMDB is added as new backend kv store for sys DB, this new backend sys DB will be used to store SMD for MD-ON-SSD case.
For PMDK case, SMD will still be stored in PMEM for backward compatibility purpose.
> DAOS-11040 common: add lmdb backend kv for SMD

- Jenkinsfile
Add support for the Functional Hardware Medium UCX Provider stage in order to run any 'provider' tagged tests in the ucx provider branches.
Test-tag: test_always_passes_hw test_daos_pool
> DAOS-12021 tests: Add HW Medium UCX Provider stage

- src/dtx/dtx_common.c
- src/dtx/dtx_rpc.c
- src/include/daos_srv/dtx_srv.h
- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_tx.c
- src/object/srv_obj.c
- src/object/srv_obj_remote.c
If a large transaction has sub-requests to dispatch to a lot of DTX participants, then we may have to split the dispatch process to multiple steps; otherwise, the dispatch process may trigger too many in-flight or in-queued RPCs that will hold too much resource as to server maybe out of memory.
> DAOS-11679 dtx: dispatch large transaction via multiple steps

- src/tests/ftest/util/data_mover_test_base.py
Test-tag: test_basic_checkout_dm test_io_sys_admin
- Use ior_cmd.test_file instead of hardcoded 'testfile'
> DAOS-12258 test: fix run_dm_activities_with_ior testfile

- src/cart/crt_swim.c
Michael MacDonald noticed segfault
swim_dump_updates (nupds=5, upds=0x0, to_id=2, from_id=3, self_id=2)
at src/cart/swim/swim.c:105
swim_updates_parse (ctx=ctx@entry=0x7fb0c0240290,
from_id=from_id@entry=3, id=3, upds=0x0, nupds=5) at
src/cart/swim/swim.c:1079
crt_swim_cli_cb (cb_info=<optimized out>) at src/cart/crt_swim.c:566
...
with log messages
src/cart/swim/swim.c:116 swim_dump_updates() 2 <= 1: {2 A
983719075285041154} {1 A 983719042620850176} {4 S
983718416466575360} {0 A 983719070998986752}
src/cart/swim/swim.c:151 swim_updates_prepare() 2: not bootstrapped
yet with 3
src/engine/init.c:1106 print_backtrace() *** Process 24533 received
signal 11 ***
From "nupds=5, upds=0x0" and the second log message we can infer that the "retry_rc == -DER_NONEXIST" path of crt_swim_cli_cb freed …
> DAOS-12266 cart: Fix swim_dump_updates segfaults

- src/tests/ftest/launch.py
Update launch.py logger timeout to 1200 seconds (still failed timeout)
Test-tag: offline_drain
> DAOS-11925 test: Error running /usr/lib/daos/TESTING/ftest/cart/cart_logtest.py

- src/client/dfuse/dfuse.h
- src/client/dfuse/dfuse_cont.c
- src/client/dfuse/dfuse_core.c
- src/client/dfuse/dfuse_fuseops.c
- src/client/dfuse/dfuse_pool.c
- src/client/dfuse/ops/create.c
- src/client/dfuse/ops/lookup.c
- src/client/dfuse/ops/mknod.c
- src/client/dfuse/ops/readdir.c
- src/client/dfuse/ops/symlink.c
Create a common inode init function to allow us to have a common code-path.
Add a magic value which we check for in close to ensure init has been called.
Use atomics to check for concurrent readdir operations, both on the handle
and on the inode.
> DAOS-8722 dfuse: Add common init function for inodes and checking to readdir.

- SConstruct
The removal of the tesfile builder caused problems on older
scons versions so re-add it.
> DAOS-623 build: Fix build for older versions of scons.

- src/control/server/storage/scm/ipmctl.go
- src/control/server/storage/scm/ipmctl_test.go
During daos_server scm prepare, when the SCM namespace name does not
match the NUMA node index (e.g. namespace1.0 for NUMA-4 or
namespace0.0 for NUMA-1), log a NOTICE-level warning instead of
failing validation.
This will allow continued operation in environments without 1:1
NUMA-to-socket mappings or where ndctl generates namespace names that
don't match the numa_node.
> DAOS-12336 control: Relax validation condition on SCM names

- src/include/daos_srv/pool.h
- src/pool/srv_pool.c
- src/rebuild/srv.c
Check if the leader pool map has been synchronized to all other targets before rebuild start to avoid GPRVER error during rebuild start.
Test-tags: pr rebuild
> DAOS-10681 rebuild: check the global pool map version before rebuild

- src/cart/crt_swim.c
Michael MacDonald noticed segfault
swim_dump_updates (nupds=5, upds=0x0, to_id=2, from_id=3, self_id=2)
at src/cart/swim/swim.c:105
swim_updates_parse (ctx=ctx@entry=0x7fb0c0240290,
from_id=from_id@entry=3, id=3, upds=0x0, nupds=5) at
src/cart/swim/swim.c:1079
crt_swim_cli_cb (cb_info=<optimized out>) at src/cart/crt_swim.c:566
...
with log messages
src/cart/swim/swim.c:116 swim_dump_updates() 2 <= 1: {2 A
983719075285041154} {1 A 983719042620850176} {4 S
983718416466575360} {0 A 983719070998986752}
src/cart/swim/swim.c:151 swim_updates_prepare() 2: not bootstrapped
yet with 3
src/engine/init.c:1106 print_backtrace() *** Process 24533 received
signal 11 ***
From "nupds=5, upds=0x0" and the second log message we can infer that the "retry_rc == -DER_NONEXIST" path of crt_swim_cli_cb freed …
> DAOS-12266 cart: Fix swim_dump_updates segfaults (#11048)

- src/tests/ftest/dfuse/mu_perms.py
- src/tests/ftest/dfuse/mu_perms.yaml
Expand mu_perms.py to chown a directory as a different user and verify permissions.
Test-tag: test_dfuse_mu_perms
> DAOS-10856 test: verify dfuse multi-user chown

- src/object/cli_obj.c
- src/object/obj_tx.c
- src/tests/ftest/daos_test/suite.yaml
- src/tests/suite/daos_extend_simple.c
Use real grp size to get grp idx by shard for enumeration/update,
in case the object is being extended.
Skip the reintegrating shard for read operation.
Add more tests for extending.
> DAOS-12247 object: Use correct grp size for enumeration

- src/tests/ftest/util/data_mover_test_base.py
Use ior_cmd.test_file instead of hardcoded 'testfile'
Test-tag: test_basic_checkout_dm test_io_sys_admin Skip-unit-tests: true
> DAOS-12258 test: fix run_dm_activities_with_ior testfile (#11124)

- src/object/cli_shard.c
- src/tests/suite/daos_obj.c
If we are calling key_query with existing dkey/akey and getting max/min recx, an assertion is hit on non EC object. That assertion is not correct in the code so just remove it.
> DAOS-12332 object: remove wrong assertion in key_query path

- src/control/system/raft/database.go
- src/control/system/raft/database_test.go
- src/control/system/raft/mocks.go
- src/control/system/raft/raft.go
The call to raft.Barrier() was modified to return ErrNotLeader
on leadership loss in order to convey this information back to
dmg, but ResignLeadership() was not updated to include a check
for this error in order to avoid calling raft.LeadershipTransfer()
on a non-leader (which can cause a hang due to blocked channel read).
> DAOS-12239 control: Check for ErrNotLeader in ResignLeadership

- ci/functional/launchable_analysis
> SRE-415 test: Store Launchable data per stage

- src/tests/ftest/launch.py
Increase timeout to 2700, one osa_drain weekly testcase still timeout on log-transfer.
Test-tag: full_regression,osa_drain
> DAOS-11925 test: Error running ftest/cart/cart_logtest.py due to timeout

- src/tests/ftest/dfuse/caching_check.py
- src/tests/ftest/dfuse/caching_check.yaml
Test-tag: test_dfuse_caching_check
- Reduce threshold from 450% to 300%
- Misc cleanup
> DAOS-12259 test: reduce dfuse caching perf threshold (#11116)

- src/control/lib/control/pool.go
Adds sorted output of `dmg pool list` command by pool label,
which makes it a bit more convenient to run with `watch` et el.
Signed-off-by: Denis Barakhtanov <denis.barahtanov@croit.io>
> DAOS-12105 control: Ordered output for dmg pool list

- src/object/cli_shard.c
- src/tests/suite/daos_obj.c
* If we are calling key_query with existing dkey/akey and getting max/min recx, an assertion is hit on non EC object. That assertion is not correct in the code so just remove it.
* remove the is_ec assertion when querying the akey with a preset dkey as that is wrong too.
> DAOS-12332 object: remove wrong assertion in key_query path (#11144)

- src/control/system/database.go
- src/control/system/database_test.go
- src/control/system/raft.go
The call to raft.Barrier() was modified to return ErrNotLeader
on leadership lost in order to convey this information back to
dmg, but ResignLeadership() was not updated to include a check
for this error in order to avoid calling raft.LeadershipTransfer()
on a non-leader (which can cause a hang due to blocked channel read).
> DAOS-12239 control: Check for ErrNotLeader in ResignLeadership (#11163)

- src/tests/ftest/launch.py
Description:
Update launch.py cart logging timeout to 2700 seconds sync with release_2.2.
Test-tag: full_regression,osa_drain
> DAOS-11925 test: Error running ../ftest/cart/cart_log test

- src/client/ds3/ds3_internal.h
- src/client/ds3/object.c
- src/include/daos_s3.h
The function ds3_obj_read() allocates IOV and SGL variables on the stack for the underlying call to dfs_read(). This pattern works for synchronous calls, but it causes a segmentation violation for asynchronous read operations (i.e., when the event structure passed to dfs_read is not NULL).
Fix this by adding an SG list and IOV structures to the ds3_obj and using those variables in the call to dfs_read().
Signed-off-by: Chuck Tuffli <chuck.tuffli@hpe.com>
> DAOS-12181 ds3: Don't use stack allocated variables

- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/control/cmd/daos/util.go
- src/utils/daos_hdlr.c
- src/utils/daos_hdlr.h
- utils/node_local_test.py
Improve output options to ensure reliable output of container
clone and fs copy information (for both standard and JSON output).
Features: datamover
> DAOS-11551 tools: Update daos cmd output for clone/copy 

- src/bio/bio_wal.c
- src/vos/tests/vts_aggregate.c
- src/vos/tests/vts_io.h
- src/vos/tests/vts_wal.c
- Added basic IO test for WAL, it verifies pool space SCM & NVMe usage and updated values after replay.
- Expand basic pool test for WAL as basic pool/cont test.
- Fix entry_move_next() to move the offset correctly.
> DAOS-12214 test: basic IO test for WAL

- src/cart/crt_init.c
- src/cart/crt_internal_types.h
- Maximum number of cart contexts is now set to number of cores by default.
- If CRT_CTX_NUM is set, this value is used instead.
- CRT_SRV_CONTEXT_NUM is used as an upper limit, and reduced from 256 to 64.
> DAOS-12019 cart: Change number of maximum contexts (#10765)

- src/pool/srv_pool.c
When a PS leader steps down, it doesn't reset pse_stop to false. If the same PS replica becomes a new PS leader, events_handler will stop immediately after starting, as shown by these log messages:
12/11-06:50:14.89 [...] rdb_raft_step_down() e572b42d[1]: no longer leader of term 1
[...]
12/11-06:50:14.89 [...] events_handler() e572b42d: stopping
[...]
12/11-06:50:30.15 [...] rdb_raft_step_up() e572b42d[1]: became leader of term 3
[...]
12/11-06:50:30.16 [...] events_handler() e572b42d: starting
12/11-06:50:30.16 [...] events_handler() e572b42d: stopping
This patch resets pse_stop in fini_events and asserts that pse_stop must be false in init_events.
> DAOS-12324 pool: Reset pse_stop in fini_events (#11132)

- src/client/dfs/dfs.c
As part of the MWC work, one can change the SB and the default container chunks size. However if we are setting the chunk size on the root dir, it will override the system default.
Features: dfs
> DAOS-12388 dfs: don't set chunk size on root directory

- src/common/fail_loc.c
- src/object/cli_obj.c
- src/tests/suite/daos_obj_ec.c
- src/vos/vos_io.c
For EC multiple akeys update, it possibly with IO request that "(iov_nr == 0 && iods[i].iod_recxs != NULL)" for array type, server should not reject IO for that case.
Fix a bug in daos_shard_in_fail_value().
Add a test case to reproduce it.
> DAOS-12306 object: fix a bug of server reject IO incorrectly

- src/bio/bio_wal.c
- src/common/dav/dav_iface.c
- src/common/dav/stats.c
- src/common/dav/stats.h
- src/common/dav/tx.c
- counter related to currently allocated memory is now persisted at the end of every transaction.
- Removed check for sysdb in umem_pobj_open()
- Fixed integer overflow in off2lba() wich was inturn causing failures while rehydrating large vos files.
Signed-off-by: sherintg <sherin-t.george@hpe.com>
> DAOS-12383 common: Persist DAV heap statistics

- docs/admin/deployment.md
- src/control/cmd/daos_server/auto.go
Update docs to indicate the need for storage prepare commands before
running local config generate. Fix scanning NVMe when VMD is enabled
by setting the EnableVMD flag in the storage control service during
local command variant execution. VMD should always be used if
available in the case of config generate as there is no input config
in which the user could intentionally disable a VMD prerequisite.
> DAOS-12402 control: daos_server config generate VMD NVMe scan fix

- utils/githooks/find_base.sh
Some users may have the remote set to a different remote than
origin.   Allow users to set DAOS_ORIGIN to accomodate this.
> DAOS-623 ci: Allow user to set alternative origin for github

- src/bio/bio_monitor.c
- src/tests/suite/daos_nvme_recovery.c
NVMe recovery tests are currently timing out because automatic fault
detection is assumed to be active in the tests but is disabled by
default in the engine.
Fix by moving test specific faulty check to the beginning of
bio_monitor.c:is_bbs_faulty() so true is returned when fail loc has
been set (from daos_nvme_recovery.c) regardless of whether auto
detection is enabled or not.
Test-tag: daos_core_test_nvme
> DAOS-12039 test: Fix NVMe recovery tests

- src/control/server/mgmt_pool_test.go
Add a sorter cmp option to ensure stable comparisons
between actual/expected PoolProperties.
> DAOS-10752 control: Fix flaky PoolCreate unit test

- src/control/server/mgmt_drpc.go
- src/control/server/mgmt_drpc_test.go
- src/control/server/mgmt_pool.go
- src/control/server/server.go
- src/control/system/database.go
- src/mgmt/cli_mgmt.c
When a MS leader steps up, it checks the list of pools for any
not found in a Ready state. With this change, a pool in the
Creating state will be ignored rather than destroyed, on the
theory that the create may be completing on the previous leader.
Update the pool svc RAS event handler to automatically set
a Creating pool to Ready, on the theory that the pool create
has most likely completed, given that it is sending us a
svc ranks update event.
Finally, modify dc_mgmt_pool_find() to retry on -DER_NONEXIST
errors which can result from stale MS replica reads.
> DAOS-12209 control: Don't clean up Creating pools on MS step-up (#11157)

- src/container/srv_container.c
- src/container/srv_layout.c
- src/container/srv_layout.h
- src/control/cmd/daos/property.go
- src/include/daos_prop.h
- src/pool/srv_layout.c
- src/pool/srv_pool.c
- src/tests/ftest/pool/label.py
If the supplied label matches one of the special values
indicating that the label was unset, reject it as invalid.
Features: pool container datamover
> DAOS-8518 pool: Check input for default label values (#8056)

- src/cart/crt_context.c
- src/cart/crt_hg.c
- src/cart/crt_hg.h
- src/cart/crt_init.c
- src/cart/crt_internal_types.h
- src/tests/ftest/cart/no_pmix_multi_ctx.c
The crash happened due to bdev module using crt_context_create() and crt_context_destroy() in parallel from different threads, causing internal messup of context indecies and associated tables.
- Introduce list of free indecies for context ids and helper functions to get/put the index.
- Use free index instead of 'context number' as a context id.
> DAOS-12012 cart: Segfault in OFI-RXM when using SPDK DAOS bdev module

- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/control/cmd/daos/util.go
- src/utils/daos_hdlr.c
- src/utils/daos_hdlr.h
- utils/node_local_test.py
Improve output options to ensure reliable output of container
clone and fs copy information (for both standard and JSON output).
> DAOS-11551 tools: Update daos cmd output for clone/copy (#11189)

- src/control/cmd/daos/container.go
- src/control/cmd/dmg/cont.go
- src/control/cmd/dmg/cont_test.go
- src/control/cmd/dmg/pool.go
- src/control/lib/daos/acl.go
- src/control/lib/ui/acl.go
- src/control/lib/ui/acl_test.go
Centralizes input handling for user/group principals, and
improves user-friendliness by automatically converting bare
names to principals as necessary.
> DAOS-12417 security: Add ui.ACLPrincipalFlag type

- src/control/cmd/daos_server/auto_test.go
- src/control/cmd/dmg/auto_test.go
- src/control/lib/control/auto.go
- src/control/lib/control/auto_test.go
- src/control/lib/control/mocks.go
- src/control/server/storage/config.go
- src/control/server/storage/config_test.go
Add support for MD-on-SSD in config generate. When
automatically generating a config with dmg or daos_server tools
if --use-tmpfs-scm is set then populate bdev tiers appropriately.
NVMe SSDs on same NUMA as engine to be split into bdev tiers:
-  1 SSD: tiers 1
-  2-5 SSDs: tiers 1:N-1
-  6+ SSDs: tiers 2:N-2
Configs generated will not have explicit roles assigned to each bdev
tiers, instead roles will be assigned implicitly based on the bdev
tiers during control-plane validation on daos_server service start.
Implicit role assignments are decided based on the following rules:                                          
- For 1 bdev tier, all roles will be assigned to that tier.                                        
- For 2 bdev tiers, WAL role will be assigned to the first bdev tier
and …
> DAOS-11859 control: Add MD-on-SSD bdev tiering to config generate cmds

- src/client/dfs/dfs.c
When creating a file or directory with O_CREAT without O_EXCL, do the conditional insert similarly as if O_EXCL was provided, but depending on the result, go ahead and open the file if the error was EEXIST. This should improve file or directory creation performance when O_CREAT is used without O_EXCL, but add a smaller penalty if the file already exists.
Features: dfs
> DAOS-12411 dfs: change create logic for O_CREAT without O_EXCL

- src/tests/ftest/container/boundary.py
- src/tests/ftest/container/boundary.yaml
- src/tests/ftest/pool/create_capacity.py
- src/tests/ftest/pool/create_capacity.yaml
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/test_utils_pool.py
Adding a TestPool param to enable/disable elevating log
mask to DEBUG during pool create/destroy. Currently, this is
done by default for every pool create and destroy dmg call
hence adding significant test run time, causing tests to
timeout in multiple pool scenarios.
Test-tag: pool_create_tests test_container_boundary
> DAOS-12309 test: Introduce param to toggle log mast for pool create/destroy

- src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
Test-tag: ec_disabled_rebuild_single
Test-repeat: 6
Summary:
- Increase the test timeout from 400 to 550 seconds.
- Remove the pool mode to match master branch.
> DAOS-12317 test: Update rebuild_disabled_single test timeout.

- src/cart/crt_init.c
- split data_init() into part that can be initialized multiple times and a part that should only be initialized once, such as mutex init
> DAOS-12408 cart: Split data_init()

- src/control/server/storage/bdev/backend.go
- src/control/server/storage/bdev/backend_class.go
- src/control/server/storage/bdev/backend_class_test.go
Create AIO files for NVMe/SPDK emulation with 0600 perms. Remove the
created file if either the permissions or ownership change fails and
add unit test coverage
> DAOS-12290 control: Bdev class file should have 0600 perms (#11238)

- src/control/cmd/daos/container.go
This should have landed for 2.2.0, but better late than never.
Retains the existing --label flag but indicates deprecation in
2.4+.
> DAOS-12440 tools: Add positional support for label on cont create

- src/common/tests_dmg_helpers.c
- src/include/daos/tests_lib.h
- src/tests/suite/daos_test_common.c
(#11015)
Some tests (e.g., daos_test - rebuild_ec) currently might fail due the invocation of dmg stop failing to stop the specified rank. In these cases, the invocation ( via system() ) returns "success" but the failure to stop the rank causes the overall test to fail.
This PR replaces the dmg calls via system() with the daos_dmg_json_pipe() function implemented within the DAOS tests helpers module.
> DAOS-12221 test: Update implementation of dmg stop, dmg start in test code.

- src/tests/ftest/io/large_file_count.py
- src/tests/ftest/io/large_file_count.yaml
io/large_file_count.py is consistently failing since moved to medium cluster. Reason being, test timeouts while running mdtest as the workload is handled by a single client now compared to 3 client nodes previously. Reducing the workload to accommodate the test on medium cluster will defeat the purpose of the test. Hence, moving back to large cluster.
Test-tag: test_largefilecount
> DAOS-12241 test: Moving io/large_file_count.py back to large cluster

- src/control/server/ctl_storage.go
- src/control/server/ctl_storage_rpc_test.go
- src/control/server/ctl_svc_test.go
- src/control/server/harness.go
- src/control/server/instance_drpc.go
- src/control/server/instance_test.go
- src/control/server/storage/bdev.go
- src/control/server/storage/bdev_test.go
The data race was made possible because of sharing object references
too liberally. Close the gap by reducing the scope of reference
sharing when updating in-use bdev stats.
> DAOS-12366 control: Limit reference sharing when updating bdev stats

- src/control/cmd/daos/container.go
- src/control/cmd/dmg/cont.go
- src/control/cmd/dmg/cont_test.go
- src/control/cmd/dmg/pool.go
- src/control/drpc/acl.go
- src/control/lib/ui/acl.go
- src/control/lib/ui/acl_test.go
Centralizes input handling for user/group principals, and
improves user-friendliness by automatically converting bare
names to principals as necessary.
> DAOS-12417 security: Add ui.ACLPrincipalFlag type (#11258)

- src/tests/ftest/io/large_file_count.py
- src/tests/ftest/io/large_file_count.yaml
io/large_file_count.py is consistently failing since moved to medium cluster. Reason being, test timeouts while running mdtest as the workload is handled by a single client now compared to 3 client nodes previously. Reducing the workload to accommodate the test on medium cluster will defeat the purpose of the test. Hence, moving back to large cluster.
Test-tag: test_largefilecount
> DAOS-12241 test: Moving io/large_file_count.py back to large cluster (#11299)

- src/bio/bio_context.c
- src/bio/bio_internal.h
- src/bio/bio_monitor.c
- src/engine/ult.c
- src/include/daos_srv/bio.h
- src/mgmt/srv_internal.h
- src/mgmt/srv_query.c
Two fixes:
1. dev query ult should be run on the owner xstream, introduce a new api to return dev's owner xs target id.
2. SYS XS might be owner of device, fix to pass correct XS type when creating ults.
> DAOS-12372 mgmt: fix dev query assertion with MD-ON-SSD enabled

- src/object/obj_verify.c
Check object existence after object list before enumeration unpack during EC object verification.
> DAOS-10844 object: check object existence before unpack

- src/tests/ftest/server/metadata.py
To address slowdowns in orterun arbitrary command launching on release/2.2 branch tests, replace the use of orterun with clush, to launch ior commands in test_metadata_server_restart.
Skip-test-centos-7-rpms: true
Skip-test-el-8.5-rpms: true
Test-tag: test_metadata_server_restart test_basic_config
> DAOS-12319 test: invoke ior with clush not orterun

- src/object/obj_ec.h
- src/object/obj_internal.h
- src/object/srv_ec.c
- src/object/srv_internal.h
- src/object/srv_obj.c
- src/object/srv_obj_remote.c
- src/tests/suite/daos_obj_ec.c
- src/tests/suite/daos_rebuild_ec.c
Remove obj_ec_rw_req_split from obj_rw_obj_handler(), and
only allocate the memory and copy for multiple IODs cases.
> DAOS-11423 object: remove obj_ec_rw_req_split

- src/bio/bio_device.c
Commit 31ca6bd5c9a0e8ab3112f014ca6de30e2e68df64 attempted to fix
Coverity issue 838332 - led_device_action needs to return in case of
error, The issue is invalid and the fix caused the function to return
early and not populate the state in the return obj.
> DAOS-12469 bio: Fix regression preventing LED state return

- src/object/cli_obj.c
- src/tests/suite/daos_obj_ec.c
- src/vos/vos_io.c
For EC multiple akeys update, it possibly with IO request that "(iov_nr == 0 && iods[i].iod_recxs != NULL)" for array type, server should not reject IO for that case.
Add a test case to reproduce it.
> DAOS-12306 object: fix a bug of server reject IO incorrectly (#11108)

- src/client/dfs/dfs.c
- src/tests/suite/dfs_unit_test.c
the mtime and ctime update according to the max epoch changes were missed in lookupx.
Features: dfs datamover
> DAOS-10258 dfs: lookupx should properly set mtime/ctime in stbuf

- src/tests/ftest/dfuse/daos_build.py
- src/tests/ftest/launch.py
- src/tests/ftest/process_core_files.py
Add logic to not fail the DaosBuild test if it creates a forefile,
it sometimes creates a corefile from conftest which is expected
and should not cause a test failure.
Fix a bug where the program that generated the core file was read
incorrectly.
Add some debugging where the DaosBuild test fails.
> DAOS-12415 test: Allow for tests which may produce core files.

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
When the --size=% flag is used, the pool create command
performs a storage scan in order to determine the actual
available storage across the ranks. In cases where the
system has not started yet (i.e. pool create is run
immediately after storage format completes), the user may
receive a confusing error message. This patch changes the
flow to perform a system query before storage scan so that
the user receives a normal error if the MS hasn't started
yet.
> DAOS-12124 control: Fix pool create error after format

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_leader.c
If the user/admin ony wants to check some specified pool(s), then DAOS engine logic needs to filter out those pools that are not in the check list.
If the user/admin does not specify the pools list when start check, then by default, the DAOS engine will do:
1. Resume former paused pools if have, or
2. (re)check all pools from the beginning.
> DAOS-12471 chk: do not check non-specified pool

- utils/rpms/daos.spec
libuuid-devel has been a DAOS BR for a very long time but has been
masked  behind libfabric's BR for libpsm2-devel which itself BR'd
libuuid-devel.
Now that we have removed the libpsm2-devel BR from libfabric,
libuuid-devel is not being installed any more, and DAOS needs it.
Remove historic and now unnecessary dependency on libcurl4 on SUSE
distros.
> DAOS-12558 build: BR libuuid-devel

- src/tests/ftest/launch.py
- src/tests/ftest/util/results_utils.py
- Support older versions of avocado xml and html result generation
- Add logging to launch.py to print an error if the expected xml or html
is not generated
Test-tag: pr
> DAOS-12454 test: fix leap generation of results.xml,html

- src/control/cmd/daos/filesystem.go
passing pool and container explicitly (not with path) should require the dfs-path argument. This improve the error output to something more user friendly.
> DAOS-12499 tools: improve error logging of dfs fs get-attr

- src/include/daos_srv/vos.h
- src/pool/srv_pool_scrub_ult.c
- src/vos/tests/pool_scrubbing_tests.c
- src/vos/vos_pool_scrub.c
Because telemetry metrics aren't persisted across system reboots, the first time the scrubber runs, it should increment the corrupted counter for any already marked corrupted values.
When the scrubber first starts, the containers' csummer might not have initialized yet, so a check was added to make sure all containers' csummers are loaded if csums are enabled. Really it looks at if the sc_cont_child's properties have been fetched. If so then the csummer should have been initialized.
Reduced the forced sleep_time between vos_scrub_pool calls because 1 second is the minimum frequency.
Features: scrubbing checksum
> DAOS-9511 csum: Initial VOS scan counts corrupted values

- docs/admin/vmd.md
Specifying individual VMD backing device addresses is not supported so
remove the suggestions in the admin guide. It it is not possible to
share devices from the same VMD domain between engine processes.
Doc-change: true
> DAOS-12228 docs: Remove info about VMD backing addresses in cfg

- src/include/daos/mem.h
- src/vos/evtree.c
- src/vos/ilog.h
- src/vos/vos_internal.h
- src/vos/vos_obj_index.c
- src/vos/vos_pool.c
- src/vos/vos_space.c
- src/vos/vos_tree.c
This is a precursor to subsequent changes I will make in my evtree dynamic root patch.  Rather than defining exact slab values, we define common known ones and use the size, aligned to 32 bytes to calculate the slab id.  This allows us to use the slab allocator for integer key nodes as well since they didn't previously fit the hard coded size definition.
> DAOS-11405 vos: Simplify vos slab allocation

- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
Since #11157 landed, there is a possibility that a retried
pool create may encounter a pool that was automatically
promoted to the Ready state. Instead of returning -DER_ALREADY
(which is unhandled and unhelpful) to the dmg side, just
populate the pool create response as if the retried create handler
was responsible for doing it.
> DAOS-12524 control: Return created pool on retry

- src/tests/ftest/util/dfuse_utils.py
Use positional <mount> <pool> <cont> args with dfuse instead of the older formatted arguments.
Test-tag: dfuse,vm
> DAOS-623 test: use dfuse positional args

- src/include/daos_srv/daos_engine.h
- src/object/obj_rpc.h
- src/object/srv_internal.h
- src/object/srv_obj_migrate.c
- src/pool/srv_target.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/tests/suite/daos_rebuild_simple.c
Add rebuild generation to migrate tls to avoid the tls being wrongly picked by rebuild retry job, which can cause some objects being skipped during
rebuild/migration.
> DAOS-12074 rebuild: add generation to migrate tls

- src/container/srv_target.c
- src/include/daos_srv/container.h
- src/rebuild/scan.c
During reclaim or failure reclaim, the object are being discarded from the container, the aggregation should be aborted to let discarding proceed, to avoid EBUSY.
> DAOS-10681 container: add sc_discarding

- src/bio/bio_xstream.c
- utils/run_test.sh
Fix the standalone vos_tests failure related to reading JSON config
file. nvme_glb.bd_nvme_conf is freed stack memory in bio_xsctxt_alloc()
when spdk_subsystem_init_from_json_config(nvme_glb.bd_nvme_conf, ...)
is called (as memory confined in scope to bio_nvme_init). Allocate by
copying string and free explicitly on bio_nvme_fini.
Co-authored-by: Dmitry Ivanov <dmitry.ivanov2@hpe.com>
> DAOS-12580 test: Fix vos md-on-ssd unit tests

- src/tests/ftest/cart/SConscript
We had a hidden dependency here that was not specificially called out.
> DAOS-12611 build: Add protobufc dependency to tests.

- SConstruct
With recent changes to speed up the builds, this option causes build failures, usually when switching between branches.  This is indicative of some missing dependency relationship in SCons but for now, just disable the option, which is the SCons default. This ticket is filed to find and fix the issue and reenable this option.
> DAOS-12608 build: Remove option to cache implicit dependencies

- src/container/srv_container.c
- src/container/srv_target.c
- src/include/daos_srv/container.h
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
Only update the agg boundary if incoming boundary epoch is larger than the current boundary epoch, since boundary epoch distribute might be out of order.
> DAOS-11964 container: update agg boundary eph

- src/container/srv_target.c
Aggregation flags are being ignored in favor of a hard coded full scan. This would bypass all aggregation optimizations.
> DAOS-12639 object: Revert an accidental change with checksum scrubbing

- src/include/daos_srv/vos.h
- src/include/daos_srv/vos_types.h
- src/vos/vos_internal.h
- src/vos/vos_iterator.c
- src/vos/vos_pool_scrub.c
In some cases, we may yield in the middle of a callback and need to request a full reprobe.  The checksum scrubber is such a case. It could, in theory, read a value, start processing it for checksum scrubbing, and have the value deleted before it is able to continue.  If this happens, we can end up reading bad data, or worse, causing a system crash.
Features: scrubber
> DAOS-12610 vos: Add iterator API to validate current position

- src/mgmt/srv_query.c
If MD-ON-SSD is not enabled, sys xs will not have NVME setup.
> DAOS-12444 mgmt: use correct init xs type for non-MD-on-SSD

- ci/provisioning/post_provision_config.sh
Test-tag: pr test_sparsefile
The default ssh-kegen key generation has been changed from being PEM, and our EL-8 distro version of paramiko of 2.4.3 is too old to support that format.
> SRE-1665 test: update ssh-keygen to fix dfuse/sparse_file.py

- src/tests/ftest/launch.py
- src/tests/ftest/util/results_utils.py
Test-tag: pr
Combination of #11330 and #11391
- Support older versions of avocado xml and html result generation
- Add logging to launch.py to print an error if the expected xml or html is not generated
> DAOS-12454 test: fix leap generation of results.xml,html (#11330)

- src/gurt/telemetry.c
- src/gurt/tests/test_gurt_telem_producer.c
If the user increases the number of targets in the server config, the size of the old shmem region may not be large enough for per-target metrics. Instead of reattaching to the old region, we now delete it if it exists before creating the new one.
> DAOS-12364 gurt: Delete old metrics shmem region on startup

- src/cart/crt_init.c
Set default envariable setting to enable MR cache for CXI provider by default.
> DAOS-12528 cart: enable MR cache by default for CXI (#11351)

- src/tests/ftest/telemetry/telemetry_pool_metrics.py
There is not yet a dedicated metric (as the `engine_pool_resent` one for update operations) allowing to count the number of fetch operations which have failed.
To alleviate this issue, the `engine_net_req_timeout` is used to weight the expected number of fetch operations.
Sadly, It was not possible to properly check if this workaround is 100% effective.
Indeed, it was not possible to reproduce fetch operations error: this PR was submitted multiple times to the CI (with different number of repetitions) without being able to have failed fetch operations (and thus have been re-received).
However, it was possible to check that when update operations were failing (i.e.  `engine_pool_resent` > 0), the `engine_net_req_timeout` was most of the time > 0.
Thus, the `engine_net_req_timeout` should …
> DAOS-12128 test: fix telemetry expected values

- src/control/run_go_tests.sh
If the gofmt check fails in run_go_tests.sh, emit a junit
result to the test dir so that the stage fails.
> DAOS-12045 test: Emit junit for gofmt failure

- src/tests/ftest/daos_vol/h5_suite.yaml
- src/tests/ftest/mpiio/hdf5.yaml
- src/tests/ftest/util/server_utils_params.py
As a workaround for DAOS-12581 temporarily increate the crt_timeout to 180 seconds.  When a proper fix is implemented this should be reverted.
Test-tag: test_hdf5 test_daos_vol_mpich test_snapshot_aggregation test_ec_mdtest_smoke
> DAOS-12581 test: Temporarily increase crt_timeout

- src/common/mem.c
- src/include/daos/mem.h
1. Change granularity of chunk to 4K
2. Use maximum mapped to allocate page data to decouple from allocation of all pages.  The main struct now just has 16 bytes including a pointer to data that is only valid if the page is mapped (all pages for now are mapped).
> DAOS-12612 common: Make some adjustments to umem cache

- docs/admin/administration.md
- src/bio/README.md
- src/control/cmd/dmg/storage_query.go
Correct instructions regarding specifying LED identify time period by
removing references to environment variable and instead recommending
the use of --timeout dmg option.
> DAOS-12647 doc: Update LED instructions with custom timeout

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
Instead of restricting the inputs to whole integers, allow
float-based inputs for more precision and control over
storage tier allocation.
> DAOS-12561 control: Allow floats in pool create tier ratios

- src/tests/daos_racer.c
- src/tests/dts.c
1. now simple test are put in medium test, however it only tried to use 3 servers, after 
default fault domain was changed from rank to node, it was not enough to run all EC object class
for daos_race test, like what commit (DAOS-10215 container: set default fault domain level on NODE (#9631)) did,
change default domain to rank in tests  when creating containers.
2. oclass was declared as u32, fix to use correct declaration.
> DAOS-12589 test: use correct oclass declaration

- src/gurt/telemetry.c
Trying to fix coverity issue 979469 in master.
It may be safer to check cur since conv_ptr() could return NULL.
> DAOS-12658 gurt: to check whether cur is NULL before dereference

- src/cart/crt_swim.c
- src/cart/swim/swim.c
- src/include/cart/swim.h
When a swim member whose self ID is SWIM_ID_INVALID (e.g., before the
engine receives its rank from the MS) receives an incoming swim RPC, it
replies with -DER_UNINIT. When a swim member receives such a -DER_UNINIT
reply, it simulates an ALIVE update to indicate that the sender of the
reply is alive. This turns out to be insufficient if a rankless swim
member becomes suspected. The simulated ALIVE update cannot override the
SUSPECT update, as they have the same incarnation. Consequently, there
will eventually be a DEAD update about the rankless swim member, even
though it is actually alive.
This patch changes the swim RPC handler so that the rankless swim member
will simulate the ALIVE update itself, shorting its local swim state,
instead of replying with -DER_UNINIT. The rankless swim …
> DAOS-12387 cart: Improve swim rankless operation

- src/include/daos_srv/vos.h
- src/pool/srv_pool_chkpt.c
- src/vos/vos_pool.c
1. @chkpt_ctx need be set and cleared properly.
2. ABT_eventual_set() accept ABT_eventual rather than ABT_eventual *, refine
to reuse ABT_eventual
> DAOS-12612 pool: fixes for checkpoint

- src/common/misc.c
- src/object/cli_ec.c
- src/object/cli_obj.c
- src/tests/suite/daos_obj_ec.c
Fix a bug of after obj_ec_recov_data() did not set sgl's iov_len. 
Added a test case to verify it.
> DAOS-11728 object: refine sgl iov_len handling in EC data recovery

- src/control/lib/daos/status.go
- src/control/security/config.go
- src/control/security/config_test.go
- src/control/server/security_rpc.go
- src/control/server/security_rpc_test.go
- src/include/daos_errno.h
- Verify the client certificate directory is accessible during DAOS server startup.
- Provide a more descriptive error if the client certs can't be loaded at runtime.
Features: security control
> DAOS-12072 control: Check client cert dir on startup

- src/control/server/init/setup_spdk.sh
Running DAOS/SPDK via UIO as an unprivileged user is no longer
supported so we don't need to modify the relevant file ownership.
> DAOS-12334 control: Do not print spurious errors on SPDK setup

- ci/provisioning/post_provision_config_common.sh
- ci/provisioning/post_provision_config_common_functions.sh
- ci/provisioning/post_provision_config_nodes.sh
- ci/provisioning/post_provision_config_nodes_EL_8.sh
during node provisioning, so that the network stack and/or version can
be chosen per test run.
SRE-549 test: Install MOFED ucx-* packages (#10756)
Install ucx-{cma,ib,knem,rdmacm,xpmem} from the MOFED repo.
Move the modulefile module creation from being EL8 specific to being
done in post_provision_config_nodes() on all distros.
Fixes: DAOS-12361
> SRE-549 test: Install MOFED ... (#10628)

- src/control/server/ctl_ranks_rpc.go
- src/control/server/ctl_ranks_rpc_test.go
- src/control/server/instance_drpc.go
- src/control/server/mgmt_system.go
- src/control/server/mgmt_system_test.go
- src/control/system/membership.go
Return code should be non-zero if sys stop fails due to non-responsive
ranks. To fix, ensure the Errored field is set appropriately in a
MemberResult struct each time the NonResponsive state is set. Change
all create calls to use the NewMemberResult() helper which will do 
this for us.
- MemberResults with unresponsive state have errored flag set
- RC reflects member state error appropriately
- Updated unit tests
> DAOS-12308 control: Fix dmg system stop RC

- ci/provisioning/post_provision_config.sh
Test-tag: pr test_sparsefile
The default ssh-kegen key generation has been changed from being PEM, and our EL-8 distro version of paramiko of 2.4.3 is too old to support that format.
> SRE-1665 test: update ssh-keygen to fix dfuse/sparse_file.py (#11368)

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_rpc.c
- src/engine/srv.c
- src/vos/vos_dtx.c
1. Decrease DTX_RPC_HELPER_THD_DEF, then most of DTX commit RPCs will be sent via helper XS ULT.
2. Increase sleep time for DTX cleanup ULT schedule interval.
3. Fix vos_dtx_set_flags_one to allow set PARTIAL_COMMITTED flag against committable DTX entry.
4. Some debug log message.
> DAOS-12007 dtx: misc fixes for DTX related issues

- src/object/srv_obj_migrate.c
- src/tests/suite/daos_rebuild_ec.c
Both EC reintegration and rebuild should use force degraded fetch to make sure both full data cell shard will be reintegrated, even though it may be covered by partial update.
> DAOS-12631 object: force degrade fetch for EC reintegration

- src/common/tests/SConscript
Since commit 6711cc9cb15d73447972c0f000c8a0f30bb962db the Env is not passed as the first parameter of
d_test_program() method since it is its "self" now. But this behavioral change had mistakenly not been propagated to the "STACK_MMAP==1" conditional branch.
> DAOS-12584 build: fix d_test_program() method's prototype

- src/container/srv_container.c
Cherry pick [12cf6f8](https://github.com/daos-stack/daos/commit/12cf6f85fd5799c142aa89100684e1a5d2d7292a) from master to release/2.2.
Test-tag: container test_container_user_acl datamover,-test_dm_posix_meta_entry_dcp
> DAOS-12501 container: Container label may not exist.

- src/control/cmd/daos/container.go
- src/control/cmd/daos/pool.go
After the refactoring of the daos cont tool's --path handling
logic, a leak was detected upon landing. This patch removes
a useless allocation and assignment.
> DAOS-8938 tools: Remove unused pool label field

- src/common/dav/dav_iface.c
- src/engine/srv.c
- src/mgmt/srv_internal.h
- src/mgmt/srv_target.c
- src/vos/vos_pool.c
- The umempobj_create/open/close serialization lock vos_pmemobj_lock is removed. The current pmdk code already serializes it using an internal global mutex lock. The md_on_ssd allocator does not require serialization.
- The vos file allocation during pool create is now parallized using threads for md_on_ssd as fallocate on tmpfs takes considerably long time to complete. These threads are bound to the cpus where the vos file will be hosted.
> DAOS-11409 mgmt: Improve pool create, startup time with md_on_ssd

- debian/daos-server-tests.install
- docs/overview/data_integrity.md
- src/object/rpc_csum.c
- src/tests/SConscript
- src/tests/rpc/SConscript
- src/tests/rpc/rpc_tests.c
- src/vos/tests/vos_cmd.c
- utils/rpms/daos.rpmlintrc
- utils/rpms/daos.spec
- utils/run_test.sh
Introduction of rpc unit testing. This initial change only has tests for the encoding, decoding, and freeing of checksum related structures. It will be easy to add other unit style tests for other structures.
This change also makes it easier to measure how much time is spent in the rpc functions. This is especially helpful for decoding when memory allocation occurs. A future change will add timing measurements for the checksum related RPC functions.
> DAOS-12683 csum: RPC Unit Tests

- src/tests/ftest/dfuse/posix_stat.py
The test failed because the created file size is much smaller than the expected size (500MB vs 117.75MB). This may be due to the slowness in VM. Move the test to hw,medium.
Test-tag: test_stat_parameters
> DAOS-12348 test: Move dfuse/posix_stat.py to hw,medium from vm

- src/control/cmd/dmg/pretty/check.go
- src/control/lib/control/check.go
If a pool is unchecked, don't include it in the count of
checking/checked pools.
> DAOS-12471 chk: Query output should only count checked pools

- src/tests/ftest/util/daos_utils.py
Test-tag: pr daos_cmd DaosBuild
Commit 3934417 accidentally removed the implicit string conversion for set_attr, so make it explicit to cover all cases.
> DAOS-8938 test: fix str conversion for set_attr

- src/tests/ftest/server/multiengine_persocket.yaml
Test-Only for baseline 2.3.104: allow-empty
> DAOS-12570 test: multiple engine per socket test needs update based on the latest DAOS changes.

- src/object/cli_ec.c
- src/object/obj_internal.h
- src/object/obj_verify.c
During EC data degraded fetch, it will reset the sgl buffer size by replied data size from 1st degraded parity fetch, but it might be shorter than the real size, since ioc_trim_tail_holes() might trim the tail size(see akey_fetch).
So let's set the sgl size in recovery fill back process, instead of relying on the data size.
> DAOS-12709 object: Do not reset sgl size for EC data recovery

- src/container/srv_target.c
- src/engine/sched.c
- src/mgmt/srv_pool.c
- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/srv_ec_aggregate.c
- src/object/srv_mod.c
- src/object/srv_obj.c
- src/vos/SConscript
- src/vos/evtree.c
- src/vos/ilog.c
- src/vos/tests/SConscript
- src/vos/vos_common.c
- src/vos/vos_container.c
- src/vos/vos_gc.c
- src/vos/vos_io.c
- src/vos/vos_iterator.c
- src/vos/vos_obj.c
- src/vos/vos_obj_cache.c
- src/vos/vos_obj_index.c
- src/vos/vos_pool.c
- src/vos/vos_query.c
- src/vos/vos_ts.h
Make correct use of DF_RC in D_ERROR calls
Fix an issue with vos internal header files, remove the -I option
and use "" rather than <> for internal headers.
> DAOS-12702 vos: Update logging and includes for vos/object.

- src/control/server/ctl_ranks_rpc.go
- src/control/server/ctl_ranks_rpc_test.go
- src/control/server/instance_drpc.go
- src/control/server/mgmt_system.go
- src/control/server/mgmt_system_test.go
- src/control/system/membership.go
Return code should be non-zero if sys stop fails due to non-responsive
ranks. To fix, ensure the Errored field is set appropriately in a
MemberResult struct each time the NonResponsive state is set. Change
all create calls to use the NewMemberResult() helper which will do
this for us.
- MemberResults with unresponsive state have errored flag set
- RC reflects member state error appropriately
- Updated unit tests
> DAOS-12308 control: Fix dmg system stop RC (#11483)

- src/pool/srv_pool.c
> DAOS-8714 pool: move pool map transfer outside of the wr lock (#11452)

- src/cart/utils/memcheck-cart.supp
Fix a spurious Valgrind error.
> DAOS-12690 build: Add go runtime suppression

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_rpc.c
- src/dtx/dtx_srv.c
- src/engine/init.c
- src/engine/srv.c
- src/include/daos_srv/dtx_srv.h
If possible, always use helper XS to for DTX RPC, that will
reduce load on the main XS and try to avoid DTX RPC timeout.
It also unifies the RPC sender logic for all DTX RPCs.
> DAOS-12509 dtx: always use helper XS for DTX RPC

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_rpc.c
- src/dtx/dtx_srv.c
- src/engine/init.c
- src/engine/srv.c
- src/include/daos_srv/dtx_srv.h
- src/vos/ilog.c
- src/vos/ilog.h
- src/vos/tests/vts_ilog.c
- src/vos/vos_dtx.c
- src/vos/vos_ilog.c
- src/vos/vos_ilog.h
- src/vos/vos_io.c
- src/vos/vos_obj.c
- src/vos/vos_obj_cache.c
- src/vos/vos_obj_index.c
- src/vos/vos_query.c
This is combined patch with the following three commits:
1. PR#11413: 72f4a9b456d9b104e71b36ba3c356b24515ca13a
1.1 Decrease DTX_RPC_HELPER_THD_DEF, then most of DTX commit RPCs
will be sent via helper XS ULT.
1.2. Increase sleep time for DTX cleanup ULT schedule interval.
1.3. Fix vos_dtx_set_flags_one to allow set PARTIAL_COMMITTED flag
against committable DTX entry.
1.4. Some debug log message.
2. PR#11416: 6bd99af40422703299b5608212bf738b0f08d511
When update ilog for update or punch, we fetch related ilog entries
firstly, that may hits many uncommitted DTX entries on non-leaders.
If it is for non-conditional modification, then it will not trigger
DTX refresh nor client side RPC retry. But if it is for conditional
modification, then the upper layer caller will get -DER_INPROGRESS.
Under …
> Soak: combined patches for DAOS-[12007,12491,12509]

- src/engine/ult.c
If it is async mode, callback will access callback args, need make sure memory could be not freed until it is no longer used any more.
> DAOS-12744 engine: fix possible use after free in dss_ult_execute()

- src/tests/ftest/io/parallel_io.py
- src/tests/ftest/util/general_utils.py
- src/tests/ftest/util/results_utils.py
- src/tests/ftest/util/slurm_utils.py
- src/tests/ftest/util/yaml_utils.py
- Fill in auto-generated _description_ doc strings
- Fill in auto-generated _type_ doc strings
- Fix some spelling mistakes
> DAOS-623 test: update some missing docstrings

- src/client/dfuse/ops/lookup.c
Handle a race condition where create returns an open file, when
this occours set the inode pointer correctly in the file
handle.
> DAOS-12714 dfuse: Avoid a dangling pointer when create returns an existing file.

- utils/node_local_test.py
> DAOS-12180 test: cleanup log_mask passing in NLT

- src/pool/srv_iv.c
Since pool_tgt_connect/prop_update/refresh_hdl might yield due to connective operation, so it need check sp_stopping again before pool_iv_ent_copy, in case the entry has been destoryed.
> DAOS-12732 pool: recheck pool stopping in pool_iv_ent_refresh

- src/tests/ftest/dfuse/mu_mount.py
- src/tests/ftest/dfuse/mu_mount.yaml
Test-tag: DfuseMUMount
Add case to verify dfuse multi-user UNS behavior.
- Verify a container created by another user, with a UNS path in dfuse, automatically grants container ACLs to the dfuse user.
-  Verify the other user and dfuse user can access the container through dfuse.
-  Verify that revoking the container ACLs for the dfuse user only prevents access for
> DAOS-10859 test: verify dfuse multi-user UNS

- src/control/lib/dlopen/dlopen.go
dlerror() may not be thread-safe, depending on the implementation. It is possible that after clearing dlerror(), we could encounter a race with another thread.
In the DAOS control plane context, we always expect dlsym to return a non-NULL value if it succeeded. This avoids detecting an error set by another thread, when the current thread's dlsym() succeeded.
> DAOS-12689 control: Don't return an error if dlsym succeeded

- src/bio/bio_xstream.c
- src/control/server/config/server.go
- src/control/server/config/server_test.go
Use memory from any NUMA node when allocating DMA buffer when the
engine is using the legacy core allocation algorithm. Enable legacy
mode whenever a non-zero first_core value is specified in the server
config file or if a single engine on NUMA-0 is unpinned.
> DAOS-10472 bio: Use hugepages from any NUMA in legacy mode (#11594)

- src/vos/storage_estimator/common/dfs_sb.py
- src/vos/storage_estimator/common/explorer.py
- src/vos/storage_estimator/common/util.py
Array metadata is stored in an array value now rather than a single value.
Also, remove limitation on io_size setting
> DAOS-623 common: Fix array metadata in storage estimator

- src/tests/ftest/erasurecode/rebuild_fio.py
Before this change, ec offline and online rebuild fio tests failed
intermittently in tearDown during container destroy (with -DER_IO).
A suspicion was that the pool rebuild triggered by the test stopping
an engine may not have finished by the time the test went into
tearDown (just after running the fio read workload). i.e., the
container destroy target-level code may have reported -DER_BUSY
due to the ongoing (nearly-completed) rebuild.
With this change, rebuild+_fio.py code is udpated to, just before
tearDown, wait for pool rebuild to end.
Test-tag: test_ec_offline_rebuild_fio test_ec_online_rebuild_fio
> DAOS-11816 test: wait for rebuild before container destroy

- src/client/api/container.c
- src/common/acl_api.c
- src/common/tests/acl_valid_tests.c
- src/container/srv_container.c
- src/include/daos_security.h
- src/security/tests/srv_acl_tests.c
- src/tests/suite/daos_container.c
The ACL validation was so strict that adding a new permissions bit would have caused a failure between code versions. We should not be validating the content of the permissions and flags fields.
- Remove pool and container specific ACL validation, which was focused on the permissions bits.
- Remove logic checking the permissions and flags bits.
- Remove tests that are now irrelevant.
> DAOS-12643 security: Loosen ACL validation (#11499)

- src/tests/ftest/erasurecode/online_rebuild_single.py
Add wait_for_rebuild() call at the end of the test
(similar to how the test does on the master branch version).
With this change, the chance of an intermittent -DER_IO
returned by container destroy (due to pool rebuild in progress)
should be eliminated.
Test-tag: ec_online_rebuild_single
Test-repeat: 6
> DAOS-12573 test: wait on rebuild before teardown/cont destroy

- src/client/dfs/dfs.c
- src/tests/suite/dfs_unit_test.c
Retrieving an attribute that was set without any data should not return an error.
Experiments and man page seem to indicate that this is the correct.
Features: dfs,dfuse
Signed-off-by: Denis Barakhtanov denis.barahtanov@croit.io
> DAOS-12835 dfs: getxattr shouldn't return error if value wasn't set

- src/control/lib/dlopen/dlopen.go
dlerror() may not be thread-safe, depending on the implementation. It is possible that after clearing dlerror(), we could encounter a race with another thread.
In the DAOS control plane context, we always expect dlsym to return a non-NULL value if it succeeded. This avoids detecting an error set by another thread, when the current thread's dlsym() succeeded.
> DAOS-12689 control: Don't return an error if dlsym succeeded (#11596)

- src/dtx/dtx_rpc.c
- src/object/cli_shard.c
If related DTX is committable, then it will be committed
within DTX_COMMIT_THRESHOLD_AGE seconds. So if need the DTX
refresh to wait for longer, then just let related client
to retry via a shorter timeout.
More debug messge for IO request timeout.
> DAOS-11203 dtx: reduce DTX refresh RPC timeout

- src/control/server/config/server_test.go
- src/control/server/storage/config.go
- src/control/server/storage/config_test.go
Avoid segfault when control-plane parses a server config file with an
empty storage tier yaml list entry by ignoring nil when iterating
tiers during custom unmarshal.
> DAOS-12826 control: Handle empty storage tier in config unmarshal

- src/vos/storage_estimator/common/explorer.py
- src/vos/storage_estimator/common/vos_size.py
- src/vos/storage_estimator/daos_storage_estimator.py
- src/vos/vos_size.c
It appears dfs doesn't write dkey0, for array metadata, until there is actually data written to a file.  Modify the storage estimator to handle this case
Align up vos_size values to 32 bytes since that's what we do internally. Change alloc_overhead default to 0 since we use slabs.
> DAOS-623 common: Don't add array metadata for empty files

- docs/user/container.md
- src/control/cmd/daos/container.go
The DAOS tool should not allow users to create containers for users other than themselves. If the owner decides to transfer ownership later, they can use the daos cont set-owner command.
It is still possible to:
- Create a container with a specified owner-group via the daos tool.
- Create a container with a specified owner-user via the C API.
Features: control container
> DAOS-5936 control: Remove -u flag from daos cont create

- src/container/srv_target.c
- src/dtx/dtx_common.c
- src/dtx/dtx_resync.c
- src/include/daos_srv/vos.h
- src/vos/vos_container.c
- src/vos/vos_dtx.c
- src/vos/vos_internal.h
Change the process for committed DTX entries reindex as self-traced by the vos container inside VOS. Then even if related reindex ULT is stopped and restarted again and again (for container open/close, DTX resync/check), the committed DTX entries reindex process will always resume from former paused point instead of from scratch.
There is race between DTX reindex ULT start and stop. If someone is trying to stop the reindex process, then next starting reindex need to wait instead of return directly.
> DAOS-12824 dtx: reindex committed DTX entries

- src/tests/ftest/launch.py
Test log collection can fail if there is not enough space left on the remote hosts to make a directory which is then used to clush --rcopy the files to the launch host.  To avoid this ituation these directories will be created prior to running the tests.
Skip-unit-tests:true
Test-tag-hw-large: dfs_test
Test-provider-hw-large: ucx+dc_x
> DAOS-12412 test: Allow for log collection w/ No space left on device

- src/tests/ftest/harness/core_files.py
- src/tests/ftest/launch.py
We do not generate stack traces on el7 so the harness/core_test.py should not expect to see a stack trace when run on el7.
Also adding the pr taq to the harness/core_test.py to get early detection of any issues in stack trace generation.
> DAOS-12719 test: Ignore missing expected stack trace on el7

- src/client/dfs/dfs.c
- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/control/cmd/daos/flags.go
- src/control/cmd/daos/flags_test.go
- src/include/daos_fs.h
- src/tests/suite/dfs_unit_test.c
- utils/node_local_test.py
- the dfs checker and other related functions will now user exclusive container open to access the file.
- add an option for evicting all user handles with the exclusive open to ensure the checker does not fail with EBUSY.
- add a new container command that will evict open container handles.
- update unit test and nlt test
> DAOS-12637 dfs: update dfs checker to use exclusive container open

- src/tests/ftest/harness/core_files.py
- src/tests/ftest/launch.py
We do not generate stack traces on el7 so the harness/core_test.py should not expect to see a stack trace when run on el7.
Also adding the pr taq to the harness/core_test.py to get early detection of any issues in stack trace generation.
Skip-func-vm-test-el7: false
> DAOS-12719 test: Ignore missing expected stack trace on el7 (#11694)

- src/vos/lru_array.c
- src/vos/lru_array.h
master-commit: f45b589bd0467e2fa6d8a11ed4068c32ecbcfa36
When there is no free entry in a lru_sub, it is expected to be removed from the free list of the LRU array. But under some cases, such as DTX reindex that may trigger lrua_remove_entry, it does not do that, as to related lru_sub may be added into the LRU array free lru_sub list more that once. Then when traverse such list, it may fall into dead loop.
> DAOS-12447 vos: fix LRU array free lru_sub list corruption

- src/tests/ftest/control/dmg_system_reformat.py
Update dmg_get_command timeout issue and check for no-space from execption error.
Test-tag: test_dmg_system_reformat
Test-repeat: 5
> DAOS-12892 test: control/dmg_system_reformat.py test issue

- ci/bandit.config
This check is no longer used and has been removed from bandit
so do not tell bandit to use this.
There is no change in coverage here, bandit has been updated to remove
a no-longer-valid check so daos needs updating for the new bandit version.
> DAOS-623 test: Remove bandit checks B309,b325 .

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
- src/control/cmd/dmg/pretty/pool.go
Use a common helper when printing tier ratio values to ensure
consistent output. Also adds more comprehensive unit testing
for the tierRatioFlag type.
> DAOS-12561 control: Consistently format pool tier ratios

- src/control/cmd/dmg/pretty/check.go
- src/control/cmd/dmg/pretty/check_test.go
- src/control/lib/control/check.go
When a pool has been removed, it will no longer appear
in the pools list for the response. We can still detect
that a pool was removed by checking the reports list,
however. If we find a removed pool, include in the count
of checked pools when displaying the query results.
Includes misc. improvements to JSON output as well.
Features: recovery
> DAOS-12189 chk: Include removed pools in query count

- ci/bandit.config
This check is no longer used and has been removed from bandit
so do not tell bandit to use this.
There is no change in coverage here, bandit has been updated to remove
a no-longer-valid check so daos needs updating for the new bandit version.
> DAOS-623 test: Remove bandit checks B309,b325 . (#11742)

- src/pool/srv_iv.c
Since pool_tgt_connect/prop_update/refresh_hdl might yield due to connective operation, so it need check sp_stopping again before pool_iv_ent_copy, in case the entry has been destoryed.
> DAOS-12732 pool: recheck pool stopping in pool_iv_ent_refresh (#11605)

- src/tests/ftest/datamover/posix_preserve_props.py
- src/tests/ftest/util/test_utils_container.py
- src/tests/ftest/util/test_utils_pool.py
Test-tag: pr daily_regression container pool
- Use a container label by default with all tests.
- Except for create through the pydaos.raw API
- Also rename the pool label of TestLabel to TestPool
> DAOS-9721 test: use container label by default with most tests

- src/object/srv_obj.c
- src/placement/pl_map_common.c
Typo fix in pool_map_extend(), especially if there are a lot groups.
Check ptr in enum_handler.
Make sure container property is retrieved before capability check, especially during pool extending.
> DAOS-12693 object: a few fixes for pool extending (#11541)

- src/cart/crt_init.c
No longer set "FI_OFI_RXM_DEF_TCP_WAIT_OBJ" to pollfd by default on the client side. Setting this causes performance issues on some tests
Test-provider-hw-medium: ofi+tcp
Test-tag: test_pool_autotest
> DAOS-12727 cart: Update WAIT_OBJ default settings

- src/mgmt/cli_mgmt.c
Log the client's final interface/domain selection after processing the GetAttachInfo results and manually-set environment variables at INFO level instead of DEBUG.
> DAOS-12576 mgmt: Log client interface choice at INFO level

- src/common/dav/tx.c
- src/common/dav/wal_tx.c
- src/common/dav/wal_tx.h
Fixed issue related to dav_wal_tx_reserve() not handling the potential yield within underlying wal_reserve() call.
> DAOS-12897 common: fix null dereference in dav_wal_tx_reserve()

- src/pool/srv_internal.h
- src/pool/srv_pool.c
- src/pool/srv_target.c
- src/pool/srv_util.c
Request pool map distributions for potentially restarted ranks, so that
any rank who has restarted without triggering a SWIM DEAD event will
eventually receive maps of the pools that this rank belongs to.
Introduce POOL_GROUP_MAP_STATUS to ensure that a consistent set of map
status is used to determine the up ranks in various cases.
> DAOS-9163 pool: Do map_dist for restarted ranks

- src/control/cmd/daos/main.go
- src/control/cmd/daos/snapshot.go
- src/control/cmd/daos/util.go
In order to support JSON output for this command, the
listing logic needed to be ported to Go.
> DAOS-12910 tools: Move daos cont list-snap logic to Go

- Jenkinsfile
- src/common/dav/tx.c
- src/include/daos_srv/vos.h
- src/vos/tests/vts_common.h
- src/vos/tests/vts_pm.c
- src/vos/tests/vts_pool.c
- src/vos/tests/vts_wal.c
- src/vos/vos_pool.c
- utils/run_test.sh
This fix addresses a bug with DAV allocator when after the change to move all allocations to fixed slabs if they fit in a defined one, we hit a bug in tx_free which was causing an allocated range to not get flushed on commit if multiple ranges were merged at tx_alloc.
> DAOS-12755 common: fix merged ranges not flushed in DAV allocator

- src/control/cmd/ddb/commands_wrapper.go
- src/control/cmd/ddb/main.go
- src/ddb/ddb.h
- src/ddb/ddb_commands.c
The VOS file being connected to when running in non-interactive mode was not being closed. By not closing the file, the system could have difficulty starting again.  This change fixes that.
Also checks that if the user didn't close the file in interactive mode it will be automatically closed.
> DAOS-12843 ddb: Make sure VOS file is closed before exiting

- src/control/fault/code/codes.go
- src/control/lib/control/faults.go
- src/control/lib/control/interceptors.go
- src/control/lib/control/rpc.go
Properly exposes a gRPC connection timeout as a new
client fault, and adds it to the list of retryable
errors during a MS request. A connection timeout may
occur when a previously-reachable endpoint goes away
(e.g. server crashed, cable unplugged, etc).
> DAOS-12025 control: Make connection timeout retryable

- src/object/cli_shard.c
- src/tests/suite/daos_rebuild_simple.c
The structure for sending an RPC for the CSUM error report wasn't completely initialized and contained garbage data. This change fixes that. A test was also added to reproduce the issue.
Features: csum
> DAOS-12857 csum: Initialize RPC object for CSUM Report

- src/dtx/dtx_common.c
- src/dtx/dtx_resync.c
- src/dtx/dtx_rpc.c
- src/include/daos/dtx.h
- src/include/daos_srv/container.h
- src/include/daos_srv/dtx_srv.h
- src/include/daos_srv/vos.h
- src/object/srv_obj.c
- src/vos/ilog.c
- src/vos/lru_array.h
- src/vos/tests/vts_dtx.c
- src/vos/tests/vts_mvcc.c
- src/vos/vos_common.c
- src/vos/vos_container.c
- src/vos/vos_dtx.c
- src/vos/vos_dtx_iter.c
- src/vos/vos_ilog.c
- src/vos/vos_internal.h
- src/vos/vos_io.c
- src/vos/vos_obj.c
- src/vos/vos_tree.c
Under original PMDK based local TX model, we assume that current ULT will not yield inside the local PMDK TX. But such assumption is not guaranteed under other backend local TX model, such as on SSD based system.
The patch introduces three temporary status for active DTX entry in DRAM: 'preparing', 'committing' and 'aborting'. Base on these, It adjusts related DTX logic to allow CPU yield during DTX status changes, including:
1. 'init' => 'preparing' => 'prepared'
2. 'init' => 'committing' => 'committed'
3. 'prepared' => 'committing' => 'committed'
4. 'prepared' => 'aborting' => 'aborted'
It works for both PMDK based local TX and metadata on SSD model. It does not change on-wire RPC protocol. As for the on-disk data layout, it is also compatible with old release. In the patch, we reuse …
> DAOS-12595 dtx: support CPU yield during local TX commit

- src/control/cmd/daos/container_test.go
- src/control/cmd/daos/util.go
Instead of closing them in the reader goroutine, close them
in the cleanup closure that is invoked by the caller. This
ensures that the file handles are released synchronously.
Also adds context-aware cleanup to avoid leaking goroutines.
> DAOS-12904 tools: Close files in cleanup closure

- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_tx.c
dc_tx_commit_prepare() may return -DER_STALE because of stale pool map. Under such case, we need to refresh the pool map to avoid subsequent TX restart falling into dead loop.
Some other code cleanup related with task completion.
> DAOS-12911 dtx: handle stale pool map when prepare TX commit

- src/tests/ftest/nvme/enospace.py
- src/tests/ftest/nvme/enospace.yaml
Description: update script enospace.py to complete the job before exit.
Test-tag: der_enospace
Test-repeat: 30
> DAOS-12674 test: nvme/enospace.py test not waiting for thread completion

- src/control/lib/hardware/libfabric/provider.go
- src/control/lib/hardware/libfabric/provider_test.go
All libfabric providers should be labeled with the prefix, since we now also have UCX providers. Trying to differentiate between tested and untested providers in code seems unmaintainable.
> DAOS-12972 control: Add ofi prefix to all libfabric providers

- src/object/cli_ec.c
- src/object/cli_obj.c
For some fail cases it calls tse_task_complete(task, rc) for err handing. In tse_task_complete only over-write task->dt_result if it is zero, but for some cases need to overwrite task->dt_result's retry-able result if get new different failure to avoid possible dead loop of retry or assertion.
> DAOS-12830 object: refine task err handling

- src/client/dfuse/dfuse_core.c
At high file counts the hash table becomes a real performance bottleneck
so increase the size to accomodate.  With 1m files this can result in a
10x performance improvement for some workflows.
> DAOS-12971 dfuse: Increase hash table size for dfuse inodes.

- ci/codespell.ignores
- src/tests/perf_internal.h
- src/tests/vos_perf.c
- src/vos/tests/evt_ctl.c
- src/vos/tests/vos_tests.c
- src/vos/tests/vts_aggregate.c
- src/vos/tests/vts_common.h
- src/vos/tests/vts_io.c
- utils/run_test.sh
Since the nested iterator option is specific to a small subset of VOS IO tests, remove it and handle running those internally both ways.
Remove related dead code from vos_perf.
Don't run tests that are not affected by oclass more than once Make some minor naming adjustments.
Also, we don't support vmem for vos, so stop running vmem evtree tests
> DAOS-623 test: Simplify VOS unit tests a little

- src/tests/ftest/deployment/agent_failure.py
We need to provide hostnames with NodeSet to run IOR using job manager because the tear down code expects the hostnames to be provided from the tests as NodeSet.
Test-tag: AgentFailure
> DAOS-12984 test: agent_failure.py - Use NodeSet to provide client hostnames to run IOR

- src/engine/ult.c
RDB pool loading executed on sys XS.
> DAOS-13058 engine: incorrect assertion in dss_main_exec()

- src/control/system/membership.go
- src/control/system/raft/database.go
When a rank exits unexpectedly, a RAS event is raised and should
be logged at ERROR level. When a pool's service ranks are updated,
the event should be logged at INFO level.
> DAOS-12628 control: Add non-debug event logging for daos_server

- src/include/daos_srv/pool.h
- src/pool/srv_internal.h
- src/pool/srv_layout.h
- src/pool/srv_pool.c
- src/tests/suite/daos_upgrade.c
There was a mismatch in upgrading the pool property for the size of the property.
Added a 32-bit version of the function
Made all checkpoint properties 32-bit
Quick-fucntional: true
Skip-nlt: true
Test-tag: test_daos_upgrade
Test-repeat: 5
Test-Nvme: auto_md_on_ssd
> DAOS-12922 pool: Fix checkpoint property upgrade

- src/control/server/mgmt_fi.go
- src/control/system/member.go
- src/control/system/raft/database_test.go
Destroy the pool targets on all ranks, not just the service
ranks.
> cr: Use all non-excluded ranks in CR FI for missing pool

- src/tests/ftest/launch.py
Update launch.py run_remote logger timeout.
Test-tag: offline_drain,full_regression
> DAOS-11925 test: Error running cart/cart_logtest.py on the /var/tmp/daos_testing/*log* files

- ci/functional/launchable_analysis
When trying to create the job status directory during Launchable
analysis fails.
* Abbreviated testing to avoid wasting resources on testing that validates nothing about this change
* Only required an `always_passes` test as there is no Functional testing to validate this change
> SRE-415 test: Add some diagnostics

- src/tests/ftest/pool/rf.yaml
Test-tag: test_rf_pool_property
Test-repeat: 5
> DAOS-12163 test: increase rf test timeout

- src/rdb/rdb_raft.c
In rdb_raft_update_node(), avoid a double free of the replicas rank list when handling a RAFT_LOGTYPE_REMOVE_NODE raft log entry would result in the list going from 1 to 0 items.
Features: pool
> DAOS-13115 rdb: coverity CID 1347786

- src/bio/bio_wal.c
- src/pool/srv_target.c
- Use deep stack for pool child discard to avoid potential stack overrun.
- Fix WAL commit wait logic a bit to avoid missing wait when "WAL I/O is
already completed but data I/O is still inflight" before calling the
wait function.
> DAOS-13002 pool: Use deep stack for pool child discard

- src/common/pool_map.c
- src/include/daos_srv/rebuild.h
- src/object/srv_obj_migrate.c
- src/pool/srv_pool.c
- src/pool/srv_pool_map.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/tests/suite/daos_drain_simple.c
- src/tests/suite/daos_extend_simple.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_test.h
- src/tests/suite/daos_test_common.c
restore the pool map if extend/drain fail.
> DAOS-5912 rebuild: restore pool map if extend/drain fail (#11411)

- src/pool/srv_target.c
This is needed now in vos_on_blob branch because commit 9d580e80e1b093390e86b3bfb4e6a62a486b6145 has introduced unmap_wal() call to bio_wal_replay() on pool open, and this triggers huge stack consumption by SPDK/DPDK
underlying involved functions then.
> DAOS-13137 pool: use a deep stack for pool open ULT

- utils/githooks/find_base.sh
I hit a situation where I resused a remote branch
from a PR that had been merged and the branch
deleted.  This caused my new PR to use a testbuild branch for the base calculation.
Add a check to find_base.sh that the branch it
finds is an open PR.
> DAOS-623 test: Only use open remote PR for base

- src/tests/ftest/vmd/fault_reintegration.py
Hardware-medium led_state is NA, move this testcase to manual
Test-tag: test_nvme_fault_reintegration,-manual
> DAOS-13157 test: nvme_fault_reintegration - not in expected NORMAL, OFF state

- src/common/sys_lmdb.c
- src/engine/init.c
- src/vos/vos_common.c
1. In vos_self_fini_locked() bio_nvme_fini() need be called after sys db cleanup, because we need bio_nvme_configure() to check if MD on SSD enabled or not.
2. in lmm_db_fini() env need be destroyed after dbi closed to avoid use-after-free.
3. refactored lmm_db_init_ex() a bit to avoid potential memory leaks if lmm_db_open_create() return NOEXIST but it is not file not existed case.
4. add missed bio_nvme_fini() in the engine mode.
> DAOS-13144 common: fix to free lmdb memory

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
The sponsor of CR interaction will hold reference on related pool record to prevent the pool record being released. If "check stop" is triggered during such waiting, we need wakeup related interaction sponsor instead of block the "check stop".
> DAOS-13119 chk: check stop while some interaction in pending

- ci/functional/launchable_analysis
When trying to create the job status directory during Launchable
analysis fails.
- abbreviated testing to preserve testing resources that would add no value
- abbreviated testing as there is no test tag to validate this change
> SRE-415 test: Add more diagnostics

- src/tests/ftest/server/replay.py
- src/tests/ftest/server/replay.yaml
Adding a test case to verify data access after engine restart with WAL replay and no check pointing.
Test-tag: ReplayTests
> DAOS-13013 test: Adding replay test case with no checkpointing

- src/container/srv_container.c
- src/container/srv_epoch.c
- src/include/daos_srv/container.h
- src/pool/srv_pool.c
Server to server communication has to go through primary context since servers are not aware of each others secondary addresses.
This patch changed bcast code to use the primary context stored in dss_module_info->dmi_ctx instead of rpc->cr_ctx which could be secondary context if the RPC is from secondary provider.
> DAOS-13134 pool: use primary context to do bcast

- src/tests/ftest/launch.py
In order to support removing certain test yaml file entries a new --yaml_extension launch.py argument is being added to allow users to override using the default test yaml files with any yaml files with the specified extension.
> DAOS-13169 test: Adding support for custom test yaml files.

- src/cart/crt_init.c
In preparation of mercury update to 2.3.0
> DAOS-12601 mercury: disable multi-recv except for prov/cxi

- src/engine/server_iv.c
Use proper formatting of errors with the DF_RC macro as
the last option in error messages.  This puts a string
in addition to just the error number.
This change avoids some CI failures where this log mesage
is occasionally reported during shutdown and wasn't being
correctly ignored as it was not well formatted.
> DAOS-623 engine: Update a warning in the IV code.

- src/cart/crt_init.c
In preparation of mercury update to 2.3.0
> DAOS-12601 mercury: disable multi-recv for all providers

- src/control/drpc/drpc_client.go
- src/control/drpc/drpc_client_test.go
- src/control/drpc/mocks_test.go
- src/control/lib/control/pool.go
- src/control/server/harness.go
- src/control/server/harness_test.go
The current timeout of 3 minutes may be causing intermittent
failures in CI when a pool query happens during a rebuild.
Also updates the dRPC client implementation to return a
context.Canceled error when the dRPC connection is closed
due to timeout. This allows the harness to avoid incorrectly
invoking dRPC failure handlers for a canceled gRPC request.
> DAOS-13123 control: Increase pool timeout to 5 minutes

- src/control/cmd/daos_agent/procmon.go
- src/control/common/proc_utils.go
- src/control/common/proc_utils_test.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_svc.go
- src/control/server/mgmt_system.go
- src/control/server/mgmt_system_test.go
- src/control/server/server.go
The PoolEvict gRPC handler may be invoked from N agents in the
event of a large-scale application crash. This would result in
N dRPC requests from the MS leader to its local engine in order
to evict the pool handles in those requests. With this commit,
a batching mechanism is added to improve performance in these
large-scale events so that N agent requests are consolidated
into a smaller number of dRPC requests containing multiple
handles.
Also improves agent logging of evicted handles due to application
crash by including the process name and logging a single line
at INFO level instead of DEBUG.
Features: pool control
> DAOS-13114 control: Add batching support for PoolEvict requests

- src/tests/ftest/launch.py
- src/tests/ftest/util/storage_utils.py
Allowing extra yaml file entries to update generated storage configuration yaml files.  Also adding --scm_size and --scm_mount launch.py arguments to finer tune the generated storage configuration yaml files.
> DAOS-13193 test: Enabling extra yamls to update storage configs

- src/tests/ftest/osa/offline_drain.py
- src/tests/ftest/util/test_utils_pool.py
Test-tag: offline_drain
Test-repeat: 3
Summary:
Based on developer's input, we are checking the total space available instead of free space. Sometimes, the GC (garbage collection) can reclaim space which can cause intermittent failures.
> DAOS-13042 test: Check total space for offline drain.

- src/container/srv_container.c
- src/include/daos_srv/container.h
- src/pool/srv_pool.c
Use cont_svc as the parameter of ds_cont_rdb_iterate() to avoid svc leader lookup, which might return NONLEADER during PS step up.
> DAOS-13195 container: use cont_svc for rdb iterate

- src/tests/ftest/control/dmg_storage_query.py
- src/tests/ftest/util/storage_utils.py
When generating server storage configurations use explicit storage tier roles instead of implicit ones.
Test-tag: pr test_dmg_storage_query_devices
> DAOS-11421 test: Use explicit bdev tier roles.

- src/tests/suite/daos_rebuild_common.c
Increase pre rebuild version in rebuild_exclude_tgt() to make sure the rebuild triggered by this exclude will be waited in rebuild_pool_wait().
> DAOS-13191 test: increase pre rebuild version

- src/client/dfuse/dfuse.h
- src/client/dfuse/dfuse_core.c
- src/client/dfuse/dfuse_fuseops.c
- src/client/dfuse/ops/create.c
- src/client/dfuse/ops/lookup.c
- src/client/dfuse/ops/open.c
- src/client/dfuse/ops/opendir.c
- src/client/dfuse/ops/write.c
- utils/node_local_test.py
> DAOS-13215 dfuse: Use separate values for data and metadata caches.

- src/tests/ftest/container/list.py
- src/tests/ftest/container/list.yaml
- src/tests/ftest/security/cont_acl.yaml
- src/tests/ftest/security/pool_acl.py
- src/tests/ftest/security/pool_acl.yaml
- src/tests/ftest/security/pool_groups.py
- src/tests/ftest/security/pool_groups.yaml
- src/tests/ftest/util/daos_utils.py
- src/tests/ftest/util/pool_security_test_base.py
- src/tests/ftest/util/test_utils_container.py
Test-tag: pr container DaosContainterSecurityTest test_daos_pool_acl_enforcement test_daos_pool_acl_groups ListContainerTest
- Replace calls to daos.container_create with self.get_container
- Remove unused "cont" from TestContainer.create()
- This used to be for the UUID but it's not possible to create a container with a user-supplied UUID
> DAOS-9721 test: replace daos.container_create with self.get_container

- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/mdtest_test_base.py
- src/tests/ftest/util/performance_test_base.py
Test-tag: pr MdtestEasy,-manual MdtestHard,-manual MdtestSmall
- Call get_params when initializing a DaosCommand
- Add display_space arg to execute mdtest
- Works around client env not being propagated to pydaos
- 
> DAOS-13189 test: propagate client/env_vars to daos command

- src/container/srv_container.c
- src/engine/sched.c
- src/pool/srv_target.c
- src/vos/vos_pool.c
Don't skip check_space_pressure(), otherwise, destroyed pool won't be detected and the sched_pool_info for destroyed pool won't be freed.
> DAOS-13226 engine: fix sched_pool_info leak

- .github/workflows/pr-metadata.yml
This check verifies the PR title so run the check when the PR
title is modified.
> DAOS-623 cq: Re-run the jira-query trigger if the PR is modified

- src/tests/suite/daos_nvme_recovery.c
Adjust daos_nvme_recovery test since now auto faulty is enabled by default.
When auto faulty is enabled, a -DER_NVME_IO write error will be retried on client until the write succeeded or auto faulty is triggered (affected target is marked as DOWN).
> DAOS-13218 bio: adjust daos_nvme_recovery test

- src/include/daos_srv/rebuild.h
- src/object/obj_tx.c
- src/object/srv_obj_migrate.c
- src/placement/jump_map.c
- src/pool/cli.c
- src/pool/srv_pool.c
- src/rebuild/srv.c
- src/tests/ftest/control/dmg_pool_query_ranks.py
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_simple.c
- src/tests/suite/daos_test_common.c
Since object enumeration might return next punch epoch of the current object/key/rec, so let's compare the punch epoch with rebuild/reintegration stable epoch before migrate punch.
Do not allow reint/drain/extend if there are other rebuild job going on to avoid screwing up the object layout.
Fix converting task error reset in dc_tx_check_update()
Retry UPDATE_AGAIN with delay, similar as INPROGRESS.
> DAOS-12398 object: Check punch epoch before migration punch (#11667)

- src/tests/ftest/util/test_utils_pool.py
- src/tests/ftest/util/yaml_utils.py
Summary: Add support to insert delay between pool queries. User can add pool_query_delay: 5 (for insserting 5 second) delay between pool queries in the YAML file.
> DAOS-13001 test: Add pool_query_delay support to YAML.

- src/control/server/mgmt_check.go
- src/control/server/mgmt_system.go
- src/control/system/checker/faults.go
- src/tests/ftest/util/dmg_utils.py
In order to avoid unexpected behavior, the `dmg check enable`
command now requires the system to be stopped first. Likewise,
the `dmg check disable` command just disables the checker
and stops the ranks. The admin will need to use `dmg system start`
again in order to restart the ranks in normal mode.
Features: recovery
> DAOS-13170 chk: dmg check enable should not restart ranks

- src/control/drpc/drpc_server.go
The previous size of 128kB is not large enough for some
response messages on large-scale systems.
> DAOS-13284 control: Increase dRPC buffer size to 1MB

- src/cart/crt_hg_proc.c
- src/include/cart/api.h
- src/include/daos/object.h
- src/object/obj_rpc.c
- src/object/obj_rpc.h
- src/object/obj_tx.c
- src/object/srv_internal.h
- src/object/srv_obj.c
- src/object/srv_obj_remote.c
A large CPD RPC may contains a lot of sub requests as to totally packing them in RPC body will exceed lower layer CaRT RPC size limitation, as to some unexpected memory related trouble, such as -DER_NOMEM.
This patch supports to bulk transfer large CPD RPC sub requests (> DAOS_BULK_LIMIT) to the leader (and dispatch to non-leaders).
The changes only affect 2.4 release, no interoperability issues with 2.2 or older releases.
It also cleanups CPD RPC code and unifies some CPD RPC related functions name rules.
> DAOS-13122 object: support to bulk transfer CPD RPC sub requests

- src/common/tests/drpc_tests.c
- src/engine/drpc_handler.c
- src/engine/drpc_progress.c
- src/engine/srv.c
Fix issues discovered in static analysis, in which some return values weren't being checked.
Also fixes DAOS-13258, DAOS-13257, and DAOS-12355.
> DAOS-13259 engine: Check return values

- src/include/daos/placement.h
- src/include/daos_srv/rebuild.h
- src/object/srv_obj_migrate.c
- src/placement/pl_map.c
- src/pool/srv_pool.c
- src/rebuild/scan.c
- src/rebuild/srv.c
During PS leader switch, the new leader should check
if there are ongoing rebuild, whose reclaim epoch should
be used to reclaim the half rebuild object.
During extend/reintegration/drain, if there are new targets
failure, then the object impacted by the new failure, are actually
rebuilt to the new replacement target, so during the reclaim
phase, these rebuilding shards can be skipped.
Do not need migrate the object once the rebuild is done.
Features: rebuild reintegration
> DAOS-13200 rebuild: fix reclaim epoch for rebuild during PS leader change

- src/tests/ftest/harness/basic.py
Enable a 'always_passes' tagged test that will run in the Functional Hardware Provider stages.  This allows us to verify that the stage will run w/o needing to run any daos_test/suite.py tests.
Test-tag: test_always_passes_hw_provider
> DAOS-12562 test: Enable basic test for provider test stages

- src/pool/srv_pool.c
> DAOS-13247 pool: remove unneeded code reported by coverity

- src/tests/ftest/control/dmg_storage_query.py
Updating the control/dmg_storage_query.py to use the new bdev_role attribute which replaced the server config role attribute recently.
Test-tag: test_dmg_storage_query_devices
> DAOS-13281 test: Fix dmg_storage_query.py bdev_role access

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/chk/chk_srv.c
When the check against the pool is stopped, related pool's status should be set as 'STOPPPED' intead of 'COMPLETED'. If there is no more pools in checking, then check instance status should also be set as 'STOPPED'.
> DAOS-13206 chk: properly set pool status when stop check

- Jenkinsfile
Some changes in UnitTestPost happened simultaneously to
changes in UnitTestPostEx and the new changes removed
the need for the new capability.  So let's just drop the new
function.
This fixes the unit test reporting in Github which has been
broken for a few weeks requiring forced landings.
> DAOS-13324 test: Sync with pipeline-lib

- debian/changelog
- debian/control
- utils/rpms/daos.spec
> DAOS-13378 build: Temporarily pin libfabric to < 1.18

- src/control/cmd/daos_agent/security_rpc_test.go
- src/control/cmd/hello_drpc/main.go
- src/control/drpc/drpc_client.go
- src/control/drpc/drpc_client_test.go
- src/control/drpc/drpc_server_test.go
- src/control/server/drpc.go
- src/control/server/util_test.go
* Modify Connect() to accept a context that is used for
DialContext() in order to avoid making a connection with
a canceled context
* Ignore already-closed error on connection close
> DAOS-13219 control: Improve dRPC client implementation

- src/control/cmd/daos_agent/security_rpc_test.go
- src/control/security/domain_info.go
- src/control/security/domain_info_test.go
Don't include the context string in the human-readable output.
Also fixes a bad merge in daos_agent/security_rpc_test.go
> DAOS-12002 control: Fix DomainInfo stringer

- src/tests/ftest/container/full_pool_container_create.py
- src/tests/ftest/container/full_pool_container_create.yaml
Based on Yawei's comment in DAOS-9918, this test doesn't
work with small pool size.
Update year in copyright.
Test-tag: test_no_space_cont_create
> DAOS-5813 test: Remove small pool (128MB) variant from container/full_pool_container_create.py

- src/tests/ftest/cart/util/cart_logtest.py
- utils/node_local_test.py
> DAOS-13066 test: Reduce concurrency in NLT

- src/control/cmd/hello_drpc/main.go
- src/control/drpc/drpc_client_test.go
- src/control/server/mgmt_pool_test.go
- src/control/server/mgmt_svc.go
- src/control/server/mgmt_system.go
- src/control/server/mgmt_system_test.go
- src/control/server/server.go
- src/control/server/util_test.go
Remove the custom Join batch processing code in favor of using
the generalized batch processing code added for PoolEvict.
Also updates various names for clarity, and updates a few
more tests to use test.Context().
> DAOS-13114 control: Migrate Join handler to new batch style

- src/dtx/dtx_cos.c
The DTX CoS list may be too long as to exceed the specified max count for dtx_list_cos(). Under such case, we should only return the specified max count entries instead of going through all the DTX CoS list to avoid out of boundary for the returned buffer.
Skip-scan-leap15-rpms: true
> DOAS-13231 dtx: fix out of boundary issue in dtx_list_cos

- src/object/cli_shard.c
- src/object/obj_ec.h
- src/object/obj_rpc.h
- src/object/obj_tx.c
- src/object/obj_verify.c
- src/object/srv_obj.c
- src/tests/suite/daos_obj_ec.c
- src/vos/vos_io.c
1. Fix a bug of EC multiple singv update
When there are multiple singv update (different akey) in one IO request,
if the first singv distributed to all shards, it possibly cause other short singv
being written to all shards. This patch fixed it by skip those update.
2. Fix a bug of EC multiple array update in obj_get_iods_offs_by_oid().
> DAOS-12828 object: bug fix for multiple EC akeys update in one IO

- src/bio/smd/smd_pool.c
- src/common/sys_lmdb.c
smd_pool_list() only iterate Data type, it will miss pools which were created with SCM only under MD-on-SSD case.
> DAOS-13410 bio: fix smd_pool_list() without data blobs

- src/tests/ftest/daos_test/dfuse.yaml
dfuse-writeback and intercept-off variant failed with timeout during tearDown, so increase the timeout by 30 sec based on the suggestion in the ticket.
Test-tag: test_daos_dfuse_unit
> DAOS-13411 test: Increase timeout by 30 sec for daos_test/dfuse.py

- utils/node_local_test.py
Do not set logging via log_mask and env vars, only
use one or the other.
Put the class hint in server log name.
Change from time.time to change.perf_counter globally.
> DAOS-9755 test: Update server logging in NLT.

- src/client/dfuse/pil4dfs/hook.c
- src/client/dfuse/pil4dfs/int_dfs.c
> DAOS-13485 client: fix several coverity issues in libpil4dfs

- src/tests/suite/daos_drain_simple.c
> DAOS-13412 tests: shrink drain file size

- src/client/api/event.c
- src/client/array/dc_array.c
- src/client/dfs/dfs.c
- free cb should be last (registered first)
- other minor fixes
> DAOS-12638 array: fix cb order on array get_size and stat (#12204)

- src/rdb/rdb.c
After adding a timed option for triggering a checkpoint,
I failed to clear dcr_idle flag so when checkpoint waits
for a commit, it never wakes up.
Also, add some logging that was useful for finding this issue
Test-tag: test_create_pool_quantity
> DAOS-13497 rdb: Fix bug tracking idle state in rdb checkpoint logic

- src/common/debug.c
If the logfile is set to /dev/null (needed to ensure that
debug/error logs go to stderr, not stdout), don't bother
with all of the fd management. Also avoids a spurious
fsync failure on daos_debug_fini().
> DAOS-13409 tools: Ignore D_LOG_FILE=/dev/null

- src/object/cli_shard.c
- src/tests/suite/daos_checksum.c
Fix a bug of DAOS_CSUM_CORRUPT_FETCH corrupt csum in multiple
akeys cases, add a test case to reproduce/verify it.
> DAOS-13439 object: fix a bug of csum corrupt injection

- src/client/dfuse/il/int_posix.c
- src/client/dfuse/ops/ioctl.c
- src/pool/cli.c
Update the logging for cases where an incorrect or outdated
ioctl size is used.
> DAOS-13254 il: Update logging for incorrect ioctl size.

- src/tests/ftest/checksum/csum_error_logging.py
Do not skip the running daos_test -z in the csum_error_logging.py test when running with pmem.
Test-tag: test_csum_error_logging
> DAOS-13536 test: Fix csum_error_logging.py when running w/ pmem

- src/control/cmd/daos_agent/attachinfo.go
- src/control/server/ctl_network_rpc.go
- src/control/server/ctl_network_rpc_test.go
- By default dmg network scan will include all configured providers, not just the primary provider.
- In daos_agent dump-attachinfo, use the agent config as the source for the provider index.
> DAOS-13539 control: Fix network related commands for multiprovider

- src/tests/ftest/recovery/ddb.yaml
> test: Use storage: auto for recovery/ddb.py

- src/tests/ftest/util/storage_utils.py
Launch.py will incorrectly include bdev_roles for the bdev_tiers when using '--nvme auto' if there are no pmem devices found on the server hosts.  This patch resolves this issue.
Test-tag: HarnessSetupTest
> DAOS-13553 test: Fix using bdev_roles with non-pmem nvme=auto.

- src/tests/suite/daos_obj.c
> DAOS-13439 test: re-enabled IO30 test

- site_scons/prereq_tools/base.py
- utils/cq/words.dict
A bug was discovered in the patch caching logic that prevented a patch from getting
downloaded because the target filename already existed.  We need to also take the
URL into account for the patch filename.
> DAOS-13556 build: Ensure unique patches get downloaded

- src/vos/vos_dtx.c
After supporting CPU yield during local TX commit, for solo modification, the server should not return in-committing data until it is persistently committed. Otherwise, if server crashed after returned the in-committing data to client, related data will be lost, then client holds stable data silently.
> DAOS-13514 vos: not return non-durable data for solo modification

- ci/provisioning/post_provision_config_common_functions.sh
- debian/changelog
- debian/control
- src/cart/utils/memcheck-cart.supp
- utils/build.config
- utils/rpms/daos.spec
- utils/test_memcheck.supp
Apply also patch for prov/verbs QP error state recovery (DAOS-12991)
> DAOS-13085: update libfabric to 1.18.0

- src/tests/ftest/control/dmg_pool_query_test.yaml
Fix memory check failure before engine start by reserving 64gib RAM
for system use when calculating tmpfs size for engine.
Test-tag: test_pool_query_basic test_pool_query_inputs test_pool_query_ior
> DAOS-13605 test: Fix RAM mem test for dmg_pool_query

- src/gurt/dlog.c
The cache reset needs to happen after the log masks is parsed. Otherwise, threads that are logging at the same time can cache the outdated value.
> DAOS-13592 gurt: Fix race in d_log_setmasks (#12287)

- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
- src/control/server/mgmt_svc.go
- src/control/server/server.go
- src/control/server/util_test.go
Adds a new gRPC request serialization mechanism to handle
PoolCreate requests. Mitigates against a number of edge
cases that may occur during multiple concurrent PoolCreate
requests.
Moves non-leader async management out of leadership callback.
> DAOS-13266 control: Serialize PoolCreate requests

- src/cart/utils/memcheck-cart.supp
On a clean build on el8.8 one of the existing suppressions needs
tweaking.
> DAOS-623 test: Update memcheck suppressions.

- src/control/lib/control/auto.go
- src/control/lib/hardware/pci.go
- src/control/lib/hardware/pci_test.go
- src/control/lib/spdk/spdk.go
- src/control/lib/spdk/spdk_default.go
- src/control/server/storage/bdev.go
- src/control/server/storage/bdev/backend_vmd.go
- src/control/server/storage/bdev_test.go
- src/control/server/storage/provider.go
- src/control/server/storage/provider_test.go
Bdev count check fails during dmg storage query usage when scanning
storage because the comparison is made between the number of detected
backing devices behind VMD rather than the number of VMDs (as
specified in the config file). Fix by resolving the backing devices
back to the VMD devices before comparing the counts.
> DAOS-13558 control: Fix bdev count check on scan with vmd

- Jenkinsfile
Update the builds to use the latest release/2.4 RPM version.
Test-tag: always_passes
> DAOS-623 test: Fix daos RPM version.

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/tests/ftest/recovery/pass_1.py
- src/tests/ftest/util/dmg_utils.py
- src/tests/ftest/util/dmg_utils_base.py
Test-tag-hw-medium: Pass1Test
The start options for new instance should properly overwrite old ones. It also enhances CR pass 1 functionality tests:
1. Verify DAOS checker under dryrun mode.
2. Verify DAOS checker under auto mode.
3. Verify that the DAOS checker can detect and repair the inconsistency under regular mode.
4. Fix some typo for the test tags.
5. More accurate comment for test flow.
> DAOS-13047 chk: properly handle start options

- src/tests/suite/daos_checksum.c
> DAOS-13437 csum: Unskip tests

- src/control/common/proto/logging.go
- src/control/server/interceptors.go
- src/control/server/server.go
- src/control/server/server_utils.go
The previous commit placed the request log behind a
conditional check in order to try to cut down on noisy
logging for requests that often result in a sentinel error
(e.g. ErrNotLeader). That approach does result in cleaner
logs, but has the downside of making requests more difficult
to trace, as the beginning of the request handling is not
logged first.
> DAOS-12250 control: Log gRPC req before processing

- src/control/lib/control/auto.go
- src/control/lib/hardware/pci.go
- src/control/lib/hardware/pci_test.go
- src/control/lib/spdk/spdk.go
- src/control/lib/spdk/spdk_default.go
- src/control/server/storage/bdev.go
- src/control/server/storage/bdev/backend_vmd.go
- src/control/server/storage/bdev_test.go
- src/control/server/storage/provider.go
- src/control/server/storage/provider_test.go
> Revert "DAOS-13558 control: Fix bdev count check on scan with vmd"

- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
- src/control/server/mgmt_svc.go
- src/control/server/server.go
- src/control/server/util_test.go
Adds a new gRPC request serialization mechanism to handle
PoolCreate requests. Mitigates against a number of edge
cases that may occur during multiple concurrent PoolCreate
requests.
Moves non-leader async management out of leadership callback.
> DAOS-13266 control: Serialize PoolCreate requests (#12083)

- src/mgmt/srv_drpc.c
The ds_mgmt_drpc_pool_create function may leak req_props.
> DAOS-13642 mgmt: Fix ds_mgmt_drpc_pool_create leak

- ci/provisioning/post_provision_config_common_functions.sh
Support the new testing branch naming format that can contain the version number in the middle of the branch name.
> DAOS-12648 ci: Adding support for new 2.4 testing branches. (#12368)

- src/gurt/errno.c
- src/gurt/tests/SConscript
- src/gurt/tests/test_gurt.c
- src/include/daos_errno.h
Newer versions of compilers can perform type checking of enums
so put daos error numbers in a named enum.
Remove some dead code for adding error numbers dynamically.
> DAOS-623 gurt: Make daos error numbers a named enum and remove dead code.

- ci/provisioning/post_provision_config_common_functions.sh
When including a dash in an RE class it needs to be first so that it's not misinterpreted as being part of a range.
> DAOS-623 test: Dash in RE class needs to be first (#12387)

- src/cart/crt_self_test_client.c
- src/rebuild/README.md
- src/vos/README.md
> DAOS-623 doc: fix code spell errors

- src/cart/crt_self_test_client.c
- src/rebuild/README.md
- src/vos/README.md
> DAOS-623 doc: fix code spell errors (#12426)

- src/tests/ftest/util/mdtest_test_base.py
Currently the mdtest_test_base does not allow using other mpi_types for mpich.
Test-tag: mdtest mpiio mpich
> DAOS-13661 test: Allow different mpi_types for mdtest (#12371)

- src/control/lib/control/auto.go
- src/control/lib/hardware/pci.go
- src/control/lib/hardware/pci_test.go
- src/control/lib/spdk/spdk.go
- src/control/lib/spdk/spdk_default.go
- src/control/server/storage/bdev.go
- src/control/server/storage/bdev/backend_vmd.go
- src/control/server/storage/bdev_test.go
- src/control/server/storage/provider.go
- src/control/server/storage/provider_test.go
Bdev count check fails during dmg storage query usage when scanning
storage because the comparison is made between the number of detected
backing devices behind VMD rather than the number of VMDs (as
specified in the config file). Fix by resolving the backing devices
back to the VMD devices before comparing the counts.
Previous PR for this change was reverted due to the introduction of
intermittent unit test failures. Additional unit test coverage exposed
a bug in lib/harware/pci.go:PCIAdress.LessThan() where VMD backing
device addresses are improperly compared. Fix is applied in this PR.
Signed-off-by: Tom Nabarro tom.nabarro@intel.com>
>  DAOS-13558 control: Fix bdev count check on scan with vmd

- src/client/api/rpc.c
d_rand() helper use lrand48_r() internally which is more secure.
Fixed CID: 1404393
> DAOS-13717 client: use d_rand() to generate random number

- ci/docker_nlt.sh
Increase system RAM reservation when calculating tmpfs size in NLT
docker tests to avoid intermittent available memory check failures on
engine start due to memory contention across multiple containers on
the same host.
> DAOS-13684 test: Bump docker nlt system_ram_reserved

- src/control/lib/control/auto.go
- src/control/lib/hardware/pci.go
- src/control/lib/hardware/pci_test.go
- src/control/lib/spdk/spdk.go
- src/control/lib/spdk/spdk_default.go
- src/control/server/storage/bdev.go
- src/control/server/storage/bdev/backend_vmd.go
- src/control/server/storage/bdev_test.go
- src/control/server/storage/provider.go
- src/control/server/storage/provider_test.go
Bdev count check fails during dmg storage query usage when scanning
storage because the comparison is made between the number of detected
backing devices behind VMD rather than the number of VMDs (as
specified in the config file). Fix by resolving the backing devices
back to the VMD devices before comparing the counts.
Previous PR for this change was reverted due to the introduction of
intermittent unit test failures. Additional unit test coverage exposed
a bug in lib/harware/pci.go:PCIAdress.LessThan() where VMD backing
device addresses are improperly compared. Fix is applied in this PR.
> DAOS-13558 control: Fix bdev count check on scan with vmd (#12376)

- src/chk/chk_rpc.c
- src/chk/chk_srv.c
- src/pool/srv_pool_check.c
For check engine, when handle CHK_QUERY RPC from check leader, the ds_chk_query_hdlr() logic does not need to free the memory allocated for "shards" under the case of failure. Related logic in crt_corpc_reply_hdlr() will trigger co_post_reply() that will finally call chk_query_free() to handle that.
Similar logic for CHK_{START,STOP,CONT_LIST}.
> DAOS-13689 chk: fix double free when handle chk RPC failure

- src/tests/ftest/io/small_file_count.yaml
There is a possibility that our CI NVME only have about ~370GiB capacity which is not enough to store both 350GiB Data + 40GiB Meta on this SSD, reduce pool NVME size a bit to 300GiB. (test required 30G x 2 for IOR and 50K x 4KIB for mdtest), so it should be fine.
Test-tag: SmallFileCount,test_smallfilecount
> DAOS-13686 test: reduce pool NVME size for small_file_count

- src/control/cmd/daos_server/auto_test.go
- src/control/cmd/dmg/auto_test.go
- src/control/lib/control/auto_test.go
- src/control/server/config/server.go
- src/control/server/config/server_test.go
- src/control/server/storage/scm.go
- src/control/server/storage/scm_test.go
> DAOS-13672 control: Calculate engine memory reservation on nr targets

- src/control/server/ctl_storage_rpc.go
- src/control/server/ctl_storage_rpc_test.go
- src/control/server/instance_storage.go
- src/engine/init.c
Engines send a notify ready message to indicate dRPC server is up and
running. Refuse to service a storage scan request with usage flag set
when a host's engines are not ready to enforce deterministic behavior.
Differentiate between a dmg storage query usage command request and
dmg storage scan --nvme-meta as the latter should be able to be called
when engines are off-line (in which case cached data will be returned).
> DAOS-13214 control: Check engines are ready before fetching usage

- src/gurt/dlog.c
if we merge stderr to log file which is not
calculated by log_size, to avoid exceeding threshold too much, log_size will be updated with fstat if log size increased by 2% of max size every time.
Test-tags: daos_test
> DAOS-13569 gurt: limit log size more accurate

- ci/docker_nlt.sh
Increase system RAM reservation when calculating tmpfs size in NLT
docker tests to avoid intermittent available memory check failures on
engine start due to memory contention across multiple containers on
the same host.
> DAOS-13684 test: Bump docker nlt system_ram_reserved (#12432)

- src/gurt/debug.c
> DAOS-13785 gurt: protect d_log_refcount with d_log_lock

- src/pool/cli.c
Cherry-pick of to release/2.4 branch, a fix for Coverity CID 1444801
> DAOS-13786 client: pool_free take rdlock for dp_co_list check

- src/common/tests/acl_api_tests.c
The daos_acl_size function could return an error, although the test expects to succeed.
> DAOS-13720 common: Check return code for negative value (#12416)

- src/client/dfuse/dfuse_core.c
- src/pool/cli.c
- src/utils/daos_hdlr.c
Check return codes for retried functions in daos_hdlr disconnect code.
> DAOS-13595 utils: Check return codes (#12346)

- src/cart/crt_corpc.c
Propagate err code from co_aggregate to co_info->co_rc.
> DAOS-13740 cart: fix coverity warning of unused rc

- src/client/dfs/dfs.c
- utils/node_local_test.py
Every 30 seconds print how many objects have been scanned in the dfs namespace or marked in the OIT. This informs users that there is some progress being done by the checker and it's not hung in case of a large namespace.
> DAOS-13175 dfs: print progress of dfs mwc checker

- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_tx.c
During TX convert, if -DER_TX_RESTART is returned, in spite of it is caused by stale pool map or transaction conflict, the TX convert logic needs to restart the internal transaction instead of forwarding the failure to upper layer caller.
> DAOS-13540 object: handle TX_RESTART during TX convert

- src/client/dfs/dfs_internal.c
- src/client/dfs/dfs_internal.h
lock module when checking for dfs is_init.
> DAOS-13792 dfs: fix for coverity 1443161 (#12486)

- ci/unit/required_packages.sh
- site_scons/site_tools/go_builder.py
- src/control/SConscript
- src/control/build/info.go
- src/control/build/string.go
- src/control/build/variables.go
- src/control/cmd/daos/main.go
- src/control/cmd/daos_agent/main.go
- src/control/cmd/daos_server/main.go
- src/control/cmd/dmg/main.go
The control plane (and daos CLI) binaries will now include the
git sha used for the build for non-release builds.
> DAOS-13236 control: Add commit sha to version for non-release binaries

- src/client/dfs/dfs.c
- utils/node_local_test.py
Every 30 seconds print how many objects have been scanned in the dfs namespace or marked in the OIT. This informs users that there is some progress being done by the checker and it's not hung in case of a large namespace.
> DAOS-13175 dfs: print progress of dfs mwc checker (#12470)

- src/client/array/dc_array.c
- src/client/dfs/dfs.c
Fix issue when truncating arrays.
> DAOS-13801 array: fix possible double free with FI (#12507)

- src/tests/ftest/pool/rf.yaml
Increase system_ram_reserved server config file parameter to ensure
that sufficient memory is reserved for system usage before allocating
to engine RAM-disks. This should avoid control-plane memory check
failures during the test.
> DAOS-13772 test: Bump system_ram_reserved for test_rf_pool_property

- src/control/cmd/daos_agent/config.go
- src/control/lib/control/config.go
- src/control/lib/daos/system_prop.go
- src/control/server/config/server.go
- src/tests/ftest/server/daos_server_config.py
Explicitly check the configured system name and fail if
it does not meet requirements.
Test-tag: pr test_daos_server_config_basic
> DAOS-13670 control: Add system name validation on startup

- src/cart/utils/crt_utils.c
- Avoid context queue draining for clients. This reduces cart_ctl run by ~5 seconds.
> DAOS-13451 cart: Don't drain queue for cart clients (#12535)

- src/cart/crt_ctl.c
- Fix coverity cid 1426658 Thread dedlock
- Issuing 'get uri cache' command at the wrong time could end up in a deadlock due to latest changes to lockings
> DAOS-13721 cart: Fix coverity cid 1426658

- ci/provisioning/post_provision_config_common_functions.sh
- debian/changelog
- debian/control
- utils/rpms/daos.spec
Needed for the dfuse/daos_build.py tests. Also disables
module filtering for the daos-stack-deps repository
in order to allow installation of newer golang RPMs.
> DAOS-13878 test: Install golang >= 1.18 as a daos-tests dep

- src/include/daos_srv/daos_engine.h
- src/object/obj_layout.c
- src/object/srv_obj_migrate.c
- src/rebuild/scan.c
- src/tests/suite/daos_upgrade.c
During object upgrade, dkey might be migrate to
different shards within the group due to EC parity rotation, so all shards within the group should
do fetch and update during migration, otherwise
some dkeys might be missing after upgrade.
Upgrade should do group special enumeration for the moment, since 2.4 does not change dkey->group mapping.
> DAOS-13493 rebuild: upgrate the whole group

- src/control/lib/daos/pool_property.go
- src/control/lib/daos/pool_property_test.go
The default value for the self_heal pool property is Exclude|Rebuild,
so the output should reflect this.
> DAOS-13213 control: Display exclude,rebuild for default self_heal

- src/container/srv_target.c
Remove unnecessary rc assignment in ds_cont_local_open.
> DAOS-13737 container: remove unnecessary assignment

- src/client/dfuse/dfuse_core.c
> DAOS-13781 dfuse: Remove a pointless assignment. (#12468)

- src/client/dfuse/ops/readdir.c
Ensure that resources are properly freed if errors are encountered during
readdir.
> DAOS-13604 dfuse: Fix resource leaks in readdir. (#12408)

- src/client/dfuse/il/int_posix.c
To avoid a problem where programs are hard-coding low numbered FDs
for use but not getting the FD they expect then open a number
of FDs before calling daos_init() and release them afterwards.
> DAOS-13381 il: Reserve low numbered fds when calling daos_init() (#12447)

- src/client/dfs/dfs.c
Fix incorrect use of daos vs system error number.
> DAOS-13598 dfs: Convert a return code correctly in dfs_read. (#12382)

- ci/jira_query.py
- debian/changelog
- utils/rpms/daos.spec
In the Requires: on the client-tests
* `Test-tag: test_dfuse_daos_build_wb` was used to validate that the daos build test passes
> DAOS-623 packaging: Fix go/golang per distro name

- src/control/cmd/dmg/main.go
- src/tests/ftest/control/daos_agent_config.py
- src/tests/ftest/control/daos_agent_config.yaml
- src/tests/ftest/control/daos_control_config.py
- src/tests/ftest/control/daos_control_config.yaml
- src/tests/ftest/control/version.py
Fix test regression with system name introduce with PR #12509:
Fix regression introduce with PR #12508: issue with _dmg_ and configuration files parsing.
Miscellaneous small improvements of the _src/tests/ftest/control/version.py_ test.
Test-tag is used to limit the tests to the functional ones updated by this PR.
> DAOS-13886 test: Fix system name validation

- src/vos/vos_aggregate.c
Without this patch, the HAE gets updated meaning that any such entries will never be aggregated until either a full scan happens or another update occurs in the subtree. If HAE is not updated, the entries will be re-scanned.
> DAOS-13884 vos: Avoid updating HAE when entries are skipped. (#12557)

- src/common/btree.c
Fixed few error propagation issues in btree implementation.
Note: The error cleanup in current btree implementation mostly relies on PMDK transaction abort, so memory leak could happen during the error cleanup for VMEM based tree. This patch only fixes the error propagation issue which could lead to assertion on PMDK tx commit, it doesn't intend to fix the error cleanup issues for VMEM based tree.
> DAOS-13341 vos: few other error propagation issues (#12389)

- src/client/kv/dc_kv.c
- src/tests/suite/daos_kv.c
- also fix some potential double free on error path
> DAOS-13907 kv: allow users to insert keys with empty values (#12590)

- src/include/daos_task.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_task.c
- src/tests/suite/daos_obj_ec.c
Before enumeration request fanout, it should check if any shard(sub) anchor still exist in the reqest targets anymore, if not, then the sub anchor should be marked as eof to make sure the enumeration can be ended.
Some cleanup and fix for EC object key2anchor.
Add test to verify the process.
> DAOS-13412 object: Check shard anchor for enumeration (#12496)

- docs/admin/troubleshooting.md
- src/control/cmd/daos_agent/infocache.go
- src/control/lib/cache/cache.go
- Return copies of the GetAttachInfoResp instead of the direct pointer.
- cache.Item implementations should assume the caller is responsible for locking/unlocking them, since the method is exported.
- cache.Cache.Keys() calls should use a read lock.
- Document daos_agent refresh signal in admin guide.
> DAOS-13696 control: Eliminate possible data races (#12442)

- src/cart/crt_corpc.c
- src/cart/crt_hg_proc.c
- src/cart/crt_rpc.c
- src/cart/crt_rpc.h
- src/include/cart/api.h
- split uint32_t cch_dst_tag into two uint16_t inside of the header
- src_timeout field added to the header (to be replaced by deadline later)
- CORPC children inherit timeouts from the parents header/source
> DAOS-13776 cart: Inherit CORPC timeout across children (#12585)

- src/control/lib/control/mocks.go
- src/control/lib/control/system_test.go
There were some cases where the external timeout was being hit in CI.
Also updated the mock InvokeUnaryRPC() method to allow the response- sending goroutine to abort during the response delay, if there is one.
> DAOS-13496 control: Extend timeout for SystemJoin unit test

- src/bio/bio_xstream.c
Keep using large cluster size(1GB) for pmem mode, since SPDK blobstore loading time is unexpected long for smaller cluster size(32MB).
> DAOS-13694 bio: use large cluster size for pmem mode (#12460)

- src/vos/vos_dtx.c
Add some sanity check when vos aggregation hit non-committed DTX entry that must be still in active DTX table.
> DAOS-13794 vos: non-committed DTX entry must be in active table

- src/control/cmd/daos/util.go
- src/utils/daos_hdlr.c
Update go code to flush and wait for completion on shutdown.
This avoids loosing any output from the c helper code.
> DAOS-11551 control: Flush c output buffer.

- src/mgmt/srv_pool.c
> DAOS-13678 mgmt: use large RPC timeout for pool creation (#12462)

- src/container/container_iv.c
- src/pool/srv_iv.c
daos_acl_validate() might fail because of out of memory (e.g.fault injection), don't assert them in the pool and container IV for this case.
> DAOS-13904 pool: don't assert ENOMEM for daos_acl_validate()

- src/object/obj_rpc.h
Commit 7010f2e unecessarily bumped the RPC version. Instead of adding back 2 object RPC version support, just revert this version bump for master and 2.4 to keep interop support with 2.2.
> DAOS-13957 object: revert object RPC version bump

- src/control/server/server.go
- src/control/server/server_utils_test.go
- src/tests/ftest/launch.py
- src/tests/ftest/util/server_utils_params.py
This change requires ofi_rxm to be specified manually if it is desired for ofi+tcp. There is now a non-RXM tcp provider available in libfabric.
Specify ofi_rxm explicitly in ftests.
We shouldn't use the non-RXM provider by default until it is more thoroughly tested with DAOS.
Add workaround for launch.py to alias ofi+tcp to ofi+tcp;ofi_rxm
> DAOS-13774 control: Don't append ofi_rxm to ofi+tcp provider (#12546)

- src/object/obj_rpc.h
Commit 7010f2e unecessarily bumped the RPC version. Instead of adding back 2 object RPC version support, just revert this version bump for master and 2.4 to keep interop support with 2.2.
> DAOS-13957 object: revert object RPC version bump (#12636)

- src/include/daos/object.h
- src/object/cli_obj.c
- src/object/obj_class.c
Shrink the group number of GX object to avoid putting multiple shards in the same domain during rebuild, which might break RF setting.
GX group number will be shrinked from target_num/domain_nr to target_num/domain_nr - RF.
Increase drain test timeout value.
> DAOS-13516 object: shrink the group number of GX object (#12217)

- src/tests/ftest/launch.py
Update the launch.py --provider choices to include the provider alias keys.
> DAOS-13990 test: Allow provider alias values as launch.py inputs.

- src/client/dfuse/pil4dfs/int_dfs.c
- utils/node_local_test.py
When a fd allocated by libpil4dfs is dupplicated by dup(), dup2(), and fcntl(, F_DUPFD, ), a real fd allocated by kernel would be returned. In those POSIX functions taking fd as parameters, fd should be checked whether it should be redirected to a fake fd allocated by libpil4dfs. 
> DAOS-13901 client: need to query whether a fd is redirected

- src/control/cmd/daos/util.go
Update go code to flush and wait for completion on shutdown.
This avoids loosing any output from the c helper code.
> DAOS-11551 control: Flush c output buffer. (#12632)

- src/cart/crt_corpc.c
- src/cart/crt_rpc.h
- overload cch_rc field in the request header to be used as a source timeout
- 2.4 clients will set it, but 2.2 server will not use that field as cch_rc is unused in the request header.
- 2.2 clients sending rpc request to 2.4 servers will have this field as 0. as such crt_corpc modified to not inherit source timeout if it is set as 0
> DAOS-13973 cart: Fix interop breakage between 2.2 and 2.4

- src/client/dfuse/dfuse.h
- src/client/dfuse/dfuse_core.c
- src/client/dfuse/ops/forget.c
- src/client/dfuse/ops/ioctl.c
- src/control/cmd/daos/filesystem.go
- src/tests/ftest/dfuse/daos_build.py
- src/utils/daos_hdlr.c
- utils/node_local_test.py
Improve error cases where path is not backed by dfuse.
Lock forget commands against inode query.
Print and accept inodes as integers only.
Evict the build tree as part of the DaosBuild test.
> DAOS-12751 dfuse: Improve evict command.

- src/object/cli_mod.c
- src/object/obj_internal.h
- src/object/obj_tx.c
- src/tests/suite/daos_dist_tx.c
Currently, the redundancy group information in the DTX header is only used for checking whether we lost some redundancy group or not during DTX resync. It allows DTX resync logic to detect corrupted DTX. It is not fatal if not support such functionality.
On the other hand, the redundancy group information may take more than half space in the DTX header. Consider DRAM usage on DTX leader, that may become burden for very large transaction. So the patch makes such redundancy group verification as optional. User can control that via client side environment variable "DAOS_TX_VERIFY_RDG" when start the client. By default, it is disabled.
> DAOS-13503 object: skip redundancy group verification when DTX resync

- src/client/api/array.c
- src/client/api/kv.c
- src/client/api/object.c
- src/client/array/dc_array.c
- src/client/dfs/dfs.c
- src/client/dfs/dfs_sys.c
- src/client/dfuse/dfuse_core.c
- src/client/dfuse/il/int_posix.c
- src/client/kv/dc_kv.c
- src/include/daos/array.h
- src/include/daos/kv.h
- src/include/daos/object.h
- src/object/cli_obj.c
- All object close operations (obj, array, kv) are local operation and have no RPC associated with them. If user calls those with a NULL ev, there is no need to create a tse task and can just call directly the underlying close/free operations.
- Remove the close retry hack calls for fault injection testing since there is no malloc on that path anymore.
> DAOS-14031 client: change close functions with NULL ev to bypass tse

- src/cart/crt_iv.c
- src/engine/server_iv.c
> DAOS-13906 engine: Check for memory allocation properly to avoid crash. (#12635)

- src/pool/srv_iv.c
The callers of pool_iv_prop_g2l() call daos_prop_free() on
failure so it does not need to free anything itself.
Move logging to log the failure before calling prop_free().
> DAOS-13902 pool: Avoid double-free on error. (#12586)

- src/control/cmd/daos_agent/security_rpc_test.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
- src/control/lib/support/log_test.go
- src/control/security/auth/mocks.go
- src/control/security/domain_info_test.go
* Use a mock test user to avoid exposure to environments
where a very large number of supplementary groups may
cause spurious test failures.
* Adjust expected pid 1 process name based on platform.
> DAOS-13980 control: Misc. unit test fixups

- src/pool/srv_util.c
- src/tests/suite/daos_drain_simple.c
Fix a bug of cont-open and in-flight IO failed as DER_NO_HDL during drain, by don't treat DRAIN target as failed.
Add a test case to verify it.
> DAOS-13966 rebuild: don't treat DRAIN target as failed (#12631)

- src/tests/ftest/launch.py
Test-tag: pr
- newer versions of fi_info show providers that aren't actually supported for our uses.
- We want to move to hg_info anyway
- Just replace usage of fi_info with hg_info
> DAOS-13964 test: use hg_info instead of fi_info

- src/control/lib/control/pool.go
- src/control/lib/control/pool_test.go
JSON marshalling fails when attempting to print PoolGetProps()
control-API response as some of the returned properties have no
associated value set. This can occur when dmg pool get-prop is called
from a >= v2.4 dmg/daos_server using a pool that was created with v2.2.
This occurs because the old pool has a reduced set of properties and so
those that don't have an associated value in the RPC response end up
as PoolProperty objects with no associated value (which is not allowed
in the JSON marshal implementation for the type).
Solution is to remove the missing properties from the response before
sending to dmg, the control-API consumer. This does mean that
get-props calls can return a different property list depending on
which DAOS version was used to create the pool. …
> DAOS-13919 control: Fix dmg pool get-prop compat with v2.2 pools

- src/common/misc.c
- src/engine/server_iv.c
Errors in some sgl functions were not being propagated
which was leading to crashes in higher level code.
> DAOS-13905 common: Fix return code from daos_sgl functions.

- src/object/cli_obj.c
Cannot close the shard in the body function of RPC task since it can be completed by another task before the shard close completes, which would  make the main calling thread exit the main function before the shard is closed. If the calling thread closes the actual object before the shard is closed, we can have memory corruption issues.
> DAOS-12638 object: close shard in task completion callback (#12726)

- src/client/api/event.c
Assertion that event is in READY state should be only if progress returns success.
> DAOS-14071 client: do not assert event is ready if progress fails

- src/control/lib/control/system_test.go
- src/control/server/ctl_ranks_rpc.go
- src/control/server/ctl_ranks_rpc_test.go
- src/control/system/member.go
- src/control/system/membership_test.go
Change addresses the issue where dmg system stop fails if some ranks
have already been previously stopped. This is due to a couple of bugs.
First a situation exists where the state conveyed in a MemberResult
doesn't match the fact that the result was a failure. The consumer of
the results checks this and raises an error in the case that they don't
match. Secondly the PrepShutdown flow which is triggered as stage-one
of dmg system stop returns a failed result for an already stopped rank.
Fixes made:
- Return successful results when calling PrepShutdown on stopped ranks
- Ensure errored MemberResults convey a matching error state
> DAOS-13988 control: MemberResult state should reflect error

- src/common/misc.c
- src/engine/server_iv.c
Errors in some sgl functions were not being propagated
which was leading to crashes in higher level code.
> DAOS-13905 common: Fix return code from daos_sgl functions. (#12706)

- .github/workflows/landing-builds.yml
Github actions ARM build is failing available RAM check on engine
start due to the recent increase in default system_ram_reserved value
to 16gib. The docker environment is memory constrained and so reducing
system_ram_reserved to 6gib (the previous default) should fix the
problem. The ARM builds are only run on landings which is why this
issue was not found in PR test.
> DAOS-13672 test: Reduce system_ram_reserved for GHA ARM build

- src/control/server/engine/config.go
- src/control/server/engine/config_test.go
Ensure parameters in engine config section of server config file are
not populated with negative values.
> DAOS-14091 control: Validate against negative ints in engine conf

- src/tests/ftest/rebuild/widely_striped.yaml
Removing some swim timeouts previously added as per recommendations to the test yaml.
List of removed env vars:
- SWIM_PROTOCOL_PERIOD_LEN=2000
- SWIM_SUSPECT_TIMEOUT=19000
- SWIM_PING_TIMEOUT=1900
Test-tag: test_rebuild_widely_striped
> DAOS-14053: Removing some swim timeouts added previously

- src/control/lib/control/system_test.go
- src/control/server/ctl_ranks_rpc.go
- src/control/server/ctl_ranks_rpc_test.go
- src/control/system/member.go
- src/control/system/membership_test.go
Change addresses the issue where dmg system stop fails if some ranks
have already been previously stopped. This is due to a couple of bugs.
First a situation exists where the state conveyed in a MemberResult
doesn't match the fact that the result was a failure. The consumer of
the results checks this and raises an error in the case that they
don't match. Secondly the PrepShutdown flow which is triggered as
stage-one of dmg system stop returns a failed result for an already
stopped rank.
* Return successful results when calling PrepShutdown on stopped ranks
* Ensure errored MemberResults convey a matching error state
> DAOS-13988 control: MemberResult state should reflect error (#12719)

- utils/build.config
Patches are required to ensure thread safety of prov/tcp
> DAOS-13964 build: update libfabric to 1.18.1 and apply prov/tcp patches

- src/include/daos_srv/daos_engine.h
- src/object/obj_layout.c
- src/object/srv_obj_migrate.c
- src/rebuild/scan.c
- src/tests/suite/daos_upgrade.c
During object upgrade, dkey might be migrate to
different shards within the group due to EC parity rotation, so all shards within the group should
do fetch and update during migration, otherwise
some dkeys might be missing after upgrade.
Upgrade should do group special enumeration for the moment, since 2.4 does not change dkey->group mapping.
> DAOS-13493 rebuild: upgrate the whole group (#12550)

- src/container/srv_container.c
- src/placement/jump_map.c
- src/placement/jump_map_versions.c
- src/rebuild/scan.c
- src/rebuild/srv.c
Only check spare target if layout version > 0, since before 2.4, it will not assign the shard if there are no spare targets.
fix spare_tgt check.
Skip invalid shard and target for upgrade migration.
set reclaim ver for upgrade.
remove invalid assertion for rebuild retry.
Mark upgrade complete in any case.
> DAOS-13493 rebuild: various fixes for upgrade

- src/object/cli_obj.c
In obj_shard_task_sched() it schedules the shard tasks and then set "obj_auxi->shards_scheded = 1". It is not safe as once shard tasks scheduled it possibly be executed immediately by other threads and completed, that cause the obj_auxi be invalid and cause mem corruption. The problem found by Mohamad.
> DAOS-14119 object: fix a bug of shards_scheded setting

- src/vos/vos_common.c
- src/vos/vos_dtx.c
- src/vos/vos_internal.h
master-commit: 4c2d296e70c9a383ba4a98403a0afafebb534f8d
For md_on_ssd case, the DTX abort logic may hit some slow DTX entry that is in preparing but yield for local TX commit. Under such case, the abort logic should not directly abort the busy DTX to avoid race, instead, it can notify the preparing sponsor to delay to abort the DTX entry via set dae->dae_aborting.
> DAOS-13968 vos: handle race between DTX prepare and DTX abort

- src/client/dfuse/dfuse.h
- src/client/dfuse/dfuse_fuseops.c
- src/client/dfuse/ops/create.c
- src/client/dfuse/ops/ioctl.c
- src/client/dfuse/ops/lookup.c
- src/client/dfuse/ops/mknod.c
- src/client/dfuse/ops/read.c
- src/client/dfuse/ops/readdir.c
- src/client/dfuse/ops/symlink.c
- src/client/dfuse/ops/unlink.c
- src/client/dfuse/ops/write.c
Remove all remaining places that dfuse_projection_info was stil
used.
> DAOS-13625 dfuse: Remove dfuse_projection_info entirely.

- src/tests/ftest/deployment/critical_integration.py
Resolving version check issue reported after changes in daos_server and dmg version output.
To be more flexible in future, moved to json output
Test-tag: test_passwdlessssh_versioncheck
> DAOS-13981 test: Resolve version check issue in critical integration test

- src/control/server/harness_test.go
Attempting to re-store the atomic after addition created a gap where a race could occur, causing incremental test failures when checking the number of times Start was called.
> DAOS-14113 control: Fix unit test race condition

- src/container/srv_target.c
- src/include/daos/object.h
- src/include/daos_srv/container.h
- src/include/daos_srv/pool.h
- src/include/daos_srv/vos.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/srv_ec_aggregate.c
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/vos/vos_aggregate.c
1. reverse recx enumeration order, so data from parity rebuild will be rebuilt first, then if any replicate data being left after EC aggregation, they will be ignored during rebuild.
2. Exclude EC aggregation with the whole rebuild process to avoid enumeration might enumerate any aggregating replicate recx.
> DAOS-13295 rebuild: reverse recx enumeration order for rebuild

- src/rebuild/rebuild_internal.h
- src/rebuild/srv.c
- src/tests/suite/daos_rebuild_common.c
During rebuild status query, reclaim phase should be marked as complete, since these reclaim objects won't be touched anyone else.
Retry with reintegrate/drain/extend for DER_BUSY in test.
> DAOS-13941 rebuild: reclaim phase should be marked as complete (#12679)

- src/bio/bio_device.c
- src/bio/bio_xstream.c
- src/control/server/ctl_smd_rpc.go
- src/control/server/ctl_smd_rpc_test.go
When calling dmg storage set nvme-faulty, device state transitions can
take multiple seconds to propagate in engine-internal state machines.
As a result, a subsequent call to dmg storage replace nvme call issued
immediately after will return -DER_BUSY if state transitions are not
complete. For convenience, this change allows the replace call to
retry the drpc call internally if -DER_BUSY is received. The retry
mechanism employed uses exponential backoff and a fixed retry limit.
Also fix two VMD-LED issues:
- Cancel identify timer when setting LED state.
- Set LED to OFF state when device is physically replaced.
> DAOS-14101 control: Retry SMD manage request on DER_BUSY

- src/object/srv_obj_migrate.c
Shrink the object migrate ULT limit to 512, since putting too much ULT might saturate the single context, and causing timeout sometmes.
Use rand() to choose the enumeration target.
> DAOS-13295 object: shrink the object migrate ULT limit

- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_tx.c
If CPD RPC gets -DER_HG or -DER_EXCLUDED error, it spite of it is from client local network or remote server, it means that related target may be unavailable. Under such case, related distributd TX should restarted instead of directly resent. That will avoid miss TX conflict detection on related unavailable target. It will also generate new targets list after TX restart.
> DAOS-14150 object: restart distributed TX if hit unavailable target

- Jenkinsfile
Mock on fedora/38 is broken for building Leap 15 RPMs, so force the use of 37.  This change was missed as part of the commit 036678e changes.
> SRE-1935 build: Build Leap 15 RPMs with FVERSION=37

- src/control/cmd/daos_server/auto.go
- src/control/cmd/daos_server/auto_test.go
- src/control/cmd/dmg/auto.go
- src/control/cmd/dmg/auto_test.go
INFO level log messages were being printed to stdout during the
execution of dmg config generate meaning that the output could not be
redirected to a .yml file and used as a daos_server config. Fix by
adjusting the effective log level to ERROR during execution of the
ConfigGenerate Control-API call. The INFO and NOTICE logging can
safely be ignored as these messages are intended for daos_server users
when running in daemon mode. In order to preserve --debug cmdline
functionality, don't adjust the log level if running with the flag set.
> DAOS-14085 control: Fix config generate yaml printed to stdout (#12770)

- src/cart/crt_hg.c
- src/gurt/tests/test_gurt.c
- src/include/daos/common.h
- src/include/daos_errno.h
Reverts daos-stack/daos#12199
Reverting to test DAOS-14182.
> Revert "DAOS-13239 cart: Fix send failure error mapping.."

- src/ddb/ddb.c
- src/ddb/ddb_spdk.c
> DAOS-14152 ddb: Mismatched Dealloc Fix

- src/bio/bio_device.c
- src/bio/bio_xstream.c
- src/vos/tests/bio_ut.c
- utils/run_utest.py
SSDs can store LED state between server restarts so load state for
each bdevs after they have all been created. Additionally, don't
require state receiver in bio_led_manage.
Includes some small bio_ut fixes to enable logging in test and run 
in a local environment with linux file written to /dev/vdb.
> DAOS-14075 bio: Sync LED state on engine start

- docs/admin/administration.md
- src/control/cmd/dmg/storage_query.go
- src/control/cmd/dmg/storage_query_test.go
- src/control/server/ctl_smd_rpc.go
- src/control/server/ctl_smd_rpc_test.go
- src/mgmt/srv_query.c
To make identifying multiple SSDs (or whole nodes in a rack) easy, all
SSDs on all hosts specified in the commandline or config file hostlist
will be selected if no identifiers are provided in the commandline
positional arguments. This changes applied to dmg storage led
(identify|check) commands.
> DAOS-12670 control: Select all devices by default in led manage cmds

- src/rebuild/rebuild_iv.c
- src/rebuild/scan.c
Since ABT_mutex_lock might yield, so it needs to check global dtx with current rebuild version before wait, in case condition sigal has been issued, then it may wait infinitely.
> DAOS-13295 rebuild: check dtx global version before wait

- src/rebuild/rebuild_internal.h
- src/rebuild/srv.c
- src/tests/suite/daos_rebuild_common.c
Revert PR-12679, since it regard "reclaim" phase as rebuild/upgrade complete, though this cause a lot rebuild operation DER-BUSY failure, let's revert this PR for now.
DAOS-13941 rebuild: reclaim phase should be marked as complete (#12679)
> DAOS-14169 rebuild: revert PR-12679

- src/container/srv_container.c
missing pool hdl put in belongs_to_user().
> DAOS-14205 container: missing pool hdl put (#12869)

- src/tests/ftest/util/soak_test_base.py
- src/tests/ftest/util/soak_utils.py
The ranks used for the "dmg pool extend" harasser should be random and currently the test uses the same ranks throughout the test.    This PR will randomize the server used to get the ranks.
> DAOS-14185 test: Randomize server ranks for soak extend

- src/client/dfs/dfs.c
DAOS 2.0 is now very old and there are no known deployments with persistent datasets using the old layout version of DFS containers. Given that, remove the layout compatibility support for old DFS containers and cleanup the code.
> DAOS-14213 dfs: remove support for DAOSv2.0 layout

- src/rebuild/rebuild_iv.c
- src/rebuild/scan.c
Since ABT_mutex_lock might yield, so it needs to check global dtx with current rebuild version before wait, in case condition sigal has been issued, then it may wait infinitely.
> DAOS-13295 rebuild: check dtx global version before wait (#12836)

- src/container/srv_target.c
- src/include/daos/object.h
- src/include/daos_srv/container.h
- src/include/daos_srv/pool.h
- src/include/daos_srv/vos.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/srv_ec_aggregate.c
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/vos/vos_aggregate.c
1. reverse recx enumeration order, so data from parity rebuild will be rebuilt first, then if any replicate data being left after EC aggregation, they will be ignored during rebuild.
2. Exclude EC aggregation with the whole rebuild process to avoid enumeration might enumerate any aggregating replicate recx.
> DAOS-13295 rebuild: reverse recx enumeration order for rebuild (#12641)

- site_scons/prereq_tools/base.py
- site_scons/site_tools/extra/extra.py
The DAOS build will fail if a user builds prerequisites under /usr such as when the home directory is nested within.  This patch simply changes the check for
whether to patch rpath to continue if prereq is in the path for the binary in question.
> DAOS-14216 build: Build fail if home is under /usr

- src/object/srv_obj.c
Bypass check for EC agg or migrate, as coh->sch_cont is NULL for server cont handle.
> DAOS-14176 object: refine obj_capa_check (#12873)

- src/tests/ftest/util/soak_test_base.py
- src/tests/ftest/util/soak_utils.py
The ranks used for the "dmg pool extend" harasser should be random and currently the test uses the same ranks throughout the test. This PR will randomize the server used to get the ranks.
> DAOS-14185 test: Randomize server ranks for soak extend (#12850)

- docs/admin/pool_operations.md
> DAOS-13697 document: update pool upgrade limit

- src/control/server/harness_test.go
Attempting to re-store the atomic after addition created a gap where a race could occur, causing incremental test failures when checking the number of times Start was called.
> DAOS-14113 control: Fix unit test race condition (#12803)

- src/dtx/dtx_common.c
- src/gurt/hlc.c
- src/include/daos_srv/dtx_srv.h
- src/include/gurt/common.h
- src/vos/vos_dtx.c
When try to purge old non-committed DTX which age exceeds VOS aggregation time threshold, then generate some warning message. That will much reduce fake warning messages.
The patch also removes some old debug-purposed check.
> GCP-215 vos: warning message for purging old non-committed DTX

- src/container/container_iv.c
- src/engine/server_iv.c
- src/object/srv_obj.c
- src/pool/srv_iv.c
It does not need to check invalid entry in pool_iv_ent_invalid(), because disconnection will remove entry locally on all nodes, so the entry is not really invalid, otherwise, disconnect handles will be left in the IV cache, then during extend, these handles might be fetched by the new rank incorrectly.
Move iv_valid check into the callback, because in some cases, if invalidate only invalid a single item under one entry, for example disconnect handle, it does not need set the entry to be invalid.
> DAOS-14158 pool: do not check iv valid for entry invalid

- site_scons/prereq_tools/base.py
The DAOS build will fail if a user builds prerequisites under /usr such as when the home directory is nested within. This patch simply changes the check for whether to patch rpath to continue if prereq is in the path for the binary in question.
> DAOS-14216 build: Build fail if home is under /usr (#12907)

- src/cart/crt_rpc.c
- src/cart/crt_rpc.h
- src/cart/crt_self_test_service.c
- src/include/cart/api.h
- src/tests/ftest/cart/iv/iv_one_node.py
- src/tests/ftest/cart/iv_client.c
- src/tests/ftest/cart/iv_server.c
Do not read the vales from RPC desc after decref.
Only log address in decref, not contents.
Change rpc addref and decref to be void functions.
rc was only checked in test code.
> DAOS-14163 cart: Do not access rpc after decref.

- src/control/server/ctl_smd_rpc.go
Increase the number of dRPC device replace retries made during dmg
storage replace nvme when DER_BUSY is returned because blobstore state
has not transitioned yet in SMD. This will prevent occasional command
failure when said state transitions take longer than usual when a host
is populated with a large number of devices or there is high load.
> DAOS-14101 control: Bump maximum number of retries for dev replace

- src/tests/ftest/util/soak_utils.py
By adding a unique dir to each dfuse mount this will ensure that every job does not reuse a mount dir.
> DAOS-14230 test: Add unique id to dfuse mountpoint

- src/tests/ftest/util/soak_utils.py
By adding a unique dir to each dfuse mount this will ensure that every job does not reuse a mount dir.
> DAOS-14230 test: Add unique id to dfuse mountpoint (#12954)

- docs/admin/administration.md
- docs/admin/pool_operations.md
This patch ports following two master commits:
master-commit: 8209b47fce9b9f749abaf45e06f299b1f68fb220
DAOS-13697 doc: add documentation for pool upgrade
and
master-commit: 6ed01bf03769939e88fbce2a8cea2e99d7009aa9
DAOS-13697 document: update pool upgrade limit
>  DAOS-13697 doc: add documentation for pool upgrade

- .github/workflows/spelling.yml
This file is a list of checksums, do not run spelling checks on it.
> DAOS-623 cq: Do not run spelling check on go.sum

- src/tests/ftest/deployment/critical_integration.py
Resolving version check issue reported after changes in daos_server and dmg version output.
To be more flexible in future, moved to json output
Test-tag: test_passwdlessssh_versioncheck
> DAOS-13981 test: Resolve version check issue in critical integration test (#12767)

- src/tests/ftest/harness/setup_vm.py
- src/tests/ftest/harness/setup_vm.yaml
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/server_utils.py
- src/tests/ftest/util/server_utils_base.py
Functional test timeouts for the storage prepare and format steps in bringing up the server engines are now be based upon the number of NVMe devices defined in the server configuration.
Ensure a minimum 40 second pattern timeout is used.
Separate HarnessSetupTest tests into two files.
Test-tag: pr HarnessSetupTest HarnessSetupVmTest
> DAOS-14157 test: Update storage timeouts based upon config (#12847)

- src/tests/ftest/util/storage_utils.py
- utils/cq/words.dict
When generating storage:auto server configurations for functional tests exclude any detected devices that are mounted.
> DAOS-14171 test: Exclude mounted devices in auto storage (#12839)

- src/cart/crt_rpc.h
Do not log target rank in decref as rpc there is no reference held.
> DAOS-14163 cart: Do not access rpc after decref

- src/cart/swim/swim_internal.h
- src/tests/ftest/cart/rpc/swim_notification.yaml
It seems that a less-than-1-second ib link status change may cause a 17-second RPC outage at the daos level. Although we do not know if this is fundamentally the case for all networks DAOS supports, try increasing the default SWIM suspicion timeout to 20 s to be more conservative.
> DAOS-14027 cart: Revise default SWIM parameters

- docs/admin/administration.md
- src/bio/bio_device.c
- src/bio/bio_xstream.c
- src/control/cmd/dmg/storage_query.go
- src/control/cmd/dmg/storage_query_test.go
- src/control/server/ctl_smd_rpc.go
- src/control/server/ctl_smd_rpc_test.go
- src/mgmt/srv_query.c
- src/vos/tests/bio_ut.c
- utils/run_utest.py
SSDs can store LED state between server restarts so load state for
each bdevs after they have all been created. Additionally, don't
require state receiver in bio_led_manage.
Includes some small bio_ut fixes to enable logging in test and run in
a local environment with linux file written to /dev/vdb.
(other backport PRs in stack...)
DAOS-12670 control: Select all devices by default in led manage cmds (#12848)
To make identifying multiple SSDs (or whole nodes in a rack) easy, all
SSDs on all hosts specified in the commandline or config file hostlist
will be selected if no identifiers are provided in the commandline
positional arguments. This changes applied to dmg storage led
(identify|check) commands.
> DAOS-14075 bio: Sync LED state on engine start (#12749)

- src/tests/ftest/pool/list_verbose.py
Description: added pool state and rebuild_state to pool list verbose verification.
> DAOS-14243 test: pool/list_verbose.py:test_fields_basic - missing rebuild_state

- src/tests/ftest/control/dmg_system_reformat.yaml
Bump system_ram_reserved to 32 to avoid OOM-killer terminating engine process.
Skip-func-hw-test-medium-ucx-provider: true
Test-tag pr daily_regression
> DAOS-13613 test: Make 2nd pool create fail with ENOSPACE

- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/tests/ftest/deployment/basic_checkout.py
- src/utils/daos_hdlr.c
Features: daos_fs_copy daos_cont_clone
PR #11189 moved the container create messages to the GO code, but this isn't correct because the container isn't *always* created.
The original logging issue was resolved by #12632, so the messages can be moved back to the C code where there is finer control.
> DAOS-13499 tools: fix datamover container create message

- src/tests/ftest/container/snapshot.py
- src/tests/ftest/container/snapshot.yaml
To avoid ENOSPACE failures with large single value writes the pool size has been increased in the container/snapshot.py test.
Test-tag: Snapshot
> DAOS-13674 test: Bump pool size in container/snapshot.py

- src/tests/ftest/container/snapshot.py
- src/tests/ftest/container/snapshot.yaml
To avoid ENOSPACE failures with large single value writes the pool size has been increased in the container/snapshot.py test.
Test-tag: Snapshot
> DAOS-13674 test: Bump pool size in container/snapshot.py (#13012)

- src/tests/ftest/pool/create_all_vm.yaml
See the Jira ticket for the context. This patch reduces the number iterations in test_recycle_pools_vm so that each iteration will get more time and the test will take less time.
Test-tag: PoolCreateAllVmTests
> DAOS-14228 tests: Adjust pool/create_all_vm.yaml (#12955)

- src/cart/crt_hg.c
- Do not print an internal layer error when exceeding the context limit, as daos client layer will try to allocate as many contexts as it can in some usage models. Printing an error is not user friendly in such situations.
> DAOS-14328 cart: Do not print error when exceeding context limit

- ci/rpm/build_unsuccessful.sh
- utils/rpms/packaging/rpm_chrootbuild
Some debugging for failures meant that the actual result was being
masked.  Move the debugging to the "unsuccessful" script and
re-instate the fail-on-failure behaviour.
> DAOS-623 build: Fail the build stage in Jenkins for rpm build failure.

- src/tests/ftest/util/server_utils.py
Resolve an issue wherte cleanup commands need to be run on a subset of the test hosts running servers.
> DAOS-14254 test: Fix functional test server cleanup

- src/tests/suite/daos_drain_simple.c
- src/tests/suite/daos_extend_simple.c
- src/tests/suite/daos_obj_ec.c
Do not run the DAOS_Drain_Simple test when DAOS is built without fault injection.
Also skipping the DAOS_Extend_Simple.EXTEND[7,9,11,13,15,16] and DAOS_EC.EC28 test when fault injection is disabled.
Test-tag: test_daos_drain_simple test_daos_extend_simple test_daos_ec_obj
> DAOS-14302 test: Skip DAOS_Drain_Simple w/o fault injection (#13039)

- src/control/cmd/daos_agent/main.go
- src/control/cmd/dmg/main.go
- src/control/common/proto/consts.go
- src/control/lib/control/interceptors.go
- src/control/lib/control/mocks.go
- src/control/lib/control/rpc.go
- src/control/security/grpc_authorization.go
- src/control/security/grpc_authorization_test.go
- src/control/server/interceptors.go
- src/control/server/interceptors_test.go
- src/control/server/server.go
- src/control/server/server_utils.go
The interoperability checking code relies on getting the
peer component from the peer certificate. When running
in insecure mode, the peer component information is
unavailable, and the interoperability check defaults
to the most stringent requirements.
This patch adds new component/version headers to the
grpc client request to allow the server to perform
interoperability checks without the peer certificate.
Change-Id: I1d9a6d171ecadded3bf041a36e2a156881d93f57
> DAOS-14332 control: Use gRPC metadata for interop

- src/tests/ftest/util/test_utils_pool.py
When using the TestPool.pool_query_delay BasicParameter access its value property not the object.
Test-tag: rebuild
> DAOS-14385 test: Fix TestPool.pool_query_delay use

- src/control/cmd/daos_server/start.go
- src/control/server/config/server.go
- src/control/server/server.go
Add daos_server start --auto option to enable engines to start without
having to trigger a storage format with an externally executed dmg
storage format command. If the flag is detected the server will call
the format API during its start-up routine and if the server config
file used is valid the engines will be started after format completes.
> DAOS-12425 control: Add opt to auto-format on server start-up

- src/tests/ftest/cart/util/cart_logtest.py
- src/tests/ftest/launch.py
Update log_test to not check for descriptor consistency when parsing
ftest logs.  As ftest debug masks change on live systems these tests
aren't valid and will fail if RPCs are in flight during the change.
> DAOS-14052 test: Update cart_logtest usage in launch.py

- src/control/cmd/daos/flags.go
- src/control/cmd/daos/flags_test.go
- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
Updated the error message in case of wrong value or none is provided.
Code is trying to pass the command line value to ParseFloat(). If it's a string it returns ErrSyntax like "strconv.ParseFloat: parsing "": invalid syntax". Which is little bit more detailed coding error. So instead returning the ErrSyntax, it's wrapped with descriptive message.
> DAOS-9653 control: Improve pool creation error message

- src/client/dfuse/dfuse_main.c
libfuse supports opening /dev/fuse and passing the file descriptor as the mountpoint. In some cases, realpath may not work for these file descriptors, and so we should ignore ENOENT errors and instead check that we can get file descriptor attributes from the given path.
> DAOSGCP-213 dfuse: Ignore ENOENT errors on file descriptors

- src/client/dfs/duns.c
> DAOS-623 build: fix build when lustre APIs are installed (#13069)

- src/engine/drpc_client.c
- src/mgmt/srv_drpc.c
This function returns -1 rather than a daos errno so treat it
as such.
Do not use the result in DF_RC as it will print DER_UNKNOWN.
Put the call in the if statement itself rather than assigning rc.
Use the new logging macros to log the error proplerly.
Do not log the invalid uuid.
> DAOS-14438 mgmt: Improve error reporting on uuid_parse failure.

- src/vea/vea_free.c
Reclaiming unused bitmaps might yield for MD-on-SSD, we need make sure those lists(to be reclaimed) could be not allocated by reserve ult
> DAOS-14417 vea: reclaim bitmaps might yield for MD-on-SSD

- src/control/lib/support/log_test.go
The test runs hostname -d and checks that the result is a substring of os.Hostname(), which is not the case in our environment.
From the man page, hostname -s should give us the hostname cut at the first dot, so I would expect this to be portable.
> DAOS-14420 control: use hostname -s instead of -d

- src/rebuild/srv.c
Only show tgts_buf if there are real targets in task structure.
> DAOS-14450 rebuild: Only print target buffers if there are any

- docs/admin/tiering_uns.md
The old Lustre dynamic tuneable name had been
mistakenly left in documentation (daos_enable vs now foreign_symlink_enable).
> DAOS-6412 doc: fix Lustre dynamic tuneable name

- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/tests/ftest/deployment/basic_checkout.py
- src/utils/daos_hdlr.c
Features: daos_fs_copy daos_cont_clone
PR #11189 moved the container create messages to the GO code, but this isn't correct because the container isn't *always* created.
The original logging issue was resolved by #12632, so the messages can be moved back to the C code where there is finer control.
> DAOS-13499 tools: fix datamover container create message (#12642)

- src/tests/ftest/control/log_entry.yaml
The server config file setting of system_ram_reserved: 1 is probably
too low for this test. It was presumably set to this value as the test
is only run on VMs but given the test force kills ranks and restarts
them a 1gib reserve of RAM is not enough. Bump value to 2gib.
> DAOS-14427 test: Bump system_ram_reserved for control/log_entry ftest (#13105)

- docs/admin/administration.md
- src/control/cmd/dmg/storage_query.go
- src/control/cmd/dmg/storage_query_test.go
- src/control/server/ctl_smd_rpc_test.go
Report health of all devices on a given host by default when calling
dmg storage query device-health.
> DAOS-12174 control: Query all device-health by default (#12701)

- src/common/ad_tx.c
- src/common/dav/bucket.c
- src/common/dav/bucket.h
- src/common/dav/dav.h
- src/common/dav/dav_iface.c
- src/common/dav/dav_internal.h
- src/common/dav/heap.c
- src/common/dav/heap.h
- src/common/dav/obj.h
- src/common/dav/palloc.c
- src/common/dav/palloc.h
- src/common/dav/recycler.c
- src/common/dav/recycler.h
- src/common/dav/tx.c
- src/common/mem.c
- src/common/tests/umem_test_bmem.c
- src/include/daos/mem.h
- New umem macros are exported to do the allocation within memory bucket. umem internally now calls the modified backend allocator routines with memory bucket id passed as argument.
- umem_get_mb_evictable() and dav_get_zone_evictable() are added to support allocator returning preferred zone to be used as evictable memory bucket for current allocations. Right now these routines always return zero.
- The dav heap runtime is cleaned up to make provision for memory bucket implementation.
> DAOS-13701: Memory bucket allocator API definition

- src/tests/ftest/util/server_utils.py
Add raising exceptions for failed server file cleanup steps during
server startup and limiting mount cleanup to existing mount points.
Resolve an issue where cleanup commands need to be run on a subset of
the test hosts running servers.
> DAOS-14254 test: Improve test harness server file cleanup in startup (#12978)

- src/common/dav/dav_iface.c
- src/common/mem.c
- src/common/tests/umem_test.c
- src/include/daos/mem.h
- src/vos/vos_pool.c
Four sets of umem cache APIs will be exported for md-on-ssd phase II:
1. Cache initialization & finalization
- umem_cache_alloc()
- umem_cache_free()
2. Cache map, load and pin
- umem_cache_map();
- umem_cache_load();
- umem_cache_pin();
- umem_cache_unpin();
3. Offset and memory address converting
- umem_cache_off2ptr();
- umem_cache_ptr2off();
4. Misc
- umem_cache_commit();
> DAOS-13703 umem: umem cache APIs for phase II

- src/tests/ftest/control/dmg_storage_query.py
Resolve a test failure with test_dmg_storage_query_devices when running on a MD on SSD storage configuration with multiple data NVMe drives.
Test-tag: test_dmg_storage_query_devices
> DAOS-13687 test: Fix storage query for multiple data NVMes

- src/tests/ftest/pool/pda.py
PR12605 changed the default value.
Test-tag: pr pool_pda_property
> DAOS-14137 tests: change expected rp_pda property value

- src/tests/ftest/control/dmg_storage_query.py
Resolve a test failure with test_dmg_storage_query_devices when running on a MD on SSD storage configuration with multiple data NVMe drives.
Test-tag: test_dmg_storage_query_devices
> DAOS-13687 test: Fix storage query for multiple data NVMes (#13173)

- src/chk/chk_engine.c
- src/chk/chk_leader.c
When need interaction for inconsistency pool label or container label, embedding the pool label or container label in related repair options will help the user to make the decision easily.
> DAOS-13989 chk: embed label into repair options

- src/tests/ftest/pool/verify_space.py
When running on CI cluster with larger disks, display the disk usage in GB in the df output so that the checks work correctly.
Test-tag: test_verify_pool_space
> DAOS-3672 test: Fix larger capacity pool size verification

- src/tests/ftest/pool/verify_space.py
- src/tests/ftest/pool/verify_space.yaml
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/general_utils.py
- src/tests/ftest/util/server_utils.py
- src/tests/ftest/util/test_utils_pool.py
Automating a manual test that verifies the pool space usage with system commands.
Test-tag: test_verify_pool_space test_aggregation_io_small test_io_sys_admin
> DAOS-3672 test: Verify pool space usage via sys commands (#13045)

- src/client/dfuse/pil4dfs/int_dfs.c
- src/tests/ftest/util/cmocka_utils.py
- src/tests/ftest/util/verify_perms.py
- utils/node_local_test.py
intercept fstatat() with trampoline. add nlt test for file. also replace "a" with "w" in open since O_APPEND is not supported by DFS.
> DAOS-14521 client: intercept __pread64_chk() and __read_chk()

- src/client/dfuse/pil4dfs/hook.c
- src/tests/ftest/util/verify_perms.py
> DAOS-14508 client: free memory *buf in case of error in read_map_file()

- src/tests/ftest/control/dmg_telemetry_io_basic.py
The test_io_telmetry_metrics_basic test was ignoring failures from the run_ior_with_pool function, which will raise an error if there is a problem setting up dfuse.  Ignoring this failure can then result in issues running subsequent ior commands.
Test-tag: test_io_telmetry_metrics_basic
> DAOS-14461 test: Fix ignoring ior/dfuse failures

- src/tests/ftest/control/dmg_telemetry_io_basic.py
The test_io_telmetry_metrics_basic test was ignoring failures from the run_ior_with_pool function, which will raise an error if there is a problem setting up dfuse.  Ignoring this failure can then result in issues running sunsequent ior commands.
Test-tag: test_io_telmetry_metrics_basic
> DAOS-14461 test: Fix ignoring ior/dfuse failures (#13207)

- src/tests/ftest/control/dmg_system_reformat.yaml
Bump system_ram_reserved to 32 to avoid OOM-killer terminating engine
process.
Test-tag: pr test_dmg_system_reformat
> DAOS-13613 test: Make 2nd pool create fail with ENOSPACE (#12998)

- utils/cr_demo/demo_utils.py
- utils/cr_demo/run_demo_aurora.py
- utils/cr_demo/show_fixed_aurora.py
Following bandit issue was reported in feature/cat_recovery branch:
```
Test ID: B404 Severity: LOW Confidence: HIGH
CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
Consider possible security implications associated with the subprocess module.
Location ./utils/cr_demo/demo_utils.py:6
```
+2 other files. They all need nosec at the end of the line to exclude these lines from the bandit check because we treat import subprocess as not an issue.
> DAOS-14534 test: Fix bandit issues in CR demo scripts

- src/tests/ftest/pool/list_verbose.py
Fix full_regression test failures caused by commit 6a99368a2bb18e0f0e90b2ff4891bbeffa346034.
Skip-func-hw-test-medium-ucx-provider: true
> DAOS-14545 test: Fix pool list_verbose.py text match issue

- src/tests/perf_internal.h
- src/tests/vos_perf.c
- utils/utest.yaml
For vos_iterate test, add an option to avoid recursion. Also, run a couple of vos_perf tests in unit tests to touch test the new iterator option as well as the flat kv option.
> DAOS-13563 test: Add no-recurse option to vos_perf

- src/tests/ftest/dfuse/mu_perms.py
- src/tests/ftest/util/verify_perms.py
Test-tag: verify_perms
In _real_w, always write a line that allows the file to be executable since opening in "w" mode will truncate the file.
> DAOS-14521 test: fix very_perms.py _real_w

- src/include/daos_srv/vea.h
- src/include/daos_srv/vos.h
- src/pool/srv_target.c
- src/vea/tests/vea_ut.c
- src/vea/vea_api.c
- src/vea/vea_free.c
- src/vea/vea_internal.h
- src/vos/vos_gc.c
Given that it doesn't make sense to unmap tiny extents (much smaller than SSD erase block size), and too many parallel unmap calls could impact I/O performance, we opt to unmap only large enough extents.
This patch also removes 'force' aging flush and guarantees a free extent would never be made available for allocation unless it expires (10 seconds by default), so that following potential data corruption could be avoided:
- Server starts NVMe DMA transfer over an NVMe extent for fetch request.
- Aggregation freed the NVMe extent when coalesceing small extents.
- The freed NVMe extent is immediately made available by 'force' aging flush.
- The NVMe extent is allocated & being overwritten by others before the fetch done.
> DAOS-14263 vea: avoid unmap for tiny extents

- src/common/dav_v2/dav_v2.h
- src/common/dav_v2/tx.c
- src/common/mem.c
Fixed a race involving dav_reserve which violated the rule of “checkpointing must be done after WAL is committed”. Additionally removed the atomic copy functionality with UMEM_COMMIT_DEFER flag.
> DAOS-14510 umem: dav_reserve now commits WAL immediately

- .github/CODEOWNERS
Notify interested parties of any changes to the engine-side
telemetry library.
> DAOS-623 build: Add telem-watchers to CODEOWNERS

- src/object/srv_obj_migrate.c
It should trigger the inflight condition before waiting for the system migrate TLS to be finished, in case the migrate ULT is blocked on this condition.
> DAOS-14552 object: trigger inflight condition for sys TLS

- src/tests/ftest/telemetry/telemetry_pool_metrics.py
This PR is clean cherry-pick of the two PRs #12478 and #13122.
When the ior command is failing, it is not possible to properly test the metrics as we do not know how much data have been transferred.  When such error is occurring, the best option is to fail the test.
The `engine_pool_xferred_fetch` metric threshold is updated to manage extra networking control traffic.
Some comments are added on the limitation of the tests.
Test-Tag pragma is used to only run functional tests which could be impacted by this PR.
> DAOS-14220 test: Fix ior errors management and fetch metric threshold #12478 #13122

- src/container/container_iv.c
- src/container/srv_container.c
- src/tests/suite/daos_container.c
Fix and clean up fail_loc usage in daos_test CONTAINER tests. Also, fix
bugs revealed by the fixed tests:
- cont_iv_prop_l2g should set DAOS_CO_QUERY_PROP_SCRUB_DIS for
DAOS_PROP_CO_SCRUBBER_DISABLED.
- CONT_ACL_UPDATE should update the IV.
Test-tag: DaosCoreTest
> DAOS-14448 container: Fix fail_loc in CONTAINER tests

- src/vos/tests/vts_gc.c
- src/vos/vos_common.c
- src/vos/vos_gc.c
- src/vos/vos_internal.h
- src/vos/vos_pool.c
- src/vos/vos_space.c
* Add some metrics for garbage collection
* Add total metrics for vos space, so we can infer free space
> DAOS-14561 vos: Add garbage collection metrics

- src/control/cmd/daos_agent/main.go
- src/control/cmd/dmg/main.go
- src/control/common/proto/consts.go
- src/control/lib/control/interceptors.go
- src/control/lib/control/mocks.go
- src/control/lib/control/rpc.go
- src/control/security/grpc_authorization.go
- src/control/security/grpc_authorization_test.go
- src/control/server/interceptors.go
- src/control/server/interceptors_test.go
- src/control/server/server.go
- src/control/server/server_utils.go
The interoperability checking code relies on getting the
peer component from the peer certificate. When running
in insecure mode, the peer component information is
unavailable, and the interoperability check defaults
to the most stringent requirements.
This patch adds new component/version headers to the
grpc client request to allow the server to perform
interoperability checks without the peer certificate.
> DAOS-14332 control: Use gRPC metadata for interop (#13018)

- src/control/cmd/daos_server/start.go
- src/control/fault/code/codes.go
- src/control/server/config/server.go
- src/control/server/config/server_legacy.go
- src/control/server/ctl_storage_rpc.go
- src/control/server/ctl_storage_rpc_test.go
- src/control/server/harness.go
- src/control/server/instance_exec.go
- src/control/server/instance_storage.go
- src/control/server/instance_storage_test.go
- src/control/server/instance_superblock.go
- src/control/server/instance_superblock_test.go
- src/control/server/instance_test.go
- src/control/server/server_utils.go
- src/control/server/server_utils_test.go
- src/control/server/storage/faults.go
In the special case where the tmpfs has already been
mounted but is empty, don't skip NVMe format and
configuration. Enables the use case of running
daos_server in a container with an external tmpfs.
> DAOS-14251 control: Allow premounted empty tmpfs (#12968)

- src/cart/crt_context.c
- src/cart/crt_hg.c
Fix to return error for crt_provider_get_ctx_idx(), so we don't need
call crt_provider_put_ctx_idx() if it failed to avoid assertion in crt_finalize().
> DAOS-12961 cart: return error if crt_provider_get_ctx_idx() failed

- src/bio/bio_device.c
- src/bio/bio_xstream.c
In VMD mode with PMem SCM, hotplug add event (triggered through SPDK
rpc in engine) was not resulting in bdev being reinstated in DAOS. The
cause was a regression related to MD-on-SSD code changes where role
could not be decoded from bdev_name. In the case where SPDK is being 
initialised through daos_nvme.conf, role info is encoded into the name
whereas during hotplug scanning, the name is generic and doesn't
include the role info.
Fix by passing roles into create_bio_bdev and decode as before for
init case but use a default value for scan/hotplug case (as the
bdev_name doesn't have role info). In the latter scenario make default
role assignment consistent with operating mode (unset for PMem and
DATA for MD-on-SSD).
Also fix LED reporting by performing pci address match before checking …
> DAOS-14573 bio: Skip role assignment for hotplugged bdev

- src/container/srv_target.c
- src/include/daos_srv/container.h
- src/object/srv_ec_aggregate.c
- src/pool/srv_target.c
To make each pool child able to be stopped individually, this patch revert the original fix (#8572) and fix the use after free issue in a different way: just free the eph list after all pool child stopped.
> DAOS-9335 pool: fix use after free issue on eph query

- site_scons/site_tools/doneapi.py
- utils/docker/Dockerfile.el.8
- utils/docker/Dockerfile.el.9
- utils/docker/Dockerfile.leap.15
- utils/scripts/helpers/repo-helper-el9.sh
- utils/scripts/helpers/repo-helper-leap15.sh
- utils/scripts/install-leap15.sh
Rather than using zypper to bootstrap dnf, use an image that has dnf
built in.
Remove version from go packages on Leap 15 to ensure we are alwys using
the latest version availalble for SDL requirements.
Add targets to our EL8 and Leap 15 Dockerfiles to allow building more
basic containers that are just configured to use our Artifactory repo
server.  This can be utilized by adding "--target basic" to your docker/
podman build command.
Sync EL9 Dockerfile to EL8 and Leap15 format.
> DAOS-623 build: Use leap-dnf Docker image (#13271)

- docs/overview/transaction.md
- src/control/cmd/dmg/pretty/pool.go
- src/control/cmd/dmg/pretty/pool_test.go
dmg pool query -e: reports ranks as targets
> DAOS-14568 control: dmg pool query info change targets to ranks

- src/dtx/dtx_common.c
- src/dtx/dtx_rpc.c
The dtx_rpc_prep function uses DSS_DEEP_STACK_SZ to create dtx_rpc_helper ULTs. Since the latter function does not seem to require unusually large stack space, we can try using the default stack size here.
Similarly, the dtx_leader_exec_ops function uses DSS_DEEP_STACK_SZ to
create dtx_leader_exec_ops_ult ULTs, which does not execute the
stack-hungry, local part of func. (We assume that the compiler will not
inline the functions called by the local part of func.) Hence, we can
try using the default stack size here too.
> DAOS-14261 dtx: Remove unnecessary deep stack size

- src/tests/ftest/cart/util/cart_logtest.py
- src/tests/ftest/launch.py
Update log_test to not check for descriptor consistency when parsing
ftest logs. As ftest debug masks change on live systems these tests
aren't valid and will fail if RPCs are in flight during the change.
Signed-off-by: Ashley Pittman ashley.m.pittman@intel.com>
> DAOS-14052 test: Update cart_logtest usage in launch.py (#13005)

- src/bio/bio_device.c
- src/bio/bio_xstream.c
In VMD mode with PMem SCM, hotplug add event (triggered through SPDK
rpc in engine) was not resulting in bdev being reinstated in DAOS. The
cause was a regression related to MD-on-SSD code changes where role
could not be decoded from bdev_name. In the case where SPDK is being
initialised through daos_nvme.conf, role info is encoded into the name
whereas during hotplug scanning, the name is generic and doesn't
include the role info.
Fix by passing roles into create_bio_bdev and decode as before for
init case but use a default value for scan/hotplug case (as the
bdev_name doesn't have role info). In the latter scenario make default
role assignment consistent with operating mode (unset for PMem and
DATA for MD-on-SSD).
Also fix LED reporting by performing pci address match before checking …
> DAOS-14573 bio: Skip role assignment for hotplugged bdev (#13280)

- src/dtx/dtx_rpc.c
The dtx_cleanup() logic is used to handle the long-time non-committed DTX on non-leader. But DTX leader may switch to new target if the old leader is evicted (such as engine death). So when DTX leader switches to new leader, dtx_cleanup() needs to check such case and skip relted DTX entry.
> DAOS-14526 dtx: do not cleanup DTX with new leader on current target

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/include/daos_types.h
- src/rdb/rdb.c
- src/tests/ftest/daos_test/suite.yaml
- src/tests/ftest/util/dmg_utils_base.py
When someone wants to stop current check instance, it needs to set ins->ci_sched_exiting to notify related instance scheduler to exit.
Originally, we used "ci_sched_running" for such purpose. But it is confused to distinguish whether the scheduler has already exited or someone is stopping the instance. The others may misunderstand that related check scheduler has already exited, but the scheduler is in stopping process, as to subsequent checker restart will get failure.
> DAOS-14467 chk: properly stop check scheduler

- src/tests/ftest/util/collection_utils.py
Redo the cart_logtest fix implemented for DAOS-14052 that was broken when moving launch.py methods into separate utils.
> DAOS-14052 test: Fix broken merge.

- src/cart/utils/memcheck-cart.supp
Rocky 8.9 has brought in a new go version which is reporting
spurious leaks so add suppressions for them.
> DAOS-14680 ci: Update go suppressions.

- src/cart/utils/memcheck-cart.supp
Rocky 8.9 has brought in a new go version which is reporting
spurious leaks so add suppressions for them.
> DAOS-14680 ci: Update go suppressions. (#13402)

- site_scons/site_tools/go_builder.py
- src/vos/vos_aggregate.c
- src/vos/vos_common.c
- src/vos/vos_gc.c
- src/vos/vos_internal.h
* Switch gc gauges to counters for monitoring
as rates instead of absolute values
* Add aggregation failure counter
Also adds a small change to the Go builder for
handling versions with a -suffix.
Change-Id: I0af682bff3dcfe28a78c69d9ed1746afffe9eafa
> DAOS-14561 vos: Adjust GC metrics

- src/control/server/config/faults.go
- src/control/server/config/server.go
- src/control/server/config/server_test.go
Add a unit test for the case when the number of SSD addresses in
bdev_list is not the same across engine configs. Also correct seenIdx
initial value so error messages on validation failure don't give the
wrong engine instance ID.
> DAOS-14181 control: Add unit-test for when nr bdevs not equal in config

- src/vos/tests/pool_scrubbing_tests.c
- src/vos/vos_pool_scrub.c
This change fixes the following issue ...
When the scrubber is lazy mode and the system gets really busy, the scrubber will get wait until the system is not busy before continuing. If the user decides to change the mode to timed in this state, the is_idle check doesn't look at the mode anymore so a change to timed mode would be ignored.
Feature: scrubber
> DAOS-12433 csum: Scrubber Lazy to Timed Mode Fix

- src/dtx/dtx_common.c
- src/include/daos_srv/dtx_srv.h
- src/include/daos_srv/vos.h
- src/object/srv_obj.c
- src/tests/ftest/util/telemetry_utils.py
- src/vos/lru_array.h
- src/vos/tests/vts_ilog.c
- src/vos/vos_dtx.c
The transaction epoch maybe renewed after DTX entry allocated. Under such case, related lru entry for the DTX entry needs to be refreshed for its key. Otherwise, we cannot locate such lru entry with the new DTX epoch.
> DAOS-13129 vos: refresh lru entry key with DTX epoch renew

- src/client/dfs/dfs.c
> DAOS-14711 dfs: fix coverity 1565890

- src/tests/ftest/ior/crash.py
Cherry pick of master commit 5daa960 to release/2.4 branch.
Before this change, the final container query ci_nhandle verification (done while ior is running without crash/interruption) would pass only if timing was fortunate. The code expected to see ci_nhandles=1 but the correct expectation is in fact ci_nhandles=2 (one for the test container handle open to perform the query, and another for the ior just launched). For a long time, the test would be lucky and always observe ci_nhandles=1. More recently, ci_nhandles=2 observations are occurring, presumably due to timing differences introduced in daos.
With this change, the test is updated to expect ci_nhandles=2, and is also modified to perform multiple (5) attempts with 2 second delays between attempts, to give time for ior to start up …
> DAOS-14686 test: ior/crash.py fix race in ci_nhandles check (#13405)

- src/cart/crt_group.c
- src/gurt/misc.c
- src/include/gurt/common.h
- src/rdb/rdb_raft.c
The function
int d_rank_list_del(d_rank_list_t *rank_list, d_rank_t rank)
calls
d_rank_list_t *d_rank_list_realloc(d_rank_list_t *ptr, uint32_t size)
which may free (or reallocate) the object ptr points and return NULL (or
the address of a new object). Due to d_rank_list_del’s signature, this
can’t be conveyed to the caller, who may continue using the freed
object. A similar pitfall exists in d_rank_list_append.
This patch renames d_rank_list_realloc to d_rank_list_resize and changes
its behavior so that it never frees the d_rank_list_t object.
> DAOS-14624 gurt: Fix d_rank_list_del and friends (#13317)

- src/client/dfuse/dfuse.h
- src/client/dfuse/dfuse_core.c
- src/client/dfuse/ops/readdir.c
Remove the usee of assert for detecting unexpected kernel behaviour.
Add a lock to protect against concurrent readdir calls.
> DAOS-14716 dfuse: Add a inode lock for readdir and remove assert.

- src/vos/vos_io.c
The old logic in vos_fetch_begin() may assign io_context handle to the
output parameter too early, but some subsequent logic may destroy such
handle after that because of some failure. That can cause the returned
handle to be invalid as to related memory to be double freed.
Priority: 2
> DAOS-14714 vos: return fetch handle only when vos_fetch_begin succeed

- src/tests/ftest/dfuse/caching_check.py
- src/tests/ftest/dfuse/caching_check.yaml
Test-tag: DfuseCachingCheck
Test-repeat: 5
Increase timeout for dfuse/caching_check.py and add more logging.
> DAOS-13433 test: increase timeout for dfuse/caching_check (#13355)

- src/vos/vos_io.c
The old logic in vos_fetch_begin() may assign io_context handle to the
output parameter too early, but some subsequent logic may destroy such
handle after that because of some failure. That can cause the returned
handle to be invalid as to related memory to be double freed.
Priority: 2
> DAOS-14714 vos: return fetch handle only when vos_fetch_begin succeed - b24

- src/tests/ftest/util/osa_utils.py
Summary:
- Race condition happens when dmg_objects from different threads updates the BasicParameter object. This can cause problem.
- Avoid invoking dmg_command from the IOR thread under osa_utils.py
- Presently, ior thread is checking the pool space (which uses a dmg command object).
> DAOS-14048 test: Avoid dmg_command objects race condition. (#12750)

- src/object/srv_obj.c
- src/tests/suite/daos_container.c
Check RF and other performance before retry check, so non-allowed write should return failuer immediately, instead of retrying endless.
Use rebuild/reintegrate_pool_rank in daos_container test to avoid DER_BUSY failure.
> DAOS-14353 objects: check permission before retry

- src/container/rpc.h
- src/pool/rpc.h
Use clang-format on and clang-format off code comments to control what sections of these rpc header files get formatted.
Previous code patches for this feature have resulted in some unreadable cart RPC definition macros in the code. This change restores the readable code alignments and prevents clang-format from attempting to make the unreadable changes in the future.
> DAOS-14021 pool: undo clang-format on pool, container RPCs

- src/container/cli.c
- src/include/daos/tse.h
should register completion callback before task reinit, or the complete cb possibly cannot be triggered.
(issue reported by Zhao Zhen <zp_8483@163.com>)
> DAOS-14788 container: refine task process in pmap_refresh_cb

- utils/cq/requirements.txt
> DAOS-623 cq: Bump versions of isort and pylint.

- src/client/dfs/dfs.c
- src/include/daos/object.h
DAOS 2.2.0 and previous (OBJ_VERSION <= 8) do not support querying just the max epoch of an object. So when a 2.4.x client is talking to a 2.2.x server, avoid issuing that operation to prevent an error on stat() operations. What that means is that mtime on directory objects is not always accurate and will use the initial entry mtime in that scenario.
> DAOS-14784 dfs: do not use query_max_epoch if server is < 2.4

- src/control/cmd/daos_agent/start.go
- src/control/drpc/drpc_server.go
- src/control/drpc/drpc_server_test.go
- src/control/drpc/fault.go
- src/control/fault/code/codes.go
- utils/test_memcheck.supp
This allows for the case where multiple agents are used to allow a client connections to multiple systems. The agent log prints a NOTICE-level message to indicate the presence of other daos_agent processes on startup.
> DAOS-14707 control: Allow multiple agents simultaneously (#13465)

- src/tests/ftest/util/collection_utils.py
TO prevent xml parsing errors do not include CDATA sections of other xml files in the launch.py job.log by only logging the diff of xml file changes.
Test-tag: test_daos_pool test_daos_management test_core_files test_launch_failures
> DAOS-14591 test: Avoid including xml CDATA in the job.log (#13310)

- src/dtx/dtx_common.c
- src/include/daos_srv/dtx_srv.h
- src/include/daos_srv/vos.h
- src/object/srv_obj.c
- src/tests/ftest/util/telemetry_utils.py
- src/vos/lru_array.h
- src/vos/tests/vts_ilog.c
- src/vos/vos_dtx.c
The transaction epoch maybe renewed after DTX entry allocated. Under such case, related lru entry for the DTX entry needs to be refreshed for its key. Otherwise, we cannot locate such lru entry with the new DTX epoch.
> DAOS-13129 vos: refresh lru entry key with DTX epoch renew - b24

- src/control/server/server_utils_test.go
- src/control/server/storage/bdev/backend.go
- src/control/server/storage/bdev/backend_test.go
- src/control/server/storage/bdev/firmware.go
- src/control/server/storage/bdev/firmware_test.go
- src/control/server/storage/faults.go
Report the specific case where VMD address has no backing devices. A
bdev scan of PCI address specified in server config file bdev_list
should report an error indicating if any of the addresses are for a
VMD which has no backing storage (backing NVMe SSDs).
> DAOS-14793 control: Fail if VMD has no backing storage

- src/container/srv_container.c
- src/container/srv_target.c
- src/object/srv_ec_aggregate.c
EC aggregation shouldn't be paused even when the target is busy, otherwise, it'll result in the global EC boundary not being bumped timely, and impact VOS aggregation over all targets.
Added few warning messages when the EC boundary is't bumped timely.
> DAOS-14837 container: don't pause EC aggregation
