src/tests/ftest/avocado_tests.py, src/tests/ftest/cart/corpc/corpc_five_node.py, src/tests/ftest/cart/corpc/corpc_one_node.py, src/tests/ftest/cart/corpc/corpc_two_node.py, src/tests/ftest/cart/ctl/ctl_five_node.py, src/tests/ftest/cart/ctl/ctl_one_node.py, src/tests/ftest/cart/ghost_rank_rpc/ghost_rank_rpc_one_node.py, src/tests/ftest/cart/group_test/group_test.py, src/tests/ftest/cart/iv/iv_one_node.py, src/tests/ftest/cart/iv/iv_two_node.py, src/tests/ftest/cart/no_pmix/multictx_one_node.py, src/tests/ftest/cart/nopmix_launcher/launcher_one_node.py, src/tests/ftest/cart/rpc/multisend_one_node.py, src/tests/ftest/cart/rpc/rpc_one_node.py, src/tests/ftest/cart/rpc/rpc_two_node.py, src/tests/ftest/cart/rpc/swim_notification.py, src/tests/ftest/cart/selftest/selftest_three_node.py, src/tests/ftest/checksum/csum_basic.py, src/tests/ftest/harness/basic.py, src/tests/ftest/harness/unit.py
Test-tag: CartSelfThreeNodeTest ApricotTests CartCoRpcFiveNodeTest CartCoRpcTwoNodeTest CartGhostRankRpcOneNodeTest CartNoPmixLauncherOneNodeTest CartGroupTest CartIvOneNodeTest CartIvTwoNodeTest CartCtlFiveNodeTest CartCtlOneNodeTest CartMultisendOneNodeTest HarnessBasicTest CartRpcOneNodeTest CartRpcOneNodeSwimNotificationOnRankEvictionTest HarnessUnitTest CartIvTwoNodeTest CsumContainerValidation
Explicitly tag all VM tests with the "vm" tag.
=> DAOS-9249 test: tag vm tests with vm tag

src/tests/suite/daos_capa.c
The test was run with 2 ranks (-np 2), better to barrier before close container.
=> DAOS-13586 tests: add par_barrier before daos_cont_close

src/client/dfs/dfs_internal.c, src/client/dfs/dfs_internal.h
lock module when checking for dfs is_init.
=> DAOS-13792 dfs: fix for coverity 1443161

src/client/array/dc_array.c
=> DAOS-13791 client: free iod->iod_recxs first, then free params

src/common/ad_mem.c, src/common/dav/heap.c
1444800 - field accessed without a lock
1444804 - unused value
=> DAOS-13783 common: Address a couple of coverity issues

src/cart/utils/crt_utils.c
- Avoid context queue draining for clients. This reduces cart_ctl run by ~5 seconds.
=> DAOS-13451 cart: Don't drain queue for cart clients

src/cart/crt_hg.c, src/cart/crt_hg.h, src/cart/crt_init.c, src/include/cart/types.h
=> DAOS-13086 cart: add support for ofi tcp w/o rxm (#12436)

src/client/array/dc_array.c
=> DAOS-13791 client: free iod->iod_recxs first, then free params (#12475)

src/common/dav/alloc_class.c
Fixed a potential leak in alloc_class_new()
CID: 474927
=> DAOS-13113 common: Fixed coverity issue in dav code (#12493)

src/common/ad_mem.c, src/common/dav/heap.c
1444800 - field accessed without a lock
1444804 - unused value
=> DAOS-13783 common: Address a couple of coverity issues (#12481)

src/cart/crt_hg.c
- Fix cid 1404275 Copy into fixed size buffer
=> DAOS-13716 cart: Fix coverity issue cid 1404275 (#12459)

src/client/dfuse/dfuse_core.c
=> DAOS-13781 dfuse: Remove a pointless assignment.

src/control/lib/control/mocks.go
Added logging to the MockInvoker to make debugging easier in the event that unit tests that use it fail.
=> DAOS-13496 test: Add logging to MockInvoker

src/object/cli_obj.c, src/object/srv_enum.c, src/tests/ftest/cart/util/cart_logtest.py
=> DAOS-623 test: Check for use of DER_UNKNOWN in logs.

src/engine/init.c, src/engine/srv_internal.h, src/include/daos_srv/daos_engine.h, src/mgmt/srv_drpc.c, src/mgmt/srv_internal.h, src/mgmt/srv_target.c, src/mgmt/tests/mocks.c
Setup all modules from within the dRPC setup handler to ensure this is
performed before the ready state is set in the control-plane.
=> DAOS-13214 engine: Setup modules in DRPC SetUp handler

src/container/srv_container.c
=> DAOS-13808 container: check before dereferencing filter parts

src/bio/bio_recovery.c
Keep re-trigger reintegration when reint_reaction() returns 1.
=> DAOS-13815 bio: fix typo in on_normal()

src/control/cmd/daos/filesystem.go
Two PRs that modified the go json code crossed in CI.
=> DAOS-13471 control: Fix conflict with go build.

src/engine/srv_internal.h, src/include/daos_srv/daos_engine.h
=> DAOS-13876 engine: fix assertion with STACK_MMAP enabled

src/include/daos_task.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_task.c, src/tests/suite/daos_obj_ec.c
Before enumeration request fanout, it should check if any shard(sub) anchor still exist in the reqest targets anymore, if not, then the sub anchor should be marked as eof to make sure the enumeration can be ended.
Add test to verify the process.
=> DAOS-13412 object: Check shard anchor for enumeration

src/common/misc.c
Fix coverity issue CID: 1450478 Explicit null dereferenced
=> DAOS-13806 common: refine NULL buf case in daos_sgl_processor

src/object/cli_csum.c
Fix for coverity 1450480
Features: checksum
=> DAOS-13807 csum: Potential NULL Dereference

src/include/daos_srv/pool.h, src/object/srv_obj_migrate.c, src/pool/srv_target.c
Check discard status for reintegration.
=> DAOS-13799 object: check discard status

src/client/dfs/dfs_sys.c
=> DAOS-13710 client: Fix a return code in dfs_sys. (#12409)

src/control/cmd/daos/acl.go
If the name doesn't contain an '@', it is assumed to be a local user or group name.
=> DAOS-13645 control: Make '@' optional in owner user/group (#12404)

src/common/fault_domain.c, src/common/fault_domain.h, src/common/pool_map.c, src/common/tests/fault_domain_tests.c, src/control/server/config/faults.go, src/control/server/faultdomain.go, src/control/server/faultdomain_test.go, src/include/daos/cont_props.h, src/include/daos/object.h, src/include/daos/pool_map.h, src/object/cli_obj.c, src/object/srv_ec_aggregate.c, src/placement/jump_map.c, src/placement/jump_map.h, src/placement/jump_map_versions.c, src/placement/pl_map.h, src/placement/tests/SConscript, src/placement/tests/jump_map_dist.c, src/placement/tests/jump_map_pda.c, src/placement/tests/jump_map_place_obj.c, src/placement/tests/pl_bench.c, src/placement/tests/place_obj_common.c, src/placement/tests/place_obj_common.h, src/placement/tests/placement_test.c, src/placement/tests/ring_map_place_obj.c, src/rebuild/scan.c
Add PO_COMP_TP_GRP component type to pool map.
Add pda parameter (omd_pda) to struct daos_obj_md to generate layout.
Add pda selection and constrain to jump_map placement code.
Add unit test - "placement/tests/jump_map_pda.c".
Add a test tool to test layout distribution -
jump_pl_map -d <-n num_objs> <-l obj_class_name>
for example - ./jump_pl_map -d -n 1024 -l EC_8P2G1
to test contiguous OIDs' layout distribution on all targets.
Control-plane side change (from Kris) -
- Add support for a second layer in fault_path in config yaml.
- Update pool map parsing to understand the second layer, if it
exists, as PO_COMP_TP_GRP.
- Remove previous hacks to add group components.
- Fix the component count used as idx for group case
Signed-off-by: Xuezhao Liu …
=> DAOS-9548 placement: add PDA (performance domain affinity) support

src/client/dfs/dfs.c, src/container/cli.c, src/container/srv_target.c, src/engine/drpc_listener.c, src/engine/init.c, src/include/daos/object.h, src/mgmt/srv_drpc.c, src/object/cli_shard.c, src/pool/cli.c, src/pool/srv_pool.c, src/rdb/rdb.c, src/vos/evtree.c, src/vos/vos_tree.c
Fix log and error messages so that they contain at least one newline.
Remove some logging that's not needed.
=> DAOS-13895 cq: Fix complex log/error lines that do not contain newline

src/bio/bio_buffer.c, src/include/daos_srv/bio.h, src/vos/vos_aggregate.c
Change bio_copy_prep() to return proper error code, and fix the related error propagation issue in aggregation code.
=> DAOS-13903 bio: Change bio_copy_prep() to return error code

src/include/daos_srv/pool.h, src/object/srv_obj_migrate.c, src/pool/srv_target.c
Check discard status for reintegration.
=> DAOS-13799 object: check discard status (#12514)

src/include/daos_obj.h
Add missing cast from uint32_t to a enum daos_obj_redun.
=> DAOS-13925 object: fix conversion to daos_obj_redun

src/rebuild/scan.c, src/rebuild/srv.c
object discard from reclaim should be excluded with EC aggregation.
=> DAOS-13295 rebuild: exclude EC aggregation with discard

src/engine/srv_internal.h
=> DAOS-13876 engine: fix assertion with STACK_MMAP enabled (#12552)

src/tests/ftest/control/version.py, src/tests/ftest/control/version.yaml, src/tests/ftest/util/general_utils.py
Follow up of the PR #12570 fixing non standard coding guidelines introuce in the functional test control/version.py
=> DAOS-13886 test: Fix version functional test

src/container/srv_target.c
Remove unnecessary rc assignment in ds_cont_local_open.
=> DAOS-13737 container: remove unnecessary assignment (#12417)

src/pool/srv_pool.c
Pool reintegration discard should be done after rebuild to make sure all DOWNOUT targets being discarded before reintegration.
=> DAOS-13896 pool: reintegration discard after rebuild

Jenkinsfile, site_scons/env_modules.py
Test-tag: OSAOnlineExtend
Fix cases where an exeption was accidentally ignored/lost.
=> DAOS-13680 test: fix env_modules exception handling

src/control/lib/control/mocks.go, src/control/lib/control/system_test.go
This changeset is a backport of two other commits. Both of these commits were clean cherry-picks:
* DAOS-13496 test: Add logging to MockInvoker (#12384)
Added logging to the MockInvoker to make debugging easier in the
event that unit tests that use it fail.
Signed-off-by: Kris Jacque <kris.jacque@intel.com>
* DAOS-13496 control: Extend timeout for SystemJoin unit test (#12591) 
There were some cases where the external timeout was being hit in
CI.
Also updated the mock InvokeUnaryRPC() method to allow the response-
sending goroutine to abort during the response delay, if there is one.
Signed-off-by: Kris Jacque <kris.jacque@intel.com>
=> DAOS-13496 control: Extend timeout for SystemJoin unit test

src/client/dfuse/ops/readdir.c, src/tests/suite/dfuse_test.c
=> DAOS-13833 test: Add a test for seekdir use in readdir.

src/cart/crt_iv.c, src/engine/server_iv.c
=> DAOS-13906 engine: Check for memory allocation properly to avoid crash.

src/client/dfs/dfs.c
in case of the failure of "daos_obj_query_max_epoch(dir_oh, th, &ep, NULL);"
=> DAOS-13983 client: dir_oh instead of oh should be closed

site_scons/env_modules.py
Test-tag: OSAOnlineExtend DaosCoreTest
Dummy-Skip-func-hw-test-medium-ucx-provider: false
Test-provider: ucx+dc_x
Fix cases where an exeption was accidentally ignored/lost.
=> DAOS-13680 test: fix env_modules exception handling (#12437)

src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py, src/tests/ftest/util/test_utils_pool.py
- Add DmgCommand.pool_upgrade
- Add TestPool.upgrade
- Not yet used
=> DAOS-13984 test: add ftest utilities for dmg pool upgrade

src/include/daos_obj.h
Add missing from uint32_t to a enum daos_obj_redun.
=> DAOS-13925 object: fix conversion to daos_obj_redun (#12613)

src/object/obj_tx.c
dc_tx_convert_post() may be triggered by the callback for related (existence) condition check. It is relative rare but valid, should not assert.
=> DAOS-13540 object: handle RESTART for TX convert with condition

src/pool/srv_util.c, src/tests/suite/daos_drain_simple.c
Fix a bug of cont-open and in-flight IO failed as DER_NO_HDL during drain, by don't treat DRAIN target as failed.
Add a test case to verify it.
=> DAOS-13966 rebuild: don't treat DRAIN target as failed

src/control/common/env_utils.go, src/control/common/env_utils_test.go, src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go, src/control/server/config/server.go, src/control/server/engine/config.go, src/control/server/engine/exec.go
Azure VM is using the network driver NetVSC to manage its virtual interface connected to the Azure accelerated network. This kind of virtual interface have to be managed in a different way as standard virtual NIC. For example, these virtual interfaces are placed in the /sys/class/net/ directory instead of the /sys/devices/virtual/net one.
More details on the management of such virtual NIC could be found in the documentation on Virtual Machine Network Adapters.
The validation of the patch was manually done on the Azure small cluster used for developing the POC of DAOS on Azure and for performance benchmarking.
=> DAOS-12746 control: Support of of NetVSC Azure VM NIC (#12465)

src/tests/ftest/nvme/object.py, src/tests/ftest/nvme/object.yaml
Test-tag: NvmeObject
- Use copy of DmgCommand since it's in a thread
- fix threading error handling
- Misc cleanup
=> DAOS-13928 test: fix nvme/object.py

src/common/pool_map.c, src/placement/jump_map.c, src/placement/jump_map.h, src/placement/jump_map_versions.c, src/placement/tests/jump_map_place_obj.c, src/placement/tests/place_obj_common.c, src/placement/tests/place_obj_common.h, src/placement/tests/placement_test.c
Tracking the real used group during layout generation to make sure shards within the same group will be put to different domains if avaible.
do_target_nr is not being set for new adding domain during extend.
Add test cases and options to verify the layout if failure domain is NODE. (jump_pl_map -n).
=> DAOS-13909 placement: various fixes for layout

src/client/dfuse/ops/readdir.c, src/tests/suite/dfuse_test.c
When seeking to the start of a directory do not try in
increase the anchor.
Add a test covering this case.
=> DAOS-13833 dfuse: Fix an issue in readdir with seek to start. (#12593)

src/chk/chk_leader.c
That may cause the check leader to skip dangling pool process.
Test-tag-hw-medium: PoolListConsolidationTest
=> DAOS-13998 chk: fix typo in chk_leader_sched

src/ddb/tests/ddb_vos_tests.c
Fix for invalid pointer sign conversion
Test-tag: ddb_cmd
=> DAOS-14025 ddb: Fix build issue

src/pool/srv_pool.c
Pool reintegration discard should be done after rebuild to make sure all DOWNOUT targets being discarded before reintegration.
=> DAOS-13896 pool: reintegration discard after rebuild (#12577)

src/object/cli_obj.c
If the shard reaches to the EOF during dkey enumeration, it should choose the right target to set INGORE rank, then the shard RPC can be skipped.
=> DAOS-13931 object: choose the right target to skip

src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
All logs will now be written to DAOS_TEST_SHARED_DIR
=> DAOS-13932 test: Remove remote logging from soak

src/object/cli_obj.c
If the shard reaches to the EOF during dkey enumeration, it should choose the right target to set INGORE rank, then the shard RPC can be skipped.
=> DAOS-13931 object: choose the right target to skip (#12674)

src/tests/ftest/launch.py
This reverts commit 61723b1b62c08b2e13212a5a10af2c55e862a5a0.
=> Revert "DAOS-13964 test: use hg_info instead of fi_info (#12713)"

src/mgmt/cli_mgmt.c
=> DAOS-14047 mgmt: Fix some string copying code.

src/client/array/dc_array.c, src/client/kv/dc_kv.c
=> DAOS-14031 client: fix leak in direct calls for closing handles

src/object/cli_obj.c
Cannot close the shard in the body function of RPC task since it can be completed by another task before the shard close completes, which would  make the main calling thread exit the main function before the shard is closed. If the calling thread closes the actual object before the shard is closed, we can have memory corruption issues.
=> DAOS-12638 object: close shard in task completion callback

src/control/server/config/server.go
Log the following at INFO level so that they are visible
in production configurations:
* Auto-calculated per-engine ramdisk size
* Auto-calculated hugepage count
=> DAOS-14064 control: INFO logging for ramdisk/hugepages (#12717)

src/client/array/dc_array.c, src/client/kv/dc_kv.c
=> DAOS-14031 client: fix leak in direct calls for closing handles (#12725)

src/cart/crt_hg.c
When HG_Reset fails, zero the "rpc_priv->crp_hg_hdl" cause it cannot be freed, this patch fixes the leak.
=> DAOS-12638 cart: fix a HG handle leak when HG_Reset() fails

src/tests/ftest/server/daos_server_config.yaml
Test-tag: test_daos_server_config_basic
Test-repeat: 3
=> DAOS-14015 test: Updating the targets_str config val.

src/tests/ftest/rebuild/widely_striped.yaml
Removing some swim timeouts previously added as per recommendations to the test yaml.
List of removed env vars:
- SWIM_PROTOCOL_PERIOD_LEN=2000
- SWIM_SUSPECT_TIMEOUT=19000
- SWIM_PING_TIMEOUT=1900
Test-tag: test_rebuild_widely_striped
=> DAOS-14053 test: Removing some swim timeouts added previously (#12735)

src/tests/ftest/control/dmg_network_scan.py, src/tests/ftest/launch.py
Test-tag: pr test_dmg_network_scan_basic
- fi_info -d option does not work as expected
- We want to move to hg_info anyway
- Just replace usage of fi_info with hg_info
- Also alias ofi+verbs -> ofi+verbs;ofi_rxm
- hg_info returns ofi+verbs;ofi_rxm but ofi+verbs is still used elsewhere
=> DAOS-13964 test: use hg_info instead of fi_info (#12724)

src/tests/ftest/ior/small.yaml
=> DAOS-12725 test: Update ior_small ior timeout.

src/gurt/tests/test_gurt.c
Fix the test that was broken by the merge.
=> DAOS-14132 test: Fix d_errstr unit test

src/tests/ftest/server/daos_server_config.yaml
Changed PASS to FAIL under nr_xs_helpers_negative in daos_server_config.yaml
Test-tag: DaosServerConfigTest
=> DAOS-14111 test: adjusted expected from PASS->FAIL

src/tests/ftest/io/seg_count.py
=> DAOS-13587 test: Added weekly tags in py file

src/tests/ftest/util/fault_config_utils.py
Test-tag: pr test_snapshots test_snapshot_negativecases BasicTxTest faults soak_smoke
Only remove fault_file if it was set/created.
=> DAOS-14094 test: only remove fault_file if exists

src/object/cli_obj.c, src/object/obj_internal.h, src/object/obj_tx.c
master-commit: c2001d2c9ed7855ca8870f3c7bb66263644efeee
During TX convert, if -DER_TX_RESTART is returned, in spite of
it is caused by stale pool map or transaction conflict, the TX
convert logic needs to restart the internal transaction instead
of forwarding the failure to upper layer caller.
master-commit: 599ce429031d3576a36fe6ef80497b8e4880d15d
dc_tx_convert_post() may be triggered by the callback for related
(existence) condition check. It is relative rare but valid, should
not assert.
=> DAOS-13540 object: handle TX_RESTART during TX convert

src/pool/srv_iv.c
Avoid updating the epoch control with a stale value.
Avoid update when old epoch is equal to cached one.
=> DAOS-14118 pool: Fix a race on pool upgrade

src/tests/ftest/recovery/ddb.yaml, src/tests/ftest/recovery/ms_membership.yaml, utils/test_memcheck.supp
These tests run on VMs, in limited memory.
Features: recovery
=> DAOS-14143 test: Adjust system_ram_reserved for recovery VM tests

src/container/container_iv.c, src/container/srv_target.c, src/object/srv_obj.c
Skip prop get for container server handle.
=> DAOS-12945 container: skip prop get for container server handle

src/common/checksum.c, src/object/rpc_csum.c
Some memory tracing tools treat 0 size mallocs as errors. also malloc of size 0 is implementation defined and can return NULL under some implementations.
=> DAOS-623 csum: check for 0 size array before alloc (#12714)

src/rebuild/rebuild_internal.h, src/rebuild/srv.c, src/tests/suite/daos_rebuild_common.c
During rebuild status query, reclaim phase should be marked as complete, since these reclaim objects won't be touched anyone else.
=> DAOS-13941 rebuild: reclaim phase should be marked as complete

src/tests/ftest/util/fault_config_utils.py
Test-tag: pr test_snapshots test_snapshot_negativecases BasicTxTest faults soak_smoke
Only remove fault_file if it was set/created.
=> DAOS-14094 test: only remove fault_file if exists (#12751)

src/tests/ftest/container/per_server_fault_domain.py, src/tests/ftest/control/daos_agent_support_collect_log.py, src/tests/ftest/control/daos_server_support_collect_log.py, src/tests/ftest/control/daos_system_query.py, src/tests/ftest/daos_racer/multi.py, src/tests/ftest/daos_racer/parallel.py, src/tests/ftest/daos_racer/simple.py, src/tests/ftest/daos_vol/bigio.py, src/tests/ftest/dfuse/fio_pil4dfs_small.py, src/tests/ftest/harness/unit.py, src/tests/ftest/interoperability/diff_versions.py, src/tests/ftest/ior/hard.py, src/tests/ftest/object/fetch_bad_param.py, src/tests/ftest/object/update_bad_param.py, src/tests/ftest/pool/bad_evict.py, src/tests/ftest/pool/create_all_hw.py, src/tests/ftest/pool/create_all_hw.yaml, src/tests/ftest/pool/create_all_vm.py, src/tests/ftest/pool/create_all_vm.yaml, src/tests/ftest/pool/create_capacity.py, src/tests/ftest/pool/evict.py, src/tests/ftest/rebuild/io_conf_run.py, src/tests/ftest/security/cont_delete_acl.py, src/tests/ftest/security/cont_get_acl.py, src/tests/ftest/security/cont_overwrite_acl.py, src/tests/ftest/security/cont_update_acl.py, src/tests/ftest/security/pool_acl.py, src/tests/ftest/security/pool_groups.py, src/tests/ftest/server/replay.py, src/tests/ftest/soak/stress_2h.py
Test-tag: test_daos_system_query test_harness_unit_run_remote_no_stdout test_daos_server_support_collect_log test_daos_agent_support_collect_log test_replay_posix PerServerFaultDomainTest test_harness_unit_run_remote_failure test_update_cont_acl_no_perm test_cont_overwrite_acl_no_perm test_cont_get_acl_no_perm test_cont_delete_acl_no_perm test_rebuild_run_io_conf test_obj_fetch_bad_handle test_obj_update_bad_handle PoolBadEvictTest PoolEvictTest test_one_pool_hw test_one_pool_vm test_recycle_pools_hw test_recycle_pools_vm test_two_pools_hw test_two_pools_vm IorHardBasic DaosRacerMultiTest DaosRacerParallelTest DaosRacerSimpleTest PoolCreateCapacityTests DaosVolBigIO SecurityPoolACLTest SecurityPoolGroupsTest
Update tests to use the …
=> DAOS-10653 test: use a test's name as its unique tag

src/vos/vos_obj_cache.c
That will indicate subsequent vos_dtx_check_availability to make proper decision for related DTX visibility.
=> DAOS-12945 vos: use DAOS_INTENT_DISCARD intent for vos_obj_discard_hold

src/rdb/rdb_raft.c
This can be triggerred by out of memory conditions or fault
injection testing in the server.
=> DAOS-13400 rdb: Do not assert on failure of raft_begin_snapshot

utils/rpms/packaging/Dockerfile.mockbuild, utils/rpms/packaging/rpm_chrootbuild
* Force landing necessary as CI run stopped after build for efficiency and expediency.  Once the build is complete and verified (i.e. manually) as being successful, that validates this change.
=> SRE-1935 build: Disable bootstrap-image use

src/container/container_iv.c, src/container/srv_target.c, src/object/srv_obj.c
Skip prop get for container server handle.
=> DAOS-12945 container: skip prop get for container server handle (#12441)

src/tests/ftest/server/daos_server_config.yaml
Add a negative test case for targets: -1
=> DAOS-14015 test: Updating the targets_str config val. (#12732)

src/object/cli_obj.c, src/object/srv_obj_migrate.c, src/tests/suite/daos_upgrade.c
Upgrade needs to enumerate all groups of the object, because the dkey to group mapping might be changed.
=> DAOS-13941 object: enumerate all groups for upgrade (#12762)

utils/node_local_test.py
=> DAOS-13392 test: Fix the compression of log files.

ci/provisioning/post_provision_config_common_functions.sh
Evaluation ported from master.  The [[ ]] string evaluation of
PR-repos: needs to account for spaces in order to work correctly.
=> DAOS-14172 test: Fix for RPM-test-version: pragma

utils/rpms/packaging/Dockerfile.mockbuild, utils/rpms/packaging/rpm_chrootbuild
=> SRE-1935 build: Disable bootstrap-image use (#12831)

src/tests/ftest/recovery/pool_membership.py, src/tests/ftest/recovery/pool_membership.yaml
Test steps:
1. Create a pool and a container.
2. Write some data with IOR using SX.
3. Stop servers.
4. Remove pool directory from one of the mount points.
5. Enable checker.
6. Start checker.
7. Query the checker until expected number of inconsistencies are repaired.
8. Disable checker and start servers.
9. Wait for rebuild to finish.
10. Query the pool and verify that expected number of targets are disabled.
Add wait_for_check_complete() to refactor.
Test-tag: pool_membership
Test-repeat: 6
=> DAOS-11735 test: CR Pass 2 - Dangling rank entry test

src/tests/ftest/io/seg_count.py, src/tests/ftest/io/seg_count.yaml
Updating test to enabling CI.
Updated YAML file to increase pool size
Also included #12787.
Enabled the io/seg_count.py test to run in weekly builds.
Test-tag: test_segcount
=> DAOS-13587 test: Re-enable skipped DAOS Seg Count test (#12283)

src/container/srv_container.c
missing pool hdl put in belongs_to_user().
=> DAOS-14205 container: missing pool hdl put

src/common/ad_mem.c
CID 1347806 integer overflow
CID 1347807 storage leak
=> DAOS-14194 common: Address admem coverity issues

src/placement/jump_map_versions.c
Check spare_left in get_target().
=> DAOS-14198 placement: check spare_left

src/object/srv_obj_migrate.c
Shrink the object migrate ULT limit to 512, since putting too much ULT might saturate the single context, and causing timeout sometmes.
Use rand() to choose the enumeration target.
=> DAOS-13295 object: shrink the object migrate ULT limit (#12816)

src/object/srv_obj_migrate.c, src/pool/srv_target.c, src/rebuild/srv.c
Retry discard if iteration failed with INPROGRESS.
=> DAOS-13295 pool: retry discard for INPROGRESS failure (#12817)

src/common/ad_mem.c
CID 1347806 integer overflow
CID 1347807 storage leak
=> DAOS-14194 common: Address admem coverity issues (#12866)

src/client/dfs/dfs.c, src/client/dfs/dfs_internal.h, src/tests/suite/dfs_unit_test.c
add an async version of ostat that schedules the fetch and stat in parallel.
=> DAOS-6854 dfs: add dfs_file_ostat with async support

src/object/srv_obj.c
Bypass check for EC agg or migrate, as coh->sch_cont is NULL for server cont handle.
Test-tag: pr ec_server_restart
=> DAOS-14176 object: refine obj_capa_check

src/vos/vos_pool.c
In CI, mlock on 8 vos pool takes more than 40 seconds totally, while mlock internally will hold kernel @mmap_lock, which might block other process to do some normal memory operations like page fault.
Originally lock whole vos pool is introduced to avoid page out when RDMA to SCM, however RDMA to SCM directly is disabled for DAOS now.
To fix this issue, let's skip mlock for MD-on-SSD case now.
=> DAOS-14028 vos: skip mlock for MD-on-SSD case

src/tests/ftest/soak/harassers.py, src/tests/ftest/soak/harassers.yaml, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/stress.yaml, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
improve logging
enable harassers to run witout manual changes
=> DAOS-14191 test: Soak updates for harassers

src/tests/ftest/soak/harassers.py, src/tests/ftest/soak/harassers.yaml, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/stress.yaml, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
improve logging
enable harassers to run witout manual changes
=> DAOS-14191 test: Soak updates for harassers (#12860)

src/rebuild/rebuild_internal.h, src/rebuild/srv.c, src/tests/suite/daos_rebuild_common.c
Revert PR-12679, since it regard "reclaim" phase as rebuild/upgrade complete, though this cause a lot rebuild operation DER-BUSY failure, let's revert this PR for now.
=> DAOS-14169 rebuild: revert PR-12679 (#12881)

src/client/api/client_internal.h, src/client/api/event.c, src/client/array/dc_array.c, src/common/tse.c, src/common/tse_internal.h, src/include/daos/tse.h, src/object/cli_obj.c, src/object/cli_shard.c, src/placement/pl_map.c
Thread sanitizer reports several errors with multithreaded applications. Fix the errors on the client side.
=> DAOS-14165 client: fix thread sanitizer warnings on the client side

src/vos/vos_io.c
=> DAOS-14174 vos: add a few log info

src/gurt/misc.c, src/include/gurt/common.h
=> DAOS-13399 gurt: Do not include malloc.h in public header file.

src/tests/ftest/dfuse/daos_build.py
A recent OFI upgrade increased memory usage for this test so
tune down the number of processes to use.
Test-tag: DaosBuild
=> DAOS-14112 test: Decrease the process count on VMs for DaosBuild.

src/tests/ftest/dfuse/daos_build.py
A recent OFI upgrade increased memory usage for this test so
tune down the number of processes to use.
=> DAOS-14112 test: Decrease the process count on VMs for DaosBuild. (#12940)

src/tests/ftest/soak/harassers.yaml
The online server stop/server start harasser was wrong in the yaml
=> DAOS-14222 test: Fix harasser name in yaml

src/container/srv_target.c
Do not disable vos aggregation during rebuild, only disable EC aggregation.
Features: pr rebuild ec
=> DAOS-14208 container: do not disable vos aggregation

src/tests/ftest/soak/harassers.yaml
The online server stop/server start harasser was wrong in the yaml
=> DAOS-14222 test: Fix harasser name in yaml (#12930)

docs/dev/contributing.md, utils/githooks/README.md
Document some of the requirements for getting full use from the githooks for developers.
=> DAOS-623 doc: Add some additional Githook docs

src/tests/ftest/container/per_server_fault_domain.py, src/tests/ftest/control/daos_system_query.py, src/tests/ftest/daos_racer/multi.py, src/tests/ftest/daos_racer/parallel.py, src/tests/ftest/daos_racer/simple.py, src/tests/ftest/daos_vol/bigio.py, src/tests/ftest/dfuse/fio_pil4dfs_small.py, src/tests/ftest/harness/unit.py, src/tests/ftest/interoperability/diff_versions.py, src/tests/ftest/ior/hard.py, src/tests/ftest/object/fetch_bad_param.py, src/tests/ftest/object/update_bad_param.py, src/tests/ftest/pool/bad_evict.py, src/tests/ftest/pool/create_all_hw.py, src/tests/ftest/pool/create_all_hw.yaml, src/tests/ftest/pool/create_all_vm.py, src/tests/ftest/pool/create_all_vm.yaml, src/tests/ftest/pool/create_capacity.py, src/tests/ftest/pool/evict.py, src/tests/ftest/rebuild/io_conf_run.py, src/tests/ftest/security/cont_delete_acl.py, src/tests/ftest/security/cont_get_acl.py, src/tests/ftest/security/cont_overwrite_acl.py, src/tests/ftest/security/cont_update_acl.py, src/tests/ftest/security/pool_acl.py, src/tests/ftest/security/pool_groups.py, src/tests/ftest/server/replay.py, src/tests/ftest/soak/stress_2h.py
Update tests to use the method name as a unique tag
Test-tag: test_daos_system_query test_harness_unit_run_remote_no_stdout test_daos_server_support_collect_log test_daos_agent_support_collect_log test_replay_posix PerServerFaultDomainTest test_harness_unit_run_remote_failure test_update_cont_acl_no_perm test_cont_overwrite_acl_no_perm test_cont_get_acl_no_perm test_cont_delete_acl_no_perm test_rebuild_run_io_conf test_obj_fetch_bad_handle test_obj_update_bad_handle PoolBadEvictTest PoolEvictTest test_one_pool_hw test_one_pool_vm test_recycle_pools_hw test_recycle_pools_vm test_two_pools_hw test_two_pools_vm IorHardBasic DaosRacerMultiTest DaosRacerParallelTest DaosRacerSimpleTest PoolCreateCapacityTests DaosVolBigIO SecurityPoolACLTest SecurityPoolGroupsTest …
=> DAOS-10653 test: use a test's name as its unique tag (#12666)

src/tests/dts.c
Fix an improper assert in test code.
=> DAOS-13341 test: fix improper assert (#12818)

src/container/srv_target.c
Do not disable vos aggregation during rebuild, only disable EC aggregation.
=> DAOS-14208 container: do not disable vos aggregation (#12934)

src/container/srv_target.c, src/vos/vos_aggregate.c
* DAOS-14211 vos: fix improper assert in umark_removals()
Fix an improper assert in unmark_removals().
=> DAOS-14211 vos: fix improper assert in umark_removals() (#12910)

src/dtx/dtx_common.c, src/gurt/hlc.c, src/include/daos_srv/dtx_srv.h, src/include/gurt/common.h, src/vos/vos_dtx.c
When try to purge old non-committed DTX which age exceeds VOS aggregation time threshold, then generate some warning message. That will much reduce fake warning messages.
=> GCP-215 vos: warning message for purging old non-committed DTX

src/cart/crt_corpc.c, src/cart/crt_iv.c
crt_bulk_free() should always be called before buffer free, 
otherwise retried rma may corrupt freed memory.
=> DAOS-14224 cart: call crt_bulk_free before iv_put

src/vos/vos_common.c, src/vos/vos_dtx.c
That will avoid triggering assertion for 'prepare' status check during dtx_rec_release().
=> DAOS-14246 vos: do not reset dae_preparing until dtx_rec_release done

src/object/srv_obj_migrate.c
Do not merge parity epoch during parity rebuild, which might cause some parity mismatch issue during degraded fetch.
=> DAOS-14208 object: do not cross stripe during parity rebuild

src/tests/ftest/scrubber/csum_fault.py
Adding 'faults' tag to scrubber/csum_fault.py.
Test-tag: test_scrubber_csum_fault
=> DAOS-14301 test: Disable fault injection tests from release testing.

src/client/java/hadoop-daos/pom.xml
minimize possible vulnerabilities in dependent packages per SDL requirement.
=> DAOS-14335 client: bump hadoop-common version from 3.3.3 to 3.3.6

src/object/srv_obj_migrate.c, src/placement/jump_map.c, src/placement/pl_map_common.c, src/placement/tests/jump_map_place_obj.c, src/rebuild/scan.c, src/rebuild/srv.c, src/tests/ftest/daos_test/suite.yaml, src/tests/ftest/rebuild/basic.py, src/tests/ftest/rebuild/container_create_race.py, src/tests/ftest/rebuild/with_io.py, src/tests/ftest/util/rebuild_test_base.py, src/tests/suite/daos_rebuild_ec.c
Checking rebuilding shard by comparing the old and new layout map, similar as drain/reintegration, since non-failure shard might be moved to other targets due to co-locate and failure domain factors.
Add reclaim phase for rebuild as well.
Add test to verify it.
A few other fixes due to this.
Increase rebuild EC timeout value.
Disable rs_obj_nr and rs_rec_nr check, since
reclaim phase is added after rebuild, rs_obj_nr
and rs_rec_nr might be the objects and record
being reclaimed, rather than rebuilt.
=> DAOS-14208 rebuild: several fixes for multiple shards in the same target

src/tests/ftest/pool/svc.yaml
Due to the recent increase of SWIM suspicion timeout, increase the test timeout of pool/svc.yaml.
Test-tag: test_pool_svc
=> DAOS-14232 tests: Increase pool/svc.yaml timeout

src/tests/suite/daos_drain_simple.c, src/tests/suite/daos_extend_simple.c, src/tests/suite/daos_obj_ec.c
Do not run the DAOS_Drain_Simple test when DAOS is built without fault injection.
Test-tag: test_daos_drain_simple
=> DAOS-14302 test: Skip DAOS_Drain_Simple w/o fault injection

.rpmignore
do not ship DAOS test RPMs (add all daos*tests RPMs to .rpmignore) 
update .rpmignore to retire centos7
=> DAOS-14309 packaging: remove daos tests RPMs from distro

src/object/srv_obj_migrate.c
Since exclude/drain might change the shard location as well, so let's create the container for all casing during migration.
=> DAOS-14338 object: create migrate container in all cases

src/tests/suite/daos_drain_simple.c
Test-tag: test_daos_drain_simple
=> DAOS-14302 test: Fix skipping DAOS_Drain_Simple tests

docs/release/release_notes.md, docs/release/support_matrix.md
Update 2.4 software levels to RC1 levels
Remove 2.2 known limitations that are fixed
Remove OPX Tech Preview
Update information on MLNX_OFED levels
Doc-only: true
=> DAOS-9355 doc: update 2.4 release documentation

SConstruct, src/client/api/event.c, src/client/dfs/dfs.c, src/client/dfuse/il/int_posix.c, src/client/dfuse/il/int_read.c, src/client/dfuse/il/int_write.c, src/client/dfuse/il/ioil.h, src/common/misc.c, src/include/daos/dtx.h, src/tests/ftest/dfuse/daos_build.py
- Use an EQ in the IL for dfs read and write for better performance and support of fork mode in fio()
- add a new env variable D_IL_MAX_EQ to make the number of EQs / network contexts configurable. 64 is the default and the maximum allowed. Asking for more than that will not be an error though and the library will print a warning an set that to 64.
- in case of multiple threads, each thread will create a new EQ till the max are created, then other threads will just round robin use of the EQs that are created.
- When fork is called, the main thread eq is replaced with a new one from the child process (with at_fork child handler) to prevent sharing of any internal network context resources.
- Update the IL VM build test to use less EQs than the default to prevent OOM since the VMs are …
=> DAOS-14110 il: create and do io against an EQ in the IL

site_scons/components/__init__.py
Let mercury use libfabric pkg-config instead of hard-coded lib path
=> DAOS-14409 build: use libfabric pkgconfig files

src/client/dfs/duns.c
=> DAOS-623 build: fix build when lustre APIs are installed

src/cart/README.env, src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_srv.c, src/engine/init.c, src/engine/srv.c, src/engine/srv_internal.h, src/engine/srv_metrics.c, src/gurt/misc.c, src/gurt/telemetry.c, src/include/daos_errno.h, src/include/daos_srv/dtx_srv.h, src/include/gurt/common.h, src/include/gurt/telemetry_common.h, src/include/gurt/telemetry_producer.h, src/tests/ftest/util/telemetry_utils.py, src/utils/daos_metrics/daos_metrics.c, src/vos/lru_array.c, src/vos/lru_array.h, src/vos/tests/vts_io.c, src/vos/tests/vts_ts.c, src/vos/vos_common.c, src/vos/vos_container.c, src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_obj_cache.c, src/vos/vos_tls.h, src/vos/vos_ts.c, src/vos/vos_ts.h
Add memory metrics for DTX and VOS memory usage.
=> DAOS-12945 vos: add memory metrics

mkdocs.yml
edit mkdocs.yml for 2.4
Doc-only: true
=> DAOS-9355 doc: mkdocs for 2.4

mkdocs.yml
edit mkdocs.yml for 2.5
Doc-only: true
=> DAOS-9355 doc: mkdocs for 2.5

mkdocs.yml
edit mkdocs.yml for 2.2
Doc-only: true
=> DAOS-9355 doc: mkdocs for 2.2

src/tests/ftest/dfuse/daos_build.py
Test-tag: test_dfuse_daos_build_wt_il
=> DAOS-14391 il: reduce eq count and build jobs for vm build test

src/object/srv_obj_migrate.c
fetch epoch should be lower than stable epoch to avoid inflight data being rebuilt as well.
=> DAOS-14352 object: fetch epoch should be lower than stable epoch

SConstruct, src/client/api/event.c, src/client/dfs/dfs.c, src/client/dfuse/il/int_posix.c, src/client/dfuse/il/int_read.c, src/client/dfuse/il/int_write.c, src/client/dfuse/il/ioil.h, src/common/misc.c, src/include/daos/dtx.h, src/tests/ftest/dfuse/daos_build.py
- Use an EQ in the IL for dfs read and write for better performance and support of fork mode in fio()
- add a new env variable D_IL_MAX_EQ to make the number of EQs / network contexts configurable. 64 is the default and the maximum allowed. Asking for more than that will not be an error though and the library will print a warning an set that to 64.
- in case of multiple threads, each thread will create a new EQ till the max are created, then other threads will just round robin use of the EQs that are created.
- When fork is called, the main thread eq is replaced with a new one from the child process (with at_fork child handler) to prevent sharing of any internal network context resources.
- Update the IL VM build test to use less EQs than the default to prevent OOM since the VMs are …
=> DAOS-14110 il: create and do io against an EQ in the IL (#13007)

docs/admin/administration.md
Formally document the policy with a reference table
in the Admin Guide.
=> DAOS-11552 doc: Document Interoperability Policy

src/tests/ftest/recovery/pool_cleanup.py, src/tests/ftest/recovery/pool_cleanup.yaml, src/tests/ftest/util/dmg_utils.py
Test steps:
1. Create a pool.
2. Mangle the label in the MS (Mangle the copy of the PS metadata exists in the MS).
3. Check that the label in MS is corrupted with -fault added.
4. Check that the label in PS isn’t corrupted.
5. Stop the servers and enable the checker.
6. Set the policy to --all-interactive.
7. Start the checker and query the checker until the fault is detected.
8. Repair with option 1; Trust PS pool label.
9. Query the checker until the fault is repaired.
10. Call dmg check disable and restart the servers.
11. Wait for all ranks to join.
12. Verify that the corrupted label in MS is fixed.
Test-tag: test_corrupt_label_ms
Test-repeat: 6
=> DAOS-11741 test: CR Pass 3 - Corrupt label in MS

.github/workflows/ci2.yml, .github/workflows/landing-builds.yml, site_scons/components/__init__.py, site_scons/prereq_tools/base.py, src/bio/bio_wal.c, src/cart/crt_internal_types.h, src/client/java/daos-java/pom.xml, src/client/java/hadoop-daos/pom.xml, src/object/tests/srv_checksum_tests.c, utils/build.config, utils/docker/Dockerfile.el.8, utils/scripts/install-el8.sh
Fix a couple of newer compiler warnings on Fedora 38 and move GHA to Fedora 38 to prevent new ones.
Move developer build to ucx 1.14.1. The RPM update can be done independently or not at all. We only build the RPM to build DAOS. We use MOFED drivers when we actually use UCX at runtime.
=> DAOS-13813 ci: Move GHA build to Fedora 38 (#12516)

utils/githooks/README.md
Doc-only: true
Fix the githook config command.
=> DAOS-623 doc: fix githook config command

src/tests/ftest/util/pool_create_all_base.py, utils/ansible/ftest/vars/Rocky8.yml
Information on PMEM usage in /sys are asynchronously updated when a pool is destroyed.  This PR add a timeout to let them be updated after deleting a pool.
For debugging this PR, the ansible scripts allowing to locally deploy a functional test platform, have been updated:
* A missing dependency (i.e. mercury) has been added.
This new version of the test was successfully run multiple times with the CI:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13115/2/tests
_pylint_ and _codespell_ errors are not related to the code updated in this PR
=> DAOS-14306: Fix pool create all tests

src/cart/crt_hg_proc.c, src/cart/crt_init.c, src/cart/crt_internal.h, src/cart/crt_internal_types.h, src/cart/crt_iv.c, src/cart/crt_rpc.h, src/common/misc.c, src/engine/server_iv.c, src/include/cart/api.h, src/include/cart/iv.h, src/include/gurt/common.h, src/object/obj_rpc.c, src/pipeline/pipeline_rpc.c
If IV buffer size < 19K, let's use inline buffer for IV operation, instead of bulk to avoid extra overhead.
=> DAOS-14413 cart: Using inline buffer for IV operation

src/client/dfuse/il/int_posix.c, src/tests/ftest/dfuse/daos_build.py
Test-tag: test_dfuse_daos_build_wt_il
Test-repeat: 1
=> DAOS-14391 test: change build parameters for IL VM build test

src/client/dfuse/ops/read.c, src/client/pydaos/__init__.py
Ignore cyclic import in pydaos since it would require reworking the import structure.
=> DAOS-14482 cq: ignore cyclic import in pydaos

src/pool/srv_iv.c
Initialize pool iv key for ds_iv_invalidate, in case the pool srv handle IV invalidate before pool srv handle IV update, i.e. iv entry is not created yet.
=> DAOS-14473 pool: init pool iv key for invalidate

src/tests/ftest/control/dmg_system_cleanup.py, src/tests/ftest/dfuse/posix_stat.py, src/tests/ftest/nvme/enospace.py
Test-tag: DmgSystemCleanupTest POSIXStatTest NvmeEnospace
=> DAOS-14470 test: fix except TestFail uses

src/include/daos_srv/control.h, src/rsvc/srv.c, src/tests/ftest/server/metadata.yaml
Fix a mistake made in recent commit 443ff85 to ensure that when the DAOS_MD_CAP environment variable is present, its value is used (as long as its value is valid). The minimum rdb size check was not modified in that commit which changed the default size from 128 MiB to 1GiB. A daos_server.yml configuration with DAOS_MD_CAP=128 would not be accepted, for example. This change fixes the problem.
Also, to avoid out of space errors on pool service replica followers, in the server/metadata.yaml functional test config, change the rdb log compaction frequency (RDB_COMPACT_THRESHOLD) to be once every 64 entries, rather than the prdoduct default 256. For applications that push the metadata/rdb space to its limits, this is one tactic to reduce the amount of free space skew between the leader and …
=> DAOS-13982 rsvc: DAOS_MD_CAP fix, test set compact threshold

src/tests/ftest/rebuild/container_create_race.yaml
Test-tag: test_rebuild_container_create
=> DAOS-14475 test: fix container_create_race

Jenkinsfile
=> DAOS-14516 test: Disable coverage report from FI testing.

src/tests/ftest/recovery/pool_cleanup.py
Test Steps:
1. Create a pool.
2. Mangle the label in the PS metadata.
3. Call dmg pool get-prop TestLabel_1 label and verify that the label value is TestLabel_1-fault.
4. Stop servers and enable the checker.
5. Set checker policy to --all-interactive.
6. Start the checker and query the checker until the fault is detected.
7. Repair with option 0; Trust MS pool label.
8. Query the checker until the fault is repaired.
9. Disable the checker and restart servers.
10. Wait for all ranks to join.
11. Call dmg pool get-prop mkp1 label and verify that the original label is restored.
Test-tag: test_corrupt_label_ps
Test-repeat: 5
=> DAOS-11742 test: CR Pass 3 - Corrupt label in PS

Jenkinsfile, ci/functional/test_main.sh, ci/functional/test_main_prep_node.sh, ci/storage/test_main.sh, ci/storage/test_main_storage_prepare_node.sh, utils/githooks/find_base.sh, utils/scripts/helpers/scan_daos_maldet.sh
Validate that the hardware is ready and functional before attempting to run tests with it.
Fix the Storage Prep stage for current syntax.
Fix label for VMs with an SSD used for simulating NVMe.
=> SRE-200 Build: Validate hardware before tests

src/control/cmd/dmg/pretty/pool.go, src/control/cmd/dmg/pretty/pool_test.go, src/control/lib/control/pool.go, src/control/lib/control/pool_test.go
Improvements to dmg pool list output.
=> DAOS-7847 control: Minor wording changes for pool list

src/tests/ftest/rebuild/container_create_race.yaml
Test-tag: test_rebuild_container_create
=> DAOS-14475 test: fix container_create_race (#13147)

ci/functional/test_main.sh
Fix typo on ci/funcitional/test_main.sh.
=> SRE-200 Build: Minor typo fix

src/tests/ftest/util/dfuse_utils.py
Cleaned dfuse_utils.py code to use fusermount3
=> DAOS-13079 test: ftest to use fusermount3

src/tests/ftest/control/dmg_system_cleanup.py, src/tests/ftest/dfuse/posix_stat.py, src/tests/ftest/nvme/enospace.py
Test-tag: DmgSystemCleanupTest POSIXStatTest NvmeEnospace
=> DAOS-14470 test: fix except TestFail uses (#13125)

src/tests/ftest/container/query_attribute.py, src/tests/ftest/security/cont_acl.py, src/tests/ftest/security/cont_create_acl.py, src/tests/ftest/security/cont_delete_acl.py, src/tests/ftest/security/cont_get_acl.py, src/tests/ftest/security/cont_overwrite_acl.py, src/tests/ftest/security/cont_update_acl.py, src/tests/ftest/security/pool_acl.py, src/tests/ftest/security/pool_groups.py, src/tests/ftest/server/multiengine_persocket.py, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/cont_security_test_base.py, src/tests/ftest/util/daos_utils.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/pool_security_test_base.py, src/tests/ftest/util/test_utils_container.py, src/tests/ftest/util/test_utils_pool.py
Test-tag: DfuseMUMount DfuseMUPerms UpdateContainerACLTest DaosContainterSecurityTest CreateContainterACLTest DeleteContainerACLTest OverwriteContainerACLTest GetContainerACLTest SecurityPoolACLTest SecurityPoolGroupsTest ContainerQueryAttributeTest
- Update tests to use labels instead of UUIDs.
- Add ExecutableCommand.temp_exit_status_exception
- Add ExecutableCommand.temp_run_user
- Add TestContainer.get_acl
- Add TestContainer.get_attr
- Add TestContainer.overwrite_acl
- Add TestContainer.list_attrs
- Add TestContainer.set_owner
- Cleanup ContSecurityTestBase
- Cleanup PoolSecurityTestBase
=> DAOS-12859 test: use pool and container labels (pass 2) (#12241)

.clang-format, src/include/daos_obj.h, src/include/daos_srv/vos_types.h, src/tests/vos_perf.c, src/vos/tests/vts_aggregate.c, src/vos/vos_gc.c, src/vos/vos_ilog.h, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_iterator.c, src/vos/vos_layout.h, src/vos/vos_obj.c, src/vos/vos_query.c, src/vos/vos_tree.c
Since many use cases, particularly array and KV APIs use a single AKEY, implement an optimization for these object classes to bypass the akey tree altogether.
The interface remains the same with the exception that the akey passed to vos is ignored completely. Iteration adds a fake akey '0' so that various things built on vos_iterate (e.g. rebuild, ec aggregation), will still function the same as before.
Also removed the akey condition from vos.  This
capability is not used and can be replaced entirely using the pipeline API.
Also refactored iterator callbacks to reduce switch statements.  More work can be done here in the future.
=> DAOS-13563 vos: Implement flat dkey for array and flat KV object types

src/container/container_iv.c, src/container/srv_container.c, src/include/daos_srv/container.h, src/object/srv_obj_migrate.c
Fetch EC boundary epoch before object migration actively, since during reintegration, EC boundary may not be synced to the reintegrating target before object migration.
=> DAOS-14352 object: fetch ec boundary

src/pool/srv_target.c, src/vos/vos_aggregate.c
In the job-2023-09-27T17.13-0445b67-soak-harassers run reported on the Jira ticket, one engine (daos_logs.wolf-120/daos_server0.log.84682), for instance, generated 1,162,260 of the following message in about 14 s.
vos  ERR  src/vos/vos_aggregate.c:2555 aggregate_enter()
3b718498/e7e49455: In aggregation epr[0, 1382603772039495680]
This not only made the engine log much less useful, but also might have affected the processing of other activities. Hence, this patch changes the error message to a debug, since it doesn't really indicate an end-to-end error, and adds some backoff to each loop.
=> DAOS-14324 pool: Fix extreme discard busy looping

src/common/rsvc.c, src/gurt/misc.c, src/include/gurt/common.h, src/pool/rpc.h, src/pool/srv_pool.c, src/rsvc/srv.c
The "nominated" optimization for pool create operations in ds_rsvc has
become less effective because of certain recent timing changes. This
patch replaces the "nominated" optimization with new one that piggybacks
on the first POOL_CREATE sent to a pool service.
- Employ the unused pool_create_in.pri_op.pi_hdl to ask a PS replica
to campaign, so that no RPC protocol bump is necessary.
In theory, the absolute safety of both optimizations relies on a raft
update (to be made soon).
This patch also changes rsvc_client to begin each leader search from a
random replica, instead of a fixed one. When a lot of pool services are
created on the same set of ranks, this change distributes the pool
service leader more evenly.
=> DAOS-14443 pool: Fix pool create performance

src/tests/ftest/osa/online_drain.yaml, src/tests/ftest/osa/online_extend.yaml, src/tests/ftest/osa/online_reintegration.yaml
Test-tag: online_drain online_reintegration online_extend
=> DAOS-8100 test: Enable checksum scrubber on online OSA tests.

src/common/dav/tx.c, src/common/mem.c, src/common/tests/umem_test_bmem.c, src/include/daos/mem.h, src/vos/vos_gc.c
Fixed a race involving dav_reserve which violated the rule of “checkpointing must be done after WAL is committed”.
=> DAOS-14510 umem: dav_reserve now commits WAL immediately

src/vos/vos_pool.c
In CI, mlock on 8 vos pool takes more than 40 seconds totally, while
mlock internally will hold kernel @mmap_lock, which might block other
process to do some normal memory operations like page fault.
Originally lock whole vos pool is introduced to avoid page out when
RDMA to SCM, however RDMA to SCM directly is disabled for DAOS now.
To fix this issue, let's skip mlock for MD-on-SSD case now.
=> DAOS-14028 vos: skip mlock for MD-on-SSD case (#12849)

src/rebuild/scan.c
remove unnecessary yield in container scan cb.
=> DAOS-13295 rebuild: remove unnecessary yield in container scan cb

docs/admin/hardware.md, docs/overview/use_cases.md, requirements.txt
There are some typos in docs.
yamllint is needed in python env.
flake8 needs to be < 6.0.0 as 6.0.0 removed --diff option so breaks flake8 precommit hook.
Signed-off-by: Yinglin Sun <yinsun@tesla.com>
=> Fix some doc typos and add missing packages

utils/githooks/find_base.sh
- Need to reference $ORIGIN/$base instead of $base
- Need to redirect stderr and stdout because the parent script uses set -eu
=> DAOS-14475 cq: fix find_base issue from #13135

src/control/server/ctl_storage_rpc.go, src/include/daos_srv/rsvc.h, src/mgmt/srv_target.c, src/rsvc/srv.c, src/tests/ftest/pool/create.yaml, src/vos/vos_pool.c, utils/ansible/ftest/templates/daos-make.sh.j2
This PR is a clean cherry pick of the PR #12715
vos RDB pool was not properly deleted. spdk blobs of the RDB and RDB
WAL were closed but not deleted.
=> DAOS-13967 engine: Fix NVMe storage leakage with md-on-ssd #12715

src/control/SConscript
Argobots dependency was missing from the scons file.
=> DAOS-14562 build: Fix ddb build

src/container/container_iv.c, src/object/srv_obj_migrate.c, src/tests/suite/daos_rebuild_ec.c
During parity rebuild, it should compare with stable epoch to make sure using the right epoch to fetch from data shards.
=> DAOS-14352 object: checking fetch data epoch during parity rebuild.

src/utils/daos_hdlr.c
Test-tag: fs_copy,vm cont_clone,vm
Update daos fs copy to open source pool and
container with R only.
=> DAOS-14547 tools: fs copy only needs R for source

utils/githooks/find_base.sh, utils/githooks/pre-commit, utils/githooks/pre-commit.d/10-update-copyright, utils/githooks/pre-commit.d/20-flake.sh, utils/githooks/pre-commit.d/40-gofmt.sh, utils/githooks/pre-commit.d/40-pylint.sh
Try to use the "closest" branch as the target instead of assuming master, when "gh" is not installed.
=> DAOS-14475 cq: enhance githook target branch detection (#13135)

src/cart/README.env, src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_srv.c, src/engine/init.c, src/engine/srv.c, src/engine/srv_internal.h, src/engine/srv_metrics.c, src/gurt/misc.c, src/gurt/telemetry.c, src/include/daos_errno.h, src/include/daos_srv/dtx_srv.h, src/include/gurt/common.h, src/include/gurt/telemetry_common.h, src/include/gurt/telemetry_producer.h, src/tests/ftest/util/telemetry_utils.py, src/utils/daos_metrics/daos_metrics.c, src/vos/lru_array.c, src/vos/lru_array.h, src/vos/tests/vts_io.c, src/vos/tests/vts_ts.c, src/vos/vos_common.c, src/vos/vos_container.c, src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_obj_cache.c, src/vos/vos_tls.h, src/vos/vos_ts.c, src/vos/vos_ts.h
- Add memory metrics for DTX and VOS memory usage.
- Update error message for PARTIAL update.
- Add total memory usage track.
- Only enable it by D_MEMORY_TRACK=1
- Add memory allocation(-m) information to telemetry.
=> DAOS-13503 gurt: add memory metrics (#11956)

.github/workflows/ci2.yml, .github/workflows/create_release.yml, .github/workflows/landing-builds.yml, utils/docker/Dockerfile.leap.15, utils/docker/Dockerfile.ubuntu
Add build for Ubuntu 23.10, keep 22.04 for landings.
Update leap from 15.4 to 15.5
=> DAOS-623 build: Upgrade distro versions used in Docker.

Jenkinsfile
Also, debug for branch checkout.
=> Collect commit pragmas into the env.

src/pool/srv_target.c
Because I couldn't reproduce the hang in pool_fetch_hdls_ult_abort even
after a considerable effort both manually and through CI, I have to propose
landing these extra logging.
=> DAOS-14126 pool: Debug fetch_hdls

utils/docker/Dockerfile.el.8, utils/docker/Dockerfile.leap.15, utils/scripts/helpers/repo-helper-el8.sh, utils/scripts/helpers/repo-helper-leap15.sh, utils/scripts/install-leap15.sh
=> Revert "DAOS-623 build: Use leap-dnf Docker image"

Jenkinsfile
=> DAOS-14589 ci: Set reference build for PRs.

src/tests/ftest/container/fill_destroy_loop.py, src/tests/ftest/control/dmg_system_cleanup.py, src/tests/ftest/pool/evict.py, src/tests/ftest/rebuild/container_create_race.py, src/tests/ftest/util/container_rf_test_base.py, src/tests/ftest/util/test_utils_container.py, src/tests/ftest/util/test_utils_pool.py
Test-tag: BoundaryPoolContainerSpace DaosObjectQuery DmgSystemCleanupTest PoolServicesFaultInjection NvmeObject PoolEvictTest RbldBasic RbldCascadingFailures RbldContainerCreate RbldDeleteObjects RbldReadArrayTest EcodOfflineRebuildSingle  EcodDisabledRebuildSingle test_container_redundancy_factor_oclass_enforcement RbldContRfTest container,pr,vm pool,pr,vm
- Remove TestContainer.write_objects_wo_failon
- Update calles to use TestContainer.write_objects
- Remove fail_on from TestContainer.write_objects
- Update tests appropriately
- Remove unused TestContainer.get_prop_values
- Remove unused TestPool.get_prop_values
=> DAOS-14541 test: remove redundant write_objects_wo_failon

utils/build.config
=> DAOS-14322 build: update to libfabric 1.19.0

docs/QSG/build_from_scratch.md
=> DAOS-14634 doc: fix build_from_scratch.md python install command error

docs/overview/transaction.md
DAOS-14588 doc: transaction md description fix(#13295)
change 'tx' to 'th'
Signed-off-by: shiying yshi1210@gmail.coms
=> DAOS-14588 doc: transaction md description fix

docs/user/filesystem.md, src/client/dfuse/dfuse_main.c
=> DAOS-14494 dfuse: Better document MAP_SHARED behaviour.

src/include/gurt/common.h
=> DAOS-623 gurt: fix some compile warnings seen with icc

src/cart/crt_group.c, src/gurt/misc.c, src/include/gurt/common.h, src/rdb/rdb_raft.c
The function
int d_rank_list_del(d_rank_list_t *rank_list, d_rank_t rank)
calls
d_rank_list_t *d_rank_list_realloc(d_rank_list_t *ptr, uint32_t size)
which may free (or reallocate) the object ptr points and return NULL (or the address of a new object). Due to d_rank_list_del’s signature, this can’t be conveyed to the caller, who may continue using the freed object. A similar pitfall exists in d_rank_list_append.
This patch renames d_rank_list_realloc to d_rank_list_resize and changes its behavior so that it never frees the d_rank_list_t object.
=> DAOS-14624 gurt: Fix d_rank_list_del and friends

src/client/api/event.c, src/client/dfuse/il/int_posix.c, src/client/dfuse/pil4dfs/int_dfs.c, src/include/daos/event.h, src/tests/ftest/dfuse/bash.py
Features: dfuse pil4dfs
Also port the multiple event-queue patch from IL (https://github.com/daos-stack/daos/pull/13007) to pil4dfs. Add a test case of fio to verify the support of fork(). Child processes need to call daos_eq_lib_reset_after_fork() after fork().
=> DAOS-14346 client: add daos_eq_lib_reset_after_fork to support fork

.github/workflows/version-checks.yml, docs/QSG/build_from_scratch.md, utils/cq/requirements.txt
=> DAOS-623 cq: Upgrade yamllint package

src/container/srv_layout.h, src/include/daos_srv/rdb.h, src/pool/srv_internal.h, src/pool/srv_pool.c, src/pool/srv_target.c, src/rdb/rdb.c
As a quick fix, attempt to upgrade any RDB VOS pools too when doing so to I/O VOS pools.
This patch piggybacks an unrelated container/srv_layout.h cleanup.
=> DAOS-14109 pool: Upgrade RDB VOS pools

.github/workflows/landing-builds.yml, src/client/dfuse/dfuse.h, src/client/dfuse/dfuse_fuseops.c, src/client/dfuse/dfuse_main.c, src/client/dfuse/ops/readlink.c
=> DAOS-14636 dfuse: Enable symlink caching.

ci/docker/Dockerfile.maldet.el.8, site_scons/site_tools/doneapi.py, utils/docker/Dockerfile.el.8, utils/docker/Dockerfile.el.9, utils/docker/Dockerfile.leap.15, utils/scripts/helpers/build_url_repo.sh, utils/scripts/helpers/repo-helper-el9.sh, utils/scripts/helpers/repo-helper-leap15.sh, utils/scripts/install-leap15.sh
Rather than using zypper to bootstrap dnf, use an image that has dnf
built in.
Remove version from go packages on Leap 15 to ensure we are alwys using
the latest version availalble for SDL requirements.
Add targets to our EL8 and Leap 15 Dockerfiles to allow building more
basic containers that are just configured to use our Artifactory repo
server.  This can be utilized by adding "--target basic" to your docker/
podman build command.
Sync EL9 Dockerfile to EL8 and Leap15 format.
Fix for OneAPI compilter packaging changes
=> DAOS-623 build: Use leap-dnf Docker image (#13271) (#13311)

utils/build.config
Active message failure is due to "out of memory" error.
=> DAOS-14418 mercury: Update Mercury and DAOS to handle UCX active message failure.

src/utils/daos_hdlr.c
Test-tag: fs_copy,vm cont_clone,vm
Update daos fs copy to open source pool and container with R only.
=> DAOS-14547 tools: fs copy only needs R for source (#13231)

src/rebuild/rebuild_iv.c
=> DAOS-14640 rebuild: rpt ref leak in rebuild_iv_ent_refresh()

utils/build.config
- update build config to libfabric 1.19.0
=> DAOS-14322 build: update to libfabric 1.19.0 (#13277)

Jenkinsfile
Disable timed (daily) builds on the master branch.  This testing will be covered by a new daily-testing branch.
=> DAOS-14658 test: Disable timed builds

Jenkinsfile
Disable timed (daily) build on the md-on-ssd-testing branch. This testing will be covered by a new daily-testing branch.
=> DAOS-14658 test: Disable timed builds.

src/cart/crt_iv.c
missing iv put for inline IV update.
=> DAOS-14675 cart: missing iv put

src/client/pydaos/raw/conversion.py, src/tests/ftest/nvme/enospace.py, src/tests/ftest/nvme/enospace.yaml, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/nvme_utils.py, utils/node_local_test.py
Fix the name of the client log file to parse and ignore transient communication timeout errors.
Add a new function allowing to get the the C identifier string of a C error code.
Add statistics to check pool usage and distribution.
Fix pool space usage limits.
=> DAOS-14086 test: Fix client logs parsing (#13141)

src/gurt/tests/SConscript, src/tests/ftest/cart/utest/SConscript
Don't overwrite LINKFLAGS in src/gurt/tests and src/tests/ftest/cart/utest. This causes some linkages issues on Frontera and doesn't seem to be needed anyway.
=> DAOS-12268 build: don't overwrite LINKFLAGS (#13201)

Jenkinsfile
Fix collecting the Functional Hardware Large MD on SSD artifacts by using the correct and unique stage name.
Cleaned up the Check PR stages.  Removed the 'Used Required Git Hooks' stage as this branch does not have githooks and enabled the 'Branch name check' stage now that the branch exists.
=> DAOS-14658 test: Fix Functional Hardware Large MD on SSD stage

src/tests/ftest/pool/create_capacity.py, src/tests/ftest/pool/create_capacity.yaml, src/tests/ftest/util/storage_utils.py
First PR for finding relevant ratio of pool to create.
=> DAOS-14528 test: Fix PoolCreateCapacityTests for md-on-ssd

src/tests/ftest/daos_test/suite.yaml
now test_daos_ec_obj with 17 "wait for 30 seconds for EC aggregation", that need 510S, so the original timeout of 600 Seconds possibly hit if the system is busy. Increase to 700 S.
=> DAOS-14590 tests: increase test_daos_ec_obj timeout

src/object/srv_obj_migrate.c
It should trigger the inflight condition before waiting for the system migrate TLS to be finished, in case the migrate ULT is blocked on this condition.
=> DAOS-14552 object: trigger inflight condition for sys TLS (#13232)

src/tests/ftest/deployment/agent_failure.py, src/tests/ftest/deployment/target_failure.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.yaml, src/tests/ftest/telemetry/pool_space_metrics.yaml, src/tests/ftest/util/data_mover_utils.py, src/tests/ftest/util/ior_test_base.py, src/tests/ftest/util/ior_utils.py, src/tests/ftest/util/job_manager_utils.py, src/tests/ftest/util/mdtest_test_base.py
Test-tag: pr IorEasy,-manual IorHard,-manual MdtestEasy,-manual MdtestHard,-manual TelemetryPoolSpaceMetrics AgentFailure TargetFailure datamover ior mdtest
- Replace --bind-to and --map-by with generic args to support flexible options.
- Update mpirun np AND ppn to be compatible with more implementations
=> DAOS-14650 test: replace mpirun bind-to and map-by with args

Jenkinsfile
Adding HW Medium and Large weekly test stages that run with MD on SSD enabled.
=> DAOS-14658 test: Add MD on SSD weekly test stages

src/cart/crt_hg.c, src/cart/crt_hg.h, src/cart/crt_init.c, src/cart/crt_internal_types.h
Add CRT_POST_INIT / CRT_POST_INCR env vars
This enables tuning of multi-recv buffer sizes and number of server preposted recvs when multi-recv is not enabled.
=> DAOS-13883 cart: control request_post_init/incr through env vars

src/bio/bio_xstream.c, src/vos/tests/bio_ut.c
CID 1530973 unchecked return value
CID 1530972 unused value
=> DAOS-14713 bio: Address bio coverity issues

Jenkinsfile
To ease CI queues disable running MD on SSD functional Hardware stages by default in PRs. To enable running theses stages the submitter will need to select the appropriate build parameter or pass a matching 'Skip-func-hw-*: false' commit pragma.
Also adding large and medium verbs provider MD on SSD stages to match the daily-testing branch.
=> DAOS-14693 test: Skip MD on SSD stages by default

Jenkinsfile
The pipeline is too large. Tempoarily removing the newly added Test RPM stages to free up some space.
=> DAOS-14732 test: Temporarily remove Test RPMs stages

src/tests/ftest/pool/create_all_hw.yaml
Pool destroy taking longer and causing the test timeout. Increasing test timeout
=> DAOS-14597 test: Pool destroy taking longer

Jenkinsfile
Update the Function on Leap test stage name to refelect the distro version being tested.
=> DAOS-14744 test: Update Leap Function test stage

src/SConscript
Hotfix allowing to compile  the project [vols-daos](https://github.com/HDFGroup/vol-daos): it reinstall the tse.h header file which is needed by the vold-daos project to compile.
It is a partial revert of the PR [#11885](https://github.com/daos-stack/daos/pull/11885/files#diff-9116ad061f153255d5ab5704c51ac6039e65f4b77b5282d8f1c46b28bda2ad06).
=> DAOS-14567: Add missing dependencies for vols-daos

src/object/srv_obj_migrate.c, src/rebuild/rebuild_internal.h, src/rebuild/scan.c, src/rebuild/srv.c
Decrease sp_rebuilding until tls is really destoryed and also check mpt_fini in the begining of ds_migrate_stop().
And also add more debug information here.
=> DAOS-14691 rebuild: decrease sp_rebuilding

src/client/dfs/README.md
This documents opening of an existing file or
directory.  It also demonstrates some of the
capablity of Github documentation with Mermaid.
=> DAOS-623 doc: Add a couple of dfs_open diagrams

Jenkinsfile
Update Functional on Leap 15.4 stage to 15.5.
=> DAOS-14744 test: Update Functional on Leap version

src/tests/ftest/checksum/csum_error_logging.py, src/tests/ftest/nvme/health.py, src/tests/ftest/util/pool_create_all_base.py, src/tests/ftest/util/soak_utils.py, src/tests/ftest/vmd/fault_reintegration.py
=> DAOS-14798 test: Fix key lookups on changed dmg JSON for SmdDevices

src/tests/ftest/daos_test/suite.yaml
now test_daos_ec_obj with 17 "wait for 30 seconds for EC aggregation", that need 510S, so the original timeout of 600 Seconds possibly hit if the system is busy. Increase to 700 S.
=> DAOS-14590 tests: increase test_daos_ec_obj timeout (#13376)

src/common/dav_v2/dav_iface.c, src/common/mem.c, src/pool/srv_target.c
- Added strict tx_id checking in touch_page().
- Fixed a merge glitch in pool_child_recreate().
=> DAOS-14317 umem: add tx_id checking in touch_page()

src/bio/bio_internal.h, src/bio/bio_monitor.c, src/bio/bio_xstream.c
Fix a race which could cause 'bdh_inflights' not being decreased when stopping health monitor on engine shutdown.
=> DAOS-14748 bio: race in stopping health monitor

src/common/rsvc.c, src/gurt/misc.c, src/include/gurt/common.h, src/pool/rpc.h, src/pool/srv_pool.c, src/rsvc/srv.c
The "nominated" optimization for pool create operations in ds_rsvc has become less effective because of certain recent timing changes. This patch replaces the "nominated" optimization with new one that piggybacks on the first POOL_CREATE sent to a pool service.
- Employ the unused pool_create_in.pri_op.pi_hdl to ask a PS replica to campaign, so that no RPC protocol bump is necessary.
In theory, the absolute safety of both optimizations relies on a raft update (to be made soon).
This patch also changes rsvc_client to begin each leader search from a random replica, instead of a fixed one. When a lot of pool services are created on the same set of ranks, this change distributes the pool service leader more evenly.
=> DAOS-14443 pool: Fix pool create performance (#13003)

ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_common.sh, ci/provisioning/post_provision_config_nodes_EL_8.sh
First test run of this PR confirmed UCX functionality. A few of the known issues with UCX occurred, but the fix is shown to resolve the control plane scan failure to enable UCX. 
Skip-build-el8-gcc: true
Test-provider: ucx+dc_x
=> DAOS-14746 test: Fix provisioning of MOFED in CI.

ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_common.sh, ci/provisioning/post_provision_config_nodes_EL_8.sh
=> DAOS-14746 test: Update CI provision scripts to correctly install MOFED.

Jenkinsfile, src/tests/ftest/util/network_utils.py
Support running functional UCX tests with either ucx+dc_x or ucx+ud_x and default to using ucx+ud_x.
Skip-func-hw-test-medium-md-on-ssd: true
Skip-func-hw-test-large-md-on-ssd: true
=> DAOS-14480 test: Extend Python code to support UCX with ud_x

Jenkinsfile
Default running with the 'ucx+ud_x' provider.
=> DAOS-14480 test: Run UCX testing with ud_x

src/vos/ilog.c, src/vos/ilog.h, src/vos/tests/vts_ilog.c, src/vos/vos_dtx.c, src/vos/vos_ilog.c, src/vos/vos_obj_index.c
The ilog_tree_modify() logic should not return -DER_TX_RESTART when
hit existing ilog entry for the modification with fixed epoch, such
as rebuild, ec_agg, ec_rep and so on. Because related modification
must either has been committed or is committable under such cases.
Please note that rebuild may split modifications belong to the same
transaction into multiple vos operations. So the modifications with
the same fixed epoch should be regarded as the same transaction and
need to be further handled with minor epoch.
=> DAOS-14845 vos: avoid TX_RESTART for modification with fixed epoch

src/cart/crt_rpc.c
- Fix macro to generate case statement correctly
=> DAOS-14966 cart: Fix incorrect opc logging

src/pool/srv_internal.h
Only allow UPIN engine as PS replicas to avoid IV leader switch hashles during rebuild for the moment.
=> DAOS-14972 pool: Only allow UPIN engine as PS replicas

src/rebuild/scan.c
Do not need wait for EC aggregation for reclaim operation, which does not involve fetch and update.
=> DAOS-14845 rebuild: do not wait for EC agg for reclaim

src/tests/ftest/erasurecode/online_rebuild_single.yaml
Use rd_fac:2 in online_rebuild_single
Test-tags: test_ec_online_rebuild_single
=> DAOS-14965 tests: using correct rd_fac in online_rebuild_single

docs/release/release_notes.md, docs/release/support_matrix.md, mkdocs.yml
update release notes and support matrix for daos-2.4.1
Doc-only: true
=> DAOS-9355 doc: release docs for daos-2.4.1

src/utils/SConscript
It should be part of server build, not tests
=> DAOS-623 build: daos_metrics is in server rpm

src/tests/ftest/nvme/fragmentation.py, src/tests/ftest/nvme/pool_capacity.py, src/tests/ftest/nvme/pool_exclude.py, src/tests/ftest/nvme/pool_extend.py, src/tests/ftest/osa/offline_drain.py, src/tests/ftest/osa/offline_reintegration.py, src/tests/ftest/osa/online_drain.py, src/tests/ftest/osa/online_extend.py, src/tests/ftest/osa/online_parallel_test.py, src/tests/ftest/osa/online_reintegration.py, src/tests/ftest/util/write_host_file.py
Test-tag: cart,vm SegCount NvmeFragmentation NvmePoolCapacity NvmePoolExclude NvmePoolExtend OSAOfflineDrain OSAOfflineReintegration OSAOnlineDrain OSAOnlineExtend OSAOnlineParallelTest OSAOnlineReintegration datamover pr,vm
- Do not log a DEBUG line for each host because it's too verbose
- Make slots None by default. It's infrequently used
- Use mkstemp instead of random, which is racy
=> DAOS-14735 test: simplify write_hostfile (#13464)

src/tests/ftest/deployment/agent_failure.py, src/tests/ftest/deployment/target_failure.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.yaml, src/tests/ftest/telemetry/pool_space_metrics.yaml, src/tests/ftest/util/data_mover_utils.py, src/tests/ftest/util/ior_test_base.py, src/tests/ftest/util/ior_utils.py, src/tests/ftest/util/job_manager_utils.py, src/tests/ftest/util/mdtest_test_base.py
Test-tag: pr IorEasy,-manual IorHard,-manual MdtestEasy,-manual MdtestHard,-manual TelemetryPoolSpaceMetrics AgentFailure TargetFailure datamover ior mdtest
- Replace --bind-to and --map-by with generic args to support flexible options.
- Update mpirun np AND ppn to be compatible with more implementations
=> DAOS-14650 test: replace mpirun bind-to and map-by with args (#13392)

src/tests/ftest/util/server_utils_base.py
Test-tag: pr DfuseMUPerms
Harden the regex for DAOS I/O Engine started so it doesn't match on "not started"
=> DAOS-15047 test: harden regex for engine started

src/tests/ftest/container/fill_destroy_loop.py, src/tests/ftest/control/dmg_system_cleanup.py, src/tests/ftest/pool/evict.py, src/tests/ftest/rebuild/container_create_race.py, src/tests/ftest/util/container_rf_test_base.py, src/tests/ftest/util/test_utils_container.py, src/tests/ftest/util/test_utils_pool.py
Test-tag: BoundaryPoolContainerSpace DaosObjectQuery DmgSystemCleanupTest PoolServicesFaultInjection NvmeObject PoolEvictTest RbldBasic RbldCascadingFailures RbldContainerCreate RbldDeleteObjects RbldReadArrayTest EcodOfflineRebuildSingle  EcodDisabledRebuildSingle test_container_redundancy_factor_oclass_enforcement RbldContRfTest container,pr,vm pool,pr,vm
- Remove TestContainer.write_objects_wo_failon
- Update calles to use TestContainer.write_objects
- Remove fail_on from TestContainer.write_objects
- Update tests appropriately
- Remove unused TestContainer.get_prop_values
- Remove unused TestPool.get_prop_values
=> DAOS-14541 test: remove redundant write_objects_wo_failon (#13218)

src/client/dfuse/il/int_read.c, src/client/dfuse/il/int_write.c
Rather than sending one entry at a time, we create a d_iov_t for the whole write. This shows about a 13x performance increase for checkpointing in maxtext AI application.
=> DAOS-15037 client: Pass vectorized write to dfs (#13628)

src/client/dfs/dfs.c
- memcpy is more efficient to avoid scanning the entire kds string.
- remove an assert and replace with error when looking up "."
=> DAOS-15069 dfs: use memcpy instead of snprintf for readdir (#13654)

src/tests/ftest/util/soak_utils.py
Update the dmg led identify syntax
=> DAOS 15082 test: Update VMD led identify harasser

src/tests/ftest/util/server_utils_base.py
Test-tag: pr DfuseMUPerms
Harden the regex for DAOS I/O Engine started so it doesn't match on "not started"
=> DAOS-15047 test: harden regex for engine started (#13636)

src/tests/ftest/performance/ior_easy.py, src/tests/ftest/performance/mdtest_easy.py, src/tests/ftest/rebuild/widely_striped.py, src/tests/ftest/util/mdtest_test_base.py, src/tests/ftest/util/performance_test_base.py
Test-tag: performance,-manual mdtest LargeFileCount SmallFileCount
Don't run ior and mdtest in a subprocess since it isn't needed. The variants that needed this aren't ran and need to be reworked in a new context.
Also remove support for multipler iterations since it was never used.
=> DAOS-14103 test: remove performance_test_base subprocess (#13601)

utils/node_local_test.py
When NLT is compressing log-files it tries to wait for child proccess to exit, however the logic for this was incorrect so it was not blocking for children or reaping the processes.
Normally this does not matter as the last log file to be processed in the server log which is quite large and is correctly waited for but a recent change to reduce the server log size means that the previous log-file to be compressed is still running when NLT exits and this causes problem with the archiving as the .log file disappears after the .bz2 file is complete.
This is causing Fault Injection test errors in Jenkins.
=> DAOS-623 test: Properly wait for log compression in NLT. (#13726)

src/bio/bio_xstream.c
Always call bio_release_bdev() on init thread.
=> DAOS-15122 bio: release bdev on init thread

ci/docker_nlt.sh, src/object/cli_obj.c, src/tests/suite/daos_obj.c
Posix might provide sgl with iov of (base NULL, len 0) for readv/writev, refine obj_sgls_dup to process that case.
=> DAOS-15089 object: refine sgl pre-process

.github/CODEOWNERS, .github/pull_request_template.md
Added a few teams for different areas of the code.
Change-Id: I929ef48d1bf7380784bf1ba694bf0f5131b85306
=> DAOS-623 ci: Use owners teams for CODEOWNERS (#13721)

src/client/dfuse/pil4dfs/int_dfs.c, src/tests/ftest/util/run_utils.py, src/tests/suite/dfuse_test.c
ftello() checks the offset anyway. errno could be misleading when rewind() succeeds.
=> DAOS-15121 test: do not check errno after rewind()

.github/CODEOWNERS
Doc-only: true
Change-Id: I0bd9ed4592ec052f20362094843dc6f6b55715c4
=> DAOS-623 ci: Add bio and vea to vos CODEOWNERS

src/tests/ftest/util/soak_utils.py
Update the dmg led identify syntax
=> DAOS 15082 test: Update vmd harasser (#13696)

docs/admin/administration.md
Provide details of different logging parameters that can be adjusted
with dmg server set-logmasks and describe reset behaviour.
Doc-only: true
=> DAOS-15104 docs: Improve set-logmasks documentation in admin guide

SConstruct, site_scons/components/__init__.py, src/client/dfuse/SConscript, utils/build.config, utils/scripts/install-el8.sh, utils/scripts/install-el9.sh, utils/scripts/install-leap15.sh, utils/scripts/install-ubuntu.sh
Also add developer build.  This needs some work on the libfuse RPM side.  But it should remove any
runtime dependence on the installed libfuse version.
Change-Id: I976f135af29d4e3da61cad9129ee19cbb419cddb
=> DAOS-15136 build: Add ability to use static libfuse

utils/cq/requirements.txt
=> DAOS-15149 cq: update yamllint to 1.34.0

debian/changelog, utils/rpms/daos.spec
Because EPEL now has isa-l need to rename from libisa-l
=> DAOS-15203 packaging: Updated name of dependency

src/control/cmd/daos/filesystem.go
Features: daos_fs_copy
Use errors.Errorf instead of errors.New(fmt.Sprintf
=> DAOS-10942 utils: use errors.Errorf in go

SConstruct, site_scons/prereq_tools/base.py, src/client/dfuse/SConscript
Move the scons code to a common place and add dl library.
=> DAOS-15136 build: Refine static libfuse building.

src/tests/ftest/soak/harassers.yaml
The file oclass was using GX and should be using G1
=> DAOS-15200 test: Fix typo in soak harasser yaml

src/tests/suite/daos_rebuild.c
Do not kill PS leader repeatly inside the test,
which might cause issues in rebuild wait.
=> DAOS-15165 tests: do not kill ps leader repeatly

src/tests/ftest/soak/harassers.yaml, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/stress.yaml, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
=> DAOS-14505 test: enable scrubber in soak

.github/workflows/ci2.yml, .github/workflows/clang-format.yml, .github/workflows/create_release.yml, .github/workflows/doxygen.yml, .github/workflows/flake.yml, .github/workflows/landing-builds.yml, .github/workflows/linting.yml, .github/workflows/pr-metadata.yml, .github/workflows/pylint.yml, .github/workflows/rpm-build-and-test.yml, .github/workflows/spelling.yml, .github/workflows/version-checks.yml, .github/workflows/yaml.yml
To account for Node.js 16 deprecation.
=> DAOS-15111 cq: update GHA versions

src/client/dfs/duns.c, src/tests/ftest/datamover/dst_create.py, src/tests/ftest/datamover/dst_create.yaml, src/utils/daos_hdlr.c, utils/node_local_test.py
Features: dfs dfuse DmvrDstCreate
duns_resolve_path should allow a '-' in labels.
Add a test case for datamover tools.
=> DAOS-15107 tools: add dash to duns_resolve_path regex

src/tests/ftest/control/daos_system_query.yaml, utils/githooks/find_base.sh
Workaround for test failing on some CI VMs with virtual NVMe drives.
Also fix TARGET: unbound variable in githooks.
Test-tag: test_daos_system_query
=> DAOS-15202 test: Avoid using virtual NVMe in VM test

utils/cq/requirements.txt
=> DAOS-15225 cq: update yamllint to 1.35.0

src/cart/crt_hg.c, src/cart/crt_hg.h
=> Revert "DAOS-15044: Refactor error codes"

utils/cq/requirements.txt
=> DAOS-15225 cq: update yamllint to 1.35.1

src/container/container_iv.c
Increase capa ULT stack sizeto avoid stack overflow.
=> DAOS-15085 container: increase capa ULT stack size

src/tests/ftest/util/soak_utils.py
scrub-freq was updated to scrub_freq in DAOS-7674
=> DAOS-15246 test: Update scrub_freq

src/tests/ftest/telemetry/dkey_akey_enum_punch.py
Test-tag: pool_tgt_dkey_akey_punch
=> DAOS-14904 test: use correct metric to very akey/dkey punch

src/tests/ftest/soak/stress.yaml
=> DAOS-14456 test: soak - Increase lammps job timeout

src/client/dfs/cont.c
If the dfs_cont_set_owner() function fails because of a non existing uid/gid, we don't want the daos ACL to change in this case because an error is returned to the user.
=> DAOS-15063 dfs: move the set owner after the uid/gid checks

src/tests/ftest/util/soak_utils.py
=> DAOS-15264 test: pool create fails if no properties specified

src/client/dfs/cont.c, src/client/dfs/dfs_internal.h, src/client/dfs/dir.c, src/client/dfs/file.c, src/client/dfs/io.c, src/client/dfs/lookup.c, src/client/dfs/mnt.c, src/client/dfs/obj.c, src/client/dfs/pipeline.c, src/client/dfs/readdir.c, src/client/dfs/rename.c, src/client/dfs/xattr.c
=> DAOS-623 dfs: update copyright of dfs files after breaking up dfs.c

debian/changelog, debian/control, src/gurt/misc.c, src/include/gurt/common.h, src/rdb/rdb_internal.h, src/rdb/rdb_module.c, src/rdb/rdb_raft.c, utils/rpms/daos.spec
Update raft to adopt get_rand and log levels.
=> DAOS-15120 rdb: Update raft

src/client/dfuse/pil4dfs/hook.c, src/client/dfuse/pil4dfs/hook_int.h
Fix coverity issue, CID 1584041
=> DAOS-15333 client: use dynamic memory allocation for module_name

docs/QSG/build_from_scratch.md
Modified Build from scratch file under QSG folder.
- added sudo
- added python3 -m pip --no-cache-dir install --upgrade pip under python packages section
- added '-j' option to speed up scons build
=> DAOS-12701 doc: Modify Build from scratch file under QSG

src/tests/ftest/cart/util/cart_logtest.py, utils/cq/daos_pylint.py, utils/cq/requirements.txt, utils/node_local_test.py
=> DAOS-15286 cq: update pylint to 3.1.0

src/bio/bio_device.c, src/pool/srv_target.c
1.  set @bb_trigger_reint to trigger pool child startup and reintegration.
2.  reset pool header before recreating pool for PMDK case.
=>  DAOS-15154 bio: fix to start child pool if replacing same device

utils/rpms/packaging/get_release_branch
Do not set -x in get_release_branch because it is too verbose for the githooks.
=> DAOS-623 cq: quiet githook output

src/tests/daos_racer.c
in racer parallel test, ever hit sgl->sg_iovs pointer as "0x9a0", looks like stack overflow. So reduce the stack size for sgl_bufs (40KB) in update_or_fetch().
Test-tag: daos_racer
=> DAOS-15276 tests: reduce stack usage of daos racer

.gitignore, Jenkinsfile
… Not the env namespace.
Although referencing them in the env namespace seems to sometimes work,
sometimes it seems not to.
Fix some linting issues.
=> DAOS-623 ci: Parameters are in the params namespace

src/placement/tests/jump_map_pda.c, src/placement/tests/placement_test.c
CID: 1529947 Unchecked return value
CID: 1529951 Missing break in switch
=> DAOS-15292 placement: fix coverity warning

src/tests/ftest/server/metadata.py
Test-tag: ObjectMetadata
Fix pylint issue introduced by #19456 and #13883
=> DAOS-14023 test: fix pylint issue

src/bio/bio_config.c
vmd_addr is leaked, free before exiting traddr_to_vmd
File: /src/bio/bio_config.c
Line: 210
git commit: f34040a1eab
=> DAOS-15315 bio: Fix CID-1958030 Resource leak

src/control/server/storage/config.go
The maximum number of bdev tiers allowed with MD-on-SSD is 3. Update
some comments that indicate otherwise and prevent assigning roles in
config generate mode when there are more than 3.
=> DAOS-15415 control: Enforce no more than 3 bdev tiers in MD-on-SSD

src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/procmon.go, src/control/cmd/daos_agent/start.go, src/control/lib/control/system.go, src/control/security/auth/auth_sys.go, src/control/security/grpc_authorization.go, src/control/security/grpc_authorization_test.go, src/control/server/mgmt_system.go, utils/config/daos_agent.yml
In the agent there is a process monitoring feature (procmon.go) that
tracks application connections (pool handles). It calls PoolEvict for
the handles that an application has created when the application
process no longer exists. It has been perceived that there is a gap
where dangling handles could be left in the case of a host crash where
the agent exit handlers are not able to execute and revoke relevant
application-created pool handles as expected. To address this gap this
change adds a routine to call SystemCleanup(<machine_name>) on agent
start-up which will revoke any pool handles associated with the host
the agent is running on.
=> DAOS-13881 control: Clean associated handles on agent start

src/control/server/config/server_test.go, utils/config/examples/daos_server_mdonssd.yml
Ensure example MD-on-SSD config file is up-to-date and valid by adding
a unit test to verify parsing the file results in a valid config.
=> DAOS-14630 doc: Improve MD-on-SSD example config and validate with test

src/client/dfuse/il/int_posix.c
Seeking to SEEK_END is not impolemented in libioil. It causes interception to be disabled with some python framework.
=> DAOS-15412 ioil: add support for SEEK_END

src/client/dfuse/pil4dfs/int_dfs.c
Add macro for PAGE_SIZE if it is not defined on arm64.
=> DAOS-15432 client: fix compiling issue on arm64

src/tests/ftest/util/server_utils_params.py
Functional tests will now use the default crt_timeout value defined by the server.
=> DAOS-15424 test: Remove default test crt_timeout value

pyproject.toml, utils/githooks/pre-commit.d/40-codespell.sh
=> DAOS-15251 cq: add codespell githook

docs/release/release_notes.md, docs/release/support_matrix.md
=> DAOS-9355 doc: relnotes for daos-2.4.2

src/tests/ftest/soak/harassers.yaml
Include rebuild TO updates for 2.4.   These updates were included in DAOS-14505/PR-13800 on master but that PR included changes that should not land on 2.4 so a separate PR for 2.4 was needed.
=> DAOS-15397 test: Rebuild TO updates are needed on 2.4

src/rdb/rdb_internal.h, src/rdb/rdb_raft.c
Before this change, the rdb / PS leader avoids appending a raft entry for the metadata operation if free space in rdb falls below 512KiB. With this change, the threshold is increased to 4MiB to (further) prevent the potential for follower replicas to encounter out of space. This helps to avoid potential PS instability.
Another minor change is made to error logging when processing raft reply messages, to make it easier to know the engine rank that handled the RPC (and sent the reply).
Test-tag: pr test_metadata_fillup test_metadata_addremove test_metadata_server_restart
=> DAOS-13982 rdb: increase noappend bytes in test for nospace (#13866)

utils/githooks/commit-msg, utils/githooks/commit-msg.d/10-watermark.py, utils/githooks/hook_base.sh, utils/githooks/pre-commit, utils/githooks/prepare-commit-msg
*Allow one to set DAOS_SKIP=exp1,exp2 to skip
git hooks on a case by case basis as needed.
*Unify the scripts in one file
=> DAOS-623 ci: Modify githooks to allow skip (#13885)

src/client/dfuse/pil4dfs/int_dfs.c, src/tests/suite/dfuse_test.c
=> DAOS-15423 client: intercept readv & writev in pil4dfs

.github/workflows/unit-testing.yml
=> SRE-2105 cq: Add permissions metatdata for GHA files.

src/tests/ftest/daos_test/dfuse.py, src/tests/suite/dfuse_test.c
=> Resolve issues with the seekdir test.

src/tests/ftest/ior/crash.py, src/tests/ftest/util/container_rf_test_base.py, src/tests/ftest/util/rebuild_test_base.py, src/tests/ftest/util/test_utils_container.py
Test-tag: IorCrash test_container_redundancy_factor_oclass_enforcement RbldContRfTest RbldCascadingFailures RbldDeleteObjects RbldReadArrayTest
- Replace TestContainer.check_container_info with verify_query
- More generic and uses daos instead of API
- Update callers appropriately
- Remove now unused TestContainer.get_info()
- Remove now unused TestContainer.info
- Just the same as TestContainer.container.info anyway
=> DAOS-14542 test: replace check_container_info with verify_query (#13219)

Jenkinsfile
Use vm instead of -hw to distinguish VM tests.
=> SRE-1975 cq: replace -hw with vm

src/tests/ftest/slurm_setup.py, src/tests/ftest/soak/stress.py, src/tests/ftest/soak/stress.yaml, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
=> DAOS-14702 test: Updates to soak for aurora (#13418)

.github/workflows/linting.yml, src/tests/ftest/aggregation/checksum.py, src/tests/ftest/daos_test/dfs.py, src/tests/ftest/datamover/posix_preserve_props.py, src/tests/ftest/erasurecode/ior_smoke.py, src/tests/ftest/erasurecode/mdtest_smoke.py, src/tests/ftest/erasurecode/online_rebuild.py, src/tests/ftest/erasurecode/online_rebuild_mdtest.py, src/tests/ftest/network/cart_self_test.py, src/tests/ftest/nvme/object.py, src/tests/ftest/pool/info.py, src/tests/ftest/rebuild/pool_destroy_race.py, src/tests/ftest/scrubber/basic.py, src/tests/ftest/security/cont_overwrite_acl.py, src/tests/ftest/tags.py, utils/cq/words.dict, utils/rpms/daos.spec, utils/utest.yaml
Features: NvmeObject EcodOnlineRebuild InfoTests OverwriteContainerACLTest OverwriteContainerACLTest
- Add ftest/tags.py utility
- lint option for linting tags
- list option to list tags associated with files
- dump option to dump test and tag info for files
- Add infrastructure that can be extended for future tag work
=> DAOS-12950 test: add ftest tag linter (#13642)

utils/cq/requirements.txt
=> DAOS-15225 cq: update yamllint to 1.35.1 (#13821)

utils/build.config
=> DAOS-15433 build: update to libfabric 1.19.1

src/bio/bio_internal.h, src/bio/bio_monitor.c, src/bio/bio_xstream.c
Fix a race which could cause 'bdh_inflights' not being decreased when stopping health monitor on engine shutdown.
=> DAOS-14748 bio: race in stopping health monitor (#13500)

src/control/lib/daos/pool_cont_prop.go
Add missing comment for exported go function.
Doc-only: True
=> DAOS-7674 pool: add comment to exported go function

docs/user/filesystem.md
=> DAOS-15509 dfs: update POSIX compliance documentation (#14060)

src/cart/utils/memcheck-cart.supp
=> DAOS-15548 test: add new valgrind suppression for daos tool

Jenkinsfile
Limit running daily release/2.4 builds to once per week.
Skip-nlt: true
=> DAOS-15533 test: Reduce release/2.4 timed build frequency

docs/admin/ucx.md
=> DAOS-15552 doc: update UCX rpm documentation

utils/build.config
add mercury patch to fix dlclose issue
add mercury patch to remove excessive warning
=> DAOS-15470 build: add mercury patch to fix ucx info query

docs/user/filesystem.md, src/client/dfuse/pil4dfs/int_dfs.c, src/tests/ftest/daos_test/dfuse.py, src/tests/suite/dfuse_test.c, utils/node_local_test.py
Document how to run pil4dfs without dfuse.
Change environment variables to use the D_IL_ prefix to be consistent with other environment variables.
=> DAOS-14344 pil4dfs: document and change env variables

Jenkinsfile
Disable running timed builds on the weekly-2.4-testing branch.
=> DAOS-15533: Disable timed release/2.4 builds

docs/admin/ucx.md
=> DAOS-15552 doc: update UCX rpm documentation (#14083)

src/mgmt/srv_query.c
CID: 1984828 Uninitialized scalar variable.
File: /src/mgmt/srv_query.c
Line: 135
=> DAOS-15560 mgmt: fix coverity error

docs/QSG/build_from_scratch.md, src/tests/ftest/dfuse/daos_build.py
Test-tag: DaosBuild
Update dfuse/daos_build.py to use requirements.build.txt.
=> DAOS-15611 test: fix dfuse/daos_build.py requirements

Jenkinsfile
Warnings-ng 11.2.2 removed the ignoreFailedBuilds parameter from the recordIssues Step.
* Still waiting for final hardware testing stages, but the PR has tested along far enough to prove the fix
=> SRE-2145 Warnings-ng 11.2.2 modified API (#14111)

src/common/btree.c, src/vos/vos_tree.c
Coverity reports `old_key.ivo_len` as a `TAINTED_SCALAR`. Adding a size check to `ktr_hkey_gen`.
Run-GHA: true
=> DAOS-15322 common: fix untrusted loop bound

Jenkinsfile
The ignoreFailedBuilds parameter was removed in reaction to the warnings-ng plug api change. Adding the requiredResult parameter to the discoverGitReferenceBuild call should create the same behavior.
=> SRE-2145 ci: Add requiredResult

src/tests/suite/daos_pool.c
Adjust daos_test -p, pool_op_retry() fault injection before dmg operations to specify fail always (until explicitly cleared), rather than fail once with implicit clear.
The change is needed because dmg / control plane can "fan out" gRPC requests to multiple MS daos_server instances, and may (intermittently) initiate retries when one returns ErrNotLeader and the other returns an error(e.g., -DER_MISC in this case). Before this change, dmg retry would result in rc=0 surfaced to daos_test (contrary to the expected -DER_MISC). With this change, the dmg retry (that is actually a distinct operation from the engine standpoint) will also have the fault injected in the engine handler, surfacing the intended -DER_MISC result to the dmg caller (daos_test).
Test-tag: test_daos_pool …
=> DAOS-15522 test: daos_test fi always for potential dmg retry

src/tests/ftest/rebuild/mdtest.py, src/tests/ftest/rebuild/mdtest.yaml, src/tests/ftest/util/mdtest_test_base.py, src/tests/ftest/util/osa_utils.py
Test-tag: RebuildMdtest
Add test to verify rebuild with 1 million files of size 1M.
Steps:
- Create pool / container
- Create 1 million EC_2P1GX files of size 1M
- Start reading the files
- Stop 1 rank during read
- Verify rebuild completes within some threshold
- Verify mdtest completes successfully
=> DAOS-15197 test: rebuild with 1 million files

src/tests/ftest/soak/stress.yaml
=> DAOS-15629 test: Remove 16 ppn from soak datamover

src/tests/ftest/util/server_utils.py
To help understand how related memory is used.
Test-tag: EcodOnlineMultFail NvmeFault EcodDisabledRebuild
=> DAOS-15615 tests: collect memory usage after server stop

src/tests/ftest/container/per_server_fault_domain.yaml, src/tests/ftest/erasurecode/cell_size_property.yaml, src/tests/ftest/erasurecode/offline_rebuild.yaml, src/tests/ftest/rebuild/container_create_race.yaml
Test-tag: PerServerFaultDomainTest EcodCellSizeProperty EcodOfflineRebuild RbldContainerCreate
Test-repeat: 5
=> DAOS-15535 test: Add crt_timeout to offline_rebuild.py test.

docs/user/datamover.md
Doc-only: true
Remove outdated restriction about 1.2.
Replace UUID examples with generic pool/cont
=> DAOS-13880 doc: remove outdated datamover restriction

src/tests/ftest/daos_test/suite.py, src/tests/ftest/daos_test/suite.yaml, src/tests/ftest/recovery/cat_recov_core.py, src/tests/ftest/recovery/cat_recov_core.yaml, src/tests/ftest/recovery/container_cleanup.py, src/tests/ftest/recovery/container_cleanup.yaml, src/tests/ftest/recovery/container_list_consolidation.py, src/tests/ftest/recovery/container_list_consolidation.yaml, src/tests/ftest/recovery/ms_membership.py, src/tests/ftest/recovery/pool_cleanup.py, src/tests/ftest/recovery/pool_cleanup.yaml, src/tests/ftest/recovery/pool_list_consolidation.py, src/tests/ftest/recovery/pool_membership.py
DAOS catastrophic recovery core tests may take more than 1 hour. Keep it in PR test set is too long for most of non-cat_recov PR. Let's move it to daily test set.
Add cat_recov tag for catastrophic recovery test cases.
Skip-nlt: true
=> DAOS-15638 tests: move cat_recovery test from pr to daily test

src/tests/suite/daos_cr.c
Currently, we do not have some efficient way to make the test scripts to be aware of whether rank is really excluded during CR test. So have to wait some relative long time (30 seconds). Since there are very few use cases for that, it will not much increase the whole test time.
=> DAOS-15614 tests: more wait when exclude rank during CR test

.github/workflows/rpm-build-and-test.yml
From the corresponding GHA workflows.
=> DAOS-623 ci: Update the existing (Jenkins) commit statuses

src/tests/ftest/cart/test_group_np_cli.c
- Set individual rpc timeouts for swim test client to 10 seconds, so that the global timeout would not be affecting them.
=> DAOS-15667 cart: Set individual rpc timeouts

.github/workflows/ossf-scorecard.yml
Update actions/upload-artifact used in ossf-scorecard due to deprecation notice.
=> DAOS-623 cq: update actions/upload-artifact version

src/client/pydaos/raw/daos_api.py, src/client/pydaos/raw/daos_cref.py, src/tests/ftest/pool/target_query.py
Test-tag: test_pool_target_query
Use TestPool.get_space_per_target instead of the pydaos.raw API call. Remove the no longer used pydaos.raw target_query and supporting code.
=> DAOS-15646 test: update target_query.py to use get_space_per_target

utils/utest.yaml
required_src was added to avoid conflicts on the file during feature development. It is not necessary any longer (and wrong since ddb has moved from src to src/utils now).
=> DAOS-9576 test: remove path to ddb src in ut

src/tests/ftest/recovery/ddb.yaml
Avoid using storage: auto on vm tests until DAOS-15233 can be addressed.
Test-tag: DdbTest
=> DAOS-15648 test: Avoid failures with virtual NVMe

src/common/tests_dmg_helpers.c, src/include/daos/tests_lib.h, src/tests/suite/daos_container.c
Inject more faults in the non-baseline workload loops (10% / 20% fault rate change to 33% / 50%), so there is more separation in baseline loop timing compared to the fault-injection loops timing.
Also, turn down engine logging during execution of the timed metadata workloads in co_op_dup_timing(). Restore to the originally-configured setting after the timed operations. This is done with the addition of a new tests dmg helper function, dmg_server_set_logmasks(), called from co_op_dup_timing().
Test-repeat: 5
=> DAOS-15622 test: enhance co_op_dup_timing() predictability

src/tests/ftest/server/metadata.py, src/tests/ftest/server/metadata.yaml, src/tests/ftest/util/pool_security_test_base.py
Description: implement more test to metadata with disable svc.
(continue from: https://github.com/daos-stack/daos/pull/14145)
Test-tag: ObjectMetadata
=> DAOS-15628 test: Verify maximum containers create with and without dup metadata ops

src/tests/ftest/rebuild/continues_after_stop.py
Test-tag: ContinuesAfterStop
Fix an uncaught merge confclit between #14100 and #14201
=> DAOS-15655 test: fix set_daos_params conflict

src/tests/ftest/soak/harassers.yaml, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/stress.yaml
Increase the size of the job pool to accommodate the
increase in data for the datamover test
=> DAOS-15767 test: Increase soak job pool size

src/tests/ftest/slurm_setup.py, src/tests/ftest/util/soak_utils.py
=> DAOS-15650 test: Update soak cleanup with new dfuse mounts

src/client/dfuse/dfuse_core.c
Change-Id: Ia8452f68990f495e42e8af2e8a1eb7c951fbbdfa
=> DAOS-15753 dfuse: Do not deadlock when failing to mount. (#14252)

.github/workflows/landing-builds.yml
Add missing wildcard to path matching.
=> DAOS-623 ci: fix landing-builds trigger

src/engine/server_iv.c
Test-tag: test_daos_oid_allocator
=> DAOS-15139 container: do not sleep for 1 sec on OID IV retries

src/container/oid_iv.c, src/container/srv_internal.h, src/engine/server_iv.c
Test-tag: test_daos_oid_allocator
=> DAOS-13037 container: test oid IV

src/tests/ftest/pool/verify_space.py
Skip cleanup for inaccessible container
=> DAOS-15798 test: fix pool/verify_space.py

src/include/daos/btree.h
Add return value 1 comment for the .to_rec_update().
doc-only: true
=> DAOS-15670 doc: update comment for .to_rec_update()

src/tests/ftest/util/test_utils_container.py
Test-tag: BasicSnapshot Snapshot BasicTxTest PunchTest SameKeyDifferentValue Permission RbldBasic RbldWithIO NvmePoolCapacity VerifyPoolSpace
Default TestContainer.register_cleanup to True
=> DAOS-15807 test: fix container register_cleanup

Jenkinsfile
Correct the provider and MD on SSD stage build parameters so that they use underscores in their names.
=> DAOS-15814 test: Fix build parameter for HW test stages

Jenkinsfile
Disabling timed build on this branch.  Testing will be moved to the new provider-testing branch.
=> DAOS-15772 test: Consolidating provider testing branches

src/tests/ftest/rebuild/basic.py, src/tests/ftest/rebuild/basic.yaml
Test-tag: RbldBasic
Test-repeat: 2
Remove redundant variants for data size and num records when there are zero objects.
Misc cleanup.
=> DAOS-14668 test: remove redundant rebuild/basic variants

src/tests/ftest/mpiio/llnl_mpi4py.py
Suppoprt searching for the mpi4py/tests installations in different python site-packages directories than the version being used to run launch.py.
Test-tag: test_mpi4py
=> DAOS-15617 test: Fix mpiio/llnl_mpi4py.py on EL9

src/vos/vos_obj.c
Add comment to those intended falling through cases and suppress coverity warning
=> DAOS-15309 vos: add comments to suppress coverity warning

src/tests/ftest/soak/harassers.yaml, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/stress.yaml
=> DAOS-15770 test: Increase lammps job timeout; add ior 4k job

src/rdb/rdb_raft.c
Remove a comment that is not applicable to the current code found by Mohamad.
Doc-only: true
=> DAOS-15670 rdb: Remove stale comment

utils/cq/requirements.txt
Update pylint from 3.1.0 -> 3.1.1
=> DAOS-15830 cq: update pylint to 3.1.1

src/tests/ftest/erasurecode/restart.py
The group argument was removed by #14201.
=> DAOS-15835 test: remove invalid argument

src/client/dfuse/pil4dfs/dfs_dcache.c, src/client/dfuse/pil4dfs/int_dfs.c
Fix te following coverity issues:
- CID 2555628: Argument cannot be negative
- CID 2555629: Argument cannot be negative
=> DAOS-623 client: Fix coverity issue 2555628 and 2555629

.github/workflows/linting.yml, src/tests/ftest/tags.py, utils/githooks/pre-commit.d/73-ftest.sh
Support --verbose to "tags.py lint".
Adjust GHA to run "tags.py lin --verbose"
Add githook to run "tags.py lint" only on modified files.
=> DAOS-15762 test: add githook for ftest changes

utils/rpms/packaging/get_release_branch
Speedup get_release_branch by filtering release/* branches to only 2.4+
=> DAOS-623 cq: speedup get_release_branch

src/client/dfuse/pil4dfs/aio.c, src/client/dfuse/pil4dfs/int_dfs.c, src/tests/ftest/dfuse/bash.py
Create a dedicated event queue for each aio context
=> DAOS-15803 client: simplify aio code in pil4dfs

src/client/dfuse/pil4dfs/dfs_dcache.c, src/client/dfuse/pil4dfs/int_dfs.c
=> DAOS-15831 client: fix a couple of coverity issues

src/tests/ftest/erasurecode/online_rebuild.yaml
Test-tag: EcodOnlineRebuild always_passes
Test-repeat: 3
=> DAOS-15785 test: Fix erasurecode/online_rebuild.py test times out.

utils/cq/requirements.txt, utils/githooks/pre-commit.d/73-ftest.sh
Skip the ftest tags.py githook when the python3 yaml module is not installed.
=> DAOS-623 cq: skip ftest githook for missing deps

src/tests/ftest/util/apricot/apricot/test.py
Use the CI-skip-list-release-2.6 skip list with the release/2.6 branch.
=> DAOS-15859 test: Updates for release/2.6

utils/cq/requirements.txt
=> DAOS-15860 cq: update pylint to 3.2.2

Jenkinsfile
Set the next_version correctly for this branch.
=> DAOS-15859 test: Fix next_version

src/client/dfs/cont.c
Calling daos filesystem scan on a posix container not containing any files make the daos scanner command seg faulting.
=> DAOS-15916 dfs: Seg fault with DFS scanner

Jenkinsfile
Use a copy of a working Jenkinsfile to attempt to get this branch running.
=> DAOS-15859 test: Fix builds

Jenkinsfile
Use the correct re match syntax for whitelist check.
=> DAOS-15859 test: Fix whitelist

Jenkinsfile
Use branchTypeRe() to match newer whitelist branch names.
=> DAOS-15859 test: Fix branch whitelist check

src/tests/ftest/rebuild/basic.yaml
Use crt_timeout: 10 for rebuild/basic, to restore config prior to PR #13997.
This reduces the test time drastically.
=> DAOS-15856 test: speedup rebuild/basic (#14398)

src/client/dfuse/pil4dfs/int_dfs.c
=> DAOS-15834 client: disable interception before exec() (#14405)

src/tests/ftest/deployment/agent_failure.py
=> DAOS-15868 test: Remove the mpi_type parameter.

ci/jira_query.py
Temporary fix for the jira_query.py script until  the regex approach can be validated by @ashleypittman.
=> SRE-2180 ci: Update jira_query.py with 2.6 release values

src/cart/utils/memcheck-cart.supp
Another Valgrind false positive.
=> DAOS-15959 cart: Add valgrind suppressions for Go runtime

src/pool/srv_pool.c
Make pool_svc_update_map_metrics() a void function, as
the caller can't do anything useful/different if the
metrics update fails.
Change-Id: I3a6031cd15b82907c5a516a90f075c48a9de70cf
=> DAOS-15972 pool: Address Coverity 2555665,2555666

utils/cq/requirements.txt
=> DAOS-15991 cq: update pylint to 3.2.3

src/bio/README.md, src/common/tests_dmg_helpers.c, src/control/cmd/dmg/json_test.go, src/control/cmd/dmg/pretty/storage_test.go, src/control/cmd/dmg/storage_query.go, src/control/cmd/dmg/storage_query_test.go, src/control/lib/support/log.go, src/control/server/ctl_smd_rpc_test.go, src/include/daos/tests_lib.h, src/tests/ftest/checksum/csum_error_logging.py, src/tests/ftest/nvme/health.py, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py
Remove unnecessary command alias in favor of dmg storage query list-devices --health.
=> DAOS-15966 control: Remove dmg storage query device-health

docs/admin/troubleshooting.md, src/control/server/mgmt_system.go, src/control/server/mgmt_system_test.go, src/control/system/errors.go, src/control/system/membership.go, src/control/system/membership_test.go
Previously the re-join was succeeding but not updating the address, which led to surprising behavior. With this change, the re-join fails and notifies the admin.
=> DAOS-15842 control: Reject re-join with different control addr (#14470)

src/cart/crt_hg.c
Change-Id: Idf1690c981d3d3cc4ef4108f94bda4f80d166a96
=> Enable libfabric warning logging by default

src/tests/ftest/util/server_utils.py
Redirect stderr to stdout so "grep -v <error>" works as expected.
=> DAOS-16000 test: fix get_host_log_files ignoring error

src/tests/ftest/mpiio/llnl_mpi4py.py, src/tests/ftest/mpiio/llnl_mpi4py.yaml
Remove get_test_repo() as it's no longer needed.
=> DAOS-15602 test: Find mpi4py test in /usr/bin (#14163)

utils/rpms/packaging/Makefile_packaging.mk
For more details see #14387 
It is already a part of packaging: https://github.com/daos-stack/packaging/pull/82
=> DAOS-15851 ci: Use CI_PR_REPOS parameter if provided

docs/admin/administration.md
=> DAOS-15966 docs: Remove references to device-health cmd

docs/admin/pool_operations.md, docs/user/container.md, docs/user/filesystem.md, docs/user/mpi-io.md, docs/user/python.md, docs/user/spark.md
remove depecated --label flag from dmg and daos commands
Doc-only: true
=> DAOS-15913 doc: remove depecated --label flag

docs/admin/deployment.md, src/include/daos/tests_lib.h
Admin guide documentation on configuring MD-on-SSD. Describes
necessary config file changes and example scenarios.
Doc-only: true
=> DAOS-14630 docs: Document MD-on-SSD configuration

src/cart/utils/memcheck-cart.supp
=> DAOS-16034: Valgrind issues related to go 1.22.3

docs/admin/deployment.md
Admin guide documentation on configuring MD-on-SSD. Describes necessary config file changes and example scenarios.
Doc-only: true
=> DAOS-14630 docs: Document MD-on-SSD configuration (#14559)

docs/admin/pool_operations.md, docs/user/container.md, docs/user/filesystem.md, docs/user/mpi-io.md, docs/user/python.md, docs/user/spark.md
remove depecated --label flag from dmg and daos commands
Doc-only: true
=> DAOS-15913 doc: remove depecated --label flag (#14546)

src/tests/ftest/util/server_utils.py
Redirect stderr to stdout so "grep -v <error>" works as expected.
=> DAOS-16000 test: fix get_host_log_files ignoring error (#14540)

src/client/pydaos/pydaos_shim.c
Fixing offset when appending a \0 between keys oit_mark().
=> DAOS-16026 pydaos: fix offset issue in oit_mark

src/cart/utils/memcheck-cart.supp, utils/test_memcheck.supp
Change-Id: I3458d7a4c250e39adb580486c1096e4bb8e9b704
=> DAOS-16011 : Valgrind suppressions due to update Go to 1.22.3 (#14564)

src/tests/suite/dfs_unit_test.c
=> DAOS-16087 test: disable dfs pipeline test in release build

src/tests/ftest/daos_test/suite.yaml
The daos_test container test occassionally exceeds the test timeout yet still passes.  This change will increase the test timeout.
=> DAOS-16021 test: Increase timeout for test_daos_container

src/chk/chk_leader.c
The chk_bookmark::cb_gen for leader may be refreshed during start checker even if the start process failed for some reason finally. Under such case, we need to recover the chk_bookmark::cb_gen back to its original value (before the failed 'chk start'); otherwise, if some former in-running instance failed current 'chk start', it will affect subsequent 'chk stop' command to stop such instance.
=> DAOS-15919 chk: rollback generation if failed to start checker

src/tests/ftest/util/soak_utils.py
Summary: led identify commands are sent to the appropriate host which has the valid UUIDs
=> DAOS-15999 test: Update led check method for soak_utils.py

src/control/go.mod
Go 1.20 is the latest version currently available via EPEL.
This update will enable developers to use newer Go language features.
=> DAOS-15738 control: Update required Go build version (#14413)

docs/admin/administration.md, src/bio/README.md, src/common/tests_dmg_helpers.c, src/control/cmd/dmg/json_test.go, src/control/cmd/dmg/pretty/storage_test.go, src/control/cmd/dmg/storage_query.go, src/control/cmd/dmg/storage_query_test.go, src/control/lib/support/log.go, src/control/server/ctl_smd_rpc_test.go, src/include/daos/tests_lib.h, src/tests/ftest/checksum/csum_error_logging.py, src/tests/ftest/nvme/health.py, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py
Remove unnecessary command alias in favor of dmg storage query list-devices --health.
=> DAOS-15966 control: Remove dmg storage query device-health (#14508)

src/tests/ftest/performance/ior_easy.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.py, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.py, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.py, src/tests/ftest/performance/mdtest_hard.yaml, src/tests/ftest/util/performance_test_base.py
Add performance variants for dfuse + libpil4dfs.
Add some variants for mpiio and hdf5.
Removed unused variants.
Test-tag: performance
=> DAOS-13994 test: variants for performance pil4dfs

src/tests/suite/dfs_unit_test.c
=> DAOS-16087 test: disable dfs pipeline test in release build (#14627)

src/cart/utils/memcheck-cart.supp
Valgrind issues that have already been merged to release 2.6. (See https://github.com/daos-stack/daos/pull/14580)
=> DAOS-16075 ci: Valgrind issues related to go 1.22.3

src/tests/ftest/daos_test/rebuild.py, src/tests/ftest/daos_test/rebuild.yaml, src/tests/suite/daos_rebuild.c
Check return code of daos_cont_destroy() call in the test rebuild_cont_destroy_and_reintegrate(). Also make sure that test is actually executed at least in daily_regression CI.
Test-tag: test_rebuild_35
=> DAOS-16016 test: Coverity 2555785 fix and run test_rebuild_35 (#14619)

src/client/array/dc_array.c
=> DAOS-16009 client: punch extent for dkey 1 (first array dkey)

src/include/daos/pool_map.h, src/placement/pl_map.h, src/placement/pl_map_common.c, src/tests/ftest/rebuild/cascading_failures.py, src/tests/ftest/util/container_rf_test_base.py
=> DAOS-16001 placement: fix cases for delay_rebuild

src/tests/ftest/performance/ior_easy.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.py, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.py, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.py, src/tests/ftest/performance/mdtest_hard.yaml, src/tests/ftest/util/performance_test_base.py
Test-tag: performance BasicCheckout
Add performance variants for dfuse + libpil4dfs.
Add some variants for mpiio and hdf5.
Removed unused variants.
=> DAOS-13994 test: variants for performance pil4dfs (#14533)

utils/cq/requirements.txt
=> DAOS-16122 test: update pylint to 3.2.4

src/control/lib/daos/pool_property.go, src/control/lib/daos/pool_property_test.go, src/control/lib/daos/system_prop_test.go
Updates scrub_freq property handler.
Change-Id: I268be61c8abc914d6cb91e81c800aaff25fa029e
=> Handle human-friendly duration values in pool properties

src/common/btree.c
Coverity claims that key->iov_buf can be null in the following function call memcpy(hkey, key->iov_buf, key->iov_len);
See #14625
=> DAOS-16078 common: fix Coverity issue (release/2.6)

src/mgmt/cli_debug.c, src/mgmt/cli_mgmt.c, src/mgmt/cli_query.c, src/mgmt/rpc.c, src/mgmt/rpc.h, src/mgmt/srv.c
* DAOS-16101 mgmt: enhanced interoperability for MGMT module
DAOS release 2.6 bumped mgmt RPC version because of CR feature, This PR focuses on ensuring backward compatibility and interoperability between DAOS version 2.4 and 2.6 for MGMT module.
=> DAOS-16101 mgmt: enhanced interoperability for MGMT module (#14638)

src/cart/utils/memcheck-cart.supp
=> DAOS-623 test: update suppressions for NLT

src/cart/crt_context.c, src/cart/crt_group.c, src/cart/crt_rpc.c, src/cart/crt_rpc.h
In rare corner cases an rpc could end up being on both temp submit and timeout lists, causing corruption of one or the other.
submit list is populated from wait_q list, while timeout list is populated when rpc is cancelled or times out.
Fix:
Separated timeout and submit list links in rpc_priv Added additional check to prevent aborted rpcs from being added to submitted list. timed out or cancelled rpcs will be no-ops now in dispatch_rpc() Added ref counting to between submit list population and dispatching of rpcs Early checks in group lookup to avoid looking up CRT_NO_RANK/-1 extra debug info when uri lookups fail
=> DAOS-16107 cart: submit vs timeout list

src/bio/bio_device.c, src/bio/bio_monitor.c, src/bio/bio_xstream.c
Refine the error messages when failed to acqurie traddr for AIO device.
=> DAOS-15962 bio: error message cleanup

docs/QSG/setup_rhel.md, docs/QSG/setup_suse.md, docs/admin/deployment.md, docs/index.md, mkdocs.yml
prepare docs for 2.6 release
Doc-only: true
=> DAOS-16162 doc: prepare docs for 2.6 release

utils/cq/requirements.txt
=> DAOS-16134 cq: update pylint to 3.2.5

SConstruct
Disable warning for deprecated support for python
version so it doesn't fail the build.
=> DAOS-16168 build: Ignore scons version deprecation

SConstruct
Disable warning for deprecated support for python
version so it doesn't fail the build.
Change-Id: I7753b5e32e291fe748cddfe4caea2fc851b15e66
=> DAOS-16168 build: Ignore scons version deprecation (#14715)

utils/githooks/hook_base.sh
Change-Id: I5820d9b4c426235e6697d481652d588fcd0794b0
=> Fix issue with shellcheck

utils/nlt_server.yaml
=> Revert "DAOS-16153 nlt: set server nlt tmpfs size to 8g"

src/tests/ftest/deployment/io_sys_admin.py, src/tests/ftest/deployment/io_sys_admin.yaml
Set container ownership to the existing root user instead of creating a new user so the test doesn't need sudo.
Also misc cleanup to be inline with latest standards.
=> DAOS-16204 test: remove sudo requirements from io_sys_admin.py

src/pool/srv_pool.c
This is a cherry-pick of master PR 14753.
- pool_upgrade_props should take care of ds_pool_prop_svc_ops_{num,max} too.
- pool_upgrade_props modifies ds_pool_prop_svc_ops_{enabled,age,max}, which are cached by pool_svc. It must also update the cached values too.
- read_db_for_stepping_up should only access ds_pool_prop_svc_ops_{enabled,age,max} when the pool global version is high enough. If one of the properties is expected but absent, it should be an error; recovering the value to 0 may not be desirable.
Features: pool
=> DAOS-16037 pool: Fix upgrade for svc_ops

src/cart/crt_rpc.c
- Internal URI_LOOKUP rpc to inherit origianl RPC timeout if set
=> DAOS-16226 cart: URI_LOOKUP rpc to inherit the original RPC timeout

src/client/dfs/dfs_sys.c, src/control/cmd/daos/filesystem.go, src/control/cmd/daos/flags.go, src/control/cmd/daos/flags_test.go, src/include/daos_fs_sys.h, src/utils/daos_dfs_hdlr.c, src/utils/daos_hdlr.h
=> DAOS-16253 control: Add chmod to daos utility

site_scons/components/__init__.py, site_scons/prereq_tools/base.py
It causes issues at runtime with loading libioil.so
Change-Id: I25cf05bf11110fc7d2590fca65434e2f66796c77
=> b/352822244 Remove ucx from build

docs/user/mpi-io.md
add MPICH and IMPI infos on how to set daos: prefix
=> DAOS-16162 doc: add information on MPI-IO daos: prefix

utils/cq/requirements.txt
=> DAOS-16261 cq: update pylint to 3.2.6

src/tests/ftest/deployment/ior_per_rank.py, src/tests/ftest/deployment/ior_per_rank.yaml
use math.inf to disable threshold checks in CI so the test can run as a smoke test
=> DAOS-13078 test: update ior_per_rank.py to work in CI

src/tests/ftest/osa/online_drain.py, src/tests/ftest/osa/online_drain.yaml
Test-repeat: 2
Get the targets and ranks from the config instead of hardcoding. Also use self.random instead of direct random.
=> DAOS-15953 test: update online_drain to use config values

src/tests/ftest/dfuse/daos_build.py
Try to build with the SHA under test if possible in the dfuse/daos_build.py test.
=> DAOS-15613 test: build current SHA in daos_build.py

src/tests/ftest/datamover/negative.py, src/tests/ftest/util/data_mover_test_base.py
remove DataMoverTestBase.posix_local_test_paths in favor of local references
Test-tag: datamover
=> DAOS-15778 test: remove DataMoverTestBase.posix_local_test_paths

docs/release/release_notes.md, docs/release/support_matrix.md, docs/release/upgrading.md
add draft 2.6 release notes document
Doc-only: true
=> DAOS-9355 doc: first draft of DAOS 2.6 release notes

docs/user/mpi-io.md
add MPICH and IMPI infos on how to set daos: prefix
=> DAOS-16162 doc: add information on MPI-IO daos: prefix (#14794)

src/tests/suite/dfs_unit_test.c
In some cases one of the servers has a time stamp that is some microseconds different from the client. If that happens we can see this issue in the mtime and ctime test to make it look like we went back in time. Because the ctime reported from the dfs_osetattr() is the one on the client node, and it’s comparing to an mtime value that was obtained from an hlc obtained from the server side. So I will update the test to sleep for 10 ms to avoid such issue.
Test-tag:test_daos_dfs_unit
=> DAOS-16234 test: add a 10 ms sleep in the dfs time test

src/control/cmd/daos/filesystem.go, src/control/cmd/daos/flags.go, src/control/cmd/daos/flags_test.go, src/utils/daos_dfs_hdlr.c, src/utils/daos_hdlr.h
Example usage:
// Original state
[juszhan_google_com@juszhan-dev daos]$ ls -la /tmp | grep dfuse0
drwxr-xr-x   1 juszhan_google_com juszhan_google_com   120 Apr 17 23:53 dfuse0
-rw-r--r--   1 juszhan_google_com juszhan_google_com  9146 Apr 17 23:53 dfuse0.log
// Change group to a known group id
[juszhan_google_com@juszhan-dev daos]$ getent group 1001 tmpuserjohn:x:1001:
[juszhan_google_com@juszhan-dev daos]$ run_cmd daos fs chown pool cont -g 1001 --dfs-path=/ Running DAOS_AGENT_DRPC_DIR=/tmp/agent daos fs chown pool cont -g 1001 --dfs-path=/
[juszhan_google_com@juszhan-dev daos]$ ls -la /tmp | grep dfuse0
drwxr-xr-x   1 juszhan_google_com tmpuserjohn          120 Apr 17 23:53 dfuse0
-rw-r--r--   1 juszhan_google_com juszhan_google_com  9146 Apr 17 23:53 dfuse0.log
// Change group to a …
=> b/334917514 - Add daos fs chown (#14184)

src/client/dfs/obj.c, src/control/cmd/daos/filesystem.go, src/control/cmd/daos/object.go, src/include/daos_fs.h, src/tests/ftest/util/daos_utils.py, utils/node_local_test.py
Makes it a little easier to query the layout
=> DAOS-16237 control: Add OID to filesystem get-attr (#14774)

src/cart/utils/crt_utils.c, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/cart_ctl_utils.py, src/utils/ctl/cart_ctl.c
- Change cart_ctl to no longer fail if pre-ping fails in daos env
- Set individual cmd pings to be 3 seconds
- Change cart_ctl invocation to use 'no sync' option, avoiding pinging all ranks, including possibly dead ones
=> DAOS-16008 cart: cart_ctl fixes (#14686)

src/control/cmd/daos_server/auto_test.go, src/control/cmd/dmg/auto_test.go, src/control/lib/control/auto.go, src/control/lib/control/auto_test.go, src/control/server/config/server_test.go, src/tests/ftest/control/config_generate_output.py
Config generate should not output auto calculated values update ftest
to not expect scm_size in config generate yaml output
=> DAOS-16223 control: Config generate to not output auto values (#14778)

src/control/lib/hardware/cart/cart_test.go, src/control/lib/hardware/cart/ucx.go, src/control/lib/hardware/cart/ucx_test.go
- Include the original UCX transport name (e.g. "ucx+rc_verbs") in the list of accepted UCX providers, alongside the aliases (e.g. "ucx+rc_v", "ucx+rc").
=> DAOS-16159 control: Accept UCX full transport names (#14768)

src/cart/utils/memcheck-cart.supp
=> DAOS-16228 test: update suppressions for NLT again (#14762)

src/tests/ftest/deployment/io_sys_admin.py, src/tests/ftest/deployment/io_sys_admin.yaml
Set container ownership to the existing root user instead of creating a new user so the test doesn't need sudo.
Also misc cleanup to be inline with latest standards.
=> DAOS-16204 test: remove sudo requirements from io_sys_admin.py (#14732)

src/utils/self_test/self_test.c
- Added --no-sync option (-n) to self_test. When set will skip pre-ping of all ranks in the group before running the actual self_test
- Usages of self_test with daos_agent env (-u option) changed to automatically disable sync.
Rationale: crtu_wait_for_ranks() which performs sync was added for scenarios when self_test is started in a stand-alone mode, which then allows self_test to block until all test servers are up. In the production case (using daos agent), this step is not needed and can lead to self_test aborting on a dead target that is not related to the one attempting to be tested.
=> DAOS-16151 cart: add no-sync option to self_test (#14697)

src/common/btree.c
=> DAOS-16078 common: fix a Coverity issue (release/2.6 catching up with the master)

src/tests/suite/daos_extend_simple.c
In release 2.6 RC1 testing certain daos_test -B (extend_simple)
cases failed (EXTEND6, EXTEND8, EXTEND14). It was found that, although
some extend tests use fault injection via dfs_extend_internal(), they
did not invoke FAULT_INJECTION_REQUIRED(). Tthis can result in
unpredictable execution (e.g., hangs) when running with a daos build
whose BUILD_TYPE=release.
This change adds the FAULT_INJECTION_REQUIRED() macro call,
and makes some minor changes to the test code to make the output
reflect what steps the test executes - to facilitate debugging.
Test-tag: test_daos_extend_simple
faults-enabled: false
=> DAOS-15930 test: extend_simple add FI required macro call

docs/release/release_notes.md, docs/release/support_matrix.md
=> DAOS-16162 doc: DAOS 2.6 support matrix

src/cart/crt_hg.c, src/cart/crt_register.c
Small cleanup
- simplified crt_get_info_string
- version check messages modified with one being moved to info
=> DAOS-16317 cart: Simplify crt_get_info_string

src/tests/ftest/aggregation/continuous_write.py, src/tests/ftest/aggregation/space_rb.py, src/tests/ftest/deployment/agent_failure.py, src/tests/ftest/deployment/basic_checkout.yaml, src/tests/ftest/deployment/ior_per_rank.yaml, src/tests/ftest/deployment/network_failure.py, src/tests/ftest/deployment/server_rank_failure.py, src/tests/ftest/deployment/target_failure.py, src/tests/ftest/ior/hard.yaml, src/tests/ftest/ior/hard_rebuild.yaml, src/tests/ftest/nvme/enospace.py, src/tests/ftest/nvme/fragmentation.py, src/tests/ftest/nvme/pool_capacity.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/rebuild/continues_after_stop.py, src/tests/ftest/server/metadata.py, src/tests/ftest/util/ior_test_base.py, src/tests/ftest/util/ior_utils.py, src/tests/ftest/util/mdtest_test_base.py, src/tests/ftest/util/mdtest_utils.py, src/tests/ftest/util/nvme_utils.py, src/tests/ftest/util/soak_utils.py
support dynamic stonewall file for ior and mdtest by using DAOS_TEST_LOG_DIR
Features: ior mdtest
=> DAOS-16229 test: support dynamic stonewall file

src/vos/vos_obj_cache.c
This fixes a minor perf issue with conditional update that prevents us from creating the object only to remove it.
=> DAOS-16323 vos: Fix conditional update perf bug

site_scons/components/__init__.py, site_scons/prereq_tools/base.py, utils/build.config
Move URLs for repos to the config file allowing
one to replace the config file.
=> DAOS-16305 build: Simplify hermetic builds (#14874)

src/tests/ftest/deployment/io_sys_admin.yaml, src/tests/ftest/io/large_file_count.yaml, src/tests/ftest/io/small_file_count.yaml, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/file_count_test_base.py
Use different set of oclasses for ior and mdtest.
Add intercept option in mdtest_test_base.
Use interception for POSIX runs in the test.
Test-tag: pr test_io_sys_admin test_largefilecount test_smallfilecount test_basic_checkout_dm
=> DAOS-15960 tests: Improvements for io_sys_admin test (#14503)

src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/fault_config_utils.py
Since fault injection files used by the test harness are placed in a location owned by the user sudo is not needed to remove the files.
Also replace run_command and pcmd with run_remote in test.py.
Test-tag: faults
=> DAOS-16219 test: Remove sudo usage from fault injection files

src/tests/ftest/dfuse/mu_perms.yaml, src/tests/ftest/util/dfuse_utils.py
Increase the VerifyPermsCommand.timeout from 120 seconds to 240 seconds.
Test-tag: DfuseMUPerms
=> DAOS-16301 test: Increase verify_perms.py timeout

src/tests/ftest/dfuse/mu_perms.yaml, src/tests/ftest/util/dfuse_utils.py
Increase the VerifyPermsCommand.timeout from 120 seconds to 240 seconds.
Test-tag: DfuseMUPerms
=> DAOS-16301 test: Increase verify_perms.py timeout (#14910)

src/tests/ftest/control/daos_agent_config.py, src/tests/ftest/deployment/network_failure.py, src/tests/ftest/harness/advanced.py, src/tests/ftest/harness/coverage.py, src/tests/ftest/harness/coverage.yaml, src/tests/ftest/util/agent_utils.py, src/tests/ftest/util/agent_utils_params.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/command_utils_base.py, src/tests/ftest/util/environment_utils.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/network_utils.py, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/support_test_base.py
Add new launch.py command line arguments to support running the agent as
a different user and support this user argument within the test framework.
Add a new harness test to easily verify common test functions.
Recent support for user run daos_agent in the test harness enabled
always creating the runtime_dir, but this causes the
test_daos_agent_config_basic test to fail when using a list for the
runtime_dir value.  This change supports skipping the creation of the
runtime_dir for testing purposes.
Test-tag: DaosAgentConfigTest HarnessCoverageTest DmgSupportCollectLogTest DaosServerSupportCollectLogTest DaosAgentSupportCollectLogTest SoakSmoke NetworkFailureTest
Signed-off-by: Phil Henderson …
=> DAOS-16218 test: Support running agent as user #14751

src/bio/bio_wal.c, src/vos/tests/wal_ut.c
Bump max WAL tx size from 8MB to 16MB.
=> DAOS-16036 bio: bump max WAL tx size to 16MB (#14589)

src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/fault_config_utils.py
Since fault injection files used by the test harness are placed in a location owned by the user sudo is not needed to remove the files.
Also replace run_command and pcmd with run_remote in test.py.
Test-tag: test_always_passes_hw EcodFaultInjection PoolServicesFaultInjection TestScrubberEvictWithAggregation TestWithScrubberFault TestScrubberEvictWithRebuild TestScrubberEvictWithSnapshot TestWithScrubberTargetEviction
=> DAOS-16219 test: Remove sudo usage from fault injection files (#14898)

src/cart/crt_hg.c, src/cart/crt_register.c
- simplified crt_get_info_string
- version check messages modified with one being moved to info
=> DAOS-16317 cart: Simplify crt_get_info_string (#14896)

src/cart/crt_rpc.c
- If a URI_LOOKUP fails for a target of PROTO_QUERY rpc then avoid performing lookup retries as the caller will retry PROTO_QUERY to a different target on failure anyway.
This should avoid needless retries and errors when an excluded rank is picked as a target of PROTO_QUERY and URI_LOOKUP of it fails (due to it being excluded).
=> DAOS-16354 cart: Don't retry URI_LOOKUPs for PROTO_QUERY rpc (#14922)

src/tests/ftest/soak/harassers.yaml, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
=> DAOS-16333 test: Disable the debug mask during rebuild in soak testing

debian/changelog, debian/daos-client.install, src/utils/self_test/SConscript, src/utils/self_test/self_test.c, src/utils/self_test/self_test_lib.c, src/utils/self_test/self_test_lib.h, utils/rpms/daos.rpmlintrc, utils/rpms/daos.spec
Move the non-UI logic from self_test.c into a new
library that can be used from other callers.
Features=CartSelfTest
Change-Id: Ifcf8f62e20f7c9fdced0cab17343654765758536
=> DAOS-16304 tools: Create libdaos_self_test

src/tests/ftest/soak/harassers.yaml, src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
=> DAOS-16333 test: Disable the debug mask during rebuild in soak testing (#14913)

src/cart/crt_hg.c, src/cart/crt_hg.h, src/cart/crt_init.c, src/cart/crt_internal_fns.h
Skip-build-el8-gcc: true
Test-provider: ucx+dc_x
=> DAOS-15439 cart: Support free-form provider specification for UCX.

src/tests/ftest/dfuse/bash.py, src/tests/ftest/dfuse/bash_dcache.py, src/tests/ftest/dfuse/bash_fd.py, src/tests/ftest/dfuse/daos_build.py, src/tests/ftest/dfuse/mu_perms.py, src/tests/ftest/dfuse/pil4dfs_dcache.py, src/tests/ftest/dfuse/pil4dfs_fio.py, src/tests/ftest/ior/intercept_messages.py, src/tests/ftest/ior/intercept_messages_pil4dfs.py, src/tests/ftest/ior/intercept_multi_client.py
Update il -> ioil for consistency
=> DAOS-16310 test: consolidate il and ioil tags (#14881)

src/tests/suite/daos_rebuild_ec.c
for easier debugging when the test fails, to know what subtest it was running, etc.
Test-tag: test_daos_rebuild_ec
=> DAOS-15996 test: enhance output of test_daos_rebuild_ec

debian/daos-client.install, src/utils/self_test/SConscript, src/utils/self_test/self_test.c, src/utils/self_test/self_test_lib.c, src/utils/self_test/self_test_lib.h, utils/rpms/daos.rpmlintrc, utils/rpms/daos.spec
Move the non-UI logic from self_test.c into a new
library that can be used from other callers.
Change-Id: I21da8b82a57f423974b9af9b8870551b2f4b8f8b
=> DAOS-16304 tools: Create libdaos_self_test (#14950)

src/tests/ftest/launch.py, src/tests/ftest/util/launch_utils.py
diff returns rc=1 if the files are different, which is expected. Ignore the rc
=> DAOS-16391 test: ignore rc from run_local diff

src/rsvc/srv.c
From @yyyshi: It is likely that a simplified implementation was used in the early stages of the project and updates were ignored in the future, i think a fix is needed.
=> DAOS-14544 rsvc: crt tree type usgae fix

src/tests/ftest/util/launch_utils.py
diff returns rc=1 if the files are different, which is expected. Ignore the rc
=> DAOS-16391 test: ignore rc from run_local diff (#14978)

src/cart/crt_hg.c
- Added explicit assert check for provider_str not being null and removed a conditional check which confused coverity.
=> DAOS-16407 cart: coverity 2555825 fix (#14994)

src/tests/ftest/telemetry/wal_metrics.py
Change the expected WAL replay time range from [10us, 5ms] to [1us, 1s].
=> DAOS-16279 test: bump expected WAL replay time (#14833)

src/tests/ftest/control/config_generate_run.py
Update the --control-metadata-path assignment for dmg config generate command to avoid issues cleaning up the files generated.
=> DAOS-16334 test: Fix permission denied removing temporary test files

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/infocache_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go
Fabric interfaces defined statically in the daos_agent config file are fundamentally different from those detected via hardware scanning. They don't include information derived from the hardware such as their true device class or fabric provider(s).
This patch adds some rigor to what is ignored regarding these manually-defined interfaces.
- Ignore provider for statically-defined fabric interfaces, as we do not bother detecting it. They are assumed to be compatible with whatever provider the agent is using.
- Silence confusing "no interfaces requested" error from WaitFabricReady by not calling it if there are no interfaces to check.
- Remove some defunct logic related to detecting the provider in the multi-provider case. The agent may only use a single provider. …
=> DAOS-16352 control: Handle cases with static ifaces (#14953)

src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/server_utils.py
Remove get_host_log_files since it is no longer needed. Also remove search_log which used get_host_log_files and is unused. 
=> DAOS-16463 test: remove get_host_log_files

src/include/daos_srv/vos_types.h, src/vos/vos_iterator.c, src/vos/vos_obj.c
vos_iter_param_t.ip_hdl is for passing dkey or akey tree open handle in vos_iterate_key() case, don't always regard it as 'vos_pool' or 'vos_container'.
=> DAOS-16465 vos: fix misused ip_hdl

src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/server_utils.py
Remove get_host_log_files since it is no longer needed. Also remove search_log which used get_host_log_files and is unused.
=> DAOS-16463 test: remove get_host_log_files (#15030)

utils/build.config
=> DAOS-16315 mercury: update to 2.4.0rc5 (#15015)

src/include/daos_srv/vos_types.h, src/vos/vos_iterator.c, src/vos/vos_obj.c
vos_iter_param_t.ip_hdl is for passing dkey or akey tree open handle in vos_iterate_key() case, don't always regard it as 'vos_pool' or 'vos_container'.
=> DAOS-16465 vos: fix misused ip_hdl (#15034)

src/rsvc/srv.c
- Change from flat to knomial tree for broadcasts
=> DAOS-14544 rsvc: crt tree type usage fix (#14834)

src/tests/ftest/dfuse/ioctl_pool_handles.py, src/tests/ftest/dfuse/ioctl_pool_handles.yaml
The dfuse/ioctl_pool_handles.py test is overloading the VM so reduce the number of engine targets.
Test-tag: test_ioctl_pool_handles
=> DAOS-16471 test: Reduce targets for ioctl_pool_handles.py

utils/build.config
=> DAOS-16271 mercury: Add patch to avoid seg fault in key resolve.

utils/build.config
=> DAOS-16271 mercury: Add patch to check ep for null in UCX key resolve.

src/client/dfs/common.c, src/tests/ftest/tags.yaml
Automatically include dfs tests when dfs files are modified in PRs.
=> DAOS-16450 test: auto run dfs tests when dfs is modified

utils/cq/requirements.txt
=> DAOS-16510 cq: update pylint to 3.2.7

src/common/btree.c, src/include/daos/btree.h, src/vos/vos_container.c, src/vos/vos_gc.c, src/vos/vos_internal.h, src/vos/vos_layout.h, src/vos/vos_obj_cache.c, src/vos/vos_obj_index.c, src/vos/vos_tree.c
- Use the reserved vos_gc_item.it_args to store 2 bucket IDs for
GC_OBJ, GC_DKEY and GC_AKEY, so that GC drain will be able to tell the
what buckets need be pinned by looking up bucket numbers stored in
vos_obj_df.
- Once GC drain needs to pin a different bucket, it will have to commit
current tx; unpin current bucket; pin required bucket; start new tx;
- Forge a dummy object as the private data for the btree opened by GC,
so that the 'ti_destroy' hack could be removed.
- Store evict-able bucket ID persistently for newly created object, this
was missed in prior PR.
TODO:
- Reorg DTX commit code to pre-load objects before starting transaction.
- Reorg multiple-objects tx code to pre-load objects.
- Improve engine scheduler to take both non-evict-able & evict-able zones
space pressure into …
=> DAOS-14316 vos: object preload for GC

src/vos/vos_obj.c
Fix coverity 2555843 explict null dereferenced.
=> DAOS-16514 vos: fix coverity issue

src/vos/vos_obj.c
Fix coverity 2555843 explict null dereferenced.
=> DAOS-16514 vos: fix coverity issue (#15083)

src/bio/bio_context.c, src/bio/bio_wal.c, src/bio/bio_wal.h, src/include/daos/mem.h, src/include/daos_srv/bio.h, src/vos/vos_dtx.c, src/vos/vos_gc.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_obj_cache.c, src/vos/vos_obj_index.c, src/vos/vos_pool.c, src/vos/vos_tree.c
VOS local transaction (dtx_begin() with DTX_LOCAL flag) was introduced for large tx with many objects/operations involved, it doesn't support yield within the tx, so it can only be used for RDB so far.
In md-on-ssd phase2, evictable (scm_size < meta_size) RDB pool and VOS local transaction over evictable pool will not be supported.
=> DAOS-14313 vos: Various changes for VOS local tx

src/tests/ftest/soak/soak-extra-mdonssd.yaml
=> DAOS-16540 test: include extra yaml for md on ssd

src/common/dav_v2/dav_v2.h, src/common/dav_v2/heap.c, src/common/dav_v2/heap.h, src/common/dav_v2/heap_layout.h, src/common/dav_v2/palloc.c, src/common/dav_v2/stats.c, src/common/mem.c, src/common/tests/umem_test_bmem.c, src/include/daos/mem.h, src/vos/tests/vts_wal.c
New api umempobj_get_mbusage() is introduced to fetch the allocation stats for an MB. If the id passed is zero then the allocation stats of all the non-evictable MBs are returned.
=> sherintg/vos on blob p2/daos 16489

src/tests/ftest/util/systemctl_utils.py
Handle unexpected output when parsing the systemctl service file.
=> DAOS-16560 test: Improve get_service_file() (#15116)

src/tests/ftest/util/ior_utils.py
=> DAOS-16567 test: remove unused IorCommand.log_metrics

src/tests/ftest/server/multiengine_persocket.py, src/tests/ftest/server/multiengine_persocket.yaml, src/tests/ftest/util/apricot/apricot/test.py
Update the server/multiengine_persocket.py test to use test harness methods to ensure compatability with future test harness updates.  Also add a test_mode option to allow verification of all but the PMem reconfiguration in CI.
=> DAOS-16566 test: Update server/multiengine_persocket.py

src/tests/ftest/control/config_generate_run.py, src/tests/ftest/harness/config.yaml, src/tests/ftest/util/dmg_utils_base.py
Use the TestEnvironment.conftrol.config file by default with the DmgCommand object when a config file is not specified.
Test-tag: DmgNvmeScanTest ConfigGenerateOutput ConfigGenerateRun HarnessConfigTest
=> DAOS-16495 test: Use the test env control config file w/ dmg (#15094)

Jenkinsfile, src/tests/ftest/tags.py, src/tests/ftest/vmd/fault_reintegration.py, src/tests/ftest/vmd/led.py
Enable a stage for functional tests that require VMD hardware.
Skip-func-hw-test-medium-vmd: false
Test-tag: VmdLedStatus NvmeFaultReintegrate
=> DAOS-16589 test: Add Hardware Medium VMD test stage.

src/common/mem.c, src/include/daos/mem.h, src/vos/vos_common.c, src/vos/vos_gc.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_obj_cache.c, src/vos/vos_pool.c
Added umem cache metrics for md-on-ssd phase2 pool.
=> DAOS-16562 vos: umem cache metrics

Jenkinsfile, src/tests/ftest/harness/basic.py
Add Build with parameters option to run the stage.  Enable some basic harness tests to run in the stage.
Skip-func-hw-test-medium-vmd: false
Test-tag: test_always_passes_hw test_load_mpi_hw
=> DAOS-16589 test: Support Functional Hardware Medium VMD stage

src/common/mem.c, src/vos/tests/vts_wal.c
Added VOS unit tests for phase2 pool.
=> DAOS-16569 test: phase2 VOS unit tests

src/tests/ftest/util/network_utils.py, utils/build.config
PR-repos: mercury@PR-123:1
Test-provider: ucx+dc_mlx5
=> DAOS-16634 cart: Test DAOS with Mercury UCX updates.

utils/build.config
=> DAOS-16634 mercury: Update source build in release 2.6 with ucx patch.

utils/cq/requirements.txt
=> DAOS-16626 cq: update pylint to 3.3.1

docs/release/release_notes.md
2.6.1 release notes document
Doc-only: true
=> DAOS-9355 doc: DAOS 2.6.1 release notes

ci/unit/test_nlt_node.sh, src/cart/crt_init.c
=> Just a test to see if we can get around the extra NLT warning

src/tests/ftest/util/ior_utils.py
=> DAOS-16567 test: remove unused IorCommand.log_metrics (#15128)

src/tests/ftest/deployment/io_sys_admin.py, src/tests/ftest/deployment/io_sys_admin.yaml
Support running independent io sys admin steps from the yaml.
=> DAOS-16584 test: Support running independent io sys admin steps (#15134)

src/engine/sched.c, src/include/daos_srv/vos_types.h, src/vos/vos_space.c
Taking NE usage into account on space pressure checking.
=> DAOS-16640 vos: NE usage on space pressure checking

src/tests/ftest/soak/soak-extra-mdonssd.yaml
=> DAOS-16540 test: include extra yaml for soak md on ssd (#15104)

Jenkinsfile
Enable running weekly tests that require VMD hardware.
=> DAOS-16589 test: Add Functional Hardware Medium VMD stage.

src/tests/ftest/daos_test/rebuild.py, src/tests/ftest/daos_test/rebuild.yaml
Adding rebuild tests currently not executed by daos_test/rebuild.py.
Test-tag: test_rebuild_31 test_rebuild_32 test_rebuild_33 test_rebuild_34
=> DAOS-16027 test: Adding daos_test REBUILD31-34 subtests (#14584)

docs/admin/administration.md, src/bio/README.md, src/common/tests_dmg_helpers.c
Fix missing reference to --host in C test helper and update some doc references.
=> DAOS-16487 test: fix dmg c helper for set-faulty changes (#15151)

src/tests/ftest/io/large_file_count.yaml, src/tests/ftest/io/small_file_count.yaml, src/tests/ftest/ior/small.yaml, src/tests/ftest/util/file_count_test_base.py, src/tests/ftest/util/ior_test_base.py, src/tests/ftest/util/ior_utils.py, src/tests/ftest/util/soak_utils.py
set D_IL_REPORT per test instead of setting defaults values in utilities. This allows running without it set.
Features: IoctlPoolHandles IoSysAdmin performance ior dfuse soak_smoke
=> DAOS-16447 test: set D_IL_REPORT per test (#15012)

src/bio/smd/smd_pool.c
The 'ex_meta_pool' table was introduced to store 'scm_size' in SCM when a pool is evict-able (blob_size > scm_size), so on pool destroy, we'd first check if the 'ex_meta_pool' table exists before deleting it, otherwise, a DER_NONEXIST error message would be printed for the pools with blob_size == scm_size.
=> DAOS-16668 bio: avoid nonexist error message on pool destroy

src/tests/ftest/daos_test/suite.py, src/tests/ftest/harness/skip_list.py, src/tests/ftest/tags.py
Check that test_ tags are only used specifically for the one method they tag.
Test-tag: DaosCoreTest pr,vm
=> DAOS-16548 test: add ftest lint check for invalid test_ tag (#15106)

src/common/dav_v2/heap.c, src/common/dav_v2/tx.c
Refixing this ticket to take care of yield in umem_cache_map() in heap_create_evictable_mb(). Also make sure that the mapped page is pinned before updating the zone headers.
=> DAOS-16633 common: SEGV in heap_mbrt_incrmb_usage()

src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/mdtest_easy.py, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.py, src/tests/ftest/performance/mdtest_hard.yaml
- Add variants for mdtest with RP_3G1
- Update ec cell size to 1MiB for mdtest and ior easy
=> DAOS-16590 test: misc ftest/performance updates (#15144)

src/client/pydaos/pydaos_shim.c
Disable call to pthread_atfork and daos_reinit() in pydaos until DAOS-16637 is understood.
=> DAOS-16637 pydaos: disable atfork handler

Jenkinsfile, src/tests/ftest/harness/basic.py, src/tests/ftest/tags.py, src/tests/ftest/vmd/fault_reintegration.py, src/tests/ftest/vmd/led.py
Add Build with parameters option to run the stage.  Enable some basic
harness tests to run in the stage.
Enable a stage for functional tests that require VMD hardware.
Skip-func-hw-test-medium-vmd: false
Test-tag: test_always_passes_hw test_load_mpi_hw
=> DAOS-16589 test: Support Functional Hardware Medium VMD stage (#15166)

src/client/java/hadoop-daos/pom.xml
Bumps org.apache.hadoop:hadoop-common from 3.3.6 to 3.4.0.
---
- dependency-name: org.apache.hadoop:hadoop-common dependency-type: direct:development ...
=> DAOS-16667 client: bump hadoop-common from 3.3.6 to 3.4.0 (#15194)

debian/changelog, debian/control, site_scons/site_tools/go_builder.py, src/control/go.mod, utils/docker/Dockerfile.ubuntu, utils/rpms/daos.spec
* DAOS-16621 build: Fix Go versions in rpm/deb packaging
Set Go minimum version to 1.21 in rpm and debian packaging spec files. Update scons Go version check to use version in go.mod. Add a reminder in go.mod file so we remember the packaging files when bumping the minimum Go version in the future. Update Ubuntu 22.04 Dockerfile to get an appropriate version of Go.
=> DAOS-16621 build: Fix Go versions in rpm/deb packaging (#15174)

.github/workflows/linting.yml
Pin isort to v1.1.0 to avoid suprprise changes and because v1.1.1 is not working for us.
=> DAOS-16720 cq: pin isort to v1.1.0 (#15338)

src/tests/suite/daos_container.c
DAOS-16703 requires this cherry pick PR from the earlier DAOS-15852.
Rarely, this test will produce timings that exceed the failure threshold. Local and PR/CI experiments have shown that increasing the test's NUM_OPS to more than 200 iterations greatly reduces or may eliminate such intermittent timing failures, by "spreading out" the magnitude of the time spent in the 3 main loops of the test (0% loops perform fault injections, 33%, and 50%).
=> DAOS-15852 test: more timing samples for co_op_dup_timing() (#14497)

Jenkinsfile
Release branch PRs should use the release branch build instead of master branch build for NLT reference
Skip-functional-test: true
=> DAOS-16716 ci: Set reference build for PRs

src/control/server/ctl_storage_rpc.go, src/control/server/ctl_storage_rpc_test.go, src/control/server/storage/bdev.go
Target ID list returned for SMD devices on storage scan can contain
duplicate IDs and ID "1024" representing the sysXS "target".
Sanitization of the ID list is performed when converting from protobuf
to native types (storage.SmdDevice.UnmarshalJSON) however
adjustNvmeSize() mutates protobuf (not-native type) controller objects
so when performing calculations the un-sanitized ID list is being used.
This results in calculation errors and so in order to use the correct
target count use a helper that converts the device to native form
before returning count.
Feature: control
=> DAOS-16160 control: Fix count calcs for MD-on-SSD dev tgt IDs

src/control/cmd/dmg/auto_test.go, src/control/server/storage/scm.go, src/control/server/storage/scm_test.go, utils/config/daos_server.yml
Update system_ram_reserved to avoid an OOM issue when running pool
create 100% in MD-on-SSD mode with a single engine per host. Default
value has been increased from 16 to 26 based on experiments using wolf
cluster. Value expected to be used to tune behaviour based on specific
deployment environments.
=> DAOS-16698 control: Bump system_ram_reserved for MD-on-SSD pool create

src/cart/crt_iv.c
- Fix rc in error path during ivo_on_update failure
=> DAOS-16696 cart: Fix rc in error path (#15313)

src/tests/ftest/recovery/pool_list_consolidation.yaml
dmg check disable takes longer for
test_lost_majority_ps_replicas() and test_orphan_pool_trust_ms(). Increase timeout by 30 sec.
Test-tag: pool_list_consolidation
=> DAOS-16704 test: Increase timeout for pool_list_consolidation.py

src/vos/vos_obj_cache.c
It's not necessary to pin object in vos_obj_check_discard() since it doesn't access object at all.
=> DAOS-16668 vos: remove unnecessary object pin

src/common/dav_v2/heap.c, src/common/tests/umem_test_bmem.c, src/vos/tests/vts_wal.c
Existing Active EMB will now swtich to a different EMB if its space utilization is greater than 75%.
=> DAOS-16740 common: Change in EMB selection for new objects.

src/cart/README.env, src/cart/crt_hg.c, src/cart/crt_init.c, src/cart/crt_internal_types.h
=> DAOS-14262 cart: add ability to select traffic class for SWIM context (#14893)

src/container/srv_target.c
To reduce the side-effect caused by frequent log with -DER_INPROGRESS.
=> DAOS-16469 container: Lower log level for cont_aggregate_interval

src/client/dfuse/pil4dfs/int_dfs.c
Intercept PMPI_Init() to avoid calling daos_init() if MPI_Init() is intercepted by other library (like darshan and mpip).
=> DAOS-16722 client: to intercept PMPI_Init() in libpil4dfs

src/tests/ftest/util/command_utils.py
Do not raise an exception if parsing empty json output.
=> DAOS-16709 test: Handle decoding empty json output

utils/githooks/find_base.sh, utils/rpms/packaging/get_release_branch
The githooks support DAOS_ORIGIN setting, propagate this to the get_release_branch script.
=> DAOS-16744 ci: Enable change of origin

utils/githooks/find_base.sh, utils/rpms/packaging/get_release_branch
The githooks support DAOS_ORIGIN setting, propagate this to the get_release_branch script.
=> DAOS-16741 ci: Enable change of origin (#15380)

Jenkinsfile
Explicitly specify the base_branch for Functional HW test stages.
=> SRE-2329 build: Fix checkout 'null' from version control

src/include/daos_errno.h
=> DAOS-623 common: Remove quotes from error string.

src/tests/ftest/util/soak_test_base.py, src/tests/ftest/util/soak_utils.py
DAOS-16167 changes needed on aurora/2.6
Includes aurora/2.6 - rc3
Includes PR-14775 (master) 
Updates needed from master -> 2.6   (launch_vmd_identify_check function)
remove daos_clients from yamls
include daos_test_env in dfuse
remove taskset from dfuse cmd; cores: in yaml
See details in DAOS-16167
=> Update vmd harasser with 2.6 function

utils/build.config
=> DAOS-15162 build: update to libfabric 1.22.0

utils/build.config
PR-repos: libfabric@PR-77:lastBuild mercury@PR-122:lastBuild
=> DAOS-16752 build: update mercury to 2.4.0

src/object/srv_ec_aggregate.c
Invalid hole extent might be left by process_hole_ult(), so let's skip it.
=> DAOS-16639 object: fix assertion (#15329)

src/client/api/init.c
Move daos_hhash_fini ahead of dc_pool_fini()
and dc_obj_fini(), since daos_hhash_fini()
may cause obj_free and dc_pool_fini, otherwise
it will cause segfault during daos_fini().
=> DAOS-16783 client: move daos_hhash_fini ahead

src/cart/crt_hg.c
- If failed to reply, skip rpc early buffer release
=> DAOS-16812 cart: read after free cid 2556737

docs/overview/terminology.md
=> DAOS-16757 doc: improve the documentation

.github/workflows/bullseye-coverage.yml, .github/workflows/rpm-build-and-test.yml
=> Use organizational and repository variables

.github/dependabot.yml, tmp.txt
Setup dependabot for requirements.txt.
=> DAOS-16843 cq: setup dependabot for requirements.txt

docs/admin/env_variables.md, src/pool/srv.c
Since 0 is the minimum RF, we should allow setting it to 0. We can revisit naming later.
=> DAOS-16830 pool: Allow setting DAOS_POOL_RF to 0

Jenkinsfile
Change-Id: I0b5df8b3d04c13cc7b53b5c4fa56fedd40971737
=> Do a landing build for google/2.6

.github/dependabot.yml, .github/workflows/ci2.yml, .github/workflows/landing-builds.yml, .github/workflows/linting.yml, .github/workflows/pr-metadata.yml, .github/workflows/version-checks.yml, Jenkinsfile, ci/storage/test_main_storage_prepare_node.sh, ci/unit/test_post_always.sh, docs/admin/env_variables.md, site_scons/site_tools/compiler_setup.py, src/client/dfuse/dfuse_core.c, src/client/java/daos-java/pom.xml, src/gurt/telemetry.c, src/placement/tests/benchmark_util.h, src/placement/tests/jump_map_place_obj.c, src/pool/srv.c, src/tests/ftest/scripts/main.sh, src/utils/crt_launch/crt_launch.c, utils/cq/requirements.txt, utils/node_local_test.py, utils/scripts/helpers/install_maldet.sh
* Build fixes causing failures in CI
* Moving GHA docker build to supported ubuntu version
* Fix DAOS_POOL_RF to allow 0
* Use google/2.6 as reference build for NLT
=> Backport several fixes

src/tests/ftest/checksum/csum_basic.yaml, src/tests/ftest/container/api_basic_attribute.yaml, src/tests/ftest/container/basic_snapshot.yaml, src/tests/ftest/container/boundary.yaml, src/tests/ftest/container/query_attribute.yaml, src/tests/ftest/container/snapshot.yaml, src/tests/ftest/control/dmg_system_cleanup.yaml, src/tests/ftest/dtx/basic.yaml, src/tests/ftest/erasurecode/rank_failure.yaml, src/tests/ftest/nvme/object.yaml, src/tests/ftest/object/create_many_dkeys.yaml, src/tests/ftest/object/fetch_bad_param.yaml, src/tests/ftest/object/integrity.yaml, src/tests/ftest/object/open_bad_param.yaml, src/tests/ftest/object/punch_test.yaml, src/tests/ftest/object/update_bad_param.yaml, src/tests/ftest/osa/dmg_negative_test.yaml, src/tests/ftest/pool/evict.yaml, src/tests/ftest/rebuild/basic.yaml, src/tests/ftest/rebuild/cascading_failures.yaml, src/tests/ftest/rebuild/delete_objects.yaml, src/tests/ftest/rebuild/read_array.yaml, src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml, src/tests/ftest/util/test_utils_base.py
Change the default container control_method to daos instead of API. Update configs to explicitly use API/daos to maintain existing behavior.
Features: pr container
=> DAOS-15645 test: change default cont control_method to daos

.github/workflows/bullseye-coverage.yml
Saturdays at midnight, UTC.
- Build and test skipped as this affects only GitHub Actions
=> DAOS-16262 ci: Run Bullseye workflow on schedule

.github/workflows/rpm-build-and-test.yml
For the case where daos is being used as a downstream test.
- Skipped build and test as this PR only affects GHA.
=> SRE-2171 ci: Accept and propagate a run-gha variable

src/tests/ftest/pool/permission.yaml
Add the required test yaml entry to create the contianer =via the pydaos API.
Skip-nlt: true
Test-tag: test_file_modification
=> DAOS-16870 test: Fix pool/permission test

docs/release/release_notes.md
2.6.2 release notes document
Doc-only: true
=> DAOS-9355 doc: DAOS 2.6.2 release notes

src/vos/vos_iterator.c
Reset anchors before iterating next bucket.
=> DAOS-16794 vos: reset anchors for vos_iterate_obj()

.github/CODEOWNERS, .github/dependabot.yml
=> DAOS-16871 cq: add GHA workflows to dependabot

src/tests/ftest/util/command_utils.py
Do not raise an exception if parsing empty json output.
=> DAOS-16709 test: Handle decoding empty json output (#15397)

src/tests/ftest/container/rf_enforcement.py, src/tests/ftest/control/ms_resilience.py, src/tests/ftest/io/macsio_test.py, src/tests/ftest/io/parallel_io.py, src/tests/ftest/nvme/pool_capacity.py, src/tests/ftest/pool/destroy.py, src/tests/ftest/pool/query_attribute.py, src/tests/ftest/rebuild/cascading_failures.py, src/tests/ftest/rebuild/no_cap.py, src/tests/ftest/rebuild/pool_destroy_race.py, src/tests/ftest/rebuild/read_array.py, src/tests/ftest/rebuild/with_io.py, src/tests/ftest/scrubber/aggregation.py, src/tests/ftest/scrubber/basic.py, src/tests/ftest/scrubber/csum_fault.py, src/tests/ftest/scrubber/frequency.py, src/tests/ftest/scrubber/rebuild.py, src/tests/ftest/scrubber/snapshot.py, src/tests/ftest/scrubber/target_auto_eviction.py, src/tests/ftest/server/metadata.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/osa_utils.py, src/tests/ftest/util/rebuild_test_base.py, src/tests/ftest/util/scrubber_test_base.py, src/tests/ftest/util/test_utils_container.py, src/tests/ftest/util/vol_test_base.py
Features: ContRfEnforce DestroyTests ListPoolsTest MacsioTest ManagementServiceResilience NvmePoolCapacity ObjectMetadata ParallelIo QueryAttributeTest RbldCascadingFailures RbldNoCapacity RbldPoolDestroyWithIO RbldReadArrayTest RbldWithIO TestScrubberEvictWithAggregation TestScrubberEvictWithRebuild TestScrubberEvictWithSnapshot TestWithScrubberBasic TestWithScrubberFault TestWithScrubberFreq TestWithScrubberTargetEviction scrubber DmvrDstCreate DmvrObjSmallTest DmvrPreserveProps RbldDeleteObjects DaosVolBigIO DaosVol osa
=> DAOS-12859 test: use pool and container labels (pass 3) (#13210)

.github/workflows/linting.yml, utils/cq/check_update_copyright.sh
Use github.event.pull_request.base.sha || github.ref in case it is not a PR.
Also add existence check for the new utility in case it does not exist on the PR yet.
=> DAOS-15677 cq: fix copyright GHA for landing run

.github/workflows/rpm-build-and-test.yml
- Only running minimal passing test suite and skipping hardware testing as none of that is needed to validate this fix.
=> SRE-2171 ci: Test inputs context before trying to use it

src/tests/suite/daos_cr.c
Test-tag: test_daos_cat_recov_core
=> DAOS-16802 tests: properly set fault_injection for CR test

src/cart/crt_hg.c
- If failed to reply, skip rpc early buffer release
=> DAOS-16812 cart: read after free cid 2556737 (#15517)

utils/githooks/pre-commit.d/71-flake.sh
Use -r so if no scons or non-scons files are grep'ed, flake8 does not run.
=> DAOS-16875 cq: fix flake8 xargs usage

utils/githooks/pre-commit.d/71-flake.sh
Use -r so if no scons or non-scons files are grep'ed, flake8 does not run.
=> DAOS-16875 cq: fix flake8 xargs usage (#15608)

src/client/java/daos-java/pom.xml
Update netty-buffer to 4.1.115
=> DAOS-16880 client: Address java security scan (#15542)

.github/workflows/ci2.yml, .github/workflows/landing-builds.yml, .github/workflows/linting.yml, .github/workflows/pr-metadata.yml, .github/workflows/version-checks.yml, ci/storage/test_main_storage_prepare_node.sh, ci/unit/test_post_always.sh, src/tests/ftest/scripts/main.sh, utils/scripts/helpers/install_maldet.sh
Update mantic (EOL) to oracular.
Update 22.04 LTS to 24.04 LTS.
Test-tag: pr,vm,-daos_test
=> DAOS-16833 cq: update GHA ubuntu (#15538)

src/control/SConscript
Add a requirement to protobufc for building daos control binaries.
=> DAOS-16889 build: fix finding protobuf (#15625)

src/bio/bio_buffer.c, utils/cq/check_update_copyright.sh
Add a new HPE copyright line for modified files.
Update HPE copyright instead of Intel
=> DAOS-16917 cq: update copyright for HPE

Jenkinsfile
Run functional VM tests on Leap 15.6.
=> DAOS-16500 test: Move to Leap 15.6

Jenkinsfile, ci/parse_ci_envs.sh, utils/rpms/daos.rpmlintrc, utils/rpms/daos.spec, utils/rpms/packaging/Makefile_distro_vars.mk, utils/scripts/helpers/repo-helper-leap15.sh
Test with Leap 15.6 instead of Leap 15.5.
To support building Leap 15.5 DAOS RPMs and testing them on Leap 15.6 the Functional on Leap 15.6 stage needs to explicitly specify the Leap 15.6 image for node provisioning.
Combination of #15561, #15684
Test-tag: always_passes test_cart_corpc_one_node test_dfuse_daos_build_wt_il
=> DAOS-16500 build: Move to Leap 15.6 (#15561)

Jenkinsfile
To support building Leap 15.5 DAOS RPMs and testing them on Leap 15.6 the Functional on Leap 15.6 stage needs to explicitly specify the Leap 15.6 image for node provisioning.
Skip-func-test-el8: true
Test-tag: always_passes test_cart_corpc_one_node
=> DAOS-16500 test: Update Functional on Leap 15.6 stage

src/engine/server_iv.c, src/vos/vos_dtx.c
- Rate limit on IV_OID busy message.
- Don't print warning message in vos_dtx_check_availability() for fresh record.
=> DAOS-16918 vos: suppress two log messages

utils/cq/check_update_copyright.sh
Add a new HPE copyright line for modified files.
Update HPE copyright instead of Intel.
=> DAOS-16917 cq: update copyright for HPE (#15678)

docs/admin/env_variables.md, src/pool/srv.c
Since 0 is the minimum RF, we should allow setting it to 0. We can revisit naming later.
=> DAOS-16830 pool: Allow setting DAOS_POOL_RF to 0 (#15564)

utils/cq/check_update_copyright.sh
=> DAOS-623 ci: Add copyright for Google

src/cart/utils/memcheck-cart.supp
Suppress another false positive originating from the Go race detection code.
=> DAOS-16925 cart: Add memcheck suppression for tsan::MemoryAccessRange

utils/githooks/commit-msg
Change-Id: Idf421edda1391b98ab063e63d923a014c95d702c
=> Add back commit-msg githook

Jenkinsfile, site_scons/prereq_tools/base.py
Sometimes these tests get scheduled on Broadwell VMs and they are slow Fix isort complaint
Change-Id: I68347c677cb9ccd50b0e3f4df5f16902cca54c5b
=> DAOS-623 ci: Update time for bdev memcheck tests

src/container/srv_target.c, src/include/daos_srv/container.h
Check inflight container open, which might be stucked in IV fetch, then the following cont open will just increase the open count, then if the previous container open failed, it will get the assertion failure.
So let's retry if there are inflight container open.
=> DAOS-16916 container: check inflight open (#15682)

utils/build.config
We are using v1.0.0 for rpm, just sync the build.config. There is no functional difference here between them.
=> DAOS-623 build: Update developer package for fused

src/cart/crt_hg.c, src/control/server/engine/utils.go, src/include/cart/api.h, src/mgmt/srv_drpc.c, src/mgmt/tests/mocks.c
This reverts commit d595e30d26d580fae34e2c063ae8b3bfeb3f1cb8.
=> Revert "b/390177544 cart: Support dynamic mercury/libfabric loglevels (#15738)"

utils/cq/words.dict
Used in copyright so avoid flagging spelling error
=> DAOS-623 ci: Add LLC to ignore list

src/engine/server_iv.c, src/vos/vos_dtx.c
- Rate limit on IV_OID busy message.
- Don't print warning message in vos_dtx_check_availability() for fresh record.
=> DAOS-16918 vos: suppress two log messages (#15679)

src/container/srv_target.c, src/dtx/dtx_common.c, src/include/daos_srv/container.h
Serialize container open by ABT mutex.
Remove incorrect sc_open assertion, which might be faulty if iv fetch is failed and following container open tried again.
Run-GHA: true
=> DAOS-16916 container: serialize container open

src/container/oid_iv.c
=> DAOS-16931 iv: fix the copyright from previous PR

utils/build.config, utils/ofi_debug_ip.patch
Add extra debug information for exporting source
IP address when failures happens for TCP provider.
Run-GHA: true
=> DAOS-16971 utils: add OFI TCP debug patch

docs/user/pytorch.md, mkdocs.yml, requirements-ftest.txt, src/client/pydaos/torch/Readme.md, src/client/pydaos/torch/__init__.py, src/client/pydaos/torch/torch_api.py, src/client/pydaos/torch/torch_shim.c, src/tests/ftest/SConscript, src/tests/ftest/directory_tree.py, src/tests/ftest/pytorch/checkpoint.py, src/tests/ftest/pytorch/checkpoint.yaml, src/tests/ftest/pytorch/dataset.py, src/tests/ftest/pytorch/dataset.yaml, src/tests/ftest/util/io_utilities.py, utils/cq/check_update_copyright.sh, utils/cq/words.dict, utils/node_local_test.py
Introducing PyTorch checkpoint interface and user documentation for pydaos.torch module.
Change-Id: Id960646f40c083a51c0ed939de78bea2f88888ba
Signed-off-by: Denis Barakhtanov <dbarahtanov@enakta.com>
Co-authored-by: Dalton Bohning <dalton.bohning@hpe.com>
=> DAOS-16362 pydaos: pydaos.torch checkpointing (#15691)

utils/build.config
=> DAOS-16257 mercury: Update build.config to include ep flush patch.

SConstruct, site_scons/prereq_tools/base.py, utils/ci/run_in_gha.sh
Adds --skip-download option to allow one to use already download sources for prerequisites. Removes --build-deps=build-only as it can be replaced with --build-deps=only --skip-download Adds --build-deps=fetch which just downloads sources and exits. A few minor cleanup changes.
Change-Id: I5766ecf5377990bcf636ec4146ba0e87ae23f36e
=> DAOS-11866 build: Add --build-deps=fetch option (#14125)

src/container/srv_container.c
Use ABT thread instead of ABT task for cont_refresh_track_eph_one(), since local tx is used in the function which yield in md-on-ssd mode.
=> DAOS-17003 container: use thread instead of task

src/tests/ftest/server/metadata.py, src/tests/ftest/server/metadata.yaml, src/tests/ftest/util/command_utils.py
Remove the calling of cleanup methods for multiple containers and ior commands that can be handled by destroying the pool and a single ior kill command.
Test-tag: ObjectMetadata
=> DAOS-16969 test: Reduce cleanup operations for metadata.py test

src/client/dfuse/ops/read.c
Fix incorrect sema post, which is only needed if dfs api is being called.
Run-GHA: true
=> DAOS-16686 dfuse: fix incorrect sema post

.github/dependabot.yml
Enable Dependabot scans for release 2.6 branch.
An example of how it works:
https://github.com/grom72/daos/pull/78
=> DAOS-623 ci: enable dependabot for GHA on branch 2.6

.github/dependabot.yml
Ignore avocado updates since more work is required to support it.
=> DAOS-17090 cq: dependabot ignore avocado

src/cart/README.env, src/cart/crt_hg.c, src/cart/crt_init.c, src/cart/crt_internal_types.h, src/include/cart/types.h
This allows to initialize CART in busy wait mode
=> DAOS-17000 cart: add cio_progress_busy cart init option

site_scons/prereq_tools/base.py
When a component has a required program, the exception can give more information.
Change-Id: If0df705db29aa7425039093735205a27cf398c07
=> DAOS-623 build: Improve error message

ci/jira_query.py, utils/build.config, utils/ofi_retry_failure.patch
Add OFI patch to avoid ep being disabled by unnecessary failures.
=> DAOS-16686 ofi: add ofi retry failure patch

utils/trivy/.trivyignore
Suppress io.netty:netty-common 4.1.115.Final CVE - no fix available 
Suppress io.netty:netty-handler 4.1.100.Final CVE - fix available in 4.1.118.Final
Doc-only: true
Backport of #15889
=> DAOS-17108 common: suppress io.netty 4.1.115 CVE (#15889)

src/vos/vos_obj_cache.c
=> DAOS-16408 coverity: 2555831 Unused value

src/tests/ftest/telemetry/wal_metrics.py
Bump checkpoint valid duration from 2 secs to 4 secs.
=> DAOS-16813 test: bump checkpoint duraion

src/tests/ftest/nvme/enospace.yaml
Increase the minimal SCM usage to take into account that data are not fully distributed across the engines.
=> DAOS-16733 test: Fix enospace.py ftest limits

src/cart/swim/swim.c
Skip swim updates from nodes that already marked as dead because it may include inaccurate info.
Change-Id: Ic38bca247a3a654d911686dbef09478680ed2ddc
=> DAOS-17111 swim: do not trust dead node

src/cart/utils/memcheck-cart.supp
Add memcheck suppressions for false positives in Go runtime functions in the internal/bytealg package.
=> DAOS-16578,17016 utils: Add NLT memcheck suppressions for Go runtime

src/bio/bio_recovery.c
When teardown a faulty device, ensure the inflight health collecting NVMe command completed before putting the io channel & open descriptor for health monitor.
=> DAOS-17045 bio: drain inflight health collecting on teardown (#15884)

.github/workflows/linting.yml, pyproject.toml, utils/githooks/pre-commit.d/20-codespell.sh
Skip *.patch files (we have none in master branch) Skip same files in githook we do in CI
Change-Id: I8de37f3840093d23206691a7ca444f008fcfdea6
=> DAOS-17133 ci: Add to codespell skip list

src/cart/crt_group.c, src/cart/crt_group.h, src/cart/crt_rpc.c, src/cart/utils/crt_utils.c, src/include/cart/api.h, src/tests/ftest/cart/no_pmix_launcher_client.c, src/tests/ftest/cart/rpc_test_common.h, src/utils/self_test/self_test_lib.c
- Remove PSR-related code, as it is only used by cart tests and samples
=> DAOS-17114 cart: remove psr stuff

src/pool/srv_pool.c
Currently, we do not support jumping version upgrades for the pool. Moreover, our interoperability tests have never included such scenarios. For safety reasons, we should reject any requests for jumping version upgrades.
=> DAOS-17121 pool: reject jumping pool upgrade

src/utils/ddb/ddb_common.h
=> DAOS-623 ddb: Add line numbers to error prints

src/cart/utils/memcheck-cart.supp
=> DAOS-17141 mercury: valgrind suppression for mercury errors

ci/provisioning/post_provision_config_common_functions.sh
Not sure if this is from bad merge or not but it's causing warnings on PRs
Change-Id: I25be061f7b4685078b22feb8886b5449991e00de
=> DAOS-623 ci: Remove unused function

src/placement/tests/jump_map_place_obj.c, src/pool/srv_pool.c, src/pool/srv_pool_map.c, src/pool/srv_pool_map.h
No logic changes; just adding pool UUID and pool map address to pool map change logging, and logging important messages to both stdout and log.
=> DAOS-16902 pool: Polish map change logging (#15744)

src/cart/swim/swim.c
Skip swim updates from nodes that already marked as dead because it may include inaccurate info.
Change-Id: Ic38bca247a3a654d911686dbef09478680ed2ddc
=> DAOS-17111 swim: do not trust dead node (#15894)

src/cart/crt_hg.c, src/cart/crt_init.c, src/client/api/event.c, src/client/api/init.c, src/client/api/tests/eq_tests.c, src/common/misc.c, src/engine/init.c, src/include/daos/common.h
Only enable HG metrics if it's the server or client side metrics are enabled.
Change-Id: I07d445cb9713ae023853fa6bc5722e74b037508c
=> DAOS-17006 cart: Check use_sensors flag

src/cart/crt_context.c, src/cart/crt_hg.c, src/cart/crt_hg_proc.c, src/cart/crt_internal.h, src/cart/crt_register.c, src/cart/crt_rpc.c
lower error messages to warn level
backport master PR: #15529
Change-Id: I71966a235c068abbd3c74c422458a68e3a86154a
Signed-off-by: Jinshan Xiong <jinshanx@google.com>
=> DAOS-16824 cart: lower error messages to warn level (#15529)

src/client/pydaos/raw/daos_api.py
Conditionally depend on libtest in pydaos.raw instead of being a hard requirement.
Test-tag: ObjectDataValidation ObjFetchBadParam DaosObjectQuery CsumContainerValidation ObjOpenBadParam DkeyAkeyEnumPunch DmvrSerialSmall DmvrObjSmallTest
=> DAOS-17160 test: conditionally depend on libtest

.github/CODEOWNERS
pydaos/raw is client code but only used by ftest.
=> DAOS-623 cq: CODEOWNERS put pydaos/raw under ftest owners

site_scons/components/__init__.py
Change-Id: I36c5c33653a049969bbb087629d042684307f5c7
=> b/400469211 build: copy SPDK blobcli for debugging

src/engine/init.c, utils/build.config
Print each dump to a new file
Fix a bug in argobots preventing multiple dumps
Change-Id: I1c41aced134cae3966caf0dff7e28673c0e7fad7
=> DAOS-17206 engine: Improve stack trace logic

src/bio/bio_internal.h, src/cart/README.env, src/cart/crt_bulk.c, src/cart/crt_context.c, src/cart/crt_hg.c, src/cart/crt_hg.h, src/cart/crt_hg_proc.c, src/cart/crt_init.c, src/cart/crt_internal_fns.h, src/cart/crt_internal_types.h, src/cart/crt_rpc.h, src/include/cart/types.h, src/utils/self_test/self_test_lib.c
=> DAOS-17178 cart: Implement D_QUOTA_BULKS

src/bio/bio_monitor.c, src/bio/bio_recovery.c, src/dtx/dtx_coll.c, src/dtx/dtx_internal.h, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c, src/include/daos/dtx.h, src/include/daos_srv/dtx_srv.h, src/object/obj_rpc.c, src/object/srv_coll.c, src/pool/srv_pool.c, utils/cq/check_update_copyright.sh, utils/githooks/find_base.sh, utils/githooks/git-version.sh, utils/githooks/hook_base.sh, utils/githooks/pre-commit, utils/githooks/pre-commit.d/10-update-copyright.sh, utils/githooks/pre-commit.d/20-codespell.sh, utils/githooks/pre-commit.d/40-yamllint.sh, utils/githooks/pre-commit.d/50-clang-format.sh, utils/githooks/pre-commit.d/60-gofmt.sh, utils/githooks/pre-commit.d/70-isort.sh, utils/githooks/pre-commit.d/71-flake.sh, utils/githooks/pre-commit.d/72-pylint.sh, utils/githooks/pre-commit.d/73-ftest.sh, utils/githooks/prepare-commit-msg, utils/rpms/packaging/get_release_branch
- **DAOS-16898 cq: support user bash in githooks (#15648) (#15892)**
- **DAOS-16936 dtx: rank range based DTX hints for coll_punch - b26 (#15975)**
- **DAOS-17271 pool: Fix handle_event -DER_NONEXISTs (#16081) (#16090)**
- **DAOS-17282 bio: clear io contexts for unplugged faulty device (#16097)**
=> Merge release/2.6 into google/2.6

src/tests/ftest/util/systemctl_utils.py
With DAOS-7809 resolved, revert a workaround that increased the number of maximum retries.  Also make this an option for any future implementations.
=> DAOS-17304 test: Restore stop_service max loops

src/cart/utils/memcheck-cart.supp
Suppress another intermittent false positive related to Go runtime.
=> DAOS-17331 cart: Suppress memcheck on __tsan_go_atomic64_fetch_add

docs/release/release_notes.md
2.6.3 release notes
Doc-only: true
=> DAOS-17337 doc: 2.6.3 release notes

docs/release/support_matrix.md
2.6.3 support matrix
Doc-only: true
=> DAOS-17337 doc: 2.6.3 support matrix

.github/workflows/bullseye-coverage.yml, .github/workflows/ci2.yml, .github/workflows/landing-builds.yml, .github/workflows/rpm-build-and-test.yml, .github/workflows/unit-testing.yml, site_scons/components/__init__.py, site_scons/prereq_tools/base.py, utils/rpms/Makefile, utils/rpms/create_tar.sh, utils/rpms/resolve_patches.sh
Add CopyRetriever as alternative to GitRepoRetriever.  Use it for submodule option at first.
Add support for internal, static library
Add patch support to rpm source rpm
See PR#16134 for example
Change-Id: I6f97606617ad91998956c39ae7abee4c57a4741a
=> DAOS-17344 build: Enhance SCons options

src/cart/utils/memcheck-cart.supp
This PR includes a set of cherry-picked NLT suppressions that are present in master.
This set of commits should be landed as-is, rather than squashed.
=> DAOS-16925,16578,17016,17149,17331 cart: Suppress NLT Go valgrind errors

utils/build.config, utils/na_tag_rpc_fix.patch, utils/ofi_tag_rpc_fix.patch
This PR discards unexpected tagged messages for both passive and active endpoints.
Change-Id: I55cbf64226a7f1ebac39e63af6b9dd45facb71b9
=> b/405431459: discard unexp tagged message

utils/rpms/archive.sh
The name modification needs to be in submodule loop
Change-Id: I62f64f3d7c2bd8ea0a316e3acdfc8d51db8fb497
=> Pull in change from master branch

.github/workflows/bash_unit_testing.yml, .github/workflows/bullseye-coverage.yml, .github/workflows/ci2.yml, .github/workflows/landing-builds.yml, .github/workflows/linting.yml, .github/workflows/rpm-build-and-test.yml, .github/workflows/unit-testing.yml
So previous runs are cancelled on new pushes.
=> DAOS-17406 cq: use cancel-in-progress for more workflows

Jenkinsfile, ci/functional/launchable_analysis, ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_nodes.sh, ci/unit/test_nlt.sh, ci/unit/test_nlt_node.sh, ftest.sh, utils/githooks/pre-commit.d/30-Jenkinsfile.sh, utils/node_local_test.py
Set of changes required for FC Lab to enable RPM build, Unit Tests and Functional tests
All changes shall be harmless for RR Lab
Backport of #16139:
=> SRE-2832 build: unblock Build, Unit tests, Functional test (EL8) stages in FC Lab (#16139)

docs/admin/pool_operations.md
Add a section on how to rename a pool.
Improve the pool creation text.
Fix several markdown mistakes.
=> DAOS-10039 doc: add pool rename and improve pool creation

utils/githooks/prepare-commit-msg.d/10-submodule-update-check.py
Re-write the check so it does not re-run the same subprocess commands.
=> DAOS-17461 cq: speedup githook submodule check

src/include/daos_obj.h
=> DAOS-623 doc: fix comment in header about enumeration type

docs/admin/administration.md, docs/admin/pool_operations.md
Address review comments on PR-16261
Doc-only: true
=> DAOS-15947 docs: Update admin guide dmg pool command advice

Jenkinsfile
Explicitly set 'scm:' argument for recordIssues.
Skip-fault-injection-test: false
=> SRE-3035 ci: Set scm param for recordIssues (#16437)

Jenkinsfile, ci/rpm/gen_rpms.sh, utils/rpms/daos.sh, utils/rpms/fpm_common.sh, utils/scripts/install-el9.sh, utils/scripts/install-leap15.sh
=> Add another test

docs/admin/administration.md, src/control/system/raft/database_test.go
Add documentation on how to add or remove MS replicas.
Also remove unused variable in a unit test.
=> DAOS-17835 doc: Document how to add/remove MS replica (#16651)

.github/actions/make_release/entrypoint.sh, .github/workflows/create_release.yml
Give create_release.yml write permission so it can create tags. Also exit on error.
Doc-only: true
=> DAOS-17877 cq: give create_release.yml write permission (#16708)

src/tests/ftest/rebuild/basic.py, src/tests/ftest/rebuild/basic.yaml
Combine all the variants into one complete variant. This is closer to production and is more efficient.
=> DAOS-17890 test: condense rebuild/basic.py

Jenkinsfile, ci/rpm/build_success.sh, ci/rpm/gen_rpms.sh
Change-Id: If3673b6b164c08e91c7d5760acfbc5eb5e8cd08f
=> Test alternative pipeline-lib

.github/workflows/ci2.yml, .github/workflows/landing-builds.yml
Downgrade oracular (EOL) to Noble.
Only used in GHA.
Doc-only: true
=> DAOS-17982 cq: update GHA ubuntu to Noble

Jenkinsfile
Update the skip build commit pragma and build parameters to reflect the recent changes to the build stages.
Test-tag: test_setup_vm
=> DAOS-17981 build: Fix CI_BUILD_PACKAGES_ONLY use

src/tests/ftest/util/collection_utils.py
=> Revert "SRE-3150 test: Fix running server storage verification"
