src/mgmt/srv_query.c

When attempting to free string memory in LedManage dRPC handler,
D_FREE is finding non-null pointers and attempting to free when no
memory has been allocated. This is due to the protobuf init functions
setting string values non-null. Solve by resetting string values to
NULL after controller message structure is initialized.
Skip-func-hw-medium-md-on-ssd: false
Skip-func-hw-medium-verbs-provider-md-on-ssd: false
Test-tag: VmdLedStatus,test_disk_failure_recover

DAOS-14801 mgmt: Fix LedManage dRPC handler response cleanup

---

src/container/srv_target.c
src/pool/srv_target.c
src/vea/vea_free.c

Two fixes to accelerate space reclaiming under space pressure:
- Make VOS aggregation & GC run in tight mode when the pool is under
space pressure, no matter if the system is busy or not.
- Bump the max number of reclaimed bitmap chunks from 10 to 256 for
single VEA flush.

DAOS-14838 gc: run in tight mode under space pressure

---

src/client/dfuse/il/int_posix.c

Fix an issue where all errors would be mapped to 1 (EPERM)

DAOS-14805 dfuse: Correctly propagate errors in ioil.

---

.github/workflows/pylint.yml
src/tests/ftest/control/config_generate_run.py
src/tests/ftest/dfuse/simul.py
src/tests/ftest/slurm_setup.py
src/tests/ftest/util/apricot/apricot/test.py
src/tests/ftest/util/apricot/setup.py
src/tests/ftest/util/io_utilities.py
src/tests/ftest/util/server_utils.py
src/tests/ftest/util/server_utils_base.py
utils/cq/daos_pylint.py
utils/cq/words.dict

Our CI systems run diffferent distros so fix spelling issues reported
by the el8.8 upgrade for developers.

DAOS-14839 cq: Update pylint check to 3.11 and fix issues.

---

src/object/srv_obj_migrate.c
src/tests/suite/daos_rebuild_ec.c

During migration, it should choose the minimum epoch from rebuild stable epoch and EC aggregation boundary to make sure correct data is being fetched during recovery.
Add tests to verify the process.

DAOS-14352 object: recover migrate with correct epoch

---

src/vos/vos_dtx.c

In vos, when the modification hit failure, it may firstly reset related dth->dth_active and dht->dth_ent before returning to upper layer caller. And then, the caller will further handle the failure, such as abort the transaction or retry after DTX refresh. If it is not the DTX leader, it needs to cleanup related DTX entry via invoking vos_dtx_cleanup(). Such cleanup logic may be misguided by the "dth_active" and "dth_ent", as to leak the active DTX entry in DRAM. If no further DTX abort from related (dead) DTX leader, the stale DXT entry will block subsequent resent RPC with the same transaction ID.
This patch makes vos_dtx_cleanup() to check related DTX entry existence by force to cleanup.

DAOS-14671 vos: cleanup active DTX entry by force

---

src/object/obj_tx.c
src/pool/cli.c

The map_refresh and map_refresh_cb functions access the pool variable after reinitializing the task. Since the dc_pool reference is stored in the task object, it may be released by the new incarnation of the task before being accessed by the current incarnation. This patch addresses the problem by getting an extra dc_pool reference for the pool variable.
The dc_tx_restart function sets the internal private data of the task after reinitialing the task. This causes a data race because the current thread may write the internal private data while another reads the data.

DAOS-14788 pool: Fix some reinit usages

---

src/tests/ftest/nvme/fragmentation.py
src/tests/ftest/nvme/pool_capacity.py
src/tests/ftest/nvme/pool_exclude.py
src/tests/ftest/nvme/pool_extend.py
src/tests/ftest/osa/offline_drain.py
src/tests/ftest/osa/offline_reintegration.py
src/tests/ftest/osa/online_drain.py
src/tests/ftest/osa/online_extend.py
src/tests/ftest/osa/online_parallel_test.py
src/tests/ftest/osa/online_reintegration.py
src/tests/ftest/util/write_host_file.py

Test-tag: cart,vm SegCount NvmeFragmentation NvmePoolCapacity NvmePoolExclude NvmePoolExtend OSAOfflineDrain OSAOfflineReintegration OSAOnlineDrain OSAOnlineExtend OSAOnlineParallelTest OSAOnlineReintegration datamover pr,vm
- Do not log a DEBUG line for each host because it's too verbose
- Make slots None by default. It's infrequently used
- Use mkstemp instead of random, which is racy

DAOS-14735 test: simplify write_hostfile

---

src/tests/ftest/util/dmg_utils.py
src/tests/ftest/util/pool_create_all_base.py

Fix ftest key lookups for dev_state during storage query usage
which were broken in commit https://github.com/daos-stack/daos/commit/8e1c8468428e7b2ac97975300e18d0aaff8e381c.
Test-tag: pool,pool_create_all

DAOS-14852 test: Fix JSON key lookup in NVMe space usage query

---

.github/workflows/rpm-build-and-test.yml
ci/functional/test_main.sh

The supported distro versions got missed in 56e3228d36 for the GitHub
Actions workflow.
* Abbreviated the hardware testing as only a single hardware test run is sufficient to prove the change.

DAOS-14440 build: Update distro versions in GHA

---

src/tests/ftest/ior/hard_rebuild.yaml

Test-tag: EcodIorHardRebuild
Test-repeat: 3
Skip-func-test-hw-large-md-on-ssd: False
- Use both SCM and NVMe when creating a pool to accomodate MD on SSD.
- Use GX so space is spread across targets.

DAOS-14831 test: use scm and nvme for ior/hard_rebuild 

---

src/tests/ftest/control/config_generate_run.yaml
src/tests/ftest/util/command_utils_base.py
src/tests/ftest/util/environment_utils.py

The ConfigGenerateRun tests fail to use certs because insecure mode is
enabled when trying to access non-existent DAOS_INSECURE_MODE env. Fix
by updating env keyname to DAOS_TEST_INSECURE_MODE.

DAOS-14718 test: Fix reading of DAOS_TEST_INSECURE_MODE envar (#13441)

---

src/tests/ftest/erasurecode/multiple_failure.yaml

original set 1 cannot work if the killed rank happened to be the only server replica.
Test-tag: ec_multiple_failure

DAOS-13252 tests: set svcn for multiple_failure test

---

src/gurt/misc.c
src/include/gurt/common.h

Restore missing plain function d_getenv_int() to fix missing symbol with libdaos.

DAOS-14981 gurt: restore d_getenv_int undefined symbol

---

src/pool/srv_internal.h
src/pool/srv_iv.c
src/pool/srv_pool.c

Set the pool server handler before IV update, to make sure IV server checking accurate on the PS leader once step up finish.

DAOS-14884 pool: set the pool server handle before update

---

Jenkinsfile

With a recent change to support multiple UCX providers the default --nvme argument for launch.py was unintentionally removed. This adds the default back in.
Test-tag: test_daos_management

DAOS-14886 test: Add default nvme arg for UCX provider stage

---

src/cart/crt_iv.c
src/container/oid_iv.c
src/engine/server_iv.c

OID IV entry lock might be required again for retry case.
Test-tag: test_daos_oid_allocator test_daos_management

DAOS-14969 container: retry IV might cause deadlock

---

src/tests/suite/daos_md_replication.c

Cherry-pick master commit a81c0b2 to release/2.4 branch
Test-tag: test_daos_md_replication
Test-repeat: 20

DAOS-13584 tests: limit pool query test time (#12451)

---

src/control/cmd/daos/filesystem.go

The dfs fs check command already allows evicting containers using the --flags=evict option. the --evict option was added by mistake and does not do anything today, so remove it.

DAOS-14474 dfs: remove unused --evict option from checker

---

src/rdb/rdb.c
src/rdb/rdb_raft.c

The recent unplanned raft update has introduced a new raft error,
RAFT_ERR_MIGHT_VIOLATE_LEASE, which is mapped to the default -DER_MISC.
This patch maps the new raft error to the slightly more meaningful
-DER_NO_PERM, to complete the raft update.

DAOS-14443 rdb: Improve rdb_campaign error

---

src/client/dfs/dfs.c
src/client/dfs/duns.c
src/tests/suite/dfs_unit_test.c
utils/node_local_test.py

- In order to avoid stale root stat data, update the root stbuf on lookup.
- add mtime/ctime proper querying for dfs_lookup()

DAOS-14476 dfs: update root stbuf on lookup of root

---

src/client/dfs/dfs.c
src/tests/suite/dfs_unit_test.c

- in dfs_osetattr(), if user sets both mtime and size, the hlc for the mtime is not being update on storage. To fix that, use the hlc reported from the array_stat and update that when updating the mtime in the entry.

DAOS-15049 dfs: fix bug in setattr when mtime and size are being set

---

src/object/srv_ec_aggregate.c

Possibly one target failed but the rank is fine that should not affect other good targets.

DAOS-14903 object: fix bug in agg peer status check

---

src/tests/suite/daos_base_tx.c
src/tests/suite/daos_verify_consistency.c

1. Wait non-replied RPC before cleanup.
2. Use rebuild_sub_teardown to cleanup when rebuild is involved.
3. Properly inject fail_loc for object consistency verification.

DAOS-14725 tests: avoid DER_EBUSY when test teardown

---

src/object/cli_obj.c

Before resending the collective punch RPC, we need to check whether the original leader shard is valid or not. It is possible the object layout has been shrinked after rebuild. Under such case, select a new shard as the collective punch leader.

DAOS-14976 object: properly select collective punch leader for resend

---

src/tests/ftest/server/metadata.py
src/tests/ftest/server/metadata.yaml

Change the server/metdata.py tests to expect, for a pool rdb capacity of 128 MiB, out of space errors just before creating a maxiimum of about 7500 containers (increasing from the prior value 3500).
Test-tag: server,metadata
Test-repeat: 5

DAOS-14781 test: expect more containers before rdb nospace

---

src/control/SConscript
src/control/build/string.go
src/control/build/variables.go

Include build timestamp in all builds. Only
include build host in non-release builds.
Change-Id: I2d5525c21da2537a9583e9dbd57265e34639913f

DAOS-15055 tools: Add build host/time to JSON version

---

src/tests/ftest/deployment/ior_per_rank.py
src/tests/ftest/deployment/ior_per_rank.yaml

- Only run with transfer size 1M
- Reduce stonewall to 15s

DAOS-14654 test: simplify ior_per_rank.py (#13346)

---

docs/admin/administration.md
src/bio/README.md
src/bio/bio_config.c
src/bio/bio_internal.h
src/bio/bio_xstream.c
src/control/server/config/server_test.go
src/control/server/engine/config.go
src/control/server/storage/bdev.go
src/control/server/storage/bdev/backend_class_test.go
src/control/server/storage/bdev/backend_json.go
src/control/server/storage/bdev/backend_json_test.go
src/control/server/storage/config.go
src/control/server/storage/provider.go
src/control/server/storage/provider_test.go
src/include/daos_srv/control.h
utils/config/daos_server.yml

SSD auto faulty is enabled by default and criteria set  through
environment variables. Make criteria settable through the server
configuration file instead of environment variables. bdev_auto_faulty
parameter can be used to set enable, max_io_errs and max_csum_errs.

DAOS-14442 control: Make NVMe auto-faulty configurable

---

src/container/srv_container.c

1.The OIT OID KVS will be only created if the pool global version is greater than or equal to 2. Otherwise, pool upgrade will fail with EEXIST. (Thanks Li Wei's pointing this out)
2. To walk around the upgrade failure, the upgrade process will skip the creation of OIT OID KVS if it already exists.
3. When destroying a container, if the OIT OID KVS doesn't exist, it will be skipped for destruction.

DAOS-14799 container: interoperability fix for OIT OID KVS

---

src/bio/bio_device.c
src/control/common/proto/ctl/addons.go
src/control/server/ctl_smd_rpc_test.go
src/control/server/instance_storage_rpc.go
src/control/server/instance_storage_rpc_test.go
src/mgmt/srv_drpc.c
src/mgmt/srv_query.c

dmg storage query list-devices fails if run after a NVMe device is
unplugged during a physical hot-remove. The failure is due to
UNPLUGGED NVMe device state resulting in a SMD object not being
populated with a NVMe controller reference. Unplugged devices should
be reported in list-devices and ignored in storage scan so handle
UNPLUGGED device state without returning an error.
Features: control nvme

DAOS-14985 bio: Handle NVMe unplugged in list devs

---

src/tests/ftest/ior/hard_rebuild.yaml

Test-tag: EcodIorHardRebuild
Test-repeat: 3
Skip-func-test-hw-large-md-on-ssd: False
- Use both SCM and NVMe when creating a pool to accomodate MD on SSD.
- Use GX so space is spread across targets.

DAOS-14831 test: use scm and nvme for ior/hard_rebuild (#13551)

---

src/control/cmd/daos_server/start.go
src/control/server/config/server.go
src/control/server/server.go

Add daos_server start --auto-format option to enable engines to start without having to trigger a storage format with an externally executed dmg storage format command. If the flag is detected the server will call the format API during its start-up routine and if the server config file used is valid the engines will be started after format completes.

DAOS-12425 control: Add opt to auto-format on server start-up (#13074)

---

src/tests/ftest/performance/ior_easy.py
src/tests/ftest/performance/mdtest_easy.py
src/tests/ftest/rebuild/widely_striped.py
src/tests/ftest/scrubber/check_csum_metrics_mdtest.py
src/tests/ftest/util/mdtest_test_base.py
src/tests/ftest/util/performance_test_base.py

Test-tag: performance,-manual mdtest LargeFileCount SmallFileCount
Don't run ior and mdtest in a subprocess since it isn't needed. The variants that needed this aren't ran and need to be reworked in a new context.

DAOS-14103 test: remove performance_test_base subprocess

---

src/tests/ftest/launch.py

Exit as early as possible if extra yaml is not a file.

DAOS-15031 test: launch.py: exit early if extra yaml is not a file

---

src/client/dfs/dfs.c
src/client/dfs/duns.c
src/control/cmd/daos/filesystem.go
src/tests/suite/dfs_unit_test.c
utils/node_local_test.py

DAOS-14474,14219,14476,15049 dfs: dfs bug fixes

---

src/bio/bio_context.c
src/bio/bio_internal.h
src/bio/bio_recovery.c

When a normal device is hot removed before being marked as faulty, the faulty reaction won't be performed, so that we need to close opened blobs when teardown the device, at the same time, the closed blobs need be opened on setup when the normal device is plugged back (in which case reint won't be triggered).

DAOS-15041 bio: handle normal device hot remove

---

utils/node_local_test.py

Have the fault injection test play nicely with the CI system by
decreasing the level of concurrency when the system is loaded.

DAOS-14164 test: Have fault injection test slow down on loaded systems.

---

src/tests/ftest/container/rf_enforcement.py
src/tests/ftest/deployment/server_rank_failure.yaml
src/tests/ftest/erasurecode/multiple_failure.yaml
src/tests/ftest/erasurecode/offline_rebuild.yaml
src/tests/ftest/erasurecode/offline_rebuild_single.yaml
src/tests/ftest/erasurecode/online_rebuild.yaml
src/tests/ftest/erasurecode/online_rebuild_single.yaml
src/tests/ftest/erasurecode/rebuild_disabled.yaml
src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
src/tests/ftest/rebuild/cascading_failures.yaml
src/tests/ftest/rebuild/container_rf.py
src/tests/ftest/rebuild/container_rf.yaml
src/tests/ftest/rebuild/delete_objects.yaml
src/tests/ftest/rebuild/read_array.yaml
src/tests/ftest/rebuild/widely_striped.yaml
src/tests/ftest/rebuild/with_ior.yaml
src/tests/ftest/util/container_rf_test_base.py
src/tests/ftest/util/test_utils_pool.py

When possible, use the system default of svc_rf * 2 + 1 for rebuild tests instead of hardcoding to inappropriate values.
Otherwise, update some tests with svnc: 5 to account for killing a rank.
Test-tag: RbldCascadingFailures RbldDeleteObjects RbldReadArrayTest RbldContRfTest RbldWidelyStriped RbldWithIOR
Test-repeat: 2

DAOS-15002 test: use default pool svc for rebuild tests

---

src/control/server/ctl_storage_rpc.go
src/control/server/ctl_storage_rpc_test.go
src/control/server/instance_storage_rpc.go
src/control/server/instance_storage_rpc_test.go

Bad merge involving PR-13614 resulted in broken bdevScanEngine go unit test.
- Fix merge conflict affecting unit test by adding roles to bdev in scan.
- Improve reliability of unit test by sorting response content.
- Move filtering of bdevs in bad state so that retry logic is not inadvertently triggered.

DAOS-14985 test: Address unit test failure due to merge

---

src/tests/suite/dfs_test.c

Features: daos_core_test_dfs
Since cmocka is not MPI-aware, force all ranks other than rank 0 to write to stdout to avoid race conditions with the XML file.

DAOS-14594 test: fix dfs_parallel xml generation (#13312)

---

src/tests/ftest/dfuse/daos_build.py

Move slow variants of test to weekly testing.
Move fastest variant to PRs.
Add il tag to il variant.
Test-tag: DaosBuild

DAOS-15080 test: Update dfuse/daos_build test tags.

---

src/client/dfuse/il/int_read.c
src/client/dfuse/il/int_write.c
src/object/cli_obj.c

Rather than sending one entry at a time, we create a d_iov_t for the whole write.  This shows about a 13x performance increase for checkpointing in maxtext
AI application.
Change-Id: Ib14b189ad37eb799d84d19794fc06077c3436989

DAOS-15037 client: Pass vectorized write to dfs

---

src/include/daos/lru.h
src/pool/srv_target.c
src/vos/vos_obj.h
src/vos/vos_obj_cache.c

Sometimes, when a pool is stopped, some user may be still using the pool with reference held on such pool. For the user that is holding the last reference on the stopped pool, when it releases reference, it will trigger pool_free_ref that will stop (with block mode) the container that may wait current user (ULT) to exit.
To avoid potential deadlock, we will use another independent ULT to release the reference (on the stopped pool) asynchronously and make current ULT to go ahead.

DAOS-15073 pool: avoid deadlock when put last ref on stopped pool

---

src/tests/ftest/erasurecode/offline_rebuild_aggregation.py

The test_ec_offline_rebuild_agg_disabled test in erasurecode/ offline_rebuild_aggregation.py should be deleted because this is not a scenario that real users will ever do.
Test-tag: ec

DAOS-14320 test: remove offline_rebuild_agg test

---

src/client/dfs/dfs.c

- memcpy is more efficient to avoid scanning the entire kds string.
- remove an assert and replace with error when looking up "."
Features: dfs

DAOS-15069 dfs: use memcpy instead of snprintf for readdir

---

src/container/srv_container.c
src/container/srv_target.c
src/object/srv_ec_aggregate.c

EC aggregation shouldn't be paused even when the target is busy, otherwise, it'll result in the global EC boundary not being bumped timely, and impact VOS aggregation over all targets.
Added few warning messages when the EC boundary is't bumped timely.

DAOS-14837 container: don't pause EC aggregation (#13539)

---

src/tests/ftest/daos_test/suite.yaml
src/tests/ftest/util/daos_core_base.py

Revert "DAOS-14969 test: Increase crt_timeout for test_daos_oid_allocator"

---

src/tests/ftest/server/metadata.py
src/tests/ftest/server/metadata.yaml

Change the server/metdata.py tests to expect, for a pool rdb capacity
of 128 MiB, out of space errors just before creating a maxiimum of
about 7500 containers (increasing from the prior value 3500).
To avoid out of space errors on pool service replica followers,
in the server/metadata.yaml functional test config, change the
rdb log compaction frequency (RDB_COMPACT_THRESHOLD) to be once every
64 entries, rather than the prdoduct default 256. For applications
that push the metadata/rdb space to its limits, this is one tactic to
reduce the amount of free space skew between the leader and followers.
Such skew, if allowed to become too large, can cause followers to run
out of space in rdb before the next periodic trigger of log compaction.
And that of course can impact overall pool service …

DAOS-14781 test: expect more containers before rdb nospace (#13647)

---

src/control/cmd/dmg/pretty/storage.go
src/control/cmd/dmg/pretty/storage_test.go
src/control/cmd/dmg/storage_query.go

Update display output and command description to indicate that dmg
storage query list-pools will only show pools containing some NVMe.

DAOS-9572 control: Indicate list-pools only shows NVMe

---

src/tests/ftest/nvme/fault.py
src/tests/ftest/nvme/fault.yaml

To enable compatibility with server PMEM and MD on SSD modes, the pool created for the nvme/fault.py will now use a percentage for the size instead of calculating the maximum NVMe size.
Test-tag: test_nvme_fault
Skip-func-hw-medium-md-on-ssd: false

DAOS-14828 test: Utilizing pool percentage for nvme/fault.py

---

src/tests/ftest/dfuse/bash_fd.py
src/tests/ftest/dfuse/bash_fd.yaml

Add a test for pil4dfs that tries to replicate what configure
scripts do with file descriptors.
Test-tag: FdTest
Skip-init-tests: true

DAOS-14826 test: Add a dfuse/pil4dfs test for bash fd usage.

---

src/control/SConscript
src/control/build/string.go
src/control/build/variables.go

Include build timestamp in all builds. Only
include build host in non-release builds.

DAOS-15055 tools: Add build host/time to JSON version (#13644)

---

.github/CODEOWNERS
.github/pull_request_template.md

Added a few teams for different areas of the code.
Doc-only: true

DAOS-623 ci: Use owners teams for CODEOWNERS

---

src/tests/ftest/dfuse/daos_build.yaml

Increase RAM reserved for system when calculating tmpfs size to avoid
failing available memory check on start-up when host is running other
applications requiring system RAM.
Test-tag: daosio,dfuse

DAOS-14894 test: Bump system_ram_reserved for dfuse/daos_build.py

---

src/dtx/dtx_coll.c
src/dtx/dtx_common.c
src/dtx/dtx_internal.h
src/dtx/dtx_rpc.c
src/include/daos_srv/dtx_srv.h
src/object/SConscript
src/object/cli_coll.c
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_ec.h
src/object/obj_internal.h
src/object/obj_rpc.c
src/object/obj_rpc.h
src/object/obj_tx.c
src/object/obj_utils.c
src/object/srv_coll.c
src/object/srv_internal.h
src/object/srv_mod.c
src/object/srv_obj.c
src/object/srv_obj_remote.c
src/tests/ftest/util/telemetry_utils.py
src/tests/suite/daos_obj.c

Currently, get file size (query key) for large-scaled object is very slow. Because DAOS does not has logic (metadata) center to store the file size. The client needs to send query RPCs to all related redundancy groups, then aggregate related query results. For EC object with parity rotation, it is worse, the client has to send query RPCs to all shards in every redundancy group. It will cause a lot of query RPCs. For large-scaled object (such as the "GX" object class), current method is too heavy loaded for both client and servers.
To resolve such bad situation, we introduce new mechanism: collective query. The basic idea is that: before sending query RPCs to related engines, based on the shards to be queried, the client will generate the bitmap for related VOS targets on each involved …

DAOS-14557 object: collectively query key

---

src/tests/ftest/dfuse/bash.py
src/tests/ftest/dfuse/bash.yaml

Test-tag: test_bashcmd test_bashcmd_ioil test_bashcmd_pil4dfs
Test-repeat: 5

DAOS-15066 test: Update dfuse/bash and more to vms.

---

src/container/cli.c
src/include/daos/tse.h
src/object/obj_tx.c
src/object/srv_ec_aggregate.c
src/pool/cli.c
src/tests/ftest/erasurecode/multiple_failure.yaml

should register completion callback before task reinit, or the complete cb possibly cannot be triggered.
and a few other backports:
6d4e549db9 - DAOS-14788 pool: Fix some reinit usages (#13518) 
91b93c84e8 - DAOS-13252 tests: set svcn for multiple_failure test (#13619) 
d30e842afc - DAOS-14903 object: fix bug in peer status check (#13585)

DAOS-14903 container: refine task process in pmap_refresh_cb (#13491)

---

utils/node_local_test.py

When NLT is compressing log-files it tries to wait for child
proccess to exit, however the logic for this was incorrect so
it was not blocking for children or reaping the processes.
Normally this does not matter as the last log file to be
processed in the server log which is quite large and is
correctly waited for but a recent change to reduce the server
log size means that the previous log-file to be compressed
is still running when NLT exits and this causes problem with
the archiving as the .log file disappears after the .bz2 file
is complete.
This is causing Fault Injection test errors in Jenkins.

DAOS-623 test: Properly wait for log compression in NLT.

---

src/mgmt/srv_target.c

Check vos tls in vos_pool_hhash_get(), since it maybe called in the system xstream.

DAOS-15045 vos: check tls before accessing

---

src/client/api/event.c

- Since we have no Cart RPC abort, on a force EQ destroy we flush the cart context to drain all RPCs. However the corresponding DAOS tasks need to be processed in the scheduler and their events processed in the event queue before we can destroy the EQ.

DAOS-15096 client: poke the scheduler on eq destroy

---

src/pool/srv_util.c

Only allow UPIN engine as PS replicas to avoid IV leader switch hashles during rebuild for the moment.

DAOS-14972 pool: Only allow UPIN engine as PS replicas (#13593)

---

src/control/lib/daos/pool_property_test.go

Recently-added pool properties svc_ops_enabled and svc_ops_entry_age could use some control plane unit tests, added in this patch.

DAOS-14909 test: unit tests for new pool properties

---

src/dtx/dtx_common.c
src/dtx/dtx_resync.c
src/dtx/dtx_rpc.c

To avoid noisy dtx related message when open/close the container.

DAOS-15050 dtx: replace D_INFO with D_DEBUG for debug message (#13643)

---

src/control/cmd/dmg/pretty/storage.go
src/control/cmd/dmg/pretty/storage_test.go
src/control/cmd/dmg/storage_query.go

Update display output and command description to indicate that dmg
storage query list-pools will only show pools containing some NVMe.

DAOS-9572 control: Indicate list-pools only shows NVMe (#13711)

---

src/client/api/event.c

- Since we have no Cart RPC abort, on a force EQ destroy we flush the cart context to drain all RPCs. However the corresponding DAOS tasks need to be processed in the scheduler and their events processed in the event queue before we can destroy the EQ.

DAOS-15096 client: poke the scheduler on eq destroy (#13706)

---

src/control/cmd/daos/filesystem.go
src/utils/daos_hdlr.c
src/utils/daos_hdlr.h

Features: daos_fs_copy
The setuid, setgid, and sticky bit can cause fatal errors when the datamover tool sets file permissions after copying a file, since these are not supported by DFS. We can just ignore this bit when calling dfs_chmod.

DAOS-10942 utils: chmod should ignore unsupported bits (#12949)

---

src/tests/ftest/erasurecode/rebuild_disabled.py
src/tests/ftest/erasurecode/rebuild_disabled_single.py

Test-tag: EcodDisabledRebuildSingle EcodDisabledRebuild
Test-repeat: 3
Killing 2 ranks generally requires 2n+1 ranks total for the pool svc. Although it's possible to lower the svcn, there is no guarantee which ranks will be the svc ranks.
And it wouldn't be recommended in production to run with data RF2 but only pool svc RF 1.

DAOS-15002 test: only kill 2 ranks if we have 2n+1 total

---

src/cart/crt_init.c
src/common/rsvc.c
src/gurt/misc.c
src/include/gurt/common.h
src/pool/cli.c
src/pool/srv_util.c

- Remove duplicate d_srand calls in crt.
- Use tv_nsec instead of tv_nsec / 1e3 when calling d_srand, for this reduces the chance of seed collisions among daos_engine processes.
- Replace rand calls in libgurt and libpool with d_rand.
- Remove d_randn (introduced by this author), since lrand48_r doesn't return the lowest bits from Xi, and the % method is therefore sufficient for our purposes.

DAOS-15120 crt: Misc d_rand-related fixes

---

src/pool/cli.c
src/pool/srv_target.c

This patch cleans up the pool map update logging on the client side and the engine side. A few notable changes:
- In dc_pool_map_update, if the incoming map is of the same version as the one we already have, do not perform the update.

DAOS-14730 pool: Clean up map update logging

---

src/cart/utils/memcheck-cart.supp

DAOS-15159 test: add a supression for new valgrind warning in NLT

---

src/control/SConscript

Indicate to scons that the BuildTime linker flag should be
ignored when determining whether or not a rebuild of a Go
binary is necessary.
Change-Id: I00ee6536ec2506881f9a774d85ee5e4e8532cf83

DAOS-15055 build: Ignore BuildTime in rebuild calculation

---

src/client/dfs/dfs.c
src/control/cmd/daos/filesystem.go
src/control/cmd/daos/util.h
src/include/daos_fs.h
src/utils/daos_dfs_hdlr.c
src/utils/daos_hdlr.h
utils/node_local_test.py

Instead of just returning the oclass of new objects, return the oclass of the directory, the creation oclass of new directories, and the creation oclass of new files.
Features: dfs

DAOS-15138 dfs: improve output of daos fs get-attr

---

docs/admin/common_tasks.md
docs/admin/troubleshooting.md
src/control/events/engine.go
src/control/events/ras.go
src/control/server/instance.go
src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go
src/control/server/mocks.go
src/control/server/server.go
src/control/system/raft/database_members.go
src/control/system/raft/mocks.go
src/include/daos_srv/ras.h

Previously updating the fabric provider required reformatting the entire system. With this change, the fabric provider can be changed by stopping all engines, shutting down all daos_servers, and changing the provider in the config files. The MS leader is considered the canonical source of the system's expected fabric provider. It will reject ranks that attempt to join with unexpected fabric providers.

DAOS-6533 control: Automatically update fabric provider

---

src/common/ad_mem.c

DAOS-14194 common: fix memory leak reported by Coverity
CID 1347807 - resource leak
Related to: #12866 

DAOS-14194 common: fix memory leak reported by Coverity

---

src/vos/vos_io.c
src/vos/vos_obj.c

It may be not fatal if we cannot commit some shared DTX before VOS modification, but the failure for commit may cause related backend TX to be aborted. If we ignore the failure, subsequent operation may trigger local TX related assertion.

DAOS-15245 vos: do not ignore failure for DTX commit-on-share

---

src/control/cmd/daos/filesystem.go
src/utils/daos_hdlr.c
src/utils/daos_hdlr.h
utils/node_local_test.py

- **DAOS-14411 control: Expose dfuse statistics as yaml.**

DAOS-14411 control: Expose dfuse statistics as json

---

src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go

There was a possibility that an access point could shut down and re-join the system, win a MS leadership election, and subsequently change the fabric provider, even though there are members already joined and communicating over the old provider.

DAOS-15248 control: Prevent provider change when system up

---

src/tests/ftest/nvme/health.py

RDB memory should be considered when calculating max number of pools for pool creation.
Test-tag: test_monitor_for_large_pools

DAOS-14829 test: fix max number of pools for MD-on-SSD

---

src/control/cmd/dmg/pretty/printers.go
src/control/cmd/dmg/pretty/system.go
src/control/cmd/dmg/pretty/system_test.go
src/control/cmd/dmg/system_test.go
src/control/server/mgmt_system.go
src/control/system/membership.go
src/control/system/rankgroups.go
src/control/system/rankgroups_test.go

Results from dmg system stop cmd are not being displayed when a rank result error message contains a character that clashes with what is used as a separator when generating result rank groups. Use a tab character as that separator and replace any tab chars in result text with spaces. This solution should prevent any information loss in result text whilst avoiding character clashes.

DAOS-15207 control: Use tab char separator when generating system cmd results

---

src/control/cmd/dmg/pretty/system_test.go

DAOS-15207 control: Fix codespell issue

---

src/placement/jump_map.c
src/placement/jump_map_versions.c
src/vos/vos_dtx.c
src/vos/vos_internal.h

Fix a few typo for delay rebuild.

DAOS-14010 placement: refine for delay rebuild

---

src/rdb/rdb_internal.h
src/rdb/rdb_raft.c

Before this change, the rdb / PS leader avoids appending a raft entry for the metadata operation if free space in rdb falls below 512KiB. With this change, the threshold is increased to 4MiB to (further) prevent the potential for follower replicas to encounter out of space. This helps to avoid potential PS instability.
Another minor change is made to error logging when processing raft reply messages, to make it easier to know the engine rank that handled the RPC (and sent the reply).
Test-tag: pr test_metadata_fillup test_metadata_addremove test_metadata_server_restart

DAOS-13982 rdb: increase noappend bytes in test for nospace

---

src/tests/suite/daos_container.c

This change fixes a bad memset() size argument in the daos_test container co_op_retry() function. Pass the sizeof(daos_pool_info_t) instead of daos_cont_info_t when clearing the pinfo structure.

DAOS-15324 test: fix CID 1971004 memset size argument

---

src/tests/ftest/datamover/negative_space.py
src/tests/ftest/datamover/negative_space.yaml
src/tests/ftest/util/data_mover_test_base.py

Test-tag: DmvrNegativeSpaceTest
Create the source file in a DAOS pool instead of tmp for speed. Use a smaller file size.
Use multiple procs.

DAOS-15263 test: speedup datamover/negative_space.py

---

src/tests/suite/daos_test.c

Since cmocka is not MPI-aware, force all ranks other than rank 0 to write to stdout to avoid race conditions with the XML file.

DAOS-15250 test: fix multi proc writing same cmocka xml

---

src/gurt/dlog.c

This commit fixes the unchecked return value message from the pthread_mutex_unlock and pthread_mutex_lock calls. We should never hit these scenarios in practice based on the existing code and documented errors. Adding void indicates to Coverity that we don't need to worry about the return value for this use case.

DAOS-15306 gurt: Fix Coverity message for unchecked return value.

---

src/tests/ftest/util/apricot/apricot/test.py
src/tests/ftest/util/collection_utils.py
src/tests/ftest/util/launch_utils.py

To help better identify issues in timed out tests, log steps will now report an elapsed time between the steps that are logged.

SRE-471 test: Adding elapsed time to log steps

---

src/cart/crt_rpc.c

Before an engine knows its rank, it skips both the rank and the tag checks for incoming RPCs. Because we progress the SWIM context before knowing the rank of the engine, we handle RPCs sent to our SWIM tag in the SWIM xstream. Some of these RPCs may be sent to a different tag of a previous DAOS system, whose network address happens to be the same as that of our SWIM tag! Hence, this patch strengthens crt_rpc_common_hdlr to perform the tag check regardless of self_rank.

DAOS-15277 cart: Strengthen incoming tag checks

---

src/vos/vos_obj.c

The krec pointer is initialized inside vos_tree.c's "key_tree_prepare" function, so this adds a NULL check to squash this warning. If the toh is valid, then the krec will always be initialized.

DAOS-15310 vos: Fix Coverity issue for uninitialized pointer read.

---

utils/githooks/commit-msg.d/10-watermark.py

When there is a Change-Id in the commit message,
emit the watermark before that line to stay
compatible with Gerrit
Doc-only: true
Change-Id: Id64ed582966580b90ca30df4ffbdeb51673a82a4

DAOS-623 ci: Emit watermark before Change-Id

---

src/client/dfs/obj.c

DAOS-15296 dfs: properly handle errors on the statx async call

---

src/control/lib/control/rpc_test.go
src/control/logging/syslog_test.go
src/control/provider/system/system_linux_test.go

Fixes a few Go unit test failures:
* Adjust gRPC client tests to behave correctly
with newer gRPC versions
* Don't run the syslogger test if syslogd is not
running
* Adjust some system tests to use paths that are
more likely to exist on most systems
Change-Id: Ifb3198435113f3dc251c6c0822b66c157aa1a369

DAOS-15429 test: Fix Go unit tests

---

utils/githooks/commit-msg.d/10-watermark.py

When there is a Change-Id in the commit message,
emit the watermark before that line to stay
compatible with Gerrit
Change-Id: Ic3956446312f2da503df626c0263a1c77f59076e

DAOS-623 ci: Emit watermark before Change-Id (#13966)

---

src/container/srv_target.c
src/engine/server_iv.c
src/pool/srv_iv.c
src/pool/srv_target.c

Use deep stack size for IV ULT.

DAOS-15395 pool: use deep stack size for IV ult

---

src/include/daos_srv/pool.h
src/pool/srv_target.c

The ds_pool.sp_checkpoint_props_changed bitfield is modified from target xstreams, causing a data race on all surrounding bitfields among the system xstream and all the target xstreams. It is this author's guess that such data races have likely led to the pool destroy timeouts caused by pool_fetch_hdls_ult_abort hangs reported in the Jira ticket.
Here is how the hang happened during one pool destroy timeout:
31:54.85 pool_fetch_hdls_ult() b262bfcf: begin: fetch_hdls=1
stopping=0
31:54.85 pool_fetch_hdls_ult() b262bfcf: waiting for map
32:03.96 pool_fetch_hdls_ult() b262bfcf: fetching handles
32:03.96 pool_fetch_hdls_ult() b262bfcf: signaling done
32:03.96 pool_fetch_hdls_ult() b262bfcf: end
38:07.48 pool_fetch_hdls_ult_abort() b262bfcf: begin: fetch_hdls=1
stopping=1
38:07.48 …

DAOS-14126 pool: Fix a pool destroy timeout

---

src/common/btree.c

Adding a null check before dereferencing.
While I don't have access to the coverity report, the dereference seems to be `rec`. Although given a null `btr_record`, the rc check after `btr_rec_fetch()` should prevent the dereferencing null. Typically the callee should be validating inputs.

DAOS-15323 common: fix explicit null dereferenced

---

src/cart/utils/memcheck-cart.supp

On a clean build on el8.8 one of the existing suppressions needs tweaking.

DAOS-15416 test: Update memcheck suppressions.

---

site_scons/components/__init__.py

Meson "setup" sets up a package for buidlding, meson configure
sets a configuration option, but does not do the setup.
Previously our code would do setup, then configure which would
set configuration options but not apply them.
Ninja has file age checking built-in so if the config file was
older than the build file then it would re-run setup to apply
the correct config, and this was happening most times so
the build would work, but occasionally the file timestamps would
be the same so the check would not fail and the build would be run
without the configuration options applied.

DAOS-15417 build: Fix intermittent issue with libfuse build.

---

src/tests/ftest/datamover/negative_space.py
src/tests/ftest/datamover/negative_space.yaml
src/tests/ftest/util/data_mover_test_base.py

Test-tag: DmvrNegativeSpaceTest
Create the source file in a DAOS pool instead of tmp for speed. Use a smaller file size.
Move to VM.

DAOS-15263 test: speedup datamover/negative_space.py (#13859)

---

src/tests/ftest/dfuse/mu_perms.yaml

To workaround SRE-471 increase the dfuse/mu_perms.py test timeout by 60 seconds.
Test-tag: DfuseMUPerms

DAOS-15402 test: Increase dfuse/mu_perms.py timeout

---

src/tests/ftest/util/telemetry_utils.py

Since these are always going to be a single level of nested
lists, we don't need the more complex _flatten() helper.
Change-Id: I7c38b7763ea119c0c2414c87c69ae3fd176b23f2

DAOS-15426 test: Use splat for stats metrics lists

---

src/cart/crt_rpc.c

Before an engine knows its rank, it skips both the rank and the tag checks for incoming RPCs. Because we progress the SWIM context before knowing the rank of the engine, we handle RPCs sent to our SWIM tag in the SWIM xstream. Some of these RPCs may be sent to a different tag of a previous DAOS system, whose network address happens to be the same as that of our SWIM tag! Hence, this patch strengthens crt_rpc_common_hdlr to perform the tag check regardless of self_rank.

DAOS-15277 cart: Strengthen incoming tag checks (#13934)

---

src/cart/utils/memcheck-cart.supp
src/tests/ftest/cart/corpc/corpc_five_node.yaml
src/tests/ftest/cart/corpc/corpc_two_node.yaml
src/tests/ftest/cart/ctl/ctl_five_node.yaml
src/tests/ftest/cart/ghost_rank_rpc/ghost_rank_rpc_one_node.yaml
src/tests/ftest/cart/group_test/group_test.yaml
src/tests/ftest/cart/iv/iv_one_node.yaml
src/tests/ftest/cart/iv/iv_two_node.yaml
src/tests/ftest/cart/no_pmix/multictx_one_node.yaml
src/tests/ftest/cart/no_pmix_group_test.c
src/tests/ftest/cart/nopmix_launcher/launcher_one_node.yaml
src/tests/ftest/cart/rpc/multisend_one_node.yaml
src/tests/ftest/cart/rpc/rpc_one_node.yaml
src/tests/ftest/cart/rpc/rpc_two_node.yaml
src/tests/ftest/cart/rpc/swim_notification.yaml
src/tests/ftest/cart/selftest/selftest_three_node.yaml
src/tests/ftest/cart/utest/utest_portnumber.c
src/tests/ftest/control/config_generate_output.py
src/tests/ftest/control/config_generate_run.yaml
src/tests/ftest/server/multiengine_persocket.yaml
src/tests/ftest/util/dmg_utils.py
src/tests/ftest/util/network_utils.py
src/tests/ftest/util/server_utils_params.py
utils/docker/vcluster/daos-server/el8/daos_server.yml.in
utils/nlt_server.yaml
utils/test_memcheck.supp

Test-provider-hw-medium: ofi+tcp
Test-provider-hw-large: ofi+tcp
Test-tag: full_regression

DAOS-14669 test: switch tcp;ofi_rxm testing to tcp

---

src/cart/utils/memcheck-cart.supp
src/control/lib/telemetry/duration_test.go
src/control/lib/telemetry/gauge_test.go
src/control/lib/telemetry/promexp/collector.go
src/control/lib/telemetry/promexp/collector_test.go
src/control/lib/telemetry/telemetry.go
src/control/lib/telemetry/test_helpers.go
src/gurt/telemetry.c
src/tests/ftest/util/telemetry_utils.py

The Prometheus exporter is missing a few stats metrics
that would make some things easier to graph:
* sum
* sample_size
* sum_of_squares
Fixes the Min/Max/Sum methods to return uint64, as this is
the underlying data type. Callers should adjust as necessary.
Change-Id: Ic12a5f2ff562bcebbc9dc4351b999ef7d6b6d6d6

DAOS-15426 telemetry: Export missing stats metrics (#13979)

---

src/common/mem.c
src/include/daos/mem.h
src/pool/srv_pool_chkpt.c
src/pool/srv_target.c
src/rdb/rdb.c
src/vos/vos_pool.c

When WAL SSD is faulty, WAL commit will always fail and the last committed tx ID won't be bumped anymore, checkpoint ULT shouldn't wait on tx commit in such case, otherwise, the checkpoint ULT will never be woken up, and the pool_child_stop() will be blocked on stopping the checkpoint ULT.

DAOS-15457 vos: don't wait for tx commit when SSD is faulty

---

src/utils/SConscript

When using server target, daos_metrics wasn't built because it was buried under a check for client target. I really need to figure out a better way to specify targets but this will fix the immediate issue.
Change-Id: Ifa3e49e42ad95fb96f246e723a5e4ec77f10e4d9

DAOS-623 build: daos_metrics not built

---

src/include/daos_srv/pool.h
src/pool/srv_target.c

The ds_pool.sp_checkpoint_props_changed bitfield is modified from target xstreams, causing a data race on all surrounding bitfields among the system xstream and all the target xstreams. It is this author's guess that such data races have likely led to the pool destroy timeouts caused by pool_fetch_hdls_ult_abort hangs reported in the Jira ticket.
Here is how the hang happened during one pool destroy timeout:
31:54.85 pool_fetch_hdls_ult() b262bfcf: begin: fetch_hdls=1
stopping=0
31:54.85 pool_fetch_hdls_ult() b262bfcf: waiting for map
32:03.96 pool_fetch_hdls_ult() b262bfcf: fetching handles
32:03.96 pool_fetch_hdls_ult() b262bfcf: signaling done
32:03.96 pool_fetch_hdls_ult() b262bfcf: end
38:07.48 pool_fetch_hdls_ult_abort() b262bfcf: begin: fetch_hdls=1
stopping=1
38:07.48 …

DAOS-14126 pool: Fix a pool destroy timeout (#13983) (#12889)

---

site_scons/site_tools/daos_builder.py
src/control/SConscript
src/tests/ftest/dfuse/daos_build.py

This avoids a long-standing but previously unknown issue where
the build directory was in LD_LIBRARY_PATH when running gcc etc.
Update site_scons to not se LD_LIBRARY_PATH for all commands launched
during the build but rather only set it for the step where the dmg man
pages are generated.
This impacts the daos_build test which bas previously always needed
to run the daos_build with --jobs=1, with this change then the build
can be run in parallel which reduces the run-time of this test by a third.

DAOS-15497 build: Only set LD_LIBRARY_PATH in scons build where required.

---

src/control/server/storage/scm/ipmctl.go
src/control/server/storage/scm/ipmctl_dimm_test.go
src/control/server/storage/scm/ipmctl_firmware.go
src/control/server/storage/scm/ipmctl_firmware_test.go
src/control/server/storage/scm/ipmctl_region_test.go
src/control/server/storage/scm/ipmctl_test.go
src/control/server/storage/scm/ndctl_test.go

Race condition exists where occasionally ipmctl library init fails.
This seems to be due to having initialized libipmctl before 
subsequently calling ipmctl binary during scm scan operation. Fix this
by restricting the use of libipmctl API to SCM firmware calls only and
removing the library init call from the generic command runner.
Adjust tests and mocking as appropriate.

DAOS-15495: Fix libipmctl init failure

---

src/vos/vos_common.c
src/vos/vos_dtx.c

Clear dae_aborting flag on active DTX entry to avoid blocking subsequent resent RPC.
More log message when fail to create active DTX entry.

DAOS-15222 vos: handle dae_aborting flag for active DTX entry

---

Jenkinsfile

Warnings-ng 11.2.2 removed the ignoreFailedBuilds parameter from the recordIssues Step.

SRE-2145 Warnings-ng 11.2.2 modified API

---

src/tests/ftest/rebuild/container_create_race.yaml

Test-tag: RbldContainerCreate
Test-repeat: 3
Do not specify 1 svc. Let the system default choose 3.

DAOS-15002 test: fix rebuild/container_create_race

---

src/client/dfuse/dfuse.h

Support ARM64 O_LARGEFILE flags.
This value is hard coded to x86 value.
This value is different in ARM.
added a flag to identify the right flag.

DAOS-14902 dfuse: ARM fcntl flags are different for O_LARGEFILE

---

src/common/dav/dav_iface.c
src/common/dav_v2/dav_iface.c
src/common/mem.c
src/common/tests/umem_test.c
src/include/daos/mem.h

- Remove the redundant check in umem_cache_map(), that could mistakenly fail the call when mapping an evict-able page.
- Fix need_reserve() to deal with the case when "max_ne_pgs - ne_pgs < UMEM_CACHE_RSRVD_PAGES".

DAOS-14317 umem: two fixes for umem cache

---

src/cart/crt_init.c

- Prevent engines from using "CRT_CTX_NUM" setting to restrict number of contexts. This option is only proper for scalable endpoint setting which is no longer supported by any provider.
- This is intended to fix a rebuild test that currently sets SEP=true, CRT_CTX_NUM=8 while trying to start engines with more contexts than 8.

DAOS-15598 cart: Prevent engines from setting wrong number of contexts

---

utils/githooks/pre-commit.d/20-Jenkinsfile

build.hpdd.intel.com is not accessible externally. Ideally githooks should not use network calls at all but workaround this for now by skipping.

DAOS-623 cq: skip jenkinsfile hook if URL not accessible

---

src/client/dfuse/dfuse_core.c
src/utils/daos_hdlr.c

Fixes coverity ID 1979831
Also fix 1981011 about correct handling of fd 0

DAOS-15345 dfuse: Ignore return of cont_close.

---

src/utils/daos_hdlr.c

DFS allows S_ISGID and S_ISUID so the copy tool should not unmask them.
Features: datamover

DAOS-15594 tools: do not unmask gid and uid on chmod

---

src/client/dfs/cont.c
utils/node_local_test.py

When a container is created with --oclass, query was showing that as UNKNOWN since we switched to using file-oclass and dir-oclass internally. Fix this display issue to avoid raising alarms for users.
Features: dfs

DAOS-15255 dfs: fix display bug of cont query if --oclass is used

---

.github/actions/provision-cluster/action.yml
.github/workflows/bash_unit_testing.yml
.github/workflows/ci2.yml
.github/workflows/clang-format.yml
.github/workflows/create_release.yml
.github/workflows/doxygen.yml
.github/workflows/flake.yml
.github/workflows/landing-builds.yml
.github/workflows/linting.yml
.github/workflows/ossf-scorecard.yml
.github/workflows/pr-metadata.yml
.github/workflows/pylint.yml
.github/workflows/rpm-build-and-test-report.yml
.github/workflows/rpm-build-and-test.yml
.github/workflows/spelling.yml
.github/workflows/version-checks.yml
.github/workflows/yaml.yml
utils/githooks/pre-commit.d/20-flake.sh

Also, skip `flake8 --diff` if flake8 >= 6.0.0.
Resolve **Token-Permissions** issues from OSSF Scorecard in all workflows.
Don't install PR daos repo if RPM-test-version was specified.
Add `checks: write` for _EnricoMi/publish-unit-test-result-action_ uses.

DAOS-623 ci: Add a workflow for OSSF Scorecard

---

src/tests/ftest/util/test_utils_container.py

It should not be necessary to disconnect from the pool before creating a container with "daos container create".

DAOS-15477 test: remove unnecessary pool disconnect

---

src/include/daos_srv/pool.h
src/include/daos_srv/rdb.h
src/include/daos_srv/rsvc.h
src/pool/srv_internal.h
src/pool/srv_pool.c
src/pool/srv_target.c
src/rdb/rdb.c
src/rdb/tests/rdb_test.c
src/rsvc/rpc.h
src/rsvc/srv.c
src/vos/vos_pool.c

If a pool with an old layout version is served by a DAOS version with a new default layout version, for instance, a 2.4-layout pool served by DAOS 2.5, then any new VOS pools created for this DAOS pool must use the old layout, or downgrading back to the old DAOS version would become impossible.

DAOS-15605 rsvc: Create rsvc with VOS DF version

---

SConstruct

Change-Id: I81c32246ee0956fe2c380ccfb78875d8acdb1256
Signed-off-by: Jeff Olivier <jeffolivier@google.com>

Simple merge

---

src/tests/ftest/datamover/negative.py
src/tests/ftest/util/data_mover_test_base.py
src/utils/daos_hdlr.c

Features: daos_fs_copy
Check if the source and destination are the same.
Check if the source is a subset of the destination.

DAOS-15388 tools: daos fs copy: error when src is dst

---

src/engine/ult.c

When dss_chore.cho_func returns DSS_CHORE_DONE, the dss_chore object may
have been freed already. For instance, in the dtx_rpc_helper case,
dtx_check may have already returned, freeing (strictly speaking,
releasing) its stack frame that contains the dca.dca_chore object.
Hence, after calling chore->cho_func, dss_chore_queue_ult should only
dereference chore if the return value is DSS_CHORE_YIELD.

DAOS-15563 engine: Fix dss_chore use-after-free (#14096)

---

src/control/lib/telemetry/promexp/httpd_test.go

The prometheus exporter test starts a simple http
listener to verify that the setup code works correctly,
and the test should wait until the listener is really
ready.
Change-Id: I904ccf7d2dfb55c6787bb9fae3f8b5232dc47473

DAOS-8331 test: Fix racy unit test

---

src/control/cmd/daos_server/auto_test.go
src/control/cmd/daos_server/config.go
src/control/cmd/daos_server/main.go
src/control/cmd/daos_server/ms_recovery_test.go
src/control/cmd/daos_server/network_test.go
src/control/cmd/daos_server/storage_nvme_test.go
src/control/cmd/daos_server/storage_scm_test.go

Move ConfigPath field from the mainOpts struct to cfgCmd so that only
commands that embed the latter will inherit the -o flag. Specifically
daos_server config generate command will no longer support -o with the
result that config file input and output behaviour will be unambiguous.

DAOS-12891 control: Make -o daos_server option subcommand specific

---

src/gurt/dlog.c

A change further up in the stack revealed that "ERROR" wasn't accepted as a log mask string at the engine level.
Test-tag: pr test_version

DAOS-15686 gurt: Accept ERROR as a log mask string

---

src/control/cmd/daos_agent/attachinfo.go
src/control/cmd/daos_agent/network.go
src/control/cmd/daos_agent/start.go
src/control/cmd/daos_server/auto.go
src/control/cmd/daos_server/network.go
src/control/cmd/dmg/auto.go
src/control/cmd/dmg/cont.go
src/control/cmd/dmg/firmware.go
src/control/cmd/dmg/network.go
src/control/cmd/dmg/pool.go
src/control/cmd/dmg/server.go
src/control/cmd/dmg/storage.go
src/control/cmd/dmg/storage_query.go
src/control/cmd/dmg/system.go
src/control/cmd/dmg/telemetry.go
src/control/common/cmdutil/logging.go
src/control/logging/context.go
src/control/logging/context_test.go
src/tests/ftest/util/telemetry_utils.py

Updates control plane tools to set a context in a logger
for ease of debug/trace logging.

DAOS-14850 control: Allow logging.Logger in Context (#13569)

---

src/client/dfuse/dfuse_core.c
src/client/dfuse/dfuse_main.c
src/client/dfuse/dfuse_thread.c
src/client/dfuse/inval.c

When setting these previously I thought they only appeared in
debugger output so they have names which are only meaningful
in that context, but the thread names are also visable in
ps and top and having a process called "main" does not make
sense here.
Do not rename the main dfuse thread, and use a dfuse prefix
for other thread names.

DAOS-623 dfuse: Update dfuse thread names.

---

src/tests/ftest/dfuse/ioctl_pool_handles.py
src/tests/ftest/dfuse/mu_mount.py
src/tests/ftest/dfuse/mu_perms.py

Add missing ':avocado: recursive' from test class docstrings.
Test-tag: DfuseMUMount DfuseMUPerms IoctlPoolHandles

DAOS-15750 test: Missing dfuse/mu_perms.py execution

---

src/mgmt/cli_mgmt.c

- Fix mem leak for coverity 2555536

DAOS-15717 bug: Fix memory leak cid 2555536

---

src/include/gurt/common.h

The coverity tool gets confused about the use of assert in the
debug version of the logging macros and can think a lock is
being unlocked twice which it reports as a API usage error.
Disable the complex macros for coverity to reduce the instances
of false positives in the tool.
Fixes coverity ID 1975167 and others.

DAOS-15329 cq: Disable debug locking macros for coverity.

---

src/tests/ftest/erasurecode/rank_failure.yaml

Originally use parameters "-g 11 -t 7 -o 3 -a 3 -d 3" for daos_gen_io_conf will generate 437 cmd lines that includes 54 exclude/add cmd each will trigger one rebuild. The total time 2100 Second possibly not enough to run those cmds (most time spend for the 54 rebuilds). This patch reduce the parameters "-g 11 -t 4 -o 3 -a 2 -d 2" will generate 181 cmd lines includes 24 exclude/rebuild cmds to reduce testing time.
Reduce the timeout value accordingly.
Test-tag: test_daos_run_io_conf

DAOS-15059 test: reduce parameter for rank_failure test

---

src/tests/ftest/control/dmg_system_cleanup.py

Test-tag: test_dmg_system_cleanup_one_host
"dmg system cleanup" will cleanup the pools and containers so skip teardown cleanup.

DAOS-15768 test: skip cont cleanup in dmg_system_cleanup

---

src/control/cmd/dmg/pretty/storage.go
src/control/cmd/dmg/pretty/storage_test.go

For certain situations a zero value NVMe namespace ID will be returned
in dmg output, in this case it should be omitted from display output as
valid values are non-zero.

DAOS-15048 control: Display NSID only when populated in storage query

---

src/tests/suite/dfs_unit_test.c

DAOS-623 test: fix gid typo check in unit test

---

src/client/dfuse/dfuse_core.c

DAOS-15753 dfuse: Do not deadlock when failing to mount.

---

docs/user/filesystem.md
src/client/dfuse/dfuse.h
src/client/dfuse/dfuse_cont.c
src/client/dfuse/dfuse_core.c
src/client/dfuse/dfuse_fuseops.c
src/client/dfuse/dfuse_main.c
src/client/dfuse/dfuse_pool.c
src/client/dfuse/ops/create.c
src/client/dfuse/ops/forget.c
src/client/dfuse/ops/ioctl.c
src/client/dfuse/ops/lookup.c
src/client/dfuse/ops/mknod.c
src/client/dfuse/ops/open.c
src/client/dfuse/ops/opendir.c
src/client/dfuse/ops/read.c
src/client/dfuse/ops/readdir.c
src/client/dfuse/ops/readlink.c
src/client/dfuse/ops/rename.c
src/client/dfuse/ops/setxattr.c
src/client/dfuse/ops/symlink.c
src/client/dfuse/ops/unlink.c
src/client/dfuse/ops/write.c
src/control/cmd/daos/filesystem.go
src/include/dfuse_ioctl.h
src/tests/ftest/dfuse/daos_build.py
src/utils/daos_hdlr.c
src/utils/daos_hdlr.h
utils/node_local_test.py

Multiple cherry-picks to add daos fs query feature for fuse statistics.  Helpful for understanding and tuning DAOS performance when dfuse is used.
As a side effect, also adds daos filesystem evict which instructs dfuse to free up local resources for a file.
DAOS-13625 dfuse: Merge the info and projection_info structs. (#11881)
DAOS-13658 dfuse: Add filesystem query command. (#12367)
DAOS-12751 control: Add a daos filesystem evict command. (#12331)
DAOS-12751 dfuse: Improve evict command. (#12633)
DAOS-13625 dfuse: Remove dfuse_projection_info entirely. (#12796)
DAOS-13625 dfuse: Replace fs_handle with dfuse_info. (#12894)
DAOS-13625 dfuse: Add core inode_lookup() and inode_decref() functions. (#12573)
DAOS-14411 dfuse: Add per-container statistics. (#12819) …

DAOS-14411 dfuse: Add daos fs query

---

src/client/dfuse/ops/read.c

Increase the pre-read statistics before replying to the read,
otherwise the oh might not be valid which can lead to unexpected
behaviour.

DAOS-15745 dfuse: Add the pre_read metrics whilst holding reference.

---

src/client/dfs/duns.c
src/include/daos_pool.h
src/tests/ftest/control/daos_system_query.py
src/tests/ftest/control/daos_system_query.yaml
src/tests/ftest/util/apricot/apricot/test.py

Test-tag: pr,vm DaosSystemQuery
Add a case for changing the default name of "daos_server" Fix bug when setting config name

DAOS-15684 test: add test case for custom server name

---

src/chk/chk_common.c
src/chk/chk_engine.c
src/chk/chk_leader.c
src/chk/chk_upcall.c
src/include/daos_srv/daos_chk.h
src/mgmt/srv_drpc.c
src/tests/suite/daos_cr.c

CID: 2555541 2555529 2555517 2555545 2555527

DAOS-15713 chk: fix kinds of coverity issues

---

src/tests/ftest/util/pool_security_test_base.py

Test-tag: SecurityPoolGroupsTest SecurityPoolACLTest
Skip container cleanup in teardown since the pool is destroyed explicitly first.

DAOS-15774 test: fix pool_acl and pool_groups

---

src/pool/cli.c

Free the allocated metrics in the failure handler.
Change-Id: I4a0f85b2d5c4dc885b391ba09bb640d800914d6a

DAOS-15706 telemetry: Fix coverity issue 2555548

---

src/tests/ftest/dfuse/daos_build.py

To speedup scons install with "--implicit-deps-unchanged" to save CI resource. It decreases this step a little over 10 minutes in local test when libpil4dfs.so is loaded.

DAOS-15773 tests: add "--implicit-deps-unchanged" in scons install command in daos build test

---

src/gurt/telemetry.c

Check the return value of d_tm_del_ephemeral_dir() in
the failure handler. Also fixes a potential deadlock
in the failure handler that was introduced in a
previous commit.
Change-Id: I0995cd4152c50c748bc8c9e653a9b7cdaf3fe850

DAOS-15705 telemetry: Fix coverity warning 2555549

---

src/common/tests_dmg_helpers.c

Check the rc when parsing the pool list from JSON.
Change-Id: Idc805b948a219a3b688d5817410b6c59246a0f08

DAOS-15728 test: Fix coverity issue 2555526

---

src/control/logging/syslog_test.go
src/control/server/mgmt_pool.go

check rank against membership before issuing rank update for integrate.
Also fix a minor unit test bug related to getting syslog

DAOS-15651 control: fail fast on invalid rank for integrate

---

src/client/dfuse/pil4dfs/int_dfs.c
src/tests/ftest/dfuse/daos_build.py

To fix the dead lock issue in CI in get_fd_redirected().
Also decrease timeout a little bit to decrease the wasted time in case of deadlock.
Repeat daos build with libpil4dfs by three times.

DAOS-15783 client: fix the deadlock issue in daos build in CI

---

src/tests/ftest/nvme/enospace.yaml
src/tests/ftest/nvme/pool_capacity.py
src/tests/ftest/util/test_utils_container.py

Test-tag: NvmeEnospace
Track containers created with start_ior_load and delete them explicitly.

DAOS-15774 test: fix nvme/enospace.py container destroy

---

src/client/api/metrics.c
src/control/cmd/daos_agent/mgmt_rpc.go
src/control/cmd/daos_agent/start.go
src/control/lib/telemetry/promexp/client.go
src/control/lib/telemetry/promexp/client_test.go
src/control/lib/telemetry/telemetry.go
src/mgmt/cli_mgmt.c

Enable scenarios where client telemetry is collected and dumped
to a CSV without agent config changes or involvement.
Setting D_CLIENT_METRICS_DUMP_DIR in the client process
environment will enable client telemetry dump to the
specified directory even if the agent is not configured
to export telemetry.
Change-Id: I243d11a2e00059ef3115d392d63c523048477122

DAOS-8331 telemetry: Support client metrics dump without agent

---

src/client/api/init.c
src/control/cmd/daos/pool.go
src/control/cmd/daos/util.go
src/engine/init.c
src/include/daos/mgmt.h
src/include/daos_srv/daos_engine.h
src/mgmt/cli_debug.c
src/mgmt/cli_mgmt.c
src/pool/srv_cli.c

Contains the following backports:
- DAOS-15655 control: fix support for non default system name (#14170)
- DAOS-13151 client: cache and reuse the attach info for the default system (#14172)

DAOS-13151 client: cache and reuse the attach info for the default system

---

src/pool/srv_pool.c

For Coverity 2555539.
In the check mode (CR), pool_svc_schedule incorrectly returns 0, causing pool_svc_schedule_reconf to leak the pool_svc_reconf_arg object. This patch changes the return value to -DER_OP_CANCELED to indicate that the scheduling didn't happen.
When ignoring a nonzero rc, we should set rc to zero afterwards, in order to avoid leaking the nonzero rc value to subsequent code unintentionally.

DAOS-15715 pool: Fix reconf_arg leak in check mode

---

Jenkinsfile

Pipeline lib isn't reading any default that has -
rather than underscore.  After talking to Intel,
changing to _ is best path forward.
Change-Id: Ie06711a82a344cbe6af581bf13f4c2d413a65ee0

DAOS-623 ci: Fix bug to disable hw tests

---

src/tests/ftest/util/test_utils_container.py

Move test_hints argument to read_an_obj only, not read_an_array
Test-tag: RbldWithIO RbldReadArrayTest RbldBasic DaosObjectQuery PoolEvictTest DkeyAkeyEnumPunch ObjFetchBadParam

DAOS-15797 test: fix nvme/object.py read_an_array

---

docs/admin/deployment.md
docs/admin/env_variables.md
src/control/cmd/daos_server/start.go
src/control/cmd/dmg/auto_test.go
src/control/server/config/server.go
src/control/server/ctl_storage_rpc_test.go
src/control/server/engine/config.go
src/control/server/instance.go
src/control/server/instance_exec.go
src/engine/init.c
src/engine/srv.c
src/engine/srv_internal.h
src/engine/ult.c
src/tests/ftest/control/daos_system_query.yaml
src/tests/ftest/control/dmg_pool_query_test.yaml
src/tests/ftest/control/dmg_server_set_logmasks.yaml
src/tests/ftest/harness/core_files.yaml
src/tests/ftest/pool/create_all_vm.yaml
src/tests/ftest/pool/query_attribute.yaml
src/tests/ftest/server/daos_server_dump.yaml
src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml
utils/config/daos_server.yml
utils/nlt_server.yaml

Backport for the following patches
DAOS-13380 engine: refine tgt_nr check (#12405)
DAOS-15739 engine: Add multi-socket support (#14234)
* DAOS-13380 engine: refine tgt_nr check
1. for non-DAOS_TARGET_OVERSUBSCRIBE case fail to start engine if #cores is not enough
2. for DAOS_TARGET_OVERSUBSCRIBE case allow to force start engine The #nr_xs_helpers possibly be reduced for either case.
* DAOS-15739 engine: Add multi-socket support (#14234)
Add a simple multi-socket mode for use cases where a single engine must be used. Avoids the issue of having all helper xstreams automatically assigned to a single NUMA node thus increasing efficiency of synchronizations between I/O and helper xstreams.
It is the default behavior if all of the following are true
Neither pinned_numa_node nor first_core are …

DAOS-15739 engine: Add single-engine, multi-socket support

---

Jenkinsfile

Correct the provider and MD on SSD stage build parameters so that they use underscores in their names.

DAOS-15814 test: Fix build parameter for HW test stages

---

src/include/daos_srv/rdb.h
src/rdb/rdb_internal.h
src/rdb/rdb_raft.c
src/rdb/rdb_tx.c
src/rdb/rdb_util.c
src/rdb/tests/rdb_test.c

Reorder the LC and MC updates in rdb_raft_log_offer_single, so that the
MC update happens first. This causes MC updates of different log_offer
vtxs to get the same minor epoch, which is friendlier to vos, and would
work around the data loss found in the Jira ticket (even without the vos
fix).
Add a missing rdb_kvs_cache_evict call when rdb_raft_log_offer_single
has potentially dirtied the cache but fails to store the entry.
Fix the handling of deterministic errors. With VOS local TXs, we can't
call vos_discard upon deterministic errors in rdb_tx_apply. Instead, we
have to abort current VOS local TX to discard any operations we've done
so far, and start a new one to commit the entry without calling
rdb_tx_apply.

DAOS-15670 rdb: Do MC updates first in log_offer

---

src/control/cmd/daos_agent/security_rpc_test.go
src/control/drpc/drpc_client.go
src/control/drpc/drpc_client_test.go
src/control/server/ctl_ranks_rpc_test.go
src/control/server/ctl_smd_rpc_test.go
src/control/server/ctl_svc_test.go
src/control/server/harness_test.go
src/control/server/instance.go
src/control/server/instance_drpc.go
src/control/server/instance_drpc_test.go
src/control/server/mgmt_check_test.go
src/control/server/mgmt_cont_test.go
src/control/server/mgmt_pool_test.go
src/control/server/mgmt_system_test.go
src/control/server/util_test.go

The idea here is to remove the bottleneck in `daos_server` that serializes dRPC calls, to enable `daos_server` to pass along multiple dRPC calls even if the first one hasn't yet returned. In the current master branch, we have a single dRPC client structure that uses RW locks to control access to its internals. dRPC calls that take a long time can potentially impede other commands.
My proposed solution is to create a new `drpc.ClientConnection` for each command that needs to be sent to the `daos_engine`. Each command is handled on its own connection. We were using a connect->send->disconnect pattern on the client connection anyway.

DAOS-14834 control: Enable parallel server->engine dRPCs

---

src/chk/chk_common.c
src/chk/chk_engine.c
src/chk/chk_internal.h
src/chk/chk_iv.c
src/chk/chk_leader.c
src/chk/chk_rpc.c
src/container/srv_target.c
src/include/daos_srv/container.h
src/include/daos_srv/daos_chk.h
src/include/daos_srv/pool.h
src/mgmt/srv_pool.c
src/mgmt/srv_target.c
src/pool/srv_pool.c
src/pool/srv_target.c
src/pool/srv_util.c
src/tests/ftest/recovery/pool_membership.py
src/tests/suite/daos_cr.c

Currently, under check mode, before the pool check complete, the PS is either not started or partial started with some functionality skipped. Once the pool is checked with all potential inconsistency resolved, we will start former skipped parts for the pool service.
Such way can work, but has potential risk for new added logic that needs to be handled during PS start. More clean solution is that we can restart the PS with new flag that will overwrite the global engine_in_check() only for the special pool, then related PS can be fully started.
The patch also fixes another two issues:
1. Before destroying orphan pool target, need to stop related pool child firstly.
2. When destroy orphan pool shard, need to notify check engine to cleanup such pool shard related things.

DAOS-15769 chk: restart PS with full functionality after check

---

src/tests/ftest/deployment/critical_integration.py
src/tests/ftest/dfuse/simul.py
src/tests/ftest/pool/bad_query.py
src/tests/ftest/util/configuration_utils.py
src/tests/ftest/util/data_mover_test_base.py
src/tests/ftest/util/ec_utils.py
src/tests/ftest/util/file_count_test_base.py
src/tests/ftest/util/nvme_utils.py
src/tests/ftest/util/osa_utils.py
src/tests/ftest/util/pool_create_all_base.py
src/tests/ftest/util/pool_security_test_base.py
utils/cq/daos_pylint.py
utils/cq/requirements.txt

Update pylint from 3.1.1 -> 3.2.0 and resolve new warnings.
Features: BasicCheckoutDm IoSysAdmin EcodOnlineRebuildSingle LargeFileCount SmallFileCount NvmeFault OSAOfflineReintegration pool_create_all DaosContainterSecurityTest

DAOS-15830 cq: update pylint to 3.2.0

---

src/tests/ftest/util/soak_test_base.py
src/tests/ftest/util/soak_utils.py

DAOS-15848 test: Add module use to soak job scripts for aurora

---

src/common/tests/SConscript

Looks rsvc_tests should use tenv instead of unit_env.

DAOS-15846 common: Use tenv for rsvc_tests

---

src/control/cmd/daos_agent/security_rpc_test.go
src/control/drpc/drpc_client.go
src/control/drpc/drpc_client_test.go
src/control/server/ctl_ranks_rpc_test.go
src/control/server/ctl_smd_rpc_test.go
src/control/server/ctl_storage_rpc_test.go
src/control/server/ctl_svc_test.go
src/control/server/harness_test.go
src/control/server/instance.go
src/control/server/instance_drpc.go
src/control/server/instance_drpc_test.go
src/control/server/mgmt_cont_test.go
src/control/server/mgmt_pool_test.go
src/control/server/mgmt_system_test.go
src/control/server/util_test.go

The idea here is to remove the bottleneck in daos_server that serializes
dRPC calls, to enable daos_server to pass along multiple dRPC calls even
if the first one hasn't yet returned. In the current master branch, we
have a single dRPC client structure that uses RW locks to control access
to its internals. dRPC calls that take a long time can potentially impede
other commands.
My proposed solution is to create a new drpc.ClientConnection for each
command that needs to be sent to the daos_engine. Each command is handled
on its own connection. We were using a connect->send->disconnect pattern
on the client connection anyway.
Change-Id: Ibe5a03d28ecc5099b5827ef22fbbace9e3d8b963
Signed-off-by: Kris Jacque <kris.jacque@intel.com>

DAOS-14834 control: Enable parallel server->engine dRPCs (#14193)

---

src/cart/crt_register.c
src/cart/crt_rpc.c
src/client/api/rpc.c
src/include/cart/api.h
src/tests/ftest/cart/test_proto_client.c

Set it to 5 seconds so we can try a different target more quickly if a rank is down.

DAOS-15540 cart: Change proto query default timeout

---

src/control/lib/hardware/cart/bindings.go

Lack of it was causing failures in the Ubuntu build.

DAOS-15779 control: Explicitly link to libgurt in cgo

---

src/control/provider/system/mocks.go
src/control/provider/system/system_linux.go
src/control/provider/system/system_linux_test.go
src/control/server/ctl_storage_rpc_test.go
src/control/server/instance_storage.go
src/control/server/instance_storage_test.go
src/control/server/instance_superblock.go
src/control/server/instance_superblock_test.go
src/control/server/instance_test.go
src/control/server/storage/metadata/provider.go
src/control/server/storage/metadata/provider_test.go
src/control/server/storage/mount/provider.go
src/control/server/storage/mount/provider_test.go
src/control/server/storage/provider.go
src/control/server/storage/scm/mocks.go
src/control/server/storage/scm/provider.go
src/control/server/storage/scm/provider_test.go

Some control-plane storage unit tests are inadvertently calling into
test runner host OS filesystem. Fix by consolidating SystemProvider
interface and applying storage subsystem provider stubs by default
in the unit test framework. As a result coverage can be improved by
exercising a greater number of code paths.

DAOS-15841 control: Improve coverage and fs mocking in storage packages

---

src/cart/crt_init.c
src/cart/crt_register.c
src/cart/crt_rpc.c
src/client/api/rpc.c
src/common/rsvc.c
src/gurt/misc.c
src/include/cart/api.h
src/include/gurt/common.h
src/pool/cli.c
src/tests/ftest/cart/test_proto_client.c
src/tests/ftest/erasurecode/rebuild_disabled_single.yaml

Pick from all possible ranks for protocol query handling
Backports the following patches, last one fixes the issue but prior two are benign and make the backport work without conflict
DAOS-13717 client: use d_rand() to generate random number (#12418)
DAOS-15120 crt: Misc d_rand-related fixes (#13738)
DAOS-15476 client: do not use rsvc for proto query rank selection (#14131)
DAOS-15540 cart: Change proto query default timeout (#14382)

DAOS-15476 client: Better protocol query handling

---

src/client/dfuse/pil4dfs/int_dfs.c

Disable interception right before calling exec() which loads a new application image. All IO requests inside exec() will be handled by dfuse.
Once the new application image is loaded in exec and starts, function interception will be enabled inside the constructor function.

DAOS-15834 client: disable interception before exec()

---

src/tests/ftest/telemetry/wal_metrics.py

When verifying the wal checkpoint metrics after check pointing has occurred, make sure to use a case-insensitive match of the UUID of the pool for which the metrics are expected to have changed.
Test-repeat: 3
Test-tag: test_wal_checkpoint_metrics

DAOS-15873 test: Fix wal checkpoint metric test

---

src/container/srv_target.c
src/include/daos_srv/pool.h
src/pool/srv_target.c

Reorganize ds_pool_child start/stop code to make it able to be started/stopped individually:
- Introduced four states for ds_pool_child: NEW, STARTING, STARTED and STOPPING.
- ds_pool_child is added/removed to/from cache through the collective call of pool_child_add/delete_one(), now the cache doesn't hold the ds_pool_child reference anymore.
- Introduced ds_pool_child_start/stop() for callers to start/stop ds_pool_child individually, ds_pool_child_state() to query the state of ds_pool_child.
- Removed ds_pool_child_get();

DAOS-14535 pool: start/stop ds_pool_child individually (#13347)

---

src/tests/ftest/control/dmg_storage_query.py

The dmg storage set nvme-faulty command will now return a non-zero return code if host errors are detected. With MD on SSD we expect these host errors, so allow the test to continue in this case without raising an exception.

DAOS-15808 test: Fix test_dmg_storage_query_device_state

---

src/pool/cli.c
src/pool/srv_internal.h
src/pool/srv_pool.c
src/pool/srv_target.c
src/pool/srv_util.c

* DAOS-11955 pool: Ensure a PS is inside its pool
It was found that a PS leader may enter ds_pool_plan_svc_reconfs with itself being an undesirable replica. This may lead to an assertion failure at "move n replicas from undesired to to_remove" in ds_pool_plan_svc_reconfs. Moreover, such a PS leader may be outside of the pool group, making it incapable of performing many duties that involve collective communication.
This patch therefore ensures that a PS leader will remove undesirable PS replicas synchronously before committing a pool map modification that introduces new undesirable PS replicas. (If we were to keep an undesirable PS replica, it might become a PS leader.)
- Extend and clean up pool_svc_sched. * Allow pool_svc_reconf_ult to return an error, so that we can fail a pool map …

DAOS-11955 pool: Ensure a PS is inside pool (#13046)

---

utils/githooks/pre-commit.d/30-Jenkinsfile
utils/githooks/pre-commit.d/71-flake.sh
utils/githooks/pre-commit.d/72-pylint.sh
utils/githooks/pre-commit.d/73-ftest.sh

Fixed an issue where /bin/sh pointing to /bin/dash instead of /bin/bash was breaking compatibility on Ubuntu 22.04

SRE-2229 utils: Replace /bin/sh with /bin/bash in githooks

---

src/tests/ftest/control/dmg_storage_query.py

The dmg storage set nvme-faulty command will now return a non-zero return code if host errors are detected. With MD on SSD we expect these host errors, so allow the test to continue in this case without raising an exception.
Test-tag: test_dmg_storage_query_device_state

DAOS-15808 test: Fix test_dmg_storage_query_device_state (#14440)

---

src/bio/bio_xstream.c
src/control/lib/spdk/src/nvme_control.c

In SPDK issue 2683, SPDK incorrectly determines that an AMD iommu does not support virtual addressing.  As a result, DAOS engines cannot run as non-root on an AMD server.  Change DAOS to specify iova_mode = "va" when calling spdk_env_init() when running as non-root. This is a workaround until SPDK issue 2683 is fixed.

Provide workaround for SPDK issue 2683, AMD iommu support

---

src/client/dfuse/pil4dfs/int_dfs.c

DAOS-15862 client: declare num_fd_dup2ed atomic and lock_fd_dup2ed as rwlock

---

src/client/dfuse/pil4dfs/hook.c
src/tests/ftest/dfuse/bash.py

Somehow process memcheck in valgrind does not have "[heap]".

DAOS-15935 client: search section "[stack]" instead of "[heap]"

---

src/tests/ftest/util/daos_core_base.py

Improve identifying server log files associated with daos_test test variants by including the variant number of the test varaint that started the server in log file name.
Test-tag: DaosCoreTest

DAOS-15948 test: Include the varaint number in log files

---

src/object/srv_obj_migrate.c

migrate_system_enter possibly will yield, so need to do a re-probe before delete.

DAOS-15498 rebuild: reprobe in migrate_obj_iter_cb (#14458)

---

src/client/dfuse/pil4dfs/int_dfs.c

Workaround an issue with some compilers not playing nicely with the strncmp and STR_AND_SIZE macros in the case where strncmp is also defined as a macro.

DAOS-14539 client: fix pil4dfs strncmp compile in some envs (#14041)

---

src/bio/bio_context.c
src/bio/smd/smd_internal.h
src/bio/smd/smd_pool.c
src/bio/smd/tests/smd_ut.c
src/include/daos_srv/bio.h
src/include/daos_srv/smd.h
src/mgmt/srv_target.c
src/pool/srv_target.c
src/utils/ddb/ddb_vos.c
src/vos/tests/wal_ut.c
src/vos/vos_pool.c

In md-on-ssd phase 2, the scm_sz (VOS file size) could be smaller than the meta_sz (meta blob size), then we need to store an extra scm_sz in SMD, so that on engine start, this scm_sz could be retrieved from SMD for VOS file re-creation.
To make the SMD compatible with pmem & md-on-ssd phase 1, a new table named "meta_pool_ex" is introduced for storing scm_sz.

DAOS-15681 bio: store scm_sz in SMD

---

docs/admin/troubleshooting.md
src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go
src/control/system/errors.go
src/control/system/membership.go
src/control/system/membership_test.go

Previously the re-join was succeeding but not updating the address, which led to surprising behavior. With this change, the re-join fails and notifies the admin.

DAOS-15842 control: Reject re-join with different control addr

---

src/control/server/storage/bdev/backend_class_test.go
src/control/server/storage/bdev/backend_json.go
src/control/server/storage/bdev/backend_json_test.go

Ensure hotplug directives in SPDK JSON configuration appear after any
device attach entries to avoid enumeration race seen with multiple
VMD domains and described in https://github.com/spdk/spdk/issues/3370.

DAOS-15805 control: Adjust SPDK config entry order to avoid hotplug race

---

src/tests/suite/daos_base_tx.c
src/vos/evt_iter.c

To avoid locating the iteration position (for the first time) on some invisible EV data (with in-processing or aborted DTX).

DAOS-15885 vos: check DTX visibility when probe for EV iteration

---

src/common/btree.c
src/include/daos_srv/evtree.h
src/include/daos_srv/vos_types.h
src/vos/evt_priv.h
src/vos/evtree.c
src/vos/tests/evt_ctl.sh
src/vos/vos_internal.h
src/vos/vos_io.c
src/vos/vos_tree.c

DAOS-14010 vos: Allow rebuild overwrite (#13326)
DAOS-15670 vos: SV overwrite missed tx_add_range() (#14241)
* Partial overwrite is difficult for upper layer to avoid.  If we reserve a range of minor epochs for rebuild, we can just always allow rebuild to overwrite any extents currently in the tree for the given major epoch.
* In SV overwrite case, the btr_update_record() will defer free the original record and allocate new record for record replacing, however, btr_node_tx_add() is mistakenly skipped in btr_update(), that leads to:
1. In md-on-ssd mode, tree node changes are missed in WAL.
2. In pmem mode, tree node snapshot is missed in undo log.

Backport two changes that can improve rebuild stability

---

src/cart/utils/memcheck-cart.supp
utils/rpms/packaging/Dockerfile.ubuntu.20.04

DAOS-15959 cart: Add valgrind suppressions for Go runtime (#14507)
Another Valgrind false positive.
DAOS-623 build: Update packaging to… (#14513)
Pick up a fix from the packaging repo for getting the HPE repository signing key from our Artifactory instead of he HPE servers.  This insulates us from management issues with their server such as when they forget to update their certificate.

Backport two CI related patches

---

src/tests/ftest/util/daos_core_base.py

Improve identifying server log files associated with daos_test test variants by including the variant number of the test varaint that started the server in log file name.
Test-tag: DaosCoreTest

DAOS-15948 test: Include the varaint number in log files (#14488)

---

src/client/dfuse/pil4dfs/hook.c
src/tests/ftest/dfuse/bash.py

Somehow process memcheck in valgrind does not have "[heap]".

DAOS-15935 client: search section "[stack]" instead of "[heap]" (#14472)

---

src/tests/ftest/util/apricot/apricot/test.py

Add a config option, dump_engine_ult_on_failure, to disable dumping engine ULT stacks on test failure.

DAOS-15963 test: option to disable ULT stack dump on failure

---

src/tests/ftest/dfuse/pil4dfs_fio.py
src/tests/ftest/dfuse/pil4dfs_fio.yaml
utils/cq/words.dict

Clean cherry pick of the PR #14375
Add functional tests running FIO using the libaio ioengine and the PIL4DFS interception library.
Compare the bandwidth of these runs with one using the dfs ioengine.

DAOS-15801 test: Add aio ioengine to pil4dfs_fio.py functional test

---

src/tests/ftest/util/apricot/apricot/test.py

Add a config option, dump_engine_ult_on_failure, to disable dumping engine ULT stacks on test failure.
Rename dump_engines_stacks to __dump_engines_stacks

DAOS-15963 test: option to disable ULT stack dump on failure (#14506)

---

src/tests/ftest/telemetry/wal_metrics.py

In test_wal_checkpoint_metrics the engine_pool_checkpoint_duration can be larger than what was originally scoped for the test.  This will increase the expected value range and allow the test to pass.
Test-tag: test_wal_checkpoint_metrics
Test-repeat: 5

DAOS-15052 test: Update expected wal checkpoint metrics

---

src/container/container_iv.c

Apparently, when an I/O request fetches a container handle on the engine who is the PS leader, if the ds_cont_hdl object is absent (because the engine has restarted), then the cont_iv code won't create a ds_cont_hdl object, even though the handle is found in the RDB. This patch adds a ds_cont_tgt_open call to cont_iv_ent_fetch, so that the flow is similar to cont_iv_ent_update.

DAOS-15968 container: Fix CAPA fetch on NS master

---

src/control/security/config.go
src/control/security/config_test.go
src/control/security/pem_test.go
src/control/security/testdata/certs/badperms/README
src/control/security/testdata/certs/goodperms/README

Previously we returned a Fault indicating bad permissions whenever we failed to read the client cert directory. This could be misleading if, for example, the directory was a file or didn't exist at all.
Also refactored some older unit tests to not depend on in-source directories with assumed permissions.

DAOS-15850 control: Pass up errors when failing to read cert dir (#14475)

---

src/cart/crt_init.c
src/cart/crt_internal_types.h
src/cart/utils/crt_utils.c
src/cart/utils/crt_utils.h
src/utils/self_test/self_test.c

Change to how cart deals with envariables:
- env list is now controlled by CRT_ENV_LIST macro in crt_types_internal.h
- all envs stored in structure generated from CRT_ENV_LST (g_env) now, ENV is read out at crt_env_init() time and env strings deallocated at crt_env_fini().
- accsor functions/macros crt_env_init/fini/get/dump are provided.
- string-type envs no longer need to be freed after retrieval.
With this change, any env to be used will need to appear on the list first, ensuring it gets dumped as well as ensuring proper name usage later. Env name typos when using crt_env_get() will now result in compile time errors

DAOS-15961 cart: Reorganize how envs are handled

---

src/container/container_iv.c

Apparently, when an I/O request fetches a container handle on the engine who is the PS leader, if the ds_cont_hdl object is absent (because the engine has restarted), then the cont_iv code won't create a ds_cont_hdl object, even though the handle is found in the RDB. This patch adds a ds_cont_tgt_open call to cont_iv_ent_fetch, so that the flow is similar to cont_iv_ent_update.

DAOS-15968 container: Fix CAPA fetch on NS master (#14511)

---

src/tests/suite/daos_container.c

Rarely, this test will produce timings that exceed the failure threshold. Local and PR/CI experiments have shown that increasing the test's NUM_OPS to more than 200 iterations greatly reduces or may eliminate such intermittent timing failures, by "spreading out" the magnitude of the time spent in the 3 main loops of the test (0% loops perform fault injections, 33%, and 50%).

DAOS-15852 test: more timing samples for co_op_dup_timing()

---

src/cart/utils/memcheck-cart.supp
utils/test_memcheck.supp

Valgrind suppression for go-build-toolchain package v.1.22.3
Validation has been done via go-build-toolchain PR-25 with pragma `Test-master-branch: grom72/DAOS-16011`
The results are here:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-go-build-toolchain-PR-25-master/16/testReport/
Reference build w/o Valgrind suppressions:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-go-build-toolchain-PR-25-master/13/testReport/
The scope of validation only to SW tests (where Valgrind is used).

DAOS-16011 : Valgrind suppressions due to update Go to 1.22.3

---

src/tests/ftest/util/run_utils.py
src/tests/ftest/util/soak_test_base.py

Set clush fanout in run_remote to the max of the default or number of logical cores. This will help in large-scale environments.

DAOS-15955 test: increase clush fanout for run_remote

---

src/include/daos/pool_map.h
src/placement/pl_map.h
src/placement/pl_map_common.c

DAOS-16001 placement: fix cases for delay_rebuild

---

src/tests/ftest/telemetry/wal_metrics.py

In test_wal_checkpoint_metrics the engine_pool_checkpoint_duration can be larger than what was originally scoped for the test.  This will increase the expected value range and allow the test to pass.
Test-tag: test_wal_checkpoint_metrics
Test-repeat: 5

DAOS-15052 test: Update expected wal checkpoint metrics (#14520)

---

src/common/tests_dmg_helpers.c
src/control/cmd/dmg/pool.go
src/control/cmd/dmg/pool_test.go
src/gurt/misc.c
src/gurt/tests/test_gurt.c
src/include/daos_srv/pool.h
src/include/gurt/common.h
src/mgmt/srv_drpc.c
src/mgmt/srv_internal.h
src/mgmt/srv_pool.c
src/mgmt/tests/mocks.c
src/mgmt/tests/mocks.h
src/mgmt/tests/srv_drpc_tests.c
src/pool/srv_cli.c
src/pool/srv_pool.c
src/tests/ftest/control/dmg_pool_query_ranks.py

Allow enabled and disabled ranks option to be used simultaneously (DAOS-10250).
Update and add cmocka unit tests of engine management related functions (DAOS-10253).
Fix memory leaks of ranks string in function ds_mgmt_drpc_pool_query().
Change-Id: I27f5b3acb003faea2d53697e83f0afeb0e284080

DAOS-10250 control: Get enabled and disabled ranks with dmg pool query (#14436)

---

src/container/container_iv.c
src/container/srv_container.c
src/container/srv_internal.h
src/container/srv_target.c
src/dtx/dtx_resync.c
src/engine/ult.c
src/include/daos_srv/container.h
src/include/daos_srv/daos_engine.h
src/include/daos_srv/pool.h
src/mgmt/rpc.h
src/mgmt/srv.c
src/mgmt/srv_internal.h
src/mgmt/srv_target.c
src/object/srv_obj_migrate.c
src/pool/srv_iv.c
src/pool/srv_target.c
src/rebuild/scan.c
src/tests/suite/daos_test_common.c

DAOS-14679 pool: Report on stopping sp_stopping (#14374)
DAOS-15514 container: fix container destroy failure (#14108)
DAOS-15672 rebuild: Fix pool destroy hangs (#14183)
DAOS-15145 pool: add pool collective function (#13764)
*DAOS-14105 object: collectively punch object (#13493)
* partial backport, just the bitmap function
Change-Id: I2b21b8121cbdecc79ae49a464a42b1d47fb9be10

Backports to address b/336317519

---

src/mgmt/srv_pool.c

The ds_mgmt_create_pool leaks the pg_str string in an error case.

DAOS-16015 mgmt: Fix Coverity 2555784

---

src/cart/utils/memcheck-cart.supp
src/vos/tests/vts_wal.c
utils/test_memcheck.supp

some tests required fault injection, skip these tests if this feature is not enabled.

DAOS-16052 test: Skip wal tests if fault injection feature is disabled

---

src/client/dfs/obj.c
src/tests/suite/dfs_unit_test.c
src/tests/suite/dfuse_test.c

Python buffered read/write relies on st_blksize as default buffer size. dfuse calls dfs_ostatx() which returns stat with zero st_blksize. Consequently, 4096 for st_blksize is returned to application.
Features: dfs

DAOS-15992 client: set st_blksize in ostatx_cb() and add unit test

---

src/bio/bio_buffer.c
src/bio/bio_xstream.c

In md-on-ssd mode, when the update data size <= bio_max_async_sz, the local tx will execute in the async data io mode: "submit both data NVMe I/O and WAL NVMe I/O, then wait for both data I/O and WAL I/O completion", the purpose of this async data I/O mode is to reduce the update latency (by one WAL I/O latency comparing with the old sync mode).
However, tests showed that this async data I/O mode has slightly worse throughput comparing with the legacy sync I/O mode when the data size and QD are large (io size > 32k, QD = 64 or 128).
The reason could be that async I/O mode would more likely generate mixed I/O to SSD (when the WAL & data blob are sharing the same SSD, which is typical configuration), and that might cause more severe I/O reordering on SSD and that would badly impact …

DAOS-15751 bio: change default bio_max_async_sz to 32k

---

src/common/mem.c

in umem_cache_checkpoint(), reset the rc to 0 once so_flush_prep() failed for a chkpt_data, otherwise, the rc could be mistakenly used for so_flush_post() for a prior prepared chkpt_data.

DAOS-16091 umem: reset rc properly

---

src/tests/ftest/rebuild/cascading_failures.py
src/tests/ftest/util/container_rf_test_base.py

Placement fixes for delayed rebuild
* Note: this is just a partial backport of stuff that changed since we backported it (See #14558) before it landed on master branch.

DAOS-16001 placement: fix cases for delay_rebuild (#14557)

---

src/tests/suite/daos_cr.c

It may take sometime for check engine and control plane to recover the status after system restart. Let's wait more in the test logic.

DAOS-15919 test: wait more time after system restart

---

src/tests/ftest/daos_test/rebuild.py
src/tests/ftest/daos_test/rebuild.yaml
src/tests/suite/daos_rebuild.c

Check return code of daos_cont_destroy() call in the test
rebuild_cont_destroy_and_reintegrate(). Also make sure that
test is actually executed at least in daily_regression CI.
Test-tag: test_rebuild_35

DAOS-16016 test: Coverity 2555785 fix and run test_rebuild_35

---

src/tests/ftest/util/run_utils.py
src/tests/ftest/util/soak_test_base.py

Features: soak_smoke
Set clush fanout in run_remote to the max of the default or number of logical cores. This will help in large-scale environments.

DAOS-15955 test: increase clush fanout for run_remote (#14509)

---

src/tests/ftest/daos_vol/bigio.yaml

Using the correct the storage config and pool creation parameters for the test_daos_vol_bigio test.
Test-tag: DaosVolBigIO

DAOS-14517 test: Fixing test_daos_vol_bigio (#14523)

---

src/tests/suite/daos_container.c
src/tests/suite/daos_pool.c

Before this change, daos_test -p pool_op_retry() and daos_test -c co_op_retry() functions still executed even if fault injection support was disabled in the daos build. In release build testing, the tests then failed since they expected actual fault behavior on the engine side that did not get triggered.
With this change, the FAULT_INJECTION_REQUIRED() macro is invoked at the start of the test functions to skip them.
Test-tag: test_daos_pool test_daos_container
faults-enabled: false

DAOS-16084 test: make FI required for pool/cont retry tests

---

src/chk/chk_leader.c

The chk_bookmark::cb_gen for leader may be refreshed during start checker even if the start process failed for some reason finally. Under such case, we need to recover the chk_bookmark::cb_gen back to its original value (before the failed 'chk start'); otherwise, if some former in-running instance failed current 'chk start', it will affect subsequent 'chk stop' command to stop such instance.

DAOS-15919 chk: rollback generation if failed to start checker

---

src/common/mem.c

in umem_cache_checkpoint(), reset the rc to 0 once so_flush_prep() failed for a chkpt_data, otherwise, the rc could be mistakenly used for so_flush_post() for a prior prepared chkpt_data.

DAOS-16091 umem: reset rc properly (#14621)

---

src/tests/ftest/control/ms_failover.yaml

Adding 60 seconds to the control/ms_failover.py test_ms_failover test timeout to avoid intermittent VM test timeouts.
Test-tag: test_ms_failover

DAOS-16103 test: Increase test_ms_failover test timeout

---

src/tests/ftest/control/ms_failover.yaml

Adding 60 seconds to the control/ms_failover.py test_ms_failover test timeout to avoid intermittent VM test timeouts.
Test-tag: test_ms_failover

DAOS-16103 test: Increase test_ms_failover test timeout (#14656)

---

src/tests/suite/daos_extend_simple.c

In release 2.6 RC1 testing certain daos_test -B (extend_simple)
cases failed (EXTEND6, EXTEND8, EXTEND14). It was found that, although
some extend tests use fault injection via dfs_extend_internal(), they
did not invoke FAULT_INJECTION_REQUIRED(). This can result in
unpredictable execution (e.g., hangs) when running with a daos build
whose BUILD_TYPE=release.
This change adds the FAULT_INJECTION_REQUIRED() macro call,
and makes some minor changes to the test code to make the output
reflect what steps the test executes - to facilitate debugging.
Test-tag: test_daos_extend_simple
faults-enabled: false

DAOS-15930 test: extend_simple add FI required macro call

---

src/tests/ftest/deployment/agent_failure.py
src/tests/ftest/deployment/agent_failure.yaml

Use EC_16P2GX instead of SX.
In the test yaml, use base block and child block to support different IOR parameters.
Test-tag: test_agent_failure test_agent_failure_isolation

DAOS-16040 test: Agent failure Aurora support - Use EC object class

---

src/client/dfuse/pil4dfs/int_dfs.c
src/tests/suite/dfuse_test.c

sizeof() does not work for a non-constant string variable inside a loop. strlen() should be used.
Also let stat() and its variants fail if path is empty as glibc does.

DAOS-16141 client: strlen() to replace sizeof() for a string variable

---

src/common/btree.c

DAOS-16078 common: fix a Coverity issue

---

src/control/build/context.go
src/control/build/context_test.go
src/control/build/errors.go
src/control/lib/control/interceptors.go
src/control/lib/control/rpc.go
src/control/lib/control/rpc_test.go

The upstream compatibility policy requires that admin clients
(e.g. dmg, Jumpbox) must be the same version as daos_server. In
our environment, this hard requirement may not make as much sense.
This commit adds a small workaround that allows the control client
to masquerade as whichever version the server reports.
Change-Id: I2a170bddf3ee62ede082da10939510880a6702ac

b/352550886 control: Allow Jumpbox to contact servers regardless of version

---

src/cart/utils/memcheck-cart.supp

DAOS-16228 test: update suppressions for NLT again

---

debian/changelog
utils/rpms/daos.spec

Add pciutils-devel requirement for client-tests package. Specifically needed for the dfuse/daos_build.py test

DAOS-16215 test: add pciutils-devel requirement for client-tests

---

src/pool/srv_pool.c

- pool_upgrade_props should take care of ds_pool_prop_svc_ops_{num,max} too.
- pool_upgrade_props modifies ds_pool_prop_svc_ops_{enabled,age,max}, which are cached by pool_svc. It must also update the cached values too.
- read_db_for_stepping_up should only access ds_pool_prop_svc_ops_{enabled,age,max} when the pool global version is high enough. If one of the properties is expected but absent, it should be an error; recovering the value to 0 may not be desirable.
Features: pool

DAOS-16037 pool: Fix upgrade for svc_ops

---

src/control/lib/hardware/cart/cart_test.go
src/control/lib/hardware/cart/ucx.go
src/control/lib/hardware/cart/ucx_test.go

- Include the original UCX transport name (e.g. "ucx+rc_verbs") in the list of accepted UCX providers, alongside the aliases (e.g. "ucx+rc_v", "ucx+rc").

DAOS-16159 control: Accept UCX full transport names

---

src/control/cmd/daos_agent/config_test.go
src/control/cmd/daos_agent/infocache.go
src/control/cmd/daos_agent/infocache_test.go
src/control/cmd/daos_agent/mgmt_rpc.go
src/control/cmd/daos_agent/mgmt_rpc_test.go
src/control/cmd/daos_agent/security_rpc.go
src/control/cmd/daos_agent/security_rpc_test.go
src/control/lib/cache/cache.go
src/control/lib/cache/cache_test.go
src/control/security/auth/auth_sys.go
src/control/security/auth/auth_sys_test.go
src/control/security/config.go
utils/config/daos_agent.yml

On heavily-loaded client nodes where many processes are being
launched by the same user or users, the admin may optionally
enable the credential cache in the agent in order to lower
agent overhead caused by generating identical credentials
for each process owned by a user. The agent-generated
credential is presented by the client process during pool/container
connection and is used to evaluate ACL permissions for
that connection.
Example config:
credential_config:
cache_expiration: 1m

DAOS-15874 control: Add optional credential cache to agent (#14412)

---

src/vos/vos_internal.h
src/vos/vos_obj.c
src/vos/vos_tree.c

In tree_open_create(), address issues with interoperability:
- When handling cases where a subtree might have been created by an older pool version and the dkey is not flat, ensure usage of KREC_BF_BTR.
- Consider not only the SUBTR_EVT flag but also KREC_BF_NO_AKEY for existing formats.

DAOS-16210 vos: Interoperability fix for flat dkey

---

src/cart/crt_group.c
src/client/api/init.c
src/pool/cli.c
src/pool/rpc.c
src/pool/rpc.h
src/pool/srv_internal.h
src/pool/srv_target.c

On some providers (ofi/ucx+verbs) establishing the qp can be expensive and better done on pool connection rather than first IO. This add a new env variable D_POOL_WARMUP to enable that process of the client process establishing a connection with a new RPC that does a 4k bulk transfer too.
Signed-off-by: Johann Lombardi johann.lombardi@gmail.com
Signed-off-by: Xuezhao Liu xuezhao.liu@intel.com
Signed-off-by: Mohamad Chaarawi mohamad.chaarawi@intel.com

DAOS-14311 pool: add pool warmup RPC + bulk on connect (#14669)

---

src/container/srv_container.c

- **DAOS-16168 build: Ignore scons version deprecation (#14715) (#14717)**
- **DAOS-16214 container: Ensure Correct Protocol Version is Passed to cont_create_in_get_data() (#14757)**

Merging release/2.6 into google/2.6

---

src/tests/suite/dfs_unit_test.c

In some cases one of the servers has a time stamp that is some microseconds different from the client. If that happens we can see this issue in the mtime and ctime test to make it look like we went back in time. Because the ctime reported from the dfs_osetattr() is the one on the client node, and it’s comparing to an mtime value that was obtained from an hlc obtained from the server side. So I will update the test to sleep for 10 ms to avoid such issue.
Test-tag:test_daos_dfs_unit

DAOS-16234 test: add a 10 ms sleep in the dfs time test 

---

src/control/build/context.go
src/control/build/context_test.go
src/control/build/errors.go
src/control/lib/control/interceptors.go

Allow the control client to report a version other than the
static value embedded at build time. Enables some nonstandard
use cases where Control API users will take responsibility
for version interoperability without code changes.
Change-Id: I0ce6ddbf2c742ce9c8dab9e21e37cd5ea8c5f5b3

DAOS-16250 control: Allow control client version override

---

src/cart/utils/memcheck-cart.supp

Added some more Go runtime suppressions. I've added counterparts for all functions already on the list, as well as the false positives that have been recently spotted.

DAOS-16238 utils: Add valgrind suppressions for Go runtime

---

docs/release/release_notes.md
docs/release/support_matrix.md
docs/release/upgrading.md
docs/user/mpi-io.md
src/tests/suite/dfs_unit_test.c

- **DAOS-9355 doc: first draft of DAOS 2.6 release notes (#14820)**
- **DAOS-16162 doc: add information on MPI-IO daos: prefix (#14794) (#14811)**
- **DAOS-16234 test: add a 10 ms sleep in the dfs time test (#14795)**

Merge upstream/release/2.6 into upstream/google/2.6

---

src/cart/crt_context.c
src/cart/crt_group.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h

In rare corner cases an rpc could end up being on both temp submit and timeout lists, causing corruption of one or the other.
submit list is populated from wait_q list, while timeout list is populated when rpc is cancelled or times out.
Fix:
- Separated timeout and submit list links in rpc_priv
- Added additional check to prevent timed out or cancelled rpcs from being added to submitted list.
- timed out or cancelled rpcs will be no-ops now in dispatch_rpc()
- Added ref counting to between submit list population and dispatching of rpcs
- Early checks in group lookup to avoid looking up CRT_NO_RANK/-1
- extra debug info when uri lookups fail

DAOS-16107 cart: submit vs timeout list

---

src/control/server/mgmt_pool.go

This patch addresses a corner case where a leadership change may occur while a pool is in the Destroying state. During checkPools, if the pool is in a Destroying state, the MS will attempt to destroy the pool. The top level PoolDestroy method attempted to wait for leadership step-up to finish, but was needed in order for step-up to complete.
It is okay to skip the leadership check for PoolDestroy in this case. Leadership was already checked at the beginning of checkPools.

DAOS-16103 control: Avoid deadlock during leadership change (#14781)

---

src/client/dfuse/pil4dfs/int_dfs.c
src/tests/suite/dfuse_test.c

To intercept function fdatasync() in libpil4dfs.

DAOS-16286 client: intercept fdatasync()

---

src/cart/crt_rpc.c

- Internal URI_LOOKUP rpc to inherit original RPC timeout if set

DAOS-16226 cart: URI_LOOKUP rpc to inherit the original RPC timeout

---

src/tests/ftest/dfuse/daos_build.py

Try to build with the SHA under test if possible in the dfuse/daos_build.py test.

DAOS-15613 test: build current SHA in daos_build.py (#14796)

---

src/tests/ftest/util/launch_utils.py

Use subprocess.run instead of run_local so test output is printed while running.

DAOS-16295 test: fix streaming stdout when running launch.py locally

---

src/client/dfuse/pil4dfs/int_dfs.c
src/tests/suite/dfuse_test.c

DAOS-16286 client: intercept fdatasync() (#14835)

---

src/cart/utils/memcheck-cart.supp

Added some more Go runtime suppressions. I've added counterparts for all functions already on the list, as well as the false positives that have been recently spotted.

DAOS-16238 utils: Add valgrind suppressions for Go runtime (#14823)

---

src/cart/crt_context.c
src/cart/crt_hg.c
src/cart/crt_init.c
src/cart/crt_internal_types.h
src/tests/ftest/cart/no_pmix_multi_ctx.c

- parse out domain similarly to interface for multi-interface case
- fix issue with multi-interface and cxi workaround 
- treat not set and set to empty as the same for domain/interface
- update test

DAOS-16300 cart: Parse domain properly for multi-interface case

---

src/control/cmd/daos/pool.go
src/control/cmd/dmg/pool.go
src/control/cmd/dmg/pool_test.go

Running `(daos|dmg) pool query-targets` with just a rank
argument should query all targets on that rank.

DAOS-16013 tools: Query all pool targets by default (#14783)

---

src/control/lib/daos/api/api.go
src/control/lib/daos/api/system.go

Apparently these are needed on Ubuntu.
Change-Id: Ieb0446760f0b53e2f09feeae0226ea26dd455d58

DAOS-16313 build: Add explicit linker flags to lib/daos/api

---

src/tests/ftest/control/daos_agent_config.py
src/tests/ftest/util/agent_utils.py

Recent support for user run daos_agent in the test harness enabled always creating the runtime_dir, but this causes the test_daos_agent_config_basic test to fail when using a list for the runtime_dir value.  This change supports skipping the creation of the runtime_dir for testing purposes.
Test-tag: pr DaosAgentConfigTest

DAOS-16316 test: Disable runtime dir creation for test

---

src/cart/crt_init.c
src/cart/crt_internal_types.h
src/cart/utils/crt_utils.c
src/cart/utils/crt_utils.h
src/tests/ftest/cart/utest/utest_portnumber.c
src/utils/crt_launch/crt_launch.c
src/utils/self_test/self_test.c

Cherry-pick of 2 PRs from master:
993558ea563b6ab833cfa1cbb3b0f35ddf516bbf - env reorg
7f805482bfb27ed50cc8d55fb069f118fe57e906 - bugfix to env reorg
Change to how cart deals with envariables:
- env list is now controlled by CRT_ENV_LIST macro in crt_types_internal.h
- all envs stored in structure generated from CRT_ENV_LST (crrt_genv) now, ENV is read out at crt_env_init() time and env strings deallocated at crt_env_fini().
- accsor functions/macros crt_env_init/fini/get/dump are provided.
- string-type envs no longer need to be freed after retrieval.
- Change cart utility function to populate crt_init_options_t instead of setting and querying env.
With this change, any env to be used will need to appear on the list first, ensuring it gets dumped as well as ensuring proper name usage …

DAOS-15961 cart: Reorganize how envs are handled (#14504)

---

src/cart/crt_group.c
src/tests/ftest/cart/test_group_np_cli.c
src/tests/ftest/cart/test_no_timeout.c

Coverity fixes for DAOS-16287,16288,16289.

DAOS-16288 cart: coverity fixes for 16287,16288,16289 (#14843)

---

src/tests/ftest/dfuse/bash.py
src/tests/ftest/dfuse/bash_dcache.py
src/tests/ftest/dfuse/bash_fd.py
src/tests/ftest/dfuse/daos_build.py
src/tests/ftest/dfuse/mu_perms.py
src/tests/ftest/dfuse/pil4dfs_dcache.py
src/tests/ftest/dfuse/pil4dfs_fio.py
src/tests/ftest/ior/intercept_messages.py
src/tests/ftest/ior/intercept_messages_pil4dfs.py
src/tests/ftest/ior/intercept_multi_client.py

Update il -> ioil for consistency

DAOS-16310 test: consolidate il and ioil tags

---

src/cart/crt_context.c
src/cart/crt_group.c
src/cart/crt_init.c
src/cart/crt_internal.h
src/cart/crt_internal_fns.h
src/cart/crt_internal_types.h

- Reduce burst timeout error prints when multiple rpcs fail at the same time
- Replace error prints with info during rpc state processing, as error is already logged above
- Few cleanups, added crt_gdata_dump() at the end of init.

DAOS-16330 cart: Reduce error logs during timeouts

---

src/cart/README.env
src/cart/crt_hg.c
src/cart/crt_hg.h
src/cart/crt_init.c
src/cart/crt_internal_types.h

DAOS-15914 cart: add D_MRECV_BUF env var to control number of multi-recv buffers

---

src/cart/crt_rpc.c

- If a URI_LOOKUP fails for a target of PROTO_QUERY rpc then avoid performing lookup retries as the caller will retry PROTO_QUERY to a different target on failure anyway.
This should avoid needless retries and errors when an excluded rank is picked as a target of PROTO_QUERY and URI_LOOKUP of it fails (due to it being excluded).

DAOS-16354 cart: Don't retry URI_LOOKUPs for PROTO_QUERY rpc

---

src/common/lru.c

This fix addresses a use-after-free issue in the LRU cache that can occur
in the following scenario:
Considering following case:
ULT1---------------------- ULT2-----------------ULT3
daos_lru_ref_wait_evict()
--cont_child_waitq()`
----wait ref to be 1
------yeild()
---------------------------daos_lru_release()
-----------------------------ref become 1
-----------------------------wakeup()
-------------------------------------------------daos_lru_hold().
---------------------------------------------------drop ref and become 1.
---------------------------------------------------free memory
---->access freed memory
To resolve this issue, only drop ref if daos_lru_hold failed internally to avoid
wakeup() is called twice as well.

DAOS-16306 common: Fix Use-After-Free issue in LRU Cache

---

src/cart/crt_context.c
src/cart/crt_group.c
src/cart/crt_init.c
src/cart/crt_internal.h
src/cart/crt_internal_fns.h
src/cart/crt_internal_types.h

- Reduce burst timeout error prints when multiple rpcs fail at the same time
- Replace error prints with info during state processing, as error is already logged above
- nuke 'No more free indices left' debug message
- cleanup of startup logs

DAOS-16330 cart: Reduce error logs during timeouts (#14905)

---

src/bio/bio_internal.h
src/bio/bio_monitor.c
src/bio/bio_recovery.c
src/bio/bio_xstream.c
src/include/daos_srv/bio.h
src/vos/vos_internal.h
src/vos/vos_io.c
src/vos/vos_obj.c
src/vos/vos_pool.c

When a health device is unplugged, we should keep counting the I/O errors against the device, once the number of I/O errors reached faulty criteria, the unplugged device should be automatically marked as FAULTY and trigger targets exclusion accordingly.

DAOS-16291 bio: auto detect faulty for an unplugged device

---

src/client/dfuse/il/int_posix.c
src/client/dfuse/pil4dfs/int_dfs.c
src/tests/ftest/dfuse/bash.py

Features: ioil pil4dfs
Create network context when a read/write operation is processed.

DAOS-16307 client: Defer creating network context in child processes

---

docs/user/filesystem.md

--disable-wb-caching should be --disable-wb-cache
Doc-only: true

DAOS-16368 doc: Fix typo in dfuse documentation

---

src/common/lru.c

This fix addresses a use-after-free issue in the LRU cache that can occur
in the following scenario:
Considering following case:
ULT1---------------------- ULT2-----------------ULT3
daos_lru_ref_wait_evict()
--cont_child_waitq()`
----wait ref to be 1
------yeild()
---------------------------daos_lru_release()
-----------------------------ref become 1
-----------------------------wakeup()
-------------------------------------------------daos_lru_hold().
---------------------------------------------------drop ref and become 1.
---------------------------------------------------free memory
---->access freed memory
To resolve this issue, only drop ref if daos_lru_hold failed internally to avoid
wakeup() is called twice as well.

DAOS-16306 common: Fix Use-After-Free issue in LRU Cache (#14906)

---

src/client/dfs/cont.c

Calling daos filesystem scan on a posix container not containing any files make the daos scanner command seg faulting.
Clean cherry pick of the PR #14449.

DAOS-15916 dfs: Seg fault with DFS scanner (#14449)

---

src/bio/bio_context.c
src/bio/bio_wal.c
src/bio/bio_wal.h
src/include/daos/mem.h
src/include/daos_srv/bio.h
src/vos/tests/wal_ut.c
src/vos/vos_pool.c

Use user specified backend type when possible, if user specify BMEM V1 backend and try to create a pool with "meta_size > scm_size", turn to use BMEM V2 instead.
Store the per-pool backend type in meta blob header for pool open.

DAOS-16278 vos: per pool backend type

---

src/utils/ctl/cart_ctl.c

- Fix finilization order in the cart_ctl tool, where now a group is destroyed only after the progress has been stopped.
This avoids a segfault that can happen if an RPC is cancelled as part of the 'progress stop' sequence, which then references a group.

DAOS-16340 cart: Fix order of finalize in cart_ctl

---

src/tests/ftest/aggregation/continuous_write.py
src/tests/ftest/aggregation/space_rb.py
src/tests/ftest/deployment/agent_failure.py
src/tests/ftest/deployment/basic_checkout.yaml
src/tests/ftest/deployment/ior_per_rank.yaml
src/tests/ftest/deployment/network_failure.py
src/tests/ftest/deployment/server_rank_failure.py
src/tests/ftest/deployment/target_failure.py
src/tests/ftest/ior/hard.yaml
src/tests/ftest/ior/hard_rebuild.yaml
src/tests/ftest/nvme/enospace.py
src/tests/ftest/nvme/fragmentation.py
src/tests/ftest/nvme/pool_capacity.py
src/tests/ftest/performance/ior_easy.yaml
src/tests/ftest/performance/ior_hard.yaml
src/tests/ftest/rebuild/continues_after_stop.py
src/tests/ftest/server/metadata.py
src/tests/ftest/util/ior_test_base.py
src/tests/ftest/util/ior_utils.py
src/tests/ftest/util/mdtest_test_base.py
src/tests/ftest/util/mdtest_utils.py
src/tests/ftest/util/nvme_utils.py
src/tests/ftest/util/soak_utils.py

support dynamic stonewall file for ior and mdtest by using DAOS_TEST_LOG_DIR
Features: ior mdtest

DAOS-16229 test: support dynamic stonewall file (#14771)

---

src/control/cmd/daos_agent/fabric.go
src/control/cmd/daos_agent/fabric_test.go
src/control/cmd/daos_agent/infocache.go
src/control/cmd/daos_agent/infocache_test.go
src/control/cmd/daos_agent/mgmt_rpc.go
src/control/cmd/daos_agent/mgmt_rpc_test.go

Fabric interfaces defined statically in the daos_agent config file are fundamentally different from those detected via hardware scanning. They don't include information derived from the hardware such as their true device class or fabric provider(s).
This patch adds some rigor to what is ignored regarding these manually-defined interfaces.
- Ignore provider for statically-defined fabric interfaces, as we do not bother detecting it. They are assumed to be compatible with whatever provider the agent is using.
- Silence confusing "no interfaces requested" error from WaitFabricReady by not calling it if there are no interfaces to check.
- Remove some defunct logic related to detecting the provider in the multi-provider case. The agent may only use a single provider. …

DAOS-16352 control: Handle cases with static ifaces

---

src/tests/ftest/util/file_count_test_base.py

Currently, the logic in util/file_count_test_base.py runs IOR with HDF5-VOL with only one object class. The second (and beyond) object class will not run with HDF5-VOL (it runs as a normal IOR). Update line 120 to:
`if api == 'HDF5-VOL':`
so that if multiple object classes are defined in the test yaml, all of them will run with HDF5-VOL.
Test-tag: test_io_sys_admin test_largefilecount test_smallfilecount

DAOS-16381 test: Run IOR with HDF5-VOL with multiple object classes

---

src/common/dav_v2/container_ravl.c
src/common/dav_v2/heap.c
src/common/tests/umem_test_bmem.c
src/vos/vos_pool.c

- The 80% rule for NE buckets will not be applied if the scm_sz is almost equal to meta_sz.
- Corrected the check for toggling between V1 and V2 store type when scm_sz passed  is zero.
- Added assert to catch incorrect computation of chunk_id if zone counts are not set during boot correctly.

DAOS-14416 umem: Handle scm_sz ~ meta_sz with the v2 allocator

---

src/utils/ctl/cart_ctl.c

- Fix finalization order in the cart_ctl tool, where now a group is destroyed only after the progress has been stopped.
This avoids a segfault that can happen if an RPC is cancelled as part of the 'progress stop' sequence, which then references a group.

DAOS-16340 cart: Fix order of finalize in cart_ctl (#14969)

---

src/tests/suite/daos_extend_simple.c

for easier debugging when the test fails, to know what it was trying to do (kill rank, extend, reintegrate, etc.), and where it actually failed.
Test-tag: test_daos_extend_simple

DAOS-15137 test: enhance output of test_daos_extend_simple

---

src/cart/crt_hg.c

- Added explicit assert check for provider_str not being null and removed a conditional check which confused coverity.

DAOS-16407 cart: coverity 2555825 fix

---

src/client/dfuse/il/int_posix.c
src/tests/suite/dfuse_test.c

DAOS-16371 il: do not return unsupported for fputs if ioil is loaded

---

src/engine/server_iv.c
src/pool/srv_iv.c

- ivc_on_get stores random entry_priv_val into priv_entry for many ivc_ent_get implementations. Although not used, this should be avoided.
- ds_iv_done stores pointer to stack variable rc in cb_info->future, which outlives the stack frame of ds_iv_done. Although not used, this pointer is confusing.
- ds_pool_iv_map_update associates the input map buffer with the map version from ds_pool, rather than the input map version. Although this may be fine, we should really not ask for unnecessary trouble/concern.

DAOS-16251 engine: Misc fixes and cleanups

---

src/mgmt/cli_mgmt.c

In dc_mgmt_pool_list, calling wipe_cred_iov on in->pli_cred after calling crt_req_decref on rpc is a use-after-free.

DAOS-16251 mgmt: Fix use-after-free in pool_list

---

src/client/dfuse/pil4dfs/dfs_dcache.c
src/client/dfuse/pil4dfs/int_dfs.c

Hotfix of miscellaneous issues:
- invalid type of atomic_flag
- invalid usage of DL_WARN macro

DAOS-14348 client: GC for pil4dfs dentry cache

---

src/client/dfuse/pil4dfs/int_dfs.c

We observed deadlock in MPI applications on Aurora due to nested calls of zeInit() inside MPI_Init(). daos_init() is involved in such nested calls. This PR intercepts MPI_Init() and avoid running daos_init() inside MPI_Init().

DAOS-16365 client: intercept MPI_Init() to avoid nested call

---

src/tests/ftest/aggregation/dfuse_space_check.yaml
src/tests/ftest/dfuse/sparse_file.yaml
src/tests/ftest/osa/offline_drain.yaml
src/tests/ftest/osa/offline_parallel_test.yaml
src/tests/ftest/osa/online_drain.yaml
src/tests/ftest/util/yaml_utils.py

remove server manager srv_timeout since it is unused
Test-tag: DfuseSpaceCheck SparseFile OSAOfflineDrain OSAOfflineParallelTest OSAOnlineDrain

DAOS-16462 test: remove server manager srv_timeout

---

src/control/lib/telemetry/promexp/util.go
src/control/lib/telemetry/promexp/util_test.go
src/control/security/pem_test.go

These stats metrics should be Counter rather than Gauge,
as their values will only increase.
Also includes a small fix for pem_test.go to set the
test dir permissions explicitly irrespective of umask.
Change-Id: Iaae589189a5fc60b58ce4ba05262763a88956fcf

DAOS-16451 telemetry: Adjust type of (_sum|_sumsquares)

---

src/tests/ftest/util/server_utils.py

display_memory_info was added to debug an issue when starting the servers,
but resolved by #14295.
It is no longer needed and consumes too much log space and time.

DAOS-16457 test: remove display_memory_info

---

src/tests/ftest/control/config_generate_run.py

Update the --control-metadata-path assignment for dmg config generate command to avoid issues cleaning up the files generated.

DAOS-16334 test: Fix permission denied removing temporary test files (#15022)

---

src/tests/ftest/daos_test/dfuse.py
src/tests/ftest/launch.py
src/tests/ftest/pool/destroy.py
src/tests/ftest/recovery/ddb.py
src/tests/ftest/util/agent_utils.py
src/tests/ftest/util/apricot/apricot/test.py
src/tests/ftest/util/collection_utils.py
src/tests/ftest/util/command_utils.py
src/tests/ftest/util/environment_utils.py
src/tests/ftest/util/fault_config_utils.py
src/tests/ftest/util/file_utils.py
src/tests/ftest/util/general_utils.py
src/tests/ftest/util/launch_utils.py
src/tests/ftest/util/server_utils.py
src/tests/ftest/util/systemctl_utils.py

Use agent, control, and server config files placed in the common test directory instead of /etc/daos with a systemctl override configuration file.
Test-tag: pr test_setup_vm DdbTest DaosCoreTestDfuse DestroyTests DaosAgentSupportCollectLogTest DaosServerSupportCollectLogTest

DAOS-16366 test: Use agent/server config files from test directory (#14944)

---

src/tests/ftest/aggregation/dfuse_space_check.yaml
src/tests/ftest/dfuse/sparse_file.yaml
src/tests/ftest/osa/offline_drain.yaml
src/tests/ftest/osa/offline_parallel_test.yaml
src/tests/ftest/osa/online_drain.yaml
src/tests/ftest/util/yaml_utils.py

remove server manager srv_timeout since it is unused
Test-tag: DfuseSpaceCheck SparseFile OSAOfflineDrain OSAOfflineParallelTest OSAOnlineDrain

DAOS-16462 test: remove server manager srv_timeout (#15029)

---

src/tests/ftest/util/environment_utils.py

When including the local host in the default interface selection a difference in ib0 speeds will cause the logic to select eth0 and then the tcp provider.
Test-tag: test_setup test_setup_vm

DAOS-16484 test: Exclude local host in default interface selection

---

src/client/dfs/dfs_internal.h
src/client/dfs/mnt.c
src/include/daos_obj.h

We've noticed that with sequential order, object placement is poor.
We get 40% fill for 8GiB files with 25 ranks and 16 targets per rank
with EC_2P1G8.  With this patch, we get a much better distribution.
This patch adds the following:
1. A function for cycling oid.hi incrementing by a large prime
2. For DFS, randomize the starting value
3. Modify DFS to cycle OIDs using the new function.

DAOS-16445 client: Add function to cycle OIDs non-sequentially

---

src/client/dfs/dfs_internal.h
src/client/dfs/mnt.c
src/include/daos_obj.h

We've noticed that with sequential order, object placement is poor.
We get 40% fill for 8GiB files with 25 ranks and 16 targets per rank with EC_2P1G8. With this patch, we get a much better distribution.
This patch adds the following:
1. A function for cycling oid.hi incrementing by a large prime
2. For DFS, randomize the starting value
3. Modify DFS to cycle OIDs using the new function.
Change-Id: I4b35ba1b3e2285f760d3be8db9e5bc724f24d772

DAOS-16445 client: Add function to cycle OIDs non-sequentially (#14999)

---

src/client/dfs/obj.c

If user creates a container without --file-oclass, the get_info call was returning the default oclass of a directory for both file and directory creation oclass on daos fs get-attr for a parent dir. Fix that to properly use the enum types for default scenario.

DAOS-16272 dfs: fix get_info returning incorrect oclass

---

src/common/btree.c
src/include/daos/btree.h
src/include/daos/mem.h
src/include/daos_srv/evtree.h
src/tests/ftest/util/telemetry_utils.py
src/vos/evtree.c
src/vos/tests/vts_io.c
src/vos/vos_aggregate.c
src/vos/vos_gc.c
src/vos/vos_internal.h
src/vos/vos_io.c
src/vos/vos_layout.h
src/vos/vos_obj.c
src/vos/vos_obj.h
src/vos/vos_obj_cache.c
src/vos/vos_obj_index.c
src/vos/vos_query.c
src/vos/vos_tree.c

- Introduced new durable format 'vos_obj_p2_df' for the md-on-ssd phase2
object, at most 4 evict-able bucket IDs could be stored.
- Changed vos_obj_hold() & vos_obj_release() to pin or unpin object
respectively.
- Changed the private data of VOS dkey/akey/value trees from 'vos_pool' to
'vos_object', the private data will be used for allocating/reserving from
the evict-able bucket.
- Move the vos_obj_hold() call from vos_update_end() to vos_update_begin()
for the phase2 pool, reserve value from the object evict-able bucket.
TODO:
- Reorg GC code to pre-load objects before starting transaction.
- Reorg DTX commit code to pre-load objects before starting transaction.
- Reorg multiple-objects tx code to pre-load objects.
- Improve engine scheduler to take both non-evict-able & evict-able …

DAOS-14317 vos: initial changes for the phase2 object pre-load

---

src/client/dfuse/pil4dfs/int_dfs.c

We observed deadlock in MPI applications on Aurora due to nested calls of zeInit() inside MPI_Init(). daos_init() is involved in such nested calls. This PR intercepts MPI_Init() and avoid running daos_init() inside MPI_Init().

DAOS-16365 client: intercept MPI_Init() to avoid nested call (#14992)

---

src/client/dfs/obj.c

If user creates a container without --file-oclass, the get_info call was returning the default oclass of a directory on daos fs get-attr. Fix that to properly use the enum types for default scenario.

DAOS-16272 dfs: fix get_info returning incorrect oclass (#15048)

---

src/common/lru.c
src/container/srv_target.c
src/include/daos/lru.h

while destroying a container, cont_child_destroy_one() releases its own refcount before waiting, if another ULT releases its refcount, which is the last one, wakes up the waiting ULT and frees it ds_cont_child straightaway, because no one else has refcount.
When the waiting ULT is waken up, it will try to change the already freed ds_cont_child.
This patch changes the LRU eviction logic and fixes this race.

DAOS-15863 container: fix a race for container cache

---

src/tests/ftest/dfuse/ioctl_pool_handles.yaml

The dfuse/ioctl_pool_handles.py test is overloading the VM so reduce the number of engine targets.
Test-tag: test_ioctl_pool_handles

DAOS-16471 test: Reduce targets for ioctl_pool_handles.py (#15063)

---

src/tests/ftest/util/environment_utils.py
src/tests/ftest/util/network_utils.py

Allow selecting a default interface that is running at a different speed on different hosts.  Primarily this is to support selecting the ib0 interface by default when the launch node has a slower ib0 interface than the cluster hosts.
Test-tag: test_setup test_setup_vm

DAOS-16484 test: Support mixed speeds when selecting a default interface

---

src/tests/ftest/util/server_utils.py

display_memory_info was added to debug an issue when starting the servers, but resolved by #14295.
It is no longer needed and consumes too much log space and time.

DAOS-16457 test: remove display_memory_info (#15031)

---

src/tests/ftest/aggregation/dfuse_space_check.py
src/tests/ftest/datamover/posix_meta_entry.py
src/tests/ftest/datamover/posix_symlinks.py
src/tests/ftest/deployment/critical_integration.py
src/tests/ftest/dfuse/sparse_file.py
src/tests/ftest/util/data_mover_test_base.py
src/tests/ftest/util/ior_test_base.py

replace usage of IorTestBase.execute_cmd with run_remote
Test-tag: DfuseSpaceCheck DmvrPosixMetaEntry DmvrPosixSymlinks critical_integration SparseFile

DAOS-16509 test: replace IorTestBase.execute_cmd with run_remote

---

src/common/lru.c
src/container/srv_target.c
src/include/daos/lru.h

* DAOS-15863 container: fix a race for container cache
while destroying a container, cont_child_destroy_one() releases its own refcount before waiting, if another ULT releases its refcount, which is the last one, wakes up the waiting ULT and frees it ds_cont_child straightaway, because no one else has refcount.
When the waiting ULT is waken up, it will try to change the already freed ds_cont_child.
This patch changes the LRU eviction logic and fixes this race.

DAOS-15863 container: fix a race for container cache (#15038)

---

src/control/cmd/daos/pretty/selftest.go
src/control/cmd/daos/pretty/selftest_test.go
src/control/lib/daos/selftest.go
src/control/lib/daos/selftest_test.go

The previous default of 1MiB isn't helpful at large scales.
Use a default of 1KiB to get faster results and a better
balance between raw latency and bandwidth.
Also include calculated rpc throughput and bandwidth in
JSON output.
Change-Id: Ie033d7a4c2df15d3d54a4d0e3f0af812dfc84d1f

DAOS-16304 tools: Adjust default RPC size for net-test

---

ci/gha_functions.sh

SRE-2408 ci: Increase timeout (to 15 minutes) for system restore

---

src/tests/ftest/util/systemctl_utils.py

Handle unexpected output when parsing the systemctl service file.
Test-tag: HarnessCoverageTest

DAOS-16560 test: Improve get_service_file()

---

src/tests/ftest/ior/small.yaml

ior/small.py is failing because the test doesn't provide enough opportunities for RPC retries. To increase RPC retries, decrease crt_timeout in the test yaml to 10 from 60.
Test-tag: test_ior_small

DAOS-16468 test: ior/small.py - Decrease crt_timeout to 10

---

src/control/lib/hardware/hwprov/defaults.go
src/control/server/instance_storage_rpc.go

Commit 21450930f4 added a new pciutils package that provides
bindings for the library so that the server can interrogate
PCI device status. The work also included a change to the
hwprov package that forces all users of hwprov to pull in
libpci, even though only the server needs it. This commit
changes the server to pull in the pciutils package directly
and removes the dependency from other users of hwprov.
Change-Id: Iec155fe4b6f16ddad421226200617ecd5700aa76

DAOS-16570 control: Remove non-server dependency on libpci

---

src/tests/ftest/telemetry/wal_metrics.py

Increase the upper expected bounds for the
engine_pool_checkpoint_dirty_pages_samples metric.

DAOS-16480 test: Increase expected range for dirty_pages metric

---

src/tests/ftest/datamover/copy_procs.py
src/tests/ftest/datamover/dst_create.py
src/tests/ftest/datamover/large_dir.py
src/tests/ftest/datamover/large_file.py
src/tests/ftest/datamover/negative.py
src/tests/ftest/datamover/obj_large_posix.py
src/tests/ftest/datamover/obj_small.py
src/tests/ftest/datamover/posix_meta_entry.py
src/tests/ftest/datamover/posix_preserve_props.py
src/tests/ftest/datamover/posix_subsets.py
src/tests/ftest/datamover/posix_symlinks.py
src/tests/ftest/datamover/posix_types.py
src/tests/ftest/datamover/serial_large_posix.py
src/tests/ftest/datamover/serial_small.py
src/tests/ftest/deployment/basic_checkout.py
src/tests/ftest/util/data_mover_test_base.py

Replace DataMoverTestBase.create_pool with self.get_pool
Test-tag: BasicCheckout BasicCheckoutDm DmvrCopyProcs DmvrDstCreate DmvrLargeDir DmvrNegativeTest DmvrObjLargePosix DmvrObjSmallTest DmvrPosixLargeFile DmvrPosixMetaEntry DmvrPosixSubsets DmvrPosixSymlinks DmvrPosixTypesTest DmvrPreserveProps DmvrSerialLargePosix DmvrSerialSmall datamover

DAOS-15776 test: remove DataMoverTestBase.create_pool

---

src/tests/ftest/deployment/basic_checkout.yaml
src/tests/ftest/performance/mdtest_easy.yaml
src/tests/ftest/performance/mdtest_hard.yaml

Use a dynamic stonewall file with mdtest instead of hardcoded path.

DAOS-16550 test: use correct stonewall file with mdtest

---

src/control/server/config/server.go
src/control/server/config/server_test.go
src/control/server/storage/bdev.go
src/control/server/storage/bdev_test.go

DMA buffer allocations may fail for single target count due to
insufficient hugepages available. Increase minimum number of hugepages
for single target count when in PMem mode.
Feature: control

DAOS-16482 control: Increase min hugepages for single tgt count

---

src/tests/ftest/deployment/io_sys_admin.py
src/tests/ftest/deployment/io_sys_admin.yaml

Support running independent io sys admin steps from the yaml.

DAOS-16584 test: Support running independent io sys admin steps

---

src/control/cmd/daos_agent/infocache.go
src/control/cmd/daos_agent/main.go
src/control/cmd/daos_agent/network.go
src/control/cmd/daos_agent/start.go
src/control/cmd/daos_server/auto.go
src/control/cmd/daos_server/main.go
src/control/cmd/daos_server/network.go
src/control/cmd/daos_server/storage_utils.go
src/control/common/cmdutil/topology.go
src/control/lib/hardware/defaults/network/defaults.go
src/control/lib/hardware/defaults/network/defaults_test.go
src/control/lib/hardware/defaults/topology/defaults.go
src/control/lib/hardware/defaults/topology/defaults_test.go
src/control/lib/support/log.go
src/control/server/ctl_network_rpc.go
src/control/server/instance_storage_rpc.go
src/control/server/server.go

The hwprov package was created to provide default
constructors for users of the hardware packages and
to avoid import cycles.
This commit refactors the monolithic hwprov package
into smaller packages that encourage better separation
of concerns and reduces the possibility that a user
of one package will inadvertently pull in unnecessary
dependencies required for another package.
Change-Id: Ib55576a8dda9e679c117cc204eeb1ee31314944a

DAOS-16570 control: Break up hwprov package

---

src/control/lib/control/pool.go
src/control/lib/control/pool_test.go

In some API use cases, the PoolCreate RPC may be invoked
by different processes. Allowing the same pool UUID to be
supplied as part of the create makes the operation
idempotent in these scenarios. This commit does not
change the dmg UI.
Change-Id: I41f0dbbe80f36d4baf56c25d3f9f04063468b56d

DAOS-16292 control: Allow optional pool UUID for Create API

---

src/tests/ftest/daos_test/suite.py
src/tests/ftest/harness/skip_list.py
src/tests/ftest/tags.py

Check that test_ tags are only used specifically for the one method they tag.

DAOS-16548 test: add ftest lint check for invalid test_ tag

---

src/container/srv_target.c
src/include/daos_srv/container.h

- Don't allow multiple callers to destroy the same container, later call should get EBUSY
- Remove the loop in cont_child_destroy_one(), because it will wait for refcount dropping to zero, the loop is useless now.

DAOS-16559 container: return EBUSY for container being destroyed

---

src/tests/suite/daos_cr.c

When running the recovery/cat_recov_core.py in release builds the tests should be skipped as they require fault injection.
Test-tag: CatRecovCoreTest

DAOS-16169 test: Skip recovery tests requiring fault injection

---

src/tests/suite/daos_cr.c

When running the recovery/cat_recov_core.py in release builds the tests should be skipped as they require fault injection.
Test-tag: CatRecovCoreTest

DAOS-16169 test: Skip recovery tests requiring fault injection (#15159)

---

src/common/dav_v2/dav_iface.c
src/common/dav_v2/dav_v2.h
src/common/mem.c
src/include/daos/mem.h
src/include/daos_srv/vos.h
src/mgmt/srv_drpc.c
src/mgmt/srv_target.c
src/vos/vos_pool.c

The scm and meta sizes for vos are now aligned-up to 16M for pools using phase 2 allocator.

DAOS-16591 mgmt, vos, common: Align scm/meta size

---

utils/cq/pylintrc
utils/cq/requirements.txt

DAOS-16613 cq: update pylint to 3.3.0

---

src/vos/vos_gc.c
src/vos/vos_internal.h
src/vos/vos_io.c
src/vos/vos_obj_cache.c

- Clear dth before yield, restore dth after back from yield.
- Use correct object pointer for the SCM reserve on update code path.
- Use telemetry gauge interface instead of counter interface for page stats.

DAOS-16569 vos: fix few defects

---

Jenkinsfile
utils/node_local_test.py

DAOS-16153 test: Do not run NLT fi tests for release builds.

---

site_scons/prereq_tools/base.py
src/tests/SConscript

Client and server tests require different packages. Separate test target so it doesn't imply client or server.  It requires one or the other but this
allows building just client or server tests.

DAOS-16629 build: Allow separate test builds

---

src/common/dav_v2/heap.c
src/common/dav_v2/tx.c

Multiple ULTs calling dav_allot_mb_evictable_v2() at the same time was causing incorrect update of active evictable mb and mb->qptr. This was due to heap_create_evictable_mb() yielding as part of lw_tx_end() call. The new fix ensures that call to heap_get_evictable_mb() is serialized between multiple ULTs.

DAOS-16633 common: SEGV in heap_mbrt_incrmb_usage()

---

src/tests/ftest/recovery/ddb.py
src/tests/ftest/slurm_setup.py
src/tests/ftest/util/run_utils.py

Make timeout in get_clush_command per host instead of for all hosts.
Test-tag: soak_smoke DdbTest pr,vm

DAOS-16298 test: improve get_clush_command timeout

---

debian/changelog
debian/control
site_scons/site_tools/go_builder.py
src/control/go.mod
utils/docker/Dockerfile.ubuntu
utils/rpms/daos.spec
utils/scripts/install-ubuntu.sh

- Set Go minimum version to 1.21 in rpm and debian packaging spec files.
- Update scons Go version check to use version in go.mod.
- Add a reminder in go.mod file so we remember the packaging files when bumping the minimum Go version in the future.
- Update Ubuntu 22.04 Dockerfile to get an appropriate version of Go.

DAOS-16621 build: Fix Go versions in rpm/deb packaging

---

src/client/dfuse/il/int_posix.c
src/client/dfuse/pil4dfs/int_dfs.c

After fork(), child process inherits the value of the counter of event queues, d_eq_count in libpil4dfs and ioil_iog.iog_eq_count in libioil. They need to be reset to zero.

DAOS-16628 client: reset eq counter to zero after fork() in IL

---

src/client/dfuse/ops/readdir.c

The dfuse readdir caching feature stats entries returned by dfs readdir that might be legimitely deleted by another process or another node. When this happens, the dfuse code decides to skip the deleted entry, but might leave the readdir entry cache in an inconsistent state causing the following assertion failure in dfuse_dre_drop():
drc->drc_next_offset == expected_offset + 1 || drc->drc_next_offset == READDIR_EOD
This patch fixes the offset in the linked list of cached readdir entries to support skipped entries.
Change-Id: Icbd5abb648110559851002301e758128e4ced2c7

DAOS-13938 dfuse: adjust offset in readdir cache entry list

---

src/client/dfuse/il/int_posix.c
utils/node_local_test.py

Use the ioil statistics to verify read/write counts rather
than just checking for function name.

DAOS-16585 tests: Improve NLT checking of ioil metrics.

---

src/tests/ftest/deployment/disk_failure.py

Remove hw tag from manual tests not expected to work in CI:
- vmd/fault_reintegration.py
- vmd/led.py
- deployment/disk_failure.py

DAOS-16577 test: remove hw tag from some manual tests

---

src/client/dfuse/il/int_posix.c
utils/node_local_test.py

Disable this test non non-el systems until we can add interception.

DAOS-16585 test: disable NLT fstat test for non-redhat systems.

---

src/tests/ftest/server/multiengine_persocket.py
src/tests/ftest/server/multiengine_persocket.yaml

Update the server/multiengine_persocket.py test to use test harness methods to ensure compatability with future test harness updates.  Also add a test_mode option to allow verification of all but the PMem reconfiguration in CI.

DAOS-16566 test: Update server/multiengine_persocket.py (#15127)

---

src/tests/ftest/performance/ior_easy.yaml
src/tests/ftest/performance/mdtest_easy.py
src/tests/ftest/performance/mdtest_easy.yaml
src/tests/ftest/performance/mdtest_hard.py
src/tests/ftest/performance/mdtest_hard.yaml

- Add variants for mdtest with RP_3G1
- Update ec cell size to 1MiB

DAOS-16590 test: misc ftest/performance updates

---

src/tests/ftest/deployment/disk_failure.py

Remove hw tag from deployment/disk_failure.py
since it is not expected to work in CI

DAOS-16577 test: remove hw tag from deployment/disk_failure.py (#15138)

---

src/tests/ftest/datamover/copy_procs.py
src/tests/ftest/datamover/dst_create.py
src/tests/ftest/datamover/large_dir.py
src/tests/ftest/datamover/large_file.py
src/tests/ftest/datamover/negative.py
src/tests/ftest/datamover/obj_large_posix.py
src/tests/ftest/datamover/obj_small.py
src/tests/ftest/datamover/posix_meta_entry.py
src/tests/ftest/datamover/posix_preserve_props.py
src/tests/ftest/datamover/posix_subsets.py
src/tests/ftest/datamover/posix_symlinks.py
src/tests/ftest/datamover/posix_types.py
src/tests/ftest/datamover/serial_large_posix.py
src/tests/ftest/datamover/serial_small.py
src/tests/ftest/deployment/basic_checkout.py
src/tests/ftest/util/data_mover_test_base.py

Replace DataMoverTestBase.create_pool with self.get_pool
Test-tag: BasicCheckout BasicCheckoutDm DmvrCopyProcs DmvrDstCreate DmvrLargeDir DmvrNegativeTest DmvrObjLargePosix DmvrObjSmallTest DmvrPosixLargeFile DmvrPosixMetaEntry DmvrPosixSubsets DmvrPosixSymlinks DmvrPosixTypesTest DmvrPreserveProps DmvrSerialLargePosix DmvrSerialSmall datamover

DAOS-15776 test: remove DataMoverTestBase.create_pool (#15079)

---

src/tests/ftest/recovery/ddb.py
src/tests/ftest/slurm_setup.py
src/tests/ftest/util/run_utils.py

Make timeout in get_clush_command per host instead of for all hosts.
Test-tag: soak_smoke DdbTest pr,vm

DAOS-16298 test: improve get_clush_command timeout (#15113)

---

src/tests/ftest/deployment/basic_checkout.yaml
src/tests/ftest/performance/mdtest_easy.yaml
src/tests/ftest/performance/mdtest_hard.yaml

Use a dynamic stonewall file with mdtest instead of hardcoded path.

DAOS-16550 test: use correct stonewall file with mdtest (#15109)

---

src/tests/ftest/deployment/ior_per_rank.yaml

Test deployment/ior_per_rank fail with 'No space' on some CI clusters. Reduce the requested pool size to accomidate nodes with smaller storage capacity.
Test-tag: test_ior_per_rank

DAOS-16350 test: decrease pool size for ior_per_rank

---

src/chk/chk_vos.c
src/common/lru.c

The VOS sys_db may have multuiple users, such as SMD and CHK.
It is caller's duty to take lock against the VOS sys_db before
accessing it to handle concurrent operations from multiple XS.

DAOS-16488 chk: take sd_lock before accessing VOS sys_db

---

ci/doc_only_change.sh

ci/doc_only_change.sh shall not return 1 if it detects no changes since the last execution (or reference branch).
"Doc-only: false" is no longer needed to fix this problem
Additionally, the `LICENSE` file is treated as documentation.
See: https://github.com/daos-stack/pipeline-lib/pull/446
Signeed-off-by: Tomasz Gromadzki <tomasz.gromadzki@intel.com>

SRE-2509 common: do not skip tests on empty commits

---

src/client/dfuse/il/int_posix.c
src/client/dfuse/pil4dfs/int_dfs.c

After fork(), child process inherits the value of the counter of event queues, d_eq_count in libpil4dfs and ioil_iog.iog_eq_count in libioil. They need to be reset to zero.

DAOS-16628 client: reset eq counter to zero after fork() in IL (#15187)

---

src/control/server/config/server.go
src/control/server/config/server_test.go
src/control/server/storage/bdev_test.go

DMA buffer allocations may fail for single target count due to
insufficient hugepages available. Increase minimum number of hugepages
for single target count when in PMem mode.

DAOS-16482 control: Increase min hugepages for single tgt count (#15115)

---

src/client/dfuse/pil4dfs/int_dfs.c

In the compatible mode of libpil4dfs, write() is done in user mode. We need to let kernel to update file status before calling mmap().
Skip-func-vm-test-leap15: false

DAOS-16556 client: call fstat() before mmap() to update file status in kernel

---

src/common/mem.c
src/vos/vos_gc.c

- Fix race of two concurrent ULTs trying to evict same page.
- Fix race of mapping two pinfo to same page in cache_pin/map_pages()
- Fix error code used for umem_tx_end() in GC.
Signed-off-by: Sherin T George <sherin-t.george@hpe.com>

DAOS-16668 umem: race on page evicting

---

docs/admin/env_variables.md
src/pool/srv_pool.c
src/tests/ftest/util/server_utils_params.py

When multiple engines become unavailable around the same time, if a pool
cannot tolerate the unavailability of those engines, it is sometimes
desired that the pool would not exclude any of the engines. Hence, this
patch introduces a CaRT event delay, tunable via the server-side
environment variable, CRT_EVENT_DELAY, so that the events signaling the
unavailability of those engines will be handled in hopefully one batch,
giving pool_svc_update_map_internal a chance to reject the pool map
update based on the RF check.
When the RF check rejects a pool map change, we should revisit the
corresponding events later, rather than simply throwing them away. This
patch improves this case by returning the events back to the event
queue, and pause the queue handling until next new event or pool map …

DAOS-16653 pool: Batch crt events

---

.github/workflows/trivy.yml
utils/trivy/.trivyignore
utils/trivy/trivy.yaml

Hadoope 3.4.0 has resolved a few CVE issues but introduces new
additionally, enable on-demand scan and scan on final PR merge for proper update to the GitHub Security tab.

DAOS-16673 common: ignore Hadoop 3.4.0 related CVE

---

src/vos/sys_db.c

Then up layer caller can hold sysdb lock recursively and avoid self-deadlock.
Features: PoolCleanupTest PoolListConsolidationTest CatRecovCoreTest

DAOS-16674 vos: create sysdb lock with recursive attribute

---

src/vos/vos_dtx.c

Use 4KB blob for committed DTX table and 16KB for active DTX table. It is more efficient for lower allocator and reduce the possibility of space allocation failure when space pressure.
Simplify vos_dtx_commit logic and code cleanup.

DAOS-16574 vos: shrink DTX table blob size

---

src/control/lib/telemetry/counter.go
src/control/lib/telemetry/duration.go
src/control/lib/telemetry/gauge.go
src/control/lib/telemetry/snapshot.go
src/control/lib/telemetry/telemetry.go
src/control/lib/telemetry/timestamp.go
src/gurt/telemetry.c
src/include/gurt/telemetry_common.h

In rare cases, a reader may attempt to access a telemetry
node after it has been added to the tree, but before it
has been fully initialized. Use an atomic to prevent
reads before the initialization has completed. Unlucky
readers will get a -DER_AGAIN instead of crashing.
Change-Id: I12281a7db7ef70d5f827547af1233b7a6619ae6d

DAOS-16693 telemetry: Avoid race between init/read

---

.github/workflows/landing-builds.yml
debian/changelog
debian/control
site_scons/components/__init__.py
src/control/server/engine/config.go
src/control/server/engine/config_test.go
src/control/server/server.go
src/mgmt/srv_target.c
utils/build.config
utils/rpms/daos.rpmlintrc
utils/rpms/daos.spec
utils/run_utest.py
utils/scripts/install-el8.sh
utils/scripts/install-el9.sh
utils/scripts/install-leap15.sh
utils/scripts/install-ubuntu.sh

This PR prepares DAOS to be used with NDCTL enabled in PMDK, which means:
- NDCTL must not be used when non-DCPM (simulate PMem) - `storage class: "ram"` is used:
`PMEMOBJ_CONF=sds.at_create=0` env variable disables NDCTL features in the PMDK
This change affects all tests run on simulated PMem (e.g. inside VMs).
Some DOAS utility applications may also require `PMEMOBJ_CONF=sds.at_create=0` to be set.
- The default ULT stack size must be at least 20KiB to avoid stack overuse by PMDK with NDCTL enabled and be aligned with Linux page size.
`ABT_THREAD_STACKSIZE=20480` env variable is used to increase the default ULT stack size.
This env variable is set by control/server module just before engine is started.
Much bigger stack is used for pmempool open/create-related tasks e.g. …

DAOS-14408 common: ensure NDCTL not used for storage class `ram`

---

src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go

With this change, when a daos administrator runs dmg system exclude for a given set of engines, the system map version / cart primary group version will be updated. In turn, daos_engines will more immediately detect the "loss" of the administratively excluded engines, update pool maps and perform rebuild. This change supports a use case of a proactive exclusion of ranks that are expected to be impacted by planned maintenance that would cut off connectivity to certain engines.
Features: control ms_membership

DAOS-16650 control: dmg system exclude, update group version

---

utils/ansible/ftest/README.md
utils/ansible/ftest/file/configure-passwd.sh
utils/ansible/ftest/file/install_dev-el8.sh
utils/ansible/ftest/inventory-sample.yml
utils/ansible/ftest/library/daos_hugepages.py
utils/ansible/ftest/tasks/daos_base.yml
utils/ansible/ftest/tasks/daos_clients.yml
utils/ansible/ftest/tasks/daos_dev.yml
utils/ansible/ftest/tasks/daos_servers.yml
utils/ansible/ftest/tasks/el8/clients_dependencies.yml
utils/ansible/ftest/tasks/el8/devs_dependencies.yml
utils/ansible/ftest/tasks/el8/servers_dependencies.yml
utils/ansible/ftest/templates/daos-launch.sh.j2
utils/ansible/ftest/templates/daos-launch_nlt.sh.j2
utils/ansible/ftest/templates/daos-make.sh.j2
utils/ansible/ftest/vars/Rocky8.yml

Miscellaneous inmoprovements allowing to use ansible ftest deloyment script with GCP virtual machines.

DAOS-10146 build: Support of GCP VMs with ansible ftest

---

.github/workflows/linting.yml

Pin isort to v1.1.0 to avoid suprprise changes and because v1.1.1 is not working for us.

DAOS-16720 cq: pin isort to v1.1.0

---

docs/admin/env_variables.md
src/pool/srv_pool.c
src/tests/ftest/util/server_utils_params.py

When multiple engines become unavailable around the same time, if a pool cannot tolerate the unavailability of those engines, it is sometimes desired that the pool would not exclude any of the engines. Hence, this patch introduces a CaRT event delay, tunable via the server-side environment variable, CRT_EVENT_DELAY, so that the events signaling the unavailability of those engines will be handled in hopefully one batch, giving pool_svc_update_map_internal a chance to reject the pool map update based on the RF check.
When the RF check rejects a pool map change, we should revisit the corresponding events later, rather than simply throwing them away. This patch improves this case by returning the events back to the event queue, and pause the queue handling until next new event or pool map …

DAOS-16653 pool: Batch crt events (#15230)

---

src/common/dav_v2/heap.c
src/common/mem.c

Addresses the following issues:
- When an EMB is out of space the allocation will spill over to NEMB. Added a fast fail feature so as to avoid exhaustive search of free memory blocks in EMB. md_test shows performance improvement with this change.
- Reordered the serialization code in EMB creation so as to reduce wait time for ULT requesting EMB. md_test shows performance improvement with this change.
- Addressed a bug in umem_cache_reserve(), where it was sometimes returns -DER_BUSY.

DAOS-16725 common: Fast failpath for allocation in EMB

---

src/tests/ftest/erasurecode/multiple_failure.yaml
src/tests/ftest/erasurecode/rebuild_fio.yaml
src/tests/ftest/util/apricot/apricot/test.py

Prevent accumulating large server log files caused by temporarily enabling the DEBUG log mask while creating or destroying pools.
Test-tag: EcodFioRebuild EcodOnlineMultFail

DAOS-16265 test: Fix erasurecode/rebuild_fio.py out of space (#15020)

---

utils/node_local_test.py

Modifications to utils/node_local_test.py to better control which tests are run and which aren't.
* Added ability to specify multiple --test arguments
* Added ability to exclude specific tests via --exclude-test arg
* Added ability to "parameterize" test names to specify particular variants
* Added ability to exclude previous unnamed tests
POSIX tests were run with two variants: cached and uncached. Test names can now optionally include "_caching_on" and "caching_off" suffices to control which version to run or not run. Names without suffices are automatically expanded.
Note that previously some tests used the the "_with_caching" suffix, so this will change some reported test names.
Use of the needs_dfuse_with_opt and needs_dfuse decorators made interposing on test lists a bit difficult; …

DAOS-16568 tests: Better cmdline control of NLT tests

---

src/control/lib/telemetry/counter.go
src/control/lib/telemetry/duration.go
src/control/lib/telemetry/gauge.go
src/control/lib/telemetry/snapshot.go
src/control/lib/telemetry/telemetry.go
src/control/lib/telemetry/timestamp.go
src/gurt/telemetry.c
src/include/gurt/telemetry_common.h

In rare cases, a reader may attempt to access a telemetry
node after it has been added to the tree, but before it
has been fully initialized. Use an atomic to prevent
reads before the initialization has completed. Unlucky
readers will get a -DER_AGAIN instead of crashing.

DAOS-16693 telemetry: Avoid race between init/read (#15306)

---

src/vos/vos_dtx.c

Use 4KB blob for committed DTX table and 16KB for active DTX table. It is more efficient for lower allocator and reduce the possibility of space allocation failure when space pressure.
Simplify vos_dtx_commit logic and code cleanup.

DAOS-16574 vos: shrink DTX table blob size - b26 (#15220)

---

src/tests/ftest/erasurecode/multiple_rank_failure.py
src/tests/ftest/erasurecode/multiple_rank_failure.yaml
src/tests/ftest/erasurecode/multiple_target_failure.py
src/tests/ftest/erasurecode/multiple_target_failure.yaml

Split the erasurecode/multiple_failure.py into two separate tests to reduce the possibility of a large number of ERR messages in the server log file from preventing other test variants from failing dure to out of space errors.
Test-tag: EcodFioRebuild EcodOnlineMultFail

DAOS-16265 test: Split erasurecode/multiple_failure.py

---

src/vos/vos_dtx.c
src/vos/vos_obj_cache.c

Add missed so_cmp_key() function.

DAOS-16668 vos: missed so_cmp_key()

---

src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go

With this change, when a daos administrator runs dmg system exclude for a given set of engines, the system map version / cart primary group version will be updated. In turn, daos_engines will more immediately detect the "loss" of the administratively excluded engines, update pool maps and perform rebuild. This change supports a use case of a proactive exclusion of ranks that are expected to be impacted by planned maintenance that would cut off connectivity to certain engines.
skip-nlt: true
Features: control ms_membership

DAOS-16650 control: dmg system exclude, update group version (#15288)

---

src/chk/chk_vos.c
src/common/lru.c
src/vos/sys_db.c

The VOS sys_db may have multuiple users, such as SMD and CHK. It is caller's duty to take lock against the VOS sys_db before accessing it to handle concurrent operations from multiple XS.
Features: CatRecovCoreTest

DAOS-16488 chk: take sd_lock before accessing VOS sys_db - b26

---

src/tests/ftest/pool/list_verbose.py

In any case that is not MD-on-SSD phase-2, mem_file_bytes should equal scm_size.
Skip-nlt: true
Test-tag: ListVerboseTest,hw,medium,pool

DAOS-16712 test: Fix list_verbose mem_file_bytes comparison

---

src/control/lib/control/rpc_test.go

The previous change to this test introduced a race in the
context cancellation test case. Safer to just select on
the context done channel or the time after channel.
Change-Id: Idbf4fa69ece13136b5c392a0bf1760c448cc47a0

DAOS-15429 test: Fix racy unit test

---

src/tests/ftest/osa/online_drain.py

Test-tag: online_drain
Test-repeat: 3
Summary: Check for the total space instead of free space similar to offline drain testing to avoid intermittent failures.

DAOS-16710 test: Check for total space instead of free space.

---

src/tests/ftest/control/dmg_pool_query_test.py
src/tests/ftest/pool/list_verbose.py
src/tests/ftest/util/dmg_utils.py

In pool query response (performed implicitly as part of dmg pool list),
expect mem_file_bytes to be zero in PMem mode and equal to scm_size in
MD-on-SSD phase-1 mode (when mem-ratio == 1).
Test-tag: hw,medium,ListVerboseTest

DAOS-16712 test: Add mdonssd cond check to list_verbose

---

src/common/dav_v2/dav_iface.c
src/common/dav_v2/heap.c
src/common/dav_v2/heap.h
src/common/dav_v2/heap_layout.h
src/vos/tests/vts_wal.c

A new tunable, DAOS_MD_ON_SSD_NEMB_PCT is introuced, to define the percentage of memory cache that non-evictable memory buckets can expand to. This tunable will be read during pool creation and persisted, ensuring that each time the pool is reopened, it retains the value set during its creation.

sherintg/vos on blob p2/daos 16763

---

src/client/dfuse/dfuse_core.c

DAOS-16685 dfuse: Change eq poll to use NOWAIT.

---

src/vos/vos_obj_index.c

There is a possible race between aggregation deleting the object tree and discard working on the same
object tree.  Add a check to avoid this race

DAOS-16211 vos: Avoid race condition with discard (#15370)

---

src/client/dfuse/pil4dfs/hook.c
src/client/dfuse/pil4dfs/hook.h
src/client/dfuse/pil4dfs/int_dfs.c
src/client/dfuse/pil4dfs/pil4dfs_int.h

libfabric loads libze_loader.so which calls zeInit(). We observed deadlock due to nested calls when daos_init() is called inside zeInit(). We intercept dlsym() and zeInit() to avoid calling daos_init() inside zeInit(). dlsym(RTLD_NEXT, ) checks returning address to determine caller's module. To maintain expected behavior of dlsym(RTLD_NEXT, ) with our interception, new_dlsym() is implemented with assembly code to use jmp instruction instead of call. dlsym() has been moved from libdl.so to libc.so since version 2.34.

DAOS-16365 client: intercept dlsym() and zeInit() to avoid nested calls

---

debian/changelog
debian/daos-server.install
debian/daos.install
src/client/api/metrics.c
src/gurt/telemetry.c
src/include/gurt/telemetry_common.h
src/utils/daos_metrics/daos_metrics.c
utils/rpms/daos.spec

In cases where the client telemetry has been manually
enabled, daos_metrics should be able to read it as
long as the client's PID is known and the user has
read access to the shared memory segment.
Moves the daos_metrics utility into the common daos
package for use from both server and client sides.
Change-Id: I660dd758314a9c48a486f51647a1b497c8e27bd9

DAOS-16781 client: Allow daos_metrics read via pid

---

src/client/dfuse/SConscript

When STATIC_FUSE=1 is set, the arm build on ubuntu fails because it can't find libfuse3.a.  Just add the expected path to the list of search paths.

DAOS-623 build: Add arm path when looking for fuse

---

debian/daos-server.install
debian/daos.install
src/client/api/metrics.c
src/gurt/telemetry.c
src/include/gurt/telemetry_common.h
src/utils/daos_metrics/daos_metrics.c
utils/rpms/daos.spec

In cases where the client telemetry has been manually
enabled, daos_metrics should be able to read it as
long as the client's PID is known and the user has
read access to the shared memory segment.
Moves the daos_metrics utility into the common daos
package for use from both server and client sides.
Change-Id: Ibdcbb88de450b02bf31513ca7fadf9d73f16bd97

DAOS-16781 client: Allow daos_metrics read via pid (#15448)

---

src/client/dfuse/SConscript

When STATIC_FUSE=1 is set, the arm build on ubuntu fails because it can't find libfuse3.a.  Just add the expected path to the list of search paths.

DAOS-623 build: Add arm path when looking for fuse (#15467)

---

src/tests/ftest/pool/verify_space.py
src/tests/ftest/pool/verify_space.yaml

In the past few passing runs, the test had ~100 sec test time remaining at the end with 600 sec timeout. This means the test usually takes ~500 sec. Set the timeout to
normal test duration * 1.5 = 750 sec
Test-tag: test_verify_pool_space

DAOS-16765 test: pool/verify_space.py - Increase timeout

---

ci/unit/test_nlt_node.sh
src/cart/crt_init.c
utils/ansible/ftest/templates/daos-launch_nlt.sh.j2
utils/node_local_test.py

With tcp provider, using many sockets can cause significant file descriptor usage.  Bump the soft limit, if possible and warn if it appears insufficient.
Valgrind sets hard limit to soft limit, so work around that in NLT.

DAOS-16645 cart: Bump file descriptor limit (#15224)

---

src/control/cmd/dmg/telemetry.go
src/control/lib/control/telemetry_test.go
src/control/lib/daos/telemetry.go
src/control/lib/daos/telemetry_test.go
src/control/lib/telemetry/counter.go
src/control/lib/telemetry/duration.go
src/control/lib/telemetry/gauge.go
src/control/lib/telemetry/histogram.go
src/control/lib/telemetry/promexp/client.go
src/control/lib/telemetry/promexp/client_test.go
src/control/lib/telemetry/promexp/collector.go
src/control/lib/telemetry/promexp/engine_test.go
src/control/lib/telemetry/promexp/histogram.go
src/control/lib/telemetry/promexp/source.go
src/control/lib/telemetry/promexp/util.go
src/control/lib/telemetry/snapshot.go
src/control/lib/telemetry/timestamp.go
src/gurt/telemetry.c
src/gurt/tests/test_gurt_telem_producer.c
src/include/gurt/telemetry_common.h
src/include/gurt/telemetry_producer.h

Update the Prometheus exporter to support passthrough histograms
from native DAOS telemetry format. Fixes a few bugs and inefficiencies
in the native histogram implementation.

DAOS-7203 control: Add histogram support to Prometheus exporter

---

src/vos/vos_aggregate.c

The evt recx trace is used for vos aggregation debugging, and it's currently reset on akey iteration callback, but the akey iteration callback could be skipped in some cases, for example, when evt aggregation hit an aborted recx, it'll start over in evtree level without the recx trace reset, that could lead to integer overflow on the 'int ap_trace_count'.
This patch moved the ap_trace_count reset to merge window open/close to ensure the evt recx trace always being reset properly.

DAOS-16374 vos: integer overflow on evt recx trace

---

src/control/cmd/daos_agent/config.go
src/control/cmd/daos_agent/config_test.go
src/control/cmd/daos_agent/fabric.go
src/control/cmd/daos_agent/fabric_test.go
src/control/cmd/daos_agent/infocache.go
utils/config/daos_agent.yml

Provide an inverse to the existing exclude_fabric_ifaces
directive. In some cases, a given environment will only have
a small number of valid interfaces, so it is simpler to
specify that rather than having to exclude all of the
invalid interfaces.
Change-Id: I0d8445fcc2da267df76856d7f9f9b43eed290599

DAOS-16791 control: Add include_fabric_ifaces to agent config

---

src/client/dfuse/pil4dfs/hook.c
src/client/dfuse/pil4dfs/int_dfs.c

Fix a few minor remaining issues in previous PR intercepting dlsym and zeInit.
1) Use D_ASPRINTF when possible
2) Remove unneeded newline, debugging output, and parentheses.

DAOS-16365 client: use D_ASPRINTF and fix format issues

---

src/control/cmd/dmg/telemetry.go
src/control/lib/control/telemetry_test.go
src/control/lib/daos/telemetry.go
src/control/lib/daos/telemetry_test.go
src/control/lib/telemetry/counter.go
src/control/lib/telemetry/duration.go
src/control/lib/telemetry/gauge.go
src/control/lib/telemetry/histogram.go
src/control/lib/telemetry/promexp/client.go
src/control/lib/telemetry/promexp/client_test.go
src/control/lib/telemetry/promexp/collector.go
src/control/lib/telemetry/promexp/engine_test.go
src/control/lib/telemetry/promexp/histogram.go
src/control/lib/telemetry/promexp/source.go
src/control/lib/telemetry/promexp/util.go
src/control/lib/telemetry/snapshot.go
src/control/lib/telemetry/timestamp.go
src/gurt/telemetry.c
src/gurt/tests/test_gurt_telem_producer.c
src/include/gurt/telemetry_common.h
src/include/gurt/telemetry_producer.h

Update the Prometheus exporter to support passthrough histograms from native DAOS telemetry format. Fixes a few bugs and inefficiencies in the native histogram implementation.

DAOS-7203 control: Add histogram support to Prometheus exporter (#5382)

---

src/tests/ftest/deployment/basic_checkout.py
src/tests/ftest/deployment/basic_checkout.yaml
src/tests/ftest/dfuse/mu_perms.yaml
src/tests/ftest/dfuse/simul.yaml
src/tests/ftest/ior/small.py
src/tests/ftest/ior/small.yaml
src/tests/ftest/util/ior_test_base.py

Update some tests to use unique dfuse mount directory by letting the framework generate one.
Remove mount_dir from run_ior_multiple_variants since it is no longer needed and this level of fine control should be handled per test ideally.
Test-tag: BasicCheckout BasicCheckoutDm DfuseMUPerms IorSmall PosixSimul

DAOS-16662 test: update some tests to use unique dfuse mount

---

src/cart/utils/memcheck-cart.supp

* Add a suppression for Go runtime function racefuncenter.
* Add suppression for rt0_go CGo malloc
Signed-off-by: Kris Jacque <kris.jacque@intel.com>

DAOS-16787 utils: Suppress NLT valgrind false positives (#15478)

---

docs/admin/pool_operations.md
src/control/cmd/daos/pretty/pool.go
src/control/cmd/daos/pretty/pool_test.go
src/control/cmd/dmg/pretty/pool_test.go
src/control/lib/control/pool.go

Update dmg pool list -v tabular output for MD-on-SSD. Change column
titles to describe META and DATA tiers (rather than SCM and
NVME as for PMem mode).
Correct confusing behaviour by making Used and Imbalance table values
in non-verbose output refer to DATA tier always and don’t vary based
on value comparison. With previous implementation the-most-used and
the-most-imbalanced tier value would be shown and different tier
values could be shown in the same row (DAOS-12900).
Hide usage columns in table output if --no-query is set (DAOS-16701).
Hide upgrade and disabled columns if --no-query -v set (DAOS-16296).

DAOS-16328 control: Update dmg pool list for MD-on-SSD

---

src/control/cmd/daos_agent/config.go
src/control/cmd/daos_agent/config_test.go
src/control/cmd/daos_agent/fabric.go
src/control/cmd/daos_agent/fabric_test.go
src/control/cmd/daos_agent/infocache.go
utils/config/daos_agent.yml

Provide an inverse to the existing exclude_fabric_ifaces
directive. In some cases, a given environment will only have
a small number of valid interfaces, so it is simpler to
specify that rather than having to exclude all of the
invalid interfaces.

DAOS-16791 control: Add include_fabric_ifaces to agent config (#15470)

---

site_scons/prereq_tools/base.py

Check patchelf return codes more strictly, only accept
failure for the ond file that fails and only accept one
return code.
This means that any other failure of patchelf will correctly cause
a build failure.

DAOS-16814 build: Add tighter checking to patchelf failures.

---

src/tests/ftest/control/config_generate_run.py
src/tests/ftest/control/daos_agent_config.py
src/tests/ftest/network/cart_self_test.py
src/tests/ftest/util/apricot/apricot/test.py

Support calling register cleanup methods for tests based upon the Test and TestWithoutServers classes. Also remove stopping agents as part of calling TestWithServers.stop_servers() since DAOS-6873 is no longer an issue.
Test-tag: pr daily_regression full_regression

DAOS-16825 test: Support register cleanup for all Test classes

---

src/tests/ftest/control/daos_server_helper.py
src/tests/ftest/control/daos_server_helper.yaml

verify daos_server_helper on server instead of the runner/client. misc cleanup

DAOS-15964 test: verify daos_server_helper on server

---

src/client/dfs/common.c
src/client/dfs/dfs_sys.c
src/include/daos_fs_sys.h
src/tests/suite/dfs_sys_unit_test.c

As a usability enhancement, add a mkdir variant with
the following properties:
* If the directory or any of its parents already exist
and are directories, don't return an error
* If any of the parent directories need to be created,
automatically do so as a prerequisite step to creating
the final child directory
Features: dfs

DAOS-16822 client: Add mkdir_p variant to dfs_sys API

---

debian/daos-client.dirs
debian/daos-client.install
debian/libdaos0.dirs
requirements-utest.txt
src/SConscript
src/client/api/init.c
src/client/dfuse/il/int_posix.c
src/client/dfuse/pil4dfs/int_dfs.c
src/client/pydaos/SConscript
src/client/pydaos/pydaos_shim.c
src/client/pydaos/torch/Readme.md
src/client/pydaos/torch/__init__.py
src/client/pydaos/torch/torch_api.py
src/client/pydaos/torch/torch_shim.c
src/client/setup.py
src/common/misc.c
src/container/cli.c
src/gurt/hash.c
src/include/daos.h
src/include/daos/common.h
src/include/daos/container.h
src/include/daos/pool.h
src/include/gurt/hash.h
src/pool/cli.c
utils/cq/requirements.txt
utils/cq/words.dict
utils/node_local_test.py
utils/rpms/daos.spec

Introducing pydaos.torch module that allows use DAOS POSIX containers
as a datasource for pytorch framework in form of pydaos.torch.Dataset and
pydaos.torch.IterableDataset classes.
Signed-off-by: Denis Barakhtanov <dbarahtanov@enakta.com>

DAOS-16355 client: pydaos.torch module (#15475)

---

src/client/dfs/common.c
src/client/dfs/dfs_sys.c
src/include/daos_fs_sys.h
src/tests/suite/dfs_sys_unit_test.c

As a usability enhancement, add a mkdir variant with
the following properties:
* If the directory or any of its parents already exist
and are directories, don't return an error
* If any of the parent directories need to be created,
automatically do so as a prerequisite step to creating
the final child directory

DAOS-16822 client: Add mkdir_p variant to dfs_sys API (#15526)

---

.github/workflows/ci2.yml
.github/workflows/landing-builds.yml
.github/workflows/linting.yml
.github/workflows/pr-metadata.yml
.github/workflows/version-checks.yml
ci/storage/test_main_storage_prepare_node.sh
ci/unit/test_post_always.sh
src/tests/ftest/scripts/main.sh
utils/scripts/helpers/install_maldet.sh

Update mantic (EOL) to oracular.
Update 22.04 LTS to 24.04 LTS.

DAOS-16833 cq: update GHA ubuntu

---

utils/cq/requirements.txt
utils/githooks/pre-commit.d/71-flake.sh

Update flake8 to 7.1.1.
Adjust githook to work with newer flake8.
Also tested to be backwards compatible with flake8<6

DAOS-16865 cq: update flake8 to 7.1.1

---

.github/workflows/trivy.yml
README.md
utils/trivy/trivy.yaml

- Enable write access to the Security section of the Github project
- Use GHA cache to avoid Trivy scan failures due to overuse of CVEs database results in database download failure
Upgrade `trivy-action` to version 0.28.0 where the caching mechanism is enabled by default.
Enable the debug option in Trivy to be prepared for detailed scan failure analysis
See #15201 for a reference

SRE-2525 ci: Fix Trivy scan upload to the Security tab

---

src/tests/ftest/deployment/ior_per_rank.yaml

Test deployment/ior_per_rank fails with 'No space' on some CI clusters. Reduce the requested pool size to accommodate nodes with smaller storage capacity.
Test-tag: test_ior_per_rank

DAOS-16350 test: decrease pool size for ior_per_rank (#15183)

---

src/tests/ftest/dfuse/root_container.py

Loop retrying the check for the pool free space after destroying half of the containers. If the check doesn't pass within 60 seconds, then fail the test.
Test-tag: test_dfuse_root_container

DAOS-16096 test: Add retry loop for comparing free pool space (#15289)

---

src/tests/ftest/control/config_generate_run.py
src/tests/ftest/control/daos_agent_config.py
src/tests/ftest/network/cart_self_test.py
src/tests/ftest/util/apricot/apricot/test.py

Support calling register cleanup methods for tests based upon the Test and TestWithoutServers classes. Also remove stopping agents as part of calling TestWithServers.stop_servers() since DAOS-6873 is no longer an issue.

DAOS-16825 test: Support register cleanup for all Test classes (#15530)

---

src/tests/ftest/util/job_manager_utils.py
src/tests/ftest/util/soak_test_base.py
src/tests/ftest/util/soak_utils.py

Update soak to support using an internal job scheduler.

DAOS-16167 test: update soak test to use internal job scheduler (#14775)

---

utils/cq/requirements.txt
utils/githooks/pre-commit.d/71-flake.sh

Update flake8 to 7.1.1.
Adjust githook to work with newer flake8.
Also tested to be backwards compatible with flake8<6

DAOS-16865 cq: update flake8 to 7.1.1 (#15575)

---

src/client/dfs/dfs_sys.c
src/tests/suite/dfs_sys_unit_test.c

if a dfs sys mount has caching enabled, disable force removal of dir that does not check for child entries. DFS sys does not evict them from the cache in that case and that can cause namespace corruptions.

DAOS-16863 dfs: disallow force removal of entries with caching

---

docs/admin/pool_operations.md
docs/admin/troubleshooting.md

Add a section on handling unavailable engines.

DAOS-16276 doc: Address engine unavailability (#15456)

---

src/cart/crt_corpc.c
src/cart/crt_rpc.c

reset rc to 0 to avoid unnecessary RPC_DECREF in fail case in crt_req_send.

DAOS-16170 cart: refine corpc fail handling for CRT_RPC_FLAG_CO_FAILOUT

---

src/tests/ftest/control/dmg_pool_query_test.py

Update expected pool_layout_ver in
dmg_pool_query_test/test_pool_query_basic.
Test-tag: test_pool_query_basic

DAOS-16874 tests: Update expected pool_layout_ver

---

src/control/SConscript

Add a requirement to protobufc for building daos control binaries.

DAOS-16889 build: fix finding protobuf

---

src/tests/ftest/deployment/basic_checkout.py
src/tests/ftest/deployment/basic_checkout.yaml
src/tests/ftest/dfuse/mu_perms.yaml
src/tests/ftest/dfuse/simul.yaml
src/tests/ftest/ior/small.py
src/tests/ftest/ior/small.yaml
src/tests/ftest/util/ior_test_base.py

Update some tests to use unique dfuse mount directory by letting the framework generate one.
Remove mount_dir from run_ior_multiple_variants since it is no longer needed and this level of fine control should be handled per test ideally.
Test-tag: BasicCheckout BasicCheckoutDm DfuseMUPerms IorSmall PosixSimul

DAOS-16662 test: update some tests to use unique dfuse mount (#15242)

---

.github/workflows/linting.yml

DAOS-15677 cq: make copyright GHA required

---

src/client/dfs/SConscript
src/client/dfs/common.c
src/client/dfs/dfs_internal.h
src/client/dfs/dir.c
src/client/dfs/io.c
src/client/dfs/metrics.c
src/client/dfs/metrics.h
src/client/dfs/mnt.c
src/client/dfs/obj.c
src/client/dfs/readdir.c
src/client/dfs/rename.c
src/client/dfs/xattr.c
src/control/lib/telemetry/promexp/client.go
src/control/lib/telemetry/promexp/client_test.go
src/control/lib/telemetry/promexp/engine.go
src/control/lib/telemetry/telemetry.go
src/control/lib/telemetry/telemetry_test.go
src/gurt/telemetry.c
src/include/daos/pool.h
src/pool/cli.c
src/tests/ftest/telemetry/basic_client_telemetry.py
src/tests/ftest/telemetry/dfs_client_telemetry.py
src/tests/ftest/telemetry/dfs_client_telemetry.yaml
src/tests/ftest/util/telemetry_utils.py

If metrics are enabled for a POSIX container, create
a new pool/$UUID/container/$UUID/dfs metrics root in
the client telemetry to provide DFS-oriented metrics
(POSIX ops, file I/Os, etc).
Also fixes a bug in the agent code for pruning unused
client telemetry segments.
Features: container telemetry

DAOS-16837 container: Add client-side DFS metrics

---

src/client/dfuse/dfuse.h
src/client/dfuse/ops/open.c
src/client/dfuse/ops/read.c

The file open handle can be freed from under the pre-read. The inode should be used instead.

DAOS-16887 dfuse: use the inode instead of open handle in pre-read

---

src/control/cmd/daos_agent/support.go
src/control/cmd/daos_server/support.go
src/control/cmd/dmg/fi.go
src/control/cmd/dmg/support.go
src/control/cmd/dmg/telemetry.go
src/control/common/file_utils.go
src/control/common/test/utils.go
src/control/drpc/drpc_client_test.go
src/control/lib/control/config.go
src/control/lib/control/config_test.go
src/control/lib/control/control.go
src/control/lib/control/http.go
src/control/lib/control/server_meta_test.go
src/control/lib/hardware/sysfs/provider.go
src/control/lib/hardware/sysfs/provider_test.go
src/control/lib/support/log.go
src/control/lib/support/log_test.go
src/control/pbin/app.go
src/control/pbin/exec_test.go
src/control/security/config_test.go
src/control/security/pem.go
src/control/security/signature_test.go
src/control/server/config/server.go
src/control/server/config/server_test.go
src/control/server/ctl_ranks_rpc.go
src/control/server/storage/bdev/backend_class_test.go
src/control/server/storage/bdev/backend_vmd.go
src/control/system/raft/database_test.go
src/control/system/raft/raft_recovery.go

The ioutil package has been deprecated since Go 1.16
and may be removed in the future. Update the code to
use the standard interfaces.
Also fix a linter warning that is now a compile error
in Go 1.24+ (non-constant format string in call
to *f functions).

DAOS-16886 control: Update deprecated code

---

src/common/dav_v2/dav_iface.c
src/common/dav_v2/dav_v2.h
src/common/dav_v2/heap.c
src/common/dav_v2/heap.h
src/common/dav_v2/palloc.c
src/common/dav_v2/tx.c
src/common/dav_v2/valgrind_internal.h
src/common/mem.c
src/include/daos/mem.h
src/vos/tests/vts_wal.c
src/vos/vos_aggregate.c
src/vos/vos_gc.c

Pre-enabler changes to umem_cache_map routine to enable allocator to mark a non-evictable page as evictable and visa-versa. The allocator will make use of the above changes as follows:
- When all memory blocks in a non-evictable page is marked unused, allocator can mark the entire page as unused and will notify the umem_cache to mark the page as evictable. No further allocations from this memory block will happen from now ownwards.
- Allocator will request the umem_cache to map the page again as non-evictable when there is a need to extend non-evictable region or as evictable page when a new evictable page has to be reserved.

DAOS-16818 common: Evict NE memory bucket when empty - MD_ON_SSD_p2

---

docs/admin/troubleshooting.md
src/control/cmd/daos/pool.go
src/control/common/proto/logging.go
src/control/lib/daos/pool.go
src/control/lib/daos/pool_test.go

The patch landed for DAOS-16477 introduced a regression
in the pool query functionality of the daos tool. This
patch simplifies the pool query logic to retrieve
enabled and disabled ranks. Dead ranks are not available
to the client without pool query protocol changes.

DAOS-16829 client: Fix daos pool query regression

---

src/tests/suite/daos_cr.c

Test-tag: test_daos_cat_recov_core
faults-enabled:  false
Skip-nlt: true

DAOS-16802 tests: properly set fault_injection for CR test - b26

---

src/vos/tests/vts_aggregate.c
src/vos/vos_dtx.c
src/vos/vos_gc.c
src/vos/vos_obj.c
src/vos/vos_obj_index.c

As long as the container is not destroyed, then anytime want to deregister a modification from related active DTX entry (that is usually triggered for vos discard or aggregation), the caller needs to offer container handle to vos_dtx_deregister_record() for locating the DTX entry in active DTX table. Otherwise, if the caller offers empty container handle, then it will cause dangling reference in related DTX entry as to data corruption in subsequent DTX commit or abort.
On the other hand, if the container will be destroyed, then all related DTX entries for such container will be useless any more. We need to destroy DTX table firstly to avoid generating dangling DTX references during destroying the container.

DAOS-16876 vos: set cont parameter when deregister modification from DTX

---

Jenkinsfile

Run functional VM tests on Leap 15.6.

DAOS-16500 test: Move to Leap 15.6

---

src/common/dav_v2/heap.c
src/common/dav_v2/heap.h
src/common/dav_v2/heap_layout.h
src/common/dav_v2/palloc.c
src/common/dav_v2/tx.c
src/common/tests/umem_test_bmem.c
src/vos/tests/vts_wal.c

The DAV_v2 allocator now includes support for Spill Over Evictable Buckets (SOEMB). All global allocations will continue to utilize the standard non-evictable memory buckets, while spillover allocations from evictable memory buckets will be directed to SOEMB. In the current implementation, SOEMB remains locked in the memory cache, similar to the behavior of non-evictable memory buckets.

DAOS-16896 common: Spill Over Evictable Buckets Implementation

---

src/vos/tests/vts_aggregate.c
src/vos/vos_dtx.c
src/vos/vos_gc.c
src/vos/vos_obj.c
src/vos/vos_obj_index.c

As long as the container is not destroyed, then anytime want to deregister a modification from related active DTX entry (that is usually triggered for vos discard or aggregation), the caller needs to offer container handle to vos_dtx_deregister_record() for locating the DTX entry in active DTX table. Otherwise, if the caller offers empty container handle, then it will cause dangling reference in related DTX entry as to data corruption in subsequent DTX commit or abort.
On the other hand, if the container will be destroyed, then all related DTX entries for such container will be useless any more. We need to destroy DTX table firstly to avoid generating dangling DTX references during destroying the container.

DAOS-16876 vos: set cont parameter when deregister modification from DTX - b26

---

.github/workflows/bullseye-coverage.yml
.github/workflows/ci2.yml
.github/workflows/landing-builds.yml
.github/workflows/linting.yml
.github/workflows/ossf-scorecard.yml
.github/workflows/pr-metadata.yml
.github/workflows/rpm-build-and-test-report.yml
.github/workflows/rpm-build-and-test.yml
.github/workflows/trivy.yml

- Bump github/codeql-action from 3.24.9 to 3.27.7 (#15589)
- Bump github/codeql-action from 3.27.7 to 3.27.9 (#15618)
- Bump github/codeql-action from 3.27.9 to 3.28.0 (#15662)
- Bump thollander/actions-comment-pull-request from 2 to 3 (#15590)
- Bump aquasecurity/trivy-action from 0.28.0 to 0.29.0 (#15591)
- Bump codespell-project/actions-codespell to latest (#15592)
- Bump EnricoMi/publish-unit-test-result-action from 1.17 to 2.7 (#15593)
- Bump EnricoMi/publish-unit-test-result-action from 2.7.0 to 2.18.0 (#15660)
- Bump isort/isort-action from 1.1.0 to 1.1.1 (#15594)
- Bump phoenix-actions/test-reporting from 10 to 15 (#15617)
- Bump actions/setup-python from 5.1.0 to 5.3.0 (#15661)
Run-GHA: true

DAOS-16872 cq: Bump GHA versions

---

src/client/dfuse/dfuse_core.c

This operation will never succeed since the file system is already unmounted. Therefore it always returns EBADF from libfuse.
Actually, it should not attempt to do that since dentries will be cleared by kernel at the time of unmounting.
Change-Id: I18eaffc0437d05e5ccc50d0a548451c4837cb1f9
Run-GHA: true

DAOS-16932 dfuse: do not flush dentries at fs stop

---

src/cart/crt_iv.c
src/engine/server_iv.c

Change the debug level of two IV log messages from INFO to DEBUG.

DAOS-16918 iv: change debug level for IV messages

---

src/container/oid_iv.c

the src pointer for on_update() callback is on the stack and should not be saved beyond that call to detect the same current request, because in some cases we can end up with 2 different requests sharing getting the same pointer value. Use the private pointer allocated by the oid iv on_alloc operation instead.

DAOS-16931 container: fix oid iv race with using invalid on_update ptr

---

src/bio/bio_xstream.c

Sys target needs only very limited DMA buffer for the WAL of RDB, we can prealloc only 1 chunk for sys target so that leave more hugepages for regular VOS targets.

DAOS-16866 bio: prealloc less DMA buffer for sys tgt

---

src/object/cli_mod.c

This reverts commit a2819ecd9f785673e78adcb075244b042cdddf32.

Revert "b/360833010 disable punch and stat collectives (#14974)"

---

src/vos/vos_internal.h
src/vos/vos_pool.c

The pool_open() logic maybe yield in VOS, then it is possible that multiple pool_open() sponsors open the same vos pool concurrently. This patch serializes such concurrent pool_open() and handle kinds of race conditions.
Test-tag: pool_list_consolidation,pr

DAOS-16799 vos: handle concurrent pool_open in VOS

---

src/bio/bio_device.c

DAOS-16868 bio: Skip LED reset on absent bdev (#15718)

---

src/cart/crt_hg.c
src/control/server/engine/utils.go
src/include/cart/api.h
src/mgmt/srv_drpc.c
src/mgmt/tests/mocks.c
utils/githooks/commit-msg

Mercury and libfabric are much too spammy to enable at lower
than warning level by default. Mercury does support adjustment
of its log level and logged subsystems at runtime, so this
patch provides access to that functionality from the
existing `dmg server set-logmasks` tool.
Change-Id: Ib04594dde5a7b3f50cce4176759edf1f109c0947

b/390177544 cart: Support dynamic mercury/libfabric loglevels

---

src/container/srv_target.c
src/include/daos_srv/container.h

Check inflight container open, which might be stucked in IV fetch, then the following cont open will just increase the open count, then if the previous container open failed, it will get the assertion failure.
So let's retry if there are inflight container open.

DAOS-16916 container: check inflight open

---

src/client/dfs/SConscript
src/client/dfs/common.c
src/client/dfs/cont.c
src/client/dfs/dfs_internal.h
src/client/dfs/dir.c
src/client/dfs/file.c
src/client/dfs/io.c
src/client/dfs/lookup.c
src/client/dfs/metrics.c
src/client/dfs/metrics.h
src/client/dfs/mnt.c
src/client/dfs/obj.c
src/client/dfs/pipeline.c
src/client/dfs/readdir.c
src/client/dfs/rename.c
src/client/dfs/xattr.c
src/control/lib/telemetry/promexp/client_test.go
src/control/lib/telemetry/promexp/engine.go
src/control/lib/telemetry/telemetry.go
src/control/lib/telemetry/telemetry_test.go
src/gurt/telemetry.c
src/include/daos/pool.h
src/pool/cli.c
src/tests/ftest/telemetry/basic_client_telemetry.py
src/tests/ftest/telemetry/dfs_client_telemetry.py
src/tests/ftest/telemetry/dfs_client_telemetry.yaml
src/tests/ftest/util/telemetry_utils.py
utils/node_local_test.py

If metrics are enabled for a POSIX container, create
a new pool/$UUID/container/$UUID/dfs metrics root in
the client telemetry to provide DFS-oriented metrics
(POSIX ops, file I/Os, etc).
Also fixes a bug in the agent code for pruning unused
client telemetry segments.

DAOS-16837 container: Add client-side DFS metrics (#15544)

---

ci/junit.sh

Fixes a bug that sets the number of result files to 1 if none exist

DAOS-16959 ci: Fix post-provisioning bug

---

src/engine/sched.c
src/vos/vos_aggregate.c

When md-on-ssd phase2 pool runs into space pressure, larger SCAN credits will be used to reduce yield & reprobe on iterating, larger DEL credits will be used to drop more punched objects to GC in one batch, so that GC will likely reclaim more objects when reclaiming a bucket.
Though larger aggregation credits will lower front end I/O performance, it can greatly reduce page misses for GC when free space/page is tight.
This PR also fixed the NE space pressure check, where the sys reserved space should not be taken into account.

DAOS-16640 vos: tune aggregation credits for phase2 pool

---

Jenkinsfile

Increase timeout to avoid issues on slow CI nodes with broadwell.

DAOS-16958 ci: increase timeout for Unit Test with memcheck

---

src/pool/srv_pool.c

It has been observed that pool_svc_step_up_cb may encounter a
-DER_NOTLEADER and pass it to ds_pool_failed_add. This error is a
replica error and may be transient; it doesn't indicate that the PS is
unavailable. This patch addresses the observed scenario by replacing the
ds_pool_failed_add call from pool_svc_step_up_cb with a special
up-but-with-error mode for the PS, which can only serve requests by
returning an error.
- Add pool_svc.ps_error for indicating the special up-but-with-error
mode. Check and return it in pool_svc_lookup_leader. Handle it
specially in callers of pool_svc_lookup.
- Use this new mode only for a conservative set of errors. Including
an error by mistake is worse than missing an error.
- Add pool UUIDs to a few log messages to make future debugging
easier.
The …

DAOS-16878 pool: Reduce unexpected DER_NO_SERVICEs

---

.dockerignore
site_scons/prereq_tools/base.py
utils/build.config
utils/docker/Dockerfile.el.8
utils/docker/Dockerfile.el.9
utils/docker/Dockerfile.leap.15
utils/docker/Dockerfile.ubuntu
utils/mrecv_err.patch
utils/ofi_tcp.patch

Two patches from Jerome to fix progress hang

DAOS-16971 utils: two patches from Jerome to fix progress hang

---

src/pool/srv_pool.c

It has been observed that pool_svc_step_up_cb may encounter a -DER_NOTLEADER and pass it to ds_pool_failed_add. This error is a replica error and may be transient; it doesn't indicate that the PS is unavailable. This patch addresses the observed scenario by replacing the ds_pool_failed_add call from pool_svc_step_up_cb with a special up-but-with-error mode for the PS, which can only serve requests by returning an error.
- Add pool_svc.ps_error for indicating the special up-but-with-error mode. Check and return it in pool_svc_lookup_leader. Handle it specially in callers of pool_svc_lookup.
- Use this new mode only for a conservative set of errors. Including an error by mistake is worse than missing an error.
- Add pool UUIDs to a few log messages to make future debugging easier.
The …

DAOS-16878 pool: Reduce unexpected DER_NO_SERVICEs (#15665)

---

src/include/daos_srv/pool.h
src/pool/srv.c
src/pool/srv_internal.h
src/pool/srv_pool.c
src/pool/srv_target.c
src/pool/srv_util.c
src/tests/ftest/util/server_utils_params.py

Improve concurrent POOL_QUERY, POOL_CONNECT, and POOL_TGT_QUERY_MAP efficiency by giving them a chance to share the same pool map buffer and pool map buffer bulk handle.
Introduce pool space query on service leader to avoid space query flooding. The pool space cache expiration time is 2 seconds by default, one can change the expiration time via DAOS_POOL_SPACE_CACHE_INTVL, if the expiration time is set to zero, space cache will be disabled.

DAOS-16930 pool: Share map bulk resources

---

site_scons/site_tools/extra/extra.py
utils/githooks/pre-commit.d/50-clang-format.sh

To avoid `extra.py` script corruption when `clang-format` is not installed.
```
Traceback (most recent call last):
File "/home/grom72/repos/daos/./site_scons/site_tools/extra/extra.py", line 141, in <module>
main()
File "/home/grom72/repos/daos/./site_scons/site_tools/extra/extra.py", line 105, in main
supported = _supports_correct_style(WhereIs('clang-format'))
File "/home/grom72/repos/daos/./site_scons/site_tools/extra/extra.py", line 51, in _supports_correct_style
rawbytes = subprocess.check_output([clang_exe, "-version"])
File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib64/python3.9/subprocess.py", line 505, in run
with Popen(*popenargs, **kwargs) as process:
File …
```

DAOS-623 ci: avoid exception in extra.py when clang-format is missing

---

src/container/oid_iv.c
src/container/srv_internal.h

on retry the priv pointer is always freed/allocated, so use the sgl iov pointer instead.

DAOS-16931 container: fix the oid iv check for same request

---

src/client/dfs/dcache.c
src/client/dfs/dfs_internal.h
src/client/dfs/readdir.c
src/include/daos_fs.h
src/tests/suite/dfs_unit_test.c

Add a new DFS readdir API that utilizes a new DFS anchor object which can be updated to include caching parameters for future calls. This API will be more useful when client side caching for readdir is implemented to access buckets of readdir entries.

DAOS-16924 dfs: new readdir API

---

src/tests/ftest/security/cont_acl.py
src/tests/ftest/security/cont_acl.yaml
src/tests/ftest/util/launch_utils.py
src/tests/ftest/util/pool_security_test_base.py
src/tests/ftest/util/security_test_base.py
src/tests/ftest/util/user_utils.py
utils/cq/words.dict

Replace security_test_base.py:add_del_user with calls to individual functions and handle errors.
Test-tag: SecurityPoolACLTest SecurityPoolGroupsTest DaosContainerSecurityTest

DAOS-15268 test: handle errors in add_del_user

---

src/client/dfuse/ops/readdir.c

The dfuse readdir caching feature stats entries returned by dfs readdir that might be legimitely deleted by another process or another node. When this happens, the dfuse code decides to skip the deleted entry, but might leave the readdir entry cache in an inconsistent state causing the following assertion failure in dfuse_dre_drop():
drc->drc_next_offset == expected_offset + 1 || drc->drc_next_offset == READDIR_EOD
This patch fixes the offset in the linked list of cached readdir entries to support skipped entries.

DAOS-13938 dfuse: adjust offset in readdir cache entry list (#15190)

---

src/container/oid_iv.c
src/container/srv_internal.h

- **DAOS-16931 container: fix oid iv race with using invalid on update pt… (#15720)**
- **DAOS-16931 iv: fix the copyright from previous PR (#15802)**
- **DAOS-13938 dfuse: adjust offset in readdir cache entry list (#15190) (#15756)**

Merge release/2.6 into google/2.6

---

src/client/dfuse/pil4dfs/aio.c

Intercepting io_queue_init() is needed on Ubuntu. There is compatibility issue for pil4dfs interception library when used with fio libaio engine. In some cases, fio initialize the aio context through io_queue_init function when loading the libaio engine. Through the pil4dfs has intercepted the io_setup function, but it seems that the io_setup which called by io_queue_init is not intercepted some times, which causing invalid aio context for I/O processing. So add an interception for io_queue_init to make it work for this case.

DAOS-16807 client: intercept io_queue_init in libpil4dfs

---

src/tests/ftest/control/dmg_pool_query_ranks.py
src/tests/ftest/control/dmg_pool_query_test.py
src/tests/ftest/pool/list_verbose.py

The backport from master missed a couple of pool tests that
needed to be updated for the new JSON output from pool query.
Query results always include a dead_ranks array, even when
it's empty.

DAOS-16968 test: Fix pool query tests

---

src/tests/ftest/util/scrubber_test_base.py

Test-tag: TestScrubberEvictWithAggregation test_always_passes_hw
Test-repeat: 3
Summary: Pass the ior_timeout to avoid the test hanging under certain situations.

DAOS-15604 test: Address intermittent scrubber aggregation test failure. (#15696)

---

src/cart/crt_internal.h

- CORPC don't have ep_target set, making their prints confusing during timeouts

DAOS-17013 cart: Fix timeout error prints for CORPCS

---

src/container/srv_target.c
src/pool/srv_target.c

With this change, three ULTs in pool and container code launched via ds_pool_thread_collective() are changed to specify a larger ("deep") stack size of 64KiB rather than a default 16KiB stack size. i.e., the flags parameter specified as DSS_ULT_DEEP_STACK. The three ULT function entrypoints are:
cont_open_one, cont_snap_update_one,and update_vos_prop_on_targets.
Before this change, intermittently in CI testing, shortly after daos_engine startup, a dmg pool list (pool query on the back end) would occasionally result in a segmentation fault in an engine, in these three particular areas of the code. Specifically, the faults occurred within the ABT thread create, inside ABTI_mem_pool_alloc().
This change is based on a guess that the stack size parameter may have some effect.
Features: pool …

DAOS-16768 pool: larger ABT ULT stack sizes

---

src/control/cmd/dmg/system.go
src/control/cmd/dmg/system_test.go
src/control/lib/control/system.go
src/control/lib/control/system_test.go
src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go
src/tests/ftest/control/log_entry.py
utils/node_local_test.py

Whenever stopping an engine process from within the control-plane, use
SIGKILL rather than asking nicely (SIGTERM). This has been requested
to try to avoid situations that could result in dataloss.
This change preserves the behaviour where ds_mgmt_drpc_prep_shutdown()
and then ds_pool_disable_exclude() will be called during a controlled
shutdown where dmg system stop is called with new --full argument.
Notable behavior changes with this PR:
- Always performs SIGKILL on dmg system stop unless --full command
option is supplied.
- Will attempt prepare shutdown to disable exclusions across cluster
during “controlled” shutdown where dmg system stop is called with
--full option but this should be regarded as experimental and not
for use in production environments.
- Force option is a no-op and …

DAOS-16312 control: Always use --force for dmg system stop

---

src/cart/README.env
src/cart/crt_hg.c
src/cart/crt_init.c
src/cart/crt_internal_types.h

This is a workaround for DAOS-16990, DAOS-17009, DAOS-17011.
When using the CXI provider, retry HG_Init_opt2() on error cases since it seems CXI has intermittent issues on initialization. A new environment variable is added (CRT_CXI_INIT_RETRY) to control the retry count (default is 3) and to be able to test future SS fixes without retry.

DAOS-16990 cart: workaround to CXI init errors with retrying HG init

---

Jenkinsfile

Increase the "Unit Test bdev with memcheck on EL 8.8" step timeout to be in sync with the master branch.

DAOS-17020 test: Increase unit test bdev memcheck timeout

---

src/tests/ftest/pytorch/dataset.yaml

To be on the safe side.
Features: PytorchDatasetsTest,PytorchCheckpointTest

DAOS-16362 pydaos: increase torch ftest timeout

---

src/cart/crt_bulk.c
src/cart/crt_hg.c
src/cart/crt_internal.h
src/cart/crt_internal_fns.h
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/include/cart/api.h
src/object/srv_obj.c

Add cart RPC origin address to error handling.

DAOS-16971 cart: add RPC origin address

---

src/client/dfuse/pil4dfs/int_dfs.c

Third argument is "void *" type in libc source code. "va_arg(arg, int);" leads to wrong argument retrieved. also need to return ENOTSUP for flock when compatible mode is not enabled.

DAOS-17059 client: fcntl 3rd parameter should be void *

---

src/tests/ftest/server/metadata.py
src/tests/ftest/server/metadata.yaml
src/tests/ftest/util/command_utils.py

Remove the calling of cleanup methods for multiple containers and ior commands that can be handled by destroying the pool and a single ior kill command.
Test-tag: ObjectMetadata

DAOS-16969 test: Reduce cleanup operations for metadata.py test (#15779)

---

src/vos/vos_common.c
src/vos/vos_dtx.c
src/vos/vos_internal.h

It is used to handle existing partial committed DTX records that were
generated when ran as DAOS-2.6.3-rc{1,2} to avoid repeated DTX commit
after engine restarted.
To be safe, it is required for the user/admin to explicitly set server
side environment variable "DAOS_SKIP_OLD_PARTIAL_DTX" when restart the
engine that has ever run as DAOS-2.6.3-rc{1,2}. If the user has never
used such version, such as directly upgrading from 2.6.1 to 2.6.3-rc3
or newer, then please do NOT set this environment variable.

DAOS-16876 vos: skip DTX record when load partial committed DTX - b26

---

src/client/api/init.c
src/client/array/dc_array.c
src/include/daos/array.h
src/include/daos/common.h
src/include/daos_array.h
src/include/daos_fs.h
src/tests/suite/dfs_unit_test.c

For dfs_readx/writex and array_read/write operations, add a limit for the number of IODs being passed to DAOS of 16k if the iod rexc sizes are smaller than 16 bytes.

DAOS-17055 client: add a soft limit of 16k to nr ranges for list-io

---

src/client/api/init.c
src/client/array/dc_array.c
src/include/daos/array.h
src/include/daos/common.h
src/include/daos_array.h
src/include/daos_fs.h
src/tests/suite/dfs_unit_test.c

For dfs_readx/writex and array_read/write operations, add a limit for the number of IODs being passed to DAOS of 16k if the range lengths are under 16 bytes (best effort checking).
Features: dfs

DAOS-17055 client: add a soft limit of 4k to nr ranges for list-io

---

src/cart/utils/crt_utils.c
src/gurt/telemetry.c
src/gurt/tests/test_gurt.c
src/gurt/tests/test_gurt_telem_producer.c
src/include/gurt/common.h
src/vos/vos_pool_scrub.c

Add d_timeless() for time comparison
Align d_timediff() to pass in pointers
Add d_timenull() and d_time_ms() for conversion
Update tests
Add missing D_COND_INIT() / D_COND_DESTROY()

DAOS-17088 gurt: add d_gettime_coarse() for fast timers

---

src/cart/crt_context.c
src/cart/crt_init.c
src/cart/crt_internal_types.h
src/tests/ftest/cart/utest/utest_swim.c

Only support a single callback per context for now
Fix utest_swim not creating cart context

DAOS-17089 cart: simplify progress callback registration

---

src/tests/ftest/deployment/critical_integration.py

Updated the expected journalctl message from "exited with 0" to "killed", since #15811 changed the default dmg system stop to use --force.

DAOS-17052 test: update expected msg for critical_integration

---

utils/trivy/.trivyignore

Suppress io.netty:netty-common 4.1.115.Final CVE - no fix available 
Suppress io.netty:netty-handler 4.1.100.Final CVE - fix available in 4.1.118.Final
Doc-only: true

DAOS-17108 common: suppress io.netty 4.1.115 CVE

---

src/bio/bio_recovery.c

When teardown a faulty device, ensure the inflight health collecting NVMe command completed before putting the io channel & open descriptor for health monitor.

DAOS-17045 bio: drain inflight health collecting on teardown

---

src/tests/ftest/erasurecode/rebuild_fio.py
src/tests/ftest/erasurecode/rebuild_fio.yaml

Simplify and fix aggregation detection in rebuild_fio by simply checking for when the total free space increases.
Test-repeat: 3

DAOS-17002 test: fix rebuild_fio aggregation detection

---

src/common/btree.c

When deleting the "root" record we cannot assume the `tr_node` offset points to a node since it can also point to an embedded value. So, we first have to consider the trace info or the tree flags to learn what the tree's "root" actually is.
This patch also introduced a few readability changes and a few pieces of in-source documentation.

DAOS-16954 common: fix how the embedded value is deleted

---

src/cart/crt_bulk.c
src/cart/crt_hg.c

DAOS-17087 cart: fix crt_bulk_create() not accepting CRT_BULK_WO

---

SConstruct
site_scons/prereq_tools/base.py

* add --deps-as-gitmodules-subdir flag that ignores branch, tag, and commit information for dependencies in build.config and expects such dependencies to exist as submodules in the supplied sub-directory (relative to base of repo)
* build such dependencies in place by inserting relative symlinks into the build directory

DAOS-17117 build: build dependencies as git submodules

---

.github/workflows/linting.yml
pyproject.toml
utils/githooks/pre-commit.d/20-codespell.sh

Skip *.patch files (we have none in master branch).
Skip same files in githook we do in CI

DAOS-17133 ci: Add to codespell skip list

---

src/include/daos_srv/evtree.h
src/tests/ftest/util/telemetry_utils.py
src/vos/evt_priv.h
src/vos/evtree.c
src/vos/ilog.c
src/vos/tests/vts_ilog.c
src/vos/vos_common.c
src/vos/vos_dtx.c
src/vos/vos_ilog.c
src/vos/vos_internal.h
src/vos/vos_obj_index.c
src/vos/vos_tls.h
src/vos/vos_tree.c

When commit or abort a DTX, we will check whether it is a valid entry or not. For invalid case, we will discard it with warning message and increase related metrics counter.
It may be not perfect solution, but it is efficient to help the user to cleanup system efficiently.

DAOS-16876 vos: discard invalid DTX when commit or abort - b26

---

src/pool/srv_pool.c

If a pool upgrade encounters an error in pool_upgrade_props, the upgrade global version remains at the old global version, while the upgrade status changes to FAILED. In this state, a repeated pool upgrade will fail with the following error in the PS leader engine log:
ds_pool_upgrade_if_needed() b377db55: upgrading pool 3 -> 4 is
unsupported because pool upgraded to 3 last time failed
This patch implements a quick fix that ensures the upgrade global version is updated to the new global version when the upgrade status changes to FAILED, so that a repeated upgrade command will attempt to upgrade the pool again.

DAOS-16927 pool: Fix upgrade DER_NOTSUPPORTEDs

---

src/tests/ftest/erasurecode/online_rebuild_mdtest.py
src/tests/ftest/erasurecode/online_rebuild_mdtest.yaml
src/tests/ftest/util/ec_utils.py

Test-tag: EcodOnlineRebuildMdtest
Test-repeat: 4
- Run with a stonewall and stop ranks after half of the stonewall time so the timing is more reliable than arbitrarily sleeping for 30 seconds.
- Catch exceptions raised in the mdtest thread.
- Reduce logging.
- Misc refactoring improvements

DAOS-16464 test: improve online_rebuild_mdtest.py (#15108)

---

src/cart/crt_context.c

Clean up crt_context_init()/destroy()

DAOS-17086 cart: clean up context_quotas_init()/finalize()

---

SConstruct
site_scons/prereq_tools/base.py

* add --deps-as-gitmodules-subdir flag that ignores branch, tag, and commit information for dependencies in build.config and expects such dependencies to exist as submodules in the supplied sub-directory (relative to base of repo)
* build such dependencies in place by inserting relative symlinks into the build directory

DAOS-17117 build: build dependencies as git submodules (#15909)

---

src/container/srv_container.c

With this change, the cont_refresh_track_eph_one ULT that itself is
created within iv_op_ult() and ds_cont_tgt_refresh_track_eph()
is configured to use a deep stack size (64KiB) rather than 16KiB.
This change is made because intermittent engine segmentation faults
were observed in ABTI_mem_pool_alloc() during CI testing.
This is a similar "solution" to the same segmentation fault that
was observed in other code paths, and fixed in PR 15822.
Features: container test_engine_restart

DAOS-17094 container: increase stack size of cont_refresh_track_eph_one ULT

---

src/client/pydaos/torch/torch_api.py
src/client/pydaos/torch/torch_shim.c

Dataset reads a lot of samples that are stored under just a few common directories, to reduce computation load on lookup for each sample file, this commit introduces a cache of directory objects.
Features: PytorchDatasetsTest,PytorchCheckpointTest

DAOS-16355 pydaos: add dir object cache for Datasets

---

src/client/dfuse/pil4dfs/int_dfs.c
src/include/daos_fs.h

DAOS-17153 il:  library should populate fstype

---

src/cart/utils/memcheck-cart.supp

Another Go runtime false positive popped up.

DAOS-17149 cart: Suppress NLT memcheck false positive

---

.github/pull_request_template.md

DAOS-623 ci: Simplify the pull request template

---

src/cart/crt_context.c
src/cart/crt_hg.c
src/cart/crt_init.c
src/client/api/event.c
src/client/api/init.c
src/client/api/metrics.c
src/client/api/tests/eq_tests.c
src/common/misc.c
src/engine/init.c
src/include/daos/common.h
src/include/daos/metrics.h

Fixes an oversight in the client where HG metrics were
causing warnings on startup when client telemetry is not
enabled.
Change-Id: I0144f432106e641ff7fb8f2ea0ab9c73c564c25d

DAOS-17006 cart: Bypass telemetry init when not enabled

---

utils/build.config
utils/na_tag_rpc.patch
utils/ofi_tag_rpc.patch

Otherwise it would choke the underlying tcp connection.
** a temporary fix on our end while waiting for the libfabric decision **
internal ticket: b/395943619
ofi PR: https://github.com/ofiwg/libfabric/pull/{10792,10783}
mercury PR: https://github.com/mercury-hpc/mercury/pull/784
Skip-func-hw-test-medium: false
Skip-func-hw-tests-large-md-on-ssd: false
Change-Id: I108417b19f02d027e3bf7ee55165edd43c23d15b

DAOS-17103 ofi: discard unmatched tag messages

---

src/client/pydaos/torch/torch_api.py
src/client/pydaos/torch/torch_shim.c

Also change defaults for checkpoint writes from unbounded memory usage to modest 1GB.
Features: pytorch

DAOS-16362 pydaos: add batch read for checkpoints

---

src/client/dfuse/pil4dfs/int_dfs.c

DAOS-16811 client: Intercept dlopen() instead of dlsym() and zeInit()

---

src/client/dfs/cont.c
src/client/dfs/obj.c
src/client/dfuse/ops/lookup.c
src/tests/obj_ctl.c

There are several issues in strncpy usage that may cause memory corruption. Target string may not be ended by `\0` character.
Issues detected during sanitizer integration
Ref: #15105
Co-authored-by: Cedric Koch-Hofer <cedric.koch-hofer@hpe.com>
Co-autohred-by: Tomasz Gromadzki <tomasz.gromadzki@hpe.com>
Signed-off-by: Tomasz Gromadzki <tomasz.gromadzki@hpe.com>

DAOS-17131 dfs: Possible missing string termination after strncpy function call

---

src/control/cmd/daos_agent/mgmt_rpc_test.go
src/control/common/test/utils.go
src/control/lib/daos/api/container_test.go
src/control/lib/daos/api/pool_test.go
src/control/lib/daos/api/selftest_test.go
src/control/lib/daos/api/util.go
src/control/lib/telemetry/promexp/client_test.go
src/control/lib/telemetry/telemetry_test.go
src/control/server/mgmt_system_test.go

Reduce boilerplate in unit tests with test.MustLogContext(), which
takes care of creating a buffer-backed logger, injecting it into
a context, and then logging the contents of the buffer on test
failure.

DAOS-10028 test: Update unit test helper

---

src/tests/ftest/server/metadata.py
src/tests/ftest/server/metadata.yaml
src/tests/ftest/util/job_manager_utils.py

Raise an exception when the clush job_manager run fails.
Fix ior usage server/metadata.py since it was previously silently failing.
Test-tag: ObjectMetadata DaosCoreTestDfuse

DAOS-15817 test: raise exception for clush job_manager failure

---

.github/dependabot.yml

DAOS-623 ci: Avoid Jenkins build for Dependabot PR
Doc-only: true
There is no need to start any action on Jenkins for Dependabot PRs.
An example of proposed result is here:
https://github.com/grom72/daos/pull/70/commits/5cfa1c0ed97a322336136e94516acbe64a0c03b1

DAOS-623 ci: Avoid Jenkins build for Dependabot PR

---

.github/pull_request_template.md

Add a reminder to enable the appropriate functional test stages in a PR.
Doc-only: true

DAOS-17204 ci: Update the pull request template

---

src/client/dfuse/dfuse_core.c
src/client/dfuse/dfuse_main.c

When there are open file handles and dfuse is shutdown using umount -f, it would assert due to resources being used.  Rather than asserting, just print a warning that we are shutting down ungracefully.

DAOS-16922 dfuse: Avoid assertion on shutdown (#15972)

---

src/client/pydaos/torch/torch_shim.c
src/tests/ftest/pytorch/dataset.py
src/tests/ftest/pytorch/dataset.yaml

Directory objects lifecycle is defined by cache, releasing object outside it will result in the error: Invalid object handler.
Features: pytorch

DAOS-16355 pydaos: fix dir obj cache invalid handle error

---

utils/ofi_tag_rpc.patch

The hints might be NULL from intel MPI, which led to crash.
Change-Id: I6b368318232858e078d5f0bf533d9f2da2b25c9e

DAOS-17103 ofi: need to check hints in xnet_getinfo

---

src/cart/crt_swim.c
src/cart/crt_swim.h

In swim, csm_alive_count may underflow because some
cst->cst_state.sms_status changes in csm overlook the count. Moreover,
not counting SUSPECT members seems to be a mistake. Consider a
membership of three, {x, y, z}. If x enters a state where it can't
receive any SWIM messages, and it picks y in the next period, then it
will suspect y, causing csm_alive_count to drop from 3 to 2, which
prevents x from declaring an "outage". (In the subsequent period, x will
suspect z, causing csm_alive_count to drop from 2 to 1 quickly.) Since x
keeps pinging SUSPECT members, it seems reasonable to count them in and
expect them to send messages to x until they become DEAD.
This patch fixes the underflow, and counts SUSPECT members in addition
to ALIVE members in csm_alive_count (renamed to …

DAOS-17111 cart: Fix csm_alive_count

---

src/client/dfuse/pil4dfs/int_dfs.c
src/include/daos_fs.h

Many file systems advertise what they are through the 'f_fsid' field of struct stat.  While DAOS typically uses dFUSE (which advertises itself as FUSE), it's possible to access DAOS through other means.
The pil4dfs interception library intercepts the statfs() call but doesn't completely populate it, leaving the f_fsid field zero.  This commit populates that field.

DAOS-17153 il:  library should populate fstype (#15953)

---

src/tests/ftest/util/storage_utils.py

To avoid generating a server storage configuration in CI testing that uses ram instead of PMEM when PMEM exists on all the nodes in the cluster but it is located on different NUMA nodes, ignore the NUMA association.
Test-tag: test_setup

DAOS-17209 test: Handle non-persistent PMEM naming

---

src/tests/ftest/util/storage_utils.py

To avoid generating a server storage configuration in CI testing that uses ram instead of PMEM when PMEM exists on all the nodes in the cluster but it is located on different NUMA nodes, ignore the NUMA association.
Test-tag: test_setup

DAOS-17209 test: Handle non-persistent PMEM naming (#16027)

---

src/tests/ftest/server/daos_server_restart.yaml

With this change, a test with a hard-coded tier 0 scm class: ram configuration is replaced with storage: auto (an ftest abstraction). This will steer testing to use the correct class: dcpm on functional hardware clusters with PMEM. Also, the pool size is increased to avoid pool create failures that would happen in the new configuration, i.e., avoiding:
"requested SCM capacity is too small".
Before the change, scm class: ram was used with PMEM, and led to Argobots ULT stack overflows and segmentation faults observed when executing in its mem pool allocation logic.
Test-tag: DaosServerTest
Test-repeat: 7

DAOS-17094 test: auto storage config for daos_server_restart

---

.github/pull_request_template.md

Document just the essentials
Signed-off-by: Jeff Olivier <jolivier23@gmail.com>
Co-authored-by: Dalton Bohning <dalton.bohning@hpe.com>
DAOS-17204 ci: Update the pull request template (#16002)
Add a reminder to enable the appropriate functional test stages in a PR.
Signed-off-by: Phil Henderson <phillip.henderson@hpe.com>

DAOS-623 ci: Simplify the pull request template (#15969)

---

src/pool/srv_iv.c

Use deep stack size for IV ULT to avoid stack overflow.

DAOS-17094 pool: deep stack size for IV ULT

---

src/pool/srv_iv.c

Use deep stack size for IV ULT to avoid stack overflow.

DAOS-17094 pool: deep stack size for IV ULT - b26

---

src/client/pydaos/torch/torch_api.py
src/client/pydaos/torch/torch_shim.c
src/tests/ftest/pytorch/dataset.py
src/tests/ftest/pytorch/dataset.yaml

Also change defaults for checkpoint writes from unbounded memory usage to
modest 1GB.
Change-Id: I941867d4aa67c5545267874739f87e12c81634ea
Signed-off-by: Denis Barakhtanov <dbarahtanov@enakta.com>

DAOS-16362 pydaos: add batch read for checkpoints (#15921)

---

src/cart/crt_swim.c
src/cart/swim/swim.c
src/tests/ftest/cart/test_swim_emu.c

In the current implementation of DAOS, when it fails to select a dping target, it will set its self_id to SWIM_ID_INVALID and from now on, the node is not fully functional because only swim_updates_short() will be invoked to respond to PING and IPING request. Once the node enters into this state, it can not be restored.
This PR fixes the problem by not setting the self_id to SWIM_ID_INVALID if it won't be able to find a dping target. It's simply not necessary.
Change-Id: I4a2dad9aeb0571f938a84a97a9e29868a33b01a1
Signed-off-by: Jinshan Xiong [jinshanx@google.com](mailto:jinshanx@google.com)

DAOS-17106 swim: Never change self_id

---

site_scons/prereq_tools/base.py
src/common/SConscript
src/common/tests/SConscript
src/tests/SConscript

When tests are specified, some server components are built. Argobots is still built for some mocks but this is acceptable for now.
Change-Id: I24dd8d76f021472f93b674425590de930731b037

DAOS-17253 build: Fix client only build

---

ci/unit/test_nlt_node.sh

Change-Id: I14da19d10a7d20a8e5c52f92473b601d9fd1136f

DAOS-623 ci: Add some wiggle room for logging

---

src/tests/suite/daos_rebuild_simple.c

Fault injection may corrupt two replica datasets and cause DER_CSUM errors during fetch operations. Current rebuild logic indefinitely retries for these errors. Until protocol handling is improved to properly address this scenario, restrict fault injection testing to rank 0 only.
Test-tag: test_daos_rebuild_simple

DAOS-17200 tests: avoid data corruption across all replicas

---

src/cart/crt_hg.c
src/gurt/dlog.c
src/include/cart/api.h
src/include/gurt/debug.h
src/mgmt/srv_drpc.c
src/mgmt/tests/mocks.c

Mercury and libfabric are much too spammy to enable at lower
than warning level by default. Mercury does support adjustment
of its log level and logged subsystems at runtime, so this
patch provides access to that functionality from the
existing `dmg server set-logmasks` tool.
This version of the patch adds support for writing DEBUG logs to
a separate file in order to avoid problems with log ingestion
pipelines that may be overwhelmed by the volume of DEBUG-level
logging. To enable a standalone debug log, set the environment
variable D_LOG_DEBUG_FILE to a path on disk where debug logs
will be written. The log size and rotation behavior set for
the main log file will be also applied to the debug log.
To enable debug logging for just the mercury/libfabric libraries:
dmg server set-logmasks …

b/390177544 cart: Support dynamic mercury/libfabric loglevels (#15738)

---

src/pool/srv_pool.c

When handling the exclusion of multiple ranks,
pool_svc_update_map_internal aborts the whole request and returns -DER_NONEXIST if any of the ranks is absent in the pool map. This is correct for the dmg case, but problematic for the handle_event case, where ranks not in the pool map should simply be ignored. (See the Jira ticket for more.)

DAOS-17271 pool: Fix handle_event -DER_NONEXISTs

---

utils/cq/check_update_copyright.sh
utils/githooks/find_base.sh
utils/githooks/git-version.sh
utils/githooks/hook_base.sh
utils/githooks/pre-commit
utils/githooks/pre-commit.d/10-update-copyright.sh
utils/githooks/pre-commit.d/20-codespell.sh
utils/githooks/pre-commit.d/30-Jenkinsfile.sh
utils/githooks/pre-commit.d/40-yamllint.sh
utils/githooks/pre-commit.d/50-clang-format.sh
utils/githooks/pre-commit.d/60-gofmt.sh
utils/githooks/pre-commit.d/70-isort.sh
utils/githooks/pre-commit.d/71-flake.sh
utils/githooks/pre-commit.d/72-pylint.sh
utils/githooks/pre-commit.d/73-ftest.sh
utils/githooks/prepare-commit-msg
utils/rpms/packaging/get_release_branch

Replace hardcoded /bin/bash with /usr/bin/env bash in the githook scripts, for the case where /bin/bash does not support newer features like, e.g., mapfile.
replace mapfile with loop in get_release_branch
SKip-unit-tests: true
Skip-nlt: true

DAOS-16898 cq: support user bash in githooks (#15648)

---

src/client/api/object.c
src/client/dfs/pipeline.c
src/tests/ftest/daos_test/dfs.yaml
src/tests/suite/dfs_unit_test.c

- use DIOF_TO_SPEC_GROUP instead of DIOF_TO_SPEC_SHARD

DAOS-17224 object: fix anchor split listing

---

src/engine/srv.c
src/include/daos_srv/daos_engine.h

The stack size set for the server xstreams and
the NVMe polling ULT is 64K. This size seems to
result in occasional segfaults on engine startup,
likely due to being near a limit. Doubling the
stack size for these ULTs should avoid the problem.
Change-Id: Id339cc48985825ccce291ad288e1490920facf5c

b/402103828: Increase xstream stack size

---

docs/admin/administration.md
docs/admin/deployment.md
src/client/api/event.c
src/client/api/init.c
src/client/api/rpc.c
src/include/daos/mgmt.h
src/mgmt/cli_mgmt.c

When one or more ranks are excluded, the calculation for sending RPC to a service rank is invalid: it will eventually select a rank which has been excluded.
Moreover, if the system has been extended after evicting one or more ranks, then the new rank will never be used.

DAOS-17127 cart: Fix random rank calcultation

---

src/pool/srv_pool.c

When handling the exclusion of multiple ranks,
pool_svc_update_map_internal aborts the whole request and returns -DER_NONEXIST if any of the ranks is absent in the pool map. This is correct for the dmg case, but problematic for the handle_event case, where ranks not in the pool map should simply be ignored.

DAOS-17271 pool: Fix handle_event -DER_NONEXISTs (#16081)

---

src/bio/bio_monitor.c
src/bio/bio_recovery.c

When teardown an unplugged health device, we close blobs but keep the io contexts (for the up layer opened VOS pool), so that when the device is plugged back, blobs will be auto opened for these existing io contexts.
However, if the unplugged device is marked as FAULTY (after teardown completed), the upper layer VOS pools will be closed on faulty reaction, so we need to clear all the closed io contexts when setup device.

DAOS-17282 bio: clear io contexts for unplugged faulty device

---

src/cart/crt_hg_proc.c
src/cart/crt_internal_types.h
src/cart/crt_swim.c

The "network outage" detection for swim (see the existing crt_swim_update_last_unpack_hlc) uses all crt contexts. In an engine, if the swim context can't receive or send any message, while at least one other context can and does receive messages constantly, then swim will not detect any "network outage", leading to more false positive DEAD events. The purpose of that detection is to find out swim-specific "network outages", where swim may be unable to receive any swim message.
This patch changes the detection algorithm to use only the swim crt context:
- Remove crt_context.cc_last_unpack_hlc.
- Update crt_swim_membs.csm_last_unpack_hlc when receiving swim requests and replies.

DAOS-17111 cart: Use only swim ctx for outage

---

src/common/fault_domain.c
src/common/fault_domain.h
src/common/pool_map.c
src/common/prop.c
src/common/tests/fault_domain_tests.c
src/control/lib/daos/pool_cont_prop.go
src/control/lib/daos/pool_property.go
src/control/server/mgmt_pool_test.go
src/control/system/membership.go
src/control/system/membership_test.go
src/include/daos/object.h
src/include/daos/pool_map.h
src/include/daos_prop.h
src/placement/jump_map.c
src/placement/tests/jump_map_pda_layout.c
src/placement/tests/jump_map_place_obj.c
src/placement/tests/place_obj_common.c
src/pool/srv_pool.c
src/pool/srv_util.c

- Rename pool map levels to allow for optional fault domain level above
node.
- Rename any performance domain "group" terminology.
- Update compressed fault domain tree parsing to include metadata about
whether to include optional fault or performance domains.
- Update compressed domain tree format in control plane.
Signed-off-by: Kris Jacque <kris.jacque@hpe.com>

DAOS-16940 common: Update pool map levels

---

ci/provisioning/post_provision_config_nodes_EL_8.sh

Fix typo that's failing HW stages.
Test-tag: test_always_passes_hw

SRE-2928 build: Fix artifactory url variable (16123)

---

src/cart/crt_hg_proc.c
src/cart/crt_internal_types.h
src/cart/crt_swim.c

The "network outage" detection for swim (see the existing crt_swim_update_last_unpack_hlc) uses all crt contexts. In an engine, if the swim context can't receive or send any message, while at least one other context can and does receive messages constantly, then swim will not detect any "network outage", leading to more false positive DEAD events. The purpose of that detection is to find out swim-specific "network outages", where swim may be unable to receive any swim message.
This patch changes the detection algorithm to use only the swim crt context:
- Remove crt_context.cc_last_unpack_hlc.
- Update crt_swim_membs.csm_last_unpack_hlc when receiving swim requests and replies.

DAOS-17111 cart: Use only swim ctx for outage (#15924)

---

src/control/server/mgmt_check.go

It's expected that querying the MS properties will
fail before the storage is formatted, so we shouldn't
log it as an error.

DAOS-17317 control: Quiet misleading server error

---

src/control/server/storage/bdev/backend_class_test.go
src/control/server/storage/bdev/backend_json.go
src/vos/tests/daos_nvme.conf

The retry_count parameter in the SPDK bdev configuration was
deprecated in v22 and renamed to transport_retry_count. As
of v24, retry_count is not accepted and will cause a parsing
error on engine startup. Using transport_retry_count will
work for both v22 and v24.

DAOS-17343 control: Rename retry_count in SPDK config

---

src/client/dfuse/ops/read.c

Initialize the list, otherwise it might be corrupted if multiple threads read the same file.

DAOS-16686 dfuse: fix list corruption

---

src/common/checksum.c
src/common/misc.c

client side checksum calculation is based on the request iod recxs, though the checksum is calculated by real IOM, so the input request bytes might be larger than the real fetched bytes in sgl, so let's ignore the size after the real fetched bytes.

DAOS-16136 common: unnecessary sgl warning

---

src/tests/suite/daos_rebuild_simple.c

Fault injection may corrupt two replica datasets and cause DER_CSUM errors during fetch operations. Current rebuild logic indefinitely retries for these errors. Until protocol handling is improved to properly address this scenario, restrict fault injection testing to rank 0 only.
Test-tag: test_daos_rebuild_simple

DAOS-17200 tests: avoid data corruption across all replicas (#16047)

---

src/client/api/object.c
src/client/dfs/pipeline.c
src/tests/ftest/daos_test/dfs.yaml
src/tests/suite/dfs_unit_test.c

- use DIOF_TO_SPEC_GROUP instead of DIOF_TO_SPEC_SHARD

DAOS-17224 object: fix anchor split listing (#16056)

---

src/container/srv_target.c
src/vos/vos_pool_scrub.c

In sc_wait_until_should_continue(), the function could sleep for over 60 seconds before proceeding, causing container destruction timeouts and DER_BUSY errors during retries. This fix adds 1-second interval checks for sc_cont_is_stopping() during sleep cycles.
Additionally, enhanced error logging when container destruction is already in progress.

DAOS-16620 vos: exit scrub earlier during container destruction (#15957)

---

docs/user/container.md

DAOS-16767 doc: improve documentation for daos cont set-prop

---

site_scons/site_tools/go_builder.py

By default scons only searches the execution environment PATH, not the external user environment PATH. We must request the user's PATH explicitly.

DAOS-17350 build: Search in user environment for Go binary

---

src/tests/ftest/aggregation/dfuse_space_check.py
src/tests/ftest/aggregation/dfuse_space_check.yaml
src/tests/ftest/container/multiple_delete.py
src/tests/ftest/nvme/enospace.py
src/tests/ftest/nvme/enospace.yaml
src/tests/ftest/util/test_utils_pool.py

Update tests to use pool.check_free_space to dynamicall wait for pool aggregation.
Test-tag: test_enospace_time_with_fg DfuseSpaceCheck MultipleContainerDelete test_enospace_lazy_with_fg

DAOS-16845 test: update tests to use check_free_space (#15553)

---

src/cart/crt_iv.c
src/engine/server_iv.c
src/vos/vos_dtx.c

- Rate limit on IV_OID busy message, change the debug level of two IV log messages from INFO to DEBUG.
- Don't print warning message in vos_dtx_check_availability() for fresh record.

DAOS-16918 vos: suppress two log messages (#15679)

---

src/container/srv_target.c

- Change container state check errors to debug level in three locations:
1. cont_child_start() when container is stopping/destroying
2. cont_child_destroy_one() when container already being destroyed
3. cont_child_prop_update() during container termination
- Add DB_MD debug stream for container management operations
- Preserve original error codes (-DER_SHUTDOWN/-DER_BUSY) while reducing log noise during normal container destroy/stop operations

DAOS-16620 container: demote lifecycle errors to debug (#16193)

---

src/tests/ftest/deployment/io_sys_admin.yaml

Local flock support is needed to create hdf5 file by daos-serialize in test io_sys_admin.
Test-tag: test_io_sys_admin

DAOS-17376 tests: enable local flock in dfuse for io_sys_admin

---

src/tests/ftest/deployment/critical_integration.py

Updated the expected journalctl message from "exited with 0" to "killed", since #15811 changed the default dmg system stop to use --force.

DAOS-17052 test: update expected msg for critical_integration (#15855)

---

src/bio/bio_device.c
src/bio/smd/smd_device.c
src/control/cmd/ddb/commands_wrapper.go
src/control/cmd/ddb/ddb_commands.go
src/control/cmd/ddb/main.go
src/utils/ddb/ddb.c
src/utils/ddb/ddb.h
src/utils/ddb/ddb_commands.c
src/utils/ddb/ddb_vos.c
src/utils/ddb/ddb_vos.h

If a NVMe SSD namespace is failed to be discovered by SPDK, the engine will fail to start due to missing device, so there is no way to do the online device replacing.
To fix above missing SSD namespace issue, offline device replacing could be used in following steps:
- Run 'ddb dev_list' to show all devices;
- Run 'ddb dev_replace' to replace the old broken SSD with an unused new SSD;
- Start engine;
- Run 'dmg storage replace' with same old and new device UUID to revive the replaced SSD (blobs will be auto created and reintegration will be triggered);
Limitation:
Offline device replacing can't handle the missing sys SSD in md-on-ssd mode (RDB is located on sys SSD in md-on-ssd mode) so far.

DAOS-17180 ddb: replace device offline

---

utils/githooks/branches.default
utils/githooks/branches.google
utils/githooks/find_base.sh
utils/rpms/packaging/get_release_branch

When we are using a repo for other than GitHub, things may not be in proper places for the defaults to work. This enables running plugin scripts to get extra
branch names
Change-Id: I07a1e952b0873ec95a9c2c7b5d9a093e3274255a

DAOS-17404 ci: Enable plugin for finding branches

---

src/control/cmd/daos_server_helper/handler.go
src/control/cmd/daos_server_helper/main.go
src/control/fault/code/codes.go
src/control/server/ctl_storage_rpc.go
src/control/server/instance_storage.go
src/control/server/storage/bdev.go
src/control/server/storage/bdev/backend.go
src/control/server/storage/bdev/backend_class.go
src/control/server/storage/bdev/backend_class_test.go
src/control/server/storage/bdev/backend_json.go
src/control/server/storage/bdev/backend_json_test.go
src/control/server/storage/bdev/backend_test.go
src/control/server/storage/bdev/mocks.go
src/control/server/storage/bdev/provider.go
src/control/server/storage/faults.go
src/control/server/storage/mocks.go
src/control/server/storage/provider.go
src/control/server/storage/provider_test.go

Before starting an engine, first check to see if the on-disk
SPDK configuration file can be read and parsed by this
version of DAOS. If it's not found or can't be parsed, take
it as a signal to regenerate the file.
Change-Id: I3ccbd4c5ce036435c45f185f902f0aa6a679beb3

DAOS-17343 control: Validate SPDK config on engine start

---

src/container/srv_target.c
src/engine/sched.c
src/pool/srv_target.c
src/tests/ftest/util/server_utils_params.py
src/vea/vea_api.c
src/vea/vea_free.c
src/vos/vos_internal.h

Seek to avoid false ENOSPACE by few adjustments:
- Revert the 60 seconds VOS_AGG_GAP_DEF back to 20 seconds.
- Aggregation ULTs don't voluntarily sleep when there is space pressure, otherwise, scheduler will think that there is nothing to be reclaimed and gives up on throttling I/O.
- Increase the reclaim ULTs CPU ratio for all pressure levels: bump the original [20, 30, 40, 50, 60] to [30, 45, 60, 75, 90].
- Shrink VEA flush/expire interval from 5/10 seconds to 2/3 seconds.
- Shrink the flush ULT sleep interval from 5/1 seconds to 500/50 milli-seconds.

DAOS-17152 pool: seek to avoid false ENOSPACE

---

src/pool/srv_pool.c

If a pool upgrade encounters an error in pool_upgrade_props, the upgrade global version remains at the old global version, while the upgrade status changes to FAILED. In this state, a repeated pool upgrade will fail with the following error in the PS leader engine log:
ds_pool_upgrade_if_needed() b377db55: upgrading pool 3 -> 4 is
unsupported because pool upgraded to 3 last time failed
This patch implements a quick fix that ensures the upgrade global version is updated to the new global version when the upgrade status changes to FAILED, so that a repeated upgrade command will attempt to upgrade the pool again.

DAOS-16927 pool: Fix upgrade DER_NOTSUPPORTEDs (#15873)

---

src/tests/ftest/tags.py
utils/githooks/pre-commit.d/73-ftest.sh

Add support in tags.py to filter tests by tags and/or paths. Add TagSet to handle negative matching. E.g. foo,-bar

DAOS-15630 test: tags.py filter tests by tags (#15705)

---

utils/githooks/branches.google
utils/githooks/get_branch

Branch resolution was broken
1. In trying to address shellcheck, it actually broke the checks
2. Add google/2.6 as a branch
3. Don't fail branches.google script if grep fails
Change-Id: Ibec7319d44fc533325207d39145b99de52cb9651

Fix an issues with internal githooks

---

src/tests/ftest/dfuse/find.py

test_dfuse_find_perf is a manual test that requires Lustre and we do not have Lustre so disable it.
Test-tag: test_dfuse_find_perf

DAOS-17423 test: disable test_dfuse_find_perf in CI

---

src/tests/ftest/dfuse/find.py

test_dfuse_find_perf is a manual test that requires Lustre and we do not have Lustre so disable it.
Test-tag: test_dfuse_find_perf

DAOS-17423 test: disable test_dfuse_find_perf in CI (#16262)

---

src/control/lib/control/pool_test.go

DAOS-15947 control: Unit test for PoolRanksReq type conversion

---

src/tests/ftest/control/dmg_storage_scan_scm.py
src/tests/ftest/control/log_entry.py
src/tests/ftest/control/ssd_socket.py
src/tests/ftest/control/super_block_versioning.py
src/tests/ftest/control/version.py
src/tests/ftest/daos_racer/parallel.py
src/tests/ftest/deployment/agent_failure.py
src/tests/ftest/deployment/network_failure.py
src/tests/ftest/dfuse/posix_stat.py
src/tests/ftest/erasurecode/truncate.py
src/tests/ftest/nvme/enospace.py
src/tests/ftest/recovery/container_list_consolidation.py
src/tests/ftest/recovery/ddb.py
src/tests/ftest/server/cpu_usage.py
src/tests/ftest/server/daos_server_dump.py
src/tests/ftest/util/agent_utils.py
src/tests/ftest/util/cpu_utils.py
src/tests/ftest/util/daos_racer_utils.py
src/tests/ftest/util/ddb_utils.py
src/tests/ftest/util/general_utils.py
src/tests/ftest/util/job_manager_utils.py
src/tests/ftest/util/macsio_util.py
src/tests/ftest/util/performance_test_base.py
src/tests/ftest/util/run_utils.py
src/tests/ftest/util/server_utils.py
src/tests/ftest/util/soak_utils.py

Replace usage of pcmd with run_remote
Features: CPUUsage DAOSVersion DmgStorageScanSCMTest Ecodtruncate NetworkFailureTest POSIXStatTest SSDSocketTest SuperBlockVersioning soak_smoke MacsioTest daos_racer OSAOnlineExtend OSAOnlineParallelTest DdbTest ContainerListConsolidationTest performance,-manual NvmeEnospace TestWithScrubberTargetEviction Pil4dfsFio AgentFailure ControlLogEntry test_ras ContinuesAfterStop test_scrubber_ssd_auto_eviction

DAOS-17120 test: replace pcmd with run_remote (#15915)

---

src/tests/ftest/container/boundary.py
src/tests/ftest/deployment/disk_failure.py
src/tests/ftest/dfuse/find.py
src/tests/ftest/harness/config.py
src/tests/ftest/harness/config.yaml
src/tests/ftest/nvme/pool_exclude.py
src/tests/ftest/osa/offline_drain.py
src/tests/ftest/osa/offline_parallel_test.py
src/tests/ftest/osa/offline_reintegration.py
src/tests/ftest/osa/online_parallel_test.py
src/tests/ftest/osa/online_reintegration.py
src/tests/ftest/pool/create_all_vm.py
src/tests/ftest/pool/management_race.py
src/tests/ftest/rebuild/mdtest.py
src/tests/ftest/server/replay.py
src/tests/ftest/util/apricot/apricot/test.py
src/tests/ftest/util/daos_io_conf.py
src/tests/ftest/util/pool_security_test_base.py
src/tests/ftest/util/server_utils.py
src/tests/ftest/util/slurm_utils.py
src/tests/ftest/util/soak_test_base.py
src/tests/ftest/util/soak_utils.py

Use self.random in nearly all cases so it can be seeded for reproducibility. Test-tag: BoundaryTest DfuseFind DiskFailureTest HarnessConfigTest NvmePoolExclude OSAOfflineDrain OSAOfflineParallelTest OSAOfflineReintegration OSAOnlineParallelTest OSAOnlineReintegration PoolCreateAllVmTests PoolManagementRace ReplayTests EcodRunIoConf DaosRunIoConf soak_smoke security RebuildMdtest Skip-unit-tests: true

DAOS-13700 test: use self.random in most cases

---

utils/githooks/branches.default
utils/githooks/find_base.sh
utils/githooks/get_branch

When we are using a repo for other than GitHub, things may not be in proper places for the defaults to work. This enables running plugin scripts to get extra
branch names

DAOS-17404 ci: Enable plugin for finding branches (#16234)

---

src/cart/crt_swim.c

The removal of the swim "shutdown" logic in swim_progress may result in ~240,000 of the following debug message being logged in ~1.7 s when an engine starts:
crt_swim_get_dping_target() there is no dping target
This patch removes the debug message as a temporary solution.

DAOS-17106 cart: Fix floods of swim debug messages

---

docs/admin/administration.md
docs/admin/pool_operations.md

Documentation updates relating to:
- New commands `dmg system drain|reintegrate`
- New command syntax for multiple --ranks
`dmg pool drain|reintegrate|exclude –ranks 1-9,11-19`
- New command flag `dmg storage format --replace`
Doc-only: true

DAOS-15947 docs: Update admin guide dmg system command syntax

---

utils/build.config
utils/ofi_error_handling.patch

This PR merges two commits from upstream 86ae6d745df6f6463a261558dcb62ff0854bc2f6 and b3103f4007408b80b99e736774cfb2cfb68ac4ff for better error handling.

ofi: better error handling in libfabric

---

src/object/srv_ec_aggregate.c
src/placement/pl_map.c

Call pl_map_decref() after pl_map_find() in order
to avoid a weird assertion on a long-running system.
Change-Id: Ia2a735856b14abede3ddf1b4cdd7a30cc0e9b1c2

DAOS-17531 object: Fix pl_map ref leak in EC agg

---

src/object/cli_obj.c

DAOS-17351 object: backoff for notleader error

---

src/cart/crt_context.c

Add out of quota RPC to timeout list once resubmit them.

DAOS-17470 cart: add out of quota RPC to timeout

---

src/client/dfuse/inval.c

The kernel doesn't release directory inodes aggresively so dfuse added a 30 minute timeout to release them but it can cause getcwd to fail.  Set the timeout to a ridiculous number. If there is memory pressure, the kernel will tell dfuse to forget them.
Change-Id: I22559f7caa54e9d6312e5c4800ee1be618a4b9e1

DAOS-17496 client: Avoid premature inode invalidation

---

src/pool/srv_internal.h
src/pool/srv_iv.c
src/pool/srv_pool.c
src/pool/srv_target.c

Pool handles should be loaded to IV cache in step up callback, in case all pool svc handles are restarted.

DAOS-17351 pool: load pool handles to IV cache

---

src/control/go.mod

The version of the Go toolchain in go.mod serves as a minimum. One of our dependencies requires 1.23--it does not matter which version of 1.23.

DAOS-17541 control: Reduce minimum Go toolchain version

---

src/engine/sched.c

Shrink MAX_SCHED_REQ_NUM from 1M to 64K for each xstream to avoid OOM, since 1M ULT will use 16G memory, which is too much for single xstream.

DAOS-17351 engine: shrink MAX_SCHED_REQ_NUM

---

src/control/server/interceptors.go

The component compatibility check is noisy, and reduces the
usefulness of debug-level logging for customers. It's still
useful for devs as a trace-level message.
Signed-off-by: Kris Jacque <kris.jacque@hpe.com>

DAOS-16565 control: Log component check at Trace level

---

src/control/go.mod

The version of the Go toolchain in go.mod serves as a minimum. One of our dependencies requires 1.23--it does not matter which version of 1.23.

DAOS-17541 control: Reduce minimum Go toolchain version (#16365)

---

Jenkinsfile

Avoid utilizing excessive CI resources usage while manually starting CI jobs by disabling functional test stages that are normally skipped when running PRs.

DAOS-17577 test: Temporarily skip some functional tests by default

---

Jenkinsfile
ci/functional/test_main.sh
ci/functional/test_main_node.sh
ci/functional/test_main_prep_node.sh
ci/gha_functions.sh
ci/provisioning/post_provision_config.sh
ci/provisioning/post_provision_config_common.sh
ci/provisioning/post_provision_config_common_functions.sh
ci/provisioning/post_provision_config_nodes.sh
ci/provisioning/post_provision_config_nodes_EL_8.sh
ci/provisioning/post_provision_config_nodes_LEAP_15.sh
ci/provisioning/post_provision_config_nodes_UBUNTU_20_04.sh
ci/storage/test_main_storage_prepare_node.sh
ci/unit/test_main.sh
ci/unit/test_main_node.sh
ftest.sh
site_scons/env_modules.py
src/tests/ftest/dfuse/bash.py
src/tests/ftest/process_core_files.py
src/tests/ftest/scripts/main.sh
utils/rpms/daos.spec
utils/run_utest.py

Enable CI running in Fort Collins with:
- passing HTTPS_PROXY to functional tests
- fixing repository paths, E-MAIL domain, and hardware check
- fixing expectations for InfiniBand adapters and IBoIP device detection
- added build parameter to skip all functional or functional HW tests
- limiting number of NVMe devices used to 4
- creating local host file to prevent DNS glitches
- added minimum required python3-mpi4py-tests, mpich, and Lmod/lua-lmod versions
- removed mpi/mlnx_openmpi-x86_64 module file
- installing updated lua-lmod package for Leap 15.6 testing
- commented out jenkins curl test in gha_functions.sh
- default FUNCTIONAL_HARDWARE_MEDIUM_VERBS_PROVIDER_LABEL -> ci_ofed5
- fixed debuginfo RPM installs for stack trace generation

SRE-2832 FC fixes to enable Functional Tests (#16224)

---

docs/admin/administration.md
docs/admin/pool_operations.md

Documentation updates relating to:
- New commands dmg system drain|reintegrate
- New command syntax for multiple --ranks dmg pool drain|reintegrate|exclude –ranks 1-9,11-19
- New command flag dmg storage format --replace

 DAOS-15947 docs: Update admin guide dmg system command syntax (#16261)

---

Jenkinsfile

Exclude the OPA cluster from running Functional HW Verbs Provider stage.

SRE-2832 test: Update HW Verbs provider label

---

src/common/btree.c
src/include/daos/btree.h
src/vos/vos_dtx.c

The dbtree feature BTR_FEAT_SKIP_LEAF_REBAL was introduced to optimize
DTX aggregation. It does not only affect the balance among leaves, but
also changes some dbtree general behaviors, such as removing leaf node
from any position instead of only from the right side, then breaks the
assumption for some dbtree general logic, such as del_xxx_merge(). The
usages for the changes are very limited as to related verification may
be not enough. To be safe, disable the feature to avoid some potential
issue. It may affect DTX aggregation efficiency a bit under some cases,
but may be not important, because we prepare to handle DTX aggregation
with more efficient solution.

DAOS-17148 common: disable BTR_FEAT_SKIP_LEAF_REBAL

---

src/common/btree.c
src/include/daos/btree.h
src/vos/vos_dtx.c

The dbtree feature BTR_FEAT_SKIP_LEAF_REBAL was introduced to optimize DTX aggregation. It does not only affect the balance among leaves, but also changes some dbtree general behaviors, such as removing leaf node from any position instead of only from the right side, then breaks the assumption for some dbtree general logic, such as del_xxx_merge(). The usages for the changes are very limited as to related verification may be not enough. To be safe, disable the feature to avoid some potential issue. It may affect DTX aggregation efficiency a bit under some cases, but may be not important, because we prepare to handle DTX aggregation with more efficient solution.

DAOS-17148 common: disable BTR_FEAT_SKIP_LEAF_REBAL - b26

---

src/vos/vos_dtx.c

Do not clear "dae_need_release" flags after partial commit to avoid DTX entry only being evicted from DRAM but still left on-disk.

DAOS-17598 vos: keep dae_need_release flag for partial commit

---

src/vos/vos_dtx.c

Do not clear "dae_need_release" flags after partial commit to avoid DTX entry only being evicted from DRAM but still left on-disk.

DAOS-17598 vos: keep dae_need_release flag for partial commit - b26

---

src/client/api/metrics.c
src/gurt/telemetry.c
src/include/gurt/telemetry_common.h
src/mgmt/cli_mgmt.c

In cases where the client telemetry will not be
sampled via the agent (e.g. when dumping to a
CSV at process exit), it would be preferable to
avoid overhead and exposure to resource limits
imposed by the use of shared memory segments.
Setting the D_TM_NO_SHMEM flag in d_tm_init()
will result in process-local memory allocations
for the telemetry segments.
Change-Id: I60f8640aec5bc856c43b83c3bd691ae07276d457

DAOS-17403 telem: Add non-shared memory flag (#16237)

---

src/cart/utils/memcheck-cart.supp

Based on NLT Valgrind results, it seems the path for internal Go runtime functions has changed with the latest Go version.

DAOS-17432 test: Update suppressions for Go runtime

---

src/cart/utils/memcheck-cart.supp

Based on NLT Valgrind results, it seems the path for internal Go runtime functions has changed with the latest Go version.

DAOS-17432 test: Update suppressions for Go runtime (#16310)

---

src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go

The CR checker tool needs to use a graceful shutdown when stopping ranks. It may select a subset of ranks if some are admin-excluded.
- Remove the limitation that non-forced shutdown may only be used on the whole system, not while specifying ranks.

DAOS-17049 control: Allow graceful shutdown for specific ranks

---

src/tests/ftest/dfuse/daos_build.py
utils/scripts/install-el8.sh
utils/scripts/install-el9.sh
utils/scripts/install-leap15.sh
utils/scripts/install-ubuntu.sh

Use the utils/scripts/install-<distro>.sh scripts to ensure the required pacakges are installed to be able to buid DAOS in the dfuse/daos_build.py test.
Test-tag: DaosBuild DaosBuildVM

DAOS-17653 test: Resolve daos_build.py ofi failed to build

---

src/vos/vos_container.c
src/vos/vos_dtx.c

After engine restart or container/pool reopen, DTX related statistical information in DRAM needs to be recalculated with considering existing on-disk DTX information.

DAOS-17560 vos: maintain DTX statistical info correctly

---

src/vos/vos_pool.c

ABT_cond_wait() requires the caller to hold the mutex lock.

DAOS-17674 vos: add missing ABT mutex lock protection

---

ci/provisioning/post_provision_config_nodes_LEAP_15.sh

Temporarily skip the GPG check for the lua-lmod install in post provisioning for Leap 15.6.
Skip-func-test-el8: true
Skip-func-test-el9: true

SRE-3149 test: Skip gpg check for lua-lmod install (#16531)

---

src/client/dfs/dcache.c
src/gurt/shm_dict.c
src/include/gurt/shm_dict.h

allow longer ht name
decrease dentry ht reference

DAOS-16452 dfs: fix memory overflow due to padding

---

src/tests/ftest/util/daos_core_base.py

Remove any trailing space from cmocka commands to ensure they can be properly stopped in tearDown.
Test-tag: DaosCoreTest DaosCoreTestDfuse CsumErrorLog DaosCoreTestDfs DaosCoreTestNvme CatRecovCoreTest

DAOS-17179 test: Fix stop commands with trailing space (#15993)

---

src/tests/ftest/process_core_files.py

Avoid 'missing debuginfo' messages in EL 8.8 generated stack traces.
Test-tag: test_core_files

DAOS-17562 test: Add missing EL 8 debuginfo packages

---

src/control/cmd/dmg/pool.go
src/control/cmd/dmg/pool_test.go
src/pool/srv_cli.c

Allow the pool's rd_fac to be modified on existing pools.

DAOS-9217 pool: allow rd_fac to be modified (#16289)

---

src/gurt/telemetry.c

In some scenarios the computed variance may be less than
zero, and therefore the sqrtl() function will return NaN.
Guard against this and return zero instead.

DAOS-17522 telemetry: Handle negative variance in std_dev

---

src/pool/srv_pool_map.c

If the target is being drained, then exclude should not change its fseq number, otherwise it may get wrong object layout and interfere the drain process.

DAOS-17589 pool: not changing fseq for exclude during drain

---

utils/cq/pylintrc
utils/cq/requirements.txt

Updates `flake8` from 7.2.0 to 7.3.0
Updates `isort` from 5.13.2 to 6.0.1
Updates `pylint` from 3.2.0 to 3.3.7
Updates `yamllint` from 1.35.1 to 1.37.1
Updates `codespell` from 2.2.6 to 2.4.1

DAOS-17761 cq: bump python package versions (#16530)

---

src/tests/ftest/util/dmg_utils.py

Always reset the timeout in DmgCommand in dmg
utilities no matter the outcome of storage format.

DAOS-17241 test: reset timeout in dmg command util

---

src/tests/ftest/erasurecode/rebuild_fio.py
src/tests/ftest/erasurecode/rebuild_fio.yaml

Simplify and fix aggregation detection in rebuild_fio by simply checking for when the total free space increases.

DAOS-17002 test: fix rebuild_fio aggregation detection (#15817)

---

src/control/cmd/daos/container.go

Fixes an oversight from the migration to the new Container
API for the daos tool. After opening a container, set the
pool helpers on the command.

DAOS-10028 client: Set cmd.pool in openContainer()

---

src/common/dav_v2/dav_iface.c
src/common/dav_v2/heap.c
src/common/dav_v2/heap.h
src/common/dav_v2/tx.c
src/common/dav_v2/tx.h
src/common/tests/umem_test_bmem.c

This commit adds pre-reserved space in the persistent heap (md-blob) to enable future resizing. The space is tied to the zone info vector, which tracks allocator-managed zones/buckets.

DAOS-17365 common: Phase-2 allocator pre-enabler for md-blob resize

---

utils/rpms/packaging/Dockerfile.mockbuild

SRE-3194 build: Remove redhat-lsb-core from Dockerfile.mockbuild

---

src/utils/daos_metrics/daos_metrics.c

Add the missing meminfo option in the daos_metric application help message.

DAOS-17786 metrics: fix daos_metrics help

---

src/chk/chk_engine.c
src/include/daos_srv/pool.h

When check engine verifies pool membership, it may discard the rank or target which status is ‘DOWN' or 'DOWNOUT’ to release related space. Such logic was fine before. But as incremental reintegration feature is on the way, such logic needs to be improved; otherwise, if related orphan pool shard is removed by check engine, subsequent reintegration has to be started from the scratch instead of incremental work.

DAOS-17576 chk: keep orphan pool shard which status is DOWN or DOWNOUT

---

src/chk/chk_common.c

The user/admin may specify repeated pool(s) in the check list via 'dmg check' command. The logic needs to handle such case to avoid invalid assertion.
The patch also fixes chk dump logic to avoid out-of-boundary DRAM accessing.

DAOS-17822 chk: filter out repeated pools in the check list

---

src/tests/ftest/recovery/check_start_options.py
src/tests/ftest/recovery/check_start_options.yaml
src/tests/ftest/util/recovery_test_base.py

Test steps:
1. Create a pool.
2. Inject orphan pool fault.
3. Enable checker and set policy to --all-interactive.
4. Start the checker with --failout=on.
5. Query and check that it detected the orphan pool.
6. Remove the pool directory from the mount point.
7. Repair the pool.
8. Query and verify that Current status is FAILED. i.e., State is failed.
Added query_detect in recovery_test_base.py that's used in this new test and test_check_start_reset.
Fixed test_check_start_reset.
Added container in the test yaml.
Test-tag: test_check_start_reset test_check_start_failout

DAOS-17818 test: CR Automate Test - dmg check start --failout

---

src/cart/utils/memcheck-cart.supp

An additional case of tsan::TraceRestartMemoryAccess with a slightly different call stack. This is a false positive coming from the Go runtime.
Also moved another tsan suppression to be near similar ones, and named them more descriptively.

DAOS-17783 test: Suppress NLT false positives in Go

---

src/control/system/raft/database.go
src/control/system/raft/database_test.go
src/control/system/raft/mocks.go
src/control/system/raft/raft.go
src/control/system/raft/raft_test.go

When adding a new access point to config and restarting, the member is updated, not added, so it was not being considered a voter in the MS leader election.

DAOS-17492 control: Ensure updated members can become voters (#16392)

---

src/tests/ftest/recovery/check_start_options.py
src/tests/ftest/recovery/check_start_options.yaml

Add test_check_start_find_orphans in recovery/check_start_options.py
When some fault is detected and not fixed due to --all-interactive, checker state becomes stopped. At this point, we can restart the checker, but the checker can’t detect orphan pool when its state is stopped. One way to detect is to reset it (dmg check start --reset). However, admin may not want to reset it, so the alternative is to use --find-orphans.
1. Create a pool and a container.
2. Inject non orphan pool fault such as orphan container.
3. Stop server, enable checker, set policy to --all-interactive, and start without argument.
4. Check that orphan container is detected.
5. Stop and disable checker. Start system.
6. Create an orphan pool.
7. Enable checker and start without argument.
8. Check that orphan pool …

DAOS-17819 test: CR Automate Test - Check start options --find-orphans

---

ci/provisioning/post_provision_config_nodes_LEAP.sh

ci/provisioning/post_provision_config_nodes_LEAP.sh:
Something in Leap-15.6 added an additional dependency of the distro
provided lua-lmod that is not removed when lua-lmod is removed and
blocks the install of the newer lua-lmod.

SRE-3236 LUA-LMOD hack fix for Leap 15.6

---

src/container/srv_epoch.c
src/container/srv_target.c

Return CONT_TGT_SNAPSHOT_NOTIFY RPC errno to the snap_oit_create() sponsor instead of converting it as -DER_IO. Then related client side logic can know what the failure is.

DAOS-17845 container: keep CONT_TGT_SNAPSHOT_NOTIFY RPC errno

---

src/control/lib/control/pool.go

When specific properties are requested, dmg pool get-prop outputs the properties in (Go map) random order, leading to unit test failures. (It is also a good idea to offer stable UI output.) This patch sorts the list of properties in the output.

DAOS-17659 control: Sort dmg pool get-prop output

---

docs/admin/pool_operations.md
src/pool/cli.c
src/pool/srv_pool.c

The dc_pool_exclude code path, used by NVMe fault handling, skips the RF check, potentially raising safety concerns. This patch drops flag POOL_TGT_UPDATE_SKIP_RF_CHECK in that code path, so that the RF check will apply.
The error messages logged when the RF check fails focus on ranks. To make them slightly more accurate, this patch updates the wording, and offers the list of DOWN targets when corresponding ranks are UPIN, in the draft pool map built by this POOL_EXCLUDE request. But we are unable to log the list of _all_ unavailable ranks/targets at the moment; the administrator needs to use `dmg pool query` and `dmg storage query list-devices`.
Since NVMe fault handling retries dc_pool_exclude upon -DER_RF, this patch tunes down the engine stdout/stderr output caused by those errors.

DAOS-17802 pool: Check RF for dc_pool_exclude

---

src/control/lib/control/pool.go

TestPoolCommands/Get_pool_properties still fails from time to time with my previous PR #16711. It turns out that I overlooked the hint right at the beginning of the diff,
=== RUN   TestPoolCommands/Get_pool_properties
command_test.go:291: unexpected function calls (-want, +got):
strings.Join({
`*control.PoolGetPropReq-{"Sys":"","HostList":null,"ID":"031bcaf8`,
^^^
which clearly indicates that the problem is with the request, rather than the response. Hence, this patch revises the approach to sort both the properties in the request and the command output.

DAOS-17895 control: Fix TestPoolCommands failures

---

src/tests/ftest/cart/rpc/swim_notification.yaml
src/tests/ftest/cart/test_group_np_cli.c
src/tests/ftest/cart/test_group_np_common.h

Change how the test behaves. At start it will now wait for all 3 ranks to be present and waits 30 seconds after that before rank=2 is shut down.
30 seconds is left to allow for swim notification status to be propagated across all 3 servers in this group.
Added --skip_wait option to clients to skip crtu_wait_for_ranks() call as only first client invocation needs to ensure all 3 servers are up.

DAOS-17871 cart: Improve swim notification test

---

src/pool/srv_pool.c

daos/src/tests/ftest/control/log_entry.py is looking for rank.* is
down messages whereas daos/src/pool/srv_pool.c is no longer printing
within ds_pool_map_tgts_update(). This change reinstates the printing. 
Test-tag: pr vm,test_control_log_entry

DAOS-17942 control: Fix ftest ControlLogEntry by printing updates

---

utils/config/daos_server.yml

Target number is limited by number of SSDs, specify this limitation in daos_server.yml

DAOS-17910 doc: maximum number of targets per SSD

---

src/bio/bio_xstream.c
src/include/daos_srv/bio.h
src/include/daos_srv/vos.h
src/utils/ddb/ddb_commands.c
src/utils/ddb/ddb_spdk.c
src/utils/ddb/ddb_spdk.h
src/utils/ddb/ddb_vos.c
src/utils/ddb/ddb_vos.h
src/vos/vos_common.c

Make sure smd_sync can slove data/meta/wal blobs.
Signed-off-by: Wang Yunpeng <ywang@panasas.com>

DAOS-17308 ddb: command 'smd_sync' support for md-on-ssd mode

---

src/tests/ftest/dfuse/daos_build.yaml

Remove the system_ram_reserved entry from the dfuse/daos_build.py test yaml.

DAOS-17950 test: Fix dfuse/daos_build.py test

---

src/control/server/server_utils.go
src/utils/daos_autotest.c

Lock removal on engine exit callback was being skipped in MD-on-SSD
mode. Fix by returning after lock cleanup.

DAOS-17341 control: Fix remove locks on engine exit

---

src/client/api/init.c
src/common/misc.c
src/container/cli.c
src/gurt/hash.c
src/include/daos.h
src/include/daos/common.h
src/include/daos/container.h
src/include/daos/pool.h
src/include/gurt/hash.h
src/pool/cli.c

This patch marks all pool and container handles as if they were created with g2l in the child processes after fork. It prevents misinteractions if one of the child processes closes the handle.
The marking is done by iterating through all the pool and container handles which was not supported by the hhash code.

DAOS-16563 client: mark pool/cont handle as g2l after fork (#15125)

---

src/gurt/shm_dict.c

Robust mutex needs the address of lock is 4-byte aligned. Otherwise, it cannot work as expected. This was observed on x86_64 platform. It has not been checked on other platforms yet. Since proper alignment normally is a good idea performance-wise, we enforce 4-byte alignment for the data stored in hash table record in shared memory to avoid such mis-alignment related issues. During the memory allocation for hash table record, the space used for padding needs to be included.

DAOS-17988 client: Include padding space during memory allocation

---

.gitignore
src/client/java/daos-java/pom.xml
src/client/java/hadoop-daos/pom.xml
utils/trivy/.trivyignore
utils/trivy/trivy.yaml

Hadoop 3.4.2 eliminates the following vulnerabilities:
CVE-2023-39410,HIGH,7.5,"apache-avro: Apache Avro Java SDK: Memory when deserializing untrusted data in Avro Java SDK","org.apache.avro:avro","1.7.7","1.11.3", https://avd.aquasec.com/nvd/cve-2023-39410
CVE-2024-47561,CRITICAL,,"apache-avro: Schema parsing may trigger Remote Code Execution (RCE)", "org.apache.avro:avro","1.9.2","1.11.4",https://avd.aquasec.com/nvd/cve-2024-47561
CVE-2025-24970,HIGH,,"io.netty:netty-handler: SslHandler doesn't correctly validate packets which can lead to native crash when using native SSLEngine","io.netty:netty-handler", "4.1.100.Final","4.1.118.Final",https://avd.aquasec.com/nvd/cve-2025-24970
CVE-2025-49128,MEDIUM,,"com.fasterxml.jackson.core/jackson-core: Jackson-core Memory Disclosure via Source …

DAOS-17997 cq: Update hadoop from 3.4.1 to 3.4.2

---

src/cart/crt_hg.c
src/cart/crt_hg_proc.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h

- Deadlines were not set for some internal RPCs due to conversion from timeout to deadline happening in an rpc tracking code. Some internal RPCs bypass rpc tracking

DAOS-17990 cart: Fix deadlines

---

src/tests/ftest/recovery/check_policy.py
src/tests/ftest/recovery/check_policy.yaml
src/tests/ftest/recovery/check_repair.py
src/tests/ftest/recovery/check_repair.yaml
src/tests/ftest/recovery/check_start_options.py
src/tests/ftest/recovery/check_start_options.yaml
src/tests/ftest/recovery/check_stop.py
src/tests/ftest/recovery/check_stop.yaml

Update the checker-related tests that are using VM to use Hardware Medium so that they run on MD-on-SSD
cluster.
Skip-func-hw-test-medium: false
Test-tag: DMGCheckPolicyTest DMGCheckRepairTest DMGCheckStartOptionsTest DMGCheckStopTest

DAOS-17497 test: Adjust CR tests for md-on-ssd mode 1

---

src/tests/ftest/recovery/check_start_corner_case.py
src/tests/ftest/recovery/check_start_corner_case.yaml

Update check_start_corner_case.py/yaml to use
Hardware Medium so that they run on MD-on-SSD
cluster.
Skip-func-hw-test-medium: false
Test-tag: DMGCheckStartCornerCaseTest

DAOS-17497 test: Adjust CR tests for md-on-ssd mode 2

---

src/vos/vos_dtx.c

It will be helpful to understand the DTX status when hit in-aborting DTX entry during update.

DAOS-18003 vos: more log message when hit in-aborting DTX entry

---

src/tests/ftest/daos_test/suite.yaml

Increase test_daos_rebuild_ec timeout 30 minutes
Test-tag: test_daos_rebuild_ec

DAOS-17673 test: Increase test_daos_rebuild_ec timeout

---

src/client/dfuse/dfuse_main.c

If using MPI to launch dfuse, we should not force running in the foreground as that introduces several limitations. MPI like clush should be able to launch and daemonize dfuse.

DAOS-18015 dfuse: do not force foreground if run with MPI
