- .gitmodules
Change-Id: Idf6ceba5ae4f360d0c117d5367f682b6a99ae047
> DAOS-2158 build: Update submodule URL for scons_local

- Jenkinsfile
When a build fails.
Change-Id: Ib963f355e92283b7ed4190d932b6de53931dd8d8
> CORCI-413 Put config.log into artifacts

- src/bio/smd/smd_device.c
smd_nvme_get_device() should return 0 on success.
Change-Id: I2deb3818eeee5a8d45d9b31f7a4aa2e1b8ebcba2
> DAOS-2152 smd: typo in smd_nvme_get_device()

- src/bio/bio_buffer.c
ABT locks of bio_desc are required only for NVMe/SPDK, it will add
extra latency to small I/O patch because creation of ABT_mutex and
ABT_cond take about 1 micro-second.
This patch moves allocation of these locks to bio_iod_post() and
they are created on demand.
> DAOS-2157 bio: don't create ABT locks for SCM

- src/common/README.md
- src/control/README.md
- src/control/drpc/README.md
Added documentation for the dRPC C and Golang APIs.
> DAOS-1602 docs: Document dRPC APIs

- src/utils/py/daos_api.py
- src/utils/py/daos_cref.py
- Added DTgtList Structure to Python API.
- Updated DTgtList instead of Ranklist for pool.exclude, pool.exclude_out, pool.add
- Pool/Container Properties updated in Async API.
- Clean some Indentation in code.
Signed-off-by: Samir <samir.raval@intel.com>
> DAOS-2094 Test: A couple of functions removed from API.

- src/client/api/container.c
- src/common/misc.c
- src/container/cli.c
- src/container/rpc.h
- src/container/srv_container.c
- src/container/srv_epoch.c
- src/container/srv_internal.h
- src/container/srv_layout.c
- src/container/srv_layout.h
- src/include/daos/common.h
- src/include/daos_task.h
- src/include/daos_types.h
- src/tests/suite/daos_container.c
- src/tests/suite/daos_pool.c
- src/tests/suite/daos_test.h
- src/tests/suite/daos_test_common.c
Change-Id: I01ba921ee423288a9c5f7c74f2d6a80f8ae5541f
> DAOS-2031 metadata: add container properties API implementation

- utils/check_modules.sh
- utils/docker/Dockerfile.centos:7
So that pylint will find all of the imported modules.
> CORCI-601 Add functional test paths to PYTHONPATH

- src/SConscript
- src/client/dfs/SConscript
- src/client/dfs/dfs.c
- src/client/dfs/dfuse.c
- src/client/dfs/duns.c
- src/client/dfs/duns_tool.c
- src/common/misc.c
- src/include/daos/common.h
- src/include/daos/debug.h
- src/include/daos_fs.h
- src/include/daos_types.h
- src/include/daos_uns.h
DAOS-2010 dfs: add new tool & API for setting DAOS specific xattrs
> Duns initial

- Jenkinsfile
When a new patch is pushed to a PR, cancel any in-progress build/test
jobs.
> CORCI-607 Cancel previous jobs in progress

- utils/docker/Dockerfile.leap:15
- utils/docker/Dockerfile.ubuntu:18.04
> DAOS-892 doc: Remove unused SPDK pkgs from docker files

- src/rsvc/README.md
Add an initial README for module rsvc.
Change-Id: I66cdbda9edba9184e1f2a5ea04f5e782c12c21b0
> DAOS-2154 rsvc: Add README.md

- src/vos/README.md
This is partial documentation of VOS.   About 1/3 through the file so far
> DAOS-2169 doc: Update VOS documentation

- src/client/api/README.md
> DAOS-1981 update README.md for client API

- src/object/README.md
> DAOS-2166 doc: add object module's readme

- src/rebuild/README.md
Add README for rebuild. It is just an initial version, and I
will update it.
> DAOS-2141 rebuild: add README

- src/vos/vea/tests/vea_ut.c
- src/vos/vea/vea_api.c
Fixed defect in process_resrvd_list() where the last disjoint
extent isn't processed. Improved unit test to verify the fix.
Change-Id: Ia1049cbc42c79405d1f6c2fa997c9d58ef7dcaa2
> DAOS-2217 vea: defect in extent publish/cancel

- src/common/README.md
> DAOS-1981 readme: Update common Readme.md with TSE overview

- src/rebuild/README.md
> DAOS-2141 rebuild: update rebuild readme

- src/include/daos_srv/daos_server.h
- src/iosrv/README.md
Document the module interface, TLS, ABT integration and IV support.
> DAOS-2172 doc: update iosrc README.md

- SConstruct
> DAOS-2172 version: bump version to 0.4

- src/control/README.md
- src/control/client/README.md
- src/control/common/README.md
- src/control/dmg/README.md
- src/control/server/README.md
Add individual package readmes and link to from
src/control/README.md. Update with brief summaries and expand server
and management tool descriptions.
> DAOS-1213 control: add and update pkg readme files

- src/vos/README.md
- src/vos/tests/SConscript
- src/vos/tests/vos_dfs_sample.yaml
- src/vos/tests/vos_size.py
- src/vos/tests/vos_size_input.yaml
Modify format of input yaml to make it more flexible and
powerful.  Update the vos_size tool accordingly
> DAOS-2169 vos: Update the vos metadata overhead tool

- src/common/misc.c
- src/utils/dmg.c
Add single target exclude to dmg exclude command.
> DAOS-2236 utils: add target exclude to dmg exclude

- src/tests/daos_perf.c
> DAOS-2293 daos_perf: add large object class option to DAOS perf

- src/object/cli_shard.c
If an RPC fails sending, the shard decref is done twice, once in the
body function and another in the completion CB.
> DAOS-2267 object: Avoid double decref when RPC fails

- Jenkinsfile
- utils/docker/Dockerfile.leap.42.3
- utils/docker/Dockerfile.sles.12.3
Signed-off-by: John.E.Malmberg <john.e.malmberg@intel.com>
> CORCI-638 build: Add SLES 12.3 / Leap 42.3

- src/object/cli_obj.c
Remove the temporary variable "io_retry" from the function
obj_comp_cb(). Then all the client stack IO retry will be
controlled via obj_auxi_args::io_retry that will enable
subsequent retry in related RPC sponsor logic, such as
dc_obj_update()/dc_obj_punch().
> DAOS-2310 object: unify client stack io retry control

- src/utils/py/daos_api.py
Signed-off-by: ravalsam <samir.raval@intel.com>
> DAOS-2313: Pool query test API updated because of recent addition of query info bit.

- src/client/dfuse/SConscript
- src/client/dfuse/dfuse.h
- src/client/dfuse/dfuse_cont.c
- src/client/dfuse/dfuse_core.c
- src/client/dfuse/dfuse_fuseops.c
- src/client/dfuse/dfuse_main.c
- src/client/dfuse/dfuse_pool.c
- src/client/dfuse/ops/lookup.c
Add support for automatically connecting to pools.
Keep a reference on the parent inode on successfull lookup.
> DAOS-2279 dfuse: Implement automatic pool connect.

- src/vos/tests/vts_aggregate.c
> DAOS-2453 test: Fix VOS 414 Test case string

- src/common/mem.c
Tweak the pmem_tx_free() to skip pmemobj_tx_free() call when the
transaction is already aborted, this could happen on error cleanup
code path.
The reason we don't fix caller to avoid calling tx_free() in an
aborted transaction is that the caller code could be shared by both
transactional and non-transactional (where UMEM_CLASS_VMEM is used,
see btree code) interfaces, and the explicit umem_free() on error
cleanup is necessary for non-transactional case.
Change-Id: If1004298693575c864b4ce4dc0b6e69fd05b798b
> DAOS-2431 umem: skip tx_free() for aborted transaction

- src/pool/srv_iv.c
> DAOS-2466 pool: fix a bug in pool_iv_value_alloc_internal

- Jenkinsfile
- src/tests/ftest/launch.py
Instead of Job-<date/time>-<hash>:
name the dirs after the test that created them:
> CORCI-662 More sensibly named artifact dirs

- src/utils/py/daos_api.py
Signed-off-by: ravalsam <samir.raval@intel.com>
> DAOS-2483: Add support for container aggregation in Python test API.

- src/mgmt/srv_target.c
Create a pthread to execute the fallocate calls and avoid blocking
progress on context 0 during fallocate
> DAOS-2159 pool: Pool create times out

- src/utils/dmg.c
Signed-off-by: ravalsam <samir.raval@intel.com>
> DAOS-2528: Update target and rank help message for dmg utility 

- SConstruct
- src/utils/py/daos_api.py
> DAOS-2172 version: bump version to v0.5

- src/utils/py/daos_api.py
epoch need to pass as an argument to the daos_cont_aggregate() and not the pointer to the epoch.
> DAOS-2555:Aggregation not migrating IOR data to SSD.

- src/tests/ftest/daos_test/daos_core_test.yaml
> DAOS-2501 test: enable rebuild tests until 20

- src/pool/srv_util.c
Add target status changing message to console
for rebuild test.
> DAOS-2670 pool: add target status to console

- src/control/Gopkg.toml
- src/control/vendor/github.com/daos-stack/go-ipmctl/README.md
- src/control/vendor/github.com/daos-stack/go-ipmctl/Taskfile.yml
- src/control/vendor/github.com/daos-stack/go-ipmctl/ipmctl/nvm.go
- src/control/vendor/github.com/daos-stack/go-ipmctl/ipmctl/nvm_test.go
- src/control/vendor/github.com/daos-stack/go-ipmctl/ipmctl/nvm_types.go
- src/control/vendor/github.com/daos-stack/go-spdk/README.md
- src/control/vendor/github.com/daos-stack/go-spdk/Taskfile.yml
- src/control/vendor/gopkg.in/yaml.v2/encode.go
Update versions of src/control/vendor Go packages to keep up-to-date
with recent changes.
> DAOS-2675 control: bump vendor packages

- src/vos/tests/evt_ctl.c
> DAOS-2645: Validate evt_iter_delete,evt_find and delete extents.

- src/object/cli_obj.c
> DAOS-2444 obj: fix CLANG build error

- src/common/misc.c
- src/tests/suite/daos_obj.c
- utils/build.config
> DAOS-2444 obj: fix a sg_nr_out handling

- src/pool/srv_util.c
During the pool step up, it needs to query DOWN targets
from the pool map, and uses fseq+1 as the rebuild version
to match the normal rebuild process.
> DAOS-2379 rebuild: Use fseq+1 as rebuild version

- src/placement/tests/place_obj.c
> DAOS-1766 placement: fix err in pl_map UT

- src/include/daos_api.h
- src/pool/cli.c
- src/pool/rpc.h
- src/pool/srv_pool.c
- src/pool/srv_target.c
- src/tests/daosctl/pool-cmds.c
- src/utils/py/daos_api.py
> DAOS-2655 rebuild: fix a bug of return rebuild_status when connect

- src/tests/ftest/container/simple_create_delete_test.py
- src/tests/ftest/container/simple_create_delete_test.yaml
Removed the fixed gid and uid values from the yml file and added the function call to pool_create from general_utils.py
Signed-off-by: Amanda Justiniano <amanda.justiniano-pagn@intel.com>
> Changes to how test creates and connects to pool.

- doc/admin/administration.md
- doc/admin/app_interface_tiering.md
- doc/admin/architecture.md
- doc/admin/env_variables.md
- doc/admin/hardware.md
- doc/admin/index.md
- doc/admin/installation.md
- doc/admin/intro.md
- doc/admin/performance_tuning.md
- doc/admin/pool_operations.md
- doc/admin/troubleshooting.md
- doc/admin/utilities_examples.md
Line endings changed to unix LF, minor changes in content formatting to
be compliant with mkdocs.
Signed-off-by: Craig Durfey <craig.durfey@intel.com>
> DAOS-2748 - Fix line endings and updates

- SConstruct
- doc/quickstart.md
also rename daos_m.conf to daos.conf
> DAOS-2666 docs: remove use_installed from quickstart

- .gitignore
> DAOS-2666 gitignore: add daos.conf to .gitignore

- src/tests/ftest/daos_test/daos_core_test.yaml
Disable rebuild30 test temporarily.
> DAOS-2716 tests: disable rebuild30 test

- src/client/dfs/dfs.c
> DAOS-2666 dfs: fix some compile warnings with strncpy

- .travis.yml
- doc/admin/installation.md
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.leap.42.3
- utils/docker/Dockerfile.sles.12.3
- utils/docker/Dockerfile.ubuntu.18.04
Fix docker file name and update scons command line.
> DAOS-2412 doc: update docker build instructions

- doc/admin/app_interface_tiering.md
Wrap at 80 columns and update dfuse instructions.
Add reference to daos utility for container creation.
> DAOS-2412 doc: update app interface section of admin guide

- SConstruct
- src/utils/py/daos_api.py
- utils/rpms/daos.spec
> DAOS-2172 version: dump version to v0.6

- src/mgmt/srv.c
Fix the cleanup code in process_drpc_request() when ds_mgmt_create_pool()
failed. Protobuf initializes both create_pool_resp->{svcreps,uuid} to a
static string equal to "\0" which should not be freed with D_FREE().
> DAOS-2782 mgmt: fix segfault when ds_mgmt_create_pool() fails

- src/tests/ftest/util/apricot/apricot/test.py
> NodeSet.fromlist() takes a python list

- src/common/btree.c
During the btr_probe(), when we locate some position in the tree,
we will check whether related record is available or not because
of some potential aborted or uncommitted DTX attached to related
target/record. For update/punch operation, we will check whether
the target exists or not, if not exists, we will find a suitable
position to insert the new target/record. Such position is not a
fixed one, instead, it is the relative order among its neighbors.
So if the update/punch target (object/key) itself does not exist,
then in spite of whether its neighbors are available or not will
not affect the modifcation target's position. Means that even if
the DTX for some of its neighbor is aborted, the positions order
between current new target/record and such aborted one will keep
the same. So it …
> DAOS-2819 dtx: do availability check only when necessary

- src/bio/README.md
- src/vea/README.md
Also adjusted indent in both BIO and VEA READMEs.
> DAOS-2682 bio: Incorrect filename in BIO README

- src/client/dfs/dfs.c
- src/include/daos_fs.h
> DAOS-2926 dfs: new API to update parent and entry name of an open handle

- src/dtx/dtx_common.c
- src/include/daos/object.h
- src/object/cli_obj.c
- src/vos/vos_dtx.c
1. make it works in sync commit for EC obj
to simplify the EC fetch handing for now.
2. a few other minor changes
> DAOS-2444 obj: make it works in sync commit for EC obj

- src/tests/ftest/daos_test/daos_core_test-rebuild.yaml
disable rebuild30 temporarily for DAOS-2943.
> DAOS-2943 tests: disable rebuild30

- src/vos/tests/csum_extent_tests.c
> DAOS-2998: csum_extent_tests.c: error: Failure!

- Jenkinsfile
We occasionally run into times when the DAOS RPM build fails due to
component library incompatibilities. This is a temporary situation which
will be resolved when component libraries are properly maintaining
versions and we have a repository server capable of serving multiple
versions of libraries at the same time.
Until then we need to occasionally disable requiring the RPM builds
and/or tests to pass.
> DAOS-3035 Allow DAOS RPM builds and/or tests to fail

- Jenkinsfile
- ftest.sh
Also make ftest.sh work better outside of Jenkins.
> DAOS-3020: test: Use clush instead of pdsh in ftest.sh

- doc/mkdocs.yml
Add mkdocs.yml file to publish documentation on GitHub pages.
See https://www.mkdocs.org/user-guide/deploying-your-docs/ for
more information.
Signed-off-by: Johann Lombardi <johann.lombardi@@intel.com>
> DAOS-2412 doc: add mkdocs yml file

- src/client/dfs/dfs.c
- src/client/dfs/dfuse_hl.c
- src/include/daos/common.h
- src/tests/suite/daos_obj_array.c
> DAOS-2666 dfuse_hl: fix return value of get xattr

- src/control/run_go_tests.sh
Missed this in local/CI testing because the variables were
set externally. In the case where build environment variables
need to be set, provide default empty values to avoid triggering
unset variable errors. Also adds hwloc path to environment.
> DAOS-3085 control: Fix go test runner environment

- Jenkinsfile
Changes to make the Jenkinsfile more compatible with the weekly-testing
branch so that changes to master can be easily synced to weekly-testing.
> CORCI-610 test: Sync with the weekly-testing branch

- Jenkinsfile
- utils/docker/Dockerfile-mockbuild.centos.7
- utils/docker/Dockerfile.centos.7
Guard stages we don't want to run using the weekly-testing branch name.
The goal here is that master and weekly-testing should be only a very
little different.
> Further sync with master

- doc/admin/deployment.md
Remove initial link to basic workflow as requested.
> DAOS-3171 doc: admin guide deployment fixup

- doc/admin/deployment.md
- doc/middleware.md
- doc/mkdocs.yml
- doc/overview/fault.md
- doc/overview/security.md
- doc/overview/storage.md
- doc/overview/terminology.md
- doc/overview/transaction.md
- doc/overview/use_cases.md
> DAOS-2412 doc: split storage.md into multiple files

- src/client/array/dc_array.c
- src/container/oid_iv.c
> DAOS-2666 container: add debug logs for oid IV allocator

- Jenkinsfile
Rather than the lastSuccessfulBuild daos RPMs.
> DAOS-2240 test: Install daos RPM from the build

- src/dtx/dtx_rpc.c
> DAOS-2469 dtx: add a few log to DTX RPC

- doc/admin/deployment.md
- src/control/server/README.md
Update admin guide and README to reflect syntax changes.
> DAOS-3245 doc: update storage prepare syntax

- Jenkinsfile
- utils/docker/Dockerfile-rpmbuild.leap.42.3
Also, build all RPMs on Quick-build.  They are all quick so don't
impact the goal of Quick-build.
> DAOS-2240 build: Build RPMs on Leap 42.3

- Jenkinsfile
Send email when breaking the build
> CORCI-633 build: Send email when breaking the build

- src/tests/ftest/io/ior_small.py
- src/tests/ftest/io/mdtest_small.py
> renable mdtest and ior small tests after updating respective repos

- src/control/server/storage_scm.go
- src/control/server/storage_scm_prep.go
- src/control/server/storage_scm_prep_test.go
- src/control/server/storage_scm_test.go
Enable successful format without ndctl package installed since this
is only a hard requirement for PMEM device file scan and SCM prepare.
Verify binary is available before use in all relevant functions to
provide reliable error handling. Improve test coverage to fill gaps and
check for regressions in this behaviour.
> DAOS-3307 control: allow format with no ndctl installed

- src/proto/Makefile
> DAOS-3333 proto: Fix Protobuf Makefile

- src/pool/srv_pool.c
This patch fixes a few regressions in ds_pool_connect_handler:
- When failing to read the pool map, ds_pool_connect_handler leaks
ps_lock and other resources.
- When failing to transfer the pool map, ds_pool_connect_handler leaks
the properties.
- The comment on the pool map transfer is moved to the wrong place.
> DAOS-3306 pool: Fix ps_lock leaks in POOL_CONNECT

- Jenkinsfile
- utils/rpms/Makefile
> DAOS-3341 Fix "tech" name for el-7

- SConstruct
- src/SConscript
- src/control/SConscript
> DAOS-2666 build: Use our build of ofi in control plane

- doc/admin/installation.md
Update as per feedback on the mailing list:
- add reference to modprobe uio_pci_generic
- clarify mem/disk requirements on Mac
> DAOS-2412 doc: update docker instructions

- src/tests/ftest/io/ior_small.yaml
- src/tests/ftest/pool/destroy_rebuild.yaml
- src/tests/ftest/pool/info_tests.yaml
- src/tests/ftest/pool/rebuild_no_cap.yaml
- src/tests/ftest/pool/rebuild_tests.yaml
- src/tests/ftest/pool/rebuild_with_io.yaml
- src/tests/ftest/pool/rebuild_with_ior.yaml
- src/tests/ftest/rebuild/container_create.yaml
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/server_utils.py
Error reported on master:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/1060/
Reverts daos-stack/daos#1147
> Revert "DAOS-3302 test: Targets specification needs to be under "server:""

- doc/admin/installation.md
Updated the section to reflect what is currently being
built for dependencies/components
> Updated SW installation dependencies section

- src/tests/SConscript
- src/tests/daos_racer.c
- utils/rpms/daos.spec
> DAOS-3528 test: add daos_racer

- src/client/dfs/dfs.c
- src/tests/ftest/daos_test/daos_core_test.yaml
- src/tests/suite/SConscript
- src/tests/suite/daos_test.c
- src/tests/suite/daos_test.h
- src/tests/suite/dfs_test.c
- Add Xuezhao's test for multi-threaded read
- Add simple mount / umount test
- verify POSIX container type in dfs_mount
> DAOS-3549 DFS: Add initial test suite

- src/common/README.md
Updated to reflect code changes and meet line width
requirements.
> DAOS-2929 doc: Update dRPC C API docs

- src/common/tests/abt_perf.c
Add a few more tests to abt_perf to benchmark Argobots performance
> DAOS-2157 common: Add more tests to abt_perf

- src/placement/SConscript
- src/placement/tests/SConscript
- src/placement/tests/jump_map_place_obj.c
- src/placement/tests/place_obj_common.c
- src/placement/tests/place_obj_common.h
- src/placement/tests/ring_map_place_obj.c
- src/tests/ftest/unittest/unittest.py
- src/tests/ftest/unittest/unittest.yaml
- utils/rpms/daos.spec
Updated Unit tests for placement.
- Separate unit tests for Jump Map and Ring Map.
- Moved common test functions to separate files.
- Added tests to unittest files.
> DAOS-3527 Placement: Create Placement Map Unit Tests

- src/client/pydaos/raw/daos_cref.py
- src/include/daos_types.h
- src/pool/rpc.c
- src/rebuild/README.md
- src/rebuild/initiator.c
- src/rebuild/rebuild_internal.h
- src/rebuild/rebuild_iv.c
- src/rebuild/srv.c
- src/tests/ftest/util/test_utils.py
- src/tests/suite/daos_rebuild.c
Add time costs to rebuild query information.
> DAOS-3203 rebuild: add time costs to rebuild

- src/tests/ftest/io/mdtest_small.py
> DAOS-3519 DFS: re-enable mdtest PR testing with DFS after IOR was updated in CI

- Jenkinsfile
> CORCI-818: test

- src/mgmt/srv_pool.c
ds_mgmt_create_pool creates a temporary group for the MGMT_TGT_CREATE
CORPC. Since CaRT will eventually remove crt_group_create, this patch
replaces the temporary group by sending the MGMT_TGT_CREATE CORPC to a
specific subset of the primary group (using a new crt_corpc_req_create
flag).
> DAOS-2822 mgmt: Remove pool create temporary group

- src/client/dfs/dfs.c
- src/include/daos_fs.h
> DAOS-3638 DFS: add optional prefix option to trim off absolute path lookup

- src/client/dfs/dfs.c
> DAOS-3638 DFS: fix prefix len check

- src/vos/ilog.c
Cache return values in ilog_fetch
Fetch and cache entire log
Refresh the status if the previous return code was -DER_INPROGRESS
> DAOS-3735 vos: More careful caching of incarnation log

- src/control/provider/system/system_linux.go
- src/control/server/storage/scm/provider.go
The returned SCM state wasn't set, resulting in Prepare requests
failing due to unknown SCM state.
Also adds code to handle unmounting mounted SCM namespaces prior
to reset.
> DAOS-3670 control: Record SCM state from forwarded Scan result

- src/vos/vos_io.c
If client specified zero-sized IOD (daos_recx_t::rx_nr is zero),
then handle it as NOP.
> DAOS-3693 vos: skip IO for zero-sized IOD

- src/tests/daos_racer.c
To check whether or not replicas consistency for replicated object
is affectted by some random successful (or failed) modification in
the racer test.
> DAOS-3681 tests: verify replicas consistency after racer test

- src/control/lib/hostlist/hostlist_test.go
- src/control/lib/hostlist/hostset.go
- src/control/lib/hostlist/hostset_test.go
* Ensure that zero values are useful
* Add HostSet.MergeSet() for efficient HostSet merging
> DAOS-3407 control: Misc HostList/HostSet improvements

- src/vos/vos_io.c
Originally, we did not assign value to ioc::io_umoffs for EV record
on NVMe case. It was not problem before we check the ioc::ic_umoffs
for such case. With patch 8679ec77f42edcfdcd1ab06a6fb7ec05fe8fc65b,
we need to check ioc::ic_umoffs for both SCM and VNMe cases. So set
it as UMOFF_NULL for EV record on NVMe.
> DAOS-3815 vos: init ioc::ic_umoffs for EV record on NVMe

- src/tests/ftest/network/cart_self_test.py
> Changed the uri location from basepath to tmp

- src/include/daos_srv/daos_server.h
- src/iosrv/vos.c
- src/object/srv_obj.c
Only pack punch key epoch for rebuild iteration.
> DAOS-2185 enumerate: do not pack punch epoch

- src/container/container_iv.c
- src/include/daos_srv/container.h
Add snapshot invalidate/fetch for snapshot IV.
> DAOS-2185 iv: Add snapshot invalidate/fetch

- src/rdb/rdb_raft.c
Since epoch is not allowed to be 0 after new punch model,
Let's use epoch in record for snapshot replication.
> DAOS-3783 rdb: use epoch in record for installing snapshot

- src/container/container_iv.c
PR #1450 used some functions whose signatures were modified
by PR #1393.
> DAOS-2185 iv: Fix build failure

- utils/rpms/daos.spec
> DAOS-3763 build: Require minimum version of libfabric

- src/control/cmd/dmg/main.go
This patch adds support for dmg commands to access the
client configuration.
> DAOS-3610 dmg: Support commands using client config

- .github/CODEOWNERS
For adding VOS team members for VOS changes
> DAOS-623 build: Add code owner for VOS files

- Jenkinsfile
> DAOS-623 build: Move mpich back to default branch

- src/tests/daos_racer.c
It is possible that daos_racer generates the OID that object class
is out of the range of vos targets count in the system. Under such
case, related DAOS API will return -DER_INVAL. That is normal, the
daos_racer should not break because of that.
> DAOS-3681 tests: verify consistency for valid DID after racer

- Jenkinsfile
- utils/build.config
> DAOS-623 Untranspose - and _ in daos-adio_rpm

- src/vos/tests/vts_aggregate.c
In the multiple keys aggregation unit test, the expected physical
records should be zero when there isn't any updates in aggregate
EPR, the original way of comparing update EPR with aggregate EPR
to get expected recs is wrong, because it is sparse updating for
multiple key test cases.
Change-Id: I428cdb7b2f4b60166ceb7cb97e5a3a1b319df92d
> DAOS-3870 tests: defect in VOS aggregation unit test

- src/tests/suite/daos_verify_consistency.c
To simulate some failure cases, we make the rank_0 thread (for replicas
consistency verification) to set fail_loc at some points, then reset it
after the test done. But because of schedule issue the rank_0 may reset
the fail_loc too early before other ranks complete related tests. So we
need synchronization among related threads before reset fail_loc.
> DAOS-3893 tests: synchronization before reset fail_loc

- doc/admin/deployment.md
> Reviewed deployment section; minor edit

- src/common/prop.c
- src/include/daos_prop.h
- src/include/daos_srv/pool.h
- src/pool/srv_internal.h
- src/pool/srv_iv.c
- src/pool/srv_layout.c
- src/pool/srv_pool.c
- src/pool/srv_target.c
- src/tests/suite/daos_pool.c
Propagate pool reclaim prop into ds_pool through pool prop IV, it'll
be used by aggregation ULT.
Change-Id: Ied17e67989fd3238511a698d5a5d9138a1c6e321
> DAOS-3614 pool: Propagate reclaim prop

- Jenkinsfile
So that we can update CaRT to lastest master which is an ABI break.
> DAOS-3934 build: Pin ior-hpc and mpich versions

- src/control/server/instance.go
- src/control/server/superblock.go
- src/tests/ftest/data/daos_server_baseline.yaml
- src/tests/ftest/launch.py
- src/tests/ftest/util/server_utils.py
* Log SCM total/avail on startup
* Enable daos_admin logs in CI
> DAOS-3918 control: Improve daos_server startup output

- Jenkinsfile
- ftest.sh
- utils/docker/Dockerfile.centos.7
Move pre and post Functional Test cleanup to Jenkinsfile.
- This allows one to accumulate results when running locally for
comparisons, etc.
> DAOS-623 Miscellaneous small FTest fixes

- src/client/dfs/dfs.c
> DAOS-2666 DFS: fix build warnings on fedora

- doc/admin/deployment.md
Give up-to-date instructions on control plane parallel start-up and
format using daos_server and dmg.
> DAOS-2592 doc: update admin deployment basic workflow

- Jenkinsfile
Use mpich and IOR from the repo.
- pin their version to something compatible.
> DAOS-623 build: Backport some changes from master

- doc/admin/deployment.md
- doc/admin/env_variables.md
- doc/admin/installation.md
- doc/admin/pool_operations.md
- doc/admin/troubleshooting.md
- doc/admin/utilities_examples.md
- doc/mkdocs.yml
Restructure deployment section slightly to merge
the workflow with subsequent sub-sections.
> DAOS-2592 doc: merge subsections of the deployment section

- src/client/java/README.md
- src/client/java/daos-java-api/find_java_home.sh
- src/client/java/daos-java-api/pom.xml
- src/client/java/daos-java-api/src/main/java/com/intel/daos/client/Constants.java
- src/client/java/daos-java-api/src/main/java/com/intel/daos/client/DaosFile.java
- src/client/java/daos-java-api/src/main/java/com/intel/daos/client/DaosFsClient.java
- src/client/java/daos-java-api/src/main/java/com/intel/daos/client/DaosObjectType.java
- src/client/java/daos-java-api/src/main/java/com/intel/daos/client/StatAttributes.java
- src/client/java/daos-java-api/src/main/native/com_intel_daos_client_DaosFsClient.c
- src/client/java/daos-java-api/src/main/native/include/com_intel_daos_client_DaosFsClient.h
- src/client/java/daos-java-api/src/main/resources/log4j2.xml
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFileIT.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFsClientIT.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFsClientTestBase.java
- src/client/java/hadoop-daos/pom.xml
- src/client/java/hadoop-daos/src/main/resources/log4j2.xml
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosFSFactory.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosInputStreamIT.java
- src/client/java/pom.xml
This PR is to continue the Java Wrapper. It includes,
- upgraded log4j to log4j2 to fix log4j vulnerability.
- fixed JVM crash when shutdown
- fixed miscellaneous issues from review. They are,
1, remove pool creation related code
2, add the move function with parameter of opened source dir and target dir
3, use object type name instead of id
4, more comments in Constants and StatAttributes
5, newline after declaration
> DAOS-3906 Add DAOS DFS Java API and implement Hadoop FileSystem Interface

- doc/admin/performance_tuning.md
Add instructions for running self_test with test_group
to doc/admin/performance_tuning.md
> CART-838 Add instructions to the DAOS admin guide for CaRT self_test

- src/tests/ftest/launch.py
> DAOS-4010: Change to launch to set speed on "down" device

- src/include/daos_srv/daos_server.h
- src/iosrv/vos.c
- src/rebuild/initiator.c
- src/rebuild/rebuild_internal.h
Remove iod_eprs from rebuild pack/unpack process.
> DAOS-1662 rebuild: remove iod_eprs from rebuild.

- src/rebuild/scan.c
Since pool map will be shared by all xstreams on each server,
let's lock the pool map before accesing it.
And also do collective scan done even if it failed, otherwise
it will hang there.
> DAOS-3951 rebuild: lock the pool map during rebuild accessing

- utils/build.config
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.leap.42.3
- utils/docker/Dockerfile.ubuntu.18.04
Try RC1 because it's the latest version
> DAOS-0000 VOS: switch to pmdk-1.8

- doc/admin/deployment.md
Add documentation covering installation and configuration
of privileged helper binary.
> DAOS-2881 control: Update admin guide for daos_admin

- src/include/daos_task.h
> DAOS-2666 headers: do not include private headers in public API

- src/control/SConscript
Modified installation code for these two directories and their sub_dirs:
./install/share/spdk
./install/include/spdk
Change-Id: I66ce247dd4c367e8e1deaec9ccae11ec79b38b8b
Signed-off-by: Hua Kuang <hua.kuang@intel.com>
> DAOS-2382 build: DAOS should clean SPDK files from "scons -c install"

- doc/admin/deployment.md
> DAOS-4011 doc: Update admin guide with NVMe SSD health monitoring

- src/iosrv/sched.c
- src/iosrv/srv.c
Minor cleanup on error handling & comments in dss_srv_handler().
> DAOS-4073 iosrv: minor cleanup to iosrv scheduler

- utils/build.config
Update to CART 63fa727c055c2446f4f6f2d06d3aec8e84071c2b in order
to pick up latest OFI
> DAOS-4079 ofi: Update to latest cart

- src/pool/srv_iv.c
- src/pool/srv_util.c
> DAOS-3948 pool: two ds_pool leaks

- SConstruct
> CORCI-812 release: Use raw_input() on Python 2

- src/container/srv_target.c
Free snapshots in cont_child_aggregate().
> DAOS-4128 container: free snapshots

- SConstruct
> DAOS-623 lint: Address SConstruct pylint warnings

- Jenkinsfile
> CORCI-812 release: Update release branch name prefix

- src/placement/README.md
- Added sections to the document to reflect the addition and usage
of the Jump Map Placement Map.
- Corrected encoding errors.
- Rearranged several sections to make sense with new additions.
> DAOS-2202 doc: Update Placement Documentation to Reflect Jump Map.

- src/placement/README.md
- Added sections to the document to reflect the addition and usage
of the Jump Map Placement Map.
- Corrected encoding errors.
- Rearranged several sections to make sense with new additions.
> DAOS-2202 doc: Update Placement Documentation for Jump Map. (#1820)

- src/bio/bio_xstream.c
The newly added whitelist in BIO breaks AIO device support, it's
actually not useful for AIO device, so we can just skip whitelist
thing for non-NVMe devices for this moment.
A memory leak in the whitelist code is fixed too.
> DAOS-4151 bio: skip whitelist for AIO device

- src/pool/srv_target.c
Check sp_map inside ds_tgt_pool_map_update().
> DAOS-3890 target: check the sp_map

- Jenkinsfile
- utils/rpms/packaging/Dockerfile.mockbuild
Due to https://github.com/rpm-software-management/mock/issues/484.
Skip-run_test: true
> DAOS-623 build: Pin mock and mock-core-configs

- src/object/cli_shard.c
- src/tests/suite/daos_obj.c
When obj fetch with smaller sgl buffer, it will return DER_REC2BIG.
This patch set the iod.iod_size for that case so user can know the
needed length of buffer.
> DAOS-2448 obj: set iod_size for DER_REC2BIG case

- Jenkinsfile
- ftest.sh
- src/tests/ftest/launch.py
- utils/docker/Dockerfile.centos.7
From servers in Functional test.
> CORCI-747 test: Collect and process core files

- src/control/server/storage/scm/mocks.go
Missed this in review. The commit which introduced support
for mocking multiple mount points did unsafe access to the
isMounted map, resulting in intermittent race detector
failures.
> DAOS-4002 control: Fix race in scm mock

- src/tests/suite/daos_kv.c
add tests to check for DER_REC2BIG when small buffer is used for fetch.
> DAOS-2448 KV: daos_kv_get() should return size when buffer is small

- src/tests/ftest/util/test_utils_pool.py
> DAOS-4200 SystemTest: Regression in getting the NVMe pool size value from test file.

- utils/config/daos.yml
- utils/config/daos_agent.yml
- utils/config/daos_server.yml
- utils/rpms/daos.spec
- utils/systemd/daos_agent.service
- utils/systemd/daos_server.service
* Rename services to match the daemon names
* Fix daos_server service to include start argument
* Remove -i flag from server/agent services -- should be
handled via config file
* Update config yaml to make security options clearer
> DAOS-4081 control: Update systemd unit files

- src/tests/ftest/util/test_utils_pool.py
> DAOS-4205 fix issue with groupname

- src/iosrv/ult.c
The ABT_thread_attr_free() may fail after the child ULT created.
We should not return such failure to the caller. Otherwise, the
caller will free the parameters "arg" that is being used by the
child ULT as to segfault.
So let's ignore the failure, the worse case is that we may leak
some DRAM, but that is not fatal.
> DAOS-4244 iosrv: ignore ABT_thread_attr_free failure

- doc/admin/installation.md
> Update Admin guide-installation-building daos

- src/mgmt/srv_target.c
Fix bit shift in tgt_profile_task.
> DAOS-4250 mgmt: bit shift in tgt_profile_task

- Jenkinsfile
Convert to only using snapshot restores for hardware tests.
> CORCI-852 build: Convert to Snapshot restores

- src/tests/suite/daos_epoch_io.c
Fix SDL/Coverity reported warning in epoch_io test.
> DAOS-4251 test: fix SDL warning in epoch_io test

- src/client/api/tests/SConscript
- src/tests/ftest/unittest/unittest.py
- src/tests/ftest/unittest/unittest.yaml
Added agent_tests unit tests.
Skip-run_test: true
Test-tag: unittest,tiny,full_regression
> DAOS-1763 Test:Fixed unit test bin location and updated Avocado tags.

- src/vos/README.md
> DAOS-3113 vos: Update README for conditional update

- Jenkinsfile
Convert to only using snapshot restores for hardware tests.
> CORCI-852 build: Convert to Snapshot restores (#2008)

- doc/admin/troubleshooting.md
> Added the daos_agent log to the troubleshooting sections

- doc/admin/deployment.md
> Update admin guide-deployment - Agent Startup

- src/tests/suite/daos_epoch_io.c
Fix SDL/Coverity reported warning in epoch_io test.
Signed-off-by: Liu Xuezhao <xuezhao.liu@intel.com>
> DAOS-4251 test: fix SDL warning in epoch_io test (#2054)

- src/vos/README.md
Update src/vos/README.md to add the MVCC rules.
> DAOS-3113 vos: Update README for MVCC rules

- Jenkinsfile
> CORCI-843 buid: Skip build and test for doc-only

- Jenkinsfile
> Revert "CORCI-843 buid: Skip build and test for doc-only"

- src/container/srv_container.c
- src/container/srv_epoch.c
- src/container/srv_internal.h
- src/container/srv_target.c
Cherry-pick fix of DAOS-4223 and the dependent fix of DAOS-4128.
> DAOS-4223 snapshot: Propagate snap IV after commit

- src/object/srv_csum.c
Only non-hole biov possibly with csum, original code possible with
invalid memory access.
> DAOS-2448 obj: fix a bug in ds_csum_add2iod

- src/client/dfs/dfs.c
currently we don't check that we are using the correct version for the
DFS SB and layout on dfs_mount(). add checks to fail if a wrong version
is encountered.
> DAOS-4266 DFS: dfs_mount() should verify correct SB and Layout version (#2063)

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/system.go
- src/control/common/collection_utils.go
- src/control/common/collection_utils_test.go
- src/control/server/ctl_harness.go
- src/control/server/ctl_system.go
- src/control/server/harness.go
- src/control/server/instance.go
- src/control/server/ioserver/exec.go
- src/control/server/ioserver/mocks.go
- src/control/server/mgmt_svc.go
Address remaining review comments from PR 2021
- improve check for non-temporary dial errors
- make number list parsing more generic
> DAOS-4224 control: fixups from pr 2021

- doc/admin/deployment.md
> DAOS-4193 doc: add warning that vfio doesn't yet work

- src/vos/tests/vts_ilog.c
In my previous patch to fix log versioning bug, I added tests to
check the versioning but didn't add tests for aggregation.
Also, this fixes the aggregation and discard tests to ensure
everything is added to the log so we actually test aggregation.
> DAOS-623 vos: Log version checks in ilog_aggregate/discard tests

- doc/admin/deployment.md
> Update admin guide-deployment - Agent Startup (#1987)

- doc/admin/installation.md
Add text about scons COMPILER option
> Update Admin guide-installation-building daos (#1992)

- doc/admin/troubleshooting.md
> Added the daos_agent log to the troubleshooting sections (#2030)

- Jenkinsfile
This reverts commit f02186f13ca5d3ee4589355670117ca55a7b53a0.
This reverts commit 58d8beeb3573213e539345e5c879be03d4b55e9e.
> Revert "CORCI-843 buid: Skip build and test for doc-only (#2117)"

- src/control/README.md
- src/control/server/README.md
README updated for control & control/server directories including
developer relevant details such as package and code structure.
> DAOS-2599 control: update control server design/internals doc

- Jenkinsfile
Also add a bit of debug to find out what those values are on landing.
> Tests for CHANGE_TARGET

- src/include/daos/mgmt.h
- src/include/daos_srv/daos_server.h
- src/iosrv/profile.c
- src/mgmt/cli_mgmt.c
- src/mgmt/rpc.h
- src/mgmt/srv.c
- src/mgmt/srv_target.c
- src/object/obj_internal.h
- src/object/srv_mod.c
- src/utils/dmg.c
Add aggregate/average option to profile.
> DAOS-4365 profile: Add aggregate option to profile

- src/cart/_structures_from_macros_.h
skip-build: true
skip-test: true
> DAOS-2666 cart: add src/cart/_structures_from_macros_.h

- src/tests/ftest/io/mdtest_small.py
> Revert "Move mdtest_small to weekly run for master"

- src/iosrv/sched.c
- utils/build.config
> DAOS-4450 abt: upgrade to v1.0

- src/SConscript
- src/client/pydaos/__init__.py
- src/tests/ftest/pool/multiple_creates_test.py
- src/tests/ftest/util/daos_perf_utils.py
- src/tests/ftest/util/fio_test_base.py
- src/tests/ftest/util/ior_test_base.py
- src/tests/ftest/util/mdtest_test_base.py
- utils/daos_build.py
- utils/sl/check_script.py
Fix, and introduce a python error in mdtest to see what gets reported.
> CORCI-896 test: Change check_script to work on older python versions.

- src/control/logging/debug.go
- src/control/logging/logging_test.go
Use the runtime package to inspect the call stack and adjust
for any Debug() or Debugf() wrappers. Ensures that the correct
caller info is logged.
> DAOS-2881 control: Print correct caller info in logging.Debugf()

- src/bio/smd/smd_store.c
- src/mgmt/srv_target.c
- src/vos/vos_pool.c
Change the created file/directory to 0600/0700,
so only the owner can read/write these
files/directories.
> DAOS-863 mgmt: Fix the file permission

- src/vos/evtree.c
In current implementation, sometimes we may inogre some simple PMDK
TX oepration result. It is dangerous under some special cases, such
as the server is out of memory or space. Under such cases, the PMDK
TX operation may fail and related PMDK TX will be aborted silently.
If we do not check the return value and continuously use such PMDK
TX handle for subsequent PMDK TX operation, then it will cause PMDK
assertion.
> DAOS-4406 vos: check PMDK TX operation result

- src/rebuild/srv.c
> DAOS-2666 build: fix clang build error

- src/container/srv_target.c
- src/include/daos_srv/container.h
- src/object/srv_obj_migrate.c
- src/tests/suite/daos_rebuild.c
Some fixes about reintegrate server
1. open/create the container if it does not
exist.
2. Only reintegrate offline pool.
> DAOS-2833 reintegrate: reintegrate the server

- src/tests/suite/SConscript
It causes some issues with python3
> DAOS-623 build: Fix issues with cmocka workaround #419

- doc/man/man8/daos.8
- src/utils/daos.c
Changes daos command online help to become
per-resource/command for better clarity.
Also document this in daos command man page.
Change-Id: Ie2458f32fcaeb6b3f3af89391b1116d859fe64db
> DAOS-3219 utils: daos cmd per-resource/command help

- src/include/daos_api.h
- src/include/daos_array.h
- src/include/daos_cont.h
- src/include/daos_event.h
- src/include/daos_fs.h
- src/include/daos_kv.h
- src/include/daos_mgmt.h
- src/include/daos_security.h
- src/include/daos_task.h
- src/include/daos_types.h
- src/include/daos_uns.h
fix some issues reported by doxygen; error return values, etc.
Co-authored-by: cdurf1 <craig.durfey@intel.com>
Conflicts:
src/include/daos_task.h
> DAOS-4235 docs: fix API documentation in headers (#2296)

- Jenkinsfile
- utils/docker/Dockerfile.code_scanning
Add Bandit python code scans to the project.
Skip-run_test: true
Skip-scan-centos-rpms: true
> CORCI-751 sdl: Add Bandit python code scan (#2326)

- doc/admin/deployment.md
This reverts commit 9d322133d28ee9862772a09ecaa4914bb1a8a452.
> Revert "DAOS-4193 doc: add warning that vfio doesn't yet work (#2128)"

- Jenkinsfile
- utils/rpms/daos.spec
> DAOS-623 build: Clean up SPDK dependencies

- src/common/checksum.c
- src/container/srv_csum_recalc.c
- src/include/daos/common.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/srv_csum.c
- src/object/srv_obj.c
- Additional tracing
- Error messages include more detailed info about what/where is
corrupted.
> DAOS-4397 csum: Log Message Improvements for Checksums

- src/client/api/SConscript
- src/client/dfs/SConscript
- src/include/daos_api.h
- src/include/daos_array.h
- src/include/daos_cont.h
- src/include/daos_event.h
- src/include/daos_fs.h
- src/include/daos_kv.h
- src/include/daos_obj.h
- src/include/daos_obj_class.h
- src/include/daos_pool.h
- src/include/daos_prop.h
- src/include/daos_security.h
- src/include/daos_task.h
- src/include/daos_types.h
- src/include/daos_uns.h
Reverts daos-stack/daos#2250
Actually too complex to implement in our build system.
Let's take a different approach at link time. PR to come.
> Revert "DAOS-4431 client: hide internal symbols"

- src/control/lib/spdk/src/nvme_control.c
- src/iosrv/sched.c
- src/mgmt/srv_pool.c
- src/placement/tests/benchmark_util.h
- src/placement/tests/pl_bench.c
- src/placement/tests/place_obj_common.c
- src/pool/srv_pool.c
- src/security/srv_acl.c
- src/tests/obj_ctl.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_test_common.c
Fixed several problems found by coverity static analysis.
Signed-off-by: Byron Marohn <byron.marohn@intel.com>
Co-authored-by: Peter Fetros <peter.fetros@intel.com>
> DAOS-3328 SDL : Fix several problems found by coverity (#1837)

- .gitignore
- .travis.yml
- Jenkinsfile
- utils/build.config
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.leap.15
- utils/rpms/Makefile
- utils/rpms/daos.spec
Set it to master rather than just a commit hash as evey CaRT commit on
master now should be for DAOS 1.0.
> DAOS-623 build: Update to CaRT master

- .travis.yml
> Revert "DAOS-4352 build: Force EL7 build to use fuse3 RPM"

- src/cart/src/gurt/dlog.c
dlog could print the same message to stderr for millions
of times if the log file is full.
With this patch, dlog stores the previous error so it can
find the same error and avoid to output message flood
> DAOS-4514 debug: do not print the same error

- src/common/fail_loc.c
- src/include/daos/common.h
- src/iosrv/srv.c
- utils/build.config
Some fixes for fail inject yml.
Add RPC lost req fail injection.
> DAOS-4418 fail: some fixes for fail inject yml

- doc/user/hpc.md
> DAOS-2666 doc: Update MPICH ROMIO driver usage docs

- src/vos/tests/vts_gc.c
Fixing last Missed Coverity Issue
> DAOS-4116 SDL: Fixing last Missed Coverity Issue (#2534 )

- Jenkinsfile
Again, due to our multiple DAOS versions in the repo providing the same
ABI, and Yum's poor dependency selection algorithms, we need to coerce
the matching daos-client to be installed with the server.
Skip-run_test: true
Skip-scan-centos-rpms: true
> DAOS-4569 test: Install client with server

- src/tests/daos_perf.c
> DAOS-4367 tests: add ULT support to daos_perf

- doc/admin/performance_tuning.md
> DAOS-2594 docs: Update to performance tuning section

- doc/admin/env_variables.md
- utils/build.config
- utils/rpms/daos.spec
- Update daos version to 0.9.3
- Pick cart v4.7.0 tag
> CART-89 daos: Update daos to v4.7.0 of cart

- src/pool/srv_pool.c
Pool service leader uses pool map buffer stored in AEP for RDMA
while propagating to other servers or transferring back to client.
This patch changes this and copies pool map buffer from AEP to
DRAM before RDMA because some providers cannot support RDMA
from/to AEP
> DAOS-4407 pool: copy pool map buffer before RDMA

- src/proto/Makefile
- src/proto/README.md
> DAOS-4759 doc: fix broken protobuf compiler links

- src/tests/daos_perf.c
Reverts daos-stack/daos#2497
The duration and performance results calculation are wrong,
output is not making sense now.
> Revert "DAOS-4367 tests: add ULT support to daos_perf"

- src/common/pool_map.c
- src/vos/ilog.c
- src/vos/vos_dtx.c
- src/vos/vos_io.c
- ilog: change the debug level from IO to TRACE
- dtx: change the debug level from IO to TRACE
- poo_map: change the debug level from MGMT to TRACE
> DAOS-4233 debug: reduce debug logs

- doc/admin/env_variables.md
- doc/mkdocs.yml
- doc/user/interface.md
Add link to doxygen API.
Change fonts to Ubuntu.
Fix nit in table presentation.
> DAOS-4240 doc: add link to API & change fonts

- src/include/daos_srv/daos_server.h
- src/include/daos_srv/rebuild.h
- src/iosrv/server_iv.c
- src/object/obj_internal.h
- src/object/srv_obj_migrate.c
- src/pool/srv_target.c
- src/rebuild/rebuild_internal.h
- src/rebuild/srv.c
- src/tests/suite/daos_test_common.c
Abort migrate and rebuild before destory the pool.
> DAOS-1 DAOS-4740 rebuild: abort migrate and rebuild

- utils/rpms/daos.spec
> DAOS-4747 build: Fix fuse3-libs -> libfuse3

- utils/rpms/daos.spec
To daos-devel's Requires as they seem to have gotten dropped when cart
was merged in.
> DAOS-623 packaging: Add cart-devel's Requires:

- utils/docker/Dockerfile.centos.7
Install the python codespell package so the recent change
to code-review can report on spelling mistakes in PRs.
> CORCI-27 test: Install the codespell package to enable CI checks.

- utils/build.config
- Update to latest ofi + sockets provider patch
> DAOS-4394 ofi: Update to latest ofi

- src/common/pool_map.c
- src/vos/ilog.c
- src/vos/vos_dtx.c
- src/vos/vos_io.c
- ilog: change the debug level from IO to TRACE
- dtx: change the debug level from IO to TRACE
- pool_map: change the debug level from MGMT to TRACE
> DAOS-4233 debug: reduce debug logs (#2671)

- src/control/server/harness_test.go
> DAOS-4980 control: fix harness start intermittent failure

- Jenkinsfile
- utils/rpms/daos.spec
> DAOS-623 build: Pragma to enable parallel build

- doc/admin/administration.md
- doc/admin/deployment.md
> DAOS-4535 doc: update system administration commands

- utils/check/README.md
- utils/check/download_rpms.sh
- utils/check/handle_rpms.sh
Add hardening-check to the scripts to check for CVEs.
Doc-only: true
> DAOS-3389 test: Add hardening-check

- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFileIT.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFileMultiThreadsIT.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFilePathTest.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFsClientIT.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosFsClientTestBase.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosIOExceptionTest.java
- src/client/java/daos-java-api/src/test/java/com/intel/daos/client/DaosUtilsTest.java
- src/client/java/hadoop-daos/src/main/java/com/intel/daos/hadoop/fs/DaosConfig.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosConfigTest.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosFSFactory.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosFileSystemContractIT.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosFileSystemIT.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosFileSystemTest.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosInputStreamIT.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosInputStreamTest.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosOutputStreamIT.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosOutputStreamTest.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/DaosUtils.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/multiple/MultipleDaosOpenFileIT.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/multiple/TestMultipleDaosCreateFile.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/multiple/TestMultipleDaosMkdir.java
- src/client/java/hadoop-daos/src/test/java/com/intel/daos/hadoop/fs/multiple/TestMultipleDaosMount.java
License copied from master PR #2872
> DAOS-5018 license: Add Apache license to Hadoop files

- src/utils/daos_hdlr.c
Make daos command pool/cont get-prop output more meaningful.
Change-Id: I3c7b194078ef76bbadcd31cd374981cc91932c30
> DAOS-5107 utils: beautify daos pool/cont get-prop output

- doc/admin/predeployment_check.md
Should be rp_filter instead of rp_local
> DAOS-4240 doc: fix nit in multi-rail section

- src/README.md
- src/cart/src/gurt/fault_inject.c
- src/object/README.md
These were caught by Ken during a previous review, but missed by
codespell.
> CORCI-27 spelling: Correct three more spelling mistakes.

- src/client/api/object.c
- src/include/daos/object.h
- src/include/daos/task.h
- src/include/daos_srv/vos.h
- src/include/daos_task.h
- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_ec.h
- src/object/obj_internal.h
- src/object/obj_rpc.c
- src/object/obj_rpc.h
- src/object/obj_task.c
- src/object/srv_obj.c
- src/vos/vos_io.c
Adds the support of recover the missed data on shadow epochs.
> DAOS-2448 obj: EC degraded fetch with data recovering

- src/tests/ftest/util/dmg_utils.py
Add storage query functionality into dmg_utils.py
Signed-off-by: Justiniano-pagn <amanda.justiniano-pagn@intel.com>
> DAOS-5166 test: Integrate storage_query functions into dmg_utils.py

- utils/docker/Dockerfile.ubuntu.20.04
Remove a line added while debugging Ubuntu travis build locally
Skip-test: True
> DAOS-623 build: Remove debugging from #2590

- src/utils/daos_hdlr.c
Change-Id: Ia99ffb12f12cad291d74c4333ca4e6f7c110f3e8
> DAOS-5107 utils: handle sha[1,256,512] cksums in daos tool

- src/iosrv/sched.c
The d_list_empty() assert in sched_req_wakeup() is not correct, since
when the request isn't in sleep, it could be queued in 'spi' to be
scheduled.
This patch also removed the code of "don't sleep on space pressure"
in sched_req_sleep(), because it's totally up to caller to decide
if the ULT needs be put into sleep, scheduler doesn't have enough
knowledge to make this decision.
> DAOS-5205 sched: remove improper assert

- src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSystem.java
1. modify uri and workingDir on uns model
2. modify resolvePath method , when path.startsWith(unsPrefix), path add scheme and authority
> resolve the problem  that path has not scheme and authority

- src/object/srv_obj.c
The API changed while new usages were added.
> DAOS-4818 dtx: Fix merge conflict between #2862 and #2000

- src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSystem.java
1. modify resolvePath method , when path.startsWith(unsPrefix), path add scheme and authority
> path add scheme and authority

- doc/release/releaseNote_v1_0.md
> DAOS-5159 doc: a few fixes to the Release Notes

- src/client/java/pom.xml
Update to version 2.13.3 or greater due to github security alert
> DAOS-623 java: Update log4j-core version due to security alert

- src/tests/ftest/launch.py
> CORCI-898 test: Fix bug in stack trace generation

- src/object/cli_shard.c
- src/object/srv_obj.c
Add a few useful IO LOG, so it can generate in CI log.
> DAOS-5152 object: add a few useful IO DEBUG log.

- utils/rpms/daos.spec
Fix typo on the date of the latest change added
to the changelog.
Signed-off-by: Martinez Montes, Jonathan <jonathan.martinez.montes@intel.com>
> DAOS-5278 Fix typo on daos.spec date

- src/bio/bio_xstream.c
xs_poll_completion() doesn't have to drain all events.
> DAOS-5208 bio: doesn't have to drain all events

- src/control/cmd/daos_agent/README.md
Added information about the GetAttachInfo cache
to the Get Attach Info section.
> DAOS-4593 doc: Update agent design documentation

- src/tests/suite/daos_obj.c
- src/tests/suite/daos_test.c
- src/tests/suite/daos_test.h
- src/tests/suite/daos_test_common.c
Add object class options for iotest for EC object.
> DAOS-5293 test: add object class option

- src/tests/suite/SConscript
Change-Id: I7f81b864a06d1bff9b00f348f88f64805c36523b
> DAOS-5304 build: beautify cmocka version config msgs

- Jenkinsfile
- ci/coverity_success.sh
- ci/coverity_unsuccessful.sh
- ci/doc_only_change.sh
- ci/unit/test_post_always.sh
* Refactoring the test stages to use one step from pipeline-lib for the
test steps and one step from pipeline-lib for each post action.
> CORCI-918 build: Refactor test stages

- src/rebuild/srv.c
Since we can not skip the target rebuild, let's reschedule
the rebuild for any failure.
And also it should not schedule any rebuild for the "NEW"
failure targets, let's always rely on SWIM to detect failure
targets.
> DAOS-5315 rebuild: reschdule rebuild for failures

- src/bio/bio_buffer.c
- src/cart/src/cart/crt_iv.c
- src/pool/srv_iv.c
- src/tests/ftest/launch.py
Move some frequent log messages to trace
> DAOS-5338 log: Reduce some debug logs

- src/tests/ftest/server/metadata.yaml
- src/tests/ftest/util/server_utils_params.py
> DAOS-5338 test: Turn down default debug levels on servers.

- src/tests/ftest/container/list_containers.py
- src/tests/ftest/pool/connect_test.py
- src/tests/ftest/pool/list_pools.py
- src/tests/ftest/pool/multi_server_create_delete_test.py
- src/tests/ftest/pool/query_attribute.py
- src/tests/ftest/pool/storage_ratio.py
- src/tests/ftest/pool/storage_ratio.yaml
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/command_utils_base.py
- src/tests/ftest/util/daos_utils.py
- src/tests/ftest/util/daos_utils_base.py
- src/tests/ftest/util/dmg_utils.py
- src/tests/ftest/util/dmg_utils_base.py
- src/tests/ftest/util/pool_security_test_base.py
- src/tests/ftest/util/test_utils_pool.py
Start migrating DmgCommand/DaosCommand helper methods to internally
process the output of the command and apply the regular expressions
in those methods in order to return a more user-friendly dictionary
of data.
Provide the base class changes to enable this functionality and
update DmgCommand.pool_create() as an example.
> DAOS-5339 tests: Enhance gathering dmg command output

- utils/rpms/daos.spec
> DAOS-4747 build: Include correct SLES fuse library

- Jenkinsfile
- ci/parse_ci_envs.sh
- ci/provisioning/log_cleanup.sh
- ci/provisioning/log_cleanup_nodes.sh
- ci/provisioning/post_provision_config.sh
- ci/provisioning/post_provision_config_nodes.sh
- ci/provisioning/post_provision_config_nodes_EL_7.sh
- ci/provisioning/post_provision_config_nodes_LEAP_15.sh
- ci/rpm/build_success.sh
- ci/rpm/build_unsuccessful.sh
- ci/rpm/test_daos_node.sh
- ci/unit/test_post_always_node.sh
- ftest.sh
- src/control/server/init/setup_spdk.sh
- src/object/obj_internal.h
- src/object/srv_obj.c
- src/tests/ftest/launch.py
- src/tests/ftest/util/mpio_utils.py
- utils/daos_build.py
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.ubuntu.20.04
- utils/rpms/Makefile
- utils/rpms/daos.spec
- utils/rpms/packaging/Dockerfile.mockbuild
- utils/rpms/packaging/Makefile_packaging.mk
- utils/sl/env_modules.py
Build and test on Leap 15.2 in CI.
> DAOS-4480 test: Test in CI with Leap 15

- .travis.yml
- src/client/api/kv.c
> test conditional java build

- src/tests/ftest/container/container_check.yaml
- src/tests/ftest/control/daos_agent_config.yaml
- src/tests/ftest/control/daos_control_config.yaml
- src/tests/ftest/io/dfuse_bash_cmd.yaml
- src/tests/ftest/io/ior_small.yaml
- src/tests/ftest/io/parallel_io.yaml
- src/tests/ftest/nvme/nvme_fragmentation.yaml
- src/tests/ftest/nvme/nvme_object.yaml
- src/tests/ftest/nvme/nvme_pool_capacity.yaml
- src/tests/ftest/osa/osa_offline_reintegration.yaml
- src/tests/ftest/osa/osa_online_reintegration.yaml
- src/tests/ftest/pool/storage_ratio.yaml
- src/tests/ftest/server/daos_server_config.yaml
> DAOS-5324 Test: Remove deprecated srv_timeout from yaml file.

- src/object/cli_obj.c
Clean up object req valid and remvoe some
unnecessary code.
> DAOS-4257 object: cleanup object req valid

- src/vos/vos_space.c
vos_space_hold() should allow a SCM only update even when the
NVMe space is full.
> DAOS-5378 vos: Don't reject SCM update when NVMe is full

- src/vos/tests/vts_mvcc.c
Add "same TX" and "diff TX" cases to MVCC test conflicting_rw. These are
excluded by a "FIXME" temporarily, due to the missing implementation
from vos. Also, implement fetch_f.
> DAOS-5195 vos: Add TX ID cases to MVCC tests

- src/client/pydaos/raw/daos_api.py
- src/include/daos/object.h
- src/include/daos_obj_class.h
- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_class.c
- src/object/obj_ec.h
- src/object/obj_internal.h
- src/object/srv_obj.c
- src/tests/suite/daos_epoch_io.c
- src/tests/suite/io_conf/daos_io_conf_4
- src/tests/suite/io_conf/daos_io_conf_5
Add some special handling for EC single-value's degraded fetch.
> DAOS-4899 obj: add support for EC singv degraded fetch

- src/object/cli_obj.c
> DAOS-4899 obj: fix TSE_TASK_ARG_LEN assertion

- src/object/cli_obj.c
The D_ASSERT(shard < obj->cob_shards_nr) possibly be triggered when
pool map refreshed.
> DAOS-5379 obj: fix assertion in obj_shard2tgtid

- src/object/obj_tx.c
Some DAOS logic, such as rebuild scan and data consistency
verification, uses DAOS local read-only TX to read (fetch/
list) data against specified epoch. For such kind of usage,
it is NOT necessary to restart the TX if found the client's
pool map is stale, instead, the sponsor can retry the read
operation after refreshing the pool map.
> DAOS-5382 dtx: not restart local read-only TX

- src/tests/ftest/osa/osa_offline_drain.py
- src/tests/ftest/osa/osa_offline_reintegration.py
- src/tests/ftest/osa/osa_online_drain.py
- src/tests/ftest/osa/osa_online_reintegration.py
Summary:
- Fix target index range from 1-8 to 0-7.
- DMG command presently passes with invalid range. This will be addressed
by a separate PR.
> DAOS-5416 test: AssertionError: Pool Version Error

- src/object/cli_obj.c
- src/object/obj_internal.h
Conflict between #3166 and #3108 
> DAOS-623 build: Fix build error caused by two independent commits

- src/cart/test/util/cart_logparse.py
- src/cart/test/util/cart_logtest.py
Print a report to stdout of how common various log lines and
facilities are used.
> CART-822 test: Add tracking of log line/mask/level frequency.

- src/container/cli.c
> DAOS-5408 cont: fix incorrect return value

- src/rebuild/scan.c
- src/tests/suite/daos_rebuild_common.c
set more debug info for rebuild test
> DAOS-5446 tests: set more debug for rebuild test

- src/cart/src/cart/crt_hg_proc.c
- During free operation do not perform hg_proc_save_ptr
> DAOS-5452 proc: Do not perform hg_proc_save_ptr on free operation

- src/dtx/dtx_common.c
Change log to error for debugging DAOS-5493
> DAOS-5493 dtx: Add logging for DER_EP_OLD

- src/placement/pl_map_common.c
Grp_map is allocated by object layout number, but setbit
by target number, which might overwrite the grp_map.
let's Using array, instead of bitmap, for grp_map tracking,
because bitmap + target id might need allocate bitmaps
for all targets in pool map.
> DAOS-5528 placement: use array for grp_map tracking

- src/include/daos_srv/pool.h
- src/pool/rpc.h
- src/pool/srv_internal.h
- src/pool/srv_iv.c
- src/pool/srv_pool.c
- src/pool/srv_target.c
Fetch pool handle from IV, instead of distributing
handle actively.
> DAOS-5449 pool: fetch pool handle by IV

- src/vos/tests/vts_pm.c
- src/vos/vos_ilog.c
- src/vos/vos_ts.c
- src/vos/vos_ts.h
> Fix issue with vos for DAOS-5530

- src/tests/ftest/nvme/nvme_fault.py
- src/tests/ftest/nvme/nvme_fault.yaml
- src/tests/ftest/util/ior_utils.py
Test-tag-hw-medium: nvme_fault
> DAOS-5497 Test: dfs container needs --oclass for folder level replica.

- src/pool/srv_iv.c
If pool iv entry is enough for holding the incoming
pool handles, let's reallocate for refresh & update
callback.
> DAOS-5552 pool: re-allocate iv entry for -REC2BIG

- src/tests/ftest/nvme/nvme_io_verification.yaml
> DAOS-5516 test: add -o /testfile  to nvme_io_verification test

- doc/admin/installation.md
Installation.md is updated to include new RPM installation instructions
> DAOS-5422 documentation: Update Installation instructions for RPMs

- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/obj_ec.h
- src/object/obj_internal.h
- src/object/srv_obj_migrate.c
- src/tests/ftest/daos_test/daos_core_test.yaml
- src/tests/suite/daos_obj.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_ec.c
- src/tests/suite/daos_rebuild_simple.c
- src/tests/suite/daos_test.c
- src/tests/suite/daos_test.h
1. Add ec rebuild test.
2. Some fixes of EC rebuild.
> DAOS-3018 tests: add ec rebuild test

- src/tests/ftest/util/job_manager_utils.py
> DAOS-5580 tests: Fix mca param default value

- doc/overview/fault.md
- doc/overview/storage.md
- doc/overview/transaction.md
- doc/overview/use_cases.md
- src/README.md
Several markdown files had long paragraphs as a single
line, making this very hard to edit and diff.
Broke them down to <80 char/line. No other changes.
> DAOS-5579 doc: adding line breaks to doc/overview/*.md, src/README.md

- doc/overview/security.md
Typographical and clarification edits to the
Security Overview document.
> DAOS-5579 doc: reviewed doc/overview/security.md

- Jenkinsfile
- ci/unit/test_main_node.sh
Disable NLT for coverage testing
Fixed coverage build to always run with quick build
> DAOS-5608 test: Disable NLT for coverage testing

- src/tests/simple_array.c
To avoid Error in realloc(): invalid old size
> DAOS-5431 test: Allocate rank_list dynamically

- doc/user/container.md
- doc/user/hpc.md
- doc/user/interface.md
- doc/user/posix.md
- doc/user/spark.md
Doc fixes (contents and and formatting) in the User Guide.
> DAOS-5579 doc: User Guide doc review

- utils/build.config
- utils/rpms/daos.spec
- Update libfabric to tag v1.11.0
> CART-89 ofi: Update ofi to v1.11.0

- utils/build.config
- utils/rpms/daos.spec
> Revert "CART-89 ofi: Update ofi to v1.11.0"

- src/include/daos_srv/daos_server.h
- src/include/daos_srv/vos_types.h
- src/object/cli_ec.c
- src/object/obj_enum.c
- src/object/obj_internal.h
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
- src/tests/suite/daos_rebuild_ec.c
- src/vos/vos_obj.c
1. some fixes about single EC value rebuild.
2. Add single value rebuild tests.
> DAOS-3018 rebuild: add single value rebuild

- src/common/pool_map.c
- src/mgmt/srv_pool.c
- src/pool/srv_pool.c
Fix a few memory leak for pool map extend
> DAOS-5625 pool: a few memory leak for pool map extend

- src/object/cli_shard.c
Since the object layout(shards) might be refreshed
during the I/O, so let's remove shards from the argument
of dc_rw_cb for the moment.
> DAOS-5646 object: remove the shard from the dc_rw_cb

- doc/admin/administration.md
- doc/admin/deployment.md
- src/control/server/instance_drpc.go
Update instructions for dmg storage scan and dmg system cmds.
> DAOS-5535 doc: admin guide updates for dmg cmds

- utils/githooks/README.md
- utils/githooks/pre-commit
> DAOS-623 utils: Add a pre-commit hook example for copyright update

- src/tests/daos_perf.c
Fix an assertion in daos_perf vos mode testing.
> DAOS-4898 test: fix an assertion in daos_perf

- src/tests/ftest/aggregation/aggregation_basic.py
- src/tests/ftest/daos_test/daos_core_test-rebuild.py
- src/tests/ftest/daos_test/daos_core_test.py
- src/tests/ftest/io/daos_vol.py
- src/tests/ftest/io/io_consistency.py
- src/tests/ftest/io/ior_small.py
- src/tests/ftest/io/macsio_test.py
- src/tests/ftest/io/mdtest_small.py
- src/tests/ftest/nvme/nvme_object.py
- src/tests/ftest/osa/osa_online_drain.py
- src/tests/ftest/osa/osa_online_reintegration.py
- src/tests/ftest/pool/evict_test.py
- src/tests/ftest/pool/pool_svc.py
- src/tests/ftest/server/daos_server_restart.py
Adding tag "DAOS-5610" to tests affected by the issue
in this jira ticket to create a group of tests which can
be tirggered easily in CI
> DAOS-5610 test: Adding tag "DAOS-5610" to some tests

- src/dtx/dtx_common.c
To avoid accessing invalid area.
> DAOS-5676 dtx: DTX handle verification before further use

- src/container/cli.c
- src/container/cli_internal.h
- src/container/srv_cli.c
Free the container correctly in dsc_cont_open().
> DAOS-5658 container: free container correctly

- src/pool/srv_iv.c
Refine a few details of valid checking pool_iv_conn.
> DAOS-5654 IV: refine pool_iv_conn pic_size handling

- CONTRIBUTING.md
- README.md
- doc/admin/deployment.md
- doc/admin/hardware.md
- doc/admin/installation.md
- doc/admin/performance_tuning.md
- doc/debugging.md
- doc/index.md
- doc/mkdocs.yml
- doc/overview/architecture.md
- src/README.md
- src/client/dfs/README.md
Minore doc edits (formatting, typos, broken links).
Added CONTRIBUTING.md.
new file:   CONTRIBUTING.md
modified:   README.md
modified:   doc/admin/deployment.md
modified:   doc/admin/hardware.md
modified:   doc/admin/installation.md
modified:   doc/admin/performance_tuning.md
modified:   doc/debugging.md
modified:   doc/index.md
modified:   doc/mkdocs.yml
modified:   doc/overview/architecture.md
modified:   src/README.md
modified:   src/client/dfs/README.md
> DAOS-5579 doc: minor doc edits

- src/pool/srv_iv.c
Fix iv_pool_map size in pool_iv_ent_update, and
also fix pool put in pool_iv_ent_update.
> DAOS-5625 pool: fix iv_pool_map size

- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_internal.h
- src/object/srv_obj_migrate.c
- src/placement/pl_map_common.c
- src/rebuild/scan.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_ec.c
- src/tests/suite/daos_rebuild_simple.c
- src/tests/suite/daos_test.h
Some fixes for 2 parities EC object enumeration.
> DAOS-4652 ec: Some fixes for 2 parities

- utils/rpms/daos.spec
- utils/sl/components/__init__.py
- Compile OFI with --disable-efa to disable EFA provider
> CART-89 efa: Disable EFA provider

- ci/provisioning/post_provision_config_nodes_EL_7.sh
- ci/provisioning/post_provision_config_nodes_LEAP_15.sh
Fully to the latest O/S updates available.
> DAOS-5763 test: Ensure test nodes are updated

- src/object/cli_obj.c
- src/rebuild/rpc.h
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_test_common.c
Remove a few unnecessary sleep in the test after we shrink
SWIM_SUSPECT time.
> DAOS-5717 test: remove a few unnecessary sleep in the test

- src/tests/ftest/io/ior_hdf5.py
> DAOS-5736: Update ior_hdf5 test with correct hw tag.

- SConstruct
- utils/sl/components/__init__.py
> DAOS-623 build: Add lz4 dependence to scons checks

- src/tests/SConscript
- src/tests/simple_obj.c
> DAOS-5803 example: add simple example for different object APIs

- src/rebuild/scan.c
- src/rebuild/srv.c
Update rebuild status during failure, so it can notify
the leader.
> DAOS-5807 rebuild: update rebuild status during failure

- src/object/obj_tx.c
The obj_iod_array::oia_iods need to be released when cleanup the
DTX handle on client. For EC object update, recover the original
iod array after reassemble when cleanup related DTX handle.
> DAOS-5553 object: memory leak when cleanup DTX handle on client

- src/control/drpc/property.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
- src/mgmt/srv_drpc.c
Adds support for more pool properties. Support for the label
property will come later.
Also cleans up some debug logging in the gRPC pool handlers.
> DAOS-5456 control: Add support for space_rb/self_heal props

- src/object/cli_obj.c
Check failure for obj_grp_leader_get().
> DAOS-5885 object: check failure for obj_grp_leader_get

- src/control/cmd/daos_admin/README.md
Create some developer-focused documentation for daos_admin
and explain the privileged helper concept.
> DAOS-2881 control: Add README for daos_admin

- utils/build.config
> DAOS-5940 build: Specify isa-l_crypto version

- src/common/SConscript
- src/common/compression.c
- src/common/compression_isal.c
- src/common/compression_qat.c
- src/common/qat.c
- src/common/tests/compress_tests.c
- src/include/daos/compression.h
- src/include/daos/qat.h
* add qat as backend for deflate algorithm
* qat related code is not built for now until "HAVE_QAT" defined
* qat detection and configuration will be in seperate commit
* synchronous mode only - wait for completion
* asynchronous support will be added in the next commit
Signed-off-by: Weigang Li <weigang.li@intel.com>
> Compression: add qat support for deflate

- src/common/tests/btree_direct.c
- utils/test_memcheck.supp
> DAOS-5995: free key and value buffer in btree direct test code

- src/cart/crt_swim.c
- src/cart/swim/swim.c
Don't report about SWIM shutdown when server is alone.
> DAOS-5991 swim: remove weird error message about SWIM shutdown

- src/vos/vos_obj.c
- utils/test_memcheck.supp
> DAOS-6000: fix memory leak in vos key_punch for akey case

- src/object/obj_tx.c
The TX logic on client needs to properly check fail_loc
"DAOS_DTX_STALE_PM" to simulate the case of client used
stale pool map: skip the initial request (tx_pm_ver = 0)
and block the subsequent retried ones.
> DAOS-6008 dtx: simulate stale pool map via fail_loc

- src/tests/ftest/osa/osa_online_reintegration.yaml
Summary: Update the log_mask for debugging
> DAOS-5807 test: update log_mask

- src/placement/pl_map.c
Skip rebuilding shard for EC object leader selection.
> DAOS-5996 placement: avoid rebuilding shard for EC leader

- src/object/srv_ec_aggregate.c
The conflict is caused when merge the two commits that share
and modify the same function ds_pool_check_dtx_leader()
1. 80341790f9a3ced0316bbc1659cc48c647e7d0c2
DAOS-3911 dtx: distributed transaction recovery (#3837)
2. 77881ad833063d9fecdba82b9a977a8ab59ade53
DAOS-5297 ec: Initial code for EC aggregation (#3774)
> DAOS-5553 object: merge conflict for ds_pool_check_dtx_leader

- src/cart/crt_init.c
- src/cart/crt_self_test.h
- src/cart/crt_self_test_client.c
- src/cart/crt_self_test_service.c
- src/vos/tests/evt_ctl.c
Fix incorrect condition check.
> DAOS-5277 cart: fix for memory leak

- src/tests/ftest/util/test_utils_pool.py
Updating start_rebuild() in test_utils_pool.py
to be able trigger rebuild using dmg sytem stop
and exclude the explicit call to server evict api call
Skip-func-test-leap15: true
> DAOS-6130 test: Update test_utils_pool.py

- ci/provisioning/post_provision_config_nodes_EL_7.sh
- ci/provisioning/post_provision_config_nodes_LEAP_15.sh
> DAOS-623 test: Use DNF on Leap 15

- Jenkinsfile
> CORCI-1020 test: Fix Skip-func-test: true

- src/vos/vos_dtx.c
Signed-off-by: Fan Yong fan.yong@intel.com
> DAOS-6190 vos: fix possible segfault

- src/tests/ftest/datamover/copy_procs.py
- src/tests/ftest/datamover/copy_procs.yaml
> Revert "DAOS-6194 test: Avoid datamover timeout"

- src/tests/daos_perf.c
Client performance also affect overall performance.
After optimizing memory copy in daos_perf client I
was able to improve results as following:
```
update successfully completed:
duration : 21.009056  sec
bandwith : 48.741     MB/sec
rate     : 12477.67   IO/sec
latency  : 80.143     us (nonsense if credits > 1)
```
with new daos_perf client it become:
```
update successfully completed:
duration : 20.136903  sec
bandwith : 50.852     MB/sec
rate     : 13018.09   IO/sec
latency  : 76.816     us (nonsense if credits > 1)
```
> DAOS-5277 perf: speedup daos_perf client

- src/tests/ftest/io/daos_vol.py
- src/tests/ftest/io/daos_vol.yaml
- src/tests/ftest/io/ior_small.yaml
> Revert "DAOS-6076 test:  daos_vol: disabled h5_partest_testphdf5"

- src/control/server/storage/bdev/backend.go
When multiple devices are listed in PCI_WHITELIST to be unbound by SPDK,
the VMD address that is queried by $lspci | grep "Volume Management Device|201d"
loses it prefix of "0000:" which results in DAOS not using the correct
backing transport address for the SSDs behind the VMD address.
Add check for this prefix, and include it when missing.
> DAOS-6160 control: Fix detectVMD() output to add address prefix when missing

- src/object/cli_ec.c
Only check single_tgt after all iods and sgls
are reassemblied, otherwise single_tgt might
be set incorrectly if the last sgl/iod is
within single target.
> DAOS-6149 ec: set orr_single_tgt correctly

- Jenkinsfile
> DAOS-623 misc: Set artifact retention

- Jenkinsfile
> DAOS-623 ci: Set artifact retention

- .travis.yml
Pass -j4 to scons and use one thread per core for Maven.
> DAOS-4093 travis: use parallel build

- doc/admin/troubleshooting.md
- Update documentation for DER_HLC_SYNC
> CART-89 doc: Update doc for DER_HLC_SYNC

- .travis.yml
PR's will still be tested but not the underlying branch
> DAOS-623 build: Limit travis branch builds to master only

- doc/admin/env_variables.md
- doc/admin/installation.md
Fix a few things and properly document how to use -v
in the docker instructions.
> DAOS-4240 doc: update docker intructions and few fixes

- doc/user/container.md
- doc/user/mpi-io.md
- doc/user/spark.md
Add more information on running DAOS with IntelMPI,
and on building MPICH.
> DAOS-5579 doc: update MPI-IO user guide

- src/control/events/pubsub.go
- src/control/events/ras.go
- src/control/lib/control/system_test.go
- src/control/server/mgmt_system.go
- src/control/system/membership.go
- src/control/system/membership_test.go
> DAOS-6063 control: event notification code review updates

- ci/provisioning/post_provision_config_nodes_EL_7.sh
- src/tests/ftest/datamover/copy_procs.py
- src/tests/ftest/launch.py
- src/tests/ftest/pool/multiple_creates_test.py
After 20 minutes and retry up to 3 times before failing fatally.
Fix syntax error in stacktrace collection scriptlet.
Ignore python-magic import error.
weekly_regression is actually called full_regression￼.
> DAOS-623 ci: Timeout yum upgrade

- src/tests/ftest/daos_test/daos_core_test-rebuild.yaml
> Revert "DAOS-6249 tests: enable rebuild 0-10"

- src/tests/ftest/cart/SConscript
- Fix building of fault_status test to properly link to required
libraries.
> DAOS-6371 fault: Fix building of fault_status test

- ci/provisioning/post_provision_config_nodes_EL_7.sh
> DAOS-623 ci: Apply timeout to yum install

- Jenkinsfile
- src/tests/ftest/launch.py
Also deduce Jenkins job retention.
> DAOS-623 ci: Use gdb to get core file creator

- utils/config/examples/daos_server_sockets.yml
Fix port number in daos_server_sockets.yml file
> CART-89 fix: Fix port number in daos_server_sockets example

- README.md
- debian/source/options
> DAOS-4093 ubuntu: ignore .travis.yml file in dpkg-source

- src/tests/ftest/daos_test/daos_core_test-rebuild.yaml
> Revert "DAOS-5851 tests: re-enable rebuild test"

- src/bio/bio_device.c
This functionality is a part of the NVMe Hotplug feature and allows for SSD
identification with the use of VMD LED device management.
Turn the VMD LED back to "OFF" after an evicted device has been reintegrated
back into use via the 'dmg storage replace nvme' command.
> DAOS-6275 vmd: Set OFF state on VMD LED upon faulty device reint

- doc/admin/performance_tuning.md
* Update building commands
* Update relative paths on examples
* Add links to the DAOS documentation
* Add minor changes to the markdown format
Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>
> DAOS-5102 doc: update performance tunning doc

- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/obj_verify.c
- src/rsvc/srv_common.c
> DAOS-5925 logging: Resolve some more DF_KEY issues.

- Jenkinsfile
Skip-unit-test-memcheck: true
Skip-func-test-leap15: true
> DAOS-6046 test: Fix unit test coverage build

- src/vos/vos_dtx.c
For rebuild fetch, if hit non-committed DTX, has to ask the
sponsor to wait and retry, otherwise, the new in-rebuilding
target may miss some data.
> DAOS-6310 vos: retry rebuild fetch for non-committed DTX

- src/tests/ftest/security/cont_create_acl.py
Disabling CreateContainerACLTest test_container_basics
for DAOS-6479
> DAOS-6479 test: Disable CreateContainerACLTest

- Jenkinsfile
> DAOS-623 ci: Reduce build retention to 200 builds

- src/cart/crt_iv.c
These happen on shutdown and are expected, so do not represent
a problem, however logging them leads to inconsistent results
from the NLT job.
> DAOS-5377 ec: Use CDEBUG to silence NOTLEADER warnings.

- src/container/srv_target.c
Destory container eph target in ds_cont_tgt_ec_eph_query_ult()
to avoid race between target container destory and EC eph
container ULT.
> DAOS-6506 container: cont eph ult vs container destory

- src/tests/ftest/datamover/copy_basics.py
Disable datamover copy basics test test_copy_types for DAOS-6484
> DAOS-6484 test: Disable datamover copy basics test

- src/tests/ftest/osa/osa_offline_reintegration.py
Disable osa offline reintegration test for DAOS-6521
> DAOS-6521 test: Disable osa offline reintegration test

- doc/overview/architecture.md
> DAOS-5579 doc: clarify DAOS components in Architecture Overview

- src/include/daos_array.h
- src/include/daos_fs.h
- src/include/daos_kv.h
> DAOS-5023 doc: update API comments in some header files

- src/include/daos_security.h
Fixed some minor wording issues.
Doc-only: true
> DAOS-5030 doc: Update security API comments

- Jenkinsfile
> DAOS-623 ci: Reduce job retention

- src/include/daos_obj.h
> DAOS-5028 doc: update API comments in daos_obj.h

- doc/overview/storage.md
- doc/overview/terminology.md
- doc/overview/transaction.md
> DAOS-5579 doc: minor edits to overview/storage.md

- src/mgmt/srv_system.c
As a workaround for problems reported in DAOS-5919, part of
the old mgmt svc implementation was brought back to
handle asynchronous map broadcast. This commit fixes the
shutdown flow to properly stop the worker and allow the
rank to exit cleanly.
> DAOS-6386 iosrv: Fix shutdown on MS ranks

- src/tests/suite/daos_dist_tx.c
- src/tests/suite/daos_mgmt.c
Disable daostest -m (test 5) and -T (test 37)
> DAOS-6615 test: Disable daostest -m (test 5) and -T (test 37)

- utils/build.config
> DAOS-623 build: Update PMDK to 1.9.2

- src/client/pydaos/raw/daos_api.py
- src/client/pydaos/raw/daos_cref.py
Fix DaosObjShard structure for tests.
> DAOS-5377 tests: fix DaosObjShard

- src/control/cmd/dmg/README.md
Update management tool design documentation (dmg readme).
Doc-only: true
> DAOS-4957 doc: update management tool source readme

- src/tests/suite/daos_aggregate_ec.c
- src/tests/suite/daos_array.c
> DAOS-6334 test: use assert_rc_equal for unit tests

- src/tests/ftest/checksum/csum_error_logging.py
- src/tests/ftest/checksum/csum_error_logging.yaml
Update csum_error_logging.py and csum_error_logging.yaml
to comply with changes in DaosCoreBase
> DAOS-6651 test: Fix csum error logging test setup failure

- src/tests/suite/daos_rebuild_simple.c
Add more reintegration verification in rebuild_simple tests.
> DAOS-6465 tests: add more reintegration tests

- src/placement/jump_map.c
add_layout is not free when exit from the function.
> DAOS-6626 placement: fix memory leak

- src/tests/ftest/osa/osa_offline_drain.py
- src/tests/ftest/osa/osa_offline_extend.py
- src/tests/ftest/osa/osa_offline_parallel_test.py
- src/tests/ftest/osa/osa_offline_reintegration.py
- src/tests/ftest/osa/osa_online_drain.py
- src/tests/ftest/osa/osa_online_drain.yaml
- src/tests/ftest/osa/osa_online_extend.py
- src/tests/ftest/osa/osa_online_extend.yaml
- src/tests/ftest/osa/osa_online_parallel_test.py
- src/tests/ftest/osa/osa_online_parallel_test.yaml
- src/tests/ftest/osa/osa_online_reintegration.py
- src/tests/ftest/osa/osa_online_reintegration.yaml
- src/tests/ftest/util/osa_utils.py
> Revert "DAOS-5871 test: Re-enable all OSA tests"

- src/tests/suite/daos_base_tx.c
- src/tests/suite/daos_capa.c
- src/tests/suite/daos_checksum.c
> DAOS-6334 test: use assert_rc_equal for some daos unit tests

- src/client/dfs/dfs.c
- src/client/dfs/dfs_internal.h
- src/tests/suite/SConscript
- src/tests/suite/dfs_unit_test.c
> DAOS-6486 dfs: add dfs_lookupx to lookup entry + fetch xattrs

- src/client/java/daos-java/src/main/java/io/daos/Constants.java
- src/client/java/daos-java/src/main/java/io/daos/DaosContainer.java
- src/client/java/daos-java/src/main/java/io/daos/DaosPool.java
- src/client/java/daos-java/src/main/java/io/daos/obj/DaosObjClient.java
- src/client/java/daos-java/src/main/java/io/daos/obj/DaosObject.java
- src/client/java/daos-java/src/main/native/daos_jni_common.c
- src/client/java/daos-java/src/main/native/include/daos_jni_common.h
- src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
- src/client/java/daos-java/src/main/native/io_daos_dfs_DaosFsClient.c
- src/client/java/daos-java/src/main/native/io_daos_obj_DaosObjClient.c
- src/client/java/daos-java/src/test/java/io/daos/DaosIOExceptionTest.java
- src/client/java/daos-java/src/test/java/io/daos/DaosTestBase.java
- src/client/java/daos-java/src/test/java/io/daos/dfs/DaosFsClientIT.java
- src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosFSFactory.java
More checks on memory allocation, buffer boundary and string manipulation
Signed-off-by: jiafu zhang jiafu.zhang@intel.com
>  DAOSSDE-14 [DAOS - DAOS 1.2] T189: Minimize the use of unmanaged (native) code

- src/tests/ftest/daos_test/daos_core_test.py
- src/tests/ftest/daos_test/daos_core_test.yaml
Remove stale daos core test -F
> DAOS-6676 test: Remove stale daos core test -F

- doc/user/mpi-io.md
update MPICH 3.4.1 info and add note about --svc API change
> DAOS-5579 doc: update MPICH information

- utils/rpms/daos.spec
> DAOS-6280 build: Update minimum libfabric version

- src/container/srv_container.c
- src/object/cli_obj.c
- src/pool/srv_pool_map.c
Fix/avoid a few coverity defects.
> DAOS-6727 misc: fix Coverity defects

- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.centos.8
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.ubuntu.20.04
add daos_server and daos_agent users to Dockerfile.*,
and use those users/groups to chown the DAOS directories
(keep the existing build user "daos", too)
> DAOS-6304 integration: harmonize user/group setup

- src/rebuild/rebuild_internal.h
- src/rebuild/scan.c
- src/rebuild/srv.c
Missing reclaim object count during reclaim process.
> DAOS-6537 rebuild: missing reclaim object count

- src/tests/ftest/nvme/nvme_pool_capacity.py
> DAOS-6677 Test: Fix Typo for Pylint error.

- src/tests/suite/daos_dist_tx.c
> DAOS-6771 tests: disable dtx_37

- src/bio/SConscript
- src/bio/bio_internal.h
- src/bio/bio_xstream.c
- src/control/SConscript
- src/control/lib/spdk/include/nvme_control.h
- src/control/lib/spdk/nvme.go
- src/control/lib/spdk/spdk.go
- src/control/lib/spdk/src/nvme_control.c
- src/control/server/storage/bdev/backend.go
> Populate PCI allow list in spdk_env_opts union

- src/bio/SConscript
- src/bio/bio_context.c
- src/bio/bio_device.c
- src/bio/bio_internal.h
- src/bio/bio_monitor.c
- src/bio/bio_recovery.c
- src/bio/bio_xstream.c
- src/control/SConscript
- src/control/lib/spdk/SConscript
- src/control/lib/spdk/ctests/SConscript
- src/control/lib/spdk/include/nvme_control.h
- src/control/lib/spdk/nvme.go
- src/control/lib/spdk/spdk.go
- src/control/lib/spdk/src/nvme_control.c
- src/control/server/storage/bdev/backend.go
- utils/sl/components/__init__.py
TODO: rename pci_whitelist of spdk_env_opts in control plane
> BIO & build scripts changes for upgrading to SPDK v21.01

- src/vos/sys_db.c
Modify the sys_db sequence so we first do some access checks
on the file and don't attempt to call vos_pool_open on a
non-existent file.  This removes an error message from
the common initialization path.
> DAOS-6782 vos: Remove spurious error message with sys_db

- src/tests/suite/daos_container.c
- src/tests/suite/daos_dedup.c
- src/tests/suite/daos_degraded.c
- src/tests/suite/daos_dist_tx.c
> DAOS-6334 test: use assert_rc_equal

- src/tests/suite/daos_drain_simple.c
- src/tests/suite/daos_epoch_io.c
- src/tests/suite/daos_epoch_recovery.c
> DAOS-6334 test: use assert_rc_equal for daos unit tests

- src/common/README.md
Some spacing issues fixed. Updates to file names where checksum
algorithm functions reside.
Doc-only: true
> DAOS-2614 csum: Common README Update

- src/tests/suite/daos_obj.c
- src/tests/suite/daos_obj_array.c
- src/tests/suite/daos_oid_alloc.c
- src/tests/suite/daos_test.h
> DAOS-6334 test: use assert_rc_equal for unit test

- src/tests/ftest/mdtest/mdtest_small.py
Disable mdtest small in PR testing
> DAOS-6798 test: Disable mdtest small in PR testing

- src/common/tests/lru.c
- src/vos/tests/vts_pool.c
Couple of coverity related issues in test files for vos and
lru.
Signed-off-by: Vishwanath Venkatesan <vishwanath.venkatesan@intel.com>
> DAOS-6705 tests: Coverity fixes in test files

- src/tests/ftest/io/hdf5.py
- src/tests/ftest/launch.py
Add debuginfo package installtion for hdf5
Test-tag-hw-small: pr,hw,small hdf5
> DAOS-6718 tests: Add debuginfo package installtion for hdf5

- src/include/daos/pool_map.h
- src/placement/jump_map.c
- src/placement/pl_map.h
- src/placement/pl_map_common.c
- src/placement/tests/jump_map_place_obj.c
- src/pool/srv_pool_map.c
Also added some debugging and moved format defines.
> DAOS-6520 test: Removed skips of things fixed by other commits

- src/object/srv_ec_aggregate.c
Or server-side will trigger assertion in ds_obj_ec_agg_handler.
> DAOS-6755 EC: set ca_count for ea_remove_eps/ea_remove_recxs

- src/client/api/tests/eq_tests.c
- src/engine/server_iv.c
- src/tests/suite/daos_test_common.c
Fix coverity defects in eq_tests.c,server_iv.c and
daos_test_common.c
> DAOS-6845 misc: coverity fixes

- src/cart/README.env
- src/cart/crt_init.c
- src/gurt/dlog.c
- src/include/gurt/debug.h
> DAOS-6799 log: Add D_LOG_FLUSH envariable

- src/common/tests/prop_tests.c
- src/vea/tests/vea_ut.c
- src/vos/tests/vts_aggregate.c
> DAOS-6334 tests: use assert_rc_equal for unit tests

- src/include/daos/tests_lib.h
> DAOS-6334 test: make assert_rc_equal independent of passed arguments

- src/gurt/telemetry.c
Refine a few dbg log related with shm.
> DAOS-6849 gurt: small refine of dbg log of shm

- src/common/README.md
Corrected a small inaccuracy about the dRPC server handler,
leftover from an older revision.
Doc-only: true
> DAOS-2614 doc: Update common README

- src/tests/ftest/io/large_file_count.py
Fix large_file_count.py in weekly run
Test-tag-hw-large: pr,hw,large largefilecount
> DAOS-6869 tests: Fix large_file_count.py in weekly run

- Jenkinsfile
> DAOS-623 test: Run daily integration testing

- src/client/dfs/README.md
- src/object/README.md
> DAOS-2615 docs: update README for some client APIs (#4799)

- Jenkinsfile
To only run at 00:00 ET as release/1.2 is now running at 12:00 ET.
Minor sync with release/1.2 Jenkinsfile changes.
> DAOS-623 test: Reduce daily integration testing

- src/mgmt/srv_query.c
- src/tests/suite/daos_test_common.c
Fixes for CIs 318171 and 313058.
> DAOS-6699 misc: Fix coverity issues

- src/object/srv_obj_migrate.c
If the container is being destroyed during migration,
then the object pulling might not be able to get anything,
so let's ignore those objects for the moment.
> DAOS-6840 objects: skip empty object during migration

- Doxyfile
- doc/index.md
- doc/man/man8/daos.8
- doc/overview/data_integrity.md
- doc/user/interface.md
> daos-4802 documentation: update daos man page and other doc updates

- src/tests/ftest/datamover/dm_posix_meta_entry.py
- src/tests/ftest/datamover/dm_posix_meta_entry.yaml
Test-tag-vm: pr dm_posix_meta_entry
Added test case to test inode metadata for dcp.
Added commented out future support for xattrs.
> DAOS-6390 test: datamover verify POSIX metadata

- src/client/storage_estimator/common/vos_size.py
- src/client/storage_estimator/daos_storage_estimator.py
- src/include/daos_srv/vos.h
- src/vos/vos_overhead.c
- src/vos/vos_size.c
Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>
> DAOS-623 vos: Add container overhead to the storage estimator tool

- src/control/server/engine/config.go
- src/control/server/engine/exec.go
- src/control/server/engine/exec_test.go
By default, all environment variables provided to the
engine subprocesses must be set by the control plane.
An optional per-engine config parameter (env_pass_through)
may be set to pass through variables set before the control
plane was started.
> DAOS-3105 control: Scrub engine environment

- src/control/server/engine/config.go
- src/control/server/engine/exec.go
- src/control/server/engine/exec_test.go
> Revert "DAOS-3105 control: Scrub engine environment"

- src/rebuild/srv.c
Do not set complete to rebuild task if it needs to be rescheduled,
otherwise query status might get wrong information.
> DAOS-6997 rebuild: Not set complete for reschedule rebuild

- src/vos/tests/evt_ctl.c
This bug was identified by Coverity
> DAOS-6732: Remove line of code that is not reached (#4797)

- src/client/dfs/dfs.c
> DAOS-7009 dfs: fix rc return bug

- src/client/api/object.c
- src/container/srv_oi_table.c
- src/include/daos/object.h
- src/object/obj_class.c
OIT should with #replicas = cont_rf + 1.
> DAOS-7013 obj: OIT should match with cont_rf

- src/client/dfs/duns.c
- fix issue where direct format isn't checked from beginning
- allow for direct format only with resolve_path (needed for HDF5)
- support direct format for create_path (needed for HDF5)
for pool only path, match exact format for regex and fail if path is specified.
> DAOS-6574 duns: some bug fixes and features to DUNS (#4798)

- Jenkinsfile
> CORCI-1060 ci: Use correct builds for warnings-ng/NLT reference.

- src/control/server/server.go
Sync WaitGroup used to know when to start collecting telemetry data can
be decremented below zero when an engine exits and is restarted within
the lifetime of a daos_server process. WaitGroup should be reset on
engine process exit.
> DAOS-7014 control: fix dmg system start segfault

- src/tests/ftest/container/full_pool_container_create.py
- src/tests/ftest/container/full_pool_container_create.yaml
Unskipping and fixing container/full_pool_container_create.py
Test-tag: fullpoolcontcreate
> DAOS-6321 test: Unskip and fix container/full_pool_container_create.py

- src/mgmt/srv_pool.c
- src/object/srv_ec_aggregate.c
- src/pool/cli.c
- src/pool/cli_internal.h
- src/pool/srv_cli.c
- src/tests/jobtest.c
- Fix reference counting for pool
- Free memory in an error path
> DAOS-6808 pool: Fix cleanuping resources

- src/common/dts.c
Another fix to prevent destroying the existing pool after daos
racer if it is specified via the option "-p".
> DAOS-6938 tests: keep the pool after racer test if required(2)

- src/tests/ftest/cart/SConscript
- src/tests/ftest/cart/dual_iface_server.c
> DAOS-6006 test: Add dual interface server test

- src/tests/suite/daos_rebuild_simple.c
Add tests to verify inflight I/O with reintegration.
> DAOS-6999 tests: add tests to verify reintegrate inflight IO

- src/control/lib/control/system.go
- src/control/lib/control/system_test.go
Event logger incorrectly assumes that a syslogger for a given priority
can be created (which requires syslog to be configured on the local
host). Missing syslog capability on host triggers an exception in
daos_server. Fix by reporting error when failing to create syslogger
and skipping missing syslog priority targets when logging event.
> DAOS-7047 control: fix panic when syslog is not configured

- src/cart/crt_context.c
- src/include/cart/api.h
- Add new crt_rank_abort_all() API.
> CART-959 api: Add new crt_rank_abort_all() API

- src/tests/ftest/container/full_pool_container_create.py
- src/tests/ftest/container/full_pool_container_create.yaml
Unskipping and fixing container/full_pool_container_create.py
Test-tag: fullpoolcontcreate
> DAOS-6321 test: Unskip and fix container/full_pool_container_create.py (#4972)

- src/tests/ftest/daos_vol/daos_vol.py
- src/tests/ftest/daos_vol/daos_vol.yaml
Add missing HDF5 async test
Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>
> DAOS-5243 test: Add missing HDF5 async test

- Jenkinsfile
- src/engine/init.c
> DAOS-623 build: Split hardware tests into a new pipeline stage

- src/control/cmd/dmg/pretty/telemetry.go
- src/control/cmd/dmg/telemetry.go
- src/control/lib/control/telemetry.go
- src/control/lib/control/telemetry_test.go
Minor cleanup based on feedback.
> DAOS-5915 dmg: Clean up DMG metrics commands

- src/tests/ftest/nvme/nvme_io_verification.py
- src/tests/ftest/util/ior_utils.py
Fixing test_nvme_io_verification failing with TypeError
Test-tag-hw-large: pr,hw,large nvme_io_verification
> DAOS-7095 test: Fix weekly test nvme_io_verification

- src/engine/sched.c
Fix the improper assert in sched_try_relax().
> DAOS-6792 sched: fix improper assert (#5005)

- src/vos/vos_dtx.c
To handle the race from DTX refresh, the leader will pre-create
the DTX entry in DRAM before dispatching related modifications.
If such pre-created DTX entry was found by the resent handling
logic before leader prepared related local modifications, then
the server should return "-DER_INPROGRESS" to the client. Then
the modification for actived DTX entry should not happen unless
former abort left stale entry.
Master-PR: https://github.com/daos-stack/daos/pull/4791
> DAOS-6733 vos: handle resend RPC when original one is not prepared

- src/container/srv_target.c
When aggregation is already triggered in lazy mode, and xstream
started to be busy on processing IO, we'd control the aggregation
to run in a slow rate (when no space pressure) to avoid impacting
IO performance too much.
> DAOS-5403 container: control aggregation rate

- src/rsvc/srv_common.c
This is a new way to fix extra data leak problem if
destination buffer is larger than real attr size.
To allow for only requested or attr exact size to be sent and
avoid packing by Mercury, each segment has to be sent as a
single bulk transfer instead as all being part of the same
bulk transfer and have Mercury do own management.
This allows to conform with original behaviour, so
no associated tests need to be modified anymore.
This PR is the 1.2 version of master PR-4745.
Master-PR: https://github.com/daos-stack/daos/pull/4745
> DAOS-6709 rsvc: xfer only attr size and fix tests (#4745)

- src/tests/ftest/daos_test/daos_core_test_dfs.yaml
- src/tests/suite/dfs_unit_test.c
> DAOS-7065 test: add multi threaded dfs test for mkdir of same dir

- src/client/dfs/dfs.c
- src/include/daos_fs.h
> DAOS-7102 DFS: correct name of max len instead of path (#5190)

- src/tests/ftest/rebuild/io_conf_run.py
> DAOS-3866 Test: Updating the skip ticket as now io_conf_run is blocked  on ticket DAOS-7136

- src/container/cli.c
- src/container/container_iv.c
- src/container/srv_cli.c
- src/gurt/hash.c
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/srv_obj_migrate.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- Fix reference counting for container
- Free memory in an error path
- Resolve the race in REBUILD code
> DAOS-6808 container: Fix cleanuping resources

- src/tests/ftest/object/object_integrity.py
Fix failing weekly test object_integrity.py
Test-tag: objectvalidation
> DAOS-7090 test: Fix failing weekly test object_integrity.py

- Jenkinsfile
- ci/rpm/build.sh
- ci/unit/test_post_always.sh
- src/tests/ftest/cart/util/cart_utils.py
- src/tests/ftest/get_remote_files.sh
- src/tests/ftest/launch.py
- src/tests/ftest/scripts/setup_nodes.sh
- src/tests/ftest/util/daos_core_base.py
- utils/rpms/daos.spec
- utils/run_test.sh
- utils/sl/prereq_tools/base.py
Enable cov file generation on functional tests
when Skip-fnbullseye is set to false
> DAOS-4817 test: Enable cov file generation on functional tests (#5021)

- ci/rpm/build.sh
Fix shellcheck in rpm build.sh
> DAOS-7171 script: Fix shellcheck in rpm build.sh

- doc/user/spark.md
- src/client/java/README.md
Update spark.md to reflect latest Java wrapper update
> DAOS-5529 Update spark.md to reflect latest Java wrapper update (#4553)

- src/tests/ftest/cart/rpc/cart_rpc_one_node_with_swim_notification_on_rank_eviction.yaml
- Fix swim test to wait for 10 seconds for swim to initialize
> CART-89 test: Fix swim test

- src/tests/ftest/daos_test/daos_core_test-nvme_recovery.yaml
- src/tests/ftest/daos_test/daos_core_test-rebuild.yaml
- src/tests/ftest/daos_test/daos_core_test.yaml
This reverts commit d90fe57b
Test-tag-hw-medium: pr,hw,medium,ib2,daos_core_test
> Revert "DAOS-7006 csum: Add csum property to daos_test yaml"

- src/client/pydaos/raw/daos_api.py
Code is comparing a str with a byte obj
> DAOS-7185 test: fix string compare of byte obj

- src/include/daos_obj.h
> DAOS-623 doc: fix object header comment on flags to indicate supported

- src/object/cli_obj.c
Including dkey, akeys, iods, sgl validity check for transactional
update and punch before caching them in the DTX client side cache.
> DAOS-7215 object: validity check for transactinoal modification

- src/tests/ftest/daos_test/daos_core_test-nvme_recovery.py
- src/tests/ftest/daos_test/daos_core_test-nvme_recovery.yaml
- src/tests/suite/daos_nvme_recovery.c
> DAOS-7120 Test: Adding NVMe recovery test for offline and online pool.

- src/common/tests/common_test.c
- src/common/tests_dmg_helpers.c
Fixed Below CDT issues:
313028(#1 of 2)
313033(#1 of 1)
329579(#1 of 1)
> DAOS-7238 Test: Fixed coverity issue in test code.

- src/utils/daos_hdlr.c
Move an rc check + free to fix resource leak.
Features: fs_copy,-hw
> DAOS-6604 coverity: defect in fs_copy

- src/object/obj_enum.c
- src/object/srv_obj_migrate.c
Fixes for issues 329168 and 329166.
Label: ast-fixes
> DAOS-7240 obj: Coverity fixes

- src/placement/jump_map.c
- src/placement/ring_map.c
- src/placement/tests/placement_test.c
> DAOS-7239 coverity: various fixes in placement (#5463)

- third_party_programs.txt
Signed-off-by: Scott Kirvan <Scott.Kirvan@intel.com>
> daos-7249 doc: document 3rd party code usage

- third_party_programs.txt
Signed-off-by: Scott Kirvan <Scott.Kirvan@intel.com>
Co-authored-by: cdurf1 <craig.durfey@intel.com>
> daos-7249 doc: document 3rd party code usage (#5486)

- src/utils/daos_hdlr.c
Move an rc check + free to fix resource leak.
Master-PR: https://github.com/daos-stack/daos/pull/5457
> DAOS-6604 coverity: defect in fs_copy (#5457)

- src/tests/ftest/cart/test_group_np_common.h
> Revert "DAOS-7246: Fix Coverity issue in CaRT Test code (2)"

- src/tests/ftest/util/data_mover_test_base.py
> DAOS-7266 test: Fix merge conflict typo in data mover test

- src/tests/ftest/datamover/dm_dst_create.py
- src/tests/ftest/datamover/dm_dst_create.yaml
- src/tests/ftest/util/data_mover_test_base.py
Test-tag: pr datamover
- Added test case to verify creation of destination containers.
- Added display_space to DataMoverTestBase.run_ior
- Added cont_type param to DataMoverTestBase.create_cont
> DAOS-6837 test: datamover dst create

- src/tests/suite/daos_nvme_recovery.c
> DAOS-7281 Test:Fix Coverity Issue in NVMe Recovery Test

- src/tests/ftest/osa/osa_offline_reintegration.py
Test-tag-hw-medium: pr,hw,medium,ib2 offline_reintegration_srv_stop
> DAOS-6805 test: Re-enable system stop/start test

- src/engine/ult.c
sched_ult2xs() should avoid using XS0 for IO forwarding, to avoid
blocking XS0.
> DAOS-7170 engine: avoid using XS0 for IO forwarding

- src/client/dfuse/dfuse_main.c
- utils/node_local_test.py
This got broken with recent changes, so re-instate it and
add a test to verify it's correct.
> DAOS-7176 dfuse: Fix single-threaded option to dfuse.

- src/control/cmd/daos/container.go
- src/control/cmd/daos/pool.go
- src/control/cmd/daos/util.go
- src/utils/SConscript
- src/utils/daos_autotest.c
* leverage dmg's pretty printer for pool info
* pool query
* pool list-attrs
* pool get-attr
* pool set-attr
* pool del-attr
* pool autotest
> Add pool commands

- doc/admin/deployment.md
Update admin guide to recommend using storage prepare locally.
> DAOS-7365 doc: update storage prepare usage in admin guide

- doc/admin/deployment.md
Update admin guide to recommend using storage prepare locally.
> DAOS-7365 doc: update storage prepare usage in admin guide (#5602)

- src/cart/crt_group.c
- Downgrade warning message to info
> CART-89 fix: Downgrade log message

- src/utils/daos.c
- utils/node_local_test.py
Add a NLT test to copy a container.
> DAOS-7128 test: Add a test for container copy.

- src/object/README.md
Replace "schema" with "class" because "class" is the terminology we
decided to use.
Remove detailed description of client side replication because it is a distraction
Add EC description to single (unstripped) object
> DAOS-623 doc: Update README.md (#5614)

- Jenkinsfile
This was working reliably in a PR, however has failed once
landed to master, so keep the new code but disable it
for now until we can identify the problem.
> DAOS-7128 test: Disable NLT in build stage.

- src/tests/ftest/osa/osa_offline_drain.yaml
Test-tag-hw-medium: pr,hw,medium,ib2 offline_drain
> DAOS-7279 test: Increase scm/nvme (offline drain)

- src/tests/ftest/cart/util/cart_logtest.py
This is happening intermittently now and showing as a regression
so silence it.
Adding file src/tests/ftest/cart/util/cart_logtest.py
> DAOS-7193 test: Ignore rdb_stop() warning in server logs.(#5360)

- doc/admin/deployment.md
Update the certificate documentation for 'certs' dir under /etc/daos
> DAOS-7388 doc: Update deployment.md for certs

- SConstruct
- src/client/array/dc_array.c
- src/common/tests/sched.c
- src/gurt/tests/test_gurt.c
- src/include/daos/common.h
- src/include/daos/tests_lib.h
- src/include/gurt/common.h
- src/mgmt/srv_drpc.c
- src/rdb/rdb_util.c
- src/vea/vea_alloc.c
- src/vos/vos_io.c
- utils/run_test.sh
- utils/test_memcheck.supp
Master PR #5613, PR #5633
Memory leaks, bug fixes, valgrind optimizations
Co-authored-by: Kris Jacque kristin.jacque@intel.com
> DAOS-623 common: Cherry pick several bug fixes

- src/tests/ftest/datamover/dm_serial_large_posix.py
- src/tests/ftest/datamover/dm_serial_large_posix.yaml
- src/tests/ftest/util/data_mover_test_base.py
- Added test case for serializing a large posix container
> DAOS-7432 test: datamover serialize large posix

- src/container/cli.c
- src/container/cli_internal.h
- utils/node_local_test.py
Add a NLT test for this so it's run under valgrind.
> DAOS-7128 test: Add a test for container clone.

- src/client/array/dc_array.c
- src/client/dfs/dfs.c
- src/dtx/dtx_common.c
- src/dtx/dtx_rpc.c
- src/mgmt/srv_target.c
- src/object/srv_ec_aggregate.c
- src/object/srv_obj.c
> DAOS-6808 misc: Fix cleaning up resources (#5010)

- src/tests/ftest/osa/osa_offline_extend.py
Test-tag-hw-large: pr,hw,large offline_extend
> DAOS-7493 test: Skip offline extend (oclass) test

- src/tests/suite/daos_nvme_recovery.c
> DAOS-623 test: Add fault injection check for NVMe tests

- src/tests/ftest/erasurecode/ec_offline_rebuild.py
- src/tests/ftest/erasurecode/ec_offline_rebuild_single.py
- src/tests/ftest/erasurecode/ec_offline_rebuild_single.yaml
- src/tests/ftest/erasurecode/ec_online_rebuild.py
- src/tests/ftest/erasurecode/ec_online_rebuild_single.py
- src/tests/ftest/erasurecode/ec_online_rebuild_single.yaml
- src/tests/ftest/erasurecode/ec_rebuild_disabled.py
- src/tests/ftest/erasurecode/ec_rebuild_disabled_single.py
- src/tests/ftest/erasurecode/ec_rebuild_disabled_single.yaml
- src/tests/ftest/util/ec_utils.py
- Adding EC Rebuild disabled for single data type.
Test-tag: ec_disabled_rebuild_single
> DAOS-7314 Test: Adding EC test case for single data type.

- src/control/lib/control/README.md
- src/control/lib/control/doc.go
Add links to public API methods and a simple example.
Doc-only: true
> DAOS-4729 control: Update Control API README

- src/control/lib/control/auto.go
- src/control/lib/control/auto_test.go
- src/control/lib/control/pool_test.go
- src/control/server/config/server.go
- src/control/server/ctl_storage.go
- src/control/server/engine/config.go
- src/control/server/engine/config_test.go
- src/control/server/engine/exec_test.go
- src/control/server/engine/tags.go
- src/control/server/engine/tags_test.go
- src/control/server/engine/testdata/full.golden
- src/control/server/instance_storage_rpc.go
- src/control/server/storage/class.go
- src/control/server/storage/config.go
- src/control/server/storage/provider.go
* Update tags parser to set -T based on slice length
* Rename storage.StorageConfig -> storage.Config
* Rename storage.Config -> storage.TierConfig
* Skip nvme config generation with 0 bdevs
> Misc recommended improvements

- src/client/api/container.c
- src/common/pool_map.c
- src/container/container_iv.c
- src/container/srv_container.c
- src/container/srv_internal.h
- src/container/srv_layout.c
- src/container/srv_target.c
- src/include/daos/object.h
- src/include/daos_cont.h
- src/include/daos_prop.h
- src/include/daos_srv/container.h
- src/include/daos_srv/pool.h
- src/include/daos_srv/security.h
- src/object/cli_obj.c
- src/object/cli_shard.c
- src/object/obj_rpc.h
- src/object/srv_ec_aggregate.c
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
- src/pool/srv_iv.c
- src/pool/srv_target.c
- src/security/srv_acl.c
- src/tests/suite/daos_checksum.c
- src/tests/suite/daos_container.c
- src/tests/suite/daos_degrade_ec.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_ec.c
- src/tests/suite/daos_test_common.c
- src/utils/daos.c
> Revert "DAOS-7235 obj: turn off read/write perm when cont_rf broken"

- debian/daos-client.install
- src/control/SConscript
- src/control/cmd/daos/acl.go
- src/control/cmd/daos/attribute.go
- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/control/cmd/daos/main.go
- src/control/cmd/daos/pool.go
- src/control/cmd/daos/property.go
- src/control/cmd/daos/snapshot.go
- src/control/cmd/daos/util.c
- src/control/cmd/daos/util.go
- src/control/cmd/daos/util.h
- src/control/server/server.go
- src/tests/ftest/security/cont_get_acl.py
- src/utils/SConscript
- src/utils/daos_hdlr.c
- utils/node_local_test.py
- utils/rpms/daos.spec
s/daos/daos_old/
s/daos_new/daos/
> Switch to new implementation

- Jenkinsfile
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.centos.8
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.ubuntu.20.04
Set up the CentOS and Leap dockerfiles to be able to use their
own repository.
> CORCI-1063 build: Add repository for Dockerfiles

- src/dtx/dtx_rpc.c
For efficiently sending DTX RPCs to related servers, we classify
the DTX sub requests in DRAM on the leader. For each sub request,
usually, it will be added in the classification tree and a global
list. But under some special cases, such as out of memory on the
leader, above classification may fail, as to related sub request
only exists in the list. Then only destroying the classification
tree cannot release related sub request. We still need to travel
the global list to drop those failed sub requests after DTX RPC.
> DAOS-7666 dtx: properly cleanup DTX sub requests

- src/dtx/dtx_rpc.c
- src/include/daos/rpc.h
- src/pool/cli.c
- src/pool/rpc.h
- src/pool/srv_pool.c
- src/pool/srv_target.c
Extend current pool target query C API to return target space
info.
> DAOS-3625 pool: Pool target space query

- src/pool/srv_util.c
> DAOS-7012 bio: fix spelling nit

- src/rsvc/srv_common.c
- src/tests/suite/daos_container.c
- src/tests/suite/daos_pool.c
> Revert "DAOS-6710 rsvc: don't exit upon non-existent attr"

- src/bio/bio_context.c
- src/bio/bio_device.c
- src/pool/srv_util.c
This reverts commit 79faa06c342e5713e77976581bdb3c9ec5dc07c7.
> Revert "DAOS-7012 bio: Tolerate inconsistent SMD info (#5754)"

- src/placement/tests/jump_map_place_obj.c
> DAOS-7728 test: Unskip placement tests referenced by fixed tickets

- src/control/lib/control/telemetry.go
- src/control/lib/control/telemetry_test.go
The QuantileMap type couldn't be marshaled/unmarshaled by the JSON
library. Added custom JSON marshal/unmarshal functions to handle
this type.
> DAOS-7760 dmg: Fix JSON output for telemetry query

- src/client/dfs/dfs_sys.c
- Fix a double free
- Fix a potential NULL dereference
> DAOS-7699 coverity: Fix cid 331783

- src/tests/ftest/rebuild/cascading_failures.py
- src/tests/ftest/rebuild/delete_objects.py
- src/tests/ftest/rebuild/read_array.py
- src/tests/ftest/util/ec_utils.py
Test-tag-vm: pr rebuild
Test-tag-hw-small: pr rebuild
Test-tag-hw-medium: pr rebuild
Test-tag-hw-large: pr rebuild
> DAOS-7801 test: clear cont status in rebuild tests

- doc/overview/use_cases.md
- src/cart/crt_internal_types.h
- src/engine/srv_cli.c
- src/tests/ftest/control/dmg_storage_query.py
- src/tests/ftest/util/agent_utils_params.py
- utils/node_local_test.py
> DAOS-7012 doc: via various spelling nits

- src/cart/crt_hg.c
- src/cart/crt_hg_proc.c
- src/cart/crt_iv.c
- src/cart/crt_rpc.c
- src/cart/crt_rpc.h
- src/cart/crt_swim.c
- src/container/cli.c
- src/dtx/dtx_rpc.c
- src/include/cart/api.h
- src/mgmt/cli_debug.c
- src/mgmt/cli_query.c
- src/mgmt/srv.c
- src/object/cli_shard.c
- src/object/obj_rpc.c
- src/object/obj_tx.c
- src/object/srv_obj_remote.c
- src/pool/cli.c
- src/pool/srv_iv.c
- Fix reference counting for rpc
- Free memory in an error path
> DAOS-6808 rpc: Fix cleanuping resources (#4807)

- Jenkinsfile
Disable release branch nightly and weekly
> DAOS-7817 test: Disable release branch nightly and weekly

- doc/dev/development.md
> DAOS-623 doc: Document the custom build target change

- src/object/obj_class.c
Linear search of EC codec is too expensive(over 200 EC classes).
This patch uses binary search to search EC codec.
> DAOS-7850 object: binary search for EC codec

- src/tests/ftest/daos_test/daos_core_test_dfs.py
- src/tests/ftest/daos_test/daos_core_test_dfs.yaml
Quick-Functional: True
Test-tag: dfs_test
- Run dfs_test -s
- Tag tests with dfs_test
> DAOS-7759 test: run dfs_sys tests

- doc/admin/administration.md
- src/control/events/README.md
> DAOS-6711 doc: ras event structure and ids

- src/tests/ftest/daos_vol/daos_vol.py
> DAOS-7888 test: Skip h5_test_testhdf5

- ftest.sh
- src/tests/ftest/scripts/main.sh
Update argument passing for launch.py to support recent pipeline-lib
changes.
> DAOS-7886 tests: Fix failing Functional HW stages

- src/client/dfuse/dfuse_core.c
> Revert "DAOS-7671 dfuse: change attrs names memory location"

- src/client/dfuse/dfuse_cont.c
- src/client/dfuse/dfuse_core.c
- utils/node_local_test.py
Enable the new feature added recently.
> DAOS-7174 dfuse: Enable testing of dfuse with container labels.

- doc/user/mpi-io.md
- doc/user/posix.md
> DAOS-7521 doc: update posix.md

- doc/release/support_matrix.md
Removed suse 15.2 from 1.2 support matrix
> Remove SUSE 15.2 from 1.2 support

- site_scons/prereq_tools/base.py
> Revert "DAOS-623 build: Use shallow clone when building deps."

- doc/admin/performance_tuning.md
> DAOS-7510 doc: update perf doc

- src/cart/utils/memcheck-cart.supp
Suppress some intermittent errors.
> DAOS-623 go: Update suppression files for go.

- utils/build.config
> DAOS-623 build: Update to PMDK 1.11

- src/control/server/engine/exec.go
Reduce the amount of code being run in a separate goroutine,
thereby eliminating the need to guard the cmd field against
unsafe concurrent access.
> DAOS-7995 control: Fix race in engine runner

- .github/workflows/ci.yml
- .github/workflows/ci2.yml
- .github/workflows/doxygen.yml
- ci/copy_doxygen_files.sh
- site_scons/components/__init__.py
- src/include/cart/api.h
- src/include/daos_types.h
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.centos.8
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.ubuntu.20.04
Use pip3 --user
Do not install pandoc, curl, man or doxygen.
Move leap to new build process to cut down on leap rebuilds by
making use of github cache.
Update the doxygen process so it's all in a shell script, not github json.
* Do not attempt to review non-release header file.
* Abort early if no release headers are modified.
> DAOS-623 build: Resolve issues with Dockerfiles.

- src/control/server/harness.go
The interface needed to be updated for new callbacks.
> DAOS-7124 control: Fix build breakage after landing

- doc/admin/performance_tuning.md
- src/utils/self_test/self_test.c
- Update self_test documentation section
- Update self_test to deprecate arguments that are no longer used
Signed-off-by: Alexnader Oganezov <alexander.a.oganezov@intel.com>
> DAOS-7510 doc: Update self_test documentation section

- src/control/cmd/daos/container.go
- src/control/cmd/daos/pool.go
- src/control/cmd/daos/property.go
* Add `cont list` alias to `pool list-cont`
* Add `cont create --label` for convenience
* Don't display empty table if pool has no containers
* Limit container info shown after create
* Fix settable props handling/completion
* Destroy by path should remove directory
> DAOS-8031 tools: Misc fixups for daos tool

- src/tests/ftest/soak/soak_faults.yaml
- src/tests/ftest/soak/soak_harassers.yaml
- src/tests/ftest/soak/soak_smoke.yaml
- src/tests/ftest/soak/soak_stress_2h.yaml
- src/tests/ftest/soak/soak_stress_48h.yaml
- src/tests/ftest/soak/soak_utils.py
- src/tests/ftest/util/dmg_utils.py
- src/tests/ftest/util/dmg_utils_base.py
- src/tests/ftest/util/test_utils_pool.py
Test-tag-hw-large: pr soak_smoke
> DAOS-8036 test: Add pool properties to TestPool and Dmg

- src/pool/srv_pool.c
Since ds_pool_query_handler no longer transfer the pool map buffer
directly from persistent memory, it no longer has to do so under the
metadata lock. This patch releases the lock before the transfer, to
improve POOL_QUERY concurrency.
> DAOS-560 pool: Optimize map transfer in POOL_QUERY

- site_scons/daos_build.py
- site_scons/env_modules.py
- site_scons/prereq_tools/base.py
- site_scons/site_tools/extra/extra.py
- utils/docker/Dockerfile.ubuntu.20.04
- utils/sl/fake_scons/SCons/Script/__init__.py
Move from using distutils.find_executable to WhereIs.
Fix pylint issues.
> DAOS-623 build: Replace distutils with WhereIs

- src/cart/utils/memcheck-cart.supp
- utils/test_memcheck.supp
> DAOS-623 valgrind: Suppress a new mercury reachable leak

- src/object/srv_ec_aggregate.c
If there are partial stripes being processed, it should
set SKIP, so the extent can be skipped after yield.
> DAOS-8018 EC: Missing SKIP set for EC aggregation

- .github/workflows/ci2.yml
- utils/run_in_ga.sh
This workaround was removed last week after testing, however
once the removal was landed we're seeing the bug again so
add back in the workaround.
Add some diagnostics to validate the issue.
> DAOS-7764 gha: Re-instate workaround for spdk build issue.

- src/client/array/dc_array.c
- src/client/dfs/dfs.c
> DAOS-6726 array: fixing memleak in FI testing

- src/tests/ftest/util/apricot/apricot/test.py
Do not attempt to log a message to the server log when a test is not
running a daos_agent.
> DAOS-8144 tests: Fix IndexError for tests w/o agent running.

- src/vos/ilog.c
- src/vos/ilog.h
- src/vos/vos_layout.h
Allocate minimum size and align to 64 bytes
Remove some dead code
> DAOS-7878 vos: Address some review comments from prior patch

- src/control/cmd/daos_agent/fabric_test.go
- src/control/cmd/daos_agent/infocache_test.go
Conflict crept in with recent agent-related changes.
> DAOS-8047 test: Fix Go unit test conflict

- src/engine/server_iv.c
Move iv entry destroy from iv_ns_destory_cb to ds_iv_ns_stop(),
since iv entry destroy might need iv class ops from different
module, and iv_entry_destroy_cb() might be too late for it.
> DAOS-8125 IV: move iv entry destroy to ds_iv_stop

- debian/changelog
- debian/daos-client.install
- debian/daos.install
- src/common/policy.c
- src/common/tests/policy_tests.c
- src/control/SConscript
- src/control/drpc/property.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_property.go
- utils/rpms/daos.spec
Some fixes:
* Use C-based policy validator to avoid duplicate logic
* Adjust policy param delimiter to "/" to work with property parser
> Misc fixes

- src/tests/ftest/erasurecode/ec_cell_size.py
- src/tests/ftest/erasurecode/ec_cell_size.yaml
Test-tag-hw-large: pr,hw,large ec_cell_size
> DAOS-7311 Test: Add test cases to run IOR with different cell size.

- src/vos/tests/vts_mvcc.c
- src/vos/vos_ilog.c
Conditional insert was not handling inprogress and uncertain
entries properly.  Fix those cases so we return appropriate errors
when we can't determine if the key exists or not
> DAOS-7984 vos: Fix conditional insert

- src/placement/jump_map.c
If all targets of the domain has been used, then let's set
the current group bit as well to make sure the domain will not
be choosen again, and also reset the group track bits correctly.
> DAOS-8165 placement: set cur group used bit for full domain

- src/control/server/instance_test.go
Update the mock to match the interface.
> DAOS-7124 control: Fix unit test failure

- src/client/dfuse/dfuse_obj_da.c
- src/common/tests_dmg_helpers.c
- src/container/srv_target.c
- src/vos/sys_db.c
various minor fixes about checking return value of
some functions.
> DAOS-7971 daos: various minor fixes

- src/tests/ftest/erasurecode/ec_aggregation.yaml
- src/tests/ftest/erasurecode/ec_offline_rebuild.yaml
- src/tests/ftest/erasurecode/ec_offline_rebuild_single.yaml
- src/tests/ftest/erasurecode/ec_online_rebuild.py
- src/tests/ftest/erasurecode/ec_online_rebuild.yaml
- src/tests/ftest/erasurecode/ec_online_rebuild_single.py
- src/tests/ftest/erasurecode/ec_online_rebuild_single.yaml
- src/tests/ftest/erasurecode/ec_rebuild_disabled.py
- src/tests/ftest/erasurecode/ec_rebuild_disabled.yaml
- src/tests/ftest/erasurecode/ec_rebuild_disabled_single.yaml
Updated the SCM/NVMe size to work with new cluster.
Test-tag-hw-large: ec_single ec_array
> DAOS-7592 Test: Removed skip for EC tests.

- src/common/tests/checksum_tests.c
- src/tests/suite/daos_checksum.c
- src/vos/tests/evt_ctl.c
- src/vos/tests/vts_container.c
> DAOS-7969 test: coverity fixes in test code

- src/tests/ftest/ior/ior_small.yaml
> DAOS-8233 test: increase timeout on ior_small

- utils/config/daos_server.yml
> DAOS-8302: fix typo of non-RDMA-capable Ethernet provider

- utils/docker/Dockerfile.ubuntu.20.04
This is required to apply patch for SPDK.
> DAOS-8003 build: add curl to docker file

- doc/overview/data_integrity.md
- src/rebuild/README.md
- src/vos/README.md
The requirements section in the data_integrity.md document did not
belong so it was removed. Also moved some of the developer specific
notes out of the overview and into more appropriate source READMEs.
Doc-only: true
> DAOS-7503 csum: Documentation Update for 2.0

- src/tests/ftest/util/job_manager_utils.py
> DAOS-8306 test: Verify Job manager has attr check_results_list

- src/rebuild/scan.c
If the reintegrate is restarted due to the failure, then reclaim
phase will not be executed, so it might put multiple shards in
the same VOS target, so it might see duplicate OID in the next
scan phase, i.e. see -DER_EXIST failure, so let's ignore this
failure for the moment, since the duplicate object will be removed
in the final reclaim phase anyway.
> DAOS-8259 rebuild: ignore DER_EXIST for reintegration

- doc/QSG/autotest.md
- doc/QSG/cartselftest.md
- doc/QSG/datamover.md
- doc/QSG/dbench.md
- doc/QSG/mdtest.md
- doc/QSG/runior.md
- doc/QSG/scratch.md
- doc/QSG/setup.md
- doc/QSG/suse_setup.md
- doc/QSG/test_index.md
- doc/QSG/tour.md
> daos-8295 documentation: update and place qsg files

- src/tests/ftest/daos_vol/daos_vol.py
- src/tests/ftest/ior/ior_small.py
- src/tests/ftest/ior/ior_small.yaml
- src/tests/ftest/util/ior_test_base.py
also revert commit 75a46e5.
as that change does not work for HDF5-VOL IOR tests.
> DAOS-8207 test: re-enable vol tests after being disabled

- doc/admin/administration.md
- doc/admin/tiering_uns.md
- src/rebuild/README.md
> daos-7503 documentation: csum review and telem section review

- src/control/provider/system/distribution.go
Define a type to match os.Open's signature to improve readability.
> DAOS-8107 control: Small refactoring of distribution.go

- src/tests/ftest/cart/corpc/cart_corpc_five_node.yaml
- src/tests/ftest/cart/corpc/cart_corpc_one_node.yaml
- src/tests/ftest/cart/corpc/cart_corpc_two_node.yaml
- src/tests/ftest/cart/ctl/cart_ctl_five_node.yaml
- src/tests/ftest/cart/ctl/cart_ctl_one_node.yaml
- src/tests/ftest/cart/ghost_rank_rpc/cart_ghost_rank_prc_one_node.yaml
- src/tests/ftest/cart/group_test/group_test.yaml
- src/tests/ftest/cart/iv/cart_iv_one_node.yaml
- src/tests/ftest/cart/iv/cart_iv_two_node.yaml
- src/tests/ftest/cart/no_pmix/cart_nopmix_multictx_one_node.yaml
- src/tests/ftest/cart/nopmix_launcher/cart_nopmix_launcher_one_node.yaml
- src/tests/ftest/cart/rpc/cart_rpc_one_node.yaml
- src/tests/ftest/cart/rpc/cart_rpc_one_node_with_swim_notification_on_rank_eviction.yaml
- src/tests/ftest/cart/rpc/cart_rpc_two_node.yaml
- src/tests/ftest/cart/selftest/cart_selftest_three_node.yaml
- src/tests/ftest/cart/util/cart_utils.py
Multiplex avocado yaml file on CRT_PHY_ADDR_STR
> CART-976 tests: Add 'sm' variant to cart tests

- src/control/fault/code/codes.go
- src/control/security/faults.go
- src/control/security/pem.go
Provide clearer information about the problem and how to fix it.
> DAOS-8435 control: Add structured errors for certificate problems

- src/object/obj_tx.c
When client side logic prepares CPD RPC to commit some
distributed transaction, it firstly generates dc_tx_rdg
data structure for every sub request to record related
redundancy group information. These RDG information may
be mergeable if multiple sub requests against the same
object or some objects share the same redundancy group.
When merge these redundancy group information, we will
set DMF_SRDG_REP flag if related distributed transaction
only touches single replicated object. That will simplify
server work if some others hit conflict with this DTX in
subsequent operations. If such flag is set by wrong, it
may cause others cannot get the committable status from
related DTX leader as to be blocked with repeated -2018
until such committable DTX is committed.
On the other hand, try to …
> DAOS-8444 dtx: merge redundancy groups properly

- src/common/btree.c
- src/common/btree_class.c
Fix few missing return value checking cases.
> DAOS-7851 vos: return value checking

- src/tests/ftest/soak/soak_smoke.yaml
- src/tests/ftest/soak/soak_stress_48h.yaml
- src/tests/ftest/soak/soak_test_base.py
- src/tests/ftest/soak/soak_utils.py
> DAOS-8434: Re-enable daos_racer in soak; DAOS-7436 no-fix

- Jenkinsfile
- ci/provisioning/post_provision_config.sh
- ci/provisioning/post_provision_config_nodes.sh
post_provision_config_nodes.h:
Fix to allow retries to run.
> CORCI-1112 Build: Post provisioning retry fixes

- src/control/cmd/daos_agent/mgmt_rpc.go
- src/control/cmd/daos_agent/mgmt_rpc_test.go
> DAOS-8477 agent: Fix GetAttachInfo when cache disabled

- src/tests/suite/daos_obj_ec.c
Add test case for different EC obj class' single-value overwrite.
> DAOS-7322 EC: add test case for single-value overwrite

- src/cart/crt_context.c
- src/cart/crt_utils.c
fix race during abort causing double completions.
> DAOS-7306 race: Fix race condition for double rpc completions

- src/object/srv_obj.c
There will be CPU yield during DTX refresh. We need to pin current
DTX before refreshing other DTX(es). Otherwise, during DTX refresh,
client may resend the RPC and related conflict DTX(es) entries may
have been committed when handling the the resent RPC. Then the DTX
for resent RPC may be committed before its original RPC, that will
trigger assertion in subsequent VOS check.
> DAOS-8492 object: pin DTX before DTX refresh for modification

- docs/admin/pool_operations.md
- docs/user/container.md
Update requirements now that we support hyphen.
doc-only: true
> DAOS-7174 doc: update label requirement

- src/tests/ftest/erasurecode/ec_offline_rebuild.yaml
- src/tests/ftest/erasurecode/ec_online_rebuild.yaml
- src/tests/ftest/erasurecode/ec_rebuild_disabled.yaml
Adding Partial update IO for offline rebuild and disabled rebuild existing test case.
Test-tag-hw-large: pr ec_offline_rebuild_array ec_disabled_rebuild_array
> DAOS-7321 Test: Adding Partial strip cases for rebuild.

- src/tests/ftest/soak/soak_utils.py
Test-tag-hw-large: pr soak_smoke
> DAOS-8506 tests: Fix daos_metrics logging in soak

- src/client/dfs/README.md
- src/object/README.md
> DAOS-8530 doc: add documentation to explain auto class selection

- src/object/srv_ec_aggregate.c
- src/placement/pl_map.c
If some objs skipped during EC aggregation (ds_pool_check_dtx_leader
failed for example), should not move ahead cont->sc_ec_agg_eph to
avoid VOS agg going ahead.
> DAOS-8230 EC: don't move ahead sc_ec_agg_eph if skipped obj

- docs/admin/administration.md
- docs/admin/deployment.md
Update admin guide instructions to take account of tiered storage config.
> DAOS-8488 doc: tiered storage config

- src/pool/srv_pool.c
Miss use object group size and class grp size during leader
selection, since object layout might be extend during reintegration.
> DAOS-8231 pool: miss use obj grp size and class grp size

- src/control/server/engine/utils.go
> DAOS-8547 control: allow error as well as err in setmasks

- src/control/server/ctl_network_rpc_test.go
- src/control/server/ctl_storage.go
- src/control/server/harness_test.go
- src/control/server/instance_test.go
- src/control/server/mgmt_drpc_test.go
- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
- src/control/server/mgmt_system.go
- src/control/server/storage/bdev/backend.go
- src/control/server/storage/bdev/backend_class_test.go
- src/control/server/storage/bdev/runner.go
- src/control/server/storage/config.go
> DAOS-8040 control: prune unused code and fix linter warnings

- src/tests/ftest/osa/osa_offline_reintegration.py
Test-tag-hw-medium: pr,hw,medium,ib2 daily_regression
> DAOS-7826 test: Update test to exclude all targets

- src/utils/daos_autotest.c
Added progress indicator to autotest
> DAOS-7735 test: Added progress indicator to autotest

- src/client/api/object.c
- src/include/daos/object.h
- src/object/cli_obj.c
> DAOS-8622 objects: fix split anchor for replicated objects

- src/include/gurt/common.h
- src/include/gurt/types.h
> DAOS-8490 common: Changed typeof to __typeof__ in header files.

- src/tests/ftest/util/apricot/apricot/test.py
> DAOS-8626 test: Ignore commit_list in manual test env

- docs/QSG/scratch.md
- docs/overview/data_integrity.md
- docs/overview/fault.md
- docs/user/python.md
- mkdocs.yml
various other doc updates to fix formatting and other issues
> daos-7501 documentation: Update Fault Model Documentation

- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/cart_ctl_utils.py
Disable cart_ctl object until issues with it are fixed
> CART-89 tests: Disable cart_ctl

- src/client/dfs/duns.c
- src/client/pydaos/pydaos_shim.c
> DAOS-8634 pydaos: coverity fixes

- src/mgmt/cli_mgmt.c
- src/mgmt/srv_drpc.c
-Cleaned up logically dead code pertaining to out_label. Coverity issue: 332669.
> DAOS-8636 mgmt: Fix Coverity Issue

- src/tests/ftest/aggregation/shutdown_restart.py
> DAOS-8677 test: Refactor aggregation/shutdown_restart.py

- src/cart/crt_context.c
- src/cart/crt_init.c
- src/cart/crt_internal_types.h
- src/cart/crt_swim.c
- src/cart/crt_swim.h
- src/cart/swim/swim.c
- src/cart/swim/swim_internal.h
- src/engine/init.c
- src/engine/sched.c
- src/engine/srv.c
- src/engine/srv_internal.h
- src/engine/ult.c
- src/include/cart/api.h
- src/include/cart/types.h
- src/include/daos/rpc.h
- src/include/daos_srv/daos_engine.h
- src/pool/srv_pool.c
- src/tests/ftest/cart/test_swim_net.c
> Revert "DAOS-8483 srv: Assign SWIM to a separate core"

- src/tests/ftest/launch.py
- src/tests/ftest/scripts/post_process_xml.sh
- utils/docker/Dockerfile.code_scanning
To try to get more accurate/relevant lists of tests to apply to PRs in
the future.
> DAOS-632 test: Submit test data to Launchable

- docs/admin/tiering_uns.md
Update the data migration portion of the
DAOS tiering document.
> DAOS-7513 doc: update daos tiering document

- src/tests/ftest/cart/iv_server.c
> DAOS-8861 cart: Remove errant assertion. (#7104)

- src/cart/utils/crt_utils.c
> DAOS-8637 cart: Address Coverity issues in CaRT (#7036).

- src/object/cli_obj.c
1. in shard_task_sched() reinit the task after register dependency,
this is safer for multi-threads because the task can be scheduled
right after reinit.
2. don't reuse original shard tasks when retry fetch
3. a few other refine for retry handling
> DAOS-8607 obj: refine task retry handling

- src/client/api/event.c
- src/client/array/dc_array.c
- src/client/dfs/dfs.c
- src/client/dfuse/dfuse_core.c
- src/common/tests/SConscript
- src/common/tests/sched.c
- src/common/tse.c
- src/tests/suite/dfs_par_test.c
- fix memleak when tse task is completed by child + add test
- combine short read task in IO read list
- fix some possible leaks with FI testing
- call event fini in dfuse
- other minor code format and test fixes.
> DAOS-8890 client: some fixes in tse, dc_array, and dfuse

- src/dtx/dtx_srv.c
- src/engine/module.c
- src/include/daos_srv/daos_engine.h
- src/include/daos_srv/vea.h
- src/include/daos_srv/vos.h
- src/object/srv_mod.c
- src/pool/srv_target.c
- src/vea/tests/vea_stress.c
- src/vea/tests/vea_ut.c
- src/vea/vea_alloc.c
- src/vea/vea_api.c
- src/vea/vea_free.c
- src/vea/vea_internal.h
- src/vea/vea_util.c
- src/vos/tests/vts_aggregate.c
- src/vos/vos_common.c
- src/vos/vos_internal.h
- src/vos/vos_pool.c
Add per VOS pool VEA telemetry.
> DAOS-8909 vea: Add VEA telemetry

- src/tests/suite/daos_degrade_ec.c
Add more unit tests for EC degraded mode + aggregation
- overlapped writes (misaligned with cell size)
- overlapped overwrites
> DAOS-7544 tests: Add EC aggregation+degraded test

- utils/docker_nlt.sh
- utils/setup_daos_admin.sh
Fix a couple of issues that prevented the script from
working correctly with non-standard installs.
> DAOS-8962 tool: Minor fixes for setup_daos_admin.sh

- src/tests/ftest/ior/intercept_basic.py
- src/tests/ftest/ior/intercept_basic.yaml
Test-tag: iorinterceptbasic
Test-repeat: 20
> DAOS-5857 test: Update the expected IL performance in IOR test.

- src/utils/crt_launch/crt_launch.c
- Fix crt_launch to work for both port-based and non-port providers
> CART-89 tests: Fix crt_launch to work for all providers

- src/client/api/README.md
- src/include/daos_event.h
> DAOS-8963 EQ: update documentation for event queue creation

- CONTRIBUTING.md
- README.md
- doc/admin/troubleshooting.md
- doc/dev/contributing.md
- doc/index.md
- doc/mkdocs.yml
- doc/overview/use_cases.md
- doc/release/release_notes_v1_2.md
- doc/release/support_matrix_v1_2.md
- src/engine/srv_cli.c
- src/placement/pl_map.c
- src/tests/ftest/control/dmg_storage_query.py
- src/tests/ftest/util/agent_utils_params.py
- utils/node_local_test.py
> DAOS-5579 doc: misc v1.2 doc fix-ups

- docs/admin/predeployment_check.md
> DAOS-8928 doc: fix mem lock link in pre-deployment checklist

- src/client/api/README.md
- src/include/daos_event.h
> DAOS-8963 EQ: update documentation for event queue creation (#7224)

- src/pool/srv_iv.c
Check special IV entry (for not enough entry size) during
connect IV entry refresh.
> DAOS-8648 pool: Check special IV entry during pool connect refresh

- src/common/prop.c
- src/common/tests/sched.c
- src/mgmt/cli_mgmt.c
- src/placement/tests/place_obj_common.c
- src/tests/ftest/cart/dual_iface_server.c
- src/tests/suite/daos_rebuild_ec.c
Coverity identified multiple issues in various C sources. This fixes CIDs:
329561, 331438, 332668, 332945, 339129, 340852
> DAOS-8921 Coverity: Various fixes for Coverity Issues

- docs/admin/predeployment_check.md
> DAOS-8928 doc: fix mem lock link in pre-deployment checklist (#7266)

- src/control/server/ctl_storage.go
- src/control/server/ctl_storage_rpc_test.go
- src/control/server/mgmt_pool.go
- src/control/server/storage/bdev/backend.go
- src/control/server/telemetry.go
> DAOS-9045 control: fix golangci-lint warnings in server package

- src/cart/crt_iv.c
Double check the reference count is changed in the gap between
refcount == 0 and real IV namespace destroy.
> DAOS-8949 inast: Fix race of IV namespace implementation

- src/client/api/event.c
- src/client/array/dc_array.c
- src/object/cli_shard.c
- src/tests/suite/dfs_par_test.c
> DAOS-9044 event: if async op failed, we are not resetting the priv event

- src/client/dfuse/il/int_posix.c
- src/client/dfuse/il/intercept.h
Add new interception for this function.
> DAOS-8822 il: Add interception for openat (#7020)

- src/tests/ftest/rebuild/no_cap.py
- src/tests/ftest/rebuild/no_cap.yaml
Test Description:
Create and connect to a pool and container. Full fill the pool
container, verify the pool information after rebuild, make sure
correct error of pool full status after rebuild.
Test steps:
(1)Check for pool and rebuild info
(2)Display pool free space before write
(3)Start write data to full fill the container
(4)Display pool size after write before rebuild
(5)Stop rank for rebuild
(6)Wait for rebuild started
(7)Poll and verify pool rebuild status with error after rebuild
(8)Verify pool and rebuild info after rebuild
modified:   no_cap.py
modified:   no_cap.yaml
Test-tag: pr no_cap
> DAOS-8846-test2: Fix and enable script for no_cap.py

- src/cart/crt_iv.c
Double check the reference count is changed in the gap between
refcount == 0 and real IV namespace destroy.
> DAOS-8949 inast: Fix race of IV namespace implementation (#7179)

- src/tests/ftest/rebuild/no_cap.py
- src/tests/ftest/rebuild/no_cap.yaml
Cherry pick from master(PR-7303)
Test Description:
Create and connect to a pool and container. Full fill the pool
container, verify the pool information after rebuild, make sure
correct error of pool full status after rebuild.
Test steps:
(1)Check for pool and rebuild info
(2)Display pool free space before write
(3)Start write data to full fill the container
(4)Display pool size after write before rebuild
(5)Stop rank for rebuild
(6)Wait for rebuild started
(7)Poll and verify pool rebuild status with error after rebuild
(8)Verify pool and rebuild info after rebuild
modified: no_cap.py
modified: no_cap.yaml
Test-tag: pr no_cap
> DAOS-8846-test_rel2.0: Cherry pick from master(PR-7303).

- src/tests/ftest/rebuild/container_create_race.py
- src/tests/ftest/rebuild/container_create_race.yaml
Cherry-pick from Master PR-7173
Description: Update test for rebuild container race condition.
Test steps:
(1)Start IOR before rebuild.
(2)Starting rebuild by killing rank.
(3)Wait for rebuild to start.
(4)Race condition, create containers, data write/read during
rebuild.
(5)Wait for rebuild to finish.
(6)Check for pool and rebuild info after rebuild.
modified: container_create_race.py
modified: container_create_race.yaml
Test-tag: pr rebuild_cont_create
> DAOS-8741-test_2.0: Cherry-pick PR-7173 fix script issue on rebuild/container_create_racetest failures

- ci/rpm/test_daos_node.sh
Enusring the daos_agent has completely started before running daos_test
in the test_daos_node.sh script.
Skip-test-leap-15-rpms: true
> DAOS-8986 tests: Fixing test_daos_node.sh timing issue (#7235)

- src/tests/ftest/control/dmg_telemetry_io_latency.py
- src/tests/ftest/control/dmg_telemetry_io_latency.yaml
Verify the io dtx committed and committable metrics
Verify the io latency fetch and update metrics
> DAOS-8624 test: Verify io telemetry metrics (#6926)

- src/tests/ftest/container/snapshot.py
- src/tests/ftest/container/snapshot.yaml
Description: Update snapshot data size and snapshot number for EC test.
modified:   snapshot.py
modified:   snapshot.yaml
Test-tag: pr snapshots
> DAOS-8508-test2: Fix script and add test case for EC Snapshots

- ci/provisioning/post_provision_config_common.sh
- ci/provisioning/post_provision_config_nodes_EL_7.sh
- ci/provisioning/post_provision_config_nodes_EL_8.sh
- site_scons/env_modules.py
- src/tests/ftest/harness/basic.py
- src/tests/ftest/scripts/setup_nodes.sh
- src/tests/ftest/util/daos_core_base.py
- src/tests/ftest/util/general_utils.py
Support needed for testing with EL8 on hardware clusters.
> CORCI-1081 ci: Move default EL7 testing to EL8

- utils/grafana/DAOS-Grafana-Dashboard.json
Looks like when Exemplars is True it does not display the Graph at all.
Changing the exemplar option from true to false.
Doc-only: true
> DAOS-9069 Grafana: Removed the exemplar option for graphs.

- utils/config/daos_server.yml
clarify "immutable after reformat" in daos_server.yml
Doc-only: true
> DAOS-5579 (doc): daos_server.yml clarification

- src/rsvc/srv_common.c
> DAOS-9158 bulk: Fix leaking bulk

- src/tests/ftest/control/daos_object_query.py
Description: Update DAOS object enumeration class with recent changed per discussion with Mohamad and ShiLong.
modified: control/daos_object_query.py
Test-tag: daos_object_query
> DAOS-9125-test2: Update test for the recent DAOS object enumeration class changed

- src/cart/crt_iv.c
- Fix error case handling in case of mem alloc failure in pre-sync cb
> DAOS-9068 iv: Fix error case handling

- Jenkinsfile
Just testing a system-pipeline-lib branch
> DO NOT LAND

- src/cart/crt_context.c
- src/cart/crt_corpc.c
- src/cart/crt_hg.c
- src/cart/crt_internal.h
- src/include/cart/api.h
- src/include/daos/common.h
- src/rebuild/rebuild_iv.c
As requested, quiet common -DER_GRPVER ERRs to DBUGs.
> DAOS-9138 cart: Quiet -DER_GRPVER ERR messages (#7467)

- docs/admin/administration.md
- docs/admin/installation.md
- docs/admin/pool_operations.md
- docs/admin/predeployment_check.md
- docs/index.md
- docs/overview/fault.md
- docs/user/container.md
- mkdocs.yml
- rework the extension section to seperate system & pool extension
- add RAS event example
- remove old text from admin guide about unsupported features
- add new sections for the redundancy factor and cell size
- fix several nits
doc-only: true
> DAOS-7174 doc: various user and admin guide updates

- docs/admin/administration.md
- docs/admin/installation.md
- docs/admin/pool_operations.md
- docs/admin/predeployment_check.md
- docs/overview/fault.md
- docs/user/container.md
- mkdocs.yml
- rework the extension section to seperate system & pool extension
- add RAS event example
- remove old text from admin guide about unsupported features
- add new sections for the redundancy factor and cell size
- fix several nits
doc-only: true
> DAOS-7174 doc: various user and admin guide updates (#7599)

- utils/build.config
- Update build.config to include DAOS-9173 ofi patch
> DAOS-9173 build: Update build.config

- docs/release/upgrading_to_v2_0.md
- mkdocs.yml
add "Upgrading to DAOS Version 2.0" document
Doc-only: true
> DAOS-5579 doc: add "upgrading to daos 2.0" doc

- src/tests/ftest/cart/ghost_rank_rpc/one_node.yaml
- src/tests/ftest/cart/ghost_rank_rpc/one_node.ypy
- src/tests/ftest/cart/test_rpc_to_ghost_rank.c
This reverts commit bd66b172e5350af8c1a69e5a35308c0219979016.
> Revert "CART-986: Fix ghost_rank file extension and test (#7141)"

- src/cart/crt_iv.c
- src/container/srv_container.c
- src/container/srv_target.c
- src/engine/server_iv.c
- src/include/cart/iv.h
- src/include/daos_srv/container.h
- src/include/daos_srv/daos_engine.h
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
- src/pool/srv_target.c
- src/rebuild/srv.c
- src/vos/evtree.c
- src/vos/tests/evt_ctl.c
- src/vos/tests/vts_io.c
- src/vos/vos_aggregate.c
- src/vos/vos_obj.h
- src/vos/vos_obj_cache.c
Master PR #7637 
Master PR #7463
> DAOS-9195 vos: Prevent multiple range discard on same object

- docs/release/support_matrix_v2_0.md
updated support documentation with details on:
* community support and commercial support
* supported hardware
* supported operating systems
* fabric support
* scaling targets and scaling tests
Doc-only: true
> DAOS-5579 doc: update support matrix for DAOS 2.0

- src/tests/ftest/server/metadata.py
Supplemental fix for previous server/metadata.py
test_metadata_server_restart test case where unique temporary base
directories for each orterun command where based on the previous unique
temporary directory that no longer existed when the next ior command was
issued.
Test-tag: metadata_ior offline_extend_oclass
> DAOS-8655 test: Fix mpi tmpdir_base assignment in threads. (#7614)

- src/cart/crt_iv.c
- src/container/srv_container.c
- src/engine/server_iv.c
- src/include/cart/iv.h
- src/include/daos_srv/daos_engine.h
- src/object/srv_obj_migrate.c
- src/pool/srv_target.c
- src/rebuild/srv.c
> DAOS-9515: revert PR-7463

- src/tests/ftest/util/daos_utils.py
Doc-only: true
fix container_query docstring
> DAOS-623 test: fix container_query docstring

- Jenkinsfile
Use the CI_*_LABEL values specified in the build parameters.
> DAOS-623 tests: Support overriding CI_*_LABEL values

- docs/user/mpi-io.md
update MPICH, Intel MPI, and libfabric information for 2.0
> DAOS-5579 (doc): update MPI information

- docs/testing/ior.md
Clarify IOR usage, including the use of API=DFS
> DAOS-9210 doc: clarify IOR usage in QSG/testing

- src/tests/ftest/osa/offline_reintegration.py
> DAOS-9313 tests: skip osa_offline_reintegration_server_stop

- docs/release/support_matrix_v2_0.md
A blank line is required before each bullet list.
Doc-only: true
> DAOS-7174 doc: add blank line before bullets

- docs/admin/deployment.md
- utils/config/daos_agent.yml
fix fabric_ifaces: syntax in daos_agent.yml
Doc-only: true
> DAOS-9186 doc: fix fabric_ifaces: syntax in daos_agent.yml

- docs/admin/hardware.md
> DAOS-7509 documentation: Update DAOS HW documentation

- docs/QSG/setup_centos.md
- docs/QSG/setup_suse.md
- docs/admin/administration.md
Document the dmg system erase command
Change dmg storage format --reformat to --force
Doc-only: true
> DAOS-9323 (doc): Document dmg system erase

- docs/QSG/setup_centos.md
- docs/QSG/suse_setup.md
- docs/admin/administration.md
Document the dmg system erase command
Change dmg storage format --reformat to --force
Doc-only: true
Signed-off-by: Michael Hennecke michael.hennecke@intel.com
>  DAOS-9323 (doc): Document dmg system erase

- docs/admin/hardware.md
- docs/release/release_notes_v2_0.md
Release Notes with log4j onfo and line ending updates for HW.md
> DAOS-9362 7509 documentation: Update for log4j and HW

- ci/doc_only_change.sh
Add some error checking and failsafe if there are any errors.
> DAOS-623 ci: Update auto-doc-only detection
