src/object/cli_obj.c
src/vos/tests/vts_mvcc.c

Modifies the mvcc test to use the d_errstr version of the error
code rather than the numeric code for easier reading
Also fix an unrelated spelling error

DAOS-623 test: Use d_errstr rather than numeric code in output

---

src/control/server/mgmt_system_test.go

There was a very small window during which the raft state
could be leader while the leader address was unset, causing
intermittent failures in this test. Updating the test to
wait for the leader address to be set should eliminate the
race.

DAOS-6183 control: Fix race in MgmtSvc.LeaderQuery test

---

src/bio/bio_device.c
src/mgmt/srv_query.c

- Don't try to get traddr for unplugged device.
- Fixed device/pool list drpc handler to avoid free "empty string"
on error cleanup.

DAOS-6176 bio: don't get traddr for unpluged device

---

src/tests/ftest/datamover/copy_procs.py
src/tests/suite/daos_oid_alloc.c

Disabling the daos_test OID test due to DAOS-5999.
Disabling the datamover/copy_procs.py test due to DAOS-6194.

DAOS-5999 tests: Disabling tests failing in CI.

---

src/object/obj_internal.h
src/object/srv_obj_migrate.c

Since duplicating write with the same epoch might cause some
trouble for VOS, so let's remember all migrated objects in a
separated migrated tree to avoid the objects being migrated
multiple times.
We used to have this in the old rebuild code, but got removed
when separating the migration with rebuild.

DAOS-6133 rebuild: store migrated objects into migrated tree

---

src/container/cli.c
src/vos/tests/vts_mvcc.c

This patch fixes a few issue found by Coverity:
- cont_query_bits misses a break in the DAOS_PROP_CO_DEDUP_THRESHOLD
case.
- Assert the implicit size relation in vts_mvcc's
uncertainty_check_exec_one, hopefully silent Coverity next time.

DAOS-5731 misc: Fix Coverity issues

---

src/tests/ftest/pool/create_test.py

There are two intermittent pool/create_test.py issues:
- creating a pool across 5 of 6 ranks after an expected failed attempt
to create the same pool using all 6 ranks as a pool already exists on
the first rank (DAOS-6174)
- destroying pools after creating 100 and rebooting the
daos_io_servers (DAOS-6200)
These two test variants are being skipped until they have been
resolved.

DAOS-6200 tests: Skipping variants 3 & 5 from pool/create_test.py

---

doc/admin/deployment.md

Describe the cache and what disabling it means, as well as
documenting the procedure.

DAOS-6217 doc: Add instructions for disabling daos_agent cache

---

src/object/srv_obj_migrate.c
src/tests/suite/daos_rebuild.c

Currently rebuild only wait for local dtx resync, so
if the dtx resync does not finish on the remote node
(especially for new dtx leader), then the enumeration
might return -EINPROGRESS, instead of returning
failure, migration should retry to the leader until
dtx resync is finished.

DAOS-6216 rebuild: retry EINPROGRESS for migration

---

src/pool/srv_target.c

When pool_alloc_ref encounters certain errors, the ABT_cond_free call
under err_done_cond throws away the error and report its own return
value, which is likely 0, instead. This has led to segfaults in
daos_lru_ref_hold, which sees the 0 return value, believes the entry has
been allocated successfully, and dereferences the NULL entry pointer. It
is a regression introduced by #3672. This patch guesses that #3672
intends to check the return value of the crt_group_secondary_destroy
call instead, and employ a temporary variable to store its return value.

DAOS-6204 pool: Fix pool_alloc_ref error reporting

---

doc/overview/security.md

Add information in the Security Overview doc about how
DAOS doesn't secure the data plane communications. This
includes a hint about how an ethernet fabric can be
configured for security.

DAOSSDE-64 doc: Add data plane network security info

---

.travis.yml

The java .xom file wants it in dev.   We should automate this but
this should fix the immediate issue.

DAOS-623 build: Use BUILD_TYPE=dev for travis build

---

src/iosrv/init.c

Added parenthesis to address Coverity error
that operands do not affect the result.

DAOS-6244 IO Server: Coverity 275736

---

utils/docker/Dockerfile.leap.15

Use chown workaround to change ownership of /var/run/daos_server
and /var/run/daos_agent.

DAOS-4240 leap: add chown hack to docker file

---

src/tests/ftest/util/server_utils.py

The previous timeout of 20s was right on the edge of
startup timing variability, causing a number of spurious
intermittent failures.

DAOS-6245 test: Increase server startup timeout

---

src/bio/bio_context.c
src/tests/ftest/pool/create_test.py

When SSD is shared by multiple xstreams, the sync blob open/close
completion could be executed on different xstream, so caller may
change/free the completion argument while completion is running.
This patch uses saved 'async' arg to avoid above race, re-enables
the test case was originally disabled for this defect.

DAOS-6200 bio: race in sync blob open/close

---

src/bio/bio_xstream.c
src/common/dts.c
src/tests/daos_perf.c

Fixes to daos_perf to ensure it works with multiprocess mode.
This is for SCM-only mode and added for simulating multiple targets.
Create SMD only when nvme is used.
Signed-off-by: Vishwanath Venkatesan <vishwanath.venkatesan@intel.com>

DAOS-1364 tests: Multi-process vos_perf with SCM

---

src/container/container_iv.c
src/container/srv_container.c
src/container/srv_internal.h
src/container/srv_target.c
src/include/daos_srv/container.h
src/include/daos_srv/iv.h
src/include/daos_srv/pool.h
src/object/cli_shard.c
src/pool/srv_target.c

To coordinate EC aggregation and vos aggregation,
VOS aggregation can not aggregate the extent
which has not been processed by EC aggregation yet.
During EC aggregation, each server report
its current EC aggregation epoch to the leader,
and the leader will chose the minum epoch, then
broadcast (by IV sync) it to all servers, who
will use it as the VOS aggregation epoch bondary.

DAOS-6021 container: EC aggregation IV

---

src/cart/crt_corpc.c
src/cart/crt_hg.c
src/cart/crt_hg_proc.c
src/cart/crt_hlc.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/include/cart/api.h
src/tests/ftest/cart/utest/utest_hlc.c

- Instead of returning errors directly to mercury during unpack we
now save error as part of rpc_priv field and fail gracefully
- Upon this failure application will now get -DER_HLC_SYNC error.
- crt_hlc_get_msg() expanded to include optional 'drift' output
parameter that will be set only for cases when -DER_HLC_SYNC is
generated

CART-927 hlc: Improve log messages on HLC failures

---

src/include/daos_task.h

Users using the task API should be able to set the uuid in the struct
for operations that take them as input parameters (pool/container
create, destroy, etc.). This is different than an API call where
the uuid is passed vs being set in a struct which will cause warnings
in the user code.

DAOS-2666 task: the task struct should not use const for uuids

---

src/vos/README.md

This patch updates the MVCC rules section in src/vos/README.md:
- We now use server HLCs to choose epochs.
- We now employ exponential backoffs with randomizations to reduce
starvations.

DAOS-623 vos: Update MVCC rules section

---

src/mgmt/cli_mgmt.c
src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Client function dc_mgmt_get_pool_svc_ranks() selects sy_psrs[0] from
struct dc_mgmt_sys returned by get_attach_info() to identify the
"management service" ioserver to send MGMT_POOL_GET_SVCRANKS rpc.
This is done when a client needs to discover the list of pool
service replica ranks.
Recent changes have populated sy_psrs[] with multiple servers,
e.g., referring to two ioservers deployed on a single MS replica
host. Some tests e.g., rebuild will stop some ranks and it has
been shown that in some cases the rank associated with sy_psrs[0]
in the test client is the one affected. This causes the client
to time out or get a DER_UNREACH error when trying to fetch
the pool service ranks.
This change iterates through sy_psrs[] attempting to fetch
the pool service ranks.
Signed-off-by: Kenneth Cain …

DAOS-6187 mgmt: client iterate sy_psrs[] for get svcranks rpc

---

src/object/cli_ec.c
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_internal.h
src/object/srv_obj_migrate.c

Add orr_size_set to indicate if the iod_size has been
set by fetch shard reply, and only update size if
iod_size is not being set or iod_size is still 0.

DAOS-6149 EC: set iod_size by reply size for EC object

---

.travis.yml

Switch to Focal Fossa (20.04) as baseline distribution
instead of Xenial (16.04) for travis build.

DAOS-4093 travis: use 20.04 as baseline distrib

---

src/tests/ftest/datamover/copy_procs.py
src/tests/ftest/datamover/copy_procs.yaml

Moved the copy_procs test to hw small to avoid timeout,
since the VM nodes do not have enough cores allocated.

DAOS-6194 test: Move copy_procs to hw small

---

src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Disable daoscoretest rebuild r26 due to DAOS-5852

DAOS-5852 test: Disable daoscoretest rebuild r26

---

src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_rpc.h
src/object/srv_obj.c

Originally csum report is done by retry the IO task, that complicate the
retry logic and target selection details.
This patch simplify it by send another RPC to same shard target when
gets csum error for that shard.

DAOS-4898 obj: simplify csum report handling

---

src/tests/ftest/cart/tests_common.h

- Remove sleep(2) from tc_wait_for_ranks, which was originally added
as a workaround to 'stabilize' endpoints. This stabilization was
required before when early RPC pings were causing server to become
unresponsive later on.

CART-89 fix: Remove sleep from tc_wait_for_ranks

---

src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Re-enable rebuild 0-10 after fixing related bugs via PR#3838.

DAOS-6249 tests: enable rebuild 0-10

---

src/tests/ftest/io/daos_vol.py
src/tests/ftest/io/daos_vol.yaml
src/tests/ftest/io/ior_small.yaml

This PR  enables the hdf5 vol daos unit test and
skip any tests that have open tickets.  This PR will also
enable ior -HDF5-VOL in ior_small

DAOS-5647 test: skip for ticket daos vol unit tests

---

src/cart/crt_swim.c
src/cart/utils/fault-inject-cart.yaml
src/gurt/fault_inject.c
src/include/gurt/fault_inject.h

Add fault injection into SWIM to test the time of failure detection.
To enable this functionality you should set the following YAML file
in D_FI_CONFIG environment.
```
fault_config:
- id:            65025
interval:      0
max_faults:    0
probability_x: 1
probability_y: 0
err_code:      0
argument:     "rank=1,delay=10"
```

DAOS-6077 swim: fault injection into SWIM

---

src/control/server/ctl_system.go
src/control/server/ctl_system_test.go
src/control/server/harness_test.go
src/control/server/mgmt_pool_test.go
src/control/server/test_utils.go
src/control/system/member.go
src/control/system/member_test.go
src/control/system/mocks.go

Prevent unit tests from attempting to resolve TCP addresses on the
running host as test outcomes are then dependent on the network of
the test host. Unit tests should not be calling the real TCP resolver
so apply the relevant mocking. Also DRY-up ctlsvc tests.

DAOS-6063 control: mock tcp resolver in unit tests

---

src/tests/ftest/launch.py

In the clean up of the core file after a failed debuginfo installation,
the removal command was not using the path to the core file when trying
to  remove it resulting in an ENOENT.

DAOS-6345 test: Use path when removing core files

---

src/tests/ftest/launch.py

I am not sure why we are getting 0 byte core files, so we probably need
to gather more data when it happens, so make it an error when they are
empty.

DAOS-6331 test: Flag as an error if core file is 0 bytes long

---

src/include/daos/debug.h
src/object/cli_ec.c
src/pool/srv_internal.h
src/pool/srv_pool.c
src/pool/srv_util.c
src/rebuild/srv.c
src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

1. Use target version as the rebuild version, instead of
pool map version, which might be updated when the node
status changes as well, because only the target status
changes needs to retrigger rebuild/reintegration.
2. let's abort the local target rebuild status ULT if it
return ENOTLEADER, otherwise it will become the orphan
ULT, which will block the pool destory.

DAOS-6318 rebuild: use target version as rebuild version

---

src/control/cmd/daos_agent/main.go
src/control/common/net_utils.go
src/control/common/net_utils_test.go
src/control/lib/control/hostlist.go
src/control/lib/control/hostlist_test.go
src/control/server/config/server.go
src/control/server/config/server_test.go

Dedupe and normalize before further validation in order
to ensure that the access_points list contains a set of
distinct and valid entries.

DAOS-6225 control: Parse server access_points as hostlist

---

src/pool/srv_target.c

ds_pool_child refernce count should decrease to 1
until all container child are stopped.

DAOS-3885 pool: check spc_ref correctly during purge

---

src/tests/suite/daos_degrade_ec.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_rebuild_ec.c
src/tests/suite/daos_rebuild_simple.c
src/tests/suite/daos_test.h

1. Upgrade DAOS EC rebuild tests to include DFS tests.
2. Kill more nodes after rebuild ec to verify parity rebuild.

DAOS-6347 tests: Upgrade DAOS EC rebuild tests

---

doc/admin/installation.md
utils/docker/Dockerfile.centos.7
utils/docker/Dockerfile.leap.15
utils/docker/Dockerfile.ubuntu.20.04

Change prefix from /usr/local to /opt/daos to fix
build issue with rpath not being set.
Update documentation to skip submodule init/update.

DAOS-4240 docker: move to /opt/daos

---

src/container/srv_target.c

Previously this function was logging raw memory with %s which was
leading to errors in the log file and potential crashes.

DAOS-5925 logging: Correct usage of DF_UUID/DP_UUID in srv_target.c

---

src/cart/crt_swim.c

- In one of cases rpc_priv could be set to null before being accessed

CART-934 fix: rpc_priv could be set to null and accessed on error

---

src/container/srv_target.c
src/pool/srv_pool.c
src/pool/srv_util.c
src/tests/suite/daos_degraded.c
src/tests/suite/daos_nvme_recovery.c
src/tests/suite/daos_test_common.c
src/vos/vos_container.c

There were cases where DP_UUID wasn't used, resulting in invalid
data being written to the log file which was causing test errors
but on inspection there were also a number of places where
DF_UUID wasn't being used correctly either so fix those.
This fixes at least one logging error which was causing test failures
and could have caused a crash, and it resolves a number of places
where incorrect data would have been logged.

DAOS-5925 logging: Correct usage of DF_UUID/DP_UUID.

---

src/common/dts.c
src/include/daos/dts.h
src/tests/daos_perf.c

This patch includes a few changes:
- daos_perf has too many parameters, it is unrealistic to add
a new opcode for a new test type. This patch add a generic
opcode '-R', all tests are just parameter for this opcode.
Example:
Run UPDATE test with performance output, and run FETCH
test with performance output as well, then verify data
correctness without performance output, the parameter
should be like:
$ daos_perf ... -C 16 -A -R 'U;p F;p V'
'U' means UPDATE, 'p' means outputing performance
'F' means FETCH 'p' means outputing performance
'V' means verify correctness of data
- UPDATE, FETCH, VERIFY can support (partial) overwrite
$ daos_perf -s 1024k -A -R "U U;o=4k;s=4k V"
"U" writes 1024K data
"U;o=4k;s=4k" overwrites from 4K-8K of the first write
"V" verify correctness of two writes
- …

DAOS-5906 test: daos_perf improvements

---

src/common/compression.c
src/common/compression_isal.c
src/common/compression_qat.c
src/common/qat.c
src/common/tests/SConscript
src/include/daos/compression.h
src/include/daos/qat.h

* Support function "daos_compressor_(de)compress_async",
user doesn't need to wait for completion, the post-processing
work can be done in the registered callback function.
* The synchronous QAT function "qat_dc_compress" relies on
"qat_dc_compress_async" now, the sync function polls response
in the current context.
* The compress_timing test will be added in the next PR to support
test cases for asynchronous functions.
Signed-off-by: Weigang Li <weigang.li@intel.com>

DAOS-5719 compression: add qat asynchronous support

---

src/client/pydaos/raw/daos_cref.py
src/common/cont_props.c
src/container/cli.c
src/container/srv_container.c
src/container/srv_layout.c
src/include/daos/cont_props.h
src/include/daos/container.h
src/include/daos_cont.h
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_class.c
src/object/obj_internal.h
src/object/obj_tx.c
src/tests/suite/daos_rebuild_common.c
src/utils/daos_hdlr.c

Only allow to obj open when #replicas > container_rf (for EC, it is
p >= container_rf).
Set the default container rf as zero, to allow to create/open
non-replica obj (such as OC_SX).
Refine/reduce daos_oclass_attr_find/daos_oclass_is_ec() callings by
cache+reuse obj oca.

DAOS-4882 obj: check container rf when obj open

---

src/tests/ftest/pool/create_test.py

PR-3997 landed the main fix for pool create failing with DER_TIMEDOUT
followed by DER_EXIST. There might be some intricate race/timing
questions to study at the ioserver target level. However, given the
nature of the fix in PR-3997 (pool create retries occurring only
after RPC reply with error), it makes sense to re-enable this test
at this time.

DAOS-6174: re-enable pool create_test

---

src/dtx/dtx_common.c
src/include/daos_srv/dtx_srv.h
src/object/srv_obj.c
src/rebuild/scan.c
src/vos/tests/vts_dtx.c
src/vos/vos_dtx.c
src/vos/vos_internal.h
src/vos/vos_iterator.c

After DTX resync, rebuild logic will scan locally to find out which
objects need to be rebuilt on new target. At that time, if hit some
uncommitted DTX, then such DTX leader will be on other DAOS target.
Under such case, we will not return -DER_INPROGRESS to the rebuild
logic, instead, skip related object that will be handled by related
rebuild scan on the DAOS target that the DTX leader resides on.

DAOS-6310 rebuild: skip uncommitted DTX for rebuild scan

---

src/container/srv_target.c
src/include/daos_srv/vos_types.h
src/vos/vos_aggregate.c
src/vos/vos_iterator.c

VOS_ITER_CB_ABORT flag is introduced, it'll be used by iteration
callbacks to inform the recursive VOS iterator to abort current
level iteration.
vos_aggregate() used to abort the whole container aggregation
once hitting a checksum error on an evtree, now it relies on the
VOS_ITER_CB_ABORT to abort current evtree aggregation only.
Small fixes in vos_iterate_internal().

DAOS-6315 vos: VOS_ITER_CB_ABORT flag for VOS iteration

---

src/client/dfuse/ops/create.c
src/client/dfuse/ops/symlink.c
utils/node_local_test.py

This means that the inode always has write permissions, even if the
open file derived from it may not, and it fixes a bug where files
were created or opened in read-only mode.
Mkdir also needs updating however I have another fix for mkdir in review
so I will add that change there.

DAOS-6238 dfuse: Ensure inode object is opened with O_RDRW.

---

src/vos/tests/vts_io.c

Cleanup skipped tests for VOS by removing this oft repeated
test that checks a feature we haven't implemented and probably
need to redesign anyway (to add more server side enumeration
conditions).

DAOS-6313 vos: Remove vos akey condition test

---

src/cart/crt_context.c
src/cart/crt_internal.h
src/cart/crt_rpc.c
src/cart/crt_rpc.h

- During timeout detection add timeout value to the error log
- crt_opc_to_str() added to print string version of internal opcodes
- RPC_ERROR modified to make use of crt_opc_to_str()

CART-89 logging: Add timeout and opcode logging

---

ci/patch_src_in_place
src/gurt/fault_inject.c
src/include/daos/debug.h

Rather than test the entire tree, only check files that are
touched by the PR.
Fix spelling mistake.

DAOS-6261 ci: Improve checkpatch to only inspect modified files.

---

Jenkinsfile

Add mpifileutils-mpich-daos-0 to the list of functional rpms.

DAOS-6257 test: Add mpifileutils-mpich-daos-0 to rpms

---

src/cart/swim/swim.c

The information about bootstrap complete is spread during the
long time and affect tests which simulate node failure immediately
after start. To avoid this just limit initial piggyback messages
with bootstrap complete information.

DAOS-6124 swim: limiting information about bootstrap complete

---

src/control/cmd/daos_agent/main.go
src/control/cmd/daos_server/main.go
src/control/cmd/dmg/main.go

The go-flags package builds the help message in an error which
was printed in the exitWithError() helper, but this is potentially
confusing because it would result in the utilities exiting with 1
instead of 0. Just inspect the error returned from parseOpts() and
only pass it to exitWithError() if it's actually an error.

DAOS-6396 control: CLI utils should exit 0 after --help

---

src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Re-enable rebuild tests 0-10  after the fix PR-3838
is landed.

DAOS-5851 tests: re-enable rebuild test

---

src/tests/ftest/cart/test_group_np_cli.c

- If multiple contexts are specified, test was not waiting for
individual check_in() operations to complete before starting next
one. This resulted in RPC handles being incorrectly re-used.

CART-89 test: Fix issue with test

---

src/common/btree_class.c
src/include/daos/btree.h
src/iosrv/init.c
src/object/srv_obj_migrate.c
src/rebuild/scan.c
src/vos/vos_internal.h
src/vos/vos_tree.c

Use DBTREE_CLASS_UV tree class for rebuild container
tree.

DAOS-6149 rebuild: use UV tree for container tree

---

utils/node_local_test.py

There are occasionally small races between the time that the
control plane reports an instance as Joined and the time that
the instance is actually ready to process a pool create request.
This commit adds some retry logic to make_pool() in order to
handle retrying on create failure. Also increases the maximum
allowed time for system startup, and refactors some common
logic into helper methods.

DAOS-3885 test: Make NLT more resilient

---

src/vos/tests/vts_aggregate.c
src/vos/tests/vts_gc.c
src/vos/tests/vts_io.c
src/vos/tests/vts_pm.c
utils/test_memcheck.supp

Fixes a memory leak in vos IO test
Adds a few instances of DAOS_ON_VALGRIND to speed up valgrind runs
Fix a suppression for gc when run standalone

DAOS-623 vos: Fix a memory leak

---

.github/workflows/ci.yml
utils/docker/Dockerfile.centos.7
utils/docker/Dockerfile.leap.15
utils/docker/Dockerfile.ubuntu.20.04

Add new COMPILER ARG to the docker files to be able to
select compiler.
Modify GH action to build with both gcc and clang.

DAOS-4093 docker: add ability to select compiler

---

ci/unit/test_main_node.sh
src/common/tests/btree.sh
src/vos/tests/evt_ctl.sh
utils/run_test.sh

Store UT Valgrind XMLs in current directory instead of test_results
When there is a failure on the CI UT with memcheck stage, test_main_node.sh
exists because it has set -e. This prevents this script from moving the
Valgrind XMLs to current directory where pipeline-lib scripts can find them
and archive them for later debug of the memory leaks.
In practice, it is not necessary to have those Valgrind XMLs in test_results
and then move them. We can reduce this step and overcome this issue by
directly keeping those files in the current directory.

DAOS-6425: Store UT Valgrind XMLs in current directory

---

src/control/lib/control/rpc.go
src/control/lib/control/rpc_test.go
src/control/system/errors.go

Missed this case in the client rework. When sending a request
to a MS replica that is starting up, it's valid to retry after
receiving an error indicating that raft is not available (yet).

DAOS-6409 control: Add retry case for starting MS

---

Jenkinsfile

DAOS-623 ci: Reduce master job retention

---

src/control/system/rank.go

The system.RanksToUint32() and system.RanksFromUint32() helpers
were using convert.Types() under the hood, but it's simple
enough and much more efficient to just do the conversion directly.

DAOS-4447 control: Convert to/from []Rank more efficiently

---

utils/docker/Dockerfile.leap.15

Same as DAOS-6053.  which downloads dependencies from google repo instead of maven central repo for centos and ubuntu, we need to do the same switch for Leap 15 too.

DAOS-6463 enhance stability of Java build in Leap 15

---

src/object/obj_tx.c

It is known that the dc_tx_convert() caller will not reuse
or release related data buffer before related DTX committed.
So it is unnecessary to copy data when convert standalong IO
to DAOS internal transaction.

DAOS-6177 object: zero copy for dc_tx_convert

---

src/cart/swim/swim.c

For ALIVE event we don't update the state for incurnation number
which is the same as currect. This should not be for inactive state.

CART-939 swim: update inactive state regardless version

---

src/tests/ftest/control/dmg_pool_query_test.py

Disabling cmd pool query basic test for DAOS-6452

DAOS-6452 test: Disable Dmg pool query basic test

---

utils/config/daos_server.yml

Added description and usage for the pinned_numa_node
server configuration option.

DAOS-6369 Control: Document pinned_numa_node in daos_server.yml

---

src/tests/daos_perf.c

If write size is not page aligned, daos_perf can overrun the
write buffer while initiazing. This patch can fix the overrun.

DAOS-5906 utils: buffer overrun of daos_perf

---

src/bio/bio_xstream.c
src/iosrv/init.c

Remove the default NVMe config path "/etc/daos_nvme.conf", this
default value is out of date now since control plane uses
"$storage_path/daos_nvme.conf" to start io server.
The wrong default value could cause io server start error when
NVMe isn't configured in server ymal but "/etc/daos_nvme.conf"
happen to be presented. (from prior daos_perf VOS mode runs).

DAOS-4398 bio: remove default NVMe config path

---

src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Use CANCEL_FOR_TICKET for rebuild 0-10
instead of comments in yaml
Py is already updated. This pr is just to remove the comments in yaml.

DAOS-6429 test: Use CANCEL_FOR_TICKET for rebuild 0-10

---

Jenkinsfile
ftest.sh

Using them as a directory name could result in an ENAMETOOLONG.
Move pre_clean call so that it's path is known when it's called.

DAOS-623 ci: Deal with long tag lists

---

src/tests/ftest/launch.py

The code to use gdb to find the executable that created a core file was
always expecting the executable to have arguments and failing to find
the executable name when it didn't have any.

DAOS-623 ci: Find executable name without arguments

---

src/control/cmd/dmg/pretty/pool.go
src/control/cmd/dmg/pretty/pool_test.go
src/control/server/mgmt_pool.go
src/control/server/mgmt_pool_test.go

The new pool create functionality didn't handle some edge
cases, and the response formatter wasn't correctly calculating
total pool size.

DAOS-6498 control: Fix some issues in pool create

---

src/dtx/dtx_common.c
src/dtx/dtx_cos.c

For resent modifcation, the DTX entry on the leader has existed,
current IO handler will not initialize dth->dth_dkey_hash under
such case, then cannot use it to add the DTX into the CoS cache.
Otherwise, such DTX entry in the CoS cannot be removed later as
to trigger assertion during dtx_flush_on_deregister().
On the other hand, sync committing DTX entry for resent IO also
avoid adding the DTX into CoS cache repeatedly.

DAOS-6499 dtx: sync commit DTX for resent modfication

---

src/tests/ftest/daos_test/daos_core_test.yaml

The daos_test -z suite has started intermittently failing due
to timeout in cleanup because the test run does not leave
enough time. Increasing the overall test timeout by 20s to
240s should alleviate this problem.

DAOS-6507 test: Increase timeout for checksum tests

---

utils/daos_build.py

This adds a definition on the command line that will cause scons to
recompile any code that was previously compiled with a different
mpicc so that one can change the mpi used without more drastic
clean of all daos binaries.

DAOS-623 build: Force recompilation of MPI when mpicc changes

---

src/tests/ftest/pool/multiple_creates_test.py
src/tests/ftest/security/cont_create_acl.py
src/tests/ftest/soak/soak_utils.py
src/tests/ftest/util/cont_security_test_base.py

Test-tag: pr,-hw createone createtwo createthree cont_create_acl
Test-tag-hw-large: pr,hw,large soak_smoke
The test was failing due to the change to TestPool and TestContainer utils that added
a fail_on decorator to the method.  The was done to simplify the try/except fail code in test cases.
But it impacted tests that need to catch the exception.   The few tests that where negatively impacted have 
been updated to catch "TestFail"

DAOS-6480 test: Re-enable Create Container ACL

---

src/control/system/faultdomain.go
src/control/system/faultdomain_test.go

- Stop allowing the separator to be part of a fault domain level
name. It should only be used to separate level names.
- Improve a couple error messages.
- When attempting to add a root domain to the FaultDomainTree,
it's a no-op, not an error.

DAOS-6473 control: Forbid "/" as fault domain level name

---

.gitignore
Jenkinsfile
ci/provisioning/post_provision_config_nodes_EL_7.sh
ci/provisioning/post_provision_config_nodes_LEAP_15.sh

Our repo is considerable more complicated than a repo a customer would
install from.  So much more complicated that YUM is unable to properly
resolve dependencies among duplicated packages.
To deal with this, use DNF on EL7.  DNF is much smarter than YUM at
resolving dependencies.

DAOS-623 ci: Use DNF on EL7

---

src/object/obj_tx.c

When do conditional modification inside some distributed transaction,
the DTX client logic will trigger a conditional fetch request firstly
before adding such conditional modification reqeust into client side
cache, then according to the conditional fetch result (exist or not)
to decide whehter cache such conditional modification request or not.
So when triggers dc_tx_commit, it has checked related conditions, it
is NOT necessary to re-check the conditions on server when commit.

DAOS-6474 dtx: no condition ops when commit distributed transaction

---

utils/systemd/daos_agent.service
utils/systemd/daos_server.service

If something prevents daos_server or daos_agent from restarting it will
immediately try to restart indefinitely causing a restart storm in the logs.

DAOS-6394 Systemd: Systemd restarts DAOS too quickly on failure

---

src/control/cmd/daos_agent/mgmt_rpc.go

Reworked access to aic.defaultNumaNode so that it now
has mutex protection to avoid a data race between the
initResponseCache() that initializes it, and the
handleGetAttachInfo() that reads it.

DAOS-6045 Agent: Data race in agent attachInfoCache

---

src/tests/ftest/util/nvme_utils.py

Updated the raise derived from CommandFailure Baseclass instead
of string.

DAOS-5436 Test: Fix exception derived from CommandFailure Base class.

---

src/object/cli_mod.c
src/object/obj_class.c
src/object/obj_internal.h
src/object/srv_mod.c

The current object class is using linear search, it can have
performance problem because more and more object classes are
added.
This patch changes the search function and switches to binary
search.

DAOS-6485 object: object class binary search

---

utils/sl/components/__init__.py

Bump protobuf-gen-c version pulled in build from 1.3.0 to 1.3.3 to
align with what we expect developers to be using.

DAOS-6513 build: bump protobuf-gen-c version

---

src/gurt/fault_inject.c
src/gurt/misc.c
src/include/gurt/common.h
src/include/gurt/fault_inject.h
src/include/gurt/list.h

MPICH has its own memory trace capability.
So, fixed the DAOS romio plugin compilation.

DAOS-6251 gurt: fix compilation of MPICH romio plugin

---

src/dtx/dtx_rpc.c
src/object/srv_obj.c

For DTX logic, -DER_INPROGRESS means the server does not
know whether related DTX is committable/committed or not;
-DER_TX_RESTART means that related DTX need restart. They
are not fatal failure, so it is unnecessary to mark them
as error; otherwise it will misguide the user.
Similarly, -DER_NONEXIST for DTX RPC reply is normal case,
not some fatal failure,

DAOS-6476 dtx: avoid misguiding error message

---

src/tests/ftest/cart/corpc/cart_corpc_five_node.yaml
src/tests/ftest/cart/corpc/cart_corpc_one_node.yaml
src/tests/ftest/cart/corpc/cart_corpc_two_node.yaml
src/tests/ftest/cart/ctl/cart_ctl_five_node.yaml
src/tests/ftest/cart/ctl/cart_ctl_one_node.yaml
src/tests/ftest/cart/ghost_rank_rpc/cart_ghost_rank_prc_one_node.yaml
src/tests/ftest/cart/group_test/group_test.yaml
src/tests/ftest/cart/iv/cart_iv_one_node.yaml
src/tests/ftest/cart/iv/cart_iv_two_node.yaml
src/tests/ftest/cart/no_pmix/cart_nopmix_multictx_one_node.yaml
src/tests/ftest/cart/nopmix_launcher/cart_nopmix_launcher_one_node.yaml
src/tests/ftest/cart/rpc/cart_rpc_one_node.yaml
src/tests/ftest/cart/rpc/cart_rpc_two_node.yaml
src/tests/ftest/cart/selftest/cart_selftest_three_node.yaml

- Change log masks on cart tests to be ERR,RPC=DEBUG,HG=DEBUG in
order to reduce size of logs generated.

CART-89 logs: Change log mask to be less verbose on cart tests

---

src/vos/vos_layout.h

We've made several incompatible changes.  A misunderstanding of the
code here means we are assuming compatiblity with older versions
which is just wrong.   Set the lowest compatible version and
add comments to make it clearer.

DAOS-4888 vos: Fix lowest supported version

---

src/include/daos/tests_lib.h
src/vos/tests/vts_dtx.c
src/vos/tests/vts_gc.c
src/vos/tests/vts_ilog.c
src/vos/tests/vts_io.c
src/vos/tests/vts_pm.c
src/vos/tests/vts_pool.c
src/vos/tests/vts_ts.c

This macro converts the return codes to DAOS rc strings and compare
them, in order to have the rc logged as strings and not hexadecimal
number in case of an error.

DAOS-6334: Add assert_rc_equal macro

---

src/vos/vos_dtx.c

The dtx_leader_begin() may generate DTX entry in DRAM before any
real modification. The index for such DTX entry will not be set
until all related modifications are done locally. If the DTX is
aborted before that, the dtx_rec_release() that is triggered by
DTX abort logic will hit assertaion when check the index of DTX
entry, that is wrong, and should be removed.

DAOS-6440 vos: remove invalid DTX status check

---

SConstruct

Some platforms don't add the textfile tool which provides the Substfile
builder so add the tool explicitly when loading the scons environment.

DAOS-623 build: Add textfile tool for systems where it's not default

---

ci/unit/test_post_always.sh
utils/node_local_test.py

Use bz2 to compress log files that NLT generates.  Perform the
compress just after parsing them, so any errors that raise
assertions will mean individual log files aren't compressed which
should aid debugging in CI.
Update the pull script to copy them back to the build node.
This should save several hundred MB per build.

DAOS-6402 nlt: Compress NLT log files.

---

src/include/daos/tests_lib.h
src/tests/suite/daos_pool.c
src/tests/suite/daos_rebuild.c

DAOS-6334: use assert_rc_equal in daos_pool and daos_rebuild tests

---

src/tests/suite/daos_rebuild.c

Skip rank 0 for rebuild test 27 until the test is
configuring replicated MS.

DAOS-6564 tests: skip rank 0 in test_27

---

src/dtx/dtx_common.c
src/dtx/dtx_cos.c
src/include/daos_srv/container.h

If we destroy the CoS tree when the DTX batched commit ULT exits,
then because of ULT schedule race, some other ULTs may still try
to access the CoS, that may cause unexpected error. The solution
is that keep the CoS tree until related container is closed.

DAOS-6177 dtx: keep the CoS tree until container close

---

src/control/events/generic.go
src/control/events/generic_test.go
src/control/events/pubsub.go
src/control/events/pubsub_test.go
src/control/events/ras.go
src/control/events/ras_test.go
src/control/lib/control/system.go
src/control/server/mgmt_drpc_test.go
src/control/server/server.go

Events that are raised through the ds_notify_ras_event API exposed in
daos_srv/ras.h should be handled when received by daos_server over
dRPC. The events should be converted into generic RAS go event and
NOT forwarded to MS leader but published to local instance syslog
(for this ticket just log to INFO in control plane).

DAOS-6593 control: handle generic ras events received over drpc

---

src/utils/daos_hdlr.c

The "daos cont create" command with the --path option goes
through a different code path than without. The ACL file and
owner/group properties weren't being added on that second
code path.

DAOS-6529 tools: Add ACL in cont create with path

---

src/include/daos_api.h

Update the transaction API comments:
- Fix -DER_RESTARTs (should be -DER_TX_RESTARTs).
- Avoid unnecessary concepts (e.g., "persistent" versus volatile
snapshots).
- Avoid committing to client caching as an API promise. (But we could
explain it as a specific behavior of the current implementation, for
informational purposes instead of a promise.) Instead, specify
clearly that ZERO_COPY callers must keep data buffers until commit
operaionts complete.
- Avoid saying -DER_TX_RESTARTs are completely due to conflicts. This
is unnecessary and incorrect (e.g., some may be due to pool map
version mismatches).
Doc-only: true

DAOS-5022 api: Update TX API comments

---

src/tests/ftest/io/large_file_count.yaml

With resolution of DAOS-5841, the large_file_count test case
exercising objectclass RP_3GX can be re-enabled.
Test-tag-hw-large: largefilecount

DAOS-5911 test: enable RP_3GX large_file_count, DAOS-5841 fix

---

src/bio/SConscript
src/bio/bio_internal.h
src/bio/bio_xstream.c

Call spdk_subsystem_init() to initialize all registered subsystems
like 'bdev', 'vmd' and 'copy', that'll simplify the BIO SPDK
init/fini code, also register VMD hotplug poller properly.

DAOS-6281 bio: initialize VMD subsystem

---

src/include/daos_api.h

Follow up Jeff's review comment for #4377:
It may be better to just say that reads using that epoch may get
unexpected or undefined results.

DAOS-5022 api: Fix comments for daos_tx_open_snap

---

doc/admin/pool_operations.md

Add 'dmg pool set-prop' command description to explain how to control
aggregation strategy through modifying pool reclaim property.

DAOS-4241 doc: description of 'dmg pool set-prop'

---

src/object/cli_mod.c
src/object/srv_mod.c
src/placement/tests/pl_bench.c

The commit b19a56be66ce44efba35b28e50413f21b5917cc5 introduced
the memory loss during the error path in dc_obj_init().
Also pl_bench is crashing without prpopper obj_class_init().

DAOS-6485 object: Fix for object class init/fini

---

src/vos/vos_dtx.c
src/vos/vos_internal.h

To handle the race from DTX refresh, the leader will pre-create
the DTX entry in DRAM before dispatching related modifications.
If such pre-created DTX entry was found by the resent handling
logic before leader prepared related local modifications, then
it should not be regarded as 'prepared' locally; instead, under
such case, related RPC needs to be handled as a new RPC on the
leader, and then dtx_leader_begin will find former non-prepared
DTX entry (that is in processing), then reply "-DER_INPROGRESS"
to the client.

DAOS-6499 dtx: handle resent RPC properly

---

src/tests/suite/daos_oid_alloc.c

Since DAOS-6187 has been fixed, let's re-enable OID
subtest 3.

DAOS-5999 tests: re-enable OID subtest 3

---

.github/workflows/ci.yml

No need to check the git hooks, etc.
doc-only: true

DAOS-6589 test: Add .git to codespell skips

---

src/dtx/dtx_common.c
src/dtx/dtx_cos.c

There may be CPU yield during DTX commit. If we do not hold
reference on the DTX entry, some other may free it by race.

DAOS-6619 dtx: hold reference on DTX entry when commit

---

src/tests/ftest/cart/selftest/cart_selftest_three_node.py
src/tests/ftest/cart/test_group_np_srv.c

During cart_selftest_three_node run the same test runs twice - once in
sep mode and one in non-sep mode.
Previous patch caused all servers by default to delay their shutdown by 2
seconds. In this test test_group_np_srv servers are shutdown by client
sending an RPC to the server to which server responds right away and then
initiates a shutdown sequence.
Python self-test script executes clients in order for this test. Once it
executes client to perform shutdown it will then start another iteration of
the test with different SEP setting, while old servers are still up (due to
2 second default delay on shutdown). This then causes servers to clash,
occasionally causing problems with new servers not being able to connect.

CART-943 bug: Fix thee node cart self test

---

src/common/checksum.c
src/object/obj_tx.c

There is race when multiple tasks calculate checksum. It appeares
that the tasks may stomp on each others checksum buffer, and then
send the incorrect checksum to the server. Creating a copy of the
csummer on the client for calculating checksums to the issue.

DAOS-6475 dtx: distinct csummer for checksum calculations

---

src/control/events/pubsub.go
src/control/events/pubsub_test.go

Make the process of updating the filters which determine which events
get published thread safe. There is a potential data race because
multiple go-routines could update the ID filter map concurrently.

DAOS-6614 control: fix data race when updating event filter

---

src/object/srv_obj.c

Check 'ioh' validness before calling vos_dedup_sgl_fini(), the 'ioh'
could be invalid in some error cases.

DAOS-6562 iosrv: check ioh validness

---

src/client/dfuse/SConscript
utils/docker/Dockerfile.centos.8
utils/sl/fake_scons/SCons/Script/__init__.py

For some reason CentOS 8 has an older version of libfuse than
CentOS 7, so add a compile check to know which ioctl prototype
we need to use.
Newer versions of libfuse have a define you can use for this
however neither CentOS 7 or 8 have this.

DAOS-6582 dfuse: Add configure check for ioctl type in libfuse.

---

utils/sl/prereq_tools/base.py

SCons was printing a message for calls to os.makedirs that
threw an exception because the directories already exist.
Rather than throwing and catching an exception, instead
first check for existence.   And only throw an exception if
the directory cannot be made.
Also, consolidate this code into a single function
Modifies creation of prereq_prefix until it's actually needed

DAOS-623 build: Remove spurious message and unify makedirs

---

src/tests/ftest/io/romio.yaml
src/tests/ftest/util/mpio_utils.py

The CI functional test for romio is unsetting env. this will cause the test to fail. CI however was not reporting that failure due to a different bug. this patch just fixes the failure.
Test-tag: romio

DAOS-6599 test: env is not set for romio test

---

src/control/events/generic.go
src/control/events/generic_test.go
src/control/events/psr_update.go
src/control/events/pubsub.go
src/control/events/rank_down.go
src/control/events/ras.go
src/control/server/mgmt_system.go
src/include/daos_srv/ras.h
src/iosrv/drpc_ras.c
src/rebuild/SConscript
src/rebuild/ras.c
src/rebuild/rebuild_internal.h
src/rebuild/srv.c

Add RAS events to mark when pool rebuild operations
start, finish, and fail.
Also cleans up the events package API and removes some
overly-chatty debug messages.

DAOS-6595 rebuild: Add RAS events for Pool rebuild

---

src/gurt/dlog.c

Signed-off-by: Steven Bollinger <stevenx.bollinger@intel.com>

CART-89-dlog DEBUG: Extension of CART-933. Fixed range check in pristr

---

src/vos/vos_dtx.c

Originally, it was freed in dtx_rec_release(), but it maybe still
used after dtx_rec_release(). That will cause server corruption.

DAOS-6646 vos: free vos_dtx_act_ent::dae_oids in dtx_act_ent_cleanup

---

src/tests/ftest/cart/no_pmix/cart_nopmix_multictx_one_node.py
src/tests/ftest/cart/no_pmix_multi_ctx.c

Test under normal conditions ended up running in 8-9 seconds, and
with default 10 second timeout it ended up occasionally going over
board and as such being marked as a failure.
- Test timeout/wait bumped to 30 seconds
- Test modified to not perform sleep(1) as well as not set any
delay for shutdown sequence (2 seconds by default).
Singed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

DAOS-6648 test: Bump timeout value for test

---

src/cart/crt_rpc.h
src/container/rpc.h
src/container/srv_container.c
src/include/daos_srv/pool.h
src/mgmt/rpc.h
src/mgmt/srv_system.c
src/object/obj_rpc.h
src/pool/rpc.h
src/pool/srv_pool.c
src/pool/srv_util.c
src/rdb/rdb_internal.h
src/rdb/tests/rpc.h
src/rebuild/rpc.h
src/rebuild/srv.c
src/rsvc/rpc.h

Currently, we do not support old client (1.0) to talk with new
server (1.2), and vice versa. Bump the cpf_ver for RPC related
modules.

DAOS-6585 common: bump cpf_ver for interoperability issues

---

src/dtx/dtx_common.c
src/include/daos_srv/dtx_srv.h
src/vos/tests/vts_dtx.c
src/vos/vos_internal.h
src/vos/vos_iterator.c

The pre-detect uncommitted DTX during vos iteration is some
kind optimization for try to reduce the RPC overhead caused
by related DTX refresh. But the optimization may cause some
issues as following:
1. It cannot handle non-committed DTX when vos_iter_probe().
That is the first place to detect non-committed DTX entry
that may affect current iteration. If we skip over it, we
may skip related tree under such point. That may make the
pre-detection of uncommitted DTX to become meaningless or
cause more overhead.
2. Similarly for non-committed DTX when handle vos_iter_next.
3. Need to consider CPU yield during the pre-detection scan.
For the object with a lot of keys/values, hundreds of or
thousands of pre-detection may not find more uncommitted
DTX but introduce more overhead. But if we do …

DAOS-6388 vos: remove DTX pre-detection from vos iterator

---

src/control/lib/spdk/include/nvme_control_common.h
src/control/lib/spdk/src/nvme_control.c

When formatting multiple NVMe namespace (like on GCP), we should create
one queue pair per controller and reuse it for each namespace otherwise
we expose some bugs with write completion events that are never reported.
This patch also:
- removes the additional read after write which is not necessary
- calculates the number of LBAs based on the sector size to make
sure that we are really writting 4K (and not 512B).
- uses spdk_dma_zmalloc() for convenience

DAOS-6640 control: reduce number of qpair creation during format

---

src/include/daos_srv/rebuild.h
src/object/cli_obj.c
src/rebuild/srv.c
src/tests/suite/daos_rebuild_simple.c

1. Add RP_XSF tests.
2. Ouput rebuild/reintegrate/drain/extend operation
by console.

DAOS-5851 tests: add RP_XSF rebuild

---

src/client/dfs/duns.c
src/include/daos_fs.h
src/include/daos_uns.h

Check header file is correct, and resolve some Doxygen issues.
Only define max_len in one location
Do not define min_men at all.
Use snprintf() in preference to sprintf.

DAOS-5033 uns: Update comments in daos_uns.h and remove defines.

---

src/container/srv_target.c
src/dtx/dtx_common.c
src/dtx/dtx_cos.c
src/include/daos_srv/container.h
src/include/daos_srv/daos_server.h
src/vos/vos_dtx.c

In original implementation, when fail to open the container,
the container reference may be dropped unexpectedly, that may
caused the container to be released while others are using it.
The patch also add just DTX batched commit register/deregister
logic to avoid potential assertion for container status check.

DAOS-6573 container: fix container reference issue

---

utils/githooks/pre-commit

"\s" seems to be GNU specific. To make pre-commit work on BSDs, like
macOS, change "\s" to "[[:blank:]]".

DAOS-623 githooks: Fix pre-commit for BSDs

---

src/object/cli_shard.c

For query key RPC inside distributed transaction, server may reply
-DER_TX_RESTART to require related TX to restart. Under such case,
the RPC callback on client needs to parse the returned error from
reply firstly, then call dc_tx_op_end() to handle it; otherwise,
the upper layer caller may get failure when restart the TX.

DAOS-6475 object: handle TX restart for query key RPC callback

---

src/tests/ftest/container/snapshot.py

Disable container snapshot negative test in CI

DAOS-6692 test: Disable container snapshot negative test in CI

---

src/cart/crt_hg.c

Fix possible NULL pointer dereference on error pass handling.
```
22. assign_zero: Assigning: rpc_priv->crp_hg_hdl = NULL.
884                        rpc_priv->crp_hg_hdl = NULL;
885                        RPC_ERROR(rpc_priv,
886                                  "HG_Reset failed, hg_ret: %d\n",
887                                  hg_ret);
888                        rc = -DER_HG;
889                }
890        }
891
892        if (crt_gdata.cg_sep_mode == true) {
CID 290781 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)
28. var_deref_model: Passing null pointer rpc_priv->crp_hg_hdl to HG_Set_target_id, which dereferences it. [hide details]
893                hg_ret = HG_Set_target_id(rpc_priv->crp_hg_hdl,
/install/prereq/release/mercury/include/mercury.h …
```

DAOS-6686 cart: Fix coverity defect

---

src/dtx/dtx_rpc.c
src/dtx/dtx_srv.c
src/object/srv_obj.c
src/tests/suite/daos_dist_tx.c
src/vos/tests/vts_mvcc.c
src/vos/vos_dtx.c

To avoid being reported as coverity defects.

DAOS-6628 dtx: code style issues found by coverity

---

src/pool/srv_target.c

Exclude sys reserved space from the pool space query result.

DAOS-6691 vos: exclude sys reserved space

---

src/client/dfuse/ops/lookup.c
utils/node_local_test.py

DAOS-6486 dfuse: Use new dfs_lookupx function to check for xattrs.

---

utils/build.config

Also remove FUSE and FIO from build.config since we don't buid those any
more.

DAOSSDE-54 build: Update isa-l to 2.30.0

---

src/client/dfs/dfs.c
src/tests/suite/dfs_par_test.c

- when using O_EXCL mode, a TX is not needed since it's only 1
conditional op.
- Dir and Symlinks don't need a TX for the same reason.
- Refactor dfs_cont_create() a little and add a unit test for
atomicity.

DAOS-6222 dfs: use TX in DFS open only when needed

---

src/include/daos_srv/iv.h
src/include/daos_srv/rebuild.h
src/iosrv/server_iv.c
src/pool/srv_internal.h
src/pool/srv_iv.c
src/pool/srv_pool.c
src/pool/srv_target.c
src/rebuild/rebuild_internal.h
src/rebuild/rebuild_iv.c
src/rebuild/srv.c
src/tests/suite/daos_mgmt.c

Add rebuild leader stop condition, so ds_pool_stop
will wait for rebuild_task_ult() to stop on the leader.
Add iv_stop in iv_ns to avoid retry during pool destory.
Add iv_ns refcount and wait all iv reference
before pool stop.

DAOS-5868 iv: add rebuild leader stop condition

---

doc/admin/env_variables.md

Add description of SCHED env vars, remove obsolete env vars.

DAOS-6720 doc: description of SCHED env vars

---

src/tests/ftest/cart/ctl/cart_ctl_five_node.py
src/tests/ftest/cart/ctl/cart_ctl_five_node.yaml

- Add client shutdown command to five node test, instead of letting
servers to expire.
- Remove unneeded sleeps in the test as cart_ctl will perform retries
to connect to the group

CART-89 tests: Fix five node tests

---

src/tests/suite/daos_test_common.c

Fix resource leak in wait_and_verify_pool_tgt_state() and
also add check for null target state parameter.

DAOS-6703 sdl: Fix resource leak in daos_test_common function

---

src/include/daos_srv/iv.h
src/rebuild/srv.c

1. check rgt in rebuild_task_ult.
2. reverse iv_refcount and iv_done_eventual
in ds_iv_ns to save some bytes.

DAOS-5868 rebuild: check rgt in rebuild_task_ult

---

src/tests/ftest/datamover/copy_basics.py

Re-enabled the copy_types and copy_subsets tests.
Features: copy_basics

DAOS-6523 test: Re-enable datamover copy_basics tests

---

src/bio/smd/smd_internal.h
src/bio/smd/smd_pool.c
src/bio/smd/smd_store.c

If there is no NVMe storage, the storage query
seg faults trying to list smd pools.  Add
smd_db_ready() API to avoid trying to list the pools
in such case.

DAOS-6737 smd: Fix storage query with no NVMe

---

src/iosrv/drpc_client.c
src/iosrv/module.c
src/rdb/rdb.c
src/tests/ftest/cart/util/cart_logtest.py

This call must have been dropped at some point in the past and
was causing a number of server memory leaks.
Fix a crash caused by double-shutdown of the rdb code.
Add D_ALLOC logging to one place in the drpc code.
Overall this improves the shutdown, and closes a number of
memory leaks in the server.

DAOS-6723 iosrv: Call sm_fini when shutting down server modules.

---

src/rdb/tests/rdbt.c

Coverity issue ID 303781 revealed a bug in PR 2708 in the
rdbt_find_leader() function. Change the check for resp_invalid
to hint_isvalid since that is what the printf argument refers to.

DAOS-6702 rdb,test: fix conditional in printf, Coverity issue

---

src/bio/bio_context.c
src/container/srv_target.c

- Dereference before NULL check in src/container/srv_target.c
- Unchecked return value in src/bio/bio_context.c

DAOS-6729 SDL: Two coverity defects

---

src/container/srv_container.c
src/object/cli_obj.c
src/object/srv_obj_migrate.c
src/placement/jump_map.c
src/placement/pl_map.h
src/placement/pl_map_common.c
src/pool/srv_target.c
src/rebuild/srv.c
src/tests/suite/daos_oid_alloc.c
src/tests/suite/daos_rebuild_simple.c

1. st_shard in shard_tgt should be the real offset
of the shard in object shards array.
2. Do not add new remap shards to the extend list for
remap shards for reintegration layout.
3. Using real group size, instead of object class group
size to calculate the group index.
4 add tests to verify large stripe rebuild/reintegration.

DAOS-6255 placement: few fixes for placement

---

ci/codespell.ignores
src/common/pool_map.c
src/container/srv_container.c

1. free prop for cont_open handler.
2. initialize co_out_ver during map initialization.

DAOS-6734 misc: coverity defects

---

src/rebuild/srv.c

Let's abort the rebuild only when IV ns is stopped, i.e.
destory the pool, so during leader change, the rebuild
will hang for IV until the new leader step up and update
the master.

DAOS-6748 rebuild: abort the rebuild correctly

---

src/client/dfs/dfs.c

Remove all fifo references from dfs.  The completes DAOS-6486.

DAOS-6486 dfs: Remove fifo support now it's no longer used.

---

src/cart/README.env
src/cart/crt_init.c

- Automatically disable MR caching unless new CRT_MRC_ENABLE
variable is not set.
- MR caching is disabled as it is causing rdma buffer corruptions.

CART-89 mrc: Automatically disable MR caching

---

Jenkinsfile
ci/functional/job_cleanup.sh

When daos-stack/pipeline-lib@370aff9 landed, it broke the pipeline-lib API such that no daos commit prior to it would build with the current pipeline-lib master.
The original API needs to be restored and a new API created for the desired changes and DAOS updated to use the new API.

CORCI-1052 build: Fix pipeline API breakage

---

src/control/server/config/server_test.go
utils/config/daos_server.yml
utils/config/examples/daos_server_local.yml
utils/config/examples/daos_server_psm2.yml
utils/config/examples/daos_server_sockets.yml
utils/config/examples/daos_server_unittests.yml

rename daemon logfiles to daos_server.log and daos_engine.N.log
where needed, change server to engine in config file comments

DAOS-6659 continue renaming of daos_io_server to daos_engine

---

src/cart/crt_init.c

- Incorrect envariable was being set to disable mrc

CART-89 env: Fix enironment variable name for mrc

---

doc/admin/performance_tuning.md
doc/admin/tiering_uns.md
doc/user/container.md

remove references to container type MPI-IO (MPI-IO uses POSIX containers)
clarify IOR usage in performance_tuning.md

DAOS-5579 doc: clarifiy container type and IOR backends

---

src/cart/crt_internal_fns.h
src/cart/crt_register.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/cart/crt_swim.c
src/include/cart/types.h
src/utils/ctl/cart_ctl.c

Rather than have one big "internal" protocol containing
a number of server<=>server and client<=>server RPCs split
it into several.  This avoids needing to change the client
protocol on server changes and isolates things like the
self-test code from needing to change when other things do.
This brings us a big step forward towards interoperability.
Create protocols for IV, self-test and ctl. Update cart_ctl
to query the protocol before use.
There is one RPC the cart_ctl uses to ping the servers looking
for startup, so leave this one in the internal protocol, cart_ctl
should be updated to use the register itself to perform the ping.

DAOS-6620 cart: Split CaRT protocols into smaller units.

---

Jenkinsfile

The Docker update was landed without landing the pipeline-lib update
first, so back out the reference to the branch in Jeninksfile.

DAOS-6742 build: Remove incorrect pipeline-lib reference.

---

src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Fix daostest rebuild 27 to use 6 svcs

DAOS-6792 test: Fix daostest rebuild 27 to use 6 svcs

---

src/control/security/domain_info.go
src/control/server/security_rpc.go

- Genericize errors to avoid revealing security credential
details.
- Remove debug logging of auth_sys token information.

DAOSSDE-52 sec: Remove potentially sensitive logging

---

src/engine/init.c

Move pl_fini after modules unload, because module
unload might need placement hash table.

DAOS-6777 engine: move pl_fini after unload modules

---

src/object/cli_obj.c
src/object/srv_obj_migrate.c

For object enumeration, let's set the iov_len of the sgl
in obj_shard_list_obj_cb(), so if the object(especially
EC object) enumeration needs to fetch from multiple shards,
the iov_len can be updated accordingly in shard callback.

DAOS-5827 object: set sgl len correctly for migration

---

src/engine/drpc_ras.c

Rather than a hardcoded ID (fixing a copy paste mistake).

DAOS-6436 engine: return event id str on error

---

src/control/drpc/drpc_server.go
src/control/server/drpc.go
src/control/server/instance_drpc.go
src/include/daos/drpc.h

The previous size was 16K, which is too small for large systems.
Increasing it to 128K should be plenty.

DAOS-6032 control: Increase drpc message size limit

---

src/mgmt/srv_pool.c
src/tests/ftest/daos_test/daos_core_test-rebuild.yaml

Before this change, intermittently the svc_ranks argument provided
by the control plane to the ioserver ds_mgmt_destroy_pool() function
could have (due to close timing, or even a failure to raise a RAS event)
some pool service ranks that have actually been excluded from
the pool. With the recent change to the pool destroy corpc protocols,
this results RSVC_STOP broadcast RPCin ds_pool_svc_destroy()
failing with DER_UNREACH.
With this change, ds_mgmt_destroy_pool(), after retrieving the full
list of pool ranks from the PS leader, filters svc_ranks so it only
contains ranks understood to be part of the pool at destroy-time.

DAOS-6789 mgmt: filter svc_ranks by pool ranks for RSVC_STOP

---

src/include/daos_srv/daos_engine.h
src/include/daos_task.h
src/mgmt/cli_mgmt.c
src/pool/cli.c
src/pool/srv_cli.c
src/pool/srv_util.c
src/tests/ftest/daos_test/daos_core_test-nvme_recovery.py

PR 3935 inadvertently removed the svcl argument to the functions
dsc_pool_tgt_exclude() and dsc_pool_tgt_reint(). This resulted in a
segmentation fault in the daos engine in dc_mgmt_get_pool_svc_ranks()
during internal pool updates (e.g., as part of nvme faulty reaction).
The crash is due to the code going too far into the client RPC stack,
attempting a client-only MGMT_POOL_GET_SVCRANKS RPC. And relying on
struct dc_mgmt_sys.sy_info.ms_ranks, only filled for clients.
With this change the arguments are restored, and the calling function,
update_targets_ult() provides the pool service server rank to contact
for the exclude/reintegration operation. And some defensive checks
are made to prevent the engine from calling certain client-only code.
Test-tag-hw-medium: pr,hw,medium,ib2 …

DAOS-6764 md: add svcl argument to dsc_pool_tgt_exclude/reint

---

src/rebuild/srv.c

Reset tgt_pos to 0 for every loop in rebuild_debug_print_queue.

DAOS-6804 rebuild: typo in rebuild_debug_print_queue

---

src/gurt/telemetry.c
src/utils/daos_metrics/daos_metrics.c

When running daos_metrics as a different user/group than
the one that started the I/O Engine, the daos_metrics
process would fail to attach to the shared memory segment
and generate a segfault when trying to access that memory.
The function shmat() can return NULL or -1 on error.  The -1
was not identified as an invalid address.
Opportunistic fix for Coverity CID 318954 and CID 318949
which occur in the same files being edited.

DAOS-6814 Telemetry: Segfault in daos_metrics

---

src/rsvc/srv_common.c

This reverts commit f1b0dc97655276f6e512b9872a383ff0e7b8e82a.

Revert "DAOS-6709 rsvc: do not xfer more than real attr size (#4623)"

---

utils/rpms/Makefile
utils/rpms/daos.spec

The linter doesn't like anything on a %endif line.
When defining macros, don't include the % in the macro name.

DAOS-6746 build: Fix some RPM building issues

---

src/bio/bio_monitor.c

Server crash seen when querying nvme-health after manually evicting an SSD.
This was due to an assert being hit when the blobstore pointer passed was
NULL, in this case just return before querying blobstore space usage stats
instead of asserting.

DAOS-6821 bio: Fix server crash when querying nvme-health

---

src/tests/ftest/util/daos_core_base.py
src/tests/suite/daos_pool.c

The cmocka xml file name was the same as the avocado xml file name so any cmocka
failures in a test would get overwritten in the results making it impossible to figure out
what actually failed to cause the test failure.   This simply renames the file.  I verified
with first version of this patch that this works.

DAOS-623 test: Force cmocka xml to be in unique file

---

doc/admin/deployment.md
doc/release/release_notes_v1_0.md
src/control/cmd/dmg/auto.go
src/control/cmd/dmg/main.go
src/control/lib/control/auto.go
src/control/lib/control/config.go
src/control/lib/control/config_test.go

* Validate the auto-generated config file after its creation.
* Enable hostlist to be read from config file or overridden on cli.
* Document limitation caused by github.com/pmem/ndctl/issues/130.

DAOS-6605 control: validate auto-generated config file

---

doc/admin/deployment.md
doc/release/release_notes_v1_0.md

Bug in ndctl that causes dmg storage scan and dmg config generate to
work incorrectly because NUMA affinity of pmem bdevs are not correctly
reported has been fixed in CentOS7.9. Update admin guide and release
notes.
Doc-only: true

DAOS-6605 doc: report that ndctl numa bug fixed in centos7.9

---

src/tests/suite/daos_container.c

reset fail loc on all servers in container
test 23, otherwise it may cause failures
in following test.

DAOS-5313 tests: reset fail loc

---

src/control/lib/atm/bool.go
src/control/lib/atm/bool_test.go

Oversight when the original implementation was added. Also
adds a unit test to verify that atm.Bool's zero value works
as expected.

DAOS-3938 control: Add a Store() method to atm.Bool

---

src/pool/srv.c

Move iv_fini after ds_pool_hdl_hash_fini(), because
ds_pool_hdl_hash_fini might call pool_free_ref()->
ds_iv_ns_fini(), which need iv_class.

DAOS-6793 pool: move iv_fini after ds_pool_hdl_hash_fini

---

src/cart/crt_iv.c

Memory allocated in iv_ops->ivo_on_get() should be freed in
corresponding iv_ops->ivo_on_put(). This is not always happens,
especially in case of errors.

DAOS-6808 iv: fix memory leaks in IV operations

---

doc/admin/pool_operations.md

Reflect removal of libdaos mgmt APIs.
Reflect deprecation of scm-size argument to dmg pool create.
Add information about querying pool properties with daos tool.
Add information about vos SCM and NVMe space reservation and
impact on interpreting pool query min output.

DAOS-4949 doc: update pool operations info for DAOS v1.2

---

src/cart/crt_corpc.c
src/cart/crt_group.c
src/cart/crt_hg_proc.c
src/cart/crt_init.c
src/cart/crt_iv.c
src/cart/crt_tree.c
src/tests/ftest/cart/no_pmix_group_test.c

- -DER_GRPVER errors are no longer emitted as errors
- Rank is emitted once into log, instead of on every failed corpc
- group_test modified to remove 10 second sleep that is no longer needed
- Envariables affecting CART are now printed as D_INFO

CART-89 debug: Cleanups, remove error prints from -DER_GRPVER

---

src/container/container_iv.c
src/container/oid_iv.c
src/container/srv_internal.h
src/container/srv_target.c
src/engine/server_iv.c
src/include/daos_srv/iv.h
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/pool/srv_internal.h
src/pool/srv_iv.c
src/pool/srv_target.c
src/rebuild/rebuild_iv.c
src/tests/suite/daos_container.c
src/tests/suite/daos_rebuild_simple.c

Remove temporay maxim snapshot limitation, and add
retry for snapshot IV fetch if the fetching buffer
is not big enough.
Add ifo_misc for cart iv fetch so it will return size
information for REC2BIG error.
Move some crt_proc_d_sg_list_t from object module to
cart so ifo_misc can use it.
Add tests in rebuild_simple to verify the large
snapshot handling.

DAOS-5313 container: add retry for snapshot fetch

---

src/tests/suite/daos_rebuild_simple.c

fix oid_gen interface for large_snap test.

DAOS-5313 tests: fix typo in large_snap test

---

src/placement/pl_map_common.c

Any failure targets in the remap list should either
be set to unavaible(po_shard = -1) or valid replacement
target, i.e. we can not skip any targets in the remap
list.

DAOS-6748 placement: set the remap target correctly

---

src/tests/ftest/datamover/copy_negative.py
src/tests/ftest/datamover/copy_negative.yaml
src/tests/ftest/util/data_mover_test_base.py

Test-tag-vm: pr,-hw datamover,-hw
Added a datamover/dcp test case for a posix
filesystem being out of space.
Adjusted run_datamover to accept a list of
output expected in stderr.

DAOS-6387 test: datamover posix fs space

---

src/engine/sched.c

Scheduler maintains a 'spi' for each active VOS pool, when the
pool is destroyed, scheduler will purge the 'spi' if it won't
be accessed by any outstanding sched_request.
However, current purging code overlooked the sleeping GC ULT, so
the spi could be purged even if it'll be accessed by sleeping GC
ULTs later. Such race happens only when a pool is destroyed and
a new pool with same UUID being created immediately (before the
old 'spi' purged).

DAOS-6818 sched: race in purging spi

---

debian/changelog
utils/rpms/daos.spec

Many -devel packages were being required by daos- devel that are not
actually needed to build client applications.

DAOS-6819 build: Reduce daos-devel Requires

---

src/pool/srv_target.c
src/rebuild/srv.c

Move iv_ns destory after container agg ULT stop, which might
access IV ns.

DAOS-6828 pool: move iv_ns destroy after container agg stop

---

src/control/server/mgmt_pool.go
src/control/server/mgmt_pool_test.go

In some edge cases, a pool could be left in a state where the
MS entry exists but the data plane resources have been destroyed,
and subsequent attempts to destroy the pool would fail.
This commit changes the pool destroy handler to properly handle
various scenarios where the destroy process is interrupted or
fails in unexpected ways.

DAOS-6824 control: Fix pool destroy RPC handler

---

src/control/server/ctl_ranks_rpc.go
src/control/server/harness.go

Allow longer for ranks to terminate when requested during system stop,
under I/O load 3 seconds is not enough and system stop may report
errors. Increase to 10 seconds (start rank deadline remains at 30).

DAOS-6859 control: increase stop rank deadline

---

src/container/srv_target.c
src/object/obj_internal.h
src/object/obj_rpc.h
src/object/srv_obj_migrate.c
src/pool/srv_pool.c
src/rebuild/scan.c

This patch changes the rebuild migration behavior to delete individual
existing objects prior to reintegration, rather than whole containers.
This means that any object that exists on a server prior to that server
being reintegrated will be deleted only if the rebuild migration process
detects that data as existing on another target and attempts to migrate
it.
There are several practical results of this enhancement:
- Containers will no longer be deleted incorrectly on other local
targets when reintegrating just one target (DAOS-6162)
- Objects that have no rendundancy but are still healthy on the
reintegrating node will still be available after reintegration.
- Objects will still be deleted prior to migration, so that VOS will not
be unhappy about migrating the same data on top of …

DAOS-6714 rebuild: Delete redundant objects prior to reintegration

---

Jenkinsfile
ci/provisioning/post_provision_config_nodes.sh
ci/provisioning/post_provision_config_nodes_EL_7.sh
ci/provisioning/post_provision_config_nodes_LEAP_15.sh

DNF seems to have changed how it substitutes % encodings in URLs into
repository path names.
DRY out some common code across EL7 and LEAP15's use of DNF to provision
nodes.

DAOS-623 test: Fix % substitutions in repo paths

---

src/container/srv_target.c
src/object/obj_internal.h
src/object/obj_rpc.h
src/object/srv_obj_migrate.c
src/pool/srv_pool.c
src/rebuild/scan.c

This patch changes the rebuild migration behavior to delete individual
existing objects prior to reintegration, rather than whole containers.
This means that any object that exists on a server prior to that server
being reintegrated will be deleted only if the rebuild migration process
detects that data as existing on another target and attempts to migrate
it.
There are several practical results of this enhancement:
- Containers will no longer be deleted incorrectly on other local
targets when reintegrating just one target (DAOS-6162)
- Objects that have no rendundancy but are still healthy on the
reintegrating node will still be available after reintegration.
- Objects will still be deleted prior to migration, so that VOS will not
be unhappy about migrating the same data on top of …

DAOS-6714 rebuild: Delete redundant objects prior to reintegration (#4739)

---

src/tests/ftest/datamover/copy_negative.py

Test-tag: copy_negative
Skip-scan-centos-rpms: true
Disable test_copy_space_dcp until the timeout issue
is resolved.

DAOS-6871 test: disable datamover copy_space

---

utils/node_local_test.py

Fix a bug in NLT where it has been assuming the order of files
in a directory and testing the first one, rather than using
the specific file it wants by name.
Move the test into it's own method to provide better isolation
and reporting.

DAOS-6886 test: Do not assume directory order in NLT.

---

src/common/tests_dmg_helpers.c

Fixed Coverity issue in the test code.
313028(#2 of 2) and 313033(#1 of 1).

DAOS-6685 Test: Fixed coverity issue in test code.

---

src/container/container_iv.c

Silence more intermittent startup warnings.

DAOS-6572 container: Use CDEBUG to silence more warnings.

---

src/tests/ftest/control/daos_object_query.py
src/tests/ftest/control/daos_object_query.yaml
src/tests/ftest/server/cpu_usage.py

The test was failing because the object class code changed.
Updated the test so that it verifies daos object query output with S1, RP_2G1, RP_3G1, and RP_2G2.
It checks oid and grp_nr values. It also checks the number of grp and replica rows in the table based
on the object class.

DAOS-6851 test: Fixed and improved daos object query test (#4716)

---

src/tests/ftest/util/daos_utils.py

DAOS-6878 test: Fix control daos_snapshot script issue
Update: daos_utils.py
Skip-nlt: true
Test-tag: daos_snapshot

DAOS-6878 test: Fix control daos_snapshot script issue

---

src/client/dfs/README.md
src/object/README.md

DAOS-2615 docs: update README for some client APIs

---

doc/user/container.md

Add to list of container properties that may be set at create-time.
Refer to daos cont get-prop and daos_cont_get_prop() API ;
and daos cont get/set/list attr commands.
Update description of container snapshot, including reference
to new daos cont commands in this area.
Doc-only: true

DAOS-4950 doc: update container info for DAOS v1.2

---

src/client/java/daos-java/pom.xml
src/client/java/daos-java/src/main/java/io/daos/dfs/DaosFsClient.java
src/client/java/hadoop-daos/pom.xml
src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosConfigFile.java
src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosFileSystemContractIT.java
src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosFileSystemTest.java
src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/contract/DaosContractCreateIT.java

Code scanning tools identified the need to upgrade hadoop to eliminate dependency on packages with known vulnerabilities.

DAOS-6759 java: Update Hadoop from v 2.6.7 to 3.1.3

---

src/common/dts.c
src/include/daos_prop.h

Fix a coverity warning in dts.c, fix a typo in daos_prop.h

DAOS-6849 test: fix coverity warning

---

utils/systemd/daos_agent.service.pre230

The LimitMEMLOCK=infinity line that was added to fix verbs support in
daos_agent landed after the file was copied to create the pre230 version of the
daos_agent service file. This adds the line into the pre230 version of the
daos_agent service file to get verbs working again by default on centos 7. This
change only affects the centos 7 builds.

DAOS-6898 systemd: Add missing line to pre230 systemd unit files

---

src/tests/ftest/util/mpio_test_base.py
src/tests/ftest/util/mpio_utils.py

Checking for command failures in the command output rather than the
entire test's stdout for the MpiioTests-based tests.
Test-tag: llnlmpi4pyhdf5 llnl romio

DAOS-6905 tests: Fixing false failures in llnl_mpi4py and romio tests

---

src/object/cli_obj.c
src/object/srv_obj_migrate.c
src/placement/pl_map_common.c
src/tests/suite/daos_drain_simple.c
src/tests/suite/daos_rebuild.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_test.h

1. Update daos_drain_simple tests to use R1S to
focus on single replica drain.
2. Use grp_size instead of object replica number
to search the valid replicas.
3. Do not need fetch from leader for migration,
since we already do dtx resync before migration, and
also for single replica case, it will not be
able to find leader in this case.
4. Do not set po_rebuilding for drain case, otherwise
it will not be able to fetch anything during drain.

DAOS-6466 object: a few fixes for Drain

---

utils/config/daos_server.yml

remove OPA reference from daos_server.yml, fix " typo

DAOS-5579 doc: remove OPA reference from daos_server.yml

---

src/tests/ftest/cart/util/cart_logtest.py

The cost of keeping the whitelist up to date is greater than the benefit
from having the check so simply remove it.

DAOS-6926 logging: Do not check for facility used in alloc/free.

---

src/client/java/hadoop-daos/pom.xml

Snyk updated its recommendation again to upgrade from 3.1.3 to 3.2.1 so we are
updating to the latest which is 3.2.2

DAOS-6929 Java: Update Hadoop dependency from 3.1.3 to 3.2.2

---

src/tests/ftest/cart/iv_server.c

Fixes unused value defect in cart iv server functional test.

DAOS-6731 sdl: Fix coverity defect in CaRT IV server test

---

src/control/cmd/dmg/system.go
src/control/cmd/dmg/system_test.go
src/control/system/database.go
src/control/system/errors.go
src/control/system/membership.go
src/control/system/membership_test.go

As a leftover from some older logic, servers with a new
UUID were being allowed to present a join request for an
existing rank, with the result that the new server replaced
the old one in the system membership. This commit removes
the ability to implicitly replace an existing server. Future
work will add support for explicit replacement via new API
surface.

DAOS-6915 control: Don't allow new ranks to claim existing

---

src/placement/jump_map.c

Do not clear used_tgts in get_targets, since we do not want
put multiple shards in a single VOS target yet, which could
happen when there are different VOS targets in each fault
domain.
Add dom_occupied to get_targets to represent the domain whose
targets has been used up for the objects, so to avoid the
domain to be choosen.
Do not need rehash within the same rank, if the targets has been
used, let's just walk through the targets to find the avaible
spots.

DAOS-6748 placement: Do not clear used_tgts in get_target (#4751)

---

src/include/daos_srv/vos_types.h
src/vos/tests/vts_pm.c
src/vos/vos_obj.c
src/vos/vos_obj_index.c

Add future object punch epoch to key iterator.  Needed for
rebuild migration so we can rebuild punched objects that
are visible in a prior snapshot.

DAOS-4698 vos: Report future object punch with iterator

---

src/pool/srv_iv.c
src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/SConscript
src/tests/suite/daos_extend_simple.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_test.c
src/tests/suite/daos_test.h
src/tests/suite/daos_test_common.c

1. Add extend simple test.
2. Fix memory corruption in IV pool map, which
might cause extend tests segfault.

DAOS-6464 tests: add extend simple test

---

src/rebuild/rebuild_internal.h
src/rebuild/rebuild_iv.c
src/rebuild/srv.c

During rebuild,  the leader IV sync(rebuild_leader_status_check)
is used to sync the global status to all other server, but it
might also call local iv update entry callback on the leader,
which might then update rebuild global staus. So add iv_sync to
avoid the rebuild global status being updated in this case.

DAOS-6840 rebuild: add iv_sync to rebuild iv.

---

src/engine/server_iv.c
src/include/daos_srv/iv.h
src/pool/srv_pool.c

Let's stop the iv ns leader during the destory first, so
all arriving IV requests will fail and return immediately.

DAOS-6798 iv: stop the iv ns leader first during destroy

---

src/tests/ftest/pool/evict_test.yaml

Increase timeout as the pool create operations are taking longer now.
Test-tag: DAOS_5610

DAOS-6931 test: Fix pool/evict_test.yaml

---

Jenkinsfile

ClamAV seems to have implemented some type of throttle so turning off
by default until the scans can use a local mirror.

CORCI-1055: Turn of clamAV scanning by default

---

src/tests/ftest/util/command_utils.py
src/tests/ftest/util/dmg_utils.py
src/tests/ftest/util/general_utils.py

Resolving a JSON parsing encountered by the pool/create_test.py when
failing to create a pool by replacing the "combined" stdout/stderr
output currently produced by avocado's process.run() with the "both"
option.
Test-tag-hw-large: pr,hw,large pool_create_tests,hw,large

DAOS-6932 tests: Resolving DmgCommand JSON parsing error

---

src/client/java/hadoop-daos/pom.xml

Snyk updated its recommendation again to upgrade from 3.1.3 to 3.2.1 so we are
updating to the latest which is 3.2.2
Master-PR: https://github.com/daos-stack/daos/pull/4844

DAOS-6929 Java: Update Hadoop dependency from 3.1.3 to 3.2.2 (#4844)

---

src/tests/ftest/util/command_utils.py
src/tests/ftest/util/dmg_utils.py
src/tests/ftest/util/general_utils.py

Resolving a JSON parsing encountered by the pool/create_test.py when
failing to create a pool by replacing the "combined" stdout/stderr
output currently produced by avocado's process.run() with the "both"
option.
Master-PR: https://github.com/daos-stack/daos/pull/4858

DAOS-6932 tests: Resolving DmgCommand JSON parsing error (#4858)

---

src/gurt/tests/test_gurt.c

DAOS-623 test: Fix allocation of counters in hash perf test

---

src/object/cli_obj.c
src/object/srv_obj_migrate.c
src/placement/pl_map_common.c
src/tests/suite/daos_drain_simple.c
src/tests/suite/daos_rebuild.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_test.h

1. Update daos_drain_simple tests to use R1S to
focus on single replica drain.
2. Use grp_size instead of object replica number
to search the valid replicas.
3. Do not need fetch from leader for single replica
migration.
4. Do not set po_rebuilding for drain case, otherwise
it will not be able to fetch anything during drain.

DAOS-6466 object: a few fixes for Drain (#4813)

---

src/control/cmd/dmg/cont.go
src/control/cmd/dmg/main.go
src/control/cmd/dmg/pool.go
src/control/cmd/dmg/storage.go

Rather than handling errors piecemeal, centralize the
decision about whether or not an error should be formatted
as JSON.
Master-PR: https://github.com/daos-stack/daos/pull/4804

DAOS-6891 control: Clean up JSON output for errors

---

src/include/daos_srv/vos_types.h
src/vos/tests/vts_pm.c
src/vos/vos_obj.c
src/vos/vos_obj_index.c

Add future object punch epoch to key iterator.  Needed for
rebuild migration so we can rebuild punched objects that
are visible in a prior snapshot.

DAOS-4698 vos: Report future object punch with iterator (#4854)

---

src/gurt/dlog.c

Fix memset to be done before mst is initialized for flushing

CART-89 fix: Fix dlog_flush

---

src/rebuild/scan.c
src/tests/suite/daos_rebuild_simple.c

Remove obsolote check after we delete the objects
after reintegration, otherwise it may cause duplicate
shards in the same vos target.
Add tests to verify the case, but skip it due to
DAOS-5758.

DAOS-6925 rebuild: remove obsolote check in scan

---

src/control/events/ras.go
src/control/lib/control/system.go

With this change, RAS events are written directly to SYSLOG on the host
that they are first raised. This now occurs regardless of how daos_server
is launched (doesn't depend on systemd forwarding events to SYSLOG).
In production deployments it may be preferable to disable systemd
forwarding to SYSLOG to restrict logging to RAS events only as currently
a significant amount of logging is forwarded by daos_server.
RAS events written to SYSLOG have a DAOS specific structure and do not
currently adhere to RFC 3164 or RFC 5424.

DAOS-6327 control: write ras events to syslog

---

src/utils/daos_hdlr.c

Add NULL check before dereference on path string in daos_hdlr

DAOS-6683 daos: coverity fix 316578

---

src/rebuild/rebuild_internal.h
src/rebuild/rebuild_iv.c
src/rebuild/srv.c

During rebuild,  the leader IV sync(rebuild_leader_status_check)
is used to sync the global status to all other server, but it
might also call local iv update entry callback on the leader,
which might then update rebuild global staus. So add iv_sync to
avoid the rebuild global status being updated in this case.

DAOS-6840 rebuild: add iv_sync to rebuild iv. (#4855)

---

src/tests/ftest/pool/evict_test.yaml

Increase timeout as the pool create operations are taking longer now.

DAOS-6931 test: Fix pool/evict_test.yaml (#4846)

---

src/tests/ftest/mdtest/mdtest_small.py

Add the pr avocado tag to the test after PR #4827 landed a solution
for pool destroy timeouts.
Test-tag: mdtestsmall

DAOS-6798 test: re-enable mdtest_small on PRs

---

src/tests/ftest/cart/iv_server.c

Fixes unused value defect in cart iv server functional test.
Master-PR: https://github.com/daos-stack/daos/pull/4793

DAOS-6731 sdl: Fix coverity defect in CaRT IV server test (#4793)

---

src/tests/ftest/erasurecode/ec_rebuild_disabled.py
src/tests/ftest/erasurecode/ec_rebuild_disabled.yaml
src/tests/ftest/pool/destroy_rebuild.py
src/tests/ftest/pool/pool_svc.py
src/tests/ftest/pool/pool_svc.yaml
src/tests/ftest/pool/rebuild_no_cap.py
src/tests/ftest/pool/rebuild_no_cap.yaml
src/tests/ftest/pool/rebuild_tests.py
src/tests/ftest/pool/rebuild_tests.yaml
src/tests/ftest/pool/rebuild_with_io.py
src/tests/ftest/pool/rebuild_with_io.yaml
src/tests/ftest/pool/rebuild_with_ior.py
src/tests/ftest/pool/rebuild_with_ior.yaml
src/tests/ftest/rebuild/cascading_failures.py
src/tests/ftest/rebuild/cascading_failures.yaml
src/tests/ftest/rebuild/container_create.py
src/tests/ftest/rebuild/container_create.yaml
src/tests/ftest/rebuild/delete_objects.py
src/tests/ftest/rebuild/delete_objects.yaml
src/tests/ftest/rebuild/read_array.py
src/tests/ftest/rebuild/read_array.yaml
src/tests/ftest/util/command_utils.py
src/tests/ftest/util/command_utils_base.py
src/tests/ftest/util/rebuild_test_base.py
src/tests/ftest/util/server_utils.py
src/tests/ftest/util/test_utils_container.py
src/tests/ftest/util/test_utils_pool.py

Replacing the TestPool.start_rebuild() method with the
DaosServerManager.stop_ranks() method which also correctly sets the
expected state of the stopped rank.  A timeout has been added to allow
retring the dmg pool query command after initializing rebuild.
The rebuild/read_array.py is being re-enabled.
The BasicParameter-based opbjects now include an updated attribute which
is used by YamlParameters objects to determine when an updated yaml
configuration file needs to be generated.  This will reduce the
execution of DmgCommand.run() when executing multiple dmg commands w/o
the need to update and copy the configuration file.
Co-authored-by: Ding Ho <ding-hwa.ho@intel.com>

DAOS-6359 tests: Replacing rebuild tests 'start_rebuild' method (#4527)

---

src/control/cmd/dmg/system.go
src/control/lib/control/system.go
src/control/lib/control/system_test.go
src/control/server/ctl_ranks_rpc.go
src/control/server/ctl_ranks_rpc_test.go
src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go
src/control/system/member.go
src/control/system/member_test.go
src/control/system/membership.go

Return a non-zero exit code from dmg if unrecognised hosts or ranks are
specified on the commandline or if any host operations were unsuccessful.
Return informative errors from dmg system commands when --json output
is selected as log messages may not be consumed and the reason for
failure may not otherwise be clear.
Update system membership with a clear reason for failure when dmg system
command results contain errors.
Disallow stopped->evicted state transition.
Signed-off-by: Tom Nabarro tom.nabarro@intel.com

DAOS-6783 control: return non-zero on dmg system action result error

---

src/object/srv_obj_migrate.c

If the container is being destroyed during migration,
the object pulling might not be able to get anything,
then let's fail the current rebuild and retry.

DAOS-6840 objects: check zero iod during migration (#4760)

---

ci/unit/test_nlt_node.sh
utils/node_local_test.py

Create a subdirectory to put dfuse mounts in, so that if there
is a deadlock the post section can read /tmp/*.log without itself
deadlocking if dfuse is unresponsive.

DAOS-6960 test: Do not mount dfuse in /tmp for NLT testing.

---

src/tests/ftest/container/multiple_container_delete.py
src/tests/ftest/io/io_aggregation.yaml
src/tests/ftest/util/ior_test_base.py

Removing oclass param from create_cont() inside
ftest/util/ior_test_base.py as it is breaking some
of the weekly tests.
The change was earlier added to the code for datamover
tests which now use an overriden version of this method.
Hence 'oclass' param is not needed anymore andn ot used
anywhere else.
Test-tag-hw-small: pr,hw,small dfusespacecheck ioaggregation dfusesparsefile
Test-tag-hw-large: pr,hw,large multicontainerdelete

DAOS-5737 tests: Removing oclass param from create_cont() (#4729)

---

src/container/cli.c
src/vos/tests/vts_checksum.c

The following coverity issues are fixed.
- Coverity CID 280727 - vts_checksum.c passed a large structure 
by value instead of by reference. Changed it to pass by
reference. 
- Coverity CID 319831 - pool lock wasn't being unlocked if 
dc_cont_props_init failed. 

DAOS-6678 csum: Fixed issues caught by coverity

---

src/tests/ftest/pool/destroy_tests.yaml

Update: pool/destroy_test.yaml
Skip-nlt: true
Test-tag: destroysingleloop destroymutliloop

daos-6918-test2: pool_destroy testcase failed due to Timeout

---

src/pool/srv_iv.c
src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/SConscript
src/tests/suite/daos_extend_simple.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_test.c
src/tests/suite/daos_test.h
src/tests/suite/daos_test_common.c

1. Add extend simple test.
2. Fix memory corruption in IV pool map, which
might cause extend tests segfault.

DAOS-6464 tests: add extend simple test (#4837)

---

src/client/api/event.c
src/client/api/task.c

crt_progress can sometimes return errors that are not timeout. Those
are not properly handled in synchronous IO calls and cause the private
event to be in an unusable state for following IOs.
This PR checks the error from cart and reinits the private event in
case an error was returned so it can be resused rather then returning
to the user.

DAOS-6958 event: proper event handing in case of progress errors

---

src/control/server/mgmt_svc.go
src/control/server/mgmt_system.go
src/control/server/server.go

When a rank is marked as evicted after a swim down event, request
an asynchronous group update instead of making concurrent blocking
calls. This change eliminates potential out-of-order updates and
performs better at scale due to batching.

DAOS-6902 control: Perform async group update on rank eviction

---

src/pool/srv_pool.c
src/rebuild/rebuild_iv.c

If the leader is stepping down/up during rebuild, then
iv_master_rank might be set to -1, so let's check that
in rebuild_iv_ent_update(), and return ENOTLEADER in this
case.
Fix memory cleanup error in ds_mgmt_create_pool().

DAOS-6978 rebuild: return NOTLEADER for -1 master rank

---

src/common/checksum.c
src/include/daos/checksum.h
src/object/cli_obj.c
src/object/rpc_csum.c

- Now Using DF_RC where appropriate.
- Renamed pointer for allocation so NLT can detect
where the allocation is freed.
- Added missing check if memory was allocated

DAOS-6979 csum: Fixes detected by NLT

---

src/control/events/generic.go
src/control/events/generic_test.go
src/control/lib/control/system.go
src/control/lib/control/system_test.go

Add coverage for writing RAS events to syslog at the correct priority.

DAOS-6327 control: write ras events to syslog unit tests

---

src/placement/pl_map.c

During DAOS server reintegration, some objects' shards may be
migrated from existing server(s) to the new server. That will
cause related objects to have more shard than claimed ones as
its object class does in the layout temporarily.
Our current DTX leader election algorithms depends on object's
layout. We need to guarantee that the elected DTX leader during
DAOS server reintegration will be the same as without DAOS server
reintegration; otherwise, there may be unnecessary leader switch
during DAOS server reintegration as to unnecessary DTX resync.
This patch uses claimed object replicas count in related object
class rather than the temporary redundancy group size during the
data migration. That avoids above unnecessary DTX leader switch.
Master-PR: …

DAOS-6988 dtx: avoid leader switch during server reintegration

---

src/object/obj_rpc.c

It must be initialized as zero, because it will be used as
part of the vos object cache index. If it is uninitialized,
then we may cannot find out former created object or others
cannot find out the object created by current udpate.

DAOS-6989 dtx: initialize daos_unit_oid_t::id_pad_32

---

src/rebuild/scan.c
src/tests/suite/daos_rebuild_simple.c

Original reintegration protocol does not delete old object, so it has
a check to avoid a rank sends OID to itself and reconstruct a
duplicated shard for itself, which is problematic for the current VOS.
This patch removes the check because reintegration protocol can
remove the old shard and reconstruct a new one.
Add tests to verify the case, but skip it due to DAOS-5758.

DAOS-6925 rebuild: remove obsolote check in scan (#4872)

---

src/vos/tests/vts_mvcc.c
src/vos/vos_obj.c

This prevents orphaning updates (updates in subtree with
no creation timestamp in the incarnation log).

DAOS-6953 vos: Avoid under punch under normal I/O (#4868)

---

src/engine/drpc_client.c
src/engine/drpc_internal.h
src/engine/drpc_ras.c
src/engine/init.c
src/engine/tests/SConscript
src/engine/tests/drpc_client_tests.c
src/include/daos_srv/daos_engine.h
src/include/daos_srv/ras.h
utils/rpms/daos.spec

In an engine, we invoke every dRPC synchronously on the calling xstream.
Before a response is received, the calling xstream is blocked, unable to
execute any other ULTs. For the system xstream, this may even affect the
stability of SWIM and Raft.
This patch introduces dss_drpc_call for invoking dRPCs in an engine.
When invoking a synchronous dRPC, dss_drpc_call creates a pthread to
send the request and receive the response using a private dRPC
connection:
- The impact on the calling xstream will be reduced to the level of
100 us (roughly).
- Concurrent dRPCs will be possible.
- dRPC latencies, however, will increase greatly to the level of 100
ms (roughly), probably because the pthreads struggle to get CPU
time from xstreams.
When invoking a dRPC without waiting for a response, …

DAOS-6853 engine: Introduce dss_drpc_call (#4717)

---

src/tests/ftest/server/metadata.py
src/tests/ftest/server/metadata.yaml

Previous commit 0b86a68 inadvertently set this constant too high.
The constant is intended to represent a near-maximum number of
containers that can be created in a pool, from the perspective of the
pool's metadata (rdb) capacity, based on empirical testing.
That commit worked for the existing metadatafill tests, which currently
passes in testing. However it negatively impacted metadata_free_space,
and also impacts a subsequently-developed test metadata_der_nospace.
With this change the constant is set based on the actual number of
containers that can be created before the pool service would return
DER_NOSPACE.
Also with this change, a setting that is no longer applicable is
removed from metadata.yaml. And, the scm_class is now set to dcpm
to exercise persistent memory rather than tmpfs …

DAOS-7007 md,test: fix NO_OF_MAX_CONTAINER setting

---

src/cart/crt_hg.c

- Enable default NA logging of warnings/errors.

CART-89 debug: Enable NA logging

---

src/cart/crt_iv.c
src/engine/server_iv.c
src/object/obj_rpc.c

- IV ivc_on_put() should release the value buffer
- Add missing "break" for the switch in obj_reply_map_version_set()
- minor fix for memory leak in failure handling of IV
Signed-off-by: Dmitry Eremin <dmitry.eremin@intel.com>

DAOS-6808 misc: Fix a memory leak in IV fetch

---

src/tests/ftest/pool/destroy_tests.yaml

DAOS-6918-test_rel_1.2: pool_destroy testcase failed due to Timeout
Update: pool/destroy_tests.yaml
Skip-nlt: true
Test-tag: destroysingleloop destroymutliloop

DAOS-6918-test_rel_1.2: pool_destroy testcase failed due to Timeout

---

src/placement/jump_map.c
src/placement/tests/jump_map_place_obj.c
src/tests/suite/daos_degrade_ec.c

Prior to this patch, placement would refuse to place a failed shard if
there aren't enough available top-level fault domains to guarantee
redundancy (for example, 4-way replication, and one rank fails). While
is a nice idea to try to encourage data safety, at the point where a
failure occurs data safety is already at risk. Refusing to rebuild that
data onto a still-living spare target does more harm than good.
This patch enables jump map placement to always find a spare target so
long as unused targets are available in the system, even if that means
that the redundancy available is less than the object class requires.
Already landed on master, this is cherry-pick to 1.2

DAOS-6515 placement: Find spare targets even when fault domains are used (#4906)

---

src/cart/crt_context.c
src/cart/crt_group.c
src/cart/crt_hg.c
src/cart/crt_init.c
src/cart/crt_internal_types.h
src/cart/crt_rpc.c
src/common/misc.c
src/engine/init.c
src/include/cart/types.h
src/include/daos_srv/vos.h
src/object/obj_internal.h
src/object/srv_mod.c
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/rdb/rdb_util.c
src/tests/daos_perf.c
src/vos/tests/vts_checksum.c
src/vos/tests/vts_gc.c
src/vos/tests/vts_io.c
src/vos/vos_io.c

Change latency measurement for update and fetch RPCs to be reported
on per-size range. To do so, VOS had to be changed to report total
I/O size back to object layer.
Move start time calculation to do_obj_ioc_begin() since compound RPCs
bypass obj_ioc_begin().
Add cart counters for URI lookups and failed RPCs.

DAOS-6526 object: refine stats

---

src/client/api/client_internal.h
src/client/api/event.c
src/client/dfs/dfs.c
src/include/daos/event.h
src/tests/suite/dfs_unit_test.c

calling dfs IO function asynchronously can set the ev_error field with -DER codes since those are set in the DAOS lib. The DFS API should always return errno codes to the user, even in the async case, so update the event handling to add an option for converting the DER to errno for the DFS cases.
also fix some bugs where ret value was not set on dfs_readx.

DAOS-7009 dfs: dfs async IO should return errno instead of -der

---

src/vos/ilog.c

In debugging DAOS-5758, I found it useful if we change logs to use
lid, as is done with DTX and to log the failing address associated
with the ILOG_ASSERT_VALID assertion.

DAOS-623 vos: Add some logs that would help with debugging assertion

---

src/client/java/daos-java/pom.xml

SNYK found a vulnerability in the version of netty that we use so we need to
update to the latest version.

DAOS-7004 Java: Update Netty to latest version

---

src/control/cmd/dmg/pretty/system.go
src/control/cmd/dmg/pretty/system_test.go

Make dmg system query [--verbose] output format when displaying results
for a single rank consistent with the output format when displaying
multiple rank results.

DAOS-7010 control: dmg system query output consistent for single rank

---

doc/overview/data_integrity.md
src/client/api/object.c
src/common/checksum.c
src/common/misc.c
src/common/tests/checksum_tests.c
src/container/srv_csum_recalc.c
src/include/daos/checksum.h
src/include/daos/common.h
src/include/daos/task.h
src/include/daos_srv/daos_engine.h
src/include/daos_srv/vos.h
src/include/daos_task.h
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_enum.c
src/object/obj_task.c
src/object/obj_tx.c
src/object/obj_verify.c
src/object/srv_cli.c
src/object/srv_csum.c
src/object/srv_ec_aggregate.c
src/object/srv_obj_migrate.c
src/tests/suite/daos_aggregate_ec.c
src/tests/suite/daos_checksum.c
src/tests/suite/daos_obj.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_test_common.c
src/vos/vos_io.c

Because rebuild only enumerates visible extents,
partial extents must have new checksums calculated
and original extents must be verified.
- In order for rebuild to get the checksum through the
fetch task api, a csum iov param was added. The csums
will be packed similar to enumeration.
- During enumeration, the unpacking of the key
descriptors was changed to not unpack the checksums.
Object migration/rebuild will be responsible for
unpacking the checksums for data that is inlined.
- Added a call in VOS to be able to set the iod_csums
of an io context. This is needed because rebuild
gets the checksums after vos update begin and so
isn't able to provide them at the beginning of the
VOS IO.
- Removed some redundant arg checking in srv_csum.c
Cherry-picked from master  (PR: 3746, commit: …

DAOS-5827 csum: Checksum Verify During Object Enumerate

---

ci/provisioning/post_provision_config_nodes_EL_7.sh
ci/provisioning/post_provision_config_nodes_LEAP_15.sh
src/tests/ftest/launch.py

Call avocado using it's avocado-%python-version name instead of just
bare avocado as an introduction to being able to run it with Python 3.
Install python-macros RPM(s) to support the above.

DAOS-623 test: Add compatibility for new Python 3 Avocado 69.2 RPMs

---

src/client/api/event.c

- exit loop if event error is reported to match original behavior

DAOS-7015 event: proper event handing in case of progress errors

---

src/SConscript
src/include/daos/common.h
src/pool/cli.c
src/security/cli_security.c
src/security/tests/cli_security_tests.c

Security credentials could be grabbed from a core dump or memory dump and used
later if not freed securely. Implement a secure erase of the memory used for
the security credential.
Master-PR: https://github.com/daos-stack/daos/pull/4690

DAOS-6801 Security: Implement Secure Erase for Credential memory (#4690)

---

src/cart/crt_iv.c
src/engine/server_iv.c
src/object/obj_rpc.c

- IV ivc_on_put() should release the value buffer
- Add missing "break" for the switch in obj_reply_map_version_set()
- minor fix for memory leak in failure handling of IV
Signed-off-by: Dmitry Eremin <dmitry.eremin@intel.com>

DAOS-6808 misc: Fix the server IV memmory leak (#4944)

---

src/tests/ftest/control/daos_admin_privileged.yaml
src/tests/ftest/control/daos_agent_config.py
src/tests/ftest/control/daos_agent_config.yaml
src/tests/ftest/control/dmg_network_scan.py
src/tests/ftest/control/dmg_nvme_scan_test.py
src/tests/ftest/daos_test/daos_core_test.py
src/tests/ftest/launch.py
src/tests/ftest/network/cart_self_test.yaml
src/tests/ftest/pool/pool_svc.py
src/tests/ftest/pool/pool_svc.yaml
src/tests/ftest/server/daos_server_config.py
src/tests/ftest/server/dynamic_start_stop.py
src/tests/ftest/util/agent_utils.py
src/tests/ftest/util/apricot/apricot/test.py
src/tests/ftest/util/command_utils.py
src/tests/ftest/util/dmg_utils.py
src/tests/ftest/util/general_utils.py
src/tests/ftest/util/job_manager_utils.py
src/tests/ftest/util/server_utils.py

Resolving issues starting up daos_agent processes resulting from still
executing daos_agent processes from a previous test.  If the previous
test's tearDown() process prematurely exits leaving daos_agent processes
running it causes errors in the next test when it attempts to start
daos_agents on the same hosts.  To resolve this daos_agents will make
use of the same code implored by servers to start the agents once per
test file.  This includes code in launch.py that will stop any
daos_agent.service found running on any host after the test file
completes.

DAOS-6790 tests: Fix daos_agent start-up issues. (#4636)

---

src/tests/ftest/control/dmg_pool_evict.py

DAOS-6928-test: Daos pool list-containers succeed after the pool already been evicted
Updated: control/dmg_pool_evict.py
Skip-nlt: true
Test-tag: dmg_pool_evict

DAOS-6928-test: Daos pool list-containers succeed after the pool already been evicted

---

src/tests/ftest/daos_test/daos_core_test-nvme_recovery.py
src/tests/ftest/util/server_utils.py

List all servers to dmg.yaml hostlist parameter in tests to enable dmg
non-MS commands to run across all hosts.
Master PR: https://github.com/daos-stack/daos/pull/4973
Conflicts:
src/tests/ftest/daos_test/daos_core_test-nvme_recovery.py

DAOS-5621 test: add all test servers in dmg.yaml hostlist

---

src/vos/tests/vts_common.c

By default, daos_racer will automatically create pool for test.
But if the user wants to use existing pool via "-p" option, then
no pool will be created by daos_racer. Under such case, after the
daos_racer finished, it should not destroy such specified pool.

DAOS-6938 tests: keep the pool after racer test if required

---

src/tests/ftest/control/dmg_pool_evict.py

DAOS-6928-test-rel1.2: Daos pool list-containers succeed after the pool already been evicted.
cherry-pick
Updated: control/dmg_pool_evict.py
Skip-nlt: true
Test-tag: dmg_pool_evict

DAOS-6928-test-rel1.2: Daos pool list-containers succeed after the pool already been evicted

---

src/client/api/client_internal.h
src/client/api/event.c
src/client/dfs/dfs.c
src/include/daos/event.h
src/tests/suite/dfs_unit_test.c

also fix some bugs where ret value was not set on dfs_readx.

DAOS-7009 dfs: dfs async IO should return errno instead of -der (#4987)

---

src/client/api/event.c
src/client/api/task.c

crt_progress can sometimes return errors that are not timeout. Those
are not properly handled in synchronous IO calls and cause the private
event to be in an unusable state for following IOs.
This PR checks the error from cart and reinits the private event in
case an error was returned so it can be resused rather then returning
to the user.

DAOS-7015 event: proper event handing in case of progress errors (#4911)

---

src/dtx/dtx_common.c

dlh_future might be freed already in error handling
path, so let's check dlh_future before wait.

DAOS-6995 dtx: check dlh_future in dtx_leader_wait

---

src/cart/crt_hg.c
src/cart/crt_hg_proc.c
src/cart/crt_iv.c
src/cart/crt_rpc.c
src/cart/crt_rpc.h
src/cart/crt_swim.c
src/container/cli.c
src/dtx/dtx_rpc.c
src/include/cart/api.h
src/mgmt/cli_debug.c
src/mgmt/cli_query.c
src/mgmt/srv.c
src/object/cli_shard.c
src/object/obj_rpc.c
src/object/obj_tx.c
src/object/srv_ec_aggregate.c
src/object/srv_obj_remote.c
src/pool/cli.c
src/pool/srv_iv.c

Split this patch into several small patches. This patch is for following:
- Fix reference counting for rpc
- Free memory in an error path

DAOS-6808 rpc: Fix cleanuping resources

---

src/client/java/daos-java/pom.xml

SNYK found a vulnerability in the version of netty that we use so we need to
update to the latest version.
Master-PR: https://github.com/daos-stack/daos/pull/4962

DAOS-7004 Java: Update Netty to latest version (#4962)

---

src/control/server/engine/config.go
src/control/server/engine/exec.go
src/control/server/engine/exec_test.go
utils/nlt_server.yaml
utils/node_local_test.py

By default, all environment variables provided to the engine subprocesses
must be set by the control plane.
An optional per-engine config parameter (env_pass_through) may be set to
pass through variables set before the control plane was started.
Includes an additional patch from Ashley:
DAOS-3105 test: Pass env from NLT to engine though config file.
Now the engine scrubs the environment by default configure NLT to set all
env vars via the config file.

DAOS-3105 control: Scrub engine environment

---

src/control/cmd/dmg/main.go
src/control/logging/defaults.go
src/control/logging/logger.go
src/tests/ftest/util/dmg_utils_base.py

Changes the logger to emit debug on stderr so that we can
get debug output without affecting JSON consumers, and
enables dmg debug output by default.

DAOS-6992 test: Enable debug output for dmg in CI

---

src/placement/tests/jump_map_place_obj.c
src/placement/tests/place_obj_common.c

CID 316617 (resource leak)
CID 316613 (explicit null dereferenced)
CID 316615 (explicit null dereferenced)

DAOS-6678 sdl: Fix various coverity defects in placement tests (#4794)

---

src/tests/ftest/unittest/unittest.py
src/tests/ftest/unittest/unittest.yaml

Ring placement algorithm is obsolete now and the tests are failing
the weekly test run, so removing.

DAOS-6259 test: Remove Ring Placement Test from Weekly Test

---

src/client/java/hadoop-daos/pom.xml

This is the last update we can possible do for the hadoop package. It should
address a significant number of the outstanding security issues found with the
hadoop 3.2.2 dependency.
Master-PR: https://github.com/daos-stack/daos/pull/5066

DAOS-7046 Java: Update Hadoop from 3.2.2 to 3.3.0

---

src/engine/init.c
src/object/srv_mod.c
src/object/srv_obj.c

Cast d_tm_* producer functions to (void) to address Coverity
scan failures, because there is no interest in processing these
return codes at this time.
A separate story exists (DAOS-7032) to change the return type
of these functions to void.
This quick change was requested as an intermediate step towards
that change.

DAOS-7054 Telemetry: Coverity scan fixes

---

src/cart/crt_swim.c
src/cart/swim/swim.c

To avoid mismatch in error codes switch to use DER_ error codes
everywhere.

DAOS-6977 swim: use DER_ error codes everywhere in SWIM

---

src/common/checksum.c
src/common/cont_props.c
src/container/srv_container.c
src/object/cli_obj.c

In the server, on a container open, the output properties are set
based on requested prop bits. This was being skipped when the
container handle was already open. This patch moves where the
requested props are read so they will always be set.

DAOS-6376 container: Get Props with Open Container Handle

---

src/common/btree.c
src/include/daos_srv/vos_types.h
src/vos/ilog.c
src/vos/ilog.h
src/vos/tests/vts_ilog.c
src/vos/tests/vts_pm.c
src/vos/vos_aggregate.c
src/vos/vos_ilog.c
src/vos/vos_ilog.h
src/vos/vos_iterator.c
src/vos/vos_obj.c
src/vos/vos_obj_index.c

The main issue we are trying to prevent is removal of a subtree that isn't empty.
This typically means that we have a bug in aggregation or in the incarnation log
This patch does the following:
Modifies the btree code so that it returns aborted entries during aggregation.
Modify ilog_aggregate so it takes a minor epoch into account. Previously, if we had a punch of a parent, it would remove the child at the same major epoch even if it had updates afterward.
Modify the incarnation log to ensure we take the punch of a parent into account when doing an update
4.Modify aggregation so that we skip aggregation of parent objects if a child iterator hits -DER_TX_BUSY. This avoids removing orphaned subtrees.
Aggregation of the incarnation log was returning -DER_TX_BUSY for entries that are after …

DAOS-6967 vos: Data loss on updates after uncommitted punch (#4899)

---

src/include/daos/object.h
src/object/cli_obj.c
src/object/obj_rpc.c
src/object/obj_rpc.h
src/object/obj_tx.c
src/object/srv_obj.c
src/object/srv_obj_remote.c

*Add shard id to daos_shard_tgt, since st_shard is
the shard index, which is not the id_shard for
reintegrating/extending layout.
*Because shard index and identifier may be different for the object
with reintegrating/extending layout, we need to properly use them
for compounded RPC.
Co-authored-by: Fan Yong <fan.yong@intel.com>

DAOS-6999 object: add shard id to daos_shard_tgt (#4959)

---

src/cart/crt_corpc.c
src/container/srv_container.c
src/engine/server_iv.c
src/pool/srv_pool.c

Ignore -DER_NONEXIST failure for IV during pool connect and
disconnect, in case some ranks are being stopped at that
time.

DAOS-6970 iv: avoid pool connect/disconnect failure

---

src/pool/srv_pool.c
src/rebuild/rebuild_iv.c

If the leader is stepping down/up during rebuild, then
iv_master_rank might be set to -1, so let's check that
in rebuild_iv_ent_update(), and return ENOTLEADER in this
case.
Fix memory cleanup error in ds_mgmt_create_pool().

DAOS-6978 rebuild: return NOTLEADER for -1 master rank (#4921)

---

Jenkinsfile

It was inadvertently included in a commit that was landed.

DAOS-623 ci: Revert use of stage_vm9 clusters

---

src/tests/ftest/unittest/unittest.py
src/tests/ftest/unittest/unittest.yaml

Ring placement algorithm is obsolete now and the tests are failing
the weekly test run, so removing.
Cherry-pick from master: f0d81c841ba27f21eaf8b4eaf8225d1a00f94c85
Master PR: https://github.com/daos-stack/daos/pull/5034

DAOS-6259 test: Remove Ring Placement Test from Weekly Test (#5034)

---

src/dtx/dtx_common.c

dlh_future might be freed already in error handling
path, so let's check dlh_future before wait.

DAOS-6995 dtx: check dlh_future in dtx_leader_wait (#4952)

---

utils/test_memcheck.supp

DAOS-5950 test: remove evt memory leaks suppressions

---

src/utils/daos_hdlr.c

Fix time string issues in the daos container check output.

DAOS-7042 test: adjust daos container check output

---

ci/provisioning/post_provision_config_nodes_EL_7.sh

DAOS-623 build: Do not try and install the python3 package

---

ci/provisioning/post_provision_config_nodes_EL_7.sh

The package is already installed, and for some reason dnf
takes a long time to establist this.

DAOS-623 build: Do not try and install the python3 package (#5127)

---

src/control/cmd/dmg/pretty/storage_test.go
src/control/lib/hostlist/hostlist.go
src/control/lib/hostlist/hostlist_test.go
src/control/lib/hostlist/hostset_test.go

Accept multiple hyphens in hostname when parsing and coalescing
hostlists. Make the assumption that the numeric identifier to be ranged
occurs after the rightmost hyphen.
daos-server-j-0001,daos-server-j-0002,daos-server-j-0001 will now be
compressed into daos-server-j-[0001-0003] by the hostlist library.

DAOS-7074 control: support multiple hyphens in hostlist names

---

src/tests/ftest/pool/rebuild_tests.py
src/tests/ftest/pool/rebuild_tests.yaml

DAOS-6961-test_1.2: Pool rebuild test scripts update work around
Cherry-pick
Updated: pool/rebuild_tests.py
pool/rebuild_tests.yaml
Skip-nlt: true
Test-tag: rebuildmulti rebuildsimple

DAOS-6961-test_1.2:: Pool rebuild test scripts update work around

---

src/engine/drpc_client.c
src/mgmt/srv.c

A user could pass a nonexistent pool ID during normal operation.
This shouldn't be logged as an error.

DAOS-7038 mgmt: Reduce logging noise

---

src/object/obj_internal.h
src/object/srv_obj_migrate.c

Add migration inflight control to avoid using up
all DMA.

DAOS-5279 rebuild: add rebuild inflight control

---

src/common/pool_map.c
src/include/daos/placement.h
src/include/daos/pool_map.h
src/placement/jump_map.c
src/placement/pl_map.c
src/placement/pl_map.h
src/placement/pl_map_common.c
src/placement/ring_map.c
src/placement/tests/jump_map_place_obj.c
src/rebuild/scan.c
src/tests/suite/daos_rebuild_simple.c

1: Add allow_status to layout generation, so only
the target with allow status can be existed in
the layout. And remove op_type/for_reint and some
duplication to make those placement algorithm easier
to follow.
2. During reintegration reclaim process, it needs
to compare the shard id as well, i.e. if shard id
is different, the object needs to be deleted as
well.
3. In particular, fix find_reint and main placement
APIs returning too many items when the pool map
contains simultaneous reintegration, drain, and
failure operations. This is a possible real-world
scenario that would be triggered when a reintegration
is running and something fails.
4. re-enable a few placement tests and add multiple
simultaneous states tests.
Signed-off-by: Byron Marohn …

DAOS-5758 pl: fixes for placement

---

src/cart/crt_corpc.c
src/container/srv_container.c
src/engine/server_iv.c
src/pool/srv_pool.c

1. If the rank is being stopped, then iv operation might
return DER_SHUTDOWN, let's ignore such failure for pool
disconnect/connect.
2. Return GRPVER if the group can not be found in local
SG, so let's the caller retry until the rank is excluded
from the pool map or the pool service is stopped.

DAOS-6970 iv: avoid pool connect/disconnect failure (#4903)

---

src/include/daos_srv/rebuild.h
src/object/cli_obj.c
src/pool/srv_pool.c
src/rebuild/rebuild_internal.h
src/rebuild/srv.c

1. Do not retry internally for migration, because during
system shutdown, if the migration is inside the loop of
retry, for example keeping refreshing the pool map from
the pool leader, then there is no easy way to stop the
migration process inside the client stack. So let's return
all failure to the migration. If there is failure happens,
migration(rebuild) will requeue the job anyway.
2. Add schedule delay time to rebuild task, instead of sleeping
directly in rebuild_task_ult(), since it might blocking the
current rebuild to finish.

DAOS-7056 object: do not retry internally for migration

---

src/pool/srv_pool.c
src/rsvc/srv.c

To optimize pool create latencies, when creating and bootstrapping an
rsvc with an initial membership, this patch lets one replica to start
campaigning without waiting for the election timeout. Also, the patch
replaces the 1 s constant backoff in ds_pool_svc_create with an
exponential one starting from a few milliseconds. The greatest factor of
the latency of a pool create operation will more likely be the creation
of the PMDK pools, as a result.
Master-PR: https://github.com/daos-stack/daos/pull/4873

DAOS-6319 rsvc: Optimize bootstrapping latencies (#4873)

---

src/tests/ftest/container/attribute.py
src/tests/ftest/pool/destroy_tests.yaml

Pool destroy multi-loop test failed on 1.2 CI due to timeout.
Workaround for DAOS-6880 container.list_attr daos_api issue.
Update file: pool/destroy_test.yaml
container/attribute.py
Skip-nlt: true
Test-tag: async_conattribute sync_conattribute destroymutliloop

DAOS-7085-test: pool destroy multi-loop test failed on 1.2 CI due to timeout

---

src/tests/ftest/object/obj_update_bad_param.py

Fix object/obj_update_bad_param.py in release/1.2 failing due to python3 transition
Test-tag: objupdatebadparam

DAOS-7089 test: Fix object/obj_update_bad_param.py in release/1.2

---

src/bio/bio_xstream.c

Large DMA chunk size could suffer from fragmentation problem, small
chunk size will hurt large io performance (any io larger than chunk
size has allocate DMA on-the-fly), so we choose a compromised chunk
size: 8MB.
The initial buffer size is still 256MB, upper limit is 1GB. The
hardcoded upper limit will be removed and being derived from the
configured nr_hugepages in later patch.

DAOS-5279 bio: change DMA chunk size to 8MB

---

src/placement/tests/jump_map_place_obj.c

Since oid has been changed by PR-5075, so the reint
count in PLACEMENT10 needs to be fixed.

DAOS-5758 tests: fix typo in placement test

---

src/tests/ftest/datamover/copy_negative.py

Disable test_copy_space_dcp until the timeout issue
is resolved.

DAOS-6871 test: disable datamover copy_space (#4758)

---

src/tests/ftest/object/object_integrity.py

Fix failing weekly test object_integrity.py on release/1.2
Test-tag: objectvalidation

DAOS-7090 test: Fix failing weekly test object_integrity.py on release/1.2

---

src/tests/ftest/container/attribute.py
src/tests/ftest/pool/destroy_tests.yaml

DAOS-7085-test_rel-1.2: pool destroy multi-loop test failed on 1.2 due to timeout.
Workaround for DAOS-6880 container.list_attr daos_api issue.
Update file: pool/destroy_test.yaml
container/attribute.py
Skip-nlt: true
Test-tag: async_conattribute sync_conattribute destroymutliloop

DAOS-7085-test_rel-1.2: pool destroy multi-loop test failed on 1.2

---

doc/user/container.md

Update dedup limitation of NVMe support on memcpy mode.
Doc-only: true

DAOS-6772 doc: update dedup limitations (#5004)

---

src/bio/bio_buffer.c
src/bio/bio_context.c
src/bio/bio_internal.h
src/bio/bio_xstream.c
src/engine/sched.c
src/include/daos/common.h

spdk_subsystem_fini() won't run to completion if any bdev is
held by open blobs, we set a timeout as temporary workaround.
This patch makes 'dmg system stop' able to shutdown io engine
even when there are leakded ds_pool_child holding opened blob.
Cleanup ds_pool_child on shutdown (even when pool connected,
container opened) will be fixed in other ticket.

DAOS-6783 bio: timeout for spdk_subsystem_fini() (#4977)

---

src/cart/crt_corpc.c
src/mgmt/srv.c
src/mgmt/srv_internal.h
src/mgmt/srv_target.c

1. provide co_post_reply to free memory
2. change corpc to not call co_post_reply on root node.

DAOS-6808 rpc: fix memleak in MGMT_TGT_CREATE corpc (#5037)

---

src/include/daos/placement.h
src/placement/pl_map.c
src/rebuild/scan.c
src/tests/suite/daos_rebuild_simple.c

Avoid single replica object so to avoid those data missing
error(-2026) during migration.

DAOS-7061 rebuild: avoid single replica object

---

src/object/obj_internal.h
src/object/srv_obj_migrate.c

1. Add inflight_max_ult so the total ults per xstream
can not be exceed this value.
2. Add inflight_max_size so the total inflight rebuild
size per xstream can not exceed it, and set it to 25%
of DMA buffer size for the moment, and may adjust it later.

DAOS-5279 rebuild: add rebuild inflight control (#4656)

---

src/bio/bio_xstream.c

Large DMA chunk size could suffer from fragmentation problem, small
chunk size will hurt large io performance (any io larger than chunk
size has allocate DMA on-the-fly), so we choose a compromised chunk
size: 8MB.
The initial buffer size is still 256MB, upper limit is 1GB. The
hardcoded upper limit will be removed and being derived from the
configured nr_hugepages in later patch.

DAOS-5279 bio: change DMA chunk size to 8MB (#5169)

---

src/cart/crt_iv.c
src/container/container_iv.c

Do not use D_ERROR for messages which are expected during
state transitions.

DAOS-6572 test: Silence more IV warnings on -DER_NOTLEADER.

---

src/client/dfs/dfs.c
src/include/daos_fs.h

DAOS-7102 DFS: fix naming between NAME and PATH max values

---

src/include/daos_obj.h
src/object/cli_obj.c
src/object/obj_class.c
src/object/obj_internal.h
src/tests/suite/daos_obj.c

- choose oclass based on set redundancy and redundance factor of container.
- adjust oclass if shard sizing is indicated in hint, otherwise use
max sharding.

DAOS-6632 obj: add support for hints on the oclass generate API (#4831)

---

src/tests/suite/dfs_test.c

Correct a "=" to "+=" when tracking total test failures.

DAOS-7098 test: dfs test increment nr fail

---

src/common/debug.c

By default log mask was set to DLOG_INFO. This is armless on
server side since it will be overidden using log_mask parameter
in config file. But on client side, now that default log stream
is stdout since first PR-3048 for DAOS-4855, it causes
unnecessary messages to be printed on interactive terminal.
So set default log mask to DLOG_ERR instead and leave the choice
to the user to change it using D_LOG_MASK environment variable.
Change-Id: If9b89a81764734ccb11e712fb3efc6a442b2713a

DAOS-4855 debug: set default log mask to DLOG_ERR

---

src/object/obj_ec.h
src/object/srv_obj_migrate.c

1. fix a bug in migrate_fetch_update_parity()
2. change OBJ_EC_MAX_P from 16 to 8 (as 8 is enough for now).

DAOS-6755 obj: fix a bug in migrate_fetch_update_parity

---

src/engine/drpc_client.c
src/pool/srv_pool.c

The normal code-paths for two entries was not cleaning up resources
leading to small leaks every time a pool was queried.

DAOS-6726 engine: Resolve two leaks in the drpc code. (#4782)

---

src/container/srv_target.c

1. Convert sp_fetch_hdls_cond to sp_map_cond. so
all ULTs, which waits for the local pool map can
wait on the condition. Then if the target is excluded
from the pool map, i.e. pool leader will not send
the pool map to these nodes, then these ULT will not
proceed.
2. If the pool map is NULL, then let's do not start
aggregation, since fetch prop by IV will fail anyway.

DAOS-7056 pool: convert sp_fetch_hdls_cond to sp_map_cond

---

src/object/srv_obj.c

just change the error to debug.
Signed-off-by: <Mohamad Chaarawi mohamad.chaarawi@intel.com>

DAOS-7064 object: EEXIST or NOEXIST for conditional ops should not be logged as errors (#5094)

---

src/tests/ftest/security/pool_connect_init.yaml

DAOS-7114-test: security pool_connect_init failed -1025 due to SCM request too small
updated: security/pool_connect_init.yaml
Skip-nlt: true
Test-tag: sec_basic

DAOS-7114-test: security pool_connect_init failed -1025 due to SCM request too small

---

src/tests/ftest/daos_test/daos_core_test-nvme_recovery.py
src/tests/suite/daos_nvme_recovery.c
src/tests/suite/daos_test.h
src/tests/suite/daos_test_common.c

Updated get_server_config() to use the default config file when daos server started with systemd.
Test-tag: daos_core_test_nvme

DAOS-6767 Test: Update the config function to use default server config path. (#4604)

---

src/tests/ftest/erasurecode/ec_rebuild_disabled.py
src/tests/ftest/util/ec_utils.py

DAOS-6661 Test: Fix EC rebuild disabled tests because of recent regression in IOR utile library.

---

src/object/obj_class.c
src/tests/suite/daos_obj.c

- more EC object classes were added, so extend the auto object class
selection to take advantage of that.
- also consider the domain_nr for selecting the EC data cell num

DAOS-6632 object: refine object class settings

---

src/include/daos_srv/rebuild.h
src/pool/srv_target.c
src/rebuild/rebuild_internal.h
src/rebuild/srv.c

Since we already move server to server handle outside
of rebuild, so these poh/coh handles are not needed
anymore.

DAOS-7076 rebuild: remove some obsolete code

---

src/include/daos_obj.h

DAOS-6632 object: fix comment about default sharding hint for oclass

---

src/common/debug.c

By default log mask was set to DLOG_INFO. This is harmless on
server side since it will be overidden using log_mask parameter
in config file. But on client side, now that default log stream
is stdout since first PR-3048 for DAOS-4855, it causes
unnecessary messages to be printed on interactive terminal.
So set default log mask to DLOG_ERR instead and leave the choice
to the user to change it using D_LOG_MASK environment variable.
Master-PR: https://github.com/daos-stack/daos/pull/5174
Change-Id: If9b89a81764734ccb11e712fb3efc6a442b2713a

DAOS-4855 debug: set default log mask to DLOG_ERR (#5174)

---

src/placement/tests/jump_map_place_obj.c

Since oid has been changed by PR-5075, so the reint
count in PLACEMENT10 needs to be fixed.

DAOS-5758 tests: fix typo in placement test (#5191)

---

src/control/fault/code/codes.go

The code groups are organized by area of functionality,
and they need to be in their own const blocks in order
to reset iota between groups. This ensures that changes
to one group does not affect numbering in subsequent groups.

DAOS-7121 control: Separate fault code groups

---

src/tests/ftest/pool/rebuild_tests.py
src/tests/ftest/pool/rebuild_tests.yaml

Due to recent increase of resources on vms the test
started failing and brought up some test code issues
as well as daos handling of server start when resources
available on nodes are limited. As a workaround number
of targets for the test is reduced and the way calculations
are done for expected values is modified a little.
Test-tag: rebuild_tests

DAOS-7115 test: Fix rebuild_test.py failing in CI

---

src/utils/daos.c
src/utils/daos_obj_ctl.c

* Make container parameter optional for daos shell. If
the container parameter is not provided, daos shell
will create a new container.
* Remove epoch from daos shell interface.
Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>

DAOS-5948 daos(8): Integrate obj_ctl utility into the daos utility

---

src/tests/ftest/pool/rebuild_tests.py
src/tests/ftest/pool/rebuild_tests.yaml

Due to recent increase of resources on vms the test
started failing and brought up some test code issues
as well as daos handling of server start when resources
available on nodes are limited. As a workaround number
of targets for the test is reduced and the way calculations
are done for expected values is modified a little.
Conflicts:
src/tests/ftest/pool/rebuild_tests.py
Test-tag: rebuild_tests

DAOS-7115 test: Fix rebuild_test.py failing in CI (#5226)

---

src/tests/ftest/nvme/nvme_object.py
src/tests/ftest/nvme/nvme_object.yaml

The test is failing because of SCM size target size is getting low 9MB with the dataset.
This test has no requirement to use low size so increase enough so the test
should not fail with ENOSPACE.
Updated test to use PCMEM instead of using tmpfs.
Test-tag: nvme_object_multiple_pools

DAOS-6965 Test: Increased the SCM size as recent layout change need more space with current dataset.

---

src/control/server/mgmt_pool_test.go

Use the protocmp sort function to sort protobuf messages
in unit tests.

DAOS-7099 control: Fix unit test sorting

---

src/tests/ftest/osa/osa_offline_drain.py
src/tests/ftest/osa/osa_offline_drain.yaml
src/tests/ftest/osa/osa_offline_reintegration.py
src/tests/ftest/osa/osa_offline_reintegration.yaml
src/tests/ftest/util/daos_utils.py
src/tests/ftest/util/daos_utils_base.py
src/tests/ftest/util/mdtest_test_base.py
src/tests/ftest/util/osa_utils.py

Test-tag-hw-medium: pr,hw,medium,ib2 offline_reintegration_daily
Summary:
(Cherry pick PR:4835 changes on master to 1.2)
- Moved some more common files to osa_utils.py
- Offline reintegration test changes
- Added multiple pool infrastructure to test multiple pools fore offline reintegration
- Test with different object class
- More ranks excluded and reintegrated
- Add mechanism to test exclude, reintegration with aggregation turned on.
- Added daos container check changes.
- Add mdtest thread methods.
- Update offline drain to accomodate osa_utils.py changes.
- Handle multiple containers for OSA testing.
- Test without checksum enabled.

DAOS-6923 test: Offline Reintegration : More tests (cherry_pick 1.2)

---

src/common/SConscript
src/tests/SConscript

Need to generate mpicc and gcc versions of object files to
avoid link errors when compiling libraries and binaries with
mpicc.

DAOS-7129 build: Fix link error with Bullseye

---

src/include/daos/placement.h
src/placement/pl_map.c
src/rebuild/scan.c
src/tests/suite/daos_rebuild_simple.c

Avoid single replica object so to avoid those data missing
error(-2026) during migration.

DAOS-7061 rebuild: avoid single replica object (#5084)

---

src/tests/suite/dfs_unit_test.c

Test-tag-hw-large: daos_core_test_dfs

DAOS-7152 test: reduce the number of threads in dfs unit test

---

src/tests/ftest/util/nvme_utils.py

Blocksize variable need to be int type to get the IOR blocksize
multiple of Transfer size.
Test-tag: nvme_fault

DAOS-7088 Test: Fix NVMe util for calculating IOR block size. (#5136)

---

src/tests/ftest/pool/pool_svc.py

Due to a recent change to the DmgCommand.pool_query() method the
pool/pool_svc.py test fails with a KeyError: 'leader' error. This is
being resolved by this change.
Test-tag: test_pool_svc

DAOS-7062 test: Fixing pool/pool_svc.py KeyError: 'leader' error (#5133)

---

src/control/cmd/dmg/acl_test.go
src/control/cmd/dmg/json_test.go
src/control/cmd/dmg/pool_test.go
src/control/common/test_utils.go
src/control/lib/control/acl_test.go
src/control/server/drpc_test.go

Some unit tests were depositing identically-named files into
the system temporary directory. This could create conflicts
if two instances of unit tests were running on the same
system.

DAOS-7126 test: Create unique files in unit tests

---

src/container/srv_target.c
src/pool/srv_iv.c
src/tests/ftest/cart/util/cart_logparse.py
src/tests/ftest/cart/util/cart_logtest.py

DAOS-6572 engine: Use CDEBUG to silence shutdown warnings. (#4859)

---

src/common/SConscript
src/tests/SConscript

A regression in the build was landed recently that broke builds
when MPI is not available.   This addresses that issue by ensuring
that dc_credit built even when mpi is not present

DAOS-623 build: Fix issue with builds where no MPI is present

---

SConstruct
utils/sl/check_script.py

A new warning started happening recently caused by check_script.py
inserting code in SCons that causes import functions to be
inserted inline
Cleanup pylint warnings in top-level SConstruct

DAOS-623 build: Disable new pylint warning in SCons checks

---

src/tests/ftest/rebuild/cascading_failures.py
src/tests/ftest/rebuild/cascading_failures.yaml
src/tests/ftest/rebuild/read_array.py
src/tests/ftest/rebuild/read_array.yaml

modified:   read_array.py
modified:   read_array.yaml
Skip-nlt: true
Test-tag: rebuildreadarray

DAOS-4757-test: remove skipForTicket rebuild read_array.py

---

src/tests/ftest/rebuild/cascading_failures.py
src/tests/ftest/rebuild/cascading_failures.yaml
src/tests/ftest/rebuild/read_array.py
src/tests/ftest/rebuild/read_array.yaml

modified: cascading_failures.py
cascading_failures.yaml
read_array.py
read_array.yaml
Skip-nlt: true
Test-tag: rebuildreadarray cascading

DAOS-4757-test_rel_1.2: remove skipForTicket rebuild read_array.py

---

src/tests/ftest/object/obj_update_bad_param.py

Fix object/obj_update_bad_param.py failing due to python3 transition
Test-tag: objupdatebadparam

DAOS-7089 test: Fix object/obj_update_bad_param.py

---

src/control/cmd/dmg/storage.go
utils/node_local_test.py

When a dmg storage command e.g. format is run with --json option set
exit with nonzero rc if host errors are contained in response. Output
error related text to stderr not stdout and update nlt to reflect that.

DAOS-7119 control: exit nonzero from dmg storage cmd --json

---

src/common/dts.c
src/include/daos_srv/rdb.h
src/include/daos_srv/vos.h
src/include/daos_srv/vos_types.h
src/mgmt/srv_target.c
src/pool/srv_target.c
src/rdb/rdb.c
src/rdb/rdb_internal.h
src/rdb/rdb_raft.c
src/rsvc/srv.c
src/vos/sys_db.c
src/vos/tests/vts_common.c
src/vos/tests/vts_common.h
src/vos/tests/vts_container.c
src/vos/tests/vts_io.c
src/vos/tests/vts_pool.c
src/vos/vos_internal.h
src/vos/vos_pool.c

A ds_rsvc_start call may involve the following PMEMobjpool operations:
rdb_create
vos_pool_create
pmemobj_create
pmemobj_close	// for vos_pool_create doesn't open the VOS pool
vos_pool_open
pmemobj_open
vos_pool_close
pmemobj_close	// for rdb_create doesn't start the DB
rdb_start
vos_pool_open
pmemobj_open
Each pmemobj_create and pmemobj_open call may take more than 20 ms. To
avoid disrupting swim and rdb_timerd, this patch yields during a
ds_rsvc_start call:
- vos
- Enable rdb to take advantage of PMEMobjpool's concurrent access
protection, so that rdb can yield safely
- Change vos_pool_create to optionally open the VOS pool
- Support opening a VOS pool exclusively
- rdb
- Change rdb_create to start the DB
- Yield after vos_pool_create and vos_pool_open calls
- Yield when loading log …

DAOS-3688 rsvc: Yield during ds_rsvc_start (#5032)

---

src/object/cli_ec.c
src/object/cli_obj.c

One use case in dfs_getxattr() will fetch with NULL sgl to query
iod_size. This patch fix the EC handling for that case.

DAOS-7141 obj: allow size query for EC obj with NULL sgl

---

src/tests/ftest/rebuild/cascading_failures.py

modified: cascading_failure.py
Skip-nlt: true
Test-tag: cascading

DAOS-7150-test: Update cascading_failure.py enable passing testcase.

---

src/tests/ftest/control/dmg_pool_query_test.py

Test-tag-vm: pr,-hw daily_regression,-hw
Test-tag-hw-small: pr,hw,small daily_regression,hw,small
Test-tag-hw-medium: pr,hw,medium,ib2 daily_regression,hw,medium,ib2
Test-tag-hw-large: pr,hw,large daily_regression,hw,large

DAOS-7175 test: Update pool_query_test to use json output

---

src/tests/ftest/daos_test/daos_core_test.yaml

There are a couple I/O tests (daos_test -i) that use EC object class
and rebuild. This currently isn't supported with checksums. DAOS-7182
will re-enable checksums for these tests when it is supported.
Test-tag-hw-medium: pr,hw,medium,ib2,test_daos_io

DAOS-7181 csum: Disable checksum for IO Tests

---

src/tests/ftest/pool/bad_create.py
src/tests/ftest/pool/bad_create.yaml

modified: pool/bad_create.yaml
pool/bad_create.py
Skip-nlt: true
Test-tag: badcreate

DAOS-7176-test: enable pool/bad_create.yaml commented-out testcases

---

src/tests/ftest/rebuild/cascading_failures.py

modify: cascading_failure.py
Skip-nlt: true
Test-tag: cascading

DAOS-7150-test_release1.2: Enable cascading testcase

---

src/tests/ftest/pool/bad_create.py

Enable skipped tests of bad_create.py
Test-tag: badcreate

DAOS-7138 test: Enable skipped tests of bad_create.py

---

src/control/server/ctl_storage_rpc.go
src/control/server/instance_storage.go

The work for DAOS-6004 modified EngineInstance.NotifyStorageFormat()
to accept a context, on the theory that the goroutine should be
cancelable if the parent context is canceled. Normally this is a
good idea, but in this case it was an error because on highly-loaded
systems the gRPC context from StorageFormat() could be canceled before
the starting instance is able to read from the storageReady channel,
leading to a deadlock on startup.
Also bypasses the NVMe format logic if the engine config has no
block devices. This avoids printing a confusing message about
formatting NVMe even though there's no NVMe in the config.

DAOS-7169 control: Fix intermittent deadlock on server startup

---

src/client/pydaos/raw/daos_api.py
src/tests/ftest/container/container_async.py
src/tests/ftest/container/container_async.yaml

When we migrated to Python3, self.cont_input_values.type in daos_api.py was changed to bytes (I think due to Python3's more
strict type checking). This caused an issue in DaosContainer create(). First, the type mismatch caused the container properties
(self.cont_prop) to have some bogus values even though the test doesn't set any container property. This bogus value was passed
into AsyncWorker1 where it creates a container with the API. The tricky part is that this container creation succeeds and
returns 0. (BTW, this may be a bug.) Instead, the following call to daos_eq_poll() (Line 232 of daos_cref.py) gets stuck for
some reason, hence the test hangs. The solutions is to simply fix the types used during the comparisons; changed to string vs.
string.
Also refactored the test. …

DAOS-7086 test: Fixed UTF-8 string and bytes comparison bug to fix container_async.py

---

src/tests/ftest/pool/bad_create.py
src/tests/ftest/pool/bad_create.yaml

Enable pool/bad_create.yaml cancelled testcases for regression
modified: pool/bad_create.yaml
Skip-nlt: true
Test-tag: badcreate

DAOS-7176-test_rel_1.2: enable pool/bad_create.yaml cancelled testcases

---

Jenkinsfile
ci/functional/required_packages.sh
ci/unit/required_packages.sh
utils/docker/Dockerfile.centos.7
utils/docker/Dockerfile.centos.8
utils/docker/Dockerfile.leap.15

These are shared by a number of different branches and so should be
maintained in a single place rather than duplciated across all of the
branches.
Also, fix empty argument in quick-build RPM list.

DAOS-623 ci: Move functions to pipeline-lib

---

src/control/server/storage/bdev/backend.go
src/control/server/storage/bdev/backend_test.go
src/control/server/storage/bdev/provider.go
src/control/server/storage/bdev/runner_test.go

During NVMe prepare step in daos_server init, cleanup leftover hugepages
from previous SPDK sessions that can be left after a crash.
Master PR: https://github.com/daos-stack/daos/pull/5232

DAOS-7103 control: clean leftover hugepages on startup

---

doc/admin/tiering_uns.md

This doc patch documents how to build a Lustre client including
the patch for the fake symlink, and then how to make it work
for DAOS UNS.
Change-Id: I273c981ba8109e4f90712b44bdc220843557387b

DAOS-6412 doc: Lustre client fake symlink patch usage

---

src/container/srv_target.c
src/include/daos_srv/vos.h
src/rdb/rdb_util.c
src/vos/tests/vts_aggregate.c
src/vos/tests/vts_pm.c
src/vos/vos_aggregate.c

Don't try to skip aggregating untouched obj/dkey/akey if the
aggregation is a 'full scan' caused by snapshot deletion.

DAOS-7179 vos: Don't skip aggregation for full scan

---

src/control/cmd/dmg/storage.go
utils/node_local_test.py

When a dmg storage command e.g. format is run with --json option set
exit with nonzero rc if host errors are contained in response. Output
error related text to stderr not stdout and update nlt to reflect that.
Signed-off-by: Tom Nabarro tom.nabarro@intel.com

DAOS-7119 control: exit nonzero from dmg storage cmd --json (#5221)

---

src/include/daos/common.h
src/object/obj_enum.c

Add usage of sgl_idx to support multiple iovs in the sgl
while using obj_enum_iterate.

DAOS-7141 object: Object enum support multiple iovs

---

src/client/pydaos/raw/daos_api.py
src/tests/ftest/container/container_async.py
src/tests/ftest/container/container_async.yaml

When we migrated to Python3, self.cont_input_values.type in daos_api.py was
changed to bytes (I think due to Python3's more strict type checking). This
caused an issue in DaosContainer create(). First, the type mismatch caused
the container properties (self.cont_prop) to have some bogus values even
though the test doesn't set any container property. This bogus value was
passed into AsyncWorker1 where it creates a container with the API. The
tricky part is that this container creation succeeds and returns 0. (BTW,
this may be a bug.) Instead, the following call to daos_eq_poll() (Line 232
of daos_cref.py) gets stuck for some reason, hence the test hangs. The
solutions is to simply fix the types used during the comparisons; changed to
string vs. string.
Also refactored the test. …

DAOS-7086 test: Fixed UTF-8 string and bytes comparison bug (#5317)

---

src/control/server/mgmt_system.go

In the MS joinLoop, a short timeout was used to avoid blocking
the loop if a join request handler exited before receiving the
batched join response. Rather than relying on an arbitrary
timeout value, we should instead pass in the join request's
context so that we can correctly wait for the handler to receive
the response or for the context to be canceled. Either way, it
won't block the join loop indefinitely.

DAOS-7198 control: Use join request context instead of timeout

---

src/common/tse.c
src/common/tse_internal.h

tse_task_complete_callback() possibly be concurrently called by
multi-threads, if one parent task with multiple dep tasks.
This patch add a special dsp lock to protect it, why don't add
a per-task lock is to save task space.

DAOS-7133 tse: add lock to protect tse_task_complete_callback()

---

utils/rpms/daos.spec

- Define an RPM package for the daos_firmware privileged
binary.

DAOS-7019 rpm: Add daos-firmware RPM package

---

src/bio/bio_buffer.c
src/bio/bio_internal.h
src/include/daos_srv/bio.h
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/rdb/rdb_util.c
src/tests/daos_perf.c
src/vos/tests/vts_gc.c
src/vos/tests/vts_io.c
src/vos/vos_io.c

Introduce DMA chunk types: IO, LOCAL & REBUILD, so that each
chunk only serves same type of request having roughly same expected
latency.
We may extend it later to dynamically throttle chunk consuming by
type, based on the current IO pattern & workload.

DAOS-7140 bio: introduce DMA chunk type

---

src/control/lib/control/response.go
src/control/server/harness.go
src/control/server/mgmt_pool.go
src/control/server/storage/types.go

CID 329542: Logically dead code
CID 329530: Dereference after null check
CID 329537: Explicit null dereferenced
CID 529520: Result is not floating-point
Master-PR: https://github.com/daos-stack/daos/pull/5336

DAOS-7162 control: Fix coverity issues

---

src/cart/crt_iv.c
src/engine/init.c
src/engine/server_iv.c

Do IV fini before module unload, because iv_fini will
need some iv class operation, which might be destoryed
during module unload.
Remove some error message in CRT IV, which might be
possible during shutdown process, to satisfy the
NLT checking.

DAOS-7043 engine: switch module unload and iv fini (#5065)

---

src/object/srv_obj_migrate.c
src/tests/suite/daos_rebuild_simple.c

Merged punched recxs under same akey to avoid the
failure of punched recxs migration.

DAOS-7136 object: merged recxs during punch migration (#5300)

---

src/tests/ftest/rebuild/delete_objects.py
src/tests/ftest/util/rebuild_test_base.py
src/tests/ftest/util/test_utils_container.py

Reenable skipped test: delete_objects.py

DAOS-6753 test: Reenable skipped test: delete_objects.py (#5171)

---

src/common/tse.c
src/common/tse_internal.h

tse_task_complete_callback() possibly be concurrently called by
multi-threads, if one parent task with multiple dep tasks.
This patch add a special dsp lock to protect it, why don't add
a per-task lock is to save task space.

DAOS-7133 tse: add lock to protect tse_task_complete_callback() (#5264)

---

src/control/cmd/dmg/auto.go

CID 329566: Dereference after null check

DAOS-7194 control: fix coverity issue

---

src/control/system/raft.go

Avoid a rare race warning which could happen if a system query
happens before the database is restored from snapshot on
server startup.

DAOS-7158 control: Lock system database on restore

---

src/object/cli_ec.c
src/object/cli_obj.c
src/tests/suite/daos_checksum.c

1. Fix obj_fetch EC array with NULL sgl (to query iod_size)
Add test cases to daos_checksum.c
2. Fix a bug of obj_list_get_shard()'s grp_idx calculation.

DAOS-7170 obj: fix bug in dfuse test with EC

---

src/common/cont_props.c
src/container/srv_target.c

ds_get_cont_props() is used to fetch prop and set cont->sc_props,
it should cover all the prop entry types needed for "struct cont_props".
Test-tag-hw-medium: pr,hw,medium,ib2 offline_reintegration_daily

DAOS-7042 cont: fix a bug in ds_get_cont_props()

---

src/control/cmd/dmg/auto.go

CID 329566: Dereference after null check

DAOS-7194 control: fix coverity issues (#5373)

---

src/include/daos_obj.h
src/object/obj_class.c
src/tests/suite/daos_obj.c

- more EC object classes were added, so extend the auto object class
selection to take advantage of that (only when EC hint is explicitly specified).
- also consider the domain_nr for selecting the EC data cell num
- For group number, G1 is used by default; unless user sets array or flat KV feat type, use GX
- add some more test cases

DAOS-6632 object: refine oclass and num grp settings for auto class selection

---

src/rebuild/rebuild_internal.h
src/rebuild/rebuild_iv.c
src/rebuild/srv.c

Do not add complete status inside refresh_iv callback, because
the current rebuild job might need retry. So let's only update
rebuild complete status inside rebuild_task_ult(), and pool query
can get correct rebuild status.

DAOS-7199 rebuild: Do not add complete status in refresh iv

---

.github/CODEOWNERS
Jenkinsfile
ci/unit/required_packages.sh

Since we are using python36 now, we should use the python36 boost when
installing packages for unit testing.

DAOS-623 ci: Use python3 boost for UT packages

---

doc/man/man8/dmg.8
src/control/cmd/daos_agent/procmon.go
src/control/cmd/dmg/pool.go
src/control/cmd/dmg/pool_test.go
src/control/cmd/dmg/system.go
src/control/cmd/dmg/system_test.go
src/control/lib/control/cont.go
src/control/lib/control/mocks.go
src/control/lib/control/network.go
src/control/lib/control/pool.go
src/control/lib/control/pool_acl.go
src/control/lib/control/request.go
src/control/lib/control/rpc.go
src/control/lib/control/rpc_test.go
src/control/lib/control/system.go
src/tests/ftest/container/global_handle.py
src/tests/ftest/pool/bad_connect.py
src/tests/ftest/pool/bad_create.py
src/tests/ftest/pool/destroy_tests.py
src/tests/ftest/pool/evict_test.py
src/tests/ftest/pool/evict_test.yaml
src/tests/ftest/pool/global_handle.py
src/tests/ftest/pool/simple_create_delete_test.py
src/tests/ftest/util/dmg_utils.py
src/tests/ftest/util/test_utils_pool.py

System name can be configured in the server and dmg config files. When
set for dmg, the control API needs to apply the new system name in
protobuf requests that are issued to the gRPC server. This PR applies
the logic for selecting the system name into the control API and takes
the system name from either the supplied request, the supplied control
config or uses the build default (in that order of preference).
In dmg, make all pool and system subcommands config aware and remove the
ability to set the system name from the commandline. Changing the system
name should instead be performed through the dmg config file which will
work reliably for pool and system commands.

DAOS-7066 control: populate system name in control api

---

src/common/debug.c
src/engine/init.c
src/gurt/debug.c
src/gurt/dlog.c
src/include/daos/debug.h
src/include/gurt/dlog.h
src/tests/ftest/cart/util/cart_logparse.py
src/tests/ftest/cart/util/cart_logtest.py

Add ABT ult id and xstream id to daos log. So daos log become
xxxx DAOS[process_id/xs_id/ABT thread ID] xxxxx
xs_id is -1 before tls is initialized, and thread id on client side,
otherwise it will be the xstream ID.
ABT thread ID is the ABT ult ID, 0 otherwise.

DAOS-7137 debug: add ABT ult id and xstream id to log

---

src/control/lib/control/rpc_test.go

Add a loop for checking the number of goroutines after canceling
the context, rather than checking once and then failing. This will
make the test less sensitive to loaded test VMs and will only
fail if a goroutine is truly stuck for 29s (the default test timeout
is 30s).

DAOS-5519 control: Make rpc_test.go less sensitive to CPU load

---

src/object/cli_shard.c
src/object/srv_cli.c
src/object/srv_obj_migrate.c

1. Do checksum verification before merge IOM, since
the checksum verification might need original iom.
2. fix typo for checksum failure report target ep.
3. recalculate single value EC checksum, instead of
using the fetched one.
4. reset the iod & sgl of api argument before the
reasb one are being freed, since they might be reused
during later retry.

DAOS-6383 csum: a few fixes for EC checksum

---

src/common/cont_props.c
src/container/srv_target.c

ds_get_cont_props() is used to fetch prop and set cont->sc_props,
it should cover all the prop entry types needed for "struct cont_props".

DAOS-7042 cont: fix a bug in ds_get_cont_props() (#5237)

---

src/rebuild/rebuild_internal.h
src/rebuild/rebuild_iv.c
src/rebuild/srv.c

Do not add complete status inside refresh_iv callback, because
the current rebuild job might need retry. So let's only update
rebuild complete status inside rebuild_task_ult(), and pool query
can get correct rebuild status.

DAOS-7199 rebuild: Do not add complete status in refresh iv (#5403)

---

src/tests/ftest/pool/multi_server_create_delete_test.py
src/tests/ftest/pool/multi_server_create_delete_test.yaml

Enable negative testcases in pool/multi_server_create_delete_test.py
Modified: pool/multi_server_create_delete_test.py
pool/multi_server_create_delete_test.yaml
Test-tag: multiserver_create_delete

DAOS-7196-test: Enable negative testcases in pool/multi_server_create_delete_test.py

---

src/tests/ftest/pool/multi_server_create_delete_test.py
src/tests/ftest/pool/multi_server_create_delete_test.yaml

Enable negative testcases in pool/multi_server_create_delete_test.py
Modified: pool/multi_server_create_delete_test.py
pool/multi_server_create_delete_test.yaml
Test-tag: multiserver_create_delete

DAOS-7196-test_rel_1.2: Enable negative testcases in pool/multi_server_create_delete_test.py

---

src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/rebuild/srv.c

If enumeration or fetch return -DER_NONEXIST, let's ignore
the failure if the container is destroyed.
For DER_BUSY, let's retry outside scan_request(), so it can
be delay for a few seconds.
Remove incorrect assertion for migrate tls.

DAOS-7192 rebuild: Check if the container is destroyed

---

src/rebuild/srv.c

Fix a typo in rebuild_task_ult, to check if rgt is
NULL before reset done.

DAOS-7202 rebuild: check if rgt is NULL

---

ci/provisioning/post_provision_config.sh
src/tests/ftest/util/apricot/apricot/test.py

And set the git hash abbreviation length to account for different
default lengths across versions and distros.

DAOS-623 ci: Fix a skip-list logic error

---

src/control/fault/code/codes.go
src/control/server/config/faults.go
src/control/server/faultdomain.go
src/control/server/faultdomain_test.go

Since the fault domain callback script is untrusted external
code, restrictions are needed to limit possible security
issues.
This patch adds checks to verify:
- The script is not writable by users other than its owner.
- The script does not have its setuid bit set.
- The script is installed within a specific directory.
- The script is not a symlink.

DAOS-5837 control: Check fault domain callback security

---

src/tests/ftest/container/basic_snapshot.py
src/tests/ftest/object/same_key_different_value.py
src/tests/ftest/pool/permission.py

Added all and daily_regression tags to:
container/basic_snapshot.py
object/same_key_different_value.py
pool/permission.py
Features: basicsnap,samekeydifferentvalue,connectpermission,filemodification

DAOS-6446 Test: Update tags on tests.

---

src/tests/ftest/pool/create_capacity_test.py

Increased pool creation timeout from 3 to 10 seconds.
Test-tag-hw-large: pr,hw,large create_performance

DAOS-6319 Test: AssertionError: Pool creation took longer than 3 seconds

---

src/control/security/pem.go

If both pkcs1 and pkcs8 decoding fail return the error appropriately instead of
squelching it.

DAOS-7162 security: Fix coverity issues found in cert loading code

---

src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/rebuild/srv.c

If enumeration or fetch return -DER_NONEXIST, let's ignore
the failure if the container is destroyed.
For DER_BUSY, let's retry outside scan_request(), so it can
be delay for a few seconds.
Remove incorrect assertion for migrate tls.
Ignore -DER_SHUTDOWN if the container is about to be destoryed
during migration.

DAOS-7192 rebuild: Check if the container is destroyed (#5354)

---

src/mgmt/srv_drpc.c

Fix targets leak in ds_mgmt_drpc_pool_create.

DAOS-7242 coverity: fixes in ds_mgmt_drpc_pool_create

---

src/rebuild/srv.c

Fix a typo in rebuild_task_ult, to check if rgt is
NULL before reset done.

DAOS-7202 rebuild: check if rgt is NULL (#5431)

---

src/control/run_go_tests.sh
src/control/server/mgmt_system_test.go
src/control/system/faultdomain.go

* Add a simple benchmark to determine VM load
* Fix go CFLAGS/LDFLAGS for dev environments
Also includes the following small tweaks made
while profiling the system tests:
* Don't busy-wait on leadership change
* Optimize FaultDomain.Equals()

DAOS-3085 control: Improve run_go_tests.sh

---

src/placement/jump_map.c
src/placement/ring_map.c
src/placement/tests/placement_test.c

DAOS-7239 coverity: various fixes in placement

---

src/object/cli_obj.c
src/object/obj_internal.h
src/object/obj_tx.c

If checksums are only enabled for dedup purpose, then we need
to verify whether the I/O is a candidate for dedup or not. If
not, then do not need to provide a checksum to the server.

DAOS-7216 object: checksums for dedup transactional update

---

src/object/obj_ec.h
src/object/srv_ec.c
src/object/srv_obj.c

Usually, for a standalone EC object update, the parity shard with
the largest index will be used as related DTX leader. But for the
distributed transaction, the leader can be any shard of EC object,
or the leader can be some server that out of the EC object layout.
Under such case, when split EC object update request on the leader
via obj_ec_rw_req_split(), we cannot assume that the leader always
be the last shard, instead, the caller needs to explicitly specify
which one is the leader. Otherwise the sub-request to be sent to
other non-leader may be dispatched to the leader server (locally).

DAOS-7168 object: properly split request for EC object update

---

src/dtx/dtx_common.c
src/dtx/dtx_internal.h
src/dtx/dtx_resync.c
src/dtx/dtx_rpc.c
src/include/daos_srv/dtx_srv.h
src/vos/tests/vts_dtx.c
src/vos/vos_dtx.c

There may be leader switch during the DTX resync and refresh.
If we used stale pool map, then we may find the wrong leader
that may be dead or does not know related DTX status.
If current server is the new DTX leader for DTX refresh, then
we need to do DTX check with other replicas as DTX resync does
to avoid blocking the refresh sponsor for very long time.

DAOS-7073 dtx: use latest pool map for DTX resync and refresh

---

src/dtx/dtx_common.c

When close the container, the sponsor will deregister the container
from the system batched commit ULT. But at that time, the container
may being used by the batched commit ULT. Then only unlink the dbca
data structure is not enough. The close sponsor needs to wait until
batched commit ULT does not handle such container any longer.
Otherwise, the close sponsor may try to destroy the pool by force
after deregister the container from the batched commit ULT.
The patch introduces dtx_batched_commit_args::dbca_refs. The batched
commit ULT and DTX aggregation logic will hold reference on the dbca
data structure when use related container.

DAOS-7173 dtx: wait container to be detached from batched commit ULT

---

src/engine/sched.c

NVMe space pressure needs be taken into account when checking space
pressure level, otherwise, the NVMe space occupied by punched
objs/keys or overwritten records won't be aggressively relaimed even
when NVMe space is running short.
This patch changed check_space_pressure() to return
max(scm_pressure_level, nvme_pressure_level) as pressure level, so
that updates will be throttled and aggregation/GC will be full speed
when either SCM or NVMe is under space pressure. A tolerable downside
of the change is that even when NVMe (or SCM) is soley under pressure,
updates to SCM (or NVMe) will be throttled as well.

DAOS-7217 sched: take NVMe space pressure into account

---

src/common/pool_map.c

Fix for Coverity CID 318157. In gen_pool_buf() map_comp is allocated on
the stack without an initializer. Before this change, in the nodes and
targets loops calling pool_buf_attach(), many map_comp members are
assigned, though not co_flags. The CID cites the first call only.
This patch assigns co_flags=PO_COMPF_NONE before both calls.

DAOS-7241 pool: coverity fix map_comp.co_flags assignment

---

src/tests/ftest/pool/connect_test.py
src/tests/ftest/pool/multi_server_create_delete_test.py

PR #5139 modified the dmg.pool_create() method to remove the
group/system parameter as it is now set in the configuration,
but missed a couple of tests that are not run for PR landings.
Test-tag: poolconnect multiserver_create_delete

DAOS-7066 test: Remove system name from additional tests

---

src/object/cli_obj.c

Including dkey, akeys, iods, sgl validity check for transactional
update and punch before caching them in the DTX client side cache.
Master-PR: https://github.com/daos-stack/daos/pull/5420

DAOS-7215 object: validity check for transactinoal modification

---

src/tests/ftest/daos_test/daos_core_test_dfs.yaml

Test-tag-hw-large: daos_core_test_dfs

DAOS-7152 test: increase timeout of dfs unit test, and run on SCM only

---

src/object/cli_shard.c

During size query of multiple group, only get the size of
the last dkey(maximum), instead of comparing extent of each dkey.

DAOS-7234 object: set size for EC obj with multiple group

---

src/tests/ftest/cart/test_group_np_common.h

swim_seq gets malloc'd, but never freed.  It's only used to print the sequence
of swim states in the swim test -- nowhere else, so freeing it shouldn't cause
any unintended side-effects.

DAOS-7246: Fix Coverity issue in CaRT Test code

---

src/object/cli_shard.c

During size query of multiple group, only get the size of
the last dkey(maximum), instead of comparing extent of each dkey.

DAOS-7234 object: set size for EC obj with multiple group (#5450)

---

Jenkinsfile

Due to what appears to be a bug in Jenkins
(https://issues.jenkins.io/browse/JENKINS-65410) simplify a startsWith()
match for 'weekly-testing*' down into simple == matches for
weekly-testing and weekly-testing-1.2.

DAOS-623 ci: Simplify weekly-testing cron trigger

---

src/utils/SConscript
src/utils/daos.c
src/utils/daos_hdlr.c
src/utils/daos_hdlr.h

This patch make daos_hdlr.c a lib so that the daos util handlers
can be exported. This will be used by new go front-end which will
do the cmd parsing and help.
A few changes have been required to simplify arguments passing for
the go binding.
Change-Id: Idbfd3d43ef466630e84c0b8300f74a2d21a5f7d9

DAOS-6458 utils: make daos_hdlr.c a lib

---

src/common/tests_dmg_helpers.c

As part of dmg_pool_create() flow, following successful execution
of the dmg pool create command, it is expected that the svc_reps
returned by dmg shall be of length > 0. Before this change, that is not
checked in the code, and Coverity CID 313058 suggests that
a use after free could occur with outpool->svc in the daos_test.
This change adds a check in parse_pool_info, returning -DER_INVAL
when the length of the svc_reps json array is less than or equal to 0.
If this were to actually occur, the dmg_pool_create() function would
return, instead of calling the d_rank_list_copy() that the CID suggests
would cause the list to be freed (as part of a realloc).

DAOS-7238 test: check pool create svc_reps length for Coverity issue

---

src/tests/ftest/cart/test_group_np_common.h

Match D_FREE with D_ALLOC (not just plain malloc).  Check for NULL on malloc.

DAOS-7246: Fix Coverity issue in CaRT Test code (2)

---

src/client/dfuse/dfuse_cont.c
src/client/dfuse/dfuse_core.c
src/client/dfuse/ops/lookup.c

Improve error handling and freeing resources correctly.
Most of these changes are the result of the pool-connect rewrite
and were found by coverity.
Co-authored-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>
Conflicts:
src/client/dfuse/ops/lookup.c

DAOS-7123 dfuse: Fix coverity issues arising from recent changes. (#5335)

---

src/tests/ftest/container/attribute.py

Use DaosCommand for list attribute instead of pydaos.
Test-tag: container_attribute

DAOS-6880 Test: container/attribute.py test failed due to Test reports unsupported test status.

---

ci/provisioning/post_provision_config_nodes_LEAP_15.sh

dnf is slow to search/validate already installed packages so remove the two
instances where it's asked to install a package that's already present.  This cuts
the VM deployment time down from 40 to 28 minutes, and increases throughput
on the test nodes by 20%.

DAOS-623 build: Do not attempt to re-install packages on leap VMs.

---

src/tests/suite/daos_nvme_recovery.c

Fix CID 329259 issue.
Test-tag: csum_error_log nvme_io

DAOS-7281 Test:Fix Coverity Issue in NVMe Recovery Test

---

Jenkinsfile

Jenkins seems to be applying the default parameter values to more than
just parameterized build requests, so make the default value for TestTag
empty so that the usual rules for test tag selection will be followed.

DAOS-623 ci: Make TestTag parameter default empty

---

src/control/events/engine.go
src/control/events/engine_failed.go
src/control/events/engine_test.go
src/control/events/pubsub_test.go
src/control/events/ras.go
src/control/events/ras_test.go
src/control/lib/control/system_test.go
src/control/server/ctl_ranks_rpc.go
src/control/server/ctl_ranks_rpc_test.go
src/control/server/instance.go
src/control/server/instance_exec.go
src/control/server/instance_exec_test.go
src/control/server/instance_storage.go
src/control/server/instance_storage_test.go
src/control/server/mgmt_system_test.go
src/control/server/server_utils.go
src/control/system/membership.go
src/control/system/membership_test.go
src/engine/tests/drpc_client_tests.c
src/include/daos_srv/ras.h

Raise RAS event when engine format is required to indicate that
administratior intervention is required (to run dmg storage format).

DAOS-6889 control: add ras event for engine format required

---

src/tests/ftest/cart/test_group_np_common.h

Per @SABollinger:
Since you know the size to malloc at compile time and since the alloc/free is
self-contained to just this function, then why don't you declare the swim_seq
just as a local variable of swim_seq[MAX_SWIM_STATUS] and forget about the alloc
and free. This will make the code cleaner and save time.
..
The description of this bug is not just a simple thing of checking whether the
allocation succeeded. The allocation has, succeeded but when the time came to
free the pointer, the pointer had been modified; i.e. some where in the
execution there was an overwrite of the pointer. This is probably not in your
code. A good method of checking this out is to print the pointer after each
function call. If there is an overwrite of the pointer, then placing the array
on the local stack may …

DAOS-7246 tests: Use local var -- remove malloc/free

---

src/tests/ftest/cart/test_group_np_common.h

swim_seq gets malloc'd, but never freed.  It's only used to print the sequence of swim states in the swim test -- nowhere else, so freeing it shouldn't cause any unintended side-effects.
Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>

DAOS-7246 Fix Coverity issue in CaRT Test code

---

utils/docker/Dockerfile.checkpatch

This was fixed in master in https://github.com/daos-stack/daos/pull/4964 however we do not need/want that full PR on 1.2 so I've just taken the additional package to resolve the pylint issue.

DAOS-623 test: Install unversioned python for pylint.

---

debian/daos-client.install
src/common/tests_dmg_helpers.c
src/control/SConscript
src/control/cmd/daos/container.go
src/control/cmd/daos/main.go
src/control/cmd/daos/pool.go
src/control/cmd/daos/util.go
src/control/drpc/status.go
src/utils/SConscript
src/utils/daos.c
src/utils/daos_hdlr.c
src/utils/daos_hdlr.h
utils/rpms/daos.spec

Add a new Go-based daos utility, temporarily named daos_new in order to
prototype UI updates to the current daos utility.
Currently supports:
`daos_new cont create <pool uuid>`
`daos_new cont destroy <pool uuid> <cont uuid>`
`daos_new pool cont-list <pool uuid>`
TODO:
duns support, etc.

WIP: add daos_new

---

src/object/cli_obj.c

1. Fix obj_fetch EC array with NULL sgl (to query iod_size)
Add test cases to daos_checksum.c
2. Fix a bug of obj_list_get_shard()'s grp_idx calculation.

DAOS-7170 obj: fix bug in dfuse test with EC (#5334)

---

src/include/daos_srv/vos.h
src/pool/srv_target.c
src/rdb/rdb_raft.c
src/vos/sys_db.c
src/vos/tests/vts_gc.c
src/vos/vos_common.c
src/vos/vos_gc.c
src/vos/vos_internal.h
src/vos/vos_tls.h

A pool is attached on GC when user deleted things from the pool,
it will be removed from GC only if the pool is destroyed or has
nothing to be freed. If DAOS is shutting down before GC frees
everything for a alive pool, it will trigger a false assertion
because this pool is still attached on GC.
- This patch removes the false assertion, it can free all pools
still attached on GC while finilizing VOS.
- It also includes a small cleanup for VOS API.
Co-authored-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

DAOS-7165 VOS: free VOS pools attached on GC (#5472)

---

src/engine/sched.c

To make time for aggregation reclaiming overwritten space, the
SCHED_DELAY_THRESH should be larger than the DAOS_AGG_THRESHOLD.

DAOS-7244 sched: bump SCHED_DELAY_THRESH

---

src/common/checksum.c
src/object/cli_shard.c

For EC obj, it possibly get different iod_size (orwo->orw_iod_sizes)
from different shard, should use that for shard csum verify for the
case of partial shards return zero iod_size.

DAOS-7210 obj: use shard iod_size for csum verify

---

src/common/tests_dmg_helpers.c

As part of dmg_pool_create() flow, following successful execution
of the dmg pool create command, it is expected that the svc_reps
returned by dmg shall be of length > 0. Coverity CID 313058 reports
that a length of 0 would result in freeing of outpool->svc and a later
use after free. A fix was attempted in commit 353e115, adding a check
in parse_pool_info(). With this change, another check is made within
dmg_pool_create() closer to the d_rank_list_copy() call that would
free outpool->svc in this (believed to be theoretical) condition.

DAOS-7238 test: another check of pool create svc_reps length

---

src/control/server/config/server_test.go
src/control/server/engine/config_test.go
src/control/server/storage/config.go

Improve validation and expand unit test coverage for bdev parameters in
the server config file.

DAOS-7278 control: improve unit test coverage of bdev config params

---

src/include/daos_obj_class.h
src/object/obj_class_def.c
src/tests/suite/daos_rebuild_simple.c

Add multiple group rebuild tests.
Upgrade inflight I/O to do i/o on the same object,
which is being rebuilt.

DAOS-7254 tests: add multiple group rebuild test

---

src/container/srv_target.c
src/include/daos_srv/evtree.h
src/object/cli_obj.c
src/object/cli_shard.c
src/object/srv_ec_aggregate.c
src/object/srv_obj.c
src/tests/ftest/daos_test/daos_core_test.py
src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/daos_degrade_ec.c
src/tests/suite/daos_rebuild_common.c
src/vos/vos_aggregate.c
src/vos/vos_io.c
src/vos/vos_obj_cache.c

Fix data-corruptions -
1) Fix the diff data process related with agg_update_parity().
2) Fix a bug in obj_ec_rw_req_split() that incorrectly select
tgt oiod on leader server (when leader is not the last parity).
3) Fix bug of ea_oid.id_shard in agg_peer_update_ult()
4) And several other small refining, such some original data type
possibly overflow.
Enhance the code to support -
1) When aggregate leader is not the last parity target,
2) #parity_tgts > 2
Add DEGRADE23: degrade io with multi-containers and aggregation.

DAOS-6755 obj: fix bugs in EC aggregation

---

src/tests/ftest/erasurecode/ec_offline_rebuild.py
src/tests/ftest/erasurecode/ec_offline_rebuild.yaml
src/tests/ftest/erasurecode/ec_online_rebuild.py
src/tests/ftest/erasurecode/ec_rebuild_disabled.yaml

- Update the Skip tickets for EC tests.
- Removed some of the EC objects which we do not want to test anymore.
Doc-only: true

DAOS-6602 Test: Updated skip ticket for EC tests.

---

src/common/lru.c
src/container/container_iv.c
src/container/srv_cli.c
src/container/srv_container.c
src/container/srv_internal.h
src/container/srv_target.c
src/gurt/hash.c
src/include/daos_srv/container.h
src/include/daos_srv/daos_engine.h
src/object/srv_obj.c
src/pool/srv_pool.c
src/pool/srv_target.c

DAOS-6798 pool: fix deadlock on pool destroy (#5494)
There is a deadlock on pool destroy:
1. ds_pool_stop() is called xstream 0 to put the last reference of
ds_pool;
2. On last reference of ds_pool put, it holds 'pool_cache_lock' and
does a collective call to clear ds_pool_child on each VOS xstream;
(see ds_pool_put() -> pool_free_ref())
3. VOS xstreams needs to wait for aggregation ULTs exited before
clearing the ds_pool_child; (see pool_child_delete_one() ->
ds_cont_child_stop_all() -> cont_child_stop())
4. Aggregation ULT may running in EC aggregation code to fetch cont
IV, and that requires calling ds_pool_lookup(), ds_pool_lookup()
needs to acquire 'pool_cache_lock';
This patch removed 'pool_cache_lock' and ensured ds_pool cache being
accessed by xstream 0 only. If VOS xstreams need …

DAOS-6798 pool: fix deadlock on pool destroy (#5494)

---

src/vos/README.md

Thanks to Duan Shibo <duanshibo.d@gmail.com> on the daos mailing list,
an inaccuracy about the external consistency statement is found. This
patch fixes the comment to reflect the current implementation.
Doc-only: true

DAOS-623 vos: Fix consistency statements in README

---

src/object/cli_ec.c
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_ec.h
src/object/obj_enum.c
src/object/srv_obj.c
src/tests/ftest/daos_test/daos_core_test.py
src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/daos_epoch_io.c
src/tests/suite/daos_obj.c

1. Check sgl in punch recxs path and single value path.
2. Since each iod will use separate recovery task, then in
dc_rw_cb(), it might update size to the wrong original iod
(efi_uiods), since it will always update the first iod in
efi_uiods. so let's add ert_oiod for each recovery task, and
update the size in obj_ec_recov_data().
3. mov ec_update_io_size ahead of ec_fetch_set_sgl, since the
updated iod_size will be needed during set_sgl.
4. update iod size for REC2BIG case.
5. in obj_bulk_transfer(), it should compare the end offset of
the transferring buffer with remote bulk size.
6. Add ec object to daos obj CI test.

DAOS-7272 EC: various fixes to make daos_obj pass with EC obj

---

src/tests/ftest/pool/permission.py

Pool was not being created, thus handle object
was not being assigned, fixed.
Test-tag-vm: pr,-hw filemodification

DAOS-7221 Test: PoolPermission: 'NoneType' object has no attribute 'handle'

---

src/cart/crt_corpc.c
src/cart/crt_hg_proc.c
src/cart/crt_rpc.c
src/cart/crt_swim.c
src/common/proc.c
src/container/rpc.c
src/include/cart/api.h
src/include/daos/common.h
src/mgmt/rpc.c
src/object/obj_rpc.c
src/object/obj_rpc.h
src/object/rpc_csum.c
src/object/rpc_csum.h
src/pool/rpc.c
src/rdb/rdb_rpc.c
src/rdb/tests/rpc.c
src/rebuild/rpc.c
src/tests/ftest/cart/test_swim_net.c

Pass proc_op as argument instead of call crt_proc_get_op() inside each proc function.
This give about 6% performance improvements for RPC send/receive.
Fix errno reporting.
For example, daos_perf results:
```
Parameters :
pool size     : SCM: 8192 MB, NVMe: 0 MB
credits       : 16 (sync I/O for -ve)
obj_per_cont  : 1 x 1 (procs)
dkey_per_obj  : 1024
akey_per_dkey : 1
recx_per_akey : 256
value type    : array
stride size   : 4096
zero copy     : no
VOS file      : <NULL>
Running UPDATE test (iteration=3)
```
Master branch show the following results:
```
UPDATE successfully completed:
duration : 36.387225  sec
bandwith : 84.425     MB/sec
rate     : 21612.86   IO/sec
latency  : 46.269     us (nonsense if credits > 1)
Duration across processes:
MAX duration : 36.387225  sec
MIN duration : …
```

DAOS-7155 proc: improve serialization functions

---

src/container/srv_target.c

Use task collective instead thread collective for small size
ULT.

DAOS-6957 container: use task collective for small size ULT

---

src/control/cmd/dmg/auto_test.go
src/control/common/collection_utils.go
src/control/common/mocks.go
src/control/fault/code/codes.go
src/control/lib/control/auto.go
src/control/lib/control/auto_test.go
src/control/lib/hostlist/hostlist_test.go
src/control/server/config/faults.go
src/control/server/config/server.go
src/control/server/config/server_test.go
src/control/server/engine/config.go
src/control/server/engine/config_test.go

Improve validation of port number parameters in the server config file
and expand relevant test coverage.

DAOS-7303 control: improve port number validation in server config

---

src/control/drpc/status.go
src/control/drpc/status_test.go

Use the d_errdesc() helper to provide more context for
a DAOS status code. Output is in line with the C side,
e.g.
DER_NOSPACE(-1007): No space on storage target

DAOS-3835 drpc: Add d_errdesc() to DaosStatus stringer

---

src/dtx/dtx_common.c
src/object/srv_obj.c
src/vos/vos_dtx.c

It is possible that a update RPC changes nothing on the target
but without failure because of empty IOD. Under such case, the
leader should not regard it as DTX entry re-allocation by race;
instead, by checking dth::dth_active, it can know that this is
a noop update, and avoid generating improper "-DER_INPROGRESS"
that will cause the client to retry again and again.

DAOS-7359 dtx: handle noop update properly

---

src/dtx/dtx_common.c

The dtx_aggregate routine was changed to take dbca as an argument but
the calling function is still passing cont.  Modify to pass correct
argument.

DAOS-7244 dtx: Fix a bug in dtx_aggregate

---

doc/user/datamover.md

Document limitations of daos fs copy in v1.2

DAOS-7367 documentation: daos fs copy 1.2 limitation

---

utils/sl/components/__init__.py
utils/sl/prereq_tools/base.py

Try to improve performance of builds and reduce resource
usage by doing a shallow clone of dependencies.

DAOS-623 build: Use shallow clone when building deps.

---

src/object/README.md

- Replace "schema" with "class" because "class" is the terminology we
decided to use.
- Remove detailed description of client side replication because it is a distraction
- Add EC description to single (unstripped) object

DAOS-623 doc: Update README.md

---

doc/admin/installation.md
doc/admin/performance_tuning.md
doc/dev/coding.md
doc/dev/contributing.md
doc/dev/development.md
doc/overview/architecture.md
doc/overview/fault.md
doc/overview/terminology.md
doc/release/support_matrix.md
doc/user/container.md
doc/user/interface.md
doc/user/mpi-io.md
doc/user/spark.md

- Add instructions to install RPMs from packages.daos.io
- Update references to point at release/1.2 branch.
- Remove stale 1.0 and svcl reference.
- Add fio instructions.
- Various cleanups.
doc-only: true

DAOS-5036 doc: update for 1.2

---

src/control/cmd/daos_server/storage.go

User is looked up during storage prepare NVMe when cleaning huge pages
so failure can occur if target user is unset. Before calling in to
provider prepare, set target user to current if unset.

DAOS-7363 control: set target user if empty in local nvme prepare

---

src/rebuild/srv.c

Check if the leader has been changed before IV sync,
otherwise it will confuse cart IV, and cause Assertion
failure.

DAOS-7191 rebuild: check if leader change before IV (#5394)

---

src/control/server/ctl_storage_rpc.go

During dmg storage prepare, before calling in to provider prepare, set
target user to current if unset in protobuf request.

DAOS-7363 control: set target user if empty in remote nvme prepare

---

src/object/srv_obj_migrate.c
src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/daos_rebuild_ec.c

1. During EC rebuild, if inline migrate data(<32 bytes)
needs to re-aligned with cell size, then let's invalidate
the inline data and fetch the data again, to avoid align
the inline data.
2. Add more EC rebuild tests to verify the cross cell
size rebuild.

DAOS-7254 EC: force refetch cross boundry inline data.

---

src/vos/README.md

Some documents and comments about single redundancy group based
DTX leader become stale after introducing distributed transaction
that may cross multiple redundancy groups. This patch refresh them
to avoid confusing.
Doc-only: true

DAOS-7298 doc: refresh DTX leader related document

---

src/client/dfs/README.md
src/client/dfs/dfs.c
src/include/daos/object.h
src/object/cli_obj.c
src/object/obj_class.c
src/object/obj_internal.h

Remove the SX default object class from DFS and generate oids using
the new API for oid generation. this means that if an oclass is not
specified to the DFS API or the DFS container creation:
- we use the container rf factor property to select the oclass for
files and dirs.
- dirs use 1 single group for faster iteration / ls; files use MAX
grps for better read/write BW.

DAOS-7205 DFS: use auto object class selection

---

doc/admin/installation.md

Renamed Leap15.2 to Leap15 on packages.daos.io.
Change documentation accordingly.
doc_only: true

DAOS-5036 doc: fix Leap15 package path

---

Jenkinsfile
src/utils/daos_hdlr.c

- Update instances of "inline void" to "static inline void"
- Add build stage for centos7 + clang + debug
Since the new stage is skipped for non-master runs, it is important to look at the previous runs that had temporary fixes to allow the stage to run on this PR.
- Step 1 - verify new stage fails in CI WITHOUT the code fix
- https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-5542/4/pipeline/90
- Step 2 - verify new stage passes in CI WITH the code fix
- https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-5542/5/pipeline/177
- Step 3 - clean run
- https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-5542/6/pipeline

DAOS-7284 build: Fix compile with debug + clang

---

src/tests/ftest/datamover/dm_dst_create.py

Skip-checkpatch: false
Test-tag: dm_dst_create
- Verify container properties and user attributes of containers
created with dcp.

DAOS-7139 test: datamover container metadata

---

src/utils/daos.c
src/utils/daos_hdlr.c

- Fix case where daos_prop_free() could go out of range of
allocated memory. The daos_prop_t is typically allocated
with the max number of entries during argument parsing,
but the prop can also be allocated later, while parsing
the ACL file and/or setting the ownership for a container.
In that case it is not necessary to allocate the max,
because we know the number of entries needed. args_free()
needs to be general enough for both cases.
- Fix case where the pointer result of the final getline()
call is not freed during ACL file parsing.
- Reset ap->props to NULL after daos_prop_free to avoid
double free
Co-authored-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

DAOS-7379 tools: Fix memory issues in daos tool

---

ci/functional/test_main.sh

The pipeline library has been updated to properly set TEST_TAG for any
of the Test-tag-* pragmas, so it doesn't need to be done in
test_main.sh any more.
Require that the caller set TEST_TAG and error out if they don't.  There
is no reasonable default for this value.

DAOS-623 ci: Update old test_tag logic

---

src/pool/srv_pool.c
src/rebuild/srv.c
src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_rebuild_ec.c
src/tests/suite/daos_rebuild_simple.c

Schedule reclaim job with reintegrate pool map version, to make
sure reclaim happening before any following reintegration,
otherwise, reintegration might get some orphan objects during
scan cause reintegration failure.
Add reintegration into EC object rebuild test to verify this.

DAOS-7254 rebuild: schedule reclaim job by reintegration

---

src/client/dfs/dfs.c
src/tests/suite/dfs_unit_test.c

- do not allow changing file types with mode.
- fix bug to correctly change the mode of the symlink target
rather than the symlink itself.

DAOS-5847 dfs: chmod and setattr fixes

---

src/tests/ftest/pool/pool_svc.py

Added function to wait for pool rebuild to complete.
Pool is now destroyed within the test.
Signed-offby: Omar Ocampo <omar.ocampo.coronado@intel.com>

DAOS-6358 Test: Pool destroy failed with DER_TIMEOUT (#5358)

---

src/vos/vos_dtx.c

1. Locate the committed DTX entry via the ID in the committed blob
instead of always using the first entry in the globla committed
list. The latter one may be not in current committed blob to be
aggregated and freed.
2. Not forget to umem_tx_end() if hit failure during the iteration
for DTX aggregation.
3. Proper error messages to indicate the failures.

DAOS-7244 vos: fix vos_dtx_aggregate

---

src/pool/srv_util.c

With this change, during pool updates the function
ds_pool_check_failed_replicas() will consider daos_engine rank 0
a candidate to replace a failed replica in the pool service.
Previous implementation constraints to avoid rank 0 (at the time,
the only management service instance) have been alleviated
(due to the service now running in the control plane).
This change helps some small pool configurations in which replica
replacement may have only one viable option (rank 0). Using all
available ranks in this situation can prevent - or at least delay
the pool service reaching a state in which it cannot achieve a
Raft quorum.
Test-tag-vm: pr,-hw nocap rebuildwithio pool_svc rebuildwithior test_simple_rebuild test_multipool_rebuild destroypoolrebuild multitarget
Signed-off-by: Kenneth Cain …

DAOS-7282 pool: allow rank 0 as a pool svc replacement rank

---

src/engine/drpc_ras.c
src/engine/init.c
src/include/daos_srv/ras.h

Raise RAS event when clock drift is detected on engine.

DAOS-6328 engine: raise event on clock drift

---

src/object/cli_obj.c
src/tests/suite/daos_obj.c

If an object oid is generated with an integer akey or dkey, object
access with an invalid dkey or akey should not cause a server assert.
This PR adds checks on client side to make sure such operations
fails with -DER_INVAL.

DAOS-7384 object: Prevent server assertion if key invalid

---

src/common/tse.c
utils/test_memcheck.supp

subsequent prep cbs need to be freed (not executed) before we return.
Conflicts:
utils/test_memcheck.supp

DAOS-623 tse: fix mem leak when task is completed in prep cb (#5642)

---

src/dtx/dtx_resync.c
src/dtx/dtx_rpc.c
src/include/daos/placement.h
src/include/daos_srv/pool.h
src/object/cli_obj.c
src/object/obj_tx.c
src/object/srv_ec_aggregate.c
src/placement/pl_map.c
src/pool/srv_pool.c

Refine ds_pool_check_dtx_leader()/pl_select_leader(), not only compare
server rank with leader rank, but also compare oid.id_shard with
leader shard.
For the case that when multiple shards co-locate on same node, previous
ds_pool_check_dtx_leader() possibly cause two shards' caller thread both
treat itself as leader. This may cause problem for EC aggregation.

DAOS-7350 obj: refine ds_pool_check_dtx_leader

---

SConstruct

If --deps-only is set, we do not save the configured options.  This
moves the line to save the options to before the exit.

DAOS-7580 build: Save sticky options before exiting with --deps-only

---

SConstruct
src/SConscript
src/client/api/SConscript
src/client/dfuse/SConscript
src/client/dfuse/test/SConscript
src/common/SConscript

clang is missing some symbols, so force use of gcc until we
can resolve this.

DAOS-5685 il: Force use of gcc for the interception library. (#5193)

---

src/object/srv_ec_aggregate.c

PR #5159 removed this line
if (*status != 0)
rc = *status;
But this ignores the fact that the ult failed.  It was
likely changed due to a coverity warning that it would
potentially get overwritten by subsequent rc settings.
But rather than removing it, change it to a goto.

DAOS-7437 ec: Don't ingore status of patch_holes_ult

---

src/bio/bio_buffer.c
src/bio/bio_bulk.c
src/bio/bio_internal.h
src/common/debug.c
src/engine/srv.c
src/include/daos/debug.h
src/include/daos_srv/bio.h
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/rdb/rdb_util.c
src/tests/daos_perf.c
src/vos/tests/vts_gc.c
src/vos/tests/vts_io.c
src/vos/vos_io.c

To reduce heavy MR operations, BIO caches bulk handles created over
DMA buffer chunks. The cached bulk handles are categorized by bulk
size, one DMA buffer chunk is populated with same sized bulk handles,
if certain sized bulk handles aren't sufficient, it'll try to populate
an idle chunk by growing DMA buffer, or evicting an unused bulk chunk
when the DMA buffer size reached upper bound.
Bulk cached is only used for NVMe I/Os so far. (not for RDMA to SCM),
to bypass bulk cache, specify "srv_bulk_cache" in the bypass env of
"DAOS_IO_BYPASS".

DAOS-6911 bio: bulk handle cache

---

src/object/obj_utils.c
src/tests/suite/daos_rebuild_simple.c

Since rx_idx is 64 bit long, so it should not use
dbtree_key_cmp_rc() to compare the key in recx_key_cmp.
Add tests to verify the large offset IO and rebuild.

DAOS-7441 object: compare rx_idx in recx_key_cmp

---

src/client/api/SConscript
src/engine/SConscript

libdaos.so depends on a conflicting version of libdaos_common
with pmem enabled.  We don't want two versions of
libdaos_common pulled in at the same time.
Instead, statically link all of the libdaos targets into
the daos_engine binary and use libdaos_common_pmem.so
to resolve the needed symbols.

DAOS-6864 build: Don't use libdaos.so from server

---

src/gurt/misc.c
src/include/gurt/common.h
src/object/srv_ec_aggregate.c

Previously, d_ routines were added for allocations, I presume
to avoid situations where we can get mismatched alloc/free
implementations.   Do the same for the other allocation
routines.  Added D_ALIGNED_ALLOC as well.
In staring at code when investigating DAOS-7441, I noticed
that we do a realloc using D_FREE and aligned_alloc in
agg_alloc_buf.  The problem is the semnatics don't match
the else case where the original buffer would not be freed
Modified to make the semantics consistent for if/else clause

DAOS-7618 common: Update allocation macros

---

ci/provisioning/post_provision_config_nodes_EL_8.sh
ci/provisioning/post_provision_config_nodes_LEAP_15.sh
debian/changelog
src/tests/ftest/launch.py
src/tests/ftest/scripts/main.sh
utils/rpms/daos.spec

Whereas RH distros do this automatically, it would appear that one needs
to specifically configure one's specfile to generate debuginfo packages
on SUSE platforms.

DAOS-7222 build: Build debuginfo packages on SUSE

---

src/utils/daos_hdlr.c

When passing a generated cont UUID to filesystem copy
dfs_cont_create was failing. The cont_type was being
set incorrectly when passed to DFS through the container
properties. Also, since uns_resolve_path has been extended
to handle daos://$pool as a destination the cont_clone_hdlr
was updated. The created container UUID is now also being
printed to stdout.

DAOS-7455 daos: fix destination container creation

---

src/common/checksum.c
src/include/daos/checksum.h
src/include/daos/common.h
src/object/cli_ec.c
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_rpc.c
src/object/srv_csum.c
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/rdb/rdb_internal.h
src/tests/suite/daos_degrade_ec.c
src/vos/tests/vts_ilog.c

Degraded EC tests (daos_test -X) where failing with checksums
enabled. There were several small issues that contributed to the
failures. The following are a list of fixes/changes:
- Added csum_iov to objec_recov_cb so that the checksum info is
passed through on ec recovery. While the actual checksums
won't be used, they will be recalcuated, the checksum info
(type, len, etc) is needed.
- Fixed SV shard rebuild
- Reordered iod and csum RPC proc so that iod akey csum is
not skipped. Otherwise, when iod.nr is 0, the akey checksum
wasn't sent
- Range with very large numbers was incorrect because recx_hi
function was returning int instead of uint64
- Addedd calculations of new checksums for EC objects on
migrating bulk or parity
Also added a bunch of logging and defined string formats to help …

DAOS-6381 csum: Fixes for ec, csum, and rebuild

---

src/engine/module.c

While looking into recent leap 15 failures, I noticed the following message:
dss_module_cleanup_all() failed to clean up module mgmt: DER_NOTLEADER(-2008): 'Not service leader'
This caused dss_module_cleanup_all() to abort the cleanup and leave
some modules behind that are still up & running.
The DER_NOTLEADER error will be addressed in a different patch,
but let's continue the cleanup regardless of errors for now.

DAOS-7342 engine: clean up all modules regardless of errors

---

src/common/proc.c

Avoid a crash on free by calling D_FREE, rather than
daos_prop_free().
This crash was caught by fault injection testing.

DAOS-7645 proc: Fix crash on error path.

---

src/control/server/harness.go

Increase fanout rank stop/start request timeouts from 10/30 to 30/60
seconds respectively.

DAOS-7623 control: bump system stop timeout to fix nlt failure

---

src/dtx/dtx_common.c
src/include/daos_srv/container.h
src/include/daos_srv/daos_engine.h

Originally, each xstream has single ULT for DTX async batched commit
in spite of how many containers attached to such xstream. Such model
has some short-comings. For example, if the unique DTX async batched
commit ULT is blocked for some reason when commit for one container,
then the batched commit for all the other containers will be blocked.
That is unreasonable. So in this patch, we start a dedicated ULT for
every container that has something to be batched committed. Such ULT
will automatically exit if become idle (there are no more DTX entries
to be committed at current time). Similarily for DTX aggregation and
stale DTX entries cleanup.

DAOS-7260 dtx: dedicated ULT for each container batched commit

---

src/control/server/instance_drpc.go

Minor change to log how long a dRPC call takes.

DAOS-3688 control: Add timing info to dRPC calls

---

src/client/api/SConscript
src/engine/SConscript
utils/node_local_test.py

libdaos.so depends on a conflicting version of libdaos_common
with pmem enabled.  We don't want two versions of
libdaos_common pulled in at the same time.
Instead, statically link all of the libdaos targets into
the daos_engine binary and use libdaos_common_pmem.so
to resolve the needed symbols.

DAOS-6864 build: Don't use libdaos.so from server (#5706)

---

src/control/cmd/dmg/system.go
src/control/cmd/dmg/system_test.go
src/control/events/engine.go
src/control/events/engine_test.go
src/control/events/generic.go
src/control/events/generic_test.go
src/control/events/psr_update.go
src/control/events/psr_update_test.go
src/control/events/pubsub.go
src/control/events/pubsub_test.go
src/control/events/ras.go
src/control/events/ras_test.go
src/control/lib/control/event_test.go
src/control/lib/control/system.go
src/control/lib/netdetect/netdetect.go
src/control/server/ctl_ranks_rpc_test.go
src/control/server/mgmt_system.go
src/control/server/mgmt_system_test.go
src/control/server/server.go
src/control/server/server_utils.go
src/control/system/membership.go
src/control/system/membership_test.go

Replace system stop/start events with a failure event indicating the
list of ranks that failed to perform the given operation.

DAOS-7264 control: modify controlled stop and start events to indicate failure

---

src/object/srv_obj.c

PR #5666 changed which iods were used to create the io maps. This
reverts that change because it's causing the degraded EC tests
to fail.

DAOS-7655 csum: Fixed for degraded EC tests

---

src/common/tests_dmg_helpers.c

The PR that made the change to dmg landed before the PR
that added by-label support, so we need to fix the helper
to use --label instead of --name.

DAOS-7174 test: Adjust dmg helper to use --label

---

src/container/srv_container.c
src/container/srv_internal.h
src/container/srv_target.c
src/include/daos_srv/container.h
src/include/daos_srv/pool.h
src/include/daos_srv/srv_obj_ec.h
src/object/srv_ec_aggregate.c
src/pool/srv.c
src/pool/srv_target.c

Separe EC agg and VOS aggregate into two ULT, so to avoid iv fetch,
dsc_pool/container open for each call back, and also make sure EC
aggregation can be triggered when snapshot are deleted.
Add DAOS_EC_AGG environment to disable EC aggregation for testing
purpose.

DAOS-7254 aggregate: separate EC aggregate with VOS aggregate

---

doc/user/container.md

- Clarify discussion on implicit owner privileges.
- Add link to security overview discussion about ACL
principals.
- Rename a link that now points to the security overview.
Doc-only: true

DAOS-7517 doc: Clarify container ACL docs

---

src/include/daos_srv/daos_engine.h
src/tests/simple_obj.c
src/tests/suite/daos_dist_tx.c
src/tests/suite/daos_drain_simple.c
src/tests/suite/daos_extend_simple.c
src/tests/suite/daos_kv.c
src/tests/suite/daos_obj.c
src/tests/suite/daos_obj_array.c
src/tests/suite/daos_rebuild_simple.c
src/vos/tests/vts_io.h

Fix compiling warning of -
src/engine/srv.c:102:33: error: '%d' directive output may be truncated
writing between 1 and 10 bytes into a region of size 7

DAOS-7577 engine fix a compiling warning

---

src/object/srv_ec_aggregate.c
src/tests/suite/daos_degrade_ec.c

1. fix a bug in agg_clear_extents().
2. change test case degrade_multi_conts_agg()'s OID set, to avoid
failing one OID's parity shards.
Need to refine err handling for that case later.

DAOS-7350 obj: fix a EC agg bug

---

src/control/cmd/dmg/auto.go
src/control/cmd/dmg/json_test.go
src/control/lib/control/auto.go
src/control/lib/control/auto_test.go

This is an all-or-nothing method so it should return a
valid response or an error, not both. This change simplifies
the error handling required by callers.

DAOS-1968 control: Simplify control.ConfigGenerate() API

---

src/common/pool_map.c
src/include/daos/pool_map.h
src/object/srv_obj_migrate.c
src/pool/srv_pool_map.c
src/rebuild/srv.c

Add co_in_ver to the pool map, which will share with co_out_ver
to indicate when the target is being reintegrated or extended,
so if the leader is switched or restarted, it can retrieve the
extend or reintegrate job version correctly.
Add more debug information to the rebuild process.

DAOS-7480 pool: add co_in_ver to pool map

---

src/mgmt/srv_target.c

In function tgt_create() we have many synchronous/blocking operations.
Those operations can block XS(0) for a long time (more than 16 seconds).
In this patch I try to move most of those operations into separate
asynchronous thread. This avoid blocking of XS(0) for a long time.

DAOS-7340 mgmt: move blocking file I/O into separate thread

---

doc/man/man8/dmg.8
src/control/cmd/daos_admin/handler_test.go
src/control/cmd/daos_server/start.go
src/control/cmd/daos_server/start_test.go
src/control/cmd/dmg/command_test.go
src/control/cmd/dmg/pool_test.go
src/control/cmd/dmg/pretty/pool_test.go
src/control/lib/control/pool_test.go
src/control/run_go_tests.sh
src/control/server/config/server.go
src/control/server/config/server_test.go
src/control/server/ctl_ranks_rpc_test.go
src/control/server/ctl_svc_test.go
src/control/server/harness_test.go
src/control/server/instance_storage_test.go
src/control/server/instance_test.go
src/control/server/mgmt_pool_test.go
src/control/server/storage/bdev/class_test.go
src/control/server/storage/errors.go
src/control/server/storage/mocks.go
src/control/server/storage/provider.go
src/control/server/test_utils.go

With this PR, the src/control/run_go_tests.sh script
works again and is expected to pass. There are still
a number of disabled tests that need to be fixed
once the code stabilizes.

Re-enable most control plane tests

---

src/placement/jump_map.c
src/placement/tests/jump_map_place_obj.c

1. Add extra allow status for remap if addition, exclude and
reintegration happened in the same time.
2. Fix the various issues for placement unit test 17.

DAOS-6981 placement: fix for concurrent addition and rebuild

---

src/client/dfuse/dfuse_core.c
src/include/gurt/common.h

Some new warnings due to strn routines having bounds larger than
the passed buffer

DAOS-623 common: Fix Fedora 34 compiler warnings

---

src/vos/vos_dtx.c

To detect potential data corruption.

DAOS-7665 vos: check committed DTX blob magic when commit

---

src/tests/ftest/util/pool_security_test_base.py

pool_security_acl testcases failed due to unable to parse pool uuid and svcarse pool uuid and svc due to DER_NOSPACE
modified: pool_security_test_base.py

DAOS-6917-test: pool_security_acl testcases failed due to unable to parse pool uuid and svc due to DER_NOSPACE

---

src/mgmt/srv_drpc.c
src/mgmt/tests/srv_drpc_tests.c

Use tierbytes[] in place of scm_bytes and nvme_bytes in context of pool
extend RPC.
Signed-off-by: Lukasz Lasek <lukasz.lasek@intel.com>

DAOS-7722 engine: adapt pool extend for storage tiering

---

src/object/srv_ec_aggregate.c
src/object/srv_obj.c
src/tests/suite/daos_obj_ec.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_test.h

1. If the replicate extent cross the stripe boundry,
after EC aggregation, and parity update, it should only
delete the extent until the stripe boundry.
2. Since VOS extent can not be partial deleted, so let's
use current epoch to delete the replicate extent.
3. Add more tests in daos_obj_ec.c to verify the EC aggregation.

DAOS-7679 EC: various fixes for EC aggregation

---

src/cart/crt_context.c
src/cart/crt_ctl.c
src/cart/crt_group.c
src/cart/crt_hg.c
src/cart/crt_hg.h
src/cart/crt_init.c
src/cart/crt_internal_fns.h
src/cart/crt_internal_types.h
src/cart/crt_rpc.c

- Refactor code for multiprovider support
- Internal structures split between global shared data and per-provider
data.
- Provider identifier moved from crt_context_t to hg_context_t
- For now default provider is used in few places, where provider
cannot be easily derived
- Additional helper functions added to return and set per-provider
data.

CART-970 refactor: Refactor code for multi-provider support

---

src/tests/ftest/ior/crash_ior.py
src/tests/ftest/util/command_utils.py

Observed that the SIGTERM signal is not being propagated through the test
client so the IOR command is never killed in that node and after 5 secs
the parent PID in test server is killed with SIGKILL signal and the test
fails.
Modified the "def stop()" function in command_utils.py source file adding
another SIGTERM signal to the signal_list list. By doing this the
SIGTERM signal is now killing the child process and the test finish
successfully.
Test-tag-hw-medium: pr,hw,medium,ib2 crashior
Signed-off-by: David Maldonado Moreno <david.maldonado.moreno@intel.com>

DAOS-5928: crash_ior.py failure to stop ior command (#4370)

---

src/client/api/container.c
src/common/pool_map.c
src/container/container_iv.c
src/container/srv_container.c
src/container/srv_internal.h
src/container/srv_layout.c
src/container/srv_target.c
src/include/daos/object.h
src/include/daos_cont.h
src/include/daos_prop.h
src/include/daos_srv/container.h
src/include/daos_srv/pool.h
src/include/daos_srv/security.h
src/object/cli_obj.c
src/object/cli_shard.c
src/object/obj_rpc.h
src/object/srv_ec_aggregate.c
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/pool/srv_iv.c
src/pool/srv_target.c
src/security/srv_acl.c
src/tests/ftest/pool/rebuild_tests.py
src/tests/suite/daos_checksum.c
src/tests/suite/daos_container.c
src/tests/suite/daos_degrade_ec.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_rebuild_ec.c
src/tests/suite/daos_test_common.c
src/utils/daos.c

For active opened container handle, DAOS will internally -
1. turn off read/write permission when cont_rf broken
2. turn on  read/write permission when cont_rf recovered by -
reintegrate the failed devices, or by clearing the UNCLEAN container
status - "daos cont set-prop --properties=status:healthy ..."
Add test case to co_rf_simple().
Now DAOS_PROP_CO_STATUS only used for storing the pm_ver for
cont_create, and when user clear the UNCLEAN status. And don't
set UNCLEAN status to RDB to avoid ambiguity when checking
with active container handle.

DAOS-7235 obj: turn off read/write perm when cont_rf broken

---

src/container/srv_cli.c
src/include/daos/common.h
src/include/daos_srv/container.h
src/object/cli_shard.c
src/object/obj_ec.h
src/object/obj_rpc.h
src/object/srv_ec_aggregate.c
src/object/srv_obj.c
src/tests/ftest/daos_test/daos_core_test.yaml

1. add csum support for EC aggregation
(punch and re-replicate not changed now)
2. fix an IOM handling for EC degraded fetch
3. add "--csum_type=crc64" option to test_daos_degraded_ec test

DAOS-5428 EC: add csum support for EC aggregation

---

src/client/dfuse/dfuse_core.c

daos_cont_get_attr() calls are failing with verbs due to memory
registration issue. Temporarily disable dfuse attribute parsing
until this is fixed.

DAOS-7671 dfuse: temporarily disable get_attr

---

src/bio/bio_context.c
src/bio/bio_device.c
src/pool/srv_util.c

The SMD pool info could be inconsistent with global pool info when
pool creation/destroy partially succeed or fail. For exmaple: If a
pool destroy happened after a blobstore is torndown for faulty SSD,
the blob and SMD info for the affected pool targets will be left
behind after the pool being destroyed.
SSD faulty reaction should tolerate such kind of inconsistency,
otherwise, state transition for the SSD won't be able to moving
forward. (The problem usually happens in testing where we mark
device as faulty, then destroy pool, then revive the device for
other tests).
In the future, we may need to have some kind of repairing
tool/mechanism to fix such inconsistency manually/automatically.

DAOS-7012 bio: Tolerate inconsistent SMD info

---

src/tests/suite/dfs_unit_test.c

- use 8 threads instead of 32
Test-tag: hw,large,pr,daos_core_test_dfs

DAOS-7626 test: decrease workload on dfs multithread test

---

src/tests/ftest/util/command_utils.py

DAOS-7605: network/cart_self_test has incorrect bash cmd

---

src/tests/ftest/container/basic_snapshot.yaml

Before this change, in virtual machine (VM)-based testing of the
container basic snapshot tests, those tests with the "8gb" scm_size
were failing due to the Linux oom-killer terminating the daos_engine
process. Currently 12GB of memory is provisoned for the VMs, and recent
changes to the engine implementation consume more memory, likely
putting too much pressure on the VM.
With this change, the "8gb" SCM size test cases are changed to instead
allocate 7GiB of SCM for the pool.
Skip-python-bandit: true
Test-tag-vm: basicsnap
Skip-scan-centos-rpms: true

DAOS-7754 test: reduce large pool SCM size in basic_snapshot

---

src/tests/ftest/util/command_utils.py

Revert "DAOS-7605: network/cart_self_test has incorrect bash cmd"

---

src/vos/vos_io.c

Fix a typo in vos_dedup_dup_bsgl().

DAOS-7766 dedup: Fix a typo

---

src/client/dfuse/dfuse.h
src/client/dfuse/dfuse_core.c
src/client/dfuse/dfuse_fuseops.c

Rather than setting a desired value for max_read or max_write
just go with the defaults.
On newer systems this will default to the largest possible size
for read, on older systems this will default to 4k.
This avoids a issue on CentOS 8 where dfuse was requesting
a larger size for perforamnce, however CentOS 8 has a newer
kernel which checks buffer size and a older libfuse which
doesn't, so requesting a larger size on CentOS 8 results
in the kernel rejecting fuse requests.

DAOS-7492 dfuse: Do not set max_read or max_write.

---

src/tests/ftest/util/command_utils.py

When not using systemctl to run the daos_agent the state checking code
ends up using pgrep to determine if the agent is running.  In the case
where the agent is not running, pgrep returns no stdout which causes a
python exception.  This change remedies this problem.

DAOS-7773 tests: Fixing checking daos_agent state

---

doc/user/spark.md
src/client/java/daos-java/pom.xml
src/client/java/daos-java/src/main/java/io/daos/DaosClient.java
src/client/java/daos-java/src/main/java/io/daos/DaosUtils.java
src/client/java/daos-java/src/main/java/io/daos/dfs/DaosFsClient.java
src/client/java/daos-java/src/main/java/io/daos/dfs/DaosUns.java
src/client/java/daos-java/src/main/java/io/daos/obj/DaosObjClient.java
src/client/java/daos-java/src/main/java/io/daos/obj/DaosObject.java
src/client/java/daos-java/src/main/java/io/daos/obj/IODataDescSync.java
src/client/java/daos-java/src/main/java/io/daos/obj/IOSimpleDDAsync.java
src/client/java/daos-java/src/test/java/io/daos/DaosClientTest.java
src/client/java/daos-java/src/test/java/io/daos/DaosUtilsTest.java
src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosConfigException.java
src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosConfigFile.java
src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSourceAsync.java
src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSourceSync.java
src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSystem.java
src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosHadoopTestUtils.java
src/client/java/pom.xml

- removed dependency to apache commons-lang3.jar 
Without this dependency, hadoop-daos can work with combinations of spark-3.0, spark-3.1, hadoop-2.7 and hadoop-3.2 or later.

DAOS-7669 Reduce third-party jar dependencies to avoid potential jar conflict

---

src/control/lib/control/pool.go
src/control/lib/control/pool_test.go
src/control/lib/control/request.go

If a -DER_GRPVER or -DER_AGAIN are encountered on pool
destroy, try the request again.

DAOS-7718 control: Retry certain pool destroy errors

---

doc/overview/security.md

- Clarify how mutually-authenticated TLS is performed in
the management network.
- Link to NFS standard document where AUTH_SYS authentication
is defined.
Doc-only: true

DAOS-7502 doc: Update Security Model doc

---

debian/changelog
utils/rpms/daos.spec

To avoid packing libdts.so in the devel package.

DAOS-7756 packages: remove *.so from devel packages

---

src/object/cli_obj.c
src/object/obj_internal.h
src/object/obj_tx.c

When do transactional modification, the reference that is held via
obj_req_valid() on the object being modified is leaked. This patch
fixes such issue.

DAOS-7709 object: fix obj leak caused by transactional modification

---

src/tests/ftest/datamover/dm_dst_create.yaml
src/tests/ftest/datamover/dm_large_dir.py
src/tests/ftest/datamover/dm_large_dir.yaml
src/tests/ftest/datamover/dm_large_file.py
src/tests/ftest/datamover/dm_large_file.yaml
src/tests/ftest/datamover/dm_negative.py
src/tests/ftest/datamover/dm_obj_small.py
src/tests/ftest/datamover/dm_posix_meta_entry.py
src/tests/ftest/datamover/dm_posix_meta_entry.yaml
src/tests/ftest/datamover/dm_posix_subsets.py
src/tests/ftest/datamover/dm_posix_symlinks.py
src/tests/ftest/datamover/dm_posix_types.py
src/tests/ftest/datamover/dm_posix_types.yaml
src/tests/ftest/datamover/dm_serial_large_posix.py
src/tests/ftest/datamover/dm_serial_large_posix.yaml
src/tests/ftest/datamover/dm_serial_small.py
src/tests/ftest/util/data_mover_test_base.py
src/tests/ftest/util/data_mover_utils.py

- Added base class for mpifileutils commands.
- Added generic set_params function for all mfu commands.
- Removed old compatibility support for DcpCommand.

DAOS-7157 test: datamover refactor

---

ci/provisioning/post_provision_config_nodes_EL_8.sh

Also hold back dpdk from upgrade on 8.4 as it's newer than what we want
for daos and spdk.

DAOS-623 ci: Upgrade test nodes using upstream baseos

---

src/client/dfs/dfs.c
src/include/daos_fs.h
src/tests/suite/dfs_par_test.c
src/tests/suite/dfs_unit_test.c

- also fix typo in punch to just punch len bytes

DAOS-7777 dfs: dfs_punch() should not set size if offset > file size

---

src/control/common/time_utils.go
src/control/common/time_utils_test.go
src/engine/drpc_ras.c

The RAS timestamps should be in ISO8601 format in order
to ensure that consumers can parse them without special
treatment.

DAOS-7351 control: Fix RAS timestamps

---

src/object/srv_obj.c

When verifying checksums on the server, it should check for the iod
size of 0. There won't be a checksum to verify on a punch.

DAOS-7695 csum: Fix for Server Verify with Punch

---

src/client/pydaos/raw/daos_cref.py

Added within daos_cref.py, each class says which
struct represents in the C code.
Updated the following python classes to reflect the
actual C code:
DaosObjClassAttr
Anchor
Fixed AsyncWorker2 to send an actual value within the CallBack Event.
Test-tag-vm: pr
Test-tag-hw-small: pr
Test-tag-hw-medium: pr
Test-tag-hw-large: pr

DAOS-3873 Test: Remove/Update out of date python test code

---

src/tests/ftest/container/attribute.py

Getting values of non-existent attributes in a container
return and empty value, not a failure.
Test now reflect the behaviour, explicity check for
negative scenarios.
Features: container_attribute

DAOS-7769 Test: Daos container attribute test failures

---

src/common/tests_dmg_helpers.c
src/engine/drpc_client.c

CID 331793 - unchecked return of uuid_parse()
CID 331792 - unchecked return of cmd_push_arg()

DAOS-7174 pool: coverity fixes

---

utils/node_local_test.py

A recent change to dmg meant that some commands return with
an exit code of 0 indicating success.  NLT was incorrectly
returning in this case, so was not retrying format commands.
Remove the incorrect check from NLT, and improve timing of
server startup to make it quicker by not waiting so long
between issueing commands.

DAOS-7653 test: Update NLT to not check for dmg return code.

---

utils/rpms/daos.spec

7ec7f6c changed the build requirement for daos-raft-devel from
= 0.7.3
to
>= 0.7.3
making it difficult to make raft API changes without temporarily
endanger daos master builds. This PR changes the requirement back to
= 0.7.3
for we will bump the minor version when making API changes.

DAOS-6833 utils: Require daos-raft-devel = x.y.z

---

src/tests/suite/daos_rebuild_simple.c

Let's disable inflight I/O verification during reintegration
due to DAOS-7420.

DAOS-7729 tests: disable inflight I/O verification

---

src/control/server/config/server.go
src/control/server/config/server_test.go
src/tests/ftest/util/server_utils_params.py

If the config file uses "servers" instead of "engines", we no
longer start the DAOS server. Instead we provide an error message
instructing the user to change to "engines".

DAOS-6758 control: Don't allow "servers" in cfg file

---

src/object/cli_obj.c

fix bug when dtx is used in object punch that leaves the obj NULL.

DAOS-623 object: Punch with valid dtx does not set the obj pointer

---

src/container/srv_target.c
src/object/obj_rpc.h
src/object/srv_ec_aggregate.c
src/object/srv_obj.c
src/tests/suite/daos_aggregate_ec.c
src/vos/vos_aggregate.c
src/vos/vos_io.c

1. agg_reset_pos() after yield during vos_iterate().
2. fix a bug in cont_ec_eph_reduce() that possibly cause issue for
agg epoch boundary, and then cause vos agg before ec agg.
3. fix a issue in daos_aggregate_ec.c, sleep 40 second cannot ensure
agg happens, enlarge to 45 S.
4. A few other changes for logs.

DAOS-7204 EC: a few fixes for EC agg

---

src/pool/srv_iv.c

pool_iv_map_ent_fetch can potentially write beyond buffer boundaries due
to what seems to be a typo.

DAOS-560 pool: Fix corruption in pool_iv_map

---

src/dtx/dtx_internal.h

Only keep about one million committed DTX entries for handling
resent request. If exceeds the threshold ((1 << 19) * 3), then
trigger DTX aggregation to remove some old ones.
The patch also reduces DTX aggregation time threshold to about
two minutes.
We know that above adjustment may cause more fake failures if
client resent request to the server with heavy load, but that
is unavoidable for current resent handling logic. Since resent
is very rare case, it is better than server out of memory.

DAOS-7845 dtx: keep less committed DTX entries

---

src/object/cli_obj.c
src/object/cli_shard.c
src/tests/suite/daos_degrade_ec.c
src/tests/suite/daos_obj_ec.c
src/tests/suite/daos_test.h

1. Fix a typo of punch size in dfs_punch().
2. In obj_shard_query_key_cb(), it should all shards for EC object
size calculation.
3. Add few test cases for EC object size query.

DAOS-7782 objects: various fixes about EC object size query

---

src/object/cli_shard.c
src/object/srv_ec_aggregate.c
src/pool/srv_pool.c
src/tests/suite/daos_aggregate_ec.c
src/tests/suite/daos_degrade_ec.c
src/tests/suite/daos_obj_ec.c
src/tests/suite/daos_test.h

1. Add EC aggregation degrade test.
2. Do not return failure if peer parity target is DOWN,
to avoid unnecessary error message.

DAOS-7856 tests: add EC aggregation under degraded

---

src/tests/ftest/daos_racer/daos_racer_simple.py
src/tests/ftest/daos_racer/daos_racer_simple.yaml

For checking system stability and robustness.

DAOS-7558 tests: daos_racer for daily_regression and full_regression

---

src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/tests/suite/daos_rebuild_common.c
src/tests/suite/daos_rebuild_ec.c
src/tests/suite/daos_test.h
src/vos/vos_io.c

1. Use correct shard offset inside migrate_enum_unpack_cb()
especially for multiple group object.
2. Add test to verify multiple group ec object rebuild.

DAOS-7826 migrate: Using correct shard offset during migrate

---

src/cart/crt_group.c
src/cart/crt_iv.c

In many places of DAOS code (especially in IV implementation) we have a reading of gp_membs_ver member without any locking.
This patch identifies the instances of access to this struct member without the required locking, and it adds the appropriate lock statements to the code.

DAOS-7211 cart: Fix locking for gp_membs_ver structure member.

---

src/container/srv_container.c
src/tests/suite/daos_container.c

Before this change, the label -> container UUID "cs_uuids" KVS
was maintained (records inserted or deleted) during container
create and destroy. Container set-prop was not accounted for.
With this change, the KVS is updated appropriately under different
set-prop scenarios (set an initial non-default label string,
rename from existing label string to another, etc.).
Also, the daos_test container properties test is updated to
exercise create/set-prop label scenarios.

DAOS-7767 container: update cs_uuids KVS in set-prop

---

SConstruct
src/control/SConscript
utils/docker_nlt.sh
utils/run_in_ga.sh

Also, add a python 2.7 check to the main SConstruct

DAOS-7440 build: Fix rpath in binary builds

---

src/include/daos_errno.h

Otherwise, we need a major version update.

DAOS-623 errno: Deprecate DER_EVICTED rather than removing it

---

src/tests/ftest/control/dmg_telemetry_basic.yaml

The container telemetry tests were timing out on CI VMs, while
otherwise executing normally.
Feature: telemetry

DAOS-7858 test: Increase telemetry test timeout

---

utils/node_local_test.py

There was a conflict between two landings using and changing
an internal API within NLT.  Update the new code to use the
new API.

DAOS-7796 test: Resolve a conflict in NLT internal APIs.

---

src/vos/vos_dtx.c
src/vos/vos_internal.h
src/vos/vos_layout.h

We store the objects' (being modified via the DTX) IDs in committed
DTX entry for EC aggregation. But EC aggregation logic does not use
such information. Then remove the useless information to reduce the
committed DTX entry size.

DAOS-7845 vos: remove useless info from committed DTX entry

---

src/tests/ftest/daos_test/daos_core_test.yaml
src/tests/suite/daos_obj.c

Otherwise, it is confusing since we run the tests with
different object classes

DAOS-623 test: Fix IO test name to include object class

---

src/object/cli_obj.c

That will cause object reference leak.

DAOS-7709 object: missed parameter when caching tx list

---

src/control/lib/control/telemetry.go
src/control/lib/control/telemetry_test.go

- Translate the metric type to and from human-friendly string
values in JSON.
- Improve JSON marshaling and unmarshaling for some related
structures.

DAOS-7797 control: Display JSON metric type as a string

---

src/container/cli.c

Container open should read the EC cell size.

DAOS-7866 container: return EC cell size on open

---

src/vos/vos_dtx.c

PR #5951 added new code in a couple of if clauses that didn't have
brackets.  Fedora warned about this, probably detecting the indentation
and seeing that it didn't match the behavior.

DAOS-623 dtx: Fix a warning caused by a missed bracket in DTX

---

site_scons/prereq_tools/base.py
utils/run_in_ga.sh

Previously, the logic in the function was messed up when multiple
custom targets are used.
For example,
scons test client server
would only build the client.
This fixes the logic in the function so it handles multiple targets
appropriately.

DAOS-623 build: Fix the parser of custom build targets

---

src/control/cmd/daos/property.go
src/control/cmd/daos/util.go

Mistaken holdover from older logic. Don't reset the
number of prop entries before freeing. Fixes an
intermittent segfault in the new daos utility.

DAOS-5692 tools: Don't reset props->dpp_nr

---

src/container/srv_container.c
src/tests/ftest/util/rebuild_test_base.py

When set DAOS_PROP_CO_STATUS container prop, set the clear_stat flag
when user set it as DAOS_PROP_CO_HEALTHY, rather than check whether or
not user passed DAOS_PROP_CO_CLEAR flag or not.
Test-tag-vm: pr rebuild
Test-tag-hw-small: pr rebuild
Test-tag-hw-medium: pr rebuild
Test-tag-hw-large: pr rebuild

DAOS-7914 cont: refine DAOS_PROP_CO_STATUS setting

---

src/tests/ftest/util/dmg_utils.py

When there are no pools in the system, the pools field is
null, not an empty array. Just return early in this case.

DAOS-7863 test: Handle list_pools response with no pools

---

src/control/lib/telemetry/counter.go
src/control/lib/telemetry/counter_test.go
src/control/lib/telemetry/duration.go
src/control/lib/telemetry/duration_test.go
src/control/lib/telemetry/gauge.go
src/control/lib/telemetry/gauge_test.go
src/control/lib/telemetry/promexp/collector.go
src/control/lib/telemetry/promexp/collector_test.go
src/control/lib/telemetry/snapshot.go
src/control/lib/telemetry/snapshot_test.go
src/control/lib/telemetry/telemetry.go
src/control/lib/telemetry/telemetry_test.go
src/control/lib/telemetry/test_helpers.go
src/control/lib/telemetry/timestamp.go
src/control/lib/telemetry/timestamp_test.go
src/gurt/telemetry.c

- Add unit tests for metric types, collector, and Prometheus
exporter.
- Fix bugs and add missing timestamp, snapshot, and duration
functionality in the collector/exporter.

DAOS-7664 test: Add tests for Go telemetry bindings

---

src/control/server/storage/bdev/backend.go
src/control/server/storage/bdev/backend_test.go
src/control/server/storage/bdev/firmware.go

Due to some changes further up the stack, firmware query and
update were trying to initialize the SPDK library twice. Since
we're already doing a storage scan for both, it's possible to
simplify the backend/bindings.

DAOS-2513 firmware: Fix NVMe firmware query/update

---

src/vos/vos_dtx.c

Unify the logic for the case of using former allocated blob to
hold committed DTX entries and the case of allocating new blob
for that. Avoid redundant memcpy() when commit DTX entries.

DAOS-7665 vos: code cleanup for dtx commit

---

doc/admin/deployment.md
doc/dev/development.md
doc/overview/use_cases.md
site_scons/components/__init__.py
site_scons/prereq_tools/base.py
src/cart/crt_init.c

This patch removes the psm2 and psm3 providers from the default DAOS build. The
providers can be enabled on demand by using the `INCLUDE` option.
For instance, to enable the psm2 provider:
`scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=psm2 install`
The list of all the optional components can be retrieved by running the scons
help command.
`scons -h`
¯\_(ツ)_/¯
Signed-off-by: Galen Erso <rogue.developer@outlook.com>

DAOS-7849 build: Remove psm2 from the default build

---

src/client/dfuse/ops/read.c
src/client/dfuse/ops/readdir.c

Avoid a crash on the failure path in readdir(), and check some
return codes in read.

DAOS-7880 dfuse: Fix coverity detected issues.

---

src/control/cmd/daos/acl.go

Add a missing check for an empty ACL in the get-acl case.
Also fixes some error handling in the acl commands when a
pool/container was not specified.
Test-tags: pr container_acl

DAOS-7910 tools: Handle empty ACL in daos cont get-acl

---

site_scons/components/__init__.py
site_scons/prereq_tools/base.py

Allow the component build to specify a pkgconfig file to configure
libraries for the build.

DOAS-7484 build: Use pkgconfig even for built dependencies

---

src/include/daos/checksum.h
src/vos/vos_io.c

The is valid IOD check should check for number of
recxs for array values. If there are none, then
don't expect a checksum during the verify processes.

DAOS-7844 csum: Improve IOD Is Valid Check

---

ci/provisioning/post_provision_config.sh
ci/provisioning/post_provision_config_nodes_EL_8.sh

Fix the test for using the CentOS 8 Appstream Mirror.
Skip-func-stage-centos8: false

DAOS-7813 Build: Fix el8 appstream mirror use

---

src/bio/bio_context.c

Initializing the 'addr' local variable to 0.
Note when left uninitialized, the 'ba_hole' may take a garbage from the stack.
In such scenario, the iov is recognized as a 'hole' and skipped in context of bio_iod_prep/iterate_biov/dma_map_one().
This triggers an assert in ctx of bio_rwv(), after the call to bio_iod_prep() - NULL value in 'bs_iovs[]'.

DAOS-7295 bio: Fixing uninitialized variable in bio_write_blob_hdr().

---

src/control/cmd/dmg/pool.go
src/control/cmd/dmg/pool_test.go
src/control/lib/ui/flags.go
src/control/lib/ui/flags_test.go

For dmg commands that require a pool id, the --pool flag
is now optional and deprecated in favor of placing the
pool id as the last argument.
e.g.
$ dmg pool query my-awesome-pool
$ dmg pool query e3e6fc92-72c8-4c4c-96d0-7e9e4149ab2a

DAOS-7921 control: Add positional pool argument to dmg

---

debian/changelog
debian/control
src/rdb/rdb_raft.c
src/rdb/rdb_rpc.c
utils/rpms/daos.spec

Update raft for the Pre-Vote feature. Increment the RDB RPC protocol
version to prevent mix-version engines from causing further harm.
Signed-off-by: Li Wei wei.g.li@intel.com

DAOS-6833 rdb: Update raft for PreVote

---

src/object/srv_ec_aggregate.c
src/vos/vos_aggregate.c
src/vos/vos_obj.c

1. reset i to 0 for each peer update loop.
2. Remove holdover extent entry inside agg_akey_post().
3. Add a few debug information for the ASSERT in
peer_update_ult().

DAOS-7897 EC: various fixes for EC aggregation

---

src/bio/bio_buffer.c
src/bio/bio_bulk.c
src/bio/bio_internal.h
src/include/daos_srv/bio.h
src/include/daos_srv/vos.h
src/include/daos_srv/vos_types.h
src/object/srv_obj.c
src/object/srv_obj_migrate.c
src/tests/daos_perf.c
src/vos/tests/vts_gc.c
src/vos/tests/vts_io.c
src/vos/vos_io.c

Introduced 4 buffer APIs for caller to acquire a DMA buffer region
and the associated bulk handle.
1. bio_buf_alloc()
- Acquire the buffer descriptor for a DMA buffer region;
2. bio_buf_free()
- Release the DMA buffer specified by buffer descriptor;
3. bio_buf_bulk()
- Get the bulk handle associated with the buffer descriptor;
4. bio_buf_addr()
- Get the buffer address associated with the buffer descriptor;
Re-organized dedup verify code to use DMA buffer instead of
allocating DRAM buffer on-the-fly.

DAOS-7803 bio: Introduce buffer APIs

---

src/control/cmd/daos_agent/infocache.go
src/control/cmd/daos_agent/infocache_test.go

Don't always fall back to the interfaces on NUMA node 0 when
some NUMA nodes don't have any local interface.
Instead, round-robin the allocations across all the NUMA nodes
that have an network device attached.

DAOS-7820 control: RR device on NUMA nodes w/o interface

---

src/common/prop.c
src/include/daos_prop.h

regex seems to be stack hungry. Since the label pattern is pretty simple,
verify it w/o using regex to avoid stack overflow on the server side.

DAOS-7174 prop: don't use regex to check label

---

src/container/cli.c

EC cell size should be packed in dc_cont_glob and
shared via g2l/l2g

DAOS-7856 container: add EC cell size to g2l/l2g

---

ci/provisioning/post_provision_config.sh

Adding -p to the mkdir /scratch command used in CI.

DAOS-6168 tests: Fixing failed mkdir /scratch

---

src/client/dfs/duns.c
src/include/daos_uns.h

- do some light refactoring
- add 2 new APIs to set the labels for some users who want to set
those themselves without the duns_resolve_path() call but later
want to free with duns_destroy_attr()

DAOS-7870 duns: update the duns to use label verify function

---

src/pool/cli.c
src/tests/suite/daos_test_common.c

The container might not be closed during pool disconnect for
some tests, so let's ignore the failure for pool disconnect
during test cleanup, otherwise it might cause CI test failure.
Since the following pool destroy will close the container anyway,
so let's only check the failure there.
Add debug message for pool disconnect EBUSY failure.

DAOS-7687 tests: ignore pool disconnect failure

---

SConstruct
src/common/btree.c
src/include/daos_srv/evtree.h
src/vos/evt_iter.c
src/vos/evt_priv.h
src/vos/evtree.c
src/vos/tests/evt_ctl.c
src/vos/vos_aggregate.c
src/vos/vos_io.c
src/vos/vos_iterator.c
src/vos/vos_obj.c
src/vos/vos_query.c

Move larger data structures to heap since ABT stacks are small

DAOS-7968 vos: Reduce stack usage

---

src/object/cli_obj.c
src/tests/daos_racer.c

1. Add EC object to racer test.
2. Do not allow rx_nr == 0 recx for Array update, which
might cause some trouble for EC object update.

DAOS-7918 EC: add EC object to racer test

---

src/object/srv_ec_aggregate.c
src/tests/ftest/daos_vol/daos_vol.py
src/vos/vos_aggregate.c

There is a situation can cause aggregation processing same item
repeatedly:
1. If aggregation callback yield when iterating in subtrees, it
will set YIELD flag to inform iterator to re-probe when iterator
is back to parent tree;
2. Iterator re-probe in parent tree and locate the last processed
entry, aggregation callback set SKIP flag to inform iterator to
skip iterating into it's subtrees again;
3. However, aggregation credits happened to be exhausted at this
point, so aggregation callback also set YIELD flag & reset the
last processed entry, then yield;
4. Aggregation back from yield and iterator do re-probe to locate
the last processed entry, then this last processed entry is
processed again;
This patch fixed the problem by not reseting the last processed entry
when SKIP flag is …

DAOS-7888 vos: avoid aggregating same entry repeatedly

---

src/tests/suite/daos_container.c

Fix a regression from 01a8c21fa522bf1f08abc3aa24f04c1fc3c3d3fc, which
changed a container label into an invalid value.

DAOS-8009 tests: Fix CONT21

---

src/bio/bio_xstream.c

SPDK subsystem fini usually will take 4 ~ 5 seconds after upgrading,
so we bump the timeout value from 3 seconds to 9 seconds.

DAOS-8011 bio: use larger subsystem fini timeout

---

src/dtx/dtx_common.c
src/dtx/dtx_cos.c
src/dtx/dtx_internal.h
src/dtx/dtx_resync.c
src/dtx/dtx_rpc.c
src/dtx/dtx_srv.c
src/include/daos_srv/dtx_srv.h
src/include/daos_srv/vos.h
src/include/daos_srv/vos_types.h
src/vos/tests/vts_dtx.c
src/vos/vos_dtx.c
src/vos/vos_dtx_iter.c
src/vos/vos_internal.h
src/vos/vos_layout.h

Drop unnecessary members from both the in-DRAM and in-PMEM
committed DTX entry, that will save 32 bytes per committed
DTX entry. Now the size for committed DTX entry in PMEM is
32 bytes, the in-DRAM size is 52 bytes.

DAOS-7930 dtx: reduce the size of committed DTX entry

---

src/include/daos_srv/rsvc.h
src/pool/srv_pool.c
src/rdb/tests/rdb_test.c
src/rsvc/srv.c

When a PS replica is being excluded (due to SWIM events), the attempt to
stop it usually fails after a lengthy RPC timeout. This is a quick and
dirty fix to remove this timeout, allowing rebuild jobs to be queued and
completed faster.

DAOS-7932 pool: Avoid timeouts during map updates

---

src/control/lib/control/storage.go
src/control/lib/control/storage_test.go
src/control/system/database.go
src/control/system/database_test.go
src/control/system/errors.go
src/control/system/mocks.go

This new error will be returned in response to system RPCs
received before the database has started (e.g. when a storage
format is required).

DAOS-7926 control: Add system.ErrUninitialized

---

src/tests/ftest/pool/evict_test.py

DAOS_3836 and DAOS-7337 pool/evict_test reenable.
Test-tag: poolevict

DAOS_3836 test DAOS-7337 pool/evict_test reenable.

---

doc/overview/data_integrity.md
src/common/tests_lib.c
src/include/daos/tests_lib.h
src/include/daos_srv/bio.h
src/include/daos_srv/evtree.h
src/include/daos_srv/vos.h
src/include/daos_srv/vos_types.h
src/vos/README.md
src/vos/evt_iter.c
src/vos/tests/evt_ctl.c
src/vos/tests/vts_checksum.c
src/vos/vos_aggregate.c
src/vos/vos_container.c
src/vos/vos_dtx_iter.c
src/vos/vos_internal.h
src/vos/vos_io.c
src/vos/vos_iterator.c
src/vos/vos_obj.c
src/vos/vos_obj_index.c
src/vos/vos_tree.c

Add the ability to set a bio address as corrupted using the VOS
iter API. This will be necessary for the checksum scrubber
to be able to mark data as corrupted when silent data
corruption is detected.
- Change the vos_iter_delete api to be more generic with an op code
parameter. Will have a delete and corrupt op code for now.

DAOS-5465 csum: Corrupt BIO Address through VOS

---

src/control/cmd/daos/main.go
src/utils/daos_hdlr.c

When a segfault occurs in the C side of the code, the
normal Go stacktrace isn't very helpful for troubleshooting.
This commit will change the crash behavior to produce a core
file when ulimit -c is set appropriately.

DAOS-7948 tools: Produce coredump on crash of daos tool

---

src/bio/bio_xstream.c
src/control/lib/spdk/spdk.go
src/control/lib/spdk/src/nvme_control.c

DPDK exposes telemetry through a temporary socket file.
To avoid telemetry socket file conflicts between runs with different
users, disable DPDK telemetry by passing option override when
initializing SPDK environment. DAOS doesn't use DPDK telemetry.

DAOS-8025 control,bio: disable dpdk telemetry

---

utils/rpms/daos.spec

Changing conditional (Leap 15) doas-client requirement for the
daos-devel package to be a non-conditional requirement.  This is to
ensure matching daos package versions on CentOS 8.

DAOS-623 build: Update daos-devel requirement for daos-client

---

src/control/cmd/dmg/main.go
src/control/lib/control/config.go
src/control/lib/control/config_test.go
src/control/lib/control/errors.go

When reading/parsing a config file results in an error,
don't mask it by using the default config.

DAOS-7927 control: Clean up control config handling

---

src/tests/ftest/erasurecode/ec_ior_smoke.yaml

Now we have some servers in CI which has lower NVMe ~350G capacity.
Removing the -k option to see if that free some space after each IOR run.

DAOS-7795 Test: Fix EC IOR smoke tests.

---

src/bio/bio_buffer.c
src/bio/bio_bulk.c
src/bio/bio_internal.h

When mapping DMA buffer to SCM, it's not necessary to shift start
offset within DMA page according to the SCM offset, that could save
one DMA page when the SCM offset isn't page size aligned.

DAOS-8022 bio: avoid unnecessary page offset

---

src/bio/bio_buffer.c
src/bio/bio_bulk.c
src/bio/bio_internal.h
src/bio/bio_xstream.c

Rebuild test shows that we may still hit DMA chunk allocation failure
(before reaching DMA buffer upper bound) even after using conservative
small upper bound. Such allocation failure could be caused by too
fragmented physical memory (or unexpected overhead from the DPDK
allocator).
- Revert the conservative small upper bound change;
- Tolerate chunk allocation failure by treating it in the same way of
handling reaching DMA upper bound case;
- Fix a defect that could return -DER_AGAIN even buffer grow succeed;

DAOS-7818 bio: tolerate chunk allocation failures
