daos-stack/daos

src/tests/ftest/rebuild/pool_destroy_rebuild.yaml
Increase timeout for pool_destroy_rebuild.py
Test-tag: pooldestroywithio
=> DAOS-7815 test: Increase timeout for pool_destroy_rebuild.py

src/vos/tests/vts_aggregate.c, src/vos/vos_aggregate.c
Corner cases triggered assertion failures with vos aggregation
Need to handle the following cases
1. All entries are removed by aggregation (no logical extents)
2. Removals are after logical extents
=> DAOS-8037 vos: Fix a few bugs with removal aggregation

src/client/dfuse/il/int_posix.c
If the filename starts with /proc, /sys or /dev then do not try the
ioctl to check for dfuse.  This should cut down on I/O calls
which were destined to fail and make program startup in particular
a little bit faster.
Make the logging for non-intercepted files more consistent across
open,fopen and creat.
=> DAOS-8034 il: Do not attempt to use interception on special files.

src/container/srv_target.c, src/include/daos/common.h, src/include/daos/object.h, src/include/daos_errno.h, src/object/cli_ec.c, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_ec.h, src/object/obj_internal.h, src/object/obj_rpc.c, src/object/obj_rpc.h, src/object/srv_ec_aggregate.c, src/object/srv_obj.c, src/tests/ftest/daos_test/daos_core_test.yaml, src/tests/suite/daos_aggregate_ec.c, src/tests/suite/daos_degrade_ec.c
As the aggregation runs asynchronously on different nodes, main race
conditions between aggregation and EC degraded fetch -
1. VOS may merge adjacent exts (now merge to lower epoch)
2. VOS may delete lower epoch ext when it is fully covered by higher
epoch ext.
3. EC aggregation updates new parity exts asynchronously to different
parity nodes
That async operation possibly cause the degraded fetch's data-recovery
handling - shadow epoch corresponding parity/data ext possibly not
readable and then cause silent data corruption in recovery.
This patch refine the handling of EC degraded fetch -
1. for step 1 in EC degraded fetch
if fetch from snapshot and  “snapshot_epoch < vos_agg_eph_boundary”
parity server replies snapshot_epoch as recovery epoch,
Client will carry (ORF_EC_RECOV_SNAP | …
=> DAOS-7879 EC: refine EC degraded fetch with aggregation

src/common/btree.c, src/include/daos/btree.h, src/vos/vos_dtx.c
The committed DTX table is organized as a btree. Normally, during
DTX aggregation, some DTX entries will be removed from such btree.
When some leaf node becomes empty, it will trigger btree rebalance
that will cause some records movement from its sibling leaf nodes.
Such rebalance is good for some potential subsequent btree search.
But for DTX aggregation, we can do some optimization:
For each time DTX aggregation run, it will remove a lot of entries
from the committed DTX table. These entries will be removed one by
one via single transaction. When some leaf node is empty, a record
from sibling leaf node will be moved to current empty node, but it
is quite possible that such record will be the next to be removed.
Then the movement caused by leaf nodes rebalance will cause a lot
of …
=> DAOS-7905 dtx: not rebalance leaf nodes for committed DTX table

src/object/cli_shard.c, src/tests/suite/daos_obj_ec.c
Add a test case for singv and array mixed IO for EC obj.
=> DAOS-7887 obj: fix a bug in dc_rw_cb_csum_verify

src/client/api/pool.c, src/client/dfuse/dfuse_core.c, src/control/cmd/daos/pool.go, src/include/daos/pool.h, src/include/daos/tests_lib.h, src/include/daos_api.h, src/include/daos_pool.h, src/include/daos_task.h, src/pool/cli.c, src/tests/suite/daos_test_common.c, src/utils/daos.c
Change daos_pool_connect() to take a string an a input parameter
that can be interpreted as either a label or a UUID string.
Backward API compatibility is supported via a
macro that will automatically convert a uuid_t (old API) to
a UUID string. We could eventually remove the macro in 2.2 or
beyond.
Backward ABI compatibility is supported by keeping around
the daos_pool_connect() symbol, but not advertising it via the
header files. We could eventually remove this symbol in 2.2.
=> DAOS-7174 pool: take a generic string in pool_connect

src/vos/vos_aggregate.c
If there are no logical extents, phy_ent will be NULL.  Instead,
save the first phy_ent and setup the csum stuff later.
=> DAOS-623 vos: Fix CID 332702 static analysis issue

src/tests/ftest/daos_test/daos_core_test-nvme_recovery.py, src/tests/ftest/daos_test/daos_core_test-nvme_recovery.yaml
All NVMe recovery test will run in Ci and server will
be reformatted for each test until DAOS-5134 is resolved.
Test-tag-hw-medium: daos_core_test_nvme
=> DAOS-8003 Test: Enabled NVMe recovery test in Ci.

src/utils/daos_hdlr.c
There is a semicolon in the container create message
in dm_connect which is part of the fs copy code. This
semicolon in the message causes the dm_dst_create tests
for fs copy to fail, because the functional tests parse
the output and do not expect a semicolon.
=> DAOS-8038 daos: remove semicolon in container create

src/vos/vos_pool.c
When VOS finalize in standalone mode (daos_perf, vos unit tests, etc.),
sysdb will try to delete blob if NVMe is enabled (/etc/daos_nvme.conf
is existing when VOS running in standalone mode), however, sysdb
actually doesn't have blob and bio_xs_context has already torndown
at this moment, so assert on "xs_ctxt != NULL" will be triggered in
bio_blob_delete().
=> DAOS-8027 vos: skip blob deletion properly

src/client/java/hadoop-daos/pom.xml
Upgrade the version of Hadoop to remove some known CVEs.
=> DAOS-8030 hadoop: Update Hadoop from 3.3.0 to 3.3.1

utils/node_local_test.py
Run all of NLT under an exception handler, and if there is an
exception record it as a failed test case which includes both
the stack trace and also the exception string.
This helps a lot with unexpected failures in the NLT code, at
least giving a stack trace, and depeending on the exception
a text description of the problem as well.
=> DAOS-623 test: Add better exception handling to NLT.

src/common/fail_loc.c, src/object/obj_rpc.h, src/object/srv_obj.c, src/tests/suite/daos_degrade_ec.c, src/tests/suite/daos_obj_ec.c, src/tests/suite/daos_test.h
1. Add snapshot EC object test.
2. Do not need assert invalid fail_loc, since client
may send any fail_loc to set by server. Just ingore
the bad fail_loc for now.
3. Remove few obsolote and temporary EC aggregation code
after new object remove function support.
4. Add extra replica check on replica.
=> DAOS-7978 tests: add snapshot for EC object test

src/pool/srv_pool.c
Change D_ERROR to D_DEBUG when remote pool map buffer capacity is
exceeded. The situation is resolved internally by retrying with a
larger buffer. This change resolves an NLT warning.
=> DAOS-5902 pool: no error when buf cap exceeded before retry

src/client/api/container.c, src/client/dfuse/dfuse_core.c, src/container/cli.c, src/control/cmd/daos/container.go, src/include/daos/container.h, src/include/daos_cont.h, src/include/daos_pool.h, src/include/daos_task.h, src/tests/suite/daos_container.c, src/tests/suite/daos_test_common.c, src/utils/daos.c
Change daos_cont_open/destroy() to take a string an a input
parameter that can be interpreted as either a label or a UUID.
Backward API compatibility is supported via a macro that will
automatically convert a uuid_t (old API) to a UUID string.
We could eventually remove the macro in 2.2 or beyond.
Backward ABI compatibility is supported by keeping around
the daos_cont_open/destroy symbols, but not advertising them via
the header files (the macro overrides it). We could also remove this
symbol at some point when all users have recompiled against 2.x
code.
Handle backward compatibility for the task API too.
Remove daos_cont_open/destroy_by_label() operations
=> DAOS-7174 cont: a take string on cont_open/destroy

src/vos/vos_io.c
ioc->ic_io_size is used by telemetry to maintain how much data
was fetched/updated from the engine. It is currently increased
for array value. This patch also covers single value.
=> DAOS-8103 vos: increment ic_io_size for single value

debian/changelog, debian/control, utils/rpms/daos.spec
Update raft to fix slow leader re-elections introduced by Pre-Vote.
=> DAOS-8023 utils: Update raft to fix slow re-elections

src/tests/ftest/control/dmg_pool_query_test.py
dmg pool query JSON output format was updated to use tier_stats instead of
scm/nvme.
Also call TestPool.set_query_data() instead of using dmg_command.
Test-tag: pool_query_basic pool_query_inputs pool_query_write
=> DAOS-8105 test: Updated control/dmg_pool_query_test.py to use tier_stats

src/cart/crt_utils.h
In file included from src/cart/crt_utils.c:18:
src/cart/crt_utils.c: In function ‘write_completion_file’:
src/cart/crt_utils.h:17:38: warning: declaration of ‘opts’ shadows a global declaration [-Wshadow]
17 |                 struct test_options *opts;                              \
|                                      ^~~~
src/cart/crt_utils.c:117:9: note: in expansion of macro ‘DBG_PRINT’
117 |         DBG_PRINT("Wrote completion file: %s.\n", completion_file);
|         ^~~~~~~~~
src/cart/crt_utils.c:21:21: note: shadowed declaration is here
21 | struct test_options opts = { .is_initialized = false };
|                     ^~~~
See https://github.com/daos-stack/daos/runs/3088961924#step:5:437
Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>
=> CART-963 tests: avoid redefinition of opts

src/bio/bio_internal.h, src/bio/bio_monitor.c, src/bio/bio_xstream.c, src/engine/srv.c, src/include/daos_srv/bio.h, src/vos/vos_common.c
Bypass health monitor setup when dss_nvme_bypass_check is set.
=> DAOS-8060 bio: bypass health monitor setup

src/common/misc.c, src/include/daos/common.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_enum.c, src/object/obj_internal.h, src/object/obj_verify.c, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/tests/suite/daos_rebuild_ec.c
1. Add EC object check to daos_obj_verify.
2. Update object enumeration sgl buffer size for bulk transfer.
3. Do not need prepare the shard sgl buffer for spec shard object
enumeration, since there is only one shard, which can use the input
sgl directly.
4. Since object enumeration will always return oid, so let's use
num < 2 to see if the enumeration buffer is empty.
=> DAOS-8029 object: add EC object check to daos_obj_verify

src/vos/ilog.c, src/vos/ilog.h, src/vos/tests/vts_ilog.c, src/vos/vos_ilog.c, src/vos/vos_layout.h
Use a simple array for the incarnation log rather than a
btree.  Simplifies fetch path so it should improve performance
a little for the delete operations
=> DAOS-7878 vos: Simplify ilog data structure

src/control/server/config/server.go
In the case that a legacy config file format (without storage tiers) has
been supplied with class NVMe and an empty device list, avoid creating a
bdev tier when converting from legacy to current storage config
structure. This change reinstates previous behavior.
=> DAOS-7673 control: don't create tier from legacy cfg if devlist empty

src/object/cli_ec.c, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_internal.h
Refine obj_ec_seg_pack() to merge segments when possible, that is
helpful to reduce #segments in bulk handle for one-full-stripe IO.
Change reasb_req's spinlock to mutex as some cases may allocate memory
when holding the lock.
=> DAOS-5898 EC: merge adjacent segments in EC sgl reassemble

src/control/server/server_utils.go, src/control/server/server_utils_test.go
Added some missing unit test cases which would have revealed
the boneheaded mistake in the config checking logic. Also
simplified the logic to make it easier to understand.
=> DAOS-8102 control: Fix SRX config enforcement

src/control/lib/telemetry/promexp/collector_test.go, src/control/lib/telemetry/test_helpers.go
- Ensure different Go package test suites don't choose the same
shmem IDs when they might run concurrently.
=> DAOS-8112 test: Fix conflict in telemetry unit tests

src/include/daos_srv/daos_engine.h, src/object/cli_obj.c, src/object/obj_enum.c, src/object/srv_obj.c, src/tests/suite/daos_rebuild_simple.c
Return the enough size for object enumeration for KEY2BIG
case, otherwise migration might be in the endless enumeraion
retry.
Add test case for big key rebuild to verify this.
=> DAOS-8029 objects: some fixes for large key migration

src/client/dfs/duns.c, src/client/java/daos-java/src/main/java/io/daos/dfs/uns/PropType.java, src/client/java/daos-java/src/main/native/include/DunsAttribute.pb-c.h, src/client/java/daos-java/src/main/resources/DunsAttribute.proto, src/client/pydaos/raw/daos_api.py, src/common/prop.c, src/container/srv_layout.c, src/include/daos/common.h, src/include/daos_prop.h, src/utils/daos_hdlr.c, src/utils/daos_hdlr.h
Add container types for new I/O middleware developped over DAOS.
Fix typo in DAOS_PROP_CO_LAYOUT_UNK(N)OWN.
=> DAOS-8103 cont: add new container types

src/bio/bio_monitor.c
Fix a defect of double free on 'bdev_io' in Intel SMART data
collecting code.
=> DAOS-8101 bio: avoid double free on bdev_io

src/control/cmd/daos/main.go, src/control/cmd/dmg/json_test.go, src/control/cmd/dmg/main.go
Both daos and dmg have commands related to containers, so
both should allow the same container/cont aliases for the
commands.
Also cleans up the generated help text and aliases for other
dmg commands.
=> DAOS-8073 control: Tool command parity

src/client/dfs/dfs.c, src/client/dfs/dfs_internal.h, src/client/dfuse/dfuse.h, src/client/dfuse/dfuse_core.c, src/client/dfuse/ops/fgetattr.c, src/client/dfuse/ops/lookup.c, src/client/dfuse/ops/rename.c, src/client/dfuse/ops/setattr.c, src/client/dfuse/ops/unlink.c, utils/node_local_test.py
Use the oid option to dfs when calling move or rename to detect
what if any file has been removed, and check for that file in
the local inode table.
When files have been moved or are observed at a different location
to what dfuse expects then update the kernel to remove the old
dentries which should reduce kernel resources required.
When files are removed then check if the file is known and if so
mark is as removed.
For getattr on removed files return most recent data rather than error.
For setattr on removed files allow setting of times only as this can
happen with cached writes.
=> DAOS-6540 dfuse: Detect clobbered files and update kernel accordingly.

src/dtx/dtx_common.c, src/include/daos_srv/dtx_srv.h, src/object/srv_obj.c, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_obj.c
To detect the case that some resent request may be handled
before its original request.
=> DAOS-8049 dtx: trace resent request

src/object/cli_obj.c, src/tests/suite/daos_rebuild_ec.c
EC enumeration might retry from parity to multiple
data shards, so let's cleanup the partiy task before
retry, otherwise it will cause failure during following
retry.
=> DAOS-8029 EC: EC enumeration retry

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/infocache_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/start.go
Split the agent cache into two separate caches: one for the remote
GetAttachInfo response, and one for the fabric interface topology
on the machine. The remote cache may still be disabled using the
environment variable. The local fabric cache may also be disabled
via a new environment variable.
=> DAOS-7894 agent: Refactor GetAttachInfo cache

src/cart/crt_rpc.c
- Avoid double completion of failed RPC if the failure happens during
hg address lookup phase.
Previously the error was handled already when HG_Reset() fails
in the lookup code (completion invoked), but it was also being propagated
to the caller, which also attempts to handle it (invoking completion again).
That caused rpc reference count to go below 0, cauisng the crash.
=> DAOS-8063 rpc: Avoid double completion of failed RPC

src/tests/daos_perf.c
Also move dkey and akey creation outside of perf test.  There may
be some cache effects here but it's a tradeoff to not measure
key creation performance.
Change iterate test to use vos_iterate
=> DAOS-623 perf: Add punch performance test to VOS mode

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache.go
- Protect NUMAFabric structure internals with a lock.
- Return copies of data from caches instead of references.
- Improve testing of round robin interface choice.
- Remove duplicate testing and unreachable code.
=> DAOS-8151 agent: Fix data races

src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/config_test.go, src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/infocache_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/start.go
- Add the optional field "fabric_ifaces" to the DAOS agent config
file, to allow users to specify the NUMA affinity of fabric
interfaces. If provided, this is used instead of detecting the
devices automatically.
=> DAOS-8047 agent: Allow user-defined fabric interfaces

src/client/dfs/dfs.c, src/common/acl_principal.c, src/container/cli.c, src/utils/daos_hdlr.c, utils/node_local_test.py
Update the test to create a new container each iteration.  This allows
the test to complete properly, and therefore finds a number of new
issues, both with logging and stdout.  For now the test is still disabled however.
Add strerr checking to the test.
Fix a number of logging/output errors, and create new DH_PERROR_SYS and
DH_PERROR_DER macros in daos_hdlr.c so we can have a consistent output
style.
=> DAOS-7446 test: Update the filesystem copy fault injection test.

src/placement/jump_map.c, src/placement/pl_map.h, src/placement/pl_map_common.c, src/placement/ring_map.c, src/placement/tests/jump_map_place_obj.c
Add doms_cur_grp_used bits array in get_targets to make sure
do not put shards within the same group in the same domain.
=> DAOS-8048 placement: Not put same grp shards in the same domain

src/object/cli_obj.c
Collect more log message when obj_shards_2_fwtgts() hit failure.
=> DAOS-7948 obj: more log when obj_shards_2_fwtgts hit failure

src/object/srv_obj_remote.c, src/tests/suite/daos_rebuild_common.c, src/tests/suite/daos_rebuild_simple.c, src/tests/suite/daos_test.h
Remote punch should use st_shard_id instead of st_shard,
because st_shard is the shard index, and st_shard_id is
the real ID for shard.
Add dfs punch open/create test.
=> DAOS-7996 objects: use st_shard_id for remote punch

src/tests/daos_racer.c
Add EC object verify to daos racer.
=> DAOS-8029 tests: add EC object verify to daos racer

src/object/cli_obj.c, src/object/srv_obj.c
For rebuild, as the aggregation will not cross the rebuild epoch, so
in obj_ec_recov_need_try_again() need to bypass the rebuild case.
=> DAOS-8108 rebuild: fix a case in obj_ec_recov_need_try_again

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_srv.c, src/engine/srv.c, src/include/daos_srv/daos_engine.h, src/include/daos_srv/dtx_srv.h, src/vos/vos_common.c, src/vos/vos_container.c, src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_obj.c, src/vos/vos_pool.c
Currently, the committed DTX table in DRAM in container based. For
the committed DTX table, the count threshold of DTX aggregation is
about 1^20 entries. If there are multiple (assume 'N') containers
maintained by the same engine, then there maybe at most 1^ 20 * N
committed DTX entries. If "N" is too large, then may cause server
out of memory.
This patch changes the container based DTX aggregation threshold
as pool based. Then the total committed DTX entries in DRAM will
be much reduced for multiple containers case.
The DTX aggregation thresholds are also adjusted:
1. Count threshold: 1^20 => 1^20 * 3
2. Time threshold: 90 sec => 180 sec
The in-DRAM committed DTX entry size is reduced to 36 bytes per entry.
=> DAOS-7930 dtx: pool based DTX aggregation threshold

src/client/api/SConscript, src/client/api/compile_check.c, src/client/api/compile_check_cpp.cpp, src/common/SConscript, src/control/cmd/daos/container.go, src/control/cmd/daos/pool.go, src/include/daos_cont.h, src/include/daos_pool.h, src/include/daos_prop.h, src/include/gurt/types.h
A recent patch (PR #6138) broke C++ compilation.  This restores
it and adds a compiler test to check it.
=> DAOS-623 build: Fix c++ compilation with pool/cont routines

src/client/dfs/dfs.c, src/client/dfuse/il/int_posix.c
Retry dfs_release on failure if the failure type is ENOMEM.
=> DAOS-8127 dfs: Check and retry dfs_release()

src/tests/ftest/erasurecode/ec_ior_smoke.yaml
Test-tag-hw-large: ec_smoke,ior
Test-repeat-hw-large: 20
=> DAOS-7795 Test: Reduce the IO size for ec_ior tests.

src/control/common/storage/commands.go, src/control/lib/spdk/src/nvme_control.c, src/control/server/ctl_storage_rpc.go, src/control/server/init/setup_spdk.sh, src/control/server/storage/bdev/backend.go, src/control/server/storage/bdev/runner.go, src/tests/ftest/util/server_utils_base.py
Server yaml variable bdev_include is not working after recent SPDK upgrade.
SPDK setup script now uses environment variables PCI_ALLOWED and PCI_BLOCKED
and had deprecated use of PCI_WHITELIST and PCI_BLACKLIST.
=> DAOS-8074 ctrl: Update storage prepare script env var to PCI_ALLOWED

src/control/cmd/daos_agent/mgmt_rpc.go
We were not able to fetch the domain, which is required for the
verbs provider, because we weren't passing the netdetect context
when fetching the device alias.
=> DAOS-8158 agent: Fix agent regression with ofi+verbs

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache_test.go
When a client sends a GetAttachInfo request, don't return any
interface that doesn't have an IP address.
=> DAOS-7894 agent: Exclude fabric IFs with no IP address

src/dtx/dtx_common.c
For the sched reqeust used by DTX aggregation main ULT.
=> DAOS-7930 dtx: fix mem-leak for DTX aggregation

src/object/cli_obj.c, src/object/cli_shard.c
For EC FETCH_AGAIN, need to reset reasb_req.orr_iom_tgt_nr as zero.
And change some D_ASSERT to D_ASSERTF to provide more info.
=> DAOS-8122 EC: zero reasb_req.orr_iom_tgt_nr before retry

src/dtx/dtx_rpc.c
DTX_AGG_THRESHOLD_AGE_LOWER was renamed to DTX_AGG_THD_AGE_LO
and old version was used in a recent patch while both landed
at the same time.
=> DAOS-623 build: Fix merge conflict

src/include/daos_srv/rebuild.h, src/pool/srv_pool.c, src/rebuild/srv.c
Check if the pool auto-healing property is set before regenerate
the rebuild task.
=> DAOS-8145 rebuild: check rebuild property for rebuild regenerate

src/container/cli.c, src/pool/cli.c
To prevent more EFAULT cases during RDRAM registration on client
side, also copy to heap, attr values for set-attr and attr names
for del-attr.
Change-Id: Ic9e56f9efe5585ec1dcfeaaf4121a50e1ff3ba8d
=> DAOS-7671 api: more heap copies of attrs names and values

src/object/srv_ec_aggregate.c, src/object/srv_obj.c
During EC aggregation peer update, if parity has been
updated successfully, let's ignore the failure of replica
deletion, otherwise, the leader will not update parity,
and cause parity inconsistency.
Remove some obsolote EC aggregation code.
=> DAOS-7420 EC: ignore failure of remove replicas on parity

src/cart/crt_hg.c
- Mercury update to 2.0.1 requires mercury subsystem to be
set in order to see logs. Cart startup modified to set subsystem
to deault if not provided by external envariable.
=> CART-89 log: Set default subsystem if not set

src/tests/ftest/nvme/nvme_fault.py, src/tests/ftest/nvme/nvme_fault.yaml, src/tests/ftest/nvme/nvme_fragmentation.py, src/tests/ftest/nvme/nvme_health.py
- Adding container RF property to nvme_fault.py tests.
- Updated container UUID in to python dictionary after IOR writes
and create the container
Test-tag-hw-medium: pr,hw,medium nvme_fragmentation nvme_fault
=> DAOS-8049 Test: Fix nvme_fragmentation and nvme_fault test.

src/control/common/file_utils.go, src/control/server/config/server.go, src/control/server/config/server_test.go, utils/config/examples/daos_server_unittests.yml
Backward compatibility has been provided with the change to support an
arbitrary number of storage tiers in the server config file. Legacy
style storage definitions (flat bdev_ and scm_ parameters assignments
under engine) in server config file are automatically converted to
multiple tiers during config validation. Add some unit test coverage for
the conversion of files with legacy storage definitions.
=> DAOS-7673 control: add config tests for legacy storage conversion

src/pool/cli.c
- Set tag to 0 when issuing RPC request for TGT_QUERY_MAP
=> CART-89 fix: CID 332947 fix - set tag to 0

src/placement/jump_map.c, src/placement/tests/jump_map_place_obj.c
Set dom_occupied bits correctly once the all targets have been
used during layout generation, otherwise get_target might be in
endless lop even if there are still targets left.
Add tests to verify this.
=> DAOS-8165 placement: set dom_occupied bits in get_object_layout

src/tests/ftest/launch.py, src/tests/ftest/util/server_utils.py
If set, appends '--failfast on' to the avocado run
arguments. This will cause avocado to abort the test
run at the first test failure. Also breaks out of the
repeat loop if --repeat was specified.
Fixes a corner case in the system query helper where the
response succeeds but contains a null members array.
=> DAOS-623 test: Add --failfast flag to launch.py

src/control/lib/control/pool.go, src/tests/suite/daos_mgmt.c
Before this change, the daos_test MGMT5 pool_create_and_destroy_retry()
test could not inject the fault DAOS_POOL_DESTROY_FAIL_CORPC and
(retry and) destroy the created pool. This resulted in a leftover pool
in the environment, in addition to the failed pool destroy.
With this change, the dmg pool destroy behavior is changed to
retry the gRPC upon a DER_TIMEDOUT reply from the MS. And the
daos_test is updated to re-enable the pool destroy fault injection.
=> DAOS-5671 control: pool destroy timeout retry, re-enable test

src/cart/crt_context.c, src/container/cli.c
fix setting error code in container/cli.c and cart/crt_context.c
The return code is not being set when out of memory error occurs. This was
revealed in fault injection testing for filesystem copy which calls
dfs_cont_create, which then calls daos_cont_create...which eventually calls this
function and returns the incorrect error code. This is causing the filesystem
copy fault injection tests to report DER_INVAL value when it should be returning
DER_NOMEM.
There was also another bug here:
src/cart/crt_context.c: D_GOTO(out, -DER_AGAIN);
Where the return code was not being set. 
=> DAOS-8210 container, cart: fix set error code in cli.c and crt_context.c

src/control/lib/control/rpc.go, src/control/lib/control/rpc_test.go
The default rand source is thread-safe, but sources
created with rand.NewSource() are not. Wrap the
MS candidate chooser source with a mutex to avoid
race warnings.
=> DAOS-8198 control: Protect rand.Source with lock

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/start.go
- Fix the initialization of the fabric cache from the config file.
- Improve debug logging.
=> DAOS-8047 agent: Fix fabric cache init from config

src/object/cli_shard.c, src/object/obj_enum.c, src/object/srv_obj_migrate.c, src/tests/suite/daos_rebuild_common.c, src/tests/suite/daos_rebuild_ec.c
Do not need checksum for EC enumeration, since
checksum needs to be re-calculated during EC
rebuild.
Cleanup iod in obj_enum_unpack() in error handling
path.
Enforce checksum for EC rebuild test.
=> DAOS-8048 EC: checksum fixes for EC

src/tests/ftest/container/snapshot_aggregation.py, src/tests/ftest/pool/bad_evict.py, src/tests/ftest/pool/evict_test.py, src/tests/ftest/pool/pool_svc.py
Add some UUID test coverage for dmg pool commands.
Updated the tests to use TestPool instead of directly calling dmg.
Test-tag: snapshot_aggregation test_pool_svc bad_evict pool_evict_basic
=> DAOS-8184 test: Use UUID to call some dmg pool commands

src/gurt/telemetry.c
The stats minimum was previously initialized to MAX_UINT, which was
confusing for users.
=> DAOS-8128 metrics: Init stats min to 0

src/tests/ftest/pool/create_capacity_test.py
Don't query the pools while listing them, to avoid intermittent
test timeouts.
=> DAOS-8229 test: Use no_query=True in PoolCreateCapacity

src/include/daos_prop.h, src/pool/srv_pool.c
Allow to set ec_cell_sz property after creation
=> DAOS-8182 pool: allow to set ec_cell_sz prop after creation

src/cart/crt_iv.c, src/cart/crt_swim.c, src/container/srv_target.c, src/mgmt/srv.c, src/mgmt/srv_pool.c, src/object/cli_ec.c, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_ec.h, src/object/obj_internal.h, src/object/srv_obj_migrate.c, src/pool/srv_pool.c, src/rebuild/scan.c
Missing collective req put for a few mgmt handler.
=> DAOS-8082 mgmt: missing collect req put

utils/rpms/daos.spec, utils/systemd/daos_agent.service, utils/systemd/daos_server.service
The option 'StartLimitIntervalSec' is to be in Unit section and not Service section.
See: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
-Moved 'StartLimitIntervalSec' from Service section to Unit section
=> DAOS-7893 Systemd: StartLimitIntervalSec in incorrect section in service file

src/vos/ilog.c, src/vos/ilog.h, src/vos/vos_ilog.c, src/vos/vos_ilog.h, src/vos/vos_obj.h, src/vos/vos_obj_cache.c
For fetch of non-existent objects or other operations that will
fail vos_obj_hold, we can use a threadprivate object to
cache the state, thus avoiding any eviction until we know
the object needs to be cached.
=> DAOS-7675 vos: Avoid unnecessary object cache eviction

src/control/common/proto/types_test.go, src/control/server/ctl_storage.go, src/control/server/storage/provider.go, src/tests/ftest/nvme/nvme_fault.py, src/tests/ftest/nvme/nvme_health.py
Remove test skips and address some small feedback issues.
=> DAOS-8080 test: re-enable nvme query and health tests

src/tests/ftest/launch.py, src/tests/ftest/util/server_utils_params.py
Since VMD is now disabled by default, the test code
needs to be updated to reflect the inverted logic.
=> DAOS-8211 test: Fix conflict in VMD configuration

src/utils/daos_metrics/daos_metrics.c
The tool wasn't updated to fetch stats gauges when the new type
was added.
=> DAOS-8261 metrics: Let daos_metrics print stats gauges

src/tests/ftest/control/dmg_pool_evict.py
Use TestPool object instead of DmgCommand to call evict.
Test-tag: dmg_pool_evict
=> DAOS-8225 test: Use TestPool in dmg_pool_evict.py

src/mgmt/srv.c, src/pool/srv_pool.c, src/tests/suite/daos_pool.c
Before this change daos_test -p pool_op_retry() test attempted to
inject pool connect/disconnect/query corpc faults on the daos_engine
side by invoking daos_debug_set_params() with a rank=0 input argument.
The rank 0 engine very often is not the pool service (PS) leader,
so the fault value in rank 0 had no actual fault injection effect
on the subsequent pool operations handled by another (PS leader) rank.
i.e., the operations succeeded, the test seemed to pass, but it did not
actually exercise rpc retry behavior due to an (injected) timeout.
With this change, the test function is changed to specify the PS leader
rank in daos_debug_set_params(). Also, the engine mgmt code is updated
to emit debug log messages to confirm fault injection is engaged.
Signed-off-by: Kenneth Cain …
=> DAOS-8197 test: pool_op_retry specify PS leader for faults

src/control/cmd/dmg/main.go, src/control/cmd/dmg/telemetry.go, src/control/cmd/dmg/telemetry_test.go, src/tests/ftest/util/dmg_utils_base.py
The special --host parameter for metrics commands was confusing.
This patch removes the --host parameter and instead uses the same
--host-list used by other dmg commands. The user may still only
query one DAOS server at a time.
=> DAOS-7166 dmg: Use hostlist in metrics list/query

src/vos/evtree.c, src/vos/tests/vts_aggregate.c, src/vos/tests/vts_io.c, src/vos/tests/vts_io.h, src/vos/vos_aggregate.c
1. vos_obj_array_remove should skip existing entries removals
rather than removing them
2. A logical extent may refer to a physical extent that is already
removed because it's fully covered in the current window.
Ignore such and assert they are not visible rather than asserting
that the case can't happen.
3. Add a test that helped uncover these issues
Features: aggregation rebuild ec
=> DAOS-8226 vos: Fix some issues with removal aggregation

src/tests/ftest/launch.py
Adding new argument '--mode' to launch.py with default
set to 'normal' which will exhibit current behaviour.
But it can accept another value 'manual' where the return
code will be non-zero incase of a failure.
=> DAOS-8256 tests: Adding new argument to launch.py

src/common/tests/lru.c, src/tests/ftest/cart/dual_iface_server.c, src/tests/ftest/cart/test_group_np_common.h, src/tests/suite/daos_epoch_io.c
DAOS-7994 test: fix CID 275713
In main: An unscrutinized value from an untrusted source
used as a loop bound.
Fix for this is to ensure that num_keys has an upper bound
which is checked and also that a check is in place to make
sure a negative number is not passed provided.
DAOS-7991 test: fix CID 329700
In main: Using an insecure temporary file creation function
Set umask before creation of temporary files.
DAOS-7987 test: fix CID 329541, 331438, 329382
329541 In cmd_line_parse: The string buffer may
not have a null terminator if the source string's
length is equal to the buffer size
Set source buffer to max - 1 to make so there is room
in destination buffer for null byte.
331438 In server_main: A character buffer that has
not been null terminated is passed to a function
expecting a null …
=> DAOS-[7987, 7991, 7994] test: Coverity fixes

src/control/server/engine/utils.go, src/control/server/engine/utils_test.go
Masks such as debug or err should not cause validation failures.
=> DAOS-8254 control: handle lowercase masks in set-logmasks

src/client/pydaos/SConscript, src/client/pydaos/pydaos_core.py, src/client/pydaos/pydaos_shim.c, src/container/cli.c, src/control/cmd/daos/container.go, src/include/daos/common.h, src/include/daos_prop.h, src/utils/daos_hdlr.c, utils/node_local_test.py
Implement the following changes to pydaos:
- Remove ifdef for python2 support.
- Add support for pool and container label.
- Use oid in the roots property to boostrap the
container and find the rootkv.
- Use container oid allocator instead of srand()
to generate object ID.
- Track container and pool handles in the shim layer
as well as the current allocated id. The pydaos
frontend is only returned an opaq pointer.
In addition, the following changes were made:
- change daos_cont_create() to allocate a root oid by
default if none is passed by the caller.
- modify the daos utility to accept all container types
- adjust nlt to accomodate the changes mentioned above.
=> DAOS-8103 pydaos: several improvements

src/object/cli_ec.c
Don't try to reuse efi_recx_lists/efi_stripe_lists in
obj_ec_fail_info_reset.
=> DAOS-8209 EC: refine obj_ec_fail_info_reset

src/control/cmd/daos/acl.go, src/control/cmd/daos/container.go, src/control/cmd/daos/filesystem.go, src/control/cmd/daos/object.go, src/control/cmd/daos/pool.go, src/control/cmd/daos/snapshot.go
Request only the level of permissions necessary for the task, to
avoid pool/container connect failures for users with RO access.
Feature: pool,container,snap,dfuse,security
=> DAOS-8219 tools: Fix permissions in daos tool

src/control/cmd/daos/util.go
When cleaning up the handler output stream, call fflush()
on the stream before closing it.
=> DAOS-5692 tools: Use fflush() on stream cleanup

SConstruct, src/include/daos_array.h, src/include/daos_obj.h, src/tests/simple_obj.c
daos_array_generate_id() still requires the oclass. Deprecate that in
favor of a new convenience API for array oid generation:
daos_array_generate_oid() that makes the oclass optional and uses the
container properties and rf factor if oclass is unknown.
=> DAOS-8280 array: deprecate daos_array_generate_id in favor of new API

src/dtx/dtx_srv.c
Check whether the dc_cont is non NULL before updating the
metrics.
=> DAOS-8103 dtx: check for NULL cont for metrics

Jenkinsfile
Now that we have resolved all detected server and client memory
leaks change Jenkinsfile so that any leaks cause a build failure.
Until now we've had either leaks or intermittent leaks so this
check has been on but not enforced which has lead to a number
of regressions slipping in.  As master is now routinely showing
no leaks discovered them change the settings to enforce this.
=> DAOS-6726 test: Update Jenkinsfile to fail build on memory leaks.

src/pool/srv_pool.c, src/tests/ftest/erasurecode/ec_offline_rebuild.py, src/tests/ftest/erasurecode/ec_offline_rebuild_single.py
Before this change, stopping the PS leader rank and then issuing
dmg pool query temporarily surfaces -DER_UNREACH to the user.
However, daos pool query internally retries the PS RPCs and seamlessly
(after a raft election delay) returns the pool query result. With dmg,
an MS engine is the cart RPC initiator, whereas with daos, libdaos is
the initiator. The code is similar, but only the libdaos code checks
for and handles "retryable" RPC errors.
With this change, the engine initiator code for POOL_QUERY RPCs checks
for and handles retryable errors (fixing the dmg pool query use case).
This patch is meant to be a precise change to solve a particular issue.
However, a follow-on patch may expand use of retryable error checks for
all MS engine-initiated PS RPCs.
The …
=> DAOS-7212 pool: pool query from MS, mind retryable RPC errors

src/control/cmd/daos/snapshot.go
This was fixed in #6356 but accidentally reverted while
resolving a merge conflict.
Test-tag: pr snapshot_aggregation
=> DAOS-8001 tools: Snapshot destroy fails due to null handle

src/container/srv_container.c, src/container/srv_internal.h, src/include/daos_prop.h, src/pool/srv_internal.h, src/tests/ftest/pool/label.py
Add a new #define (DAOS_PROP_MAX_LABEL_BUF_LEN) to indicate
the max size of a buffer that can hold a label plus a trailing
NULL to terminate the string. Fixes a crash found with label
boundary testing.
Re-enables testing for invalid pool labels (DAOS-8205).
=> DAOS-8183 engine: Correctly size label buffers

src/include/daos_srv/evtree.h, src/include/daos_srv/vos.h, src/object/cli_shard.c, src/object/obj_rpc.h, src/object/srv_obj.c, src/tests/daos_perf.c, src/tests/suite/daos_obj_ec.c, src/vos/evt_iter.c, src/vos/tests/vts_array.c, src/vos/tests/vts_io.c, src/vos/tests/vts_mvcc.c, src/vos/tests/vts_pm.c, src/vos/vos_query.c
When punch EC object, it does not punch anything on
the parity extent, only on replicate extent. so if
size querying goes to the parity shard before EC
aggregation, then it will check the punched extents.
=> DAOS-8108 object: fix EC object punch size issue

site_scons/compiler_setup.py, src/include/gurt/debug.h, src/object/cli_shard.c
- Add -Wshadow as a flag to our build; change gurt header to mark
shadow warnings as errors.
=> CART-89 shadow: Shadow param to generate error instead of warn

src/client/api/container.c, src/client/dfs/dfs.c, src/client/serialize/daos_serialize.c, src/common/prop.c, src/control/cmd/daos/property.go, src/control/cmd/daos/property.h, src/control/cmd/daos/util.c, src/control/cmd/daos/util.h, src/include/daos_prop.h, src/tests/suite/daos_container.c
The current property API usage only works for the DAOS library since it has the same allocator and free functions. regular users cannot be expected to allocate the str or ptr values for property entries, and then DAOS would free them using daos_prop_free().
This PR adds APIs to set the str and ptr values so they can be freed in daos_prop_free().
this doesn't migrate all internal usage of the props to that new API, but this is not a problem, because internal usage is the same as using this function since those entries are allocated with D_ macros internally.
=> DAOS-8301 props: provide new prop APIs to set str and ptr values.

src/object/cli_ec.c, src/object/cli_obj.c, src/object/obj_ec.h, src/object/obj_internal.h, src/tests/suite/daos_rebuild_ec.c, src/vos/evtree.c, src/vos/vos_io.c, src/vos/vos_tree.c
In EC data recovery, it possible need to recover multiple stripes
by different recovery tasks. Those tasks share the same fail_info,
so the parity_lists cannot be inside fail_info to avoid mixing
with different stripe recovery tasks.
=> DAOS-8108 EC: fix a bug in obj_ec_parity_check

src/object/srv_obj_migrate.c
Because csum will be re-calculated for EC object rebuild, so
it does not need re-allocated according to the fetched csum,
instead it should allocated csum according to the migrated SGL
and IOD.
=> DAOS-8299 object: remove obsolote csum alloc for EC object

src/vea/tests/vea_ut.c, src/vea/vea_api.c, src/vea/vea_hint.c, src/vea/vea_internal.h
vea_reserve() may yield when free extents unmap triggered internally,
so the following interleaved reserve calls could happen:
ULT A reserve 1 then yield, ULT B reserve 2 & publish 2, ULT A
continue to reserve 3 and publish 1 & 3.
This patch adjusted hit publish/cancel functions to tolerate above
interleaved reserve calls.
=> DAOS-8108 vea: allow interleaved reserve calls

src/vos/tests/vts_aggregate.c, src/vos/vos_aggregate.c
In prior patch, the merge window size was adjusted based on the newly
found visible logical extent.   The buffer size allocated needs to
be based on the actual size of enclosed extents.   Track the allocation
hi value for this purpose.
This bug was exposed in EC aggregation.  Add some testing for
aggregation with parity ranges and fix a couple of remaining issues
this change exposed.   It's still possible to get a new logical extent
that has already been removed so modify the assertion accordingly
to check if it's covered by a removal record.
=> DAOS-8332 vos: Allocation based on real merge window size

src/cart/crt_group.c
- Each time uri is queried the size is not reset. This causes previous
size response to be used for next request.
If URI length changes for next target/endpoint, then it will cause
mercury overflow error.
=> DAOS-8329 bugfix: Size not reset on each query

src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/lib/control/mocks.go
Also fixed a test-level race in MockUnaryInvoker.
=> DAOS-8235 agent: Fix data race in GetAttachInfo

src/tests/ftest/control/dmg_system_reformat.py, src/tests/ftest/control/ms_resilience.py, src/tests/ftest/pool/create_capacity_test.py, src/tests/ftest/pool/dynamic_server_pool.py, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py
Use JSON for dmg pool list.
Fixed affected tests.
Test-tag: pr list_pools dynamic_server_pool
=> DAOS-7589 test: Update pool_list() in dmg_utils.py and affected tests

src/tests/ftest/pool/attribute.py
test_pool_large_attributes is not running in CI, enable
extra daily_regreesion and all tags like test_pool_attributes
did.
Test-tag: pr large_poolattribute
=> DAOS-7717 test: enable test_pool_large_attributes in CI

src/include/daos_errno.h, src/mgmt/cli_mgmt.c, src/utils/daos_autotest.c
Extended autotest to include additional functionality:
-better diagnoses, more particularly when the agent isn't running or one
cannot connect to the server (e.g. network issue)
-use the new API to auto-select the object class
-create extra containers with RF=1 and RF=2
=> DAOS-7487 test: Extend autotest with more smoke capabilities

src/include/daos_prop.h, src/placement/tests/place_obj_common.c, src/pool/srv_pool.c, src/tests/jobtest.c
Fix two coverity warning
And add cell size parameter checking (within 1K - 1G) for pool property.
=> DAOS-7988 style: fix coverity warning

src/cart/utils/memcheck-cart.supp, src/client/dfs/duns.c, src/client/dfuse/dfuse.h, src/client/dfuse/ops/getxattr.c, src/client/dfuse/ops/setxattr.c, src/control/cmd/daos/util.c, src/include/daos_uns.h, src/utils/daos_hdlr.c, utils/node_local_test.py
Rather than have container create sometimes set an xattr on the root
directory when a container is created do not create this xattr, but
rather have dfuse create the xattr on the fly when one is requested.
This allows commands like "daos df get-attr" to work correctly,
regardless of how the container was created.
Add a test for this, and correct some returncodes from the "fs get-attr"
error paths.
=> DAOS-8298 dfuse: Return a valid duns xattr for all container roots.

src/SConscript, src/include/gurt/telemetry_consumer.h
These headers are needed for external projects (e.g. LDMS)
to use the telemetry consumer.
=> DAOS-5913 telemetry: Install telemetry headers

src/tests/ftest/daos_vol/daos_vol.py, src/tests/ftest/ior/ior_small.py, src/tests/ftest/ior/ior_small.yaml, src/tests/ftest/util/ior_test_base.py
Reverting the changes landed as part of DAOS-8207(#6464)
keeping the vol test enabling changes
=> DAOS-6325 test: Reverting DAOS-8207 (#6464) keeping test enabling changes

src/pool/cli.c, src/pool/cli_internal.h, src/pool/srv_cli.c
The following assertaion failure was observed:
pool EMRG src/pool/cli.c:1409 map_known_stale() Assertion
'pool->dp_map_version_known >= cached' failed: 1 >= 9
It implies that in some case(s), we update the cached pool map but not
the known pool map version. Going through all places that modify dp_map
reveals dc_pool_g2l as the only case. This patch changes dc_pool_g2l to
use dc_pool_map_update instead, so that dp_map_version_known will be
updated properly.
Also:
- Fix a pool_map leak in map_refresh_cb.
- Remove the redundant map_version parameter from dc_pool_map_update.
=> DAOS-8314 pool: Fix map_known_stale assertion failures

src/client/dfuse/ops/read.c, src/client/dfuse/ops/write.c
If a operation is accepted but then fails the dfs already returns
a system error number so do not attempt to convert it again.
With this change ENOSPACE is correctly reported, instead of EIO
=> DAOS-8264 dfuse: Return correct error value from read/write.

src/control/lib/control/faults.go, src/control/lib/control/mocks.go, src/control/lib/control/response.go, src/control/lib/control/rpc.go, src/control/lib/control/system.go, src/control/lib/control/system_test.go, src/control/server/mgmt_system.go, src/control/system/errors.go
Add more granularity to retryable connection errors and
make retrying the inner join timeout more explicit. Also
adds the "not formatted" error to the set of retryable
Join errors, to handle races between server storage formats.
=> DAOS-8304 control: system.Join() retry improvements

src/tests/ftest/control/ms_resilience.py
The ms_resilience.py test could intermittently fail
to find a pool immediately after creation if the read
was serviced by a non-leader replica.
=> DAOS-8354 test: Retry pool find after create

src/common/prop.c, src/common/tests/prop_tests.c, src/control/cmd/daos/property.go, src/include/daos/cont_props.h, src/include/daos_prop.h
Add a new property API to allow users to pass in a buffer of prop
entry and value pairs to create a new property that can be used to
create a container. The format of the buffer is:
entry1:val1;entry2:val2;...
Skip-nlt: true
=> DAOS-8325 prop: new API for creating a property with entries+values

src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_layout.h
It is mainly used for handling resent distributed transaction
CPD RPC that requires the server to reply the client with the
committable/committed transaction epoch.
This patch enlarges the committed DTX entry size with 8 bytes.
=> DAOS-8300 vos: maintain epoch for committed DTX entry

src/tests/ftest/control/dmg_pool_query_test.py
Added the "media_type" field to the test expectations.
Feature: pool_query
=> DAOS-8321 test: Fix dmg pool query test

src/tests/ftest/server/daos_server_restart.py
The test wasn't comparing against the actual pool list in the
response.
Feature: server_restart,server_reformat
=> DAOS-8350 test: Fix getting pool list from JSON

src/cart/crt_hg.c, src/cart/crt_init.c, src/cart/crt_internal_types.h, src/include/cart/types.h, src/tests/ftest/cart/dual_iface_server.c
- Expose expected/unexpected message size limits to be settable
optionally via crt_init_opt_t structure
=> CART-89 limits: Expose expected/unexpected message size limits

src/common/prop.c, src/common/tests/prop_tests.c
- fixes a coverity warning
- add a test
Skip-nlt: true
=> DAOS-8325 prop: check that name and vals from prop string are not NULL

src/include/daos/object.h, src/object/cli_ec.c, src/object/obj_ec.h, src/object/srv_obj.c, src/tests/suite/daos_rebuild_ec.c
Refine parity list processing, and refine the test case.
=> DAOS-8108 EC: refine parity list handling in EC data recovery

src/bio/smd/smd_device.c
If there is no NVMe storage, the storage query
seg faults trying to list smd devices. fix to check
before calling smd_db_lock() to avoiding segfault.
=> DAOS-8352 smd: Fix storage device list without NVME

doc/admin/env_variables.md, src/rdb/rdb_internal.h, src/rdb/rdb_raft.c
It was observed that RDB leaders sometimes send AE requests with
thousands of entries. These AE requests may take considerable efforts
from the followers to process. Because the processing does not yield to
the Argobots scheduler, it may starve other ULTs (e.g., dss_srv_handler)
on the same xstream for too long. This patch limits each AE request by
both a maximum number of entries and a maximum aggregated entry data
size.
Also:
- Fix -DER_IO_INVALs from vos_ioc_create when installing snapshot
chunks. It appears that rdb_raft_exec_unpack_io may be called with
an empty io, whose ui_iods_top field equals -1. This patch follows
other dss_enum_unpack_io callbacks to skip such ios.
- Return -DER_MISC from rdb_raft_cb_recv_installsnapshot_resp when a
chunk is not successfully installed. There …
=> DAOS-7721 rdb: Limit AE sizes

src/tests/ftest/scripts/setup_nodes.sh, src/tests/ftest/util/agent_utils.py, src/tests/ftest/util/server_utils_params.py
Fix permission for daos_engine to write to test.cov
Set COVFILE for daos agent and daos server
=> DAOS-8398 test: Fix permission for daos_engine to write coverage

src/control/cmd/daos/container.go
daos tool currently opens the container read only causing list-obj to fail
since that creates then destroys a snapshot. fix that issue and open
container RW.
=> DAOS-8419 daos: open container RW for when list-obj is called

src/object/srv_obj.c, src/object/srv_obj_migrate.c
Two ds_cont_child reference leaks.
=> DAOS-7228 rebuild: two ds_cont_child leaks

src/client/dfs/dfs_sys.c, src/include/daos_fs_sys.h, src/tests/ftest/datamover/dm_large_dir.yaml, src/tests/ftest/datamover/dm_large_file.yaml, src/tests/suite/dfs_sys_unit_test.c
Test-tag: pr fs_copy dcp
Don't set size = -1 for daos_size_t types, since it is unsigned.
The rc is set appropriately anyway, so this is redundant.
=> DAOS-8293 dfs: dfs_sys should not set size = -1

src/control/server/mgmt_pool.go, src/control/system/database.go, src/control/system/database_test.go
The user-visible list should only include pools that are
ready to be used.
=> DAOS-8282 control: ListPools() should only include Ready pools

src/include/daos_srv/evtree.h, src/vos/evtree.c, src/vos/vos_obj.c
We can have orphaned removal records even if there is no
orphaned data.   Augment the check for an empty tree
to only fail if there there is actual data and the tree
isn't just removal entries.  This case can happen if
the EC aggregation inserts removals while aggregation
is processessing the tree.
=> DAOS-8425 vos: Check evtree for orphaned data

src/include/daos/object.h, src/include/daos_srv/daos_engine.h, src/include/daos_srv/vos_types.h, src/object/cli_ec.c, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_ec.h, src/object/obj_enum.c, src/object/obj_internal.h, src/object/obj_rpc.h, src/object/obj_verify.c, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/tests/suite/daos_rebuild.c, src/tests/suite/daos_rebuild_common.c, src/tests/suite/daos_rebuild_ec.c, src/tests/suite/daos_test.h, src/vos/vos_io.c
1. Add random rank failed for EC rebuild test.
2. Add DIOF_EC_RECOV_FROM_PARITY and VOS_OF_SKIP_FETCH to
split the partial EC overwrite rebuild into 2 steps.
1) reconstruct the data from the parity rebuild.
2) reconstruct the data from replicate data on the pairty.
So the parity will not be corrupted before EC aggregation.
3. Remember recx epoch during migration unpack, so the parity
rebuild will use the maxim epoch from all data shards, to make
sure the right shadow epoch will be chosen during degraded fetch
after rebuild.
4. Remove obsolete invalid_inline_sgl, since EC rebuild will not fetch
inline data anyway.
5. enlarge some rebuild tests pool size to avoid ENOSPACE error.
=> DAOS-8353 rebuild: a few fixes for overwrite EC rebuild

src/common/tests/compress_timing.c, src/tests/suite/daos_aggregate_ec.c
This PR addresses Coverity issues pertaining to integer overflow, potential divide by zero and a
negative return assigned to unsigned int.
Issues: 316292, 331104, 331105
```
Unintentional integer overflow (OVERFLOW_BEFORE_WIDEN)
overflow_before_widen: Potentially overflowing expression k * len with type unsigned int (32 bits, unsigned) is evaluated using 32-bit arithmetic, and then used in a context that expects an expression of type daos_size_t (64 bits, unsigned).
```
Issue: 329169
```
Division or modulo by float zero (DIVIDE_BY_ZERO)
80. divide_by_zero: In expression (float)rc / total_sz, division by expression total_sz which may be zero has undefined behavior.
```
Issue: 329170
```
Improper use of negative value (NEGATIVE_RETURNS)
4. negative_returns: file_sz is passed to a parameter …
```
=> DAOS-7970 test: Fixed Coverity issues in test and compress_timing

SConstruct, src/client/pydaos/raw/daos_cref.py, src/container/cli.c, src/container/rpc.h, src/container/srv_container.c, src/container/srv_epoch.c, src/container/srv_internal.h, src/container/srv_layout.c, src/container/srv_layout.h, src/control/cmd/daos/container.go, src/include/daos_cont.h, src/pool/srv_layout.h, src/tests/suite/daos_epoch.c, src/utils/daos_hdlr.c
Return daos_cont_info_t.ci_nsnapshots in container query and open,
instead of always returning the value 0. Also, update the container
CaRT RPC version since a new snapshot count (out) parameter is added
to both CONT_QUERY and CONT_OPEN, and since CONT_QUERY no longer
returns cqo_hae (see daos_cont_info_t change).
The daos_engine (pool and) container metadata layout version is updated
to include a new ds_prop_cont_nsnapshots key / unsigned integer value
in the container properties KVS. The value increments and decrements
appropriately with snapshot create / destroy operations and is more
quickly read (compared to iterating snapshots keys) during container
open and query operations.
The libdaos API version is also updated to v1.5.0 to reflect removal
of ci_hae (highest aggregated epoch) …
=> DAOS-7479 container: query return number of snapshots

src/bio/bio_buffer.c
When mapping DMA buffer to NVMe IOVs, we always check if current IOV
is contiguous with previous mapped IOV, if they are congiguous
(current IOV starts from the same blob page where the previous IOV
ended), we just expand the existing reserved region to avoid issuing
two blob I/Os against the same blob page.
There is a defect in current "consecutive reserve" which overlooked
a case: current IOV and previous IOV are both small IOV within same
blob page, and current IOV is ahead of previous IOV, for example:
current IOV is [100, 200), previous IOV is [300, 400).
=> DAOS-8430 bio: Fix consecutive reserving

src/client/dfuse/ops/rename.c
We intent to udpate parent inode num with new parent inode number.
but it was updated as parent's parent inode number.
Fixes: dc7a4f24f7e ("DAOS-6540 dfuse: Detect clobbered files and update kernel accordingly")
=> DAOS-8424 dfuse: fix to update parent inode num for rename

src/control/lib/control/pool.go, src/control/server/mgmt_pool.go, src/control/system/raft.go, src/tests/ftest/util/dmg_utils.py
When a pool is found to already be in the Creating state
on a retried create, trigger the cleanup code for that single
pool.
Also adds -DER_UNREACH to the set of retryable pool errors,
as testing shows that these can still be encountered after
a server has been killed but hasn't been excluded yet.
Removes some redundant retry code from the test harness.
=> DAOS-8313 control: Minimize scope of cleanup on pool create

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c
For the object with multiple shards (such as 16 + 2 EC), the DTX
batched commit operation against hundreds of DTX entries, the RPC
sending to multiple non-leader servers may take some long time. We
can use the helper XS to speedup related process.
=> DAOS-8344 dtx: send DTX batched commit RPC via helper SX

src/bio/bio_buffer.c
Fix an improper assert introduced by commit cb92725
=> DAOS-8430 bio: fix improper assert

src/common/mem.c
PMDK logic may return positive errno to DAOS caller, that will
misguide related DAOS logic to regard it as succeed case. This
patch converts the PMDK positive errno to DAOS errno (-DER_XXX)
before returning to DAOS caller.
=> DAOS-8439 common: convert PMDK positive errno to DAOS errno

src/tests/ftest/erasurecode/ec_aggregation.yaml, src/tests/ftest/erasurecode/ec_offline_rebuild.yaml, src/tests/ftest/erasurecode/ec_offline_rebuild_single.yaml, src/tests/ftest/erasurecode/ec_online_rebuild.yaml, src/tests/ftest/erasurecode/ec_online_rebuild_single.yaml, src/tests/ftest/erasurecode/ec_rebuild_disabled.yaml, src/tests/ftest/erasurecode/ec_rebuild_disabled_single.yaml, src/tests/ftest/util/ec_utils.py
During TB5 testing, there are few test failed when try to
create the container.This test has the dfs_oclass as list with
server numbers.
So changing the default obj_class name in yaml file.
Test-tag-hw-small: pr ec
Test-tag-hw-medium: pr ec
Test-tag-hw-large: pr ec
=> DAOS-8374 Test: Fix regression in test.

src/utils/daos_hdlr.c
=> DAOS-8320 tool: destroy hdlr should return -der instead of errno

src/control/fault/code/codes.go, src/control/lib/control/faults.go, src/control/lib/control/mocks.go, src/control/lib/control/request.go, src/control/lib/control/rpc.go, src/control/lib/control/rpc_test.go, src/control/lib/control/system_test.go
Rewrites some of the timeout handling logic to be
clearer and plugs a gap where a retryable timeout
returned from the complex MS response could leak
back to the RPC caller.
Also adds a structured error for request timeout to
better convey what the problem is to the user (no more
mysterious "context deadline exceeded" errors).
=> DAOS-8304 control: Fix control RPC timeout handling

src/bio/bio_monitor.c, src/include/daos/common.h
Currently we used CLOCK_MONOTONIC to get time for nvme poll,
this could have problem since we need export polling timestamps
for 'dmg storage scan --nvme-health'.
Another problem is control plane interpret timestamp
as seconds, fix it.
=> DAOS-7361 bio: fix to use realtime for nvme poll

src/container/srv_target.c
if cont_child_gather_oids() failed, it returned directly without
releasing extra container reference count.
=> DAOS-8474 container: fix potential leak in cont_snap_notify_one()

src/common/misc.c, src/include/daos/common.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_rpc.h, src/object/obj_tx.c, src/tests/suite/daos_checksum.c
Use new functionality exported by Mercury/Cart to initialize
the message size at init time.
Modify DAOS to use inline requests up to 47KiB and keep an
extra 1KiB for headers.
=> CART-89 rpc: bump bulk threshold

src/include/daos/object.h, src/object/cli_obj.c, src/object/obj_internal.h, src/object/obj_tx.c, src/object/srv_obj_migrate.c, src/pool/srv_target.c, src/tests/suite/daos_rebuild_common.c, src/tests/suite/daos_rebuild_ec.c, src/tests/suite/daos_test.h, src/tests/suite/daos_test_common.c
It should use shard % grp_size to check if it is
data shard or parity shard for EC object.
Add tests to verify it
=> DAOS-8231 object: missing % grp_size in object list

utils/build.config
There are a few silicon changes with VMD for the IceLake platform found
when testing on a Coyote Pass system. First off, the bus numbering is
different (half of bus numbers now available), new BUS RESTRICTION VMD
registers, and the PCIe device ID has also been updated to 0x28c0.
Patch has been landed to SPDK, as that is where the code for unbinding
the VMD devices and finding the backing NVMe SSDs can be found. Apply
this patch in the meantime until the next SPDK version update. This will allow
VMD to be used on all Icelake systems, where currently functionality is broken.
SPDK PR: https://review.spdk.io/gerrit/c/spdk/spdk/+/8331
=> DAOS-7874 build: Add SPDK patch for ICX VMD driver update

src/tests/ftest/daos_test/daos_core_test-nvme_recovery.yaml, src/tests/ftest/daos_test/daos_core_test-rebuild.yaml, src/tests/ftest/daos_test/daos_core_test.yaml, src/tests/ftest/daos_test/daos_core_test_dfs.yaml
To avoid situations where a restarted server is writing to same
log file, always use the flag to append the pid to the log
name.
=> DAOS-8409 test: Use D_LOG_FILE_APPEND_PID for core tests

src/tests/ftest/cart/util/cart_logparse.py
* filename and line number fields can be malformated
* use split(None, 8) rather than split(' ', 8) for the checks.  The latter
will include whitespace entries.   For instance,
line = "a b  c" would get ['a', 'b', '', 'c'] whereas split()
yields ['a', 'b', 'c'].  This means the bounds check doesn't
prevent calls to LogLine in some cases because LogLine does
split() which is the same as split(None)
=> DAOS-8409 test: Catch and ignore some exceptions with log parser

src/tests/ftest/erasurecode/ec_cell_size_property.py, src/tests/ftest/erasurecode/ec_cell_size_property.yaml, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/test_utils_pool.py
Verify cell size is picked based on container property if it's set.
By default container cell size will be the same as the pool cell size.
Test-tag: ec_cell_property
=> DAOS-7321 Test: Add test case to verify container EC cell size property.

docs/admin/deployment.md, utils/config/daos_agent.yml
Add documentation about manually defining client fabric interfaces
in the agent config file.
Doc-only: true
=> DAOS-8489 doc: Document manually-defined fabric ifaces

src/pool/srv_pool.c, src/rdb/rdb.c
Before this change, test osa/osa_dmg_negative_test.py
(tag dmg_negative_test_extend) when issuing dmg pool extend commands
that refer to existing pool ranks (e.g., 1, 2, or 3), goes through
a code path in the pool service that leaks a reference on struct rdb.
The pool_extend_internal() function calls rdb_tx_begin() incrementing
the reference, but the pool_extend_map() function it calls invokes
rdb_tx_end() that would decrement the reference. In this scenario,
the rdb_tx_end() call is missed in the error handling path. At the end
of the test pool destroy fails since the RSVC_STOP broadcast does not
get a reply from the pool service leader (it is waiting on references
that will never be released).
This change promotes the rdb_tx_end() call up to pool_extend_internal()
so that the db …
=> DAOS-8437 pool: fix rdb ref leak in pool extend

src/container/srv_container.c, src/container/srv_epoch.c, src/container/srv_internal.h, src/include/daos_srv/rdb.h, src/rdb/rdb_tx.c
It was observed that when evicting 10,000 container handles,
cont_close_hdls could occupy the xstream for more than 10 s, if there is
only one RDB replica. This patch adds ABT_thread_yield calls to the
ds_cont_close_by_pool_hdls procedure.
- Yield when iterating cont->c_hdls and svc->cs_hdls. This requires
the addition of a new rdb API, rdb_tx_revalidate.
- Yield when closing handles. This reason behind the one-TX-per-handle
approach no longer exists. So a batch of handles will be closed in
one TX, with the size of the batch limited by both TX size and
xstream occupation considerations.
- Remove ds_cont_epoch_{init,fini}_hdl. These are no longer necessary.
- Clean up srv_internal.h a bit.
=> DAOS-7721 container: Yield when evicting handles

src/engine/tests/drpc_client_tests.c
When run under Valgrind, test_drpc_verify_notify_pool_svc_update
sometimes takes 10 s or more to return from dss_drpc_call. It is unclear
what exactly causes this delay, but adding a system call into the
polling loop in dss_drpc_call seems to help. (Probably Valgrind has some
impact on memory model and/or scheduling.) This patch adds a real thread
sleep to the sched_req_sleep mock (which is not supposed to block the
current thread) as "the system call".
=> DAOS-7424 engine: Reduce drpc_client_tests delay

src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_ec.h, src/object/srv_ec.c, src/object/srv_obj.c, src/placement/pl_map.c
1. reset start_shard for retry task as well, because
the layout might change during reintegration after
layout refresh.
2. If the parity is rebuilding, let's return ESTALE to
retry and wait until parity rebuilding finished.
3. checksum might need be calculated for retry IO, if
the failure happened before the initial checksum  init.
4. A few st_shard fixes for ec split req process on the
leader.
=> DAOS-8167 EC: various fixes for EC

src/cart/crt_context.c, src/cart/crt_swim.c, src/cart/crt_swim.h
Increase SWIM timeouts by twice for slow network providers.
Improve debug messages.
=> DAOS-8221 swim: tolerate to slow network providers

CONTRIBUTING.md, README.md, docs/admin/performance_tuning.md, docs/overview/terminology.md, src/README.md, src/bio/README.md, src/client/api/README.md, src/client/java/README.md, src/container/README.md, src/control/security/README.md, src/control/server/README.md, src/object/README.md, src/placement/JUMP_MAP.md, src/placement/README.md, src/placement/RING_MAP.md, src/pool/README.md, src/proto/README.md, src/rdb/README.md, src/rebuild/README.md, src/security/README.md, src/vos/README.md
With PR 6565 the doc folder was renamed to docs. Many image sources
and links need to be updated to point to 'docs' instead of 'doc'.
Doc-only: true
Note : DAOS-7174 doesn't appear to be the correct ticket number for the doc changes, however it is what was used for PR 6565 so using it for now. Can update when correct ticket number is identified.
=> DAOS-7174 doc: Update image sources from doc to docs

src/object/srv_ec_aggregate.c
If EC data stripe processing has been yield, then the
it should set YIELD flag when iteration goes back to
akey to avoid messed up the iterator.
=> DAOS-8499 EC: set YIELD flag if EC aggregation yield.

src/common/checksum.c, src/object/srv_obj_migrate.c, src/vos/vos_dtx.c
Coverity identified issues in the engine code where a null pointer is
dereference either before or after a check for NULL is done.
CID: 331131, 331444, 331453
=> DAOS-7976: Fix Coverity Null Pointer Deference Issues in Engine

src/container/container_iv.c, src/container/oid_iv.c, src/container/srv_container.c, src/container/srv_internal.h, src/container/srv_target.c, src/engine/server_iv.c, src/include/daos_srv/iv.h
1. Remove IV related stuff during container destroy.
2. Remove EC aggregation container tracker during container destroy.
=> DAOS-8082 container: remove IV stuff for container destroy

src/control/cmd/daos_agent/procmon.go
Remove inode check for process monitoring since the inode number for a
/proc/pid entry can change under heavy memory pressure. This is a temporary fix
until process monitoring can be tied to a long running dRPC connection.
=> DAOS-8263 agent: EINVAL with dfuse (caching on) with large dd

src/include/daos_srv/vos.h, src/include/daos_srv/vos_types.h, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/vos/tests/vts_io.c, src/vos/vos_io.c
See
https://daosio.atlassian.net/browse/DAOS-8491?focusedCommentId=85686
for a description of the problem. In short, if vos_update_begin/end are
used to update a SINGLE value with an iod whose iod_recxs points to a
daos_recx_t object, then the ir_gsize of this value will become the
memory address of the daos_recx_t object. When this SINGLE value is
fetched later, the output iod_size will contain an incorrect size---the
aforementioned memory address! With dss_enum_unpack, the problem affects
at least rdb use cases.
To make the VOS API safer in this regard, this patch changes akey_update
to treat iod_recxs as "gsize" only if the object is an EC object. Also:
- Add an iod_size verification to vts_io.c. This verification fails
without the rest of this patch.
- Add comments mentioning the …
=> DAOS-8491 vos: Fix non-EC SINGLE gsizes

src/bio/bio_xstream.c, src/common/control.c, src/control/lib/spdk/spdk.go, src/control/lib/spdk/src/nvme_control.c, src/include/daos_srv/control.h
Undesired log messages are being printed to stdout of daos_server. These
messages originate from DPDK which sets some of the facility log masks
to NOTICE and INFO.
This PR sets masks for all DPDK facilities to ERROR in daos_admin and
daos_engine and moves the log level cli args to a common location.
=> DAOS-8008 control: set dpdk log masks to error

src/tests/ftest/util/osa_utils.py
Creating objects with oclass RP_2G1 implies rf:1, which
was expected failure if container was created with rf:2.
Test-tag-hw-medium: pr,hw,medium,ib2,offline_drain
=> DAOS-7758 test: set rf to be 1 for offline drain test

src/client/dfuse/dfuse_main.c
Dfuse uses duns to check the mount point exists, and for UNS
entry points, however for many failure modes it was not printing
anything, or logging at ERROR.
Add specific error for ENOTCONN in case of previous failed fuse
mounts, and a generic error for all other cases.
=> DAOS-8472 dfuse: Ensure error message is printed on duns errors.

src/cart/crt_utils.c
- Remove crt_rank_abort_all() from crtu_drain_queue helper
function. This causes corpc tests to run much slower, especially on
valgrind runs, as servers start cancelling rpc parts of corpc as
servers are shutting down.
=> DAOS-7306 test: Remove rank abort all from crtu_drain_queue

src/tests/ftest/cart/corpc/cart_corpc_one_node.yaml, src/tests/ftest/cart/corpc/cart_corpc_two_node.yaml, src/tests/ftest/cart/ghost_rank_rpc/cart_ghost_rank_prc_one_node.yaml, src/tests/ftest/cart/iv/cart_iv_one_node.yaml, src/tests/ftest/cart/iv/cart_iv_two_node.yaml, src/tests/ftest/cart/rpc/cart_rpc_one_node.yaml, src/tests/ftest/cart/rpc/cart_rpc_two_node.yaml, src/tests/ftest/cart/selftest/cart_selftest_three_node.yaml
- SEP is currently not supported by TCP or verbs, making most of
SEP testing on sockets not that useful while doubling test time on cart
=> CART-89 sep: Remove sep variants from most cart tests

src/cart/crt_iv.c
The IV code has been restructured to eliminate redundant calls to ivc_on_put, which was leading to pointers being freed twice.
=> DAOS-7785 cart: Fix double free in IV code following failure of bulk create.

src/engine/server_iv.c
1. Verify master rank in ivc_on_hash.
2. Do not retry for iv sync, if master rank has been changed.
=> DAOS-8456 iv: verify master rank for IV sync

src/tests/ftest/cart/util/cart_logparse.py, src/tests/ftest/cart/util/cart_logtest.py
In the log that failed, the last line was truncated after
the : so there was no line number.   If there, is a function,
however, there should generally be a line number.
=> DAOS-8497 test: Catch AttributeError when getting source location

src/bio/SConscript, src/bio/bio_xstream.c, src/control/lib/spdk/SConscript, src/control/lib/spdk/spdk.go
Avoid printing non-error level SPDK messages to stderr which results in
confusing log output.
=> DAOS-8008 control,bio: set spdk stderr mask in admin and engine

src/utils/daos_autotest.c
Added support for skipping steps on containers
using prop RF1 or RF2 if domain_nr is less than
required replicas.
=> DAOS-8412 test: Readded single server support for autotest.

src/object/cli_obj.c
For DER_FETCH_AGAIN, it sets new_shard_tasks to create new shard task
when retry, but should remove original shard tasks to avoid memleak.
=> DAOS-8082 obj: fix a memleak in FETCH_AGAIN handling

src/tests/ftest/util/test_utils_pool.py
- Fix error message which printed timeout and label in wrong order
=> CART-89 msg: Fix error message

src/utils/self_test/self_test.c
- If self test fails we do not want to overwrite the error. This
way outside script will be able to test for $? to see whether test
passed or failed
=> CART-89 self_test: Do not overwrite the error

src/container/cli.c, src/container/rpc.h, src/container/srv_container.c, src/control/cmd/daos/container.go, src/include/daos_srv/rdb.h, src/include/daos_srv/vos.h, src/rdb/rdb_internal.h, src/rdb/rdb_tx.c, src/rdb/rdb_util.c, src/tests/suite/daos_epoch.c, src/utils/daos_hdlr.c, src/vos/vos_query.c
Get a container's most recent snapshot in daos container open/query.
In the pool/container service, the vos_obj_query_key() function is
invoked through a new function rdb_tx_query_key_max() to get the
largest epoch/snapshot key in the container snapshot rdb KVS.
The vos_obj_query_key() behavior is also updated to allow a single
value akey when the user does not specify VOS_GET_RECX in flags.
Engine logging code prints out the epoch/snapshot values in hexadecimal
format, since the values are HLC with components that are more easily
read this way. Also, the daos utility output for the container query
(ci_lsnapshot) and list-snap commands are updated to print the values
in hex. Finally, the daos_test epoch tests are updated to assert a
correct value in daos_cont_info_t.ci_lsnapshot, returned …
=> DAOS-7479 container: open, query return most recent snapshot

src/object/srv_obj_migrate.c
It should check pool version of recx when merging recx
to existing migration IOD.
Cleanup migrate merging IOD process.
=> DAOS-8522 migrate: checking version when merging recx

src/object/cli_obj.c
Let's remove all shard tasks for key query, so it can recheck
the leader/shard status.
cleanup the key query a bit.
=> DAOS-8531 object: query key retry should recheck leader status

src/object/srv_obj_migrate.c
Missing setting up iod_nr as 1 during parity rebuild in some
cases.
=> DAOS-8167 object: forget set iod_nr to 1 during parity update

src/control/server/mgmt_pool.go, src/control/server/mgmt_pool_test.go
Follow-on from DAOS-8313, which added a cleanup handler to deal
with finding a partially-created or partially-destroyed pool left
over from a previous create request. Adjusts the logic to actually
include pools in the Destroying state.
=> DAOS-8516 control: Cleanup pools in Destroying state on create

src/control/server/mgmt_system.go, src/control/server/mgmt_system_test.go
In rare circumstances after a MS replica comes back online,
it may temporarily appear to have an empty membership. In
this case, just return ErrRaftUnavail to indicate to the
client that it should try a different replica.
=> DAOS-8527 control: Return ErrRaftUnavail on empty membership

src/control/cmd/daos_server/storage.go, src/control/cmd/dmg/auto.go, src/control/cmd/dmg/firmware.go, src/control/cmd/dmg/pool.go, src/control/cmd/dmg/storage.go, src/control/cmd/dmg/storage_query.go, src/control/cmd/dmg/system.go
These aliases were not intuitive and were inconsistenly defined.
With tab-completion, the commands shouldn't need any aliases, but
some of the more obvious ones were left in case they are useful.
=> DAOS-7741 control: Remove single-letter command aliases

Jenkinsfile, ci/functional/required_packages.sh, ci/parse_ci_envs.sh, ci/provisioning/post_provision_config_nodes_EL_8.sh, ci/rpm/build_success.sh, ci/rpm/test_daos_node.sh, utils/rpms/daos.spec, utils/rpms/packaging/Makefile_packaging.mk
It should never have been specified as an explicit Requires: as RPM's
autoprovides/requires will take care of installing the necessary hwloc
library RPM at installation time.
Also Remove hwloc from the required packages for functional testing.
This is all because we are going to ship compat-hwloc1 with DAOS to be
able to use the RPMs that we build on EL 8.3 on EL 8.4 also.
=> DAOS-8432 Remove R: hwloc

src/bio/bio_xstream.c, src/engine/sched.c, src/engine/srv.c, src/include/daos/common.h, src/include/daos_srv/daos_engine.h, src/vos/vos_io.c
clock_gettime() is supposed to return monotonic time when
monotonic is specified, however, backwards time was observed
on rare instances.
This patch adjusted scheduler code to tolerate backwards
time, and two unnecessary gettime calls are removed.
=> DAOS-7973 sched: tolerate backwards time

src/object/srv_ec_aggregate.c
Missing set yield flag in agg_encode_full_stripe().
=> DAOS-8499 object: missed setting yield in agg_encode_full_stripe

src/bio/bio_config.c, src/bio/bio_internal.h, src/bio/bio_xstream.c
Extract transport addresses from JSON config bdev subsystem and add to
spdk_env_opts before spdk_env_init, this will restrict which VFIO device
files DPDK accesses for the given engine process and should avoid
problems associated with access across different IOMMU groups which
results in EAL VFIO device or resource busy errors.
The above-described problem stops hosts with VMD-enabled NVMe devices
from running multiple DAOS engines and is resolved by this change.
=> DAOS-8040 bio: add config bdevs to dpdk allow list

src/cart/crt_utils.c
- When crtu_wait_for_ranks() fails to ping a rank, add 1 second
delay between retries.
=> CART-89 test: Add 1 second delay on retry to wait for ranks

src/tests/ftest/io/dfuse_bash_cmd.yaml, src/tests/ftest/util/dfuse_test_base.py
Changes made to dfuse_test_base.py to allow dfuse tests to be
able to run from local host if needed.
Also modifying io/dfuse_bash_cmd.py to run from local host
instead of remote client.
Test-tag-hw-small: pr bashcmd
=> DAOS-8529 test: Allow dfuse tests to be able to run from local host

src/common/lru.c, src/include/daos/lru.h
The current LRU scans all the items to evict unused ones.
This patch adds the LRU list back and put those items w/o
refcount on the LRU list, so it can evict items w/o scanning.
=> DAOS-8343 common: avoid full scan while evicting form LRU

src/gurt/telemetry.c, src/gurt/tests/test_gurt_telem_producer.c, src/include/gurt/telemetry_consumer.h
Adds a new method for getting the subdirectories of
a node, up to an optional max depth.
=> DAOS-4495 telemetry: Add d_tm_list_subdirs()

src/common/btree.c
This should help catch missing probe errors a little earlier
=> DAOS-8499 common: Assert if tr_node is set to NULL

src/control/cmd/daos/filesystem.go, src/include/daos_fs.h, src/utils/daos_dfs_hdlr.c, src/utils/daos_hdlr.h
- Use separate command objects instead of relying on argument
order. The options (like --json) may be placed earlier in
the command string, e.g. "daos fs --json get-attr ..."
- Add a new handler for daos fs get-attr to return the contents
of dfs_obj_info_t. The tool decides on the formatting.
=> DAOS-8330 tools: Fix JSON output for daos fs attr cmds

src/vos/vos_common.c
vos_pool_settings_init is not called in the daos_engine use case,
causing the following error when creating many DAOS pools (see
DAOS-6505):
vos  ERR  src/vos/vos_pool.c:281 vos_pool_create() Failed to create
pool /dev/shm/NEWBORNS/d90bf88f-bbbe-43f7-910d-4a5030e93b39/vos-0,
size=0: pool initialization failed
mgmt ERR  src/mgmt/srv_target.c:470 tgt_vos_create_one() d90bf88f:
failed to init vos pool
/dev/shm/NEWBORNS/d90bf88f-bbbe-43f7-910d-4a5030e93b39/vos-0: -1013
... [retries]
This patch moves the call from vos_self_init to vos_mod_init, so that
both the daos_engine case and the standalone case will be covered.
=> DAOS-8517 vos: Fix a missing PMDK setting

src/tests/ftest/network/zero_config.py
Updating the network/zero_config.py test to run on clusters with
Mellanox hardware.
Test-tag: zero_config
=> DAOS-8410 tests: Fix network/zero_config.py

src/tests/ftest/container/autotest.yaml
Due to space pressure issues while running autotest, the test was taking too long to complete.
* Increased autotest NVMe size to 224G.
=> DAOS-7946 test: Increased autotest NVMe size to 224G.

src/tests/suite/daos_nvme_recovery.c
Test-tag-hw-medium: pr daos_core_test_nvme
=> DAOS-8448 Test: Updating the log file to look for disk event messages in control log file instead of server log.

src/include/daos_srv/vos.h, src/mgmt/srv_target.c, src/vos/vos_pool.c
On pool target destroy, if vos_pool is still being held by lingering
IO requests, we'd defer the blob destroy and pmemobj file deletion
until the vos_pool is released.
The blob destroy will be deferred till the last vos_pool reference
put, or the next server start. The pmemobj file deletion will be
deferred till the next pool target creation, or next server start.
=> DAOS-8053 pool: cleanup lingering pools

src/tests/ftest/server/cpu_usage.yaml
The server config has NVMe enabled and 16 targets, 4096 hugepages
configured. BIO internally requires at least 1GB hugepages per target,
so the hugepages needs be configured as 8192 or larger.
Test-tag: pr cpu_usage
=> DAOS-8431 test: increase number of hugepages for cpu_usage test

docs/admin/predeployment_check.md
Updated Non-default Directory - daos_server -d no longer supported
Updated Default Directory (persistent) - not necessary if installed from
rpms
Doc-only: true
=> DAOS-7512 doc: Update predeployment_check.md

src/tests/ftest/erasurecode/ec_offline_rebuild.yaml
The latest master has fixed the original issue so adding
back the ec_offline_rebuild with partial IO.
Test-tag-hw-large: pr ec_offline_rebuild_array
=> DAOS-8502 Test: Enabled offline rebuild tests.

src/include/daos_srv/vos.h, src/pool/srv_pool_scrub_ult.c, src/vos/tests/pool_scrubbing_tests.c, src/vos/tests/scrubbing_sched_tests.c, src/vos/vos_pool_scrub.c
This is an enhancement to PR-6410 that was recently landed. It has
some cleanup and fixes some issues when there is only a single item
to scrub. Also,
- Removed extra layer of structs for metrics. Should have done
this when removed container metrics.
- Moved more of the schedule flow out of the ULT code.
=> DAOS-6049 csum: Improve sleeping of scrubber

src/control/server/config/server_test.go
Replace reference to the psm2 server config file with verbs.
=> DAOS-7174 utils: remove reference to psm2 yaml file

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c
Allow to control DTX aggregation threshold via set the environment
variable "DTX_AGG_THRESHOLD" on server when start DAOS engine. The
valid value range is [2^20, 2^24], the default value is 2^19*7.
It is helpful for performance tuning.
=> DAOS-8300 dtx: control dtx aggregation threshold when start engine

debian/changelog, debian/control, utils/rpms/daos.spec
Update raft to 0.8.1 to fix InstallSnapshot performance as well as to
avoid some incorrect 0.8.0 RPMs.
=> DAOS-7623 utils: Update raft to 0.8.1

src/tests/ftest/container/list_containers.py, src/tests/ftest/container/list_containers.yaml
Test-tag: list_containers
- Fix usage of container_create in test_list_containers
=> DAOS-8585 test: fix test_list_containers

src/tests/ftest/pool/uuid_corner_case.py
Pool label is required at creation time, so the test to create without it is invalid.
=> DAOS-8454 test: Removed test_create_destroy_uuid

src/utils/daos_hdlr.c
Check return code in daos_cont_open that handles opening containers
for fs_copy and cont_clone
Test-tag: pr fs_copy cont_clone
=> DAOS-8543 daos: check return from daos_cont_open

src/client/dfuse/dfuse_fuseops.c
Check for FUSE_CAP_CACHE_SYMLINKS, FUSE_CAP_NO_OPENDIR_SUPPORT and
FUSE_CAP_EXPLICIT_INVAL_DATA in the want flags so we can log
if the kernel supports them.
Downgrade the message for unknown flags from a error to a warning.
There is no code change here, dfuse simply logs the features that
libfuse is offering, the issue is that a newer kernel and libfuse
had set some feature bits that dfuse was not aware of, this change
simply logs the feature bits by name on startup.
=> DAOS-8190 dfuse: Add checking for new fuse flags.

src/include/daos_srv/ras.h, src/include/daos_srv/vos.h, src/vos/vos_pool.c
Raise RAS event for deferred pool destroy.
=> DAOS-8053 vos: ras event for deferred pool destroy

src/control/cmd/dmg/command_test.go, src/control/cmd/dmg/pool.go, src/control/cmd/dmg/pool_test.go, src/control/common/proto/mgmt/addons.go, src/control/lib/control/pool.go
As the label is now a required parameter, it should be
settable as a positional argument. The existing --label
flag is kept but marked as deprecated.
=> DAOS-8565 control: Allow positional label for pool create

src/control/server/ctl_smd_rpc.go
Instead of failing, just skip the device health query for any SSDs
in the “NEW” state. This way the health output of all devices will
be printed with dmg storage query list-devices --health instead of
failing with a single “NEW” device.
=> DAOS-8557 ctrl: Skip health query for "NEW" devices

docs/admin/administration.md, docs/admin/deployment.md, src/control/cmd/dmg/pretty/storage_nvme.go, src/control/cmd/dmg/pretty/storage_nvme_test.go, src/control/cmd/dmg/pretty/storage_test.go
Error in SMART stats output now resolved.
Intel Vendor SMART Attributes:
Program Fail Count:
Normalized(%%):100 --> Normalized:100%
=> DAOS-8545 dmg: Fix double percent mark in SMART stats output

src/tests/ftest/SConscript, src/tests/ftest/telemetry/telemetry_pool_metrics.py, src/tests/ftest/telemetry/telemetry_pool_metrics.yaml, src/tests/ftest/util/telemetry_utils.py
Adding test to verify pool metrics data for
"engine_pool_ops_fetch", "engine_pool_ops_update",
"engine_pool_xferred_fetch", "engine_pool_xferred_update"
Test-tag: telemetry_pool_metrics
Test-repeat: 5
=> DAOS-8357 test: Adding pool metric verification test

src/cart/utils/crt_utils.c
Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>
=> CART-981 tests: Move net_cfg_setenv before crt_init

src/object/cli_obj.c, src/object/srv_ec_aggregate.c
- obj_comp_cb should destroy bulk handle for degraded mod
- targets returned by pool_map_find_failed_tgts should be
freed
=> DAOS-6808 object: Fix a few memory leaks for EC

src/include/daos_errno.h, src/object/cli_ec.c, src/object/cli_obj.c
Refine shard tasks' error code handling, add a new error code
DER_TGT_RETRY as previous DER_BAD_TARGET possibly conflict with
cart's failure case.
Change obj_ec_recov_tgt_recx_nrs() a little bit to avoid assertion.
=> DAOS-8082 obj: fix an assertion in obj_ec_recov_tgt_recx_nrs

src/container/srv_container.c, src/tests/suite/daos_test_common.c, src/vos/vos_obj.c
Use default label for containers in daos_test when a label isn't
passed via the properties.
Also with this change, modify container service code that renames
a container (via set prop) so that in the cs_uuids KVS the new label
akey insert is done before punching the old label akey. When there is
a single entry in cs_uuids, this approach avoids a momentary empty KVS
in the same epoch that would cause vos punch propagation (on the dkey).
And avoids vos returning -DER_NO_PERM due to punch and update.
Change vos_obj_punch() logging to print epoch in hex, aligning it
with other vos logging.
Co-authored-by: Johann Lombardi <johann.lombardi@intel.com>
=> DAOS-8591 test, container: enable default label in daos_test

docs/admin/administration.md, docs/admin/deployment.md, src/bio/bio_monitor.c, src/control/cmd/dmg/pretty/storage_nvme.go, src/control/cmd/dmg/pretty/storage_nvme_test.go, src/control/cmd/dmg/pretty/storage_test.go, src/control/lib/spdk/src/nvme_control_common.c
The output for Intel SMART stats for Timed Workout, Media Wear was
falsely reporting a confusing percentage for media wear, instead of the
raw value. The media wear percentage is only meaningful after a
reasonable workload > 60 min is conducted, and the value can then be
converted to a percent.
Timed Workload, Media Wear: 65535 (raw, reset value)
Timed Workload, Media Wear: 41 (after workload test)
Media wear = 41/1024 = 0.04%
=> DAOS-8549 dmg: Fix percent output for media_wear_raw SPDK health stats

src/engine/sched.c, src/engine/srv.c, src/engine/srv_internal.h, src/include/daos_srv/daos_engine.h
sched_exec_time() is to get the elapsed time since the current
ULT/task was scheduled last time. It's introduced for debug purpose,
caller can call this function to tell if current ULT/Task is hogging
CPU for too long.
sched_exec_time() is enabled for sys xstream by default, one can set
"DAOS_SCHED_WATCHDOG_ALL=1" to enable it for VOS xstreams as well.
=> DAOS-8561 sched: sched_exec_time()

src/client/dfs/dfs.c
strncpy does not NULL terminate in edge case.
=> DAOS-8631 dfs: fix coverity issue 329522

src/bio/bio_internal.h, src/bio/bio_recovery.c, src/bio/bio_xstream.c
On device state transition, BIO used to check the per-xstream io
stats open descriptor to see if the setup procedure is done, however,
this open descriptor was removed by 'commit 639a3d0b76e2 ("DAOS-6526
bio: export SSD smart info via d_tm (#5413)")', and the device state
transition logic wasn't adjusted accordingly.
This patch introduced per-xstream 'bxc_ready' flag to indicate
if the setup procedure for a xstream is finished.
=> DAOS-8600 bio: properly check xstream setup state

src/control/cmd/dmg/pool.go, src/control/cmd/dmg/pretty/pool.go, src/control/lib/control/pool_property.go, src/control/server/storage/bdev/backend_vmd.go
- Avoid dividing by zero. (332706, 332705)
- Remove check for uint < 0. (332670)
- Clarify logic that caused a false positive in Coverity, so the intent
is clearer to readers. (333475)
=> DAOS-8630 control: Fix static analysis issues

src/dtx/dtx_rpc.c
During rebuild, DTX refresh may hits -DER_STALE when
locate the leader for non-rebuilt EC object. That is
not fatal and will cause related request sponsor to
repeatedly retry until rebuild done or hit some other
failure. Such repeatedly retry may generate huge of
log message as to the server out of space. Since it
is not fatal, convert it from "ERROR" to "TARCE" in
the log.
=> DAOS-8641 dtx: avoid noisy error log message

src/object/cli_obj.c
If no_retry is set for the task, which is usually used by migration
task, then it should not check io_retry, otherwse both io_retry and
no_retry will be set, and retry_cb will not be scheduled, so bulks
will not freed, but its buffer allocated by DAOS will be freed, so
later if the data arrive, it will cause segfaults.
Missing bulk free if retry_cb() failed.
=> DAOS-8542 object: missing bulk free in obj_comp_cb

src/tests/ftest/daos_test/dfs.py, src/tests/ftest/daos_test/dfs.yaml
Test-tag: daos_test,dfs
- Increase test_daos_dfs_sys timeout to 90
- Tag tests with "dfs"
=> DAOS-8650 test: increase test_daos_dfs_sys timeout

src/tests/ftest/server/daos_server_restart.py, src/tests/ftest/server/daos_server_restart.yaml
the agent's cached rank->uri map can get out of sync with the servers
if the agent is not restarted when the servers are.
Test-tag-hw-large: pr,hw,large,server_reformat DAOS_5610
=> DAOS-8621 test: restart daos agents with daos server restart

src/include/daos/common.h, src/object/cli_ec.c, src/object/cli_obj.c, src/object/obj_tx.c, src/object/srv_ec.c, src/tests/suite/daos_degrade_ec.c
When #fail_shard < #parity, should allow obj update success, rather than
fail it.
Fixed several bugs related with dc_tx_convert()/obj_ec_rw_req_split()
and obj_ec_tgt_oiod_init() that may affect details in co-located
layout and EC handling.
=> DAOS-8583 EC: allow EC degraded update

docs/user/filesystem.md, src/client/dfuse/dfuse_core.c
Fix a bug where minutes were not accepted, and add support
for hours and days.  Update documentation accordingly.
=> DAOS-8604 dfuse: Allow cache times in minutes, hours and days.

src/vos/tests/vts_gc.c
Errors from dts_ctx_init() are not relayed by gc_setup(), this
allows GC subtests to be wrongly run anyway and thus also
group-teardown routine gc_teardown(), leading to dts_ctx_fini()
to be called, even if it had been already during error-path in
dts_ctx_init(), causing too early extraneous unreferencing and
freeing of self_mode.self_tls with later crash consequences upon
dereferencing for next test-groups running attempts.
Simply relaying these errors from group-setup routine will allow
cmocka to handle this gracefully, by not running associated
sub-tests not group-teardown, and thus keep self_mode in a
consistent state.
Change-Id: Ife0fa364c33c09ef0a3d440a9ccef6866cef6488
=> DAOS-7670 tests: report errors from gc_setup()

src/client/serialize/daos_serialize.c
DAOS-8632 client: fix coverity issues in daos_serialize library
CID 332911: Uninitialized scalar variable (UNINIT)
uninit_use_in_call: Using uninitialized value coh
when calling daos_cont_close.
CID 332912: Resource leak (RESOURCE_LEAK)
leaked_storage: Variable prop going out of scope
leaks the storage it points to.
CID 332915: Resource leak (RESOURCE_LEAK)
leaked_storage: Variable names going out of scope
leaks the storage it points to.
CID 332916: Resource leak (RESOURCE_LEAK)
Variable buffers going out of scope leaks the
storage it points to.
=> DAOS-8632 client: fix coverity issues in daos_serialize library

src/object/srv_obj.c, src/vos/vos_dtx.c
There are some cases that current ULT may be blocked and yield during
DTX process, such as some NVMe operation (allocation, data copy). And
related RPC may be resent and handled by another ULT. Under such case,
when the blocked ULT is scheduled again, it needs to check resent RPC
to properly handle the case of the DTX for resent RPC being committed
before its original RPC.
=> DAOS-8492 object: check resent RPC during DTX with CPU yield

src/tests/ftest/container/snapshot.py
DAOS-8602-test: container/snapshot RC -1005 when snapshot destroy the 2nd snapshot by daos_api
modified: container/snapshot.py
Summary: Script updates with current_snapshot object in destroying snapshot loop for destroying multiple snapshots, and removed the redundant step (8).
Test-tag: pr snapshots
Co-Author: Kenneth Cain kenneth.c.cain@intel.com
=> DAOS-8602-test: container/snapshot RC -1005 when snapshot destroy the 2nd snapshot by daos_api

src/object/srv_ec_aggregate.c
Ad PR6732 (8aca03a3ef) landed, vos_iterate() internally set
VOS_ITER_CB_YIELD when needed, remove related code in EC agg.
=> DAOS-8082 EC: cleanup yield in EC aggregation

src/control/common/storage/commands.go
"-b" is overloaded with debug and block list options, remove the short
command aliases to avoid the conflict.
=> DAOS-8676 control: daos_server storage prepare has duplicate -b option

src/client/java/daos-java/src/main/java/io/daos/DaosContainer.java, src/client/java/daos-java/src/main/java/io/daos/obj/IOSimpleDDAsync.java, src/client/java/daos-java/src/main/native/io_daos_DaosClient.c
It's ok to list attributes from one container in Java. But failed when more than one container. 
The cause is the buffer size parameter in list_cont_attribute is type of 4-byte int whilst it should be 8-byte size_t.
=> DAOS-8657 Failed to list attributes from more than one container in Java

src/vos/ilog.c, src/vos/vos_obj.c
332770 - rc check is never true in ilog.c
329605 - goto has no effect in vos_obj.c
=> DAOS-8637 coverity: Fix coverity issues reported on VOS

src/client/dfs/dfs.c, src/client/dfuse/dfuse_cont.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/dfuse_pool.c, src/client/dfuse/dfuse_thread.c, src/client/dfuse/ops/create.c, src/client/dfuse/ops/lookup.c, src/client/dfuse/ops/mknod.c, src/client/dfuse/ops/readdir.c, src/client/dfuse/ops/rename.c, src/client/dfuse/ops/symlink.c, src/client/dfuse/ops/unlink.c
Correctly handle errors from sem_init()
dfs_cont_create() needs to return system error code.
Correctly terminate strings after copy.
=> DAOS-8628 dfuse: Resolve issues identified by coverity

src/client/api/object.c, src/common/pool_map.c, src/dtx/dtx_resync.c, src/object/srv_obj.c, src/tests/ftest/nvme/pool_exclude.py, src/tests/ftest/nvme/pool_exclude.yaml
Mainly contain three fixes:
1. The RF property should be enough for two targets failure
(excluded) in nvme_pool_exclude test. Otherwise, the IOR
will get DER_RF(2031) during the test.
2. There is CPU yield during DTX resync. That is normal that
someone may has punched the object during the interval of
resync the DTX enteries (that are related with the object)
and marking the object as re-synced.
3. Trying to verify a non-exist object is not fatal failure.
Test-tag-hw-large: pr,hw,large nvme_pool_exclude
=> DAOS-8449 tests: misc fixes for nvme_pool_exclude

src/tests/ftest/util/dfuse_utils.py
Improve dfuse cleanup in case of crash on client.
Adding conditon when there is no fuse process running
and dfuse is still mounted.
=> DAOS-8639 test: Improve dfuse crash handling in test

src/tests/ftest/dfuse/posix_stat.py, src/tests/ftest/dfuse/sparse_file.py
Tag all tests in ftest/dfuse with "dfuse"
Test-tags: dfuse,dfusesparsefile dfuse,stat_parameters
=> DAOS-8652 test: tag tests in ftest/dfuse

src/cart/crt_init.c
- Change init time warnings for srx and universe size to info
- Only check port ranges for port-based providers
=> CART-89 cleanup: Change some warnings to info level

src/tests/ftest/launch.py
Improve tag argument processing to only allow test filenames that exist.
=> DAOS-8021 tests: Fix Checkmarx XML Handling Issues in Test Launcher

src/include/daos/dtx.h, src/include/daos_srv/evtree.h, src/include/daos_srv/vos_types.h, src/vos/evt_iter.c, src/vos/ilog.c, src/vos/ilog.h, src/vos/tests/vts_ilog.c, src/vos/vos_aggregate.c, src/vos/vos_dtx.c, src/vos/vos_ilog.c, src/vos/vos_ilog.h, src/vos/vos_internal.h, src/vos/vos_obj.c, src/vos/vos_obj_index.c
* Follow-up patch to prior patch that implemented vos_discard for single
object epoch range.
* Modify discard to actually remove everything, including uncommitted data.  It's used for snapshot rollback so uncommitted data in the range should be removed too.
* For object specific discard, only discard uncommitted entries.
* need_aggregate should always return true for discard
=> DAOS-8559 vos: Ensure aggregation not running with obj discard

src/client/dfs/duns.c
=> DAOS-623 duns: use strncpy instead of snprintf

src/cart/crt_corpc.c
Incoming bulk handler is overwritten by  new without free.
=> DAOS-8498 cart: Fix bulk handler leak

src/client/api/event.c, src/client/array/dc_array.c, src/client/dfs/dfs.c, src/client/dfuse/dfuse_core.c, src/tests/suite/dfs_par_test.c
- just in case the scheduler does not recognize the dependency of the
parent task to the size task, add the size task to be scheduled with
the io tasks and not seperately to take care of possible races.
- fix some possible leaks with FI testing
- call event fini in dfuse
- other minor code format and test fixes.
=> DAOS-8890 & 8924 array: combine short read task in IO read list

utils/test_memcheck.supp
Add EL8 version of libevent suppression
=> DAOS-8869 memcheck: Add suppression for EL8 (#7127)

src/tests/ftest/fault_injection/pool.py, src/tests/ftest/fault_injection/pool.yaml
The test should detect failures when creating/destroying pools and containers.
The test was previously failing because it was not detecting the injected faults.
Features: test_pool_services
=> DAOS-8610 test: Fix pool fault injection test (#6846)

src/object/srv_obj.c
master-commit: e8f70a152ecdb4ea7efba7c17e7762f07812acb5
On server side, for enumeration handler, dynamically allocate "anchors"
variable on heap instead of allocating it on stack. That can save about
1.4KB stack space.
=> DAOS-8433 object: reduce stack usage for enumeration

src/container/srv_container.c, src/control/cmd/daos/container.go, src/control/cmd/daos/util.c, utils/node_local_test.py
* Run this under NLT so that server memory leaks can be detected.
* Resolve memory leaks.
=> DAOS-8204 test: Add a test for "container list". (#6325)

src/rebuild/scan.c, src/rebuild/srv.c
Similar as reintegration, reclaim should be scheduled after extend
as well.
Change a few important DB_REBUILD log to D_INFO.
During rebuild scan, let's skip invalid objects.
=> DAOS-8889 rebuild: reclaim for extend (#7103)

src/control/cmd/daos_agent/agent_test.go
With 128 child processes, the test was failing intermittently
with broken pipe errors, most likely due to hitting an open
file handle limit.
=> DAOS-8950 test: Reduce # of children in GetAttachInfo test

src/control/cmd/daos_agent/agent_test.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/infocache_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/lib/control/mocks.go
Eliminate racy initialization of the AttachInfo cache that
can occur when multiple client applications all start at
the same time.
=> DAOS-8707 control: Fix agent AttachInfo cache (#7055)

src/container/srv_container.c, src/container/srv_target.c, src/dtx/dtx_common.c, src/dtx/dtx_rpc.c, src/engine/sched.c, src/include/daos_srv/daos_engine.h, src/pool/srv_pool_scrub.c, src/pool/srv_target.c, src/rebuild/scan.c
Argobots dictates the following:
- A ULT that is not unnamed must be freed explicitly via
ABT_thread_free. (ABT_thread_join does not do this.)
- An unnamed ULT cannot be freed explicitly via ABT_thread_free.
- A ULT cannot free itself.
- ABT_thread_free implicitly joins the ULT before freeing it.
- An unnamed ULT cannot be joined via ABT_thread_join.
In several modules, ULTs are only joined but not freed, leading to ULT
leaks. This patch replaces these ABT_thread_join calls with
ABT_thread_free call, which both join as well as free. Also, in some
error paths among those cases, the ULTs may not terminate, leading to
hangs. This patch adopts a check-if-req-is-null-in-the-ULT approach from
other error paths, whose correctness subtly relies on the absence of
yielding between the ULT creation …
=> DAOS-8888 misc: Fix ULT leaks

src/control/lib/control/event.go
When an event was successfully forwarded to the MS leader,
log which machine received it.
Test-tag: pr ms_resilience ms_failover
=> DAOS-8446 control: Add debug logging for event forwarding

src/object/cli_obj.c, src/object/srv_obj_migrate.c, src/tests/ftest/daos_test/suite.yaml, src/tests/suite/daos_rebuild_ec.c
Since migrate will convert both parity and replicate
extent into DAOS offset, so let's merge them to remove
the overlap area, which might exist if parity shards are
not being aggregated yet.
Add test cases to verify it.
Set service replica as 5 for daos_replica_ec test to make
sure PS service is always avaible after exclude ranks.
=> DAOS-8939 rebuild: Overlap update for EC 2P object

src/control/cmd/daos_agent/agent_test.go
It's causing intermittent failures in CI and affecting PRs.
=> DAOS-8967 test: Disable daos_agent.TestAgent_MultiProcess_AttachInfoCache

src/control/cmd/daos_agent/agent_test.go
It's causing intermittent failures in CI and affecting PRs.
=> DAOS-8967 test: Disable daos_agent.TestAgent_MultiProcess_AttachInfoCache (#7189)

src/tests/ftest/osa/offline_drain.py, src/tests/ftest/osa/offline_reintegration.py
start_ior_load() API was modified to accommodate a few changes, part of that operation needs to be passed as an argument for auto-filled.
Test-tag-hw-medium: pr,hw,medium,ib2 offline_drain offline_drain_full offline_reintegration_daily offline_reintegration_full
=> DAOS-7160 Test: Updating the core API function based on recent modification.

src/tests/ftest/aggregation/shutdown_restart.py, src/tests/ftest/aggregation/shutdown_restart.yaml
Description: Update EC by default for aggregation/shutdown_restart tests.
modified:   shutdown_restart.py
modified:   shutdown_restart.yaml
Test-tag: ioaggregation
=> DAOS-7312-test4a: Functional testing for EC auto object class selection and move some existing tests to use EC by default

src/object/cli_obj.c
(master commit - fe0db608b)
1. in shard_task_sched() reinit the task after register dependency,
this is safer for multi-threads because the task can be scheduled
right after reinit.
2. don't reuse original shard tasks when retry fetch
3. a few other refine for retry handling
=> DAOS-8607 obj: refine task retry handling (#7121)

src/object/cli_obj.c, src/object/srv_obj_migrate.c, src/tests/ftest/daos_test/suite.yaml, src/tests/suite/daos_rebuild_ec.c
Since migrate will convert both parity and replicate
extent into DAOS offset, so let's merge them to remove
the overlap area, which might exist if parity shards are
not being aggregated yet.
Add test cases to verify it.
Set service replica as 5 for daos_replica_ec test to make
sure PS service is always avaible after exclude ranks.
=> DAOS-8939 rebuild: Overlap update for EC 2P object (#7167)

src/cart/README.env, src/cart/crt_init.c, src/vos/vos_internal.h, src/vos/vos_pool.c
Change CART envirable to turn on memory pinning globally
with it off by default.   Instead, lock each vos pool
individually.
=> DAOS-8927 vos: Lock memory for VOS pools

src/control/lib/netdetect/netdetect_test.go
In hwloc 2.0+, a NUMA node is automatically added to the
topology if the synthetic topology did not contain one.
A number of the unit tests were written with the assumption
that a loaded topology could contain 0 NUMA nodes, and are
therefore not valid anymore.
=> DAOS-8873 control: Fix hwloc tests on el8 (#7093)

src/control/lib/control/rpc_test.go
Add a runtime check to disable advanced testing features
when run on older versions of Go.
=> DAOS-8868 test: Fix control test on Go < 1.15

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache_test.go, src/control/lib/netdetect/netdetect.go, utils/nlt_server.yaml
- Remove exceptions for loopback interface in network detection
in daos_agent. Loopback is now treated like any other network
interface.
- Recognize loopback type in netdetect.
- Update NLT config to test over loopback.
=> DAOS-8855 agent: Fix lo network device detection

src/vos/tests/vts_mvcc.c, src/vos/vos_obj.c, src/vos/vos_tree.c
Enable punch propagation to object level and associated mvcc tests
Enable propagation optimization that saves the umem offset of the last
key known to exist so we can skip iterating if the key hasn't been punched.
This has potentially make punch propagation significantly cheaper so
it can be enabled a the object level, potentially making the object
emptiness check faster too.
=> DAOS-7878 vos: Implement punch propagation optimization

src/container/srv_container.c, src/container/srv_target.c, src/include/daos_srv/container.h, src/object/srv_ec_aggregate.c
Since collective reduce may cost too much time here, so let's instead
allocating an array for all local VOS targets, then assigning each
individual item from the array to each target, which will be
updated by each xstream container EC aggregation ULT, then the EC query
ULT on system xstream will find the minimum eph by just checking the array.
=> DAOS-8345 EC: Not using collective reduce for aggregation eph query

src/tests/ftest/object/create_many_dkeys.py, src/tests/ftest/object/create_many_dkeys.yaml
Description: Fix script failure due to output of unicode and
-1007 not enough space with 10k dkeys.
modified:   create_many_dkeys.py
modified:   create_many_dkeys.yaml
Test-tag: many_dkeys
=> DAOS-8904-test2: Fix and enable object/create_many_dkeys.py

src/tests/suite/daos_test_common.c
Use random number for container label in daos_test, to
avoid duplicate labels if it needs to create multiple
container for the test.
=> DAOS-8908 tests: use random number for container label

src/object/cli_obj.c, src/tests/suite/daos_epoch_io.c
Fix a typo of punch opcode in dc_obj_punch, and a few other refinings.
=> DAOS-8900 obj: fix a typo in dc_obj_punch

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/infocache_test.go, src/control/cmd/daos_agent/mgmt_rpc.go
Move interface domain-checking logic into the fabric cache to
avoid returning an interface without a domain when a verbs
provider is used.
=> DAOS-8850 agent: Improve iface detection for verbs (#7144)

ci/rpm/test_daos_node.sh
Ensure that if daos_test -m hangs, the test does not hang indefinitely.
Try to get daos_server output if daos_test -m hangs or otherwise exits
!0.
=> DAOS-8984 test: Add a timeout to the RPMs test

src/control/lib/control/rpc_test.go
Add a runtime check to disable advanced testing features
when run on older versions of Go.
=> DAOS-8868 test: Fix control test on Go < 1.15 (#7090)

Jenkinsfile
Let parseStageInfo() figure that out as it knows more.
=> DAOS-623 ci: Don't specify the target on HW stages

src/include/gurt/common.h, src/mgmt/srv_target.c, src/vos/vos_pool.c
mlock will fail if trying to lock memory to a page boundary and
PMDK doesn't even map the whole space if there are leftover bits
on a page.   Just round up the size to the next page boundary.
=> DAOS-8927 vos: Fix vos pool locking to align scm size to a page

src/include/daos/placement.h, src/object/cli_obj.c, src/object/obj_internal.h, src/placement/pl_map_common.c
Since we do not allow inflight I/O for reintegrating shard,
so let's return EIO for such update until online reintegration
is supported.
=> DAOS-8894 objects: return EIO for inflight reintegrate IO

src/control/server/server.go
Upon gaining leadership state, the MS needs to request a GroupUpdate
in order to ensure that all ranks have the latest group map. The
request should not happen until at least one rank is ready to receive
the request, in order to avoid spurious error messages.
=> DAOS-8882 control: Wait for ready engine before GroupUpdate

src/control/common/pci_utils.go, src/control/common/pci_utils_test.go
* Rename PCIAddressList -> PCIAddressSet, to better reflect
the use/capabilities of the type
* Make PCIAddressSet use a map as the core data structure, for
automatic deduplication
* Sort on demand when Addresses() is called
=> proposed updates

src/client/dfuse/il/int_posix.c, src/client/dfuse/ops/ioctl.c
If a non-file is opened by the IL then we currently get an error
in dfuse from the ioctl, and a error-path is taken in the IL
that will cause it to disconnect from the container.
After this patch we take the following behaviour:
When a directory is opened the container/pool are opened and
dfs is mounted, however when it comes to opening the dfs object
the ioctl code in dfuse will return with E_ISDIR rather than
EINVAL and the IL itself will spot this and not attempt to
release resources - so it will keep dfs mounted for any future
access.
=> DAOS-9017 dfuse: Add checking for fetching handles for non-files.

src/pool/srv_target.c
Do not stop gc ULT thread before all workers ULTs running
on ds_pool_child have completed, because some of them, like
container_aggregate, can be late and need to schedule gc ULT.
This patch is a follow-on to DAOS-8546/PR-6079, where it is
ensured to wait for all late workers ULTs to be done prior
terminating ds_pool_child.
Change-Id: I7def5c933ca78de3818b3cd7e8bf9d9b708b31d0
=> DAOS-8825 pool: stop gc ULT when all ops ULTs are gone

src/cart/README.env, src/cart/crt_init.c, src/include/gurt/common.h, src/mgmt/srv_target.c, src/vos/vos_internal.h, src/vos/vos_pool.c
Change CART envirable to turn on memory pinning globally
with it off by default.   Instead, lock each vos pool individually.
=> DAOS-8927 vos: Lock memory for VOS pools (#7153)

src/tests/suite/daos_test_common.c
Use different container label for daos test.
=> DAOS-8908 tests: use different container label (#7118)

src/tests/ftest/object/create_many_dkeys.py, src/tests/ftest/object/create_many_dkeys.yaml
Description: Cherrypick for release_2.0, fix script failure due to output of unicode and
-1007 not enough space with 10k dkeys.
modified: create_many_dkeys.py
modified: create_many_dkeys.yaml
Test-tag: many_dkeys
=> DAOS-8904-test_rel_2.0: Fix and enable object/create_many_dkeys.py

src/object/cli_obj.c, src/tests/suite/daos_epoch_io.c
(master commit 9c89307db)
Fix a typo of punch opcode in dc_obj_punch, and a few other refinings.
=> DAOS-8900 obj: fix a typo in dc_obj_punch (#7187)

src/include/daos/placement.h, src/object/cli_obj.c, src/object/obj_internal.h, src/placement/pl_map_common.c
Since we do not allow inflight I/O for reintegrating shard,
so let's return EIO for such update until online reintegration
is supported.
=> DAOS-8894 objects: return EIO for inflight reintegrate IO (#7120)

src/control/server/server.go
Upon gaining leadership state, the MS needs to request a GroupUpdate
in order to ensure that all ranks have the latest group map. The
request should not happen until at least one rank is ready to receive
the request.
=> DAOS-8882 control: Wait for ready engine before GroupUpdate (#7242)

src/include/daos_srv/vea.h, src/include/daos_srv/vos.h, src/pool/srv_target.c, src/vea/tests/vea_ut.c, src/vea/vea_api.c, src/vea/vea_free.c, src/vos/vos_gc.c, src/vos/vos_pool.c
- Get rid of VEA 'plug' operation. The 'plug' operation was introduced
for improving space reclaiming speed on container destroy, however,
it could result in too many frags stays in aging buffer for too long
time.
- Explicitly call vea_flush() in GC ULT, and don't sleep if there are
frags to be flushed.
- Add back flush triggering on reserve, otherwise, too many aging
frags could be accumulated in aging buffer.
- Restrict the number of frags on each flush to avoid hogging CPU for
too long.
=> DAOS-8930 vea: various frag flushing fixes

src/client/dfs/dfs.c
This variable isn't used, and it's presence is casuing warnings
in the Intel compiler.
=> DAOS-9032 dfs: Remove mode variable.

src/mgmt/cli_mgmt.c, src/tests/ftest/launch.py, src/tests/ftest/network/zero_config.py, src/tests/ftest/util/server_utils_params.py
The network interface and domain must be acquired from the same
source, either the agent automatic config, or the OFI_INTERFACE
and OFI_DOMAIN environment variables.
=> DAOS-8916 client: Fix potential OFI interface/domain mismatch

src/include/daos_srv/vea.h, src/include/daos_srv/vos.h, src/pool/srv_target.c, src/vea/tests/vea_ut.c, src/vea/vea_api.c, src/vea/vea_free.c, src/vos/vos_gc.c, src/vos/vos_pool.c
- Get rid of VEA 'plug' operation. The 'plug' operation was introduced
for improving space reclaiming speed on container destroy, however,
it could result in too many frags stays in aging buffer for too long
time.
- Explicitly call vea_flush() in GC ULT, and don't sleep if there are
frags to be flushed.
- Add back flush triggering on reserve, otherwise, too many aging
frags could be accumulated in aging buffer.
- Restrict the number of frags on each flush to avoid hogging CPU for
too long.
=> DAOS-8930 vea: various frag flushing fixes (#7171)

src/client/dfs/dfs.c
This variable isn't used, and it's presence is casuing warnings
in the Intel compiler.
=> DAOS-9032 dfs: Remove mode variable. (#7278)

src/include/daos/common.h, src/object/cli_obj.c, src/object/srv_ec.c, src/tests/suite/daos_aggregate_ec.c, src/tests/suite/daos_degrade_ec.c, src/tests/suite/daos_epoch_io.c, src/tests/suite/daos_iotest.h, src/tests/suite/daos_obj.c, src/tests/suite/daos_rebuild_ec.c
The problem is in detailed handing in EC degraded update.
1) fix an assertion in obj_ec_rw_req_split()
Assertion 'tgts[i].st_shard >= start_shard' failed
2) small refine in obj_shards_2_fwtgts()
3) add test case to reproduce/verify the problem.
=> DAOS-8961 obj: fix a bug in EC degraded update

src/mgmt/cli_mgmt.c, src/tests/ftest/launch.py, src/tests/ftest/util/server_utils_params.py
The network interface and domain must be acquired from the same
source, either the agent automatic config, or the OFI_INTERFACE
and OFI_DOMAIN environment variables.
Replace the use of OFI_INTERFACE to provide a default fabric_iface value
to the server config with a new DAOS_TEST_FABRIC_IFACE environment
variable.  Launch.py will still use any existing OFI_INTERFACE value but
will no longer set the env.  In CI this will allow the launch node to
run without OFI_INTERFACE beign set.
Co-authored-by: Phillip Henderson <phillip.henderson@intel.com>
=> DAOS-8916 client: Fix potential OFI interface/domain mismatch (#7183)

src/engine/server_iv.c
Even though iv_ns_lookup is failed due to IV stop,
iv_ns_put is still needed to balance the get in
ivc_on_get().
=> DAOS-8832 IV: missing iv_ns_put

utils/rpms/daos.spec
=> DAOS-8935 build: fix rmem_{max,default} values applied in specfile

src/control/server/config/server.go, src/control/server/server.go, src/tests/ftest/control/ms_resilience.py
Wait for the killed ranks to be marked as excluded in the membership
before proceeding to pool operations. This will avoid RPC delays
and timeouts due to unreachable ranks.
Also improves a couple of error messages for the case when the
config has an unknown interface.
=> DAOS-8446 test: Update ms_resilience.py to wait for dead hosts

src/tests/ftest/launch.py, src/tests/ftest/scripts/main.sh, src/tests/ftest/scripts/setup_nodes.sh, src/tests/ftest/util/server_utils_params.py, src/tests/ftest/util/telemetry_utils.py
Adding support into launch.py to set the provider based upon the
selected interface driver by setting environment variables.  Any
existing environment variable definitions are honored to support
overriding the automatic/default setting.
=> DAOS-5165 tests: Enable functional hw large tests over verbs (#6626)

src/client/dfuse/ops/ioctl.c
Fix a couple of bugs in dfuse where if a call to dfs global
to local failed then the wrong error could would be returned,
a system error code would be assumed to be a daos one and
converted again.
Add a extra check for one place where the return value
was not being checked.
=> DAOS-8976 dfuse: Fix return codes if ioctl calls fail. (#7201)

src/tests/ftest/ior/intercept_basic.py, src/tests/ftest/ior/intercept_basic.yaml
Change the IOR intercept pass to be less susceptible to network issues.
Adjust the data size and stonewall time so that stonewall is not happening, meaning consistent
data sizes are used for comparison.
Fail the test if stonewalling does happen.
Run for 5 rather than one IOR iteration
Only perform the performance comparison on mean and max values, not min to prevent
slow network issue from failing the test, for the test to fail all iterations need to be slow.
This should allow the test to detect actual regressions, but not fail on intermittent issues
which often happen in CI due to the shared nature of the resource.
Adding file …
=> DAOS-5857 test: Update the expected IL performance in IOR test. (#7001)

src/common/tests/drpc_tests.c, src/common/tests/test_mocks.c, src/engine/tests/drpc_client_tests.c, src/engine/tests/drpc_progress_tests.c
- Fixed the skipped unit tests that hadn't been updated to return
a correct errno.
- Unskipped the tests.
=> DAOS-8834 test: Fix skipped drpc_client_tests

src/control/server/engine/exec.go
Currently, when the control plane process is terminated, the
engines are forcibly terminated right away. Instead, we should
give the engines a chance to shut down cleanly first.
=> DAOS-9055 control: Default to clean engine shutdown

src/client/dfuse/il/int_posix.c, src/client/dfuse/ops/ioctl.c
If a non-file is opened by the IL then we currently get an error
in dfuse from the ioctl, and a error-path is taken in the IL
that will cause it to disconnect from the container.
After this patch we take the following behaviour:
When a directory is opened the container/pool are opened and
dfs is mounted, however when it comes to opening the dfs object
the ioctl code in dfuse will return with E_ISDIR rather than
EINVAL and the IL itself will spot this and not attempt to
release resources - so it will keep dfs mounted for any future
access.
Adding file src/client/dfuse/il/int_posix.c
Adding file src/client/dfuse/ops/ioctl.c
=> DAOS-9017 dfuse: Add checking for fetching handles for non-files. (#7203)

src/include/daos_srv/vos_types.h, src/vos/vos_internal.h, src/vos/vos_iterator.c, src/vos/vos_layout.h, src/vos/vos_obj.c, src/vos/vos_pool.c, src/vos/vos_tree.c
For the case where the punch propagation optimization doesn't make
it to 2.0, this is a format change that is forward compatible with
the optimization so that we can add it later, if necessary without
another format change.
=> DAOS-7878 vos: Forward compatible durable format change

src/control/server/config/server.go, src/control/server/server.go, src/tests/ftest/control/ms_resilience.py
Wait for the killed ranks to be marked as excluded in the membership
before proceeding to pool operations. This will avoid RPC delays
and timeouts due to unreachable ranks.
Also improves a couple of error messages for the case when the
config has an unknown interface.
=> DAOS-8446 test: Update ms_resilience.py to wait for dead hosts (#7272)

src/control/server/mgmt_system.go, src/control/server/mgmt_system_test.go
When the request has been forced, there is no point in
preparing the ranks for shutdown, as they will be
forcibly killed in the next step.
=> DAOS-9070 control: Bypass PrepShutdown on forced SystemStop

src/include/daos_srv/vos_types.h, src/vos/vos_internal.h, src/vos/vos_iterator.c, src/vos/vos_layout.h, src/vos/vos_obj.c, src/vos/vos_pool.c, src/vos/vos_tree.c
For the case where the punch propagation optimization doesn't make
it to 2.0, this is a format change that is forward compatible with
the optimization so that we can add it later, if necessary without
another format change.
=> DAOS-7878 vos: Forward compatible durable format change (#7304)

src/cart/crt_context.c, src/cart/crt_hg.c, src/cart/crt_rpc.c, src/cart/crt_rpc.h, src/cart/crt_swim.c, src/cart/swim/swim.c, src/cart/swim/swim_internal.h, src/tests/ftest/cart/test_swim_emu.c
Removed usage of clock_gettime() and use HLC everywhere instead.
Turned off scheduling incoming SWIM RPCs by DAOS customization.
Changed progress timeout only for very long timeout to avoid
confusing of DAOS scheduler.
Add more debug timing traces for RPCs. Now we can see in logs:
- how long RPC scheduled for processing
- how long RPC send (it was in queue before send to wire)
- how long RPC was processed before reply
=> DAOS-9033 swim: Avoid busy loop in SWIM progress

src/control/server/mgmt_system.go, src/control/server/mgmt_system_test.go
When the request has been forced, there is no point in
preparing the ranks for shutdown, as they will be
forcibly killed in the next step.
=> DAOS-9070 control: Bypass PrepShutdown on forced SystemStop (#7346)

src/tests/ftest/launch.py, src/tests/ftest/network/zero_config.py
Enable running Functional Hardware Small tests with the verbs provider
when supported.
=> DAOS-8902 tests: Run HW Small tests with the verbs provider (#7110)

src/include/gurt/common.h
If the realpath was failing for an error other than ENOMEM then this
was segfaulting, so protect against that and ensure errno is set
correctly for other failure modes.
=> DAOS-8725 gurt: Fix crash in D_REALPATH macro.

src/rebuild/rebuild_internal.h, src/rebuild/scan.c, src/rebuild/srv.c
Let's keep send stable epoch to other servers to make sure
all servers get stable epoch, otherwise rebuild scan might
be stucked.
=> DAOS-8913 rebuild: send stable epoch to other servers multiple times

src/control/server/engine/exec.go
Currently, when the control plane process is terminated, the
engines are forcibly terminated right away. Instead, we should
give the engines a chance to shut down cleanly first.
=> DAOS-9055 control: Default to clean engine shutdown (#7311)

src/vos/vos_internal.h
The local id table for DTX allocates blocks of entries using the
lru array.  It always keeps one of these around.  The current
size is way too large for a per-container allocation and uses
18MB even if the dtx active table is empty.  This will cut it
down to a about 256KB for an empty table (for the array itself
and 1 free subarray).
This amounts to 1 extra malloc per 512 DTX entries so should be
lost in noise.  It still may be a bit heavy for 10K containers
but it's a lot less total memory than before.   We probably need
to look into a mechanism to free the last subarray for unused
containers.   The reason we currently don't is to avoid cases
where we allocate and free on every I/O.
=> DAOS-8082 vos: More conservative allocation of DTX LIDs

src/object/srv_obj.c
The comp_cb function pointer wasn't being checked for NULL. This
caused a crash in a case where a user tried to delete a file in
a container for which they did not have write permissions.
=> DAOS-9059 obj: Check function pointer for NULL

src/cart/crt_context.c, src/cart/crt_hg.c, src/cart/crt_rpc.c, src/cart/crt_rpc.h, src/cart/crt_swim.c, src/cart/swim/swim.c, src/cart/swim/swim_internal.h, src/tests/ftest/cart/test_swim_emu.c
Removed usage of clock_gettime() and use HLC everywhere instead.
Turned off scheduling incoming SWIM RPCs by DAOS customization.
Changed progress timeout only for very long timeout to avoid
confusing of DAOS scheduler.
Add more debug timing traces for RPCs. Now we can see in logs:
- how long RPC scheduled for processing
- how long RPC send (it was in queue before send to wire)
- how long RPC was processed before reply
=> DAOS-9033 swim: Avoid busy loop in SWIM progress (#7186)

src/include/daos/common.h, src/object/cli_obj.c, src/object/srv_ec.c, src/tests/suite/daos_aggregate_ec.c, src/tests/suite/daos_degrade_ec.c, src/tests/suite/daos_epoch_io.c, src/tests/suite/daos_iotest.h, src/tests/suite/daos_obj.c, src/tests/suite/daos_rebuild_ec.c
The problem is in detailed handing in EC degraded update.
1) fix an assertion in obj_ec_rw_req_split()
Assertion 'tgts[i].st_shard >= start_shard' failed
2) small refine in obj_shards_2_fwtgts()
3) add test case to reproduce/verify the problem.
=> DAOS-8961 obj: fix a bug in EC degraded update (#7212)

src/tests/ftest/control/dmg_pool_query_test.yaml
Per-target SCM usage is rounded to nearest page boundary.  Account
for this in the query to check the SCM size.
Test-tag: pool_query_basic
=> DAOS-9030 test: Adjust test to account for rounding

src/gurt/misc.c, src/include/daos/common.h, src/include/gurt/common.h, src/pool/srv_pool.c
Instead of always starting with rank 1, use a shuffled list
of target ranks to choose the pool service ranks. This will
help to avoid "hot spots" caused by putting all of the
pool service instances on the same ranks.
=> DAOS-8901 pool: Randomize distribution of pool svc ranks

src/dtx/dtx_common.c, src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c, src/include/daos_srv/dtx_srv.h, src/include/daos_srv/vos.h, src/object/srv_obj.c, src/vos/tests/vts_dtx.c, src/vos/tests/vts_mvcc.c, src/vos/vos_dtx.c
master-commit: f37bbbfd66484a02ba3ad991b4c2869e8b92f475
Currently, we do not have the usage of aborting multiple DTX entries
via signle API or RPC. Then we can simplify related VOS APIs to drop
useless parameters. The patch also avoids some small pieces of DRAM
allocation for DTX commit/abort.
On the other hand, the patch also adds some check for pool related
data strucutre to avoid access invalid DRAM when prepare DTX RPCs.
Another fixes: use read lock when access pool map for DTX refresh.
=> DAOS-8735 dtx: simplify DTX abort interface

src/cart/utils/memcheck-cart.supp
We've been seeing a new intermittent leak in testing
over the last week.
=> test: Add supression for new memory leak.

src/engine/srv.c
The SWIM xstream needs to start progressing crt quickly to respond to
incoming pings. Since it is out of the scope of
dss_{thread,task}_collective, it should safely skip the xstream barrier.
=> DAOS-8901 engine: Start swimming without barrier

src/object/srv_obj.c
The comp_cb function pointer wasn't being checked for NULL. This
caused a crash in a case where a user tried to delete a file in
a container for which they did not have write permissions.
=> DAOS-9059 obj: Check function pointer for NULL (#7363)

src/tests/ftest/control/dmg_pool_query_test.yaml
Per-target SCM usage is rounded to nearest page boundary.  Account
for this in the query to check the SCM size.
=> DAOS-9030 test: Adjust test to account for rounding (#7374)

src/vos/vos_internal.h
The local id table for DTX allocates blocks of entries using the
lru array.  It always keeps one of these around.  The current
size is way too large for a per-container allocation and uses
18MB even if the dtx active table is empty.  This will cut it
down to a about 256KB for an empty table (for the array itself
and 1 free subarray).
This amounts to 1 extra malloc per 512 DTX entries so should be
lost in noise.  It still may be a bit heavy for 10K containers
but it's a lot less total memory than before.   We probably need
to look into a mechanism to free the last subarray for unused
containers.   The reason we currently don't is to avoid cases
where we allocate and free on every I/O.
=> DAOS-8082 vos: More conservative allocation of DTX LIDs (#7338)

src/tests/ftest/pool/list_verbose.py
The test failed because the actual SCM size allocated to the pool
is slightly higher than what the user requested during the create.
Apply threshold to validate rather than the direct comparison.
Test-tag: list_verbose_basic
=> DAOS-9085 test: Fix pool/list_verbose.py in weekly

src/dtx/dtx_common.c, src/include/daos_srv/dtx_srv.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_rpc.h, src/object/srv_obj.c, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c
Originally, when hit non-committed DTX on non-leader, we may ask related
operation sponsor (the client) to retry without refreshing the DTX state
with the leader. But sometimes, the sponsor retry cannot resolve related
DTX state issue in time until such DTX is batched committed by th leader.
Then we can make DTX refresh as the default behavior under such case.
=> DAOS-7878 dtx: try DTX refresh by default

src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c, src/include/daos/dtx.h, src/include/daos/object.h, src/include/daos/placement.h, src/include/daos_srv/pool.h, src/object/cli_obj.c, src/object/obj_rpc.h, src/object/obj_tx.c, src/object/srv_ec_aggregate.c, src/object/srv_obj.c, src/placement/pl_map.c, src/pool/srv_pool.c
Mainly includes the followoing:
1. When modify EC object, allow related DTX leader to be on data shard
if all parity shards are unavailable. Such data shard should be one
of the shard that participates in related modification.
2. Client needs to tell DTX leader logic which shards (via some bitmap)
will participate in related IO when elect the DTX leader.
3. Server needs to pass dtx_memberships information to DTX leader logic
for which targets participated in the DTX when DTX resync/refresh.
4. EC aggregation does not need to depend on DTX leader logic. Because
DTX leader can be on data shard. EC aggregation need its own leader
to drive the EC aggregation from one of the parity shards globally.
5. Some bug in current DTX RPC prepare logic that may cause the RPC to
some remote target to be …
=> DAOS-8870 dtx: some DTX enhancement for EC object

src/tests/ftest/rebuild/basic.py
Test-tag: test_simple_rebuild test_multipool_rebuild
Test-repeat: 1
Check whether rebuild started on first pool alone wait_for_rebuild(True). Since the test uses small data the rebuild can be completed on other pools while we iterate all pools. Just check the start on the first pool and see whether rebuild completed on other pools later with wait_for_rebuild(False) call.
=> DAOS-8926 test: 2.0 Address flaky Rebuild/basic.py test failures.

src/tests/ftest/dfuse/find.py
test_find_perf expects a Lustre mount which is not available in CI.
replace full_regression with manual, since the test should just be ran
manually.
=> DAOS-6530 test: tag test_find_perf as manual (#7015)

src/include/gurt/common.h
If the realpath was failing for an error other than ENOMEM then this
was segfaulting, so protect against that and ensure errno is set
correctly for other failure modes.
=> DAOS-8725 gurt: Fix crash in D_REALPATH macro. (#7310)

src/common/tests/SConscript, src/common/tests/common-mock-ld-opts, src/common/tests/test_mocks.c, src/common/tests/test_utils.c, src/engine/tests/SConscript, src/include/daos/test_mocks.h, src/include/daos/test_utils.h
Simple link-time symbol substitution was becoming unreliable for
mocking system calls. Changed the affected tests to use the linker's
--wrap option instead via a linker script
- Rearranged unit test utils and mocks to remove a circular
dependency.
- Ensure all tests built with the --wrap flag include the __wrap_*
symbols.
=> DAOS-8969 test: Use linker wrap for drpc unit tests (#7306)

src/object/srv_obj_migrate.c
Missing FOR_MIGRATE flag for object migrate retry.
=> DAOS-8870 migrate: missing FOR_MIGRATE flag for obj enumeration (#7241)

src/client/dfuse/ops/setxattr.c
Reject rather than accept posix ACL updates.  If these are
accepted the kernel expects them to control future access
to the file, and neither dfuse nor dfs implmenents this so
we should reject any attempt to set these.
=> DAOS-8982 dfuse: Reject attempts to set posix ACLs via xattr. (#7205)

src/tests/ftest/pool/list_verbose.py
The test failed because the actual SCM size allocated to the pool
is slightly higher than what the user requested during the create.
Apply threshold to validate rather than the direct comparison.
=> DAOS-9085 test: Fix pool/list_verbose.py in weekly (#7383)

src/client/dfuse/dfuse_cont.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/dfuse_fuseops.c, src/client/dfuse/il/int_posix.c, utils/node_local_test.py
Remove the abilty to create a container in dfuse, and therefore
drop having to have write permissions on pools at all.
Remove, or upate and cleanup tests which used this feature.
=> DAOS-9056 dfuse: Remove pool write requirement from dfuse.

utils/node_local_test.py
This test can intermittently fail with caching on on faster systems
because the negative dentry from the set-attr is still valid for the
get-attr call.  Resolve this by not running this test with caching
enabled, only with it disabled.
=> DAOS-9063 test: Do not run daos_fs_tool with caching.

src/client/dfs/dfs.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/il/int_posix.c, src/object/cli_shard.c, src/tests/ftest/cart/util/cart_logparse.py, utils/node_local_test.py
Allow read-only access to other peoples containers to be
configures/used.  Previously all containers would be opened
RW, which always works for your own containers regardless
of permissions, however if another user has granted you
read-only access to theirs then cont_open will fail and
dfuse needs to re-try RO.
Remove a local from dfs.c to make it clear open mode is
not used here, and silence some log errors when writes
are attempted in read-only mode.
=> DAOS-9060 dfuse: Open containers in RO mode if RW fails.

src/include/daos_obj_class.h, src/object/obj_class.c, src/placement/tests/place_obj_common.c
Addressed following issues:
1. return value could be negative in error, but we define it as
size_t, fix to use ssize_t instead.
2. if allocated buf is not enough to hold all names, length is
still increased, this means wrong length might be returned, return
error in this case to caller.
3. check function return value properly.
=> DAOS-9061 obj: fix daos_oclass_names_list()

site_scons/components/__init__.py
- Add cmake flags to mercury build that appear to be required with
more recent cmakes.
=> DAOS-9114 build: Add cmake flags to mercury build

docs/QSG/setup.md, docs/QSG/suse_setup.md, docs/QSG/tour.md
remove references to daos-tests in the quick start docs
(not required for production deployments, and would introduce
dependencies on MPI which are very environment-specific)
Docs-only: true
=> DAOS-7924 doc: remove references to daos-tests

src/tests/ftest/checksum/csum_basic.py, src/tests/ftest/container/autotest.py, src/tests/ftest/pool/evict.py
Test-tag: basic_checksum_object containerautotest pool_evict
Remove full_regression tags from tests already tagged with
daily_regression.
=> DAOS-9004 test: remove full_regression from daily

src/client/dfuse/dfuse_cont.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/dfuse_fuseops.c, src/client/dfuse/il/int_posix.c, utils/node_local_test.py
Remove the ability to create a container in dfuse, and therefore
drop having to have write permissions on pools at all.
Remove, or update and cleanup tests which used this feature.
=> DAOS-9056 dfuse: Remove pool write requirement from dfuse. (#7336)

src/pool/srv_target.c
First patch for DAOS-8825 was intended to fix issues where GC
UL was stopped too early, but its changes had made it too late
and particularly after pool close tasks.
This is a backport of PR-7358 from master in release/2.0
Change-Id: Ifbac99117bc3d283857ee0217f0fc0a34ba4aac7
=> DAOS-8825 pool: do not stop GC ULT after pool close #7358

src/container/srv_container.c, src/container/srv_target.c, src/dtx/dtx_common.c, src/engine/sched.c, src/include/daos_srv/daos_engine.h, src/pool/srv_pool_scrub.c, src/pool/srv_target.c
Server component used to create an externally tracked ULT in following
code snippet:
{
dss_create_ult(... , &thread);
req = sched_req_get(attr, thread);
if (req == NULL) {
ABT_thread_free(thread);
return error;
}
}
The problem is that when sched_req_get() failed, there will be no way
to inform the 'thread' to abort, so the ABT_thread_free() on error
cleanup path would be blocked forever. (sched_get_req() usually won't
fail because most 'sched_request' are pre-allocated).
This patch introduced sched_create_ult() to solve above issue.
=> DAOS-8975 sched: introduce sched_create_ult()

src/object/cli_obj.c, src/placement/pl_map.c, src/tests/suite/daos_rebuild_simple.c
Missing reintegrating setting for inflight I/O.
Remove reintegrate I/O from rebuild simple test.
Co-authored-by: Jeff Olivier <jeffrey.v.olivier@intel.com>
=> DAOS-8775 object: missing reintegrating setting (#7322)

utils/config/daos_server.yml
clarify "immutable after reformat" in daos_server.yml
(https://github.com/daos-stack/daos/pull/7403 backported to release/2.0)
Doc-only: true
=> DAOS-5579 (doc): daos_server.yml clarification

src/tests/ftest/rebuild/no_cap.py, src/tests/ftest/rebuild/no_cap.yaml, src/tests/ftest/util/rebuild_test_base.py
The rebuild/no_cap.py is currently failing with unable to find any
available service ranks for the pool after stopping rank 1.  This change
increases the initial number of available ranks from 2 to 4.
Test-tag: no_cap
=> DAOS-9117 tests: Adding more ranks to rebuild/no_cap.py

src/tests/ftest/nvme/pool_exclude.yaml
Description: Updated pool_exclude.yaml with newly updated supported oclass RP_3G6
Test-tag: nvme_pool_exclude
=> DAOS-9129-test: Fix container create oclass RP_3G5 error

src/client/dfs/dfs.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/il/int_posix.c, src/object/cli_shard.c, src/tests/ftest/cart/util/cart_logparse.py, utils/node_local_test.py
Allow read-only access to other peoples containers to be
configures/used.  Previously all containers would be opened
RW, which always works for your own containers regardless
of permissions, however if another user has granted you
read-only access to theirs then cont_open will fail and
dfuse needs to re-try RO.
Remove a local from dfs.c to make it clear open mode is
not used here, and silence some log errors when writes
are attempted in read-only mode.
=> DAOS-9060 dfuse: Open containers in RO mode if RW fails. (#7359)

src/common/btree.c, src/include/daos/btree.h, src/object/srv_obj.c, src/vos/tests/vts_mvcc.c, src/vos/vos_obj.c, src/vos/vos_tree.c
* Rather than potentially iterating all keys twice during punch
propagation, iterate once and track whether we've seen
entries or uncommitted data.
* Use existing, unused space in the object and dkey durable format
to save offset of last key known to exist so we can skip scan.  This can
significantly speed up punch propagation in the common case by limiting
full scan to the occasional instance where the saved key is punched.
for punch propagation if the key hasn't been punched.
* Enable punch propagation to object level and associated mvcc tests
In vos_perf tests, I got the following results for punch of 100K dkeys
With this patch:                                0.7 seconds
with master branch:                             0.6 seconds
master branch with propagation to object level: 118 …
=> DAOS-7878 vos: Address punch propagation performance (#7218)

src/cart/crt_context.c, src/cart/crt_hg.c, src/cart/crt_rpc.c, src/cart/crt_rpc.h, src/cart/crt_swim.c, src/cart/swim/swim.c, src/cart/swim/swim_internal.h, src/tests/ftest/cart/test_swim_emu.c
Reverts daos-stack/daos#7186 due to spurious exclusion issues.
=> DAOS-9100 swim: Revert "DAOS-9033 swim: Avoid busy loop in SWIM progress"

src/cart/crt_context.c, src/cart/crt_hg.c, src/cart/crt_rpc.c, src/cart/crt_rpc.h, src/cart/crt_swim.c, src/cart/swim/swim.c, src/cart/swim/swim_internal.h, src/tests/ftest/cart/test_swim_emu.c
Reverts daos-stack/daos#7186 due to spurious exclusion issues.
=> DAOS-9100 swim: Revert "DAOS-9033 swim: Avoid busy loop in SWIM progress (#7186)"

src/utils/daos_autotest.c
If domain_nr for pool is 1 or 2, container creation with
rf1 or rf2 will fail, skip this containers to make test happy.
=> DAOS-9104 utils: skip container creations properly

utils/rpms/daos.spec
Including an incorrect use of "%else if ..." that was an overzealous
attempt at per-OS guarding where we just need to handle a single
outlier.
=> DAOS-9008 packaging: Fix rpmlint warnings

src/tests/ftest/erasurecode/rebuild_fio.yaml, src/tests/ftest/util/ec_utils.py
The test is getting Timeout because of rebuild hung DAOS-8870. But test
does not get cleanup and has leftover fuse mount point.
So adding test cleanup procedure to kill the fuse and unmount the partition.
Test-tag-hw-large: pr ec_online_rebuild_fio ec_offline_rebuild_fio
=> DAOS-8907 Test: Force kill fuse in case of test timeout.

src/utils/daos_autotest.c
If domain_nr for pool is 1 or 2, container creation with
rf1 or rf2 will fail, skip this containers to make test happy.
Test-tag-hw-medium: containerautotest
=> DAOS-9104 utils: skip container creations properly (#7466)

src/tests/ftest/nvme/pool_exclude.yaml
Description: Updated pool_exclude.yaml with newly updated supported oclass OC_RP_3G6
Test-tag: nvme_pool_exclude
=> DAOS-9129 test: Fix container create oclass RP_3G5 error (#7453)

Jenkinsfile, src/vos/vos_obj.c
When doing punch propagation, the known key needs to be reset
if no entries are found.  Otherwise, it can cause us to access
a garbage address.
=> DAOS-7878 vos: Reset known key if no entries are found

Jenkinsfile, src/vos/vos_obj.c
When doing punch propagation, the known key needs to be reset
if no entries are found.  Otherwise, it can cause us to access
a garbage address.
Change the ignoreFailedBuilds setting for fault injection testing.
=> DAOS-7878 vos: Reset known key if no entries are found (#7484)

docs/admin/administration.md, docs/admin/pool_operations.md, docs/user/container.md, docs/user/workflow.md
Provide more details on reintegration and document the current
limitation.
Add a more detailed definition of what a container is and
how it can be used.
Fix a few nits where UUID are still used on the cmd line.
doc-only: true
=> DAOS-7174 doc: refine reintegration section (#7380)

mkdocs.yml
Use same color scheme as 2.0 documentation and change layout
to be more aligned with 2.0 (not necessarily required, but
this simplifies the naviguation). Move mkdocs.yml to the
root directory for easier scripting.
Enable the mike plugin for multi-version support
doc-only: true
=> DAOS-7174 doc: uniformize style and enable multi-version

src/object/cli_obj.c
It should refresh reply pool map version in anycase
during key query to make sure pool map refresh will
happen after RPC failure.
=> DAOS-9051 object: refresh reply pool map in anycase

src/tests/ftest/io/io_consistency.yaml
To avoid kinds of network slowness casused test timeout.
=> DAOS-9080 tests: increase IO consistency test timeout

utils/build.config
Fix SPDK bug where incorrect socket-ID is reported in NVMe controller
details when running daos_server storage scan or dmg storage scan -v.
Fix is to apply SPDK patch #10373 in build.config for source builds,
another PR will update SPDK RPM repo to apply the same patch.
=> DAOS-9121 build: fix socketid in spdk scan with vmd

src/client/kv/dc_kv.c, src/include/daos/kv.h, src/utils/daos_autotest.c
A couple of improvements:
1. Enable punch test and fixed assertion because we don't pass correct object handle
to kv_punch()
2. Fixed to return correct error in some cases.
3. limit write by 1/10 available free space so that pool size doesn't depend on hardware
performance.
=> DAOS-9089 utils: re-enable autotest punch tests

src/object/cli_obj.c
Let's use 0 map version to force map refresh in all necessary
case for the moment.
Reset map reply version for key query retry case.
Check if object map version match with dc pool map
version.
=> DAOS-9051 object: force map refresh in all necessary case. (#7431)

src/tests/ftest/control/daos_admin_privileged.py, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/server_utils.py, src/tests/ftest/util/server_utils_base.py
Enable tests to optionally detect if all the daos server engines have
started successfully via dmg system query instead of searching the
command output for engine started messages.
=> DAOS-8936 tests: Support detecting engine start via dmg (#7425)

src/cart/utils/memcheck-cart.supp
Update the memcheck suppression file for a new error we're seeing,
this is in the OFI code and an existing suppression nearly matches
with the exception of one function so change the suppression to
use a wild-card here.
Add names to the two OFI suppressions that aren't named.
=> CART-89 test: Update OFI memcheck suppression.

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_rpc.c
Two main optimizations:
1. Yield CPU during sending DTX RPCs and IO forward RPCs if the
targets list exceeds the DTX_RPC_YIELD_THD (64).
2. Take ds_pool::sp_lock out side of dtx_classify_one() to avoid
frequently lock/unlock against the shared pool.
=> DAOS-9067 dtx: avoid block during DTX commit

src/vos/tests/vts_mvcc.c, src/vos/vos_obj.c
Revert just the enabling of propagation to object level.  General
propagation should be faster if a user punches akeys.
=> DAOS-7878 vos: Partial revert of punch propagation (#7451)

docs/QSG/setup.md, docs/QSG/suse_setup.md, docs/admin/predeployment_check.md, utils/config/daos_agent.yml, utils/config/daos_server.yml, utils/config/examples/daos_server_sockets.yml, utils/config/examples/daos_server_unittests.yml
The daos_server.yml socket_dir and daos_agent.yml runtime_dir settings
for the socket directories should be kept at their defaults, especially
if the daemons are under systemd control. The systemd RuntimeDirectory
controls the location of these socket directories, and systemd will
create/remove them with the right permissions when the services are
started/stopped.
The example YML files and documentation have been updated with a warning
that these must match the systemd RuntimeDirectory (when daemons are under
systemd control), and/or those lines have been removed from the examples.
Doc-only: true
=> DAOS-9115: socket dirs and systemd RuntimeDirectory should match

utils/build.config
Fix SPDK bug where incorrect socket-ID is reported in NVMe controller
details when running daos_server storage scan or dmg storage scan -v.
Fix is to apply SPDK patch #10373 in build.config for source builds,
another PR will update SPDK RPM repo to apply the same patch.
=> DAOS-9121 build: fix socketid in spdk scan with vmd (#7479)

src/pool/srv_pool.c
Temporarily disable pool svc rank shuffle in order to
give us more time to fix tests which need to be aware
of svc rank placement.
=> DAOS-9177 pool: Disable svc rank shuffle

src/cart/crt_context.c, src/cart/crt_rpc.c, src/cart/crt_rpc.h, src/cart/crt_swim.c, src/cart/swim/swim.c
Turned off scheduling incoming SWIM RPCs by DAOS customization.
Changed progress timeout only for very long timeout to avoid
confusing of DAOS scheduler.
=> DAOS-9033 swim: Avoid busy loop in SWIM progress (#7487)

site_scons/prereq_tools/base.py
Add I_MPI_ROOT to list of variables to passthrough if set
=> DAOS-9178 build: Build fails with oneapi MPI

src/tests/ftest/control/daos_object_query.py
Description: Update DAOS object enumeration class with recent changed per discussion with Mohamad and ShiLong.
modified: control/daos_object_query.py
Test-tag: daos_object_query
=> DAOS-9125-test2.0: Cherrypick rel_2.0 update test for the recent DAOS object enumeration class changed

src/dtx/dtx_common.c, src/include/daos_srv/dtx_srv.h, src/object/srv_ec_aggregate.c, src/object/srv_obj.c, src/rebuild/scan.c
master-commit: 5b42f33c0227d3b5aecf54a42ed55737221f6259
Current, the size for dtx_leader_handle is more than 300 bytes, that
is some large for being as static variable on ULT stack, and may be
one of the important factors of ULT stack overflow. In the patch, we
dynamically allocate the DTX handle via dtx_leader_begin(), and free
it via dtx_leader_end(). Similar for dtx_begin() and dtx_end().
=> DAOS-8433 dtx: allocate DTX handle dynamically

docs/user/filesystem.md
=> DAOS-8691 doc: Add documentation for dfuse permissions. (#7361)

src/tests/ftest/mpiio/romio.py, src/tests/ftest/mpiio/romio.yaml
it seems that some VMs are running slower on async collective tests
that can potentially create background threads and use collective
MPI functions.
Test-tag: romio
=> DAOS-9072 test: move romio test to hw small 

src/tests/ftest/mpiio/romio.py, src/tests/ftest/mpiio/romio.yaml
it seems that some VMs are running slower on async collective tests
that can potentially create background threads and use collective
MPI functions.
=> DAOS-9072 test: move romio test to hw small  (#7401)

src/placement/pl_map.c
Coverity identified an issue where a loop in the placement map code will only
execute once.
=> DAOS-9187 placement: Fix dead code in placement map

src/utils/daos_autotest.c
interactive output that displays the progress of each step
does make the job.log quite large and very difficult to view in a web browser.
It turned out too many messages inside one seconds, we could
report progress once per second instead to limit ratio.
Test-tag-hw-medium: containerautotest
Test-tag-hw-small: containerautotest
Test-tag-hw-large: containerautotest
=> DAOS-9089 autotest: limit progress output for writing

src/cart/crt_iv.c, src/engine/server_iv.c, src/include/cart/iv.h, src/rebuild/srv.c
Sleep 1 second for IV retry in iv_op().
Change a few REBUILD log to INFO.
=> DAOS-9040 IV: sleep 1 second for IV retry

src/bio/bio_buffer.c
Set the 'rdma' flag correctly when the request is for rebuild pull,
otherwise, pmem will be used as RDMA fetch target, and that could
cause failure on system doesn't support pmem MR.
=> DAOS-9174 bio: Use DMA buffer for rebuild pull

src/tests/ftest/control/ms_resilience.py
If a server is killed before it is pinged at least once, it
will not be marked as dead, and the test will never progress.
Just pause long enough to ensure that all ranks have been
pinged before proceeding on to the rest of the test.
=> DAOS-9116 test: Pause ms_resilience before killing servers

utils/rpms/10-daos_server.conf
=> DAOS-8935 build: fix rmem values in sysctl conf file

src/control/server/instance_drpc.go, src/control/server/instance_superblock.go
Unguarded access to the Rank field of the superblock was
causing occasional race warnings on server startup.
=> DAOS-9142 control: Fix race in superblock access

src/tests/ftest/scripts/setup_nodes.sh
Set memlock ulimit value to unlimited to avoid cannot allocate memory
errors with verbs.
=> DAOS-5061 tests: Set memlock ulimit values to unlimited (#7328)

src/object/srv_obj_migrate.c, src/vos/evtree.c, src/vos/tests/evt_ctl.c
Let's wait all migrate ULT to finish before stopping
migrate, otherwise if the previous migrate failed,
one object might be discarded by previous migration
and retry migration concurrently.
=> DAOS-9195 migrate: wait all migrate to finish before migrate stop.

src/tests/ftest/server/metadata.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/job_manager_utils.py, src/tests/ftest/util/thread_manager.py
Use a test-specific temporary directory for temporary files generated
during the test and remove the files after test completion to free up
space for the next test.
=> DAOS-8655 tests: Fix orterun tmpdir 'No such file or directory' (#6869)

src/control/lib/control/rpc.go, src/control/server/mgmt_system.go
Let the client decide how long the request may take; don't set
an arbitrary server-side timeout value.
=> DAOS-9147 control: Use client-side timeout for fanout requests

src/tests/ftest/datamover/posix_subsets.py, src/utils/daos_hdlr.c
duns_resolve_path does not resolve a path as residing in DAOS if the
basename of the dfuse target directory does not exist, and instead copies
to a regular POSIX directory. If one level up from the target dfuse
directory exists in DAOS, then the directory should be created and data
should be copied into DAOS, not POSIX.
Test-tag: pr fs_copy cont_clone
=> DAOS-9084 daos: fix resolving dfuse destination type

debian/changelog, debian/control, utils/rpms/daos.spec
- Apply OFI patch for DAOS-9173
PR-repos: libfabric@PR-48
=> DAOS-9173 update: Apply OFI patch

debian/changelog, debian/control, utils/build.config, utils/rpms/daos.spec
- Remove mercury workaround for DAOS-9173
- Apply OFI patch for DAOS-9173 instead
NOTE: build.config patching is not included for now to avoid
build conflicts
=> DAOS-9173 ofi: Update workarounds

utils/docker/vcluster/.env, utils/docker/vcluster/README.md, utils/docker/vcluster/daos-admin/el8/.dockerignore, utils/docker/vcluster/daos-admin/el8/Dockerfile, utils/docker/vcluster/daos-admin/el8/daos_control.yml.in, utils/docker/vcluster/daos-base/el8/.dockerignore, utils/docker/vcluster/daos-base/el8/Dockerfile, utils/docker/vcluster/daos-client/el8/.dockerignore, utils/docker/vcluster/daos-client/el8/Dockerfile, utils/docker/vcluster/daos-client/el8/daos_agent.yml.in, utils/docker/vcluster/daos-cm.sh, utils/docker/vcluster/daos-server/el8/.dockerignore, utils/docker/vcluster/daos-server/el8/Dockerfile, utils/docker/vcluster/daos-server/el8/daos_server.yml.in, utils/docker/vcluster/docker-compose.yml
Backport of the pull request https://github.com/daos-stack/daos/pull/7556
Provide recipe to build and run DAOS docker containers.
This PR add some docker recipes for building images allowing to run small docker cluster using DAOS as backend storage.
More details could be found in the file utils/docker/vcluster/README.md.
***WARNING:*** all the bitbucker URI are not yet valid as they are targeting the branch master of the main DAOS repo.  They should be changed from https://github.com/daos-stack/daos.git#master:utils/docker/vcluster/daos-base/el8 to https://github.com/daos-stack/daos.git#DAOS-9088:utils/docker/vcluster/daos-base/el8
This could be done automatically with the following command:
`find "$DAOS_HOME/utils/docker/vcluster" -type f -exec grep -q -E -e …
=> DAOS-9088 docker: add recipes to run in containers

utils/build.config
Update build.config to include daos-9173 ofi patch.
=> DAOS-9173 build: Update build.config

src/pool/srv_target.c
move metrics_start ahead inside pool_alloc_ref() to
avoid iv_ns and other related stuff to be destoryed
once it failed, especially if there are concurrent
pool_alloc_ref() during reintegration.
=> DAOS-9248 pool: move metrics start ahead

src/pool/srv_target.c
move metrics_start ahead inside pool_alloc_ref() to
avoid iv_ns and other related stuff to be destoryed
once it failed, especially if there are concurrent
pool_alloc_ref() during reintegration, otherwise it may
cause segfault
=> DAOS-9248 pool: move metrics start ahead (#7621)

src/tests/ftest/datamover/posix_subsets.py, src/utils/daos_hdlr.c
duns_resolve_path does not resolve a path as residing
in DAOS if the basename of the dfuse target directory
does not exist, and instead copies to a regular POSIX
directory. If one level up from the target dfuse directory
exists in DAOS, then the directory should be created and
data should be copied into DAOS, not POSIX.
=> DAOS-9084 utils: fix resolving dfuse destination type (#7503)

ci/functional/required_packages.sh, ci/rpm/test_daos_node.sh, debian/changelog, debian/control, utils/rpms/daos.spec
Testing packages.
This allows the daos-*-tests-openmpi packages to be not included in the
distribution, due to MPI stack conflicts on target installations.
daos-*-tests-openmpi will have to be instaled explicitly where it's
desired or needed.
=> DAOS-9109 packaging: Drop dependency on openmpi

Jenkinsfile, ci/functional/required_packages.sh
So that the correct ones are installed.
I'm actually surprised that DNF needs this much help.  I would have
thought it would find the correct versioned packages itself.
=> DAOS-9109 ci: Add test version to openmpi test pkgs

src/control/lib/hardware/hwloc/bindings.go, src/control/lib/hardware/hwloc/provider.go, src/control/lib/hardware/hwloc/provider_test.go, src/control/lib/hardware/hwloc/testdata/boro-84.xml, src/control/lib/hardware/hwloc/testdata/gcp_topology.xml, src/control/lib/hardware/hwloc/testdata/multiport_hfi_topology.xml, src/control/lib/hardware/hwloc/testdata/no-numa-no-devices.xml, src/control/lib/hardware/hwloc/testdata/no-numa-nodes.xml, src/control/lib/hardware/hwloc/testdata/wolf-133.xml, src/control/lib/hardware/topology.go, src/control/lib/hardware/topology_test.go
- Create an interface for getting a hardware topology, including
NUMA node, PCI address, and devices.
- Create bindings for hwloc satisfying that interface.
=> DAOS-8905 control: Add lib for hwloc

src/container/srv_container.c, src/container/srv_target.c, src/include/daos_srv/container.h, src/include/daos_srv/daos_engine.h, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/pool/srv_target.c, src/rebuild/srv.c, src/vos/evtree.c, src/vos/tests/vts_io.c, src/vos/vos_aggregate.c, src/vos/vos_obj.h, src/vos/vos_obj_cache.c
* Assert if vos_obj_hold is done for write while vos_discard
is in progress
* Add some debug
* Fix issue where ec aggregation could race with discard
Co-authored-by: Di Wang <di.wang@intel.com>
=> DAOS-9195 vos: Prevent multiple range discard on same object

src/tests/ftest/container/snapshot_aggregation.py
Test-tag: snapshot_aggregation
Remove a "snapshot" avocado tag, since all other snapshot test use
"snap". This will hopefully prevent spreading the use of both tags.
=> DAOS-623 test: remove snapshot tag in favor of snap

src/tests/ftest/erasurecode/rebuild_fio.yaml
IOR covers the rebuild test for EC and Fio may not be ideal
application to validate the aggregation in this case.
Doc-only: true
=> DAOS-9214 Test: Removing the Fio random data for rebuild tests.

src/tests/ftest/pool/query_attribute.py
Description: Roundup pool query size in script after discussed with Mohamad and Jeff, reference DAOS-9030.
Test-tag: pool_query_attr
=> DAOS-9209-test: pool/query_attribute.py test failed on pool query Expected != actual

src/tests/ftest/pool/query_attribute.py
Description: Cherrypick for rel2.0 Roundup pool query size in script after discussed with Mohamad and Jeff.
Test-tag: pool_query_attr
=> DAOS-9209-test_2.0: Cherrypick for rel2.0 pool/query_attribute.py test failed on pool query Expected != actual

src/tests/ftest/server/metadata.py
Supplemental fix for previous server/metadata.py
test_metadata_server_restart test case where unique temporary base
directories for each orterun command where based on the previous unique
temporary directory that no longer existed when the next ior command was
issued.
Test-tag: metadata_ior offline_extend_oclass
=> DAOS-8655 tests: Fix mpi tmpdir_base assignment in threads.

src/client/java/pom.xml
Backport log4j patch.
Bumps log4j-core from 2.13.3 to 2.15.0.
---
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> DAOS-8929 java: bump log4j-core from 2.13.3 to 2.15.0 in /src/client/java (#7623)

src/common/tests_dmg_helpers.c
On CentOS 8.4 which has json package 0.13.1-0.4.On latest changes json_object_object_get_ex() fails if the value is empty. And in device-health pools is key with no value which is getting Assertion on latest JSON.
So removed the for loop and instead use the value of the device and read health info.
Test-tag: test_daos_nvme_recovery_4
=> DAOS-9189 Test: Fix the common code JSON to not to use the loop.

src/object/srv_obj.c
For conditional punch, if the target to be punched does not exist,
we will log related failure messages as DEBUG instead of "ERROR".
Similarly for conditional update case.
=> DAOS-9194 object: log existence related message as DEBUG

src/client/java/pom.xml
Bumps log4j-core from 2.13.3 to 2.15.0.
---
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> DAOS-8929 java: bump log4j-core from 2.13.3 to 2.15.0 in /src/client/java (#7623) (#7654)

src/client/java/pom.xml
Bumps log4j-core from 2.15.0 to 2.16.0.
---
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> DAOS-8929 java: Bump log4j-core from 2.15.0 to 2.16.0 in /src/client/java (#7671)

docs/QSG/tour.md, docs/admin/pool_operations.md, docs/admin/troubleshooting.md, docs/testing/autotest.md, docs/user/container.md, docs/user/filesystem.md, docs/user/mpi-io.md, docs/user/spark.md
make documentation of the dmg and daos commands consistent
to use positional arguments for pools and containers
include container labels in the examples
=> DAOS-9185 doc: fix pool/cont usage - positional args and labels

src/control/common/test_utils.go, src/control/server/engine/config.go, src/control/server/engine/config_test.go, src/control/server/engine/exec_test.go, src/control/server/engine/tags.go, src/control/server/engine/tags_test.go, src/control/server/server_utils.go, src/control/server/server_utils_test.go, utils/config/daos_server.yml
As CaRT is already doing this behind the scenes, the
server config should explicitly enable it to avoid
confusing client behavior.
=> DAOS-9154 control: Enable SRX by default

docs/QSG/tour.md, docs/admin/pool_operations.md, docs/admin/troubleshooting.md, docs/testing/autotest.md, docs/user/container.md, docs/user/filesystem.md, docs/user/mpi-io.md, docs/user/spark.md
make documentation of the dmg and daos commands consistent
to use positional arguments for pools and containers
include container labels in the examples
=> DAOS-9185 doc: fix pool/cont usage - positional args and labels (#7666)

Jenkinsfile, debian/changelog, utils/rpms/daos.spec
For release candidate testing, allow a build to enable fault injection,
which is usually disabled for RC runs.
=> DAOS-9327 ci: Param to enable FI on RC

docs/testing/cartselftest.md
add --use-daos-agent-env to self_test example
Doc-only: true
=> DAOS-9223 doc: fix CaRT self_test example

ci/gha_helper.py
Update the gha_helper script so that it looks longer back than a
week when calculating the hash key to use for builds.  When there
had been no update for a week then the check was failing
and builds were failing.
=> DAOS-7821 build: Update GHA to look further back in time for changes.

src/tests/suite/daos_degrade_ec.c, src/tests/suite/daos_obj.c, src/tests/suite/daos_obj_ec.c
Some core tests require fault injection to pass.  Skip the tests if
fault injection is not enabled.
=> DAOS-9328 test: Skip tests that require fault injection when disabled

src/tests/perf_common.c, src/tests/vos_perf.c
Enable timing a complete aggregation/discard pass in vos_perf
The intention here is to create a benchmark for testing DSA
but also can be useful for measuring general aggregation
performance as we try to improve it.
=> DAOS-9328 vos: Add aggregation/discard to vos_perf

src/bio/bio_buffer.c, src/bio/bio_bulk.c
To make bio_iod_bulk() supporting zero length IOVs, modified
iterate_biov() to move the IOV length check into callbacks.
=> DAOS-9234 bio: cope with zero length IOV

src/placement/pl_map.c
Coverity identified an issue where a loop in the placement map code will only
execute once.
=> DAOS-9187 placement: Fix dead code in placement map (#7561)

src/client/java/pom.xml
Bumps log4j-core from 2.16.0 to 2.17.0.
---
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Master PR: #7721
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump log4j-core from 2.16.0 to 2.17.0 in /src/client/java

third_party_programs.txt
The following license acknowledgements are added to third_party_programs.txt
hashicorp/go-hclog
Prometheus Monitoring
protobuf-c
protobuf_java
Doc-only: true
=> DAOS-9337 Documentation: Update Third Party Licensing

site_scons/env_modules.py, utils/docker/Dockerfile.centos.7, utils/docker/Dockerfile.centos.8, utils/docker/Dockerfile.leap.15, utils/docker/Dockerfile.ubuntu.20.04
Dockerfile RUN use /bin/sh to run command. As indicated in the bash manual: "A non-interactive shell invoked with the name sh does not attempt to read any other startup files."
More information could be found at https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html
Building MPI-related test binaries of DAOS (e.g. daos_perf, daos_test, etc.) needs some environment variables releated to modules tool.  These environmant variables are  defined in /etc/profile.d/modules.sh.
Do not hesitate to add reviewers if I forgot someone: I used git blame to create the list of reviewers.
=> DAOS-9311 build: build MPI-related test binaries with docker

src/tests/suite/daos_test_common.c
"runable" was defined as a static bool. Once a test case is determined as "skipped",
runable is set false. The following tests cases will be skipped unexpectedly.
=> DAOS-4679 fixed static runable variable in test_runable()

docs/QSG/setup_centos.md
Fix a few minor issues in the guide.
1. No need to create socker dirs with RPMs
2. Use explicit naming of nodes (admin, client, server)
3. Fix some typos
=> DAOS-9321 doc: Clean up the quickstart guide a bit

src/tests/suite/daos_test_common.c
Commit 2bb877846c removed "static" from runable, that is good. A side
effect is may cause stack_chk_fail() as the bool type size less than
MPI_INT.
=> DAOS-9370 test: fix a bug in test_runable()

src/gurt/fault_inject.c
In release builds, fault injection is disabled by design.  The user can
check if it's enabled.  No need to put a warning into the log.
=> DAOS-9328 fi: Downgrade fault injection warning to info

docs/release/upgrading_to_v2_0.md
add a note to upgrading_to_v2_0.md to explain the hwloc dependency
issue that may prevent updating CentOS from 8.3 to 8.4/8.5
Doc-only: true
=> DAOS-9348 doc: Cannot upgrade CentOS 8.3 to 8.4 with DAOS installed

src/client/dfuse/dfuse.h, src/client/dfuse/ops/create.c, src/client/dfuse/ops/mknod.c, utils/node_local_test.py
On create/mkdir then check the uid us the container, and if
they're different then apply the user bits to the group and
possibly other bits.
This is to avoid an issue where accessing other users containers
where any newly created files are owned by the container owner
and it's possible to create files without having perms to access
them.  This change will copy the user perms to the group perms,
and if there's no group overlap to the other perms as well, to
ensure the creating process is able to access the files.
=> DAOS-9064 dfuse:  Ensure new files have correct permissions. (#7417)

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c, src/include/daos_srv/vos.h, src/vos/vos_dtx.c
If the DTX touches a lot of targets, and if we use current main XS to
classify the DTX entries and send out related RPCs, then it may cause
the main SX to be held for relative long time as to have no chance to
handle other request, such as the DTX RPC from other targets. That is
the potential risk of dead lock (or RPC timeout) among the targets if
most of them are busy with DTX commit/abort with lots of targets.
This patch defines new threshold "DTX_RPC_HELPER_THD": if the targets
to be handled for the DTX RPC exceeds (or may exceed) such threshold,
we will create a helper ULT to handle that dedicatedly.
=> DAOS-9216 dtx: use helper ULT to send DTX RPC

src/common/debug.c, src/include/daos/common.h
First of all, daos_key2str returns a NULL terminated string
so there is no need to limit the characters we print.
Secondly, the %*s in daos_key2str should be %.*s.  The former
is valid printf but simply is a format specifier whereas the
latter actually limits the characters printed.
=> DAOS-9350 log: Fix issues with DF_KEY and daos_key2str

src/tests/perf_internal.h, src/tests/vos_perf.c
API for creating the oid was incorrectly handling flags so
key query check was failing
=> DAOS-9374 vos: Fix vos_perf integer key handling

src/common/tests_dmg_helpers.c
On CentOS 8.4 which has json package 0.13.1-0.4.On latest changes
json_object_object_get_ex() fails if the value is empty. And in device-health
pools is key with no value which is getting Assertion on latest JSON.
So removed the for loop and instead use the value of device and read
health info.
=> DAOS-9189 Test: Fix the common code JSON to not to use the loop. (#7586)

src/container/srv_target.c
Some ds_cont_child will only created by ds_cont_child_lookup(),
never be started at all, so let's check if the container child
is started before stop the container child.
=> DAOS-9314 container: only stop started container.

src/gurt/fault_inject.c
In release builds, fault injection is disabled by design.  The user can
check if it's enabled.  No need to put a warning into the log.
=> DAOS-9328 fi: Downgrade fault injection warning to info (#7729)

src/tests/vos_perf.c
Two conflicting patches caused master branch build to fail
vos_aggregate API changed and vos_perf started calling the
old API and both patches landed.
=> DAOS-623 build: Fix build

src/control/lib/spdk/nvme.go
@retPtr was freed before using, see following confusing
output:
[2021-12-22 00:44:12.002315] init.c: 607:spdk_env_init: *ERROR*: Failed to initialize DPDK
wolf-135.wolf.hpdd.intel.com ERROR 2021/12/22 00:44:12 /usr/bin/daos_admin spdk env init: -13
ERROR: spdk: code = 803 description = "SPDK binding failed, rc: 0, "
=> DAOS-9354 control: fix use after free

docs/QSG/docker.md, utils/docker/vcluster/daos-base/el8/Dockerfile
Fix invalid DAOS rpm repository and mask some useless systemd services.
=> DAOS-9088 docker: fix recipes to run in containers

src/control/server/server_utils.go
A small amount of huge pages is needed to do storage
scan for SPDK device probing.
Test-tag: control_start nvme_scan
=> DAOS-9354 control: use min hugepages for scan

src/include/daos/object.h, src/object/cli_ec.c
In EC data recovery, the parity recx list replied from different
parity shards is used to check if the parity extents are matched.
When VOS aggregation race with the data recovery, one parity shard
may return fragmented recxs and another return merged recxs, that
case is not an error.
=> DAOS-9357 EC: refine obj_ec_parity_check() for data recovery

docs/QSG/docker.md, utils/docker/vcluster/daos-cm.sh
This commit contains the following updates:
- Add paragraph on HugePages configuration.
- Fix note section improperly formated.
- Fix daos-cm.sh helper bash script: wait for startup of the daos_server
service.
Doc-only: true
=> DAOS-9088 docker: fix documentation and helper script

site_scons/prereq_tools/base.py
Add I_MPI_ROOT to list of variables to passthrough if set
=> DAOS-9178 build: Build fails with oneapi MPI (#7548)

src/bio/bio_buffer.c, src/include/daos_srv/bio.h, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/rdb/rdb_util.c, src/tests/vos_perf.c, src/vos/tests/vts_gc.c, src/vos/tests/vts_io.c, src/vos/vos_aggregate.c, src/vos/vos_io.c
Adding an "error code from prior data transfer operation" parameter
to bio_iod_post() & bio_copy_post() interface, so that they could
internally skip data write back once prior data transfer failed.
Fix EC aggregation RPC handler, where bio_iod_post() and the
vos_update_end() were missed on error cleanup.
=> DAOS-9384 bio: improve bio_iod_post() interface

src/engine/drpc_handler.c, src/engine/srv.c, src/engine/tests/drpc_handler_tests.c, src/engine/ult.c
1. if negative module id is passed in, drpc_hdlr_get_handler() will try
to access a random memory which is unexpected.
2. sched_ult2xs() might return negative, check return value early to
avoid assertion in dss_get_xstream()
3. -c option is deprecated, use -t in the comments instead.
=> DAOS-9141 engine: fix potential invalid memory access

src/tests/ftest/server/daos_server_config.py, src/tests/ftest/server/daos_server_config.yaml
After commit: DAOS-9146 engine: some fixes for daos server
1. Hugepages will be used if configured even without NVME configured,
And we will check huegpages with system avail free pages, it will return
fail which is expected.
2. configuring nr_hugepages with negative will set it to 4096, so
fix this test run in the hardware environment.
Test-tag: control,server_start
=> DAOS-9354 test: fix daos_server_config failure

src/object/srv_ec_aggregate.c, src/tests/suite/daos_degrade_ec.c
To avoid both parity shards treat the other is leader when they with
different pm version.
For example, 4P2G1 EC obj, with shards 0~5,on server of shard 4 with
pool map ver 10 all are alive and it check shard 5 should be EC agg
leader so shard 4 will do nothing; at that time, on server of shard 5
with pool map ver 11, it checks itself failed or in-rebuilding, then it
think shard 4 should be the leader so shard 5 will do nothing.
Both servers will not prevent the EC agg epoch move ahead but actually
did not do EC agg work.
=> DAOS-9181 EC: only select last parity shard as EC agg leader

src/container/srv_target.c
Some ds_cont_child will only created by ds_cont_child_lookup(),
never be started at all, so let's check if the container child
is started before stop the container child.
=> DAOS-9314 container: only stop started container. (#7700)

docs/admin/administration.md, docs/admin/deployment.md
Add command usage text to show up-to-date syntax. Note that daos_server
storage subcommands are not configuration file aware.
=> DAOS-9240 docs: update administration section command syntax (#7722)

src/client/dfuse/ops/setattr.c, utils/node_local_test.py
A lot of clients seem to do this, often with other metadata updates
in the same call, so if this happens allow the change, but do not
attempt to apply it.
Remove ctime setattr check, this often happens with any type of
caching enabled.
=> DAOS-8981 dfuse: Allow setattr of uid/gid in dfuse if data is unchanged. (#7204)

src/mgmt/srv_target.c
The cancel signal can arrive after thread normal complete.
So, this assertion can happens in the corner case but anyway
this consequence nothing.
=> DAOS-9169 mgmt: remove overchecks assertion

src/control/cmd/daos_server/storage.go, src/control/cmd/daos_server/storage_test.go, src/control/common/pci_utils.go, src/control/server/ctl_storage.go, src/control/server/storage/bdev/backend.go, src/control/server/storage/bdev/backend_vmd.go, src/control/server/storage/provider.go
Allow local storage scan to detect VMD backing devices and display details.
=> DAOS-9094 control: daos_server storage scan to show VMD backing devices (#7440)

src/utils/daos_autotest.c
Change status to PASS/FAIL/SKIP and color for SKIP to yellow.
Also fix alignment issue with progress and add % sign.
=> DAOS-9089 autotest: fix alignment and change status

src/control/cmd/daos/property.go, src/control/cmd/daos/property_ctest.go, src/control/cmd/daos/property_test.go
Add support of human readable format for all container size properties.
The unit tests are inspired from the methodology used by cgo to test itself:
https://go.dev/misc/cgo/test/cgo_test.go
https://go.dev/misc/cgo/test/test.go
=> DAOS-9245 control: humanize size properties

docs/admin/predeployment_check.md
Document how to apply 4kb block size to SSDs to align with how DAOS applies I/O.
This should avoid any alignment issues and help optimize use of SSDs in DAOS.
=> DAOS-9140 doc: ssd format block size instructions in admin guide

ci/unit/test_nlt_node.sh, src/client/array/dc_array.c, src/common/debug.c, src/include/daos/common.h, src/tests/ftest/rebuild/pool_destroy_race.yaml, src/vos/vos_io.c, src/vos/vos_tree.c
* Print INT key for DP_KEY, and limit the DP_KEY
by DF_KEY_STR_SIZE.
* Fix and add a few IO DAOS log.
* Set svnc to be 3 for pool_destory_race.yaml, since
the test will kill 1 rank, which might be PS leader.
* Minor optimizations to key2str
* Increase log file size limit to account for more debug
* Pull in fix for this commit from (#7756)
Co-authored-by: Di Wang <di.wang@intel.com>
=> DAOS-8872 debug: Truncate large keys and print integer keys (#7529)

src/dtx/dtx_common.c, src/dtx/dtx_rpc.c, src/include/daos_srv/dtx_srv.h, src/object/srv_obj.c, src/object/srv_obj_remote.c, src/tests/ftest/erasurecode/online_rebuild_mdtest.py
There is race between the IO handler ULT (main IO ULT) and related
IO forward ULT for using the DTX handle. It is possible that the IO
forward ULT is still using the DTX handle but related IO handler ULT
has already freed the DTX handle via dtx_leader_end(). For avoiding
such case, we add additional one compartment when create the future
dtx_leader_handle::dlh_future, it will be set by the IO forward ULT
after using the DTX handle.
The patch also adds some check to avoid repeated or leak task/RPC
completion callback. The former case may cause the one waiting on
related ABT future to be wakenup earlier unexpectedly; the latter
case will cause related RPC leak.
=> DAOS-9193 dtx: keep DTX handle until IO forward ULT exited

src/control/server/storage/scm/provider.go, src/control/server/storage/scm/provider_test.go
If --reformat is specified, proceed to format even if fs on device is
unrecognised or cannot be otherwise determined. this should avoid
situations where a PMEM device cannot be formatted because of unusual
filesystem signatures.
=> DAOS-9165 control: force format if unknown fs sig (#7604)

src/tests/ftest/erasurecode/aggregation.py, src/tests/ftest/erasurecode/restart.py, src/tests/ftest/erasurecode/restart.yaml, src/tests/ftest/nvme/enospace.py, src/tests/ftest/nvme/fault.py, src/tests/ftest/util/ec_utils.py, src/tests/ftest/util/nvme_utils.py
- Adding test which will write EC date with different object types,
Wait for aggregation to trigger and restart all the servers.
Read and verify the data after start.
- Adding test which will write the EC data with different object types,
Restart all the servers, Verify aggregation is getting trigger after start.
Read and verify the data after aggregation.
- Disabled the aggregation, Write EC data with different object types,
Enable the time mode aggregation and wait for ~20 seconds.
Restart all the servers when aggregation is also happening.
read and verify the data after aggregation.
Test-tag: ec nvme
=> DAOS-7337 test: Adding EC test cases verification with all DAOS server restart. (#6891)

src/tests/ftest/erasurecode/restart.py
Aggregation is happening faster incase of server restart the size checking logic in loop
will not work
Updating the logic to compare the memory size before and after server restart instead.
Test-tag: pr ec_server_restart
=> DAOS-9522 Test: Checking the memory size to confirm that aggregation happen after server restart.

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c, src/include/daos_srv/vos.h, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_obj.c
RPC resent related logic belong to up layer, such as object layer
or DTX module instead of inside VOS. So RPC resent related logic,
including some VOS APIs, such as vos_dtx_check(), are adjusted.
=> DAOS-9375 dtx: remove RPC resent related logic from VOS

src/dtx/dtx_common.c, src/include/daos_srv/dtx_srv.h, src/include/daos_srv/vos.h, src/object/srv_obj.c, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c, src/vos/vos_internal.h
During current IO handler ULT waits for bulk data transfer or other
non-leaders (for leader case), the DTX status may be changes by other
(such as DTX resync or refresh) by race. If the DTX has been prepared
or committed under such case, then just handle it as done instead of
retrying related RPC.
=> DAOS-9380 dtx: do not retry RPC if DTX is committed by race

src/tests/ftest/datamover/negative.py, src/tests/ftest/datamover/negative_space.py, src/tests/ftest/datamover/negative_space.yaml
Move to negative space test to hw small since VM performance
is not reliable.
Test-tag: dm_negative_space_dcp
=> DAOS-9231 test: fix dm_negative_space_dcp

src/object/cli_obj.c, src/object/srv_obj_migrate.c
If the enumeration needs to fetch from multiple shards,
let's update the anchor only if all shards enumeration
succeeds.
Some minor cleanup in the client stack.
=> DAOS-9208 object: fix mulitple shards enumeration

src/common/tests_dmg_helpers.c, src/tests/ftest/daos_test/nvme_recovery.py
dmg json output has changed name for state --> dev_state in PR#7613.
Removing the skip for NVMe Recovery 4 test.
Test-tag: pr daos_core_test_nvme
=> DAOS-9525 Test: Fix JSON output based on name change in PR#7613

src/include/daos_srv/daos_engine.h, src/object/obj_enum.c, src/object/srv_obj.c, src/tests/suite/daos_checksum.c, src/vos/vos_obj.c
Merge continous recxs to shrink the enumeration size. Since
EC rebuild needs to know the epoch for each cell, so the
merging can not cross the cell boundary.
=> DAOS-9208 rebuild: merge recxs

docs/admin/pool_operations.md
Added the following notice about usable space in
"Creating a Pool" section:
Note that it is difficult to determine the usable space by the user and
currently we cannot provide the precise value. The usable space depends not only
on pool size, but also on number of targets, target size, object class,
redundancy factor, etc.
=> DAOS-8682 doc: Added usable space notice

src/cart/crt_context.c, src/cart/crt_init.c, src/cart/crt_internal_types.h, src/include/cart/api.h, utils/node_local_test.py
The timeout callback mechanism in cart isn't used any longer.
Let's remove it.
Also remove a leftover from eviction callback.
=> CART-89 cart: remove timeout callbacks

src/include/daos/object.h, src/object/cli_ec.c, src/object/srv_obj.c, src/tests/ftest/daos_test/suite.yaml, src/tests/suite/daos_epoch_io.c, src/tests/suite/daos_obj_ec.c
For EC data recovery, merge parity list at server side.
And two small refines on test code.
=> DAOS-9236 EC: merge parity list at server side

.github/workflows/landing-builds.yml, utils/docker/Dockerfile.centos.8, utils/scripts/install-centos8.sh
Avoid a bug in CentOS 8 versions of scons by using pip to
install a later version of it.  This avoids occasional build
failures with a "Internal Error: no cycle found for node" error.
=> CORCI-1106 build: Use pip to install scons in CentOS 8.

utils/node_local_test.py
Disable this test as it's failing periodically.  Reading the
test it's always been racy as it depends on the caching
behaviour of the kernel however we've only started seeing
failures due to the recent sockets change.  Only run this
test with caching enabled.
Rework the test decorators in NLT to allow them to take
parameters.
=> DAOS-623 test: Disable test_il_with_caching test in NLT.

src/container/srv_target.c, src/include/daos/common.h, src/include/daos_srv/container.h, src/include/daos_srv/vos.h, src/object/cli_obj.c, src/object/srv_ec_aggregate.c, src/rdb/rdb_util.c, src/rebuild/srv.c, src/tests/vos_perf.c, src/vea/vea_internal.h, src/vos/tests/vts_aggregate.c, src/vos/tests/vts_pm.c, src/vos/vos_aggregate.c, src/vos/vos_common.c, src/vos/vos_internal.h
To minimize the performance impact, VOS aggregation needs to make
trade-off on VOS tree condensing and data merging/relocating (which
consumes CPU & storage bandwidth, yet likely to generate more
fragmentations).
This patch introduced 'force_merge' flag for vos_aggregate(), when
'force_merge' isn't provided, VOS aggregation will selectively merge
records on same media to minimize the performance impact.
vos_aggregate() caller is responsible for using proper flag based on
the IO workload or aggregation EPR.
This patch also suppressed NOSPACE error messages in aggregation.
=> DAOS-9101 vos: selectively merge records on aggregation

src/tests/ftest/pool/attribute.yaml
Increasing the pool/attribute.py test timeout by 30 seconds to
compensate for running on VMs.
Test-tag: large_poolattribute sync_poolattribute async_poolattribute
=> DAOS-9510 tests: Increasing the pool/attribute.py test timeout

src/tests/ftest/nvme/io_verification.yaml
Description: running timeout increase, test passed on weekly_rel2.0 #6
Test-tag: nvme_server_restart
=> DAOS-9238-test: nvme/io_verification nvme_server_restart 2 tests failed due to timeout

src/tests/ftest/cart/no_pmix_group_test.c, src/tests/ftest/cart/no_pmix_group_version.c
- Adjust cart group test timeouts and number of retries for when
running under the valgrind.
=> DAOS-9102 tests: Adjust cart timeouts and retries

src/tests/ftest/util/daos_io_conf.py
Updating the unaligned file creation to avoid end of file error.
Test-tag: unaligned_io
=> Revert "DAOS-9307 test: fix a mem usage bug in daos_epoch_io test (#7687)" (#7833)

src/control/lib/spdk/faults.go, src/control/lib/spdk/nvme.go, src/control/lib/spdk/spdk.go, src/control/lib/spdk/src/nvme_control.c, src/control/lib/spdk/src/nvme_control_common.c
Control plane SPDK binding calls should report meaningful strings from
spdk_strerror in case of failure rather than the raw return codes.
=> DAOS-9642 control: improve error reporting from spdk bindings

src/control/server/instance_drpc.go
=> COVERITY-CID-345299: fix nil dereference in instance_drpc.go

src/control/cmd/daos_server/start_test.go, src/control/cmd/dmg/auto_test.go, src/control/lib/control/auto.go, src/control/lib/control/auto_test.go, src/control/server/config/server.go, src/control/server/config/server_test.go, src/control/server/ctl_ranks_rpc_test.go, src/control/server/ctl_storage_rpc_test.go, src/control/server/ctl_storage_test.go, src/control/server/engine/config_test.go, src/control/server/engine/exec_test.go, src/control/server/harness_test.go, src/control/server/instance_storage_test.go, src/control/server/instance_superblock_test.go, src/control/server/instance_test.go, src/control/server/mgmt_pool_test.go, src/control/server/storage/bdev/backend_class_test.go, src/control/server/storage/bdev/backend_json_test.go, src/control/server/storage/config.go, src/control/server/storage/provider_test.go, src/control/server/test_utils.go
Since storage tiering has been implemented, storage class identifiers
are not bdev or scm specific. Replace WithScmClass() and WithBdevClass()
with WithStorageClass().
=> DAOS-9629 control: Replace storage class helper functions

src/control/server/instance_drpc.go
As EngineInstance.addBdevStats() may sometimes be called with a nil NvmeController,
change the error constructor to use the address in the SmdDevice parameter.
=> COVERITY-CID-345299: fix nil dereference in instance_drpc.go (#7897)

src/vos/vos_query.c
Coverity identified an issue in vos_query where a function return code was not
checked. This two issue is resolved by this commit.
=> DAOS-9645 Coverity: Fixes for Coverity Issues 314735

src/object/cli_ec.c, src/tests/suite/daos_obj.c
Need not encode for punch case.
=> DAOS-9668 EC: fix segfault when punch EC full-stripe

src/object/cli_ec.c, src/tests/suite/daos_obj.c
Need not encode for punch case.
=> DAOS-9668 EC: fix segfault when punch EC sull-stripe (#7919)

debian/changelog, debian/control, utils/build.config, utils/rpms/daos.spec
Upgrade from libfabric 1.14.0-rc3 to 1.14.0 GA.
Grab libfabric fix to store ibv_wr_opcode and reuse it
it in error cases in the verbs provider.
Move build.cfg to the official tag, the additional libfabric
patch will be added in a subsequent PR.
=> DAOS-9376 ofi: update to 1.14.0 and apply workaround (#7904)

src/vos/vos_dtx.c
Otherwise, subsequent vos_dtx_check() will handle related DTX
entry as initialized but not prepared. That may cause related
DTX cannot be resynced or fail related DTX refresh for others.
=> DAOS-9663 vos: set prepared for reindexed active DTX entry

src/control/common/cmdutil/topology.go, src/control/common/test_utils.go, src/control/lib/control/auto_test.go, src/control/lib/hardware/fabric_test.go, src/control/lib/hardware/hwloc/bindings.go, src/control/lib/hardware/hwloc/provider.go, src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/hwprov/defaults_test.go, src/control/lib/hardware/pci.go, src/control/lib/hardware/pci_test.go, src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go, src/control/lib/hardware/topology.go, src/control/lib/hardware/topology_test.go
- Add a TopologyProvider to detect network devices via sysfs, to
find devices not in the hwloc topology.
- Add the TopologyFactory, a TopologyProvider that merges the
results of other TopologyProviders.
- Fix error in NetDevClassBuilder.
- Add weighted inputs to NewTopologyFactory, to make explicit
the expected order in which TopologyProviders should be run.
- Make improvements to debug logging.
=> DAOS-8905 control: Add sysfs net device detection

src/tests/ftest/cart/no_pmix_group_test.c, src/tests/ftest/cart/no_pmix_group_version.c
- Adjust timeout time in test when running under valgrind.
Skip-func-test-vm-valgrind: false
Test-tag: group_test
=> DAOS-9102 test: Adjust shutdown time

src/tests/ftest/aggregation/shutdown_restart.yaml
Reducing the log level from DEBUG to INFO
for aggregation/shutdown_restart.py
Test-tag: ioaggregation pr
=> DAOS-9750 test: Reduce log level from test yaml for shutdown_restart.py

src/tests/ftest/control/dmg_telemetry_nvme.yaml
The work for DAOS-8905 has likely increased server
startup times just enough to increase the likelihood
of hitting this test's timeout.
Test-tag: test_nvme_telemetry_metrics
=> DAOS-9757 test: Increase NVMe telemetry test timeout

src/include/daos_obj.h, src/object/cli_obj.c, src/tests/simple_obj.c, src/tests/suite/daos_kv.c, src/utils/daos_autotest.c
Current detecting ofeats check won't work if DAOS_OF_XXX is passing
directly as ofeat flag, this patch try to fix by declaring DAOS_OF_XXX
as macro rather than enum.
Also add sanity check for daos_otype_t is valid or not before generating
oid, added deprecated warning for old flags.
=> DAOS-9753 object: fix daos_obj_generate_oid() back compatible feat flags

src/tests/ftest/util/apricot/apricot/test.py
Resolving an issue with the test_metadata_server_restart where it fails
to detect all of the daos_server engines have restarted by ensuring the
expected number of engines is properly set.
Test-tag: offline_extend_oclass metadata_ior
=> DAOS-9748 tests: Fixing test_metadata_server_restart

src/cart/crt_init.c, src/cart/crt_internal_types.h, src/include/cart/types.h, src/tests/ftest/cart/dual_iface_server.c
- New fields to control provider, interface, domain, port instead
of using envariables.
=> DAOS-9674 init: Add new crt_init_opt fields

src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_dir.yaml, src/tests/ftest/datamover/large_file.py, src/tests/ftest/datamover/large_file.yaml, src/tests/ftest/util/data_mover_test_base.py
- Update large datamover tests to use tmpfs on a single client
instead of shared NFS, since NFS is too slow.
- Reduce 30G file to 20G (tmpfs observed to have ~25G)
- Reduce test timeout
- General test cleanup
Test-tag: dm_large_dir dm_large_file
=> DAOS-9667 test: update large dm tests to use tmpfs

src/vos/tests/vts_pm.c, src/vos/vos_ts.h
Using d_hash_murmur64() for OID hash might be bad, testing
shows loops could be increased from 102 to 18201 if hash was
calculated as oid hi xor lo bits.
=> DAOS-9095 vos: improve oid hash to reduce false collisions

src/include/daos/common.h, src/object/cli_ec.c, src/object/cli_obj.c, src/object/obj_internal.h, src/tests/suite/daos_obj.c, src/tests/suite/daos_rebuild_ec.c
User may provide fetch buffer iov with zero or less iov_len, so need to check
iov_buf_len rather than iov_len in daos_iov_left().
And user possibly provide update buffer sgl/iov with iov_len < iov_buf_len,
to avoid bulk_create's confuse, in that case dup a new sgl and set iov_buf_len
as iov_len.
=> DAOS-9654 obj: a few refines of iov_buf_len/iov_len

src/dtx/dtx_rpc.c, src/object/srv_obj.c
Under some bad case, if the IO handler ULT fall into dead loop
for refresh some DTX, then print some warning message in log.
=> DAOS-9561 dtx: warning message if dead loop for DTX refresh

docs/admin/pool_operations.md
Fix some minor typos and punctutation, as well as improve grammar.
Doc-only: true
=> DAOS-623 doc: fix minor typo, punctuation, grammar

src/control/lib/hardware/fabric.go, src/control/lib/hardware/fabric_test.go, src/control/lib/hardware/hwprov/defaults_test.go, src/control/server/ctl_network_rpc.go
- Add optional CacheTopology method to cache an externally-
acquired Topology in the FabricScanner.
- Use CacheTopology in the daos_server network scan to avoid
crawling the hardware topology more than once.
=> DAOS-9757 control: Optimize daos_server network scan

src/control/server/faults.go, src/control/server/mgmt_pool.go, src/control/server/mgmt_pool_test.go
The error and resolution strings should be simpler and
more focused on giving the admin specific and actionable
information (e.g. the minimum pool size).
=> DAOS-9255 control: Improve pool creation size faults

.github/workflows/landing-builds.yml, utils/docker/Dockerfile.centos.8
=> DAOS-7821 gha: Remove CentOS 8 from GHA builds.

src/tests/ftest/util/apricot/apricot/test.py
Resolving an issue with the test_metadata_server_restart where it fails
to detect all of the daos_server engines have restarted by ensuring the
expected number of engines is properly set.
Test-tag: offline_extend_oclass metadata_ior
=> DAOS-9748 tests: Fixing test_metadata_server_restart (#7979)

src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go
- Limit sysfs traversal to discovery of devices we actually care
about collecting.
- Detect virtual network interfaces correctly.
=> DAOS-9757 control: Limit sysfs traversal

.github/CODEOWNERS
It seems that team names need to include the organization prefix.
=> DAOS-623 ci: Fix team names in CODEOWNERS

src/include/daos_srv/evtree.h, src/vos/evtree.c, src/vos/ilog.c, src/vos/ilog.h, src/vos/tests/vts_ilog.c, src/vos/vos_dtx.c, src/vos/vos_ilog.c, src/vos/vos_internal.h, src/vos/vos_tree.c
When update ilog for update or punch, we fetch related ilog entries
firstly, that may hits many uncommitted DTX entries. That is normal,
will not cause server side DTX refresh or client side RPC retry. So
we do not need to prepare the information for potential DTX refresh.
The patch also fixes related log message to avoid confusing.
=> DAOS-9036 vos: not retry if hit prepared DTX for list ilog  entries

docs/admin/predeployment_check.md, site_scons/components/__init__.py
Rename example application binaries created in source build to be
consistent with SPDK RPM.
=> DAOS-9770 build: sync SPDK example names with RPM

src/tests/ftest/launch.py, src/tests/ftest/util/server_utils.py, src/tests/ftest/util/server_utils_base.py
Updating the behavior of launch.py --nvme auto argument.  The 'auto'
keyword will now detect and use any homogenous VMD controller or NVMe
devices detected on the specified hosts.  The 'auto_vmd' and 'auto_nvme'
keywords will limit the auto-detection to either VMD controller or NVMe
devices, respectively.
Test-tag-hw-medium: pr daily_regression full_regression
=> DAOS-9562 tests: Enabling VMD detection through --nvme auto (#7868)

Jenkinsfile
Since it runs on VMs, it can take a little longer sometimes
=> DAOS-9377 test: Add 5 minutes to the memcheck stage timeout

docs/admin/performance_tuning.md
Doc-only: true
Author: Craig Durfey <craig.durfey@intel.com>
=> daos-9746 documentation: typo in perf tuning

src/control/server/storage/bdev/backend_test.go, src/control/server/storage/bdev/runner.go
This regression was introduced in commit ccf0027af99ce803c3642787426f00f6d1924d19.
daos_server storage prepare can call SPDK setup with NRHUGE set to 0
which results in the NVMe controllers being inaccessible and reporting
permission denied.
The fix applied is to always set hugepages explicitly to a non-zero
value when calling storage prepare for NVMe, otherwise devices will
not be accessible. Use default value recommended by SPDK and if no
hugepages are required then storage prepare for NVMe should not be
called (only call if NVMe devices are to be scanned or used by engine).
=> DAOS-9774 control: do not call spdk setup with zero hugepages

docs/QSG/setup_centos.md
Properly separate lines in setup_centos.md to resolve package location
Doc-only: true
=> DAOS-9661 doc: separate lines in setup_centos.md (#7911)

src/tests/ftest/erasurecode/mdtest_smoke.py, src/tests/ftest/erasurecode/offline_rebuild_aggregation.py
DAOS-9763 test: Duplicate functional test name - test_mdtest_large
Description: Update fixing of the test duplicate name on DAOS-9706 by Samir.
- Fixing the mdtest smoke test name
- Removing the skip for ec aggregation.
Test-tag: ec_mdtest_smoke ec_offline_rebuild_agg_default ec_offline_agg_during_rebuild
Test-repeat: 5
=> DAOS-9763 test: Duplicate functional test name - test_mdtest_large

src/tests/ftest/ior/intercept_basic.py
Changing the frequency of intercept_basic.py test from
weekly to daily as there is not a single interception test
running as part of daily_regression.
=> DAOS-5458 test: Moving intercept_basic from weekly to daily

src/control/cmd/daos_admin/handler_test.go, src/control/common/collection_utils.go, src/control/common/collection_utils_test.go, src/control/lib/control/auto.go, src/control/lib/control/auto_test.go, src/control/lib/hardware/pci.go, src/control/server/config/server.go, src/control/server/config/server_test.go, src/control/server/ctl_storage.go, src/control/server/engine/config_test.go, src/control/server/engine/tags.go, src/control/server/server_utils.go, src/control/server/storage/bdev.go, src/control/server/storage/bdev/backend.go, src/control/server/storage/bdev/backend_class.go, src/control/server/storage/bdev/backend_class_test.go, src/control/server/storage/bdev/backend_json.go, src/control/server/storage/bdev/backend_json_test.go, src/control/server/storage/bdev/backend_test.go, src/control/server/storage/bdev/provider.go, src/control/server/storage/bdev/provider_test.go, src/control/server/storage/config.go, src/control/server/storage/config_test.go, src/control/server/storage/provider.go
Instead of passing around strings which need to be parsed
and validated in different parts of the system, convert
the configuration to use structured device lists. This
will allow errors to be caught earlier and simplify
other parts of the codebase.
=> DAOS-9781 control: Parse bdev_list entries early

src/control/lib/control/pool.go
Per the advice in the ticket, add this error to the set of
retryable errors for Control API clients (e.g. dmg).
=> DAOS-9098 control: Retry -DER_EXCLUDED on pool operations

src/tests/ftest/control/dmg_telemetry_basic.py, src/tests/ftest/util/dfuse_utils.py, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/job_manager_utils.py, src/tests/ftest/util/server_utils.py
skip-test-rpms: true
Test-tag: pr daily_regression dfuse,-manual test_container_telemetry
- dfuse_utils.py
- simplify nodeset operations to reduce nested statements
- server_utils.py
- use set comprehension to silence warning. It's also simpler
- adjust for 80->100 line length
- dmg_utils.py
- disable=too-many-arguments for a valid use case
- dmg_telemetry_basic.py
- Iterate with .items()
- adjust for 80->100 line length
=> DAOS-623 test: pylint fixes

src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_dir.yaml, src/tests/ftest/datamover/large_file.py, src/tests/ftest/datamover/large_file.yaml, src/tests/ftest/datamover/negative.py, src/tests/ftest/datamover/posix_symlinks.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/data_mover_utils.py, src/tests/ftest/util/ior_test_base.py
Modify tests to use a shared POSIX directory for large
directory and large file tests.
Test-tag: datamover
=> DAOS-8469 test: use shared posix directory in large tests (#6910)

src/cart/swim/swim.c
Reset the stored timestamp when SWIM is disabled to avoid false
error report about stopping progress.
=> DAOS-9814 swim: Avoid false error report about stopping progress

src/client/dfuse/ops/read.c, src/tests/ftest/dfuse/fio_small.yaml
Do not use readahead when the kernel is also using write-back cache.
Add fio with random read to check for this.
=> DAOS-9738 dfuse: Disable readahead when write-through cache is used. (#7986)

src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_dir.yaml, src/tests/ftest/datamover/large_file.py, src/tests/ftest/datamover/large_file.yaml, src/tests/ftest/util/data_mover_test_base.py
Test-tag: dm_large_dir dm_large_file
- Update large datamover tests to use tmpfs on a single client
instead of shared NFS, since NFS is too slow.
- Reduce 30G file to 20G (tmpfs observed to have ~25G)
- Reduce test timeout
- General test cleanup
=> DAOS-9667 test: update large dm tests to use tmpfs (#7917)

src/tests/ftest/datamover/negative.py, src/tests/ftest/datamover/negative_space.py, src/tests/ftest/datamover/negative_space.yaml
Test-repeat: 5
Test-tag: dm_negative_space_dcp
Move to negative space test to hw small since VM performance
is not reliable.
=> DAOS-9231 test: fix dm_negative_space_dcp (#7602)

src/control/server/storage/bdev/backend.go, src/control/server/storage/config.go
Missed this test case in local testing. Relax the input
checking to work with the new implementation.
=> DAOS-9781 control: Fix NVMe scan with empty Allow list

src/object/cli_obj.c
For retry object sync case, the epoch array length should
be equal to the object redundancy group count. Otherwise,
there is DRAM corruption or accessing released DRAM.
=> DAOS-9657 object: check obj sync argument

src/dtx/dtx_common.c, src/dtx/dtx_rpc.c, src/include/daos_srv/dtx_srv.h, src/include/daos_srv/vos.h, src/object/srv_obj.c, src/vos/evtree.c, src/vos/ilog.c, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c, src/vos/vos_ilog.c, src/vos/vos_internal.h
This patch combines the following two master commit:
master-commit: 746f1936c70c6e13ec4bc7a5423507b9bab46a4a
master-commit: 457df4db26438b6f73142652b2413f1990681b81
When current IO handler ULT waits for bulk data transfer or other
non-leaders (for leader case), the DTX status may be changes by other
(such as DTX resync or refresh) by race. If the DTX has been prepared
or committed under such case, then just handle it as done instead of
retrying related RPC.
During current DTX leader waiting for non-leaders' reply,
someone (for resent rquest) may abort the DTX, that will
cause current DTX leader to do cleanup after the waiting,
such cleanup needs to avoid removing the new created DTX
entry (that belong to resent request) from the DTX table.
Do not abort current DTX if it has been always …
=> DAOS-9658 dtx: avoid removing DTX entry belong to other

src/include/daos/common.h, src/object/cli_obj.c, src/object/obj_internal.h, src/tests/suite/daos_obj.c
User may provide fetch buffer iov with zero iov_len, so need to check
iov_buf_len rather than iov_len in daos_iov_left().
And user possibly provide update buffer sgl/iov with iov_len < iov_buf_len,
to avoid bulk_create's confuse, in that case dup a new sgl and set iov_buf_len
as iov_len.
=> DAOS-9654 obj: a few refines of iov_buf_len/iov_len (#7910)

src/cart/crt_hg.c, src/cart/crt_rpc.c, src/container/srv_target.c
Add more daos log for OID allocation.
Change RPC get/reply log mask to DB_ALL.
=> DAOS-9179 container: add more daos log (#7674)

src/control/server/server_utils.go, src/control/server/server_utils_test.go, src/tests/ftest/util/server_utils_params.py
To address a regression in commit
1c9fbacf95281de9c61dd7db37b01aa1580dbc0d that causes SPDK initialisation
failures during storage scan when no NVMe is configured, simplify the
logic so that unless hugepages are explicitly disabled in config (by
setting nr_hugepages: -1), always allocate a minimum number on NUMA-0 so
that NVMe storage scan can complete (and SPDK initialiise).
Also leave nr_hugepages unset in functional tests to let the
control-plane to do the right thing.
=> DOS-9886 control: allocate minimum number of hugepages for scan

src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_space.c
Due to duplicated code, some csum fixes in vos_io.c were not applied
to vos_space.c, this patch fixed that by making few helper functions
shared by vos_io.c and vos_space.c
=> DAOS-9843 vos: few csum helper functions

src/object/cli_obj.c, src/object/obj_rpc.h
We should not retry a new replica when an existence check correctly
returns -DER_NONEXIST.  For instance, a user does a condtional fetch
and the key doesn't exist.  This is not indicative of a replica failure
=> DAOS-9885 object: Avoid retrying a new replica for existence checks

src/tests/ftest/datamover/negative.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/data_mover_utils.py
Test-tag: datamover,-hw
Remove --daos-prefix from datamover tests as it's no longer necessary.
=> DAOS-9874 test: remove --daos-prefix from datamover

src/client/api/pool.c, src/client/pydaos/raw/daos_api.py, src/control/cmd/daos/pool.go, src/include/daos_pool.h
daos_pool_connect is a weak symbol pointing to daos_pool_connect2().
Signed-off-by: Lei Huang <wiliam_huang@hotmail.com>
=> DAOS-9872 API: Expose daos_pool_connect2() as a weak symbol.

src/tests/ftest/pool/bad_connect.py, src/tests/ftest/pool/bad_connect.yaml
- Removed connectsetnames variant from pool/bad_connect.py because these variants are not used.
- Removed permission variants (connectmode) because they're tested in permission.py
- Refactored.
Test-tag: bad_connect
=> DAOS-9844 test: Remove unnecessary variants from pool/bad_connect.py

src/tests/ftest/aggregation/shutdown_restart.yaml
Avoid cart_logtest.py error by reducing the server log size generated by
the aggregation/shutdown_restart.py test.
Test-tag: ioaggregation
=> DAOS-8942 test: Reduce logging of aggregation/shutdown_restart

src/include/daos_srv/vea.h, src/vea/tests/vea_ut.c, src/vea/vea_alloc.c, src/vea/vea_api.c, src/vea/vea_free.c, src/vea/vea_init.c, src/vea/vea_internal.h
To reduce fragmentations and make VEA more scalable when the space is
very fragmented, the original reserving from small extents is changed
from first-fit to best-fit, consequently, the way of tracking small
extents is changed from a LRU array with few fixed size classes into
a size classed LRU tree. (at most 16k size classes in the tree).
=> DAOS-9630 vea: best-fit policy for small reserve

Jenkinsfile, utils/rpms/packaging/Dockerfile.mockbuild
As the update replaces epel-8-* configs with <distro>+epel-8-* which
we are not ready for yet.
=> CORCI-1176 build: Hold back mock-core-configs

src/vos/vos_aggregate.c
The issue described at DAOS-6227(PR-4072) has been resolved by a
different way.
Let's choose the highest epoch during aggregation, which can help
incremental aggregation and also avoid missing the data during
migration if we choose to reintegrate from non-zero epoch.
=> DAOS-9856 vos: aggregate to highest epoch

.github/CODEOWNERS
set up doc-watchers in CODEOWNERS
=> DAOS-9355 doc: set up doc-watchers in CODEOWNERS

src/tests/ftest/rebuild/no_cap.yaml
1. reduce pool size so that rebuild could be restarted
more quickly.
2. reduce cart timeout to make IV update return timeout
quickly to ease test.
Test-tag-hw-medium: no_cap
Test-repeat-hw-medium: 50
=> DAOS-9626 test: fix no_cap test timeout

src/client/dfs/dfs_internal.c
=> DAOS-623 dfs: add accidently removed function to free sb layout info

src/vos/vos_io.c
Fix a recx csum in vos_io.c which is missed during prior csum fix.
=> DAOS-9843 csum: missed csum fix

Jenkinsfile, utils/rpms/packaging/Dockerfile.mockbuild
*As the update replaces epel-8-* configs with <distro>+epel-8-* which
we are not ready for yet.
* Use Docker CE runner
=> CORCI-1176 build: Hold back mock-core-configs (#8216)

debian/changelog, debian/control, src/rdb/rdb.c, src/rdb/rdb_internal.h, src/rdb/rdb_raft.c, utils/rpms/daos.spec
Update raft to pick up fixes related to memberships. A few rdb changes
are required to integrate with the updated raft:
- Since election-less leaderships have been removed in the updated
raft, the workaround for the "term" assertion in
rdb_raft_queue_event is removed.
- Since raft_election_start has been changed from void to int in the
updated raft, a return-value check is added to rdb_raft_campaign
for the raft_election_start call.
- [Core] Since raft already maintains the current membership as an
array of raft_node_t objects in volatile memory, the duplicate
rdb.d_replicas is removed. This removal accounts for a major part
of the changes in this patch. (I didn't want to do this change
initially due to patch size considerations, but changed my mind once
I saw the simplification it …
=> DAOS-2054 rdb: Update raft (#7823)

src/tests/ftest/control/ms_resilience.py
If a server is killed before it is pinged at least once, it
will not be marked as dead, and the test will never progress.
Just pause long enough to ensure that all ranks have been
pinged before proceeding on to the rest of the test.
=> DAOS-9116 test: Pause ms_resilience before killing servers (#7516)

src/control/cmd/dmg/pretty/storage.go, src/control/cmd/dmg/pretty/storage_nvme.go, src/control/lib/control/mocks.go, src/control/lib/spdk/nvme.go, src/control/lib/spdk/src/nvme_control.c, src/control/server/ctl_storage_rpc.go, src/control/server/ctl_storage_rpc_test.go, src/control/server/instance_storage_rpc.go, src/control/server/storage/bdev.go, src/control/server/storage/bdev/backend.go
On platforms with multiple NVMe namespaces per controller, multiple
device format results are being registered for a single controller
causing incorrect number of NVMe devices to be reported in command
output. The cause is that when creating a result for each namespace
wipe operation, only the first result would contain the controller
address meaning that results for both an empty address and the
controllers address are returned. These results are subsequently
interpreted as two device responses.
Changes in this PR:
* Fix by adding controller address to each namespace wipe result.
* Also fix device count in situation where NVMe format is skipped.
=> DAOS-9849 control: Correct NVMe count in DMG storage format summary

src/object/cli_obj.c, src/tests/suite/daos_obj.c
* log error in obj_iod_sgl_valid()
* more error information in obj_key_valid()
Signed-off-by: Wang Shilong <wangshilong1991@gmail.com>
=> DAOS-9769 obj: reject integer keys that are less than 8 bytes (#8093)

src/client/api/container.c, src/include/daos_cont.h, src/include/daos_srv/vea.h, src/tests/ftest/nvme/io_verification.py, src/tests/ftest/osa/dmg_negative_test.py, src/tests/ftest/pool/permission.py, src/tests/ftest/scripts/main.sh, src/tests/ftest/slurm_setup.py, src/tests/ftest/soak/harassers.yaml, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/stress_2h.yaml, src/tests/ftest/soak/stress_48h.yaml, src/tests/ftest/soak/test_base.py, src/tests/ftest/soak/utils.py, src/tests/ftest/util/job_manager_utils.py, src/tests/ftest/util/slurm_utils.py, src/tests/jobtest.c, src/tests/suite/daos_container.c, src/tests/suite/daos_epoch.c, src/vea/tests/vea_ut.c, src/vea/vea_alloc.c, src/vea/vea_api.c, src/vea/vea_free.c, src/vea/vea_init.c
Update the slurm setup script to install slurm on Centos8 and Suse153
Update soak scripts to correctly import modules after DAOS-8595
Change daos metric collection to before container destroy
Add change to hdf5-vol to remove hdf5 container in batch script
Update soak yaml files to remove/update server env
Remove the large reserved file from avocado artifacts
Replace srun with mpich in sbatch scripts
=> DAOS-7607 test: Update slurm for soak testing (#6820)

src/container/srv_target.c, src/dtx/dtx_common.c, src/dtx/dtx_resync.c, src/include/daos_srv/container.h, src/include/daos_srv/dtx_srv.h, src/include/daos_srv/vos.h, src/object/srv_obj.c, src/vos/vos_dtx.c
Some IO requests may be still inflight when close the container
because of malicious or non-coordinated applications or evicted
by administrator by force. Those inflight IO requests may still
reference related active DTX entries that should be kept during
reset DTX tables when close the container.
On the other hand, the patch also adds some check for the cases
of container closed before IO requests completed.
=> DAOS-9829 dtx: keep active DTX entry when close container

utils/rpms/daos.spec
Ensure that we are building RPMs with the latest release
available in our internal package repositories.
=> DAOS-9908 build: Build with go >= 1.17

src/dtx/dtx_internal.h, src/dtx/dtx_rpc.c, src/dtx/dtx_srv.c, src/engine/srv.c, src/include/daos_srv/daos_engine.h
If there is not enough helper XS, then starting more ULT on the helper
XS cannot give much help to DTX RPC handling.
The patch also allows admin to adjust the threshold for using helper ULT
to handle DTX RPC when start DAOS engine via the server side environment
"DTX_RPC_HELPER_THD", "0" means disable helper ULT to handle DTX RPC.
=> DAOS-9760 dtx: use helper ULT for DTX RPC if has enough helper XS

src/control/common/mocks.go, src/control/fault/code/codes.go, src/control/lib/control/auto.go, src/control/lib/control/auto_test.go, src/control/lib/control/faults.go, src/control/lib/hardware/pci.go, src/control/lib/spdk/nvme.go, src/control/lib/spdk/spdk.go, src/control/server/config/server.go, src/control/server/server.go, src/control/server/storage/bdev/backend.go
Update control API to enable dmg config generate to work with
VMD-enabled storage servers. The cmd output YAML should contain
bdev_list of discovered (NUMA locality aligned) VMD endpoint addresses
and have verified that the number of VMD endpoints and total number of
backing NVMe SSDs behind the endpoints are both equal for each engine.
=> DAOS-9105 control: Generate VMD-enabled server configs with DMG

src/rdb/rdb_raft.c, src/rsvc/srv.c
Ignore already failure for ds_rsvc_dist_start(), because
restart svc rank might already start rsvc service.
When re-adding an old RDB replica, we may observe that the first
InstallSnapshot to this replica fails with -DER_MISC. This is due to a
bug in rdb_raft_cb_recv_installsnapshot_resp, which doesn't check if the
whole snapshot is complete in addition to if the chunk is successfully
stored.
=> DAOS-9317 rsvc: ingore ALREADY failure (#7685)

src/object/obj_tx.c
If all data shards are healthy, only parity shards are unavailable, then EC
related logic can guarantee the data consistency.
=> DAOS-9570 object: allow degrade IO on EC obj even if lost all parity shards

src/control/server/engine/exec.go
Instead of sharing the cmd field of the runner between goroutines,
delegate access to a single goroutine and communicate with it.
=> DAOS-9145 control: Fix racy access to engine's exec.Cmd

src/engine/srv.c
=> DAOS-9639 engine: use large stack for nvme pull ULT

src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_space.c
Due to duplicated code, some csum fixes in vos_io.c were not applied
to vos_space.c, this patch fixed that by making few helper functions
shared by vos_io.c and vos_space.c
=> DAOS-9843 vos: few csum helper functions (#8132)

src/common/pool_map.c, src/include/daos/placement.h, src/object/cli_obj.c, src/object/srv_ec_aggregate.c, src/object/srv_obj_migrate.c, src/placement/jump_map.c, src/placement/pl_map.c, src/placement/pl_map.h, src/placement/ring_map.c, src/placement/tests/jump_map_place_obj.c, src/placement/tests/pl_bench.c, src/placement/tests/place_obj_common.c, src/pool/srv_pool.c, src/rebuild/scan.c
Since extending shards are only needed for update, so do not need
add extending shards for readonly open, for example migration enum
or fetch.
Do not need check DOWN status for extending shards. Then extra shards
might change their location due to co-location, so it also needs to
update pl map test.
=> DAOS-9793 placement: Do not add extending shards for readonly open

src/gurt/dlog.c
The merging of stderr in log (DAOS-4522/PR-2450), and the log
switch based on size (DAOS-4233/PR-3405) features have been
developed separately and their full integration has been missed
causing merged stderr to not follow the log switch and thus to
continue filling <log>.old file, and thus have stderr msgs to
become desynchronized from log msgs.
Change-Id: I371119967db2e0b2211e2b898d77e2f18846c531
=> DAOS-9718 log: merged stderr should follow log switch

Doxyfile, mkdocs.yml
fix path specs in Doxyfile and mkdocs.yml
Doc-only: true
=> DAOS-9881 doc: fix doxygen path issues

src/tests/suite/daos_obj.c
with RF2, the oclass selection changed for EC oclasses, but test was
not updated.
=> DAOS-9977 test: fix auto class selection test

src/tests/ftest/aggregation/shutdown_restart.yaml
Avoid cart_logtest.py error by reducing the server log size generated by
the aggregation/shutdown_restart.py test.
Test-tag: ioaggregation
=> DAOS-8942 test: Reduce logging of aggregation/shutdown_restart (#8158)

src/tests/ftest/launch.py
Exclude the VMD NVMe RAID Controller hardware revision from the lspci -D
output that causes the clush output to be different from multiple nodes
when the pci addresses are common to all hosts resulting in an error.
Test-tag-hw-medium: pr daily_regression full_regression
=> DAOS-9562 test: Support multiple rev VMD NVMe RAID controller (#8209)

.github/workflows/doxygen.yml
add missing paths: line into doxygen.yml
=> DAOS-9880 doc: fix doyxgen.yml syntax

.github/CODEOWNERS
set up doc-watchers in CODEOWNERS
(also set up build-and-release-watchers and
client-api-watchers for consistency with 2.2)
=> DAOS-9355 doc: set up doc-watchers in CODEOWNERS (#8176)

src/tests/ftest/launch.py, src/tests/ftest/util/command_utils.py
If a failure occurs during server startup the expected server states
will not be defined.  This will cause a bug when the server states are
detected as part of the test cleanup leaving the servers running when
they should be stopped.  This code change resolves this situation.
Test-tag-hw-medium: daos_core_test
=> DAOS-9974 test: Fix server state detection.

src/common/btree.c, src/include/daos/btree.h, src/include/daos_srv/daos_engine.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_enum.c, src/object/obj_internal.h, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/tests/suite/daos_checksum.c, src/tests/suite/daos_rebuild_ec.c, src/vos/vos_obj.c, src/vos/vos_tls.h, src/vos/vos_tree.c
The patch fix the enumeration from multiple data shards,
for example degrade enumeration, or parity rotation,
1. Each shard will prepare KDS/SGL/RECX buffer invidually,
and attached to the anchor.
2. After each shard get the enumeration buffer, it
needs to sort these dkey/recxs from all shards altogether
by its order inside the VOS, so to avoid duplicate/missing
keys for enumeration.
3. Then these merged/sorted keys/recxs are dumped to
the user kds/sgl/recx, and the leftover will be left in
the merged list, which will be retrieved in the following
enumeration.
=> DAOS-9635 object: multiple shards enumeration fix

utils/rpms/daos.spec
Ensure that we are building RPMs with the latest release
available in our internal package repositories.
=> DAOS-9908 build: Build with go >= 1.17 (#8196)

src/control/server/config/server.go, src/control/server/server_utils.go, src/control/server/server_utils_test.go, src/tests/ftest/util/server_utils.py, utils/nlt_server.yaml
Set nr_hugepages to -1 in NLT tests and avoid NVMe scan in setup if
hugepages are disabled.
Remove unnecessary NVMe storage prepare in ftest setup.
Fail service start-up if initial scan errors (8335) to workaround VMD
cluster failure on degraded test.
Test-tag: pr control
=> DAOS-10014 control: Disable hugepages when running NLT based tests

src/tests/ftest/rebuild/container_create_race.py, src/tests/ftest/rebuild/container_create_race.yaml
Description: Per request, cherrypick the script fix to rel_2.0.
Test-tag: rebuild_cont_create
=> DAOS-9356 test: Cherrypick rebuild/container_create_race.py:RbldContainerCreatetest_rebuild_container_create - test timeout while running ior

utils/githooks/pre-commit
Older versions of git do not handle the wildcards well.  From
copious experimentation, I discovered that the wildcard entries
must start with '*' and that all such entries need to be before
non-wildcard entries.  Otherwise, the diff command in the hook
will match every file in the repo whether modified or not.
=> DAOS-623 tools: Fix the pre-commit hook for older versions of git

.github/CODEOWNERS
=> DAOS-623 review: add ftest-watchers to CODEOWNERS

src/client/dfuse/test/test_ioil.c
Coverity identified a double close on a fd in the do_misc_tests test. This fixes the issue by removing the double close and subsequent reporting of the close return value for the double close.
=> DAOS-9990 dfuse: Remove double close from test

src/common/compression.c, src/placement/ring_map.c, src/vea/vea_free.c
Coverity identified some dead code and leaked resources. This patch fixes
resource leaks in the compression and ring_map code and removes an unchecked
return code assignment.
=> DAOS-9990: Fix various coverity issues

src/engine/sched.c, src/engine/srv.c, src/engine/srv_internal.h
Before network poll started, for instance, when the cart progress
ULT is blocked on open barrier (waiting for join PG), scheduler
shouldn't rely on the blocking crt_progress(timeout) call to relax
CPU, instead, it should just call usleep().
=> DAOS-9896 sched: check if network poll started (#8197)

docs/admin/pool_operations.md, src/control/cmd/dmg/pool.go, src/placement/jump_map.c
for dmg pool create:
* clarify tier-ratio and server versus engine
* clarify pool service replication versus storage replication
for dmg pool get-prop/set-prop:
* clarify valid ranges and defaults for pool properties
=> DAOS-9355 doc: clarify dmg pool create and pool properties

debian/changelog, utils/build.config, utils/rpms/daos.spec
Bulk transfer will now have a timeout of 90 seconds.
This addresses an issue with request ULTs being stuck when the client
is down.
=> DAOS-9561 mercury: Update mercury to include bulk timeout patch (#8278)

utils/config/daos_server.yml
fix the example calculation for nr_hugepages in daos_server.yml
=> DAOS-9355 doc: fix nr_hugepages calculation error

utils/config/daos_server.yml
fix the example calculation for nr_hugepages in daos_server.yml
=> DAOS-9355 doc: add nr_hugepages calculation example (#8297)

src/cart/utils/memcheck-cart.supp
Suppress all memcheck failures observed on EL 8 testing.
Add generic runtime.* suppressions, and remove less specific ones.
Skip-build-centos7-rpm: true
Skip-build-el8-rpm: true
Skip-build-centos8-rpm: true
Skip-unit-test-memcheck: true
Skip-func-test-el8: true
Skip-test-rpms: true
=> DAOS-9132 test: Update memcheck suppressions.

src/object/cli_obj.c, src/object/obj_ec.h, src/tests/suite/daos_obj_ec.c
All related EC stripes should be added to the recover list.
KDS are missing for degraded EC enumeration.
=> DAOS-10044 object: Fix recovery list for EC recovery

src/include/daos_pool.h, src/include/daos_task.h
In most instances, use "/**" rather than "/*" to address doxygen
reports of undocumented structures or members.
=> DAOS-10030 doc: fix some undocumented API structures, members

src/engine/sched.c, src/include/daos_srv/daos_engine.h, src/pool/srv_pool.c, src/rdb/rdb_module.c
Scheduler needs to differentiate RDB heartbeat request and ignore
them when trying to enter relaxing mode, otherwise, the system
xstream on heartbeat receiver side will never enter relaxing mode.
Use sched_cond_wait() instead of ABT_cond_wait() for events handler
ULT, otherwise, scheduler won't enter relaxing mode.
=> DAOS-9940 sched: differentiating RDB heartbeat request (#8257)

src/control/cmd/dmg/pretty/storage.go, src/control/cmd/dmg/pretty/storage_nvme_test.go, src/control/lib/control/server_meta_test.go, src/control/lib/control/storage.go, src/control/server/ctl_smd_rpc.go, src/control/server/ctl_smd_rpc_test.go, src/control/server/ctl_storage_rpc_test.go, src/control/server/storage/bdev.go, src/control/server/storage/bdev_test.go, src/include/daos_srv/control.h
Address two incompatibility issues seen when running DAOS 2.1 dmg
against and DAOS 2.0 daos_server.
Fix nil pointer dereference on dmg storage scan by changing
HugePageInfo reference to concrete field type (DAOS-9943)
Fix invalid NVMe device state error on dmg storage query list-devices
by removing error check and instead adding an UNKNOWN state for
invalid strings e.g. empty which covers the zero value for the smd
info state field.
=> DAOS-9782 control: Resolve some interop issues in DMG (#8242)

src/tests/ftest/osa/dmg_negative_test.yaml
Test-tag: osa_dmg_negative_test
=> DAOS-9970 test: Increase test timeout for dmg_negative_test

src/client/java/daos-java/pom.xml, src/client/java/distribution/pom.xml, src/client/java/hadoop-daos/pom.xml, src/client/java/pom.xml
Hadoop release 3.3.2 brings in various security and bug fixes so make use of
it. Also bump the package version of the DAOS library and plugin to match the
release version.
=> DAOS-10068 java: Bump Hadoop to 3.3.2

src/common/checksum.c, src/include/daos_srv/srv_csum.h, src/object/SConscript, src/object/srv_csum.c, src/object/srv_io_map.c, src/object/srv_obj.c, src/object/tests/srv_checksum_tests.c, src/vos/tests/SConscript, src/vos/tests/vos_tests.c, src/vos/tests/vts_aggregate.c, src/vos/tests/vts_common.h, src/vos/tests/vts_io.c, src/vos/vos_aggregate.c
Added the ability to run VOS tests with checksums. The test, acting
as the client, is responsible for calculating the checksums on an
update and verifying the checksums on a fetch. While running the
VOS aggregation tests with checksums a few issues were discovered
and fixed.
- Previously, while inserting segments, the phy_ent's csum was
updated to the truncated ent_int, however, it pointed to the
ent_in's csum buffer instead of copying the checksum into its own
buffer. Updated it to memcpy now. The phy_ent's csum buffer should
always be big enough.
- In some cases, while adding checksums from raw extents for the
requested extents, the holes weren't managed correctly and
which could cause the incorrect checksum to be added for a
chunk. This would result in a false positive checksum error. …
=> DAOS-9804 csum: Checksum in VOS Tests and Aggregation Fix

src/client/dfs/dfs.c, src/client/dfs/dfs_internal.h, src/include/daos_fs.h
Conflicts:
src/client/dfs/dfs.c
src/client/dfs/dfs_internal.h
=> DAOS-10009 dfs: fix move and exchange API to have input names const (#8323)

src/tests/ftest/util/server_utils.py
In order for --nvme=auto:Optane to work with VMD enabled, the NVMe
devices should be rebound back to the kernel driver in cleanup.
=> DAOS-9972 test: reset nvme bindings after tests

src/vos/tests/vts_aggregate.c, src/vos/vos_aggregate.c, src/vos/vos_ilog.c, src/vos/vos_ilog.h, src/vos/vos_internal.h, src/vos/vos_obj.c, src/vos/vos_obj_index.c
Where possible, offload the punch aggregation of object and
key subtrees to garbage collection.   If an object or key is
punched in the specified range and not visible outside of
that range, we can avoid scanning it for aggregation and just
put it in the container garbage collection heap.
Skipped the vos_perf changes as the branches have diverged
=> DAOS-9756 vos: Offload object/key punch aggregation to gc (#8236)

src/dtx/dtx_common.c
The DTX cleanup ULT cannot know whether current DTX leader is still alive
or not. There is race case that the DTX leader is blocked because of some
non-leader(s) no-respond (down/crashed) then the DTX cleanup ULT may make
wrong decision to commit the DTX, but the DTX leader would abort such DTX
after related IO RPC to the bad non-leader(s) timeout.
=> DAOS-10045 dtx: not cleanup old DTX entry with leader on current target

src/tests/ftest/launch.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/distro_utils.py
Adding support for Rocky Linux and AlmaLinux to the avocado.utils.distro method.
Features: harness_advanced_test
=> DAOS-9994 test: Updating detect() method with missing distros

src/tests/ftest/daos_test/suite.yaml
to avoid the cascading RPC issue and further CI failures, bump timeout
on test.
Test-tag: test_daos_oid_allocator
=> DAOS-623 test: bump timeout on oid allocator test

src/vos/ilog.c, src/vos/ilog.h, src/vos/vos_ilog.c, src/vos/vos_io.c
master branch PRs: #8376, #8410
In first implementation of ilog tracking, we added a separate
allocation for tracking removals. Embed this information
in the, normally embedded, status array. This doesn't make
a big difference in practice but does reduce allocations on the
critical path for aggregation.
There is an inconsistency in the handling of -DER_INPROGRESS entries.
In all cases, the whole ilog should be parsed and the entries should
be marked such, letting the higher level parsing function handle
things. There was previously an inconsistency between the behavior
when updating status on a cached ilog and reading a new one.
Also, remove some unecessary assertions on the critical path and,
since we no longer ever return -DER_INPROGRESS from ilog_fetch,
remove a check on the critical …
=> DAOS-9756 vos: ilog_fetch cleanup and optimizations

src/cart/crt_rpc.c, src/include/cart/api.h, src/mgmt/cli_mgmt.c, src/tests/ftest/daos_test/suite.yaml, src/tests/ftest/pool/create_capacity.yaml
Cherry-pick of PR 8279 master commit 6b5eef3 to the release/2.0 branch.
Speed up client finding pool service replicas particularly for the
situation that a daos_engine rank is no longer reachable. Reduce
the MGMT_POOL_FIND RPC timeout to 1/4 the cart RPC timeout, with
a lower bound of 10 seconds timeout.
Test-tag: pr, daily_regression
=> DAOS-9519 mgmt: reduce MGMT_POOL_FIND RPC timeouts (#8279)

src/container/srv_target.c, src/include/daos_srv/container.h, src/object/srv_ec_aggregate.c, src/object/srv_obj.c
Add ec_update timestamp for each EC modify IO, and
do EC aggregation will only be executed only if
there is EC object modification.
This is only for 2.0 release to resolve EC aggregate
performance issue temporarily.
=> DAOS-9756 object: add ec_update timestamp

src/common/btree.c, src/object/cli_obj.c, src/tests/suite/daos_obj.c, src/vea/tests/vea_ut.c, src/vea/vea_api.c, src/vea/vea_init.c, src/vos/evt_iter.c, src/vos/evtree.c, src/vos/tests/vts_common.c, src/vos/tests/vts_mvcc.c, src/vos/vos_gc.c
Coverity has identified several issues in the engine code and tests ranging
from resource leaks to uninitialized fields and dead code.
Master PR#8395
=> DAOS-10025 coverity: Fix Various Issues (#8395)

src/cart/utils/memcheck-cart.supp
Add memcheck suppressions to silence any go warnings based on
filename.
=> DAOS-9934 test: Suppress any error from go. (#8390)

src/control/lib/control/auto.go
In the unusual case where the server already had a configuration,
the network scan during config generate was limited to the
provider already configured. This led to confusing results.
=> DAOS-10050 control: Scan all net providers in config gen
