daos-stack/daos

- docs/overview/architecture.md
docs/overview: improve wording in architecture.md
A small change to get my feet wet contributing to DAOS.
-- Anthony D'Atri, Intel NPSG
Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>
> docs/overview: improve wording in architecture.md

- docs/admin/administration.md
- docs/admin/deployment.md
Add command usage text to show up-to-date syntax. Note that daos_server
storage subcommands are not configuration file aware.
> DAOS-9240 docs: update administration section command syntax

- docs/admin/administration.md
- docs/admin/deployment.md
Reverts daos-stack/daos#7790 since patch was inadvertently landed to the release branch.
> Revert "DAOS-9240 docs: update administration section command syntax (#7722)"

- src/include/daos/object.h
- src/object/cli_ec.c
- src/object/srv_ec_aggregate.c
- src/tests/suite/daos_degrade_ec.c
- src/tests/suite/daos_epoch_io.c
- src/tests/suite/daos_iotest.h
> Revert "DAOS-9357 EC: refine obj_ec_parity_check() for data recovery"

- docs/QSG/setup_centos.md
- docs/QSG/setup_suse.md
- docs/QSG/tour.md
Several patches were landed to release/2.0 that were not ported
to master. Resync the content in this patch.
Doc-only: true
> DAOS-9321 doc: align QSG on master with release/2.0

- site_scons/components/__init__.py
> DAOS-9140 build: add lsvmd and nvme_manage example binaries

- src/client/dfuse/il/int_posix.c
If process quit without calling close(), it will make open
counter missed to decrease, daos_pool_disconnect() will return
EBUSY since ioil_shrink_cont() was skipped.
> DAOS-9013 dfuse: skip open counter check in ioil_fini() (#7259)

- src/bio/bio_internal.h
- src/bio/bio_monitor.c
- src/dtx/dtx_srv.c
- src/engine/init.c
- src/engine/sched.c
- src/engine/srv_metrics.c
- src/vea/vea_util.c
COUNTER is supposed to be increasing only, this patch changed few
COUNTER metric to GAUGE accordingly.
> DAOS-9054 sched: fix few metric types

- docs/QSG/docker.md
> DAOS-9088 docker: Documentation formatting hotfix

- docs/QSG/setup_centos.md
update setup_centos.md to reference correct repo for CentOS 7/8
Doc-only: true
> DAOS-9569 (doc): update setup_centos.md for CentOS 7/8

- utils/node_local_test.py
- utils/sl/check_script.py
A recent change to pylint checks meant that we were now getting
many errors for this file.
> CART-89 test: Fix all pylint issues in NLT.

- src/tests/ftest/launch.py
> DAOS-9285 tests: Back out part of 45759baf

- docs/release/release_notes.md
fix hyperlink in release_notes
Doc-only: true
> DAOS-9355 (doc): fix hyperlink in release_notes

- src/include/daos/object.h
- src/object/cli_ec.c
- src/object/srv_obj.c
- src/tests/ftest/daos_test/suite.yaml
- src/tests/suite/daos_epoch_io.c
- src/tests/suite/daos_obj_ec.c
(master commit 83d4f8bc1eed0)
For EC data recovery, merge parity list at server side.
And two small refines on test code.
> DAOS-9236 EC: merge parity list at server side

- docs/QSG/setup_centos.md
> DAOS-9621 doc: Fix repo link and instructions in setup_centos.md

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
Hotfix incompatible flags error message.
> DAOS-9196 control: specify pool capacity with percentage

- docs/release/support_matrix.md
placeholder for 2.2 support_matrix
Doc-only: true
> DAOS-9355 (doc): stub for 2.2 support_matrix

- docs/admin/administration.md
- src/control/cmd/dmg/storage.go
> DAOS-6945 control: update dmg storage nvme-rebind documentation

- .rpmignore
list packages to be excluded from repositories in .rpmignore
Doc-only:true
> DAOS-9675 (doc): .rpmignore

- docs/overview/use_cases.md
fix figure href in use_cases.md
Doc-only: true
> DAOS-9355 (doc): daos 2.0 doc fixes

- src/common/rsvc.c
Since we use reliable datagrams, it seems using at most 1 for
rsvc_client.sc_leader_aliveness (i.e., do not retry the leader before
starting a leader search) will make more sense in most cases. This patch
converts the maximum leader aliveness to a macro and reduces the value
from 2 to 1.
> DAOS-9040 common: Reduce rsvc_client leader_aliveness

- docs/overview/terminology.md
- Add link to raft.github.io
Doc-only: true
Skip-Test: true
> DAOS-623 doc: add raft link

- docs/overview/use_cases.md
fix figure href in use_cases.md
Doc-only: true
> DAOS-9355 (doc): fix figure href in use_cases.md

- docs/release/release_notes.md
The text in the release notes about known security issues is updated to meet
release requirements.
Doc-only: true
> DAOS-9765 doc: Fix Security Text in Release Notes

- src/tests/ftest/control/daos_admin_privileged.py
- src/tests/ftest/control/daos_admin_privileged.yaml
- src/tests/ftest/util/server_utils.py
Description: Remove orterun from test.yaml and update server_utils.py.
Test-repeat: 30
Test-tag: daos_admin
> DAOS-9352-test: control/daos_admin_privileged.py:DaosAdminPrivTest.test_daos_admin_format

- README.md
> DAOS-623 doc: Add SODA logo to readme

- docs/admin/predeployment_check.md
PR-repos: spdk@PR-37
To avoid conflicts with other packages, the spdk examples are
renamed appropriately to be consistent with existing apps.
Update doc.
> DAOS-9770 build: SPDK examples binaries renamed with prefix spdk_nvme_

- docs/release/release_notes.md
Update release_notes.md with a 2.0.1 section
Doc-only: true
> DAOS-9355 (doc): Update release_notes.md for 2.0.1

- src/vos/vos_aggregate.c
- src/vos/vos_common.c
- src/vos/vos_internal.h
- src/vos/vos_obj.c
- src/vos/vos_obj_index.c
- src/vos/vos_pool.c
Added per pool VOS aggregation metrics.
> DAOS-9651 vos: Add VOS aggregation metrics

- src/bio/bio_buffer.c
- src/bio/bio_internal.h
- src/bio/bio_xstream.c
- src/control/server/storage/config.go
> DAOS-9689 bio: apply socket-id in spdk dma malloc

- docs/admin/pool_operations.md
just a small documentation update
> correct get-acl outfile parameter docs

- docs/release/release_notes.md
Add a referenct to DAOS-9725 (DER_CSUM) to the "known issues"
section of the 2.0.1 release notes.
Doc-only: true
> DAOS-9355 (doc): Add DAOS-9725 to 2.0.1 release_notes.md

- docs/overview/transaction.md
Fix a few things in the dtx documentation and add example with
the transaction flow.
Doc-only: true
> DAOS-623 doc: add more info about distributed transaction

- src/object/cli_shard.c
- src/object/obj_rpc.h
- src/object/srv_obj.c
- src/tests/suite/daos_obj.c
Signed-off-by: Lei Huang <wiliam_huang@hotmail.com>
> DAOS-9612 Adding the support of descending order in daos_obj_list_recx

- Jenkinsfile
- LICENSE
- debian/copyright
- mkdocs.yml
- site_scons/prereq_tools/c_source/cmocka_tests.h
- site_scons/prereq_tools/c_source/unit_test.c
- site_scons/prereq_tools/c_source/unit_test.h
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.checkpatch
- utils/docker/Dockerfile.code_scanning
- utils/docker/Dockerfile.leap.15
- utils/docker/Dockerfile.ubuntu.20.04
- utils/docker/vcluster/daos-admin/el8/Dockerfile
- utils/docker/vcluster/daos-base/el8/Dockerfile
- utils/docker/vcluster/daos-client/el8/Dockerfile
- utils/docker/vcluster/daos-server/el8/Dockerfile
- utils/docker/vcluster/docker-compose.yml
- utils/fix_cmocka_xml.py
- utils/rpms/packaging/Dockerfile.centos.7
- utils/rpms/packaging/Dockerfile.mockbuild
- utils/rpms/packaging/Dockerfile.ubuntu.20.04
- utils/sl/fake_scons/SCons/Builder/__init__.py
- utils/sl/fake_scons/SCons/Errors/__init__.py
- utils/sl/fake_scons/SCons/__init__.py
bump copyright to 2022 (all but the /src/ tree)
> DAOS-9355 (doc): bump copyright to 2022

- src/control/server/mgmt_pool.go
In rare circumstances, there may be a race between pool
cleanup handlers which results in one "losing" by
attempting to remove an already-removed pool service. In
this case, just move on and return success, as there's
nothing else to be done.
> DAOS-8899 control: Handle race in pool cleanup handlers

- .github/CODEOWNERS
- src/vos/vos_obj.c
> DAOS-623 vos: Fix vos codeowners

- NOTICE
- README.md
fix hyperlinks in README, align with master
Doc-only: true
> DAOS-9693 doc: fix hyperlinks in README, align with master

- src/tests/ftest/erasurecode/rebuild_fio.py
Update JIRA ticket number in skip tag for rebuild_fio.py since new bugs were identified after running them.
Test-tag: ec_online_rebuild_fio ec_offline_rebuild_fio
> DAOS-9776 test: Update JIRA ticket number in skip tag for rebuild_fio.py

- .github/CODEOWNERS
> DAOS-623 misc: Disable all CODEOWNERS

- docs/overview/architecture.md
add comment on dmesg "EXPERIMENTAL" warning for EXT4-fs pmemX DAX mount
Doc-only: true
> DAOS-8734 doc: add comment on dmesg DAX warning

- src/common/pool_map.c
- src/placement/tests/jump_map_place_obj.c
Update total target number of the pool map after extending
the pool map.
> DAOS-9798 placement: update total target nr after map extending

- docs/release/support_matrix.md
minor 2.0 support matrix updates
Doc-only: true
> DAOS-9355 doc: minor 2.0 support matrix updates

- .github/CODEOWNERS
> DAOS-623 review: Enable vos-watcher in CODEOWNERS

- src/common/pool_map.c
- src/placement/tests/jump_map_place_obj.c
Update total target number of the pool map after extending
the pool map.
> DAOS-9798 placement: update total target nr after map extending (#8051)

- src/control/cmd/daos_firmware/handler.go
- src/control/cmd/daos_firmware/handler_test.go
- src/control/cmd/daos_firmware/main.go
- src/control/lib/hostlist/fuzz.go
- src/control/lib/telemetry/counter.go
- src/control/lib/telemetry/counter_test.go
- src/control/lib/telemetry/duration.go
- src/control/lib/telemetry/duration_test.go
- src/control/lib/telemetry/gauge.go
- src/control/lib/telemetry/gauge_test.go
- src/control/lib/telemetry/promexp/collector.go
- src/control/lib/telemetry/promexp/collector_test.go
- src/control/lib/telemetry/snapshot.go
- src/control/lib/telemetry/snapshot_test.go
- src/control/lib/telemetry/telemetry.go
- src/control/lib/telemetry/test_helpers.go
- src/control/lib/telemetry/timestamp.go
- src/control/lib/telemetry/timestamp_test.go
- src/control/logging/syslog.go
- src/control/logging/syslog_test.go
- src/control/pbin/setuid_linux.go
- src/control/security/grpc_cert_configs.go
- src/control/security/grpc_cert_configs_pre1.15.go
The new version indicated some changes in our code were needed.
> DAOS-9768 control: Run go1.17 gofmt

- src/control/cmd/daos_firmware/handler.go
- src/control/cmd/daos_firmware/handler_test.go
- src/control/cmd/daos_firmware/main.go
- src/control/lib/hostlist/fuzz.go
- src/control/lib/netdetect/netdetect_integration_test.go
- src/control/lib/telemetry/counter.go
- src/control/lib/telemetry/counter_test.go
- src/control/lib/telemetry/duration.go
- src/control/lib/telemetry/duration_test.go
- src/control/lib/telemetry/gauge.go
- src/control/lib/telemetry/gauge_test.go
- src/control/lib/telemetry/promexp/collector.go
- src/control/lib/telemetry/promexp/collector_test.go
- src/control/lib/telemetry/snapshot.go
- src/control/lib/telemetry/snapshot_test.go
- src/control/lib/telemetry/telemetry.go
- src/control/lib/telemetry/test_helpers.go
- src/control/lib/telemetry/timestamp.go
- src/control/lib/telemetry/timestamp_test.go
- src/control/logging/syslog.go
- src/control/logging/syslog_test.go
- src/control/pbin/setuid_linux.go
- src/control/security/grpc_cert_configs.go
- src/control/security/grpc_cert_configs_pre1.15.go
The new version indicated some changes in our code were needed.
> DAOS-9768 control: Run go1.17 gofmt (#8188)

- src/cart/utils/memcheck-cart.supp
Change memcheck suppressions so it matches new stack frame format.
> DAOS-9768 test: Update go supression files for new version.

- src/vos/vos_dtx.c
In old implementation, we count the committed DTX entries in DRAM for
daos metrics. When application close the container, the committed DTX
entries for the container in DRAM will be dropped to release the DRAM
resource as to the daos metrics for committed DTX entries will become
zero. But related in-PMEM entries are still there. That will misguide
users, and also cause DTX aggregation cannot work properly.
The patch fixes the logic to count the committed DTX entries in PMEM.
> DAOS-9003 vos: count committed DTX entries in PMEM for daos metrics

- .github/workflows/landing-builds.yml
- src/utils/daos_hdlr.c
Handle mixing of daos_size_t and ssize_t.
> DAOS-9254 utils: fix compile error on centos7

- src/control/server/storage/bdev/backend_test.go
> DAOS-9894 control: Fix fault package namespace

- src/tests/ftest/pool/create.py
Remove test_create_no_space from pool/create.py because the steps in this case is already covered in test_create_no_space_loop.
Test-tag: pool_create_tests
> DAOS-9948 test: Remove test_create_no_space from pool/create.py

- docs/QSG/docker.md
- docs/QSG/setup_centos.md
- docs/QSG/tour.md
- docs/admin/hardware.md
- docs/admin/performance_tuning.md
- docs/dev/development.md
- docs/overview/architecture.md
- docs/overview/data_integrity.md
- docs/overview/terminology.md
fix more broken hyperlinks in v2.2 docs
Doc-only: true
> DAOS-9881 doc: fix more broken hyperlinks

- README.md
minor edits to README.md
Doc-only: true
> DAOS-9355 doc: README.md update

- src/tests/ftest/container/open.py
Update the JIRA ID.
Also refactor the tags.
Test-tag: container_open
> DAOS-9965 test: Update JIRA ID in container/open.py

- docs/QSG/autotest.md
- docs/admin/installation.md
- docs/user/spark.md
fix more broken hyperlinks
Doc-only: true
> DAOS-9889 doc: fix more broken hyperlinks

- docs/admin/performance_tuning.md
- docs/dev/development.md
- docs/user/interface.md
fix more broken hyperlinks
Doc-only: true
> DAOS-9880 doc: fix more broken hyperlinks

- docs/debugging.md
- docs/user/spark.md
- mkdocs.yml
fix more broken hyperlinks
Doc-only: true
> DAOS-9880 doc: fix even more broken hyperlinks

- .gitignore
- Doxyfile
- docs/debugging.md
- docs/overview/data_integrity.md
- mkdocs.yml
fix more broken links in v1.2 docs
Doc-Only: true
> DAOS-5579 doc: fix more broken links in v1.2 docs

- docs/admin/predeployment_check.md
document DAOS deamon user/group setup in predeployment_checklist
Doc-only: true
> DAOS-9355 doc: document DAOS daemon user/group setup

- docs/debugging.md
- docs/user/spark.md
fix more broken hyperlinks
Doc-only: true
> DAOS-9881 doc: fix even more broken hyperlinks

- docs/admin/predeployment_check.md
document DAOS deamon user/group setup in predeployment_checklist
> DAOS-9355 doc: document DAOS daemon user/group setup (#8353)

- src/cart/utils/memcheck-cart.supp
Pick up all the master changes to this file to silence
intermittent errors.
Skip-build-centos7-rpm: true
Skip-build-el8-rpm: true
Skip-build-centos8-rpm: true
Skip-unit-test-memcheck: false
Skip-func-test-el8: true
Skip-test-rpms: true
> DAOS-9934 test: Sync memcheck suppression file with master.

- src/include/daos_api.h
> DAOS-623 api: suppress unused argument warnings

- src/container/srv_target.c
To minimize the performance impact for lazy aggregation mode,
we choose to abort current aggregation when system is busy and no
space pressure.
> DAOS-9651 vos: abort aggregation for lazy mode

- src/common/btree.c
- src/object/cli_obj.c
- src/tests/suite/daos_obj.c
- src/vea/tests/vea_ut.c
- src/vea/vea_api.c
- src/vea/vea_init.c
- src/vos/evt_iter.c
- src/vos/evtree.c
- src/vos/tests/vts_common.c
- src/vos/tests/vts_mvcc.c
- src/vos/vos_gc.c
Coverity has identified several issues in the engine code and tests ranging
from resource leaks to uninitialized fields and dead code.
> DAOS-10025 Coverity: Fix Various Coverity Issues

- utils/rpms/daos.spec
bump Release in daos.spec to -23
> DAOS-6344 build: create daos_daemons secondary group

- docs/admin/deployment.md
clean up agent section in admin/deployment.md
Doc-only: true
> DAOS-9355 doc: clean up agent section in deployment.md

- docs/admin/deployment.md
clean up agent section in admin/deployment.md
> DAOS-9355 doc: clean up agent section in deployment.md (#8401)

- src/rebuild/rebuild_iv.c
- src/rebuild/srv.c
Add some rebuild IV debug information.
> DAOS-10125 rebuild: add rebuild IV debug info

- utils/grafana/DAOS-Grafana-Dashboard.json
Update the Grafana dashboard to support changes in metrics.
> DAOS-8054 grafana: Update Grafana dashboard

- docs/QSG/setup_suse.md
Also add a space after !!! for !!! note for consistency with
the rest of the documentation.
Doc-only: true
> DAOS-9881 doc: update SuSE instructions to use 15.3

- docs/QSG/setup_suse.md
Also add a space after !!! for !!! note for consistency with
the rest of the documentation.
> DAOS-9881 doc: update SuSE instructions to use 15.3 (#8391)

- src/object/srv_ec_aggregate.c
clear EC stripe list if EC aggregation is aborted, since post_cb
might be skipped.
> DAOS-10147 EC: clear EC stripe list if EC aggregation is aborted

- docs/release/release_notes.md
update release notes for 2.0.2 fixlevel
Doc-only: true
> DAOS-9355 doc: Release Notes for 2.0.2

- src/tests/ftest/datamover/copy_procs.py
- src/tests/ftest/datamover/dst_create.py
- src/tests/ftest/datamover/large_dir.py
- src/tests/ftest/datamover/large_file.py
- src/tests/ftest/datamover/negative.py
- src/tests/ftest/datamover/negative_space.py
- src/tests/ftest/datamover/obj_large_posix.py
- src/tests/ftest/datamover/obj_small.py
- src/tests/ftest/datamover/posix_meta_entry.py
- src/tests/ftest/datamover/posix_preserve_props.py
- src/tests/ftest/datamover/posix_subsets.py
- src/tests/ftest/datamover/posix_symlinks.py
- src/tests/ftest/datamover/posix_types.py
- src/tests/ftest/datamover/serial_large_posix.py
- src/tests/ftest/datamover/serial_small.py
Test-tag: datamover,-iosysadmin
Tag datamover tests with more feature tags
> DAOS-10129 test: add feature tags to ftest/datamover

- src/tests/ftest/util/general_utils.py
Test-tag: rebuild_test
Test-repeat: 5
Signed-off-by: Kurniawan Alfizah <kurniawan.alfizah@intel.com>
> DAOS-9929 test: Test updated for 9929, increase clush timeout.

- src/dtx/dtx_common.c
If there are too many sub requests to be handled by IO forward ULT,
then need to yield CPU periodically during the process (even if for
handling failure case) to avoid holding CPU for too long time.
> DAOS-10131 dtx: IO forward ULT avoids holding CPU for too long time

- src/control/system/raft.go
In the rare event that a leadership loss occurs while a
request is being processed, return a sentinel error that
will cause some callers (e.g. system.Join()) to retry.
> DAOS-10168 control: Retry Join on leadership loss

- src/tests/SConscript
- src/tests/simple_pipeline_str_arrays.c
> add simple pipeline example to represent dfs find workload

- debian/daos-server.install
- src/client/api/pipeline.c
- src/include/daos_pipeline.h
- src/pipeline/cli_mod.c
- src/pipeline/cli_pipeline.c
- src/pipeline/common_pipeline.c
- src/pipeline/filter.c
- src/pipeline/filter_funcs.c
- src/pipeline/getdata_funcs.c
- src/pipeline/pipeline_internal.h
- src/pipeline/pipeline_rpc.c
- src/pipeline/pipeline_task.c
- src/pipeline/srv_pipeline.c
- src/tests/pipeline_common.c
- src/tests/pipeline_common.h
- src/tests/simple_pipeline.c
- src/tests/simple_pipeline_arrays.c
- src/tests/simple_pipeline_str_arrays.c
- utils/rpms/daos.spec
Creating pull request just to run all the checks
> Pipeline api v0.1

- .github/workflows/landing-builds.yml
- src/client/setup.py
- utils/run_in_ga.sh
- utils/scripts/install-ubuntu20.sh
Fix style errors in pydaos install script and add it to
automatic testing.
> DAOS-7821 pydaos: Improve setup.py and add test to GHA.

- docs/release/release_notes.md
fix nesting of headings in release_notes
Doc-only: true
> DAOS-9355 doc: fix relnotes headings

- src/pipeline/srv_pipeline.c
To not overwhelm the DAOS server, and since the Pipeline API
scans all items in order to filter and/or aggregate, yield should be
done after a while to give other RPC handling ULTs the opportunity to
run.
Signed-off-by: Eduardo Berrocal <eduardo.berrocal@intel.com>
> Doing yield after an X number of dkey fetches

- docs/release/release_notes.md
- docs/release/support_matrix.md
- docs/release/upgrading.md
- mkdocs.yml
add upgrade information doc for 2.2
move release infos to the front of the mkdocs title bar
Doc-only: true
> DAOS-9355 doc: updates for release infos

- docs/admin/troubleshooting.md
> DAOS-9579 Doc: Adding pmempool check and repair command example.

- src/control/cmd/dmg/pool.go
- src/control/cmd/dmg/pool_test.go
- src/gurt/misc.c
- src/mgmt/srv_drpc.c
Integrate last comment from reviewers which were not integrated begore the delivery of the 2.2 release.
> DAOS-10072 control: show all rank states of a pool

- docs/release/release_notes.md
- docs/release/upgrading.md
- mkdocs.yml
add upgrade information for 2.0.x fix levels
move release infos to the front of the mkdocs title bar
Doc-only: true
> DAOS-9355 doc: add upgrade information for 2.0.x fix levels

- docs/release/support_matrix_v2_2.md
- docs/release/upgrading_v2_2.md
- mkdocs.yml
add draft v2.2 release notes and v2.2 upgrading documents
(not linked to the docs.daos.io web pages yet)
Doc-only: true
> DAOS-9355 doc: add draft v2.2 release notes and upgrading doc

- src/object/srv_ec_aggregate.c
Optimize EC aggregation by ignoring any tree that doesn't have
an aggregatable write
> DAOS-10227 vos: Use aggregatable filter in EC aggregation

- src/rebuild/scan.c
rebuild scan should only yield after the current object
has been processed, since the reprobe will skip the
object, then it will not be rebuilt.
> DAOS-10172 rebuild: scan yield after processing objects

- src/tests/ftest/util/apricot/apricot/test.py
Update the skip-list file utilized by the release/2.2 branch.
skip-unit-tests: true
> DAOS-623 test: Update skip list file

- src/rebuild/scan.c
rebuild scan should only yield after the current object
has been processed, since the reprobe will skip the
object, then it will not be rebuilt.
> DAOS-10172 rebuild: scan yield after processing objects (#8682)

- docs/admin/administration.md
- docs/admin/performance_tuning.md
- docs/dev/development.md
- docs/testing/datamover.md
- docs/user/hdf5.md
fix more linkcheck issues
Doc-only: true
> DAOS-9355 doc: fix more linkcheck issues

- src/client/api/pipeline.c
- src/include/daos/task.h
- src/include/daos_pipeline.h
- src/include/daos_task.h
- src/pipeline/cli_pipeline.c
- src/pipeline/common_pipeline.c
- src/pipeline/filter.c
- src/pipeline/getdata_funcs.c
- src/pipeline/pipeline_rpc.h
- src/pipeline/pipeline_task.c
- src/pipeline/srv_pipeline.c
- src/tests/simple_pipeline.c
- src/tests/simple_pipeline_arrays.c
- src/tests/simple_pipeline_str_arrays.c
Changed:
-- The way the user pass sgl buffers to the API (more flexibility)
-- Bulk transfer for large data
> Daos 10290

- debian/changelog
- debian/control
- site_scons/components/__init__.py
- utils/build.config
- utils/rpms/daos.spec
PR-repos: libfabric@PR-56
Signed-off-by: Lei Huang <wiliam_huang@hotmail.com>
> DAOS-9883 libfabric: Update to v1.15.0rc3-1

- src/tests/jobtest.c
Add support for pool labels and more test modes.
> DAOS-5696 test: Update jobtest utility

- src/control/system/raft.go
In the rare event that a leadership loss occurs while a
request is being processed, return a sentinel error that
will cause some callers (e.g. system.Join()) to retry.
> DAOS-10168 control: Retry Join on leadership loss (#8550)

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
- docs/QSG/tour.md
- mkdocs.yml
rename EL doc to setup_rhel.md
Doc-only: true
> DAOS-9355 doc: rename EL doc to setup_rhel.md (#8839)

- src/pipeline/common_pipeline.c
- src/pipeline/filter.c
Added comprehensive error messages for pipeilne_check(), as well as some missing checks that were needed urgently.
> Daos 10459

- debian/changelog
- utils/rpms/daos.spec
> DAOS-10403 mercury: Disable unified mode in UCX.

- debian/changelog
- utils/rpms/daos.spec
> DAOS-10403 mercury: Disable unified mode in UCX. (#8922)

- Jenkinsfile
- ci/junit.sh
- ci/provisioning/post_provision_config.sh
- ci/provisioning/post_provision_config_common.sh
- ci/provisioning/post_provision_config_common_functions.sh
- ci/provisioning/post_provision_config_nodes.sh
- ci/provisioning/post_provision_config_nodes_EL_7.sh
- ci/provisioning/post_provision_config_nodes_EL_8.sh
- ci/provisioning/post_provision_config_nodes_LEAP_15.sh
- ci/rpm/build_unsuccessful.sh
- ci/rpm/test_daos_node.sh
- ci/stacktrace.sh
- utils/docker/Dockerfile.centos.7
- utils/docker/Dockerfile.el.8
- utils/docker/Dockerfile.leap.15
- utils/rpms/packaging/Dockerfile.centos.7
- utils/rpms/packaging/Dockerfile.mockbuild
- utils/rpms/packaging/Makefile_packaging.mk
- utils/rpms/packaging/rpm_chrootbuild
- utils/scripts/install-centos7.sh
- utils/scripts/install-el8.sh
- utils/scripts/install-leap15.sh
For Dockerfiles, package building and functional testing.
Fall back to Nexus repos if Artifactory repos fail for any reason and
fall back to on-image repo definitiion of fetching of repos fails for
any reason.
Move bulk of package installation in Leap 15 Dockerfile to DNF to avoid
cache coherency issues on repository proxies.
> DAOS-9919, CORCI-1170, CORCI-1171 ci: Use Artifactory

- src/cart/crt_group.c
- src/client/api/container.c
- src/client/dfuse/test/test_ioil.c
- src/container/srv_layout.c
- src/engine/sched.c
- src/engine/server_iv.c
- src/object/tests/srv_checksum_tests.c
- src/placement/tests/place_obj_common.c
- src/tests/ftest/cart/dual_iface_server.c
- src/tests/suite/dfs_unit_test.c
- src/utils/ctl/cart_ctl.c
- src/utils/daos_hdlr.c
These fixes resolve roughly 20 issues detected by coverity introduced during
the 2.2 development timeframe.
Master PR#8852
> DAOS-10414 coverity: fixes for various issues (#8852)

- src/object/README.md
Update object documentation to match changes done with
the object ID refactoring. Remove client-side replication
since this is not tested/supported any longer.
doc-only: true
> DAOS-10205 doc: update object README

- src/rebuild/srv.c
Do not update rebuild rec/object cnt for leader IV notify information,
which might mess up the rebuild rec/object count.
> DAOS-10589 rebuild: do not update rec/obj count for leader iv notify

- Jenkinsfile
Start the timed master daily build 4 hours sooner.
> DAOS-10586 test: Starting master daily build earlier

- Jenkinsfile
- ci/provisioning/post_provision_config_common.sh
- ci/provisioning/post_provision_config_nodes.sh
- ci/rpm/test_daos_node.sh
- utils/rpms/Makefile
- utils/rpms/packaging/Dockerfile.mockbuild
- utils/rpms/packaging/Makefile_distro_vars.mk
- utils/rpms/packaging/Makefile_packaging.mk
- utils/rpms/packaging/rpm_chrootbuild
- utils/rpms/packaging/rpmlint--ignore-unused-rpmlintrc.patch
But don't allow distro packages to upgrade MLNX packages.
Add EL 8.5 RPMs testing stage.
> DAOS-623 ci: Allow fuse to upgrade

- utils/docker/Dockerfile.centos.7
Removed the NOOP dnf -y install deltarpm
Testing to see if it fixes the hang seen at https://daosio.atlassian.net/browse/DCO-10410
> Removed the NOOP dnf -y install deltarpm

- src/rebuild/srv.c
Only set DRS_NOT_STARTED if the pool map version < 2, otherwise
if there are no ongoing rebuild, let's set rebuild status as
DRS_COMPLETE.
> DAOS-10521 rebuild: Only set NOT_STARTED status if map_version < 2

- src/control/server/config/server_test.go
- utils/config/examples/daos_server_local.yml
- utils/config/examples/daos_server_tcp.yml
- utils/config/examples/daos_server_unittests.yml
Stop using legacy storage style and show correct usage of nr_hugepages.
> DAOS-10581 doc: Update example server config files (#8996)

- src/tests/ftest/daos_test/suite.yaml
> DAOS-9868 test: collect more ofi logs

- src/client/dfuse/ops/setattr.c
- utils/node_local_test.py
> DAOS-6540 dfuse: Add chgrp support to dfuse.

- src/object/cli_obj.c
Initialize task list in obj_ec_recov_cb.
> DAOS-10525 ec: fix typo in obj_ec_recov_cb

- src/vos/vos_space.c
Don't reserve NVMe for dealing with fragmentation issues, otherwise,
there will be big chunk of NVMe space not available for user.
Without NVMe reservation, NVMe allocation could fail due to
fragmentations, but that will only affect the data coalescing during
aggregation, space reclaiming by punch and GC won't be affected.
> DAOS-5813 vos: get rid of NVMe reservation

- Jenkinsfile
> DAOS-623 build: Remove stages to build and test CentOS 7 on rpms.

- src/vos/vos_space.c
Don't reserve NVMe for dealing with fragmentation issues, otherwise,
there will be big chunk of NVMe space not available for user.
Without NVMe reservation, NVMe allocation could fail due to
fragmentations, but that will only affect the data coalescing during
aggregation, space reclaiming by punch and GC won't be affected.
> DAOS-5813 vos: get rid of NVMe reservation (#9280)

- src/control/server/ctl_storage_rpc.go
- src/control/server/ctl_storage_rpc_test.go
- src/tests/ftest/pool/create_all_hw.py
- src/tests/ftest/pool/create_all_hw.yaml
Clean backport of the PR https://github.com/daos-stack/daos/pull/9203
> DAOS-10593 control: Fix NVMe available space (#9203)

- docs/user/container.md
document DAOS container types
Doc-only: true
> DAOS-10641 doc: document DAOS container types (#9257)

- mkdocs.yml
fix mkdocs favicon
Doc-only: true
> DAOS-5579 doc: fix mkdocs favicon

- site_scons/prereq_tools/base.py
Check for None for self.component_prefix too
> DAOS-10849 build: fix ALT_PREFIX build

- src/tests/ftest/nvme/fragmentation.py
- src/tests/ftest/nvme/fragmentation.yaml
- src/tests/ftest/util/test_utils_base.py
Test-tag: test_nvme_fragmentation
- Set pool size to 95%
- Simplify/cleanup some logic
> DAOS-10498 test: improve nvme/fragmentation

- src/tests/ftest/launch.py
Adding running the vfio-pci binding fix workaround commands between
running avocado test files on the hosts that were used by the test to
run the daos_server command.
Also update the stopping of server and clients to limit commands to
hosts only used by the test to run servers and clients, respectively.
> DAOS-10608 test: Run vfio-pci workaround fix between tests (#9271)

- CONTRIBUTING.md
- README.md
- docs/admin/troubleshooting.md
- docs/dev/contributing.md
- docs/overview/fault.md
- docs/overview/terminology.md
switch doc URLs from http to https
Doc-only: true
> DAOS-9355 doc: switch doc URLs to https (#9428)

- mkdocs.yml
switch doc URLs in mkdocs.yml from http to https
Doc-only: true
> DAOS-9355 doc: switch doc URLs in mkdocs.yml to https

- src/control/server/server.go
There were some recent network-related control plane changes in
master that need to be updated to support a multiprovider config.
> DAOS-10876 control: Fix merges from master

- docs/admin/deployment.md
> DAOS-10132 doc: Update disable_vfio usage in admin guide

- src/control/server/config/server.go
> DAOS-10863 control: Fix log message

- src/client/api/event.c
since the function is supposed to be called when everything is locked, we
should do the lock on the ev with no eq outside of the function.
> DAOS-10756 event: move the ev lock to outside the comp_locked function

- src/ddb/SConscript
- src/ddb/ddb_cmd_options.c
- src/ddb/ddb_cmd_options.h
- src/ddb/ddb_commands.c
- src/ddb/ddb_main.c
- src/ddb/ddb_vos.c
- src/ddb/ddb_vos.h
- src/ddb/tests/ddb_cmd_options_tests.c
- src/include/daos_srv/vea.h
- src/vea/vea_api.c
The two new commands add the ability to view the free extents in the
vea free table as well as add new extents.
> DAOS-10617 ddb: View and Update VEA Free Table

- site_scons/build_info/__init__.py
- site_scons/build_info/base.py
- site_scons/components/__init__.py
- site_scons/prereq_tools/__init__.py
- site_scons/prereq_tools/base.py
- site_scons/prereq_tools/mocked_tests.py
- site_scons/site_tools/extra/__init__.py
- src/client/pydaos/raw/conversion.py
- src/client/pydaos/raw/daos_api.py
- src/client/pydaos/raw/daos_cref.py
- src/rdb/raft_tests/raft_tests.py
- utils/ansible/ftest/library/daos_hugepages.py
Remove /usr/bin/python from lots of places were it's not
required.  If needed then the file should have execute
permissions, and the line should read /usr/bin/env python3
so this code was both not used and incorrect.
Do not touch the ftest code as there are too many files
incorrect there for me to edit manually.
go: build support both amd64 and arm64.
> DAOS-623 python: Do not use #! for python files.

- src/control/server/server_utils.go
In the rare case that the node processing a SWIM dead event loses
leadership before the membership can be updated, handle the error
by re-forwarding the event so that the new leader will process it.
> DAOS-10903 control: Handle leadership loss while processing SWIM events

- site_scons/site_tools/extra/__init__.py
- site_scons/site_tools/extra/extra.py
> DAOS-623 pylint: Fix some pylint warnings

- src/client/api/event.c
- After acquiring the lock in the progress loop, check that the event is still in completed/aborted state before resetting to READY.
- Finalize the thread private event before calling init again to avoid calling pthread_mutex_init on non destroyed mutex.
> DAOS-10756 event: check before setting the event to READY

- src/include/daos/mem.h
- src/vos/vos_io.c
This makes these APIs consistent with umem_alloc/free
> DAOS-623 debug: Add some debug for umem_reserve/defer_free

- src/client/dfs/dfs.c
> DAOS-10984 DFS: fix coverity ID 105871, 119081

- src/tests/suite/daos_rebuild.c
check layout_get return value.
> DAOS-10996 tests: check layout_get return value

- src/tests/ftest/deployment/critical_integration.py
- src/tests/ftest/deployment/critical_integration.yaml
Add libfabric version check to deployment/critical_integration.py
Test-tag: criticalintegration pr
> DAOS-10656 test: Add libfabric version check to deployment/critical_integration.py (#9128)

- .github/workflows/pr-metadata.yml
- Jenkinsfile
- ci/jira_query.py
- requirements.txt
- utils/docker/Dockerfile.checkpatch
Add a GitHub action to parse Jira ticket information for a PR and update the PR
metadata to keep it in sync with Jira.  Add a comment to the PR which will be edited
to keep it up-to-date, and report the ticket description and status as well as adding
a link.
Warn on several issues around malformed PR titles (which become part of the commit
message when landed) and if work is happening on tickets which are not marked
as In Progress or In Review.
Set labels for 2.2 and 2.4 release tickets, as well as anything that should be treated
as a priority.
> DAOS-7821 gha: Add code to report Jira status into GitHub.

- src/client/pydaos/pydaos_shim.c
Signed-off-by: Sherin T George <sherin-t.george@hpe.com>
> pydaos uses shared event queue with verbs provider

- src/tests/ftest/datamover/copy_procs.py
- src/tests/ftest/datamover/copy_procs.yaml
- src/tests/ftest/datamover/dst_create.py
- src/tests/ftest/datamover/dst_create.yaml
- src/tests/ftest/datamover/large_dir.py
- src/tests/ftest/datamover/large_dir.yaml
- src/tests/ftest/datamover/large_file.py
- src/tests/ftest/datamover/large_file.yaml
- src/tests/ftest/datamover/negative.py
- src/tests/ftest/datamover/negative_space.py
- src/tests/ftest/datamover/negative_space.yaml
- src/tests/ftest/datamover/obj_large_posix.yaml
- src/tests/ftest/datamover/posix_meta_entry.py
- src/tests/ftest/datamover/posix_meta_entry.yaml
- src/tests/ftest/datamover/posix_preserve_props.py
- src/tests/ftest/datamover/posix_preserve_props.yaml
- src/tests/ftest/datamover/posix_subsets.py
- src/tests/ftest/datamover/posix_subsets.yaml
- src/tests/ftest/datamover/posix_symlinks.py
- src/tests/ftest/datamover/posix_types.py
- src/tests/ftest/datamover/posix_types.yaml
- src/tests/ftest/datamover/serial_large_posix.yaml
Resolve cosmetic python and yaml warnings.
> DAOS-7821 test: Fix style errors with datamover tests.

- src/container/srv_container.c
Before this change, when a new container was created, the metadata
rdb value for key ds_cont_prop_cont_global_version was written as
a 64-bit value in cont_prop_write(). However, the intent for this
recently-added key is a uint32_t typed value. Also, an inconsistency
exists with the pool/container layout upgrade code, upgrade_cont_cb()
writing the value as uint32_t. This results in some containers with
64-bit version values, and others with 32-bit values.
With this change, the cont_prop_write() and cont_prop_read() functions
are changed to write and read a 32-bit cont_global_version value in rdb,
to agree with the upgrade_cont_cb() code.
> DAOS-10929 container: fix size of cont_global_version value

- src/tests/ftest/nvme/fragmentation.py
- src/tests/ftest/nvme/fragmentation.yaml
- src/tests/ftest/util/test_utils_base.py
Test-tag: pr,hw,medium test_nvme_fragmentation
- Set pool size to 95%
- Simplify/cleanup some logic
- Make LabelGenerator threadsafe
> DAOS-10498 test: improve nvme/fragmentation (#9274)

- src/tests/ftest/control/dmg_network_scan.py
- src/tests/ftest/util/network_utils.py
Update network scan test to use cxi provider
> DAOS-10904 test: Update network scan test to use cxi provider (#9535)

- src/vos/vos_dtx.c
For resolving some coverity complaint.
> DAOS-10961 vos: dynamically allocate space for DTX commit

- docs/release/release_notes.md
- docs/release/upgrading.md
add release notes for DAOS 2.0.3
Doc-only: true
> DAOS-9355 doc: Release notes for DAOS 2.0.3

- utils/build.config
> DAOS-11141 build: Use githash for patch rather than branch

- src/tests/ftest/control/dmg_pool_query_test.py
Test-tag: test_pool_query_basic test_pool_query_inputs test_pool_query_ior
Update dmg_pool_query tests with expected values
> DAOS-10300 test: fix dmg_pool_query

- Jenkinsfile
To significantly reduce the job stage noise
> DAOS-623 ci: Import pragmas into an environment variable

- Jenkinsfile
Add methods to allow recording job status while the job runs
and write out a YAML file with the results.
> CORCI-1200 Build: Collect Job Information to YAML

- src/client/dfs/dfs.c
> DAOS-10984 DFS: fix coverity ID 105871, 119081 (#9594)

- src/tests/suite/daos_rebuild.c
check layout_get return value.
> DAOS-10996 tests: check layout_get return value (#9595)

- src/dtx/dtx_resync.c
During the server reintegration, some new update RPC may be sent to
the in-reintegrating server, that will generate new DTX entry which
version is newer than the version of server re-added. On the other
hand, there may be other server corruption during the reintegration
that will cause currern reintegration failure and be re-scheduled.
During the re-scheduled server reintegration, above mentioned new
generated DTX entry needs to be handled by normal DTX resync logic
instead of being discarded. The logic of discarding old DTX entries
for server reintegration is only applicable to the DTX entry which
version is older than the server re-added version.
> DAOS-11066 dtx: discard old DTX entries during server reintegration

- .github/workflows/pr-metadata.yml
- ci/jira_query.py
Load labels from github to avoid errors on removal.
Add components for il and mercury.
Experiment with pull_request_target.
Use denylist for ticket status
Co-authored-by: Phil Henderson <phillip.henderson@intel.com>
> DAOS-7821 gha: Tweak jira reporting script. (#9671)

- site_scons/prereq_tools/base.py
- src/tests/ftest/util/dfuse_utils.py
> Revert "DAOS-9915 test: rel_2.2 test to get Bullseye coverage data on El8"

- src/object/README.md
- Add object class naming conventions
- Add Caveat for maximum object layout
(cherry picked from commit f4ba4e537fac19f021385382cdd265ffdb326aad)
Co-authored-by: Wang Shilong <shilong.wang@intel.com>
> DAOS-6128 doc: add object class naming conventions (#9342)

- src/tests/ftest/server/metadata.yaml
Test-tag: metadata_fillup online_extend_with_csum
> DAOS-11153 test: Increase the mean threshold percentage.

- src/control/server/mgmt_pool.go
- src/mgmt/srv_drpc.c
- src/tests/ftest/pool/create_query.py
- src/tests/ftest/pool/create_query.yaml
- src/tests/ftest/util/test_utils_pool.py
Fix fields of the pool creation drpc reponse. Some of these fields where not filled by the engine: the control plane was using value from the request which could be different from what was really done.
> DAOS-10339 control: Fix pool creation drpc response (#8864)

- src/vos/vos_gc.c
Remove some dead-[test,code] that had been introduced by my
previous patch/commits :
_ 5babffc93488e63298557f81886a276551d61112
_ ab88cc93480d7a1507befe005d1c72ca81a71bb3
> DAOS-10998 vos: to address Coverity CID 105900 (#9627)

- utils/githooks/README.md
- utils/githooks/install
Doc-only: true
- Add utils/githooks/install
- Update README
> DAOS-11215 githooks: add githook install script

- Jenkinsfile
- ci/provisioning/post_provision_config.sh
- ci/provisioning/post_provision_config_common_functions.sh
- ci/provisioning/post_provision_config_nodes.sh
- ci/provisioning/post_provision_config_nodes_EL_8.sh
- utils/rpms/packaging/rpm_chrootbuild
Add CI_PROVISINING_POOL, CI_PR_REPOS and CI_FI_el8_TEST parameters.
Utilize the new parameters when configuring repos.
Always disable daos RPMs repo unless RPM-test-version or
CI_RPM_TEST_VERSION are used.
Fixes for launchable.
> SRE-92 ci: Updates to allow testing images

- src/pool/cli.c
Fix possible race condition in map_refresh.
> DAOS-11226 pool: refine map_refresh

- src/object/cli_shard.c
Commit bcce0b4c43 (EC shard rotate) introduced a regression in size
query handling, this patch fix it by refine obj_shard_query_recx_post().
Test-tag: ec_disabled_rebuild_array
> DAOS-10351 object: fix a bug of size query (obj_shard_query_recx_post)

- Jenkinsfile
Allow feature branch landings to be built and tested.
> SRE-451 build: Add feature/ to landing patterns

- src/common/tests/btree.c
Addresses CID: 21986
fail the test for ENOMEM
> DAOS-10956 test: fail the test for ENOMEM (#9682)

- src/container/srv_oi_table.c
While iterating container, cont_iter_obj_cb() leaks the current
OID after writing the previosu batch. This function should store
the current OID after writing to OIT.
> DAOS-10344 object: fix OID leak in OIT (#9838)

- src/vos/vos_aggregate.c
The ticket had a crash but it would be helpful to know which
part of the statement failed.
> DAOS-11232 vos: Add more information on aggregation crash

- ci/jira_query.py
this is annoying and adds spam IMO
> DAOS-623 ci: ticket status need not to be updated to push PRs

- ci/jira_query.py
> DAOS-623 ci: ticket status need not to be updated to push PRs (#9928)

- src/tests/ftest/deployment/critical_integration.py
- src/vos/storage_estimator/common/explorer.py
> DAOS-11319 test: fix pylint errors

- src/control/cmd/dmg/pretty/pool.go
- src/control/cmd/dmg/pretty/pool_test.go
- src/control/lib/control/pool.go
- src/mgmt/cli_mgmt.c
- src/mgmt/srv_pool.c
improve "Upgrade?" to "UpgradeNeeded?" to make output
more clear, also clean up codes a bit.
> DAOS-10300 control: improve pool list output (#9739)

- Jenkinsfile
- ci/provisioning/post_provision_config_common.sh
- ci/provisioning/post_provision_config_common_functions.sh
- utils/rpms/packaging/Makefile_packaging.mk
- utils/rpms/packaging/rpm_chrootbuild
It's at the point of being completely unreliable now and is masking
other failures.
Also, delegate Cancel previous stage processing to skipStage().
> DAOS-623 ci: Stop using Nexus

- utils/rpms/daos.spec
fix URL in daos.spec (missing :)
> DAOS-9355 build: fix URL in daos.spec

- utils/rpms/daos.spec
fix URL in daos.spec (missing :)
>  DAOS-9355 build: fix URL in daos.spec (#10027)

- utils/rpms/daos.spec
fix URL in daos.spec (missing :)
> DAOS-9355 build: fix URL in daos.spec (#10027)

- src/engine/server_iv.c
- src/object/cli_shard.c
Adding a few debug information for IV update.
> DAOS-10799 IV: add a few more debug information

- src/control/server/mgmt_pool.go
> DAOS-1140 control: Skip container check if pool is in destroying state

- src/rebuild/srv.c
Set rebuild complete status even for failure rebuild.
Test-tags: pr no_cap
> DAOS-11380 rebuild: set rebuild complete status

- src/object/obj_tx.c
missing ec rotation handling in tx classify
> DAOS-10524 tx: missing ec rotation in tx classify

- src/client/ds3/object.c
We should either merge this or https://github.com/daos-stack/daos/pull/10107 , whichever fixes it.
> Separate mkdir and dfs_lookup_rel in ds3_obj_create

- src/cart/crt_init.c
- src/gurt/misc.c
- src/include/gurt/common.h
> DAOS-11137 cart: Set UCX env var to allow memory allocation (#10012)

- utils/build.config
> DAOS-11151 build: Update developer PMDK version to 1.12.1

- utils/build.config
> DAOS-11151 build: Update developer PMDK version to 1.12.1 (#10115)

- src/vos/vos_aggregate.c
Since we can't reproduce DAOS-11232 anymore, let's add a bit
of debug in case it does happen again.
> DAOS-11232 vos: Add some instrumentation to aggregation

- src/client/dfs/dfs.c
> DAOS-11480 dfs: fix for coverity issues 119081, 119136, 105926, 105915

- src/client/dfs/dfs.c
Fixing: 119081, 119136, 105926, 105915
> DAOS-11480 dfs: fix for coverity issues

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
- docs/admin/deployment.md
- utils/config/daos_server.yml
- utils/config/examples/daos_server_local.yml
- utils/config/examples/daos_server_tcp.yml
- utils/config/examples/daos_server_unittests.yml
- utils/config/examples/daos_server_verbs.yml
document requirement for xs_helpers with EC (1 per 4 targets)
> DAOS-9355 doc: document requirement for xs_helpers with EC

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
- docs/admin/deployment.md
- utils/config/daos_server.yml
- utils/config/examples/daos_server_local.yml
- utils/config/examples/daos_server_tcp.yml
- utils/config/examples/daos_server_verbs.yml
document requirement for xs_helpers with EC (1 per 4 targets)
> DAOS-9355 doc: document requirement for xs_helpers with EC (#10141)

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
remove nr_hugepages from QSG (is now auto-calculated)
Doc-only: true
> DAOS-9355 doc: remove nr_hugepages from QSG

- src/tests/jobtest.c
Before this change the jobtest invocation of dc_cont_hdl2uuid() did
not check for a failure, leading to Coverity CID 22078. With this
change, the return code is checked and the test output is adjusted.
Performing build only in CI (skipping testing) since jobtest is only
invoked manually at this time. It was tested manually with this change.
> DAOS-11476 test: Fix coverity unchecked return in jobtest

- src/dtx/dtx_rpc.c
- src/object/cli_obj.c
- src/object/obj_tx.c
Fix the following coverity issues:
CID: 122757, 115028, 115029, 115030, 105941, 105919
> DAOS-11488 object: resolve some coverity issues

- src/tests/ftest/launch.py
Test-tag: pr,-hw
Support multiple extra yaml files to launch.py
> DAOS-11457 test: support multiple launch.py -e

- src/object/srv_obj_migrate.c
- src/rebuild/srv.c
- src/tests/suite/daos_rebuild_common.c
check return value for dsc_cont_close.
Put container child in all cases.
> DAOS-11492 object: check return value for dsc_cont_close (#10167)

- docs/admin/administration.md
- docs/admin/deployment.md
- docs/admin/pool_operations.md
- docs/release/updating.md
- mkdocs.yml
clarify updating command
Doc-only: true
> DAOS-11242 doc: clarify updating command

- docs/admin/administration.md
- docs/release/updating.md
- mkdocs.yml
clarify updating command
Doc-only: true
> DAOS-11242 doc: clarify updating command (#10103)

- docs/release/release_notes_v2_2.md
draft release notes for 2.2.0
Doc-only: true
> DAOS-9355 doc: release notes for 2.2.0

- src/tests/ftest/cart/common.h
- src/tests/ftest/cart/threaded_server.c
CID 105861: Check return value of pthread_create
> DAOS-11527 tests: Check return value in cart test

- src/common/tests_dmg_helpers.c
Logging in the child process after a fork() was causing an intermittent segfault.
> DAOS-11434 test: Fix segfault in dmg test helper (#10140)

- src/tests/ftest/daos_test/dfuse.py
- src/tests/ftest/daos_test/dfuse.yaml
- src/tests/suite/dfuse_test.c
Test-tag: dfuse_unit
Fix return code handling in dfuse_unit
> DAOS-11530 test: fix dfuse_unit return code

- src/cart/crt_iv.c
- src/container/oid_iv.c
- src/object/cli_obj.c
- src/object/srv_ec_aggregate.c
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
- src/rebuild/rebuild_iv.c
- src/rebuild/scan.c
- src/tests/suite/daos_obj_ec.c
> DAOS-11423 ec: enable EC parity rotation

- debian/changelog
- utils/rpms/daos.spec
> DAOS-623 build: Fix date in rpm log

- src/client/dfs/dfs_internal.c
- src/include/daos_fs.h
> DAOS-11606 dfs: fix init and fini declaration

- src/vos/vos_dtx.c
Mainly include the followings:
1. If the DTX entry is not committable, then do NOT return -DER_INPROGRESS when DTX refresh on it.
2. For stand-alone read, ignore non-prepared DTX in spite of it is on the leader or not.
> DAOS-11602 vos: fix some DTX visibility issues

- src/tests/ftest/ior/hard_rebuild.py
Test-tag: test_ec_ior_hard_online_rebuild
> DAOS-10659 test: Remove extra container created by ior/hard_rebuild.py

- src/cart/crt_context.c
- src/cart/crt_group.c
- src/tests/ftest/cart/no_pmix_multi_ctx.c
Fix race condition in cart during context creation
> DAOS-11613 cart: Fix race condition

- src/tests/ftest/nvme/io_verification.py
Test-tag: nvme_io_verification nvme_server_restart Test-repeat: 3
Updated the test case to use the container label based on developer's recommendation.
Signed-off-by: rpadma2 ravindran.padmanabhan@intel.com
> DAOS-10919 test: Fix io_verification tests (use container label) (#10095)

- src/vos/tests/vos_cmd.c
CIDs 449963, 449965, 449965, 449966, 449967
Write to pointer after free, use of 32-bit time, and unchecked return values
> DAOS-11660 tests: Address coverity issues in new VOS test

- src/object/obj_class.c
> DAOS-11419 object: handle S object classes when grp_nr is not predefined

- utils/build.config
> DAOS-11467 mercury: Fix end point creation in the UCX adapter.

- ci/codespell.ignores
- utils/cq/words.dict
> Fix pylint/codespell spam

- src/tests/suite/daos_obj_array.c
> DAOS-11613 test: reproducer for multi EQ / multi thread issue

- src/common/policy.c
- src/tests/suite/daos_checksum.c
- utils/docker/Dockerfile.leap.15
This code was a while loop written using a for loop so
correct code and avoid compile error.
> DAOS-623 common: Fix for/while loop in common/policy.

- src/control/lib/daos/status.go
- src/control/server/mgmt_pool.go
> DAOS-11636 control: don't set pool destroy state if service not up

- src/bio/bio_wal.h
- src/include/daos_srv/bio.h
Defined Meta & WAL blob header, WAL durable formats, Opaque bio_mc_context, BIO meta context management APIs.
> DAOS-11400 bio: Meta & WAL layout

- SConstruct
> DAOS-623 build: move the stdatomic.h check after sconslocal.rc is read

- .github/workflows/landing-builds.yml
- src/cart/crt_hg.c
- src/include/gurt/common.h
- src/object/obj_tx.c
- src/tests/suite/daos_nvme_recovery.c
This caused a number of compile warnings so rework code to avoid
these.
> DAOS-623 engine: Change D_FREE not to log NULL.

- ci/provisioning/post_provision_config_common_functions.sh
- src/cart/crt_hg.c
> DAOS-11688 mercury: Fix 2.2 build to select correct mercury-ucx RPM.

- src/object/srv_obj.c
Features: rebuild pool_create_all_one_hw create_max_pool_scm_only
> DAOS-11601 object: refine daos_recx_ep_list_set

- Jenkinsfile
Add CI_PR_REPOS and CI_BUILD_DESCRIPTION build parameters.
changes.
PRs.
addressed.
> DAOS-11842 ci: Update build parameter options

- src/tests/ftest/harness/config.py
Test-tag: harness_config
changes.
PRs.
addressed.
> DAOS-623 test: fix spelling error

- src/container/container_iv.c
- src/container/oid_iv.c
- src/engine/server_iv.c
- src/include/daos_srv/iv.h
- src/pool/srv_iv.c
- src/rebuild/rebuild_iv.c
Change void** to void* for ivc_on_put().
> DAOS-11678 iv: fix in ivc_on_put()

- src/rebuild/srv.c
Missing riv_sync setting for rebuild status sync
changes.
PRs.
addressed.
> DAOS-11655 rebuild: missing riv_sync

- src/control/server/storage/bdev.go
- src/control/server/storage/config.go
- src/control/server/storage/config_test.go
- src/control/server/storage/faults.go
- src/include/daos_srv/control.h
- utils/config/daos_server.yml
To improve consistency with references elsewhere in the code base,
rename MD-on-SSD role assignments from wal/index/data to
wal/meta/data.
changes.
PRs.
addressed.
> DAOS-11391 control: Rename Index SSD role assignment to Meta

- src/container/srv_container.c
- src/include/daos_prop.h
- src/pool/srv_layout.c
- src/pool/srv_layout.h
- src/pool/srv_pool.c
When checksum scrubbing landed, it did not add the new properties to the pool upgrade path. This patch fixes it so that a pool that was created with 2.2 is able to be upgraded to a version with scrubbing included.
Also did some minor renaming to make scrubbing RDB key consistent.
changes.
PRs.
addressed. …
> DAOS-11145 csum: Scrubbing Upgrade Fix

- src/include/daos_srv/vos.h
- src/vos/tests/vts_io.c
- src/vos/tests/vts_io.h
- src/vos/vos_obj.c
Customer requested ability to set the anchor manually.  Using an RPC with this API should make that possible.
changes.
PRs.
addressed.
> DAOS-11829 vos: Add a vos API to set the anchor from a key

- src/tests/suite/daos_rebuild.c
Instead of creating another new pool in test, let's wait for the original pool to rebuild.
changes.
PRs.
addressed.
> DAOS-11178 tests: wait correct pool during rebuild test

- .github/pull_request_template.md
> DAOS-623 ci: Minor edits for checklists

- src/object/cli_shard.c
Add Assertion for reasb_req check in dc_obj_shard_rw()
changes.
PRs.
addressed.
> DAOS-11597 object: coverity fix

- src/common/tse.c
- src/container/srv_container.c
- src/container/srv_target.c
And fix a bug in tse_task_reinit_with_delay().
> DAOS-11502 container: add cont uuid RF broken log msg

- src/client/pydaos/raw/daos_cref.py
pydaos AsyncWorker1() method uses an extraneous/unnecessary DaosEvent() instance than the one already created/passed by callers.
This patch enables usage of original/caller's DaosEvent() instance, like in AsyncWorker2().
changes.
PRs.
addressed.
it to create a …
> DAOS-11882 pydaos: AsyncWorker1() should use passed DaosEvent()

- docs/admin/vmd.md
- docs/release/release_notes_v2_2.md
document basic VMD support in DAOS 2.2
Doc-only: true
> DAOS-9355 doc: document VMD support

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
fixes to QSG setup guides (rhel and suse)
Doc-only: true
> DAOS-11635 doc: fixes to QSG setup guide

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
- docs/QSG/tour.md
- docs/testing/datamover.md
- docs/testing/ior.md
misc doc improvements
Doc-only: true
> DAOS-11634 doc: misc doc improvements

- src/vea/tests/vea_stress.c
> DAOS-623 vea: fix spelling

- src/client/java/hadoop-daos/src/main/resources/core-site-daos-ref.xml
- src/common/tests/compress_timing.c
- src/control/events/ras_test.go
- src/control/lib/dlopen/dlopen.go
- src/control/lib/dlopen/dlopen_example.go
- src/control/lib/dlopen/dlopen_test.go
src/client/java/hadoop-daos/src/main/resources/core-site-daos-ref.xml src/common/tests/compress_timing.c
src/control/events/ras_test.go
src/control/lib/dlopen/dlopen_example.go
src/control/lib/dlopen/dlopen.go
src/control/lib/dlopen/dlopen_test.go
DAOS is currently licensed under BSD-2-Clause-Patent.
> DAOS-11937 license: change license info from Apache to BSD-2 in 6 files

- src/utils/daos_hdlr.c
Test-tag: daos_fs_copy
Don't try to create the root - assume it always exists.
> DAOS-623 utils: daos fs copy: don't try to create root

- src/client/dfs/dfs.c
- src/control/cmd/daos/container.go
- utils/node_local_test.py
- update the daos tool to add dir_oclass and hints in query
- also return the dir oclass on get-attr for directories
> DAOS-11026 dfs: update daos tool output for dir_oclass and add nlt tests

- docs/admin/vmd.md
cherry-pick v2.2 VMD documentation
Doc-only: true
> DAOS-9355 doc: document VMD support (#10573)

- docs/admin/hardware.md
fix ucx link typo
Doc-only: true
> DAOS-11462 doc: fix typo

- src/tests/ftest/osa/offline_parallel_test.yaml
Test-tag: test_osa_offline_parallel_test_oclass
Test-repeat: 3
> DAOS-11292 test: Fix the oclass S1 to RP_2GX.

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/tests/ad_mem_tests.c
- src/include/daos_srv/ad_mem.h
- arena ID is alloated from bitmap instead of using incremental value
- remove transaction handle from arena registration API
- fix for non-pow2 aligned allocation
- add test for arena registration
- add test for invalid size allocation
> DAOS-11605 common: arena registration test

- src/vos/evtree.c
- src/vos/tests/evt_ctl.c
- src/vos/tests/evt_stress.py
- src/vos/vos_common.c
- utils/run_test.sh
Modify default sort to use even split if the tree is too deep. Otherwise, some I/O patterns can cause a segfault due to the depth exceeding the EVT_TRACE_MAX
Rename ssof to soff for consistency
> DAOS-11894 vos: Avoid segfault due to default evtree sort policy (#10618 and #10552)

- src/include/daos_srv/pool.h
- src/include/daos_srv/rebuild.h
- src/pool/srv_pool.c
- src/rebuild/rebuild_internal.h
- src/rebuild/scan.c
- src/rebuild/srv.c
Abort the stale rebuild job once it receive the
rebuild job with higher rebuild generation.
Generate rebuild version until rebuild_leader_start(), so later rebuild job will always have the higher generation, to avoid retry job might have the same generation number.
> DAOS-11383 rebuild: abort the stale rebuild job (#9999)

- Jenkinsfile
- src/tests/ftest/launch.py
- utils/githooks/pre-commit.d/20-flake.sh
- utils/rpms/daos.spec
On Leap 15.
Fix up a githook.
When resolving debuginfo files, recognize that argobots is libabt0 on SUSE.
Exporting commit pragmas into the environment for processing by pipeline-lib.
> DAOS-11764 build: Enable debuginfo sub-packages... (#10592)

- src/control/lib/daos/system_prop.go
- src/control/lib/daos/system_prop_test.go
Provide a type-safe way to work with signed integer property
values (up to int64).
> DAOS-10633 control: Add IntPropVal type to system properties

- src/tests/ftest/pool/create_capacity.yaml
> DAOS-11945 tests: Increase timeout of create_capacity.py

- src/tests/ftest/pool/create_all_vm.yaml
- src/tests/ftest/util/server_utils_params.py
> Disable tmpfs hugepages for create_all_vm.py

- src/tests/ftest/control/config_generate_run.py
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/command_utils_base.py
- src/tests/ftest/util/server_utils.py
- src/tests/ftest/util/server_utils_params.py
Resolving calling reset_yaml_data_updated() by the control/config_generate_run.py test.
Test-tag: config_generate_run
> DAOS-11946 test: Fix control/config_generate_run.py error

- src/tests/ftest/util/ior_test_base.py
Test-tag: pr,ior,vm
Remove unused ior threading functions.
> DAOS-623 test: remove dead ior_test_base code

- src/bio/bio_wal.c
- src/include/daos_srv/bio.h
Implemented repaly & checkpoint APIs, also bio_wal_flush_header()
is exported so that caller could do header flush explicitly.
- bio_meta_readv() & bio_meta_writev()
These two I/O functions used by caller to load & flush meta pages.
- bio_wal_replay()
Called on post-crash recovery to replay committed (but not checkpointed)
transactions into tmpfs. This function assumes the whole meta blob
has ready being loaded to tmpfs.
- bio_wal_ckp_start()
Called before starting a checkpoint, caller doesn't have to checkpoint
to the highest committed tx ID returned by this function.
- bio_wal_ckp_end()
Called after checkpointing to reclaim WAL space, caller needs to specify
the highest transaction ID checkpointed to.
- bio_wal_flush_header()
Explicitly flush WAL header. One use case of …
> DAOS-11408 bio: WAL APIs for replay & checkpoint

- src/bio/bio_buffer.c
- src/bio/bio_context.c
- src/bio/bio_internal.h
- src/bio/bio_wal.c
- src/bio/bio_xstream.c
- src/common/SConscript
- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
- src/common/btree_class.c
- src/common/mem.c
- src/common/tests/SConscript
- src/include/daos/mem.h
- src/include/daos_srv/ad_mem.h
- src/include/daos_srv/bio.h
- src/vea/vea_alloc.c
- src/vea/vea_api.c
- src/vea/vea_free.c
- src/vea/vea_hint.c
- src/vos/vos_aggregate.c
- src/vos/vos_gc.c
- src/vos/vos_io.c
Initial integrate ADMEM with umem.
With some umem API changes -
Add umem_tx_act_nr/_act_payload_sz/_act_first/_act_next APIs, and related umm_ops.
Add definition of "struct umem_tx", in AD TX implementation can use TLS to cache a umem_tx pointer similar as PMDK. but need to take out umem_tx and reset TLS' tx pointer before calling bio_wal_commit() as it possibly yield.
Change umem_tx_none() and umem_tx_inprogress() to add umm argument.
> DAOS-11605 common: provide umem_ops_t table for ADMEM

- src/object/cli_obj.c
- src/object/obj_verify.c
- src/object/srv_obj.c
That will be helpful for log collection.
> DAOS-11870 object: log data inconsistency as D_WARN

- src/tests/ftest/scripts/main.sh
When testing saok in CI, enable slurm on hardware stages only
changes.
PRs.
addressed.
> DAOS-11639 test: Do not install slurm on VM stage (#10428)

- src/control/server/engine/exec_test.go
Fixes two intermittent issues seen while running this
unit test suite:
* Ensure that the context is not canceled before the
child test process starts
* Don't regenerate the fake daos_engine binary if
it already exists
> DAOS-11959 control: Improve server/engine unit tests (#10682)

- src/cart/crt_init.c
- src/cart/utils/crt_utils.c
- src/utils/self_test/self_test.c
- Fixed init bug that left mutex held after bad cart init, resulting in extra errors on exit
- self_test: default msg sizes are now set to "0,0" "0 b1048578" "b1048578 0"
- self_test: default group set to 'daos_server', default inflight = 16, default repetitions = 100k
- self_test: default endpoint now set to 0:2 to match performance tuning guide settings
- Running self_test without any arguments now starts it with defaults
- self_test: will print now warning if starting in non-agent mode, along with the location of expected attach info file.
- D_INFO prints added to crtu (cart utils lib), to print msg any time envariable is setenv-ed by the code
- D_INFO prints added to crtu during rank/uri population
- Few misc self-test cleanups to handle errors better
Signed-off-by: Alexander A …
> DAOS-11917 cart: Self-test improvements

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
fixes to QSG setup guides (rhel and suse)
Doc-only: true
> DAOS-11635 doc: fixes to QSG setup guide (#10582)

- src/chk/chk_common.c
- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_iv.c
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/chk/chk_srv.c
- src/chk/chk_upcall.c
- src/chk/chk_vos.c
- src/container/srv_container.c
- src/engine/drpc_ras.c
- src/include/daos_srv/pool.h
- src/pool/srv_pool.c
- src/pool/srv_pool_check.c
- src/vos/vos_obj.c
The patch combines the following patches together:
1. https://github.com/daos-stack/daos/pull/10648
2. https://github.com/daos-stack/daos/pull/10588
3. https://github.com/daos-stack/daos/pull/10598
4. https://github.com/daos-stack/daos/pull/10651
5. https://github.com/daos-stack/daos/pull/10702
6. https://github.com/daos-stack/daos/pull/10703
7. https://github.com/daos-stack/daos/pull/10704
8. https://github.com/daos-stack/daos/pull/10713
> DAOS-11876 chk: misc patch for chk related fixes

- src/client/dfs/duns.c
To avoid the memory leak for dir in duns_create_path in src/client/dfs/duns.c.
> DAOS-12000 client: fix a coverity issue

- src/tests/ftest/aggregation/multiple_pool_cont.py
- src/tests/ftest/deployment/network_failure.py
- src/tests/ftest/deployment/target_failure.py
- src/tests/ftest/ior/intercept_verify_data_integrity.py
- src/tests/ftest/nvme/enospace.py
- src/tests/ftest/nvme/fragmentation.py
- src/tests/ftest/nvme/pool_capacity.py
- src/tests/ftest/util/ior_test_base.py
Test-tag: snapshot_aggregation multipoolparallelio test_ior_intercept_messages nvme_io_verification nvme_server_restart nvme_io datamover,pr datamover,daily_regression ior,pr ior,daily_regression osa,pr osa,daily_regression Skip-unit-tests: true
Don't hardcode Mpirun and mpich in ior_test_base.py, since get_job_manager() uses those as defaults anyway.
> DAOS-11999 test: adjust ior_test_base to use mpi_type from yaml

- docs/user/spark.md
added "Run Terasort in HiBench" in spark doc
Signed-off-by: Jifu Zhang <jiafu.zhang@intel.com>
> DAOS-11336 spark: Improve Hadoop/Spark Documentation for 2.2

- docs/index.md
- docs/release/release_notes.md
- docs/release/support_matrix.md
last-minute doc changes for 2.2 GA
Doc-only: true
> DAOS-9355 doc: last-minute doc changes for 2.2 GA

- src/dtx/dtx_rpc.c
During DTX resync, if non-leader is excluded, handle it as 'prepared'. If other non-leaders are also 'prepared' then related DTX maybe still committable or 'corrupted'. The subsequent DTX resync logic will handle related things, see dtx_verify_groups().
More fixes:
1. "-DER_INPROGRESS" for DTX RPC reply is normal, not error.
2. DTX RPC should not skip the in-drain target.
> DAOS-11828 dtx: handle excluded participant as prepared when DTX resync

- src/object/obj_rpc.c
- src/object/obj_rpc.h
- src/object/obj_tx.c
- src/object/srv_internal.h
- src/object/srv_obj.c
- src/object/srv_obj_remote.c
A distributed transaction may touch a lot of DAOS targets and keys, that may cause related CPD RPC body exceeds DAOS_BULK_LIMIT. Under such case, we need to explicitly handle the large CPD RPC body via bulk data transfer instead of some kind of CaRT internal bulk that may be unreliable.
> DAOS-11679 dtx: bulk transfer for large CPD RPC body

- site_scons/daos_build.py
Update return type to return env properly.
> DAOS-623 build: Fix scons build when MPI_PKG is used.

- src/tests/ftest/pool/autotest.yaml
Since DAOS-10884 an explicit error is raised when dmf command is used with the two options --size and --tier-ratio.
> DAOS-11989 test: dmg --size may not be mixed with --tier-ratio

- src/control/common/proto/mgmt/addons.go
- src/control/lib/control/cont.go
- src/control/lib/control/event.go
- src/control/lib/control/pool.go
- src/control/lib/control/pool_acl.go
- src/control/lib/control/response.go
- src/control/lib/control/rpc.go
- src/control/lib/control/system.go
Reduce some spam while improving response flow logging.
Eliminate boilerplate for control request/response logging.
> DAOS-11997 control: Improve control lib debug logging (#10722)

- src/bio/bio_buffer.c
- src/bio/bio_internal.h
- src/bio/bio_monitor.c
- src/bio/bio_recovery.c
- src/bio/bio_xstream.c
- src/include/daos_errno.h
- src/object/cli_obj.c
- src/object/obj_internal.h
Introduce retry-able error DER_NVME_IO, once a fetch request hits NVMe I/O error when reading from SSD, this -DER_NVME_IO will be returned to client, then the client will use the same mechanism for -DER_CSUM error to retry fetch from replicas (if any).
This patch also includes code changes for auto SSD faulty detection, the auto faulty feature is disabled by default now, once it's enabled, -DER_NVME_IO will be returned for NVMe write as well, then client won't fail the I/O but keep retry until the SSD is marked as faulty and the affected target being marked as DOWN.
> DAOS-4713 bio: introduce retry-able DER_NVME_IO (#10589)

- src/tests/ftest/pool/create_all_vm.py
Fix bug with the test of the create_all_vm ftest.
Test-tag: pr pool_create_all_recycle_vm
> DAOS-11974 test: Wrong assertion failure in create_all_vm.py

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
- src/common/tests/ad_mem_tests.c
- src/include/daos/mem.h
- src/include/daos_srv/ad_mem.h
Generate tx_add redo actions for -
1) tx_add/tx_add_ptr, or tx_xadd without UMEM_FLAG_NO_FLUSH flag
2) tx alloc without UMEM_FLAG_NO_FLUSH flag
Suppose the #ranges is not large, so use a simple linked list for it.
> DAOS-11605 common: generate tx_add redo acts

- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/include/daos_srv/daos_mgmt_srv.h
- src/mgmt/srv_pool.c
- src/pool/srv_pool_check.c
It contains the following:
1. Even if the engine is not part of the pool service, it still needs to report the daos targets status to the check leader.
2. Replace ds_mgmt_tgt_pool_destroy with ds_mgmt_tgt_pool_destroy_ranks.
3. Some ranks may have no pools for current check instance, so the
check leader should not wait them to complete, instead, as long
as the required pools have been checked (in spite of succeed or
failed), current check instance will be regarded as done.  
> DAOS-11538 chk: misc fixes for chk related issues - III

- src/tests/ftest/deployment/disk_failure.py
- src/tests/ftest/deployment/disk_failure.yaml
- src/tests/ftest/util/dmg_utils.py
- src/tests/ftest/util/dmg_utils_base.py
- src/tests/ftest/util/osa_utils.py
This is a manual test case to induce NVME faults and bring the NVME disks back to NORMAL state. Target (disk) faults are induced during IOR write. This causes disk eviction and rebuild is triggered due to target eviction. The evicted targets are brought back to normal state and reintegrated with the rank. IOR read is performed on the same container for any data loss. Finally, daos container check run to verify data integrity errors.
> DAOS-11284 test: Disk Failure Testing. (#10468)

- debian/changelog
- utils/build.config
- utils/rpms/daos.spec
> DAOS-11467 mercury: Set release 2.2 to use latest mercury and UCX 1.13.

- Jenkinsfile
> DAOS-12008 ci: Fix missing whitespace

- .github/workflows/pr-metadata.yml
- ci/jira_query.py
Add swim, tools and csum to valid components.
Fetch PR metadata via API.  This allows the code to have much
more data available and removes some complexity.
> DAOS-7821 cq: Add new valid components in commit checking.

- src/vos/tests/vts_mvcc.c
- src/vos/vos_common.c
- src/vos/vos_internal.h
- src/vos/vos_obj.c
- utils/run_test.sh
Allows us to set DAOS_DKEY_PUNCH_PROPAGATE=1 to enable propagation to object level on dkey punch.
> DAOS-623 vos: Add tunable for dkey punch propagation

- src/bio/bio_buffer.c
- src/bio/bio_context.c
- src/bio/bio_internal.h
- src/bio/bio_wal.c
- src/bio/bio_xstream.c
- src/bio/smd/smd_store.c
- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
- src/common/mem.c
- src/common/tests/ad_mem_tests.c
- src/common/tests/utest_common.c
- src/include/daos/mem.h
- src/include/daos_srv/ad_mem.h
- src/include/daos_srv/bio.h
- src/include/daos_srv/vos.h
- src/mgmt/srv_target.c
- src/vea/tests/vea_stress.c
- src/vea/tests/vea_ut.c
- src/vos/sys_db.c
- src/vos/vos_aggregate.c
- src/vos/vos_internal.h
- src/vos/vos_io.c
- src/vos/vos_obj.c
- src/vos/vos_pool.c
- src/vos/vos_pool_scrub.c
- Make umem_pool consists of two parts: umem_store and private allocator handle for AD, BMEM or PMEM. The umem_store will be used by AD and BMEM to access the BIO meta context and WAL function table. For PMEM, the umem_store provides only the data blob I/O context.
- Create/open BIO meta context and pass the prepared umem_store to umempobj_create/open(). A dummy data blob I/O context is introduced to unify the BIO meta context create/open logic for both md on SSD and SCM (with or without NVMe conigured) cases.
- Rename umem_tx to umem_wal_tx and remove umem_instance from it. The umem_wal_tx could be required by some transactions when umem_instance isn't ready yet. (like the transactions on umem pool creation).
- Small fixes and minor cleanup for bio_mc_create/open/close(). …
> DAOS-11885 bio: prepare umem_store

- src/tests/ftest/telemetry/telemetry_pool_metrics.py
- src/tests/ftest/telemetry/telemetry_pool_metrics.yaml
- src/tests/ftest/util/telemetry_utils.py
Fix telemtry functional tests which was failing on invalid telemetry output size.  Some new metadata, such as mtime, have been added since this test was design and which could explain those failures. Also remove some useless threshold percent.
> DAOS-10818 test: fix telemetry expected values

- site_scons/components/__init__.py
Remove unnecessary --with-rdma configure option.
PR-repos: spdk@PR-51
> DAOS-11868 build: Remove --with-rdma configure option from SPDK build

- src/pool/srv_pool.c
Fix double free for extend failure case in
pool_svc_update_map_internal()
> DAOS-12044 pool: double free in pool_map_svc_update extend case

- src/client/dfs/dfs.c
- src/common/prop.c
- src/tests/ftest/datamover/dst_create.py
- src/tests/ftest/datamover/negative.py
- src/tests/ftest/datamover/obj_large_posix.py
- src/tests/ftest/datamover/obj_small.py
- src/tests/ftest/datamover/posix_preserve_props.py
- src/tests/ftest/datamover/posix_types.py
- src/tests/ftest/datamover/posix_types.yaml
- src/tests/ftest/datamover/serial_large_posix.py
- src/tests/ftest/datamover/serial_small.py
- src/tests/ftest/util/data_mover_test_base.py
- src/tests/ftest/util/duns_utils.py
- src/tests/ftest/util/ior_utils.py
- src/tests/ftest/util/test_utils_container.py
- src/utils/daos_hdlr.c
- utils/node_local_test.py
Test-tag: pr datamover
- Fix incorrect handling of user-provided container label when creating a new container for fs copy and cont clone
- Add datamover test cases that use labels to verify this
- Refactor some datamover test cases
> DAOS-11224 datamover: accept user container label (#10023)

- src/object/obj_class.c
dc_set_oclass set the obj class possibly cause grp size exceed domain_nr, this patch is to fix it.
> DAOS-12041 object: dc_set_oclass should consider small domain_nr

- src/common/ad_mem.c
- src/common/tests/ad_mem_tests.c
- src/include/daos_srv/ad_mem.h
. group add and remove share the same functions
. Because BIO has changed code and does not require umem as
intialization parameter:
- merge blob_prep_create() and blob_post_create() to blob_create
- merge blob_prep_open() and blob_post_open() to blob_open
> DAOS-11605 common: reorg a few functions

- src/tests/ftest/container/auto_oc_selection.py
- src/tests/ftest/util/daos_utils.py
- src/tests/ftest/util/daos_utils_base.py
- src/tests/ftest/util/test_utils_container.py
- utils/ansible/ftest/templates/daos-launch.sh.j2
Update ftest to check new `--dir_oclass` option of the `daos container create` command.
Update ansible ftest script to allow using _launch-ftest.sh_ with _git bisect_
> DAOS-11907 test: Container create succeeded with invalid RF-OC pair

- src/vos/vos_common.c
master-commit: 6b1aa37e90cdfe9fe870841987616316f71e6ec2
For a distributed transaction with multiple update/punch against the same akey, some reserved nvme area may be released internally. These area is recorded via dth->dth_deferred_nvme. In spite of whether the transaction is committed or aborted finally, we both need to cancel these area to avoid space leak.
> DAOS-12020 vos: cancel deferred nvme list unconditionally

- src/cart/crt_context.c
- Minor style fixes and proper return code
> DAOS-11977 cart: Cleanup

- src/cart/crt_context.c
- src/cart/crt_hg.c
- UCX does not have local address for clients causing failures during context creation.
> DAOS-12115 cart: Fix UCX client startup

- src/bio/bio_context.c
- src/bio/bio_internal.h
- src/bio/bio_recovery.c
- src/bio/bio_wal.c
- src/bio/bio_wal.h
- src/bio/smd/smd_pool.c
- src/engine/init.c
- src/engine/srv.c
- src/include/daos_srv/bio.h
- src/include/daos_srv/smd.h
- src/include/daos_srv/vos_types.h
- src/rdb/rdb.c
- src/vos/vos_internal.h
- src/vos/vos_pool.c
1. Skip WAL commit for sysdb temporarily until we figure out a good solution for the sysdb sharing issue.
2. Store SMD pool table for RDB pools separately, otherwise, the RDB pool ID will be conflicting with the regular pool ID.
3. Avoid passing zero meta size to bio_mc_create() when creating pool with existing pool file.
4. In bio_blob_create(), the ABT eventual needs be reset before reusing.
5. In dss_srv_handler(), set dmi_xstream before initializing the sysdb.
> DAOS-11885 bio: various bug fixes

- src/common/ad_mem.c
- src/common/ad_tx.c
- src/common/tests/ad_mem_tests.c
- fix a bug in find_bits
- ad_alloc() should check UMEM_FLAG_ZERO and memset for it
- change tx_perf to emulate the real case
> DAOS_11605 ad_mem: fix a bug in find_bits

- src/bio/bio_xstream.c
- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
- src/common/mem.c
- src/include/daos_srv/ad_mem.h
1. DAOS_MD_ON_SSD ENV set as 0 for PMEM, 1 for BMEM, 2 for ADMEM.
2. Hook with umempobj_create/_open/_close/_get_heapusage etc.
3. Add ad_root()/add_base() API to support umempobj_get_rootptr()/query base,
reserve another 32KB in arena 0, and limit root obj size as 32KB.
4. create blob file and fallocate space
5. Fix ad mem internal tx handling, and several other bug fixing
> DAOS-11605 common: fill gap between admem and umem

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
Add tls cache to reuse ad_act and tx memory.
TX rate (tested by ad_mem_tests) improved from about 170K to 220K.
> DAOS-11605 common: reuse act and tx memory

- src/rebuild/srv.c
Let's search the adjacet rebuild job to merge
the targets in case there are multiple interleave
rebuild jobs queued in the rebuild queue.
> DAOS-11064 rebuild: search the right targets to merge

- src/common/ad_mem.c
- Fix a bug in group search by (unit size && weight)
- Remove unnecessary "goto" statement
> DAOS-11605 ad_mem: fix a bug for group search

- docs/QSG/build_from_scratch.md
when building from scratch, make sure to clone the correct branch
Doc-only: true
> DAOS-9355 doc: git clone the specific branch

- src/client/ds3/SConscript
Fix merge conflict with 6711cc9cb15d73447972c0f000c8a0f30bb962db.
> DAOS-12175 ds3: fix build issue

- src/container/cli.c
- src/object/obj_tx.c
- src/pool/cli.c
To avoid the pool map being updated during access.
> DAOS-12113 pool: hold dp_map_lock when access pool map

- Jenkinsfile
Remove time trigger for soak-testing branch for now
> DAOS-12159 test: Remove time trigger from Jenkinsfile

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removes the now unused Functional Hardware Small stage.
> DAOS-12083 test: Removing HW Small stage.

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removes the now unused Functional Hardware Small stage.
> DAOS-12088 test: Removing HW Small stage.

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removed the now unused Functional Hardware Small stage.
> DAOS-12084 test: Removing HW Small stage

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removed the now unused Functional Hardware Small stage.
> DAOS-12089 test: Removing HW Small stage

- Jenkinsfile
In conjunction with moving all functional tests tagged to run on the Functional Hardware Small stage to now run on the Functional Hardware Medium or Large stages, this PR removed the now unused Functional Hardware Small stage.
> DAOS-12085 test: Removing HW Small stage

- src/object/srv_obj.c
When bulk transfer is over secondary provider, the bulk completion is called on secondary xstream and the bulk transfer waiter is on primary xstream, so in the obj_bulk_inflights() (which is called in the bulk completion), we shouldn't access the completion argument (which could have been freed by the waiter) after wakeup waiter.
> DAOS-12111 object: fix race in obj_bulk_inflights()

- src/rebuild/scan.c
missing reset id_shard for local rebuild case.
> DAOS-12149 rebuild: missing set id_shard

- utils/githooks/pre-commit.d/40-gofmt.sh
Require that any changes to .go files be run through
gofmt before creating a PR.
> DAOS-7821 build: Add a gofmt githook

- src/object/cli_obj.c
During EC object enumeration, kds and recxs over each sub anchor may need reallocate, if the number is changed.
> DAOS-12063 object: reset kds and recxs for each shard (#10834)

- src/rebuild/srv.c
Keep "reclaim fail" operation unchanged if it needs to retry.
> DAOS-12112 rebuild: keep reclaim op unchanged

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
- src/common/tests/ad_mem_tests.c
- src/include/daos_srv/ad_mem.h
- space counter taken by reserve() should be released on transaction abort
- code cleanup
> DAOS-11605 ad_mem: fix a bug in free space tracking

- docs/admin/deployment.md
- utils/config/daos_server.yml
- utils/config/examples/daos_server_mdonssd.yml
Add an example configuration file called daos_server_mdonssd.yml to help explain the MD on SSD feature and new bdev_roles list for NVMe engine storage tiers.
Add description of using class ram plus scm_size with class nvme plus bdev_roles in deployment.md, but don't give an example there.
Update the brief description of the new tier property in sample daos_server.yml.
> DAOS-12060 doc: Describe daos_server.yml changes for MD on SSD

- src/client/java/daos-java/src/main/java/io/daos/DaosClient.java
- src/client/java/daos-java/src/main/java/io/daos/dfs/DaosFsClient.java
- src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSystem.java
change log level from INFO to DEBUG to prevent log being output to console.
> DAOS-12096 Separate hadoop-daos log from hadoop command line output

- src/chk/chk_engine.c
- src/chk/chk_internal.h
- src/chk/chk_leader.c
- src/chk/chk_rpc.c
- src/chk/chk_srv.c
- src/chk/chk_upcall.c
1. Use the same sequence if report an inconsistency multiple times
Continue the fixes in PR#10909, if the first report is for ask for
interaction from non-leader, then the next report after the repair
should reuse the sequence to allow the control plane to locate the
original interaction report.
2. Remove act_msgs from check report upcall
The control plane uses act_details for check query output, that is
more meaningful for the users.
3. Offer pool label and container label for check report upcall
The daos engine will transfer related pool label and the container
label (if applicable) to control plane via check report upcall. It
is more meaningful (than related UUID) for the users.
> DAOS-12145: chk: misc fixes for chk related issues - II

- src/container/cli.c
- src/object/obj_tx.c
- src/pool/cli.c
master-commit: ba09d12d29614c3afb1b2f377205d128255a95ce
To avoid the pool map being updated during access.
> DAOS-12113 pool: hold dp_map_lock when access pool map (#10887)

- utils/rpms/packaging/Dockerfile.mockbuild
- utils/rpms/packaging/Dockerfile.ubuntu.20.04
- utils/rpms/packaging/Makefile_packaging.mk
- utils/rpms/packaging/debian_chrootbuild
- utils/rpms/packaging/rpm_chrootbuild
Builds Ubuntu from Artifactory instead of upstream repos.
Only patches rpmlint if patch is not already applied upstream.
> DAOS-12253 packaging: Update packaging/ subdir

- src/control/lib/hardware/ucx/bindings.go
The DAOS control plane does a dlopen of libucs.so and libuct.so to validate UCX configurations. A recent change to the CI system images resulted in the elimination these files (symbolic links).  Accord to the SRE team, the CI images prior to currently were all in error, and the correct configuration is for these symbolic links to not be present.  Hence, the SRE team has dictated that the control plane code has be change to accommodate this change to the CI installations.
> DAOS-12254 ucx: UCX initialization failing because of change to CI system configuration.

- src/common/dav/out.h
- src/common/dav/tx.c
This fix ensures that all internal data related to dav transaction are cleaned up before invoking WAL reserve/commit calls.
Signed-off-by: sherintg <sherin-t.george@hpe.com>
> DAOS-12058 common: Fixed leaks in BMEM WAL reserve/commit.

- utils/setup_daos_admin.sh
> DAOS-12265 control: Fix SPDK include path symlink for dev setup (#11032)

- src/bio/bio_config.c
- src/bio/bio_device.c
838332 led_device_action needs to return in case of error
838333 ctx should be freed
838334 ctx should be freed
> DAOS-12229 bio: Fixed several coverity issues

- src/gurt/tests/test_gurt.c
- src/include/gurt/list.h
- src/object/cli_obj.c
- src/tests/ftest/deployment/io_sys_admin.py
- src/tests/ftest/util/data_mover_test_base.py
- src/tests/ftest/util/file_count_test_base.py
- src/tests/suite/daos_obj.c
- src/tests/suite/daos_obj_ec.c
Backport of the PR #10008.
This patch mainly fixes an invalid management of EC recx list with converting parity recx to normal recx. A new NLT tests ec_rec_parity_list() has been added to check this. Several fixes and updates have also been done on the functional tests deployment/io_sys_admin.py which initially detected the regression with the EC recx list management.
Test-tag: pr iosysadmin,hw,large
Co-authored-by: Di Wang <di.wang@intel.com>
> DAOS-9218 test: data-mover erasure code support (#10008)

- src/ddb/tests/ddb_commands_print_tests.c
- src/ddb/tests/ddb_parse_tests.c
> update ddb tests for new oid format

- site_scons/site_tools/extra/extra.py
- site_scons/site_tools/go_builder.py
- src/control/cmd/daos/pool.go
- utils/githooks/pre-commit.d/20-flake.sh
- utils/githooks/pre-commit.d/40-gofmt.sh
- utils/githooks/pre-commit.d/40-pylint.sh
> DAOS-623 build: Update the go builder and tweak commit hooks.

- Jenkinsfile
> DAOS-11637 test: Update testing to use Leap 15.4

- src/tests/ftest/ior/crash.py
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/ior_test_base.py
- src/tests/ftest/util/ior_utils.py
- src/tests/ftest/util/server_utils.py
Test-tag: ior,pr test_ior_crash
Increase IOR subprocess pattern_timeout to 60s.
Misc cleanup
> DAOS-11192 test: simplify ior/crash subprocess checking (#10925)

- src/common/misc.c
allow cio_max_expected_size and cio_max_unexpected_size (RPC eager limit) to be set through an environment variable DAOS_RPC_SIZE_LIMIT (if set), instead of hardcoding it to the value of DAOS_RPC_SIZE.
> DAOS-12273 cart: add DAOS_RPC_SIZE_LIMIT

- src/dtx/dtx_common.c
- src/dtx/dtx_internal.h
- src/dtx/dtx_resync.c
- src/dtx/dtx_rpc.c
- src/dtx/dtx_srv.c
- src/include/daos/dtx.h
- src/include/daos_srv/vos.h
- src/include/daos_srv/vos_types.h
- src/object/obj_tx.c
- src/object/srv_obj.c
- src/vos/vos_dtx.c
master-commit: de4da22fc80d681eca265f11736940637806f5ed
Before committing the DTX on remote participants, we cannot remove the active DTX locally; otherwise, the local committed DTX entry may be removed via DTX aggregation before remote participants commit done. Under such case, if some remote DTX participant triggere DTX_REFRESH for such DTX during the interval, then it will get -DER_TX_UNCERTAIN, that may cause related application to be failed. So we let remote participants to commit firstly, if failed, we will ask the leader to retry the commit until all participants got committed.
> DAOS-12091 dtx: commit DTX on remote participants before local

- src/tests/ftest/control/daos_object_query.yaml
- src/tests/ftest/object/create_many_dkeys.yaml
- src/tests/ftest/object/integrity.yaml
Some VM tests specifying 4GiB of tmpfs capacity, and that use almost all of the space (e.g., 128MiB MS allocation, 3GB pool targets, and 1GiB rdb-pool) occasionally encounter DER_NOSPACE when trying to allocate rdb-pool. This was specifically seen intermittently in Leap 15.3 VM functional testing. Increase scm_size to 5GiB in the tests that have encountered the failures.
Test-tag: test_object_query test_invalid_tx_commit_close test_single_object_validation test_array_object_validation test_many_dkeys
> DAOS-12257 test: increase tmpfs scm_size in some tests

- src/common/ad_mem.c
- src/common/ad_mem.h
1. refine find unused grp in arena_reserve_grp()
2. use D_ALLOC_PTR_NZ for ad_operate
3. a few other detailed refine.
> DAOS-11605 common: a few refine for AD mem

- src/tests/ftest/util/verify_perms.py
Test-tag: test_dfuse_mu_perms
Skip-func-test-leap15: False
> DAOS-12298 test: fix verify_perms.py typo and cd

- Jenkinsfile
Add support for the Functional Hardware Medium UCX Provider stage in order to run any 'provider' tagged tests in the ucx provider branches.
Test-tag: test_always_passes_hw test_daos_pool
> DAOS-12021 tests: Add HW Medium UCX Provider stage

- src/common/tests_dmg_helpers.c
- src/include/daos/tests_lib.h
- src/tests/suite/daos_checksum.c
- src/tests/suite/daos_container.c
- src/tests/suite/daos_epoch_io.c
- src/tests/suite/daos_obj.c
- src/tests/suite/daos_pool.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_simple.c
- src/tests/suite/daos_test.h
- src/tests/suite/daos_test_common.c
Add a new-style dmg helper for server/target exclusion.
> DAOS-12277 test: Convert suite to use new-style dmg helpers (#11090)

- Jenkinsfile
Updating Jenkinsfile stages to be in compliance with recent updates.
Test-tag: test_always_passes_hw test_daos_pool
> DAOS-12021 test: Adding missing Jenkinsfile updates.

- utils/docker/vcluster/daos-admin/el8/Dockerfile
- utils/docker/vcluster/daos-client/el8/daos_agent.yml.in
- utils/docker/vcluster/daos-cm.sh
- utils/docker/vcluster/daos-server/el8/daos_server.yml.in
DAOS agent is not properly managing virtual docker interface.
This last one has to be explicitly excluded in the config file.
Doc-only: true
> DAOS-11979 docker: fix daos agent with docker

- src/bio/bio_wal.c
Missed TX header verify for each blocks when tail csum is disabled.
> DAOS-11412 bio: verify tx blocks

- src/common/ad_mem.c
- src/common/tests/ad_mem_tests.c
- add a new test case for performance test
- code cleanup
> DAOS-11605 ad_mem: add another performance test

- src/tests/ftest/deployment/agent_failure.py
- src/tests/ftest/deployment/agent_failure.yaml
Change np to ppn in the config, since the test uses ppn.
Misc robustness updates.
Test-tag: AgentFailure
> DAOS-12307 test: correct np to ppn

- src/tests/ftest/daos_test/dfs.yaml
> DAOS-12192 test: enable IO debug log for dfs parallel

- docs/user/filesystem.md
- src/tests/ftest/dfuse/mu_mount.py
- src/tests/ftest/dfuse/mu_mount.yaml
- src/tests/ftest/util/dfuse_utils.py
- src/tests/ftest/util/test_utils_container.py
Test-tag: pr,dfuse,vm daily_regression,dfuse,vm test_dfuse_mu_mount DaosBuild Skip-unit-tests: true
- Add more negative and positive cases for dfuse mount permissions.
- Add mount_callback to Dfuse.run to be called after mounting.
- Remove bind_cores from Dfuse.run
- Should instead be set before calling run
- Add TestContainer.update_acl
> DAOS-8135 test: dfuse mount permissions

- src/bio/bio_context.c
- src/bio/bio_wal.c
- src/common/dav/dav_iface.c
- src/common/dav/wal_tx.c
- src/common/dav/wal_tx.h
- src/include/daos/mem.h
- src/include/daos_srv/bio.h
- src/vos/tests/vts_common.h
- src/vos/tests/vts_wal.c
- src/vos/vos_pool.c
> Ivanodmi/vos on blob/daos 12217

- mkdocs.yml
> DAOS-9355 doc: mkdocs update

- src/tests/ftest/container/snapshot_aggregation.py
Test-tag: test_snapshot_aggregation
Test-repeat: 3
Call get_info and set_query_data, which is no longer called in some scenarios due to #11118
> DAOS-12326 test: fix snapshot_aggregation space check

- src/tests/ftest/fault_injection/pool.py
> DAOS-12040 test: Error message has changed (#10807)

- src/cart/crt_iv.c
- src/cart/crt_rpc.c
- Release bulk handle early in the process before responding
- Handle bulk transfer error on update
- Perform extra addref/decref for customized rpc handlers (this is done for clarity, handle shouldn't be free-ed even without it)
> DAOS-11678 cart: Handle extra error and early bulk release

- src/pool/srv_pool.c
When a PS leader steps down, it doesn't reset pse_stop to false. If the same PS replica becomes a new PS leader, events_handler will stop immediately after starting, as shown by these log messages:
12/11-06:50:14.89 [...] rdb_raft_step_down() e572b42d[1]: no longer leader of term 1
[...]
12/11-06:50:14.89 [...] events_handler() e572b42d: stopping
[...]
12/11-06:50:30.15 [...] rdb_raft_step_up() e572b42d[1]: became leader of term 3
[...]
12/11-06:50:30.16 [...] events_handler() e572b42d: starting
12/11-06:50:30.16 [...] events_handler() e572b42d: stopping
This patch resets pse_stop in fini_events and asserts that pse_stop must be false in init_events.
> DAOS-12324 pool: Reset pse_stop in fini_events

- src/control/cmd/daos_server/storage_nvme.go
- src/control/cmd/daos_server/storage_scm.go
daos_server nvme|scm prepare|reset commands should not require a
server config file to exist in order to run.
> DAOS-12344 control: nvme and scm cmds run without conf file

- src/tests/ftest/container/boundary.yaml
Commit ca976cc introduced dynamic log_mask DEBUG setting for
every pool create/destroy performed in functional testing.
Some tests such as container/boundary perform a larger number
of pool and container creates than most tests, and in some cases
in parallel. And the tests may also perform io. This scenario can be
problematic if the test uses the default DD_MASK that includes io.
And especially problematic if a pool create/destroy hangs.
With this change, the container/boundary test config is changed
to specify DD_MASK=group_metadata_only (md, mgmt). This preserves
detailed logging for pool creates/destroys, but will not overwhelm
logs with io-related entries.
A future change may modify the functional test code to give an option
for whether to invoke the set-logmasks command before/after …
> DAOS-12160 test: reduce debug logs in container/boundary test

- src/tests/ftest/osa/offline_extend.yaml
Test-tag: test_osa_offline_extend_oclass test_osa_offline_extend_during_aggregation
> DAOS-12242 test: Fix server info for offline extend.

- src/tests/ftest/util/server_utils.py
Test-tag: pr test_config_generate_run
> DAOS-12320 test: AttributeError: 'int' object has no attribute 'split'

- ci/unit/test_nlt_node.sh
- src/client/dfs/duns.c
- src/control/cmd/daos/container.go
- src/control/cmd/daos/pool.go
- src/include/daos_uns.h
- utils/node_local_test.py
Today this is only supported on container creation. This PR adds an option to allow linking a container that already exists in the namespace.
> DAOS-12212 uns: add option to link an existing container in the UNS

- src/vos/vos_dtx.c
When vos aggregation tries to aggregate the data record that is referenced by some non-committed DTX entry, then give some warn messages for help debug.
> DAOS-12278 vos: warning if try to aggregate active modification

- src/tests/ftest/datamover/obj_large_posix.yaml
- src/tests/ftest/datamover/serial_large_posix.yaml
Test-tag: DmvrSerialLargePosix DmvrObjLargePosix
Test-repeat: 3
> DAOS-12322 test: increase test timeout

- src/tests/ftest/scrubber/basic.py
Test and enable the fixes of DAOS-8906
Test-tag: test_scrubber_disabled_during_pool_creation
> DAOS-8906 test: Verify and enable the fixes

- src/tests/ftest/datamover/obj_large_posix.yaml
- src/tests/ftest/datamover/serial_large_posix.yaml
Test-tag: DmvrSerialLargePosix DmvrObjLargePosix
Test-repeat: 3
> DAOS-12322 test: increase test timeout (#11162)

- Jenkinsfile
- ci/provisioning/post_provision_config_nodes.sh
- src/tests/ftest/cart/nopmix_launcher/launcher_one_node.py
- src/tests/ftest/launch.py
- src/tests/ftest/scripts/setup_nodes.sh
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/command_utils_base.py
- src/tests/ftest/util/daos_perf_utils.py
- src/tests/ftest/util/daos_racer_utils.py
- src/tests/ftest/util/ior_utils.py
- src/tests/ftest/util/mdtest_utils.py
- src/tests/ftest/util/pool_security_test_base.py
- src/tests/ftest/util/server_utils.py
- src/tests/ftest/util/server_utils_base.py
Skip-fnbullseye: false
Skip-python-bandit: true
> DAOS-12121 test: Bullseye backports from master branch to rel_2.2

- utils/build.config
> DAOS-11550 build: Add SPDK patch to build with glibc 2.36 (#11185)

- src/include/daos_uns.h
> DAOS-12212 duns: add a clarification on the uns link option

- src/tests/ftest/osa/offline_extend.yaml
Test-tag: test_osa_offline_extend_oclass test_osa_offline_extend_during_aggregation
Fix server info for offline extend.
> DAOS-12242 test: Fix server info for offline extend. (#11176)

- src/client/dfs/dfs.c
- src/include/daos_fs.h
- src/object/cli_shard.c
- src/tests/suite/daos_obj.c
- src/tests/suite/dfs_unit_test.c
- update checker API to allow user to pass directory to store oids under lost+found. If a directory is not passed, then a directory with current timestamp will be created for that.
- before linking a file to l+f, check the largest offset in all dkeys to see if it's larger than the default chunk size. If it is, then change the file chunk size (that is maintained in the directory entry of that file) to that.
> DAOS-12176 dfs: lost+found checker fixes

- src/bio/bio_device.c
> DAOS-12393 bio: Don't log error in LED check if no VMD

- utils/rpms/daos.rpmlintrc
> DAOS-623 build: quiet rpmlint for ddb

- src/object/cli_ec.c
- src/object/srv_obj_migrate.c
Skip invalid object during migrate unpack. Add some debugging information.
> DAOS-11886 object: skip invalid object during migrate unpack (#10645)

- src/bio/bio_context.c
- src/bio/bio_wal.c
- src/include/daos/mem.h
- src/include/daos_srv/bio.h
- src/vos/vos_internal.h
- src/vos/vos_pool.c
Introduced meta flush callbacks:
- so_flush_prep: Reserve DMA buffer and return a flush handle;
- so_flush_copy: Copy page data to reserved DMA buffer;
- so_flush_post: Write meta blob and release buffer;
Checkpoiting will use them to flush back metadata to meta blob, there are few advantages of using such phased flush APIs comparing with using the single so_write call:
- Checkpointing could copy page data to DMA buffer before the data is being committed to WAL, then trigger NVMe write once the WAL commit done, comparing with the approach of calling so_write after page data being committed, "copy before commit" has shorted window of blocking new updates on update starvation;
- It's easier to handle the rarely happened yield on DMA buffer reserving;
- It's easier to utilize DSA to do …
> DAOS-11401 vos: meta flush callbacks

- src/client/dfs/dfs.c
- src/client/dfs/dfs_internal.h
- src/control/cmd/daos/container.go
- src/control/cmd/daos/filesystem.go
- src/control/cmd/daos/flags.go
- src/control/cmd/daos/flags_test.go
- src/include/daos_fs.h
- src/tests/suite/dfs_unit_test.c
- src/utils/SConscript
- src/utils/daos_dfs_hdlr.c
- src/utils/daos_hdlr.h
> DAOS-12169 dfs: Add DAOS filesystem tool option for DFS MWC

- src/client/dfs/dfs.c
- src/client/dfs/dfs_internal.h
- src/utils/daos_dfs_hdlr.c
> DAOS-12169 dfs: fix typo and function name

- utils/githooks/find_base.sh
- utils/githooks/pre-commit.d/20-flake.sh
"set -u" treats unset variables as errors, so use proper default value
> DAOS-623 ci: fix find_base.sh unbound variable

- src/utils/daos_hdlr.c
Have to make sure ca is not NULL before freeing
ca->src and ca->dst in cont_clone_hdlr().
> DAOS-12418 utils: need to make sure ca is not NULL

- src/tests/ftest/container/auto_oc_selection.py
Test-tag: test_oc_selection
The command option is --dir-oclass but the python variable is dir_oclass
> DAOS-12373 test: fix dir-oclass / dir_oclass

- src/control/cmd/daos/container.go
> DAOS-623 tools: container hints short conflicts with help

- src/cart/crt_group.c
- src/cart/crt_internal_fns.h
- src/cart/crt_swim.c
- src/control/system/member.go
- src/engine/init.c
- src/pool/srv_pool.c
A rank may be excluded from the system due to false positive SWIM DEAD events caused by temporary progressing or network issues. Currently, such a rank has no way to detect the exclusion. If it hosts a PS leader, other replicas of this PS cannot become a new leader, while the current PS leader being unable to perform its job due to the stale local primary group. See the Jira ticket for a real occurrence.
This patch introduces a lightweight protocol being piggybacked on SWIM RPCs so that such a rank will eventually detect such an exclusion.
> DAOS-12053 cart: Detect exclusions of self rank (#6307)

- src/cart/crt_context.c
- Remove unneeded put when index is out of bounds
> DAOS-12012 cart: Remove un-needed put

- .github/workflows/ci2.yml
- .github/workflows/landing-builds.yml
Node.js 12 is deprecated and satackey/action-docker-layer-caching is no
longer maintained. Update and switch to jpribyl/action-docker-layer-caching@v0.1.1
Resolves "Node.js 12 actions are deprecated"
> DAOS-623 ci: update GHA action-docker-layer-caching

- src/tests/SConscript
- src/tests/simple_dfs.c
> DAOS-623 dfs: add a simple DFS program

- src/tests/ftest/rebuild/container_rf.py
Verifying if the test passes in release2.2
Test-repeat: 5
Test-tag: test_rebuild_with_container_rf
> DAOS-8827 test: Verifying if the test passes in release2.2

- .github/workflows/ci2.yml
- .github/workflows/create_release.yml
- .github/workflows/doxygen.yml
- .github/workflows/flake.yml
- .github/workflows/landing-builds.yml
- .github/workflows/spelling.yml
Node.js 12 is deprecated and satackey/action-docker-layer-caching is no
longer maintained.
- https://github.com/daos-stack/daos/pull/11265 - Update and switch to jpribyl/action-docker-layer-caching@v0.1.1
- https://github.com/daos-stack/daos/pull/10548 - Update to actions/checkout@v3
Resolves "Node.js 12 actions are deprecated"
> DAOS-623 ci: update GHA action-docker-layer-caching (#11265)

- src/bio/bio_wal.c
- utils/run_test.sh
Missed counting & placing data csum tx entry in WAL.
> DAOS-12214 bio: fix data csum tx entry

- utils/rpms/daos.spec
Fix daos-tests-internal dependency on daos-tests noarch RPM.
> DAOS-12446 build: Fix daos-tests-internal dependency

- docs/user/container.md
- docs/user/filesystem.md
- src/client/dfs/README.md
Replace deprecated rf parameters with rd_fac from the documentation.
> DAOS-11418 doc: replace deprecated rf parameter with rd_fac

- src/object/srv_obj_migrate.c
Let's fail migration if the system is shutdown, instead of keep retrying.
> DAOS-11922 object: fail rebuild during shutdown (#11180)

- site_scons/components/__init__.py
- site_scons/prereq_tools/base.py
Add a check for it in prebuild checks for server.
> DAOS-623 build: Improve error message when lmdb is missing

- src/rebuild/srv.c
Fix an invalid assertion in regenerate_task_internal().
> DAOS-10681 rebuild: fix an invalid assertion

- src/client/ds3/bucket.c
- src/client/ds3/pool.c
coverity fixes in DS3 for ticket DAOS-12377 and DAOS-12376: 709511, 709507, 709504, 709510, 709508, 709506, 709505, 709503
> DAOS-12377 ds3: coverity fixes

- src/tests/ftest/rebuild/container_create_race.yaml
Use -F for IOR in container_create_race to create more objects to make sure the rebuilding will actually migrate objects and records.
Test-tag: rebuild_cont_create
> DAOS-11996 tests: Use -F for IOR in container_create_race

- src/tests/ftest/launch.py
Fixxing an unhandled exception for when launch.py is run with an extra yaml that does not require any placeholder replacements.
Test-tag: pr test_core_files
> DAOS-12502 test: Fix extra yaml unhandled exception

- src/client/dfs/dfs.c
> DAOS-12438 dfs: fix some error return paths

- src/client/pydaos/pydaos_core.py
- src/client/pydaos/pydaos_shim.c
- utils/node_local_test.py
> DAOS-12173 pydaos: add container checker for python containers

- src/bio/bio_monitor.c
> DAOS-12372 bio: pass in dev uuid for bio_get_dev_state_internal

- Jenkinsfile
Collect more detailed data from the running steps starting with runtime of steps.
Signed-off-by: John E. Malmberg <john.e.malmberg@intel.com>
> SRE-1682 Build: Collect more step statistics

- src/common/dav/tx.c
- src/common/dav/wal_tx.c
- src/common/tests/SConscript
- src/common/tests/btree.c
- src/common/tests/btree_direct.c
- src/common/tests/umem_test.c
- src/common/tests/umem_test_bmem.c
- src/common/tests/utest_common.c
- src/common/tests/utest_common.h
- src/vos/tests/evt_ctl.c
- Added test unit tests for all of the umem apis with bmem as the backing interface.
- Addressed bugs in dav_free(), dav atomic apis.
Signed-off-by: sherintg <sherin-t.george@hpe.com>
> DAOS-12443 common: umem unit tests for bmem

- src/control/server/storage/mount/provider.go
The change causes failures when mounting control metadata.
> DAOS-12523 control: Revert mountpoint permissions change

- src/object/srv_internal.h
- src/object/srv_mod.c
- src/object/srv_obj.c
- src/tests/ftest/util/telemetry_utils.py
Add bio metrics to measure BIO latency, so fetch/update
latency will be detailed by VOS_LATENCY + BIO_LATENCY +
BULK_LATENCY.
> DAOS-12426 object: add bio metrics

- src/object/cli_obj.c
- src/object/srv_obj_migrate.c
Reset iov off to 0 if migrate object enumeration
needs to retry.
Add more information and check once memory copy
out of the range.
> DAOS-11964 object: reset the iov off to 0

- src/tests/ftest/util/dfuse_utils.py
- src/tests/ftest/util/run_utils.py
Test-tag: dfuse,-manual volunit
- Detect and unmount "rogue" fuse processes
- Improve logging
- Adjust most dfuse definitions to be private
> DAOS-12144 test: improve dfuse mount checking (#10898)

- src/client/dfs/dfs.c
- src/tests/ftest/datamover/posix_meta_entry.py
- src/tests/suite/dfs_unit_test.c
the mtime update according to the max epoch changes were missed in lookupx.
> DAOS-10258 dfs: lookupx should properly set mtime in stbuf (#11337)

- src/cart/crt_init.c
- Set default envariable settings for CXI provider
> DAOS-12528 cart: Set default envariable settings for CXI

- docs/overview/data_integrity.md
- src/include/daos_srv/vos.h
- src/pool/srv_pool_scrub_ult.c
- src/vos/vos_pool_scrub.c
Made several updates to the checksum scrubber metrics to better align with the requirements defined in SRS-371.
- Removed tree scrub finish time.
- Updated metric descriptions.
- Added ms to next csum and tree scrub. These are helpful for understanding the state of the scrubber.
- Added busy_time to track if not able to scrub because of active IO.
- Updates to the wiki page.
Features: checksum
> DAOS-10753 csum: Checksum Scrubber Metrics Update

- src/control/server/mgmt_pool.go
- src/control/server/mgmt_pool_test.go
Since #11157 landed, there is a possibility that a retried
pool create may encounter a pool that was automatically
promoted to the Ready state. Instead of returning -DER_ALREADY
(which is unhandled and unhelpful) to the dmg side, just
populate the pool create response as if the retried create handler
was responsible for doing it.
> DAOS-12524 control: Return created pool on retry

- src/tests/ftest/launch.py
Replace '.' with '-' so the directory name is correct.
> DAOS-12454 test: fix functional leap 15.4 results name

- docs/admin/vmd.md
> DAOS-12228 docs: Remove info about VMD backing addresses in cfg (#11234)

- src/cart/crt_group.c
- Reset size param prior to each invocation of crt_hg_get_addr()
> DAOS-12575 cart: Reset size param during self set rank

- src/container/container_iv.c
- src/container/srv_container.c
- src/container/srv_target.c
- src/dtx/dtx_resync.c
- src/engine/server_iv.c
- src/include/daos/common.h
- src/include/daos_obj.h
- src/include/daos_srv/iv.h
- src/include/daos_srv/pool.h
- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_verify.c
- src/object/srv_internal.h
- src/object/srv_obj_migrate.c
- src/pool/srv_internal.h
- src/pool/srv_iv.c
- src/pool/srv_pool.c
- src/pool/srv_target.c
- src/pool/srv_util.c
- src/rebuild/rebuild_internal.h
- src/rebuild/scan.c
- src/rebuild/srv.c
Several rebuild patches sync with master
DAOS-11444 pool: return rc for ds_pool_lookup (#10551)
DAOS-11952 rebuild: increase stack size for rebuild ULT (#10683)
DAOS-11064 rebuild: search the right targets to merge (#10776)
DAOS-12112 rebuild: keep reclaim op unchanged (#10973)
DAOS-10836 pool: add master term to IV namespace (#11024)
DAOS-12198 rebuild: remove invalid assertion. (#11070)
DAOS-10681 rebuild: check the global pool map version before rebuild (#11140)
DAOS-10681 object: misc fixes for layout upgrade and rebuild (#11129)
> DAOS-12112 rebuild:rebuild patches port from 2.4

- src/object/cli_ec.c
- src/object/srv_obj.c
- src/object/srv_obj_migrate.c
Missing fill_oid for object enumeration retry
case.
> DAOS-12419 object: missing fill_oid in obj enum (#11272)

- src/container/srv_container.c
Test-tag: container test_container_user_acl datamover,-test_dm_posix_meta_entry_dcp
daos_prop_entry_get(x, DAOS_PROP_CO_LABEL) returns NULL when the label of a container is not set.
> DAOS-12501 container: Container label may not exist.

- src/tests/ftest/launch.py
- src/tests/ftest/process_core_files.py
Resolve 'No symbol table info available.' errors in CI stacktrace generation by installing missing doas-*-tests debuginfo packages.
Test-tag: pr test_core_files
DAOS-12415 test: Allow for tests which may produce core files. (#11326)
Add logic to not fail the DaosBuild test if it creates a forefile, it sometimes creates a corefile from conftest which is expected and should not cause a test failure.
Fix a bug where the program that generated the core file was read incorrectly.
Add some debugging where the DaosBuild test fails.
> DAOS-12527 test: Add missing debug symbols for stacktraces (#11364)

- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/run_utils.py
- src/tests/ftest/util/server_utils.py
Test-tag: test_ec test_metadata_server_restart
> DAOS-12578 test:

- src/vos/tests/vts_io.c
Co-authored-by: Dmitry Ivanov <dmitry.ivanov2@hpe.com>
> DAOS-12580 test: Add missing fault injection macro

- debian/changelog
- debian/control
- utils/rpms/daos.spec
change ipmctl requirement from v2 to v3
> DAOS-12314 build: change ipmctl from v2 to v3

- SConstruct
- src/SConscript
That way any generated files are put in variant directory rather than the source directory.
> DAOS-623 build: Move version information to src/SConscript

- .gitignore
src/include/daos_version.h should be included.
> DAOS-623 repo: update git ignore list

- src/client/dfs/dfs.c
- src/tests/suite/dfs_unit_test.c
> DAOS-12422 dfs: add test for removing / recreating SB

- src/client/api/tests/eq_tests.c
- Set provider explicitly in the test
> DAOS-12633 test: Set provider explicitly

- src/rebuild/scan.c
Move debug ahead of debtree_iter_del in rebuild_obj_fill_buf() to avoid accessng after free.
> DAOS-10681 rebuild: Move debug ahead of dbtree_iter_del

- src/common/pool_map.c
- src/include/daos_srv/rebuild.h
- src/object/srv_obj_migrate.c
- src/pool/srv_pool.c
- src/pool/srv_pool_map.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/tests/suite/daos_drain_simple.c
- src/tests/suite/daos_extend_simple.c
- src/tests/suite/daos_rebuild.c
restore the pool map if extend/drain fail.
> DAOS-5912 rebuild: restore pool map if extend/drain fail

- src/vos/tests/vts_wal.c
Signed-off-by: Dmitry Ivanov <dmitry.ivanov2@hpe.com>
Add a new test to vos_tests “WAL” (-w) test suite for the large transaction as well as the transaction of the large (1K to 8K) values stored under akey (DAOS_OT_MULTI_HASHED). The data is fetched and checked after the WAL replay.
> DAOS-12442 tests: add large transactions to VOS tests for WAL

- docs/QSG/setup_suse.md
fix zypper typo in QSG
Doc-only: true
> DAOS-12551 doc: fix zypper typo (#11365)

- docs/QSG/setup_suse.md
fix zypper typo in QSG
Doc-only: true
> DAOS-12551 doc: fix zypper typo

- src/tests/ftest/harness/advanced.py
- src/tests/ftest/harness/advanced.yaml
- src/tests/ftest/launch.py
Test-tag: pr,vm HarnessAdvancedTest,vm
Add support in laucnh.py to kill processes before and after running tests
- cart_ctl
- orterun
- mpirun
- dfuse
> DAOS-12144 test: cleanup rougue processes after tests

- debian/changelog
- debian/control
- utils/rpms/daos.spec
change ipmctl requirement from v2 to v3
change spdk requirement from 22.01.1 to 22.01.2
fix libfabric requirement for debian (had 1.14, should have had 1.15)
> DAOS-12314 build: change ipmctl from v2 to v3 (#11404)

- debian/changelog
- utils/rpms/daos.spec
As this was never necessary as the auto-dependency generator will handle ensuring that the needed library is installed.
> DAOS-12585 build: Remove R: protobuf-c

- src/tests/ftest/launch.py
Limit the number of time a group of tests can be repeated in CI to 10.
> DAOS-12645 test: Impose a test repeat limit in CI.

- src/client/dfs/dfs.c
- fix checker to detect leaked subdirs and not link them in top level l+f
- fix checker for subdir traversal to be non-recursive by leveraging lower level DAOS API
> DAOS-12651 dfs: update checker to not link leaked directories twice

- src/tests/ftest/harness/advanced.py
- src/tests/ftest/harness/advanced.yaml
- src/tests/ftest/launch.py
Test-tag: pr,vm test_cleanup_procs
Add support in laucnh.py to kill processes before and after running tests
- cart_ctl
- orterun
- mpirun
- dfuse
> DAOS-12144 test: cleanup rougue processes after tests (#11341)

- src/bio/bio_buffer.c
- src/bio/bio_internal.h
- src/include/daos_srv/bio.h
- src/vos/vos_pool.c
Introduced non-blocking bio_iod_try_prep() for checkpoint flush prep, where we can't tolerate yield in DMA buffer preparing.
> DAOS-12612 bio: Non-blocking bio_iod_try_prep()

- src/bio/bio_buffer.c
- src/common/mem.c
- Fix typo in bio_iod_try_prep();
- Fix umem_cache_checkpoint() to handle the flush prep failure;
> DAOS-12612 bio: fix typo in bio_iod_try_prep()

- src/tests/SConscript
- src/tests/daos_mw_fi.c
- src/tests/suite/dfs_unit_test.c
- utils/node_local_test.py
> DAOS-12651 test: add nlt test for dfs container check

- src/include/daos_srv/daos_engine.h
- src/object/obj_internal.h
- src/object/obj_rpc.h
- src/object/srv_obj_migrate.c
- src/pool/srv_target.c
- src/rebuild/scan.c
- src/rebuild/srv.c
- src/tests/suite/daos_rebuild_simple.c
Add rebuild generation to migrate tls to avoid the tls being wrongly picked by rebuild retry job, which can cause some objects being skipped during
rebuild/migration.
> DAOS-12074 rebuild: add generation to migrate tls (#11375)

- src/control/server/init/setup_spdk.sh
Running DAOS/SPDK via UIO as an unprivileged user is no longer
supported so we don't need to modify the relevant file ownership.
> DAOS-12334 control: Remove obsolete checks in SPDK setup script

- docs/release/updating.md
> DAOS-9335 doc: online docfix

- src/pool/srv_pool.c
> DAOS-8714 pool: move pool map transfer outside of the wr lock

- src/client/ds3/object.c
The function ds3_obj_write() allocates IOV and SGL variables on the stack for the underlying call to dfs_write(). This pattern usually work, but it can cause a segmenation fault if a different thread is polling the event queue than the thread issuing the writes.  If thread that polls the event queue schedules the task before the I/O issuing thread that initiates the ds3_obj_write(), then the stack allocated variables for the task might now be corrupted by the I/O issuing thread.
Fix this by allocating  ds3_obj_args_t argument that is then freed via event completion callback.
> DAOS-12661 ds3: Don't use stack allocated variables for async write

- src/tests/suite/dfs_unit_test.c
> DAOS-12423 dfs: add test to unlink root from SB and fix

- src/tests/ftest/launch.py
Limit the number of time a group of tests can be repeated in CI to 10.
> DAOS-12645 test: Impose a test repeat limit in CI. (#11460)

- src/bio/tests/wal_ut.c
Pointer used before initialization.
Authored-by: Niu Yawei  <yawei.niu@intel.com>
> DAOS-12686 test: Fix bio_ut

- ci/unit/test_nlt_node.sh
- src/tests/daos_mw_fi.c
- utils/node_local_test.py
> DAOS-12687 test: update test tool to punch object and add nlt tests

- src/tests/ftest/container/label.py
- src/tests/ftest/container/label.yaml
- src/tests/ftest/deployment/network_failure.py
- src/tests/ftest/deployment/server_rank_failure.py
- src/tests/ftest/deployment/target_failure.py
- src/tests/ftest/util/test_utils_container.py
Test-tag: ContainerLabelTest TargetFailure NetworkFailureTest test_pda_pool_property ServerRankFailure
Add container label test cases
- Container create with valid labels
- Container create with invalid labels
- Container create with duplicate labels
> DAOS-11272 test: container label test cases

- src/tests/ftest/erasurecode/rebuild_fio.py
- src/tests/ftest/erasurecode/rebuild_fio.yaml
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/test_utils_pool.py
Update test_ec_offline_rebuild_fio with dfuse oclass EC.
Test-tag: test_ec_offline_rebuild_fio
> DAOS-12572 test: erasurecode rebuild_fio.py ec_online_rebuild_fio aggregation failed to start

- src/client/api/array.c
- src/client/array/dc_array.c
- src/client/dfs/dfs.c
- src/include/daos/array.h
- src/include/daos_array.h
- src/include/daos_fs.h
- src/tests/suite/dfs_unit_test.c
The open handle for the file needs to be updated through the array API in addition to changing the chunk size on storage.
> DAOS-12703 dfs: fix chunk size update for leaked files and add tests

- Jenkinsfile
- ci/parse_ci_envs.sh
- ci/provisioning/post_provision_config_common_functions.sh
- debian/changelog
- utils/githooks/pre-commit.d/20-flake.sh
- utils/rpms/daos.spec
- utils/rpms/packaging/Dockerfile.ubuntu.20.04
- utils/rpms/packaging/Makefile_distro_vars.mk
As this was never necessary as the auto-dependency generator will handle ensuring that the needed library is installed.
> DAOS-12585 build: Remove R: protobuf-c (#11442)

- debian/changelog
- utils/rpms/daos.spec
libuuid-devel has been a DAOS BR for a very long time but has been
masked  behind libfabric's BR for libpsm2-devel which itself BR'd
libuuid-devel.
Now that we have removed the libpsm2-devel BR from libfabric,
libuuid-devel is not being installed any more, and DAOS needs it.
Remove historic and now unnecessary dependency on libcurl4 on SUSE
distros.
DAOS-12585 build: Remove R: protobuf-c (#11442)
As this was never necessary as the auto-dependency generator will handle
ensuring that the needed library is installed.
> DAOS-12558 build: BR libuuid-devel (#11361)

- ci/bandit.config
- src/tests/suite/SConscript
bandit scans *.py by default. Now enable scanning SConscript by update bandit's config file.
> DAOS-12103 cq: Let bandit scan SConscript as well as .py

- src/container/srv_target.c
Aggregation flags are being ignored in favor of a hard coded full scan. This would bypass all aggregation optimizations.
> DAOS-12639 object: Revert a change with checksum scrubbing (#11445)

- src/container/srv_container.c
- utils/rpms/daos.spec
Test-tag: container test_container_user_acl datamover,-test_dm_posix_meta_entry_dcp
1. Porting 12cf6f8 to testbuild/2.3.104.
2. Added "BuildRequires: libuuid-devel" in daos.spec to avoid rpm compiling issues in CI.
daos_prop_entry_get(x, DAOS_PROP_CO_LABEL) returns NULL when the label of a container is not set.
> DAOS-12501 container: Container label may not exist. (#11394)

- src/tests/ftest/server/multiengine_persocket.py
- src/tests/ftest/server/multiengine_persocket.yaml
- src/tests/ftest/util/general_utils.py
Update test with daos_server scm reset and prepare –force --scm-ns-per-socket 2 Update script to remove unneeded reboot.
Skip-build-centos8-rpm: true
> DAOS-12570 test: multi-engine per socket test for the latest DAOS changes (#11400)

- src/client/api/array.c
- src/client/array/dc_array.c
- src/client/dfs/dfs.c
- src/client/dfs/dfs_internal.h
- src/control/cmd/daos/filesystem.go
- src/include/daos/array.h
- src/include/daos_array.h
- src/tests/daos_mw_fi.c
- src/tests/suite/dfs_unit_test.c
- src/utils/daos_dfs_hdlr.c
- src/utils/daos_hdlr.h
- utils/node_local_test.py
In some scenarios, an entry might get corrupted (mode bits, mtime, ctime, etc.). Most of the these are correctable using regular linux commands (chmod, set mtime/ctime, etc.), but others are not, including a corrupted type bit. This PR extend the daos fs tool to add a fix-type option would allows a user to fix the type. The fix-chunk-size command was removed in favor of this new option that allows also to fix-entry and specify a chunk-size as something to fix. This option can be extended further for other entry options.
> DAOS-12180 dfs: extend fs tool to support fixing entry types

- src/tests/ftest/util/yaml_utils.py
Raise a user-friendly exception when the extra yaml does not exist.
> DAOS-12685 test: handle when extra yaml does not exist

- src/common/dav/memops.c
This fix addresses a bug within the bmem allocator, where the initial capacity for redo ops ulog was set incorrectly. Without this fix, if the number of redo log entries within a tx is between 40 and 64, then only the first 40 entries are getting committed.
> DAOS-12734 common: Fix for failure/crash on container destroy

- src/object/cli_shard.c
- src/tests/suite/daos_array.c
- src/tests/suite/daos_test.c
- src/tests/suite/daos_test.h
Server only reply back dkey through "okqo->okqo_dkey" when api flags
with DAOS_GET_DKEY, for other cases should take the dkey from
"okqi->okqi_dkey".
Add an array test case (ec_array_key_query) to verify it (by Mohamad).
> DAOS-12741 object: fix a bug of dkey in obj_shard_query_recx_post()

- src/tests/ftest/cart/util/cart_logparse.py
- src/tests/ftest/cart/util/cart_logtest.py
- src/tests/suite/SConscript
- utils/node_local_test.py
- DAOS-12735 test: Improve log analysis reporting.
- Required-githooks: true Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>
> DAOS-12735 test: Improve log analysis reporting.

- src/control/cmd/daos/pool.go
- src/control/cmd/dmg/pool.go
Move the required tag from the arg struct to the
specific required field in the struct.
> DAOS-12721 control: Fix dmg pool get-prop

- src/tests/ftest/io/macsio_test.py
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/daos_utils.py
- src/tests/ftest/util/general_utils.py
- src/tests/ftest/util/server_utils.py
- src/tests/ftest/util/soak_utils.py
Adding general_utils.py dict_to_list() and dict_to_str() methods to ensure items are converted to strings before being joined.
Test-tag: test_macsio test_query_attr test_dfuse_daos_build_data test_soak_smoke
> DAOS-12728 test: Fix dictionary string conversion

- src/common/btree.c
- src/vos/evtree.c
- src/vos/vos_gc.c
- src/vos/vos_io.c
- src/vos/vos_obj.c
Just use tx_add_range with NO_SNAPSHOT flag
> DAOS-12743 vos: Ensure max_write and aggregation flags get flushed

- src/vos/ilog.c
- src/vos/ilog.h
- src/vos/tests/vts_ilog.c
- src/vos/vos_ilog.c
- src/vos/vos_ilog.h
- src/vos/vos_io.c
- src/vos/vos_obj.c
- src/vos/vos_obj_cache.c
- src/vos/vos_obj_index.c
- src/vos/vos_query.c
When update ilog for update or punch, we fetch related ilog entries firstly, that may hits many uncommitted DTX entries on non-leaders. If it is for non-conditional modification, then it will not trigger DTX refresh nor client side RPC retry. But if it is for conditional modification, then the upper layer caller will get -DER_INPROGRESS. Under such case, related VOS logic need to collect those 'prepared' DTX entries information for DTX refresh to avoid related operation being blocked for long time.
> DAOS-12491 vos: handle DTX conflict for conditional updating ilog

- src/common/pool_map.c
- src/engine/ult.c
- src/include/daos/common.h
- src/include/daos/pool_map.h
- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_layout.c
- src/object/srv_obj_migrate.c
- src/placement/SConscript
- src/placement/jump_map.c
- src/placement/jump_map_versions.c
- src/placement/pl_map.h
- src/placement/pl_map_common.c
- src/placement/ring_map.c
- src/placement/tests/jump_map_place_obj.c
- src/placement/tests/place_obj_common.c
- src/placement/tests/place_obj_common.h
- src/tests/ftest/daos_test/suite.py
- src/tests/ftest/daos_test/suite.yaml
- src/tests/suite/daos_extend_simple.c
- src/tests/suite/daos_rebuild_ec.c
- src/tests/suite/daos_test.h
- src/tests/suite/daos_upgrade.c
Fix in get_target() to make sure shards within the same group will not in the same failure domain, though it might put multiple shards from different group in the same VOS target.
Add jump_map_versions.c for different layout version.
Add tests in jump_map_place_obj.c to verify the layout.
Minor fixes in layout difference compare for EC object.
> DAOS-10681 placement: fix the shard colocate issue

- requirements.txt
It seems to have some bugs that badly affect our builds
> DAOS-12833 build: Avoid updating to SCons 4.5

- src/object/cli_shard.c
- src/tests/suite/daos_obj_ec.c
possibly fetch an non-existed singv, that case will get 0 iod_size should not cause segfault in dc_rw_cb_singv_lo_get.
> DAOS-12467 object: fix a bug in dc_rw_cb_singv_lo_get

- src/object/cli_obj.c
- src/object/obj_internal.h
- src/object/obj_tx.c
- src/tests/suite/daos_base_tx.c
If the resent RPC is too old as to exceed server DTX aggregation time threshold, then related DTX entry on server may be removed by DTX aggregation, and then the resent logic will have no way to know whether related modification has ever been executed on the engine or not. Under such case, client will get -DER_EP_OLD failure. For non-conditional modifcation, that is not fatal, the client logic can re-generate newer DTX ID and retry the RPC. If its former RPC has ever been executed, it just re-executes the modification with some redundant data (that can be handled via VOS aggregation sometime later), but it will not cause semantics issues.
> DAOS-12679 object: refresh DTX ID for DER_EP_OLD

- src/tests/ftest/slurm_setup.py
- src/tests/ftest/util/cmocka_utils.py
- src/tests/ftest/util/command_utils.py
- src/tests/ftest/util/fault_config_utils.py
- src/tests/ftest/util/general_utils.py
- src/tests/ftest/util/run_utils.py
Test-tag: pr,vm container_acl,vm DfuseMUPerms
Test-tag: dfuse,pr DfuseMUPerms
Instead of:
`export foo=bar; sudo <cmd>`
The correct way is:
`sudo foo=bar <cmd>`
> DAOS-12723 test: fix ExecutableCommand.with_exports for sudo

- src/object/cli_obj.c
- src/object/srv_obj_migrate.c
- src/tests/suite/daos_rebuild_ec.c
Both EC reintegration and rebuild should use force degraded fetch to make sure both full data cell shard will be reintegrated, even though it may be covered by partial update.
> DAOS-12631 object: force degrade fetch for EC reintegration (#11486)

- ci/codespell.ignores
- docs/user/filesystem.md
- src/common/credit.c
- src/common/tests/acl_util_tests.c
- src/common/tests/checksum_tests.c
- src/include/daos_srv/daos_engine.h
- src/object/obj_tx.c
- src/tests/ftest/cart/test_group_np_common.h
- src/tests/suite/daos_obj.c
- src/vos/tests/vts_common.c
- src/vos/vos_dtx.c
- src/vos/vos_internal.h
> DAOS-623 common: Fix codespell errors that started showing up on PRs

- src/tests/ftest/daos_vol/h5_suite.yaml
- src/tests/ftest/mpiio/hdf5.yaml
- src/tests/ftest/util/server_utils_params.py
This reverts commit 0bd30780a3e8a4876fda2e24c561ca9c79c3690f.
> Revert "DAOS-12581 test: Temporarily increase crt_timeout (#11475)"

- src/bio/bio_xstream.c
BIO specifies 20k 'num_md_pages' on blobstore creation, the intention was to inform SPDK that at most 20k blobs could be created to the blobstore, and therefore SPDK will be able to reserve less space for blobstore meta data.
This is actually not necessary since DAOS uses very large cluster size (1GB), and SPDK by default set 'num_md_pages' to total clusters, so for a 1TB blobstore, by default 1k num_md_pages will be used, which is even smaller than the specified 20k. Furthermore, specifying an arbitrary 'num_md_pages' could trigger potential defects in SPDK blobstore.
> DAOS-12678 bio: don't specify num_md_pages

- Jenkinsfile
Enabling a weekly functional pr+daily build on the feature/vos_on_blob branch that will run with functional tests with md on ssd enabled.
> DAOS-11421 test: Adding weekly timed testing

- SConstruct
- site_scons/components/__init__.py
- site_scons/prereq_tools/base.py
- site_scons/site_tools/stack_analyzer.py
- src/vos/storage_estimator/daos_storage_estimator.py
It could be useful to be build external components with stack -fstack-usage enabled as well.  This updates the tool to also can the build directories for prerequisites.
> DAOS-623 build: Update stack analyzer to also search external builds

- src/tests/ftest/dfuse/mu_perms.py
- src/tests/ftest/util/dfuse_utils.py
Test-tag: DfuseMUPerms
Verify dfuse multi-user permissiosn with the interception library.
> DAOS-10857 test: verify dfuse multi-user permissions with IL

- src/tests/ftest/deployment/basic_checkout.py
Need to set self.ior_ppn = self.ppn
Test-tag: BasicCheckoutDm
> DAOS-623 test: fix basic checkout dm ppn

- src/gurt/misc.c
- src/gurt/tests/test_gurt.c
- Fix bug in d_rank_list_dup_sort_uniq
- Add a unit-test
> DAOS-12863 cart: Fix bug in d_rank_list_dup_sort_uniq

- .github/workflows/flake.yml
- src/tests/suite/SConscript
> DAOS-12103 cq: Update flake action to trigger for scons changes.

- debian/changelog
- utils/rpms/daos.spec
So that it's higher than the TB5 version that is on it's own branch.
> DAOS-623 build: Bump version to 2.3.106

- src/control/cmd/daos/container.go
> DAOS-12637 tools: update dfs cont evict option from evict-all to all

- Jenkinsfile
Moving setting the default Test-Nvme argument in pipeline-lib as opposed to in the Jenkinsfile.
> DAOS-11421 test: Set the default Test-nvme arg for vos_on_blob

- src/tests/ftest/launch.py
Fix for commit 18c3c93.
Skip-unit-tests:true
Test-tag-hw-large: dfs_test
Test-provider-hw-large: ucx+dc_x
> DAOS-12903 test: Fix path for pre-created archive directories

- src/tests/ftest/util/soak_utils.py
Recent change to .with_export changed the cmdline for fio in the batch script
> DAOS-12902 test: Remove .with_exports from fio cmdline

- src/client/dfs/dfs.c
- src/vos/README.md
- src/vos/storage_estimator/common/dfs_sb.py
- src/vos/storage_estimator/common/explorer.py
- src/vos/storage_estimator/common/util.py
- src/vos/storage_estimator/common/vos_size.py
Fix documentation link
Remove array metadata from dfs file entry, DFS doesn't create an entry in the file object.
Make dfs entry size reflect actual size
Don't sort yaml keys
Fix output to use KiB, MiB, etc
> DAOS-12853 common: More fixes for storage estimator

- src/tests/ftest/launch.py
Test log collection can fail if there is not enough space left on the
remote hosts to make a directory which is then used to clush --rcopy the
files to the launch host.  To avoid this ituation these directories will
be created prior to running the tests.
DAOS-12903 test: Fix path for pre-created archive directories (#11716)
Fix for commit https://github.com/daos-stack/daos/commit/18c3c93963a0737365a4ddf2e4226c7012271619.
Skip-unit-tests:true
> DAOS-12903 test: Allow for log collection w/ No space left on device (#11700)

- src/tests/ftest/erasurecode/truncate.py
- src/tests/ftest/fault_injection/ec.py
- src/tests/ftest/io/parallel_io.py
- src/tests/ftest/util/fio_utils.py
Test-tag: pr soak_smoke fio
Fix fio command string, broken by 7d624c01874c81ac98e9cdb910a7fcd7d111aa2b. Instead of overriding __str__, override with_bind so all of these properties work as expected:
- __str__
- with_bind
- with_sudo
- with_exports
> DAOS-12723 test: fix fio command string

- src/bio/SConscript
- src/bio/tests/SConscript
- src/common/SConscript
- src/common/mem.c
- src/common/tests/umem_test.c
- src/include/daos/mem.h
- src/include/daos_srv/pool.h
- src/include/daos_srv/vos.h
- src/pool/srv_pool_chkpt.c
- src/pool/srv_target.c
- src/vos/vos_internal.h
- src/vos/vos_pool.c
In order to implement a WAL size based checkpoint trigger, rework the code to separate upper layer logic from VOS and checkpoint logic.
Implement the WAL size based trigger.
> DAOS-12612 common: Rework checkpoint triggering code

- src/object/srv_obj.c
Fix some memory corruption issuse for csum in
obj_get_iods_offs_by_oid().
> DAOS-12706 object: Some memory corruption issue

- src/container/srv_container.c
- src/include/daos_srv/security.h
- src/security/srv_acl.c
- src/security/srv_internal.h
- src/security/tests/srv_acl_tests.c
Add CONT_CAPA_OPEN_EX and CONT_CAPA_EVICT_ALL and remove the is_owner parameter of ds_sec_cont_get_capabilities.
> DAOS-12065 security: Add CONT_CAPA_{OPEN_EX,EVICT_ALL}

- debian/changelog
- utils/rpms/daos.spec
Add runtime dep as control-plane shells out to numastat to fetch debug
on hugepage/DMA buffer memory shortages.
> DAOS-12924 build: Add numactl dep to agent and server in spec

- src/tests/ftest/util/soak_utils.py
> DAOS-12956 test: Add unique container label to soak

- .rpmignore
update .rpmignore to not ship locally built protobuf-c RPMs
> DAOS-12872 build: don't ship protobuf-c RPMs

- src/common/debug.c
- src/common/tests_dmg_helpers.c
- src/gurt/debug.c
strtok_r() should be used to be safe. Otherwise, calling daos API could break the applications calling strtok().
> DAOS-12959 gurt: Replace strtok with strtok_r

- src/bio/bio_wal.c
- src/bio/bio_wal.h
- src/include/daos_srv/bio.h
- src/vos/vos_pool.c
Introduced bio_meta_is_empty() and bio_meta_clear_empty() for avoid loading a newly created meta blob on pool creation.
> DAOS-12890 bio: skip loading empty meta blob

- src/mgmt/srv_target.c
Fixed a regression introduced by a recent fix to tgt_vos_preallocate where the error return code like DER_NOSPACE was incorrectly tracked.
> DAOS-12951 mgmt: Pool create did not fail due to DER_NOSPACE

- src/bio/bio_wal.c
- src/bio/tests/wal_ut.c
- src/common/dav/dav_iface.c
- src/common/mem.c
- src/common/tests/umem_test.c
- src/common/tests/umem_test_bmem.c
- src/include/daos/mem.h
- src/include/daos_srv/bio.h
- src/vos/vos_common.c
- src/vos/vos_internal.h
- src/vos/vos_pool.c
Added metrics to capture the checkpoint duration, pages copied and wal size purged.
Additionally fixed a bug related to mismatch in meta blob size and the vos file size.
> DAOS-11411 vos: Add new metrics to track checkpointing activity

- src/tests/ftest/pool/create_capacity.py
- src/tests/ftest/pool/create_capacity.yaml
Reducing the pool nvme size to allow the test to pass on clusters with smaller NVMe drives.
Test-tag: test_create_pool_quantity
> DAOS-12899 test: Reduce nvme size for pool/create_capacity.py

- utils/docker/examples/client/README.md
- utils/docker/examples/client/daos-client_agent/el8/.dockerignore
- utils/docker/examples/client/daos-client_agent/el8/Dockerfile
- utils/docker/examples/client/daos-client_agent/el8/daos-bash.in
- utils/docker/examples/client/deploy-docker_stack.sh
- utils/docker/examples/client/docker-compose.daos_client_agent.gathered.yml
- utils/docker/examples/client/docker-stack.daos_client_agent.gathered.yml
Defines how to use docker containers for running an application accessing a DAOS file system.  The DAOS Agent service and the DAOS client are running in the same docker container.
Using DocOnly Pragma as the docker things are not tested by the CI.
> DAOS-12184 docker: Run DAOS application in a unique container

- src/tests/ftest/container/simple_create_delete.py
- src/tests/ftest/control/dmg_telemetry_io_latency.py
- src/tests/ftest/control/dmg_telemetry_io_latency.yaml
- src/tests/ftest/nvme/pool_capacity.py
- src/tests/ftest/security/cont_acl.py
- src/tests/ftest/security/cont_create_acl.py
- src/tests/ftest/security/cont_delete_acl.py
- src/tests/ftest/security/cont_get_acl.py
- src/tests/ftest/security/cont_overwrite_acl.py
- src/tests/ftest/security/cont_update_acl.py
- src/tests/ftest/util/cont_security_test_base.py
- src/tests/ftest/util/ec_utils.py
- src/tests/ftest/util/pool_security_test_base.py
Test-tag: pr container TestWithTelemetryIOLatency test_ec_offline_rebuild_single test_ec_degrade_single_value test_ec_aggregation_default SimpleCreateDeleteTest DaosContainterSecurityTest CreateContainterACLTest DeleteContainerACLTest GetContainerACLTest OverwriteContainerACLTest UpdateContainerACLTest
- Update tests to use get_container instead of TestContainer directly
- Misc avocado tag cleanup
- Misc code cleanup
> DAOS-9721 test: update tests to use get_container

- src/cart/crt_hg.c
- src/cart/crt_init.c
- src/common/misc.c
Fix an issue of did not pass correct cio_ctx_max_num to crt_init_opt, and refined a few details in crt init process.
> DAOS-12717 cart: pass correct cio_ctx_max_num to crt_init_opt

- Jenkinsfile
- ci/unit/test_main_node.sh
- src/tests/ftest/scripts/post_process_xml.sh
- src/vos/tests/vts_io.c
- src/vos/tests/vts_wal.c
- utils/run_test.sh
Change md_on_ssd to phase to use -A 50 rather than -w
Add USE_DEV variable to optionally run the NVMe tests using an
existing device.
Add a few sleep(1) to workaround DAOS-13040
Move from hardware to bwx_vm1 tag which has unused /dev/vdb
Cleanup the xml processing a bit.  I noticed when running
locally, it would result in one file getting prepended with
UTEST_* over and over again.  Instead, skip files that
already have UTEST_ prefix.  This avoids needing to move
files to xml subdirectory.
Skip-nlt: true
> DAOS-12963 test: Run unit tests on VM again

- src/tests/ftest/osa/offline_reintegration.yaml
Enable IO debug for more logs.
> DAOS-9313 tests: more log for osa_offline_reintegration_with_rf

- src/tests/suite/daos_md_replication.c
- src/tests/suite/daos_mgmt.c
Bump pool size in tests to ensure each VOS pool larger than the blob cluster size (32MB).
> DAOS-13045 tests: bump minimal pool size

- src/tests/ftest/rebuild/basic.yaml
- src/tests/ftest/rebuild/cascading_failures.yaml
- src/tests/ftest/rebuild/delete_objects.yaml
- src/tests/ftest/rebuild/read_array.yaml
Change rd_fac to rf for release 22
Test-tag: test_simple_rebuild test_simultaneous_failures test_rebuild_delete_objects test_read_array_during_rebuild
> DAOS-13062 tests: change rd_fac to rf for 22

- ci/provisioning/post_provision_config_common.sh
- src/tests/ftest/util/job_manager_utils.py
Test MOFED 5.8-1.1.2.1 on master branch.
Skip-scan-rpms: true
Skip-test-rpms: true
> DAOS-12739 test: ensure that we use MOFED 5.8-1.1.2.1 with master/2.4 and 2.2.1

- src/tests/ftest/checksum/csum_error_logging.py
- src/tests/ftest/daos_test/suite.py
- src/tests/ftest/util/daos_core_base.py
Save dmg logs for all daos_test cases.
Test-tag: pr daos_test
> DAOS-11394 test: Save dmg log for daos_test suite (#11783)

- .github/workflows/flake.yml
- src/client/pydaos/__init__.py
- src/tests/ftest/deployment/ior_per_rank.py
- src/tests/ftest/object/fetch_bad_param.py
- src/tests/ftest/object/integrity.py
- src/tests/ftest/object/open_bad_param.py
- src/tests/ftest/object/punch_test.py
- src/tests/ftest/object/update_bad_param.py
- src/tests/ftest/pool/global_handle.py
Test-tag: test_ior_per_rank GlobalHandle ObjOpenBadParam ObjFetchBadParam PunchTest ObjectDataValidation ObjUpdateBadParam
Resolve all flake issues in ftest.
> DAOS-13006 test: resolve all flake issues in ftest

- src/object/cli_obj.c
- src/tests/suite/daos_obj_ec.c
return -DER_INVAL if obj_fetch with non-zero iod_size and NULL sgl, to avoid segfault in obj_ec_recx_reasb().
> DAOS-12895 object: handle fetch with non-zero iod_size and NULL sgl

- src/ddb/tests/ddb_test_driver.c
- src/vos/tests/vts_io.c
After a merge with master, the dtx_handle must be attached for the ddb unit tests. This change fixes that.
> DAOS-13072 ddb: Unit Test Fix

- site_scons/site_tools/doneapi.py
xiar seems to have a serious bug on newer Leap 15.  Use the system
archive tool instead for now.
> DAOS-13087 build: Use ar instead of xiar for Intel builds

- site_scons/site_tools/doneapi.py
xiar seems to have a serious bug on newer Leap 15.  Use the system archive tool instead for now.
> DAOS-13087 build: Use ar instead of xiar for Intel builds (#11859)

- src/control/cmd/drpc_test/main.go
- src/control/drpc/drpc_client.go
- src/control/drpc/drpc_client_test.go
- src/control/drpc/drpc_server_test.go
- src/control/server/drpc.go
- src/control/server/drpc_test.go
- src/control/server/mgmt_pool_test.go
- src/control/server/util_test.go
- Use context to close connection on cancel
- Introduce mutex to protect connection reference
- Remove unused dRPC retry logic
> DAOS-12672 control: Make dRPC calls context aware (#11760)

- src/cart/crt_init.c
- Set FI_OFI_RXM_DEF_TCP_WAIT_OBJ to pollfd on the server only
> DAOS-12727 cart: Set FI_OFI_RXM_DEF_TCP_WAIT_OBJ to pollfd on the server

- debian/changelog
- debian/control
- utils/rpms/daos.spec
- Pin libfabric to be below 1.18 version for 2.2 branch. Libfabric 1.18 introduces a new TCP provider and requires a mercury update. 
> DAOS-12988 cart: Pin libfabric to be below 1.18 version for 2.2 branch

- SConstruct
deepcopy on os.environ doesn't work properly.  It can result in changes to the cloned environment
appearing in the parent environment.
This is illustrated by this simple example
jvolivie-desk1:[~/scons_test]$ cat SConstruct 
import os
bad_env = DefaultEnvironment()
good_env = bad_env.Clone()
bad_env.Replace(ENV=os.environ)
good_env.Replace(ENV= os.environ.copy())
good_env_clone = good_env.Clone()
bad_env_clone = bad_env.Clone()
good_env_clone["ENV"]["FOO"] = "1"
bad_env_clone["ENV"]["FOO"] = "1"
print(f"good_env['ENV']['FOO'] = {good_env['ENV'].get('FOO', '')}")
print(f"bad_env['ENV']['FOO'] = {bad_env['ENV'].get('FOO', '')}")
In this example, FOO is set in bad_env
> DAOS-13051 build: Use os.environ.copy() for SCONS_ENV option

- src/object/cli_ec.c
- src/object/cli_obj.c
- src/object/obj_ec.h
original code possibly set iod_size from invalid memory address when there are multiple iods in the fetch request and hit -DER_FETCH_AGAIN in data recovery process.
> DAOS-12410 object: fix a bug in recov_task_cb

- ci/unit/test_main_node.sh
- src/common/tests/btree.sh
- src/object/tests/srv_checksum_tests.c
- utils/run_test.sh
- utils/run_utest.py
- utils/utest.yaml
It's difficult to add new features and new tests that don't fit the standard in bash.  This gives a little more flexibility.
Preemptively add placeholders for tests that are on feature branches so that post merge, they will still run.
Fix a bug in srv_checksum_test.c.  It wasn't actually running under valgrind due to placement within run_test.sh, something that was unintentional and another reason to use python.
> DAOS-623 test: Create python script for unit tests

- ci/provisioning/post_provision_config_common.sh
- src/tests/ftest/util/job_manager_utils.py
Test with MOFED 5.8-1.1.2.1 on Release_2.2.1 branch
Skip-scan-rpms: true
Skip-test-rpms: true
> DAOS-12739 test: ensure that we use MOFED 5.8-1.1.2.1 with 2.2.1

- src/pool/srv_iv.c
- src/pool/srv_pool.c
Add term to the IV POOL HDL invalidate sync process to avoid the new SRV handle being closed by old IV invalidate.
> DAOS-11572 pool: add term to the IV srv HDL invalidate

- Jenkinsfile
- ci/unit/test_main_node.sh
- ci/unit/test_post_always.sh
- utils/run_utest.py
Save stdout and stderr in logs
Print to output where to find logs for a failed test
Fix regression in run_go_test cmocka results (UTEST_control. prefix)
> DAOS-623 test: Improve run_utest.py

- src/container/srv_target.c
- src/dtx/dtx_common.c
- src/dtx/dtx_resync.c
- src/include/daos_srv/container.h
More clear trace for DTX register/resync/reindex enter and exit.
> DAOS-13077 dtx: trace container reference for DTX logic

- src/client/dfs/dfs.c
- src/tests/daos_mw_fi.c
- utils/node_local_test.py
also fix nlt test after latest master merge on feature branch causing NLT to fail.
> DAOS-13105 dfs: fix coverity 1347923 and 1347922

- utils/run_utest.py
Rather than capturing output and then printing when the command is finished, have subprocess.run write directly to output file. This makes for a better experience when running locally so we can monitor a long running command.
> DAOS-623 test: Unit tests write directly to log file

- src/control/cmd/daos/container.go
- src/utils/daos_hdlr.c
- src/utils/daos_hdlr.h
Removed the redundant C handler and updated the Go code to call daos_cont_set_prop directly.
> DAOS-13070 control: Port daos cont set-prop handler to Go

- src/object/cli_obj.c
- src/object/obj_tx.c
- src/object/srv_obj_migrate.c
- src/placement/jump_map.c
- src/pool/cli.c
- src/pool/srv_pool.c
- src/rebuild/srv.c
- src/tests/ftest/control/dmg_pool_query_ranks.py
- src/tests/suite/daos_drain_simple.c
- src/tests/suite/daos_extend_simple.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_simple.c
Since object enumeration might return next punch epoch of
the current object/key/rec, so let's compare the punch
epoch with rebuild/reintegration stable epoch before
migrate punch.
Do not allow reint/drain/extend if there are other rebuild
job going on to avoid screwing up the object layout.
Fix converting task error reset in dc_tx_check_update()
Co-authored-by: Fan Yong <fan.yong@intel.com>
> DAOS-12398 object: Check punch epoch before migration punch

- src/control/lib/hardware/fabric.go
- src/control/lib/hardware/fabric_test.go
- src/control/lib/hardware/mocks.go
- Add internal support for fabric scan with multiple providers specified.
> DAOS-13088 control: Support fabric scan with multiple providers

- src/bio/bio_xstream.c
Address valgrind issues exposed by bio_ut.
> DAOS-13144 bio: address valgrind issues

- src/bio/bio_buffer.c
- src/bio/bio_wal.c
- src/bio/bio_xstream.c
- src/bio/tests/bio_ut.c
- src/bio/tests/bio_ut.h
- src/bio/tests/wal_ut.c
CIDs: 1347[789, 792, 799, 802, 803, 810, 811, 812]
> DAOS-13111 bio: address coverity issues

- src/control/cmd/daos_server/storage_utils.go
- src/control/lib/hardware/libfabric/bindings.go
- src/control/lib/hardware/libfabric/provider.go
- src/control/server/server.go
- src/control/server/server_utils.go
Some additional work was necessary to make specified provider
query work with multiprovider.
> DAOS-13088 control: Fix provider query with multiprovider

- utils/githooks/git-version.sh
Handle unexpected extra “ (Apple Git-133)" pattern from “git --version" output on MacOs
> DAOS-13152 githooks: accept "git --version" output with MacOs

- src/control/lib/hardware/libfabric/bindings.go
- src/control/lib/hardware/libfabric/provider.go
Allocating the hint manually wasn't working for some providers.
> DAOS-13153 control: Use libfabric method to alloc hint

- utils/build.config
- Update to libfabric to v1.17.1
- Apply DAOS 12407 patch to ofi
> DAOS-12407 cart: Update libfabric to v1.17.1

- src/bio/bio_wal.c
- src/bio/bio_xstream.c
- src/include/gurt/common.h
- utils/test_memcheck.supp
Suppress some memcheck errors.
> DAOS-13144 bio: suppress some memcheck errors

- src/tests/ftest/container/snapshot.py
To reduce snapshot data to 200 characters.
Test-tag: snapshot
> DAOS-12282 test: container/snapshot.py test_snapshots artifacts size very large (#11112)

- src/pool/srv_iv.c
Only update IV entry epoch for IV update and sync, to avoid the entry being updated by out of order IV request.
> DAOS-13095 pool: only update entry epoch for IV update

- docs/cloud/index.md
add link to IBM blog post on DAOS in IBM Cloud VPC
Doc-only: true
> DAOS-9355 doc: add IBM Cloud VPC

- docs/cloud/index.md
add link to IBM blog post on DAOS in IBM Cloud VPC
Doc-only: true
> DAOS-9355 doc: add IBM Cloud VPC (#11911)

- docs/QSG/setup_rhel.md
- docs/QSG/setup_suse.md
fixes to QSG docs
Doc-only: true
> DAOS-11874 doc: fixes to QSG docs

- docs/QSG/setup_rhel.md
- docs/QSG/tour.md
- docs/testing/autotest.md
- docs/testing/datamover.md
misc QSG and tesing doc fixes
Doc-only: true
> DAOS-11869 doc: misc QSG fixes

- docs/admin/predeployment_check.md
clarify that memlock limit is also relevant on DAOS clients
Doc-only: true
> DAOS-12316 doc: memlock for daos_agent

- src/tests/ftest/ior/intercept_multi_client.yaml
Test-Tag: test_ior_intercept_multi_client
Test-repeat: 3
> DAOS-11830 test: Increase performance diff to 10 percent.

- src/object/cli_obj.c
Let's use dkey hash to get replication object leader
to avoid always using the same shard as the DTX leader.
Signed-off-by: Di Wang <di.wang@intel.com>### Before requesting gatekeeper:
> DAOS-GCP147 object: use dkey hash to get RP leader

- src/tests/ftest/nvme/fragmentation.py
- src/tests/ftest/nvme/io_verification.py
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/daos_utils.py
- src/tests/ftest/util/data_mover_test_base.py
- src/tests/ftest/util/test_utils_base.py
- src/tests/ftest/util/test_utils_container.py
Test-tag: pr container datamover test_nvme_fragmentation test_nvme_io_verification test_nvme_server_restart
- Rename Test.label_generator to self.pool_label_generator
- Add Test.cont_label_generator
- Add TestContainer.label_generator to generate a unique label
- Currently only when a label value is already supplied
- Add TestContainer.identifier to return the label if defined
- Add TestContainer.use_label to tell the framework to use labels by default
- Adjust TestContainer functions to use self.identifier instead of self.uuid
- Simplify some control_method checks in TestContainer
> DAOS-7590 test: use container labels with daos by default (#11324)

- src/container/srv.c
- src/dtx/dtx_srv.c
- src/engine/srv.c
- src/engine/srv_internal.h
- src/engine/tls.c
- src/include/daos_srv/daos_engine.h
- src/object/srv_mod.c
- src/pool/srv.c
- src/rebuild/srv.c
- src/vos/vos_common.c
- src/vos/vos_ts.h
In order to save some memory, VOS should only allocate tls on xtreams that use VOS.
Additionally, it can avoid allocating the timestamp cache for the rdb xstream.
The main xstream calls into vos_db_init which will also use VOS so it needs to have tls as well.
In the future, we should look into supporting VOS
api calls without tls initialized or in the sys_db case, we could potentially just initialize it and
finalize it for the duration of the call only.
> DAOS-13190 engine: Rework engine tls initialization

- src/vos/vos_gc.c
In gc_add_item(), we shouldn't internally trigger gc_reclaim_pool() when gc_bin_add_item() failed for ENOSPACE, otherwise, nested tx begin in gc_reclaim_pool() could hit assert since the outer tx may have aborted due to ENOSPACE.
Instead of performing inline gc_reclaim_pool() on ENOSPACE, we'd rely on VOS sys space reserving to ensure gc_add_item() never fail for ENOSPACE, if it really fail for ENOSPACE due to fragmentation or disabled reserving (for tiny pool), there is nothing we can do at the moment.
This patch also fix few error propagating issues in GC.
> DAOS-12901 vos: Don't do inline gc_reclaim_pool()

- ci/jira_query.py
> DAOS-623 build: Retry jira-query once if it gets rate-lmited.

- src/bio/bio_wal.c
- src/common/dav/memblock.c
Introduced a cosmetic change to prevent valgrind reporting uninitialized values errors (false positives) in the WAL replay and data fetch paths.
> DAOS-13144 common: Fixed valgrind errors around DAV.

- docs/user/blockdev.md
- mkdocs.yml
Integrate instructions on how to export a POSIX container as a block device.
Signed-off-by: Denis Nuja <denis.nuja@croit.io>
Acked-by: Johann Lombardi <johann.lombardi@intel.com>
> DAOS-11869 doc: add documentation for NVMe-oF export

- src/client/dfs/dfs.c
To be consistent with access().
To check permission bit for root too.
> DAOS-13156 api: return EACCES instead of EPERM in dfs_access()

- src/tests/ftest/erasurecode/multiple_failure.yaml
Let's use G1 for multiple failure tests for 2.2 to avoid layout upgrade.
Test-tag: ec_multiple_failure
> DAOS-10681 tests: use G1 for multiple failure test

- src/include/daos_task.h
> DAOS-12841 include: fix check warning

- src/tests/ftest/dfuse/enospace.py
- src/tests/ftest/dfuse/sparse_file.py
- DAOS-623 engine: Update a warning in the IV code.
- DAOS-10383 ftest: Improve failure reporting for enospace test.
> DAOS-10383 test: Improve failure reporting for enospace test.

- docs/user/python.md
- src/client/pydaos/__init__.py
- src/client/pydaos/pydaos_core.py
- src/client/pydaos/pydaos_shim.c
- src/client/pydaos/raw/README.md
- utils/node_local_test.py
> DAOS-10930 pydaos: Adding option to pass the object class for dictionary as an argument.

- src/bio/bio_internal.h
- src/bio/bio_monitor.c
- src/bio/bio_xstream.c
Wait for health collecting done before the bdev subsystem is finalized, otherwise, health collecting completion callback could access freed spdk_bdev_io.
> DAOS-13176 bio: wait for health collecting done

- ci/unit/test_nlt_node.sh
> DAOS-13241 test: Increase NLT log size from 800 MiB to 900 MiB

- src/bio/bio_xstream.c
- src/include/daos/tests_lib.h
- src/tests/suite/daos_aggregate_ec.c
- src/tests/suite/daos_container.c
- src/tests/suite/daos_dist_tx.c
- src/tests/suite/daos_epoch.c
- src/tests/suite/daos_mgmt.c
- src/tests/suite/daos_obj.c
- src/tests/suite/daos_obj_ec.c
- src/tests/suite/daos_pool.c
- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
- src/tests/suite/daos_rebuild_ec.c
- src/tests/suite/daos_rebuild_simple.c
- src/tests/suite/dfs_par_test.c
- src/tests/suite/dfs_unit_test.c
For daos functions, use the assert that will print the string error code rather than hex codes.  Makes it easier in triage.
> DAOS-623 test: Use assert_rc_equal or assert_success

- src/common/ad_mem.c
- src/common/ad_mem.h
- src/common/ad_tx.c
- src/common/tests/ad_mem_tests.c
Coverity fixes for:
CID 1347[813, 808, 807, 806, 801, 797, 795, 794, 793, 790]
> DAOS-13110 common: coverity fixes for vos_on_blob

- docs/overview/security.md
The Security Model document was lacking details about the importance of certificates in client and admin authorization.
Doc-only: true
> DAOS-13116 doc: Add cert details to security overview

- Jenkinsfile
- src/vos/tests/vts_io.c
Fail the build if any Valgrind test detects an error.
> SRE-1729 Build: Fail build Valgrind Errors

- Doxyfile
> DAOS-13223 cq: Fail Doxygen build on warnings.

- src/bio/bio_xstream.c
- src/control/fault/code/codes.go
- src/control/server/config/faults.go
- src/control/server/config/server.go
- src/control/server/config/server_test.go
- src/control/server/faults.go
- src/control/server/server_utils.go
- src/control/server/server_utils_test.go
Reduced the minimal per target hugepages requirement from 1GB to 256MB,
changed initial allocation from 256MB to 192MB.
Remove hard validation checks if number of hugepages specified in the
config file is not able to be allocated. Control-plane will continue
to auto-calculate and assign number of huge pages in server config
file based on 1gib per engine target to satisfy DMA buffer requirement
for average workload but if this requirement cannot be met then a
NOTICE log level message will be printed but the engine will still be
able to start. Memory requirement validation will be left to the
engine after process is spawned. This change allows engine to be
started with lower number of hugepages allocated in resource
constrained environments. When there are insufficient free hugepages
to …
> DAOS-13232 bio: adjust minmal hugepages requirement

- src/tests/ftest/ior/small.yaml
This patch extends the ior timeout for the ior_small test from 60 seconds to 75 seconds.  This change allows the test to pass with the TCP provider.
> DAOS-12725 test: IOR/small.py Failed (with TCP): Timeout detected.

- mkdocs.yml
revert formatting changes in mkdocs.yml that broke the mkdocs/mike documentation system.
> DAOS-9355 doc: fix mkdocs.yml broken by PR10639

- site_scons/components/__init__.py
- src/cart/crt_hg.c
- src/cart/utils/memcheck-cart.supp
- utils/build.config
- utils/test_memcheck.supp
> DAOS-12601 mercury: update to 2.3.0rc5

- src/rdb/rdb.c
- src/rdb/rdb_internal.h
- src/rdb/rdb_raft.c
- src/vos/vos_pool.c
For MD on SSD RDB pools, we need to checkpoint the the metadata to the metadata blob to free space in the WAL.
> DAOS-13186 rdb: Enable vos checkpoint ULT in rdb

- Jenkinsfile
Limit the tests run in the md-on-ssd-testing branch until the feature/vos_on_blob branch is merged with master.
> DAOS-12562 test: Limit md-on-ssd-testing testing until merge

- src/tests/ftest/checksum/csum_error_logging.py
Skip-nlt: true
Test-tag: test_csum_error_logging
> DAOS-12888 test: skip non data device checking

- src/include/daos_types.h
Added Doxygen comments.
Doc-only: true
> DAOS-7983 doc: Document daos_rank_uri struct members

- src/client/pydaos/pydaos_shim.c
- utils/node_local_test.py
also cleanup some error printing in pydaos
> DAOS-13300 pydaos: Use EX mode for container open in checker

- src/dtx/dtx_resync.c
- src/dtx/dtx_rpc.c
There is race between DTX refresh RPC being triggered on current engine and DTX commit RPC on remote leader. Related DTX entry on current engine may has been committed by race before DTX refresh RPC being replied. And it is possible that related DTX entry on remote leader may be removed by DTX aggregation before the DTX refresh RPC being handled on the leader. Under such case, the leader will reply -DER_NONEXIST to the DTX refresh RPC sponsor that may be misguided as ever missing related DTX abort RPC and try to abort such DTX locally. We need to check (the DTX existence) such case to avoid confused abort failure.
> DAOS-13124 dtx: handle race between DTX refresh and DTX commit

- src/control/server/ctl_storage_rpc_test.go
> Fix control-plane unit tests after merge

- src/chk/chk_engine.c
- src/chk/chk_leader.c
If someone stop daos check while some check interactions to be handled, then related inconsistency should not be marked as 'ignored', otherwise, it will misguide the user.
> DAOS-13197 chk: properly handle interrupted check interaction

- src/tests/ftest/launch.py
Set execute permission on temporary test directories so other users can create files/logs/etc. in the directories. E.g. daos_agent
> DAOS-13325 test: set execute permission on tmp test dirs

- src/pipeline/cli_mod.c
- src/pipeline/srv_pipeline.c
- src/tests/suite/daos_pipeline.c
> DAOS-13161 pipeline: fix coverity issues

- src/engine/sched.c
> DAOS-11632 common: clean up log error messages that aren't really errors

- debian/changelog
- utils/rpms/daos.spec
> DAOS-13378 build: fix libfabric/libfabric1 dependency mismatch on SuSE

- docs/admin/pool_operations.md
Disable parallel drain/reintegrate/extend operation in document.
> DAOS-13063 admin: Disable parallel rebuild operation in document

- src/placement/jump_map.c
- src/placement/tests/jump_map_place_obj.c
The rebuilding shard should be reintegrated to its replacement target as well, since the DWON shards
are taken into account in all cases.
Features: rebuild reintegration
> DAOS-13200 placement: reintegrate rebuilding shard

- site_scons/components/__init__.py
> DAOS-12694 cart: Fix pylint warning

- src/tests/ftest/daos_test/suite.yaml
Before this change, no particular daos_test '-s' command line argument (number of pool service replicas) is given when running test_daos_md_replication. This results in the daos_test svc_nreplicas variable taking a default value (1). The code in mdr_stop_pool_svc() gracefully skips the main test logic, since at least 3 pool service replicas are necessary in this test. The test "passes", while not running the objective functionality.
With this change, suite.yaml adds command-line argument "-s5" when running this test.
Test-tag: test_daos_md_replication
> DAOS-13440 test: daos_test -R: specify number of svc replicas

- src/dtx/dtx_rpc.c
The drr->drr_cb_args[n] contains external allocated "dsp" that needs to be released during failure handling.
> DAOS-13432 dtx: fix memory leak for dtx_refresh_internal

- docs/admin/predeployment_check.md
check firewall as part of pre-deployment checklist
Doc-only: true
> DAOS-9355 doc: add firewall check to pre-deployment checklist

- src/tests/ftest/cart/util/cart_utils.py
- Update cart utils to parse out additional envariables such as HG_LOG_LEVEL and HG_LOG_SUBSYS
> DAOS-13450 cart: Update cart_utils.py to parse out HG_ variables

- src/tests/ftest/util/job_manager_utils.py
First check that `self.job` is set before trying to kill it.
> DAOS-13470 test: fix edge case in JobManager.kill()

- src/include/daos_srv/daos_engine.h
- src/include/daos_srv/vos.h
- src/object/srv_obj_migrate.c
- src/placement/pl_map.c
- src/rebuild/scan.c
- src/tests/suite/daos_upgrade.c
- src/vos/vos_internal.h
- src/vos/vos_io.c
- src/vos/vos_obj.c
- src/vos/vos_obj.h
- src/vos/vos_obj_index.c
Upgrade id layout version for non EC object.
migrate specific shard for non-EC object upgrade.
Delete the old layout version object once upgrade
finished.
> DAOS-13379 object: fixes for object upgrade

- src/control/cmd/daos_agent/config.go
- src/control/cmd/daos_agent/config_test.go
- src/control/cmd/daos_agent/infocache.go
- src/control/cmd/daos_agent/infocache_test.go
- src/control/cmd/daos_agent/start.go
- src/control/lib/cache/cache.go
- src/control/lib/cache/cache_test.go
* Simplify and generalize cache.ItemCache
* Rework agent.InfoCache to use reworked cache.ItemCache
> WIP cache suggestions

- src/bio/bio_monitor.c
- src/include/daos_srv/bio.h
- src/mgmt/srv_query.c
Use queried value after the query ULT executed.
> DAOS-13472 bio: fix defect in ds_mgmt_get_bs_state()

- src/tests/ftest/mdtest/small.yaml
To avoid frequent RPC resending caused by short crt_timeout.
> DAOS-13413 tests: use longer crt_timeout for mdtest

- site_scons/site_tools/compiler_setup.py
- src/client/api/init.c
- src/engine/init.c
- src/include/daos/debug.h
- src/tests/suite/daos_pipeline.c
> DAOS-13427 pipeline: Do not enable the pipeline module in release builds

- src/client/api/rpc.c
Test-tag: test_rebuild_no_capacity
> DAOS-13479 client: init base_opc in daos_rpc_proto_query()

- src/control/server/config/server.go
- src/control/server/ctl_storage_rpc.go
- src/control/server/server_utils.go
- utils/config/daos_server.yml
Follow-up changes relating to code review comments on PR-11978.
> DAOS-13354 control: Minor code review related fixes

- src/bio/bio_monitor.c
Drain the health collecting request before putting I/O channel.
> DAOS-13176 bio: Drain health collecting request

- src/tests/suite/daos_rebuild.c
- src/tests/suite/daos_rebuild_common.c
Reintegrate needs to wait for rebuild finish.
> DAOS-13191 tests: wait rebuild finish

- src/vos/vos_tree.c
Properly propagate error in svt_rec_free_internal().
> DAOS-13341 vos: propagate error in svt_rec_free_internal()

- utils/node_local_test.py
> DAOS-13477 test: Disable some checks from daos_fs_fix test.

- src/client/dfuse/pil4dfs/int_dfs.c
We do need to run DAOS benchmark on Frontera at TACC which runs CentOS 7.9. It would be helpful to let libpil4dfs support CentOS 7.9.
> DAOS-13483 client: to fix libpil4dfs compiling issue on CentOS 7.9

- src/object/srv_obj_migrate.c
- src/tests/suite/daos_drain_simple.c
When rebuilding the data from parity shard, it should choose minimum epoch only from the parity epochs.
Feature: ec rebuild
> DAOS-12945 object: choose minimum epoch correctly

- src/rebuild/rebuild_iv.c
Do not update rebuild iv cache if the rebuild has
been finished or aborted.
Features: rebuild reintegrate
> DAOS-13279 rebuild: Do not update rebuild IV cache

- src/client/dfuse/SConscript
- src/client/dfuse/pil4dfs/int_dfs.c
Ignore "-Wnonnull-compare" only for the places where necessary inside int_dfs.c
> DAOS-13500 build: Remove '-Wno-error=nonnull-compare'

- Jenkinsfile
Add running pr and daily_regression tagged tests every day.
> DAOS-13528 test: Run tests with md on ssd daily

- Jenkinsfile
Moving daily builds of the release/2.2 branch to a weekly frequency.
> DAOS-13526 test: Disable daily testing of release/2.2 branch

- src/control/server/instance.go
I carelessly introduced a local variable with a name that is against the standard Go coding style. This patch renames the local variable.
> DAOS-13448 control: Fix a silly variable name

- src/tests/ftest/util/test_utils_pool.py
These functions are unused, and it's preferred to use dmg/daos instead
of the API:
- display_pool_rebuild_status
- get_pool_rebuild_status
- check_pool_space
> DAOS-13534 test: remove unused pool functions

- src/tests/ftest/launch.py
Set wrx permission for /var/tmp/daos_testing on localhost
> DAOS-13325 test: set wrx for daos_testing on localhost

- src/include/daos/placement.h
- src/include/daos_srv/rebuild.h
- src/object/srv_obj_migrate.c
- src/placement/pl_map.c
- src/pool/srv_pool.c
- src/rebuild/scan.c
- src/rebuild/srv.c
During PS leader switch, the new leader should check if there are ongoing rebuild, whose reclaim epoch should be used to reclaim the half rebuild object.
During extend/reintegration/drain, if there are new targets failure, then the object impacted by the new failure, are actually rebuilt to the new replacement target, so during the reclaim phase, these rebuilding shards can be skipped.
Do not need migrate the object once the rebuild is done.
Features: rebuild reintegrate
> DAOS-13200 rebuild: fix reclaim epoch for extend (#12050)

- src/object/srv_ec_aggregate.c
Clear extent list before reset extent cnt to 0 in
agg_reset_dkey_entry()
> DAOS-13295 object: clear extent list during reset

- .github/workflows/landing-builds.yml
- utils/ci/run_in_gha.sh
> DAOS-13573 test: Change NLT settings in GHA.

- mkdocs.yml
mkdocs.yml update to v2.4
Doc-only: true
> DAOS-9355 doc: mkdocs.yml update to v2.4

- mkdocs.yml
mkdocs.yml update to v2.5
Doc-only: true
> DAOS-9355 doc: mkdocs.yml update to v2.5

- src/control/events/pubsub_test.go
The TestEvents_PubSub_Debounce_Cooldown go unit test is intermittently
failing due to sporadic VM multi-millisecond lockups causing cooldown
timeout expiry. The test debug shows events having >10ms latency very
occasionally resulting in cooldown period being exceeded and more than
expected events being recorded. To ensure that the test is reliable in
CI this change applies the following approach:
- Increase cooldown time period to 25ms from 10ms to reduce the chance
of false expiry.
- Validate that single events are recorded from each outer-loop
iteration (where event incarnation is increased) and incarnation
value matches what is expected whilst all other events are ignored
through debounce logic
- If test loop gets stalled for more or equal length of time to the
cooldown period, restart …
> DAOS-13089 control: Fix debounce evt unit test race

- src/control/cmd/daos_agent/fabric.go
- src/control/cmd/daos_agent/infocache.go
- src/control/cmd/daos_agent/infocache_test.go
- src/control/cmd/daos_agent/mgmt_rpc.go
- src/control/cmd/daos_agent/mgmt_rpc_test.go
- src/control/cmd/daos_agent/start.go
- Move fabric ready check into InfoCache so it is only performed when needed.
- Quiet some other noisy logging.
> DAOS-7029 control: Quiet noisy fabric ready logging

- Jenkinsfile
Disabling weekly runs of full_regression tagged functional tests on the release/2.2 branch with the tcp provider.
> DAOS-623 test: Disable provider-testing-tcp-2.2 timed builds

- Jenkinsfile
Update all Jenkinsfile cron entries to use UTC timezones and match exact branch names.
> DAOS-623 test: Jenkinsfile updates.

- Jenkinsfile
Disabling weekly runs of full_regression tagged functional tests on the release/2.2 branch.
> DAOS-623 test: Disable weekly-testing-2.2 timed builds

- src/tests/ftest/container/basic_snapshot.py
- src/tests/ftest/container/snapshot.py
- src/tests/ftest/control/dmg_pool_query_ranks.py
- src/tests/ftest/control/dmg_telemetry_basic.py
- src/tests/ftest/control/log_entry.py
- src/tests/ftest/control/log_entry.yaml
- src/tests/ftest/control/ms_failover.py
- src/tests/ftest/control/ms_resilience.py
- src/tests/ftest/deployment/agent_failure.py
- src/tests/ftest/deployment/critical_integration.py
- src/tests/ftest/object/integrity.py
- src/tests/ftest/pool/api_attribute.py
- src/tests/ftest/server/multiengine_persocket.py
- src/tests/ftest/util/apricot/apricot/test.py
- src/tests/ftest/util/general_utils.py
- src/tests/ftest/util/job_manager_utils.py
- src/tests/ftest/util/server_utils.py
- src/tests/ftest/util/soak_test_base.py
Test-tag: pr,vm ControlLogEntry BasicSnapshot snapshot,vm DmgPoolQueryRanks TestWithTelemetryBasic ManagementServiceFailover ManagementServiceResilience ObjectDataValidation PoolAPIAttributeTest AgentFailure CriticalIntegrationWithServers soak_smoke
- Add test to verify control log messages for various operations
- Add Test.random with a seed for reproducible random generation
- Update VM tests using random to use self.random
- Add general_utils.journalctl_time() to get the time formatted for journalctl
- Update tests to use this
> DAOS-13403 test: verify reliability and serviceability in logs (#12139)

- src/gurt/dlog.c
The cache reset needs to happen after the log masks is parsed. Otherwise, threads that are logging at the same time can cache the outdated value.
> DAOS-13592 gurt: Fix race in d_log_setmasks (#12287)

- Jenkinsfile
> DAOS-623 test: Fix timed weekly-testing builds.

- src/common/ad_mem.c
A continue in a while loop still checks the condition so setting O_CREAT will just exit the loop with fd as -1.  Addresses coverity 1397475
> DAOS-13603 common: Fix bug in ad_mem with open/create

- src/tests/ftest/container/snapshot_aggregation.yaml
Test-tag: test_snapshot_aggregation
> DAOS-13570 test: increase crt timeout

- src/tests/ftest/control/dmg_pool_query_test.yaml
> DAOS-13605 test: Fix RAM mem test for dmg_pool_query (#12313)

- docs/QSG/build_from_scratch.md
- docs/QSG/docker.md
- docs/index.md
- docs/release/release_notes.md
- docs/release/support_matrix.md
- docs/release/upgrading.md
document version fixup for v2.4 after branching release/2.4
Doc-only: true
> DAOS-9355 doc: document fixup for v2.4

- src/control/events/pubsub_test.go
The TestEvents_PubSub_Debounce_Cooldown go unit test is intermittently
failing due to sporadic VM multi-millisecond lockups causing cooldown
timeout expiry. The test debug shows events having >10ms latency very
occasionally resulting in cooldown period being exceeded and more than
expected events being recorded. To ensure that the test is reliable in
CI this change applies the following approach:
* Increase cooldown time period to 25ms from 10ms to reduce the chance
of false expiry.
* Validate that single events are recorded from each outer-loop
iteration (where event incarnation is increased) and incarnation
value matches what is expected whilst all other events are ignored
through debounce logic.
* If test loop gets stalled for more or equal length of time to the
cooldown period, …
> DAOS-13089 control: Fix debounce evt unit test race (#12260)

- src/control/cmd/daos_agent/fabric.go
- src/control/cmd/daos_agent/infocache.go
- src/control/cmd/daos_agent/infocache_test.go
- src/control/cmd/daos_agent/mgmt_rpc.go
- src/control/cmd/daos_agent/mgmt_rpc_test.go
- src/control/cmd/daos_agent/start.go
- Move fabric ready check into InfoCache so it is only performed when needed.
- Quiet some other noisy logging.
> DAOS-7029 control: Quiet noisy fabric ready logging (#12298)

- ci/provisioning/post_provision_config_common_functions.sh
Support the new testing branch naming format that can contain the version number in the middle of the branch name.
> DAOS-12648 ci: Adding support for new 2.4 testing branches.

- src/client/dfuse/pil4dfs/int_dfs.c
Add return value for discover_dfuse() and discover_daos_mount().
> DAOS-13574 client: add return value for discover_dfuse()

- utils/build.config
> DAOS-13593 build: update to mercury 2.3.0

- src/tests/ftest/util/mdtest_test_base.py
Currenly the mdtest_test_base does not allow using other mpi_types for mpich.
Test-tag: mdtest mpiio mpich
> DAOS-13661 test: Allow different mpi_types for mdtest

- src/control/cmd/daos_agent/config.go
- src/control/cmd/daos_agent/config_test.go
- src/control/cmd/daos_agent/fabric.go
- src/control/cmd/daos_agent/fabric_test.go
- src/control/cmd/daos_agent/infocache.go
- src/control/cmd/daos_agent/infocache_test.go
- src/control/cmd/daos_agent/mgmt_rpc.go
- src/control/cmd/daos_agent/mgmt_rpc_test.go
- src/control/cmd/daos_agent/start.go
- src/control/lib/cache/cache.go
- src/control/lib/cache/cache_test.go
- src/control/lib/hardware/fabric.go
- src/control/lib/hardware/fabric_test.go
- src/control/lib/hardware/mocks.go
- utils/config/daos_agent.yml
These two commits required some significant changes to successfully merge from master.
> DAOS-7029 control: Add refresh methods for agent cache (feature/multiprovider)

- src/tests/ftest/soak/harassers.yaml
- src/tests/ftest/soak/smoke.yaml
- src/tests/ftest/soak/stress.yaml
- src/tests/ftest/util/soak_utils.py
Use --disable-caching for fio jobs to improve perf
> DAOS-11610 test: change dfuse caching param for fio (#12321)

- src/client/dfs/dfs.c
> DAOS-13598 dfs: Convert a return code correctly in dfs_read.

- src/client/java/daos-java/pom.xml
- src/client/java/hadoop-daos/pom.xml
- src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/Constants.java
- src/client/java/hadoop-daos/src/main/java/io/daos/fs/hadoop/DaosFileSystem.java
- src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosFSFactory.java
- src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosFileSystemContractIT.java
- src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/DaosFileSystemTest.java
- src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/contract/DaosContractAppendAsyncIT.java
- src/client/java/hadoop-daos/src/test/java/io/daos/fs/hadoop/contract/DaosContractAppendIT.java
- src/client/java/hadoop-daos/src/test/resources/contract/daos.xml
- src/client/java/pom.xml
For now, the Java code runs with Java 8. We want to support higher JDK version, 11, which has better GC perf.
We added a new maven profile for JDK 11 so that both JDK 8 and JDK 11 are supported. I also fixed some integration test failures along this PR.
> DAOS-13511 [Java] Support JDK11

- src/common/ad_mem.c
A continue in a while loop still checks the condition so setting O_CREAT will just exit the loop with fd as -1.  Addresses coverity 1397475
> DAOS-13603 common: Fix bug in ad_mem with open/create (#12320)

- src/client/serialize/daos_serialize.c
- src/tests/ftest/datamover/serial_small.py
Features: DmvrSerialLargePosix DmvrSerialSmall
- Fix error handling in deserialize_roots
- H5Tget_size returns 0 on error, not a negative
> DAOS-13597 tools: coverity ids 22055, 21738, 21798 (#12319)

- src/control/cmd/daos/acl.go
If the name doesn't contain an '@', it is assumed to be a local user or group name.
> DAOS-13645 control: Make '@' optional in owner user/group

- Jenkinsfile
Remove reference to pipeline-lib and trusted-pipeline-lib PRs.
Skip-func-hw-test-medium-tcp-provider: true
> DAOS-13648 test: Update Jenkinsfile

- src/tests/suite/daos_checksum.c
Test-tag: test_daos_checksum
For 2.4
Cherry-picked: PR12318
> DAOS-13437 csum: Unskip tests (#12318)

- src/common/tests/acl_api_tests.c
The daos_acl_size function could return an error, although the test expects to succeed.
> DAOS-13720 common: Check return code for negative value

- src/client/api/event.c
- src/client/array/dc_array.c
- src/client/ds3/bucket.c
- src/client/kv/dc_kv.c
- src/object/cli_obj.c
- src/tests/suite/daos_kv.c
- Fix for coverity: 1449753 1449752 1449751 709506 1449749 1449748.
- Remove some uneeded allocations in array set size when adding 1 record.
> DAOS-13711 client: several coverity silencing fixes

- utils/build.config
> DAOS-13593 build: update to mercury 2.3.0 (#12348)

- src/cart/crt_init.c
> DAOS-623 cart: fix typo in env name

- src/tests/ftest/util/apricot/apricot/test.py
Add utilizing the branch-specific skip-list for this branch.
Test-tag: test_csum_error_logging
> DAOS-13648 test: Add release/2.4 skip-list

- docs/user/filesystem.md
> DAOS-13707 doc: add libpil4dfs in filesystem.md

- src/control/cmd/daos/main.go
- utils/node_local_test.py
If DD_STDERR wasn't already set, we should log ERR-level logs to stderr, to make libdaos errors easier for users to debug.
> DAOS-13090 control: Output ERR logs to stderr for daos tool (#12307)

- src/rdb/rdb_raft.c
The rdb_raft_load_replicas includes an unnecessary assignment of zero to rc.
> DAOS-13643 rdb: Remove an unnecessary assignment

- docs/user/filesystem.md
> DAOS-13707 doc: add libpil4dfs in filesystem.md (#12457)

- src/tests/suite/daos_md_replication.c
Test-tag: DaosCoreTest,test_daos_md_replication
Test-repeat: 5
> DAOS-13584 tests: limit pool query test time 

- ci/bullseye_generate_report.sh
- utils/docker/Dockerfile.el.8
- utils/docker/Dockerfile.el.9
> DAOS-13167 test: Enable bullseye build.

- utils/build.config
- add prov/tcp patch to fix registration lock issue
- add prov/opx patch to fix 32-bit conversion issue
> DAOS-13626 build: add libfabric 1.18.0 patches

- utils/build.config
- add prov/tcp patch to fix registration lock issue
- add prov/opx patch to fix 32-bit conversion issue
> DAOS-13626 build: add libfabric 1.18.0 patches (#12487)
