daos-stack/daos

src/object/srv_io_map.c
If p_maps in ds_iom_create is NULL then the memory
allocated in the function will never be freed. Because
there is no reason to call ds_iom_create without p_maps,
changed the function to assert that p_maps was passed,
then can remove the conditional.
=> DAOS-10088 io: Fix memory escape

src/client/api/container.c, src/client/api/pool.c, src/include/daos_cont.h, src/include/daos_pool.h
We need macros to enforce middleware call daos_pool_connect2(),
daos_cont_open2(), and daos_cont_destroy2(). Without such macros, 
middleware compiled with DAOS master breaks in release 2.0.
Signed-off-by: Lei Huang <wiliam_huang@hotmail.com>
=> DAOS-10076 API: Macros are needed for middleware compatibility

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_resync.c, src/dtx/dtx_srv.c, src/include/daos_srv/vos_types.h, src/vos/vos_dtx_iter.c, src/vos/vos_internal.h, src/vos/vos_obj.c, src/vos/vos_obj_index.c
When a DAOS target is down, related active DTX entries on it will
be handled via DTX resync by other alive targets: either committed
or aborted. When the target is reintegrated back, these DTX entries
are stale and need to be discarded before doing real data migration.
=> DAOS-9860 dtx: discard stale active DTX entries for reintegration

src/common/checksum.c, src/common/tests/checksum_tests.c, src/include/daos/checksum.h, src/include/daos_srv/srv_csum.h, src/include/daos_srv/vos.h, src/object/srv_csum.c, src/object/srv_obj.c, src/object/tests/srv_checksum_tests.c, src/vos/tests/vts_checksum.c, src/vos/tests/vts_io.c, src/vos/vos_io.c
During a vos_fetch_begin() the checksums are collected into an
array of csum_info structures. These structures pointed to the
checksums in SCM. However, after vos_fetch_begin() a call to
bio_iod_prep() can yield because of NVMe access. During the yield
the checksum the csum_info structures reference could change,
corrupting the csum. Instead of pointing to the checksum in SCM
we need to copy it into memory.
In order to manage the csum_infos and csum_buf in memory a new
structure and functions for better managing a list
of csum_infos is introduced. These functions and structure are
used during vos fetch.
=> DAOS-9725 csum: Eliminate potential race condition for fetch

src/tests/ftest/launch.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/distro_utils.py
Adding support for Rocky Linux and AlmaLinux to the avocado.utils.distro method.
Test-tag: pr harness_advanced_test
=> DAOS-9994 test: Updating detect() method with missing distros (#8420)

src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c
Even if no application open the container, or someone just did DTX
resync against the container but current DTX resync is for discard
old DTX entries, then current DTX resync should not be skipped.
=> DAOS-9860 dtx: do not skip DTX resync

src/tests/ftest/control/dmg_telemetry_io_latency.py, src/tests/ftest/control/dmg_telemetry_io_latency.yaml
Verify the IO dtx "committed" metrics by running IOR multiple times over
different transfer sizes to confirm values. Also update the expected value
for engine_io_dtx_committed_min to 1 and use baseline io dtx values
when verifying values.
Skip-scan-centos-rpms: True
Skip-scan-centos-15-rpms: True
Test-tag: test_io_latency_telemetry test_ior_latency_telemetry test_ior_dtx_telemetry offline_extend_oclass
=> DAOS-8973 test: Verify correctness of telemetry data for I/O dtx committed metrics (#7412)

debian/daos-client.preinst, debian/daos-server.preinst, utils/rpms/daos.spec
Create daos_daemons secondary group for daos_server and daos_agent,
to enable both daemons to write their logfiles into the same
non-world-writeable logfile directory (being writeable by the
daos_daemons group will be sufficient).
=> DAOS-6344 build: create daos_daemons secondary group (#8331)

src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/config_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/cmd/daos_agent/start.go, src/control/lib/control/network.go, utils/config/daos_agent.yml
This patch allows the agent to support secondary providers if any
are returned by the server in the GetAttachInfo call.
The client requires no knowledge of primary and secondary providers.
The agent decides which provider to return based on its config file.
- Add support for secondary providers to GetAttachInfo messages.
- Add optional "provider" parameter for the agent configuration. If
specified the agent will search secondary providers for the
requested provider, and return the appropriate network info to
the client as if it was the primary provider.
=> DAOS-9623 agent: Support configurable provider

src/control/lib/hardware/hwloc/provider_test.go
On more complex systems, the unit test for the worst-case
uncached topology will time out with a large number of
goroutines. In this case, reduce the number of goroutines
to a number that is likely to pass while still testing
thread-safety.
=> DAOS-8905 test: Adjust hwloc test for real hardware

src/tests/ftest/rebuild/with_ior.py
@rs_state expect rebuild not started(DRS_NOT_STARTED) which is 1 after pool created,
0 means DRS_IN_PROGRESS which is not case here, fix it.
Test-tag: rebuildwithior
=> DAOS-10126 test: fix rs_state before rebuild

src/object/cli_ec.c, src/object/cli_obj.c, src/object/obj_internal.h, utils/docker/Dockerfile.checkpatch
If with single data target shard, use RPC inline transferring for small
size IO.
=> DAOS-10015 EC: refine for EC IO with single data target case

src/tests/ftest/nvme/io_verification.py, src/tests/ftest/nvme/io_verification.yaml
Description: Cherry pick io_verification.py and io_verification.yaml to release 2.0
Test-tag: nvme_io_verification
=> DAOS-9614 test: Cherry pick to rel_2.0 nvme io_verification script failed due to DER_NOSPACE

src/tests/ftest/ior/crash_ior.yaml
Increasing block size for ior run command
to increase aggregate file size. As the hardware
medium tests have moved to verbs the orignal
checks inside the test for write and read completion
are at borderline and the test has the scope to
return false failure intermittently, hence increasing
the aggregate io size 1.5 times that of previous value.
=> DAOS-9342 test: Increasing block size for ior run command (#7755)

src/control/server/init/setup_spdk.sh
Script is run by daos_admin in privileged execution mode so sudo
is unnecessary.
=> DAOS-10152 control: Remove sudo from SPDK setup script

src/control/lib/control/rpc.go, src/control/lib/control/rpc_test.go
In the event that a control server's RPC response
indicates that the RPC is unimplemented, don't
retry it and return the error immediately.
=> DAOS-9584 control: Don't retry unimplemented RPCs

src/engine/srv.c
It looks like the OS can still decide to move target to a different
CPU. Try to use strict core binding if supported by the platform.
=> DAOS-10124 engine: use strict CPU binding

src/control/lib/hardware/fabric.go, src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/ucx/disabled_bindings.go
When a given fabric provider is unsupported, don't
emit an info or error message, just skip it.
=> DAOS-9555 control: Suppress spurious messages for unsupported fabrics

src/control/cmd/daos/main.go, src/control/cmd/daos_agent/main.go, src/control/cmd/daos_server/main.go, src/control/lib/hardware/hwprov/topology_cmd.go
Not a perfect home for it, but isolates the dependencies
on hwloc, libfabric, etc. Also removes the dump-topology
subcommand from the daos utility because it pulls in
unnecessary dependencies from the control plane.
=> DAOS-10019 control: Move TopologyCmd to hwprov package

src/dtx/dtx_common.c
If there are too many sub requests to be handled by IO forward ULT,
then need to yield CPU periodically during the process (even if for
handling failure case) to avoid holding CPU for too long time.
=> DAOS-10131 dtx: IO forward ULT avoids holding CPU for too long

src/tests/ftest/ior/intercept_basic.py, src/tests/ftest/ior/intercept_basic.yaml, src/tests/ftest/ior/intercept_messages.py, src/tests/ftest/ior/intercept_multi_client.py, src/tests/ftest/ior/intercept_multi_client.yaml, src/tests/ftest/ior/intercept_verify_data_integrity.py, src/tests/ftest/util/ior_intercept_test_base.py, src/tests/ftest/util/ior_test_base.py
Test-tag: ior_intercept ior_intercept_basic ior_intercept_multi_client
Rework interception performance tests to be more robust
- Create ior_intercept_test_base.py for common test procedure
- Run with 60s stonewall for 3 iterations
- Only check "Max" value until we have a better handle on variance
- Add human-readable description of performance difference
- Update tags for interception tests
Conflicts:
src/tests/ftest/ior/intercept_multi_client.py
src/tests/ftest/ior/intercept_multi_client.yaml
=> DAOS-9237 test: rework interception perf tests (#8112)

src/rdb/rdb_kvs.c, src/rdb/rdb_raft.c, src/rdb/rdb_tx.c, src/rdb/rdb_util.c
The rdb module caches <KVS path, VOS object ID> pairs for the Log
Container at the last index. When popping log entries, we should empty
this cache just in case that the popping reverts some KVS create
operations and leaves incorrect <KVS path, VOS object ID> pairs in the
cache. This patch adds two such rdb_kvs_cache_evict calls that are
missing when popping entries and when loading snapshots.
The rdb_raft_log_offer_single function has a few error paths that
discards the same index more than once. Since discarding an index may be
expensive, this patch avoids that.
=> DAOS-10179 rdb: Add missing KVS cache evictions

src/vos/vos_obj_index.c
If object creating before following change:
89809(DAOS-9053 vos: Track accurate latest write time for an object (#7845))
Which could happen while upgrading DAOS from 2.0 to 2.2.
It is possible @vos_max_write is zero with an existed object,
assign current epoch to avoid later assertion.
=> DAOS-10141 vos: init vo_max_write for upgrading case

src/control/system/database.go
Fixes a longstanding intermittent failure that can occur when a
node loses MS leadership and then regains it.
=> DAOS-10168 control: Don't exit monitoring loop on leadership loss

src/object/cli_ec.c, src/object/cli_obj.c
1. add orr_size_updated to only update the original iod_size
if the reasseblied iod_size has been updated by replied RPC.
2. Check efi_stripe_sgls, instead of efi_stripe_lists, which will
not be set for single value.
3. Remove unnecessary assert in obj_ec_recov_stripe(), since fail_info
list might be shared by multiple recover tasks, so one recov ent list
may not exist in one IOD.
=> DAOS-9636 EC: various fixes about EC

src/control/system/database.go
Fixes a longstanding intermittent failure that can occur when a
node loses MS leadership and then regains it.
=> DAOS-10168 control: Don't exit monitoring loop on leadership loss (#8522)

src/rebuild/scan.c
In rebuild_container_scan_cb() if ds_cont_fetch_snaps() failed,
vos_cont_close() will be not called.
=> DAOS-10187 rebuild: close vos container in rebuild_container_scan_cb()

src/cart/crt_iv.c, src/engine/server_iv.c
In ivc_on_put(), it will call ds_iv_ns_put() upon shutdown
case, so if ivo_on_put() failed, don't call it again.
=> DAOS-10186 cart_iv: fix wrong ivo_on_put call

src/control/cmd/daos_server/storage.go, src/control/common/storage/commands.go, src/control/fault/code/codes.go, src/control/server/storage/faults.go, src/control/server/storage/scm.go, src/control/server/storage/scm/ipmctl.go, src/control/server/storage/scm/ipmctl_test.go, src/control/server/storage/scm/mocks.go, src/control/server/storage/scm/provider.go
Add (-S N|--scm-namespaces-per-numa N) option to daos_server storage prepare
subcommand to enable creation of multiple SCM namespaces per NUMA node.
For example, on a typical dual-socket platform, the command:
daos_server storage prepare -s -S 2
would generate the following PMem block devices:
/dev/pmem0 /dev/pmem0.1 /dev/pmem1 /dev/pmem1.1
=> DAOS-9876 control: Create multiple SCM namespaces per NUMA node

src/pool/cli.c
pool_query_cb() calls d_rank_list_free(ranks) where ranks should be
assigned (non-NULL) when the preceding process_query_reply() succeeds.
However, Coverity is flagging the usage. Initialize ranks to NULL.
=> DAOS-9166 pool: coverity CID 351284 illegal accesses

src/object/srv_ec_aggregate.c
clear EC stripe list if EC aggregation is aborted, since post_cb
might be skipped.
Test-tag: largefilecount
=> DAOS-10147 EC: clear EC stripe list if EC aggregation is aborted

src/tests/ftest/launch.py, src/tests/ftest/util/server_utils_params.py
Adding additional launch.py command line options for on-site testing:
--disable_stop_daos    disables stopping daos_server and daos_agent
services after running a test file
--extra_yaml           enables specifying an additional yaml file to
supplement (override/append) existing test
yaml values
--timeout_multiplier   multiply any timeout value in the test yaml by
the specified value
Enabled verifying test yaml file modification without the need to
remotely contact the hosts specified with the --test_servers or
--test_clients arguments by combining the --list and --modify arguments.
Adding the ability to detect and use cxi as a provider.
Adding support for non-hexadecimal bdev_list placeholders
Adding debug option to view yaml variants which includes the combined
result of any extra yaml …
=> DAOS-8992 test: launch.py updates for on-site testing (#8229)

src/rebuild/rebuild_internal.h, src/rebuild/rebuild_iv.c, src/rebuild/scan.c, src/rebuild/srv.c, src/tests/ftest/daos_test/rebuild.yaml, src/tests/ftest/daos_test/suite.yaml
Let's wait for dtx resync to finish on all engines, then
start rebuild, to make sure rebuild will not miss any
un-commit data during rebuild/reintegration.
=> DAOS_10172 rebuild: wait dtx resync globally

src/container/srv_target.c, src/pool/srv_target.c
Stop container before abort ec_eqh ULT, to avoid container
EC aggregation ULT to access ec_eqh after abort ec_eqh ULT.
=> DAOS-9335 pool: stop container before abort ec_eqh ult

src/control/server/engine/config.go, src/control/server/engine/config_test.go, src/control/server/server_utils_test.go
Use a comma to separate the multiple provider list instead of a
space. This matches up with what CART is expecting.
=> DAOS-9623 control: Use comma separator for providers

src/tests/ftest/nvme/enospace.py, src/tests/ftest/util/ec_utils.py, src/tests/ftest/util/nvme_utils.py
Python background job is getting hung so removed the queue for result checking
and instead using the list.
Cleanup the code to use the ior local object instead of the self.ior as enospace
is running multiple IOR job and it's overlapping the container UUID.
Test-tag: der_enospace aggregationchecksum
Test-repeat: 5
=> DAOS-9729 Test: Removed the Python queue and used the list for result checking in thread

src/control/server/server.go
- Check all the fabric interfaces in the server.
=> DAOS-9623 control: Check multiprovider interfaces

src/control/common/proto/srv/srv.pb.go, src/control/server/mgmt_drpc.go, src/control/server/mgmt_drpc_checker.go, src/control/server/mgmt_drpc_checker_test.go, src/control/server/mgmt_system_test.go, src/engine/srv.pb-c.c, src/engine/srv.pb-c.h, src/proto/srv/srv.proto
Implement control plane handlers for the following
engine checker dRPC upcalls:
* CheckerListPools
* CheckerRegisterPool
* CheckerDeregisterPool
=> DAOS-9584 chk: Add srv handlers for checker upcalls

src/object/srv_ec_aggregate.c, src/vos/vos_aggregate.c, src/vos/vos_gc.c, src/vos/vos_query.c
Currently, we use tls to pass DTX handle in VOS. So if any ULT yield
or exit without reset the DTX handle, then it will affect subsequent
ULT's running.
On the other hand, for EC aggregation, since the aggregation leader
is always the last parity node that is also the DTX leader, then it
is unnecessary to trigger DTX refresh for EC aggregation. The patch
removes related logic and avoids the trouble caused by yield during
EC aggregation.
=> DAOS-10221 dtx: reset DTX handle before yield

src/control/server/mgmt_system_test.go, src/control/system/membership.go, src/control/system/membership_test.go
Relax the rejoin rules for this scenario which can occur
when the join partially succeeded (e.g. the member was added,
but the response was not sent). Adds test coverage for Join() handler.
=> DAOS-10222 control: Allow rejoin with NilRank

docs/release/release_notes.md
release_notes.md:
add the known limitation that DAOS 2.0 is setting rf_lvl=1
(rank=engine), and does not support setting it to 2 (server).
Doc-only: true
=> DAOS-10215 doc: redundancy level is fixed at 1 (rank=engine)

src/control/lib/hardware/ucx/ucx.go, src/control/lib/hardware/ucx/ucx_test.go
We were previously accepting only the ucx+dc alias. ucx+dc_x is
also valid.
=> DAOS-10256 control: Allow ucx+dc_x provider

src/pool/srv_pool.c
Reduce duration of sleep in the case of non-leader request from 1000 to
250 milliseconds and remove sleep in the case of pool map resize.
=> DAOS-8046 pool: Reduce sleep durations on retry (#8624)

docs/admin/performance_tuning.md, src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/config_test.go, src/control/cmd/daos_agent/start.go, utils/config/daos_agent.yml
A new daos_agent configuration option, disable_caching, can be used
to avoid caching the GetAttachInfo response and local fabric hardware
details when clients request engine URIs. If disable_caching is set to
true, the agent will query the access point and rescan the hardware
every time a client requests the URIs.
=> DAOS-8052 agent: Add disable_caching option to config

src/client/api/pipeline.c, src/include/daos_pipeline.h, src/tests/pipeline_common.c
Added API function to free allocated objects (filters and filter parts)
during pipeline construction. This can be expanded in the future when
we add more helper functions to make DAOS allocate all needed data for
the pipeline. Then, we can free also iovs used for data types and such.
Signed-off-by: Eduardo Berrocal <eduardo.berrocal@intel.com>
=> daos-10209 pipeline: freeing allocated structs

src/tests/ftest/control/dmg_pool_query_test.py
Pool query now provides "enabled_ranks" and "disabled_ranks" fields.
In the basic case, they aren't returned.
Features: pool_query
=> DAOS-10072 test: Add new pool query fields to test

src/tests/ftest/control/dmg_pool_query_test.py
Pool query now provides "enabled_ranks" and "disabled_ranks" fields.
In the basic case, they aren't returned.
Test-tag: pool_query
=> DAOS-10072 test: Add new pool query fields to test (#8656)

src/tests/ftest/control/dmg_telemetry_io_latency.py
Test-tag: test_ior_latency_telemetry
Summary: Update the avocado test-tag to include ib2 string.
=> DAOS-9744 test: Update the avocado tag with ib2

ftest.sh, src/tests/ftest/launch.py
Adding support for an updated default launch.py --nvme=auto:-3DNAND
argument to support inverted matching for newer clusters in CI.
=> DAOS_9562 test: Support VMD clusters w/ non-Optane NVMes (#8571)

src/control/lib/hardware/ucx/ucx.go, src/control/lib/hardware/ucx/ucx_test.go
We were previously accepting only the ucx+dc alias. ucx+dc_x is
also valid.
=> DAOS-10256 control: Allow ucx+dc_x provider (#8636)

src/vos/vos_aggregate.c
Fixed a typo in VOS aggregation.
=> DAOS-623 vos: fix typo in vos aggregation

src/tests/ftest/util/server_utils_base.py
Test-tag: offline_drain_multiple_pools  online_drain_with_csum
Test-repeat: 5
Summary:
- We are noticing intermittent SCM format timeout issues
due to format taking more than 30 seconds. Increasing
it to 45 seconds.
=> DAOS-10058 test: Update default SCM format timeout

src/tests/ftest/network/cart_self_test.py
Resolve intermittent daos engine start detection by using dmg to detect
the engine start.
Test-tag: cartselftest
=> DAOS-9353 test: Detect engine start via dmg for cart_self_test

src/tests/ftest/cart/test_rpc_to_ghost_rank.c
- Adjust ghost rpc test to expect potential DER_HG error when sending
RPC to a dead host
=> DAOS-10055 test: Adjust ghost rpc test

src/tests/ftest/util/command_utils.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/server_utils.py
Fix using the the user's primary group in chown commands instead of
assuming the group uses the same name as the user account.
=> DAOS-10164 test: Correct using user group for chown commands

src/object/srv_obj.c, src/object/srv_obj_migrate.c
During EC rebuild, it will do degraded fetch from multiple
shards, which may stored multiple check sums by dc_rw_cb()
from different shards, but it can not match these csums for
different shards, which makes it very difficult for EC rebuild.
So let's only use these direct check sum for replication
rebuild, and EC rebuild will re-calculate the check sum for
all cases.
=> DAOS-10145 rebuild: only fetch csum for replicate rebuild

src/tests/ftest/util/command_utils.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/server_utils.py
Fix using the the user's primary group in chown commands instead of
assuming the group uses the same name as the user account.
=> DAOS-10164 test: Correct using user group for chown commands (#8604)

src/tests/ftest/network/cart_self_test.py
Resolve intermittent daos engine start detection by using dmg to detect
the engine start.
Test-tag: cartselftest
=> DAOS-9353 test: Detect engine start via dmg for cart_self_test (#8576)

mkdocs.yml
fix mkdocs.yml edit_uri to point to release branch
Doc-only: true
=> DAOS-5579 doc: fix mkdocs edit_uri

docs/release/upgrading.md, mkdocs.yml
fix mkdocs.yml edit_uri to point to release branch
add dummy upgrading.ml
Doc-only: true
=> DAOS-9355 doc: fix mkdocs edit_uri

src/include/daos_srv/vos_types.h, src/vos/vos_aggregate.c, src/vos/vos_internal.h, src/vos/vos_obj.c, src/vos/vos_obj_index.c
DAOS-10227 vos: Export aggregatable time to filter callback (#8620)
If we simply export the aggregatable time, we don't need to call
into vos iterator functions to retrieve it and we can do the filter
directly in the aggregation filter callback. This will make it
simpler to use this timestamp in EC aggregation code.
Also, optimize the snapshot aggregation case to ignore trees that
have no aggregatable write after the low epoch.
=> DAOS-10227 vos: Export aggregatable time to filter callback (#8620)

src/control/cmd/dmg/system_test.go, src/control/lib/control/check.go, src/control/lib/control/system.go
Setting the system name in the RPC callback is racy.
=> DAOS-9586 control: Fix race in control RPCs

src/vos/vos_gc.c
When pools are too small, SCM space reserving is disabled. This
is problematic for tests that use tiny pools, fill them and then
try to delete a container. The gc bag isn't able to be allocated
for garbage collection. By pre-allocating the first bags this
issue can be worked around.
Also increased the bag size from 250 to 1018 (250 + 3 * 256) so each gc_bag consume 16K and can have more entries in each bag.
=> DAOS-9028 gc: Pre-allocate first GC bags

src/object/srv_ec_aggregate.c, src/tests/suite/daos_aggregate_ec.c
Since EC multiple shards fetch might mess up the reply CSUM,
so let's recalculate the checksum during EC aggregation.
=> DAOS-10145 EC: recalculate EC checksum for hole processing

src/common/pool_map.c, src/include/daos/cont_props.h, src/include/daos/pool_map.h, src/object/cli_obj.c, src/object/srv_ec_aggregate.c, src/placement/jump_map.c, src/placement/tests/jump_map_pda.c, src/placement/tests/place_obj_common.c, src/placement/tests/placement_test.c, src/rebuild/scan.c
1. avoid co-located shards in PD as far as possible
If all fault-domains used (or some failed) for the group within the PD,
then ignore the PD restrict to avoid co-located shards as far as
possible.
2. allow to select target from other PD if all domains in current PD occupied.
3. integrate with PDA property (get PDA parameter from cont prop)
Get PDA parameter from container property when calculate layout.
4. Rename PO_COMP_TP_PD as PO_COMP_TP_GRP, as performance domain
can be set at rack/group level.
=> DAOS-9548 placement: refine perf_dom handling

debian/changelog, debian/control, src/rdb/rdb_raft.c, utils/rpms/daos.spec
Since rdb no longer calls raft_add_node when offering each add-node log
entry, it should set the self node ID via the new raft_set_nodeid
method, right after creating the raft_server_t object.
Update raft to pick up the new raft_set_nodeid method as well as a few
minor fixes.
=> DAOS-10249 rdb: Fix uninitialized raft node ID (#8608)

src/control/common/proto/mgmt/addons.go, src/control/server/mgmt_cont.go, src/control/server/mgmt_cont_test.go, src/control/server/mgmt_pool_test.go, src/mgmt/srv_container.c
The dmg cont set-owner command wasn't updated to include the pool
service ranks.
Features: control security
=> DAOS-8752 control: Fix dmg cont set-owner to use svc ranks (#8668)

src/vos/evtree.c, src/vos/tests/vts_aggregate.c, src/vos/vos_internal.h
For RDB to perform 1000 txns/s, we need more bits to store
an epoch.   Use 42-bits of HLC instead of 32.  This gives us
roughly 116 years worth of epochs.
Also, don't update the epoch if it's lower than the stored
one.  This is a bug.
=> DAOS-10227 vos: Fix a bug and add more bits to timestamp

src/tests/ftest/osa/dmg_negative_test.yaml
Test-tag: osa_dmg_negative_test
Increase test timeout to account for different cluster hardware.
=> DAOS-9970 test: Increase test timeout for dmg_negative_test (#8365) (Cherry pick to release/2.0)

src/tests/ftest/control/dmg_telemetry_io_latency.py
Test-tag: test_ior_latency_telemetry
Update the avocado test-tag to include ib2 string.
=> DAOS-9744 test: Update the avocado tag with ib2 (#8547) (Cherry-pick for release/2.0)

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_srv.c, src/vos/ilog.c, src/vos/vos_dtx.c, src/vos/vos_internal.h, src/vos/vos_layout.h
master-commit: 2c69d62d4ff6fabcf47490d39af1e2637666cb43
There is race between DTX aggregation and DTX refresh. Consider the
following scenario:
The DTX leader triggers DTX commit for some DTX entry, then related
DTX participants (including the leader itself) will commit the DTX
entry on each own target in parallel. It is possible that the leader
has already committed locally but DTX aggregation removed the committed
DTX very shortly after the commit. On the other hand, on some non-leader
before the local commit, someone triggers DTX refresh for such DTX on
such non-leader. Unfortunately the DTX entry has already gone on the
leader. Then the non-leader will get -DER_TX_UNCERTAIN, that will cause
related application to fail unexpectedly.
So even if the system has DRAM pressue, we still need …
=> DAOS-10188 dtx: handle race between DTX aggregation and DTX refresh

src/object/srv_obj.c, src/object/srv_obj_migrate.c
During EC rebuild, it will do degraded fetch from multiple
shards, which may stored multiple check sums by dc_rw_cb()
from different shards, but it can not match these csums for
different shards, which makes it very difficult for EC rebuild.
So let's only use these direct check sum for replication
rebuild, and EC rebuild will re-calculate the check sum for
all cases.
Signed-off-by: Di Wang di.wang@intel.com
=> DAOS-10145 rebuild: only fetch csum for replicate rebuild (#8657)

src/client/api/client_internal.h, src/client/api/event.c
It is possible that the error is not reset to 0 when a process is retrieving the private event in a multi-threaded environment since another thread might have processed the event completion. 
add a lock on daos_event_t for events that are not part of an event queue, including the thread private event. This is required because in a multithreaded environment like dfuse, the event can be completed and the error set non
atomically, while the main thread sees the completion but before the error has actually set, causing the owner of the event to reset the event error, with the other thread setting the error after. this affects future use of the event that launches with ev_error already set to the previous error.
=> DAOS-10202 event: private event needs lock on completion and poll

src/vos/evtree.c, src/vos/tests/vts_aggregate.c, src/vos/vos_internal.h
For RDB to perform 1000 txns/s, we need more bits to store
an epoch.   Use 42-bits of HLC instead of 32.  This gives us
roughly 116 years worth of epochs.
Also, don't update the epoch if it's lower than the stored
one.  This is a bug.
=> DAOS-10227 vos: Fix a bug and add more bits to timestamp (#8709)

src/client/dfuse/il/ioil.h
- DAOS-10355 dfuse: Add interception for ftruncate.
- DAOS-10353 dfuse: Use 64 bit types for storing inode in IL.
=> DAOS-10353 dfuse: Use 64 bit types for storing inode in IL.

src/client/dfuse/il/int_posix.c, src/client/dfuse/il/intercept.h
Add interception for ftruncate.  This does not change the file
position so is reasonably easy.
=> DAOS-10355 dfuse: Add interception for ftruncate.

src/include/daos_srv/evtree.h, src/object/cli_obj.c, src/object/obj_enum.c, src/object/srv_ec.c, src/object/srv_ec_aggregate.c, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/tests/ftest/erasurecode/rebuild_fio.py, src/tests/ftest/erasurecode/rebuild_fio.yaml, src/tests/suite/daos_degrade_ec.c, src/vos/evtree.c
1. Fix a bug in EC obj degraded update
For EC (K+1) obj partial update, it will update to one data shard and                                  
replicate to parity shards. When that data shard failed, the degraded                               
update will send to the leader parity shard.                                                           
The code of ds_obj_rw_handler() -> obj_gen_dtx_mbs() will change the                                   
tgt_cnt to zero, then will not call obj_ec_rw_req_split() for the update                               
request. Actually for that case still need to call obj_ec_rw_req_split()                               
to split the iod->iod_recxs[] for the leader. …
=> DAOS-8640 obj: bug fixes in EC degraded update, key query and aggregation

src/tests/ftest/harness/setup.py, src/tests/ftest/harness/setup.yaml, src/tests/ftest/launch.py, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/server_utils.py
The timeouts for server prepare and format were hardcoded
and should be settable in the test yaml.
=> DAOS-10155 test: Allow timeouts for server startup (#8594)

src/client/pydaos/raw/daos_api.py, src/client/pydaos/raw/daos_cref.py, src/tests/ftest/pool/target_query.py, src/tests/ftest/pool/target_query.yaml
- Adding python API support for target_query.
- Adding Avocado test to validate the specific object data is
writing to the expected number of targets
Test-tag: iorsmall pool_query_target
=> DAOS-4661 Test: Adding test case and Python APi for pool target query.

src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.yaml
Test-tag: performance,-manual
- Bump pool size from 90% to 95%
- Use server log_mask: ERR instead of INFO
- Use 128KiB EC Cell Size
- Bump PPN from 8 to 32
- For ior_hard, adjust chunk size to be inline with ec cell size
=> DAOS-7528 test: adjust ftest/performance

src/utils/ctl/cart_ctl.c
Fix timeout values in cart_ctl. Bump from 5 to 60 seconds for the
initial wait_for_ranks stage with longer values if valgrind is being used.
=> DAOS-10218 test: Adjust timeouts in cart_ctl (#8642)

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go
If the client process's NUMA node doesn't have a local network
interface that is usable with DAOS, we now load-balance among
all other interfaces across NUMA nodes.
=> DAOS-10150 agent: Load balance amongst NUMA nodes

src/include/daos_srv/evtree.h, src/vos/evtree.c, src/vos/tests/evt_ctl.c, src/vos/vos_aggregate.c, src/vos/vos_io.c, src/vos/vos_tree.c
Avoid setting aggregatable time when the evtree has nothing to
aggregate.  For example, if extents are disjoint, there is no
need to scan the tree, even if there is more than one extent.
Since this is also used for EC aggregation, we need to ensure we
invoke EC aggregation when there is a parity mismatch.  Without
stripe and cell size, the best we can do is set the flag any time
there is both a partial and a parity extent.
=> DAOS-10227 vos: Optimize setting of aggregatable time

src/control/cmd/dmg/pool.go
fix this message in dmg pool create to say "per-engine":
"Creating DAOS pool with manual per-server storage allocation"
=> DAOS-10082 doc: fix pool per-server msg (#8758)

src/control/cmd/dmg/pool.go
fix this message in dmg pool create to say "per-engine":
"Creating DAOS pool with manual per-server storage allocation"
=> DAOS-10082 doc: fix pool per-server msg

src/tests/ftest/container/auto_oc_selection.py, src/tests/ftest/control/dmg_telemetry_basic.py, src/tests/ftest/io/parallel_io.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/ior_test_base.py
Test-tag: pr daily_regression oc_selection test_with_telemetry_basic parallelio multipoolparallelio datamover,pr datamover,daily_regression ior,pr ior,daily_regression
- Add generic kwargs to `get_container` that accepts any param.
- Update some tests to pass params this way
=> DAOS-9827 test: unified container create

src/tests/ftest/control/dmg_pool_query_ranks.py, src/tests/ftest/control/dmg_pool_query_ranks.yaml, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py
Add tests checking the state of ranks (i.e. enabled or disabled) with the pool query new features introduced with patches https://github.com/daos-stack/daos/pull/8587 and https://github.com/daos-stack/daos/pull/8659. 
Update `pool_query()` helper function to handle the new options `--show-enabled` and `--show-disabled` of the dmg cli sub-command pool query.
The tests introduced within this patch have been manually tested and also extensively been tested with the CI (thanks to the pragma Test-repeat-vm).
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-8699/3/tests
=> DAOS-10251 test: Test ranks state with pool query

src/tests/ftest/util/test_utils_base.py
flake check reported:
./src/tests/ftest/util/test_utils_base.py:8:1:
F401 'os.environ' imported but unused
=> DAOS-10429 test: remove unused import

src/tests/ftest/server/metadata.py, src/tests/ftest/server/metadata.yaml
Test-tag: offline_extend_oclass metadata_addremove
Test now calculates the total container difference the test should not deviate for each test loop. (eg: Assume mean containers created for each run is around 2500 containers. total container difference for each test loop = 2500 * (mean_percent [defined in yaml] / 100) = 13 containers.
Each test loop cannot exceed mean_container_count + percent deviation accepted. As shown in the above example, if mean_container_count is 2500, the percent deviation is 13. Which means total containers created for each loop can be in between 2513 and 2487.
Based on more investigation, we can still update the mean_percent value in the YAML to either high value or low value. For now, the value is 0.5 percent. …
=> DAOS-9078 test: Fix sequential decrease in containers (#8424) (Cherry pick for release/2.2)

src/tests/ftest/util/test_utils_base.py
Fix the F401 'os.environ' imported but unused Flake8 error recently
introduced in test_utils_base.py.
Skip-uint-tests: true
=> DAOS-623 test: Resolve flake8 lint import error

src/object/srv_ec_aggregate.c, src/tests/suite/daos_aggregate_ec.c
Since EC multiple shards fetch might mess up the reply CSUM,
so let's recalculate the checksum during EC aggregation.
=> DAOS-10145 EC: recalculate EC checksum for hole processing (#8695)

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go
If the client process's NUMA node doesn't have a local network
interface that is usable with DAOS, we now load-balance among
all other interfaces across NUMA nodes.
=> DAOS-10150 agent: Load balance amongst NUMA nodes (#8782)

src/control/common/test_utils.go, src/control/server/mgmt_pool.go, src/control/server/mgmt_pool_test.go
The PoolDestroy RPC handler's behavior was changed slightly
with the result that a forced destroy could sometimes fail
to zap the label on the existing pool service. This could
lead to confusing behavior when the admin tries to create a
new pool with the same label.
=> DAOS-10194 control: Fix forced PoolDestroy flow (#8598)

src/vos/vos_gc.c
When pools are too small, SCM space reserving is disabled. This
is problematic for tests that use tiny pools, fill them and then
try to delete a container. The gc bag isn't able to be allocated
for garbage collection. By pre-allocating the first bags this
issue can be worked around.
Back-port of PR #8708
=> DAOS-9028 gc: Pre-allocate first GC bags (#8708)

src/control/lib/hardware/fabric.go, src/control/lib/hardware/fabric_test.go, src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/hwprov/defaults_test.go, src/control/lib/hardware/mocks.go, src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go, src/control/server/server.go
Wait for infiniband fabric interfaces to be ready before scanning
for their details on daos_server startup.
- Add method to check fabric readiness via sysfs. It checks the same
sysfs data used by ibstat/libibumad to determine if the interface
is active.
- Add function hardware.WaitFabricReady to loop on ready checks,
with a configurable sleep between loops. It will be canceled when
the context is canceled.
- Log an informative message at error level if a fabric interface isn't
ready.
=> DAOS-9923 control: Wait for IB to be ready

src/control/lib/hardware/libfabric/bindings.go, src/control/lib/hardware/libfabric/provider.go
With libfabric v1.15.0 release candidates, an empty hint resulted
in fabric interfaces not being returned.
=> DAOS-10436 control: Don't call fi_getinfo with empty hint

src/control/server/mgmt_system_test.go, src/control/system/membership.go, src/control/system/membership_test.go
Relax the rejoin rules for this scenario which can occur
when the join partially succeeded (e.g. the member was added,
but the response was not received).
=> DAOS-10222 control: Allow rejoin with NilRank (#8618)

docs/admin/hardware.md
update hardware.md to explain that/how multiple NICs are
supported on the DAOS client side.
Doc-only: true
=> DAOS-9901 doc: explain multi-NIC support on the client

src/include/daos_srv/evtree.h, src/vos/evtree.c, src/vos/tests/evt_ctl.c, src/vos/vos_aggregate.c, src/vos/vos_io.c, src/vos/vos_tree.c
Avoid setting aggregatable time when the evtree has nothing to
aggregate.  For example, if extents are disjoint, there is no
need to scan the tree, even if there is more than one extent.
Since this is also used for EC aggregation, we need to ensure we
invoke EC aggregation when there is a parity mismatch.  Without
stripe and cell size, the best we can do is set the flag any time
there is both a partial and a parity extent.
=> DAOS-10227 vos: Optimize setting of aggregatable time (#8752)

src/tests/ftest/rebuild/no_cap.py
Description:  rebuild will keep retry due to out of space (-1007) error. Update test script per JIRA comment, rs_state could be 0 or 1.
Test-tag: no_cap
=> DAOS-10217-test: Invalid pool rebuild info rs_state=1 detected after rebuild

src/tests/ftest/nvme/enospace.py, src/tests/ftest/nvme/enospace.yaml
Description: Increase SCM size per triage suggestion, 62% is proven stable.
Test-tag: der_enospace
=> DAOS-10337-test: nvme/enospace.py failed due to SCM pool used failed > 55%, to increase usage limit to 62%

src/control/lib/hardware/libfabric/bindings.go, src/control/lib/hardware/libfabric/provider.go
With libfabric v1.15.0 release candidates, an empty hint resulted
in fabric interfaces not being returned.
=> DAOS-10436 control: Don't call fi_getinfo with empty hint (#8820)

src/control/lib/hardware/fabric.go, src/control/lib/hardware/fabric_test.go, src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/hwprov/defaults_test.go, src/control/lib/hardware/mocks.go, src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go, src/control/server/server.go
Wait for infiniband fabric interfaces to be ready before scanning
for their details on daos_server startup.
- Add method to check fabric readiness via sysfs. It checks the same
sysfs data used by ibstat/libibumad to determine if the interface
is active.
- Add function hardware.WaitFabricReady to loop on ready checks,
with a configurable sleep between loops. It will be canceled when
the context is canceled.
- Log an informative message at error level if a fabric interface
isn't ready.
=> DAOS-9923 control: Wait for IB to be ready (#8730)

src/utils/daos_hdlr.c
Add O_TRUNC flag in fs_copy_file().
=> DAOS-9826 datamover: truncate files that exist in daos fs copy.

src/tests/ftest/cart/iv_server.c, src/tests/ftest/cart/no_pmix_corpc_errors.c, src/tests/ftest/cart/no_pmix_group_test.c, src/tests/ftest/cart/no_pmix_group_version.c, src/tests/ftest/cart/no_pmix_launcher_client.c, src/tests/ftest/cart/test_corpc_exclusive.c, src/tests/ftest/cart/test_corpc_prefwd.c, src/tests/ftest/cart/test_group_np_cli.c, src/tests/ftest/cart/test_no_timeout.c, src/utils/self_test/self_test.c
Internal timeouts for pings in cart tests were set to 5-10 seconds
causing CI failures under valgrind vm runs or multi-node vm runs
with many servers/clients. Timeouts changes to 50-60 seconds instead
=> DAOS-10226 test: Update internal timeouts (#8817)

src/tests/ftest/deployment/agent_failure.py, src/tests/ftest/deployment/agent_failure.yaml
This is the cherry-pick PR from master.
**Summary**
Verify agent failure is properly handled.
1. Create a pool and a container.
2. Run IOR.
3. Stop daos_agent process while IOR is running.
4. Check the error on the client side. When
daos_agent is killed in the middle of IOR, the
file write completes successfully, but the pool
disconnect at the end fails, so we get the error
message that includes -1005. This step is more
like a verification of the test itself rather
than the product.
5. Verify daos_server doesn’t have the pool
handle opened. Call:
dmg telemetry metrics query --metrics=engine_pool_pool_handles
that shows the number of open pool handle.
Verify that it's 0 after the agent is stopped
and IOR is finished. This step verifies the
isolation of the failure. In this case,
daos_agent …
=> DAOS-9385 test: Add agent failure test (#8368)

src/tests/ftest/cart/no_pmix_corpc_errors.c
=> DAOS-10166 cart: Add shutdown delay to corpc errors test.

src/control/lib/control/pool.go, src/control/server/ctl_storage_rpc.go, src/control/server/ctl_storage_rpc_test.go
When NVMe of different size are used by the same engine, then the storage available for each device is equal to the one of the smallest device.
Automatic functional tests could not be easily done as it will need to have at least one node equipped with NVMe devices of different size.
The unit tests were manually validated and the CI test suite will ne relaunched as soon as it will be fixed.
The patch was manually validated with wolf-157 which have disk of different size as illustrated in the following traces:
```
[1048] > $HOME/daos/install/bin/dmg -o /etc/daos/daos_control.yml storage scan -v
--------
wolf-157
--------
HugePage Size: 2048 KB
SCM Namespace Socket ID Capacity
------------- --------- --------
pmem0         0         3.2 TB
pmem1         1         3.2 TB
NVMe PCI       Model …
```
=> DAOS-10225 control: fix available storage with heterogeneous NVMe

src/tests/ftest/ior/hard_rebuild.py, src/tests/ftest/ior/hard_rebuild.yaml
1) in hard_rebuild.py, remove the first time ior_read_dataset() calling,
as it will zero the stoneWallingStatusFile's content and fail
the 2nd ior_read_dataset().
2) hard_rebuild.yaml, add "-c" (collective) flag for ior write to avoid
generate holes (see ior code WriteOrRead() in ior.c, hitStonewall
related code).
Test-tag: ec_ior_hard_online_rebuild
=>     DAOS-10342 test: refine hard_rebuild.py/yaml

src/tests/ftest/slurm_setup.py, src/tests/ftest/soak/smoke.yaml, src/tests/ftest/soak/test_base.py, src/tests/ftest/soak/utils.py
Test-tag: soak_smoke offline_extend_oclass
Some command lines in soak have prepended sudo and they are unnecessary and should be removed.
=> DAOS-10216 test: remove unecessary soak sudo cmds (#8611)

src/tests/ftest/rebuild/widely_striped.py, src/tests/ftest/rebuild/widely_striped.yaml
- Set cont_rf so mdtest completes successfully
- Run mdtest as a subprocess instead of thread
- Make sure mdtest is actually successful
- Misc cleanup
rf should be set on a POSIX container for root/SB objects.
Test-tag: rebuild_widely_striped
=> DAOS-10454 test: improve rebuild_widely_striped

src/object/srv_ec_aggregate.c
Setting peer parity targets before checking if peer
parity is alive, otherwise it might skip the peer
parity update during EC aggregation, and cause parity
inconsistency on different parity shards.
=> DAOS-10435 ec: set peer parity before checking

src/tests/ftest/control/dmg_telemetry_io_latency.py, src/tests/ftest/soak/utils.py, src/tests/ftest/util/file_count_test_base.py
Replace duplicate get_rf functions with
oclass_utils.extract_redundancy_factor
Test-tag: smallfilecount soak_smoke test_io_latency_telemetry
=> DAOS-623 test: replace duplicate get_rf functions

src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.yaml
Test-tag: performance,-manual
- Bump pool size from 90% to 95%
- Use server log_mask: ERR instead of INFO
- Use 128KiB EC Cell Size
- Bump PPN from 8 to 32
- For ior_hard, adjust chunk size to be inline with ec cell size
=> DAOS-7528 test: adjust ftest/performance (#8719)

utils/config/daos_server.yml
Default applied if unset is INFO, correct comment and list of options.
Doc-only: true
=> DAOS-10489 doc: Correct default log mask level

src/ddb/README.md, src/ddb/SConscript, src/ddb/ddb_cmd_options.c, src/ddb/ddb_cmd_options.h, src/ddb/ddb_commands.c, src/ddb/ddb_common.h, src/ddb/ddb_entry.c, src/ddb/ddb_main.c, src/ddb/ddb_parse.c, src/ddb/ddb_parse.h, src/ddb/ddb_printer.c, src/ddb/ddb_printer.h, src/ddb/ddb_vos.c, src/ddb/ddb_vos.h, src/ddb/tests/SConscript, src/ddb/tests/ddb_cmd_options_tests.c, src/ddb/tests/ddb_cmocka.h, src/ddb/tests/ddb_commands_print_tests.c, src/ddb/tests/ddb_commands_tests.c, src/ddb/tests/ddb_main_tests.c, src/ddb/tests/ddb_parse_tests.c, src/ddb/tests/ddb_smoke_tests.sh, src/ddb/tests/ddb_test_driver.c, src/ddb/tests/ddb_test_driver.h, src/ddb/tests/ddb_vos_tests.c
- Introduces the dump, dump_ilog, dump_dtx, load, and rm commands for the 
ddb tool.
- Reworked the construction of the unit test lists so that the
test function name is printed in stead of a separate description.
- Added some filtering to the unit tests.
- Abstracted out the printing of the commands so that what is
printed is more easily testable and to clean up the
command functions a little.
=> DAOS-10224 ddb: dump, load, rm commands

src/vos/vos_common.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_obj.c, src/vos/vos_obj_index.c
Holding the value across a yield can cause undefined behavior.
At some point, this should be fixed so we pass the dth through
parameters rather than expecting us to always get this right
inside of VOS.  Making sure we never have it set across yield
points is difficult.
=> DAOS-10200 vos: Avoid setting dth in TLS across yield

src/control/lib/control/auto.go, src/control/lib/control/auto_test.go, src/control/server/config/server.go, src/control/server/config/server_test.go, src/control/server/engine/config.go, src/control/server/engine/config_test.go, src/control/server/server.go, src/control/server/server_utils_test.go, src/control/server/storage/bdev/backend_json_test.go
* Remove engine/Config.MultiEngine field
- Leaks details across package boundaries and requires
changes throughout the codebase
* Fix bad precedent that Validate() methods may be used
to change state
- These methods should be as read-only as possible and
simply verify that the config is sane and meets requirements
* Centralize logic for determining per-engine NUMA affinity
in a single location to improve maintainability and
testability
- Makes future changes to enhance NUMA affinity detection
easier to make in a targeted way with minimal changes to
the surrounding codebase
- It would be better not to have this logic implemented in
a method on server/config/server.Config, in order to
encourage cleaner separation of responsibilities, but putting
it here for now is a compromise to maintain …
=> Proposed updates to PR

src/tests/ftest/scrubber/target_auto_eviction.yaml
Skip-nlt: true
Test-tag: test_scrubber_target_auto_eviction
Summary:
-  Update the YAML file to make the test more reliable with fault injection framework. 
-  Use all the targets (using the RP_2GX)
-  Increase the block size so all targets gets some data and corruption happens in few targets.
=> DAOS-9318 test: Update the target eviction test case.

src/control/lib/control/auto.go, src/control/server/config/server.go, src/control/server/config/server_test.go, src/control/server/server.go, src/control/server/server_utils_test.go
Allow affinity detection methods to be injected into
the config.Server.SetEngineAffinities() method in order
to maintain clean package boundaries and areas of
responsibility.
=> Refactor for affinity sources

src/vos/vos_common.c, src/vos/vos_io.c, src/vos/vos_obj.c, src/vos/vos_obj_index.c
Holding the value across a yield can cause undefined behavior.
At some point, this should be fixed so we pass the dth through
parameters rather than expecting us to always get this right
inside of VOS.  Making sure we never have it set across yield
points is difficult.
=> DAOS-10200 vos: Avoid setting dth in TLS across yield (#8857)

src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/cmd/daos_agent/start.go, src/control/common/collection_utils.go, src/control/lib/hardware/errors.go, src/control/lib/hardware/errors_test.go, src/control/lib/hardware/fabric.go, src/control/lib/hardware/fabric_test.go, src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/hwprov/defaults_test.go, src/control/lib/hardware/mocks.go, src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go, src/control/lib/hardware/topology.go, src/control/server/server.go
The agent must, similar to the server, wait for fabric interfaces
to become ready before performing a full fabric scan. In the agent
we scan as needed, so it won't happen until the client makes a
GetAttachInfo call.
- Add mechanism for agent to check fabric readiness for the relevant
class of net interfaces for the GetAttachInfo call. This will
happen only before the fabric scan, which means cached fabric info
will not require a re-check.
- Refactor hardware.FabricReadyChecker into NetDevStateProvider,
which fetches the state directly, for the caller to act on.
- Replace sysfs.Provider CheckFabricReady() function with
GetNetDevState(). This gets the state of ordinary net interfaces
as well as IB. The logic for multi-device/multi-port configs
is more sophisticated now: A device is ready …
=> DAOS-9923 agent: Wait for fabric ready before scan

src/tests/ftest/datamover/dst_create.py, src/tests/ftest/erasurecode/cell_size_property.py, src/tests/ftest/rebuild/container_rf.py, src/tests/ftest/util/container_rf_test_base.py, src/tests/ftest/util/daos_utils.py, src/tests/ftest/util/test_utils_container.py
Update `DaosCommand.container_get_prop()` to use JSON and
support `properties`. Also add `TestContainer.get_prop()`.
Update the tests that use `container_get_prop()`.
This is the cherry-pick PR of the following two PRs.
https://github.com/daos-stack/daos/pull/8454, https://github.com/daos-stack/daos/pull/8741
The tags from the two PRs above are merged and used in this PR.
(Some of the tests, such as pool/rf.py, don't exist in 2.0, so the
changes to those tests aren't included.)
=> DAOS-10430 test: Update container_get_prop() to use JSON

src/object/srv_ec_aggregate.c
Setting peer parity targets before checking if peer
parity is alive, otherwise it might skip the peer
parity update during EC aggregation, and cause parity
inconsistency on different parity shards.
=> DAOS-10435 ec: set peer parity before checking (#8859)

docs/admin/troubleshooting.md
e2fsck tool can be used for recovering the PMEM device after it's been restored to healthy stats.
doc-only: true
=> DAOS-9578 Doc: Adding e2fsck commands to check and repair the PMEM devices.

src/control/server/ctl_ranks_rpc.go, src/control/server/ctl_ranks_rpc_test.go, src/control/server/engine/mocks.go, src/control/server/harness.go
This reverts commit 30a960b698fc2d8453b7b9cd9a0578f3657a3c2b, which
is causing frequent unit test failures in CI.
=> Revert "DAOS-10495 control: Remove inner RPC timeouts for system commands (#8875)"

docs/admin/predeployment_check.md
clarify that the sysctl settings for multiple server interfaces
are required for both the verbs and the tcp provider.
Doc-only: true
=> DAOS-9355 doc: clarify sysctl for multiple interfaces

src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/cmd/daos_agent/start.go, src/control/common/collection_utils.go, src/control/lib/hardware/errors.go, src/control/lib/hardware/errors_test.go, src/control/lib/hardware/fabric.go, src/control/lib/hardware/fabric_test.go, src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/hwprov/defaults_test.go, src/control/lib/hardware/mocks.go, src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go, src/control/lib/hardware/topology.go, src/control/server/server.go
The agent must, similar to the server, wait for fabric interfaces
to become ready before performing a full fabric scan. In the agent
we scan as needed, so it won't happen until the client makes a
GetAttachInfo call.
- Add mechanism for agent to check fabric readiness for the relevant
class of net interfaces for the GetAttachInfo call. This will
happen only before the fabric scan, which means cached fabric info
will not require a re-check.
- Refactor hardware.FabricReadyChecker into NetDevStateProvider,
which fetches the state directly, for the caller to act on.
- Replace sysfs.Provider CheckFabricReady() function with
GetNetDevState(). This gets the state of ordinary net interfaces
as well as IB. The logic for multi-device/multi-port configs
is more sophisticated now: A device is ready …
=> DAOS-9923 agent: Wait for fabric ready before scan (#8877)

src/include/gurt/common.h, src/include/gurt/debug.h
Also casts the expression to a uintptr_t.  Otherwise we get
compiler warnings when someone does
D_ASSERT(x)
where x is a pointer.  I tried a couple of scenarios and codegen is
identical for cast vs no cast
=> DAOS-10494 common: Use likely in assert macro

src/control/lib/spdk/src/nvme_control.c, src/control/lib/spdk/src/nvme_control_common.c, src/control/server/instance_storage_rpc.go
To reduce duration of dmg storage format command, which wipes NVMe
namespaces, use the async version of spdk_nvme_detach API which batches
detach tasks and performs them together when poll is called at a later time.
Format operations with 16TB NVMe SSDs previously took ~14s per SSD and
should now take ~15s per engine regardless of the number of SSDs.
=> DAOS-10174 control: Reduce duration of NVMe storage format

src/client/pydaos/SConscript
Some setups require the use of the minor version number when installing
so use this rather than just python3
Remove redundant code from the build step.
=> DAOS-10490 build: Use major-minor python versions when installing pydaos.

src/tests/ftest/dfuse/caching_check.yaml
Test-tag: dfusecachingcheck
Performance in CI is not stable enough, so reduce 10x -> 5x
=> DAOS-10469 test: adjust dfuse caching performance threshold

src/tests/ftest/ior/hard_rebuild.py
in hard_rebuild.py, remove the first time ior_read_dataset() calling,
as it will zero the stoneWallingStatusFile's content and fail
the 2nd ior_read_dataset.
Test-tag: pr ec_ior_hard_online_rebuild
=> DAOS-10342 test: refine hard_rebuild.py #8743

utils/config/daos_server.yml
Default applied if unset is INFO, correct comment and list of options.
=> DAOS-10489 doc: Correct default log mask level (#8865)

src/include/gurt/debug.h, src/vos/evtree.c, src/vos/vos_gc.c
This can be problematic if the condition runs a function.  We noticed
this when trying to insert a patch for coverity issue 349749. That
fix is in this patch for reference.
=> DAOS-10494 common: Assert macros run the condition more than once (#8873)

src/control/lib/control/auto.go, src/control/server/config/server.go, src/control/server/config/server_test.go, src/control/server/engine/config.go, src/control/server/engine/config_test.go, src/control/server/server.go, src/control/server/server_utils_test.go, src/control/server/storage/bdev/backend_json_test.go, utils/config/daos_server.yml
Previous behavior is that pinned_numa_node is not always passed when
executing engine which causes engine to default to NUMA-0.
In the case where server config does not specify pinned_numa_node and
control plane derives NUMA node to be 1 (e.g. from fabric_iface "ib1"
affinity), hugepages will be allocated on NUMA-1 but engine will try to
allocate DMA buffer from NUMA-0 and fail.
Correct behavior by passing pinned_numa_node commandline parameter when
starting engine unless single engine is on NUMA-0 or first_core is set,
in which case we want to avoid passing pinned_numa_node so that the
legacy core allocation algorithm is activated in the engine. Verify that
first_core and pinned_numa_node parameters are never be set together in
server config file engine section.
Co-authored-by: Michael …
=> DAOS-10450 control: Always set engine NUMA node on exec (#8827)

src/control/lib/spdk/src/nvme_control_common.c, src/control/server/instance_storage_rpc.go
To reduce duration of dmg storage format command, which wipes NVMe
namespaces, use the async version of spdk_nvme_detach API which batches
detach tasks and performs them together when poll is called at a later time.
Format operations with 16TB NVMe SSDs previously took ~14s per SSD and
should now take ~15s per engine regardless of the number of SSDs.
=> DAOS-10174 control: Reduce duration of NVMe storage format (#8603)

src/object/cli_ec.c, src/object/cli_obj.c
1. Various fixes for EC multiple shards enumeration.
2. Check efi_stripe_sgls, instead of efi_stripe_lists, which will
not be set for single value.
3. Remove unnecessary assert in obj_ec_recov_stripe(), since fail_info
list might be shared by multiple recover tasks, so one recov ent list
may not exist in one IOD.
4. Remove unnecessary invalid nr check for multiple shards enumeration.
5. Reset kd_key_len to 0 for enumeration, since it may return the
required size for KEY2BIG case.
Conflicts:
src/object/cli_obj.c
=> DAOS-10415 EC: various fixes about EC (#8506)

src/container/srv_container.c, src/container/srv_layout.c, src/container/srv_layout.h, src/pool/srv_layout.h
The ds_cont_prop_version key conflicts with ds_pool_prop_version. The
two keys refer to the same value in the root RDB KVS. This patch removes
ds_cont_prop_version to avoid future confusions, for using separate
versions for pool and container metadata would be an overkill currently.
The patch also includes some layout-related fixes and improvements:
- Fix the value type comments for ds_cont_prop_ec_pda and
ds-cont_prop_rp_pda.
- Improve the consistency of value type comments.
How to add layout-version-dependent code to src/container is left to
further discussions (e.g., by exporting and using ds_pool_prop_version
and/or ds_pool_prop_global_version?).
=> DAOS-8918 container: Fix key conflict with pool MD

src/bio/bio_buffer.c
Split large IO into chunk size IOs (8MB by default) to avoid exceeding
the SPDK bdev single IO size limit.
=> DAOS-9991 bio: split large IO

src/tests/ftest/dfuse/caching_check.yaml
Test-tag: dfusecachingcheck
Performance in CI is not stable enough, so reduce 10x -> 5x
=> DAOS-10469 test: adjust dfuse caching performance threshold (#8920)

src/client/dfuse/il/ioil.h
When intercepting fstat the interception library was storing
the inode in a 32 bit variable which would lead to incorrect
values being reported to the user.  Ensure the correct types
are used.
=> DAOS-10353 dfuse: Use 64 bit types for storing inode in IL. (#8772)

SConstruct, src/client/dfs/dfs.c, src/include/daos_fs.h, src/tests/suite/dfs_unit_test.c
If a user connect to a DFS container with dfs_connect(), they don't have
access to the pool and container handles that are opened by DFS internally.
Users sometimes need to add attributes or query the pool and container info,
so provide a mechanism to return those internal pool and container handles
with proper refcounting, requiring users to put the handles when done before
umount of dfs.
=> DAOS-10477 dfs: add new APIs to retrieve pool and container handles

Jenkinsfile
Use the 9-node clusters to run functional HW Medium tests in the
release/2.0 branch to avoid running these tests on VMD-enabled clusters.
=> DAOS-9562 test: Prevent running release/2.0 tests with VMD

src/include/daos_srv/rebuild.h, src/pool/srv_pool.c, src/pool/srv_target.c, src/rebuild/rebuild_internal.h, src/rebuild/rebuild_iv.c, src/rebuild/rpc.h, src/rebuild/scan.c, src/rebuild/srv.c
Add rebuild generation for each rebuild retry, which will
be increased whenever it needs to retry rebuild, to avoid
retry rebuild might mess with the original rebuild.
Some cleanup for rebuild complete notification.
=> DAOS-10125 rebuild: add rebuild generation

Jenkinsfile
Replace
"<module>/*.pb-c.[ch]:"
with
"*.pb-c.[ch]:"
to avoid the scenario where one adds a new pb-c file but forgets to
update this list.
=> DAOS-10542 Jenkinsfile: Simplify pb-c patterns

src/client/dfuse/dfuse_obj_da.c, src/client/pydaos/raw/daos_cref.py, src/include/daos_types.h
New mutex added in private event did not take into consideration extra
8 byte of mutex size on aarch64. add that padding to private event size.
=> DAOS-10569 client: fix build on aarch64

src/dtx/dtx_common.c, src/include/daos/object.h, src/include/daos_errno.h, src/include/daos_srv/dtx_srv.h, src/object/cli_obj.c, src/object/obj_internal.h, src/object/obj_rpc.c, src/object/obj_tx.c, src/object/srv_obj.c, src/object/srv_obj_remote.c, src/tests/suite/daos_degrade_ec.c, src/vos/vos_io.c
During object rebuild, if the client triggers conditional operation
on the object that is in rebuilding, then condition check cannot be
properly handled on the in-rebuilding target as to cause unexpected
result when double failures happened.
To resolve such trouble, we will delay IO forwarding of conditional
sub requests to the in-rebuilding targets until the healthy targets
have processed related condition check.
From client perspective, related RPC will become slow, but consider
that the case (conditionally modify the in-rebuilding object shard)
is rare, then the total overhead is not too much.
This patch also fixes a bug in dc_tx_convert logic for update/punch
with condition and needs to be handled via distributed transaction.
The original implementation dropped condition check by …
=> DAOS-10204 dtx: delay IO forward for conditional ops during rebuild

src/tests/ftest/nvme/enospace.py
Description: Increase SCM size per triage suggestion, 62% is proven stable.
nvme/enospace.py failed due to SCM pool used failed > 55%
Test-tag: online_drain_mdtest enospc_no_aggregation
=> DAOS-10337 test: increase SCM usage limit to 62% (#8720)

src/client/dfuse/dfuse_obj_da.c, src/client/pydaos/raw/daos_cref.py, src/include/daos_types.h
* New mutex added in private event did not take into consideration extra
8 byte of mutex size on aarch64. add that padding to private event size.
* move the magic int to be next to the pthread key since both are
4 bytes so compiler doesn't insert an extra 8 byte pads (4 each) when
statically checking the size.
=> DAOS-10569 client: fix build on aarch64 (#8986)

src/client/dfuse/dfuse.h, src/client/dfuse/dfuse_core.c, src/client/dfuse/ops/create.c, src/client/dfuse/ops/ioctl.c, src/client/dfuse/ops/lookup.c, src/client/dfuse/ops/open.c, src/client/dfuse/ops/opendir.c, src/client/dfuse/ops/readdir.c
Track when the IL has opened file handles and invalidate all kernel
metadata when in use.  Track the ioctl calls and use atomics to
track the number of calls per open file, and the number of files
per inode, when returning inode metadata check the il-in-use count.
This should mean that when the IL is in use, all metadata requests
will go to the servers, so avoids a situation where a file is opened,
the IL writes data to it then the kernel will continue to return
stale size data.
Add checks in forget that the IL and open file count are at zero.
=> DAOS-10356 dfuse: Disable dfuse metadata caching when using IL. (#8760)

Jenkinsfile, src/tests/ftest/launch.py
Adding a launch.py --proider arugment to specify the default provider to
use in the test daos_server config file.
=> DAOS-9989 test: Adding launch.py --provider option.

src/container/container_iv.c
Let's delete IV entry before container handle, which might yield,
to avoid inflight I/O might re-open/start the container through IV
at the same time.
=> DAOS-10194 container: delete iv entry before close cont hdl

src/pool/srv_layout.c, src/pool/srv_layout.h, src/pool/srv_pool.c
If pool created after daos 2.2, downgrade it back
to 2.0 should be unsupported and fail properly.
=> DAOS-10541 pool: backport compatibility check

utils/config/daos_server.yml
clarify provider documentation in the daos_server.yml template
Doc-only: true
=> DAOS-9644 doc: correct provider documentation in server.yml (#8934)

src/include/daos_srv/pool.h, src/pool/srv_internal.h, src/pool/srv_pool_check.c
Add a ds_pool_check_svc_clues API, which analyzes clues about replicas of a PS
and reports whether rebootstrapping is required as well as which replica
to rebootstrap from.
=> DAOS-9592 pool: Introduce ds_pool_check_svc_clues

ci/provisioning/post_provision_config_common.sh
But don't allow distro packages to upgrade MLNX packages.
=> DAOS-623 ci: Allow fuse to upgrade

ci/unit/test_main_node.sh, src/vos/tests/daos_nvme.conf, src/vos/tests/vts_aggregate.c, src/vos/vos_common.c, utils/run_test.sh
Enable NVMe when running VOS unit tests.
=> DAOS-10367 tests: enable NVMe for VOS unit tests

src/control/lib/hardware/hwloc/bindings.go, src/control/lib/hardware/hwloc/provider.go, src/control/lib/hardware/hwloc/provider_test.go, src/control/lib/hardware/pci.go, src/control/lib/hardware/pci_test.go, src/control/lib/hardware/pretty.go, src/control/lib/hardware/pretty_test.go, src/control/lib/hardware/topology.go
Allow dump-topology subcommands to include block devices and
their NUMA affinities in the scan output. Also tweaks the pretty-printer
output to group PCI devices by bus.
=> DAOS-10526 control: Add block devices to topology scan (#8970)

src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/fault/fault.go, src/control/fault/fault_test.go, src/control/lib/daos/status.go, src/include/daos_errno.h
- Add a new error, DER_CONTROL_INCOMPAT, to indicate that control
plane components (agent, server, dmg) are not compatible.
- Return the new error as a status code to client processes if the
agent discovers it is not compatible with the DAOS server.
- Fix broken GetAttachInfo unit test.
=> DAOS-10395 agent: Add component incompatibility error

src/control/lib/ui/flags.go, src/tests/ftest/container/list.py, src/tests/ftest/control/dmg_pool_evict.py, src/tests/ftest/nvme/enospace.py, src/tests/ftest/util/daos_utils.py
The default behavior is to use CamelCase; just add json: tags
to the struct fields to make them snake_case.
=> DAOS-10579 tools: Ensure daos list-container JSON is lowercase

src/tests/ftest/util/apricot/apricot/test.py
Due to import change, call time() instead of time.time()
Test-tag: ior_intercept_verify_data
=> DAOS-10609 test: fix usage of time

src/container/srv_target.c, src/include/daos_srv/pool.h, src/include/daos_srv/vos.h, src/include/daos_srv/vos_types.h, src/object/obj_internal.h, src/object/srv_obj_migrate.c, src/pool/srv_target.c, src/tests/vos_engine.c, src/vos/tests/vts_common.c, src/vos/vos_container.c, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_layout.h, src/vos/vos_obj.c, src/vos/vos_pool.c, src/vos/vos_tree.c
Explicitly enable the optimization when the GLOBAL_VERSION is >= 1.
DAOS 2.0 has no such property so the global version will be 0. This
should allow us to use a 2.0 pool even if it's been touched by 2.2
For pools that are created with 2.2, we set an new durable format version
such that this feature is always enabled. This maintains compatibility with
the old durable format up until a pool upgrade.
Also added #9034 to this patch.
=> DAOS-10465 vos: Avoid using aggregation optimization on v2.0 pool (#8953)

.rpmignore, Jenkinsfile, ci/functional/required_packages.sh, debian/changelog, debian/control, utils/rpms/daos.spec
Limit daos_tests requiement to the non-openmpi daos-*-tests packages.
=> DAOS-10535 build: Remove daos_tests daos-*-tests-openmpi requirement

src/tests/ftest/pool/svc.yaml
To avoid intermittent timeout errors with the pool/svc.py test the
avocado test timeout is being increased by 50 seconds.
Test-tag: test_pool_svc
Test-repeat-vm: 5
=> DAOS-8495 test: Increase test timeout for pool/svc.py

src/tests/ftest/osa/dmg_negative_test.yaml
Test-tag: osa_dmg_negative_test
=> DAOS-9625 test: Increase the timeout.

src/container/container_iv.c
Let's delete IV entry before container handle, which might yield,
to avoid inflight I/O might re-open/start the container through IV
at the same time.
=> DAOS-10194 container: delete iv entry before close cont hdl (#9001)

src/tests/ftest/nvme/fault.py, src/tests/ftest/nvme/fault.yaml, src/tests/ftest/util/nvme_utils.py
Test-tag: nvme_fault mdtest_small
Improve nvme/fault.py
- Increase capacity to 15% to avoid IOR finishing before setting the
device faulty
- Simplify yaml params
- Remove unused params
- More logging
=> DAOS-10534 test: improve nvme/fault.py

src/tests/ftest/pool/list_verbose.py, src/tests/ftest/pool/list_verbose.yaml
list_verbose.py
- Add state: Ready to expected output.
- Remove dfs_dir_oclass from IOR
- Remove ib2 test tag (unused)
=> DAOS-10442 test: add state to expected output

src/tests/ftest/nvme/health.py, src/tests/ftest/nvme/health.yaml
Test-tag: nvme_health
nvme/health.py
- Increase total space usage from 75% to 90%
=> DAOS-10500 test: nvme/health.py: increase pool capacity

src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go
The agent was assuming NUMA nodes were sorted by index rather than
ID for load balancing purposes. This broke in cases with network
interfaces on non-sequential NUMA nodes.
Feature: control
=> DAOS-10530 agent: Fix NUMA node rotation (#8973)

src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/drpc/status.go, src/control/fault/fault.go, src/control/fault/fault_test.go, src/include/daos_errno.h
- Add a new error, DER_CONTROL_INCOMPAT, to indicate that control
plane components (agent, server, dmg) are not compatible.
- Return the new error as a status code to client processes if the
agent discovers it is not compatible with the DAOS server.
- Fix broken GetAttachInfo unit test.
=> DAOS-10395 agent: Add component incompatibility error (#9072)

src/chk/SConscript, src/chk/chk_internal.h, src/chk/chk_srv.c, src/chk/chk_vos.c, src/include/daos_srv/daos_chk.h
The leader instance uses the bookmark "CHK_BK_LEADER" to trace the
leader check process, such as the instance status, the scan phase,
inconsistency statistics information related with the leader, time
information, and so on. Each engine instance has each own bookmark,
called CHK_BK_ENGINE, to trace related check process on the engine.
The engine's bookmark does not include detailed pools' check info,
that will be traced via the pool bookmark named with the pool UUID.
Every pool shard on each related engines all has its pool bookmark.
All above bookmarks are organized as KV under vos sys_db. The dkey
is "CHK_DB_TABLE".
On each engine participating in the check, there is shared property
KV "CHK_PROPERTY" under the vos sys_db. It contains the check flags,
leader information, inconsistency …
=> DAOS-9583 chk: interface for vos operations to trace check process

ci/provisioning/post_provision_config_nodes.sh
Adding a workaround to enable binding devices back to nvme or vfio-pci
after they are unbound from vfio-pci to nvme.  This should resolve the
following error seen when attempting to start daos engines:
storage: code = 304 description = "NVMe SSD [0000:86:00.0] not found"
=> DCO-10397 test: Resolve NVMe SSD not found errors

utils/githooks/pre-commit.d/30-yamllint.sh
Also fix some comments to make it clear how a user might workaround
issues locally.
=> DAOS-623 hooks: Make the yamllint hook only run on diffs

src/tests/ftest/pool/svc.yaml
To avoid intermittent timeout errors with the pool/svc.py test the
avocado test timeout is being increased by 50 seconds.
Test-tag: test_pool_svc
Test-repeat-vm: 5
=> DAOS-8495 test: Increase test timeout for pool/svc.py (#9012)

.rpmignore, Jenkinsfile, debian/changelog, debian/control, utils/rpms/daos.spec
Creating the daos-tests-internal metadata package to provide all the
test packages required for functional testing in CI.
=> DAOS-10535 tests: Add daos-tests-internal package

src/tests/ftest/util/apricot/apricot/test.py
Test-tag: ior_intercept_verify_data
Due to import change, call time() instead of time.time()
=> DAOS-10609 test: fix usage of time (#9049)

utils/sl/pylint3.rc
Test-tag: pr,-hw
This spews too many warnings and we aren't yet away from the yoke of
python2
=> DAOS-623 pylint: disable consider-using-f-string (#9022)

site_scons/components/__init__.py, site_scons/prereq_tools/base.py, src/control/SConscript, src/control/fault/fault.go, src/control/fault/fault_test.go, src/control/lib/hardware/ucx/bindings.go, src/control/lib/hardware/ucx/bindings_test.go, src/control/server/storage/config.go, src/control/server/storage/config_test.go
Build UCX support in the control plane and in Mercury (if we are
building dependencies) if the UCX libraries/headers are detected.
=> DAOS-10539 build: Autodetect UCX (#8967)

src/client/dfuse/il/int_posix.c
Only run the destructor if run in the same thread id as the constructor.
some programs, at least sh, run lightweight threads so can end up
calling the destructor more times than the constructor, so to avoid
deadlocks save the tid in the constructor and only run the destructor
if it matches.
=> DAOS-10354 dfuse: Check thread id in interception library destructor.

src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/config_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/procmon.go, src/control/cmd/daos_agent/start.go, utils/config/daos_agent.yml
When the agent is shut down, it loses all knowledge of
currently-open pool handles on the local node. By default,
it should instead attempt to evict all open pool handles
before shutting down.
This behavior can be overridden by setting the following
in the agent configuration:
disable_auto_evict: true
Features: control pool container
=> DAOS-10611 control: Evict pool handles on agent shutdown

ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_common_functions.sh
Ensure the daos repos are enabled for weekly branch PR testing.
=> DAOS-10621 test: Don't disable daos repos for weekly branch PRs

utils/scripts/install-el8.sh
A recent upstream change means this isn't being installed
by default and without it the permissions on /tmp are
incorrect so docker builds fail.
=> DAOS-623 build: Add systemd as a dependency on el8.

src/tests/ftest/control/dmg_network_scan.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/network_utils.py
Adding new network_utils.py methods to collect network information for
ofi and ucx and providing a data structure for storing this information.
Updating the dmg_network_scan.py to make use of these new utility
methods to verify interfaces used with ofi and ucx providers.
Use the specified remote host to run the server and issue the network
discovery commands on the same remote host (DAOS-10062).
Test-tag: dmg,network_scan,basic zero_config
=> DAOS-10397 test: Add ucx provider support to dmg_network_scan.py (#9025)

utils/node_local_test.py
A recent change to the daos command changed the case for
some json entries.  Update NLT to expect the new names.
=> DAOS-623 test: Update json format for NLT.

src/tests/ftest/deployment/critical_integration.py, src/tests/ftest/util/apricot/apricot/test.py
Test-tag: criticalintegration
- Add get_hosts_from_yaml to TestWithoutServers
- merge-compatible with https://github.com/daos-stack/daos/pull/8809 / DAOS-10390
- Split test_passwdlessssh_versioncheck and test_ras into separate classes
- Adjust test_passwdlessssh_versioncheck to not start servers
- Use TestWithoutServers so the framework doesn't try to run any
commands on the server or clients, which could fail the test early
and prevent isolation of node failures.
=> DAOS-10630 test: passwdlessssh not start servers

src/tests/ftest/deployment/agent_failure.py, src/tests/ftest/deployment/agent_failure.yaml, src/tests/ftest/util/general_utils.py
Cherry-pick of https://github.com/daos-stack/daos/pull/8690 to release/2.2.
* Test with multiple clients to verify the failure isolation.
Run IOR from two separate clients using separate agent process.
Kill one of the agents and verify that the other client
isn’t affected.
* Use `ppn: 10` for IOR processes.
* Remove `write_x` and `read_x` from IOR section in the yaml.
* Use `sw_deadline: 300` instead of `-D 300` in IOR section in
the yaml.
* Move `get_journalctl` to ftest/util/general_utils.py
Test-tag: agent_failure
=> DAOS-10244 test: Improve deployment/agent_failure.py - release/2.2 (#8690)

src/control/system/raft/database_test.go
The timeouts were causing occasional spurious failures on slow VMs. There is
still an overall test timeout that will prevent the test from hanging indefinitely.
=> DAOS-10533 test: Remove timeouts in leadership cb test

src/control/lib/ui/flags.go, src/tests/ftest/container/list.py, src/tests/ftest/control/dmg_pool_evict.py, src/tests/ftest/nvme/enospace.py, src/tests/ftest/util/daos_utils.py, utils/node_local_test.py
The default behavior is to use CamelCase; just add json: tags
to the struct fields to make them snake_case.
=> DAOS-10579 tools: Ensure daos list-container JSON is lowercase (#9019)

src/ddb/ddb_cmd_options.c, src/ddb/ddb_cmd_options.h, src/ddb/ddb_commands.c, src/ddb/ddb_main.c, src/ddb/ddb_printer.c, src/ddb/ddb_vos.c, src/ddb/ddb_vos.h, src/ddb/tests/ddb_cmd_options_tests.c, src/ddb/tests/ddb_cmocka.h, src/ddb/tests/ddb_commands_print_tests.c, src/ddb/tests/ddb_commands_tests.c, src/ddb/tests/ddb_smoke_tests.sh, src/ddb/tests/ddb_test_driver.c, src/ddb/tests/ddb_vos_tests.c
Introduce the commands to process and remove ilogs and
committed dtx entries. Also added a help command.
=> DAOS-10416 ddb: Processing and Clearing ilog and dtx

src/gurt/tests/test_gurt.c, src/include/daos_errno.h, src/include/daos_srv/pool.h, src/pool/srv_pool.c, src/pool/srv_target.c
If one pool is not up because of disk incompatible reasons,
pool query will return DER_NOTLEADER and retry forever.
If one pool failed to start, track failed pool list, and
before searching pool service, check if pool is tracked
in the failed list, return error directly.
=> DAOS-10567 pool: track failed pool lists

src/control/server/config/server_test.go, utils/config/daos_server.yml
correct provider documentation in the daos_server.yml template
Doc-only: true
=> DAOS-9644 doc: correct provider documentation in server.yml

src/control/system/database_test.go
The timeouts were causing occasional spurious failures on slow VMs. There is
still an overall test timeout that will prevent the test from hanging indefinitely.
=> DAOS-10533 test: Remove timeouts in leadership cb test (#9106)

src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/config_test.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/procmon.go, src/control/cmd/daos_agent/start.go, utils/config/daos_agent.yml
When the agent is shut down, it loses all knowledge of
currently-open pool handles on the local node. By default,
it should instead attempt to evict all open pool handles
before shutting down.
This behavior can be overridden by setting the following
in the agent configuration:
disable_auto_evict: true
=> DAOS-10611 control: Evict pool handles on agent shutdown (#9052)

utils/test_memcheck.supp
We started seeing a new leak inside of OpenMPI so suppress it
=> DAOS-10677 test: Add a new suppression for internal MPI leak

ci/provisioning/post_provision_config_common.sh
There was a conflict between UCX and Mellanox packages on some
CI nodes.
PR-repos-el8: openucx@master
PR-repos-el7: openucx@master
PR-repos-leap15: openucx@master
=> DAOS-10600 ci: Prevent UCX pkg from breaking MLNX

src/tests/ftest/deployment/critical_integration.py
=> DAOS-10630 test: change NodeSet.append -> add

src/tests/ftest/nvme/health.py, src/tests/ftest/nvme/health.yaml
Test-tag: nvme_health mdtest_small
nvme/health.py
- Increase total space usage from 75% to 90%
=> DAOS-10500 test: nvme/health.py: increase pool capacity (#9066)

src/ddb/ddb_vos.c, src/ddb/tests/ddb_test_driver.c
After a change landed to master, ddb's usage of vos_self_init
needs to be updated to work with the new interface.
=> DAOS-10615 ddb: Fix ddb usage of vos_self_init

src/chk/SConscript, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_srv.c, src/include/daos_errno.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/vos_types.h, src/mgmt/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
For each check instance, there is one check engine on every specified
ranks by the control plane. Corresponding to the check leader, engine
instance are the ones that drive pool based scanning on every related
DAOS target.
The check engines use pool records tree to trace each own local check
process. The local check instance will be marked as completed locally
when such tree is empty.
We allow the check engine to rejoin former uncompleted check instance
when restarts under check mode as long as it is not marked as dead by
the check leader. If successfully rejoin former uncompleted check, it
will resume the scan the last phase before restart. In the future, we
may support to resume the scan from more accurate check-point when we
do object/key level consistency checking.
Quick-Functional: …
=> DAOS-9583 chk: DAOS check engine logic

src/chk/SConscript, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_leader.c, src/chk/chk_srv.c, src/include/daos_errno.h, src/include/daos_srv/daos_chk.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/vos_types.h, src/mgmt/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
For each check instance, there is a unique check leader on the specified
rank by the control plane. The leader instance is in charge of the check
engines to start/stop/query check process, monitor check engines status,
and forward inconsitency report from check engines.
The check leader uses the rank records tree to trace the check engines.
The check instance will be marked as completed when such tree is empty.
Currently, we do not support run multiple check instances in the system
(even if they are on different rank sets) at the same time. If multiple
pools need to be checked, then please either specify the uuids together
(or not specify pool option, then check all pools by default) via single
"dmg check" command, or wait one check instance done and then start next.
Another to be …
=> DAOS-9583 chk: DAOS check leader logic

src/chk/SConscript, src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_leader.c, src/chk/chk_srv.c, src/include/daos/btree_class.h, src/include/daos_errno.h, src/include/daos_srv/daos_chk.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/vos_types.h, src/mgmt/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
The common functionalities shared between DAOS check leader and
check engine, mainly includes:
1. Pool records tree operations set. Check leader uses the pool
records tree to handle "check query" result and organize the
pools (and related service) list. Check engine user the tree
to trace the check process.
2. Pending action records tree operations set. The tree is used
by both check leader and check engine to trace those actions
that need interact with the admin for reparation decision.
3. Some general tools and check instance initialization library.
=> DAOS-9583 chk: common logic for DAOS check

src/chk/SConscript, src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_leader.c, src/chk/chk_srv.c, src/include/daos/btree_class.h, src/include/daos_errno.h, src/include/daos_srv/daos_chk.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/iv.h, src/include/daos_srv/vos_types.h, src/mgmt/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
DAOS check IV is mainly among check leader and check engines for
the following scenarios:
1. Check leader notifies check engines that its status (such as
check failed because of some unrecoverable error) change via
check IV refresh.
2. Check engine notifies check leader that its process (such as
the check phase) and its status (such as failed or completed
the check) via IV update.
=> DAOS-9589 chk: DAOS check IV

Jenkinsfile, src/chk/SConscript, src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_leader.c, src/chk/chk_srv.c, src/chk/chk_upcall.c, src/engine/drpc_ras.c, src/include/daos/btree_class.h, src/include/daos_errno.h, src/include/daos_srv/daos_chk.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/iv.h, src/include/daos_srv/ras.h, src/include/daos_srv/vos_types.h, src/include/daos_types.h, src/mgmt/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
There are four upcalls as following:
1. DRPC_METHOD_CHK_LIST_POOL:
Check leader uses it to get all the known pools list and related pool
service replicas from MS.
2. DRPC_METHOD_CHK_REG_POOL:
Check leader adds some orphan pool and the pool service replicas to MS.
3. DRPC_METHOD_CHK_DEREG_POOL:
Check leader delete some (dangling) pool from MS.
4. DRPC_METHOD_CHK_REPORT:
Check leader reports its found inconsistency and related repair result,
or forward other engines detected inconsistency and related reparation
to the control plane.
Re-enable code format check against chk_internal.
=> DAOS-9583 chk: DAOS check dRPC upcall

Jenkinsfile, src/chk/SConscript, src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_leader.c, src/chk/chk_rpc.c, src/chk/chk_srv.c, src/chk/chk_upcall.c, src/common/proc.c, src/engine/drpc_ras.c, src/include/daos/btree_class.h, src/include/daos/common.h, src/include/daos/rpc.h, src/include/daos_errno.h, src/include/daos_srv/daos_chk.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/iv.h, src/include/daos_srv/pool.h, src/include/daos_srv/ras.h, src/include/daos_srv/vos_types.h, src/include/daos_types.h, src/mgmt/srv_target.c, src/object/obj_rpc.c, src/pool/srv_pool_check.c, src/vos/vos_layout.h, src/vos/vos_pool.c
The RPC layout and sponser logic. There are seven RPCs for DAOS check
as following:
1. CHK_START:
From check leader to check engine to start the check instance on
specified pool(s) or all pools.
2. CHK_STOP:
From check leader to check engine to stop the check instance on
specified pools(s) or all pools.
3. CHK_QUERY:
From check leader to check engine to query the check process for
specified pools(s) or all pools.
4. CHK_MARK:
From check leader to check engine to mark some rank as "dead".
Under check mode, if some rank is dead (and failed to rejoin),
it will not be exlcuded from related pool map to avoid further
damaging the system, instead, it will be mark as "dead" by the
check instance and the check status on related pool(s) will be
marked as "failed".
5. CHK_ACT:
From check leader to …
=> DAOS-9583 chk: DAOS check RPC

Jenkinsfile
The daos-tests-clients-openmpi RPM is now installed via the
daos-tests-internal package.  Include the installation of this
package in all functional test stages.
Test-tag: daos_racer_parallel daosperf,full_regression
=> DAOS-10651 test: Install daos-tests-internal for weekly tests

src/rsvc/srv.c
When working on feature/cat_recovery, we found a ds_rsvc leak
during "rdbt test-multi". The functions ds_rsvc_{add,remove}_replicas
use put_leader to release only the leader reference, leaking the ds_rsvc
reference. This patch replaces the put_leader calls with
ds_rsvc_put_leader, which releases both references.
Since these functions are currently called only from rdbt, this is a
test issue at the moment.
=> DAOS-9592 rsvc: Fix ds_rsvc leaks

src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_iv.c, src/chk/chk_leader.c, src/chk/chk_rpc.c, src/chk/chk_srv.c, src/chk/chk_vos.c, src/engine/drpc_ras.c, src/engine/init.c, src/engine/server_iv.c, src/include/daos_srv/daos_chk.h, src/include/daos_srv/daos_engine.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/iv.h, src/include/daos_srv/vos_types.h, src/mgmt/SConscript, src/mgmt/srv_chk.c, src/mgmt/srv_drpc.c, src/mgmt/srv_internal.h, src/mgmt/srv_target.c, src/mgmt/tests/mocks.c, src/mgmt/tests/srv_drpc_tests.c, src/pool/srv_pool.c, src/vos/vos_layout.h, src/vos/vos_pool.c
The DAOS check dRPC download interfaces are implemented inside mgmt,
include the following:
1. DRPC_METHOD_MGMT_CHK_START:
Start DAOS check on the spcified ranks. Both the ranks list and
the leader rank are specified by the control plane.
2. DRPC_METHOD_MGMT_CHK_STOP:
Stop DAOS check for the specified pool(s), or for all pools if
without pool option. If only some pools are specified to stop,
then the check instance will continue the check for the other
left pool(s).
3. DRPC_METHOD_MGMT_CHK_QUERY:
Query check process for specified pools or all pools by default,
including the instance status, related pool status, summary for
all the engines (and the leader) found inconsistencies, related
handle actions and the results, and so on.
4. DRPC_METHOD_MGMT_CHK_PROP:
Get current check instance run …
=> DAOS-9583 mgmt: dRPC downcall interfaces for DAOS check

src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_leader.c, src/dtx/dtx_srv.c, src/engine/init.c, src/include/daos_srv/daos_mgmt_srv.h, src/mgmt/srv_pool.c, src/pool/srv.c, src/pool/srv_pool_check.c, src/vos/vos_layout.h
Compare the engines reported pools (and services) list with the ones
from MS. Handle the following cases:
1. Dangling pool: the pool only exists in MS but not on the engines.
Then the pool record will be removed from MS, or need to interact
with admin if it is required.
2. Orphan pool: the pool only exists on the engines but not in MS.
Then register the orphan pool to MS by default, or interact with
admin if it is required. If some pool shards are under zombies,
then it is suggest to destroy the orphan pool.
3. We lost the majority pool service replicas, but we still can find
some valid pool service replica. Then we will dictate the service
from some specified pool service replica.
4. For a pool, we lost all pool service replicas, can neither have a
quorum or dictate the service from some …
=> DAOS-9592 chk: pool list consolidation

utils/test_memcheck.supp
This isn't really a backport because master branch has diverged to use
libdpar.so to wrap MPI calls whereas 2.2 and 2.0 have not.  So rather
this is an equivalent suppression for 2.2.
=> DAOS-10677 test: Backport for #9173 to suppress MPI leak

src/vos/vos_gc.c
A racy scenario exists when GC ULT his working on a
vos_container and this one can be freed during
container close/destroy.
To avoid this, have GC ULT take an extra reference
on vos_container during the time it works on it.
=> DAOS-10381 vos: GC to take a vos_container reference (#8885)

ci/rpm/test_daos_node.sh, debian/changelog, debian/control, debian/daos-admin.dirs, debian/daos-admin.install, debian/daos-client.install, utils/rpms/daos.spec
Create a new admin-only package to allow installation
independently of client/server dependencies.
=> DAOS-10458 build: Move dmg into daos-admin package

src/control/cmd/dmg/auto_test.go, src/control/common/hugepages.go, src/control/common/hugepages_test.go, src/control/server/config/faults.go, src/control/server/config/server.go, src/control/server/config/server_test.go, src/control/server/server_utils.go, src/control/server/server_utils_test.go, utils/config/daos_server.yml, utils/config/examples/daos_server_unittests.yml, utils/nlt_server.yaml
Replace setting nr_hugepages: -1 with an explicit disable_hugepages: true
directive to improve clarity of intent.
=> DAOS-10603 control: Add disable_hugepages server config file parameter

ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_common_functions.sh
Moving to using CHANGE_TARGET resolves the issue of running with the
correct daos RPMs in a weekly-testing* branch PR, but this variable is
not set during timed weekly-testing* builds.  Use the BRANCH_NAME
variable if the CHANGE_TARGET variable is not set to allow
weekly-testing* timed builds to install the correct doas RPMs.
=> DAOS-10621 test: Fix weekly-testing timed builds

src/client/java/daos-java/pom.xml
Update netty used by daos-java to the latest version to address CVE-2022-24823
=> DAOS-10741 java: Update Netty to Latest Version

docs/QSG/cloud.md, docs/cloud/index.md, docs/index.md, mkdocs.yml
add documentation for DAOS in the Cloud,
including DAOS on GCP references
Doc-only: true
=> DAOS-9355 doc: add infos for DAOS in the Cloud

src/control/lib/control/system_test.go, src/control/server/mgmt_system.go, src/control/server/mgmt_system_test.go, src/control/system/member.go, src/control/system/membership_test.go, src/control/system/mocks.go, src/control/system/raft/database_test.go
There are situations where multiple results for the same rank maybe
received after a distributed system fanout request e.g. during
dmg system stop command execution.
Work-around this issue by removing duplicate results for a single rank
after the fanout results have been collected. Log an error if the
duplicate results do not have identical content.
=> DAOS-10660 control: Remove duplicate rank results after system fanout

src/control/events/pubsub.go, src/control/events/pubsub_test.go, src/control/events/ras.go, src/control/events/ras_test.go, src/control/server/server_utils.go
When a rank is seen as dead by multiple other ranks, the
number of events raised may be as large as N-1, where N
is the size of the cluster. As we only care about the first
event for the purpose of updating the system membership,
we can ignore subsequent events for the same rank:incarnation
combination.
=> DAOS-10643 control: Debounce SWIM Rank Dead events

src/control/lib/hardware/ucx/ucx.go, src/control/lib/hardware/ucx/ucx_test.go
- Add support for ucx+all alias.
- Stop scanning non-network components. For now we will limit
scanning to the infiniband (ib) and tcp components.
- For tcp, don't attempt to build a multirail device name.
=> DAOS-10736 control: Improve UCX transport support (#9214)

ci/provisioning/post_provision_config_common_functions.sh, ci/provisioning/post_provision_config_nodes.sh, ci/provisioning/post_provision_config_nodes_UBUNTU_20_04.sh
Some post_provision_config functions unintentionally abort execution to
early resulting in missed post provisioning steps.  These functions now
return a status that can be handled correctly by the calling script.
=> DAOS-10397 ci: Fix post_provision_config scripts (#9140)

src/tests/ftest/dtx/basic.yaml
Increase test timeout.
Test-tag: basictx
=> DAOS-9310 test: Fix dtx/basic.py pool connect timeout (#7840)

src/pool/srv_iv.c
-1 in pic_size is used to tell the real size of the pool
connection IV size, and no pic_conns, so checking pic_size
in pool_iv_conn_lookup().
=> DAOS-10679 pool: check pic_size (== -1) for pool conns IV

src/common/tse.c, src/common/tse_internal.h
Original code using dtp_completing flag for task re-init check -
1. first set dtp_completing == 1 and call task completion CB,
2. inside task completion CB if it calls re-init then will zero the flag,
3. check dtp_completing flag if it is zero then the task was re-inited
But a problem is once the task re-inited in step2, it possibly get
executing and complete (which will set the dtp_completing flag)
immediately even before step 3.
Previously we added a lock dsp_comp_lock to avoid that but did not
resolve some cases' problem, and the lock is bad as it actually
serialized all tasks' completion callbacks' executing.
This patch refines that by adding an ATOMIC generation to the task,
and removes the dsp_comp_lock.
=> DAOS-7133 tse: refine task re-init checking

src/control/cmd/dmg/system.go, src/control/cmd/dmg/system_test.go, src/control/lib/control/request.go, src/control/lib/control/response.go, src/control/lib/control/system.go, src/control/lib/control/system_test.go, src/control/lib/hostlist/hostset.go, src/control/lib/hostlist/hostset_test.go, src/control/lib/hostlist/numericlist.go, src/control/lib/hostlist/numericlist_test.go, src/control/server/mgmt_system.go, src/control/system/ranklist.go
Callers may set a reporting callback to be invoked as
HostResponse replies are received. This commit just adds
info-level logging to display finished/waiting ranks,
but the mechanism could be extended for more sophisticated
progress updates sent back to control clients.
Also adds new NumericList/NumericSet types to the hostlist
library to be used as a more efficient/capable basis for
the system.RankSet type.
=> DAOS-10495 control: Allow fanout RPCs to report progress (#8955)

src/control/server/storage/scm/mocks.go, src/control/server/storage/scm/provider.go, src/control/server/storage/scm/provider_test.go, src/tests/ftest/util/general_utils.py
Set the mounted SCM filesystem's root permissions to match the
underlying mountpoint's permissions.
=> DAOS-9873 control: Adjust permissions on mounted SCM filesystem

src/tests/ftest/pool/list_verbose.py, src/tests/ftest/pool/list_verbose.yaml
list_verbose.py
- Add state: Ready to expected output.
- Remove dfs_dir_oclass from IOR
- Remove ib2 test tag (unused)
=> DAOS-10442 test: add state to expected output (#9065)

src/pool/srv_iv.c
-1 in pic_size is used to tell the real size of the pool
connection IV size, and no pic_conns, so checking pic_size
in pool_iv_conn_lookup().
=> DAOS-10679 pool: check pic_size (== -1) for pool conns IV (#9178)

src/object/obj_internal.h
Nonleader is a temporary state during leader swich,
so let's retry for object I/O.
=> DAOS-10525 object: retry for NONLEADER

src/bio/bio_buffer.c, src/bio/bio_bulk.c
bulk_map_one() mistakenly ignored the error code returned from
dma_map_one(), that could result in bio_iod_prep() succeeds even
when it actually fails in dma_map_one().
flush_one() can skip pmem flush when it's not direct SCM access
(DMA buffer is used for SCM bulk transfer by default).
=> DAOS-10748 bio: missed error code in bulk_map_one()

src/common/tse.c, src/common/tse_internal.h
Original code using dtp_completing flag for task re-init check -
1. first set dtp_completing == 1 and call task completion CB,
2. inside task completion CB if it calls re-init then will zero the flag,
3. check dtp_completing flag if it is zero then the task was re-inited
But a problem is once the task re-inited in step2, it possibly get
executing and complete (which will set the dtp_completing flag)
immediately even before step 3.
Previously we added a lock dsp_comp_lock to avoid that but did not
resolve some cases' problem, and the lock is bad as it actually
serialized all tasks' completion callbacks' executing.
This patch refines that by adding an ATOMIC generation to the task,
and removes the dsp_comp_lock.
=> DAOS-7133 tse: refine task re-init checking (#9202)

src/container/srv_container.c, src/gurt/misc.c, src/include/daos/common.h, src/include/daos_srv/pool.h, src/include/gurt/common.h, src/pool/srv_pool.c, src/pool/srv_target.c, src/pool/srv_util.c
Remove map_ranks_class and move map_ranks_merge to
d_rank_list_range.
And DRAIN rank are still accessible until the rank
is excluded from the pool_map, so broacast RPC should
still include DRAIN ranks.
=> DAOS-10525 pool: cleanup MAP rank init

src/container/srv_container.c, src/container/srv_layout.c, src/container/srv_layout.h, src/pool/srv_layout.h
The ds_cont_prop_version key conflicts with ds_pool_prop_version. The
two keys refer to the same value in the root RDB KVS. This patch removes
ds_cont_prop_version to avoid future confusions, for using separate
versions for pool and container metadata would be an overkill currently.
The patch also includes some layout-related fixes and improvements:
- Remove ds_cont_prop_ghce and ds_cont_prop_ghpce, for these were
deprecated long ago and have not been read since.
- Fix the value type comments for ds_cont_prop_ec_pda and
ds-cont_prop_rp_pda.
- Improve the consistency of value type comments.
How to add layout-version-dependent code to src/container is left to
further discussions (e.g., by exporting and using ds_pool_prop_version
and/or ds_pool_prop_global_version?).
Signed-off-by: Li Wei …
=> DAOS-8918 container: Fix key conflict with pool MD (#8824)

src/bio/bio_buffer.c, src/bio/bio_bulk.c
bulk_map_one() mistakenly ignored the error code returned from
dma_map_one(), that could result in bio_iod_prep() succeeds even
when it actually fails in dma_map_one().
flush_one() can skip pmem flush when it's not direct SCM access
(DMA buffer is used for SCM bulk transfer by default).
=> DAOS-10748 bio: missed error code in bulk_map_one() (#9265)

src/tests/ftest/server/metadata.py
Cherry-pick of PR 9162 master commit b7d669d to reelease/2.2.
Significantly reduce the test's expectation of the minimum number of
containers that can be created in a pool, since frequent changes to
metadata layouts have an impact that triggers test failures. And since
the tests are currently designed to fill the metadata  on purpose,
rather than expect a specific quantity.
Test-tag: metadata_fillup metadata_der_nospace pool_create_all_one_hw
=> DAOS-10255 test: adjust minimum containers expectation again (#9162)

src/tests/ftest/container/query_properties.yaml, src/tests/ftest/control/dmg_telemetry_basic.yaml, src/tests/ftest/pool/create_all_vm.yaml, src/tests/ftest/telemetry/dkey_akey_enum_punch.yaml
Cherry-pick of PR 9291 master commit c03a05623 to release/2.2 branch.
Before this change, in virtual machine (VM)-based testing of the
pool create_all tests, intermittent failures were seen due to
slow/laggy performance on the VM nodes. This resulted in RPC timeouts
in daos_engine during pool create/destroy operations. This is not a
a new phenomenon. Previously it has been seen with other VM-based tests,
requiring a smaller scm_size setting to alleviate memory pressure.
With this change, the scm_size parameter is reduced in this test
and in the following tests (and addressing the associated tickets):
- container/query_properties (DAOS-10487)
- telemetry/dkey_akey_enum_punch (DAOS-10487)
- control/dmg_telemetry_basic (DAOS-10528)
Longer term for create_all_vm, it may be better to …
=> DAOS-10448 test: reduce SCM size in create_all_vm/other tests (#9291)

src/client/pydaos/raw/daos_api.py, src/tests/ftest/container/destroy.py, src/tests/ftest/container/destroy.yaml
daos_cont_destroy() in c still supports passing uuid, so container.destroy() needs uuid parameter to test non-existing uuid.
Test-tag: container
=> DAOS-10734 ftests: container.destroy() needs uuid parameter to test non-existing uuid

src/tests/ftest/control/dmg_system_reformat.py, src/tests/ftest/control/dmg_system_reformat.yaml, src/tests/ftest/util/server_utils.py
Remove skipForTicket("DAOS-6004")
Fixed typo in detect_engine_start()
Calling storage format after system stop too soon would fail.
Wait 10 sec and retry up to 4 times.
Removed detect_engine_start() argument to use all hosts.
Test-tag: dmg_system_reformat
=> DAOS-6322 test: Re-enable test_dmg_system_reformat (#7849)

ci/rpm/test_daos_node.sh, debian/changelog, debian/control, debian/daos-admin.dirs, debian/daos-admin.install, debian/daos-client.install, utils/rpms/daos.spec
Create a new admin-only RPM to allow installation
independently of client/server dependencies.
=> DAOS-10458 build: Move dmg into daos-admin RPM (#8925)

docs/admin/troubleshooting.md, src/control/lib/control/event.go
Describe the daos_server error printed when no syslog daemon is
configured and how to resolve it in the troubleshooting guide.
Also fixes a formatting issue in an error message.
=> DAOS-10085 doc: Add syslog delivery failure to troubleshooting (#9220)

src/common/tests/prop_tests.c, src/include/daos/cont_props.h, src/include/daos_prop.h, src/tests/ftest/erasurecode/cell_size_property.py, src/tests/ftest/util/daos_utils.py
The pool property name is "ec_cell_sz". For command parity
and better UX, adjust the container property name to match.
Test-tag: pr ec_cell_size ec_cell_property
=> DAOS-10378 cont: Adjust cell size prop name to match pool

src/common/tse.c, src/common/tse_internal.h, src/include/daos/tse.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_internal.h, src/object/obj_tx.c, src/tests/suite/daos_obj_ec.c, src/vos/vos_io.c
Add support of EC conditional fetch.
split to multiple sub-tasks for cond_akey fetch with multiple akeys
Add related UT cases.
A few bug fixes -
skip fetch/update in akey_fetch()/akey_update() for NULL recxs which is
possible when fetch multiple IODs and recxs only valid on partial shard.
fix a bug in shard_auxi_task_cb() that may use incorrect task pointer.
And add tse_disable_propagate() for the use case in dc_tx_get_epoch().
=> DAOS-9888 obj: add support of EC conditional fetch

Jenkinsfile
Enable weekly testing of the pr and daily_regession taggged tests on the
Functional HW test stages with the tcp and ucx providers.  This extends
the normal CI daily testing of pr and daily_regession tagged tests on
the Functional HW test stages with the verbs provider.
=> DAOS-9989 test: Enable weekly testing with tcp and ucx providers

src/common/pool_map.c
in pool_map_rf_verify() the pmap_fail_node not completly inited/zeroed, that
possibly cause problem as the memory in stack may with non-zero data
(pf_down/pf_new_fail possibly is 1 in extreme case).
=> DAOS-10829 pool: fix a bug of pmap_fail_node not inited/zeroed

src/common/tests/prop_tests.c, src/include/daos/cont_props.h, src/include/daos_prop.h, src/tests/ftest/erasurecode/cell_size_property.py, src/tests/ftest/util/daos_utils.py
The pool property name is "ec_cell_sz". For command parity
and better UX, adjust the container property name to match.
=> DAOS-10378 cont: Adjust cell size prop name to match pool (#9246)

src/object/cli_obj.c, src/object/obj_internal.h, src/object/obj_tx.c
modification
If a distributed transaction contains per akey based modification,
then we need to check every related akey's existence via each own
sub-task independently. Each one is a conditional akey fetch task.
=> DAOS-10204 dtx: handle per akey based conditional

docs/admin/deployment.md
Include information on setting option when using daos_server storage
prepare as well as setting the parameter in the server config file.
Doc-only: true
=> DAOS-10132 doc: Describe disable_vfio usage in admin guide

src/tests/ftest/object/create_many_dkeys.yaml
ofi+sockets seems having performance issue in CI with libfabric 1.15.1. tcp works fine in previous tests.
=> DAOS-10727 ftest: Set provider as tcp for many_dkeys

src/control/server/mgmt_system.go, src/control/server/mgmt_system_test.go, src/control/server/server.go, src/control/server/server_utils.go, src/control/server/server_utils_test.go
Replicas sending a Join request need to report the same ControlAddr
as the management service DB includes in its replica list. Without
this, on systems with multiple IP addresses on the same subnet,
the MS can fail to recognize itself and other nodes as replicas.
=> DAOS-10661 control: Use DB replica addr for JoinReq

src/container/srv_container.c, src/container/srv_layout.h, src/pool/srv_layout.h, src/pool/srv_pool.c
1. Remove ds_pool_prop_version, ds_pool_prop_global_version
could be used to replace its function.
2. Bump container's global version upon pool upgrading.
=> DAOS-10612 pool, container: simplify layout versioning (#9055)

src/include/daos_srv/daos_engine.h, src/pool/cli.c, src/pool/srv_internal.h, src/pool/srv_pool.c, src/pool/srv_target.c
ds_pool_tgt_query_map_handler misses (due to my ignorance) the case
where an engine may go through the map_refresh code to refresh a
"client-copy" of the pool map during a rebuild job. This patch fixes the
issue by following the handling "server handles" in
ds_pool_query_handler. Also,
- Extract a new ds_pool_hdl_is_from_srv API for
ds_pool_tgt_query_map_handler, to avoid looking up the ds_pool
object twice.
- Handle -DER_NOTLEADER from ds_pool_hdl_is_from_srv in
ds_pool_tgt_query_map_handler and resulting -DER_AGAIN in
map_refresh_cb.
- Remove the is_pool_from_srv declaration from daos_engine.h.
=> DAOS-8870 pool: Allow srv_hdls in TGT_QUERY_MAP (#7082)

Jenkinsfile, src/tests/ftest/launch.py
Adding a launch.py --proider arugment to specify the default provider to
use in the test daos_server config file.
=> DAOS-9989 test: Adding launch.py --provider option. (#8960)

src/tests/ftest/launch.py
Adding running the vfio-pci binding fix workaround commands between
running avocado test files on the hosts that were used by the test to
run the daos_server command.
Also update the stopping of server and clients to limit commands to
hosts only used by the test to run servers and clients, respectively.
=> DAOS-10608 test: Run vfio-pci workaround fix between tests (#9271)

src/gurt/misc.c, src/include/gurt/common.h, src/mgmt/srv_pool.c
Previously, the code was simply generating the group
rank list based on the group size, resulting in intermittent
create failures when the actual group differed from the
generated group.
=> DAOS-10822 pool: Get actual cart group ranks on create

src/tests/ftest/pool/dynamic_server_pool.py, src/tests/ftest/pool/multi_server_create_delete.py, src/tests/ftest/util/check_for_pool.py, src/tests/ftest/util/general_utils.py
The following tests were using the check_for_pool() helper
which did not use sudo when looking into SCM:
- pool/multi_server_create_delete.py
- pool/dynamic_server_pool.py
Fix the check_for_pool() helper to use the sudo-aware
check_file_exists() helper, and to return a friendlier
bool value instead of a return code.
Features: pool control
=> DAOS-9873 test: Fix more pool tests

src/client/dfs/duns.c
One line else statement was removed accidentally in a previous PR.
Need to put it back.
=> DAOS-9201 dfs: Put back else removed accidentally

src/pool/srv_pool_map.c
Only update domain status if the original status is DOWN
or DOWNOUT, i.e. partial targets reintegration may not
need change domain status.
Features: reintegration
=> DAOS-10525 pool: update dom status during reintegration.

src/tests/suite/daos_container.c, src/tests/suite/daos_iotest.h, src/tests/suite/daos_obj.c
set_pool_reclaim_strategy() does not work as DAOS_PROP_PO_RECLAIM is a
pool property rather than user attribute, so daos_pool_set_attr will not
work.
And if the test case need to compare pool space usage better to generate
separate pool rather than reuse the shared pool.
=> DAOS-10806 test: fix a bug for setting reclaim policy (#9307)

src/common/pool_map.c
in pool_map_rf_verify() the pmap_fail_node not comopletly inited/zeroed, that
possibly cause problem as the memory in stack may with non-zero data
(pf_down/pf_new_fail possibly is 1 in extreme case).
=> DAOS-10829 pool: fix a bug of pmap_fail_node not inited/zeroed (#9331)

docs/user/filesystem.md, src/client/dfuse/dfuse_core.c, utils/node_local_test.py
Allow True/False as well as on/off and ignore case for dfuse
cache attributes.
Ensure all attribute settings are logged.
Correct an error when an invalid setting was used for direct-io-disable.
This makes it more user friendly, as well as allowing Python True/False
values to be set without translating into on/off.
=> DAOS-7652 dfuse: Allow True/False for dfuse cache settings.

.rpmignore
do not ship UCX packages - added ucx to .rpmignore
(we use the MOFED-provided UCX)
=> DAOS-10845 packaging: do not ship UCX packages

.rpmignore
do not ship UCX packages - added ucx to .rpmignore
(we use the MOFED-provided UCX)
=> DAOS-10845 packaging: do not ship UCX packages (#9358)

src/tests/ftest/deployment/critical_integration.py, src/tests/ftest/util/apricot/apricot/test.py
Test-tag: criticalintegration
Cherry-pick of #9083 + #9148
- Add get_hosts_from_yaml to TestWithoutServers
- merge-compatible with #8809 / DAOS-10390
- Split test_passwdlessssh_versioncheck and test_ras into separate classes
- Adjust test_passwdlessssh_versioncheck to not start servers
- Use TestWithoutServers so the framework doesn't try to run any
commands on the server or clients, which could fail the test early
and prevent isolation of node failures.
=> DAOS-10630 test: passwdlessssh not start servers (#9083)

src/client/api/container.c, src/client/dfs/dfs.c, src/client/dfs/duns.c, src/client/pydaos/raw/daos_api.py, src/common/prop.c, src/control/cmd/daos/container.go, src/include/daos_cont.h, src/include/daos_fs.h, src/tests/ftest/container/async.py, src/tests/ftest/container/create.py, src/tests/ftest/container/create.yaml, src/tests/ftest/container/destroy.py, src/tests/ftest/datamover/dst_create.py, src/tests/ftest/datamover/obj_large_posix.py, src/tests/ftest/datamover/obj_small.py, src/tests/ftest/util/daos_utils_base.py, src/tests/suite/dfs_unit_test.c, src/utils/daos_hdlr.c, utils/node_local_test.py
Port the changes of removing compatibility code for daos_cont_create() to 2.2.
Test-tag: pr container dm_dst_create dm_obj_small basiccheckout_dm
=> DAOS-9201 API: Remove compatibility code for daos_cont_create()

src/tests/ftest/pool/dynamic_server_pool.py, src/tests/ftest/pool/multi_server_create_delete.py, src/tests/ftest/util/check_for_pool.py, src/tests/ftest/util/general_utils.py
The following tests were using the check_for_pool() helper
which did not use sudo when looking into SCM:
pool/multi_server_create_delete.py
pool/dynamic_server_pool.py
Fix the check_for_pool() helper to use the sudo-aware
check_file_exists() helper, and to return a friendlier
bool value instead of a return code.
=> DAOS-9873 test: Fix more pool tests (#9322)

src/tests/ftest/deployment/agent_failure.py
…tations - release/2.2 (#9273)
test_agent_failure is failing because -1005 isn't in the IOR results.
The error message is different from when I created this test.
test_agent_failure_isolation is failing because IOR on the kill
client is failing. When I created this test, no error was observed
on the client where the agent was killed.
The resolution is to fix the test so that it expects no
error or different error message.
Test-tag: agent_failure
=> DAOS-10770 test: agent_failure.py - Update IOR error expectations - release/2.2

src/tests/ftest/nvme/health.py, src/tests/ftest/nvme/health.yaml
Test-tag: nvme_health mdtest_small
To account for nodes with reduced nvme space, create UP TO 40 pools
instead of exactly 40 pools.
=> DAOS-10500 test: Make nvme/health more flexible

src/client/api/event.c, src/client/api/tests/eq_tests.c, src/include/daos_event.h, src/tests/suite/dfs_unit_test.c
daos_event_abort() was marking the event as aborted, however the DAOS
internal task is not aborted, and currently there is no way to abort
that. So later if a user progresses (through test or poll) that aborted
event, the event API frees the event and marks it as ready to initialized
since it was aborted before, but the DAOS internal task is still not done.
When the DAOS task finally progresses, it can cause corruption because the
user might have resused the event, or even reused the buffers that were passed
to the event.
Since we do not support cancellations of internal DAOS tasks and RPCs, change
the abort implementation to just be a no-op for now which would cause a test or poll
on the event to wait till the internal task is completed to avoid such corruption issues.
Signed-off-by: …
=> DAOS-10601 client: fix daos_event_abort corruption issue (#9175)

.flake8, .flake8-scons, site_scons/site_tools/extra/extra.py, src/cart/SConscript, src/cart/macro_prefix.h_in, utils/sl/fake_scons/SCons/Script/__init__.py
A couple of things were causing the preprocessing step in cart
to generate _structures_from_macros.h to be slow
1. The Preprocessor builder currently doesn't support building
multiple items in parallel so it's better to call it one file
at a time.
2. Use Command builders for intermediate steps so they don't need
to be repeated
=> DAOS-623 build: Improve the preprocessing steps

src/tests/ftest/control/dmg_system_reformat.py, src/tests/ftest/daos_test/dfs.yaml, src/tests/ftest/daos_test/rebuild.yaml, src/tests/ftest/daos_test/suite.yaml, src/tests/ftest/harness/advanced.py, src/tests/ftest/harness/advanced.yaml, src/tests/ftest/nvme/pool_exclude.py, src/tests/ftest/osa/dmg_negative_test.py, src/tests/ftest/osa/offline_drain.py, src/tests/ftest/osa/offline_extend.py, src/tests/ftest/osa/offline_parallel_test.py, src/tests/ftest/osa/offline_reintegration.py, src/tests/ftest/osa/online_extend.py, src/tests/ftest/osa/online_reintegration.py, src/tests/ftest/pool/evict.py, src/tests/ftest/scripts/main.sh, src/tests/ftest/server/daos_server_restart.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/command_utils_base.py, src/tests/ftest/util/daos_core_base.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/test_utils_pool.py
Dynamically increase the avocado runner.timeout.* values by 200 seconds
for each pool created in the test to allow for enough time for each pool
destroy during test cleanup when the test times out.
Test-tag: pr daily_regression pool_timeout osa,-offline_drain_with_less_pool_space,-offline_reintegrate_with_less_pool_space
=> DAOS-9865 test: Increase tearDown() timeout for pool destroy (#8721)

src/tests/ftest/daos_vol/bigio.py, src/tests/ftest/daos_vol/bigio.yaml, src/tests/ftest/daos_vol/h5_suite.yaml, src/tests/ftest/mpiio/hdf5.yaml, src/tests/ftest/scripts/setup_nodes.sh, src/tests/ftest/util/vol_test_base.py
- bump ulimits using 80_daos_limits.conf to override the one deployed by provisioning
- increase crt_timeout for some hdf5 test to 60 (since the timeout used was 10 which will cause RPC timeouts)
Test-tag: volbigio volunit hdf5testsuite
=> DAOS-6654 bigio: re-enable the HDF5 VOL bigio test

src/control/server/config/server.go
While using a single access point is allowed, it provides no
redundancy. This log message provides a warning for the admin.
=> DAOS-10863 control: Log warning for single access point

site_scons/components/__init__.py
When build the dependent component SPDK in aarch64 platform, an error is
reported because the incorrect march=haswell. When is ARM platform, set
march to native.
Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>
=> DAOS-10871 build: Fix aarch64 build SPDK error (#10871)

src/common/cont_props.c, src/common/pool_map.c, src/container/cli.c, src/container/srv_container.c, src/container/srv_target.c, src/control/cmd/daos/property.go, src/include/daos/cont_props.h, src/include/daos/container.h, src/include/daos/object.h, src/include/daos/pool_map.h, src/include/daos_cont.h, src/include/daos_prop.h, src/include/daos_srv/pool.h, src/object/cli_obj.c, src/object/srv_ec_aggregate.c, src/placement/jump_map.c, src/placement/pl_map.c, src/placement/tests/jump_map_place_obj.c, src/placement/tests/place_obj_common.c, src/rebuild/scan.c, src/tests/suite/daos_container.c
Handle DAOS_PROP_CO_REDUN_LVL cont property, which can be set as
DAOS_PROP_CO_REDUN_RANK/DAOS_PROP_CO_REDUN_NODE when
container create.
Can create container with rf_lvl parameter by cmd line, such as -
"daos cont create --pool= --properties=rf_lvl:2 ...", or in C code passing
DAOS_PROP_CO_REDUN_LVL type property to daos_cont_create().
With related changes in placement, container RF check, and property
handling.
Change "struct daos_obj_md" to add md_fdom_lvl parameter.
Add a test case to verify it.
=> DAOS-10215 container: handle DAOS_PROP_CO_REDUN_LVL cont property

src/tests/suite/dfs_unit_test.c
=> DAOS-625 test: fix test typo

CONTRIBUTING.md, README.md, docs/admin/troubleshooting.md, docs/dev/contributing.md, docs/overview/fault.md, docs/overview/terminology.md
switch doc URLs from http to https
Doc-only: true
=> DAOS-9355 doc: switch doc URLs to https

.gitignore
_structures_from_macros_.h was inadvertently changed to
_structures_from_macros.h so update the file and remove
the obsolete entry.
=> DAOS-623 git: Fix .gitignore after name change of generated file

mkdocs.yml
switch doc URLs in mkdocs.yml from http to https
Doc-only: true
=> DAOS-5579 doc: switch doc URLs in mkdocs.yml to https

docs/admin/env_variables.md, src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_srv.c
Ideally, dedicated DXT batched commit ULT for each opened container
is the most simple model. But it may be burden for the engine if
opened containers become more and more on the target. So it is
necessary to restrict the count for DTX batched commit ULTs on the
target. It can be adjusted via the environment "DTX_BATCHED_ULT_MAX"
when load the module. "0" means unlimited.
=> DAOS-10352 dtx: limited DTX batched commit ULTs

src/ddb/README.md, src/ddb/ddb_cmd_options.c, src/ddb/ddb_cmd_options.h, src/ddb/ddb_commands.c, src/ddb/ddb_main.c, src/ddb/ddb_parse.c, src/ddb/ddb_parse.h, src/ddb/tests/ddb_cmd_options_tests.c, src/ddb/tests/ddb_commands_tests.c, src/ddb/tests/ddb_main_tests.c, src/ddb/tests/ddb_test_driver.c, src/ddb/tests/ddb_test_driver.h, src/ddb/tests/ddb_vos_tests.c
- Added help option and help command to ddb.
- Renamed main test functions to be consistent.
- Updated readme to include output from help options.
- Provide list of commands when incorrect command is used.
=> DAOS-10895 ddb: Improve help

src/client/api/event.c
since the function is supposed to be called when everything is locked, we
should do the lock on the ev with no eq outside of the function.
=> DAOS-10756 event: move the ev lock to outside the comp_locked function

docs/admin/deployment.md
Include information on setting option when using daos_server storage
prepare as well as setting the parameter in the server config file.
=> DAOS-10132 doc: Describe disable_vfio usage in admin guide (#9249)

src/control/lib/telemetry/counter.go, src/control/lib/telemetry/counter_test.go, src/control/lib/telemetry/duration.go, src/control/lib/telemetry/duration_test.go, src/control/lib/telemetry/gauge.go, src/control/lib/telemetry/gauge_test.go, src/control/lib/telemetry/promexp/collector.go, src/control/lib/telemetry/promexp/collector_test.go, src/control/lib/telemetry/snapshot.go, src/control/lib/telemetry/snapshot_test.go, src/control/lib/telemetry/telemetry.go, src/control/lib/telemetry/test_helpers.go, src/control/lib/telemetry/timestamp.go, src/control/lib/telemetry/timestamp_test.go, src/control/server/storage/bdev/backend.go, src/control/server/storage/bdev/syscall_amd64.go, src/control/server/storage/bdev/syscall_arm64.go
go:build support both amd64 and arm64.
Dup2 function is added to support both amd64 and arm64.
=> DAOS-10872 control: Fix aarch64 build control errors (#10872) 

src/object/cli_ec.c
It is possible that different shard fetches go to different parity
shards, they got recov_lists with different parity epoch in the case
vos aggregation happens asynchronously on different parity shards
that may merge adjacent parity exts to lower epoch.
In obj_ec_stripe_list_add() for that case can take higher epoch for
data recovery.
Master branch PR: #9384
=> DAOS-10831 obj: Fix a bug in EC degraded fetch's data recovery

src/cart/crt_context.c, src/cart/crt_ctl.c, src/cart/crt_group.c, src/cart/crt_hg.c, src/cart/crt_hg.h, src/cart/crt_init.c, src/cart/crt_internal_types.h, src/cart/crt_swim.c, src/include/cart/api.h, src/tests/ftest/cart/dual_provider_server.c
- New API added to query secondary provider uri:
crt_self_uri_get_secondary()
- Fixed internal bug where provider info was stored per provider type
rather than per provider instance. This would prevent/clash in situations
when the same provider is used as a primary and a secondary
=> CART-89 multiprovider: Fix issues, add new api

src/bio/bio_buffer.c, src/cart/crt_context.c, src/cart/crt_self_test_client.c, src/cart/crt_self_test_service.c, src/common/profile.c, src/dtx/dtx_common.c, src/dtx/dtx_cos.c, src/dtx/dtx_resync.c, src/gurt/examples/telem_consumer_example.c, src/gurt/heap.c, src/gurt/telemetry.c, src/include/gurt/common.h, src/object/obj_tx.c, src/placement/pl_map_common.c, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c, src/vos/vos_dtx_iter.c
- Skip-func-hw-test: true Skip-func-test: true Quick-Functional: true Test-tag: dfuse
- Skip-func-hw-test: true Skip-func-test: true Quick-Functional: true Test-tag: dfuse Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>
- Change free calls.
- Skip-func-hw-test: true Skip-func-test: true Quick-Functional: true Test-tag: dfuse
=> DAOS-623 cq: Remove legacy D_FREE_PTR macro.

src/README.md, src/bio/README.md, src/client/api/README.md, src/client/java/README.md, src/container/README.md, src/control/security/README.md, src/control/server/README.md, src/object/README.md, src/placement/JUMP_MAP.md, src/placement/README.md, src/placement/RING_MAP.md, src/pool/README.md, src/proto/README.md, src/rdb/README.md, src/rebuild/README.md, src/security/README.md, src/vos/README.md
rename /doc/ to /docs/ in src markdown files
Doc-only: true
=> DAOS-5579 doc: rename doc to docs in src markdown files

docs/user/filesystem.md
document that DFS directories do not include . and .. entries
Doc-only: true
=> DAOS-10493 doc: document DFS dot-dir behaviour

docs/user/filesystem.md
document that DFS directories do not include . and .. entries
Doc-only: true
=> DAOS-10493 doc: document DFS dot-dir behaviour (#9433)

utils/config/daos_server.yml
clarify default engine logfile in daos_server.yml
Doc-only: true
=> DAOS-9644 doc: clarify default engine logfile in server.yml

utils/config/daos_server.yml
clarify default engine logfile in daos_server.yml
Doc-only: true
=> DAOS-9644 doc: clarify default engine logfile in server.yml (#9436)

docs/admin/hardware.md
update hardware.md to explain that/how multiple NICs are
supported on the DAOS client side.
Doc-only: true
=> DAOS-9901 doc: explain multi-NIC support on the client (#8765)

docs/admin/pool_operations.md
improve pool create documentation, explaining the three ways
to specify pool capacity (per engine in Bytes, global in Bytes,
global as a percentage of free capacity).
Doc-only: true
=> DAOS-10039 doc: improve pool create documentation

ci/provisioning/post_provision_config_common_functions.sh
Allow provider-testing branches to use pre-built daos RPMs.
Test-tag: pr
=> DAOS-9989 test: Enable provider-testing branches

ci/provisioning/post_provision_config_common_functions.sh
Allow provider-testing branches to use pre-built daos RPMs.
=> DAOS-9989 test: Enable provider-testing branches (#9506)

src/tests/suite/daos_array.c
daos_array_read with type=DAOS_OT_ARRAY, the array->byte_array is false,
then it don't invoke tse_task_register_cbs to register check_short_read_cb,
so iod.arr_nr_short_read isn't modified.
Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>
=> DAOS-10898 obj: fix the assert in small_io test (#10898)

src/tests/suite/daos_epoch.c
The test case expecte to check with arg->co_info.ci_lsnapshot.
Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>
=> DAOS-10899 test: use expected variable to do assert checking (#10899)

src/client/dfuse/il/int_posix.c
Only run the destructor if run in the same thread id as the constructor.
some programs, at least sh, run lightweight threads so can end up
calling the destructor more times than the constructor, so to avoid
deadlocks save the tid in the constructor and only run the destructor
if it matches.
=> DAOS-10354 dfuse: Check thread id in interception library destructor. (#9103)

docs/admin/deployment.md, src/control/cmd/daos_server/storage.go, src/control/fault/code/codes.go, src/control/server/config/server.go, src/control/server/engine/config_test.go, src/control/server/server_utils.go, src/control/server/server_utils_test.go, src/control/server/storage/config.go, src/control/server/storage/faults.go
Apply the following NVMe emulation related changes:
- If AIO is being used for NVMe emulation, don't require IOMMU and/or
VFIO to be enabled.
- Disallow the use of emulated and non-emulated NVMe in the same engine
config.
- Disable VMD if NVMe emulation is being used.
=> DAOS-10473 control: Do not require IOMMU for emulated NVMe (#9272)

src/client/dfuse/ops/ioctl.c, src/include/dfuse_ioctl.h, src/tests/suite/dfuse_test.c
- DAOS-6540 dfuse: Add a ioctl to fetch the dfuse user.
- Add a test cose.
- Back out file mode check.
=> DAOS-6540 dfuse: Add a ioctl to fetch the dfuse user.

SConstruct, site_scons/build_info/__init__.py, site_scons/build_info/base.py, site_scons/daos_build.py, site_scons/prereq_tools/__init__.py, site_scons/prereq_tools/base.py, site_scons/prereq_tools/mocked_tests.py, site_scons/site_tools/doneapi.py, site_scons/site_tools/extra/__init__.py, site_scons/site_tools/extra/extra.py, site_scons/site_tools/protoc/__init__.py, utils/cq/daos_pylint.py, utils/sl/fake_scons/SCons/Action/__init__.py, utils/sl/fake_scons/SCons/Subst/__init__.py, utils/sl/fake_scons/SCons/Tool/gcc/__init__.py
Handle fake_scons as it's own class with specific requirments.
This means it's tested more strictly, and we can disable specific
checks for it.
Update daos_pylint to accept directories on the command line.
=> DAOS-7821 cq: Update daos_pylint handling of fake_scons.

utils/githooks/pre-commit.d/10-update-copyright
Use the correct sed options, and do not run the hook on merge
commits.
=> DAOS-10873 cq: Fix the date githook on OS X.

src/cart/crt_context.c, src/include/cart/api.h, src/tests/ftest/network/cart_self_test.py, src/tests/ftest/network/cart_self_test.yaml
- New API crt_get_nr_secondary_providers() added.
Returns number of secondary providers initialized by CART.
- crt_self_uri_get_secondary() fixed to return -DER_NONEXIST
when no secondary providers are initialized
=> CART-89 multi_prov: new api, fixes

src/utils/wrap/mpi/SConscript
without mpi install, the base_env_mpi is null, compile error:
AttributeError: 'NoneType' object has no attribute 'AppendUnique'
In addition, there is base_env_mpi.AppendUnique(LIBPATH=[Dir('.') at
line 33.
Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>
=> DAOS-11030 mpi: fix build error when the mpi is not installed

ci/provisioning/post_provision_config_common_functions.sh
Fix allowing provider-testing branches to use pre-built daos RPMs.
=> DAOS-9989 test: FIx enabling provider-testing branches

Jenkinsfile
We are close to the limit for this stage, bump it up a bit to
avoid frequent intermittent failures.
=> DAOS-11054 test: Bump memcheck stage timeout to 45 minutes

src/client/dfs/dfs.c, src/tests/suite/dfs_unit_test.c
Store the root stbuf on dfs_mount and use that when doing a lookup
on root object.
=> DAOS-10938 DFS: fix lookup on "/" not setting stbuf

src/bio/bio_buffer.c, src/bio/bio_context.c, src/bio/bio_internal.h, src/include/daos_srv/bio.h, src/include/daos_srv/pool.h, src/include/daos_srv/vea.h, src/include/daos_srv/vos.h, src/include/daos_srv/vos_types.h, src/pool/srv_target.c, src/vea/tests/vea_stress.c, src/vea/tests/vea_ut.c, src/vea/vea_api.c, src/vea/vea_free.c, src/vea/vea_internal.h, src/vos/vos_gc.c, src/vos/vos_pool.c
1. Instead of triggering aging frags flush in vea_reserve() and vea_free()
internally, using a dedicated ULT to do flush externally, there are two
advantages of external flush:
- GC & Aggregation ULT won't be blocked on waiting for the NVMe unmap
completion;
- It's easier to control the flush rate and other parameters according
to space pressure;
Standalone VOS still uses internal flush triggered in vea_reserve() and
vea_free().
2. Use the new BIO API bio_blob_unmap_sgl() to unmap multiple freed frags
in parallel, that could reduce the total unmap latency;
3. Stop merging the aging frag when it reached a size threshold, otherwise,
the frag could be constantly merged with newly freed frag and stay in
the aging buffer for too long;
4. Adjust flush parameters to make the frags being flushed …
=> DAOS-8943 vea: optimize aging frag flushing

src/object/srv_obj_migrate.c, src/tests/ftest/daos_test/suite.yaml
replicate data needs to keep the same epoch during rebuild,
otherwise it will mess up its relationship with parity epoch,
and cause data corruption during rebuild.
=> DAOS-10833 object: keep the same epoch for replicate rebuild

src/include/daos_srv/iv.h, src/pool/srv_internal.h, src/pool/srv_iv.c
Assume these IV update process.
1. pool service start, IV prop update asynchronously.
2. set property.
3. pool IV update asynchronously.
Since 1 and 3 are asynchrnously, especially if 1 needs to
retry, then 1 might arrive later than 3 for one engine, so
let's add epoch to iv key, and if the incoming IV update epoch
is older than the current epoch of the entry, let's ignore
the update.
Test-tag: pr offline_reintegration_with_rf offline_reintegration_oclass
Test-tag: test_ec_offline_rebuild test_ec_offline_rebuild_agg_disabled
Test-tag: test_ec_offline_rebuild_agg_default
Test-tag: test_ec_offline_agg_during_rebuild
=> DAOS-10435 IV: add update and sync epoch.

src/include/daos_srv/iv.h, src/pool/srv_internal.h, src/pool/srv_iv.c
Assume these IV update process.
1. pool service start, IV prop update asynchronously.
2. set property.
3. pool IV update asynchronously.
Since 1 and 3 are asynchrnously, especially if 1 needs to
retry, then 1 might arrive later than 3 for one engine, so
adding epoch to pool IV key, and if the incoming IV update epoch
is older than the current epoch of the entry, let's ignore
the update.
Test-tag: pr offline_reintegration_with_rf offline_reintegration_oclass
Test-tag: test_ec_offline_rebuild test_ec_offline_rebuild_agg_disabled
Test-tag: test_ec_offline_rebuild_agg_default
Test-tag: test_ec_offline_agg_during_rebuild
=> DAOS-10435 IV: add update and sync epoch for pool IV.

docs/admin/pool_operations.md
remove 2.2 features from 2.0 cherry-pick
(dmg pool upgrade and dmg pool create --size in %)
Doc-only: true
=> DAOS-10039 doc: improve pool create documentation (#9443)

src/client/array/dc_array.c, src/common/pool_map.c, src/common/tse.c, src/common/tse_internal.h
1. fix a tse bug of dep task check in tse_task_complete_callback
In tse_task_complete_callback() it checks if new dep task added in
task's completion callback, by check dtp_dep_cnt. But a problem
is the dep task possibly be scheduled/executed immediately and be
completed even before checking parent task' dtp_dep_cnt, that
could cause parent task be completed 2 times.
This patch fixes it by adding generation of parent task.
2. take extra refcount in tse_task_complete_callback
3. fix a bug in dfs adjust_array_size_cb()
original code possibly create+schedule multiple dep tasks in
adjust_array_size_cb(), that may cause firstly scheduled dep task
complete immediately and then complete parent task, but still
possible add more other dep tasks cause trouble in race condition.
This patch fixes it …
=> DAOS-11029 tse/dfs: bug fix in tse or dfs about task

src/client/dfs/dfs.c, src/tests/suite/dfs_unit_test.c
Store the root stbuf on dfs_mount and use that when doing a lookup
on root object.
Co-authored-by: Dalton Bohning <dalton.bohning@intel.com>
=> DAOS-10938 DFS: fix lookup on "/" not setting stbuf (#9527)

docs/QSG/build_from_scratch.md, docs/QSG/docker.md, docs/QSG/setup_rhel.md, docs/dev/development.md
Doc changes from PR 8816 (commit 6a422f5edade3a1de4ea0885e915c826850b154a)
were made to the wrong file and then deleted in PR 9422 (commit
cf420e9786d2168d096fc63a4ae786754ea25263).
Add pip/venv instructions to the QSG/installation section.
Also clean up references to CentOS 7 in the documentation.
=> DAOS-9881 doc: re-add python venv instructions

site_scons/components/__init__.py
Having this check requires some hacky additions to extra_include_dirs
and it doesn't seem to actually affect the build.  So try removing it.
=> DAOS-11053 build: Remove check for dpdk/rte_eal.h (#9588)

src/container/cli.c, src/container/oid_iv.c
Change a few TRACE message to MD for debugging
OID allocation.
=> DAOS-10932 oid: Change trace to MD for oid alloc

src/include/daos_errno.h, src/object/cli_obj.c, src/object/obj_internal.h, src/object/obj_tx.c, src/vos/vos_dtx.c
For any transaction, the DTX entry in the active DTX table is unique.
So when we allocate new DTX entry in the active DTX table, we should
not hit the entry with the same DTX ID. If that happened, then there
may be two possible cases:
1. Client resent the RPC but without set 'RESEND' flag.
2. Client reused the DTX ID for different modifications.
Currently, the 1st case is more suspected which is DAOS client logic
bug, need to be fixed correspondingly. If it is the 2nd case, we can
re-generate new TX ID.
=> DAOS-10870 dtx: handle active DTX entry update properly

src/cart/crt_init.c
- Fix a bug that caused provider settings (like sep override) to
not take effect due to mixed arguments
=> CART-89 bug: Fix provider settings

src/bio/bio_buffer.c, src/bio/bio_bulk.c, src/bio/bio_internal.h, src/bio/bio_xstream.c, src/tests/ftest/util/telemetry_utils.py
When DMA buffer is exhausted by heavy workload, the IO request which
failed to grab DMA buffer will have to wait for prior IO's completion,
starvation could happen in following scenario:
- Request A failed to grab buffer, it starts waiting for prior IO done;
- Later request B arrived server, it's pushed into ABT pool FIFO queue
for execution;
- Prior IO completed, it wakeup request A, and request A is pushed into
ABT pool FIFO queue for execution;
- Request B will be processed before request A, and request A may have
to wait for another round if DMA buffer is used up by request B;
Another issue is that once prior IO completed, all waiters will be
woken up even if the released buffer can satisfy only fewer waiters,
that'll waste CPU cycles unnecessarily.
This patch solved the starvation …
=> DAOS-10372 bio: wait DMA buffer in FIFO order

src/object/srv_obj.c
To avoid resource being exhausted in network stack layers, yield needs
be called on initiating every 1k IOVs bulk transfers, so that cart
progress will be able to kick in to complete some inflight bulk transfers.
Test-tag: pr hdf5testsuite
=> DAOS-10399 object: yield on initiating bulk transfers

src/control/server/server_utils.go
In the rare case that the node processing a SWIM dead event loses
leadership before the membership can be updated, handle the error
by re-forwarding the event so that the new leader will process it.
=> DAOS-10903 control: Handle leadership loss while processing SWIM events (#9498)

src/control/lib/hardware/hwloc/bindings.go, src/control/lib/hardware/hwloc/provider.go, src/control/lib/hardware/hwloc/provider_test.go, src/control/lib/hardware/hwloc/testdata/tds-0002.xml, src/control/lib/hardware/mocks.go, src/control/lib/hardware/pci.go, src/control/lib/hardware/pretty.go, src/control/lib/hardware/pretty_test.go, src/control/lib/hardware/topology.go, src/control/lib/hardware/topology_test.go
The hwloc library provides quite a bit of information about
block devices; make this available. Also adds support for
non-PCI (e.g. PMEM) devices.
=> DAOS-10813 control: Add block device details to topology (#9313)

src/tests/ftest/nvme/health.py, src/tests/ftest/nvme/health.yaml
Test-tag: nvme_health mdtest_small
To account for nodes with reduced nvme space, create UP TO 40 pools
instead of exactly 40 pools.
=> DAOS-10500 test: Make nvme/health more flexible (#9346)

src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_leader.c, src/chk/chk_rpc.c, src/chk/chk_upcall.c, src/engine/drpc_ras.c, src/include/daos_prop.h, src/include/daos_srv/daos_chk.h, src/mgmt/srv_chk.c, src/mgmt/srv_internal.h, src/mgmt/tests/mocks.c, src/pool/srv_layout.c, src/pool/srv_pool_check.c
The pool label is mainly used by MS to lookup pool UUID by label.
The PS recorded pool label is some kind of the backup. So if the
MS known pool label does not match the pool label recorded by PS,
then trust MS as long as MS known pool label is not NULL. Related
repair will not happen on check leader, instead, it will be done
on the PS leader during CHK__CHECK_SCAN_PHASE__CSP_POOL_CLEANUP.
If the admin wants to recover pool label on MS with the pool info
on PS, then it will use DRPC_METHOD_CHK_REG_POOL drpc upcall.
The patch also contains some other fixes:
1. Only handle dangling pool within the given pools check list.
2. Some code cleanup for "uint32_t" and "int32_t" usage in chk.
=> DAOS-9599 chk: handle inconsistent pool label

.github/workflows/pr-metadata.yml, ci/jira_query.py, utils/docker/Dockerfile.checkpatch
Add a GitHub action to parse Jira ticket information for a PR and update the PR
metadata to keep it in sync with Jira. Add a comment to the PR which will be edited
to keep it up-to-date, and report the ticket description and status as well as adding
a link.
Warn on several issues around malformed PR titles (which become part of the commit
message when landed) and if work is happening on tickets which are not marked
as In Progress or In Review.
Set labels for 2.2 and 2.4 release tickets, as well as anything that should be treated
as a priority.
=> DAOS-7821 gha: Add code to report Jira status into GitHub. (#9628)

src/common/rsvc.c, src/pool/srv_pool.c
Cherry-pick of the same change on master branch to release/2.2 branch.
Issue 1: explicit null dereference
rsvc_client_complete_rpc() when rc_crt is -DER_INVAL in a debug log
dereferences ep->ep_grp that may be NULL. Remove that part of the
log message.
from src/pool/srv_pool.c callers, should fix:
CID: 105938, 105927, 105888, 105870, 105862, 105844, 105830, 105829
CID: 105815
from src/container/srv_container.c callers, should fix:
CID: 105873
Issue 2: unchecked return value of rsvc_client_choose()
Add error return value checks.
Addresses issues in ds_pool_extend() and ds_pool_target_update_state():
CID: 105812, 105847
=> DAOS-10960 pool,container,rsvc: fix Coverity issues

src/container/srv_container.c
Cherry pick of master PR 9545 to release/2.2 branch.
Before this change, when a new container was created, the metadata
rdb value for key ds_cont_prop_cont_global_version was written as
a 64-bit value in cont_prop_write(). However, the intent for this
recently-added key is a uint32_t typed value. Also, an inconsistency
exists with the pool/container layout upgrade code, upgrade_cont_cb()
writing the value as uint32_t. This results in some containers with
64-bit version values, and others with 32-bit values.
With this change, the cont_prop_write() and cont_prop_read() functions
are changed to write and read a 32-bit cont_global_version value in rdb,
to agree with the upgrade_cont_cb() code.
Signed-off-by: …
=> DAOS-10929 container: fix size of cont_global_version value (#9545)

src/tests/ftest/erasurecode/online_rebuild_single.py
Test-tag: ec_online_rebuild_single
Summary
- Presently, test fails to destroy the container/pool intermittently with DER_BUSY/DER_TIMEOUT status. 
- We need to make sure rebuild is not happening when we try to destroy container/pool. Once rebuild is done, pool/container destroy should work fine. 
=> DAOS-11056 test: Check for rebuild status to complete.

src/common/tests_dmg_helpers.c
=> DAOS-10954 test: Fix for CID 21969

src/container/srv_target.c, src/include/gurt/common.h, src/object/obj_rpc.h, src/object/srv_ec_aggregate.c, src/object/srv_obj.c
1. Fix a problem when reply orwo->orw_epoch
When the sc_ec_agg_eph_boundry moved ahead, should reply that epoch to
client rather than original fetch epoch, so client can take that higher
epoch to fetch again, rather than use the original epoch that may cause
dead loop.
2. Fix a bug in ds_obj_ec_rep_handler
the vos_obj_array_remove() is used to remove the parity ext, but it
used incorrect epoch range that possibly cause parity mismatch
on different parity shards. 
And a few other small refines.
=> DAOS-10655 obj: fix possible dead loop for degraded fetch again

src/control/cmd/dmg/server.go, src/control/lib/control/server.go, src/control/server/ctl_ranks_rpc.go, src/tests/ftest/control/dmg_server_set_logmasks.py, src/tests/ftest/control/dmg_server_set_logmasks.yaml, src/tests/ftest/control/dmg_storage_scan_scm.py, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py
Set system name in RPC message when setting engine log masks to avoid
interoperability check failures.
Add ftest to sanity check that the dmg server set-logmasks returns with
success to avoid regressions.
=> DAOS-10820 control: Set system name in set engine log masks RPC (#9471)

src/control/cmd/daos/acl.go
Fix a miss in Go code that was preventing [daos cont get-acl --path]
cmd to work, failing with "ERROR: daos: ap cannot be nil with --path"
error message, due to no cmd args struct passed.
Change-Id: Iff96a5311b22b7abd15bcb43d4d7046be9afe61c
=> DAOS-10664 daos: [daos cont get-acl --path] cmd to work

src/common/tests/utest_common.c, src/vos/tests/vts_mvcc.c
Addresses CID: 21874, 21952
Rather than ignoring return value of remove, print an error if
it fails and return an error to the caller.
Fix an issue checkpatch saw in same code
Add an assertion for 21748. This doesn't clear coverity issue but I believe it is a
false positive with this change.
=> DAOS-10953 test: Detect issue with remove in unit test code (#9613)

ci/provisioning/post_provision_config_common_functions.sh, utils/rpms/packaging/rpm_chrootbuild
To allow dnf builddep to install less-than-latest versions of packages
which have a BR: < $latest.
Also use --setopt=best=0 with dnf upgrade to not error out when the newest
version of a package is available but > R:.
Use dnf with mock on CentOS 7 to be able to use nobest.
=> DAOS-10683 build: Use nobest with mock

ci/provisioning/post_provision_config_common_functions.sh, utils/rpms/packaging/rpm_chrootbuild
To allow dnf builddep to install less-than-latest versions of packages
which have a BR: < $latest.
=> DAOS-623 build: Use nobest with mock

src/control/server/instance_exec.go, src/control/server/instance_exec_test.go, src/control/server/instance_storage.go, src/control/server/instance_storage_test.go, src/control/server/server_utils.go, src/control/server/storage/bdev.go, src/control/server/storage/bdev/backend.go, src/control/server/storage/bdev/backend_test.go
The previous approach to cleanup hugepages created by SPDK running in
engine process was to remove in a callback triggered on engine exit.
The criteria for hugepage file removal was that file owner matched the
running user UID and the PID encoded in the filename matched that of the
exited engine process.
This approach will not always remove all hugepages created by DAOS
processes, for example in the case where daos_server is sent SIGKILL or
when different users execute daos_server.
A more aggressive approach is implemented in this PR whereby, on
completion of engine storage format, a callback is triggered which removes
all hugepages created by SPDK that belong to a no-longer-active process
(identified by PID encoded in the filename).
=> DAOS-11031 control: Clean hugepages on engine startup (#9625)

src/bio/bio_buffer.c, src/bio/bio_bulk.c, src/bio/bio_internal.h, src/bio/bio_xstream.c, src/tests/ftest/util/telemetry_utils.py
When DMA buffer is exhausted by heavy workload, the IO request which
failed to grab DMA buffer will have to wait for prior IO's completion,
starvation could happen in following scenario:
- Request A failed to grab buffer, it starts waiting for prior IO done;
- Later request B arrived server, it's pushed into ABT pool FIFO queue
for execution;
- Prior IO completed, it wakeup request A, and request A is pushed into
ABT pool FIFO queue for execution;
- Request B will be processed before request A, and request A may have
to wait for another round if DMA buffer is used up by request B;
Another issue is that once prior IO completed, all waiters will be
woken up even if the released buffer can satisfy only fewer waiters,
that'll waste CPU cycles unnecessarily.
This patch solved the starvation …
=> DAOS-10372 bio: wait DMA buffer in FIFO order (#9584)

src/object/obj_internal.h, src/placement/tests/jump_map_place_obj.c, src/placement/tests/pl_bench.c, src/placement/tests/place_obj_common.c
DAOS-10943 src/placement/tests/pl_bench.c
DAOS-10971 src/placement/tests/place_obj_common.c
DAOS-10955 src/placement/tests/jump_map_place_obj.c
DAOS-11006 fix coverity warning in shard_task_abort
=> DAOS-11006 obj: fix coverity issues

src/control/lib/hardware/hwloc/bindings.go, src/control/lib/hardware/hwloc/provider_test.go
The hwloc library produces size values in kB, but the
printing library expects bytes.
=> DAOS-11120 control: Fix block device size display

src/tests/ftest/deployment/network_failure.py, src/tests/ftest/deployment/network_failure.yaml, src/tests/ftest/deployment/target_failure.py, src/tests/ftest/util/network_utils.py, src/tests/ftest/util/test_utils_container.py
Cherry-pick of PR8977.
Add network failure test.
Also refactor target failure test by moving `verify_health()`
to test_utils_container.py
See https://github.com/daos-stack/daos/pull/8977 for
the network failure test description.
Test-tag: network_failure target_failure
=> DAOS-10003 test: Add network failure and target failure tests - release/2.2 (#8977)

src/tests/ftest/nvme/fault.py, src/tests/ftest/nvme/fault.yaml, src/tests/ftest/util/nvme_utils.py
Test-tag: nvme_fault pr,hw,medium
Improve nvme/fault.py
- Increase capacity to 15% to avoid IOR finishing before setting the
device faulty
- Simplify yaml params
- Remove unused params
- More logging
=> DAOS-10534 test: improve nvme/fault.py (#8982)

src/tests/ftest/soak/utils.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/data_mover_utils.py, src/tests/ftest/util/duns_utils.py
Test-tag: datamover,-iosysadmin
Simplify the data mover test base to make it easier to add tests.
- Enhance and move `format_daos_path` to `duns_utils.format_path`
- New `set_dm_params` that takes a simplified set of params.
- Deprecate `set_datamover_params`. Keep compatibility so all tests
cases don't need to be updated immediately.
- Rename `self.parent` to `self.posix_root`
- Rename 'src_path' and 'dst_path' to 'src' and 'dst' for consistency
=> DAOS-9820 test: simplify datamover test base (#8109)

src/include/daos/object.h, src/object/obj_rpc.h, src/object/obj_tx.c, src/object/srv_obj.c, src/object/srv_obj_remote.c
master-commit: 02c6ccdfdb152ebd5facb885a4ad2f92c325791e
For OSA case, more than one object shards may reside on the same
DAOS target. So daos_cpd_disp_ent::dcde_write_cnt may be not the
real count of update sub requests. When dispatch CPD RPC, we need
to clone related sub requests to avoid sending some irrelevant sub
request to the remote DAOS target. During the clone operation, we
need to avoid copying the same sub request that are for the same
object's different but co-located shards repeatedly.
=> DAOS-10348 object: clone sub requests for CPD RPC

src/container/srv_target.c, src/include/gurt/common.h, src/object/obj_rpc.h, src/object/srv_ec_aggregate.c, src/object/srv_obj.c
1. Fix a problem when reply orwo->orw_epoch
When the sc_ec_agg_eph_boundry moved ahead, should reply that epoch to
client rather than original fetch epoch, so client can take that higher
epoch to fetch again, rather than use the original epoch that may cause
dead loop.
2. Fix a bug in ds_obj_ec_rep_handler
the vos_obj_array_remove() is used to remove the parity ext, but it
used incorrect epoch range that possibly cause parity epoch mismatch
on different parity shards. That also possible cause dead loop.
And a few other small refines.
=> DAOS-10655 obj: fix possible dead loop for degraded fetch again (#9504)

src/cart/crt_hg.c
Catch another case where a hg return code is being passed as DER_HG
rather than converting to a daos error code where possible.
This allows the stack to identify non-recoverable failures better
and to correctly abort or handle errors rather than spinning.
=> DAOS-11007 cart: Convert return codes from hg to daos on rpc completion.

debian/changelog, debian/control, src/bio/bio_device.c, src/bio/bio_monitor.c, src/control/server/storage/bdev/backend_vmd.go, src/control/server/storage/bdev/backend_vmd_test.go, utils/build.config, utils/rpms/daos.spec
Update DAOS source build SPDK version and patches in utils/build.config.
Update SPDK pinned version requirements in utils/rpms/daos.spec.
Resolve API breakages resulting from SPDK version change.
=> DAOS-10595 build: Update SPDK to v22.01.1 (#9063)

src/common/rsvc.c, src/pool/srv_pool.c
Cherry-pick of same master branch change to release/2.0 branch.
Issue 1: explicit null dereference
rsvc_client_complete_rpc() when rc_crt is -DER_INVAL in a debug log
dereferences ep->ep_grp that may be NULL. Remove that part of the
log message.
from src/pool/srv_pool.c callers, should fix:
CID: 105938, 105927, 105888, 105870, 105862, 105844, 105830, 105829
CID: 105815
from src/container/srv_container.c callers, should fix:
CID: 105873
Issue 2: unchecked return value of rsvc_client_choose()
Add error return value checks.
Addresses issues in ds_pool_extend() and ds_pool_target_update_state():
CID: 105812, 105847
=> DAOS-10960 pool,container,rsvc: fix Coverity null deref issue

src/tests/ftest/aggregation/dfuse_space_check.py, src/tests/ftest/aggregation/dfuse_space_check.yaml
Test-tag: dfusespacecheck
Test-repeat: 5
- Use int type for dd count
- Better logging
- Cleanup some functions
- Disable aggregation when writing files to get accurate space
measurement
=> DAOS-10466 test: improve dfusespacecheck

src/include/daos_srv/pool.h, src/rebuild/srv.c
Makito and Samir observed the following assertion failure after
restarting engines.
#0  raise () from /lib64/libc.so.6
#1  abort () from /lib64/libc.so.6
#2  __assert_fail_base () from /lib64/libc.so.6
#3  __assert_fail () from /lib64/libc.so.6
#4  pool_map_get_version (map=0x0) at src/common/pool_map.c:2852
#5  ds_pool_get_version (pool=0x7f0ca063c690, pool=0x7f0ca063c690) at
src/include/daos_srv/pool.h:296
#6  pc=rpc@entry=0x7f0ca0998d30, p_rpt=p_rpt@entry=0x7f0ca83a77b0) at
src/rebuild/srv.c:2101
#7  rebuild_tgt_scan_handler (rpc=0x7f0ca0998d30) at
src/rebuild/scan.c:954
#8  crt_handle_rpc (arg=0x7f0ca0998d30) at src/cart/crt_rpc.c:1654
#9  ABTD_ythread_func_wrapper (p_arg=0x7f0ca83a78a0) at
arch/abtd_ythread.c:21
#10 make_fcontext () from /usr/lib64/libabt.so.1
#11 ?? ()
The …
=> DAOS-10622 pool: Fix ds_pool_get_version for NULL sp_map

src/common/pool_map.c, src/dtx/dtx_resync.c, src/include/daos/pool_map.h, src/include/daos_errno.h, src/include/daos_srv/pool.h, src/mgmt/rpc.h, src/mgmt/srv_target.c, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_internal.h, src/object/obj_rpc.h, src/object/obj_tx.c, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/pool/rpc.c, src/pool/rpc.h, src/pool/srv_internal.h, src/pool/srv_pool.c, src/pool/srv_target.c, src/pool/srv_util.c, src/tests/suite/daos_rebuild_simple.c, src/vos/vos_obj_cache.c
During reintegration,  if inflight I/O arrives before dicarding,
then vos_dicard might dicard those data written by inflight I/O,
so let's discard all of the original data first, and if inflight
I/O arrives before discard finished, then it will return
DER_UPDATE_AGAIN and retry.
=> DAOS-10525 reintegrate: inflight I/O after discarding object

src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_dir.yaml, src/tests/ftest/datamover/large_file.py, src/tests/ftest/datamover/large_file.yaml, src/tests/ftest/util/command_utils_base.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/data_mover_utils.py
Test-tag: datamover,-iosysadmin,-dm_posix_meta_entry
- Add `KeywordParameter` class that accepts a mapping of replaced values
- `data_mover_test_base`
- Support ppn for various datamover utils
- Use `KeywordParameter` for `posix_root`
- `large_dir` and `large_file`
- Specify ppn instead of np
- Dual-engine and move to HW Medium
- Specify posix_root in the yaml
- `large_dir`
- Remove duplicate variants in favor of the larger
- Use EC object class by default, similar to `large_file`
=> DAOS-9820 test: make large datamover tests more configurable (#8662)

src/tests/ftest/pool/list_verbose.py
pool_layout_ver and upgrade_layout_ver were added
to the dmg pool list --verbose output. Add these
to the expected dictionary in create_expected().
Refactor the new lines.
Test-tag: list_verbose pool_create_and_query
=> DAOS-11154 test: Fix pool/list_verbose.py by adding layout fields

src/dtx/dtx_resync.c
Two patches landed that had an unseen build conflict.
#9614 and #9196 
Fix the compilation error
=> DAOS-11166 dtx: Fix compiler error

src/cart/crt_hg.h, src/include/daos/common.h
Refine crt_hgret_2_der() and daos_crt_network_error() a little bit
for err code handling.
=> DAOS-11007 cart: a few refine of err code handling

src/include/daos_srv/pool.h, src/rebuild/srv.c
Makito and Samir observed the following assertion failure after
restarting engines.
#0  raise () from /lib64/libc.so.6
#1  abort () from /lib64/libc.so.6
#2  __assert_fail_base () from /lib64/libc.so.6
#3  __assert_fail () from /lib64/libc.so.6
#4  pool_map_get_version (map=0x0) at src/common/pool_map.c:2852
#5  ds_pool_get_version (pool=0x7f0ca063c690, pool=0x7f0ca063c690) at
src/include/daos_srv/pool.h:296
#6  pc=rpc@entry=0x7f0ca0998d30, p_rpt=p_rpt@entry=0x7f0ca83a77b0) at
src/rebuild/srv.c:2101
#7  rebuild_tgt_scan_handler (rpc=0x7f0ca0998d30) at
src/rebuild/scan.c:954
#8  crt_handle_rpc (arg=0x7f0ca0998d30) at src/cart/crt_rpc.c:1654
#9  ABTD_ythread_func_wrapper (p_arg=0x7f0ca83a78a0) at
arch/abtd_ythread.c:21
#10 make_fcontext () from /usr/lib64/libabt.so.1
#11 ?? ()
The …
=> DAOS-10622 pool: Fix ds_pool_get_version for NULL sp_map (#9277)

src/tests/ftest/container/multiple_delete.py, src/tests/ftest/container/multiple_delete.yaml
Pool size was too small; 44GB/rank with 8 targets.
We write 2GB of data with IOR and that could get
out of space, so increse the size to 10%, which
is about 320GB(SCM) + 320GB(NVMe)/rank in this
configuration.
Don't create a new container during IOR run because
we have already created before running it.
Refactor the code.
Test-tag: multi_container_delete agent_failure_basic
=> DAOS-11155 test: Increase pool size for container/multiple_delete.py

src/tests/ftest/ior/intercept_multi_client.py, src/tests/ftest/ior/intercept_multi_client.yaml, src/tests/ftest/util/ior_intercept_test_base.py
Test-tag: ior_intercept_multi_client
- Move ior_intercept_multi_client to HW Large
- Some Medium clusters use TCP, which is unstable
- Large clusters all have MLX / Verbs
- Improve logging
=> DAOS-10843 test: move ior_intercept_multi_client to HW Large (#9378)

src/tests/ftest/dfuse/find.py
Test-tag: dfuse_find,-manual
test_dfuse_find_perf is not ready to run in CI, so remove feature tags
so it doesn't fail when accidentally triggered.
Also misc cleanup.
=> DAOS-6530 test: remove feature tags from dfuse_find_perf (#9715)

src/tests/ftest/aggregation/dfuse_space_check.py, src/tests/ftest/aggregation/dfuse_space_check.yaml
Test-tag: dfusespacecheck
Test-repeat: 5
- Use int type for dd count
- Better logging
- Cleanup some functions
- Disable aggregation when writing files to get accurate space
measurement
=> DAOS-10466 test: improve dfusespacecheck (#9015)

src/cart/crt_hlc.c, src/client/dfs/README.md, src/client/dfs/dfs.c, src/include/cart/api.h, src/tests/suite/dfs_unit_test.c
In some data copying tools, the file is updated and the mtime is reset on the file after the update is complete. This patch account for a user set mtime and returns the latter of either the mtime update or the file modfication.
Using HLC converted from timespec allows for nsec precision.
=> DAOS-11077 dfs: fix mtime accounting for user set mtime (#9636)

src/tests/ftest/object/same_key_different_value.py, src/tests/ftest/object/same_key_different_value.yaml, utils/cq/daos_pylint.py
Test-tag: samekeydifferentvalue
- Fix current and future pylint and flake warnings.
- Misc cleanup.
=> DAOS-11165 test: fix pylint in same_key_different_value

src/pool/srv_pool.c
The ds_pool_create_handler function should unlock ds_rsvc.s_mutex if rc
is not zero when ending the RDB TX.
=> DAOS-10986 pool: Add forgotten s_mutex unlock (#9538)

src/vos/vos_iterator.c
Only reset nonexist error after iter_next and probe, to keep the
return value from other callback in vos_iterate_interal().
=> DAOS-11063 vos: check and reset NONEXIST in iter_next and probe

src/control/cmd/dmg/storage.go, src/control/lib/control/pool.go, src/control/logging/defaults.go, src/control/logging/json.go, src/control/logging/level.go, src/control/logging/level_test.go, src/control/logging/logger.go, src/control/logging/logging_test.go, src/control/logging/notice.go, src/control/logging/syslog.go, src/control/logging/syslog_test.go, src/control/server/config/server.go, src/control/server/ctl_storage_rpc.go, src/control/server/server_utils.go, src/control/server/telemetry.go
The Notice log level is between Info and Error. It is suitable for
messages that indicate a sub-optimal or degraded condition that  will
not prevent the system from functioning correctly.
- Add Notice/Noticef methods to logger.
- In syslog, Notice messages are included in syslog level "INFO".
- Update some existing Info level messages to Notice level.
Test-tag: pr control config_generate_run
=> DAOS-11175 control: Add Notice log level

src/pool/srv_pool.c
Using sizeof(struct pool_hdl) -
sizeof(((struct pool_hdl *)0)->ph_machine) to compute
old (<= 2.0) pool_hdl size is wrong since upper rounding
occurs because ph_hostname[MAXHOSTNAMELEN + 1] field size
is only 64+1=65 bytes, so sizeof(((struct pool_hdl *)0)->ph_flags) +
sizeof(((struct pool_hdl *)0)->ph_sec_capas) must be used.
=> DAOS-10471 pool: safely compute old format pool_hdl size

src/control/lib/control/pool.go, src/control/server/mgmt_pool.go, src/control/server/mgmt_pool_test.go
As part of the work done for DAOS-8237, the pool destroy RPC
handler removed the pool service label if the request was
forced. This seemed like a usability enhancement, in that
a forced destroy would always succeed from the perspective
of the admin, particularly in the case of wanting to reuse
the label. In cases where the pool was left in a destroying
state, the idea was that it would eventually be cleaned up
as part of pool creation or leadership step-up.
In hindsight, that change was probably a bad idea in that it
hides problems with the pool destroy flow at the engine level
and could lead to resource leaks. Better to leave the label
intact on the pool service so that it's clear to the admin
that the pool isn't really destroyed yet. The next challenge
is in figuring out how to convey …
=> DAOS-11073 control: Don't remove pool label during destroy

src/tests/ftest/launch.py
Increase the timeout used when running the get_remote_files.sh command
to archive the daos logs generated on remote hosts.
Test-tag: online_drain offline_drain_with_csum offline_drain_during_aggregation offline_drain_after_snapshot
=> DAOS-11170 test: Increase timeout for daos log archiving. (#9741)

site_scons/components/__init__.py, site_scons/prereq_tools/base.py
Add bin directory for patchelf so users can use the spdk
binaries without setting LD_LIBRARY_PATH
=> DAOS-11196 build: Patch rpath in SPDK binaries

src/object/obj_tx.c
The dc_tx_convert() shares the logic for object existence check
with regular transactional update/punch. For the latter case,
the logic for object existence check returns positive value to
related task sponsor to indicate that do not complete the task
until the checking existence callback. The dc_tx_convert() needs
to follow the same API instead of regarding such positive return
value as failure case.
=> DAOS-11193 object: Properly handle object existence check result

src/vos/evtree.c
Addresses CID: 21837
changes the coding style to make coverity checker happy
(cherry picked from commit 0f7ac96357f16c422183a3b2fc7654bceea72681)
=> DAOS-10967 vos: coverity issue fix (#9681)

src/vos/vos_obj.c
- fix error handling in vos_obj_del_key()
- check returned value from key_tree_delete()
(cherry picked from commit a4420a15036ee31a286cf12707841ed10f0d1af2)
=> DAOS-10968 VOS: error handling fix (#9679)

src/object/srv_obj.c
Addresses CID: 21837
echo_sgl in TLS is not an array, it should be reused as reply
buffers of all IODs.
(cherry picked from commit 3458f8b346fd980fed3f9075268a5e0e58943294)
=> DAOS-10952 object: fix coverity issue for echo_rw (#9680)

src/control/lib/control/pool.go, src/control/server/mgmt_pool.go, src/control/server/mgmt_pool_test.go
As part of the work done for DAOS-8237, the pool destroy RPC
handler removed the pool service label if the request was
forced. This seemed like a usability enhancement, in that
a forced destroy would always succeed from the perspective
of the admin, particularly in the case of wanting to reuse
the label. In cases where the pool was left in a destroying
state, the idea was that it would eventually be cleaned up
as part of pool creation or leadership step-up.
In hindsight, that change was probably a bad idea in that it
hides problems with the pool destroy flow at the engine level
and could lead to resource leaks. Better to leave the label
intact on the pool service so that it's clear to the admin
that the pool isn't really destroyed yet. The next challenge
is in figuring out how to convey …
=> DAOS-11073 control: Don't remove pool label during destroy (#9746)

src/control/cmd/dmg/storage.go, src/control/lib/control/pool.go, src/control/logging/defaults.go, src/control/logging/json.go, src/control/logging/level.go, src/control/logging/level_test.go, src/control/logging/logger.go, src/control/logging/logging_test.go, src/control/logging/notice.go, src/control/logging/syslog.go, src/control/logging/syslog_test.go, src/control/server/config/server.go, src/control/server/ctl_storage_rpc.go, src/control/server/server_utils.go, src/control/server/telemetry.go
The Notice log level is between Info and Error. It is suitable for
messages that indicate a sub-optimal or degraded condition that  will
not prevent the system from functioning correctly.
- Add Notice/Noticef methods to logger.
- In syslog, Notice messages are included in syslog level "INFO".
- Update some existing Info level messages to Notice level.
=> DAOS-11175 control: Add Notice log level (#9792)

src/tests/ftest/datamover/copy_procs.py, src/tests/ftest/datamover/dst_create.py, src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_file.py, src/tests/ftest/datamover/negative.py, src/tests/ftest/datamover/negative_space.py, src/tests/ftest/datamover/obj_large_posix.py, src/tests/ftest/datamover/obj_small.py, src/tests/ftest/datamover/posix_meta_entry.py, src/tests/ftest/datamover/posix_preserve_props.py, src/tests/ftest/datamover/posix_subsets.py, src/tests/ftest/datamover/posix_symlinks.py, src/tests/ftest/datamover/posix_types.py, src/tests/ftest/datamover/serial_large_posix.py, src/tests/ftest/datamover/serial_small.py, src/tests/ftest/deployment/basic_checkout.py, src/tests/ftest/deployment/io_sys_admin.py, src/tests/ftest/util/data_mover_test_base.py
Test-tag: datamover
- Replace DataMoverTestBase.create_cont with
TestWithServers.get_container
- Remove DataMoverTestBase.gen_uuid
=> DAOS-9827 test: datamover: use get_container

src/mgmt/srv_drpc.c
The patches for DAOS-10339 and DAOS-10300 had a conflict
that wasn't detected until after landing.
=> DAOS-10300 build: Fix merge conflict after landing

src/pool/srv_pool.c
Support 2.0 pools with old format of pool_hdl so this handles can
be evicted and 2.0 pools can be upgraded to 2.2 format
=> DAOS-10471 pool: support older pool_hdl format (#9649)

src/tests/ftest/rebuild/widely_striped.yaml
Increased following set of parameters ignorer to get the test passing.
Test timeout increased more than double.
Cart Timeout increased from 10 secs to 60 secs
Swim Timeouts needed to be bumped. Using following values:
env_vars:
SWIM_PROTOCOL_PERIOD_LEN=2000
SWIM_SUSPECT_TIMEOUT=19000
SWIM_PING_TIMEOUT=1900
Service Replicas Increased from 1 to 5
Rebuild Timeout doubled
Pool Query Timeout doubled
Test-tag: rebuild_widely_striped
=> DAOS-10887 test: Increased set of parameters in widely_striped.py (#9827)

.gitignore, utils/githooks/commit-msg.d/10-watermark, utils/githooks/commit-msg.d/10-watermark.py, utils/githooks/pre-commit, utils/githooks/prepare-commit-msg
A few problems exist with the exisitng githook.  It doesn't
handle commit cancellations
It also doesn't work with git commit -v
Use python instead as it makes it a little simpler
Also, it adds slightly more robust check that the githooks actually
ran.
=> DAOS-11214 githooks: Fix commit cancellations

src/tests/ftest/deployment/critical_integration.py
Test-tag: passwdlessssh_versioncheck
- Fix possible index out of range error
=> DAOS-10869 test: fix passwdlessssh index error

src/tests/ftest/deployment/basic_checkout.py, src/tests/ftest/deployment/basic_checkout.yaml, src/tests/ftest/util/performance_test_base.py
As part of this pr performance_test_base.py is moved from
ftest/performance dir to ftest/util.
Adding ior-easy and mdtest-easy scenarios to the test script
Separating ior-small and mdtest-small from the basiccheckout
sanity test.
Test-tag: basiccheckout performance,-manual
=> DAOS-9898 tests: Add ior/mdtest-easy to basic_checkout.py  (#9397)

src/tests/ftest/deployment/basic_checkout.yaml
Reduce mdtest number of files/dirs and block size for
datamover section of the test.
Test-tag: basiccheckout
=> DAOS-9898 tests: Small improvements in test yaml (#9542)

src/control/server/mgmt_system.go, src/control/system/raft/raft.go
In rare circumstances, this method could be called after
leadership is lost but before the worker loop is exited.
Add a final check for leadership before invoking the group
update dRPC in order to avoid trying to make the group
update on a non-leader replica.
Also fixes a bug where a sync group update could be followed
by an unnecessary async group update.
=> DAOS-11134 control: Add leadership check to doGroupUpdate()

src/bio/bio_buffer.c, src/common/btree.c, src/common/btree_class.c, src/common/mem.c, src/common/tests/utest_common.c, src/include/daos/mem.h, src/include/daos_srv/bio.h, src/vea/tests/vea_stress.c, src/vea/tests/vea_ut.c, src/vea/vea_alloc.c, src/vea/vea_api.c, src/vea/vea_free.c, src/vea/vea_hint.c, src/vos/evtree.c, src/vos/tests/vts_common.h, src/vos/vos_aggregate.c, src/vos/vos_common.c, src/vos/vos_dtx.c, src/vos/vos_gc.c, src/vos/vos_ilog.h, src/vos/vos_internal.h, src/vos/vos_io.c, src/vos/vos_layout.h, src/vos/vos_obj.c, src/vos/vos_pool.c, src/vos/vos_space.c, src/vos/vos_tree.c
This commit addresses two stories. DAOS-11041 enhances the umem
interfaces to cover all the pmemobj interfaces DAOS currently
uses. DAOS-11042 makes use of the new interfaces in other modules.
Signed-off-by: Sherin T George <sherin-t.george@hpe.com>
=> DAOS-11042: Enhanced umem interfaces to abstract pmdk calls

src/tests/ftest/erasurecode/offline_rebuild.yaml, src/tests/ftest/erasurecode/rebuild_disabled.yaml, src/tests/ftest/erasurecode/rebuild_disabled_single.yaml
Any test that runs multiple test variants with a different set of server
hosts should start and stop the servers between each test variant.
Test-tag: ec_offline_rebuild_array ec_disabled_rebuild_array ec_disabled_rebuild_single
=> DAOS-11201 test: Always restart servers when mux'ing server hosts

src/tests/ftest/pool/create_all_hw.yaml
Increase the timeout of functional test pool/create_all_hw.py.
=> DAOS-11182 test: Increase timeout for pool/create_all_hw.py

src/control/server/mgmt_system.go, src/control/system/raft.go
In rare circumstances, this method could be called after
leadership is lost but before the worker loop is exited.
Add a final check for leadership before invoking the group
update dRPC in order to avoid trying to make the group
update on a non-leader replica.
Also fixes a bug where a sync group update could be followed
by an unnecessary async group update.
=> DAOS-11134 control: Add leadership check to doGroupUpdate() (#9737)

src/control/cmd/daos_server/start.go, src/control/cmd/dmg/storage.go, src/control/lib/control/pool.go, src/control/logging/notice.go, src/control/server/config/server.go, src/control/server/ctl_storage_rpc.go, src/control/server/ctl_storage_rpc_test.go
- Added a prefix to notice messages on the command line output.
- Removed "WARNING" prefix from messages that are now notice level.
=> DAOS-11175 control: Add prefix to notice logging

src/control/cmd/daos/container.go, src/utils/daos_hdlr.c, src/utils/daos_hdlr.h
Moved the handler over into the Go side of things in
order to build a string slice of OIDs for JSON output.
=> DAOS-11217 tools: Fix daos cont list-obj JSON output

src/control/SConscript, src/control/lib/ipmctl/nvm.go, src/control/lib/ipmctl/nvm_ctest_linux_amd64.go, src/control/lib/ipmctl/nvm_linux_amd64.go, src/control/lib/ipmctl/nvm_stubs.go, src/control/lib/ipmctl/nvm_types.go, src/control/lib/ipmctl/nvm_types_linux_amd64.go, src/control/lib/spdk/nvme.go, src/control/lib/spdk/nvme_default.go, src/control/lib/spdk/nvme_stub.go, src/control/lib/spdk/spdk.go, src/control/lib/spdk/spdk_default.go, src/control/lib/spdk/spdk_stub.go
Provide stubbing for the SPDK C library interface so that go does not
link to the actual library unless the spdk build flag is provided.
Also tidy stubbing of the libipmctl C library interface.
=> DAOS-11239 control: Stub SPDK library interface in go unit tests

src/tests/ftest/checksum/csum_basic.yaml
Test-tag: basic_checksum_object
Increase the test timeout due intermittent failures noticed under VM.
=> DAOS-10596 test: Increase the csum_basic test timeout (#9010)

Jenkinsfile, ci/provisioning/post_provision_config.sh, ci/provisioning/post_provision_config_common_functions.sh, ci/provisioning/post_provision_config_nodes.sh, ci/provisioning/post_provision_config_nodes_EL_8.sh, ci/rpm/test_daos_node.sh, utils/rpms/packaging/rpm_chrootbuild, utils/scripts/install-el8.sh
Add CI_PROVISINING_POOL, CI_PR_REPOS and CI_FI_el8_TEST parameters.
Utilize the new parameters when configuring repos.
Always disable daos RPMs repo unless RPM-test-version or
CI_RPM_TEST_VERSION are used.
Fixes for launchable.
=> SRE-92 ci: Updates to allow testing images

src/tests/ftest/scrubber/csum_fault.yaml, src/tests/ftest/scrubber/target_auto_eviction.yaml
Test-tag: test_scrubber_csum_fault test_scrubber_target_auto_eviction
Summary: The fault is not getting injected at random intervals.
Trying to reduce the target and increase IOR block size to see
if it has some effect.
=> DAOS-11179 test: Reduce target,increase block size.

src/include/daos_api.h, src/object/cli_obj.c, src/object/obj_internal.h, src/object/obj_tx.c, src/tests/suite/daos_dist_tx.c
A race similar to the one described by the Jira ticket affects
dc_tx_get_epoch. This patch moves the tse_task_reinit call inside
tx_lock, so that dc_tx_get_epoch knows that the epoch task has not run
its completion callback complete_epoch_task yet.
If the tse_task_reinit call fails, this patch makes sure that we
complete the task.
Due to tse limitations, we can't support invoking operations of one TX
from multiple tse_sched objects. This patch adds a note to the
documentation of daos_tx_open.
=> DAOS-11226 object: Fix dc_tx_get_epoch races

src/dtx/dtx_common.c, src/dtx/dtx_internal.h, src/dtx/dtx_resync.c, src/dtx/dtx_srv.c
During DTX resync, the new DTX leader will send DTX_CHECK RPC
to other alive DTX participant(s) to query related DTX status.
If related DTX entry does not exist on the non-leader and DTX
reindex on such non-leader is not completed yet, then the non
leader will reply to the new leader with -DER_INPROGRESS that
will cause the new leader to retry the DTX_CHECK RPC sometime
later. But if DTX reindex is not triggerred on the non-leader,
then the new leader will retry for ever. So the patch triggers
DTX reindex before DTX resync scanning.
The patch also adjusts the logic of filter DTX entries when
DTX resync to avoid skipping some DTX entries.
=> DAOS-11180 dtx: trigger DTX reindex before DTX resync

src/object/obj_ec.h, src/object/srv_ec.c, src/object/srv_internal.h, src/object/srv_mod.c, src/object/srv_obj.c
add EC full-stripe and partial update metrics on dtx leader node.
path - pool -> EC_update -> full_stripe/partial.
=> DAOS-11241 obj: add EC full-stripe and partial update metrics

src/tests/ftest/osa/offline_reintegration.yaml
Backport of the patch 747fd6d updating the object class and RF for
offline_reintegration.
The oclass RP_2G8 is not adapted for the test
osa/offline_reintegration.py:offline_reintegration_oclass.  Indeed, some
shards of the ior test file could be lost during the process of the many
cycles of rebuild/reintegration. These lost shards, could eventually
makes the fds_open call of ior to fail.
More details on this issue are available in the DAOS-9313 ticket.
=> DAOS-10803 test: Update the object class and RF. (#7690)

src/tests/suite/daos_checksum.c
Two issues:
* Check rc from dmg_pool_set_prop for success
* Replace unsupported "continuous" scrub value with "timed"
=> DAOS-11238 test: Fix daos checksum test

src/dtx/dtx_rpc.c
When close the container, the DTX logic will try to flush
committable ones. Such DTX commit may hit failures. If we
hide related failures inside dtx_commit, it will misguide
the dtx_flush_on_close() logic as to the DTX flush may be
assert for related undeletable DTX entries.
=> DAOS-11187 dtx: properly handle DTX commit failure

utils/cq/daos_pylint.py
The el8 version of pylint has the manager in a different
place.
=> DAOS-7821 build: Adjust pylint to work with distro pkg

src/bio/bio_buffer.c, src/bio/bio_context.c, src/bio/bio_internal.h, src/bio/bio_xstream.c
Stop issuing new NVMe I/O when the per-xstream inflight IOs reachs
a threshold.
Confine the number of batched blob unmap calls in bio_blob_unmap_sgl()
to workaroud the mysterious segfault. The default max unmap count is
set to 32, and it can be configured through DAOS_SPDK_MAX_UNMAP_CNT.
Test-tag: pr ec_aggregation_default ec_aggregation_time ec_online_rebuild_mdtest
=> DAOS-11092 bio: restrict inflight ios

docs/admin/pool_operations.md, src/tests/ftest/pool/svc.yaml
Pull request #9119 has changed the default number of PS replicas from 3
to 5 via the new pool property svc_rf. It has also disallowed the
specification of even numbers of PS replicas. This patch updates the
expectations of the pool/svc.py tests to reflect those changes.
The old rule that avoids rank 0 when selecting PS ranks causes the
maximum number of PS ranks to be 4, instead of 5, for 5-rank pools that
include rank 0. The plan is to remove that rule via the deployment of
multiple MS replicas in testing. Hence, we simply expect 4 PS ranks for
svc_params_none, svc_params_0, and svc_params_5 in this patch.
Test-tag: pool_svc
=> DAOS-11281 tests: Update pool/svc.py expectations

site_scons/components/__init__.py
The url resolves from 01org to intel and may be causing some
issues in CI.
=> DAOS-623 build: Remove indirect link for isal

src/container/srv_oi_table.c, src/dtx/dtx_resync.c, src/include/daos_srv/rebuild.h, src/placement/pl_map.c, src/pool/srv_pool.c, src/pool/srv_target.c, src/rebuild/rebuild_internal.h, src/rebuild/rebuild_iv.c, src/rebuild/scan.c, src/rebuild/srv.c, src/vos/vos_obj_cache.c
1. add dst max version to rebuild task, any further pool
map update after max version will be ignored during reintegration.
2. Do not need broadcast the ranks which is being queued to
be reintegrated after the current reintegration start.
3. add rebuild_generation to rpt and tls lookup.
4. add more debug message or infomation to the rebuild process.
5. various minor fixes for master changing during rebuild.
6. reclaim the object if rebuild fails
=> DAOS-10524 rebuild: master leader changing during rebuild

src/tests/ftest/server/metadata.py, src/tests/ftest/server/metadata.yaml
Test-tag: server,metadata pr,hw,large
- Fix thread_manager usage in server/metadata.py
- Misc cleanup
=> DAOS-11109 test: fix thread_manager usage

docs/QSG/cloud.md, docs/cloud/index.md, docs/index.md, mkdocs.yml
add documentation for DAOS in the Cloud to 2.2 docs,
including DAOS on GCP references
Doc-only: true
=> DAOS-9355 doc: add infos for DAOS in the Cloud (#9169)

.rpmignore
=> DAOS-11121 build: don't ship mercury-ucx with DAOS 2.0

.rpmignore
=> DAOS-11248 build: don't ship daos-mofed shim RPM

.rpmignore
=> DAOS-11248 build: don't ship daos-mofed shim RPM (#9934)

src/vos/tests/evt_ctl.c
The compiler erroneously is flagging a NULL pointer where
the value can't be NULL.  Work around the issue by adding
an assertion in the appropriate case.
=> DAOS-11289 build: Fix compiler warning on amd64 clang

src/tests/ftest/launch.py
So rpc logs won't be messed up to make cart_logparse work.
=> DAOS-10835 test: enable D_LOG_FILE_APPEND_PID in the client (#9399)

src/common/misc.c, src/gurt/hash.c, src/include/gurt/hash.h, src/tests/suite/daos_obj.c
Refine d_hhash_link_insert() -
1. for PTR type handle hash table, need not take any extra lock
2. for non-PTR type, refine d_hash_rec_insert_anonym()
add feat bit D_HASH_FT_NO_KEYINIT_LOCK set that for d_hhash
to avoid take all buckets' lock
Addd a simple test fo obj_open perf, by testing on boro obj_open
per second increased from 427.36 OPs/S to 313038.03 OPs/S.
(./daos_test -i -u 46, only one engine and client is enough)
=> DAOS-11146 client: refine lock handling in d_hhash_link_insert()

src/container/srv_container.c, src/gurt/misc.c, src/include/daos/common.h, src/include/daos_srv/pool.h, src/include/gurt/common.h, src/pool/srv_pool.c, src/pool/srv_target.c, src/pool/srv_util.c
Remove map_ranks_class and move map_ranks_merge to
d_rank_list_range.
And DRAIN rank are still accessible until the rank
is excluded from the pool_map, so broacast RPC should
still include DRAIN ranks.
=> DAOS-10525 pool: cleanup MAP rank init (#9183)

src/dtx/dtx_resync.c, src/dtx/dtx_srv.c
If the DTX_CHECK RPC handler hits -DER_INPROGRESS failure on some
target, then it means that the committed DTX entries on such target
are not re-indexed. Under such case, we need to trigger DTX re-index
on the target for subsequent (retry) DTX_CHECK RPC. Otherwise, it may
cause more DTX_CHECK RPCs to be retried (for ever), as to related DTX
resync cannot complete on some DTX leaders.
=> DAOS-11180 dtx: re-index committed DTX entries for DTX_CHECK

src/gurt/debug.c
Increase DD_ENV_MAX_LEN to 128 to avoid DD_MASK
exceed the maximum size.
=> DAOS-11295 gurt: increase DD_ENV_MAX_LEN

src/tests/ftest/deployment/critical_integration.py
Test-tag: passwdlessssh_versioncheck
Fix possible index out of range error
=> DAOS-10869 test: fix passwdlessssh index error (#9785)

src/tests/ftest/daos_test/dfs.yaml, src/tests/ftest/scripts/post_process_xml.sh, src/tests/ftest/util/daos_core_base.py, src/tests/ftest/util/general_utils.py
Description:
Cherry pick daos-10882 to release_2.2
modified:   src/tests/ftest/daos_test/dfs.yaml
modified:   src/tests/ftest/scripts/post_process_xml.sh
modified:   src/tests/ftest/util/daos_core_base.py
modified:   src/tests/ftest/util/general_utils.py
Test-tag: dfs_test dfuse_test daos_test
* Set the CMOCKA* environment variables correctly to ensure cmocka results
are generated in the expected location to correctly log any test errors.
(Add codes to verify cmocka_result.xml file exists before scp them)
* Update post_process_xml.sh to handle multiple testsuite entries
=> DAOS-10882 test: Include cmocka.xml results for dfs_test (#9674)

src/container/srv_layout.c, src/object/cli_obj.c, src/placement/jump_map.c, src/placement/pl_map.c, src/tests/ftest/datamover/dst_create.yaml, src/tests/ftest/datamover/posix_preserve_props.yaml, src/tests/ftest/util/daos_utils.py, src/tests/suite/daos_aggregate_ec.c, src/tests/suite/daos_obj.c, src/tests/suite/daos_obj_ec.c, src/tests/suite/daos_rebuild_common.c, src/tests/suite/daos_rebuild_ec.c, src/tests/suite/daos_rebuild_simple.c, src/tests/suite/daos_test_common.c, src/tests/suite/dfs_par_test.c, src/utils/daos_autotest.c
1) set the default fault domain level when create container
(DAOS_PROP_CO_REDUN_LVL property) as DAOS_PROP_CO_REDUN_NODE.
In test code still create container on RANK fault domain lvl.
2) get container's dcp_redun_lvl for daos_obj_generate_oid().
3) change pl_map_query() to check input parameter of attr->pa_domain
so can get different domain_nr for different containers (as
fault domain lvl may be different).
4) fix a bug in get_num_domains()
Test-tag: pool_rf_property
=> DAOS-10215 container: set default fault domain level on NODE

src/control/server/storage/bdev/backend.go, src/control/server/storage/bdev/backend_test.go
Add detailed logging of file processing during the hugepage cleanup that
is performed before the engines are started in order to aid
troubleshooting when engines don't start due to insufficient hugepages.
=> DAOS-11031 control: Log details of hugepage cleanup when starting engine

Jenkinsfile, src/chk/SConscript, src/chk/chk_common.c, src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_leader.c, src/chk/chk_rpc.c, src/chk/chk_srv.c, src/common/pool_map.c, src/ddb/tests/SConscript, src/include/daos/pool_map.h, src/include/daos/rsvc.h, src/include/daos_srv/daos_mgmt_srv.h, src/include/daos_srv/pool.h, src/mgmt/rpc.c, src/mgmt/rpc.h, src/mgmt/srv_internal.h, src/mgmt/srv_pool.c, src/mgmt/srv_target.c, src/pool/srv_pool.c, src/pool/srv_pool_check.c, src/pool/srv_pool_map.c
When DAOS check start, all involved check engines will report their
known pools' information, including the pool service replicas, pool
label and related storage allocation, to the check leader via reply.
After the pool list consolidation in the pass_1, for each pool, the
check leader will send related pool information to its pool service
leaders via new RPC - CHK_POOL_MBS.
On the check engine side, the pool service leader compares the pool
map with these information pushed from the check leader and handles
the following cases:
1. An target has some allocated storage but does not appear in the
pool map. Under such case, the associated space will be deleted
from the engine by default.
2. An target has some allocated storage and is marked as "DOWN" or
"DOWNOUT" in the pool map. For this …
=> DAOS-9595 chk: consolidate pool membership

src/pool/srv_layout.h, src/pool/srv_pool.c
credentials must be saved to be accessible in situations like when
if the pool leader is switched or all servers restart.
So save them in pool handle db.
=> DAOS-11164 pool: also save credentials in pool handle db

src/vos/tests/evt_ctl.c
The compiler erroneously is flagging a NULL pointer where
the value can't be NULL.  Work around the issue by adding
an assertion in the appropriate case.
=> DAOS-11289 build: Fix compiler warning on amd64 clang (#9926)

src/engine/init.c
Assuming this can be run from the context of a limited stack ULT, we
need to be careful how much stack space we use.  Reduce it from 1024
to 256 which still gives us a max of 32 entries.
Also clean up the code a bit and print when we don't get a stacktrace
at all.
=> DAOS-11296 engine: Reduce size of stack used by print_backtrace (#9951)

src/tests/ftest/server/metadata.py, src/tests/ftest/server/metadata.yaml
Test-tag: server,metadata pr,hw,large
- Fix thread_manager usage in server/metadata.py
- Misc cleanup
- Bump test_metadata_server_restart timeout to 960
=> DAOS-11109 test: fix thread_manager usage (#9784)

src/container/srv_container.c, src/container/srv_oi_table.c, src/gurt/misc.c, src/include/daos/common.h, src/include/daos_srv/pool.h, src/include/daos_srv/rebuild.h, src/include/gurt/common.h, src/placement/pl_map.c, src/pool/srv_pool.c, src/pool/srv_target.c, src/pool/srv_util.c, src/rebuild/rebuild_internal.h, src/rebuild/rebuild_iv.c, src/rebuild/scan.c, src/rebuild/srv.c
1. add dst max version to rebuild task, any further pool
map update after max version will be ignored during reintegration.
2. Do not need broadcast the ranks which is being queued to
be reintegrated after the current reintegration start.
3. add rebuild_generation to rpt and tls lookup.
4. add more debug message or infomation to the rebuild process.
5. various minor fixes for master changing during rebuild.
6. reclaim the object if rebuild fails
Conflicts:
src/dtx/dtx_resync.c
src/rebuild/rebuild_iv.c
src/rebuild/scan.c
=> DAOS-11116 rebuild: master leader changing during rebuild (#9744)

src/tests/ftest/erasurecode/rebuild_disabled.py, src/tests/ftest/erasurecode/rebuild_disabled.yaml, src/tests/ftest/erasurecode/rebuild_fio.py, src/tests/ftest/erasurecode/rebuild_fio.yaml, src/tests/ftest/util/ec_utils.py, src/tests/ftest/util/test_utils_pool.py, src/vos/evtree.c
1. For array remove, the RT_OVERLAP_INCLUDED range @same_epoch should be
safe to ignore to avoid failure in that case.
2. a few refine for test script
Test-tag: pr ec_online_rebuild_fio ec_offline_rebuild_fio ec_disabled_rebuild_array
=> DAOS-10916 object: some refine related with EC obj aggregation

src/include/daos_srv/daos_engine.h, src/object/srv_obj_migrate.c, src/rebuild/rebuild_internal.h, src/rebuild/scan.c, src/rebuild/srv.c
Store scan objects target id, so it does not need excessive
iteration when sending the objects to the new target.
=> DAOS-10607 rebuild: put rebuild obj cache by tgt id

src/tests/ftest/aggregation/basic.yaml, src/tests/ftest/ior/intercept_basic.yaml, src/tests/ftest/ior/intercept_messages.py, src/tests/ftest/ior/intercept_messages.yaml, src/tests/ftest/ior/intercept_multi_client.yaml, src/tests/ftest/ior/intercept_verify_data_integrity.yaml, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/command_utils_base.py, src/tests/ftest/util/daos_racer_utils.py, src/tests/ftest/util/dfuse_utils.py, src/tests/ftest/util/ior_test_base.py, src/tests/ftest/util/job_manager_utils.py, utils/cq/words.dict
Test-tag: pr daily_regression ior_intercept aggregatebasic daos_racer daosracer
Support passing client env_vars in test yamls. These can be specified at
a global level under `client/env_vars`, or a per-cmd level as
`<cmd>/env_vars`.
This is currently supported by any command inheriting from
ExecutableCommand. Conservatively, only a subset of tests are initially
updated.
- Refactor EnvironmentVariables
- add bi-directional to_list and from_list
- add bi-directional to_export_str and from_export_str
- Update IOR tests using D_LOG_MASK to instead pass in the yaml.
=> DAOS-9221 test: pass client variables in yaml

src/control/server/engine/config.go, src/control/server/engine/config_test.go
The field wasn't being updated in the engine config.
=> DAOS-11311 control: Fix srx_disabled config field (#9960)

src/pool/srv_layout.h, src/pool/srv_pool.c
credentials must be saved to be accessible in situations like when
if the pool leader is switched or all servers restart.
So save them in pool handle db.
=> DAOS-11164 pool: also save credentials in pool handle db (#9861)

src/include/daos_srv/daos_engine.h, src/object/srv_obj_migrate.c, src/rebuild/rebuild_internal.h, src/rebuild/scan.c, src/rebuild/srv.c
Store scan objects target id, so it does not need excessive
iteration when sending the objects to the new target.
=> DAOS-10607 rebuild: put rebuild obj cache by tgt id (#9812)

src/tests/ftest/cart/no_pmix_corpc_errors.c, src/tests/ftest/cart/no_pmix_group_test.c, src/tests/ftest/cart/no_pmix_group_version.c
Fix misspellings in test code, as describe in DAOS-11160.
./src/tests/ftest/cart/no_pmix_corpc_errors.c:  DBG_PRINT("Senidng shutdown to all nodes\n");
./src/tests/ftest/cart/no_pmix_group_test.c:    DBG_PRINT("Senidng shutdown to all nodes\n");
./src/tests/ftest/cart/no_pmix_group_version.c: DBG_PRINT("Senidng shutdown to all nodes\n");
Signed-off-by: Kurniawan Alfizah <kurniawan.alfizah@intel.com>
=> DAOS-11160 test: Fixing Misspelling of 'Sending'

src/control/SConscript, src/control/cmd/dmg/telemetry.go, src/control/lib/control/pprof.go, src/control/lib/control/pprof_stub.go, src/control/lib/telemetry/promexp/collector.go, src/control/lib/telemetry/promexp/collector_test.go, src/control/lib/telemetry/telemetry.go, src/control/server/server.go, src/control/server/telemetry.go, src/tests/ftest/util/telemetry_utils.py
The older implementation used regexps for picking out labels,
but this was highly inefficient with large numbers of pools.
Also fixes a couple of bugs in the prometheus naming scheme:
* Network provider name should be a label value, not part of the metric name
* NVMe device address should be a label value, not part of the metric name
=> DAOS-11381 control: Optimize Prometheus metrics exporter

src/tests/ftest/osa/dmg_negative_test.yaml
Test-tag: osa_dmg_negative_test
The osa/dmg_negative_test.py tests is taking around 18-19 minutes. There is
possibility the test crosses 20 minutes on some clusters. The timeout seems to
on borderline. Increasing the test timeout from 1200 to 1800 (to be on safe side).
=> DAOS-11191 test: Increase osa/dmg_negative_test.py timeout. (#9054)

src/control/SConscript, src/control/cmd/dmg/telemetry.go, src/control/lib/control/pprof.go, src/control/lib/control/pprof_stub.go, src/control/lib/telemetry/promexp/collector.go, src/control/lib/telemetry/promexp/collector_test.go, src/control/lib/telemetry/telemetry.go, src/control/server/server.go, src/control/server/telemetry.go, src/tests/ftest/util/telemetry_utils.py
The older implementation used regexps for picking out labels,
but this was highly inefficient with large numbers of pools.
Also fixes a couple of bugs in the prometheus naming scheme:
- Network provider name should be a label value, not part of the metric name
- NVMe device address should be a label value, not part of the metric name
=> DAOS-11381 control: Optimize Prometheus metrics exporter (#9983)

src/tests/ftest/object/same_key_different_value.py, src/tests/ftest/object/same_key_different_value.yaml
Test-tag: samekeydifferentvalue
- Fix current and future pylint and flake warnings in same_key_different_value
- Misc cleanup.
=> DAOS-11165 test: fix pylint in same_key_different_value (#9762)

src/tests/ftest/aggregation/basic.yaml, src/tests/ftest/ior/intercept_basic.yaml, src/tests/ftest/ior/intercept_messages.py, src/tests/ftest/ior/intercept_messages.yaml, src/tests/ftest/ior/intercept_multi_client.yaml, src/tests/ftest/ior/intercept_verify_data_integrity.yaml, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/command_utils_base.py, src/tests/ftest/util/daos_racer_utils.py, src/tests/ftest/util/dfuse_utils.py, src/tests/ftest/util/ior_test_base.py, src/tests/ftest/util/job_manager_utils.py
Test-tag: pr daily_regression ior_intercept aggregatebasic daos_racer daosracer
Support passing client env_vars in test yamls. These can be specified at
a global level under `client/env_vars`, or a per-cmd level as
`<cmd>/env_vars`.
This is currently supported by any command inheriting from
ExecutableCommand. Conservatively, only a subset of tests are initially
updated.
- Refactor EnvironmentVariables
- add bi-directional to_list and from_list
- add bi-directional to_export_str and from_export_str
- Update IOR tests using D_LOG_MASK to instead pass in the yaml.
=> DAOS-9221 test: pass client variables in yaml (#8628)

src/bio/bio_bulk.c, src/bio/bio_internal.h, src/object/srv_obj.c
Mercury is able to support concurrent bulk transfers against single
bulk handle, so the server bulk cache could be improved to create
single bulk handle per DMA chunk, and all bulk transfers over the
same chunk will share the same handle.
With this change, fewer handles will be created and more importantly,
bulk chunk depopulate/populate doesn't need to destroy/create handles
anymore, that'll be helpful for dealing with the potential bulk cache
thrashing problem caused by complex IO patterns.
Minor fix to BIO metrics to count only the non-empty bulk groups.
=> DAOS-11318 bio: one bulk handle per DMA chunk

src/common/tests/sched.c, src/common/tse.c
Allow tse_task_add_dependent() if task/dep_task belong to different
scheduler. To support two use cases -
1) map_refresh(), different IO tasks (may with different scheduler)
caused pool map refresh, new map_refresh task may depend on
inflight dp_map_task on different scheduler
2) dc_tx_get_epoch(), if TX's IO tasks created on different scheduler.
=> DAOS-11227 client: allow tse_task_add_dependent for different scheduler

docs/QSG/setup_rhel.md, docs/QSG/setup_suse.md, docs/admin/predeployment_check.md
Document that MOFED is a prereq on IB fabrics that needs to be
installed before installing DAOS.
Doc-only: true
=> DAOS-10889 doc: document MOFED prereq on IB

src/tests/ftest/rebuild/container_rf.yaml
Description: increase container_rf testtime with 120 sec
Test-tag: test_rebuild_with_container_rf
=> DAOS-11291 test: rebuild/container_rf.py:RbldContRfTest.test_rebuild_with_container_rf - tearDown timeout

Jenkinsfile, src/chk/chk_engine.c, src/chk/chk_leader.c, src/include/daos_srv/pool.h, src/pool/srv_pool.c
That mainly includes the following:
1. Handle the inconsistent pool label (based on former comparing result
with management service) if decide to trust MS known pool label.
2. Revoking all pool connections recorded in the pool service.
signed-off-by: Fan Yong <fan.yong@intel.com>
=> DAOS-9599 chk: pool cleanup for CR

.github/workflows/landing-builds.yml
gcc build on ARM64 was disable due to a compiler issue
that has been worked around since then.
Add ARM build on leap and rocky.
=> DAOS-10431 build: add gcc and leap/rocky build on ARM64

src/control/cmd/daos/container.go, src/control/lib/daos/hlc.go, src/control/lib/daos/hlc_test.go, src/control/lib/daos/status_test.go
Provide a Go type wrapper for cart HLC values. Handles
conversion into human-readable timestamps.
Updates `daos cont query` to display a human-readable
timestamp in addition to the HLC for the LatestSnapshot
field.
=> DAOS-3916 control: Add daos.HLC type

src/dtx/dtx_resync.c, src/vos/vos_dtx.c, src/vos/vos_dtx_iter.c
It includes the following fixes:
1. Skip new non-committed DTX when check visibility for rebuild
Up layer rebuild logic guarantees that the rebuild scan will not be
triggered until DTX resync has been done on all related targets. So
here, if rebuild logic hits non-committed DTX entry, it must be for
new IO that version is not older than rebuild, then it is invisible
to rebuild. Related new IO corresponding to such non-committed DTX
has already been sent to the in-rebuilding target.
2. Skip new DTX during DTX resync
Even if current target was the DTX leader, but if the version of
the DTX is older than DTX resync version, we still need to resync
it. Because its sponsor may be dead (if not dead, then skip it).
=> DAOS-11035 dtx: fix some DXT related issues

ci/jira_query.py
In the case of a badly formatted message, give user a better
error message.  Also, add a link to Commit Comments documentation.
=> DAOS-623 ci: Handle an index error in jira_query.py

src/control/system/raft/database.go, src/control/system/raft/mocks.go, src/control/system/raft/raft.go
In rare cases, there could be a race between replaying logs
and system queries that results in erroneous pool cleanup
attempts on leader step-up.
=> DAOS-11438 control: Call raft.Barrier() after leadership step-up

src/tests/suite/daos_obj.c
=> DAOS-11419 test: update io test to use proper str length for oclass

src/tests/ftest/container/fill_destroy_loop.py, src/tests/ftest/container/fill_destroy_loop.yaml
Cherry pick DAOS-8465 (pr-9859) to release_2.2.
Description:  repeat following steps:
(1)Create Pool and Container.
(2)Fill the pool with random block data size, verify return code is as expected
DER_NOSPACE -1007 when no more data can be written to the container.
(3)destroy the container
Test-tag: fill_cont_pool_stress
=> DAOS-8465 test: Loop to fill and destroy container and pool. (#9859)

src/tests/ftest/scripts/main.sh
The checksum/csum_error_logging.py test generates a cmocka result that
needs to be processed by the post_process_xml.sh script.  Updating
main.sh to include running post_process_xml.sh against the
FTEST_checksum.
Also fixing an error in utils/cq/daos_pylint.py that was preventing git
commit from working.
Test-tag: daos_test basic_checksum_object csum_error_log
=> DAOS-11237 test: Collect checksum cmocka results (#9909)

src/tests/ftest/control/dmg_telemetry_io_basic.py, src/tests/ftest/control/dmg_telemetry_io_basic.yaml
* Moving the control/dmg_telemetry_io_basic.py test from the VM to HW
Small functional test stage.
* pylint fixes.
Test-tag: test_io_telmetry_metrics_basic
=> DAOS-10837 test: Move dmg_telemetry_io_basic.py to HW Small (#9952)

src/object/srv_obj.c
It is normal that the CPD RPC handler detects DTX conflict
with other transactions. Under such case, it will generate
some log messages that should not use D_ERROR().
=> DAOS-11236 object: do not log DER_TX_RESTART as error

src/client/dfs/README.md, src/client/dfs/dfs.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/ops/setattr.c, src/tests/suite/dfs_unit_test.c
DAOS HLC starts on 2021, which means a user would not be able to set
mtime on files before that. Fix the mtime setting in DFS to use timespec
(which changes the layout to add the nano sec granularity) instead of the
HLC to support older dates.
=> DAOS-11433 dfs: fix mtime set to not rely on DAOS HLC

src/dtx/dtx_resync.c, src/vos/vos_dtx.c, src/vos/vos_dtx_iter.c
It includes the following fixes:
1. Skip new non-committed DTX when check visibility for rebuild
Up layer rebuild logic guarantees that the rebuild scan will not be
triggered until DTX resync has been done on all related targets. So
here, if rebuild logic hits non-committed DTX entry, it must be for
new IO that version is not older than rebuild, then it is invisible
to rebuild. Related new IO corresponding to such non-committed DTX
has already been sent to the in-rebuilding target.
2. Skip new DTX during DTX resync
Even if current target was the DTX leader, but if the version of
the DTX is older than DTX resync version, we still need to resync
it. Because its sponsor may be dead (if not dead, then skip it).
=> DAOS-11035 dtx: fix some DXT related issues (#10056)

src/common/tse.c, src/object/obj_tx.c, src/pool/cli.c
For the task that need to be handled via distributed transaction,
the client side IO logic will convert it to a transactional task.
During dc_tx_convert(), the original task maybe freed because of
the dependency on the sub-task(s) for existence check inside the
dc_tx_attach(). That will cause the "task" to become invalid for
subsequent process for the conversion.
To avoid above bad case, the patch moves the TX commit logic for
task conversion into related existence check callback before the
TX release.
=> DAOS-11231 dtx: handle dependency during task conversion

src/client/dfs/README.md, src/client/dfs/dfs.c, src/client/dfuse/dfuse_core.c, src/client/dfuse/ops/setattr.c, src/tests/suite/dfs_unit_test.c
DAOS HLC starts on 2021, which means a user would not be able to set
mtime on files before that. Fix the mtime setting in DFS to use timespec
(which changes the layout to add the nano sec granularity) instead of the
HLC to support older dates.
=> DAOS-11433 dfs: fix mtime set to not rely on DAOS HLC (#10048)

src/object/cli_obj.c
Do not need degraded fetch for specific shard fetch.
=> DAOS-11446 object: do not need degraded fetch for specific shard fetch

src/control/common/proc_utils.go, src/control/common/proc_utils_test.go, src/control/server/server.go
Extracted from the cat_recovery feature branch and
cleaned up for inclusion in master. Allows a process
to check for other processes with the same name in
order to prevent starting more than one.
=> DAOS-9582 control: Add common.CheckDupeProcess()

src/tests/ftest/util/daos_utils_base.py
In the switch to supporting positional parameters, the
subcommand parent class wasn't updated, and therefore
the parameters were not being supplied correctly.
Features: daos_object_query
=> DAOS-11431 test: Fix daos object subcommand

src/client/dfs/dfs.c, src/tests/suite/dfs_unit_test.c
=> DAOS-11204 dfs: fix dfs_osetattr to properly set mtime after set_size

.github/workflows/landing-builds.yml
So far, we have only been building on ARM64. This patch
runs node-local test (NLT) on the ARM64 self-hosted runners
kindly provided by the community.
=> DAOS-10431 test: run NLT on ARM64 runners

src/tests/ftest/scripts/main.sh
Fix the search path for cmocka files when test-results directory path
includes a Test-repeat number.
Test-tag: daos_core_test dfs_test
Test-repeat-hw-large: 10
=> DAOS-11432 test: Fix cmocka post processing with Test-repeat (#10041)

src/tests/ftest/cart/no_pmix_corpc_errors.c, src/tests/ftest/cart/no_pmix_group_test.c, src/tests/ftest/cart/no_pmix_group_version.c
Fix misspellings in test code, as describe in DAOS-11160.
./src/tests/ftest/cart/no_pmix_corpc_errors.c:  DBG_PRINT("Senidng shutdown to all nodes\n");
./src/tests/ftest/cart/no_pmix_group_test.c:    DBG_PRINT("Senidng shutdown to all nodes\n");
./src/tests/ftest/cart/no_pmix_group_version.c: DBG_PRINT("Senidng shutdown to all nodes\n");
request to merge with release/2.2.
Signed-off-by: Kurniawan Alfizah <kurniawan.alfizah@intel.com>
=> DAOS-11160 test: Fixing Misspelling of 'Sending' (#9993)

.clang-format, .flake8, site_scons/site_tools/extra/extra.py, src/cart/SConscript, src/cart/macro_prefix.h_in, src/tests/ftest/cart/util/cart_logtest.py, utils/githooks/pre-commit.d/40-clang-format, utils/sl/fake_scons/SCons/Script/__init__.py
A couple of things were causing the preprocessing step in cart
to generate _structures_from_macros.h to be slow
1. The Preprocessor builder currently doesn't support building
multiple items in parallel so it's better to call it one file
at a time.
2. Use Command builders for intermediate steps so they don't need
to be repeated
3. Pick to allow W503
Also cherry-picks this patch because it also modified extra.py so it made the other cherry-pick simpler:
DAOS-623 build: Update clang-format settings. (#9007)
Change Alignment to be closer to our established code.
Change spaces to tabs to avoid a clang bug.
Enable clang-format githook if clang-format 14.0.5 or greater is detected
=> DAOS-623 build: Improve the preprocessing steps (#9390)

src/client/api/init.c, src/common/misc.c, src/gurt/hash.c, src/include/daos/common.h, src/include/gurt/atomic.h, src/include/gurt/hash.h, src/tests/suite/daos_obj.c
1. switch one global lock to per bucket lock.
to reduce lock contention for multiple threads.
2.  add following adjustment to make apply read/write lock possible:
2.1 use atomic counter to implement rl_op_addref()/rl_op_decref()
because getref/putref switch to read lock.
2.2: remove LRU feats so we don't need hold write lock for read.
3. Refine d_hhash_link_insert() - for PTR type handle hash table, need not take
any extra lock for non-PTR type, refine d_hash_rec_insert_anonym()
add feat bit D_HASH_FT_NO_KEYINIT_LOCK set that for d_hhash
to avoid take all buckets' lock Addd a simple test fo obj_open perf,
by testing on boro obj_open per second increased from 427.36 OPs/S to 313038.03 OPs/S.
(./daos_test -i -u 46, only one engine and client is enough) (From Xuezhao)
Single client fio 4k …
=> DAOS-11146 client: reduce lock contention on hash lock (#8704)

Jenkinsfile, src/chk/chk_engine.c, src/container/srv_container.c, src/container/srv_layout.c, src/include/daos_prop.h, src/include/daos_srv/container.h, src/include/daos_srv/pool.h, src/pool/srv_pool.c, src/pool/srv_pool_check.c
Destroy the orphan containers that have storage allocated on
the engine but do not exist in container service by default.
=> DAOS-9601 chk: container cleanup

src/tests/ftest/util/command_utils_base.py, src/tests/ftest/util/daos_utils_base.py, src/tests/ftest/util/ddb_utils.py
The master and feature/cat_recovery branches had differing
approaches to adding support for positional parameters to
test commands.
=> DAOS-11266 test: Fix ftest divergence from master

debian/changelog, debian/daos-client-tests.install, src/tests/ftest/daos_test/dfuse.py, src/tests/ftest/daos_test/dfuse.yaml, src/tests/ftest/launch.py, src/tests/suite/SConscript, src/tests/suite/dfuse_test.c, utils/rpms/daos.spec
Combined cherry-pick
DAOS-10488 test: Add dfuse unit test code and call it from ftest. (#7286)
DAOS-10029 test: Use python3 for list_tests. (#8911) 
Now the builders have python3 installed use it for list tests.
This means that launch.py and the tests themselves can use
python3 features and the codebase should not depend on python2
any longer.
Fix some linting errors in launch.py
=> DAOS-10488 test: Add dfuse unit test code and call it from ftest. (#7286)

src/tests/ftest/nvme/io_verification.py
Test-tag: nvme_io_verification nvme_server_restart
Test-repeat: 3
Summary:
- Updated the test case to use the container label based on developer's recommendation.
=> DAOS-10919 test: Fix io_verification tests (use container label)

src/container/srv_target.c, src/dtx/dtx_common.c, src/dtx/dtx_resync.c, src/dtx/dtx_rpc.c, src/include/daos_srv/dtx_srv.h, src/include/daos_srv/vos.h, src/object/srv_obj.c, src/vos/tests/vts_dtx.c, src/vos/vos_dtx.c, src/vos/vos_dtx_iter.c, src/vos/vos_internal.h
It includes the following fixes:
1. Pin DTX entry in DRAM when DTX start
Originally, we pin the DTX entry in DRAM conditionally before ULT
yield. But it is relative complex to forecast whether the ULT may
yield or not. This patch much simplifies related logic and avoids
missing some corner cases.
2. Validate DTX entry before being committable or committed
If the DTX entry is returned via DTX iteration. The upper layer caller,
for DTX resync or DTX cleanup, may abort it sometime later. Before being
aborted, it may re-attach to some DTX handle for handling resent request.
Then there is race between them. So before being committable or committed
by RPC handler, needs to check whether it has been aborted or not.
3. Unify DTX resync for pool map refresh and container open
That will simplify …
=> DAOS-11035 dtx: continue to fix DXT related issues

src/tests/ftest/util/command_utils.py
Test-tag: pr,hw,large ec_io_conf_run unaligned_io iorebuild
Convert passed env to EnvironmentVariables in case it's a dict.
=> DAOS-11443 test: fix set_environment()

src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_dir.yaml, src/tests/ftest/datamover/obj_large_posix.py, src/tests/ftest/datamover/obj_large_posix.yaml, src/tests/ftest/datamover/serial_large_posix.py, src/tests/ftest/datamover/serial_large_posix.yaml
Test-tag: dm_large_dir dm_obj_large_posix dm_serial_large_posix
- when using mdtest to create and read-verify in separate phases, -G is
needed to make sure the buffers are the same
- when using -E to read, use -X to verify
- misc cleanup
=> DAOS-10376 test: datamover: use -E -X -G 27

src/object/obj_ec.h, src/object/obj_internal.h, src/object/srv_ec.c, src/object/srv_mod.c, src/object/srv_obj.c
add EC full-stripe and partial update metrics on dtx leader node.
path - pool -> EC_update -> full_stripe/partial.
=> DAOS-11241 object: add EC full-stripe and partial update metrics

src/engine/init.c
This reverts commit c6c7d0c3c27cf06ab870ed098644617cd2c917f0.
=> Revert DAOS-9881 engine: disable transparent hugepages (#9544)

src/include/daos_srv/vos.h, src/vos/tests/vts_pm.c, src/vos/vos_query.c
This is a bit overloaded but simple enough. There are cases where we
want to query the max_write of an object but don't want to query the
key(s).   Allow a call to the existing API to just query the max_write.
=> DAOS-11422 vos: Extend vos_obj_query_key to allow only max_write query

src/client/dfuse/dfuse_fuseops.c, src/tests/ftest/daos_test/dfuse.py, src/tests/suite/dfuse_test.c
Test-tag: pr dfuse,daily_regression dfuse_unit
- Change dfuse time granularity to 1 (nanosecond)
- overhaul dfuse_test.c
- Add dfuse unit mtime unit tests
- Adjust dfuse_test to run with or without metadata tests
- Add metadata tests to ftest/daos_test/dfuse.py
=> DAOS-11171 test: add dfuse mtime unit tests (#9778)

src/tests/ftest/util/command_utils.py
Test-tag: pr,hw,large ec_io_conf_run unaligned_io iorebuild
Convert passed env to EnvironmentVariables in case it's a dict.
=> DAOS-11443 test: fix set_environment() (#10060)

src/tests/ftest/cart/util/cart_utils.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.yaml, src/tests/ftest/soak/utils.py, src/tests/ftest/util/job_manager_utils.py
Test-tag: performance_ior_easy_dfs_sx performance_ior_hard_dfs_sx performance_mdtest_easy_dfs_s1 performance_mdtest_hard_dfs_s1 corpc,five_node iorebuild test_dm_posix_types_dcp dbench soak_smoke
- Fix Mpirun and Srun namespace
- Add --bind-to {} to Mpirun and Orterun
- Update instantiations to call get_params()
- Adjust performance tests to use --bind-to socket
=> DAOS-11442 test: add option for --bind-to

src/tests/ftest/nvme/health.py, src/tests/ftest/nvme/health.yaml
Test-tag: test_monitor_for_large_pools
- Verify there is enough space available before creating each pool
- Use self.get_dmg_command
- Misc cleanup
=> DAOS-11156 test: improve nvme/health.py

src/client/dfs/dfs.c, src/tests/suite/dfs_par_test.c
dfs_open with O_CREAT for directories always assume O_EXCL. While posix
does not provide a way to support that, we can easily support that in DFS
to have many processes/threads succeed when creating the same directory
with O_CREAT with only 1 creator and the rest just opening.
=> DAOS-11465 dfs: fix dfs_open for directories without O_EXCL

src/tests/jobtest.c
Before this change the jobtest invocation of dc_cont_hdl2uuid() did
not check for a failure, leading to Coverity CID 22078. With this
change, the return code is checked and the test output is adjusted.
Performing build only in CI (skipping testing) since jobtest is only
invoked manually at this time. It was tested manually with this change.
=> DAOS-11476 test: Fix coverity unchecked return in jobtest

src/tests/suite/daos_rebuild_common.c
check the return value of daos_obj_layout_get().
=> DAOS-11494 tests: check return value

src/rebuild/srv.c
=> DAOS-11493 rebuild: check tgts before print

src/object/srv_obj_migrate.c
check return value for dsc_cont_close.
Put container child in all cases.
=> DAOS-11492 object: check return value for dsc_cont_close

src/pool/srv_iv.c
Proactive cherry-pick of same change in progress for master branch.
The pool_iv_prop_l2g() function returns void, but for property
entry DAOS_PROP_PO_SVC_LIST, it calls d_rank_list_copy(). The calling
conditions are such that d_rank_list_copy() argument checking will
not return -DER_INVAL, and the execution will only perform memcpy
and return 0.
With this change get the return value and assert it is zero (success).
Features: pool
=> DAOS-11478 pool: Coverity CID 105939: check rank list copy

src/pool/srv_pool.c, src/rebuild/rebuild_internal.h, src/rebuild/rpc.h, src/rebuild/scan.c, src/rebuild/srv.c, src/tests/ftest/util/command_utils.py
Instead of using stable epoch as the reclaim epoch, let's
use the epoch when the pool map is being changed, so if
the rebuild job fail, reclaim will not discard the in-flight
data.
Test-tag: pr rebuild
Conflicts:
src/rebuild/srv.c
=> DAOS-11417 rebuild: do not use stable epoch for reclaim

src/tests/ftest/container/auto_oc_selection.py, src/tests/ftest/control/dmg_telemetry_basic.py, src/tests/ftest/io/parallel_io.py, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/data_mover_test_base.py, src/tests/ftest/util/ior_test_base.py
Test-tag: pr daily_regression oc_selection test_with_telemetry_basic parallelio multipoolparallelio datamover,pr datamover,daily_regression ior,pr ior,daily_regression
- Add generic kwargs to `get_container` that accepts any param.
- Update some tests to pass params this way
=> DAOS-9827 test: unified container create (#8082)

src/tests/ftest/erasurecode/rebuild_disabled.py, src/tests/ftest/erasurecode/rebuild_disabled.yaml, src/tests/ftest/erasurecode/rebuild_fio.py, src/tests/ftest/erasurecode/rebuild_fio.yaml, src/tests/ftest/util/ec_utils.py, src/tests/ftest/util/test_utils_pool.py, src/vos/evtree.c
1. For array remove, the RT_OVERLAP_INCLUDED range @same_epoch should be
safe to ignore to avoid failure in that case.
2. a few refine for test script
Test-tag: pr ec_online_rebuild_fio
Conflicts:
src/tests/ftest/erasurecode/rebuild_fio.py
=> DAOS-9815 object: some refine related with EC obj aggregation (#9903)

src/vos/vos_aggregate.c
Since we can't reproduce DAOS-11232 anymore, let's add a bit
of low overhead debug in case it does happen again.
=> DAOS-11232 vos: Add some instrumentation to aggregation (#10113)

src/include/daos_srv/vos.h, src/include/daos_srv/vos_types.h, src/object/srv_obj_migrate.c, src/pool/srv_target.c, src/rdb/raft_tests/raft_tests.py, src/tests/vos_engine.c, src/vos/tests/vts_common.c, src/vos/vos_layout.h, src/vos/vos_pool.c, utils/run_test.sh
Rather than setting feats, we should update the format version
so that we don't need to continually set features on every pool
open operation.
Also addresses CID105928
=> DAOS-11505 vos: Update durable format version on pool upgrade (#10174)

src/object/srv_obj.c
Addresses CID: 21837
echo_rw can only support one iod and one sgl
=> DAOS-11491 object: echo_rw only supports one iod

src/object/srv_ec_aggregate.c
=> DAOS-11490 erasure code: Fix Coverity issue with integer overflow.

src/pool/srv_pool.c
Proactive cherry-pick of same change in progress for master branch.
In pool_upgrade_props() and ds_pool_mark_upgrade_completed() it is
possible that the pool_prop_read() call allocates memory for the
daos_prop_t * output argument (even when rc != 0 is returned).
Before this change, prop was not freed, and with this change
it is freed even when pool_prop_read() fails.
Features: pool
=> DAOS-11477 pool: Coverity CIDs 105913/105918 always free prop

src/common/fail_loc.c
A 16 bit field is being shifted by more then 16 bits causing an
overflow.  Cast it first.
Coverity issues #105945, 105930
=> DAOS-11522 common: Address overflow in bit shift operation

src/chk/chk_engine.c, src/chk/chk_upcall.c, src/container/srv_container.c, src/include/daos/common.h, src/include/daos_srv/container.h
If the container label in the container service (cont_svc::cs_uuids)
exists but does not match the label in the container property, then
trust the container service and reset the one in container property.
Otherwise, if the container label in the container service does not
exists, but the one in the container property is there, then trust
the label in the container property and add it to container service.
=> DAOS-9602 chk: verify container label

src/object/srv_obj.c
Addresses CID: 21837
echo_rw can only support one iod and one sgl
=> DAOS-11491 object: echo_rw only supports one iod (#10190)

Jenkinsfile
Increasing the Unit Test with memcheck stage timeout from 45 to 60
minutes.
=> DAOS-11532 test: Increase unit test timeout

src/tests/ftest/datamover/copy_procs.py, src/tests/ftest/datamover/dst_create.py, src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_file.py, src/tests/ftest/datamover/negative.py, src/tests/ftest/datamover/negative_space.py, src/tests/ftest/datamover/obj_large_posix.py, src/tests/ftest/datamover/obj_small.py, src/tests/ftest/datamover/posix_meta_entry.py, src/tests/ftest/datamover/posix_preserve_props.py, src/tests/ftest/datamover/posix_subsets.py, src/tests/ftest/datamover/posix_symlinks.py, src/tests/ftest/datamover/posix_types.py, src/tests/ftest/datamover/serial_large_posix.py, src/tests/ftest/datamover/serial_small.py, src/tests/ftest/deployment/basic_checkout.py, src/tests/ftest/deployment/io_sys_admin.py, src/tests/ftest/util/data_mover_test_base.py
Test-tag: datamover
- Replace DataMoverTestBase.create_cont with
TestWithServers.get_container
- Remove DataMoverTestBase.gen_uuid
=> DAOS-9827 test: datamover: use get_container (#9768)

Jenkinsfile
Increasing the Unit Test with memcheck stage timeout from 45 to 60
minutes.
=> DAOS-11532 test: Increase unit test timeout (#10211)

src/include/daos/object.h
Set EC cell alignment to be 32 bytes, instead of 4096 bytes, so to avoid the data to be splitted by setting proper EC cell size like IOR hard.
=> DAOS-11423 object: Set EC cell alignment to 32 bytes

src/object/cli_obj.c
Need not complete parent task again if aborted all its dep-tasks.
=> DAOS-11241 object: fix a task err handling bug

src/client/dfs/dfs.c, src/tests/suite/dfs_par_test.c
dfs_open with O_CREAT for directories always assume O_EXCL. While posix
does not provide a way to support that, we can easily support that in DFS
to have many processes/threads succeed when creating a the same directory
with O_CREAT only with only 1 creator and the rest just opening.
=> DAOS-11465 dfs: fix dfs_open for directories without O_EXCL (#10107)

src/tests/suite/daos_test_common.c
Prior to this patch line pointer was freed upon each loop where
it could be re-used by getline(), so this was a potential
use-after-free situation, but also a double-free one !!
Since getline() can use an already allocated buffer and also
manage to re-allocate it if needed, only free line pointer
upon exit/return cases.
=> DAOS-11540 tests: only free line upon exit in verify_state_in_log()

src/vos/vos_aggregate.c
The assertion in question is incorrect.  A set of valid inputs can be chosen to make it fail.  I'm in process of creating a regression test and checking in my utility that I wrote while debugging this but it's taking too long so let's fix the issue only first.
The valid sequence that fails looks like this
write 3 bytes at index 0 at time 1
write 4 bytes at index 2 at time 2
remove 3 bytes at index 2 at time 2
write 4 bytes at index 5 at time 3
remove 3 bytes at index 5 at time 3
The issue is by the time we know we need to flush the merge window, the physical record that causes the assertion (4 bytes at 5) is already enqueued.  Here is the sequence we see at aggregation time
3 visible records at 0 at time 1
removal record at time 2 (3 bytes at 2)
3 covered records at 2 at time 2
removal …
=> DAOS-11232 vos: Remove unecessary and incorrect assertion

src/vos/vos_aggregate.c
The assertion in question is incorrect.  A set of valid inputs can be chosen to make it fail.  I'm in process of creating a regression test and checking in my utility that I wrote while debugging this but it's taking too long so let's fix the issue only first.
The valid sequence that fails looks like this
write 3 bytes at index 0 at time 1
write 4 bytes at index 2 at time 2
remove 3 bytes at index 2 at time 2
write 4 bytes at index 5 at time 3
remove 3 bytes at index 5 at time 3
The issue is by the time we know we need to flush the merge window, the physical record that causes the assertion (4 bytes at 5) is already enqueued. Here is the sequence we see at aggregation time
3 visible records at 0 at time 1
removal record at time 2 (3 bytes at 2)
3 covered records at 2 at time 2
removal …
=> DAOS-11232 vos: Remove unecessary and incorrect assertion (#10236)

src/pool/srv_pool.c
Previously to this patch, pool_prop_read() could return an error
with daos_prop_t still allocated. This was requiring callers to
handle such scenario and free it, and some of them, like
pool_upgrade_props()/ds_pool_mark_upgrade_completed() were
missing to do so.
This has been detected using Coverity tool, as both CIDs
105913/105918.
=> DAOS-11477 pool: pool_prop_read() to free daos_prop_t upon error

src/engine/ult.c
IO request should choose helper xstream randomly from all helpers.
=> DAOS-11423 engine: choose helper randomly

src/tests/ftest/nvme/health.py
Test-tag: test_monitor_for_large_pools pr,hw,medium Skip-unit-tests: true
- Verify there is enough space available before creating each pool
- Use self.get_dmg_command
- Misc cleanup
=> DAOS-11156 test: improve nvme/health.py (#9966)

src/tests/ftest/launch.py
Test-tag: pr,-hw harness_basic_test,-hw
Support multiple extra yaml files to launch.py
=> DAOS-11457 test: support multiple launch.py -e (#10081)

src/tests/ftest/cart/util/cart_utils.py, src/tests/ftest/performance/ior_easy.yaml, src/tests/ftest/performance/ior_hard.yaml, src/tests/ftest/performance/mdtest_easy.yaml, src/tests/ftest/performance/mdtest_hard.yaml, src/tests/ftest/soak/utils.py, src/tests/ftest/util/job_manager_utils.py
Test-tag: performance_ior_easy_dfs_sx performance_ior_hard_dfs_sx performance_mdtest_easy_dfs_s1 performance_mdtest_hard_dfs_s1 corpc,five_node soak_smoke pr,-hw pr,hw,large
- Fix Mpirun and Srun namespace
- Add --bind-to {} to Mpirun and Orterun
- Update instantiations to call get_params()
- Adjust performance tests to use --bind-to socket
=> DAOS-11442 test: add option for --bind-to (#10061)

src/container/container_iv.c, src/container/srv_container.c, src/container/srv_internal.h
During leader switch, the IV container hdl cache
might not be migrated to the new leader, so let's
check the container hdl in RDB if it does not exist in IV cache.
=> DAOS-10423 container: check container hdl in rdb

src/control/cmd/daos/README.md, src/control/server/README.md
File name was changed from control.proto --> ctl.proto, so
fixing the README file.
Doc-only: true
=> DAOS-11523 Doc: Fix the broken link in README.

src/object/cli_shard.c
Once EC parity rotation is enabled, each dkey will have its parity shard
calculated by dkey hash, so during key_query, it should use the dkey
in reply to calculate dkey_hash (parity), instead of the dkey in cb_args
which is always 0 for key_query.
=> DAOS-11423 object: cacluate the dkey hash by reply

src/control/build/interop.go, src/control/build/interop_test.go, src/control/build/version.go, src/control/cmd/daos_agent/attachinfo.go, src/control/cmd/daos_agent/mgmt_rpc.go, src/control/cmd/daos_agent/mgmt_rpc_test.go, src/control/cmd/daos_agent/procmon.go, src/control/lib/control/request.go, src/control/lib/control/rpc.go, src/control/server/interceptors.go, src/control/server/interceptors_test.go
A 2.2 agent must be able to communicate with a 2.0 server,
and a 2.0 agent must be able to communicate with a 2.2
server. Also adds a compatibility rule for future releases
to allow server/agent interopability within 2 minor versions.
=> DAOS-11552 control: Support 2.0/2.2 agent interop

src/include/daos/object.h, src/object/obj_rpc.c, src/object/obj_rpc.h, src/object/srv_obj_remote.c
There are some RPC protocol interoperability issues related with the changes of "struct daos_shard_tgt" between 2.0 and 2.2. This patch defines multiple RPC layouts and allows the new client and server to use the proper RPC protocol (based on peer version) to send and receive related RPC request. The affected RPC includes:
DAOS_OBJ_RPC_UPDATE
DAOS_OBJ_RPC_PUNCH
DAOS_OBJ_RPC_PUNCH_DKEYS
DAOS_OBJ_RPC_PUNCH_AKEYS
DAOS_OBJ_RPC_CPD
=> DAOS-11544 object: RPC interoperability between 2.0 and 2.2

src/control/server/config/server.go, src/control/server/server_utils.go, src/control/server/storage/bdev/backend.go
Print output of numastat -m to the daos_admin log after hugepages have been cleaned up which happens just before engine start. This provides per-NUMA details of memory allocations and usage which can be used to troubleshoot insufficient hugepage memory failures on engine start-up.
=> DAOS-11393 control: Log numa stats after hugepage cleanup (#10122)

debian/changelog, debian/daos-client-tests.install, src/tests/suite/SConscript, src/tests/suite/daos_epoch_io.c, utils/rpms/daos.spec
Also fix up daos_test -x to find them.
=> DAOS-11533 tests: Move io_conf files out of /usr/bin

src/control/lib/hardware/pci.go, src/control/lib/hardware/pci_test.go
The parsing code imposed an arbitrary constraint on the
length of the VMD address. Instead, just left-pad with
zeroes as necessary to ensure it can be parsed into a
PCI address.
=> DAOS-11473 control: Fix VMD domain parsing (#10145)

src/control/build/interop.go, src/control/build/interop_test.go, src/control/build/version.go, src/control/server/interceptors.go, src/control/server/interceptors_test.go
Allow servers and agents to communicate if they are within two
minor versions of each other (e.g. 2.2/2.4).
=> DAOS-11522 control: Allow server/agent interop across minor versions

src/chk/chk_engine.c, src/chk/chk_internal.h, src/chk/chk_leader.c, src/chk/chk_vos.c, src/include/daos/common.h, src/include/daos_prop.h, src/include/daos_types.h, src/mgmt/srv_chk.c, src/mgmt/srv_drpc.c, src/mgmt/srv_internal.h, src/mgmt/srv_pool.c, src/mgmt/tests/mocks.c
Including the followings:
1. If the admin does not want to interact with DAOS check during the
process, he/she can specify "CF_AUTO" flag when start DAOS check.
then all interaction actions will be automatically handled as 'IGNORE'.
2. Unify the message buffer size for reporting inconsistency and ask
for interaction with admin.
3. Standardize the usage for uuid_t and uuid string in DAOS check logic.
4. More comment for how to handle dead rank during DAOS check.
=> DAOS-11538 chk: some enhancement and cleanup

src/control/system/raft/database.go, src/control/system/raft/database_test.go, src/control/system/raft/mocks.go, src/control/system/raft/raft.go
In some cases, a raft operation will fail due to a leadership loss
or other transition, and in these cases it is not safe to call
ResignLeadership(). Instead, just make these calls noops as
leadership is already lost.
=> DAOS-11511 control: Make ResignLeadership() a noop on some errors

src/rebuild/rebuild_iv.c, src/rebuild/scan.c
Ignore the EXIST error for scan object insertion for now,
since it is harmless for rebuild process.
Once there are errors, let's abort the rebuild immediately
and retry.
Test-tags: pr rebuild
=> DAOS-11447 rebuild: ignore exist ERROR for object insert

src/include/daos_fs_sys.h, src/tests/suite/dfs_sys_unit_test.c
atime in DFS is not longer maintaines as of 2.2 and thus the dfs sys tests need to be adjusted.
Test-tag: test_daos_dfs_sys
=> DAOS-11565 dfs: fix dfs sys tests to ignore atime setting

src/include/daos_srv/vos_types.h, src/pool/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
Version 24 must work as aggregation optimization for backward compatibility so create a new version for the checker
=> DAOS-11448 vos: Modify pool version handling

src/client/dfs/dfs.c, src/tests/suite/dfs_unit_test.c
DFS inode stores ctime, but it’s not properly updated when doing any
metadata updates. This adds proper ctime support when object metadata
is updated.
=> DAOS-11470 dfs: add proper ctime support

src/cart/crt_swim.c
Since the csm_target is unsigned, asserting that it must be >= 0 is unnecessary.
=> DAOS-11595 cart: Fix Coverity CID 449436

src/cart/crt_hg.c
The current setting was preventing extra RPC handles from being posted once the original batch is exhausted.
=> DAOS-11395 CART: remove RPC post increment restriction

src/tests/suite/daos_test_common.c
Coverity has raised CID 449529 because it has found that testing if line is not NULL is useless here since this part of code can not be reached with line == NULL.
This regression has been introduced with PR-10245 to fix previous Coverity CID 449429.
=> DAOS-11570 tests: do not check if line is NULL

src/include/daos/dpar.h, src/utils/wrap/mpi/dpar_mpi.c, src/utils/wrap/mpi/dpar_stub.c
It's only incompatible if the user is trying to use a library that doesn't have an API they need, not the other way around.
Addresses CID: 105934
=> DAOS-11596 utils: Fix version check in libdpar.so

src/rdb/rdb_rpc.c
Custom RPC timeouts have been in use by swim and other modules for a while. Re-enable them for RDB RPCs to avoid accumulating RPCs locally when peers are unavailable.
=> DAOS-10138 rdb: Re-enable RPC timeouts

src/tests/ftest/rebuild/cascading_failures.yaml
Test-tag: test_simultaneous_failures test_sequential_failures test_cascading_failures
Test-repeat: 3
Increase timeout from 360s to 420s
=> DAOS-11609 test: increase rebuild/cascading_failures timeout

src/rebuild/srv.c
Skip the reclaim job in the rebuild queue, otherwise it might mess up the rebuild job order in the queue.
=> DAOS-10524 rebuild: skip reclaim job during merge

src/include/daos_srv/pool.h, src/mgmt/srv_internal.h, src/mgmt/srv_pool.c, src/mgmt/srv_system.c, src/mgmt/srv_target.c, src/mgmt/srv_util.c, src/pool/README.md, src/pool/srv_pool.c
For each pool, the PS ranks stored on the MS may not cover all PS replicas, in and out of the latest PS membership. The PS may have not been able to send the latest PS ranks to the MS. Or, it may have been unable to destroy some PS replicas after removing them from the membership. The ds_mgmt_destroy_pool function currently only destroys the PS replicas in the latest membership known to the MS, leaking any other PS replicas.
This patch removes the step that only destroys the known PS replicas, combines it with the target destroy CoRPC, and attempts to stop any PS replicas on all PS engines. Note that the RDB files shall be deleted along with other pool files. And, ds_pool_svc_create is renamed to ds_pool_svc_dist_create to avoid confusion.
We then have a few interesting directions to …
=> DAOS-11498 mgmt: Fix PS replica leaks (#10162)

src/tests/ftest/erasurecode/rank_failure.yaml
Test-tag: ec_io_conf_run
Test-repeat: 3
Summary: Increase the timeout for ec_io_conf_run from 1500 to 2100 seconds.
=> DAOS-11159 test: Increase timeout to 35 minutes.

src/tests/ftest/rebuild/widely_striped.py, src/tests/ftest/rebuild/widely_striped.yaml
- Set cont_rf so mdtest completes successfully
- Run mdtest as a subprocess instead of thread
- Make sure mdtest is actually successful
- Misc cleanup
rf should be set on a POSIX container for root/SB objects.
Test-tag: rebuild_widely_striped
=> DAOS-10454 test: improve rebuild_widely_striped (#8863)

utils/run_test.sh
Put new command line tests with rest of vos tests
=> DAOS-623 vos: Fix test categorization

src/control/lib/hardware/hwprov/defaults.go, src/control/lib/hardware/libfabric/bindings.go, src/control/lib/hardware/ucx/bindings.go
The use case where libfabric is present but UCX libs aren't installed is normal.
- Log missing dynamically loaded libs at debug level only.
- Improve error messages so it's easier to tell which library failed to load.
=> DAOS-11554 control: Don't log missing lib as error

src/tests/ftest/rebuild/cascading_failures.yaml
Increase timeout from 360s to 420s
Test-tag: test_simultaneous_failures test_sequential_failures test_cascading_failures Test-repeat: 3
=> DAOS-11609 test: increase rebuild/cascading_failures timeout (#10307)

src/tests/ftest/container/boundary.py, src/tests/ftest/container/boundary.yaml
Test-tag: container_boundary
Test-repeat: 3
Test Description:
Testcase 1: Test 1 pool with containers boundary condition in parallel. Testcase 2: Test large number of pools and containers in parallel. Testcase 3: Test pools and containers with io.
DAOS-10605 test: improve container/boundary.py (#9027)
- Create pools in parallel
- Create container in parallel with a single ThreadManager
- Reduces max number of inflight Threads
- Decrease timeout
- Get params from yaml once in setup instead of per thread
- Misc cleanup
=> DAOS-8464 test: Test lots of pool connections (#8605)

utils/build.config
=> DAOS-11467 build: Update DAOS to use UCX 1.13

src/object/obj_tx.c
The non-transactional task's result is "-DER_NEED_TX" when being
converted to distributed TX. Reset it as zero under such case to
avoid misguiding subsequent ASSERT check and tse complete logic.
=> DAOS-11446 object: check DER_NEED_TX when convert to  distributed TX

src/tests/ftest/osa/offline_extend.py
Re-enabling the offline extend oclass test because DAOS-7493 is not reproducible.
=> DAOS-7612 test: Re-enable the offline extend oclass test

src/tests/ftest/datamover/large_dir.py, src/tests/ftest/datamover/large_dir.yaml, src/tests/ftest/datamover/obj_large_posix.py, src/tests/ftest/datamover/obj_large_posix.yaml, src/tests/ftest/datamover/serial_large_posix.py, src/tests/ftest/datamover/serial_large_posix.yaml
Test-tag: dm_large_dir dm_obj_large_posix dm_serial_large_posix
- when using mdtest to create and read-verify in separate phases, -G is
needed to make sure the buffers are the same
- when using -E to read, use -X to verify
- misc cleanup
=> DAOS-10376 test: datamover: use -E -X -G 27 (#8737)

src/control/build/interop.go, src/control/build/interop_test.go, src/control/build/version.go, src/control/build/version_test.go
Fixes an oversight in the comparison logic that could lead
to a larger version being seen as less than. Also adds
support for finer-grained rule matching logic.
=> DAOS-11552 control: Interop rule processing fixes

src/chk/chk_common.c, src/chk/chk_leader.c
Some check engines may complete the check very soon because of no pools exist on them. But there may be dangling pools exist on MS. So the check leader still needs to handle the potential dangling pool even if all check engines have completed the check.
=> DAOS-10821 chk: handle dangling pool even if all check engine done

src/control/lib/hardware/sysfs/provider.go, src/control/lib/hardware/sysfs/provider_test.go
Infiniband pkey devices link to their parent device differently than other virtual net devices do. This patch updates both the IB status detection and topology detection to associate the pkey device to its Infiniband interface.
=> DAOS-11514 control: Detect IB pkey parent devices

src/object/cli_obj.c, src/rebuild/srv.c, src/tests/ftest/daos_test/rebuild.yaml, src/tests/ftest/daos_test/suite.yaml, src/tests/suite/daos_base_tx.c, src/tests/suite/daos_dist_tx.c, src/tests/suite/daos_drain_simple.c, src/tests/suite/daos_extend_simple.c, src/tests/suite/daos_obj.c, src/tests/suite/daos_rebuild.c, src/tests/suite/daos_rebuild_common.c, src/tests/suite/daos_rebuild_ec.c, src/tests/suite/daos_rebuild_simple.c, src/tests/suite/daos_test.h, src/tests/suite/daos_test_common.c
Enable online reintegration.
Add inflight I/O for rebuild, EC rebuild and drain test.
minor fixes in extend test.
=>  DAOS-10525 objects: enable online reintegration

src/include/daos_prop.h, src/pool/cli.c, src/pool/srv_layout.c, src/pool/srv_pool.c
Without this change, libdaos2.2, "daos cont create" (type POSIX) interacting with a 2.0 engine results in an underlying pool query (property DAOS_PROP_PO_REDUN_FAC). The 2.0 engine is unaware of this property and does not return it. The libdaos client code when copying RPC reply properties fails with -DER_PROTO due to the missing entry.
With this change, the libdaos 2.2 client code inspects the dc_pool_proto_version gotten from an earlier cart protocol query, and in this interop scenario uses a default RF value (0) rather than query the 2.0 engine/pool.
=> DAOS-11642 container: 2.2 client -> 2.0 engine: use pool RF 0

docs/overview/data_integrity.md
"vos_test" should be "vos_tests".
Doc-only: true
=> DAOS-11622 docs: fixed typo of "vos_test"

src/tests/ftest/util/cmocka_utils.py
When collecting the cmocka xml files from the remote hosts the cmocka_utils code was unintentionally issuing a doulbe clush command. This resulted in the daos_test/dfuse.py timing out when run on Leap 15.
Test-tag: test_daos_dfuse_unit
=> DAOS-11623 test: Fix cmocka_utils Leap 15 timeout

src/tests/ftest/aggregation/multiple_pool_cont.yaml
Test-tag: aggregate_multiple_pools
Test-repeat: 2
Summary: Use percentage for scm_size and nvme_size.
=> DAOS-11564 test: Update scm_size,nvme_size.

src/tests/ftest/daos_test/dfuse.py, src/tests/ftest/scripts/post_process_xml.sh, src/tests/ftest/util/cmocka_utils.py, src/tests/ftest/util/command_utils.py, src/tests/ftest/util/daos_core_base.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/job_manager_utils.py, src/tests/ftest/util/results_utils.py
Adding detecting 'Process received signal' error message in daos_test command output to avoid missing the detection of these errors.
Test-tag: daos_test dfs_test dfuse_test test_always_passes Allow-unstable-test: true
=> DAOS-11453 test: Detect silent daos_test failures (#10084)

src/chk/chk_leader.c, src/control/server/mgmt_check.go, src/mgmt/srv_drpc.c
If DAOS check is resumed from former checkpoint, then the control plane shoud not reset the check DB, otherwise the former reported events will be lost.
=> DAOS-9585 chk: reset check DB only when (re-)start from beginning

src/tests/ftest/pool/list_verbose.py
The SCM size of a pool created could eventually be greater than the one provided to dmg.  Thus, the size given to the dmg is not reliable and should not be used for consistancy checks.
Test-tag: list_verbose_basic
Test-repeat: 20
=> DAOS-10339 test: Fix inconsitant size test

src/tests/ftest/aggregation/multiple_pool_cont.yaml
Test-tag: aggregate_multiple_pools
Test-repeat: 2
Summary: Use percentage for scm_size and nvme_size.
=> DAOS-11564 test: Update scm_size,nvme_size. (#10357)

src/chk/chk_leader.c, src/control/server/mgmt_drpc_checker.go, src/control/system/checker/finding.go, src/control/system/checker/finding_test.go
When the checker takes the default action, 
it should set the action in the report so that 
the admin can learn what happened.
=> DAOS-9585 chk: Set checker action in reports

src/tests/ftest/harness/config.py, src/tests/ftest/harness/config.yaml, src/tests/ftest/util/apricot/apricot/test.py, src/tests/ftest/util/dmg_utils.py, src/tests/ftest/util/dmg_utils_base.py, src/tests/ftest/util/general_utils.py, src/tests/ftest/util/server_utils.py
Test-tag: pr,-hw test_harness_config_access_points
- Support specifying access_points_suffix in test config, which will be appended to each hostname.
- Add ftest/harness/config to test this usage
=> DAOS-11205 test: support access_points_suffix (#9986)

src/object/obj_class.c, src/tests/suite/daos_obj.c
If the container RF > 0 and user specified RP hint for arrays, that hint is currently ignored, and the oclass selected is EC. This PR fixes the issue to respect the user specified hint in this case.
=> DAOS-11667 object: fix auto object class selection for RP hints for arrays

src/tests/ftest/pool/list_verbose.py
The SCM size of a pool created given could eventually be greater than the one provided to dmg.  Thus, the size given to the dmg is not reliable and should not be used for consistancy checks.
=> DAOS-10339 test: Fix inconsitant size test (#10355)

docs/admin/troubleshooting.md
Such error will be observed when there is more than one engine per node sharing the same NIC and fabric_iface_port of engines are too close; e.g., the difference is not larger than 3. libfabric (tcp and sockets providers) uses the port assigned by fabric_iface_port and the three following ports too. We need to make fabric_iface_port of engines on the same NIC distant enough to avoid such errors.
Doc-only: true
=> DAOS-11687 docs: add libfabric error "Address already in use" in troubleshooting.md

src/cart/crt_swim.c, src/cart/swim/swim.c, src/cart/swim/swim_internal.h, src/include/cart/swim.h, src/tests/ftest/cart/test_swim.c, src/tests/ftest/cart/test_swim_emu.c, src/tests/ftest/cart/test_swim_net.c
Currently, swim starts to suspect a member as soon as a direct ping to
this member times out:
19:10:29.77 swim_progress() 24: dping 24 => {62 A 829446131208945664}
delay: 0 ms, timeout: 1900 ms
...
19:10:31.68 swim_member_suspect() alloc(calloc) 'item':48 at
0x7f4e9431fab0.
19:10:31.68 swim_progress() 24: ireq  79 => {62 S 829446131208945664}
delay: 1900 ms
19:10:31.68 swim_progress() 24: ireq  37 => {62 S 829446131208945664}
delay: 1900 ms
In this example, member 24 pinged member 62 directly. When that timed
out after 1.9 s, it immediately set the local state of member 62 to
SUSPECT, and sent indirect pings to member 79 and 37. The "S" on member
24, 79, and 37 might propogate to other members, while member 62 was
clarifying the suspicion by incrementing its incarnation. This behavior
is …
=> DAOS-11274 cart: Fix swim paranoia

ci/provisioning/post_provision_config_nodes.sh
Test images are provisioned based on the desired version of O/S for the
stage.  /etc/yum/vars/releasever is what keeps an O/S at the version
requested by the stage and prevents it from being upgraded beyond the
requested version.  So don't remove that file.
=> DAOS-623 ci: Remove the releasever removal

ci/provisioning/post_provision_config_nodes.sh
Test images are provisioned based on the desired version of O/S for the stage.  /etc/yum/vars/releasever is what keeps an O/S at the version requested by the stage and prevents it from being upgraded beyond the requested version.  So don't remove that file.
=> DAOS-623 ci: Remove the releasever removal (#10413)

src/client/array/dc_array.c, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_internal.h, src/object/obj_task.c
For dc_array_get_size/dc_array_stat, if some failure happened after registering cleanup (to free memory and drop reference) callback, then the cleanup logic may be triggered repeatedly by both task complete callback and current task sponsor.
Other fixes:
Drop tse_task_stack_{push,pop}_data for shard_query_key_task().
Remove redundant logic for obj_retry_cb().
=> DAOS-11231 client: fix memory corruption during query_key

src/include/daos_srv/vos_types.h, src/pool/srv_target.c, src/vos/vos_layout.h, src/vos/vos_pool.c
Partial cherry-pick from feature/cat_recovery because it's needed for other feature branches
Version 24 must work as aggregation optimization for backward compatibility so create a new version for the checker
=> DAOS-11448 vos: Modify pool version handling (#10271)

src/control/fault/code/codes.go, src/control/server/faults.go, src/control/server/mgmt_pool.go, src/control/server/mgmt_pool_test.go
If the pool create request has specified more ranks than are
available in the system, reject it.
=> DAOS-11740 control: Reject invalid number of pool create ranks

src/tests/ftest/harness/advanced.py
Disable the bandit check for random.choice() usage in the harness/advance.py test_launch_failures test.
Test-tag: test_launch_failures
=> DAOS-11766 test: Fix harness/advanced.py bandit check

src/cart/crt_iv.c, src/container/container_iv.c, src/container/oid_iv.c, src/container/srv_container.c, src/container/srv_internal.h, src/include/daos_errno.h, src/include/daos_srv/daos_engine.h, src/object/cli_obj.c, src/object/obj_enum.c, src/object/obj_internal.h, src/object/obj_tx.c, src/object/srv_obj_migrate.c, src/rebuild/rebuild_internal.h, src/rebuild/srv.c, src/tests/ftest/daos_test/rebuild.py, src/tests/ftest/daos_test/rebuild.yaml, src/tests/ftest/erasurecode/multiple_failure.py, src/tests/ftest/erasurecode/online_rebuild.py, src/tests/ftest/rebuild/container_rf.yaml, src/tests/ftest/rebuild/delete_objects.yaml, src/tests/ftest/rebuild/read_array.yaml, src/tests/suite/daos_rebuild.c, src/vos/tests/vts_io.c, src/vos/vos_obj_cache.c
These fixes are ported from master for EC migration
1. add ec_parity shard check during migration, so only fetch from shards if it still exists.
2. skip empty IOD.
3. Remove discard vs write assertion in vos_obj_hold, instead it will return -DER_UPDATE_AGAIN to make client retry, since it may see inflight update during rebuild reclaim.
4. Use stable epoch to discard the rebuild failure job.
5. Let's skip the empty IOD during migration to avoid creating too much ULT.
6. DAOS-11423 object: skip the first return la kds (#10267)
7. DAOS-10524 rebuild: skip reclaim job during merge
8. DAOS-11423 container: do not update oid IV for failure
9. DAOS-10423 container: check container hdl in rdb (#10241)
Test-tag: pr rebuild ec_ior_hard_online_rebuild pool_create_all_one_hw …
=> DAOS-11658 object: several fixes for EC migration

src/control/fault/code/codes.go, src/control/lib/control/auto_test.go, src/control/server/config/server_test.go, src/control/server/storage/bdev.go, src/control/server/storage/bdev/backend_class_test.go, src/control/server/storage/bdev/backend_json.go, src/control/server/storage/bdev/backend_json_test.go, src/control/server/storage/config.go, src/control/server/storage/config_test.go, src/control/server/storage/faults.go, src/control/server/storage/provider.go, src/include/daos_srv/control.h, utils/config/daos_server.yml
Allow NVMe SSD roles for MD-on-SSD to be explicitly set per-bdev-tier in
the server config file. The settings are data, index and wal. Settings
are communicated to the engine in the SPDK JSON config and exposed in
the bdev name once the SPDK subsystems have been initialized in the
engine's BIO module.
=> DAOS-11391 control,bio: Add explicit SSD role assignment to server config

utils/config/daos_server.yml
remove comment in daos_server.yml stating that fabric_iface_port is optional (which is not the case).
=> DAOS-11648 doc: fabric_iface_port is not optional

utils/config/daos_server.yml
remove comment in daos_server.yml stating that fabric_iface_port is optional (which is not the case).
=> DAOS-11648 doc: fabric_iface_port is not optional (#10472)

src/control/cmd/daos_agent/config.go, src/control/cmd/daos_agent/config_test.go, src/control/cmd/daos_agent/fabric.go, src/control/cmd/daos_agent/fabric_test.go, src/control/cmd/daos_agent/infocache.go, src/control/cmd/daos_agent/infocache_test.go, src/control/cmd/daos_agent/start.go, src/control/common/collection_utils.go, src/control/common/collection_utils_test.go, utils/config/daos_agent.yml
In some environments clients may be connected to multiple networks that support the server's fabric provider, but some of them should not or cannot be used for DAOS. This new config option allows unwanted fabric interfaces to be excluded by name, rather than defining a full fabric_ifaces configuration. Excluded interfaces will not be suggested to clients.
=> DAOS-11664 agent: Add config option to ignore interfaces

src/object/cli_obj.c, src/object/obj_internal.h, src/object/srv_obj_migrate.c, src/rebuild/rebuild_internal.h, src/rebuild/srv.c, src/tests/ftest/daos_test/rebuild.py, src/tests/ftest/daos_test/rebuild.yaml, src/tests/ftest/erasurecode/multiple_failure.py, src/tests/ftest/erasurecode/online_rebuild.py, src/tests/suite/daos_rebuild.c, src/vos/tests/vts_io.c, src/vos/vos_obj_cache.c
Remove assertion is vos_obj_hold(), instead of assertion for
inflight update request during discarding, let's return DER_UPDATE_BUSY,
which make client retry update.
Set minimum number for EC rotate object enumeration to avoid endless
enumeration during cascading failure case.
Use stable epoch to discard those rebuild failure objects. And
reclaim epoch will only be used for reintegration cleanup.
skip the empty IOD during migration to avoid creating
too much ULT.
Open object with RW mode during migrating, so reintegrating
flags can be set.
Fix grp size in valid shard get for OSA.
Remove done_cond from rpt, which is used to notify
rebuild_abort() when the current rebuild finish. But
rpt might be destroyed once notify others, which can
cause unexpected scenarios, so let's not use done_cond, …
=> DAOS-11658 rebuild: few fixes about EC parity rotation rebuild.

site_scons/daos_build.py, src/control/SConscript
Per SDL requirement, "-pie" is added for linking C executable files. "-buildmode=pie" is added for linking Go executable files.
=> DAOS-11534 build: add -fpic -pie in linkflag for program

src/pool/srv_pool.c
To work around a coverity issue: the return value rc of rdb_remove_replicas is not used/checked.
=> DAOS-11715 pool: worked around a coverity issue

ci/jira_query.py
"agent" is a valid component string. It is used for changes to the control plane that are client-side only.
=> DAOS-11815 ci: Add "agent" as commit msg component

src/control/system/raft/raft.go
The change allowing custom configuration of some raft parameters
was somehow lost from the original PR.
=> DAOS-9582 control: Fix raft test fixture generation

src/vos/vos_iterator.c
Only reset nonexist error after iter_next and probe, to keep the return value from other callback in vos_iterate_interal().
=> DAOS-11063 vos: check and reset NONEXIST in iter_next and probe (#9633)

ftest.sh, src/tests/ftest/launch.py, src/tests/ftest/scripts/main.sh
Increasing the test logs threshold size check to match the log rollover size: 1GB -> 2GB.  Increasing the timeout for the cart_logtest command and removing any empty log files prior to running the cart_logtest command. Also resolving DAOS-11812, where non-contiguous node sets where not processed correctly when updating test yaml files.
Test-tag: daosracer dfs_test ec_online_rebuild_fio ec_offline_rebuild_fio der_enospace Test-repeat: 3
=> DAOS-11762 test: Match log threshold with log rollover size

src/tests/ftest/harness/config.py, src/tests/ftest/harness/config.yaml, src/tests/ftest/util/agent_utils_params.py
Test-tag: harness_config
Add exclude_fabric_ifaces to agent params.
Add test case to verify value from config.
=> DAOS-11664 test: support agent exclude_fabric_ifaces

docs/user/filesystem.md, src/client/dfuse/dfuse.h, src/client/dfuse/dfuse_core.c, src/client/dfuse/ops/create.c, src/client/dfuse/ops/lookup.c, src/client/dfuse/ops/open.c, src/client/dfuse/ops/setattr.c, src/tests/ftest/dfuse/daos_build.py
=> Revert "DAOS-11260 dfuse: Apply timeouts to dfuse data cache."

src/cart/crt_iv.c, src/engine/server_iv.c, src/include/cart/iv.h, src/rebuild/srv.c
Create separate ULT for async IV sync to avoid
complicate IV complete callback.
Throttle IV retry in iv_op().
Change a few REBUILD log to INFO.
=> DAOS-9040 iv:  create separate ULT for async IV sync (#7463)

src/include/daos_srv/pool.h, src/include/daos_srv/rebuild.h, src/pool/srv_pool.c, src/rebuild/rebuild_internal.h, src/rebuild/scan.c, src/rebuild/srv.c
Abort the stale rebuild job once it receive the
rebuild job with higher rebuild generation.
=> DAOS-11383 rebuild: abort the stale rebuild job

src/object/srv_obj.c
Refine daos_recx_ep_list_set() to release the requirement of parity epoch mismatch check for client side,
because the client-side retry for parity epoch mismatch is for the case of EC aggregation unstable case that
parity ext updated to different parity shards asynchronously. This patch set the parity epoch as max of
parity ext and EC aggregation epoch boundary, which means once the EC aggregation done we can release
the requirement of parity ext epoch mismatch check for client-side retry.
=> DAOS-11601 object: refine daos_recx_ep_list_set

src/client/dfs/dfs.c, src/include/daos_fs.h, src/tests/suite/dfs_unit_test.c
Same as readdir but also does a stat on the entry for convenience.
=> DAOS-10663 dfs: add new DFS readdirplus API

src/client/pydaos/raw/daos_api.py
Commit c5c4b26989 (DAOS-3927/PR-1617) had introduced a regression (one parameter in excess to be passed to daos_cont_create() api, when properties specified) which has only been unveilled when commit 44c7676212 (DAOS-11375/PR-10203) has landed due to causing redundancy factor property to be passed by default !!...
This patch removes the extra/erroneous parameter.
changes.
PRs.
addressed.
it is a release branch, does it have …
=> DAOS-11643 tests: fix parameters passing to API

src/bio/SConscript, src/bio/bio_buffer.c, src/bio/bio_internal.h, src/bio/bio_wal.c, src/bio/bio_wal.h, src/include/daos_srv/bio.h
Preliminary WAL implementation includes 3 exported APIs:
- bio_iod_post_async()
Async version of bio_iod_post(), it won't wait for the NVMe data write
back triggered on IOD post. It'll be used by WAL I/O and NVMe bulk I/O
on VOS update.
- bio_wal_reserve()
Reserve WAL space & acquire WAL transaction ID before starting a local
transaction. It'll be called by umem_tx_begin().
- bio_wal_commit()
Submit WAL I/O and wait for the WAL transaction done. It'll be called
by umem_tx_commit().
Also, few BIO internal WAL functions are introduced for meta context
management:
- meta_format()
Format meta & WAL blobs, called on meta context creation.
- meta_open()
Load meta header, called on meta context open.
- meta_close()
Cleanup for meta_open(), called on meta context close.
- wal_open()
Load WAL …
=> DAOS-11400 bio: preliminary WAL implementation

src/control/README.md, src/control/cmd/daos_admin/README.md, src/control/cmd/daos_server/README.md, src/control/server/README.md, src/tests/simple_obj.c
change daos-stack.github.io to docs.daos.io/latest
Doc-only: true
=> DAOS-9355 doc: fix doc URLs in src tree (#10527)

src/control/README.md, src/control/cmd/daos_admin/README.md, src/control/cmd/daos_server/README.md, src/control/server/README.md, src/tests/simple_obj.c
change daos-stack.github.io to docs.daos.io/latest
Doc-only: true
=> DAOS-9355 doc: fix doc URLs in src tree

src/object/srv_obj_migrate.c
In ds_migrate_stop(), migrate_fini_one_ult only wait non-0 xstream ULTs to stop, so it should also wait for 0 xstream migrate ULT to stop before destroying migrate tls.
=> DAOS-11750 object: wait for 0 xstream tls stop

src/cart/crt_group.c, src/cart/crt_init.c, src/cart/crt_internal_types.h, src/cart/crt_rpc.c, src/include/cart/api.h, src/tests/ftest/cart/dual_provider_server.c
Add new API to set number of remote tags for a secondary provider
Round-robin across all secondary tags when sending RPC from a secondary cluster
=> DAOS-11884 cart: Add new API to set a number of remote endpoints 

docs/admin/pool_operations.md, docs/release/release_notes_v2_2.md, docs/user/container.md
document that ec_cell_sz changed from 1MiB to 64kiB in DAOS 2.2
provide better guidance how to select the optimal EC cell size
Doc-only: true
=> DAOS-11674 doc: document default EC cell size change in DAOS 2.2

src/vos/tests/evt_ctl.c, src/vos/vos_common.c
The -s was missing argument specifier in getopt
Log message had extra word
=> DAOS-623 vos: minor fixes in evtree logging and test

src/ddb/ddb_cmd_options.c, src/ddb/ddb_cmd_options.h, src/ddb/ddb_commands.c, src/ddb/ddb_main.c, src/ddb/ddb_spdk.c, src/ddb/ddb_spdk.h, src/ddb/ddb_vos.c, src/ddb/ddb_vos.h, src/ddb/tests/ddb_cmd_options_tests.c
- Added command arguments to smd_sync so can include path to system 
path (/mnt/daos), and nvme config json path (/mnt/daos/daos_nvme.conf)
- Restructured ddb_spdk to use a  state machine to manage callback 
complexity.
- Added device to target info for SMD sync.
=> DAOS-10616 ddb: Add device info to SMD Sync

src/include/daos/placement.h, src/include/daos/pool.h, src/include/daos_srv/pool.h, src/include/daos_srv/rebuild.h, src/object/cli_obj.c, src/object/cli_shard.c, src/object/obj_internal.h, src/object/obj_rpc.h, src/object/srv_ec_aggregate.c, src/object/srv_obj.c, src/object/srv_obj_migrate.c, src/placement/jump_map.c, src/placement/pl_map.c, src/placement/pl_map.h, src/placement/ring_map.c, src/placement/tests/pl_bench.c, src/placement/tests/place_obj_common.c, src/pool/cli.c, src/pool/rpc.h, src/pool/srv_iv.c, src/pool/srv_pool.c, src/pool/srv_target.c, src/rebuild/scan.c, src/rebuild/srv.c
Add rebuild version to pool map query reply, which will be used to generate the object layout. So any targets whose in_version (when target is added to the map) is newer than the rebuild version will be regarded as unavaible targets, otherwise inflight I/O data may be lost during reintegration.
Inflight I/O also needs to wait rebuild fence is generated, so the inflight I/O epoch will have newer epoch than the rebuild stable epoch, which is even older than rebuild fence, so rebuild will use rebuild fence epoch to check if the data needs to be rebuilt.
Do not need change it during leader switch to avoid unnecessary IV communication, i.e. do not need invalidate this IV entry during svc step down, and the new PS leader will still pick up the same handle anyway.
Signed-off-by: Di Wang …
=> DAOS-10524 pool: add rebuild version to pool query

src/common/btree.c, src/pool/srv_pool.c
It was discovered by the ddb tool that when vos_self_init/fini are called repeatedly, the container btree class is never really 'unregistered' so registering again causes it to fail with -DER_EXIST. This changes that behavior so that if registering and the class already exists, it will check if it's registering the same thing, then returns success. The registration process does not allocate memory or resources so there is no harm in multiple registrations.
=> DAOS-11915 vos: Reregistration of btree doesn't fail

src/placement/pl_map.c
The cluster has an UP state target, and the object's layout may have an extending target. Calling the pl_obj_layout_contains interface in the reclaim process essentially means that the variable i in this interface is no longer equivalent to po_shard in the layout.
Signed-off-by: wangzhaorong <wangzhaorong@cestc.cn>
=> DAOS-11132 rebuild: Incorrect deletion of local objects

src/control/server/config/server_test.go, src/control/server/storage/config.go, src/control/server/storage/provider.go, src/control/server/storage/scm.go, src/control/server/storage/scm/mocks.go, src/control/server/storage/scm/provider.go, src/control/server/storage/scm/provider_test.go, utils/config/daos_server.yml
Unless scm_hugepages_disabled is true in the engine storage configuration,
the per-engine tmpfs will be mounted with the huge=always option.
=> DAOS-11396 control: Enable hugepage support for tmpfs

src/include/daos_srv/rebuild.h, src/rebuild/scan.c, src/rebuild/srv.c
Do not set rebuild status for reclaim job to avoid messing up the real rebuild status.
Test-tags: pr no_cap
=> DAOS-11380 rebuild: do not set rebuild status for reclaim job
